### ISSUE TITLE
Mod incompatibility - Scrolling does not move items properly.

### ISSUE THREAD

**Issue by ProsperCraft** [SpongePowered/SpongeForge#1002]
https://minecraft.curseforge.com/projects/item-scroller

https://www.youtube.com/watch?v=TiCKJA1FQZw

**Comment by ProsperCraft** [comment]
This does not happen in single player, or when sponge is disabled on the server.

**Comment by bloodmc** [comment]
@ProsperCraft Test latest SF build.

**Comment by phit** [comment]
still an issue with 

itemscroller-1.11.2-0.11.0.jar
spongeforge-1.11.2-2393-6.1.0-BETA-2468.jar

**Comment by bloodmc** [comment]
@phit I don't seem to notice any issues when using this mod on client. Can you be more specific on EXACTLY what is not working?

**Comment by phit** [comment]
install it on client AND server and you will see the issue shown in the initial post video

**Comment by bloodmc** [comment]
"A client-side mod that adds several ways of moving items in inventory GUIs." This should not be installed on server.

**Comment by phit** [comment]
seems to be resolved with itemscroller-1.11.2-0.11.0 and spongeforge-1.11.2-2393-6.1.0-BETA-2592 anyway
