### ISSUE TITLE
Abyssalcraft Asorah will not appear.

### ISSUE THREAD

**Issue by ProsperCraft** [SpongePowered/SpongeForge#1003]
Relayed from one of our players- 
Unable to summon Asorah, The fallen from Abyssalcraft.  I am able to summon it just fine on single player.  Its the dragon in the abyssal wasteland dimension.  Without it you cannot progress in that mod.  After doing the ritual you can see the health bar for a brief moment then it disappears.
Basically you make the ritual altar in the Abyssal Wasteland dimension.  You place the required items on the ritual pedestals then activate the ritual with the Necronomicon.  Once the ritual completes Asorah should appear.  Asorah is more or less a green ender dragon that you need to kill to progress to the next dimension.  I performed the ritual on single player and it worked just fine.  I'm pretty confident it doesn't work because of sponge, just like the normal ender dragon summoning does not work.
Once the ritual completes there is a message displayed from Asorah and its health bar is displayed.  Then the health bar disappears and no dragon is there.  In single player the dragon appears as soon as the ritual is completed

```
SpongeAPI: 6.0.0-SNAPSHOT-f247c80
SpongeForge: 1.10.2-2107-6.0.0-BETA-1856
Minecraft Forge: 12.18.2.2114
```

**Comment by ProsperCraft** [comment]
We disabled sponge on the server and verified it is working without it.

**Comment by Aaron1011** [comment]
This issue can be solved by setting `max-bounding-box-size` to `0` in your `global.conf`.

@bloodmc: Why do we remove entities with a 'too large' bounding box by default? The only thing this seems to accomplish is breaking mods.
