### ISSUE TITLE
Biomes OP Crash

### ISSUE THREAD

**Issue by Mattabase** [SpongePowered/SpongeForge#1004]
https://gist.github.com/2685cd8366afa1ff5ddb60950b0299aa

Crash when running Build 1856

**Comment by bloodmc** [comment]
Delete your sponge config so it can regenerate fresh as it has corrupted entity activation entries. You can find this config in ./config/sponge

**Comment by Mattabase** [comment]
Thanks for response. Yeah got it all fixed on my end by deleting the config. 

I am wondering though, is this in an issue that was caused by a mod, or on sponges end? 
Should I do something to avoid this in the future or do I just do this every time it happens?
