### ISSUE TITLE
Aether & SpongeForge - crash when generating DIM for Aether

### ISSUE THREAD

**Issue by Pepejson** [SpongePowered/SpongeForge#1007]
Tried to run Aether [c82b52eb](https://git.gildedgames.com/GildedGames/Aether-II/commit/c82b52eb783848420ca05a2e1344527ad5d67cc5) with Forge 12.18.2.2099 and SpongeForge 1.10.2 - 6.0.0-BETA-1844.
It crashed during Aether dimension creating.
About a week or two ago I successfully ran Sponge with Aether but unfortunately cannot find the version numbers which worked. If I'll find them I'll edit this post.

Logs: [1844-logs.zip](https://github.com/SpongePowered/SpongeForge/files/560588/1844-logs.zip)

EDIT: The working server was on Aether [d30c593e](https://git.gildedgames.com/GildedGames/Aether-II/commit/d30c593e84912f4b7e4bd6f4b96e80f0667654f3), spongeforge-1.10.2-2098-5.1.0-BETA-0, forge-1.10.2-12.18.2.2099-universal
In the working solution, sponge was compiled with latest https://github.com/SpongePowered/SpongeForge/tree/stable-5 (checked it now and there's no new commit - just fetch latest stable-5 branch)

**Comment by Pepejson** [comment]
This time it was caused by Aether II. If you want to look what they have to do to fix it, here's the issue on their GitLab - all infos there.
https://git.gildedgames.com/GildedGames/Aether-II/issues/198

**Comment by HoopRod** [comment]
I think your problem can be fix with my video, please subscribe and leave a comment if it works for you https://youtu.be/JARonMG8G7I
