### ISSUE TITLE
[Dupe] WeaponCaseLoot

### ISSUE THREAD

**Issue by Mohron** [SpongePowered/SpongeForge#1009]
Sponge: spongeforge-1.10.2-2107-6.0.0-BETA-1856.jar
Forge: forge-1.10.2-12.18.2.2114-universal.jar
Mod: weaponcaseloot-1.10.2-4.0.1.jar

The mod add 4 item cases that when activated in your hand begin to roll from the loot pool. If you move a weapon case while it is rolling, it creates another weapon case and you still get the rolled item. Doesn't seem to affect the bow and bauble cases and I'm not sure why. Wasn't able to reproduce dupe bug when SpongeForge was removed.

[Preview (GIF)](https://giphy.com/gifs/qdpkGuuvko1oc)

**Comment by Aaron1011** [comment]
@Mohron: Can you try again with the latest SpongeForge? I'm unable to reproduce this using the latest build of SpongeForge.

Also, are you running any plugins/mod besides WeaponCaseLoot?

**Comment by bloodmc** [comment]
Closed due to no response in nearly a month.
