### ISSUE TITLE
TC Souldbound deleted on death

### ISSUE THREAD

**Issue by Vauxite** [SpongePowered/SpongeForge#1012]
**Problem**
Soulbound tinker construct tools are deleted on death

**How to reproduce**

1. Create a soulbound tinkerconstruct tool by adding a netherstar.
2. Die a vanilla death
3. TC tool is not in grave or player inventory

**Versions**
-     Minecraft: 1.10.2
-     SpongeAPI: 6.0.0-SNAPSHOT-f247c80
-     SpongeForge: 1.10.2-2107-6.0.0-BETA-1856
-     Minecraft Forge: 12.18.2.2107

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/SpongePowered/SpongeCommon/commit/de1daa0f2e30c1c34e0d4ca2602731946be73c23
