### ISSUE TITLE
[1.10.2] Problems with EntityAttributeModifiers

### ISSUE THREAD

**Issue by maxanier** [SpongePowered/SpongeForge#1013]
Hello,

there seems to be an issue with (Player) EntityAttribute modifiers.

**Short version:** Attribute Modifiers that are applied during EntityJoinWorld events change the base value of that attribute when the player dies.

**Long version:** _I'm having trouble explaining this well, but hopefully the following explains the problem enough._

My mod Vampirism applies attribute modifiers (e.g. health) to the player entity, so (depending on the players "level") the player has e.g. 36 health points. 
These modifiers are applied/changed during EntityCreation(AttachCapabilities event), on NBTLoad or on command. This works absolutely fine on normal Forge servers.
Since SpongeForge does not recreate the player entity on death, but resets it (including [recreation of the AttributeMap)](https://github.com/SpongePowered/SpongeCommon/blob/7be2adafff7858197465b917ff14a4998126a092/src/main/java/org/spongepowered/common/mixin/core/server/MixinPlayerList.java#L483) . I had to implement a workaround to reapply the the modifiers (and register custom attributes see #736 ) during EntityJoinWorldEvent (which would normally happen during entity recreation) if Sponge is installed and the player was dead.
This only works partially. The modifier is correctly applied, but somehow the base value is modified afterwards.
I've tested it a little bit:
During the  JoinWorldEvent the base value is fine: 

> [13:47:17] [Server thread/INFO] [vampirism]: [Test]Applying modifier to (20.0, 20.0) //VampirismMod.log.t("Applying modifier to (%s, %s)",instance.getBaseValue(),instance.getAttributeValue());

After applying the modifier everything is fine as well. The base value is unmodified, but the current value is increased by the modifiers value:

> [13:47:17] [Server thread/INFO] [vampirism]: [Test]Applied modifier to (20.0, 34.0) //VampirismMod.log.t("Applied modifier to (%s, %s)",instance.getBaseValue(),instance.getAttributeValue());

But later on (e.g. during the first EntityLivingUpdate event) the base value is suddenly changed to modified value (34) but the modifier still applies, so the actual value is (34+14=48)

> [13:47:17] [Server thread/INFO] [vampirism]: [Test]Player health: 34.0/48.0 with 48.0 of 34.0([AttributeModifier{amount=14.0, operation=0, name='generic.maxHealth Vampire Boost', id=56c17efe-e3ec-4e27-a12f-99d2fe927b70, serialize=false}]) 
// VampirismMod.log.t("Player health: %s/%s with %s of %s(%s)",player.getHealth(),player.getMaxHealth(),player.getEntityAttribute(SharedMonsterAttributes.MAX_HEALTH).getAttributeValue(),player.getEntityAttribute(SharedMonsterAttributes.MAX_HEALTH).getBaseValue(),player.getEntityAttribute(SharedMonsterAttributes.MAX_HEALTH).getModifiers());

I'm pretty sure that Vampirism does not do much between that JoinWorld event and the next LivingUpdate, so I don't think that Vampirism is assigning the new base value (especially as it does not occur without Sponge). Unfortunately the Sponge code is quite complex, so I could not find anything that might be causing this (maybe HealthDataProcessor?).
The base value is only changed when the player dies. So if the modifier is changed (e.g. by executing a level change command) the actual value changes, but the base value still stays on the old and wrong base value.
The changed base value also persists over reconnects.

Hopefully I was able to explain the problem. Maybe you have an idea what is causing this, thank you.

**Comment by bloodmc** [comment]
I'll be recreating the player object in SF in order to support Forge's PlayerEvent.Clone. Ticket will be open until I push a fix.

**Comment by maxanier** [comment]
Awesome, that make things cleaner and easier, thanks :)
