### ISSUE TITLE
naturally spawned creepers give no damage

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1014]
when naturally spawned creeper explode, explosion give me no damage
(gamerule mobgriefing is false)

when spawn creeper using spawn egg, all works as expected

**Comment by Aaron1011** [comment]
@hunter688: I can't seem to reproduce this - I'm still damaged by naturally spawned creepers with `mobGriefing` set to `false`.

Are you running any plugins that might prevent the damage from occuring (GriefPrevention, perhaps)?

**Comment by ghost** [comment]
yes running GP

**Comment by Aaron1011** [comment]
@hunter688: See if you can reproduce this with only Sponge.

**Comment by ghost** [comment]
looks like when updated SF, GP problem solved
