### ISSUE TITLE
Chickenbones Enderpouch crash

### ISSUE THREAD

**Issue by ProsperCraft** [SpongePowered/SpongeForge#1015]
Is it possible this is sponge? The mod was added after we completed our forge only testing phase.

https://github.com/TheCBProject/EnderStorage/issues/22

**Comment by gabizou** [comment]
Is this reproducible only with Chickenbones and SpongeForge? Need some crashlogs with that setup please, and a description on how to reproduce.

**Comment by ProsperCraft** [comment]
Logs are found here - https://github.com/Chicken-Bones/EnderStorage/issues/77

**Comment by ProsperCraft** [comment]
Fortunately the InfinityLite 1.10.2 pack we are running right now doesn't have Chickenbones Enderstorage so we won't see crashes.

**Comment by covers1624** [comment]
ES dev here.
There seems to be no issues thus far with the DW20 pack, the only way this could ever occur is if EntityPlayerMP.connection is null.

**Comment by ryantheleach** [comment]
This looks like it can be closed: https://github.com/TheCBProject/Feedback/issues/3
