### ISSUE TITLE
Crash on join.

### ISSUE THREAD

**Issue by Vauxite** [SpongePowered/SpongeForge#1016]
Feel free to close this ticket if you think this issue is not related to spongeforge.

**Problem:**
Server crash on a specific player joining.

**Crashlog**
Copied from console: http://pastebin.com/UgHPjY7q
Crashlog in crash-reports http://pastebin.com/Gt7YHjc3

**How to reproduce:**
- No clue. Tried this so far without being able to reproduce:
- I tried copy his player dat file. 
- Log into the same area.
- He was using ftb launcher, had no luck reproducing with that.

**Versions**
    Minecraft: 1.10.2
    SpongeAPI: 6.0.0-SNAPSHOT-f247c80
    SpongeForge: 1.10.2-2107-6.0.0-BETA-1860
    Minecraft Forge: 12.18.2.2107

Thank you for reading.

**Comment by Deamon5550** [comment]
Duplicate #992
