### ISSUE TITLE
Issue with Crossroads

### ISSUE THREAD

**Issue by lilmoefow** [SpongePowered/SpongeForge#1017]
There seems to be a dupe glitch with the mods Crossroads (https://mods.curse.com/mc-mods/minecraft/250231-crossroads-mc). 

When placing the gears from that mod, they get placed in world but the item is not used up from the Inventory.  The grears then can be broken with a pick axe, to retrieve a second copy of the gear.

spongeforge-1.10.2-2107-6.0.0-BETA-1862.jar
forge-1.10.2-12.18.2.2107-universal.jar
crossroads-1.10.2-1.1.8.jar

No apparent errors in any logs, sorry.

**Comment by lilmoefow** [comment]
Issue still happening with these versions.  Going to report to  the crossroads devs now as well and see if they have any input on it.

forge-1.10.2-12.18.2.2107-universal.jar
spongeforge-1.10.2-2107-6.0.0-BETA-1872.jar
crossroads-1.10.2-1.1.8.jar

**Comment by lilmoefow** [comment]
Just want to update this issue to say that it is still present with these versions

forge-1.10.2-12.18.2.2123-universal.jar
spongeforge-1.10.2-2123-5.1.0-BETA-1914.jar
crossroads-1.10.2-1.1.8.jar

**Comment by phit** [comment]
Seems to be fixed, tested with
>crossroads-1.10.2-1.3.7
>spongeforge-1.10.2-2281-5.2.0-BETA-2464

also tested in 1.11.2 and no issue there either
>crossroads-1.11.2-1.4.0
>spongeforge-1.11.2-2393-6.1.0-BETA-2471
