### ISSUE TITLE
Error With Ender Compas

### ISSUE THREAD

**Issue by lilmoefow** [SpongePowered/SpongeForge#1018]
There is an error happening on load up with Ender Compass preventing it from working.   I have installed it to help players find the strong hold because Eyes of Ender still are not working with the current releases of Sponge.  

Server Log http://pastebin.com/Ac7rNLCX

spongeforge-1.10.2-2107-6.0.0-BETA-1862.jar
forge-1.10.2-12.18.2.2107-universal.jar
EnderCompass-1.9.x-1.2.3.2.jar

I think that log also contains errors from me trying to use the ender pearl while testing the compass

**Comment by ryantheleach** [comment]
Mentioned Eye of Ender issue: https://github.com/SpongePowered/SpongeForge/issues/937

**Comment by phit** [comment]
EnderCompass-1.9.x-1.2.3.2.jar
spongeforge-1.10.2-2281-5.2.0-BETA-2464.jar

no error and compass led me to to a stronghold
![2017-07-17_22 14 36](https://user-images.githubusercontent.com/2097483/28287850-70d9040c-6b3d-11e7-8336-c269392b3008.png)
