### ISSUE TITLE
Skeleton Horse Trap does not spawn riders. SF only.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeForge#1019]
Ran into this issue when testing something unrelated. Skeleton trap explodes as expected but has no rider. Spawned naturally.

Recreated this in SpongeVanilla using command "/summon EntityHorse ~ ~ ~ {SkeletonTrap:1}"
SV creates riders as expected.

Client reports 

```
[12:31:22] [Client thread/WARN]: Received unknown passenger for wr['Skeleton Horse'/13625, l='MpServer', x=103.79, y=71.00, z=380.86]
[12:31:22] [Client thread/WARN]: Received unknown passenger for wr['Skeleton Horse'/7743, l='MpServer', x=96.30, y=71.00, z=378.00]
```

Reconnecting doesn't fix.

Tested on :
```
SpongeForge
    Minecraft: 1.10.2
    SpongeAPI: 5.1.0-SNAPSHOT-385344f
    SpongeForge: 1.10.2-2098-5.1.0-BETA-1814
    Minecraft Forge: 12.18.2.2116
```

```
SpongeVanilla
    Minecraft: 1.10.2
    SpongeAPI: 5.1.0-SNAPSHOT-385344f
    SpongeVanilla: 1.10.2-5.1.0-BETA-355
```

**Comment by Aaron1011** [comment]
@ryantheleach: Can you test on the `6.0.0-SNAPSHOT` builds? I can't reproduce it on the very latest SpongeForge.

**Comment by ryantheleach** [comment]
Unable to reproduce in 6.0.0-SNAPSHOT
