### ISSUE TITLE
draconic rev - ender dragon not dropping hearts, end crystals indestructable

### ISSUE THREAD

**Issue by acidjazz** [SpongePowered/SpongeForge#1021]
I don't know why #933 was just closed and not separated when these are still ongoing issues the past month

> Right after respawning the Ender Dragon. I can't destroy the End Crystal that are on the top of each obsidian tower, they are invincible entities unless I use the kill command. Also, it should give me some loot from the Draconic Evolution mod but since Sponge is installed, it gives nothing.

This has been confirmed and when sponge is not active this works, we get no dragon heart which is a huge part of draconic evolution

**Comment by bloodmc** [comment]
@gabizou 
I realized that we need to always fire DropItemEvent.Destruct even if nothing is captures. This is due to Forge always firing their LivingDropsEvent even though nothing was captured. This mod adds the drops during this event but since it never gets fired, it drops nothing.
