### ISSUE TITLE
[pool-4-thread-6/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@5dd1237b

### ISSUE THREAD

**Issue by ziceptor** [SpongePowered/SpongeForge#1025]
forge-1.10.2-12.18.2.2107-universal.jar
spongeforge-1.10.2-2107-6.0.0-BETA-1864.jar

Continuously spamming in the console.
http://pastebin.com/93b0p0Eh

**Comment by Zidane** [comment]
Duplicate: https://github.com/SpongePowered/SpongeCommon/issues/958
