### ISSUE TITLE
ExU2 Redstone Clock Tracking Crash Loop

### ISSUE THREAD

**Issue by phit** [SpongePowered/SpongeForge#1026]
put my server in a crash loop just now, I'll ask the player in question for reproduction steps once I can reach them
[crash-2016-11-05_14.37.47-server.txt](https://github.com/SpongePowered/SpongeForge/files/573436/crash-2016-11-05_14.37.47-server.txt)

updating to latest sponge didn't fix the crashloop either, had to remove the block
[crash-2016-11-05_14.41.29-server.txt](https://github.com/SpongePowered/SpongeForge/files/573439/crash-2016-11-05_14.41.29-server.txt)

**Comment by phit** [comment]
picture of setup that caused it http://i.imgur.com/I5quce5.png
theres a single piece of redstone on top of the clock
removing the redstone clock from extra utilities 2 resolved the issue, can't reproduce the crash without sponge

**Comment by Aaron1011** [comment]
@phit: Can you post your `global.conf` here?

**Comment by phit** [comment]
just found this

```
        mods {
            extrautils2 {
                # Set to true to perform individual capturing (i.e. skip bulk capturing) for scheduled ticks for a block type
                block-tick-capturing {
                    RedstoneClock=true
                }
                # Set to false if you want to ignore all specific rules for this mod
                enabled=true
            }
        }
```

I assume setting it to false will resolve the issue?

**Comment by Aaron1011** [comment]
@phit: `RedstoneClock` needs to be set to `true`. Why did you change it?

**Comment by phit** [comment]
it is set to true, hit ctrl+enter on accident while i was pasting
just found the line and was about to set it to false

**Comment by Aaron1011** [comment]
@phit: That's a bizarre error you're having. Can you join `#spongedev` on EsperNet to discuss this further?

**Comment by bloodmc** [comment]
@Aaron1011 what is the status of this?

**Comment by phit** [comment]
I didn't see this issue pop up again in recent builds.
