### ISSUE TITLE
[1.10.2] Issue with Correlated Potentialistics 

### ISSUE THREAD

**Issue by FiveEYZ** [SpongePowered/SpongeForge#1027]
Getting this error when trying to add items to a Correlated Potentialistics system

when i try to shift-click an item/s it will say that the item/s got added but it wont get removed from my inventory, later i can remove that same item i tried to add from the system and effectively "dupe" the item/s.
http://pastebin.com/raw/FuSEd6x8

this does not happen in singleplayer

Minecraft: 1.10.2
SpongeAPI: 6.0.0-SNAPSHOT-bd88c91
SpongeForge: 1.10.2-2107-6.0.0-BETA-1873
Minecraft Forge: 12.18.2.2120
CorrelatedPotentialistics-2.0.0-alpha2

**Comment by gabizou** [comment]
It sounds like it's restoring the item because of a sponge plugin cancelling the event. @blood, you'd be the best person to figure this one out.

**Comment by bloodmc** [comment]
@FiveEYZ This should be resolved in SF 1914. Close ticket if it is.

**Comment by FiveEYZ** [comment]
tried SF 1914 and got https://gist.github.com/FiveEYZ/c756bc37a56052c2e096cdfc4b4733b3
this client crash happend when after i sucesfully built a system and tried to shift+right-click a item in to the system.

after disabling this mod (CorrelatedPotentialistics-2.0.0-alpha2), ppl are still reporting client crash cause of SF 1914
https://gist.githubusercontent.com/anonymous/f37cdb8a9218cd0d5c3e40b2c51f7ae3/raw/1dbecd46c900391eb7c6155205a18d7d5f216154/gistfile1.txt


now i dont have IC2 but i saw @phit reported the same crash here: https://github.com/SpongePowered/SpongeForge/issues/1037#issuecomment-263520485

**Comment by FiveEYZ** [comment]
client crash stopped after updating to 1921

now i can add items to the CoPo system only using shift + right-click, but im unable to extract any items

**Comment by FiveEYZ** [comment]
Only issue left is when i try to break a Drive Bay it will dissapear and i get this error http://pastebin.com/DESLRixd

**Comment by Aaron1011** [comment]
@FiveEYZ: That appears to be an issue with the version of Scala being used by that mod. Can you check if that crash occurs without Sponge?

**Comment by FiveEYZ** [comment]
https://github.com/elytra/Correlated/commit/d4c0ce8dbcb6ea799e04b21a4843a5920456a9ca

**Comment by Aaron1011** [comment]
Lol, that commit message :)

Closing, as this was resolved in the mod.
