### ISSUE TITLE
infinite-water-source=false doesn't work

### ISSUE THREAD

**Issue by agarb7** [SpongePowered/SpongeForge#1030]
Config option `infinite-water-source=false` doesn't work.

Demo of problem: http://www.filehosting.org/file/details/616081/2016-11-07_00-53-45.mp4

Mods set:
![javaw_2016-11-07_01-02-38](https://cloud.githubusercontent.com/assets/8955838/20039818/028def54-a486-11e6-8ab1-17be66c07373.png)
![javaw_2016-11-07_01-03-27](https://cloud.githubusercontent.com/assets/8955838/20039819/030a1db8-a486-11e6-9e06-926633751eeb.png)

**Comment by Zidane** [comment]
Re-test with just Sponge (remove all mods and plugins) and test again. If it works, add back mods/plugins until you find the setup that triggers it.
