### ISSUE TITLE
Blood Magic Phantom Bridge freezing server

### ISSUE THREAD

**Issue by phit** [SpongePowered/SpongeForge#1031]
using spongeforge-1.10.2-2107-6.0.0-BETA-1871.jar
modpack ftb infinity lite
console is not responsive, warmroast screenshot: http://i.imgur.com/1VmGifG.png

**Comment by gabizou** [comment]
Is there any crash log of sorts?

**Comment by phit** [comment]
No, it freezes completely.
I waited 10 minutes and then killed the process :/

**Comment by gabizou** [comment]
Did you disable the watchdog? Set the maximum time to something reasonable and it should forcibly crash the server to shut down for "A single tick took too long!" crash log. And any instructions on how to reproduce (coming from us, we don't really know how to do much with certain mods yet).

**Comment by Zidane** [comment]
Re-test with stable-5 and re-open if it still occurs.

**Comment by phit** [comment]
works fine in spongeforge-1.10.2-2171-5.1.0-BETA-1930 👍
