### ISSUE TITLE
Players consistently kicked from server/can't join [nettyIO issue]

### ISSUE THREAD

**Issue by AussieWarGod** [SpongePowered/SpongeForge#1032]
We are unsure of the root of this problem but have narrowed it down to a sponge or a forge issue (we think) and so are pushing this issue to both sponge and forge git's.

Basically at random intervals a single player will be disconnected, pushing out a nettyIO error message.
Then at other intervals everyone will be kicked with another nettyIO error.
nettyIO errors also come up when some people try to connect and on occasion those players will be completely unable to connect until after the next restart.

This is persistent across all our 1.10 modpacks/servers. I will include the latest logs from our Infinity Lite and Hermitpack servers.

Infinity:
[Infinity Lite fml-junk-earlystartup.txt](https://github.com/SpongePowered/SpongeForge/files/574645/Infinity.Lite.fml-junk-earlystartup.txt)
[Infinity Lite fml-server-latest.txt](https://github.com/SpongePowered/SpongeForge/files/574652/Infinity.Lite.fml-server-latest.txt)
[Infinity Lite fml-server-1.txt](https://github.com/SpongePowered/SpongeForge/files/574647/Infinity.Lite.fml-server-1.txt)
[Infinity Lite fml-server-2.txt](https://github.com/SpongePowered/SpongeForge/files/574648/Infinity.Lite.fml-server-2.txt)
[Infinity Lite fml-server-3.txt](https://github.com/SpongePowered/SpongeForge/files/574649/Infinity.Lite.fml-server-3.txt)

Hermit:
[HermitPack fml-junk-earlystartup.txt](https://github.com/SpongePowered/SpongeForge/files/574668/HermitPack.fml-junk-earlystartup.txt)
[HermitPack fml-server-latest.txt](https://github.com/SpongePowered/SpongeForge/files/574669/HermitPack.fml-server-latest.txt)
[HermitPack fml-server-1.txt](https://github.com/SpongePowered/SpongeForge/files/574670/HermitPack.fml-server-1.txt)
[HermitPack fml-server-2.txt](https://github.com/SpongePowered/SpongeForge/files/574671/HermitPack.fml-server-2.txt)
[HermitPack fml-server-3.txt](https://github.com/SpongePowered/SpongeForge/files/574672/HermitPack.fml-server-3.txt)

If this is in fact not either a sponge or forge issue any assistance in identifying the problem would be greatly appreciated. Thank you in advance.

**Comment by AussieWarGod** [comment]
SpongeAPI: 6.0.0
SpongeForge: 1.10.2-2107-6.0.0-BETA-1864
Minecraft Forge: 12.18.2.2119

**Comment by Shybella** [comment]
Do these players experience slow chunk loading when loading in? As if the world isn't loading?

**Comment by KendirkRS** [comment]
I'll answer on this as i experience this issue sometimes yes sometimes the it loads just fine but i have no chat i can move around but when i disconnect and reload i'm back to the spot i started the first time

**Comment by Shybella** [comment]
I ask because I'm having this same issue and those loading issue happens with it too. They load in but the world doesn't load.

**Comment by AussieWarGod** [comment]
That usually happens just before the kicks, yes.

Chunks stop loading suddenly, tps drops and everyone is kicked

**Comment by Shybella** [comment]
I don't have the problem with kicking everyone out and low tps issue.

**Comment by AussieWarGod** [comment]
we fixed the single player disconnects and inability to connect. it was an SRV issue. 

However the mass kicks persist, when they occur they are clumped together usually.

**Comment by AussieWarGod** [comment]
Apologies, i was premature in my assumption. It seems people are still having difficulty connecting. I can provide more logs at any time you require them.

**Comment by Rasgnarok** [comment]
This happens with Pixelmon+Sponge as well, downgrading Forge helped us alleviate the trouble. How did you fix it, @AussieWarGod ? So far, I have not been able to track an actual range of versions that cause this issue _en masse_ .

**Comment by IronworksProductions** [comment]
My spongeforge 1.10.2 server is experiencing this as well
I can't join my server because of nettyio disconnecting me as soon as i am connected.
this is with the latest spongeforge for 1.10.2

**Comment by Aaron1011** [comment]
Can you re-test this wit the latest SpongeForge, and upload the new log? I've added some extra information to it.

**Comment by bloodmc** [comment]
No response in nearly 2 months, create a new ticket if problem persists.
