### ISSUE TITLE
Custom reject message

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1033]
Will be possible implement using mixin custom reject message?

https://github.com/MinecraftForge/MinecraftForge/issues/1772

in the forge ticket rotting for a long time... :(

**Comment by ghost** [comment]
Full description is in the Forge ticket.

Simply I would like change kick message sent to client. Instead of list missing/incopatible mods prefer some kind of message what understand every players. Eg. "You have wrong versions of mods, please update modpack" - this message will be configurable at server side and show to client when disconnected.

**Comment by phit** [comment]
I would like to see this added, the current message is rather useless for players that just play modpacks.

**Comment by Zidane** [comment]
Closing this for now as this shouldn't go into SpongeForge and won't unless we absolutely have to.
