### ISSUE TITLE
New User Error 

### ISSUE THREAD

**Issue by GershonR** [SpongePowered/SpongeForge#1034]
Minecraft: 1.10.2
 SpongeAPI: 6.0.0-SNAPSHOT-bd88c91
SpongeForge: 1.10.2-2107-6.0.0-BETA-1873
Minecraft Forge: 12.18.2.2116

http://pastebin.com/qhefz3G6

**Comment by kashike** [comment]
That... should not be happening at all. Is this reproducible? What operating system are you using?

**Comment by GershonR** [comment]
Probably some sort of Linux distribution, most likely Debian, it's a shared hosting so I can't tell

**Comment by kashike** [comment]
> Is this reproducible?

**Comment by GershonR** [comment]
Unsure, it started spamming it for that specific user, it looks like it started when they joined the server for the first time

**Comment by kashike** [comment]
Has it happened for anyone else?

**Comment by GershonR** [comment]
I believe not, but I just switched over to bungee, not sure if it's related to that.

**Comment by kashike** [comment]
If this happens again please reply to this issue. In the meantime, I'm going to close it.

**Comment by GershonR** [comment]
This happend again:
http://pastebin.com/JCG02DMN

**Comment by kashike** [comment]
This has been fixed in 1.11: https://github.com/SpongePowered/SpongeCommon/commit/4fd3b2754c60b42024f7f1b6f4df854230f609e7.

**Comment by GershonR** [comment]
Awesome, thanks
