### ISSUE TITLE
[1.10.2 - 1844] Error: GenericArguments$UserCommandElement.getValue

### ISSUE THREAD

**Issue by Rasgnarok** [SpongePowered/SpongeForge#1038]
Saw this error pop up really often throughout my logs, has not caused issues so far - just a lot of spam, so I thought I might as well should report it.

http://pastebin.com/VF7eLdmt

**Comment by bloodmc** [comment]
Using a very outdated build. Update to SF 1914 and repost a log if it occurs.

**Comment by bloodmc** [comment]
Closed by accident.

**Comment by stephan-gh** [comment]
If this is still happening on the latest builds, post a log here then we can re-open this issue.
