### ISSUE TITLE
Server Crash: Exception ticking world

### ISSUE THREAD

**Issue by Mohron** [SpongePowered/SpongeForge#1040]
Forge: forge-1.10.2-12.18.2.2124-universal.jar
SF: spongeforge-1.10.2-2123-6.0.0-BETA-1877

> Description: Exception ticking world
> 
> java.lang.NullPointerException: Exception ticking world
> 	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:213)
> 	at org.spongepowered.common.block.SpongeBlockSnapshot.<init>(SpongeBlockSnapshot.java:116)
> 	at org.spongepowered.common.block.SpongeBlockSnapshot.<init>(SpongeBlockSnapshot.java:108)
> 	at net.minecraft.world.WorldServer.createSpongeBlockSnapshot(WorldServer.java:1453)
> 	at org.spongepowered.common.event.tracking.TrackingUtil.randomTickBlock(TrackingUtil.java:247)
> 	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:653)
> 	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:220)
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
> 	at java.lang.Thread.run(Thread.java:745)

http://hastebin.com/gihehaxemo.sql

Edit: Had another crash :(
http://hastebin.com/ububisebun.scala

**Comment by kashike** [comment]
https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/block/SpongeBlockSnapshot.java#L116

**Comment by ProsperCraft** [comment]
Same here 
https://gist.github.com/ProsperCraft/c093d58444c616e310fba0512bc5fc3b

```
Minecraft: 1.10.2
SpongeAPI: 6.0.0-SNAPSHOT-bd88c91
SpongeForge: 1.10.2-2123-6.0.0-BETA-1877
Minecraft Forge: 12.18.2.2123
```

**Comment by ProsperCraft** [comment]
This one may help as well.

https://gist.github.com/ProsperCraft/777469f7516246c30d2133acc918219d

**Comment by ProsperCraft** [comment]
This happened after 4 of those above

https://gist.github.com/ProsperCraft/631fcb6bd91eddeb2e2967e1fb466ef3

And this one
https://gist.github.com/ProsperCraft/89ddc35e4047a0d55b2451166869258d

**Comment by bloodmc** [comment]
@Mohron @ProsperCraft Looks like you both have "max-tick-time" set to a ridiculous high value or turned off because some of these NPE's in these reports should never happen. Try setting "max-tick-time" to 120000 (2 min) and see if the watchdog dumps all threads with a more useful report.
