### ISSUE TITLE
When killing the enderdragon, spawns multiple eggs.

### ISSUE THREAD

**Issue by AussieWarGod** [SpongePowered/SpongeForge#1041]
when killing the ender dragon, drops work as normal but as it is exploding if you continue to hit it, it spawns more eggs on the ground.

**Comment by phit** [comment]
I tried to reproduce this in 1.10 an 1.11 without any mods and just SpongeForge.
Could only get one egg, hitting the exploding dragon did nothing. This probably needs more information.

**Comment by Zidane** [comment]
Closing until we get more information.
