### ISSUE TITLE
Installing Applied Energistics Causes Crash

### ISSUE THREAD

**Issue by Orcinuss** [SpongePowered/SpongeForge#1042]
I wasn't sure where to post an issue so ill make one in both.

When Applied Energistics is installed, sponge fails to launch due to:
An essential class was loaded before Sponge could patch it, this usually means  that another coremod has caused the class to load prematurely

I have tried loading in the following ways:
Forge Version > Sponge Version with AE == failed
Forge Version < Sponge Version with AE== failed
Forge Version > Sponge Version without AE == launched
Forge Version < Sponge Version without AE== launched

Running Direwolf20 1.10.2 Pack v1.0.0
Applied Energistics rv4-alpha-5
Forge v12.18.2.2124
SpongeForge v1.10.2-2123-6.0.0-BETA-1878
Multiplayer Server MC 1.10.2

Here is the error: http://pastebin.com/HayMrXN7

**Comment by Orcinuss** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2482

**Comment by kashike** [comment]
https://github.com/SpongePowered/SpongeForge/issues/966
