### ISSUE TITLE
Push for Forge version : 2124 

### ISSUE THREAD

**Issue by alicheek** [SpongePowered/SpongeForge#1043]
Hey there this morning i was attempting to set up the new DW20 server for mc version 1.10.2 it comes packaged with forge version 2124 and unfortunately with sponge the server wont boot up.

I was using the latest version of sponge as of me writing this : 6.0.0-BETA-1878

Log:  http://pastebin.com/cmns5dQd

Thanks for the great support and the amazing Sponge system really loving it :)

**Comment by kashike** [comment]
https://github.com/SpongePowered/SpongeForge/issues/966
