### ISSUE TITLE
[Bug] item dupes with extra utilities 2

### ISSUE THREAD

**Issue by NightOps007** [SpongePowered/SpongeForge#1045]
With sponge installed with extra utilities 2(extrautils2-1.10.2-alpha-1.2.2), it causes item dupe when you mine compressed anything(cobblestone, netherrack, sand, gravel, didn't try compressed dirt but probably it too). Bug duplicated in test world with only sponge and XU2 installed. Tried for both API5(spongeforge-1.10.2-2123-5.1.0-BETA-1879) and API6(spongeforge-1.10.2-2123-6.0.0-BETA-1877). Bug occurs for both.

**Comment by ProsperCraft** [comment]
We have the same issue.

**Comment by bloodmc** [comment]
@NightOps007 @ProsperCraft Test with SF 1914+.

**Comment by bloodmc** [comment]
Reopen if the issue exists in 1930+

**Comment by phit** [comment]
working fine with 
extrautils2-1.10.2-alpha-1.2.2
spongeforge-1.10.2-2171-5.1.0-BETA-1930
