### ISSUE TITLE
Exception Exiting Phase (API 5)

### ISSUE THREAD

**Issue by Dysthymic** [SpongePowered/SpongeForge#1047]
http://pastebin.com/vymVG4UU

Sponge 1877

No clue what is causing this but it's spamming our log files like no other. Today, forge-latest log file is 9GB. Yesterday, it was 400MB.

I keep seeing the entry for 29x bread. I removed the bread from the players inventory and it is still going on and on and on

**Comment by Aaron1011** [comment]
Can you link to your full `fml-server-latest.log`?

**Comment by Dysthymic** [comment]
It'll take a day or two to download and upload. It is 15GB now

**Comment by Dysthymic** [comment]
I thought it may be a confliction with our Forge version at 2107 on the latest Sponge which asks for a higher Forge. So we downgraded Sponge to 1864 as a test and it still occurs

**Comment by Aaron1011** [comment]
@Dysthymic: If the full log is too large, can you just upload several of the `Exception Exiting Phase` sections from it? In the pastebin you linked, the full error was cut off due to some kind of rate limiting with your logger.

**Comment by bloodmc** [comment]
@Dysthymic You can turn off these warnings in sponge's global.conf under cause tracker category

https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/config/category/CauseTrackerCategory.java#L33

It still has to be resolved though but at least it shouldn't spam your logs further.

**Comment by Dysthymic** [comment]
Hello, sorry for the delayed response. We had to downgrade because it was pretty serious. Here is as much of the forge-latest when we experienced the issue as I could upload http://pastebin.com/7YzTP88Y

**Comment by Aaron1011** [comment]
This should be fixed in the latest SpongeForge stable: https://www.spongepowered.org/downloads/spongeforge/stable/1.10.2.

**Comment by ghost** [comment]
Note that this was never fixed for 1.10.2 @Aaron1011

**Comment by Zidane** [comment]
@Aaron1011 

Issues for 1.10.2 are closed as we don't support 1.10.2 anymore.
