### ISSUE TITLE
Blood Magic Crash during player login (sponge #1897)

### ISSUE THREAD

**Issue by ZigTheHedge** [SpongePowered/SpongeForge#1050]
Server crashes when certain player logs in. Here's crashlog: http://pastebin.com/nD4sxh28

I'm not sure whether it is Sponge issue, or Blood Magic, so, here's link to WayOfTime's issue: https://github.com/WayofTime/BloodMagic/issues/977

Versions:
    BloodMagic: 1.9.4-2.1.0-66
    Minecraft: 1.10.2
    Forge: 2123
    Sponge: 1879

**Comment by bloodmc** [comment]
Error is coming from Blood Magic
 WayofTime.bloodmagic.demonAura.WorldDemonWillHandler.getCurrentWill(WorldDemonWillHandler.java:177)

Looks like corrupted data in the player's profile
Delete the player's dat file so it regens fresh.
