### ISSUE TITLE
1880 will not load, 1879 will.

### ISSUE THREAD

**Issue by ProsperCraft** [SpongePowered/SpongeForge#1051]
I get this crash when updating to 1880, is this the point where 6.0 doesn't work with 5.0 plugins any longer?

https://gist.github.com/ProsperCraft/50254e240e2d5722569bcd832077c773

**Comment by stephan-gh** [comment]
Yes and no. The change that is breaking two of your plugins was already made for API 5 (but is only enforced in API 6 now). That means these plugins were not properly updated to API 5. Two of your plugins need an update (they are using invalid plugin IDs):
- `VotifierListener` (`io.github.hsyyid.votifierlistener`)
- `RankUpper` (`br.net.fabiozumbi12.rankupper`)

Until they are updated you will either need to use the stable builds that will continue to be updated (without breaking these plugins) or stay on an older bleeding build.

**Comment by ProsperCraft** [comment]
Thank you.
