### ISSUE TITLE
Soulbound acts like cursed enchant

### ISSUE THREAD

**Issue by DigitalSketch** [SpongePowered/SpongeForge#1052]
We're using the FTB HermitPack and have found that since we installed Sponge to make it run more smoothly (which it does by the way, thank you!), the soulbound (From EnderIO) items completely disappear from a user's inventory and grave site.  It acts more like the cursed enchant.   I've tested this in a single player world on the FTB HermitPack mod pack, and it works as it's supposed to.

Below are the versions we are running, there is no log file for this bug.
Sponge: 1.10.2-2107-6.0.0-BETA-1844
Forge: 12.18.2.2125

**Comment by bloodmc** [comment]
You are behind over 50+ builds. Update to latest SpongeForge.
