### ISSUE TITLE
kicking message

### ISSUE THREAD

**Issue by vaniron** [SpongePowered/SpongeForge#1053]
hello guys do u think that it is possible to change error message on forge server when kicking player without modpack? 

in default it says this:
[FML]: Disconnecting Player: This server requires FML/Forge to be installed. Contact your server admin for more details. 
- but i need to change it to my language so players better understand it

is it possible to add this feature to sponge or modify the message with some other mod?

**Comment by bloodmc** [comment]
This belongs in Forge's github

https://github.com/MinecraftForge/MinecraftForge/issues
