### ISSUE TITLE
Chunk loading and tick issue - Minecarts revealed the issue.

### ISSUE THREAD

**Issue by Deadlyapples** [SpongePowered/SpongeForge#1055]
https://www.youtube.com/watch?v=dVk7hwUXErQ&feature=youtu.be

That is the evidence. This issue went away when I removed spongeforge as a mod on my server.

No crash reports or logs hint as to why this happens.

**Comment by LuxusDarkangel** [comment]
The video is set to private, change it to unlisted if you want people to access it only through the link.

**Comment by Deadlyapples** [comment]
Video link updated.

**Comment by Deamon5550** [comment]
If I understand what you are confused about: sponge adds [configurable](https://docs.spongepowered.org/master/en/server/getting-started/configuration/sponge-conf.html) entity activation ranges and does not tick entities out side of those ranges from the nearest player which is a significant performance boost at no cost in most cases. You can raise or disable the activation range for minecarts if you wish, or you can disable the entity activation range checks altogether

**Comment by Deadlyapples** [comment]
How do I remove these range checks? I tried removing them from the list but this causes No entities to exist anywhere. No mobs, no items, no carts etc
