### ISSUE TITLE
Immersive Engineering Villagers trading.

### ISSUE THREAD

**Issue by DigitalSketch** [SpongePowered/SpongeForge#1056]
We're running the hermit mod pack with sponge, and the immersive engineering villagers won't allow us to trade with them (right clicking does nothing).  I checked in a single player world and the villagers would trade.  Is there a setting to enable villager trading we have to set?  Or is this a bug?

We're running version 1888

**Comment by phit** [comment]
cant reproduce with

ImmersiveEngineering-0.10-61.jar
spongeforge-1.10.2-2281-5.2.0-BETA-2464.jar

![2017-07-17_23 40 20](https://user-images.githubusercontent.com/2097483/28291093-54abce20-6b49-11e7-9b35-c00c540414e3.png)
