### ISSUE TITLE
[1.8.9] Chunk loading related performance issues in Buildcraft

### ISSUE THREAD

**Issue by zmaile** [SpongePowered/SpongeForge#1057]
This issue has been brought up at [https://github.com/BuildCraft/BuildCraft/issues/3458](https://github.com/BuildCraft/BuildCraft/issues/3458), however it seems to be a sponge issue, not a Buildcraft issue, so i'm making it here.
------------------------

When a long Buildcraft pipe extends beyond the currently loaded chunks, the chunks seem to be getting loaded, pipes get initialised, and then the chunk is unloaded. This causes normal performance of 10ms/tick (with all pipes in loaded chunks) to become 80ms/tick when the player moves away from the pipes.

My testing showed that removing sponge removes the issue, and using sponge with no sponge-mods still has the issue.
EDIT: JvisualVM snapshots are available in the above link in [this](https://github.com/BuildCraft/BuildCraft/issues/3458#issuecomment-262496815) comment showing with+without SpongeForge, and with pipes in loaded+unloaded chunks.

Java: openjdk version "1.8.0_111"
Forge: forge-1.8.9-11.15.1.1890-1.8.9-universal.jar
SpongeForge: spongeforge-1.8.9-1890-4.2.0-BETA-1762.jar
Buildcraft: buildcraft-7.2.7.jar

**Comment by bloodmc** [comment]
1.8.9 is no longer supported. Update to 1.10.2

**Comment by bloodmc** [comment]
Hrmm maybe i'll backport my chunk gc fixes. I'll think about it =) For now, try disabling chunk gc in sponge's global.conf

**Comment by zmaile** [comment]
@bloodmc That'd be awesome as Buildcraft's latest stable is still in 1.8.9.

**Comment by bloodmc** [comment]
@zmaile Disable chunk gc in sponge's global.conf and retest.

**Comment by zmaile** [comment]
After changing to:

>chunk-gc-tick-interval=0

The tickrate issue disappears, and goes back to 12-14ms/tick

EDIT: So is this actually a bug, or is it an unfortunate side-effect of the chunk GC working as intended?

**Comment by bloodmc** [comment]
@zmaile chunk-gc is bugged in 1.8.9, it will be fine in 1.10.2+.

**Comment by zmaile** [comment]
@bloodmc okay, no worries. Thanks for your help. I'll leave it up to you if you want to close this.

**Comment by bloodmc** [comment]
OK just keep it disabled for 1.8.9. When you update to 1.10.2+, you can leave it on as it works correctly.
