### ISSUE TITLE
Crash when breaking RFTools timer with Actually Additions Drill

### ISSUE THREAD

**Issue by phit** [SpongePowered/SpongeForge#1059]
Doesn't always seem to happen, but we had a few of those now.
Pack is Direwolf20 1.0.0
spongeforge-1.10.2-2123-6.0.0-BETA-1878

[crash-2016-11-24_07.37.34-server.txt](https://github.com/SpongePowered/SpongeForge/files/613127/crash-2016-11-24_07.37.34-server.txt)

Generally the drill seems to behave rather weird, we had some people break a EnderIO Vaccum Chest with it, the block disappeared and you could place other blocks in it's place, but the vacuum effect was still happening.

**Comment by afannnn** [comment]
Why was this issue closed? @phit

**Comment by phit** [comment]
because it's no longer an issue as far as I am aware, if you had a recent crash like this with an updated Sponge & AA version I'll be happy to reopen this

**Comment by afannnn** [comment]
ok just clarifying
