### ISSUE TITLE
PSI/Sponge crash

### ISSUE THREAD

**Issue by ArbitraryHubris** [SpongePowered/SpongeForge#1062]
[Crashlog](http://pastebin.com/80V2p0gV)

[PSI Recipe](http://imgur.com/HbvOQzw)

the spell tries to smelt in a PSI pick but it didn't break the block first so it was trying to apply smelt to stone rather than cobble - this is all assumption.

Crash occurred on Direwolf20 1.10.2 pack v1.0.0

**Comment by bloodmc** [comment]
@ArbitraryHubris update to SF 1914+ and try again.

**Comment by bloodmc** [comment]
Update to latest SF. There should be no issue.
