### ISSUE TITLE
IC2 scrapbox - right click not working in hand

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1066]
Tested on pure forge server, works.
IC2 build 120
With SF 1914/1925 (no plugins or others mods) when right click no item dropped to ground, scrapbox stay in the inventory when survival mode.

**Comment by bloodmc** [comment]
@hunter688 Test 1930

**Comment by ghost** [comment]
scrapbox still not working

**Comment by ghost** [comment]
with build 1947 still not working

**Comment by Aaron1011** [comment]
For now, set `drops-pre-merge` to `false` in your `global.conf` ('I've changed the default value, but it won't affect existing configs). In the future, we'll probably have a more granular way to disable per-merging, but it's necessary to disable it completely for now to fix this issue.

**Comment by ghost** [comment]
works for me, thanks!
<pre>
/sponge -g config optimizations.drops-pre-merge false
</pre>
