### ISSUE TITLE
[1.10.2, 1.11] TabCompleteEvent.Chat firing at incorrect times

### ISSUE THREAD

**Issue by dualspiral** [SpongePowered/SpongeForge#1067]
When playing about with the [Boop plugin](https://forums.spongepowered.org/t/boop-notifies-you-when-youre-mentioned-in-chat/15672) using SpongeForge, tab completion isn't working. It turns out that the `TabCompleteEvent.Chat` event isn't firing at the correct times, firing with `TabCompleteEvent.Command` rather on it's own.

I created a Mixin plugin for 1.10.2 (with an added listener) to investigate what was going on - [see this gist for the code and the results (all tabbing done by a player, not console)](https://gist.github.com/dualspiral/ea4f0e5c656ade8e44aebba9b0b56260) - 
[and here is the mixin plugin compiled](https://github.com/SpongePowered/SpongeForge/files/620210/TestMixins.zip). I did a quick check on a freshly set up 1.11 server too, the problems are identical, so this affects all current versions - the results show the SpongeVanilla is not affected by this problem. Where it says "hooked", it's me attempting to hook onto the line `List<String> list1 = this.commandManager.getTabCompletionOptions(sender, input, pos);`.

With SpongeForge, it can been seen that `TabCompleteEvent.Chat` is fired under the conditions where `TabCompleteEvent.Command`, when for these scenarioes, it should be at the times the Command event is _not_ fired.

I'm not sure what's going on, other than it seems that it's selecting the wrong injection point in SpongeForge...

**Comment by Aaron1011** [comment]
This is my fault - I never updated our tab completions injections for 1.9, when the code was modified to support sending the targeted block during tab completion. I'll update it.
