### ISSUE TITLE
Server Didn't Start/Crashed [Latest Forge and SpongeForge]

### ISSUE THREAD

**Issue by MrDiamond123** [SpongePowered/SpongeForge#1068]
[Crash Log](https://gist.github.com/MrDiamond123/c882e9e0333e06e7c5d44622aa71ddbd)

**Comment by Deamon5550** [comment]
Please use a paste site like [gist.github.com](http://gist.github.com)

**Comment by MrDiamond123** [comment]
ok

**Comment by MrDiamond123** [comment]
https://gist.github.com/MrDiamond123/c882e9e0333e06e7c5d44622aa71ddbd

**Comment by kashike** [comment]
Fixed with https://github.com/SpongePowered/SpongeForge/commit/c88aa371c714be6fbf0c7b367fdaed8d5d5d90c8.
