### ISSUE TITLE
[1.10.2] Exception caught during firing event

### ISSUE THREAD

**Issue by FiveEYZ** [SpongePowered/SpongeForge#1069]
This exception started after updating to SF 1914, same error occurs on SF 1921.

holding any item in hand and right-click in air
https://gist.github.com/FiveEYZ/fa525501dad00a9dbce8eebdac70147f

**Comment by Deamon5550** [comment]
Post your full log that snippet is useless.

**Comment by FiveEYZ** [comment]
sure thing 
fml-server-latest.log: http://paste.ubuntu.com/23556123/
latest.log: http://paste.ubuntu.com/23556168/

**Comment by bloodmc** [comment]
Update to latest SF build.

**Comment by FiveEYZ** [comment]
Still happening on SF 1930

[fml-server-latest.log](https://gist.githubusercontent.com/FiveEYZ/3b4a9a007b040e987919b74c4430f772/raw/718dcb096d8f8f72fe996f6b5d0d55627c2acbde/fml-server-latest.log)
[latets.log](https://gist.github.com/FiveEYZ/e1b22c4b99a767204ce3765c5e224dde)

Also tried to throw a ender pearl but nothing gets thrown, the stack count gets reduced by 1 every attempt to throw.

unable to open Chisel Gui if u aim in the air (works if u aim at a block)
unable to eat food if aiming in the air (works if u aim at a block)

**Comment by bloodmc** [comment]
@FiveEYZ Remove all mods and plugins and test with ONLY SF.
