### ISSUE TITLE
1914 Crash Corruptions

### ISSUE THREAD

**Issue by Dysthymic** [SpongePowered/SpongeForge#1070]
http://pastebin.com/z49yYQ6z

Multiple players are disconnected constantly due to blocks that appear to be corrupted in the world on 1914. This is their player crash report. Upon downgrading, the issue goes away 100%.

We've encountered corrupted Pixelmon Trees, and mainly chests that cause repeat crashes upon login unless the chest or block is set to stone or air with worldedit.

**Comment by inklit** [comment]
Update to the latest version and test again, 1914 was a broken build I think. Use 1923.

**Comment by bloodmc** [comment]
@Dysthymic This has been solved with latest SF stable builds. There were many lost commits in the original merge from 1.10 bleeding.
