### ISSUE TITLE
[1.8.9] Piston trying to push pumpkin/melon at y255 crashes server

### ISSUE THREAD

**Issue by Varijon** [SpongePowered/SpongeForge#1071]
Attempting to activate a piston horizontally at y255 will crash the server if it's attempting to push a pumpkin/melon. This would normally drop these as item instead of pushing them, other blocks such as dirt do not cause the crash. It's a bit strange the error complains about y256, while everything is happening at y255.

Gif demonstration:
http://i.imgur.com/9HwsqTs.gifv

Version:
spongeforge-1.8.9-1890-4.2.0-BETA-1762.jar
forge-1.8.9-11.15.1.1902-1.8.9-universal.jar

Crash report:
http://pastebin.com/cZP36Mzc

**Comment by bloodmc** [comment]
1.8.9 is no longer supported. Update to 1.10.2+
