### ISSUE TITLE
Regression: Shift-click in the IC2 machines

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1072]
Fix IC2 jetpacks #1037 (SF build 1925) bring another bug - cannot shift-click inside IC2 machines.

**Comment by phit** [comment]
also refined storage terminals

**Comment by FiveEYZ** [comment]
same inside CorrelatedPotentialistics terminal and Chisel GUI, also cant open the Chisel GUI if aiming at air (same goes for food).

**Comment by Mohron** [comment]
I can confirm this issue affecting Refined Storage.

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/SpongePowered/SpongeCommon/commit/ce93b5fdea4a2f2f1889c6675387433098f0808f

**Comment by ghost** [comment]
It works now, thanks for fix!
