### ISSUE TITLE
Empty message when player die two times same way

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1073]
When player die two times same way (eg. Skeleton shot), the second death instead death message show empty line in the chat.

SF build 1899

**Comment by Aaron1011** [comment]
@hunter688: Can you reproduce this on the latest SpongeForge? Also, do you mean dying twice in a row by the same source, or something else?

**Comment by ghost** [comment]
Yes by same source. Reproduced with build 1933.
<pre>
[09:44:07] [Server thread/INFO]: Adam4CZ was shot by Skeleton
[09:45:02] [Server thread/INFO]:
</pre>

**Comment by Aaron1011** [comment]
@hunter688: are you able to reproduce this without any plugins or mods?

**Comment by ghost** [comment]
I will try it, then report...

**Comment by SnowBlitzz** [comment]
iirc this is an issue with GP. Not sure tho, so any tests would be nice @hunter688

**Comment by ghost** [comment]
Looks like fixed now (Tested with build 1971).
