### ISSUE TITLE
Unknown Error?

### ISSUE THREAD

**Issue by zerafox** [SpongePowered/SpongeForge#1075]
I was minding my own business, developing my farm to feed myself and my cows when all of a sudden I couldn't plant my seeds anymore, out of no where. I also couldn't use my hoe to create more farmland, couldn't access my doors, chests, furnaces, anything.

01.12 03:37:58 [Server] INFO /***********************************************************************************************************************************/ 01.12 03:37:58 [Server] INFO /* java.lang.Thread.run(Unknown Source) */ 01.12 03:37:58 [Server] INFO /* net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) */ 01.12 03:37:58 [Server] INFO /* net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) */ 01.12 03:37:58 [Server] INFO /* net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) */ 01.12 03:37:58 [Server] INFO /* net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) */ 01.12 03:37:58 [Server] INFO /* net.minecraft.util.Util.func_181617_a(SourceFile:45) */ 01.12 03:37:58 [Server] INFO /* java.util.concurrent.FutureTask.run(Unknown Source) */ 01.12 03:37:58 [Server] INFO /* java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) */ 01.12 03:37:58 [Server] INFO /* net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) */ 01.12 03:37:58 [Server] INFO /* net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjc000(SourceFile:39) */ 01.12 03:37:58 [Server] INFO /* org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:130) */ 01.12 03:37:58 [Server] INFO /* org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:190) */ 01.12 03:37:58 [Server] INFO /* org.spongepowered.common.event.tracking.phase.packet.PacketPhase.unwind(PacketPhase.java:320) */ 01.12 03:37:58 [Server] INFO /* org.spongepowered.common.event.tracking.phase.packet.PacketFunction.lambda$static$47(PacketFunction.java:900) */ 01.12 03:37:58 [Server] INFO /* com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827) */ 01.12 03:37:58 [Server] INFO /* com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821) */ 01.12 03:37:58 [Server] INFO /* com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938) */ 01.12 03:37:58 [Server] INFO /* com.google.common.cache.LocalCache.get(LocalCache.java:3934) */ 01.12 03:37:58 [Server] INFO /* com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195) */ 01.12 03:37:58 [Server] INFO /* com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280) */ 01.12 03:37:58 [Server] INFO /* com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317) */ 01.12 03:37:58 [Server] INFO /* com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524) */ 01.12 03:37:58 [Server] INFO /* org.spongepowered.common.util.LanguageUtil$1.load(LanguageUtil.java:42) */ 01.12 03:37:58 [Server] INFO /* org.spongepowered.common.util.LanguageUtil$1.load(LanguageUtil.java:45) */ 01.12 03:37:58 [Server] INFO /* org.apache.commons.lang3.LocaleUtils.toLocale(LocaleUtils.java:142) */ 01.12 03:37:58 [Server] INFO /* java.lang.IllegalArgumentException: Invalid locale format: en_us */ 01.12 03:37:58 [Server] INFO /* java.lang.Thread.run(Unknown Source) */ 01.12 03:37:58 [Server] INFO /* net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) */ 01.12 03:37:58 [Server] INFO /* net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) */ 01.12 03:37:58 [Server] INFO /* net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) */ 01.12 03:37:58 [Server] INFO /* net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) */ 01.12 03:37:58 [Server] INFO /* net.minecraft.util.Util.func_181617_a(SourceFile:45) */ 01.12 03:37:58 [Server] INFO /* java.util.concurrent.FutureTask.run(Unknown Source) */ 01.12 03:37:58 [Server] INFO /* java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) */ 01.12 03:37:58 [Server] INFO /* net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) */ 01.12 03:37:58 [Server] INFO /* net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjc000(SourceFile:39) */ 01.12 03:37:58 [Server] INFO /* org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:130) */ 01.12 03:37:58 [Server] INFO /* org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:190) */ 01.12 03:37:58 [Server] INFO /* org.spongepowered.common.event.tracking.phase.packet.PacketPhase.unwind(PacketPhase.java:320) */ 01.12 03:37:58 [Server] INFO /* org.spongepowered.common.event.tracking.phase.packet.PacketFunction.lambda$static$47(PacketFunction.java:900) */ 01.12 03:37:58 [Server] INFO /* com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827) */ 01.12 03:37:58 [Server] INFO /* com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821) */ 01.12 03:37:58 [Server] INFO /* com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938) */ 01.12 03:37:58 [Server] INFO /* com.google.common.cache.LocalCache.get(LocalCache.java:3934) */ 01.12 03:37:58 [Server] INFO /* com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201) */ 01.12 03:37:58 [Server] INFO /* com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Invalid locale format: en_us */ 01.12 03:37:58 [Server] INFO /* Stacktrace: */ 01.12 03:37:58 [Server] INFO /* Object: EntityItemEntityDropsSupplier{Captured=0} */ 01.12 03:37:58 [Server] INFO /* - Name: CapturedEntityItemDrops */ 01.12 03:37:58 [Server] INFO /* Object: EntityItemDropsSupplier{Captured=0} */ 01.12 03:37:58 [Server] INFO /* - Name: CapturedEntityItemDropMap */ 01.12 03:37:58 [Server] INFO /* Object: CapturedItemStackSupplier{Captured=0} */ 01.12 03:37:58 [Server] INFO /* - Name: CapturedItemStacks */ 01.12 03:37:58 [Server] INFO /* Object: CapturedEntitiesSupplier{Captured=0} */ 01.12 03:37:58 [Server] INFO /* - Name: CapturedEntities */ 01.12 03:37:58 [Server] INFO /* Object: CapturedItemsSupplier{Captured=0} */ 01.12 03:37:58 [Server] INFO /* - Name: CapturedItems */ 01.12 03:37:58 [Server] INFO /* Object: BlockItemDropsSupplier{Captured=0} */ 01.12 03:37:58 [Server] INFO /* - Name: CapturedBlockDropMap */ 01.12 03:37:58 [Server] INFO /* Object: BlockItemEntityDropsSupplier{Captured=0} */ 01.12 03:37:58 [Server] INFO /* - Name: CapturedBlockITemDrops */ 01.12 03:37:58 [Server] INFO /* Object: CapturedBlocksSupplier{Captured=0} */ 01.12 03:37:58 [Server] INFO /* - Name: CapturedBlocks */ 01.12 03:37:58 [Server] INFO /* Object: org.spongepowered.common.event.tracking.phase.packet.BasicPacketState@27dc5f75 */ 01.12 03:37:58 [Server] INFO /* - Name: UnwindingState */ 01.12 03:37:58 [Server] INFO /* Object: EntityPlayerMP['Zera_Fox'/26926, l='Creatures', x=-16401.83, y=63.00, z=28671.55] */ 01.12 03:37:58 [Server] INFO /* - Name: Notifier */ 01.12 03:37:58 [Server] INFO /* Object: EntityPlayerMP['Zera_Fox'/26926, l='Creatures', x=-16401.83, y=63.00, z=28671.55] */ 01.12 03:37:58 [Server] INFO /* - Name: Owner */ 01.12 03:37:58 [Server] INFO /* Object: false */ 01.12 03:37:58 [Server] INFO /* - Name: IgnoringCreative */ 01.12 03:37:58 [Server] INFO /* Object: SpongeItemStackSnapshot{itemType=Item{Name=none}, count=1} */ 01.12 03:37:58 [Server] INFO /* - Name: Cursor */ 01.12 03:37:58 [Server] INFO /* Object: net.minecraft.network.play.client.CPacketClientSettings@5c48976e */ 01.12 03:37:58 [Server] INFO /* - Name: Packet */ 01.12 03:37:58 [Server] INFO /* Object: EntityPlayerMP['Zera_Fox'/26926, l='Creatures', x=-16401.83, y=63.00, z=28671.55] */ 01.12 03:37:58 [Server] INFO /* - Name: PacketPlayer */ 01.12 03:37:58 [Server] INFO /* Object: EntityPlayerMP['Zera_Fox'/26926, l='Creatures', x=-16401.83, y=63.00, z=28671.55] */ 01.12 03:37:58 [Server] INFO /* - Name: Source */ 01.12 03:37:58 [Server] INFO /* - Name: UnwindingContext */ 01.12 03:37:58 [Server] INFO /* Context: */ 01.12 03:37:58 [Server] INFO /* - Phase: org.spongepowered.common.event.tracking.phase.general.PostState@686b08c0 */ 01.12 03:37:58 [Server] INFO /* Phases remaining : */ 01.12 03:37:58 [Server] INFO /* Object: EntityPlayerMP['Zera_Fox'/26926, l='Creatures', x=-16401.83, y=63.00, z=28671.55] */ 01.12 03:37:58 [Server] INFO /* - Name: Notifier */ 01.12 03:37:58 [Server] INFO /* Object: EntityPlayerMP['Zera_Fox'/26926, l='Creatures', x=-16401.83, y=63.00, z=28671.55] */ 01.12 03:37:58 [Server] INFO /* - Name: Owner */ 01.12 03:37:58 [Server] INFO /* Object: false */ 01.12 03:37:58 [Server] INFO /* - Name: IgnoringCreative */ 01.12 03:37:58 [Server] INFO /* Object: SpongeItemStackSnapshot{itemType=Item{Name=none}, count=1} */ 01.12 03:37:58 [Server] INFO /* - Name: Cursor */ 01.12 03:37:58 [Server] INFO /* Object: net.minecraft.network.play.client.CPacketClientSettings@5c48976e */ 01.12 03:37:58 [Server] INFO /* - Name: Packet */ 01.12 03:37:58 [Server] INFO /* Object: EntityPlayerMP['Zera_Fox'/26926, l='Creatures', x=-16401.83, y=63.00, z=28671.55] */ 01.12 03:37:58 [Server] INFO /* - Name: PacketPlayer */ 01.12 03:37:58 [Server] INFO /* Object: EntityPlayerMP['Zera_Fox'/26926, l='Creatures', x=-16401.83, y=63.00, z=28671.55] */ 01.12 03:37:58 [Server] INFO /* - Name: Source */ 01.12 03:37:58 [Server] INFO /* Affected World : WorldServer{LevelName=Creatures, DimensionId=0, DimensionType=minecraft:overworld} */ 01.12 03:37:58 [Server] INFO /* PhaseContext : */ 01.12 03:37:58 [Server] INFO /* Something happened when trying to unwind org.spongepowered.common.event.tracking.phase.packet.BasicPacketState@27dc5f75 */ 01.12 03:37:58 [Server] INFO /***********************************************************************************************************************************/ 01.12 03:37:58 [Server] INFO /* Exception Exiting Phase */ 01.12 03:37:58 [Server] INFO /***********************************************************************************************************************************/

**Comment by kashike** [comment]
You aren't running the latest build of SpongeForge. Update, and report if this still happens.

**Comment by zerafox** [comment]
This is the latest version available to me through my host. :(

**Comment by zerafox** [comment]
I just uploaded the latest version of spongeforge I could find on the site and I'm getting this:

01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /***********************************************************************************************************************/ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* java.lang.Thread.run(Unknown Source) */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:602) */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:274) */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:94) */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:125) */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* net.minecraftforge.fml.common.eventhandler.ASMEventHandler_11_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:266) */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:191) */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:41) */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:104) */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(Unknown Source) */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:160) */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:174) */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:66) */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:177) */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:138) */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* me.mrdaniel.mmo.listeners.WorldListener.lambda$onEntitySpawn$0(WorldListener.java:81) */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* net.minecraft.entity.item.EntityItem.getItemData(EntityItem.java:228) */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* org.spongepowered.common.item.inventory.util.ItemStackUtil.createSnapshot(ItemStackUtil.java:124) */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* net.minecraft.item.ItemStack.createSnapshot(ItemStack.java:233) */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* org.spongepowered.common.item.inventory.SpongeItemStackSnapshot.<init>(SpongeItemStackSnapshot.java:87) */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* net.minecraft.item.ItemStack.getContainers(ItemStack.java:254) */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* java.lang.Exception: null */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* Printing a Stacktrace: */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* Please ask help for seeing if this is an issue with a mod and report it! */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* An ItemStack has a null ItemType! This is usually not supported as it will likely have issues elsewhere. */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /***********************************************************************************************************************/ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* Null Item found! */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /***********************************************************************************************************************/ 01.12 05:20:06 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_111] 01.12 05:20:06 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?] 01.12 05:20:06 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:602) [MinecraftServer.class:?] 01.12 05:20:06 [Server] INFO at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:274) [FMLCommonHandler.class:?] 01.12 05:20:06 [Server] INFO at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:94) [EventBus.class:?] 01.12 05:20:06 [Server] INFO at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:125) [EventBus.class:?] 01.12 05:20:06 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?] 01.12 05:20:03 [Server] Server thread/INFO [com.zaxxer.hikari.HikariDataSource]: HikariPool-2 - Started.

**Comment by zerafox** [comment]
And this one too?
Not sure if their connected, apologies if they aren't..

01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /***********************************************************************************************************************/ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* java.lang.Thread.run(Unknown Source) */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:602) */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:274) */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:94) */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:125) */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* net.minecraftforge.fml.common.eventhandler.ASMEventHandler_11_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:266) */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:191) */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:41) */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:104) */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(Unknown Source) */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:160) */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:174) */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:66) */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:177) */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:138) */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* me.mrdaniel.mmo.listeners.WorldListener.lambda$onEntitySpawn$0(WorldListener.java:81) */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* net.minecraft.entity.item.EntityItem.getItemData(EntityItem.java:228) */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* org.spongepowered.common.item.inventory.util.ItemStackUtil.createSnapshot(ItemStackUtil.java:124) */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* net.minecraft.item.ItemStack.createSnapshot(ItemStack.java:233) */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* org.spongepowered.common.item.inventory.SpongeItemStackSnapshot.<init>(SpongeItemStackSnapshot.java:87) */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* net.minecraft.item.ItemStack.getContainers(ItemStack.java:254) */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* java.lang.Exception: null */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* Printing a Stacktrace: */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* Please ask help for seeing if this is an issue with a mod and report it! */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* An ItemStack has a null ItemType! This is usually not supported as it will likely have issues elsewhere. */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /***********************************************************************************************************************/ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* Null Item found! */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /***********************************************************************************************************************/ 01.12 05:20:06 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_111] 01.12 05:20:06 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?] 01.12 05:20:06 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:602) [MinecraftServer.class:?] 01.12 05:20:06 [Server] INFO at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:274) [FMLCommonHandler.class:?] 01.12 05:20:06 [Server] INFO at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:94) [EventBus.class:?] 01.12 05:20:06 [Server] INFO at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:125) [EventBus.class:?] 01.12 05:20:06 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?] 01.12 05:20:06 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_11_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) [?:?] 01.12 05:20:06 [Server] INFO at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:266) [SpongeMod.class:1.10.2-2123-5.1.0-BETA-1925] 01.12 05:20:06 [Server] INFO at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:191) [SpongeScheduler.class:1.10.2-2123-5.1.0-BETA-1925] 01.12 05:20:06 [Server] INFO at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:41) [SyncScheduler.class:1.10.2-2123-5.1.0-BETA-1925] 01.12 05:20:06 [Server] INFO at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:104) [SchedulerBase.class:1.10.2-2123-5.1.0-BETA-1925] 01.12 05:20:06 [Server] INFO at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(Unknown Source) [?:1.8.0_111] 01.12 05:20:06 [Server] INFO at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:160) ~[SchedulerBase.class:1.10.2-2123-5.1.0-BETA-1925] 01.12 05:20:06 [Server] INFO at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:174) ~[SchedulerBase.class:1.10.2-2123-5.1.0-BETA-1925] 01.12 05:20:06 [Server] INFO at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:66) ~[SyncScheduler.class:1.10.2-2123-5.1.0-BETA-1925] 01.12 05:20:06 [Server] INFO at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:177) ~[SchedulerBase.class:1.10.2-2123-5.1.0-BETA-1925] 01.12 05:20:06 [Server] INFO at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:138) ~[Task$Builder.class:1.10.2-2123-5.1.0-BETA-1925] 01.12 05:20:06 [Server] INFO at me.mrdaniel.mmo.listeners.WorldListener.lambda$onEntitySpawn$0(WorldListener.java:81) ~[WorldListener.class:?] 01.12 05:20:06 [Server] INFO at net.minecraft.entity.item.EntityItem.getItemData(EntityItem.java:228) ~[yk.class:?] 01.12 05:20:06 [Server] INFO at org.spongepowered.common.item.inventory.util.ItemStackUtil.createSnapshot(ItemStackUtil.java:124) ~[ItemStackUtil.class:1.10.2-2123-5.1.0-BETA-1925] 01.12 05:20:06 [Server] INFO at net.minecraft.item.ItemStack.createSnapshot(ItemStack.java:233) ~[adz.class:?] 01.12 05:20:06 [Server] INFO at org.spongepowered.common.item.inventory.SpongeItemStackSnapshot.<init>(SpongeItemStackSnapshot.java:92) ~[SpongeItemStackSnapshot.class:1.10.2-2123-5.1.0-BETA-1925] 01.12 05:20:06 [Server] INFO at net.minecraft.item.ItemStack.func_77952_i(ItemStack.java:244) ~[adz.class:?] 01.12 05:20:06 [Server] INFO java.lang.NullPointerException 01.12 05:20:06 [Server] Server thread/ERROR [Sponge]: The Scheduler tried to run the task adventuremmo-S-2 owned by Plugin{id=adventuremmo, name=AdventureMMO, version=1.6.3, source=/mods/MMO-v1.6.3-API5.x.jar}, but an error occured.

**Comment by kashike** [comment]
Those aren't related to this issue. You can open a new issue for those, but *please* format them correctly, and not all on one line.

**Comment by zerafox** [comment]
:\ That's how they copy from the console/file. I'll see what I can do though
