### ISSUE TITLE
[1.10.2] Crash when adding MovingWorld

### ISSUE THREAD

**Issue by FiveEYZ** [SpongePowered/SpongeForge#1077]
here is the fml log while trying to start the server with https://minecraft.curseforge.com/projects/movingworld/files/2346115

modpack is https://minecraft.curseforge.com/projects/abridged

Running with:
Forge 2171
SF 1928

[fml-server-latest.log](https://gist.github.com/FiveEYZ/9a6a32ca2af625f422e1fe078aca1ea1)
[latets.log](https://gist.github.com/FiveEYZ/65c2ddee3c09c966c707ab8075f86632)

**Comment by Aaron1011** [comment]
@FiveEYZ: With the fix of the associated Mixin bug, MovingWorld should work in the latest version of SpongeForge for 1.10.2.
