### ISSUE TITLE
Crash/Errorspam unwind org.spongepowered.common.event.tracking.phase.packet.PrimaryInventoryShiftClick@79b17038

### ISSUE THREAD

**Issue by johnfriedrich** [SpongePowered/SpongeForge#1080]
SF 1928
Forge 2123
Pixelmon 5.0 Beta 12
To be honest I have no idea how to reproduce.
We have 60 players online and we get this or even bigger traces quite often, ending in crashes or 5.000.000 lines of errors in 3 seconds.
http://pastebin.com/sbNhkX86
http://pastebin.com/arKh14Rs
http://pastebin.com/d7TnzWQP

**Comment by Aaron1011** [comment]
Can you upgrade to SpongeForge 1942? I've made some changes that will aid in debugging future stacktraces.

**Comment by johnfriedrich** [comment]
Testing with SpongeForge 1942 and Forge 2171 now. Will report back if error shows up again.

**Comment by johnfriedrich** [comment]
New error with spongeforge 1952:
http://pastebin.com/mpkTw2Hd

**Comment by Aaron1011** [comment]
@i9hdkill: Can you see if it's possible to reproduce this by left/right clicking or shift clicking in the Pixelmon pokemon gui to the left of your main inventory? You might need to actually perform an action (e.g. moving a pokemon around) for it to work.

**Comment by johnfriedrich** [comment]
Me and some staff members tried that. Even to interact with pixelmon pc's etc. all kind of pokemon movements inside the gui etc. Everything fine.

**Comment by bloodmc** [comment]
@i9hdkill Does this happen with SF 1971?

**Comment by johnfriedrich** [comment]
Not the inventory issue I guess, but this is still there:
http://pastebin.com/xqDs9XwP
Full log: (55mb)
http://pastebin.com/ScjiFFdC
https://www.dropbox.com/s/wt36v0gxwid5h4a/fml-server-latest.log?dl=0
This only happens if people give each other /at or /trust when they are both on the same claim.

For example
Player A owns a claim.
Player B is on that claim.
Player A uses /at or /trust PlayerB

Big error(debug) of death.

Maybe I should open an extra ticket, as this is not an inventory issue.

**Comment by bloodmc** [comment]
@Aaron1011 @gabizou can you see what is happening above?

**Comment by gabizou** [comment]
@bloodmc this was fixed ages ago with bed block changes. If I recall, we recently changed it ever so slightly, but it should still be capturing block changes (or letting them pass through). There's basically supposed to be special handling from the stop sleeping status packet.

**Comment by johnfriedrich** [comment]
Yes, still getting the inventory one with 1971

**Comment by johnfriedrich** [comment]
@bloodmc @gabizou Can confirm it's a bed that is causing this issue.
You can easily repdroduce it.

**Comment by bloodmc** [comment]
Unable to reproduce this with latest builds.
