### ISSUE TITLE
Duplicating Entities

### ISSUE THREAD

**Issue by zerafox** [SpongePowered/SpongeForge#1081]
Teleporting from one area to another and back again causes a Duplication of Entities.

This was discovered by the increasing amount of Cows, Pigs, Chickens & Mo' Creatures sharing a space often occupied by the player.

Mods installed to SpongeForge:
Forge: 12.18.2.2171
SpongeForge: 1.10.2-2171-5.1.0-BETA-1942
AdminShop 1.8.2
**Biomes O' Plenty:** 5.0.0.2109
**Custom Spawner:** 3.10.1
**Custom NPCs:** 1.10.2
**Mo'Creatures:** 10.0.6
EconomyLite: 2.5.1
NuVotifier: 2.3.3
PermissionManager: 2.5.1
EMPSponge: 3.0.15-sponge
keys: 1.2
AdventureMMO: 1.6.3
**More Player Models:** 1.10.2
Nations: 2.2
Nucleus: 0.14.0-5.0
**Tough As Nails:** 1.0.11
Wallet Drop: 0.2.0

I'm not 100% sure what is causing this duplication of all living entities, so I'm including a complete list of my **mods** as well as Sponge Plugin/Mods.
This was occurring on 2123 as well and we recently updated Forge & Sponge hoping it would make a difference.
There are no errors appearing in the servers console.

**Comment by zerafox** [comment]
I've done some minor teleportation tests in a Forge only environment with only the mods installed to the client, I cannot reproduce a duplication with only Forge supported Mods.
For this test, I recorded my starting location and spawned 1 Vanilla Cow, 1 Mo'Creatures Turkey and an NPC from CustomNPC. Teleported a great deal away from the location and returned. No duplication of either the Turkey or the Cow.
There has yet to be seen any duplication of the NPC from CustomNPCs, but for good measure made sure to spawn one in.

EDIT: It was discovered that this duplication also occurs in ToughAsNails items when hung on the wall. Original item remains, although sometimes invisible, and items duplicate themselves to drop onto the floor nearby. This includes the Itemframe as well. (Ticket of incident was also set to T.A.N team)

**Comment by inklit** [comment]
Oh interesting. This seems to affect my server as well but I didn't quite pin it down to what was causing it.

**Comment by zerafox** [comment]
Do you also have any of the mods I listed above?
If not, I think we can rule out any sort of mod combination or fault.

**Comment by inklit** [comment]
None of the same mods.
```
Plugins (31): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, OpenComputers (Core), SpongeAPI, SpongeForge, Unborked Core, <CCTweaks ASM>, NoXray, ComputerCraft, CCTweaks, ChunkLoaderZ, CXLibrary, EssentialCmds, GriefPrevention, Iron Chest, Just Enough Items, Kits, KristMarket, KristPay, LogDupePatch, LuckPerms, MinimalPeripherals, More Furnaces, OpenComputers, Plethora Core, Plethora, Prism, Unborked, WorldEdit
```

**Comment by bookerthegeek** [comment]
@zerafox If I am reading this right, the entity needs to be in the same block space as the player when teleporting away and then back correct?

**Comment by zerafox** [comment]
In the area, within render range when teleporting back. Doesn't have to be sharing the block or even the block next the player. I think the entities were all within a 10-20 block radius tops around the player?

It also began duplicating hung item frames and the items in them too (causing them to pop off the extras to the floor) sometimes. That one didn't occur all the time though

**Comment by bookerthegeek** [comment]
What are you using to perform the teleportation?

**Comment by zerafox** [comment]
Nucleus

**Comment by inklit** [comment]
I used EssentialCMDs

**Comment by bloodmc** [comment]
@zerafox You need to test latest Forge/SF with no other mods and/or plugins besides nucleus.

**Comment by axieum** [comment]
This is also an occurrence on our HermitPack (1.5.1) server. However, I've only seen my tamed wolves duplicate.
**SpongeForge-5.10-BETA-1992**

**Comment by bloodmc** [comment]
This was fixed awhile ago. Create a new ticket if it happens with latest builds.
