### ISSUE TITLE
Tinkers Construct of EFLN does not work

### ISSUE THREAD

**Issue by flier268** [SpongePowered/SpongeForge#1083]
Forge : forge-1.10.2-12.18.2.2179
MC : 1.10.2
SpongeForge : 1.10.2-2171-5.1.0-BETA-1933

EFLN will break block ,but i can't get any block
I have report to [here](https://github.com/SlimeKnights/TinkersConstruct/issues/2605)

**Comment by phit** [comment]
still an issue in 1.11.2

**Comment by phit** [comment]
Closing in favor of https://github.com/SpongePowered/SpongeForge/issues/1209, as it had more activity and essentially tracks the same thing. Issues with events related to EFLN.
