### ISSUE TITLE
[1.10.2] Intended to capture block changes, but there is no list available!

### ISSUE THREAD

**Issue by johnfriedrich** [SpongePowered/SpongeForge#1084]
SF 1957
Forge 2171
Not sure how this happened exactly.
Some players mentioned in this report were not even online, when this happened! Not even since the restart.(18hours before the error)
http://pastebin.com/5SBqWwfH
Tell me if you need more information.

Hm, leaf_stone_hoe is involved, which is actually bugged in the pixelmon mod.

**Comment by bloodmc** [comment]
Fixed in https://github.com/SpongePowered/SpongeCommon/commit/e197c1ea07772481b991d46b00b52641b850fc24
