### ISSUE TITLE
[1.10.2] Daylight sensor crash Cannot get property PropertyInteger

### ISSUE THREAD

**Issue by johnfriedrich** [SpongePowered/SpongeForge#1086]
Happened when saving the map
Mc server log: http://pastebin.com/f7XVyhZh
mc crash log: http://pastebin.com/rxFxFha9
No errors in forge log.
We just use Pixelmon, so no mod that uses/alters the sensor at all. So guess it's eiher sponge or forge.

**Comment by bloodmc** [comment]
This shouldn't be happening on latest builds. Create a new ticket if it persists.
