### ISSUE TITLE
NO CONFIG

### ISSUE THREAD

**Issue by LertuZUES** [SpongePowered/SpongeForge#1088]
im currently using the latest build of sponge on 1.10.2 and WHENEVER I LOAD the server to get the plugin config It wont generate it

**Comment by LertuZUES** [comment]
and no log
its like the plugins are invisible in the plugins folder

**Comment by JBYoshi** [comment]
If there is no log, could you post the terminal output?

**Comment by Deamon5550** [comment]
also when you say `plugins folder` you are aware that plugins go into the mods folder by default right?

**Comment by bloodmc** [comment]
Move plugins to mods folder as Deamon stated.
