### ISSUE TITLE
 Sponge Forge Build 1.10.2  [1971] Random Crash with RFtools Power Generator

### ISSUE THREAD

**Issue by alicheek** [SpongePowered/SpongeForge#1091]
Doesnt seem to be a consistant crash but it has done it a few times now

Crash Report : http://pastebin.com/rDBeYUKx

**Comment by Orcinuss** [comment]
This doesn't seem to be limited to one type of block. Happened to me with the RFTools timer.
Crash Report: http://pastebin.com/8JrJSFxK

I reported it on RFTools Github: https://github.com/McJty/RFTools/issues/913

**Comment by phit** [comment]
this was resolved by the mod author
