### ISSUE TITLE
Sponge Forge Build 1.10.2 [1971] : New World Generation & Lag Spikes

### ISSUE THREAD

**Issue by alicheek** [SpongePowered/SpongeForge#1092]
Hey there, now i do not have any errors for this issue but it seems that all our 1.10.2 servers with sponge forge installed seem to be getting issues with quite substantial lag spikes from  new world generation, these lag spikes can last about 10 seconds which in this time a player basically cant interact with the world.

I have quite a few servers from 1.5.2 to 1.11 and general lag will just produce a higher latency for player interactions and slower automation with machines but these are full on spikes of which no interactions can be done.

From testing about so far what seems to be the cause is when a player is generating new chunks. If no one is then moving or just at their bases then we do not get these spikes.

I have tried using the /sponge timings report but nothing substantial really comes up its almost like the whole process freezes and its not caught by the profiler. 

Now a couple of things i can remove from the equation is our hardware because 2 out of the 3 1.10.2 servers are on a different box, these boxes also have other minecraft servers which are particularly more busier and have near enough 20 tps readings.

I was wondering if maybe we could be suggested something to maybe try and find out the problem or if this is a known problem with either a mod that all these modpacks are using

Modpacks : DW20 1.10.2   Infinity Lite  HermitPack

Our Server Specs : 

Server 1 : 

CPU
Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz
Cores : 12
Cache : 15360KB
RAM
4x 32767MB DDR4 2133 MHz
Disks
2 x 480 GB SSD
Motherboard
X10SRi-F

Server 2 : 

CPU
Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz
Cores : 8
Cache : 10240KB
RAM
4x 16384MB DDR4 2133 MHz
Disks
3 x 300 GB SSD
Motherboard
X9SRE/X9SRE-3F/X9SRi/X9SRi-3F

Server 3 : 

CPU
Intel(R) Xeon(R) CPU E5-1630 v3 @ 3.70GHz
Cores : 8
Cache : 10240KB
RAM
4x 16384MB DDR4 2133 MHz
Disks
2 x 480 GB SSD
Motherboard
X10SRi-F

Thanks for your time 

alicheek

**Comment by ghost** [comment]
pregen yours world before server start...

**Comment by bloodmc** [comment]
Do what hunter688 said and pregen your world. Use nucleus or project borders to do this. Search for them on our forums.
