### ISSUE TITLE
[1.11] Exeption caught when trying to attack mobs.

### ISSUE THREAD

**Issue by shuymn** [SpongePowered/SpongeForge#1095]
Exeption happended when left clicking(attack) mobs.
This error doesn't cause server/client crash and only in SpongeForge 1972+ 

my server latest.log: http://pastebin.com/9q42KGw7

Minecraft: 1.11
SpongeForge: 1974
Forge: 2178

**Comment by Aaron1011** [comment]
Sorry about that - I forgot to update the submodule ref for my fix. The problem should be fixed in the latest SpongeForge (commit https://github.com/SpongePowered/SpongeForge/commit/846342f324bfa3b93235b3154397256dbbf960d7)
