### ISSUE TITLE
Unable to Update Redstone Neighbors -> Crash

### ISSUE THREAD

**Issue by Orcinuss** [SpongePowered/SpongeForge#1099]
Sponge seems to be having trouble updating redstone wire at times and occasionally crashes the server. The last block being updated says it has something to do with the rftools timer.

Please note that the actual size of the crash report is 1.2MB and has been cut short due to file restrictions on pastebin.
Crash Report: http://pastebin.com/Gx3K9jqZ
Full Report: http://paste.ubuntu.com/23609184/

**Comment by FiveEYZ** [comment]
U can use paste.ubuntu.com no limitation there

**Comment by Orcinuss** [comment]
It doesn't really make a difference due to the crash report being the same exact thing over and over again.

**Comment by Aaron1011** [comment]
I'm fairly certain that this is the same issue as with Extrautil2's redstone clock. I'll be investigating this later today.

**Comment by Aaron1011** [comment]
I can't reproduce this with the latest SpongeForge. Can you post a screenshot of how the timer block is wired up in the world?

**Comment by Orcinuss** [comment]
Unfortunately the red stone that was causing this has been removed.
