### ISSUE TITLE
Unable to generate crash report correctly

### ISSUE THREAD

**Issue by Orcinuss** [SpongePowered/SpongeForge#1100]
Not sure about this one. Based on the block being ticked it has something to do with refined storage but im going to guess that the actual error should come out differently and has something to due wit sponge itself.

Crash report: http://pastebin.com/ygfhrhbg

**Comment by gabizou** [comment]
Could you link a full startup log? There might be a failed mixin for whatever reason.

**Comment by Orcinuss** [comment]
I don't have the startup logs from the time of the crash. I do have the log from the time of the crash but that only has stuff from when the server was online till it crashes. 
Here is the latest startup log of the server: http://paste.ubuntu.com/23609447/

**Comment by phit** [comment]
Closing this for now, as this issue is almost a year old and there were no new reports. See also #1103
