### ISSUE TITLE
endportal with disabled end crashes server and/or collide portal 

### ISSUE THREAD

**Issue by johnfriedrich** [SpongePowered/SpongeForge#1101]
5.1.0-BETA-1971
An end portal is involved. (End is disabled in world.conf)
Server crashed, not sure what the player did.
minecraft log:
https://pastebin.com/Vi7xjCi2
minecraft crash log:
https://pastebin.com/nANjwgQz

In addition to that, server lags ridiculously, if you step into an endportal if end is disabled.
https://timings.aikar.co/v2/?id=670c5980de6e47be8f7c59d6271e4b8a&start=1481397690&end=1481398027

https://pastebin.com/mkhnDyvZ
Place three players in a end portal and the server crashes

**Comment by johnfriedrich** [comment]
Yep, throwing items under some cirumstances in endportals will crash the server.

**Comment by bloodmc** [comment]
@i9hdkill Does this still happen with latest builds?

**Comment by johnfriedrich** [comment]
No actual crash so far, but this was random at that time and requires many player that are testing endportals.
If you deactive the end, and throw an item or let falling blocks get into the portal, you can easily crash the server because of the message spam:
http://prntscr.com/eqkchs

SF 2262

Edit: After 2 minutes the server crashes with this report:
https://pastebin.com/RcEvbgDi
Guess just too many items/entities that the server is trying to teleport to a disabled world.
