### ISSUE TITLE
Actually Additions Mob drops not dropping

### ISSUE THREAD

**Issue by Mohron** [SpongePowered/SpongeForge#1102]
SF: spongeforge-1.10.2-2171-5.1.0-BETA-1976.jar
AA: ActuallyAdditions-1.10.2-r88.jar via DW20 1.1.3

This is related to #983 and #857. Actually additions bat wings and solidified xp still do not drop even with the fixes for the other drops involved in those issues. The items drop in without SF with no issues.

**Comment by bloodmc** [comment]
@Aaron1011 please look into this.

**Comment by Aaron1011** [comment]
The mod author has updated it, but only for 1.11. At the moment, I don't think there's much you can do except for upgrading to 1.11. :/

@bloodmc ^

**Comment by Mohron** [comment]
Fixed via my fork https://github.com/Rebelcraft/ActuallyAdditions/tree/spongeforge for anyone using DW20 v1.1.3

**Comment by Mohron** [comment]
@Aaron1011 Thanks for the help!
