### ISSUE TITLE
Villager causing issue with sponge.

### ISSUE THREAD

**Issue by curscascis** [SpongePowered/SpongeForge#1104]
Upon a village being generated we are getting this issue, this is on a new map.
We've attempted to disable different mods to try to find the source at no avail.

[crash-2016-12-12_00.17.34-server.txt](https://github.com/SpongePowered/SpongeForge/files/645168/crash-2016-12-12_00.17.34-server.txt)

ModPack
http://www.technicpack.net/modpack/rosecraft-2.901656

**Comment by curscascis** [comment]
After some more trying things, setting Immersive Engineering to get rid of it's villagers seemed to cause the problem, but a problem still exists with the villagers being loaded and sponge crashing upon verifying them, not sure where the problem is exactly, also reporting the bug to IE dev.

**Comment by curscascis** [comment]
I take that back, after some time we are still seeing issues but no crashing, which is good.

here is our fml log, the errors are close to the end, maybe this will help.
[fml-server-latest.txt](https://github.com/SpongePowered/SpongeForge/files/645194/fml-server-latest.txt)

**Comment by Aaron1011** [comment]
@curscascis: Can you see if this issue occurs with only Immersive Engineering, on a freshly-created world?

**Comment by curscascis** [comment]
Good Morning,
So we actually tried it out, and the issues started occurring again and we did get crash an hour o so later. So it seems as though it is not immersive engineering. just villagers of any mod that was removed.

On a freshly created world we have yet to see any errors. I'm not sure but My assumption is that sponge is just erroring out instead of handling it and either removing the entity or changing it's value. I am not sure of how the internals work.

doing things like setting Forge to delete erroring entities and spam buthchering only seemed to delay the crash.

**Comment by Aaron1011** [comment]
> So it seems as though it is not immersive engineering. just villagers of any mod that was removed.

Yes, that would definitely be causing it.

@gabizo: What do you think is the best way to handle this? Should we log a warning, and revert the villager back to a default profession?

**Comment by gabizou** [comment]
Closing in favor of #1190's resolution. Will be implementing something more descriptive and productive in terms of a warning/error.
