### ISSUE TITLE
weird bug with placing blocks

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1107]
Im found some areas on the map, where cannot place blocks, for example 2x1x1 cuboid. But can place for example torch, fence, wall. During some tests I tried using piston at adjacent area. When piston move to "bug block"  looks like its unbugged and can place block here. No errors in the console.

How i can debug what is wrong with these blocks? (some nbt, tile entity or... )

**Comment by johnfriedrich** [comment]
Got this problem today:
SF: 2003
Forge: 2171

We threw a dmg potion and killed some invisible chickens.
You can push these invisible entities(and already killed entities) with pistons but cannot remove them entirely.
Affected region file:
https://www.dropbox.com/s/0df2yp35rhgnr2f/r.-3.3.mca?dl=0
affected block positions:
-1267--1268 68-70 1884-1885

roughly a 3x2x2 area

source of this?
https://github.com/SpongePowered/SpongeForge/issues/1111

Just had a rough look at the region file, there are chickens in it.(but we killed them?!)
I think that is the chicken:
http://prntscr.com/dmos1n

**Comment by ghost** [comment]
It looks like bug still here. Or fixes only newly placed entities?

**Comment by ktole1999** [comment]
mo'creatures in your pack? if so then remove it. problem solved.

**Comment by ghost** [comment]
No MoC in my pack.
