### ISSUE TITLE
Common occurrence where a player's client will be minutes behind but their information is still processed for other players.

### ISSUE THREAD

**Issue by axieum** [SpongePowered/SpongeForge#1108]
Version: spongeforge-1.10.2-2171-5.1.0-BETA-1992

Running HermitPack: 1.5.1

A player will login, and not see other players messages, block placements etc.. for up to 2 minutes.
However, other players can still see their activity. Usually (to what I've seen) only affects one player that is online. Re-logging and restarting does not fix this. I thought my friend was going insane, until I experienced it this morning.

(psst. also Solidified Experience and Dimlet Parcels aren't dropping from mobs/endermen).

**Comment by Zidane** [comment]
Does removing Sponge fix the issue?

**Comment by axieum** [comment]
No. It has just been noticed by the maintainer of HermitPack series (Xisumavoid). Hopefully they fix that soon.

However, we've disabled sponge for now, as there are duplicating entities and solidified experience/dimlet parcels were not dropping from mobs.
