### ISSUE TITLE
Crashes After Generating Spawn on Server Start

### ISSUE THREAD

**Issue by jelaw21** [SpongePowered/SpongeForge#1109]
I have included the crash report, please assist?

[crash-2016-12-14_11.30.04-server.txt](https://github.com/SpongePowered/SpongeForge/files/652270/crash-2016-12-14_11.30.04-server.txt)

**Comment by Zidane** [comment]
We need the full server log.

**Comment by jelaw21** [comment]
The issue is tied to another. Spongeforge crashes server any time a new dimension is added. These mods I have tried and all have caused server crash trying to load other dimensions.  AbbyssalCraft, RandomThings, and Futurepack.

**Comment by bloodmc** [comment]
Fixed in latest. SpongeCommon commit can be found here
https://github.com/SpongePowered/SpongeCommon/commit/dbf3c828d24cba094ef118b6e5aa1086a3db2b17
