### ISSUE TITLE
Silent Caching Entity Error Causing TPS to Drop Below 5

### ISSUE THREAD

**Issue by Orcinuss** [SpongePowered/SpongeForge#1110]
There is a silent caching entity error that gets spammed to console over and over again. 

For some reason when this is happening the server's TPS drops below 5. I don't know what exactly is causing the error but the server always has 20 TPS unless this error is occurring. This can go on for hours before the server restarts. Sometimes the update time will reach into the upper hundreds and will usually cause the server ping to time out and force multi-craft to restart the server. 

Console Log: http://pastebin.com/kxyJGhnq

**Comment by Aaron1011** [comment]
Make sure you're running the very latest SpongeForge.

**Comment by Orcinuss** [comment]
This is still happening on the latest stable SpongeForge v1992.

**Comment by Zidane** [comment]
Update to latest. if still an issue, re-open with more information.
