### ISSUE TITLE
[1.10.2]Entities stop spawning after a period of time

### ISSUE THREAD

**Issue by johnfriedrich** [SpongePowered/SpongeForge#1111]
Forge 2171
Sponge: 1986+ Not sure, using specialversion from blood
Pixelmon Beta 12

After starting the server everything is fine, entities are spawning fine. But after 1-4 hours, it depends on the entitiy type, entities will stop spawning.
Timings with an uptime of 45 minutes and 25 players online:
https://timings.aikar.co/v2/?id=38777fef8dd84c74bbd143701d8d2970
~1500 entities

Timings with a uptime of 10 hours and 25 players online:
https://timings.aikar.co/v2/?id=6dbb905451cc416f8fa948e7285dfbf7
~1500 entities

Fine? No. If you fly around and tp to different players, you cannot find a pokemon, neither villagers are spawning in farms and so on. Players complain about entities stop spawning completely. There is nothing anymore. Not a single pokemon or villager spawning.

Seems like after killing/catching pokemon/entities stay as a ghost entity or similiar or are not correctly unregistered?

To "fix" this problem, we are now restarting the server every 6 hours.

Guess this is very hard to debug, but it's definetely an issue.

**Comment by FiveEYZ** [comment]
i most say, after reading this issue we have had this exact same thing happening to us

its happening so slow u barely notice it

**Comment by inklit** [comment]
It would definitely be helpful to know precisely which test build you are using from blood.

I am also using a test build and my server has been online for 4 days and entities spawn just fine.

**Comment by bloodmc** [comment]
Please do not create tickets for test builds. Update to latest stable and if it occurs with that then i'll reopen this ticket.
