### ISSUE TITLE
[1.10.2] Error executing task

### ISSUE THREAD

**Issue by FiveEYZ** [SpongePowered/SpongeForge#1112]
I keep seeing this error every now and then.
[latest.log](https://gist.github.com/FiveEYZ/a2492d6f1cb5aab2343839157d0d039d)

Here is the fml log if needed:
[fml-server-latest.log](https://gist.github.com/FiveEYZ/f4aad350f14a996cedb0afbf9791ae5b)

Using:
spongeforge-1.10.2-2171-5.1.0-BETA-1992
forge-1.10.2-12.18.3.2185-universal
Direwolf20 1.10 1.1.4

**Comment by Orcinuss** [comment]
I am also getting this error.

**Comment by FiveEYZ** [comment]
Bit more info on this error:

[Error executing task](https://gist.github.com/FiveEYZ/7cfb5ed4a1adb39c9444d9011b90b48a)

also updated to: 
spongeforge-1.10.2-2171-5.1.0-BETA-2009
Direwolf20 1.10 1.2.1

**Comment by Aaron1011** [comment]
This should be fixed in the latest SpongeForge: https://github.com/SpongePowered/SpongeCommon/compare/ead0600c1c30df0725967c0c3ab9a2fe0af4d297...8fa91261754b256451e5acc6327a4bbe31878959
