### ISSUE TITLE
How to go about finding FakePlayer UUID

### ISSUE THREAD

**Issue by alicheek** [SpongePowered/SpongeForge#1114]
Hey there might be a silly question but how do we go about finding the fake players to add to the list in the sponge configs?

**Comment by Zidane** [comment]
Consult the mod author's documentation (or ask them directly). You'll likely get even more replies with more options on our forums (https://spongepowered.org) as the issue tracker for SpongeForge is for issues with the product.

**Comment by inklit** [comment]
Generally if this is a problem, your server will likely be spamming lookups for that UUID. This makes it quite obvious that you need to add it to the fake player list.
