### ISSUE TITLE
Spongeforge conflict with other mod?

### ISSUE THREAD

**Issue by Xiaminou** [SpongePowered/SpongeForge#1115]
I thought I'd try spongeforge on my server with my 160 mods modpack today. But it looks like there's still conflicts with other mods, however I can't tell which.

Here is the log: [fml-server-3.txt](https://github.com/SpongePowered/SpongeForge/files/657790/fml-server-3.txt)

Minecraft: 1.10.2
Forge: 2185
Mods: [list.txt](https://github.com/SpongePowered/SpongeForge/files/657792/list.txt)

**Comment by FiveEYZ** [comment]
try remove appliedenergistics2-rv4-alpha-9

**Comment by Xiaminou** [comment]
Confirmed, it crashes with AE2 only. Yeah, looks like they're already working on it.
