### ISSUE TITLE
Can't load multiple extra worlds (Potentially due to UUID being null)

### ISSUE THREAD

**Issue by me4502** [SpongePowered/SpongeForge#1116]
http://pastebin.com/uw6Gx7WH

This error occurs when adding a second extra world to SpongeForge. After checking the line it occurs on, it appears that's where it puts the UUID into a Map. It therefore appears that the UUIDs of the worlds aren't being saved.

**Comment by bloodmc** [comment]
@me4502 Reopen this if you can still reproduce with latest.
