### ISSUE TITLE
[1.10] A dimension-adding mod changing its mod ID but not dimension ID causes a crash on load

### ISSUE THREAD

**Issue by exaskye** [SpongePowered/SpongeForge#1117]
See: elytra/Correlated#54

It seems Sponge remembers the old modid associated with a dimension and crashes if the modid has changed. (The fact the message is "derp" suggests to me this was assumed to never be the case.)

I recently renamed my mod from `correlatedpotentialistics` to `correlated` and got this issue report shortly after. The dimension imports cleanly on regular Forge.

Is there a quick fix I can do on my end? It doesn't seem like it to me, but I figure it's worth asking.

In my particular case deleting the dimension is fine, as the dungeon isn't finished yet.

**Comment by bloodmc** [comment]
Fixed in latest. SpongeCommon commit can be found here
https://github.com/SpongePowered/SpongeCommon/commit/dbf3c828d24cba094ef118b6e5aa1086a3db2b17
