### ISSUE TITLE
[1.10.2] #2171 - UTF8 Characters creeping out

### ISSUE THREAD

**Issue by Tahul** [SpongePowered/SpongeForge#1119]
https://yaelguilloux.fr/upload/java_2016-12-17_18-37-29.png
https://yaelguilloux.fr/upload/idea_2016-12-17_18-39-06.png

Those two screenshots are 1/ The result ingame, 2/ the method used to send the messages.

Thanks a lot for your help.

**Comment by Tahul** [comment]
Quick fix is anyone has the same issue, using Java Unicodes.

http://itpro.cz/juniconv/ this converter can help you.

**Comment by ST-DDT** [comment]
First of all make sure that your IDE/build system uses UTF-8 encoding.

In eclipse you can set this up under options -> workbench.
In maven there is a property for it.

````xml
<properties>
	<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
	<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
</properties>
````

If you use a text file to store these messages make sure to load them properly (define the encoding).

````java
new InputStreamReader(inputStream, "UTF-8");
````

or use a JSON parser which uses UTF-8 by default.

Outsourcing the messages in a separate text files, simplifies your code (improves readability), greatly reduces issues like encoding an special character escaping and also allows easier multi language support.

**Check our [docs](https://docs.spongepowered.org/) which cover most of the `Text` features.**

[Text Serialization](https://docs.spongepowered.org/master/en/plugin/text/representations/index.html)
and maybe also
[Text Templates](https://docs.spongepowered.org/master/en/plugin/text/templates.html)

**Comment by stephan-gh** [comment]
@ST-DDT explained the solution for this problem. In any case, this is not something we can fix in SpongeForge (needs to be fixed in the plugin itself).
