### ISSUE TITLE
[FML]: No types have been added to Biome minecraft:

### ISSUE THREAD

**Issue by ziceptor** [SpongePowered/SpongeForge#1120]
http://pastebin.com/Qz1W1zWR

**Comment by inklit** [comment]
mods? version? more details needed

**Comment by kashike** [comment]
Full server log please.

**Comment by ziceptor** [comment]
Sorry. @kashike
```
forge-1.11-13.19.0.2178-universal.jar
spongeforge-1.11-2178-6.0.0-BETA-1997.jar
```
[fml-server-latest.log](http://paste.ubuntu.com/23648586/)

**Comment by kashike** [comment]
This is a warning from Forge, you can try using a newer Forge version - but make a backup incase something breaks.

**Comment by Zidane** [comment]
Closing due to lack of feedback and isn't a Sponge bug.
