### ISSUE TITLE
Implementation : Boss death sound radius 

### ISSUE THREAD

**Issue by alicheek** [SpongePowered/SpongeForge#1123]
Just a request, something that spigot is implemented and would be great to see this also implemented in sponge, its nothing major but ive had quite a few people complaining about the sounds due to other players having wither mob grinding systems and such.

dragon-death-sound-radius
Default: 0
Type: Integer
Description: Limit the sound of the dragon's death.

wither-spawn-sound-radius
Default: 0
Type: Integer
Description: Limit the sound of spawning withers.

Thanks again for the great software!

alicheek

**Comment by axle2005** [comment]
If I recall, as we had the issue on our server... these are client side things. A viable option is to make a resource pack changing them.

**Comment by alicheek** [comment]
Well yes you can turn off mob sounds but that means you also cant hear any mobs at all which is a bit unproductive. As stated spigot have implemented a server wide setting for this.

**Comment by ProsperCraft** [comment]
We made a serverside mod that stopped the boss sounds from being sent to the client in 1.7, we were planning to update it to 1.10.2 but it has not happened yet.

**Comment by BytesByBytes** [comment]
I think this would be an awesome idea i have had to put a stop to automated wither killers due to a couple players constantly spawning them and players just getting the shits with the sound. Extra Utilities used to have the option to disable wither sounds in 1.7.`10 but has not been included in the 1.10 version

**Comment by Eufranio** [comment]
Lightning/smite are heard in all the world(s) too.

**Comment by Time6628** [comment]
Use this mod on the client, https://minecraft.curseforge.com/projects/bad-wither-no-cookie
ExtraUtils implemented a feature in this to disable boss sounds in all worlds in 1.7.10, so he will probably do it again.

**Comment by ProsperCraft** [comment]
One problem with that mod is that if you add it serverside, it requires that it be installed on the client as well, I did ping him requesting that he change that, not sure if he did yet.

**Comment by Time6628** [comment]
It wouldn't work serverside, because it blocks the sound on the client side.

**Comment by ryantheleach** [comment]
I'd sooner see this implementable as a plugin, however it appears that there isn't any sound / effect events.

https://github.com/SpongePowered/SpongeAPI/issues/1562

**Comment by phit** [comment]
@limbo-app move to sc

**Comment by phit** [comment]
@limbo-app move to sc

**Comment by kashike** [comment]
@limbo-app move to sc

**Comment by gabizou** [comment]
@limbo-app move to sf

**Comment by gabizou** [comment]
@limbo-app move to sc

**Comment by limbo-app** [comment]
Hey @alicheek! I've moved your issue to [SpongePowered/SpongeCommon#1717](https://github.com/SpongePowered/SpongeCommon/issues/1717).
