### ISSUE TITLE
[1.10.2] SpongeForge & Applied Energistics 2 hate each other

### ISSUE THREAD

**Issue by hugeblank** [SpongePowered/SpongeForge#1124]
The issue:
Applied Energistics 2  came out for 1.10.2 not too long ago. In a rush of excitment, I went to go install it to my server. Upon restart, I got a very... interesting response by sponge. [Here](http://pastebin.com/yHzr5Hv6) is the log with -DfmldebugExit set to true. I plan on reporting the same issue to the mod developers as well.
To recreate:
1: Get a forge server, and slap spongeforge, and AE2 in it.
2: run the server, and witness the error.
Versions:
spongeforge-1.10.2-2171-5.1.0-BETA-2000
appliedenergistics2-rv4-alpha-9
forge-1.10.2-12.18.3.2185

**Comment by bookerthegeek** [comment]
Before you do that you really should learn how to use the search function.

**Comment by hugeblank** [comment]
Updated link so it actually would work :P sorry about that.
and Added version info because they probably would be helpful

**Comment by Lemmmy** [comment]
@hugeblank please view issue #966.

**Comment by inklit** [comment]
AE2 is incompatible with Sponge. https://github.com/Stonebound/Applied-Energistics-2/#about for a fork of it that will work.

**Comment by hugeblank** [comment]
Ah. thanks for all the information.
