### ISSUE TITLE
[1.10.2] Blood Magic Rituals

### ISSUE THREAD

**Issue by FiveEYZ** [SpongePowered/SpongeForge#1125]
the rituals no longer works when adding SF into the mix

here is the log if needed:
[fml-server-latest.log](https://gist.github.com/FiveEYZ/8e2cb2c16ebe009f3691e1c5c5bb2b6d)

BloodMagic-1.9.4-2.1.0-68
Guide-API-1.10.2-2.0.2-45

spongeforge-1.10.2-2171-5.1.0-BETA-2000
forge-1.10.2-12.18.3.2185-universal

**Comment by Aaron1011** [comment]
@FiveEYZ: Can you describe a specific ritual that no longer works, along with detailed steps to reproduce it?

**Comment by FiveEYZ** [comment]
Can you describe a specific ritual that no longer works:
all of them

In creative take a Transcendent Blood Orb and right click 
(to make sure there is life essence to start a ritual)
because if u don't have life essence to start the ritual then nausea will be given

what i did was to start a server without sponge (just to check it wasnt a mod bug) 
1. place a master ritual stone and Ritual Stone of Water like this picture
https://gyazo.com/25733a388440e628c2ccee99e66d9e51
(I tried Ritual Stone of Water/Fire/Air)

2. use a Ritual Diviner on the middle stone 
3. use a Activation Crystal
Message will show that the ritual have started 
https://gyazo.com/e6f9e9ebe1c8f77252dc7b42d1d1eee7

4. if the ritual was successful then a water source block will spawn on the middle block

but when sponge is added the Life Essence to start the ritual will be taken but the ritual never starts
and rituals started before sponge was added will stop working

hope this helps

**Comment by ProsperCraft** [comment]
We are having the same issue @bloodmc since we updated to build 2000 with the tileentity activation.

**Comment by FiveEYZ** [comment]
yes but i did all tests with `tileentity-activation=false` but that build might effect is anyway somehow, gonna test older builds

Edit:
Rituals are working using spongeforge-1.10.2-2171-5.1.0-BETA-1998

**Comment by Aaron1011** [comment]
@FiveEYZ: I'm unable to reproduce this on the latest SpongeForge 1.10 (singleplayer). Are you running any other mods?

**Comment by FiveEYZ** [comment]
no, no other mods and i never even thought of trying it singleplayer

**Comment by Aaron1011** [comment]
@FiveEYZ: Can you test in singeplayer, with a fresh Sponge config folder?

**Comment by FiveEYZ** [comment]
yes it works in "singleplayer" but i have to click the middle stone 2 times before it starts, i dont really follow why u wanted me to try it when we have the problem on a server.
