### ISSUE TITLE
IllegalAccessError after Updating

### ISSUE THREAD

**Issue by john01dav** [SpongePowered/SpongeForge#1130]
Hello,

After updating to Sponge 5.1.0-BETA-2000 from 5.1.0.BETA-1983, my server crashed with the attached bug report when the chunks surrounding spawn were loaded. I am using the Direwolf20 1.10 pack on its latest release version. Please let me know if you need more information :)

[crash-2016-12-21_00.26.16-server.txt](https://github.com/SpongePowered/SpongeForge/files/665034/crash-2016-12-21_00.26.16-server.txt)

**Comment by Aaron1011** [comment]
@john01dav: This should be fixed in the latest SpongeForge.
