### ISSUE TITLE
[1.10.2] Sponge handling lava in an... interesting way

### ISSUE THREAD

**Issue by hugeblank** [SpongePowered/SpongeForge#1131]
Forge: 12.12.3.2185
Sponge: 2005
Issue: Flowing Lava refuses to flow after it gets itself into a certain state, and acts as a source block. This may not be the BEST example but the attached photo is one.
![2016-12-20_23 18 35](https://cloud.githubusercontent.com/assets/16393543/21382170/41b8aa88-c714-11e6-835f-f2be76547093.png)

**Comment by johnfriedrich** [comment]
Not sure why sponge does that by default, but there is a config option that restores vanilla lava behaviour.

**Comment by hugeblank** [comment]
Oh...odd. Thank you very much! 

I'm going to keep this open, just to poke the sponge devs and see if they could set this to false by default.

**Comment by Deamon5550** [comment]
That is the vanilla behavior, the config option makes it decay like vanilla `water`.

**Comment by hugeblank** [comment]
@Deamon5550 Can I ask why it works like vanilla lava when I changed that config option then?

Nowhere in the vanilla behavior does flowing lava behave like a source block.

**Comment by Deamon5550** [comment]
Can you pick it up with a bucket? otherwise its not that its acting as a source block but that it does not go away immediately which is the vanilla behaviour.

**Comment by inklit** [comment]
Are you using any plugins that may be affecting liquid movement? A protection plugin maybe?
Did you try with just SpongeForge, and did you try with just Forge?

**Comment by hugeblank** [comment]
@Deamon5550 
1. No I can't pick it up with a bucket
2. I am saying it acts like a source block as in it will NEVER go away. It stays there for as long as you are willing to stay and stare at it... and then some.

@inklit 
I didn't think that anything I installed would affect that, but apparently it did.

So with that said, bug fixed!
