### ISSUE TITLE
Issue with using Q to drop items

### ISSUE THREAD

**Issue by jelaw21** [SpongePowered/SpongeForge#1133]
Running:
TombManyGraves: 1.10.2-2.1.14
spongeforge - 1.10.2-2171-...-2003
Forge - 1.10.2-12.18.2.2171

After a player dies, they are given a deathlist. However, even with config are set properly, the deathlist does not drop when player Q's from hotbar. IF a player SHIFT-Q's the deathlist to drop it, it combines their inventory into the deathlist and deletes the actual items from the inventory. Replicated 3 times with same results.

Filled my inventory with planks, used /kill retrieved all the planks, Shift-Q'd the death list, got another death list listing all the planks and the planks were gone from inventory.

Contacting TombmanyGraves and they say its a spongeforge issue?

**Comment by Aaron1011** [comment]
This will require re-wroking how we fire Forge's `ItemTossEvent` - we currently restore the item to the inventory if it's cancelled, which isn't the behavior in Forge.

**Comment by JonoColwell** [comment]
Hi, would like to note that this is ongoing, death lists in 1.10 still remain in inventory despite being dropped.

**Comment by bloodmc** [comment]
I'm unable to reproduce this issue with latest SF builds.
