### ISSUE TITLE
Console Spam from EnderIO NetworkPowerManager: Exceptions

### ISSUE THREAD

**Issue by BytesByBytes** [SpongePowered/SpongeForge#1135]
Major Console Spam from EnderIO 

https://gist.github.com/Bubble0seven/7065e8dea8b1136a6d809aebf6160dd1

We reverted back to spongeforge-1.10.2-2171-5.1.0-BETA-1992 from spongeforge-1.10.2-2171-5.1.0-BETA-2005 and the spam has stopped. We tried spongeforge-1.10.2-2171-5.1.0-BETA-2000 before and was getting issues with console spam and certain inconsistencies so we thought updating to spongeforge-1.10.2-2171-5.1.0-BETA-2005 would fix it but it has not helped 

Sponge Version: spongeforge-1.10.2-2171-5.1.0-BETA-2005
Forge Version 12.18.3.2185

**Comment by Aaron1011** [comment]
@

**Comment by Aaron1011** [comment]
@Bubble0seven: Does this issue occur with the latest SpongeForge?

**Comment by ronaldburns** [comment]
Running 2202. Get the same errors.

**Comment by BytesByBytes** [comment]
Sorry for such a late reply i am starting to think  its only on a certain version of EnderIO as it only occurs on one server not all them. 

There is a big update coming for enderio so i would like to see if it persists or not as i am not sure whether its a sponge issue or enderio .

I will keep you informed once the update has occurd

To answer your question i have tested it on multiple versions including the most current at the time of the post. I have not updated to the latest since its built against forge 2202 and we are running forge version 2185 still

**Comment by phit** [comment]
This is no longer an issue as far as I know, at least I haven't seen this on my Beyond server. Also pretty sure this was an EnderIO issue.
