### ISSUE TITLE
[1.10.2] Piston & Armor Stand Dupes

### ISSUE THREAD

**Issue by GershonR** [SpongePowered/SpongeForge#1136]
I'm not entirely sure how these are being done, i'm still trying to catch a person attempting to do this, I definitely know that with armour stands you are able to duplicate armor pieces and with pistons you are able to duplicate blocks.

For the piston dupe I believe it's done like in the older versions of Minecraft like:
https://www.youtube.com/watch?v=gkoYCiQ3-hs

I'll try to update the ticket when I replace the dupe.

API 6
SpongeForge 1.10.2 1902
Forge 12.18.2.2151

**Comment by GershonR** [comment]
Here is a video of a hopper dupe:
https://vid.me/NKVc

**Comment by inklit** [comment]
Update Sponge; pretty sure the ~piston~ hopper dupe was already fixed.

**Comment by GershonR** [comment]
I'm currently on the latest Sponge for API 6 1.10.2, i'm waiting for some plugins to support API 5 before I can go back to API5 for 1.10.2

**Comment by Deamon5550** [comment]
The only versions of api 6 for 1.10.2 are compatible with the 5.1.0 builds for 1.10.2 so there should be nothing stopping you from using the latest.

**Comment by GershonR** [comment]
Yeah but some plugins crash the server for the API5 1.10.2 builds

**Comment by gabizou** [comment]
Then those plugins need to be for API 6 which is only updated for 1.11, do NOT use the API 6 builds of sponge for 1.10.2.

**Comment by GershonR** [comment]
Alright but are these dupes patched in the latest versions of API 5?

**Comment by gabizou** [comment]
It's nothing to do with whether it's against API 5 or 6, the dupes would be in the internal systems of the server implementation/sponge's implementation, which is API agnostic. The later builds for 1.10.2 are only built against API 5. 1.11.x builds are based on API 6. The internals that cover the block physics of this should be in both implementations (as those systems haven't changed all that much, except with something new in 1.11, but that's besides the point). It matters currently whether it's on the latest 1.10.2 builds, or on 1.11 builds.

**Comment by bloodmc** [comment]
This does not occur with latest Sponge builds.
