### ISSUE TITLE
[1.10.2] Can you update to forge 2185

### ISSUE THREAD

**Issue by BakermanLP** [SpongePowered/SpongeForge#1137]
Hello,

can you please update Spongeforge for minecraft 1.10.2 to forge 2185?

I think that will be the last release of forge for 1.10.2 and some mods have dependencies to this forge version.

Thank you

Michael (aka BakermanLP)

**Comment by axle2005** [comment]
There is nothing stopping you from updating to that forge version. We already run it on our servers alongside Build 1973 of SpongeForge.

**Comment by BakermanLP** [comment]
Sorry, but latest Build for Minecraft 1.10.2 is 5.1.0-BETA-2006 and the next row tells me, that it is compatible to forge 2177 and not 2185. In the documentation to spongeforge it is strongly recommended to use the exact version of forge. That's why I ask.

**Comment by gabizou** [comment]
Build 2006 still works fine with 2185.
