### ISSUE TITLE
[1.10.2] Abnormalities in weather causing gameplay issues

### ISSUE THREAD

**Issue by hugeblank** [SpongePowered/SpongeForge#1138]
I run a 1.10.2 modded survival server, and have come across this abnormality with the in-game weather.

**The issue:**
 For starters, it is either clear or thundering NEVER just rain. This is relatively annoying due to the fact that mobs spawn in thunderstorms, making it almost impossible to go anywhere without having to fight off mobs. The second issue is that when there is a thunderstorm, lightning is extremely common, unlike typical minecraft. In 1.9 I believe they added [trapped skeleton horses](http://minecraft.gamepedia.com/Horse#Skeleton_trap) being created when lightning strikes. These horses are EXTREMELY inconvenient to a starting player, and I've already seen accounts of players rage quitting due to the exorbitant amount of trapped horses.

**Proof:**
Before I began, I ran spongeforge, and ONLY spongeforge.
And now, to start, I set the time to 6000, 12:00. Then I set doDaylightCycle to false.
Then, I set up a small rig with a daylight sensor, 15 pieces of redstone, and then torches placed at each point where the sensor would lower its power to when the weather was clear, rainy, and thundering. Then by those torches I placed a dropper that fed into a chest. The result was a setup that, when the weather got to a certain point, the redstone torch would turn on, putting an item into the dropper. The end result was the control chest being the clear weather, when it began raining or thundering, It would drop an item into the 'Clear' chest, and then whatever weather it was to end up at (rain, or thunder). To find the amount of times it thundered, it was as simple as counting the items in the chest. To find the amount of times it rained, you took the amount of times it rained, subtracted by the amount in the control/clear chest. (just because of how it was set up). 

I spent 4-ish hours AFK watching oodles of youtube videos, letting my player idle next to the contraption. Here are my results:

Items in chests:
Clear weather: 6
Rainy: 6
Thunder: 6

So, it would total up to be:
Clear: 6
Rainy: 0
Thunder: 6

And the results make sense. I found just in my vicinity, 7 trap horses. Had I spent more time looking, I am more than willing to bet there was more. I'll leave a link [here](http://imgur.com/gallery/5Kyhn) of an imgur album, so you can see screenshots of my contraptions, and its results.

**Possible errors:**
I've already set this bug report like a lab report, so what more do I have to lose :stuck_out_tongue:

- It could very well have rained, and then started thundering, and then become clear, and you just weren't there to observe it, or vice versa (thundered, and then rained)
This argument is true, but seeing as most scenarios it just rains and then stops, I think there would have been AT LEAST one instance in the 4 hours I spent, where it rained, and then became clear.

**My conclusion:**
sponge is bugged :/ 
I'm convinced that there is something wrong with sponge itself that is not allowing it to rain on my server. I have personally witnessed the:
1: lack of just plain rain
2: the dreaded quintuple lightning strike, which is not pleasant to headphone users. (cracka-lacka-lacka-lacka-lacka boom.)

**Server details:**
MC: 1.10.2
SpongeForge: 2005
Forge: 12.18.3.2185

side note, this has probably been one of my favorite issues to report. Tinkering with redstone has been one of my favorite things to do, and even making this setup an 8 year old could do, was fun.

**Comment by Zidane** [comment]
Quite appreciated and a good read above. This is something that @bloodmc has sworn on his firstborn is occurring and we've now assigned @Aaron1011 to take a look and see just what the heck is going on.

**Comment by BytesByBytes** [comment]
I would have to concur with this my server is simply plagued with these trapped skeleton horses i have counted roughly 15 to 21 of these in 20 block radius of where i am standing.  I always thought this was a bit much or it was just because we have our server set on hard but in saying that due to the high number of these trapped skeleton horses we do not have many other normal mobs spawning such as Zombies or spiders etc. 

Screenshot of roughly 8 in one chunk daylight [Image](http://imgur.com/IOM1Ovj)

I dont think i can add anything more to this other than to confirm that i also am having the same issues

**Comment by inklit** [comment]
I've seen rain on my server........but a little too often than what seems normal. It always seems to be raining.
We haven't had a map reset ever since our beginning days so we are on Day 12K~.
Skeleton traps are incredibly populous but likely not related to weather.

**Comment by hugeblank** [comment]
Haha! Glad this 
1: isn't just me
2: my little experiment actually prove something.

If you can figure this out, you are a hero to all servers @Aaron1011 😂

**Comment by hugeblank** [comment]
Along with that, if people have noticed this before me, why hasn't anyone reported it like I did? Especially after the 1.9 update, it surprises me that nobody questioned 7 horses in one chunk 😂

That being said, I'm not blaming anyone for failing to catch an issue, I'm just shocked that I was the first.

> This is something that @bloodmc has sworn on his firstborn is occurring

Consider your firstborn saved.

**Comment by lurr** [comment]
I can also confirm that there is _excessive_ amounts of skeleton horses. 😐

**Comment by codeHusky** [comment]
I **also** can confirm that the amount of skeleton horses that spawn is very, very irritating. I had to download a plugin just so that I could develop plugins in peace.

**Comment by Tencao** [comment]
I can confirm this too. Many players on my server have been complaining not so much about the weather, but the absolute insane amount of skeleton horses.

**Comment by Aaron1011** [comment]
I've identified the cause of the lack of plain rain (though I'm unsure how this related to the excessive lightning/skeleton horses).

Whenever Sponge detects a weather change, it fires a `ChangeWorldWeatherEvent`. The problem is that this event only specifies one duration, while internally there are two - the thunder duration and the rain duration.

In Vanilla, these two numbers are set individually, with the stipulation that the thunder duration is less than the rain duration, to prevent thunder without rain. However, Sponge always sets these to the same value - the one from the event. This prevents plain rain from ever occuring, as it will always start or end at the same time as thunder does.

**Comment by hugeblank** [comment]
@Aaron1011 Yay! it's good to hear that the issue has at least been found. 

Another question for ya:
In vanilla the maximum amount of time before weather will get changed is 10 days (200 minutes). I'm not sure what the minimum is, but has sponge changed that maximum at all?

**Comment by hugeblank** [comment]
Haha Nice!

**Comment by hugeblank** [comment]
I didn't want to bother creating another issue because I knew I created this one, but this issue has arisen again in the lastest versions of sponge. Just thought I'd give you guys a heads up.

EDIT: I’ll shut up now, I thought the issue I reported here was something else, my bad.
