### ISSUE TITLE
lag on chunk autosave

### ISSUE THREAD

**Issue by vaniron** [SpongePowered/SpongeForge#1139]
Hello guys, i got new map pregenerated with nucleus on my pixelmon server but still got some lag when autosaving chunks.. quite strange?

Autosave set to 5 minutes (sponge config): http://pastebin.com/raw/1BPQBrWi
Lag times: http://prntscr.com/dnetol <= per 5 minutes as autosave happens?
Pixelmon config: http://pastebin.com/raw/9dNDDK4U
Timings: https://timings.aikar.co/v2/?id=7f23bb9ca3f44bfc892c9c366ca011f8&section=lag

Any ideas on this?
Its on dedicated machine so if you need more info just let me know what should i provide..

**Comment by bloodmc** [comment]
Update to latest SpongeForge build and make sure to enable "structure-saving" and turn off mineshaft.
