### ISSUE TITLE
server won't boot anymore?

### ISSUE THREAD

**Issue by TheMrCaveman** [SpongePowered/SpongeForge#1140]
minecraft 1.10.2
Sponge 1.10.2 beta 2006
Forge 12.18.3.2185

Modpack Old Guys Gaming

http://pastebin.com/rDFu3geG

**Comment by phit** [comment]
AE2 is currently not compatible with Sponge, see #966 and AppliedEnergistics/Applied-Energistics-2#2482
a patched version can be found [here ](https://github.com/Stonebound/Applied-Energistics-2/#about)

**Comment by TheMrCaveman** [comment]
i am using that patched version

**Comment by phit** [comment]
~what are the filenames for both AE2 and sponge in your mods folder?~
which one?

**Comment by TheMrCaveman** [comment]
appliedenergistics2-rv4-alpha-9
spongeforge-1.10.2-2171-5.1.0-BETA-2006
But i am investigating it @ the moment. Rebuilding modpack from scratch;(

**Comment by phit** [comment]
can't reproduce this with just Sponge and AE2 alpha9

**Comment by ghost** [comment]
I see latest build is 1.10.2-2171-5.1.0-BETA-2008 - why you use forge build 2185?

I think SpongeForge must be run under same forge - 2171.

**Comment by JBYoshi** [comment]
SpongeForge does not have to be run under a matching Forge build; the version just indicates which version of Forge it's tested against.

**Comment by gabizou** [comment]
Using the patched versions is practically the only way to load AE2 at the moment. It's been a known issue and the developer has been notified already.
