### ISSUE TITLE
Open Modular Turrets prevents boot. Issue with Version Checker. 

### ISSUE THREAD

**Issue by axle2005** [SpongePowered/SpongeForge#1141]
Recently tried to update our RR4 server to the public beta. It would consistently crash on boot.
Crash Log- http://pastebin.com/Gncg8EiN

Line immediately before the crash
[Sponge/]: The mod ompd was designed for omlib 3.0.0-37. It may not work properly. (It has the proper build)

New Crashlog after disabling OMPD
http://pastebin.com/yPdQihVX

After disabling Just Modular Turrets and enabling OMPD  it loads fine. 

FML Log of all mods enabled.
https://gist.github.com/axle2005/6c0fd09c3bdbaa9ec90e5916eeea5b27

This modpack will load without Sponge installed. 

Spongeforge: 1973, 2005, various others. 
Forge: 2185

**Comment by ghost** [comment]
SpongeForge is built against Forge 2171, why You use 2185?
