### ISSUE TITLE
[1.10.2] Itemstack cannot be null crash

### ISSUE THREAD

**Issue by Tencao** [SpongePowered/SpongeForge#1142]
http://paste.ee/r/i1B4z

This is causing almost frequent crashes on my server

**Comment by Aaron1011** [comment]
@Tencao: From looking at the stacktrace, this appears to be caused by breaking a certain block. Can you try to determine if a player is breaking a block immediately before the crash?

**Comment by Tencao** [comment]
I'll monitor it the next time it happens and find out which block is been broke to trigger it.

**Comment by bloodmc** [comment]
Create a new ticket if it occurs with latest builds.
