### ISSUE TITLE
[1.10.2] Cannot get properly, replacing air block with snow

### ISSUE THREAD

**Issue by Tencao** [SpongePowered/SpongeForge#1143]
I'm not sure if this is a Vanilla, Forge, or Sponge bug, so I'm going to start from here and work my way down. When trying to place snow on the ground, sometimes it will crash with this error.

http://paste.ee/r/ywcbS

**Comment by Aaron1011** [comment]
@Tencao: That's a very weird error. Are you able to reproduce this crash with any kind of consistency?

Also, would you be able to join `#sponge` on `irc.esper.net` to discuss this further?

**Comment by Tencao** [comment]
Sadly outside of two instances I've not had this crash repeat itself. I investigated the area but all I saw was a player building on a mountain with a few torches and chests, so nothing major.

**Comment by bloodmc** [comment]
I cannot reproduce any crashes with placing snow. Reopen if it occurs with latest builds.
