### ISSUE TITLE
Periodic Lag Spikes Kick Everyone

### ISSUE THREAD

**Issue by haydenfree** [SpongePowered/SpongeForge#1145]
I'm having an issue where my players periodically all time out, but have no issues with TPS loss. Only started occurring since updating from Pixelmon 5.0.0 Beta 12 to Pixelmon 5.0.0 and with that updating to Forge 2185. It seems to happen once every 10 minutes or so. The only thing I can think of on that schedule is the world auto-saving every 10 minutes (12000 ticks).

Here are two logs of what the crash looks like in console: https://hastebin.com/ivivimazem.md  &  https://hastebin.com/niyayoqezo.md

Timings: https://timings.aikar.co/v2/?id=ad429e070b4242f5a9ad86b867914ca8

Version Info:
    Minecraft: 1.10.2
    SpongeAPI: 5.1.0-SNAPSHOT-b23f81b
    SpongeForge: 1.10.2-2171-5.1.0-BETA-2006
    Minecraft Forge: 12.18.3.2185

Sponge Configs:
Global: https://hastebin.com/pikipuxexe.coffeescript
World: https://hastebin.com/xebapevupi.coffeescript
	
Startup Flags: java -Xms14G -Xmx14G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=60 -XX:InitiatingHeapOccupancyPercent=20 -XX:G1MixedGCLiveThresholdPercent=50 -XX:+AggressiveOpts -XX:+AlwaysPreTouch -jar forge-1.10.2-12.18.3.2185-universal.jar

Would greatly appreciate any advice or help :)

**Comment by vaniron** [comment]
Looks similar to mine issue #1139

**Comment by bloodmc** [comment]
This is not a sponge issue as the same disconnect issues have been reproduced with only Forge. You need to update to latest SF then disable mineshaft structure saving as this was one of the causes for disconnects.
Set structure-saving enabled to true then make sure mineshaft is false.

Dupe https://github.com/SpongePowered/SpongeForge/issues/1113
