### ISSUE TITLE
 [1.10.2] Exception trying to process over a phase!

### ISSUE THREAD

**Issue by FiveEYZ** [SpongePowered/SpongeForge#1146]
[fml-server-latest.log](http://paste.ubuntu.com/23701730/)

~11 hours up-time, i know this is a long log and most error a probably the same, but the errors can be found at these lines:
27612
27935
28215
33616
41184
41644
42351
42717
43654
47566
50089

**Comment by Aaron1011** [comment]
There appear to be at least two different issues in that log. One of them is definitely being caused by [Rough Mobs](https://mods.curse.com/mc-mods/minecraft/245849-rough-mobs) spawning an explosion  during blaze deaths.

**Comment by bloodmc** [comment]
Update to latest SF and create a new ticket if problem persists.
