### ISSUE TITLE
[1.10.2] Crash - CachedLong2ObjectMap

### ISSUE THREAD

**Issue by Tencao** [SpongePowered/SpongeForge#1147]
I have no clue what caused this, it was a random crash so I decided to bring it to your attention

http://paste.ee/r/0JpIU

Sponge version - 1.10.2-2171-5.1.0-BETA-2010
Forge version - 12.18.3.2185

**Comment by bloodmc** [comment]
Your server timed out by exceeding the set max-tick-time set in server.properties. When this occurs, the watchdog force kills the server and dumps all threads. Determine what is causing your lag, with the following 

https://github.com/sk89q/WarmRoast

and

/sponge timings paste

You can also raise max-tick-time a tad (not too high).
