### ISSUE TITLE
[1.10.2] Crash Chunk.func_177414_a (armorstand)?

### ISSUE THREAD

**Issue by johnfriedrich** [SpongePowered/SpongeForge#1149]
mc crash report:
https://pastebin.com/AV8RuYNp

No errors in fml or minecraft log.

Every player times out and server crashes after some time.

One player got spammed with this in his client:
https://pastebin.com/fqks58Ae

Broken chunkfile:
https://www.dropbox.com/s/ikivee4k7ob2bfg/r.1.0.mca?dl=0

**Comment by johnfriedrich** [comment]
Alright, found the issue. It was an invisible armorStand at -1
http://prntscr.com/dqd0vc

One armorstand...Now the server duplicated it 65536 times. (that was the issue why the server timeouted)
http://prntscr.com/dqd3jz
But no idea how that happened in the first place.

**Comment by johnfriedrich** [comment]
Short explanation:
We have issues with ghost entities, like described in an older SF ticket.
(Plugins should cancel spawning of existing entities), they do, but entities remain as ghost entities.
Lets say you have a chicken, you disable spawning of chicken. Restart server. Chicken cannot spawn, but spawns as an invisible chicken. 
(That is fixed in future builds, thx blood)
You cannot place blocks at that position.
So one of our staff members, used pistons to get rid of that invisible thing. She pushed it to -1, just under bedrock.
For any reason, this armorstand was duplicated 65536 times.

**Comment by bloodmc** [comment]
Cannot reproduce this issue using latest builds.
