### ISSUE TITLE
Sponge not passing  getDeathMessage method?

### ISSUE THREAD

**Issue by ProsperCraft** [SpongePowered/SpongeForge#1150]
https://github.com/TrainerGuy22/Reliquary/issues/234#issuecomment-266904444

**Comment by Aaron1011** [comment]
@ProsperCraft: I've tried killing some mobs with the Hunters Handgun, and I can't seem to reproduce it. Is there a specific mob that you killed?

**Comment by ProsperCraft** [comment]
Wasn't me, it was one of my players, and a while ago.

**Comment by Aaron1011** [comment]
Closing, as I was unable to reproduce this. If the issue re-occurs, please re-open this issue.
