### ISSUE TITLE
Sponge won't let me make right food with Cooking for BlockHeads

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeForge#1151]
With this mod, we can craft food in a "visual" kitchen multiblock. There is a block called "kitchen table", where we can craft food, and it has some imaginary slots, this way:

![a](http://image.prntscr.com/image/20dffd9679a74f3ea93507a6c03bf909.png)

In this table, we can double click the slots to craft the food, but as they are imaginary, looks like Sponge is having trouble with them. Sometimes, I click in a slot, and it acts like if I clicked in other one, crafting wrong foods. This happens almost all the times when I click in any slot. Also, this appears in the console:
```
 [Server thread/INFO] [STDOUT]: [net.blay09.mods.cookingforblockheads.container.inventory.InventoryCraftBook:tryCraft:110]: Got a container item, returning it to source provider
```
Cooking for BlockHeads repo: https://github.com/blay09/CookingForBlockheads

Running:
    Minecraft: 1.10.2
    SpongeAPI: 5.1.0-SNAPSHOT-e221622
    SpongeForge: 1.10.2-2171-5.1.0-BETA-2010
    Minecraft Forge: 12.18.3.2185
    CookingForBlockheads 1.10.2-4.2.26

**Comment by Aaron1011** [comment]
@Eufranio Can you retest with the latest SpongeForge? This is working fine for me.

**Comment by Eufranio** [comment]
I can still reproduce. Try double-clicking in the slots (that are showing the foods). It will craft wrong ones.

**Comment by phit** [comment]
could this be your texturepack offsetting the gui?

**Comment by Zidane** [comment]
Re-test without your current resource pack as it isn't reproduce-able.

**Comment by ryantheleach** [comment]
Also, could the behaviour be different between double and single click?
