### ISSUE TITLE
[1.11.2-2012] Server thread warning: skipping tileentity, statistic, key

### ISSUE THREAD

**Issue by bhi-elliot** [SpongePowered/SpongeForge#1152]
Good day,

Just testing out a build for a 1.11.2 server. I don't know a lot, so I apologize if this is a non-issue, but thought I would let you know the following server thread warning:
http://pastebin.com/je1eiHur
Java Version: 1.8
Minecraft Version: 1.11.2
Sponge Version: spongeforge-1.11.2-2201-6.0.0-BETA-2012
Forge Version: forge-1.11.2-13.20.0.2201-universal

Thank you for the amazing SpongeForge!

**Comment by Zidane** [comment]
This is for our benefit as it means certain data keys aren't implemented.

Thanks anyways.
