### ISSUE TITLE
Errors with event filtering

### ISSUE THREAD

**Issue by RobertHerhold** [SpongePowered/SpongeForge#1154]
Forge build 2171
SF build 1.10.2-2171-5.1.0-BETA-2010

Test plugin code:

```java
@Plugin(id = "test")
public class Test {
    @Listener(order = Order.POST)
    public void event(Event event, @Root Player player) {
    }
}

```

The stacktrace:
http://pastebin.com/cPGD1ace

So I understand that this is an issue with event filters not working on certain Forge events. I don't know of any workarounds to this issue, and I'm not obviously mis-using the API. Is there a good way to fix this?

**Comment by Deamon5550** [comment]
Not a problem with event filtering. The issue would seem to be that there is no mixin implementing that method for `FMLEvent`s. See [MixinEventState.java](https://github.com/SpongePowered/SpongeForge/blob/bleeding/src/main/java/org/spongepowered/mod/mixin/core/event/state/MixinEventState.java) for the only thing that comes close. Although this also has a getGame method implemented which hasn't existed in a long time.
