### ISSUE TITLE
ExtraUtil Compressed blocks, when mined, drop duplicated blocks. 

### ISSUE THREAD

**Issue by axle2005** [SpongePowered/SpongeForge#1155]
Seems to be a reoccurrence of: https://github.com/SpongePowered/SpongeForge/issues/1045

Sometimes its 4 blocks, sometimes its 14. 

SpongeForge version: 2010
Forge: 2185

**Comment by Tencao** [comment]
Would like to also confirm this bug too

**Comment by axle2005** [comment]
Im closing this one... the new one 1193 is so much more detailed.
