### ISSUE TITLE
SkyFactory 3 hostile mob spawns create extreme lag

### ISSUE THREAD

**Issue by xf57212** [SpongePowered/SpongeForge#1156]
Timings report: https://timings.aikar.co/v2/?id=a7bb91a91feb45bfb9a1a3f11cfdc1bf

On sky factory 3 we have discovered that hostile mobs are creating huge amounts of lag (server averaging ~7 TPS). Turning off hostile mob spawning in server.properties boosts TPS to 20.

Is there anything that can be done to allow our server to run with hostile mobs enabled?

Note its the actual process of spawning the mob that seems to generate lag, not the quantity of mobs on the server.

**Comment by xf57212** [comment]
output of /sponge version:

[01:14:21] [Server thread/INFO]: SpongeForge
    Minecraft: 1.10.2
    SpongeAPI: 5.1.0-SNAPSHOT-e221622
    SpongeForge: 1.10.2-2171-5.1.0-BETA-2010
    Minecraft Forge: 12.18.3.2185

**Comment by KaiKikuchi** [comment]
I also confirm this issue and I want to add this VisualVM profile snapshot screenshot that may help:
![image](https://cloud.githubusercontent.com/assets/8842403/21604306/bdba959a-d1a2-11e6-868f-93d9c1048330.png)

**Comment by Slind14** [comment]
Same with build 2010:
https://timings.aikar.co/v2/?id=9b5fb33bdf444d7895fd3ab46633ceb5
https://timings.aikar.co/v2/?id=420de73c16f14d37bfc701fb6f89e7b6
![](https://i.imgur.com/52WPDJ1.png)

**Comment by ktole1999** [comment]
so what happens if you use the same forge/sponge version rather than different versions?

**Comment by Rob5Underscores-zz** [comment]
There isn't a SpongeForge for 2185 that I can see - only 2202.

**Comment by ktole1999** [comment]
exactly

**Comment by xf57212** [comment]
so what are you saying ktole? change the forge version? that kind of prevents all players from logging in unless they change it client side too. not plausable for a public server

**Comment by ktole1999** [comment]
im just saying if you are running a server plugin not tested against the version of forge you are running you could have compatibility issues.

**Comment by bookerthegeek** [comment]
@xf57212 what is being said is that your forge version needs to match the SpongeForge version.

**Comment by axle2005** [comment]
Thats enough. This isn't a place to discuss this. Go on the forums and have a jolly old debate. None of it is actually related to the issue, additionally, its been said multiple times that the spongeforge version and forge version do not need to be identical, as long as forge is at least the version required by spongeforge. 

Stop filling up the issue with all your guys useless spam.

**Comment by xf57212** [comment]
@ktole1999 @bookerthegeek there is no way to make the versions match though since sponge does not have a 2185. We upgraded sponge to 2202 and have the same issue

**Comment by ktole1999** [comment]
i apologize if i was misinformed about compatibility. I was always told they needed to match.

**Comment by Aaron1011** [comment]
I'm going to improve the performance of `EntityTypeREgistry#getEntity` - it's implemented extremely inefficiently atm.

**Comment by Aaron1011** [comment]
This should be fixed in [the latest build](https://www.spongepowered.org/downloads/spongeforge/stable/1.10.2#1.10.2-2202-5.1.0-BETA-2016).

@xf57212 @KaiKikuchi @Slind14: Thank you so much for bringing this to our attention! The code I changed had been in place for over a year, and was almost certainly causing TPS issues on other servers as well (though no one identified it until now).

**Comment by Aaron1011** [comment]
@ktole1999: You're absolutely right - unless a developer says otherwise, it's important to have the Sponge and Forge build numbers match. However, the issue in this case was a performance problem, which wasn't affected by the build used.

**Comment by KaiKikuchi** [comment]
Thank you very much! <3

**Comment by Aaron1011** [comment]
@KaiKikuchi: Glad to help :) Let me know if the performance issues are resolved, and i'll close the issue.

**Comment by KaiKikuchi** [comment]
Yes it definitely fixed it! Thanks a lot!

**Comment by axle2005** [comment]
https://timings.aikar.co/v2/?id=30c9da39b59d42279e405c86aabe5943&section=lag

Not fixed. Kai lied

@Aaron1011

**Comment by Aaron1011** [comment]
@axle2005: Can you run VisualVM and/or WarmRoast, and post a screenshot? It's possible that another issue is slowing down mob spawns.

**Comment by KaiKikuchi** [comment]
Although the main method got fixed... there are other methods causing huge TPS issues:

![image](https://cloud.githubusercontent.com/assets/8842403/21626963/d807aaba-d214-11e6-8add-3da1cf411104.png)

**Comment by KaiKikuchi** [comment]
@axle2005 I didn't lie... the server had TPS 20 for the first time xD then it went to 10. It's going definitely better than before with TPS 4.

**Comment by Aaron1011** [comment]
@KaiKikuchi: This is definitely a separate problem. Can you open a new issue for it?

**Comment by KaiKikuchi** [comment]
Yes I can, but I think it's related to this issue. It's still mob spawning causing issues on SF3 :s

**Comment by Aaron1011** [comment]
@KaiKikuchi: All of the discussion here was from the specific issue I fixed. It would be better to have a fresh thread for discussing that specific problem.

**Comment by Slind14** [comment]
For us this didn't change a thing regarding performance. We are still wracking at 10-16 TPS with 30 players, same as before. But we use a custom entity limitation system.

**Comment by Slind14** [comment]
![javaw_2017-01-04_12-21-46](https://cloud.githubusercontent.com/assets/3914677/21640888/77440af2-d278-11e6-9293-8d3c134ccad2.png)
![javaw_2017-01-04_12-22-03](https://cloud.githubusercontent.com/assets/3914677/21640889/77449300-d278-11e6-8933-5163e61befda.png)

**Comment by xf57212** [comment]
@Slind14 the issue in this ticket was the getEntity() method which was fixed. instead of trying to piggy back off a closed ticket, you should make a new ticket for the separate issue you are having.
