### ISSUE TITLE
Description: Exception in server tick loop

### ISSUE THREAD

**Issue by KingDan27** [SpongePowered/SpongeForge#1157]
Not experienced with Sponge but crash seems to be caused by it as server launches fine without it.Hoping someone can help me out. Trying to add this Skyfactory 3 see crash log below

Forge version is 2185

http://pastebin.com/JXnv3cb7

**Comment by axle2005** [comment]
https://github.com/SpongePowered/SpongeForge/issues/1153

Remove yunomakegoodmap and itsbecauseuhasnogoodspawn

**Comment by bloodmc** [comment]
dupe #1153
