### ISSUE TITLE
Extra Utilities Dupe Bug With Sponge

### ISSUE THREAD

**Issue by curscascis** [SpongePowered/SpongeForge#1159]
When breaking compressed cobblestone or similar compressed blocks gives you between 4-8 blocks of the same type (on occasion up to 16). When breaking with a hammer you receive close to a stack of the intended drop. Tested on DW20 Modpack as well as SkyFactory3.

**Comment by axle2005** [comment]
https://github.com/SpongePowered/SpongeForge/issues/1155

In the future... at least do a search for issues before posting. This was 4 down...

**Comment by curscascis** [comment]
I'm sorry I did a search and looked through the issues, I didn't see it on the sponge GitHub. It's 5am I make mistakes. A simple merge, or close would do.
