### ISSUE TITLE
[1.10.2] Updating FTB Lite now wont start due to mixin error

### ISSUE THREAD

**Issue by BytesByBytes** [SpongePowered/SpongeForge#1161]
Updated Lite to their latest build and now the server simply wont start due to mixins crash see log below

Forge Version 2185

Have tried Spongeforge version 1992 and 2020 and get the same results 

[Log](https://gist.github.com/Bubble0seven/362dc3733d9744407adb4f0bd9a7831e)

**Comment by FiveEYZ** [comment]
i suggest to disable `foamfix-0.5.0-BETA2-anarchy` or update it to Lawful Edition

**Comment by BytesByBytes** [comment]
That doesn't work same error using Lawful Edition or disabling it 

 [Error](https://gist.github.com/Bubble0seven/5d0fb52f0bf7080ec15ba1791761d774)

**Comment by Inscrutable** [comment]
Just FYI, https://github.com/asiekierka/FoamFix/issues/15

**Comment by BytesByBytes** [comment]
thanks

**Comment by asiekierka** [comment]
Lawful Edition would not cause this crash, it does not include a coremod.

**Comment by FiveEYZ** [comment]
@Bubble0seven the second error u are getting is from FTBUtilities

**Comment by BytesByBytes** [comment]
Thanks Five i was having a total retard moment
