### ISSUE TITLE
IC2 crops cause server crash

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1162]
from fml-server-latest.log:
http://pastebin.com/medmmirW

no crash report generated...

server silently shut down

SF build 2020
IC2 build 146

Server crashes when do /save-all and some chunks with IC2 crops are active.

**Comment by FiveEYZ** [comment]
u should do what it says:

```
Our implementation and Minecraft's strictly prevents this from
happening, however, certain mods arenot null checking. Please provide this
report in a report to the associated mod!
```

**Comment by ghost** [comment]
Reported as: http://bt.industrial-craft.net/view.php?id=2078

**Comment by ghost** [comment]
Looks like fixed with IC2 build 147.
