### ISSUE TITLE
Cancelling InteractBlockEvent.Secondary doesn't cancell RightClickBlock

### ISSUE THREAD

**Issue by Polyana-Fontes** [SpongePowered/SpongeForge#1163]
I'm working on a protection plugin and it listen for `InteractBlockEvent.Secondary` with `@Listener(order = Order.FIRST, beforeModifications = true)`. It's working fine, and is fired before mods, but, when I cancel the event with `event.setCancelled(true)` the event is still passed to the mods as if it was not cancelled while the other plugins.

Time line:
1) Right click packet is received by the `NetHandlerPlayServer`
2) `PlayerInteractionManager` calls `SpongeCommonEventFactory`
3) `SpongeModEventManager` fires a `InteractBlockEvent.Secondary` to the plugins
4) My plugin receives and cancels the event (the Sponge event is now cancelled but the Forge event is not) and sends a message telling that the player doesn't have permission to do that.
5) `SpongeModEventManager` fires a `PlayerInteractEvent.RightClickBlock` to the mods
6) [HarvestCraft's RightClickHarvesting](https://github.com/MatrexsVigil/harvestcraft/blob/1.9.4-1.10.2a/java/com/pam/harvestcraft/addons/RightClickHarvesting.java#L40) (in my case) receives a `RightClickBlock` event and executes the harvest procedure like normal.

**Comment by Polyana-Fontes** [comment]
The cancellation state, useBlock and useItem results are not being set after the forge event is created: [SpongeForgeEventFactory:812](https://github.com/SpongePowered/SpongeForge/blob/9b833e447d053bc1eed7cbb3ba03fc6de93f33a7/src/main/java/org/spongepowered/mod/event/SpongeForgeEventFactory.java#L812)

**Comment by Zidane** [comment]
@bloodmc Can you look into this?

**Comment by Aaron1011** [comment]
Can you re-test with the latest SpongeForge? I just fixed a bug related to this.
