### ISSUE TITLE
AE2 Incompatibilty

### ISSUE THREAD

**Issue by ALebrunDev** [SpongePowered/SpongeForge#1164]
Hello,

Is there a way to cohabit Sponge and AE2 now?

**Comment by DenWav** [comment]
It was never resolved afaik. https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2482

**Comment by ALebrunDev** [comment]
Oh and if we want to play with sponge and AE2 ?
Because i need to create a Forge server with plugins on 1.10

**Comment by DenWav** [comment]
You might have more luck waiting for this fork, since they seem to actually be willing to fix the issue. https://github.com/AEModernMCPort/Applied-Energistics-3/issues/100

**Comment by ALebrunDev** [comment]
So there's a chance that someday it works?

**Comment by DenWav** [comment]
Yes, the fix is very simple and laid out in detail in the first link I posted. The developer was simply not willing to actually apply the fix.

**Comment by ALebrunDev** [comment]
I hate this Dev. 
Because a lot of FTB modpack work with AE2

**Comment by phit** [comment]
https://github.com/Stonebound/Applied-Energistics-2#about

**Comment by Deamon5550** [comment]
Duplicate
