### ISSUE TITLE
[1.10.2] world.conf gets reset on server restart

### ISSUE THREAD

**Issue by CriticalClaw** [SpongePowered/SpongeForge#1166]
Hi,

Im trying to make a server with void worlds using sponge API void generation. However every time I restart the server all the world.conf files get reset.

**Comment by Vauxite** [comment]
I can confirm this problem with the following versions:

- **SpongeForge**: spongeforge-1.10.2-2202-5.1.0-BETA-2022
- **Forge**: forge-1.10.2-12.18.3.2202

Additional plugins (have tried without them):

- griefprevention-1.10.2-2.2.0.205
- LuckPerms-Sponge-2.16.79
- Nucleus-0.18.0-S5.1-1.10.2-plugin
- projectworlds-5.1.0-0.11.4
- skyclaims-1.0.0-alpha13


In addition to the original problem. Sometimes the config change stick, however it has no effect what so ever.

Creating a new world with projectworld sucessfully use the sponge:void generationsmodifier.
`/world create skyblock -m "sponge:void"`
`/world load skyblock`
`/world teleport skyblock`

Kind regards,
Vauxite

EDIT: formatting

**Comment by bloodmc** [comment]
This was fixed awhile ago. Update to latest SF.
