### ISSUE TITLE
[1.10.2] TrackingUtil Error

### ISSUE THREAD

**Issue by lenis0012** [SpongePowered/SpongeForge#1169]
Our server has been crashing a lot recently (as in, A LOT)
I suspect there is an issue with one of the entities in our world.
And the stack trace directs towards SpongeForge (2020)

The fact that it doesn't say which entity/chunk this happened in doesn't exactly make it easier.
I would really appreciate it if someone took a look at this potential issue =)

http://pastebin.com/vuygiYsY

**Comment by Aaron1011** [comment]
Can you still reproduce this on the latest SpongeForge?

**Comment by lenis0012** [comment]
@Aaron1011 I will take a look to make sure

**Comment by lenis0012** [comment]
Updated to SpongeForge 2136 today.
So far haven't had any issues.
If it stays this way for 3 days i will consider it resolved

**Comment by Aaron1011** [comment]
I'm closing this issue. If it comes up again, feel free to re-open the issue.
