### ISSUE TITLE
[1.11.2-2201-6.0.0-BETA-2023] can't use command line to edit dimension.conf

### ISSUE THREAD

**Issue by bhi-elliot** [SpongePowered/SpongeForge#1170]
Good day,

Trying to remotely edit the dimension.conf using a command like
/sponge config -d overworld world.auto-save-interval
to check settings, produces error message:
No values matching pattern 'overworld' present for dimension!

Also tried the_end and nether, same message. also tried other config lines but could not get it to work.

What does work is, say:
/sponge config -w DIM-1 world.auto-save-interval
for the world config, but can't access the dimension config remotely.

Hope this report helps. Thanks for the great server!

**Comment by phit** [comment]
`sponge config -d minecraft:overworld world.auto-save-interval`

> Server thread/INFO Dimension overworld: Optional[world.auto-save-interval] is 900

Seems to work fine now (7.0.0-BETA-2739), as this issue is old and doesn't have a version associated I'll close this.

Let me know if you are still having issues and I'll reopen.
