### ISSUE TITLE
[Dupe] [SF3] Redstone

### ISSUE THREAD

**Issue by Vauxite** [SpongePowered/SpongeForge#1172]
**How to reproduce**
1. Acquire redstone
2. Throw redstone (Q by default).
 
Redstone is thrown and stay in inventory.

**Versions:**
    Minecraft: 1.10.2
    SpongeAPI: 5.1.0-SNAPSHOT-428c0b2
    SpongeForge: 1.10.2-2202-5.1.0-BETA-2022
    Minecraft Forge: 12.18.3.2202
    Modpack: Skyfactory 3 version 3.0.1

**Comment by axle2005** [comment]
Duplicate: [#1048](https://github.com/SpongePowered/SpongeForge/issues/1048)
