### ISSUE TITLE
[Dupe][SF3][1.10.2]

### ISSUE THREAD

**Issue by Vauxite** [SpongePowered/SpongeForge#1173]
**How to reproduce**
1. Place compressed cobblestone
2. Break placed block
3. Receive 15 extra compressed block (16 including the the block you broke)

You can use compressed hammer and get extra result too. 

**Versions:**
    Minecraft: 1.10.2
    SpongeAPI: 5.1.0-SNAPSHOT-428c0b2
    SpongeForge: 1.10.2-2202-5.1.0-BETA-2022
    Minecraft Forge: 12.18.3.2202
    Modpack: Skyfactory 3 version 3.0.1

**Comment by axle2005** [comment]
Duplicate [#1155](https://github.com/SpongePowered/SpongeForge/issues/1155)
