### ISSUE TITLE
Sponge continuing loading certain chunks 

### ISSUE THREAD

**Issue by Maudslay** [SpongePowered/SpongeForge#1174]
Hello,
When i reboot my 1.10.2 Hermitpack the server starts up alright but when i look at loaded chunks, there already is like 2000 loaded chunks with only 3 people online and slowly the cpu usage is going up and the loading error is just making it lag but having all those chunks loaded, i turned on logging.chunk-load true to see what it was coming from but when i saw the cords, i went over their and found nothing but a desert also whenever a player moves but them being so far away the chunks in these areas keep being loaded.i will show you what i mean.

Thanks in advanced :)
![screenshot_6](https://cloud.githubusercontent.com/assets/21957751/21754876/f809b714-d600-11e6-965b-10a1019553b8.png)
[fml-junk-earlystartup.txt](https://github.com/SpongePowered/SpongeForge/files/692552/fml-junk-earlystartup.txt)
[fml-server-1.txt](https://github.com/SpongePowered/SpongeForge/files/692554/fml-server-1.txt)
[fml-server-2.txt](https://github.com/SpongePowered/SpongeForge/files/692553/fml-server-2.txt)
[fml-server-3.txt](https://github.com/SpongePowered/SpongeForge/files/692556/fml-server-3.txt)
[fml-server-latest.txt](https://github.com/SpongePowered/SpongeForge/files/692555/fml-server-latest.txt)
![2017-01-09_00 18 54](https://cloud.githubusercontent.com/assets/21957751/21754907/64a502c0-d601-11e6-9344-09c6631a1ca2.png)
![2017-01-09_00 19 52](https://cloud.githubusercontent.com/assets/21957751/21754908/64a5bf30-d601-11e6-8b0c-e4c99642cfd6.png)

**Comment by Maudslay** [comment]
I'm also trying to keep them from being loaded by increasing the unload limit but that is failing slowly :/

**Comment by bloodmc** [comment]
You are only using an SF build nearly 150 builds old.

spongeforge-1.10.2-2123-5.1.0-BETA-1879.jar

Update to latest SF and Forge.
