### ISSUE TITLE
[1.10.2] Tile entities stopped being linked to a block

### ISSUE THREAD

**Issue by Tencao** [SpongePowered/SpongeForge#1175]
So I've experienced this bug with several blocks, ranging from the vanilla furnace, to item pipes, to machines, all from different mods. I've found no way of producing it, but from what I can gather based on player feedback, sometimes a vanilla furnace will randomly lose it's contents or stay turned on and never cook anything, sometimes an item pipe from ender io for example will continue to work after being destroyed and even playing cobblestone in it's exact spot, and sometimes I've had null pointers on tiles when the block is clearly loaded in that spot. All of this has lead me to believe that tile entities are being delinked from their respective blocks, but are not been cleaned up with the block, as well as possibly causing more and more tile entities to spawn in it's place.

Sponge Version - 1.10.2-2.1.7.1-5.1.0-BETA-2010
Forge version - 12.18.3.2185

Steps to reproduce - Unknown, might be linked to world saving

**Comment by phit** [comment]
#1059

may or may not be related I never found a better reproduction, but the effect was pretty much the same

**Comment by codeHusky** [comment]
I can confirm this with 1.11.2 and 1.11, when the server first starts blocks don't have tile entities either. I had a bug even where all tile entities were invisible until I reloaded the chunk, but they had no data after.

**Comment by Tencao** [comment]
I actually have multiple errors like Phit's, I'll paste them all below.

http://paste.ee/r/SFsPs
http://paste.ee/r/hrzGO
http://paste.ee/r/qGF8c <-- Should never be null as the ticks are called by the alch chest tile
https://paste.ee/r/vfR6v
https://paste.ee/r/HfbhH <-- Should never be null as the ticks are called by the DM Pedestal tile

**Comment by bloodmc** [comment]
@Tencao update to latest SF. You are using an outdated build.

**Comment by Tencao** [comment]
I'm always on the latest build, those were just old logs. I can see if the bug is fixed on the latest build though

**Comment by LemADEC** [comment]
Is this still reproduced?

**Comment by Zidane** [comment]
Closing due to no response.
