### ISSUE TITLE
Are these caused by Sponge's tracking?

### ISSUE THREAD

**Issue by Rob5Underscores-zz** [SpongePowered/SpongeForge#1176]
My server has been crashing frequently as a result of reports that easily identify the rogue block, however, all mention Sponge's tracking in the crash report? The crashes are all similar in nature, however, happen with a wide variety of mods and different blocks within each mod.

Is Sponge's tracking to blame? Do you expect disabling the tracking to stop this issue?

I have attached a few crash reports here:
http://pastebin.com/ijjdiD79
http://pastebin.com/VXKddAXE
http://pastebin.com/F6rqVaZc

SpongeForge-1.10.2-2202-5.1.0-BETA-2019

Thanks

**Comment by Tencao** [comment]
Might be linked to #1175

**Comment by Zidane** [comment]
The second pastebin link may very well be us, the other two are not. Re-test and re-open an issue for the second link if still an issue.
