### ISSUE TITLE
Sponge not compatable with FTB InfinityLite version 1.5.1 class loaded prematurely!

### ISSUE THREAD

**Issue by ProsperCraft** [SpongePowered/SpongeForge#1177]
This is similar to the AE2 problems of the past.

Oh dear. Sponge could not apply one or more patches. A required class was loaded prematurely!

https://gist.github.com/ProsperCraft/6055ba6fe2e7664538e215def577e366

spongeforge-1.10.2-2202-5.1.0-BETA-2026.jar
forge-1.10.2-12.18.3.2202-universal.jar

**Comment by phit** [comment]
can you post the full log up to this point, hopefully whatever loads that early prints something

**Comment by ProsperCraft** [comment]
That is the full log.

**Comment by FiveEYZ** [comment]
Try remove foamfix or update it to latest

**Comment by ProsperCraft** [comment]
yup! that was it, Sponge is not compatible with foamfix in 1.5.1 thank you. Updated topic.

**Comment by Deamon5550** [comment]
Duplicate #1161 and already fixed by the mod author, update to FoamFix `0.5.0-BETA3` (if its been released yet) or change to the lawful edition.
