### ISSUE TITLE
Sitting in stairs is client-side only with Sponge

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeForge#1178]
Using the mod Quak, we are able to sit in stairs. While sitting, in singleplayer/pure forge server, other players can see us when we are sitting, but with Sponge the client sit but other clients can't see. This appears in console:

```
[Server thread/ERROR] [Sponge]: No entity type is registered for class vazkii.quark.vanity.feature.SitInStairs$Seat
```

How I am supposed to be seen:

![a](http://image.prntscr.com/image/5541661ee18e44bd8dab08174c8abf8e.png)

How I am seen:

![a](http://image.prntscr.com/image/9782766fea79453aa80b6df60cd421f8.png)

    Minecraft: 1.10.2
    SpongeAPI: 5.1.0-SNAPSHOT-428c0b2
    SpongeForge: 1.10.2-2202-5.1.0-BETA-2022
    Minecraft Forge: 12.18.3.2185

**Comment by codeHusky** [comment]
Sponge clearly doesn't want you to sit. :P

**Comment by Aaron1011** [comment]
This appears to be a bug in Quark itself - I was able to reproduce the issue without Sponge installed at all.

**Comment by Eufranio** [comment]
True, it was reported in Quark repo for the ones who are having issues: https://github.com/Vazkii/Quark/issues/284#issuecomment-275197422
