### ISSUE TITLE
[1.10.2] Dupe bug with protections

### ISSUE THREAD

**Issue by Tencao** [SpongePowered/SpongeForge#1179]
From what I've observed, it seems that tools that dig multiple blocks bypass the permission and drop the item of the block, even though the block is never destroyed. This can very quickly be abused and I've observed this happening with multiple different protection plugins, which leads me to believe this is an issue with sponge not the plugins. At a guess, the event is not been canceled before breaking the block.

For record if it helps, ProjectE has tools that dupe using this method, and all of their stuff checks permission using this.
ForgeHooks.onBlockBreakEvent
FMLCommonHandler.instance().getMinecraftServerInstance().isBlockProtected
player.canPlayerEdit

Sponge version - 2171-5.1.0-BETA-2010
(Updated to version 2202-5.1.0-BETA-2026 after ticket was made, issue still present)

Forge version - 12.18.3.2185

**Comment by bookerthegeek** [comment]
Would it not be the permission plugins responsibility to inform sponge to cancel the drop? And or the mod to check permissions?

**Comment by Tencao** [comment]
Again, the mod is checking permissions, I even posted 3 ways one item on project e tests for permissions before breaking a block. As for the plugin to cancel the drop, considering this has happened with 3 different protection plugins, I'm only going to assume this is a sponge bug.

I wish you would read what I've already put in the first post before asking that.

**Comment by bookerthegeek** [comment]
I did read it, and more then once. You failed to list:

Plugins used.
Mods tested with.
Proof this does not happen without sponge.
Versions.

Please make sure bug reports include all relevant information when posting to not waste other people's time.

**Comment by Tencao** [comment]
Plugins Used/Tested
- Foxguard
- Nations 
- Safeguard

Mods Tested with
- ProjectE
- Tinkers Construct
- Mekanism

Proof this doesn't happen without sponge? Well of course it wont, it's sponge's protection that causes it

Versions are again listed in the first post. If you're referring to mod versions, the latest publicly available at the time of this post.

**Comment by bookerthegeek** [comment]
Still waiting for any testing that shows this does not happen with protection mods in a pure forge environment. 

Generally speaking you start at the lowest most likely option and start from their. 

So first,  check with each mod having this issue that they actually throw the event.  A good one in 1.7 for example was blood magic bound tools, they did not throw an event so they bypassed all protections.

Next, check that the protection mods are actually canceling the events thrown by A.O.E breaks. Towny had this issue back in its early days.

Finally, after all that has been done, and documented, then you come to sponge and see if it is not canceling the event correctly.

**Comment by Tencao** [comment]
How am I suppose to show that, this only happens in protected areas covered by sponge plugins, I even stated that. Removing sponge wont cause the dupe because the dupe is being caused by the protection plugins themselves, doing this on any unprotected land does not cause the dupe. 

I can look more into what the protection plugin themselves are doing but I do know from source that the project e tools are correctly using the inbuilt forge permission check for blocks, so I know it';s not forge's end nor the mods end.

**Comment by Bluexin** [comment]
On a sponge report tracker... Asking to test without sponge... Asking for already provided info... And even having the nerve to tell stuff like "please do so not to waste people's time"? Wow.
Who are you exactly to act like that? I mean, it's nice to try and help people but... C'mon.

**Comment by Bluexin** [comment]
On another note, might be linked to #1163

**Comment by Eufranio** [comment]
Try using GriefPrevention.

**Comment by bloodmc** [comment]
I haven't heard of this issue using latest SF and GP. Update to latest SF and try with GP. If it occurs in GP then i'll reopen.
