### ISSUE TITLE
Piston crashing the server- Exception while updating neighbours

### ISSUE THREAD

**Issue by ProsperCraft** [SpongePowered/SpongeForge#1180]
I thought this was sorted out previously, I could not find any open or closed reports that match though so here it is.

A Piston is crashing our server.

Screenshot- 
![2017-01-11_16 41 53](https://cloud.githubusercontent.com/assets/4427684/21871114/45e8222c-d81d-11e6-84ac-1fb40132bfe5.png)

Crashlog- 
https://gist.github.com/ProsperCraft/d0628f37b70a5b707182bac9a9ec44cb

**Comment by bloodmc** [comment]
Fixed in latest SF build, update.
