### ISSUE TITLE
org.spongepowered.mod.mixin.handler.MixinErrorHandler Error

### ISSUE THREAD

**Issue by Orcinuss** [SpongePowered/SpongeForge#1181]
Im getting this error regarding the order of loading core mods.
Ive had this before but in this case Applied Energistics is NOT installed.
No crash report. Only start up log.
http://pastebin.com/wHHL2swk

**Comment by FiveEYZ** [comment]
remove foamfix

alternative update it to latest or change to the lawful edition.

**Comment by Eufranio** [comment]
FoamFix in the server side(?????)

**Comment by ProsperCraft** [comment]
Yes, you can safely remove it, and the clients can still have it active on their client.

**Comment by Aaron1011** [comment]
This issue is fixed in the latest FoamFix.
