### ISSUE TITLE
crash on launch on only 1.9.4 server version

### ISSUE THREAD

**Issue by nacjmclub** [SpongePowered/SpongeForge#1182]
I built a server with the mods from skyfactory3 that are compatible and the engender mod and before the other mods get to register I am crashing on a mixintargetalreadyloadederror.

the server version is forge 1.9.4 1968 with the latest 1.9.4 spongeforge mod.

steps to reporduce:

1.build forge 1.9.4 1968 server on computer
2. add latest 1.9.4 spongeforge mod.
it should crash.

**Comment by Aaron1011** [comment]
Sponge for 1.9.4 isn't supported anymore. You'll need to upgrade to either 1.10 or 1.11
