### ISSUE TITLE
[1.10.2]Flowing water/pistons eats up flowers/grass/wheat/melons etc

### ISSUE THREAD

**Issue by johnfriedrich** [SpongePowered/SpongeForge#1183]
Forge:2202
SF 2039
**Setup:**
Place some flowers.
Get a bucket of water and place water near them.

OR

Place a piston
Place a melon in front of a piston
activate piston.

**What should happen:**
Flowers should drop

or

melon should be destroyed by the pistons and should drop melonslices.

**What actually happens:**
They are just removed by the water and no drops are spawned

or

Melon gets removed and nothing drops

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/SpongePowered/SpongeCommon/commit/bed5183c969ec784e1dc69e92f8052ed5d30ba94
