### ISSUE TITLE
Exception attempting to capture a block change! - Gamebreaking for our server!

### ISSUE THREAD

**Issue by Raycoms** [SpongePowered/SpongeForge#1184]
We have a tool which allows the player to place blocks.
"We're the minecolonies mod team". And everytime we try to place it the following happens:

/*                                                Exception attempting to capture a block change!                                                 */
/**************************************************************************************************************************************************/
/* PhaseContext :                                                                                                                                 */
/*         - Name: Source                                                                                                                         */
/*           Object: EntityPlayerMP['Time4Strike'/1321654, l='minecolonies', x=56.00, y=68.00,                                                    */
/*           z=253.00]                                                                                                                            */
/*         - Name: PacketPlayer                                                                                                                   */
/*           Object: EntityPlayerMP['Time4Strike'/1321654, l='minecolonies', x=56.00, y=68.00,                                                    */
/*           z=253.00]                                                                                                                            */
/*         - Name: Packet                                                                                                                         */
/*           Object: net.minecraft.network.play.client.CPacketClientStatus@455da41b                                                               */
/*         - Name: Cursor                                                                                                                         */
/*           Object: SpongeItemStackSnapshot{itemType=ItemBlock{Name=null}, count=45}                                                             */
/*         - Name: IgnoringCreative                                                                                                               */
/*           Object: false                                                                                                                        */
/*         - Name: Owner                                                                                                                          */
/*           Object: EntityPlayerMP['Time4Strike'/1321654, l='minecolonies', x=56.00, y=68.00,                                                    */
/*           z=253.00]                                                                                                                            */
/*         - Name: Notifier                                                                                                                       */
/*           Object: EntityPlayerMP['Time4Strike'/1321654, l='minecolonies', x=56.00, y=68.00,                                                    */
/*           z=253.00]                                                                                                                            */
/* Phases remaining :                                                                                                                             */
/*   - Phase: org.spongepowered.common.event.tracking.phase.packet.BasicPacketState@5db0d47e                                                      */
/*     Context:                                                                                                                                   */
/*     - Name: Source                                                                                                                             */
/*       Object: EntityPlayerMP['Time4Strike'/1321654, l='minecolonies', x=56.00, y=68.00, z=253.00]                                              */
/*     - Name: PacketPlayer                                                                                                                       */
/*       Object: EntityPlayerMP['Time4Strike'/1321654, l='minecolonies', x=56.00, y=68.00, z=253.00]                                              */
/*     - Name: Packet                                                                                                                             */
/*       Object: net.minecraft.network.play.client.CPacketClientStatus@455da41b                                                                   */
/*     - Name: Cursor                                                                                                                             */
/*       Object: SpongeItemStackSnapshot{itemType=ItemBlock{Name=null}, count=45}                                                                 */
/*     - Name: IgnoringCreative                                                                                                                   */
/*       Object: false                                                                                                                            */
/*     - Name: Owner                                                                                                                              */
/*       Object: EntityPlayerMP['Time4Strike'/1321654, l='minecolonies', x=56.00, y=68.00, z=253.00]                                              */
/*     - Name: Notifier                                                                                                                           */
/*       Object: EntityPlayerMP['Time4Strike'/1321654, l='minecolonies', x=56.00, y=68.00, z=253.00]                                              */
/* Stacktrace:                                                                                                                                    */
/* java.lang.IllegalStateException: Intended to capture block changes, but there is no list available! Please analyze the current phase context.  */
/*     org.spongepowered.common.event.tracking.TrackingUtil.lambda$throwWithContext$8(TrackingUtil.java:443)                                      */
/*     java.util.Optional.orElseThrow(Optional.java:290)                                                                                          */
/*     org.spongepowered.common.event.tracking.PhaseContext.getCapturedBlocks(PhaseContext.java:341)                                              */
/*     org.spongepowered.common.event.tracking.TrackingUtil.trackBlockChange(TrackingUtil.java:359)                                               */
/*     org.spongepowered.common.event.tracking.CauseTracker.setBlockState(CauseTracker.java:391)                                                  */
/*     net.minecraft.world.WorldServer.func_180501_a(WorldServer.java:1171)                                                                       */
/*     net.minecraft.world.World.func_175656_a(World.java:408)                                                                                    */
/*     com.minecolonies.coremod.network.messages.BuildToolPlaceMessage.handleHut(BuildToolPlaceMessage.java:164)                                  */
/*     com.minecolonies.coremod.network.messages.BuildToolPlaceMessage.messageOnServerThread(BuildToolPlaceMessage.java:120)                      */
/*     com.minecolonies.coremod.network.messages.BuildToolPlaceMessage.messageOnServerThread(BuildToolPlaceMessage.java:36)                       */
/*     com.minecolonies.coremod.network.messages.AbstractMessage.lambda$onMessage$82(AbstractMessage.java:24)                                     */
/*     java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)                                                                    */
/*     java.util.concurrent.FutureTask.run(FutureTask.java:266)                                                                                   */
/*     net.minecraft.util.Util.func_181617_a(SourceFile:45)                                                                                       */
/*     net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668)                                                                */
/*     net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)                                                      */
/*     net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)                                                                */
/*     net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)                                                                         */
/*     java.lang.Thread.run(Thread.java:745)                                                                                                      */
/**************************************************************************************************************************************************/
[22:33:28] [Server thread/INFO]: [Member] Naopil: Did
[22:33:34] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 3123ms behind, skipping 62 tick(s)
[22:33:46] [Server thread/INFO] [Morpheus]: Naopil is now sleeping. 1/4 (25%)
[22:33:46] [Server thread/INFO] [minecolonies]: Starting AI job com.minecolonies.coremod.job.Builder
[22:33:46] [Server thread/INFO] [minecolonies]: Starting AI job com.minecolonies.coremod.job.Miner
[22:33:46] [Server thread/INFO] [minecolonies]: Starting AI job com.minecolonies.coremod.job.Builder
[22:33:46] [Server thread/INFO] [minecolonies]: Starting AI job com.minecolonies.coremod.job.Farmer
[22:33:46] [Server thread/INFO] [minecolonies]: Starting AI job com.minecolonies.coremod.job.Builder
[22:33:46] [Server thread/INFO] [minecolonies]: Starting AI job com.minecolonies.coremod.job.Farmer
[22:33:46] [Server thread/INFO] [minecolonies]: Starting AI job com.minecolonies.coremod.job.Farmer
[22:33:46] [Server thread/INFO] [minecolonies]: Starting AI job com.minecolonies.coremod.job.Miner
[22:33:46] [Server thread/INFO] [minecolonies]: Starting AI job com.minecolonies.coremod.job.Miner
[22:33:46] [Server thread/INFO] [minecolonies]: Starting AI job com.minecolonies.coremod.job.Miner
[22:33:46] [Server thread/INFO] [minecolonies]: Starting AI job com.minecolonies.coremod.job.Lumberjack
[22:33:46] [Server thread/INFO] [minecolonies]: Starting AI job com.minecolonies.coremod.job.Miner
[22:33:46] [Server thread/INFO] [minecolonies]: Starting AI job com.minecolonies.coremod.job.Farmer
[22:33:46] [Server thread/INFO] [minecolonies]: Starting AI job com.minecolonies.coremod.job.Fisherman
[22:33:46] [Server thread/INFO] [minecolonies]: Starting AI job com.minecolonies.coremod.job.Miner
[22:33:46] [Server thread/INFO] [minecolonies]: Starting AI job com.minecolonies.coremod.job.Builder
[22:33:46] [Server thread/INFO] [minecolonies]: Starting AI job com.minecolonies.coremod.job.Lumberjack
[22:33:46] [Server thread/INFO] [minecolonies]: Starting AI job com.minecolonies.coremod.job.Lumberjack
[22:33:46] [Server thread/INFO] [minecolonies]: Starting AI job com.minecolonies.coremod.job.Builder
[22:33:46] [Server thread/INFO] [minecolonies]: Starting AI job com.minecolonies.coremod.job.Builder
[22:33:49] [Server thread/INFO] [minecolonies]: Starting AI job com.minecolonies.coremod.job.Farmer
[22:33:50] [Server thread/INFO] [minecolonies]: Starting AI job com.minecolonies.coremod.job.Farmer
[22:33:54] [Server thread/INFO] [minecolonies]: Starting AI job com.minecolonies.coremod.job.Farmer
[22:33:58] [Server thread/INFO] [minecolonies]: Starting AI job com.minecolonies.coremod.job.Farmer
/*     com.minecolonies.coremod.network.messages.BuildToolPlaceMessage.messageOnServerThread(BuildToolPlaceMessage.java:36)                       */
/*     com.minecolonies.coremod.network.messages.AbstractMessage.lambda$onMessage$82(AbstractMessage.java:24)                                     */
/*     java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)                                                                    */
/*     java.util.concurrent.FutureTask.run(FutureTask.java:266)                                                                                   */
/*     net.minecraft.util.Util.func_181617_a(SourceFile:45)                                                                                       */
/*     net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668)                                                                */
/*     net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)                                                      */
/*     net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)                                                                */
/*     net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)                                                                         */
/*     java.lang.Thread.run(Thread.java:745)                                                                                                      */
/**************************************************************************************************************************************************/

**Comment by bloodmc** [comment]
@Raycoms What SpongeForge build? Pastebin your entire fml-server-latest.log

**Comment by Raycoms** [comment]
spongeforge-1.10.2-2123-5.1.0-BETA-1879.jar

**Comment by Raycoms** [comment]
http://pastebin.com/YkaT3ztd
We also don't like the explosion event exceptions.

**Comment by ghost** [comment]
Idk why you use outdated SF build.

**Comment by gabizou** [comment]
Update your SF version and re-test.

Red protect is attempting to call some methods that are no longer available on the event, more than likely because it's either using an older version of the API or it's already updated for the latest API that hasn't been released yet.
