### ISSUE TITLE
Sponge Crashes Due to failure to load Dimensions for Skyfactory 3 ModPack

### ISSUE THREAD

**Issue by BytesByBytes** [SpongePowered/SpongeForge#1185]
Already reported so closin. Mini Moderator Phit pointed out my errors

**Comment by phit** [comment]
then why do you open a duplicate if you know it's already reported?!

**Comment by Bubble0seven** [comment]
Fuck sake maybe because i didnt see it when i first reported it sorry for making a mistake so get off ya high horse
