### ISSUE TITLE
Crash & Suggestion: Remove villager if invalid villager proffession is present

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeForge#1190]
Today I got a crash that is happening a lot with my server, related to invalid villager proffession IDs. That's the crash: https://hastebin.com/uwirejezuq.scala

`java.lang.IllegalStateException: Invalid Villager profession id is present! Found: 12`

My suggestion is to remove villagers which the ID is unknown (since they won't work anyway), or replace them with a random proffession.

    Minecraft: 1.10.2
    SpongeAPI: 5.1.0-SNAPSHOT-428c0b2
    SpongeForge: 1.10.2-2202-5.1.0-BETA-2032
    Minecraft Forge: 12.18.3.2185

**Comment by Aaron1011** [comment]
@Eufranio: Can you re-test this on the latest SpongeForge?

**Comment by Eufranio** [comment]
Yes, exploring a bit right now.

**Comment by Eufranio** [comment]
Explored a lot and no crashes, seems to be fixed, thanks!

**Comment by Eufranio** [comment]
Hmmm, nope, it crashed again, and now registering ExtraUtils2's villager:
```
java.lang.IllegalStateException: Invalid Villager profession id is present! Found: 12 when the expected contain: [SpongeProfession{id=minecraft:farmer, name=farmer, type=0}, SpongeProfession{id=minecraft:librarian, name=librarian, type=1}, SpongeProfession{id=minecraft:priest, name=priest, type=2}, SpongeProfession{id=minecraft:blacksmith, name=blacksmith, type=3}, SpongeProfession{id=minecraft:butcher, name=butcher, type=4}, SpongeProfession{id=minecraft:farmer, name=farmer, type=0}, SpongeProfession{id=minecraft:librarian, name=librarian, type=1}, SpongeProfession{id=minecraft:priest, name=priest, type=2}, SpongeProfession{id=minecraft:blacksmith, name=blacksmith, type=3}, SpongeProfession{id=minecraft:butcher, name=butcher, type=4}, SpongeProfession{id=forestry:arborist, name=arborist, type=5}, SpongeProfession{id=forestry:apiarist, name=apiarist, type=6}, SpongeProfession{id=immersiveengineering:engineer, name=engineer, type=7}, SpongeProfession{id=actuallyadditions:jamGuy, name=jamGuy, type=8}, SpongeProfession{id=extrautils2:alchemist, name=alchemist, type=9}, SpongeProfession{id=extrautils2:red_mechanic, name=red_mechanic, type=10}, SpongeProfession{id=extrautils2:shady_merchant, name=shady_merchant, type=11}]
```
Full crash-report: https://hastebin.com/tezotoweyo.scala

**Comment by CharZinta** [comment]
This seems to happen when any mod has a villager and then you remove the mod.  We are currently hitting this bug on a regular basis as we try to get out of beta and go live.

Do we know if/when this fix is slated?

**Comment by Twisted-Code** [comment]
I'm having this problem as well. For me, it started happening sometime after updating AgriCraft, which was already causing villagers with weird data to begin with. Top that off with an inexperienced admin (me, guilty as charged) and you've got a recipe for an unscheduled map reset... 
would it be too much to ask for someone to add a try/catch block for this that simply deletes villagers with broken data? While it's probably best left as a last resort, I think it's still better than the server crashing repeatedly as it tries to remove villagers one by one.

**Comment by cigagar** [comment]
Getting the same error here too! Running FTB Beyond 1.3

**Comment by ghost** [comment]
Same crash, FTB Beyond 1.4.0, lastest SF

**Comment by ghost** [comment]
thanks @gabizou

**Comment by ktole1999** [comment]
is there a way to tell which version this will get pushed to?

**Comment by stephan-gh** [comment]
@ktole1999 It should be in SF 2267+
