### ISSUE TITLE
TP Does not work

### ISSUE THREAD

**Issue by ampericus** [SpongePowered/SpongeForge#1191]
"Error occured while executing command:
org.spongepowered.api.entity.living.player.Player.setLocation(Lorg/spongepowered/api/world/Location;)V"
MC Version: 1.10.2
Forge Version: 1.10.2-12.18.3.2202
Sponge Version 1.10.2-2202-5.1.0-BETA-2032

I have not found any other issues which are similar to this.

**Comment by Deamon5550** [comment]
We'll need the full stacktrace or preferably the full log.

**Comment by Zidane** [comment]
Closing until we get more information.

**Comment by ampericus** [comment]
It does not give me a stack trace nor does it produce any error in the log (no idea why). It doesn't crash the server, it just spits that out in chat and noone gets tp-ed.
