### ISSUE TITLE
EnderIO Conduit Issues

### ISSUE THREAD

**Issue by bookerthegeek** [SpongePowered/SpongeForge#1192]
#### Issue Description:
When changing conduit Tiers from one tier to another tier the conduit dupes.

#### Background:
The mod [EnderIO](https://github.com/SleepyTrousers/EnderIO) has tiered conduits for moving Power / Liquids from point A to point B. It also has the ability to upgrade conduits already in the world in place at a rate of one to one from one tier to another tier.

#### What happens:
Conduit in hand is not used up.

#### What you expected to happen:
For the conduit in hand to be removed form inventory when used to upgrade conduit in world.

#### Steps to reproduce:
1. Place any tier of Power / Liquid (There are tree of each) in the world.
2. Right click on it with a different tiered conduit of the same type (Power for power, fluid for fluid)
3. This will recover the conduit in world, while not decreasing the count of conduit in hand.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.1.156
- EnderCore: 1.10.2-0.4.1.62-beta
- Minecraft: 1.10
- Forge: 1.10.2-12.18.3.2209
- SpongeForge: 1.10.2-2202-5.1.0-BETA-2029

#### Testing Walk through:
- Reported privately on our SF3 server.
- Confirmed on SF3 Server
- Could not reproduce SF3 SP
- Could not reproduce SP with only EnderIO
- Reproducible with only Enderio & SpongeForge SP

**Comment by bloodmc** [comment]
@Aaron1011 please look into this.

**Comment by Aaron1011** [comment]
@bookerthegeek: I'm unable to reproduce this with Sponge and EnderIO. Could you post a video or screenshot of your setup, so that I can be sure I'm testing the bug correctly?

**Comment by bookerthegeek** [comment]
Ok, after testing with the latest versions of 
- EnderCore-1.10.2-0.4.1.65-beta
- EnderIO-1.10.2-3.1.156
- spongeforge-1.10.2-2221-5.1.0-BETA-2136

It seems the Issue is no longer prevalent. Am glad this got fixed between when I posted this and now. :)
