### ISSUE TITLE
Possible reason for TPS issue in regards to mob spawns

### ISSUE THREAD

**Issue by adracamas** [SpongePowered/SpongeForge#1194]
I have a theory on the whole mob spawns increasing TPS.

A place to check is the routines for half-slabs. I have a theory that the mobs are still trying to spawn on them even if there is no space for them. Seems a peculiar thing.. but there may be a way to optimize the code to avoid checking every mob for the space.. mainly if there is another block butted against the top of it.

![image](https://cloud.githubusercontent.com/assets/3192842/21964984/01ab253c-db24-11e6-9681-1ad49e7a9bea.png)

This is an a server that is running the most recent version of SkyFactory3 (1.10 but they won't tell me the version of sponge they are using)

Hope this helps and if it does let me know.

**Comment by Deamon5550** [comment]
This should be a comment on whatever issue was open no a new issue.
