### ISSUE TITLE
Invalid Villager Profession ID is present!

### ISSUE THREAD

**Issue by Siriuo** [SpongePowered/SpongeForge#1197]
Having some server crashes caused by Villagers

Crash report from server is: http://pastebin.com/FFKSuS2Q

**Comment by Siriuo** [comment]
Seems to be caused when placing a routing node from blood magic.

**Comment by Zidane** [comment]
One of your mods is not registering villagers correctly (or at all). Remove mods one by one till you find the culprit.

**Comment by Eufranio** [comment]
Same crash with ONLY Forge + SpongeForge + Nucleus installed. I've set nucleus to generate the world, and as long it is generating, the server crashes.

**Comment by gabizou** [comment]
Duplicate of #1190 Will be fixing very soon.
