### ISSUE TITLE
SpongeForge & Placeable Items | Mod conflict | MC-1.10.2

### ISSUE THREAD

**Issue by SkyFoxCoder** [SpongePowered/SpongeForge#1199]
### Issue Description:
Mod conflict with **Placeable Items** _(forge mod)_ and **SpongeForge**.
Throws NPE at server console when right clicking with an item in hand.

Tested on a brand new Forge server, the only mods are SpongeForge and Placeable items.

> I have confirmed that this was an issue on a 133 mods Forge modpack of another user.
> _Removing_ **SpongeForge** OR **Placeable Items** _from the modpack FIXES the issue._

### Version List:
- MC: **1.10.2**
- SpongeForge: **spongeforge-1.10.2-2202-5.1.0-BETA-2034**
- Forge: **forge-1.10.2-12.18.3.2185** _(Recommended Build)_
- [Placeable Items](https://minecraft.curseforge.com/projects/placeable-items): 3.0.3.1 (Latest)

### Logs:
1. My log:
- https://hastebin.com/focodutaki.sql
2. Other user's log (133mods modpack, I do not have more info then those logs):
- https://hastebin.com/aridivoqim.rb
- https://hastebin.com/akumuzigus.vbs

### Steps to reproduce:
- Take any item, put it in your hand and right click **_Without_** aiming at a block.

**Comment by Aaron1011** [comment]
This should be fixed in the latest SpongeForge. Thanks for your extremely detailed issue report!
