### ISSUE TITLE
Sky Factory 3 (FTB) Sponge 

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1200]
so I added "spongeforge-1.10.2-2202-5.1.0-BETA-2037" to my server mod folder (Sky Factory 3) and i go to run my server and it gives me this :/ btw I haven't added any extra mods to this server

http://pastebin.com/0bLAxqaf

and i thought for a little that it was AE2 but it is not installed on the server

**Comment by axle2005** [comment]
https://github.com/SpongePowered/SpongeForge/issues/1153

**Comment by Deamon5550** [comment]
Duplicate #1161 and already fixed by the mod author, update to FoamFix `0.5.0-BETA3` (or higher) or change to the lawful edition.

**Comment by ghost** [comment]
i've updated foamfix and that didn't work so i removed it and i am still crashing... but thanks anyway

**Comment by Deamon5550** [comment]
@xXMiniGunXx after updating foamfix you likely hit the error in #1153
