### ISSUE TITLE
Ticking player

### ISSUE THREAD

**Issue by Sitherious** [SpongePowered/SpongeForge#1202]
https://paste.ubuntu.com/23814809/

**Comment by Deamon5550** [comment]
[FTBUPlayerEventHandler.java#L134](https://github.com/LatvianModder/FTBUtilities/blob/1.9/src/main/java/com/feed_the_beast/ftbu/handlers/FTBUPlayerEventHandler.java#L134) That does not look like a sponge issue?

**Comment by Sitherious** [comment]
I'm unsure if it's sponge or ftbutils but if the mod author says it's sponge I will post it in sponge.

**Comment by kashike** [comment]
`08:02:21 +LatvianModder | Yeah, thats ftbu issue, i should add nullcheck there`
