### ISSUE TITLE
Sponge crash "net.minecraftforge.fml.common.ModContainer", on Skyfactory 3 WITHOUT AE2

### ISSUE THREAD

**Issue by Kalclavia** [SpongePowered/SpongeForge#1205]
[Here](http://pastebin.com/b9TzHgjn) is the log of the crash.
I am attempting to run a skyfactory 3 server, with no other mods added. No AE2, and since this issue seems to be caused exclusively by AE2, I am unsure as to the cause of the error.

**Comment by phit** [comment]
#1161 #1153

**Comment by Deamon5550** [comment]
Update foamfix to 0.5.0-BETA3 or higher. and look at issue 1153 as well as you'll likely hit that next.
