### ISSUE TITLE
SkyFactory3 Crashing with Latest SpongeForge

### ISSUE THREAD

**Issue by HeeyItsRen** [SpongePowered/SpongeForge#1207]
I've already updated the mod FoamFix which seemed to be the issue of the crashing in the beginning where it wouldn't apply updates. After updating FoamFix, I started up the server it went fine then I get to the problem where EnderIO begins to read failures

http://pastebin.com/H8kRrjCs
I would post the entire crash report here instead but it looks too jumbled

**Comment by Deamon5550** [comment]
Duplicate #1153
