### ISSUE TITLE
[spongeforge-1.10.2-2202-5.1.0-BETA-2049] EntityActivation plugin is trying to cast EntityArmorStand to EntityLiving

### ISSUE THREAD

**Issue by weigui** [SpongePowered/SpongeForge#1208]
crash report here:
http://pastebin.com/AudsqMDe

# Issue Description
Server crashes because of the newly modified `org.spongepowered.commom.mixin.plugin.entityactivation.EntityActivationRange`  codes. 
Commit 86a52412a53acb6d2e5f130cc6d58e83f9f45407 by @bloodmc 

method `checkEntityImmunities(Entity entity)` at `EntityActivationRange.java:354` is trying to cast `net.minecraft.entity.item.EntityArmorStand` to `net.minecraft.entity.EntityLiving`, which would cause a `java.lang.ClassCastException`

# Affected Version
MC : 1.10.2
SpongeForge : 1.10.2-2202-5.1.0-BETA-2049

# Reproduce
Simply activate a chunk that contains EntityArmorStand, Server will crash immediately.

**Comment by kashike** [comment]
Fixed in https://github.com/SpongePowered/SpongeCommon/pull/1147.
