### ISSUE TITLE
Dupe with Crafting Station from Tinkers Construct 

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeForge#1211]
I explained the issue [here](https://github.com/SlimeKnights/TinkersConstruct/issues/2727#issuecomment-274230652), but it's basically that 2 players can open the crafting station and craft items at the same time, dupping. I tested with a pure forge server and it didn't happen, so I'm reporting this here. 

  Minecraft: 1.10.2
    SpongeAPI: 5.1.0-SNAPSHOT-b7a6e54
    SpongeForge: 1.10.2-2202-5.1.0-BETA-2053
    Minecraft Forge: 12.18.3.2185

**Comment by ghost** [comment]
It looks like Redpower Dupe Table is back :-)

**Comment by Eufranio** [comment]
This seems to be fixed.
