### ISSUE TITLE
Turtles from ComputerCraft won't fire events when moving 

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeForge#1212]
The only event that is fired is the block break one. With this, we can't prevent turtles from walking, entering protected areas, etc.

  Minecraft: 1.10.2
    SpongeAPI: 5.1.0-SNAPSHOT-b7a6e54
    SpongeForge: 1.10.2-2202-5.1.0-BETA-2053
    Minecraft Forge: 12.18.3.2185

**Comment by inklit** [comment]
Hm, are you sure? It should be firing onBlockPre. What are you doing to test? What version of CC are you using? Are you using CCTweaks or unborked? To say the least, I can't reproduce. More information is required.

**Comment by Eufranio** [comment]
I'm placing a turtle in a border of a GriefPrevention claim, opened and made it walk 1 block (enter the claim). The debug of GP showed only the block break event, probably by the turtle moving. 

I'm running ComputerCraft 1.80pr0 and CCTweaks 1.2.4.

**Comment by inklit** [comment]
No unborked? Try installing unborked & then retry. Unborked fixes CC for 1.10.2 for the most part.

**Comment by Eufranio** [comment]
Fixed by updating SF.
