### ISSUE TITLE
Entities causing TPS issues

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeForge#1213]
When my server gets 10+ players online, the server will start lagging, something about entities. I don't have much experience in debugging those things, but I made a [WarmRoast report](http://frani.magitechserver.cf/WarmRoastReport.rar) while the server is lagging, and also a [Timings](https://timings.aikar.co/dev/?id=185fb970424b4c898c8cf076b9975382) report. In the WarmRoast report, it seems that **org.spongepowered.common.event.tracking.TrackingUtil.tickEntity()** is consuming 21% of the tick time, and also other stuff...

My entity-activation-range settings: 
```
        defaults {
            ambient=16
            aquatic=16
            creature=16
            misc=8
            monster=16
        }
```
Sponge version:

    Minecraft: 1.10.2
    SpongeAPI: 5.1.0-SNAPSHOT-b7a6e54
    SpongeForge: 1.10.2-2202-5.1.0-BETA-2053
    Minecraft Forge: 12.18.3.2185

**Comment by Deamon5550** [comment]
I don't see anything there that looks like a hot point other than your server not being powerful enough for that many players and that many mods.

**Comment by Aaron1011** [comment]
@Eufranio: Note that all entity ticks on the server get funneled through `org.spongepowered.common.event.tracking.TrackingUtil.tickEntity()`. This causes the method to be shown as consuming a large portion of the tick time, but in reality, nearly all of the time is spent in the actual tick methods that it wraps.

**Comment by Eufranio** [comment]
So, it's a hardware problem?

**Comment by bloodmc** [comment]
This is not a sponge issue, lower spawns or adjust your entity activation config.
