### ISSUE TITLE
Actually Additions Leaf Blower Causes Crops to produce fruit and remain intact/unharvested as a block

### ISSUE THREAD

**Issue by curscascis** [SpongePowered/SpongeForge#1216]
With grief prevention, using a leaf blower on plants from a claim you are not trusted in causes the crops to duplicate. Disabling Item-spawn in gp did not fix the issue.

**Comment by Eufranio** [comment]
Try with latest SpongeForge, blood fixed a thing like this.

**Comment by curscascis** [comment]
thanks, actually I think Aaron's fix may have fixed it, by respecting the cancellation given by gp, I'll have to test it out.

**Comment by curscascis** [comment]
Can verify the fix did not apply to this bug.

**Comment by Aaron1011** [comment]
This is an issue with how ActuallyAdditions spawns in the drops, which prevents Sponge from properly tracking them. I've opened an issue here: https://github.com/Ellpeck/ActuallyAdditions/issues/624

**Comment by Aaron1011** [comment]
This has been fixed in the latest ActuallyAdditions.
