### ISSUE TITLE
Blocks lose tile entities after exploded & cancelled

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeForge#1217]
When I try to explode a block and the event is cancelled (by a protection plugin, by example), the blocks will lose their tile entities data. This breaks modded blocks, such as machines, batteries, after an explosion event near them, the energy is reseted, facing, inventory, etc.

Using:
    Minecraft: 1.10.2
    SpongeAPI: 5.1.0-SNAPSHOT-d41d606
    SpongeForge: 1.10.2-2202-5.1.0-BETA-2078
    Minecraft Forge: 12.18.3.2185

**Comment by ryantheleach** [comment]
Possibly related: https://github.com/SpongePowered/SpongeForge/issues/1274

**Comment by bloodmc** [comment]
Need more information.
