### ISSUE TITLE
Lasers from Actually Additions will damage even if pvp is off

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeForge#1220]
In the mod, we can attach lens to the Atomic Reconstructor block, and one of those lens will kill instantly any player, and the problem os that it will kill players even if PvP is turned off in the Sponge config.

**Comment by Aaron1011** [comment]
I believe that this is working as intended. My understanding of the Sponge config's pvp flag is that it only prevents damage directly initiated by players - not damage to players in general.

Pinging @SpongePowered/developers for input.

**Comment by Eufranio** [comment]
Players are able to place and activate it near other players to kill them. The best is ban the lens item then?

**Comment by Aaron1011** [comment]
@Eufranio: I think that kind of control is best left to a plugin. While Sponge could conceivably prevent all damage to players caused blocks with a different `Owner`, this would probably make the option too heavy-handed - and therefore not very useful - for most people.
