### ISSUE TITLE
Can't break blocks by end portal in the end dimension

### ISSUE THREAD

**Issue by jackytuutykcaj** [SpongePowered/SpongeForge#1221]
ftb infinity lite 1.5.1
spongeforge-1.10.2-2202-5.1.0-BETA-2078.jar

**Comment by FiveEYZ** [comment]
this happen for me to, somehow there was spawn-protection

setting `spawn-protection=0` in server.properties fixed it for me

still odd with spawn-protection in the end :P

**Comment by ghost** [comment]
add permission **minecraft.spawn-protection.override** to specific world context
