### ISSUE TITLE
Sponge doesn't handle delayed Villager Profession registration

### ISSUE THREAD

**Issue by yepidoodles** [SpongePowered/SpongeForge#1222]
Version: spongeforge-1.10.2-2202-5.1.0-BETA-2022
Modpack: http://www.technicpack.net/modpack/elbeta.705651
Crash report: http://www.codesend.com/view/44385064606caeeb2c5fa511ebfb5ed0/

The crash happens when someone goes near some villages, I suspect it's one of the mod's fault, but as the report is not pointing to any mod this is the only place I can post it. There's always a couple of seconds between the person logging in and the server crashing. If you need any other logs or information, just ask. Any help with this would be appreciated. 

- Alice

**Comment by Aaron1011** [comment]
This is due to a problem with how we handle villager profession and career registrations from Forge mods. I should have a fix available soon.

**Comment by yepidoodles** [comment]
I updated as soon as you posted the new version, had 10-16 players on since, spent my entire time searching for villages (found lots) and not a single crash. Thank you very much!
