### ISSUE TITLE
Possible Memory Leak

### ISSUE THREAD

**Issue by thefiz** [SpongePowered/SpongeForge#1226]
I'm running the latest (as of this post) version of Sponge (1.10.2-2202-5.1.0-BETA-2086) with forge 2202 on a modded server with what is mainly the Direwolf20 pack with some modifications.

Ever since switching over to Sponge I have had a pretty nasty memory leak and lag I've been chasing.  I ran a heap dump on the server when I noticed 7GB of RAM usage for 2 players (the server normally starts up around 4GB and levels out at around 3,5GB if nobody is on).

The Heap Dump pointed to almost 3 GB of usage from net/minecraft/entity/palyer/EntityPlayerMP contained within that was 2GB of usage from org/spongepowered/api/item/inventory/transaction/SlotTransaction

Any help would be appreciated in finding this leak.

**Comment by thefiz** [comment]
Forgot to attach my timings report
https://timings.aikar.co/?id=3b3fc2a58f70448286a3b20283d013c9

**Comment by Aaron1011** [comment]
@thefiz: Can you do another heap dump with the latest SpongeForge? [This commit](https://github.com/SpongePowered/SpongeCommon/commit/3ba053165a12460fe2720a20b6548917110c5719) may significantly cut down on the number of `SlotTransaction` objects.

**Comment by bloodmc** [comment]
This was fixed as reported above.
