### ISSUE TITLE
Psi dupping items if the break event is cancelled

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeForge#1227]
When we use a [Break Block spell](https://github.com/Vazkii/Psi/blob/master/src/main/java/vazkii/psi/common/spell/trick/block/PieceTrickBreakBlock.java) from Psi in a protected area, the block won't break (because the event is cancelled), but will still drop it's items. Like, we break a chest, the items will drop but the chest won't be broken, dupping them.

**Comment by liach** [comment]
Sounds like a Psi bug. Vazkii should check whether the breaking failed or not.

**Comment by Eufranio** [comment]
I guess it already does? It checks if the event is cancelled.

**Comment by liach** [comment]
change block event is not the same as block break event. Probably need to make some change in forge to fix this.

**Comment by zerafox** [comment]
PSI is not the only thing causing this problem. I get the same thing when a Creeper explodes and Nucleus cancels the block break event. I still see stone, wood, etc; show up as if the creeper **had** created it's crater.

**Comment by Eufranio** [comment]
Are you in latest SpongeForge? This was already fixed.

**Comment by zerafox** [comment]
Depends on when a "new version" was released..

**Comment by Eufranio** [comment]
Yesterday?

**Comment by zerafox** [comment]
As of the build 13hrs ago
_Which is kind of crazy/ridiculous there's a new build every couple of hours..._
my creepers aren't leaving brand new blocks from exploding.

**Comment by liach** [comment]
Related to #1231 ?

**Comment by Eufranio** [comment]
I don't think so, since this dupe happens **every time**.

**Comment by liach** [comment]
@Eufranio It should have been addressed in 0fb7475752dec8aad8e09454e582bf5c05b6d1b3. Try the latest build.

**Comment by Eufranio** [comment]
Still dupping in latest build.

**Comment by bookerthegeek** [comment]
No longer an issue with the latest version on our server. Running:
- SpongeForge 1.10.2-2221-5.1.0-BETA-2136
- Skyfactory 3
- Direwolf20

**Comment by gabizou** [comment]
Woo, good to hear. I was trying to find this issue to see if it was similar to the other issue already fixed with a recent commit.
