### ISSUE TITLE
Lightning and Wither sounds are heard in all worlds

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeForge#1228]
When a player spawns a lightning, or a wither is spawned, the song is heard in all the world(s) for all players, and this is quite annoying. Could you guys fix or add a config for range of the sounds?

**Comment by Time6628** [comment]
Have players install the Bad Wither no cookie mod.

**Comment by phit** [comment]
#1123

**Comment by Eufranio** [comment]
Oh, sorry.
