### ISSUE TITLE
Failed to handle packet

### ISSUE THREAD

**Issue by ziceptor** [SpongePowered/SpongeForge#1229]
The player said that was major lag. The other players were all good.

http://pastebin.com/GM0WVi5S

1.11.2-2201-6.0.0-BETA-2097

**Comment by ziceptor** [comment]
AntiWDL-1.1-all.jar
API6-BetterBoom.jar
AutoBroadcasterSponge-0.2.1.jar
CommandSigns-API-6.0.0-1.3.1.jar
CustomPlayerCount.-.1.1.jar
EasyScoreboards.jar
EconomyLite-5.0.0-2.8.0.jar
FlexibleLogin.jar
foxcore-0.10.3-208-server.jar
foxguard-0.20.2-api5-347-server.jar
Graveyards-v2.1.3.jar
helpme-5.0.0-0.2.2.jar
holograms-v2.0.1.jar!
IPLog-0.1.0.jar
Launchpad-v1.0-FIXED.jar
MiscStuff-1.0-SNAPSHOT.jar
Nucleus-0.20.0-S5.1-1.10.2-plugin.jar
NucleusMixins-0.15.0-S5-mixinplugin.jar
ore-plugin-1.1.0-SNAPSHOT.jar
PermissionsEx-Sponge.jar
projectportals-5.1.0-0.13.6.jar
spongeforge-1.11.2-2201-6.0.0-BETA-2092.jar
Synonym-1.0.1.jar
TitleMOTD.-.1.0.jar
treepers-5.1.3.jar
twentyticks.jar
walletdrop-5.1.0-0.2.1.jar
worldedit-sponge-6.1.7-SNAPSHOT-dist.jar

**Comment by FiveEYZ** [comment]
have also started to get alot of these packet issues lately

like this one Flux-network:
https://hastebin.com/oqecizumup.rb

or this with Waila:
https://hastebin.com/inorucozel.rb

sorry if they are not related as im using 1.10.2, and they may only be mod related

**Comment by Aaron1011** [comment]
@ziceptor: Can you pasebin your full `latest.log` and `fml-server-latest.log` when this happens again? I suspect something else is going on to cause this.

**Comment by ziceptor** [comment]
ok

**Comment by ziceptor** [comment]
@Aaron1011 [fml-server-latest.log and latest.log](https://cloud.mail.ru/public/KKu7/CNPonSeiu)
It happened when player trying to connect to the server. Before that, the player was kicked.

**Comment by ziceptor** [comment]
@Aaron1011 Any news?

**Comment by bloodmc** [comment]
This shouldn't be happening with latest Forge and SF builds. Reopen ticket if it does.
