### ISSUE TITLE
Strange Interaction Issue

### ISSUE THREAD

**Issue by yepidoodles** [SpongePowered/SpongeForge#1231]
SpongeForge version 1.10.2-2202-5.1.0-BETA-2098
Forge Version 1.10.2-12.18.3.2202

I'm not sure if this is Sponge's fault or another plugin (I know it's not a mod, doesn't happen on Singleplayer). It seems to only happen to a few players and random times, only way I've been able to fix it is with a server restart, although one player said they fixed it by teleporting between dimensions. Happy to provide a list of plugins on request.

Issue includes:
Not being able to interact with inventories, work benches, doors, etc.
Not being able to place blocks.
You can do everything else just fine.

It's happened to me twice now and I can't restart a public server everytime it happens, so any help is appreciated, even if it is just something stupid I missed.

Thanks

- Alice
[DragonTechMC](http://dragontechmc.com)

**Comment by Aaron1011** [comment]
@yepidoodles: Are playes able to use items at all (either right-clicking on blocks or in the air)?

**Comment by yepidoodles** [comment]
Yes, you can do stuff like eat and use backpacks.

**Comment by Aaron1011** [comment]
@yepidoodles: Can you upgrade tp the latest SpongeForge? Look for any errors in your `latest.log` and `fml-server-latest.log` when you do so

**Comment by yepidoodles** [comment]
Before I had a chance to update to the latest SpongeForge, it happened while I was also having issues with [AdventureMMO](https://forums.spongepowered.org/t/trophy-adventuremmo-v1-6-3-api-4-5/14985), I've since updated SpongeForge and removed AdventureMMO, hopefully it was that causing it, if it doesn't happen again in the next 3 days, I'll close this issue.

**Comment by Aaron1011** [comment]
@yepidoodles: Has this re-occured?

**Comment by yepidoodles** [comment]
It has not, sorry, forgot about the issue ^.^
