### ISSUE TITLE
[1.10.2] Error seen during startup

### ISSUE THREAD

**Issue by FiveEYZ** [SpongePowered/SpongeForge#1233]
dont know if its critical, just wanted to report it
https://gist.github.com/FiveEYZ/486266d564d78561acbd427f6ee328c1

dont know how this will affect the server as it still starts up fully.

here is the full start up log:
https://gist.github.com/FiveEYZ/24b470b33b52fd04584250a293b024e9

using:
spongeforge-1.10.2-2221-5.1.0-BETA-2104
forge-1.10.2-12.18.3.2221-universal

**Comment by bloodmc** [comment]
This is no longer an issue in latest builds.
