### ISSUE TITLE
SpongeForge is not receiving / sending messages via channels (bungeecord)

### ISSUE THREAD

**Issue by HeyZeer0** [SpongePowered/SpongeForge#1235]
SpongeForge is not receiving / sending messages via channels (bungeecord)

Tested with SpongeForge: ``1.10.2-2221-5.1.0-BETA-2109``
Tested with SpongeVanilla: ``1.10.2-5.1.0-BETA-370``

Evidences: (I'm Brazilian, so I'll translate the messages)
With SpongeVanilla: http://prntscr.com/e2srua
With SpongeForge: http://prntscr.com/e2sjx7 ``(The player should be kicked because the bungeecord did not respond)``

Code from SpongeForge test:
```
bungeecord = game.getChannelRegistrar().getOrCreateRaw(this, "BungeeCord");

public static void kickPlayer(Player p) {
        bungeecord.sendTo(p, buffer -> buffer.writeUTF("KickPlayer").writeUTF(p.getName()).writeUTF("No connection to the bungeecord"));
    }
```

The bungeecord is active and running, all messages are sended but not received.

**Comment by Eufranio** [comment]
I guess it should be posted in SpongeCommon?

**Comment by HeyZeer0** [comment]
@Eufranio The problem only occurs in the forge version, so here is probably the correct location.

**Comment by Aaron1011** [comment]
@HeyZeer0: Your code worked fine for me. Can I see your full code snippet, as well the version of BungeeCord that you're using?

**Comment by HeyZeer0** [comment]
I tried to use bungeecord version [#1225](http://ci.md-5.net/job/BungeeCord/1225/) and [HexagonMC Version](https://github.com/HexagonMC/BungeeCord)

There is my code:
<removed>

Thanks for answering @Aaron1011 =)

**Comment by simon816** [comment]
I suspect this has something to do with you using the channel in the `ClientConnectionEvent.Join` event. The network handler may not have been completely setup at that point.
Try scheduling it a few ticks later

**Comment by HeyZeer0** [comment]
@simon816 The code works perfectly on SpongeVanilla and there is already a delay.

**Comment by Time6628** [comment]
Are you using SpongePls to allow forge clients to connect to the server?

**Comment by HeyZeer0** [comment]
Thanks @Time6628, can be closed.

**Comment by Time6628** [comment]
You can close github issues you opened yourself.
