### ISSUE TITLE
1.11.2 Players lose all items when breaking grave

### ISSUE THREAD

**Issue by ProsperCraft** [SpongePowered/SpongeForge#1237]
This issue is back.

https://github.com/SpongePowered/SpongeForge/issues/1097

    Minecraft: 1.11.2                                                                                                                                                                                             
    SpongeAPI: 6.0.0-SNAPSHOT-466d1a8         
    SpongeForge: 1.11.2-2226-6.0.0-BETA-2112 
    Minecraft Forge: 13.20.0.2226

**Comment by Aaron1011** [comment]
I believe this is fixed in the latest SpongeForge (probably in https://github.com/SpongePowered/SpongeCommon/commit/a73c930b1692340cc61c1742a957dd00c1191533)
