### ISSUE TITLE
Dupe with Psi block break

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeForge#1239]
When we use a [Break Block spell](https://github.com/Vazkii/Psi/blob/master/src/main/java/vazkii/psi/common/spell/trick/block/PieceTrickBreakBlock.java) from Psi in a protected area, the block won't break, but will still drop it's items. Like, we break a chest, the items will drop but the chest won't be broken, dupping them.

    Minecraft: 1.10.2
    SpongeAPI: 5.1.0-SNAPSHOT-c82cd9e
    SpongeForge: 1.10.2-2221-5.1.0-BETA-2109
    Minecraft Forge: 12.18.3.2185

**Comment by axle2005** [comment]
Duplicate [#1227](https://github.com/SpongePowered/SpongeForge/issues/1227)

**Comment by Eufranio** [comment]
Oh sorry, how I didn't see my own issue lol
