### ISSUE TITLE
NoClassDefFoundError: net/minecraft/crash/CrashReportCategory$4

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeForge#1240]
Looks like the server doesn't have the crash report class? :P
Crash-report of the missing crash-report class: https://hastebin.com/equyeluvaz.sql

**Comment by Aaron1011** [comment]
I haven't been able to reproduce this in production - calling `CrashReportCategory.addBlockInfo` works fine in production for me. Can you provide a list of steps to reproduce this?

**Comment by Deamon5550** [comment]
Is that a patched version of applied energistics?

**Comment by Eufranio** [comment]
Yes. 
Aaron, I dont have much info about it, it just randomly happens. That's my modpack: http://www.technicpack.net/modpack/magibeta-pack.940049
I removed all the plugins and still having the crash.

**Comment by phit** [comment]
where did you get the patched ae2 version from?

**Comment by Eufranio** [comment]
Your version(?) https://github.com/Stonebound/Applied-Energistics-2

**Comment by Aaron1011** [comment]
Moving the discussion to https://github.com/SpongePowered/SpongeForge/issues/1103.

**Comment by Eufranio** [comment]
This one is #1240 lol

**Comment by Aaron1011** [comment]
Oops - I meant #1103
