### ISSUE TITLE
Custom Npcs Crash [1.10.2] 

### ISSUE THREAD

**Issue by Sean-Amor** [SpongePowered/SpongeForge#1241]
May not be sponge at all, but thought it was worth a shot posting this:

**CustomNPCs_1.10.2(20nov16)
 
Minecraft Forge: 12.18.3.2221
SpongeForge: 1.10.2-2202-5.1.0-BETA-2034
SpongeAPI: 5.1.0-SNAPSHOT-428c0b2
Minecraft: 1.10.2 23.01**
 
From what players are saying, if they have a staff and use it/have it in there inventory it crashes the server.
I believe this may be the error log, I may have to have them reproduce the issue if this is incorrect.
Console log:
https://hastebin.com/iqagemebey.vbs
Server crash-log:
https://hastebin.com/elizinafis.pl

@noppes

**Comment by bloodmc** [comment]
@Sean-Amor Update to latest SpongeForge and try again. Old builds will NOT be supported.

**Comment by bloodmc** [comment]
No response in nearly 2 months. Assuming fixed.
