### ISSUE TITLE
[Sponge 1.10.2-2221-5.1.0-BETA-2109]  Exception during phase body    

### ISSUE THREAD

**Issue by alicheek** [SpongePowered/SpongeForge#1243]
Error Report: http://pastebin.com/EDssvjVB

**Comment by Deamon5550** [comment]
The first stack is harvestcraft being stupid. The actual error seems to be a bug with https://github.com/MikeLydeamore/ExNihiloAdscensio/blob/master/src/main/java/exnihiloadscensio/barrel/modes/compost/BarrelModeCompost.java#L81 Can't see anything there that we might cause, try and reproduce it without sponge.

**Comment by Zidane** [comment]
Closing due to no feedback.
