### ISSUE TITLE
Breaking a chest or dropper with items in it make them disapear.

### ISSUE THREAD

**Issue by ProsperCraft** [SpongePowered/SpongeForge#1245]
Using spongeforge 
    Minecraft: 1.11.2
    SpongeAPI: 6.0.0-SNAPSHOT-466d1a8
    SpongeForge: 1.11.2-2226-6.0.0-BETA-2112
    Minecraft Forge: 13.20.0.2226

Breaking chests with items in them, or a dropper with items the items are lost.

**Comment by bloodmc** [comment]
dupe SpongePowered/SpongeCommon#1079
