### ISSUE TITLE
[1.11.2] Server crashloop that stops when sponge is removed.

### ISSUE THREAD

**Issue by ProsperCraft** [SpongePowered/SpongeForge#1247]
https://gist.github.com/ProsperCraft/3cab4cc74101c8753adc2095df4a6818

Modpack One Elf Squared 4.1

I can supply the world, compressed its almost 2 gigs though.

**Comment by ghost** [comment]
I think foamfix isnt compatible with sponge.

**Comment by simon816** [comment]
Appears to be an issue with Mine Colonies. From a quick look at the code it could be to do with a world unloading.

**Comment by Raycoms** [comment]
The question is why this happens with sponge and not or only rarely without.

**Comment by Aaron1011** [comment]
This appears to have been fixed in https://github.com/Minecolonies/minecolonies/commit/027251b7b151f33dc7e3bb55db5956ad9eacd384
