### ISSUE TITLE
[1.10.2] Excessive mob spawns

### ISSUE THREAD

**Issue by Tencao** [SpongePowered/SpongeForge#1249]
So for a while, I always found mob spawns to be a little underwhelming, however recently there's been so much it's nearly impossible to control. I've set far lower activation ranges for mobs in hopes to reduce their numbers, but I can still sometimes get 2000 mobs around 1 players base. Is this a bug and if not, can you add a more direct way to control mob spawning via the sponge config.

Sponge version - 2221-5.1.0-BETA-2113
Forge version -  12.18.3.2221

**Comment by phit** [comment]
Sounds like you have a chunk corruption, or some mod bugging out, I have not seen anything like this on either SF3 or DW20.
Does this happen everywhere randomly or same place all the time?

**Comment by Tencao** [comment]
I think it's most noticeable near the ocean, we tend to get a fair bit of water mobs spawning there

**Comment by bloodmc** [comment]
@Tencao Use a mod that customizes mob spawning like CustomSpawner or JustAnotherSpawner. The only changes you can make in Sponge is the same as Forge/Vanilla. I have tested the mob spawns and couldn't find any issues. If you can prove Sponge causes "excessive" spawns with a modpack such as SF3 or DW20 then I'll reopen the ticket. Make sure you test the exact same scenario with Forge only.
