### ISSUE TITLE
Exception during phase body - lumien.randomthings.entitys.EntitySoul

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeForge#1251]
This error just popped up in my server console: https://hastebin.com/ekoqimanek.md
I can't reproduce, but all the times it happened, a player clicked a soul from Random Things mod.

    Minecraft: 1.10.2
    SpongeAPI: 5.1.0-SNAPSHOT-c82cd9e
    SpongeForge: 1.10.2-2221-5.1.0-BETA-2109
    Minecraft Forge: 12.18.3.2185

**Comment by gabizou** [comment]
This is more of an exception from `EntitySoul` throwing an exception during an interact. Sponge simply wraps around to prevent the cause stack from overloading itself due to these exceptions.

**Comment by Eufranio** [comment]
Should I report to the mod author, or just ignore this error?

**Comment by Zidane** [comment]
@Eufranio 

Yes, report it.
