### ISSUE TITLE
Placing Mekanism Digital Miner Causes Phase Exception

### ISSUE THREAD

**Issue by kosakriszi** [SpongePowered/SpongeForge#1255]
Stack trace: https://gist.github.com/kosakriszi/e4d1d019e8d78a9f599c66bd512bbb05

**Comment by Aaron1011** [comment]
This is an issue with Mekanism. I've opened an issue here: https://github.com/aidancbrady/Mekanism/issues/4192

**Comment by kosakriszi** [comment]
I was having trouble figuring out if it was Mekanism or Sponge, thank you for confirming and reporting it to them!
