### ISSUE TITLE
[FML/]: NetworkDispatcher exception java.io.IOException: Error while write(...): Broken pipe [spongeforge-1.10.2-2221-5.1.0-BETA-2128]

### ISSUE THREAD

**Issue by alicheek** [SpongePowered/SpongeForge#1257]
This seems to be spamming in our logs quite durastically on our Skyfactory3 server.
Error log: http://pastebin.com/DS3TYwAi
Modpack: SkyFactory 3 3.0.6

**Comment by Aaron1011** [comment]
@alicheek Can you update to the latest SpongeForge, and upload your new log?

**Comment by alicheek** [comment]
@Aaron1011 Ok just updated it there and ill paste a log if it comes up.

**Comment by alicheek** [comment]
actually havent seen this error since so ill close for now :)
