### ISSUE TITLE
Forge ItemTossEvent not firing with Sponge

### ISSUE THREAD

**Issue by Varijon** [SpongePowered/SpongeForge#1265]
After some testing, I concluded that with SpongeForge running, the Forge ItemTossed event is not firing correctly.

I used a forge mod with an eventhandler on the ItemTossed event to test whether this event is working properly.

Using the drop button or throwing the item out of the inventory triggers the event fine.
But if a player closes their inventory with an item being held by the cursor, the event does not fire.
Not cancelled either, since the item drops normally.
Gif:
http://i.imgur.com/B8sdh8y.gifv
Note how the items got deleted when the inventory was closed, this was because it happened in a GP admin claim and the event for that drop action isn't working properly. The testing for this ticket was done locally on a separate server and updated versions.

The event fires fine with just forge running.

Versions:
spongeforge-1.10.2-2221-5.1.0-BETA-2139
forge-1.10.2-12.18.3.2221-universal

**Comment by Varijon** [comment]
Sorry for testing the fix out so late, but this did not solve the issue, ItemTossEvent is still not firing when dropping the item on cursor via inventory close. 

Versions:
forge-1.10.2-12.18.3.2221-universal
spongeforge-1.10.2-2221-5.1.0-BETA-2158

**Comment by Varijon** [comment]
Still broken in spongeforge-1.10.2-2254-5.2.0-BETA-2234.
Closing a container with item on cursor does not fire the Forge ItemToss event.

Also seems to affect item drops from fishing and pixelmon loot dropping if inventory is full.

**Comment by phit** [comment]
Tested with **spongeforge-1.12.2-2529-7.0.0-BETA-2741**, seems to not fire at all when Sponge is installed on the server.. works fine with just forge-1.12.2-14.23.0.2529

TestMod: https://gist.github.com/phit/d6b5e66efa744f83ba0f0ca4fee39181 https://phit.link/s/itemtosstest-1.0.jar

**Comment by phit** [comment]
fixed in 7.1.0-BETA-3037
