### ISSUE TITLE
[1.10.2] Forge PlayerInteractEvent.RightClickItem firing incorrectly

### ISSUE THREAD

**Issue by Varijon** [SpongePowered/SpongeForge#1266]
When SpongeForge is running, the forge PlayerInteractEvent.RightClickItem event behaves differently.
When rightclicking air, it fires the event twice.
When rightclicking a block, it fires the event once.

Without SpongeForge, the event only fires once in both cases.

Versions:
spongeforge-1.10.2-2221-5.1.0-BETA-2139
forge-1.10.2-12.18.3.2221-universal

As a sidenote, trying this with an old 2123-5.1.0-BETA-1925 jar, works as intended.

**Comment by Varijon** [comment]
Couldn't get the title quite right..
Nevertheless, it's an issue I'd like to see resolved, it's interfering with features involving items triggered on rightclick.

**Comment by emilandersson91** [comment]
Can we have some kind of response on this? As OP stated it is quite a big issue in need of being solved.

**Comment by Aaron1011** [comment]
Sorry for the delay in getting to this. This appears to be an issue with the 'pre' block interaction events we fire. I'll be talking to @bloodmc about the best way to get this resolved.

**Comment by Varijon** [comment]
Forgot you can reply to closed tickets, probably better to notify people.

The attempted fix was not successful, the behavior now is:
Rightclick with item on air= event triggers once
Rightclick with item on blocks = event doesn't trigger at all

The event fires one less time overall, compared to the previous situation.

Versions:
forge-1.10.2-12.18.3.2221-universal
spongeforge-1.10.2-2221-5.1.0-BETA-2156

**Comment by emilandersson91** [comment]
Still broken. Double-checked.
