### ISSUE TITLE
[1.10.2] Blocks not updating 

### ISSUE THREAD

**Issue by judgekreep** [SpongePowered/SpongeForge#1267]
Versions: spongeforge-1.10.2-2221-5.1.0-BETA-2142 and spongeforge-1.10.2-2221-5.1.0-BETA-2109

Water doesn't flow, lava doesn't flow, sand and gravel don't fall as intended.
When using with CustomNPCs and Pixelmon, the NPCs don't spawn unless you reload the world.
(Bone Meal only shows 1 flower or 1 tall grass, you have to reload the world for the multiple flowers/grass to be visible)
When NPCs interact with a door, you may glitch because the door seems as if its opened, but it's really closed.
Golems won't form when using iron blocks + pumpkin.

I have tested the issues with a clean install (no mods) + new configuration files and can't seem to fix the aforementioned issues.

The issue seems to be similar to this:
https://github.com/SpongePowered/SpongeForge/issues/535

Edit:
Lava and Water do spread, but it is very delayed.

**Comment by Varijon** [comment]
I've had the issue of blocks not falling when placed etc. It was because forge was outdated and no longer compatible with spongeforge, also threw console errors when placing blocks.
Just a random similar experience.

**Comment by judgekreep** [comment]
After updating, the issues were gone.
Thank you so much for sharing!
