### ISSUE TITLE
Wither breaking protected blocks

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeForge#1268]
Protected areas with GriefPrevention can be exploded by players that spawn withers near it. The wither will break the blocks, and yes they have an owner:

![a](http://image.prntscr.com/image/b4833a4af5b9496fa15c2debe828482b.png)

This player don't have permission to break the area, but the wither will still break it.

    Minecraft: 1.10.2
    SpongeAPI: 5.1.0-SNAPSHOT-6459642
    SpongeForge: 1.10.2-2221-5.1.0-BETA-2139
    Minecraft Forge: 12.18.3.2185

**Comment by axle2005** [comment]
1) This is an issue for GriefPrevention, not Sponge Forge. 
2) Do you have the proper claim flags set? Explosion is a claim flag.
