### ISSUE TITLE
[1.10.2] Dispenser not updating liquid when dispensing

### ISSUE THREAD

**Issue by Varijon** [SpongePowered/SpongeForge#1269]
When a dispenser with water bucket is triggered, it seems to place an invisible water block.
Triggering it again, fills the bucket again.

This water doesn't flow until some block update happens to it.
Hence I think the liquid block isn't updating properly when placed by a dispenser.

A gif of what I mean:
http://i.imgur.com/OBxnZyx.gifv

Versions:
forge-1.10.2-12.18.3.2221-universal
spongeforge-1.10.2-2221-5.1.0-BETA-2139

**Comment by JBYoshi** [comment]
I fixed something like this some time ago. Not sure if it was backported to 1.10.2. https://github.com/SpongePowered/SpongeCommon/pull/1115 https://github.com/SpongePowered/SpongeCommon/commit/9bd8a48407261cd35d1fbc1b77d0ba522e40e126

**Comment by Puremin0rez** [comment]
I can confirm this - found out the hard way with lava.

**Comment by Varijon** [comment]
Latest spongeforge-1.10.2-2254-5.2.0-BETA-2234 has this issue fixed.
