### ISSUE TITLE
Botania: Horn of Wild - Dupe Bug

### ISSUE THREAD

**Issue by Sir-Will** [SpongePowered/SpongeForge#1270]
Info can be found here: https://github.com/MinecraftPortCentral/GriefPrevention/issues/260

**Comment by Aaron1011** [comment]
This is [an issue in Botania](https://github.com/Vazkii/Botania/issues/2173) - there's nothing Sponge can do about this, unfortunately.

**Comment by Aaron1011** [comment]
This has been [fixed in Botania](https://github.com/Vazkii/Botania/issues/2173#event-968511646)
