### ISSUE TITLE
[1.10.2] PlayerInteractEvent.RightClickItem firing incorrectly still

### ISSUE THREAD

**Issue by Varijon** [SpongePowered/SpongeForge#1271]
The attempted fix was not successful, the behavior now is:
Rightclick with item on air= event triggers once
Rightclick with item on blocks = event doesn't trigger at all

The event fires one less time overall, compared to the previous ticket.

#1266 

Versions:
forge-1.10.2-12.18.3.2221-universal
spongeforge-1.10.2-2221-5.1.0-BETA-2156

**Comment by Aaron1011** [comment]
@Varijon: Did you intend to close this?

**Comment by Varijon** [comment]
@Aaron1011 I decided to just comment on the existing ticket later, since it's still the same issue.
See #1266
