### ISSUE TITLE
Psi block break spell removing some tile entities

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeForge#1274]
When breaking blocks with a [Block Break spell](https://github.com/Vazkii/Psi/blob/master/src/main/java/vazkii/psi/common/spell/trick/block/PieceTrickBreakBlock.java) from the Psi mod, if they are cancelled, some blocks will lose it's Tile Entities. It's reproducible when breaking IC2's machines with the spell: cables won't connect anymore, the machine will not be accessable, no blocks dropped when wrenching/breaking.

Also, after breaking Mana Pools, the mana inside it will be lost. 

Using:
    Minecraft: 1.10.2
    SpongeAPI: 5.1.0-SNAPSHOT-6459642
    SpongeForge: 1.10.2-2221-5.1.0-BETA-2147
    Minecraft Forge: 12.18.3.2185

**Comment by bloodmc** [comment]
@Eufranio Please provide a test world along with steps on what to do to reproduce this issue.

**Comment by phit** [comment]
No reply, closing this for now. Please reply with the information you have been asked for and I will reopen this issue.
