### ISSUE TITLE
Players still able to access RFTools screens if interact is cancelled

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeForge#1275]
Screens from the RFTools mod inside an area protected by GriefPrevention are accessable by players even if the interact event is cancelled. Players aren't able to open the GUI, but are able to click in the screen, activating buttons. 

Using:
    Minecraft: 1.10.2
    SpongeAPI: 5.1.0-SNAPSHOT-6459642
    SpongeForge: 1.10.2-2221-5.1.0-BETA-2147
    Minecraft Forge: 12.18.3.2185

**Comment by Aaron1011** [comment]
Unfortunately, there's not much that Sponge can do about this - the gui is [opened on the client](https://github.com/McJty/RFTools/blob/d2ada0a76ec8e/src/main/java/mcjty/rftools/blocks/screens/ScreenBlock.java#L157), using a custom packet. Without explicit support from the mod, there's probably not much that can be done here.

**Comment by Eufranio** [comment]
As I said, **Players aren't able to open the GUI, but are able to click in the screen, activating buttons.**. The GUI is closed right after be opened, so It's not the problem (I think blood did that a time ago for protection).
