### ISSUE TITLE
SpongeForge and LiteLoader still causing a crash upon world load

### ISSUE THREAD

**Issue by marshmellion** [SpongePowered/SpongeForge#1277]
semi copy of issue #1132

I have seen the aformentioned issue and would like to point out this is still a problem

it still crashes on world load with an updated setup of version between the 3 plugins/mods
forge 1.10.2 version 2221 (3 different lite loaders were tried including the newest 1.10.2 snapshot and recommended) and spongeforge 1.10.2-2221-5.1.0-BETA-2158
(i tried all version of liteloader in and out of the mods folder)

https://gist.github.com/marshmellion/1bb39c3df9115b5b5d33e1963f610298

**Comment by Deamon5550** [comment]
There is no need to open a new issue...
