### ISSUE TITLE
[6.0.0][1.11.2] UseItemStackEvent.Start and LaunchProjectileEvent Not Functioning

### ISSUE THREAD

**Issue by SjsolisZXA** [SpongePowered/SpongeForge#1278]
**Sponge Build:** spongeforge-1.11.2-2227-6.0.0-BETA-2159
**Sponge API Build:** 6.0.0-20170217.091623-41
**Forge Build:** forge-1.11.2-13.20.0.2227-universal
**Java Version:** 1.8.0_121-b13

Hello, I have the following listeners that do not function at all. Unless I'm doing something wrong, I would like to know if this can be looked at. Thanks!

````
    @Listener
    public void onPlayerConsumption(UseItemStackEvent.Start event) {
    	event.setCancelled(true);
    }

    @Listener
    public void onPotionThrow(LaunchProjectileEvent event) {
        event.setCancelled(true);
    }

**Comment by leeci** [comment]
#801

**Comment by webrsb** [comment]
Same issue here #801

**Comment by phit** [comment]
Closing this in favor of https://github.com/SpongePowered/SpongeCommon/issues/1397
