### ISSUE TITLE
[1.10.2] Whitelist message randomly displays as "java.io.IOException".

### ISSUE THREAD

**Issue by mrapplexz** [SpongePowered/SpongeForge#1282]
Logs before Sponge installation:
https://gist.github.com/mrAppleXZ/0ffa7b87c8c28e979fe966d77d8e62d1
Logs after Sponge installation:
https://gist.github.com/mrAppleXZ/f2703acb19f10acb0779655ca87be802
Is this is a Sponge issue?

**Comment by Aaron1011** [comment]
Which part of the the log displays the issue? All I was able to find was `java.io.IOException: Error while read(...): Соединение разорвано другой стороной`, which could just be a connection issue.

**Comment by mrapplexz** [comment]
@Aaron1011 I think, the logs don't contain any info about this. Maybe, several mods do something when I connect to the server and the server resets the connection before client gets "You are not whitelisted on this server" response? Or does it works differently? =)

**Comment by phit** [comment]
@mrAppleXZ is this still an issue? any idea how to reproduce it?

**Comment by Zidane** [comment]
I don't see an issue with your logs. If anything, we add more verbosity to the toString of GameProfile but otherwise that seems completely fine.
