### ISSUE TITLE
(1.10.2) Leads crash server with 'targetEntity' was not provided null pointer

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1285]
I've searched both sponge forge and sponge common repositories for similar errors.  Two separate posts came up, both closed back in 2015 listed as fixed.

Simply attempting to detach a lead from the animal it has been attached to crashes my server.

I am using the latest version of sponge available for 1.10.2: 5.1.0-BETA-2172

crashlog: http://pastebin.com/DjCe2r0d

**Comment by Aaron1011** [comment]
I can't seem to reproduce this. Can you see if removing any of the mods you have installed causes the crash to stop occuring?

**Comment by ghost** [comment]
I probably should have checked an unmodded instance first :(

The culprit is Epic Siege Mod. I'm guessing that it has something to do with epic siege hooking into the passive mob ai for hostile passive mobs.

I'm going to drop a bug report on their github as well, see if anything can be done.

**Comment by Aaron1011** [comment]
Closed in https://github.com/SpongePowered/SpongeCommon/commit/acd8119fffb56ee957f75b4bd79351be7d0e78cd.

**Comment by ghost** [comment]
Thanks for the fix :)
