### ISSUE TITLE
Error creating Sponge Timings 

### ISSUE THREAD

**Issue by Sean-Amor** [SpongePowered/SpongeForge#1287]
**Versioning:**
Minecraft Forge: 12.18.3.2221
SpongeForge: 1.10.2-2221-5.1.0-BETA-2177
SpongeAPI: 5.1.0-SNAPSHOT-794171b
Minecraft: 1.10.2
SpongeForge

**Issue:**
Cannot get timings report

**Commands:**
/sponge timings reset
/sponge timings on
/sponge timings report

**Error Log:**
https://hastebin.com/yohuquvafe.vbs

**Comment by Aaron1011** [comment]
That log appears cut off - can you get the full exception from your `latest.log` or `fml-server-latest.log`?

**Comment by Aaron1011** [comment]
Fixed in https://github.com/SpongePowered/SpongeCommon/commit/942ae729ab42a9fbd0c8bff02b12aded768b979d.
