### ISSUE TITLE
[1.10.2] Attempted to cancel a non cancellable event crash

### ISSUE THREAD

**Issue by leelawd** [SpongePowered/SpongeForge#1290]
I cannot remember exactly when this error came to light and since I am running a fairly active server, i cannot perform extensive tests to figure out what version this appeared in.

Edit: After looking through old reports, This seemed to appear after our update from SF 2165 to 2177

Here is the crash report: http://pastebin.com/0cq8ZL7d

SF: 2185
Forge: 2221

Modpack: Direwolf20 v1.5.1

**Comment by Deamon5550** [comment]
mod issue, they're cancelling an event that can't be cancelled, nothing to do with sponge

rwtema/extrautilities#1310
