### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by yepidoodles** [SpongePowered/SpongeForge#1291]
SpongeForge Version: 2221-5.1.0-BETA-2185
Forge Version: 2221
Modpack: https://www.technicpack.net/modpack/172-dragontech-testserver.408937

Error:
http://www.codesend.com/view/f8ea87195e610261b41455046de34284/

This error appears when someone places a [Digital Miner](http://wiki.aidancbrady.com/wiki/Digital_Miner) from [Mekanism](http://aidancbrady.com/mekanism/) and it pushes them out of the way (It is a single block which expands into a 3x3x2). It doesn't seem to affect the player or performance but I thought you should be aware. Also reporting it to Mekanism.

- Alice
[DragonTechMC](http://dragontechmc.com)

**Comment by Aaron1011** [comment]
@yepidoodles: Can you upload your `fml-server-latest.log`?

**Comment by Aaron1011** [comment]
This was already [fixed in the latest Mekanism](https://github.com/aidancbrady/Mekanism/issues/4192).
