### ISSUE TITLE
[1.10.2] NoSuchElement when generating chunks

### ISSUE THREAD

**Issue by Tencao** [SpongePowered/SpongeForge#1292]
Forge version - 12.18.3.2221
Sponge version - 1.10.2-2221-5.1.0-BETA-2185

Crash reports:
https://paste.ee/r/bcPwW
https://paste.ee/r/rd4qE

These crashes happened when I attempted to generate the world using a world gen plugin called ProjectBorders. By the looks of the error though, the problem seems to be sponges end so I'm coming here first.

**Comment by Deamon5550** [comment]
Duplicate spongepowered/SpongeCommon#1219

**Comment by Eufranio** [comment]
That's the same crash as mine, @Aaron1011. I think you forgot to commit the build with the debug that you commentee yesterday.
