### ISSUE TITLE
Console Spam regarding an Unknown Change

### ISSUE THREAD

**Issue by merjilin** [SpongePowered/SpongeForge#1294]
Hey there, I just this moment upgraded to spongeforge-1.10.2-2221-5.1.0-BETA-2188 and this console spam has appeared regarding an unknown change. Here's the pastebin: http://pastebin.com/5kGPzNRy
SF:  spongeforge-1.10.2-2221-5.1.0-BETA-2188
Forge: forge-1.10.2-12.18.3.2239-universal.

**Comment by merjilin** [comment]
Okay, so I just downgraded my spongeforge to the version before, along with my forge to 2221 and the spam is gone.

**Comment by Aaron1011** [comment]
@merjilin: Can you re-upgrade to the latest SpongeForge, and upload your full `fml-server-latest.log` (after the exceptions start occuring)?

**Comment by merjilin** [comment]
would you like to me update back to the newest forge or stick with 2221? And I'll do it as soon as I can.

**Comment by Aaron1011** [comment]
Stick with 2221 for now.

**EDIT**: Actually, you should upgrade to the latest Forge

**Comment by Aaron1011** [comment]
Fixed in https://github.com/SpongePowered/SpongeForge/commit/7d1cf6e346c780bcfce80d9828694512f601e839.
