### ISSUE TITLE
Can't run setupDecompWorkspace task since EventGen update

### ISSUE THREAD

**Issue by Yeregorix** [SpongePowered/SpongeForge#1297]
I cloned a recent version of SpongeForge and now, every times i'm running setupDecompWorkspace task I get this error : http://pastebin.com/C0UZJ8W1
I'm using Gradle Buildship for Eclipse.

**Comment by Aaron1011** [comment]
Does the task work if you run gradle from the command line (e.g. `./gradlew genEventImpl`)

**Comment by Yeregorix** [comment]
Yes, using cmd it works fine.

**Comment by Aaron1011** [comment]
@Yeregorix What version of Eclipse are you using?

**Comment by Yeregorix** [comment]
Eclipse JDT: 4.6.2.20161208-0625 (Neon.2)
Gradle Buildship: 1.0.21.v20161010-1640

**Comment by stephan-gh** [comment]
@Yeregorix Does this still happen? The link you posted above has expired.

**Comment by Yeregorix** [comment]
Yes, the issue is still here with the last clone of SpongeForge: https://pastebin.com/hFCyejMM

**Comment by phit** [comment]
Still an issue, tried this with bleeding.
Eclipse Oxygen Release (4.7.0) Build id: 20170620-1800

https://gist.github.com/phit/ea5d4f4914bc0d1f346674b49bf9fced

**Comment by Zidane** [comment]
@Mumfrey 

Since you are an Eclipse user, thoughts?

**Comment by Zidane** [comment]
Maybe @Deamon5550  as well?

**Comment by Deamon5550** [comment]
I use the STS gradle plugin rather than buildship so I've not had this issue.

**Comment by bloodmc** [comment]
Use STS gradle plugin.
