### ISSUE TITLE
World pre-gen crash

### ISSUE THREAD

**Issue by Yorkforce** [SpongePowered/SpongeForge#1300]
Currently trying to pregen a world with Direwolf20 1.5.1
Using nucleus 0.23.4 /world border gen command results in this crash:

http://pastebin.com/61fwYD2s

On spongeforge-1.10.2-2221-5.1.0-BETA-2178

**Comment by Aaron1011** [comment]
Can you upload your full `fml-server-latest.log`?

**Comment by Yorkforce** [comment]
Sure thing (it's actually fml-server-3.log with the crash due to auto restart)
https://www.mediafire.com/?39ynahpe8qxsi3d

(sorry for the mediafire link, github just would not accept the .log or a .zip file)

**Comment by Aaron1011** [comment]
Can you re-test on the latest SpongeForge? I've [fixed a bug](https://github.com/SpongePowered/SpongeCommon/commit/ba3642a3d8d086c270d60ad7892c8407587e8ce8) which cause causing chunk loading (and therefore CauseTracker phase completion) to happen off of the main thread.

**Comment by Yorkforce** [comment]
Same crash unfortunately:
Crash Report:
http://pastebin.com/SyLu5ptc
FML log
https://www.mediafire.com/?s4equ9q8638x5wd

Not sure if it's relevant but I did disable 'deny-chunk-requests=false' in the world.conf for UnionWorldDW1 in sponge configs

**Comment by Aaron1011** [comment]
It looks like the original issue was fixed, but now there's a new issue. I'll look into it.

**Comment by Aaron1011** [comment]
@Yorkforce Actually, it appears you're not on the latest build `1.10.2-2221-5.2.0-BETA-2199`, which contains my fix.

That crash looks to be another symptom of the bug fixed in the latest build.

**Comment by Yorkforce** [comment]
Doh my bad, I grabbed the top one, testing on 2202 now.

Edit: Yep that did it, it's generating properly now! Thanks for the super quick responses and sorry for mix up!

**Comment by Aaron1011** [comment]
No problem :) Glad to be able to help!
