### ISSUE TITLE
Tracking error on server shutdown

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeForge#1301]
When my server stops, this error is shown in the log: https://hastebin.com/qafulepuqi.md
The server doesn't crash, and no one noticed corruption, but yeah that's a error, so... I'm also usint [this](https://github.com/Stonebound/Applied-Energistics-2) version of AE2.

Using:

    Minecraft: 1.10.2
    SpongeAPI: 5.2.0-SNAPSHOT-982a6b0
    SpongeForge: 1.10.2-2221-5.2.0-BETA-2202
    Minecraft Forge: 12.18.3.2185

**Comment by bloodmc** [comment]
This was fixed recently. Update to latest SF.
