### ISSUE TITLE
Skulls aren't being rendered

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeForge#1302]
When uploading to latest SpongeForge (2202), players noticed their Skulls are not being rendered anymore, they have the Steve/Alex skin. After some tests, I realized that:

1. If the skull owner never joined the server, the skull will be rendered when in the inventory, but won't be rendered when placed in world.
2. If the skull owner joined the server once, the skull will not be rendered both in inventory and/or when placed in world.

Using:
    Minecraft: 1.10.2
    SpongeAPI: 5.2.0-SNAPSHOT-982a6b0
    SpongeForge: 1.10.2-2221-5.2.0-BETA-2202
    Minecraft Forge: 12.18.3.2185

**Comment by bloodmc** [comment]
Is this still an issue with latest builds? If not , close.
