### ISSUE TITLE
[1.11.2-2227-2204] Server crash "Exception in server tick loop"

### ISSUE THREAD

**Issue by bhi-elliot** [SpongePowered/SpongeForge#1305]
Totally took the server down. Just 1 player playing.
Hopefully this can be fixed quickly.
Thank you.

http://pastebin.com/9HdiJYFb
and
http://pastebin.com/fUfFNeQF

now with server log from the last half an hour before crash (including crash)
http://pastebin.com/sbzbDXNm

**Comment by Aaron1011** [comment]
Are you able to reproduce this consistently?

**Comment by bhi-elliot** [comment]
Thanks for the quick reply Aaron1011. No, not yet.
Note that I just updated the original post with server log showing crash:
http://pastebin.com/sbzbDXNm

**Comment by Aaron1011** [comment]
Thank you, that's very helpful. Can you upload your entire `fml-server-latest.log`, along with a list of all of the mods that you're using?

**Comment by bhi-elliot** [comment]
Couldn't upload the entire thing to pastebin because it is too large for my baby, free account. Here it is zipped and uploaded here.
[fml-server-3.zip](https://github.com/SpongePowered/SpongeForge/files/802524/fml-server-3.zip)

Hope that helps! Thank you kindly!

**Comment by bhi-elliot** [comment]
Couldn't upload the entire thing to pastebin because it is too large for my baby, free account. Here it is zipped and uploaded here.
[fml-server-3.zip](https://github.com/SpongePowered/SpongeForge/files/802525/fml-server-3.zip)

Hope that helps! Thank you kindly!

**Comment by bhi-elliot** [comment]
Happened again today, so it wasn't just a one time thing. Not sure what caused it so unable to reproduce consistently, but may have something to do with explore new land. ..

**Comment by Aaron1011** [comment]
Can you rest this on the latest SpongeForge?

**Comment by bhi-elliot** [comment]
Hi there,
I'll do my best, might be a few days. I ended up having to revert to a backup using SpongeForge build 2170 due to all the crashes. Once I get to the server location, I'll update Sponge again and let you know.
Thank you!

**Comment by bhi-elliot** [comment]
Running build 2220 for a few hours and so far no crash, which is much longer than it would stay up on build 2204

**Comment by phit** [comment]
@bhi-elliot is this still an issue?

**Comment by bhi-elliot** [comment]
Hi there,
Thank you for checking in.
I have not had this exact same crash happen. If I do, I'll re-post. I'm assuming this got fixed at some point. Currently running 1.11.2-2393-6.1.0-BETA-2468
