### ISSUE TITLE
[1.10.2] Exception during phase body

### ISSUE THREAD

**Issue by FiveEYZ** [SpongePowered/SpongeForge#1306]
Got some errors showing in my log

Exception during phase body
https://gist.github.com/FiveEYZ/0dd7d4c9e3cdfcb862fcd86418c612a4

fml-server-latest:
https://gist.github.com/FiveEYZ/7db8f279af14e626c42b0abdfec7bb15

Minecraft: 1.10.2
SpongeAPI: 5.1.0-cf4dfb1
SpongeForge: 1.10.2-2221-5.1.0-BETA-2203
Minecraft Forge: 12.18.3.2239
Modpack: Direwolf20 1.6.2

**Comment by Aaron1011** [comment]
Can you open a separate issue for each one of those?

**Comment by bloodmc** [comment]
This was fixed recently. Update to latest SF.
