### ISSUE TITLE
PluginContainer.getName() returns null if it hasn't been set in the @Plugin annotation

### ISSUE THREAD

**Issue by dags-** [SpongePowered/SpongeForge#1309]
**Forge**: `1.10.2-12.18.3.2221`
**SpongeForge**: `1.10.2-2221-5.1.0-BETA-2203`

I think it's because [this check in SpongeModPluginContainer](https://github.com/SpongePowered/SpongeForge/blob/bleeding/src/main/java/org/spongepowered/mod/plugin/SpongeModPluginContainer.java#L134) is no longer relevant because forge reads the mcmod.meta file packaged in the plugin jar, so the ModMetadata isn't flagged as "autogenerated".

This can lead to unexpected NPEs later down the line when a plugin (or sponge itself) tries to access the plugin's name.

Example plugin and console output below:
https://gist.github.com/dags-/b79a868a3c3cd95efd96a9befbfeb20b

**Comment by stephan-gh** [comment]
Fixed in https://github.com/SpongePowered/SpongeForge/pull/1106
