### ISSUE TITLE
Game Crash Whilst Rendering Screen

### ISSUE THREAD

**Issue by Vladgina** [SpongePowered/SpongeForge#1310]
Whenever I read the Origins of Darkness and come to a screen with recipes it crashes. Sometimes it takes a bit, sometimes it's when I hover over them, sometimes it's immediately.

**Comment by Aaron1011** [comment]
Can you upload any generated crashlog, your `latest.log`, and your `fml-client.latest.log`?

**Comment by phit** [comment]
so little info, but I tested this with 
CyclopsCore-1.11.2-0.10.6.jar
EvilCraft-1.11.2-0.10.29.jar
jei_1.11.2-4.5.0.291.jar
spongeforge-1.11.2-2393-6.1.0-BETA-2468.jar

navigated the "Origins of Darkness" for a while, hovered over recipes and clicked around couldn't get my game to crash
