### ISSUE TITLE
Extra Utils Quarry - Unexpected World Change Detected

### ISSUE THREAD

**Issue by KasperFranz** [SpongePowered/SpongeForge#1311]
Error in console: https://gist.github.com/KasperFranz/45d99ae80c2b888da523c257ba8e81fc

Running SpongeForge: spongeforge-1.10.2-2221-5.1.0-BETA-2208.

Extra utils version: 1.1.1

**Comment by Aaron1011** [comment]
I've reproduced the issue, and should have a fix soon.

**Comment by Aaron1011** [comment]
Fixed in [the latest SpongeForge](https://github.com/SpongePowered/SpongeForge/commit/5e4abf30d7db9a344a25a91c69d02018f9d51d4c).
