### ISSUE TITLE
[1.10.2] Exception Exiting Phase

### ISSUE THREAD

**Issue by FiveEYZ** [SpongePowered/SpongeForge#1312]
Exception Exiting Phase
https://gist.github.com/FiveEYZ/4e7e5701f15575034585cb680f3513ee

**Comment by Aaron1011** [comment]
This is another mod which doesn't properly handle having `writeToNbt` called before it's ticked. I'll open an issue with the dev, but I also think that Sponge might want to catch exceptions thrown from `writeToNBT` (when we create a Forge `BlockSnapshot`).

**Comment by Eufranio** [comment]
There's one with AE2 too. Wanna see the stacktrace?

**Comment by Aaron1011** [comment]
Yes, thanks!

**Comment by Zidane** [comment]
Closing as it isn't a Sponge issue. While, as @Aaron1011 pointed out, we could catch exceptions from writeToNbt, that would be a bandaid and isn't our job to hide mod issues.
