### ISSUE TITLE
[1.10.2] Exception attempting to capture or spawn an Entity!

### ISSUE THREAD

**Issue by FiveEYZ** [SpongePowered/SpongeForge#1313]
Exception attempting to capture or spawn an Entity!
https://gist.github.com/FiveEYZ/d126ee8285ed6e4ea3a220c32ee3a71a

**Comment by SSDFDFDF** [comment]
I got the same exception.

**Comment by Aaron1011** [comment]
This is a bug with how Sponge handles explosions, which I'll be fixing.
