### ISSUE TITLE
[1.10.2] - NetworkDispatcher

### ISSUE THREAD

**Issue by comdarksider** [SpongePowered/SpongeForge#1317]
I use spongeforge-1.10.2-2221-5.1.0-BETA-2210.
error NetworkDispatcher exception java.io.IOException: An existing connection was forcibly closed by the remote host

Link error :  
1. Paste bin -  http://pastebin.com/EPt55ZWP
2. Github -  https://gist.github.com/comdarksider/23635a7994e0fedd7c9eb9629c59d869

**Comment by Aaron1011** [comment]
This looks like the the client crashed. Can you try to get a `latest.log`, `fml-client-latest.log`, and any crash reports from affected users (e.g. `comdarksider`).

Also, please upload your full `fml-server-latest.log`

**Comment by Zidane** [comment]
Closing due to no response.
