### ISSUE TITLE
[1.10.2] World load on startup is broken

### ISSUE THREAD

**Issue by EwoutV** [SpongePowered/SpongeForge#1318]
As of SpongeForge 1.10.2-2221-5.1.0-BETA-2117, it seems like the abillity to load a world on startup is broken. When I perform the project worlds command /world loadonstartup <world> true, it doesn't load the world on startup. Also, all settings get reset for that world when I restart the server. Downgraded my sponge to 1.10.2-2221-5.1.0-BETA-2113, and the issue is gone.

**Comment by Aaron1011** [comment]
`/world` isn't a built-in Sponge command. What plugin are you using?

**Comment by phit** [comment]
>the project worlds command

https://forums.spongepowered.org/t/project-worlds-v0-11-4-world-manager/10170

**Comment by Aaron1011** [comment]
Oops, I somehow missed that.

**Comment by EwoutV** [comment]
Tried it with multiple plugins, without any success. It only worked on spongeforge 1.10.2-2221-5.1.0-BETA-2113 and below.

**Comment by EwoutV** [comment]
@Aaron1011 Definetly a Sponge bug. I'm not a developer, but I think [this](https://github.com/SpongePowered/SpongeCommon/commit/dbf3c828d24cba094ef118b6e5aa1086a3db2b17) might have something to do with the issue.

**Comment by phit** [comment]
have you tried setting it in the sponge configs not with a plugin?

**Comment by EwoutV** [comment]
Wow, I didn't know there was an option for that, it worked, thanks! Still strange how Nucleus and pwp fail loading the world when the server starts on Sponge versions 2117 and above...
