### ISSUE TITLE
[1.10.2] Railcraft's tunnel bore is able to place tracks in protected areas

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeForge#1319]
Railcraft is a mod focused in trains, rails, and etc. It has a Tunnel Bore, that is basically a locomotive that will place down tracks and mine a 3x3 area in front of it. It looks like this:

![1](http://image.prntscr.com/image/b3078714e6dd499cab56d495c08f4e48.png)

It has a Bore Head that will allow the locomotive to break blocks in front of it. It works just fine, respecting server protection, but it also place down tracks while walking:

![2](http://image.prntscr.com/image/4e0775b590b0466b832acb47809dda79.png)

And those tracks are placed even if the player don't have permission to place blocks in the area, not respecting the server protection.

Using:
    Minecraft: 1.10.2
    SpongeAPI: 5.1.0-cf4dfb1
    SpongeForge: 1.10.2-2221-5.1.0-BETA-2208
    Minecraft Forge: 12.18.3.2239

**Comment by liach** [comment]
Well, `ChangeBlockEvent` is supposed to be fired. Isn't this event fired?

**Comment by Eufranio** [comment]
I'm not that good debugging, but testing with GriefPrevention, it isn't firing any events (or at least they're not being checked). It fires the EntityMoveEvent when moving, but that's all.

**Comment by CovertJaguar** [comment]
I'm probably missing the events on that action.

**Comment by Eufranio** [comment]
User error, sorry. In SpongeForge, they're protected, but you may want to add those events anyway @CovertJaguar.
