### ISSUE TITLE
AE2 + Sponge Unexpected World Change

### ISSUE THREAD

**Issue by Time6628** [SpongePowered/SpongeForge#1322]
Getting this on spongeforge-1.10.2-2221-5.2.0-BETA-2215 and appliedenergistics2-rv4-alpha-11
https://gist.github.com/Time6628/bfc820a7f5f644093237ab6cca352e8a

**Comment by bloodmc** [comment]
@Aaron1011 please look into this.

**Comment by ghost** [comment]
Here's another example with SF 2219:
http://pastebin.com/jUxfphiV

**Comment by Aaron1011** [comment]
We're not properly handling changes that occur while a tile entity is loading. I'll create a new phase to handle this.

**Comment by Brend-Smits** [comment]
https://hastebin.com/ecomoradas.md
Same with farming stations

Causes lag spikes while these errors are being spammed.

**Comment by KasperFranz** [comment]
not sure if related but this is also in the same area (running latest sponge 2226) https://gist.github.com/KasperFranz/6d4272353ff5695a7796fb020a22943f

**Comment by JaSpr** [comment]
Same issue.  The AE2 Inscriber is using a LOT more time per tick since this started last week.

https://gist.github.com/JaSpr/d988d981d294f97eb0072c3ade563582

**Comment by Time6628** [comment]
I think they got that it is an issue.

**Comment by JaSpr** [comment]
@Aaron1011 Any update on this?  This bug causes massive lag on our server as suddenly (seemingly out of nowhere) the console will start spam logging error messages so much that the server slows to a crawl, even with 16GB dedicated memory for the process.

**Comment by bloodmc** [comment]
@JaSpr @Time6628 I added a config check to ignore the error until it gets fixed. Just make sure causetracker verbose is set to false in sponge's global.conf

**Comment by Time6628** [comment]
Thanks.
