### ISSUE TITLE
[1.10.2] RFTools Elevator's are bugging out

### ISSUE THREAD

**Issue by leelawd** [SpongePowered/SpongeForge#1326]
First of all, I am not sure if this is a GriefPrevention issue or SpongeForge issue BUT when i updated both to their latest version, the RFTools elevators would not work as intended. 

If i reverted either GP or SF back to the previously used version, everything would be fine. It only seems to do it when both are updated.

This also happens outside of a GP Claim.

I am unsure of what version's this specifically appears in.

But i updated like this:
SF: 2185 -> 2210 (since versions in between this caused my log files to be in the GB's)
GP: 2.3.1.257 -> 2.3.1.267

Here are a few Gifs of what happens:
1 - When the elevator attempts to go up
https://gyazo.com/14961e494de09f1f27f856bbb8b5fd2e

2 - when the elevator goes down
https://gyazo.com/5d392246377689c8ef86d5ef5c146ef2

When it goes up, it just reverts back to where it came from.
And when it goes down, it goes to where it was intended but also leaves behind duplicate blocks where it came from.

**Comment by ghost** [comment]
I thinks its GP bug: https://github.com/MinecraftPortCentral/GriefPrevention/issues/341

try latest build of GP

**Comment by leelawd** [comment]
I will test this soon, thanks for the information

**Comment by leelawd** [comment]
Thank you, it was a GP Issue. Closing since it has been fixed.
