### ISSUE TITLE
Explosion event not fired with Sponge.

### ISSUE THREAD

**Issue by Raycoms** [SpongePowered/SpongeForge#1327]
We offer a protection for all explosions with our mod, but it seems it doesn't work with sponge.

    public void on(final ExplosionEvent.Detonate event)
    public void on(final ExplosionEvent.Start event)

SpongeForge: 1.10.2-2221-5.1.0-BETA-2156

**Comment by Raycoms** [comment]
Someone was able to analyze this?

**Comment by Raycoms** [comment]
Any update on this?

**Comment by gabizou** [comment]
> Any update on this?

Just wait on a fix, when the fix is in, the issue will be closed. I can't provide ETA's except that I'm aware of the issue and already working on a fix.

**Comment by bloodmc** [comment]
No longer an issue in latest builds.

**Comment by Raycoms** [comment]
Please reopen, I just tried it with the newest 1.10
