### ISSUE TITLE
NullPointerException with Forestry

### ISSUE THREAD

**Issue by Nedelosk** [SpongePowered/SpongeForge#1332]
We have a problem with forestry. We have an exception that only is thrown if anyone plays with spongepowered. There is the forestry issue: https://github.com/ForestryMC/ForestryMC/issues/1524. It would be great if you could help us.

**Comment by bloodmc** [comment]
@Nedelosk Please provide a test world with ONLY Forestry and SF and list steps to reproduce.

**Comment by phit** [comment]
No reply, closing this for now. Please reply with the information you have been asked for and I will reopen this issue.
