### ISSUE TITLE
WrapperCommandSource errors

### ISSUE THREAD

**Issue by Slind14** [SpongePowered/SpongeForge#1333]
Better Questing allows a command execution as reward which packs like forever stranded utilize in their first quest for example. Unfortunately sponge does not know how to deal with it, which causes the quest claiming to never complete, allowing to reclaim it over and over again, causing an endless supply of rewards. Further more the command is not being executed which is an issue in case it is required to progress.

**Sponge** `1.10.2-2221-5.2.0-BETA-2219`
**Better Questing** `BetterQuesting-2.3.225`

```
│2017-03-07 02:40:18 | [FATAL] Error executing task                                                                                                                                                          ││                             │
│2017-03-07 02:40:18 | [RAW] java.util.concurrent.ExecutionException: java.lang.AbstractMethodError                                                                                                          ││                             │
│2017-03-07 02:40:18 | [RAW] ?at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_111]                                                                                                  ││                             │
│2017-03-07 02:40:18 | [RAW] ?at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_111]                                                                                                     ││                             │
│2017-03-07 02:40:18 | [RAW] ?at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]                                                                                                            ││                             │
│2017-03-07 02:40:18 | [RAW] ?at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:235) [SpongeImplHooks.class:1.10.2-2221-5.2.0-BETA-2219]                                        ││                             │
│2017-03-07 02:40:18 | [RAW] ?at net.minecraft.server.MinecraftServer.redirect$onRun$zhm000(MinecraftServer.java:3931) [MinecraftServer.class:?]                                                             ││                             │
│2017-03-07 02:40:18 | [RAW] ?at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]                                                                       ││                             │
│2017-03-07 02:40:18 | [RAW] ?at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]                                                                          ││                             │
│2017-03-07 02:40:18 | [RAW] ?at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]                                                                       ││                             │
│2017-03-07 02:40:18 | [RAW] ?at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]                                                                                ││                             │
│2017-03-07 02:40:18 | [RAW] ?at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]                                                                                                                         ││                             │
│2017-03-07 02:40:18 | [RAW] Caused by: java.lang.AbstractMethodError                                                                                                                                        ││                             │
│2017-03-07 02:40:18 | [RAW] ?at org.spongepowered.common.command.WrapperCommandSource.of(WrapperCommandSource.java:116) ~[WrapperCommandSource.class:1.10.2-2221-5.2.0-BETA-2219]                           ││                             │
│2017-03-07 02:40:18 | [RAW] ?at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1082) ~[bd.class:?]                                                                                      ││                             │
│2017-03-07 02:40:18 | [RAW] ?at bq_standard.rewards.RewardCommand$2.run(RewardCommand.java:80) ~[RewardCommand$2.class:?]                                                                                   ││                             │
│2017-03-07 02:40:18 | [RAW] ?at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_111]                                                                                      ││                             │
│2017-03-07 02:40:18 | [RAW] ?at net.minecraft.server.MinecraftServer.redirect$onCall$zhm000(MinecraftServer.java:3917) ~[MinecraftServer.class:?]                                                           ││                             │
│2017-03-07 02:40:18 | [RAW] ?at net.minecraft.server.MinecraftServer.func_175586_a(MinecraftServer.java:1347) ~[MinecraftServer.class:?]                                                                    ││                             │
│2017-03-07 02:40:18 | [RAW] ?at net.minecraft.server.MinecraftServer.func_152344_a(MinecraftServer.java:1359) ~[MinecraftServer.class:?]                                                                    ││                             │
│2017-03-07 02:40:18 | [RAW] ?at bq_standard.rewards.RewardCommand.claimReward(RewardCommand.java:75) ~[RewardCommand.class:?]                                                                               ││                             │
│2017-03-07 02:40:18 | [RAW] ?at betterquesting.questing.QuestInstance.claimReward(QuestInstance.java:466) ~[QuestInstance.class:?]                                                                          ││                             │
│2017-03-07 02:40:18 | [RAW] ?at betterquesting.network.handlers.PktHandlerClaim.handleServer(PktHandlerClaim.java:32) ~[PktHandlerClaim.class:?]                                                            ││                             │
│2017-03-07 02:40:18 | [RAW] ?at betterquesting.network.PacketQuesting$HandleServer$1.run(PacketQuesting.java:78) ~[PacketQuesting$HandleServer$1.class:?]                                                   ││                             │
│2017-03-07 02:40:18 | [RAW] ?at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_111]                                                                                      ││                             │
│2017-03-07 02:40:18 | [RAW] ?at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_111]                                                                                                     ││                             │
│2017-03-07 02:40:18 | [RAW] ?at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]                                                                                                           ││                             │
│2017-03-07 02:40:18 | [RAW] ?... 7 more 
```

**Comment by Slind14** [comment]
@Funwayguy In case you want to add anything.

**Comment by JBYoshi** [comment]
Confirmed to be a Sponge bug. I personally don't have time to test and upload a fix right now (I'm on my phone), but one of the other developers could.

For the technical-minded: The fix (as far as I can see) is changing `MixinICommandSender` to not implement `IMixinCommandSender` and to use `WrapperCommandSource.of()` instead of `this.asCommandSource()`.

**Comment by Slind14** [comment]
@JBYoshi do you have some time on the weekend? I'm around if you want me to test a version :)

**Comment by JBYoshi** [comment]
@Slind14 I submitted a fix, but it won't be officially released until the core devs accept it. https://github.com/SpongePowered/SpongeCommon/issues/1247

**Comment by Slind14** [comment]
Thank you.

**Comment by Noppes** [comment]
Im having the same issue
`java.lang.AbstractMethodError: noppes.npcs.NoppesUtilServer$1$1.asCommandSource()Lorg/spongepowered/api/command/CommandSource;                      
     org.spongepowered.common.command.WrapperCommandSource.of(WrapperCommandSource.java:116)                                                         
     net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1082)                                                                        
     net.minecraft.tileentity.CommandBlockBaseLogic.func_145755_a(SourceFile:114)                                                                    
     noppes.npcs.NoppesUtilServer.runCommand(NoppesUtilServer.java:252)                                                                              
     noppes.npcs.NoppesUtilServer.runCommand(NoppesUtilServer.java:163)                                                                              
     noppes.npcs.NoppesUtilServer.openDialog(NoppesUtilServer.java:151)                                                                              
     noppes.npcs.entity.EntityNPCInterface.func_184645_a(EntityNPCInterface.java:451)                                                                
     net.minecraft.entity.EntityLiving.func_184230_a(EntityLiving.java:1229)                                                                         
     net.minecraft.entity.player.EntityPlayer.func_184822_a(EntityPlayer.java:1161)                                                                  
     net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:2364)                                                        
     net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:68)                                                                 
     net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:12)                                                                 
     org.spongepowered.common.network.PacketUtil.lambda$onProcessPacket$0(PacketUtil.java:157)                                                       
     org.spongepowered.common.network.PacketUtil$$Lambda$832/581692968.call(Unknown Source)                                                          
     org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseTracker.java:160)                                                       
     org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:156)                                                                
     net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjh000(SourceFile:539)                                                        
     net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)                                                                                     
     java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)                                                                             
     java.util.concurrent.FutureTask.run(Unknown Source)                                                                                             
     net.minecraft.util.Util.func_181617_a(SourceFile:45)                                                                                            
     org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:241)                                                                
     net.minecraft.server.MinecraftServer.redirect$onRun$zhn000(MinecraftServer.java:3928)                                                           
     net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668)                                                                     
     net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)                                                           
     net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)                                                                     
     net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)                                                                              
     java.lang.Thread.run(Unknown Source)`
