### ISSUE TITLE
Incompatible with Alternate Terrain Generation

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1334]
If you use sponge + this mod is causes all new chunks biomes to be ocean. Also when generating a new world it says "Unable to find spawn biome."

https://minecraft.curseforge.com/projects/alternate-terrain-generation

**Comment by Unnoen** [comment]
Noticing this issue too.

**Comment by afannnn** [comment]
This was fixed in the latest version of ATG.
