### ISSUE TITLE
EnderIO world change error.

### ISSUE THREAD

**Issue by merjilin** [SpongePowered/SpongeForge#1335]
Hey, thanks for fixing the errors with the ExtraUtils2 Quantum Quarries! However it seems a new one has occurred. Specifically a change due to the EnderIO farming station.
Error: http://pastebin.com/D7B4kEDf
FML log (converted to txt it be posted here):
[fml-server-latest.txt](https://github.com/SpongePowered/SpongeForge/files/825285/fml-server-latest.txt)
Spongeforge: spongeforge-1.10.2-2221-5.2.0-BETA-2223
Forge: forge-1.10.2-12.18.3.2254-universal

**Comment by merjilin** [comment]
I've just had a few more errors occur, one of which was to do with quantum quarries again.
[Uploading fml-server-latest (2).txt…]()

**Comment by Aaron1011** [comment]
This appears to be an issue with TickProfiler

**Comment by merjilin** [comment]
Okay, so I updated the skyfactory 3 server to the newest build (3.0.8) along with forge to 2254 and spongeforge to 2231 and errors seemed to have stopped. I haven't touched tickprofiler either, so I'm not too sure what has fixed it.
