### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by iLefty** [SpongePowered/SpongeForge#1337]
Server is crashing for the unclear reason for me. I fight against this error, long time.
Here you will see today's crash-reports (4 times of this day):
https://yadi.sk/d/nNYwpWrB3FHqKM
All information of server is present at report. I need help!
P.S. At forge forum, have told that a problem in Sponge.

**Comment by Deamon5550** [comment]
Please upload your logs to a paste site like http://gist.github.com/ for the future.

This one looks like a world gen issue.

**Comment by iLefty** [comment]
http://pastebin.com/2jtkk1PA
http://pastebin.com/zimdVH5v
http://pastebin.com/hCpPa4d7
http://pastebin.com/qv4HZsp3
http://pastebin.com/t1VzEWBt
http://pastebin.com/SnVNaLbQ
All crashes.

**Comment by Deamon5550** [comment]
The worldgen one is definitely a duplicate of #1289 the rest are all something else.

**Comment by iLefty** [comment]
Really? I think, that's different...

**Comment by Deamon5550** [comment]
This one http://pastebin.com/hCpPa4d7 is the exact same issue. The rest are all the something else, but also something I've seen before, I think someone mentioned it was a forge bug, or at least that it occurs in forge as well without sponge.

**Comment by iLefty** [comment]
On forge forum said, that this bug in sponge.

**Comment by iLefty** [comment]
http://www.minecraftforge.net/forum/topic/52425-server-crash-1102/

**Comment by Deamon5550** [comment]
Test without sponge and see if they still occur.

**Comment by iLefty** [comment]
There is no opportunity to test without sponge. I will lose plugins for protection and players will create chaos.

**Comment by iLefty** [comment]
http://www.minecraftforge.net/forum/topic/52425-server-crash-1102/
So, people said, that error in Sponge...

**Comment by LeftBoy** [comment]
Thank you that you undertake nothing. Server crashes continues.

**Comment by Time6628** [comment]
Whitelist the server and test without sponge. If you want your issue fixed, you need to test it with your setup.

**Comment by iLefty** [comment]
Without players, the problem doesn't arise. 
Tested. Without sponge server worked 20 hours.

**Comment by iLefty** [comment]
http://pastebin.com/GHWNJFPG
http://pastebin.com/WPRVE9qH
http://pastebin.com/wNbSf9Wc
http://pastebin.com/3Z5WxdcC
Four more crashes, for today, with sponge.

**Comment by iLefty** [comment]
http://pastebin.com/ujfzRaD3
http://pastebin.com/AjUtZxHV
http://pastebin.com/6ia8t9vL
http://pastebin.com/ihD4Xipk
http://pastebin.com/9nXgk4iw
Five more crashes.
YES I LIKE IT! (No.)

**Comment by LeftBoy** [comment]
Perhaps I found the reason. Crash was most likely because of function "tracking". I will test.

**Comment by iLefty** [comment]
@Deamon5550, what I must do, that crash wasn't?

**Comment by Time6628** [comment]
They can't help you unless you can reproduce it.

**Comment by iLefty** [comment]
What? I sad, Server normally work without sponge... 20 hours.

**Comment by me4502** [comment]
Do you have any plugins that change blocks? Like changes water to slabs (Or vice versa)?

**Comment by iLefty** [comment]
In crash-reports present all information about installed plugins and mods. I think, I haven't.

**Comment by bloodmc** [comment]
Reopen if this is still an issue with SpongeForge.
