### ISSUE TITLE
Mob Spawners not spawning mobs

### ISSUE THREAD

**Issue by diluvium** [SpongePowered/SpongeForge#1338]
Using spongeforge-1.11.2-2227-6.0.0-BETA-2224.jar, mob spawners are no longer spawn mobs. If I remove spongeforge from the mods folder, then mobs happily spawn again. I can't seen anything in the logs to indicate a problem.

**Comment by kashike** [comment]
Related to https://github.com/SpongePowered/SpongeCommon/issues/1241 maybe?
