### ISSUE TITLE
Load Plugin Mixins when plugin is located outside mods folder

### ISSUE THREAD

**Issue by Grinch** [SpongePowered/SpongeForge#1339]
Currently plugins that have mixins only have their mixins loaded when located in the ./mods folder. If you put the plugin in ./mods/plugins or any other directory then the mixins for that plugin are simply not loaded.

**Comment by ktole1999** [comment]
i am just curious, would there be a certain scenario where you would not want this in the mods folder?

**Comment by Grinch** [comment]
@ktole1999 In most cases probably not. However Sponge does natively support ./mods/plugins for a plugin path and that is configurable. We should be searching the configured path as well.

**Comment by ktole1999** [comment]
gotcha, ok i misread your comment. i saw /plugins rather than /mods/plugins. my bad

**Comment by Mumfrey** [comment]
No this is not possible, you cannot open a box with the crowbar which is inside.

**Comment by Mumfrey** [comment]
Clarification:

The mechanism by which mixins can be bundled in a plugin jar is via the Mixin Tweaker, the tweaker is *discovered by Forge* in the mod container (jar) during the coremod scan, **as is the Mixin Tweaker for SpongeForge**. When SpongeForge applies its PREINIT mixins, it adds support into the mod discoverer for scanning in the second location. This second location is searched for **mods** not **coremods** (and tweakers) which were *already enumerated at this point in time*.

*A jar (container) containing a plugin can also contain a mod, it can also contain a coremod, however if you want a coremod to be loaded then Forge has to find it. Forge will only search for coremods in its configured location*.

If you are desperate to work around this, then specify the mod jar on the command line.

Further clarification available [here](https://github.com/SpongePowered/SpongeDocs/pull/572#issuecomment-276658115)
