### ISSUE TITLE
AE2/ AE2Stuff issue with sponge 

### ISSUE THREAD

**Issue by Bennyboy1695** [SpongePowered/SpongeForge#1344]
Enabled verbose as i know its helpful. But every few minutes we get a 10 second lag spike and then quite commonly we get this in console - https://gist.github.com/Bennyboy1695/ae1c2698156849b97a9aafbed32a4d82

**Comment by ktole1999** [comment]
https://github.com/SpongePowered/SpongeForge/issues/1322
