### ISSUE TITLE
Almost no mobs spawning

### ISSUE THREAD

**Issue by phit** [SpongePowered/SpongeForge#1345]
Since the async light changes, lots of people on my servers are reporting none to very few hostile mod spawns. Turning off async-lighting in the global.conf fixes it, this is consistent across various modpacks and I also heard the same thing from a few other server owners.

Tested with 5.2.0-BETA-2215 and 5.2.0-BETA-2226
Maybe related to #1338

edit: I guess it's worth mentioning, I have made no other changes besides turning on Bungee to my global.conf and tried deleting the whole sponge config folder too.

**Comment by Mohron** [comment]
I'm also encountering this issue!

**Comment by Aaron1011** [comment]
@bloodmc can you help me look into this?

**Comment by kashike** [comment]
Related to https://github.com/SpongePowered/SpongeCommon/issues/1241 maybe?

**Comment by Mohron** [comment]
Given that lighting and squid spawning is not linked in anyway I would say no.

**Comment by Aaron1011** [comment]
@Mohron Actually, the issues may be related. The mob spawner takes lighting into account, and we've had issues in the past with async lighting interfering with proper chunk loading and unloading.

**Comment by Mohron** [comment]
I guess I'm just thinking since squid spawning doesn't have lighting requirements changing lighting shouldn't affect them. But you guys know best.

**Comment by JaSpr** [comment]
We have been running the latest beta build of spongeforge (2231) all week, and still cannot get squids to spawn anywhere on the server.

**Comment by phit** [comment]
squids and bats, can confirm
turning off async lighting does not fix it though! so I don't think it's related to this issue

**Comment by FiveEYZ** [comment]
got lots of squids spawning after this fix, but i have yet to see any bats. 

Did i miss something to make them spawn?

**Comment by phit** [comment]
might be worth a shot resetting your sponge global.conf, I have seen plenty of bats on both FTB Beyond and Direwolf20
