### ISSUE TITLE
Woot Looting Issue

### ISSUE THREAD

**Issue by bookerthegeek** [SpongePowered/SpongeForge#1346]
Heyo!
So Cross posting this with some testing done for you. https://github.com/Ipsis/Woot/issues/139. Seems we are having an issue with the looting enchantment. (Please forgive the lack of Java speak & concrete documentation)

[Woot](https://github.com/Ipsis/Woot): A mod adding a multiblock structure that will generate mob drops at the cost of RF. 
It does this by spawning the mobs (In this case a slime) instantly killing the mob with either non-enchanted damage, or one of the three levels of the looking enchantment. The issue we are having is that Woot is not able to tell that it killed the mob with the looting enchantment (That is the effect, not sure of the cause)

Here are two output logs from Woot;:
 - [Run wo/ SpongeForge](https://gist.github.com/bookerthegeek/773c30b70f9c11e91606c551405d553f)
 - [Run w/ SpongeForge](https://gist.github.com/bookerthegeek/b4a958f5814867da5201c3d1b60e5414)

You will notice that the one without sponge, WOOT is able to determine that the mob was killed with Looting 3, yet on the exact same MultiBlock structure with sponge installed while it is still killing the mobs, it only is registering it as non-looting kills.

You can find the original issue [HERE ](https://github.com/Ipsis/Woot/issues/139)

EDIT: Forgot Versions:
* spongeforge-1.10.2-2221-5.2.0-BETA-2226
* woot-1.10.2-1.2.5
* forge-12.18.3.2254

**Comment by phit** [comment]
According to [this comment](https://github.com/Ipsis/Woot/issues/139#issuecomment-282484211) by the mod dev, this should cause it:
https://github.com/SpongePowered/SpongeForge/blob/stable-5/src/main/java/org/spongepowered/mod/mixin/core/fml/common/eventhandler/MixinEventBus.java#L79

**Comment by JaSpr** [comment]
Can confirm

**Comment by JaSpr** [comment]
bump.

**Comment by MiscMC** [comment]
How did you do that ?

**Comment by gabizou** [comment]
> How did you do that ?

Do what? Add tags?

**Comment by LIRIKKER** [comment]
Also having this issue! Any ETA on when a fix will be released?

**Comment by JojoLesGo** [comment]
I too am having this issue and would love to see a solution!

**Comment by Ciannicay** [comment]
Any news so far on that matter?

**Comment by bookerthegeek** [comment]
They are working on it, please be patient as they get this resolved. We don't particularly need everybody jumping in with "Me to" as they have already confirmed the issue.

**Comment by JaSpr** [comment]
Understandable, although this issue has been open for quite a while, and affects many people.  Periodic updates would be helpful at staving off requests for comment.

**Comment by bookerthegeek** [comment]
While I agree that some update would be nice, I would much rather them fix it then then worry about keeping us informed.

**Comment by Ipsis** [comment]
For reference from Woot as an example of why this is causing an issue and at the request of @ryantheleach

Handling of LivingDropsEvent:
https://github.com/Ipsis/Woot/blob/master/src/main/java/ipsis/woot/event/HandlerLivingDropsEvent.java
This is used to learn which loot is dropped by which mob.
Note that I register at the lowest priority as I want all other mods to add their loot.

Spawning of mobs:
https://github.com/Ipsis/Woot/blob/master/src/main/java/ipsis/woot/manager/SpawnerManager.java#L171
https://github.com/Ipsis/Woot/blob/master/src/main/java/ipsis/woot/manager/SpawnerManager.java#L201
This is the code that I use to spawn the mobs, which should cause the generate the LivingDropsEvent to be raised.

**Comment by bookerthegeek** [comment]
Although, @gabizou maybe a small update would be appreciated?

**Comment by Mohron** [comment]
This problem exists in 1.12.2
https://github.com/Ipsis/Woot/issues/288
woot-1.12.2-0.0.4
spongeforge-1.12.2-2555-7.0.0-BETA-2794

**Comment by JoeSGT** [comment]
Still an issue with 
SpongeForge - 1.12.2-2611-7.1.0-BETA-2964
woot-1.12.2-1.0.0
