### ISSUE TITLE
Minecolonies Worker Range Bug

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1347]
There is currently a bug with sponge with the mine colonies mod where if a player is not inside the chunk a worker is in they work at an extremely slow speed.

**Comment by gd71** [comment]
its a matter of sponge configuration
disable entity-activation-range for minecolonies if you want citizens to continue their life when players are at far distance
```            minecolonies {
                defaults {}
                # Set to false if you want mod to ignore entity activation rules and always tick.
                enabled=false
                entities {}
            
```

**Comment by bloodmc** [comment]
As gd71 stated, update your entity-activation to handle minecolonies. You can disable it entirely for the mod, just enable auto-populate then set enabled to false for minecolonies.
