### ISSUE TITLE
Actually Additions Traveler's Sack Item Dupe

### ISSUE THREAD

**Issue by phit** [SpongePowered/SpongeForge#1351]
Reproduction
https://github.com/Ellpeck/ActuallyAdditions/issues/674

Tested in 1.10.2-2221-5.2.0-BETA-2226
Modpack was FTB Beyond, dupe only happens on a Sponge server not in singleplayer

**Comment by jackytuutykcaj** [comment]
https://youtu.be/PB8Gb4h85-o

**Comment by jackytuutykcaj** [comment]
bump!
Is this fixed yet?

**Comment by JaSpr** [comment]
While this is a sponge issue, Ellpeck (actually additions author) released a workaround to prevent the duplication bug.  Fix can be found in release 1.10.2-r105
