### ISSUE TITLE
Crash when placing Opium cores from ExtraUtils2

### ISSUE THREAD

**Issue by Bennyboy1695** [SpongePowered/SpongeForge#1352]
As title said when placing an opium core from ExtraUtils2 the server instantly crashes because of sponge cause tracker.
http://pastebin.com/6RP3wTS4

**Comment by lurr** [comment]
Please post a full log, and use the latest extrautils2 (1.3.3) as it fixes issues with crashes when placing Opinium Blocks/Klein Bottles if you aren't already.

**Comment by bloodmc** [comment]
This was already resolved on our end. Update to latest SpongeForge.
