### ISSUE TITLE
Server crashes.. related to Ae2

### ISSUE THREAD

**Issue by Keaton1188** [SpongePowered/SpongeForge#1353]
Hi all, I am setting up a FTB Beyond server (just to do some tests on) and need sponge for it.
I have installed Forge correctly and added Sponge to the mods, when it starts it gives me this error 
(First pic is with Ae2 on and trying to start the server)

When I remove Ae2 and Ae2 Stuffs, the server launches further than the previous error.. but still gives me another error (another pic below)

![spongecrash](https://cloud.githubusercontent.com/assets/24898745/23832263/46668870-0729-11e7-9f9e-8730580e2869.png)
![ae2 without crash](https://cloud.githubusercontent.com/assets/24898745/23832264/4666bbb0-0729-11e7-90b6-5a3c0c9ebca3.png)

**Comment by phit** [comment]
You have to remove wireless crafting terminal if you not gonna have AE2, it requires it..
Anyway AE2 doesnt work out of the box with sponge, but you can use a [patched version ](https://github.com/Stonebound/Applied-Energistics-2#about) or [SpongeBootstrap](https://forums.spongepowered.org/t/spongebootstrap-fixes-ordering-issue-with-other-coremods/12275) and it will work!

#966

**Comment by Keaton1188** [comment]
Thanks for the reply!
