### ISSUE TITLE
Client crash [java.lang.NullPointerException]

### ISSUE THREAD

**Issue by thagreenkronic** [SpongePowered/SpongeForge#1354]
Players sometimes crash on my server when attempting to join. Simply trying to join again seems to work for them.

logs - https://gist.github.com/thagreenkronic/ce516c908043adadd30aa8a2ef4e1e2b

Problem seems to begin at line 7598 (fml-server-latest.log)

**Comment by bloodmc** [comment]
This has nothing to do with SpongeForge.
