### ISSUE TITLE
FTB Beyond Duplication glitch (Sponge servers only)

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1355]
When on the pack FTB Beyond Version 1.0.1
And running sponge forge version 1.10.2-2221-5.2.0-BETA-2229

If You Shift Right Click On Any Solar Panel From The Solar Flux Reborn Mod With The Crescent  Hammer From Thermal Expansion It Will Duplicate As Shown In The Attached Video (Sorry For Poor Quality) This Only Happens On Sponge Servers.

[Video](http://www.dailymotion.com/video/x5elyqs)

Thanks
~Spec

**Comment by phit** [comment]
not a sponge bug, update beyond to 1.1.0
https://minecraft.curseforge.com/projects/solar-flux-reborn/issues/47
https://forum.feed-the-beast.com/threads/solar-flux-reborn-really-enjoys-the-crescent-hammer.221020/
