### ISSUE TITLE
Use of /cofh

### ISSUE THREAD

**Issue by Keaton1188** [SpongePowered/SpongeForge#1356]
Hi all, I am just asking for a bit of help.

All users are able to do /cofh tps.. we do NOT want them to be able to do this command..
Is there any way to disable it? I cant seem to find anything in the configs.

Any help is appreciated

**Comment by bloodmc** [comment]
Create a plugin and handle it in SendCommandEvent.

https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/event/command/SendCommandEvent.java

**Comment by ktole1999** [comment]
not sure if there is a permission node for this command. deny it.

**Comment by Eufranio** [comment]
There IS a permission node, you can just deny it for your players with any permission plugin.

**Comment by Keaton1188** [comment]
Using PEX, is there a permission node for that so it is disabled?
