### ISSUE TITLE
Insane lag spikes to 700% usage

### ISSUE THREAD

**Issue by Aphex124** [SpongePowered/SpongeForge#1359]
Lets try this here since there wasn't a response on the forums.

Hello,

I have had my FTB Beyond server up for about 7 days now, and probably 3 days ago we have started to get insane lag spikes with a CPU usage of 700%, along with the allocated ram being maxed out. I have a decent CPU (E3-1240v5) along with a SSD, so it shouldnt be doing this, as my Resonant Rise server is not having this problem.

The problem seems to start and stop randomly, but it feels like its been taking longer and longer to stop each time. At this point its easier to restart the server and have the players join back rather than wait out the lag. The TPS goes down to ~3 instantly, and makes its way down to ~1 within a minute.

[Here are the timings running on for about a minute right after I restarted the server.](https://timings.aikar.co/?id=0ddb0e50ca7d4495a0f3af98feed648e)
[Timings during the lag spike](https://timings.aikar.co/?id=58ea63d66e224ec288b65e4cd47464d3#timings)

Thank you,
Mike

**Comment by Deamon5550** [comment]
Probably going to need to go in with a profiler and get a better look at that. Or even just warmroast could help.

**Comment by Aphex124** [comment]
@Deamon5550 Will get one during the next lag spike, but it might take a while.
**Edit:** https://hastebin.com/bimawonewi.erl Thats all it gave me during the spike

**Comment by bloodmc** [comment]
@Aphex124 Update to latest SF and make sure to provide your fml-server-latest.log along with timings.

**Comment by Aphex124** [comment]
@bloodmc During the lag spike:
[FML-server-3.log](https://gist.github.com/Aphex124/345ec9eb62feb4562fb8fae49c527621)
I don't know how else to link a WarmRoast, but um [here](https://sentnet.us/WarmRoast.html) ... I still have the page up, if you need me to copy it in another way, just ask

**Edit:** It happened again, Sponge timings report: https://timings.aikar.co/?id=f612c25409bb473d94d1d2fa344cf058#regions

**Edit 2:** Prolonged (5m) timings report: https://timings.aikar.co/?id=a7867016e0464e4482d63d999b97253c

**Comment by Aphex124** [comment]
Can anyone get anything from the log and timings? Its happening more and more often.

**Comment by bloodmc** [comment]
The lag is coming from AE2. Remove SpongeForge and retest. If it happens without sponge then report to dev.
