### ISSUE TITLE
Issue found in server console on custom modpack

### ISSUE THREAD

**Issue by Amaxter** [SpongePowered/SpongeForge#1362]
https://hastebin.com/efeqesocen.md

Mod list for pack: https://www.technicpack.net/modpack/audax.963457/mods

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/SpongePowered/SpongeCommon/commit/ff967b5517b81b73b441c4cb0aea6ce3eedde4ea

**Comment by bloodmc** [comment]
Actually i need to catch this as well

**Comment by bloodmc** [comment]
@Faithcaio please fix this.

**Comment by Faithcaio** [comment]
https://github.com/SpongePowered/SpongeCommon/commit/7719eee07ee7
this could fix it

**Comment by bloodmc** [comment]
@Faithcaio push it if it works or provide a test jar for user to test. Thanks!

**Comment by Faithcaio** [comment]
fixed in https://github.com/SpongePowered/SpongeCommon/commit/ba2a27ffa83ee972a024407921fbd36c01e768c0
