### ISSUE TITLE
Sponge Tracking Error

### ISSUE THREAD

**Issue by lilmoefow** [SpongePowered/SpongeForge#1367]
Forge: forge-1.10.2-12.18.3.2254
Sponge: spongeforge-1.10.2-2254-5.2.0-BETA-2236

Getting this error on start up, it says to report it here.  We have also been getting random crashes caused by a similar tracking issue, but i will report those separately once they occur again.

FML LOG : https://gist.github.com/lilmoefow/65ca34a5ae4f8d9ad649ee06c1afae59

**Comment by lilmoefow** [comment]
The error is also popping up again as i'm mining in the nether.  The Tick rate on the server takes a complete nose dive when this error starts.
https://gist.github.com/lilmoefow/9e5a29e35500bf410ac1dc6e2d250aa5

**Comment by lilmoefow** [comment]
The other admin on our server did some profiling with Warmroast.  Here are 2 images the results he got.

https://cdn.discordapp.com/attachments/213636083416694785/294478918012895233/moe1.PNG
https://cdn.discordapp.com/attachments/213636083416694785/294478932361740288/moe2.PNG

**Comment by lilmoefow** [comment]
#1378  is Related

**Comment by bloodmc** [comment]
This was fixed. Update to latest SpongeForge.
