### ISSUE TITLE
Extra Utilities Quantum Quarry Crash

### ISSUE THREAD

**Issue by lilmoefow** [SpongePowered/SpongeForge#1368]
Forge: forge-1.10.2-12.18.3.2254
Sponge: spongeforge-1.10.2-2254-5.2.0-BETA-2236
Crashlog: https://gist.github.com/lilmoefow/8eff708fa3a5f5395b71dc08a0500c41

Crash happened when the quarry was started. Last time this happened it was in a crash loop and i had to enable Forges RemoveErroringTileEntities config option to get it to load up.  But enabling that config just renders all Quantum Quarries completely useless.

**Comment by lilmoefow** [comment]
More Crashes today from it when a player who owns one logs onto the server.

https://gist.github.com/lilmoefow/5d74b91bad33a1ffd33b487506134d64

**Comment by Magi1053** [comment]
Related issue https://github.com/SpongePowered/SpongeForge/issues/970 https://github.com/SpongePowered/SpongeForge/issues/1371

**Comment by bloodmc** [comment]
Update to latest SF and retest.

**Comment by lilmoefow** [comment]
Updated to latest version of Sponge, enabled the quantum quarry again along with the dimension it uses. The server started back up but got a completely different crash

Crashlog : https://pastebin.com/cczzTB2i

Server Log : https://pastebin.com/wXsfDAQX

FML Log : https://gist.github.com/lilmoefow/23621fb15890b83f7b81994ef221c615

Disabling ChickenChunks on the server allowed us to start the server.

**Comment by lilmoefow** [comment]
So, Quarry works but doesnt work.. It says in its gui that it is "mining blocks" but it doesnt actually output anything any more.  The quarry also sends the cpu usage to full 100%.  Will do some profiling with Warmroast later tonight or tomorrow, and give you the results

**Comment by johnfriedrich** [comment]
Still an issue with SF 2264
https://pastebin.com/r6taVHDP

Just updated to 2300, lets see if it still happens.

**Comment by Yann151924** [comment]
When i use the spongeforge-1.10.2-2254-5.2.0-BETA-2236 , the quantum don't crash and don't freeze my server. If it could help.
But when other version the server freeze or crash.
