### ISSUE TITLE
Can no longer click chat Sponge 2236

### ISSUE THREAD

**Issue by Dysthymic** [SpongePowered/SpongeForge#1369]
With the message fixes you can no longer click on links or paginations in chat.
SpongeForge #2236

**Comment by simon816** [comment]
Cannot reproduce, I was able to navigate to different pages in the help menu
![working](https://puu.sh/uSnqh/2bfc674e44.jpg)

Do you have a specific scenario where this doesn't work?

**Comment by Dysthymic** [comment]
Removed Nucleus as a test. Seems there is an incompatibility with Nucleus (latest 26.1) and latest 2236 Sponge. Clickables work fine on 2231 with Nucleus.

**Comment by simon816** [comment]
Still works with the `/help` pagination. Is there a specific text message that's not working that I can test for?

![ss](https://puu.sh/uStQE/0055ec49c7.png)

**Comment by bloodmc** [comment]
@Dysthymic is this still an issue with latest SF?

**Comment by bloodmc** [comment]
Assuming this is fixed. I'll reopen if it happens again.
