### ISSUE TITLE
Starting of a Quantum Quarry prints a crash log to console with no crash

### ISSUE THREAD

**Issue by merjilin** [SpongePowered/SpongeForge#1371]
Hello there. I have been experiencing something especially weird with the QQ. When ever it is activated a crash log is printed to console but the server doesn't actually crash. Players have told me that this also resets the quantum quarries, causing them to lose upgrades, in addition to the fact the QQ doesn't actually mine or accept power. I'm posting this here incase this is anything to do with your side of things before I send it to the ExtraUtils2 dev.
Log: http://pastebin.com/ZkgW0vKC
Spongeforge version: spongeforge-1.10.2-2254-5.2.0-BETA-2236
ExtraUtils2:  EXTRAUTILS2-1.10.2-1.3.3
Forge: forge-1.10.2-12.18.3.2254-universal

Thank you for your time.
- merjilin

**Comment by merjilin** [comment]
Oh I have also been made aware by players than item routing is no longer working for blood magic. This may be due to the attempt of fixing the dupe with the sword. This may also link to the reason why a special chest from routers reborn crashes the server when interacting with a blood magic altar.

**Comment by Magi1053** [comment]
Duplicate issue https://github.com/SpongePowered/SpongeForge/issues/970 https://github.com/SpongePowered/SpongeForge/issues/1368 (still unresolved)

**Comment by Deamon5550** [comment]
Duplicate #1368, also please open a separate issue for your other issue.
