### ISSUE TITLE
Server crash on block update

### ISSUE THREAD

**Issue by Y0ungSandwich** [SpongePowered/SpongeForge#1372]
User placed cobblestone over Tinkers Construct drains. Ran vanilla redstone over the stone to a Extra Utilities timer. Server crashed immediately.

Pack is Mech & Magic v1.1.3 on ATLauncher
  SpongeCoremod (spongeforge-1.10.2-2254-5.2.0-BETA-2236.jar)

http://pastebin.com/gLDSy5tT

**Comment by bloodmc** [comment]
@Mumfrey any idea why the following is not working?
https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/event/tracking/CauseTracker.java#L401

**Comment by phit** [comment]
https://github.com/SpongePowered/SpongeForge/issues/1342

**Comment by phit** [comment]
Dupe of #941 & #1342 which was fixed.
