### ISSUE TITLE
TrackingUtil.tickTileEntity taking up entire server

### ISSUE THREAD

**Issue by Magi1053** [SpongePowered/SpongeForge#1378]
I dropped spongeforge into my existing DW20 pack, right off the bat the server was at 10tps. I profiled the server with Warmroast, and it told me that this was using 70% of the cpu.
` org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity() `

**Comment by phit** [comment]
everything sponge tracks will show up under that, https://github.com/SpongePowered/SpongeForge/issues/1213#issuecomment-274640181

**Comment by gabizou** [comment]
As phit said, sponge's calls are not expensive, it shows up as such because we are wrapping around everything to be able to track it. You'll need to provide some more profiling information for us to view, and likely give us an idea of how the server was preforming before you installed sponge.

**Comment by Magi1053** [comment]
The server used approximately 20-30% of the box's cpu average at 20tps. After dropping in sponge, the cpu goes up to 100% and 6-10 tps. I ran https://github.com/nallar/TickProfiler, but it wasn't showing anything that was explaining the high server usage. How else do you recommend that I profile the server?

**Comment by gabizou** [comment]
We need to see the full warm roast profile.

**Comment by Magi1053** [comment]
![image](https://cloud.githubusercontent.com/assets/1045179/24219110/acec3a9e-0f13-11e7-871a-904b1a3e90fa.png)
~link expired~

**Comment by Magi1053** [comment]
Updated warmroast profile link

**Comment by gabizou** [comment]
@Magi1053 Would you be able to provide a world + mods zip for us to be able to replicate? By the numbers, there's something somewhere causing an increase of use in the CauseTracker itself that is degrading performance for some reason, but the warm roast isn't showing anything to go off of.

**Comment by lilmoefow** [comment]
I was having the same issue on my server.  Disabling the Quantum Quarry, and the dimension affiliated with it seems to have "fixed" it.

**Comment by LemADEC** [comment]
I've noticed the quantum dimension gets filled up with entity items that remain frozen in the dimension. Could that be that Sponge is tracking those even if the mod never really 'use' them?
