### ISSUE TITLE
Pams HarvestCraft causing server lag - FTB Beyond

### ISSUE THREAD

**Issue by Keaton1188** [SpongePowered/SpongeForge#1380]
So we are getting major lag on our FTB Beyond server, from what I can see it looks like its - 
(harvestcraft:com.pam.harvestcraft.worldgen.FruitTreeWorldGen)

Sponge timings report - https://timings.aikar.co/?id=fa6cf9820f0647d5a06a9610764d2000

Any idea?

SpongeForge:
Minecraft 1.10.2
SpongeAPI 5.2.0-SNAPSHOT-a3257a0
SpongeForge 1.10.2-2254-5.2.0-BETA-2241
Minecraft Foge 12.18.3.2254

**Comment by Eufranio** [comment]
Pam's worldgen is laggy, pregen your world first and set a world border, otherwise every time someone is generating chunks your server will freeze,

**Comment by bloodmc** [comment]
As Eufranio stated, pregen your world. Use nucleus to do it.
