### ISSUE TITLE
Pixelmon "Completing incorrect phase"

### ISSUE THREAD

**Issue by crashtheparty** [SpongePowered/SpongeForge#1382]
Whenever I win a pokemon battle in Pixelmon this error shows up:

25.03 19:56:14 [Server] Server thread/INFO [STDOUT]: [com.pixelmonmod.pixelmon.battles.controller.log.BattleLog:onCrash:234]: Caught error in battle. Continuing...
25.03 19:56:14 [Server] Server thread/INFO [STDERR]: [com.pixelmonmod.pixelmon.battles.controller.log.BattleLog:onCrash:235]: java.lang.NullPointerException
25.03 19:56:14 [Server] Server thread/INFO [STDERR]: [com.pixelmonmod.pixelmon.battles.controller.log.BattleLog:onCrash:235]: at com.pixelmonmod.pixelmon.entities.pixelmon.drops.DropItemHelper.dropNormalItems(DropItemHelper.java:204)
25.03 19:56:14 [Server] Server thread/INFO [STDERR]: [com.pixelmonmod.pixelmon.battles.controller.log.BattleLog:onCrash:235]: at com.pixelmonmod.pixelmon.entities.pixelmon.Entity8HoldsItems.func_70645_a(Entity8HoldsItems.java:200)
25.03 19:56:14 [Server] Server thread/INFO [STDERR]: [com.pixelmonmod.pixelmon.battles.controller.log.BattleLog:onCrash:235]: at com.pixelmonmod.pixelmon.entities.pixelmon.EntityPixelmon.func_70645_a(EntityPixelmon.java:148)
25.03 19:56:14 [Server] Server thread/INFO [STDERR]: [com.pixelmonmod.pixelmon.battles.controller.log.BattleLog:onCrash:235]: at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:3339)
25.03 19:56:14 [Server] Server thread/INFO [STDERR]: [com.pixelmonmod.pixelmon.battles.controller.log.BattleLog:onCrash:235]: at net.minecraft.entity.passive.EntityAnimal.func_70097_a(SourceFile:64)
25.03 19:56:14 [Server] Server thread/INFO [STDERR]: [com.pixelmonmod.pixelmon.battles.controller.log.BattleLog:onCrash:235]: at com.pixelmonmod.pixelmon.entities.pixelmon.Entity3HasStats.func_70097_a(Entity3HasStats.java:353)
25.03 19:56:14 [Server] Server thread/INFO [STDERR]: [com.pixelmonmod.pixelmon.battles.controller.log.BattleLog:onCrash:235]: at com.pixelmonmod.pixelmon.entities.pixelmon.Entity6CanBattle.func_70097_a(Entity6CanBattle.java:220)
25.03 19:56:14 [Server] Server thread/INFO [STDERR]: [com.pixelmonmod.pixelmon.battles.controller.log.BattleLog:onCrash:235]: at com.pixelmonmod.pixelmon.entities.pixelmon.Entity10CanBreed.func_70097_a(Entity10CanBreed.java:1137)
25.03 19:56:14 [Server] Server thread/INFO [STDERR]: [com.pixelmonmod.pixelmon.battles.controller.log.BattleLog:onCrash:235]: at com.pixelmonmod.pixelmon.entities.pixelmon.Entity6CanBattle.doBattleDamage(Entity6CanBattle.java:879)
25.03 19:56:14 [Server] Server thread/INFO [STDERR]: [com.pixelmonmod.pixelmon.battles.controller.log.BattleLog:onCrash:235]: at com.pixelmonmod.pixelmon.battles.attacks.Attack.executeAttackEffects(Attack.java:586)
25.03 19:56:14 [Server] Server thread/INFO [STDERR]: [com.pixelmonmod.pixelmon.battles.controller.log.BattleLog:onCrash:235]: at com.pixelmonmod.pixelmon.battles.attacks.Attack.use(Attack.java:512)
25.03 19:56:14 [Server] Server thread/INFO [STDERR]: [com.pixelmonmod.pixelmon.battles.controller.log.BattleLog:onCrash:235]: at com.pixelmonmod.pixelmon.battles.controller.participants.PixelmonWrapper.useAttack(PixelmonWrapper.java:453)
25.03 19:56:14 [Server] Server thread/INFO [STDERR]: [com.pixelmonmod.pixelmon.battles.controller.log.BattleLog:onCrash:235]: at com.pixelmonmod.pixelmon.battles.controller.participants.PixelmonWrapper.useAttack(PixelmonWrapper.java:391)
25.03 19:56:14 [Server] Server thread/INFO [STDERR]: [com.pixelmonmod.pixelmon.battles.controller.log.BattleLog:onCrash:235]: at com.pixelmonmod.pixelmon.battles.controller.participants.PixelmonWrapper.takeTurn(PixelmonWrapper.java:910)
25.03 19:56:14 [Server] Server thread/INFO [STDERR]: [com.pixelmonmod.pixelmon.battles.controller.log.BattleLog:onCrash:235]: at com.pixelmonmod.pixelmon.battles.controller.BattleControllerBase.takeTurn(BattleControllerBase.java:855)
25.03 19:56:14 [Server] Server thread/INFO [STDERR]: [com.pixelmonmod.pixelmon.battles.controller.log.BattleLog:onCrash:235]: at com.pixelmonmod.pixelmon.battles.controller.BattleControllerBase.update(BattleControllerBase.java:328)
25.03 19:56:14 [Server] Server thread/INFO [STDERR]: [com.pixelmonmod.pixelmon.battles.controller.log.BattleLog:onCrash:235]: at com.pixelmonmod.pixelmon.battles.BattleRegistry.updateBattles(BattleRegistry.java:138)
25.03 19:56:14 [Server] Server thread/INFO [STDERR]: [com.pixelmonmod.pixelmon.battles.controller.log.BattleLog:onCrash:235]: at com.pixelmonmod.pixelmon.battles.BattleTickHandler.tickStart(BattleTickHandler.java:12)
25.03 19:56:14 [Server] Server thread/INFO [STDERR]: [com.pixelmonmod.pixelmon.battles.controller.log.BattleLog:onCrash:235]: at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_35_BattleTickHandler_tickStart_WorldTickEvent.invoke(.dynamic)
25.03 19:56:14 [Server] Server thread/INFO [STDERR]: [com.pixelmonmod.pixelmon.battles.controller.log.BattleLog:onCrash:235]: at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
25.03 19:56:14 [Server] Server thread/INFO [STDERR]: [com.pixelmonmod.pixelmon.battles.controller.log.BattleLog:onCrash:235]: at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:635)
25.03 19:56:14 [Server] Server thread/INFO [STDERR]: [com.pixelmonmod.pixelmon.battles.controller.log.BattleLog:onCrash:235]: at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:591)
25.03 19:56:14 [Server] Server thread/INFO [STDERR]: [com.pixelmonmod.pixelmon.battles.controller.log.BattleLog:onCrash:235]: at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:269)
25.03 19:56:14 [Server] Server thread/INFO [STDERR]: [com.pixelmonmod.pixelmon.battles.controller.log.BattleLog:onCrash:235]: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:718)
25.03 19:56:14 [Server] Server thread/INFO [STDERR]: [com.pixelmonmod.pixelmon.battles.controller.log.BattleLog:onCrash:235]: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
25.03 19:56:14 [Server] Server thread/INFO [STDERR]: [com.pixelmonmod.pixelmon.battles.controller.log.BattleLog:onCrash:235]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
25.03 19:56:14 [Server] Server thread/INFO [STDERR]: [com.pixelmonmod.pixelmon.battles.controller.log.BattleLog:onCrash:235]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
25.03 19:56:14 [Server] Server thread/INFO [STDERR]: [com.pixelmonmod.pixelmon.battles.controller.log.BattleLog:onCrash:235]: at java.lang.Thread.run(Thread.java:745)
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /********************************************************************************************************************/
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* Completing incorrect phase */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /********************************************************************************************************************/
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* Sponge's tracking system is very dependent on */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* knowing when
25.03 19:56:14 [Server] INFO a change to any world takes place, */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* however, we are attempting
25.03 19:56:14 [Server] INFO to complete a "phase" */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* other than the one we most recently entered.
25.03 19:56:14 [Server] INFO This */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* is an error usually on Sponge's part, so a */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* report
25.03 19:56:14 [Server] INFO is required on the issue tracker on GitHub. */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /********************************************************************************************************************/
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* Affected World : WorldServer{LevelName=pixelmon, DimensionId=0, DimensionType=minecraft:overworld} */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* Expected to exit phase: org.spongepowered.common.event.tracking.phase.plugin.PostWorldTickListenerState@697010d6 */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* But instead found phase: org.spongepowered.common.event.tracking.phase.entity.DeathPhase@7940f07c */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* StackTrace: */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* java.lang.Exception: null */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* org.spongepowered.common.event.tracking.CauseTracker.printIncorrectPhaseCompletion(CauseTracker.java:271) */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:191) */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* org.spongepowered.mod.event.SpongeForgeEventHooks.postEventPhaseCheck(SpongeForgeEventHooks.java:158) */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:636) */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:591) */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:269) */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:718) */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* java.lang.Thread.run(Thread.java:745) */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* Phases Remaining: */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* - Phase: org.spongepowered.common.event.tracking.phase.entity.DeathPhase@7940f07c */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* Context: */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* - Name: Source */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* Object: EntityPixelmon['Zubat'/16550, l='pixelmon', x=-26.40, y=76.50, z=54.26] */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* - Name: DamageSource */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* Object: DamageSource{Name=battle, Type=custom} */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* - Name: CapturedBlocks */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* Object: CapturedBlocksSupplier{Captured=0} */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* - Name: CapturedEntities */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* Object: CapturedEntitiesSupplier{Captured=0} */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* - Phase: org.spongepowered.common.event.tracking.phase.plugin.PostWorldTickListenerState@697010d6 */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* Context: */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* - Name: Source */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* Object: ASM: com.pixelmonmod.pixelmon.battles.BattleTickHandler@4870e5e0 */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* tickStart(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* - Name: CapturedWorldTickEvent */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* Object: net.minecraftforge.fml.common.gameevent.TickEvent$WorldTickEvent@3e5039c5 */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* - Name: CapturedBlocks */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* Object: CapturedBlocksSupplier{Captured=0} */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* - Name: CapturedEntities */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* Object: CapturedEntitiesSupplier{Captured=0} */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* - Name: CapturedPlayer */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* Object: CapturePlayer{player=null} */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* Minecraft : 1.10.2 */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* SpongeAPI : 5.2.0-SNAPSHOT-a3257a0 */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* SpongeForge : 1.10.2-2254-5.2.0-BETA-2241 */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /* Minecraft Forge : 12.18.3.2202 */
25.03 19:56:14 [Server] Server thread/ERROR [Sponge]: /********************************************************************************************************************/
25.03 19:56:14 [Server] INFO /********************************************************************************************************************/
25.03 19:56:14 [Server] INFO /* Completing incorrect phase */
25.03 19:56:14 [Server] INFO /********************************************************************************************************************/
25.03 19:56:14 [Server] INFO /* Sponge's tracking system is very dependent on */
25.03 19:56:14 [Server] INFO /* knowing when
25.03 19:56:14 [Server] INFO a change to any world takes place, */
25.03 19:56:14 [Server] INFO /* however, we are attempting
25.03 19:56:14 [Server] INFO to complete a "phase" */
25.03 19:56:14 [Server] INFO /* other than the one we most recently entered.
25.03 19:56:14 [Server] INFO This

**Comment by gabizou** [comment]
This is somewhat illegible, can you re-copy from the server log and use ` ``` ` block quotes?
