### ISSUE TITLE
Exception ticking world entities

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeForge#1386]
I have removeErroringTileEntities on, and sometimes when it tries to remove a tile entity preventing a crash, the server crashes by another reason. Crash-report: https://hastebin.com/anuxaqeqej.sql

    Minecraft: 1.10.2
    SpongeAPI: 5.2.0-SNAPSHOT-a3257a0
    SpongeForge: 1.10.2-2254-5.2.0-BETA-2245
    Minecraft Forge: 12.18.3.2239

**Comment by LemADEC** [comment]
Your forge version is outdated 12.18.3.2239 and doesn't match with your outdated spongeforge version 1.10.2-2254-5.2.0-BETA-2245

Also, I'm pretty sure we need the full server logs to investigate this kind of cascaded errors.

**Comment by Eufranio** [comment]
Fixed a few builds ago.
