### ISSUE TITLE
RFTools Builder Block can mine protected areas

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeForge#1387]
RFTools has a block called Builder Block, which can be upgraded to act like a Quarry. When a player selects an area inside a protected area (GP claim, server spawn) and turn the builder on, it will mine the blocks, not respecting if they are protected or not.

    Minecraft: 1.10.2
    SpongeAPI: 5.2.0-SNAPSHOT-a3257a0
    SpongeForge: 1.10.2-2254-5.2.0-BETA-2245
    Minecraft Forge: 12.18.3.2239

**Comment by axle2005** [comment]
This is a GP issue.

**Comment by Eufranio** [comment]
This griefs the server spawn.

**Comment by Brend-Smits** [comment]
https://github.com/McJty/RFTools/issues/1107

**Comment by bloodmc** [comment]
McJty fixed this in 5.91
