### ISSUE TITLE
More tracking errors

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeForge#1388]
Now that's the stacktraces: https://hastebin.com/nenigebebu.md

    Minecraft: 1.10.2
    SpongeAPI: 5.2.0-SNAPSHOT-a3257a0
    SpongeForge: 1.10.2-2254-5.2.0-BETA-2245
    Minecraft Forge: 12.18.3.2239

**Comment by gabizou** [comment]
Update to SpongeForge 2249 or higher, this issue is fixed for those builds, a back port for 1.10.2 will be provided in due time.
