### ISSUE TITLE
Lootbags dont drop with SpongeForge

### ISSUE THREAD

**Issue by Yorkforce** [SpongePowered/SpongeForge#1391]
Noticed this problem a while ago on Sky Factory 3, we tested in single player and the lootbags drop from mobs just fine but on the server with SpongeForge-2241 they don't drop at all.

There was an issue #1259  reported about Hatchery but I wasn't sure if it was related to this problem.

**Comment by Yorkforce** [comment]
As mentioned in #1398 disabling pre-merge in sponge config does fix this

Thanks for looking into it guys!

**Comment by bloodmc** [comment]
You should always have pre-merge turned off when running SpongeForge as there are too many compatibility issues with it.
