### ISSUE TITLE
Machines disconnect upon chunk unloading

### ISSUE THREAD

**Issue by merjilin** [SpongePowered/SpongeForge#1392]
Hey, guys. Sorry to be back so soon. 
Players seem to be having an issue where complex systems are disconnecting upon the chunks being unloaded. I mean disconnected as in a refined storage systems disconnects itself and needs breaking in order to be fixed. 
An example that has been revealed is: connecting a comprehensive refined storage auto crafting setup, and flying/teleporting away. Upon reloading the chunk, parts of the system have disconnected. 
The issue isn't isolated to refined storage, another example is item conduits from enderio.
Spongeforge: 1.10.2-2254-5.2.0-BETA-2254
Forge: 12.18.3.2254

**Comment by bloodmc** [comment]
@merjilin Did this just start happening with latest? Test other builds. You should also test this on a clean setup with only refined storage/enderio. and provide a timings report as well as a server log.

**Comment by merjilin** [comment]
I will have to do further testing tomorrow due to a tight schedule. The players told me that they had been noticing it for the past couple of weeks but didn't speak out about it. If I can remember correctly, the build I updated to before this started to occur was 2236. Though obviously testing is required.

**Comment by Eufranio** [comment]
That also happens with IC2 energy net. Sometimes when players log in the server, their E-net is gone: cables aren't connecting with eachother, machines aren't accepting/outputing power, and need to be replaced to work (everything). 

    Minecraft: 1.10.2
    SpongeAPI: 5.2.0-SNAPSHOT-a3257a0
    SpongeForge: 1.10.2-2254-5.2.0-BETA-2245
    Minecraft Forge: 12.18.3.2239

**Comment by bloodmc** [comment]
@Eufranio @merjilin  provide a test world with only IC2 or refined storage and list steps to reproduce.

**Comment by ghost** [comment]
It is very difficult to reproduce. As said Eufranio, cables disconnect sometimes (idk when chunk unloaded or loaded back).

**Comment by ktole1999** [comment]
tp to spawn. wait 5-6 min and tp back. rinse and repeat till issue happens. unless your base is within 10 chunks of spawn then you need to go farther away from your base.

**Comment by merjilin** [comment]
I can't seem to get it to reproduce with pure refined storage and spongeforge 2259. It may be because I'm having to use a creative controller due to a lack of power generation in refined storage itself.

**Comment by Eufranio** [comment]
Yeah, I can't fully reproduce it, just hear players reporting (and happened with myself). I chunkloaded the base where I had this bug and it isn't happening anymore, so defiantely is something with chunk unloading.

**Comment by phit** [comment]
this is a Refined Storage issue and won't be backported to 1.10.2

https://github.com/raoulvdberge/refinedstorage/issues/370
