### ISSUE TITLE
Farm Station spamming with removeErroringTileEntities enabled

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeForge#1393]
I've recently enabled the **removeErroringTileEntities** option in the Forge config, and then a lot of "crashes" started being printed in the console. Crash-report printed (not generated, since the server will not crash): https://hastebin.com/tiyayaqako.scala

I suspect to be something in Sponge, because I tested with the same world in a clean server and nothing crashed.

**Comment by Aaron1011** [comment]
Can you upload your full `fml-server-latest.log`?

**Comment by Eufranio** [comment]
We reseted the server and updated the pack a few days after I posted this issue, and those errors aren't happening anymore, I'll reopen if it starts again  😄
