### ISSUE TITLE
[1.10.2] ActuallyAdditions - Buttons

### ISSUE THREAD

**Issue by Brend-Smits** [SpongePowered/SpongeForge#1394]
https://github.com/Ellpeck/ActuallyAdditions/issues/587
For some odd reason a lot of mod developers just blame Sponge for everything which is extremely frustrating... Sorry to come here, but could this be fixed on the Sponge side of things of purely on ActuallyAdditions mod?

**Comment by ryantheleach** [comment]
Reading the linked issue it appears that it's been replicated without Sponge. 
Without extra details on how to reproduce this reliably it's going to cost the Sponge developers a lot of time hunting down what is likely to be a bug with the mod itself if it's able to be reproduced on pure Forge.

From: https://github.com/canitzp/Modpack-Bugs/issues/3

"
Necollex commented on 25 Jan
uhh.... Youre all having the issue with sponge? Im using Forge and it doesnt work....
all i can say is that it isnt the server. a friend tryed it and it worked.
"

"
canitzp commented on 22 Jan
I tested a pure sponge server with only actadd half an hour ago and it did work. How is you sponge server setup?
"

**Comment by Eufranio** [comment]
I tested and it works on singleplayer and forge servers, but not in Sponge. 100% of the times it DIDN'T work on sponge, and DID on forge.

**Comment by mkrtes** [comment]
I have the same problem. Modpak skyfactory3 on the sponge. However, modpak "Age of engineering" is not have this problem! While working on the sponge. Very strange.

**Comment by phit** [comment]
can't reproduce this on my own server

ActuallyAdditions-1.11.2-r110.jar
spongeforge-1.11.2-2393-6.1.0-BETA-2463.jar

I'm personally behind Hexagon's BungeeCord for 1.12, either way this is not a Sponge issue
