### ISSUE TITLE
[1.10.2] Spawning certain modded items in the world won't work

### ISSUE THREAD

**Issue by Brend-Smits** [SpongePowered/SpongeForge#1395]
Hello all, 
I'm seeking advice, we've made a new keep inventory system which basically gives the player to choose between Keeping their items (in exchange for a small fee) or dropping the items on the place of death. 
It looks like spawning certain items on the world won't work though, for example, tinkers construct or draconic evolution armors/weapons. 
If you literally take them from the player inventory and then spawn them on the world, the won't spawn at all. 
According to @Faithcaio (hehe sorry for the tag), the inventory behaves fine at the end of the event, the item-entity is in the world but it is not showing. 
Just to clarify, spawning all the items back in the inventory works fine, it's just the part where people chose to drop the items on the ground which does not work. 
My developer set up an example code that you could use to diagnose: 
https://pastebin.com/YH3JCbEs

I strongly think this is NBT related. I seek advice on how to fix this. 

Tested using:    
Minecraft: 1.10.2
    SpongeAPI: 5.2.0-SNAPSHOT-a3257a0
    SpongeForge: 1.10.2-2254-5.2.0-BETA-2254
    Minecraft Forge: 12.18.3.2254
Draconic Evolution: 	
Draconic Evolution 1.10.2-2.0.8.177-universal
Tinkers Construct: TConstruct-1.10.2-2.6.3.jar

**Comment by LemADEC** [comment]
Those mods are replacing ItemEntities with their owns, the one you spawn in is almost instantly replaced by the one from the mod

**Comment by Brend-Smits** [comment]
Thank you LemADEC, I will close this issue in that case.
