### ISSUE TITLE
aroma1997.core.command is conflicting with Sponge's MinecraftCommandWrapper

### ISSUE THREAD

**Issue by MrLegacy119** [SpongePowered/SpongeForge#1396]
Hello, I recently started trying to setup SpongeForge on my FTB Beyond server and had some difficulties, eventually after getting help from the sponge forums I got the server to load with spongeforge on it.  Once the server loaded up I went on just  to make sure it was working right and tried to use the /help command and got a long error, I went back on the forums with the error report and one of them suggested asking here.  This is the link to the forums post about my problems https://forums.spongepowered.org/t/spongeforge-on-ftb-beyond-server-crashing/18201/8

Thank you in advance for any help!

**Comment by phit** [comment]
this was solved by the mod dev and wasn't a Sponge issue

https://bitbucket.org/Aroma1997/miningworld/issues/112/help-error-on-interaction-with
