### ISSUE TITLE
Decide how to handle Forge's Entity.capturedDrops

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/SpongeForge#1398]
Forge adds [a public field 'capturedDrops'](https://github.com/MinecraftForge/MinecraftForge/blob/006b8cc8bd088b90e3e8fa7162b5d052ec8c3dd2/patches/minecraft/net/minecraft/entity/Entity.java.patch#L32) to `Entity` for the purpose of firing events. With the CauseTracker system, we end up ignoring this field as we track drops ourselves in a `PhaseContext.

However, the [Hatchery mod](https://github.com/GenDeathrow/Hatchery/blob/e88cf72a615ded9d459689b6aaf1626928ac84f9/src/main/java/com/gendeathrow/hatchery/block/nestpen/NestPenTileEntity.java#L247) makes use of this field in order to handle drops from chicken placed in one of its Nesting Pens. Since we never update this field, Hatchery will never be able to detect drops.

I think the simplest solution would be to ensure that we update this list for non-premerged drops. Handling pre-merged drops might be difficult, but we simply tell people to turn it off (as we already do for other mod-compatibility issues).

Pinging @gabizou @blood for suggestions.

**Comment by gabizou** [comment]
@Aaron1011 There's a pretty good way to go about this, we can keep it in sync with the list of drops during processing (add hooks to SpongeImplHooks, but that class desperately needs to be refactored out to the several other utility classes for their designed areas), and keep it in line with events, as I'm assuming it's because Hatchery is using the event listeners to handle the drops? Otherwise, I'm not sure how to keep the drops in sync across them.

Another thing I was going to potentially do was port the item pre-merging code to Forge so that mod authors are able to safely consider their items dropped and reduce the usage of items generated.

**Comment by GenDeathrow** [comment]
Hatchery dev - when a chicken is placed into a pen I set "capture drops" to truextrue on the entity. Than during specific ticks I check the drop list and drop the items. It's done this way so I make sure that when other mods drop items via entity.dropitem (). I can filter them thur the pens into inventories.

**Comment by GenDeathrow** [comment]
Any word on this, cause I am still getting issues on this?

**Comment by jkiejr** [comment]
plz, fix this. im begging you

**Comment by Twisted-Code** [comment]
@GenDeathrow you're sure you're doing everything you can on your end to resolve this/duct tape around this? Maybe also consider submitting a PR? Honestly I'd submit one myself, but I don't know shit about programming in Java (yet)
Also, I've noticed that the incompatibility with your mod causes items to be teleported to the origin chunks (chunks near 0,0,0) under certain circumstances. Probably nesting pens in lazy chunks?

**Comment by GenDeathrow** [comment]
I'm using the one and only method forge has given me to capture drops from entities. There basically is no other way.. if forge had an event for drops Id use that. But their only event is basically if the chicken dies. The other is when an item is created but doesn't give the origin(ie chicken) that made it. 

So, I used this method to catch my drops plus vanilla drops, and any modded drops from said chicken.  I mean I could easily handled my egg & feather drops, but any mod that adds drops will drop outside nesting pens.

As far as the 0,0,0 thing, I feel sponge doesn't like my fake entities. 

Id do a PR but tbh I have no idea how to fix their code to make it work.

**Comment by gabizou** [comment]
I’ve been working on this to resolve the hatchery issue.

**Comment by Zidane** [comment]
Closing this as we now have a project open to handle the Drops Refactor

https://github.com/orgs/SpongePowered/projects/12
