### ISSUE TITLE
crashes since SF 2254 NullPointerException: Exception in server tick loop

### ISSUE THREAD

**Issue by johnfriedrich** [SpongePowered/SpongeForge#1401]
Since SF 2254 I am getting server crashes with FTB Beyond. I am sure, the global Causetracker commit is causing this, as I am running on 2250 since then and the server isn't crashing anymore.

The mod tracks, if a player uses a bed. I think during the crash, the mod tried to update the players sleep state and during that, the player lost the connection or logged out(?) That's why it crashed(?)
mc crashlog:
https://pastebin.com/hGJucB4H

**Comment by axle2005** [comment]
The answer to this one is quite easy: The Morpheus dev has decided he does not support sponge, so just uninstall Morpheus. 

[Link to Morpheus Github](https://github.com/Quetzi/Morpheus/issues/21#issuecomment-289492033)

**Comment by johnfriedrich** [comment]
Well, i don't see the point, but hey..
Okay. Thanks for the hint.

**Comment by ktole1999** [comment]
no mod dev supports sponge when troubleshooting. this is why they say test in non sponge environment. i have this running just fine on my sponge server.

**Comment by axle2005** [comment]
Its a hit or miss thing... I have heard several large server networks having this exact same issue when they hit 2254. Its a pretty insignificant mod. 

Also, do not simply say 'no mod dev supports sponge' as that is lie. There are a few that accept sponge is a thing and support it much like how Thermos or KCauldron were supported.

**Comment by ktole1999** [comment]
did not say they didnt support it. i said "no mod dev supports sponge when troubleshooting." there is a difference
