### ISSUE TITLE
Server Crash - epicsiegemod

### ISSUE THREAD

**Issue by Yorkforce** [SpongePowered/SpongeForge#1405]
I did originally report this to the mod(pack) dev but it would appear to be a SpongeForge issue
https://github.com/Darkosto/InvasionIssues/issues/49

Summary:
Ran into this issue tonight:
https://pastebin.com/BLPwP3Qr

I believe it's related to mobs digging, after removing the mobs listed under the S:"Digging Mobs" entry in the config, the crash stopped.

**Comment by bloodmc** [comment]
The Epic-Siege mod is using reflection to replace the entity AI tasks instance with their own proxy as shown here

https://github.com/Funwayguy/Epic-Siege-Mod/blob/1.10/src/main/java/funwayguy/epicsiegemod/handlers/MainHandler.java#L61

Replacing a core class instance like they are doing is just asking for trouble. I also do not see how this is only a Sponge issue as any mod that uses the AI tasks instance BEFORE they replace it entirely would also crash. There is no guarantee that their handler would run before other mods.

Regardless, I'll work on a fix =)
