### ISSUE TITLE
org.spongepowered.common.event.tracking.phase.block.BlockDro

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1406]
Hi there - 

I've got a pretty fresh world (less than a day old), that is currently running spongeforge-1.10.2-2254-5.2.0-BETA-2262.jar. When my players are exploring, the following floods the console. 

https://pastebin.com/FbY2X6YR

I haven't been able to isolate it from anything other than exploring. Biomes o Plenty has been disabled, thinking it had something to do with how that plugin handles land generation, but the issue still persists.

**Comment by gabizou** [comment]
Duplicate of #1404
