### ISSUE TITLE
[1.11.2] Exception during phase body crash

### ISSUE THREAD

**Issue by Mohron** [SpongePowered/SpongeForge#1408]
SF: spongeforge-1.11.2-2227-6.0.0-BETA-2260.jar

The server crashes on me everytime I use the ExU 2 Crusher on some blaze rods. Right before the crash there's a Spong error.
[Crash](https://hastebin.com/siyerufiki.sql) | [Log](https://gist.githubusercontent.com/Mohron/e1283cd8ec189ce5c7ab24b2e39ecf1f/raw/88d87205fbfaaf86ab88983257b8694aa503c747/server.log)

**Comment by bloodmc** [comment]
@Mohron test without SpongeForge.

**Comment by bloodmc** [comment]
ExtraUtilities 2 bug

https://github.com/rwtema/extrautilities/issues/1409

**Comment by Mohron** [comment]
Damn. I was actually hoping it would get fixed... RIP
