### ISSUE TITLE
Wireless Crafting Terminal not working

### ISSUE THREAD

**Issue by phit** [SpongePowered/SpongeForge#1411]
No items are showing up in the terminal and this is in the console
http://vpaste.net/iJpBv

WirelessCraftingTerminal-1.10.2-0.0.17.jar
appliedenergistics2-rv4-alpha-11.jar
spongeforge-1.10.2-2254-5.2.0-BETA-2264.jar

**Comment by phit** [comment]
note this works in 2262, so something in the inventory changes broke this

**Comment by JaSpr** [comment]
Came here to see if there was a ticket for this from the latest build.  There is.  Our users are having this issue, too.

**Comment by Faithcaio** [comment]
duplicate to https://github.com/SpongePowered/SpongeCommon/issues/1281
