### ISSUE TITLE
Exception Ticking World (Invalid Villager profession id is present)

### ISSUE THREAD

**Issue by Twisted-Code** [SpongePowered/SpongeForge#1412]
https://gist.github.com/macks2008/165606051d68477ba872ff1df0e1af6c As far as I can tell,  something made this librarian so it has a wrong profession ID, and now whenever I log in (presumably because I was in the chunk and tried  interacting  with the villager), the server crashes. Is there any viable solution besides rolling the map back and deleting the villager, and perhaps any other villagers nearby?
probably going to roll back just because it's easier & faster a solution at the moment, though I'm going to try a couple more times to see if the game will "fix" the villager on its own

**Comment by Twisted-Code** [comment]
err, to clarify, this crash started happening after I tried trading with the librarian in question

**Comment by Twisted-Code** [comment]
it seems to only happens sometimes. Sometimes I'm able to connect to my server without it crashing, and just now it crashed while I wasn't even online, although I think one of my other players might have been?
https://gist.github.com/macks2008/d4150da06c69bc1cebf61831085436a5

**Comment by Twisted-Code** [comment]
on further inspection, it seems to have nothing to do with the librarian, but rather loading (or perhaps unloading?) chunks with corrupt villagers. I was the only one online and, while exploring presumably-new chunks, the server crashed again with the same error.

**Comment by ktole1999** [comment]
duplicate issue. please use search to locate original post and make comment there.

**Comment by Twisted-Code** [comment]
I tried? Didn't find anything mentioning invalid villagers,, but maybe I'm just bad at using the search function on here

**Comment by Twisted-Code** [comment]
Okay, apparently I  forgot to include closed issues. that filter being on by default really gets me sometimes...

I still feel compelled to ask on this thread (although I'll also ask on one of the others): why not catch something like this and simply delete or reset the object with the invalid data (in this case, the villager)?

**Comment by Aaron1011** [comment]
Fixed in the latest `stable-5`.
