### ISSUE TITLE
[1.11.2 - build 2260] ShulkerBox.getRootLens

### ISSUE THREAD

**Issue by bhi-elliot** [SpongePowered/SpongeForge#1413]
Complete Server crash... seems like it has something to do with Shulker boxes and Lens...

Not much info here, sorry, and I do not know enough about this stuff to help out more than provide the following. This was all I was able to get from the logs:

https://pastebin.com/U3paAWxY

**Comment by Faithcaio** [comment]
This is already fixed. Update to latest. (2264+)

**Comment by bhi-elliot** [comment]
ah, okay. thanks. I have updated.
