### ISSUE TITLE
/tellraw to console

### ISSUE THREAD

**Issue by crymates** [SpongePowered/SpongeForge#1416]
Could you make it possible to /tellraw something to the console only?

Like `tellraw @c {\"text\":\"For admin overview in log and live console\",\"color\":\"gold\"}`

`@c`  or `-` for the console.

**Comment by mattmess1221** [comment]
It's easy to do this from a plugin using `Game.getConsoleSource()`. A plugin could also create the command.

**Comment by kashike** [comment]
I'm not sure if we want to start adding our own selectors to commands.

**Comment by crymates** [comment]
I would appreciate it. What does the label system:commands say about the status of this issue report? :)

**Comment by stephan-gh** [comment]
@yololetsplay It means that this is an issue related to the command system ;)

**Comment by crymates** [comment]
@Minecrell Thx for ur quick respond :) Good to know.

**Comment by mattmess1221** [comment]
@yololetsplay Do you want a command that can display on the console or custom selectors?

**Comment by crymates** [comment]
@killjoy1221 It should be displayed on the console :)

**Comment by mattmess1221** [comment]
You misunderstand me. A plugin can easily be implemented to do the ***exact*** thing you want.

`/helpop This message will go to the console`

```java
Sponge.getServer().getConsole().sendMessage(Text.of(message));
```

What I'm confused about is if you want a new selector. I'm not too familiar with how they work, but I would assume using a custom `CommandElement` would work.

**Comment by crymates** [comment]
Oh didn't knowed that /helpop is possible.
Something like this is what we want.
Why an selector? It's not really needed if another way like `/helpop` do this.

**But:**
/helpop isn't shown in console if I run it.
It should be just an easy way to message the console about something, also colored.

E.g. `/sendconsole &4This message is shown in console.`

**In console u just see in red:**

`This message is shown in console.`

The player do not get's any information about success, for example `Your message was sent` or something, like an **hidden information for the server** if you work with e.g. the plugin `Aliases`.

**Comment by mattmess1221** [comment]
This is getting off topic. Visit the forums or irc for programming help.

**Comment by crymates** [comment]
Ur right. Do u are an dev and have some time meet in IRC?

**Comment by mattmess1221** [comment]
People are always on IRC.

**Comment by crymates** [comment]
I've sent u an mail :)
