### ISSUE TITLE
Hunger/Life reseting in the client side on world change

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeForge#1418]
When a player changes world (overworld -> nether, nether -> overworld, overworld -> spawn, etc) his life and food are reseted visually. On walk or hurt, the client will update to the right info.

**Comment by dogboy21** [comment]
This also affects the experience value

**Comment by Zidane** [comment]
@Eufranio 

Closing this as you aren't providing any information. SF version? Forge version? Log? Tickets like these are going to start being auto-closed as we need information.
