### ISSUE TITLE
Easy duplication of items on Sponge servers

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1419]
With Sponge installed, players can duplicate items by placing two pieces of sand on top of each other, an item frame on the top piece and a sign on top of the frame. Breaking the bottom piece of sand glitches it out and dupes the item. Video shows the bug:

https://i.gyazo.com/5cabeaae086e48abf7126e2044874a05.mp4

**Comment by gabizou** [comment]
Need more information than this... Versions, any sort of logs, I'm sure there's going to be some exceptions somewhere (make sure the cause tracker verbose is on).

**Comment by ghost** [comment]
Everything is on latest versions of 1.10. 
Forge 2254 and SpongeForge 2264.

When I perform this dupe, no exceptions or errors are printed to console.
All options under the cause-tracker section are turned to true.

Here is a copy of the fml-server-latest: 
https://gist.githubusercontent.com/Zachincool/4c1a0890c500dddb658e26c4cf1735eb/raw/1a91a05ac4cec6232939805b00e5192cdc1be209/latest

**Comment by Yorkforce** [comment]
We also see this kind of thing alot, for example skyclaims schematics also dupe items if an island schematic is reapplied over an old one, it's literally the same thing occurring where a block is removed thats attached to some kind of container, is it related to the cancelling of events perhaps? #1376

**Comment by Eufranio** [comment]
Confirm this dupe. `report-different-world-changes=true`, `verbose=true`, `verbose-errors=true` and **no** errors/stacktraces are being generated when this dupe happens. Running latest too.
