### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by KappaKiddie** [SpongePowered/SpongeForge#1424]
https://pastebin.com/WxjHLKCD

**Comment by gabizou** [comment]
Provide more information. What happened what was happening etc. just providing a stacktrace will prompt us to close an issue outright.

**Comment by stephan-gh** [comment]
Has this happened more than once? If not, I wouldn't worry about it too much because it looks like a problem in JLine or your terminal configuration.

**Comment by phit** [comment]
No response and not enough information to reproduce.
