### ISSUE TITLE
Extra Utilities Sickle Does not trigger correctly on grass and gives no loot/drops.

### ISSUE THREAD

**Issue by StoneLegion** [SpongePowered/SpongeForge#1430]
forge-1.10.2-12.18.3.2254-universal.jar
spongeforge-1.10.2-2254-5.2.0-BETA-2264.jar

extrautils2-1.10.2-1.3.2.jar

Pretty much the Sickles are 100% broken and no drops come from it sadly.

**Comment by Rongmario** [comment]
Does ThermalExpansion ones work?

**Comment by StoneLegion** [comment]
I sadly don't have thermal expansion I'm using a pack called All The Mods Expert.

**Comment by phit** [comment]
still an issue with
extrautils2-1.10.2-1.5
spongeforge-1.10.2-2281-5.2.0-BETA-2464

**Comment by phit** [comment]
still an issue with
extrautils2-1.12-1.6.7.jar
spongeforge-1.12.2-2529-7.0.0-BETA-2741.jar
