### ISSUE TITLE
Sponge Crash - A required class was loaded prematurely! (CustomThings3)

### ISSUE THREAD

**Issue by Rongmario** [SpongePowered/SpongeForge#1431]
https://hastebin.com/ineyawudiz.md

**Comment by Rongmario** [comment]
Turns out it was CustomThings3.

**Comment by gabizou** [comment]
Nothing Sponge can do. CustomThings3 can avoid class loading the `Block` class prematurely (i.e. when it's not supposed to), or you can use [SpongeBootstrap](https://forums.spongepowered.org/t/spongebootstrap-fixes-ordering-issue-with-other-coremods/12275) temporarily to avoid the issue.

**Comment by Rongmario** [comment]
It's all good, I was just testing CT3 thinking it'd happen, SpongeBootstrap does not actually fix it still for some reason.
