### ISSUE TITLE
No ambient spawns, again

### ISSUE THREAD

**Issue by phit** [SpongePowered/SpongeForge#1432]
~~Worked fine in 2234-2262, just updated to latest (2274) and no more ambient spawns not sure in what build it broke.~~

Not a sponge bug

**Comment by JaSpr** [comment]
@phit Where was the bug?  We're running a Sky Factory 3 sponge server and are also getting 0 bats.

**Comment by phit** [comment]
There was no bug, my users were just blind or impatient.. I raised the spawn caps a bit and now everyone seems to be happy.

**Comment by JaSpr** [comment]
All the posts online about this seem to point to the same solution.  How do I go about raising the spawn limits on my sponge server.  The only thing I find mentioning "spawn limit" is in a group called "spawner", which seems like it may control how spawners function, not how natural spawning happens.

**Comment by phit** [comment]
spawner is for all spawns https://github.com/SpongePowered/SpongeCommon/commit/9e2868044f981a3ead5a771cec837a362b6983e4

**Comment by JaSpr** [comment]
is it necessary to change it in all the conf files that reference the overworld (e.g. worlds/minecraft/overworld/world.conf AND worlds/minecraft/overworld/dimension.conf AND global.conf?)

**Comment by phit** [comment]
https://docs.spongepowered.org/stable/en/server/getting-started/configuration/index.html
