### ISSUE TITLE
Invalid InventoryPacketState on Middle-Mouse click in Inventory

### ISSUE THREAD

**Issue by NickImpact** [SpongePowered/SpongeForge#1434]
So upon testing of a custom UI in my plugin, I encountered a state which is still blocked by click events (luckily), but appears to have something invalid going on internally. On each attempt at a middle-mouse click, or item cloning, a message (listed below) is sent to the console regarding an InventoryPacketState handler which could not be found. 

`[Sponge]: Unable to find InventoryPacketState handler for click window packet: CPacketClickWindow{windowId=1, slotId=3, usedButton=0, actionNumber=1, clickedItem=null, mode=CLONE}`

Sponge Version: spongeforge-1.10.2-2281-5.2.0-BETA-2274
Forge Version: forge-1.10.2-12.18.3.2281-universal

**Comment by phit** [comment]
Can't reproduce on 1.10.2-2477-5.2.0-BETA-2698 or 1.12.2-2529-7.0.0-BETA-2741, middle clicked in survival and creative, empty slots and filled slots and also tried the pickblock feature.

If this is still an issue for you, feel free to reply with more information on how to reproduce it and I'll be happy to reopen this.
