### ISSUE TITLE
[1.11.2 build 2270] Server crash - stalled

### ISSUE THREAD

**Issue by bhi-elliot** [SpongePowered/SpongeForge#1436]
Hello,
Just reporting a crash. Just 1 player on at the time, said they were just doing normal block breaking (mining), nothing too intense. Unfortunately, I do not know enough about this to give you more info than the logs. The last few lines in server log report:
```
[Server Watchdog/FATAL]: A single server tick took 60.24 seconds (should be max 0.05)
[Server Watchdog/FATAL]: Considering it to be crashed, server will forcibly shutdown.
```

So it seems like it stalled. Whether that was the server or the computer, I do not know. Here is the crash log:
Crash log:
https://pastebin.com/fwLEqDvC

Hope that helps. Thank you!
I am now updating to build 2275 in the hopes that that will help.

**Comment by Zidane** [comment]
Need more information...such as mods being used. Closing till we get it or if no response we'll assume fixed.

**Comment by bhi-elliot** [comment]
Hi! Thank you for looking into this.
I have long since updated the server and mods and haven't had the exact same crash since, so it might have been fixed.
In any case, here are the mods that were being used at the time:
ironchest-1.11.2-7.0.18.800
Nucleus-0.27.1-1.11.2-S6.0-plugin
spongeforge-1.11.2-2227-6.0.0-BETA-2270
worldedit-sponge-6.1.7-SNAPSHOT-dist
