### ISSUE TITLE
server crash when someone sleep

### ISSUE THREAD

**Issue by fabri2000779** [SpongePowered/SpongeForge#1438]
spongeforge-1.10.2-2281-5.2.0-BETA-2274.jar

Hello like the title says my server crash when someone sleep, my server is on FTB Beyond v1.5.1
Crash report:  https://pastebin.com/cZYqpDR5

**Comment by Zidane** [comment]
There is no reference to anything regarding Sponge in this stacktrace. Remove Sponge and verify. If the issue goes away, we'll re-open.

**Comment by fabri2000779** [comment]
look this and yeah when i remove sponge server dont crash if someone sleep https://github.com/Quetzi/Morpheus/issues/21

**Comment by phit** [comment]
dupe of #830
