### ISSUE TITLE
Beyond Sponge Class Issue

### ISSUE THREAD

**Issue by Keaton1188** [SpongePowered/SpongeForge#1439]
Hi all, I am having a issue when updating our Beyond server, all files were transferred correctly etc. Its on the boot-up it dies. Error Below

Using the newest sponge version
(Also want to fix this without using Sponge Bootstrap)

![untitled](https://cloud.githubusercontent.com/assets/24898745/25057593/2c7dbb5e-2169-11e7-9f9b-5d8aad054df8.png)

**Comment by Deamon5550** [comment]
A full log would help, and you can start removing mods that have coremods one by one until you find the one breaking it.

**Comment by phit** [comment]
applied energistics 2 is the only mod in beyond that doesn't let the pack boot

https://github.com/Stonebound/Applied-Energistics-2#about

**Comment by jackytuutykcaj** [comment]
Try reuploading your libraries folder. My server seems to work fine with latest spongeforge(spongeforge-1.10.2-2281-5.2.0-BETA-2274.jar) and latest beyond(FTBBeyond-1.5.3-1.10.2). If you dont want to use bootstrap, use one of the ae2 files from the link phit gave you.

**Comment by Keaton1188** [comment]
Yea, got it all sorted now.

Thanks anyway all!
