### ISSUE TITLE
Sponge Version 2274 - Quantum Quarry issue

### ISSUE THREAD

**Issue by Keaton1188** [SpongePowered/SpongeForge#1440]
Hi again, seems that with the newest version of sponge (2274) it has stopped Quantum Quarries from working on all the 1.10 packs (Beyond, SF 3, Inf lite etc) 

Seems that the Dimension is not even being loaded (check in /gc and its not there) and then when you give the Quarry power and a chest etc, it just stays at 0 RF. Any idea?
![2017-04-14_23 44 18](https://cloud.githubusercontent.com/assets/24898745/25057953/a8cdcffc-216c-11e7-9cb8-8c53eec2f264.png)

**Comment by ktole1999** [comment]
have you tried different power source?

**Comment by Keaton1188** [comment]
Just tested with some Clockwork Engines and they DID put RF into the quarries, the Capacitor banks however, don't.

They used to and now don't anymore.

Update - Just tested with some solars from Solar Flux Reborn, it goes to power the quarry then just stops and goes back to 0 (RF) also kicks you out of the quarry (when you right click on it for where the upgrades go etc)
