### ISSUE TITLE
Tracking Crashes (2274)

### ISSUE THREAD

**Issue by Dysthymic** [SpongePowered/SpongeForge#1442]
https://pastebin.com/LyT4w3qi
We are getting this crash on our servers a couple times per day with Sponge 2274 and Forge 2281

**Comment by Aaron1011** [comment]
@Dysthymic: Can you upload your `fml-server-latest.log` and `latest.log`?

**Comment by Dysthymic** [comment]
Yeah, it hasn't happened for 5 days on one server and 2 days on the other server. It really started slowing down the past few days which is strange. I'll keep an eye out in the next 24 or so hours and provide those logs once they are available to me again if it happens again

**Comment by Dysthymic** [comment]
FML: https://pastebin.com/mftPFE6v
Latest.log: https://pastebin.com/5Uu5V28L
Happened a couple times earlier today
@Aaron1011

**Comment by bloodmc** [comment]
Reopen if this still occurs with latest builds.
