### ISSUE TITLE
SimpleDimensions Incompatibility

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [SpongePowered/SpongeForge#1444]
Crash Log
https://gist.github.com/P3rf3ctXZer0/e7ab126c5dc90dfb6236be0d66152afa

The whole server crashed after I used "SimpleDimensions" to create a island water dimension.

Additional Information
After I reloaded the server my simple dimension was completely erased. Probably going to remove sponge til its fixed.

edit by phit: Simple Dimensions (for search)

**Comment by ktole1999** [comment]
or you could use different mod to create your world.

**Comment by phit** [comment]
I can't even make a dimension
spongeforge-1.10.2-2281-5.2.0-BETA-2464.jar
SimpleDimensions-MC1.10-1.3.jar

https://gist.github.com/phit/448e3da699357adef5802020d4864407

**Comment by Zidane** [comment]
@phit 

I'm going to be investigating some world issues as we've got some bugs cropping up.

**Comment by phit** [comment]
spongeforge-1.12.2-2529-7.0.0-BETA-2741.jar
SimpleDimensions-MC1.12-1.3.1.jar

https://gist.github.com/phit/ac0acb4db7aa7e10412ca36ac0e2d53f

**Comment by Zidane** [comment]
This is being labelled as a won't fix.

Forge has a DimensionManager, the mod kindly uses it here:

https://github.com/lumien231/Simple-Dimensions/blob/master/src/main/java/lumien/simpledimensions/dimensions/DimensionHandler.java#L194

Then turns around and side-steps the Forge DimensionManager here:

https://github.com/lumien231/Simple-Dimensions/blob/master/src/main/java/lumien/simpledimensions/dimensions/DimensionHandler.java#L200

We're not supporting that.

**Comment by P3rf3ctXZer0** [comment]
@Zidane I am not using sponge forge. Also I do use the forge dimension loader so saying won't fix to my report is the same as leaving this mod broken.
