### ISSUE TITLE
Exception in world tick?

### ISSUE THREAD

**Issue by Rongmario** [SpongePowered/SpongeForge#1446]
https://hastebin.com/ehuxoburur.scala

**Comment by gabizou** [comment]
Version information? What happened before the crash? This looks like you have sponge on the client, but we don't modify the client in any of the ways that it crashed as is.

**Comment by Rongmario** [comment]
That's a server crashlog. 

>spongeforge-1.10.2-2281-5.2.0-BETA-2274

**Comment by gabizou** [comment]
> That's a server crashlog.

Most definitely not. It's referencing client code, which doesn't exist on the server. And still you haven't included what actually happened...

**Comment by gabizou** [comment]
Closing as no information is provided. Server logs missing, issue description is missing, logs provided are from the client, not the server, and sponge isn't installed on the client.
