### ISSUE TITLE
Server Crash While Teleporting Through Dimensions

### ISSUE THREAD

**Issue by RogueRaiden** [SpongePowered/SpongeForge#1447]
Server crash when using Draconic Evolution Dislocator, teleporting from Nether to Overworld. No other players online.

Crashlog shows Morpheus as being the cause. I created an issue on that mods page and they said that it is a bug through Sponge.
Not sure if this is enough information, and I thought i'd create an issue here so you guys are aware of this, if this is actually an issue through Sponge.

https://pastebin.com/ZWGTmJV3

**Comment by phit** [comment]
dupe of #830
