### ISSUE TITLE
Aether inventory crashing when sponge is installed.

### ISSUE THREAD

**Issue by BlueCyro** [SpongePowered/SpongeForge#1448]
Hi, it seems Aether Legacy(?) is causing issues with sponge when the inventory is opened.
Sponge version: 1.10.2-2281-5.2.0-BETA-2274
Disconnect error: https://pastebin.com/rsiztgf7

**Comment by Zidane** [comment]
@Faithcaio 

Is this resolved?

**Comment by Faithcaio** [comment]
should be fixed with latest build
