### ISSUE TITLE
Is there any way to create item using existing blocks with metadata?

### ISSUE THREAD

**Issue by loveyanbei** [SpongePowered/SpongeForge#1449]
I got problems creating itemstack from existing block data
Example:
I have a farm block from forestry placed on the ground
and I want to create an Itemstack from it
first I use getBlock() API and got the block object, great
according to doc I used Itemstack.builder().fromBlockState, OK , the stack has been created but..
Because forestry farm blocks shared the same id , with different meta
like gearbox => forestry:ffarm[meta=gearbox]
controller => forestry:ffarm[meta=controller],etc
The Itemstack created shows me only "Block{forestry:ffarm}"
with meta missing
How can I create a block with meta?

**Comment by loveyanbei** [comment]
val entity = world.createEntity(EntityTypes.ITEM, location.getPosition)
entity.tryOffer(Keys.REPRESENTED_ITEM, itemStack.build().createSnapshot)

and the entity is just the default , without metadata / Traits

**Comment by phit** [comment]
this is an issue tracker and not a support forum, you can get help here:
Forums: https://forums.spongepowered.org/c/plugins/plugin-development
IRC: https://webchat.esper.net/?channels=spongedev
Discord: https://discord.gg/PtaGRAs
