### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by alldaywarrior** [SpongePowered/SpongeForge#1450]
I use sponge and now the server crashes at randomly times. Players tell me that its very annoying, but i cant find out whats the problem. I hope one of you guys can tell me which mod I have to delete? I don't want to delete sponge because I think there is another mod/plugin crashing the server?

Forge version is 2254

https://pastebin.com/YUnkCkkp

**Comment by me4502** [comment]
From a quick glance it appears to be an issue with MineTweaker

**Comment by axle2005** [comment]
We actually disabled staff being able to us OP because of this. I mean its a lot more secure anyway to flush out perms... but this is a **Chance cube** thing. If anyone is in the OP list, this occurs. 

Simple solution: Delete the ops.json file and don't use /op

**Comment by Zidane** [comment]
Not a Sponge issue. Go to MineTweaker and report if still a problem.

**Comment by ryantheleach** [comment]
I suspect this was fixed looking at the history of: https://github.com/jaredlll08/CraftTweaker/blob/c6ff5111ff5d78d0ce4c6f07f710724e6c7e7eae/MineTweaker3-MC1102-Main/src/main/java/minetweaker/mc1102/server/MCServer.java
