### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by ArcasCZ** [SpongePowered/SpongeForge#1452]
https://pastebin.com/6UXSbbiB

**Comment by Aaron1011** [comment]
@ArcasCZ: Are you able to reproduce this consistently? If so, please list the steps to do so, along with a list of all mods you have installed.

**Comment by ArcasCZ** [comment]
I can't. One of our players says it happens occasionally with some item in inventory.

**Comment by Faithcaio** [comment]
This should be fixed.
