### ISSUE TITLE
FTB Beyond - massive error flood & server hangs

### ISSUE THREAD

**Issue by mkrtes** [SpongePowered/SpongeForge#1453]
Apparently, this is due to the generation of the world
https://pastebin.com/zinmryZ3

**Comment by phit** [comment]
please use pastebin/hastebin

**Comment by Deamon5550** [comment]
Seems to be harvestcraft and natura causing the recursive generation, update natura to the latest they recently fixed this. 

See https://github.com/MatrexsVigil/harvestcraft/issues/270 for an open issue with harvestcraft for this.

Related: #1443

**Comment by Zidane** [comment]
Closing as this isn't a Sponge issue.
