### ISSUE TITLE
Exception during phase body

### ISSUE THREAD

**Issue by filipsowka** [SpongePowered/SpongeForge#1459]
Minecraft crashed after dead. I can't open inventory, it kills me while I'm moving and this error appears:
[LINK](https://gist.github.com/filipsowka/be301c1628a9264e8fb048ac806b62f6)
I've got the newest sponge version and the newest forge.

**Comment by filipsowka** [comment]
OK, I managed to do this myself.
It was a problem with the TrashSlot mod.
When I deleted it, it's fine.

**Comment by Faithcaio** [comment]
Our lenses are currently constructed after the Container construction. (`MixinContainer#init`)
Even if the `ContainerPlayerInventoryLens` were constructed dynamicly (in ContainerUtil#getLens/generateLens) it could not handle slots added later:
https://github.com/blay09/TrashSlot/blob/1.10/src/main/java/net/blay09/mods/trashslot/CommonProxy.java#L49

**Comment by phit** [comment]
fixed in https://github.com/SpongePowered/SpongeCommon/commit/f6c23f5ce7ef494a44589471928cfbfe1da4fd23
