### ISSUE TITLE
Possible conflict between this mod and Mowzie's Mobs

### ISSUE THREAD

**Issue by Sunconure11** [SpongePowered/SpongeForge#1461]
https://pastebin.com/p4WSiRgh

Not sure of the frequency of this crash, but it appears to be related to Mowzie's Mobs.

SpongeForge version: spongeforge-1.10.2-2281-5.2.0-BETA-2274

Forge version: forge-1.10.2-12.18.3.2281-universal

**Comment by Sunconure11** [comment]
https://github.com/BobMowzie/MowziesMobs/issues/2

**Comment by pau101** [comment]
This was fixed later in the 1.11 release by SpongePowered/SpongeCommon@cd4eacb

**Comment by Sunconure11** [comment]
@pau101 Is it possible to bring that to 1.10.2? Because that is where the crash happened.

**Comment by Sunconure11** [comment]
Any news regarding this issue? Users keep inadvertently triggering this issue on my server (for 1.10.2, that is)

**Comment by pau101** [comment]
I've replied on the other issue https://github.com/BobMowzie/MowziesMobs/issues/2#issuecomment-298141026

**Comment by Sunconure11** [comment]
I saw. The issue is just getting bothersome, that is all.

**Comment by gabizou** [comment]
@bloodmc didn't your commit from a few days ago resolve this?
