### ISSUE TITLE
IC2 explosion event cannot be captured

### ISSUE THREAD

**Issue by loveyanbei** [SpongePowered/SpongeForge#1462]
When a IC2 TNT , IC2 nuke or IC2 Nuclear Reactor was placed near residence and detonated.
RedProtect plugin cannot protect the residence from being affected.
I tried to print log in onExplosion(ExplosionEvent.Detonate event) but the listener callback was not called
I think sponge forge didn't catch the explosion caused by mod..

**Comment by loveyanbei** [comment]
Will you fix it in the future?
I mean if can hook to all classes extended from NMS classes, it will be not necessary for me to write an extra plugin to hook into IC2Explosion, IC2Potion,etc.

**Comment by Eufranio** [comment]
I created an issue here: https://github.com/SpongePowered/SpongeForge/issues/1383 about the explosions.

**Comment by phit** [comment]
dupe of #1383

**Comment by kashike** [comment]
Duplicate of #1383.
