### ISSUE TITLE
Sponge causing QuantumQuarry crash

### ISSUE THREAD

**Issue by KappaKiddie** [SpongePowered/SpongeForge#1464]
**Crash:** https://pastebin.com/V8BNyE4r**

- SpongeForge version: 1.10.2-2254-5.2.0-BETA-2272
- Forge version: 2254
- Java version: 
- Operating System: 
 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [  ] macOS
 - [  ] Windows

**Comment by liach** [comment]
Is that a compile error?

**Comment by Deamon5550** [comment]
No thats just your server timing out. Raise the max-tick-time and/or use `/sponge timings` or a profiler to find the source of the slow down.

**Comment by KappaKiddie** [comment]
How I raise the max-tick-time ?

**Comment by phit** [comment]
https://www.google.com/search?q=max-tick-time

**Comment by KappaKiddie** [comment]
I raise for 100k, 200k, 80k and didn't work

**Comment by jackytuutykcaj** [comment]
Try -1. It works for me.

**Comment by jackytuutykcaj** [comment]
The maximum number of milliseconds a single tick may take before the server watchdog stops the server with the message, A single server tick took 60.00 seconds (should be max 0.05); Considering it to be crashed, server will forcibly shutdown. Once this criteria is met, it calls System.exit(1).
-1 - disable watchdog entirely (this disable option was added in 14w32a)

**Comment by KappaKiddie** [comment]
I will try, thanks

**Comment by KappaKiddie** [comment]
Don't crash, but consumes energy and don't mine nothing
