### ISSUE TITLE
Issues with Valkyrien Warfare and Thuttech mods.

### ISSUE THREAD

**Issue by DrakeEldridge** [SpongePowered/SpongeForge#1465]
When I use these mods in SP everything works fine. But copying the single player map and moving it to the forge server, the ships from Valkyrien Warfare and the elevators from Thuttech mod gets deleted.
Making new ships from Valkyrien Warfare works fine, but making new elevators doesn't. They break, get stuck, have to relog to see them move. Can't delete them. As soon as I remove sponge, it breaks the mod. I have taken all my plugins (Listed below) and removed them. Then I try it without spongemod, works fine, try it with spongemod (no plugins) and it breaks. So its definitely sponge.

- SpongeForge version:  spongeforge-1.10.2-2254-5.2.0-BETA-2269
- Forge version: forge-1.10.2-12.18.3.2272-universal
- Java version: 8
- Operating System: Windows 10

Plugins:
AutoBroadcasterSponge-0.2.1
CommandKits-v1.2.0
CommandSigns-API-6.0.0-1.3.1
EMPSponge
holograms-2.2
Inspector-0.6.4
PermissionsEx-Sponge
RCameraStudio-1.1.0
UniverseGuard

Modss:
3DManeuverGear-1.10.2-0.4.0
AppleCore-mc1.10.2-2.1.2
Baubles-1.10.2-1.3.9
BedBugs-1.10.2-1.1.6
BetterQuesting-2.3.225
bqautoreload-1.5.0
cfm-4.1.2-mc1.10.2
chiselsandbits-12.12
CodeChickenCore-1.10.2-2.4.0.101-universal
CodeChickenLib-1.10.2-2.5.6.233-universal
ConquestReforged-2.0.1-RC1-mc.1.10.2
Currency-1.10.2-1.0.3
CustomMainMenu-MC1.10.2-2.0.2
CustomNPCs_1.10.2(17mar17)
Decocraft-2.4_1.10.2
DynamicSurroundings-1.10.2-3.3.7.0
EnhancedVisuals v1.0.12 mc1.9-1.10
expandableBackpacks1.1.10-1.10.2
extrautils2-1.10.2-1.3.3
FastAsyncWorldEdit-forge110-17.04.23-81b60f7-666-12.4.12
foamfix-0.6.2-beta4-anarchy
ForgeMultipart-1.10.2-2.0.0.31-universal
FTBLib-1.10.2-3.4.4
FTBUtilities-1.10.2-3.4.3
Harvest-Festival-1.10.2-0.5.26
iChunUtil-1.10.2-6.3.0
ImmersiveEngineering-0.10-57
infinitylib-0.4.0
journeymap-1.10.2-5.2.4-unlimited
malisiscore-1.10.2-4.4.0
malisisdoors-1.10.2-5.2.0
MCA-1.10.2-5.2.3-universal
MCMultiPart-1.4.0-universal
MoarSigns-1.10.2-4.2.2.8
More-Player-Models-Mod-1.10.2
Morpheus-1.10.2-3.1.13
MrTJPCore-1.10.2-2.0.0.14-universal
Neat 1.3-12
NPCIntegration-2.3.21
OptiFine_1.10.2_HD_U_D7
Pam's HarvestCraft 1.9.4-1.10.2h
ProjectRed-1.10.2-4.8.1.25-Base
ProjectRed-1.10.2-4.8.1.25-integration
ProjectRed-1.10.2-4.8.1.25-mechanical
RadixCore-1.10.2-2.1.3-universal
ResourceLoader-MC1.9.4-1.5.1
soundphysics-mc1.10.2-v1.0.0
SpiceOfLife-mc1.9.4-1.3.8
thutcore-3.12.2
thuttech-4.0.10.b
ToughAsNails-1.9.4-1.1.1
Valkyrien Warfare 0.8.999 Stable
worldedit-forge-mc1.10.2-6.1.4-dist

Meant to do:
Taking single player map and putting it onto forge server should keep the ships and elevators from Valkyrien Warfare and Thuttech mod.
ThutsTech Elevators go up and down when pushing the button.

Currently does:
Taking a single player map and putting it onto forge server delete the ships and elevators from Valkyrien Warfare and Thuttech mod.
Making a new Valkyrien Warfare works fine, but making a new Elevator does not.
The elevator goes up, doesn't want to go back down. Visually it's stuck, but if you relog it's down on the bottom floor. Can't delete it. It becomes useless. 

As soon as I remove sponge everything works and I can make new ships and elevators and I can copy my SP map and use it on the forge server. But with sponge, I get these issues.

Please fix this issue urgently. It seems this issue effects mods that make objects into moving dimensions like ship mods.
[logs.zip](https://github.com/SpongePowered/SpongeForge/files/953724/logs.zip)

Here is the server log:

**Comment by DrakeEldridge** [comment]
hello?

**Comment by bloodmc** [comment]
@DrakeEldridge Update to latest SpongeForge and retest. Make sure to provide complete logs.

**Comment by phit** [comment]
@DrakeEldridge still an issue?

**Comment by DrakeEldridge** [comment]
I do not know. I do not use Thuttech anymore (Use another elevator mod) and I have not tested Valkyrien Warfare is now 1.11.2 not 1.10.2 and I have yet to test it. Will test it when I have a working VW set up.

**Comment by phit** [comment]
I wasn't able to reproduce the elevator issues with Sponge 1.12.2-2529-7.0.0-BETA-2732 and thuttech-6.0.7, haven't tested VW yet.

**Comment by gabizou** [comment]
Closing this issue, as of today 1.10.2 and 1.11.2 are not longer supported. If a sufficiently, decent, and tested Pull Request is made to fix this bug/issue, it will still be considered, however, it is NOT to be expected that any bug fixes made for 1.12.2 will be back ported to 1.11.2 or 1.10.2.

If you can reproduce this issue with SpongeForge on Minecraft 1.12.2 and this issue was wrongly closed, please [open a new issue](https://github.com/SpongePowered/SpongeForge/issues/new) with updated information.
