### ISSUE TITLE
Issue with Extra Utilites 2 and SpongeForge

### ISSUE THREAD

**Issue by LIRIKKER** [SpongePowered/SpongeForge#1468]
**I am currently running...**
- SpongeForge version: spongeforge-1.10.2-2254-5.2.0-BETA-2272.jar
- Forge version: forge-1.10.2-12.18.3.2254-universal.jar
- Java version: Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
- Operating System:
 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: FTB Beyond 1.5.3
Plugins (189): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, Applied Energistics 2 Core, Aroma1997Core, Not Enough Items, OpenComputers (Core), SpongeAPI, SpongeForge, CoFH ASM, FoamFixCore, ccl-entityhook, CoFH Core, Actually Additions, IndustrialCraft 2, Advanced Machines, Advanced Solar Panels, Applied Energistics 2, BD Lib, AE2 Stuff, InfinityLib, AgriCraft, Baubles, Botania, Akashic Tome, Just Enough Items, AppleSkin, Aquaculture, ArchitectureCraft, Aroma1997Core|Helper, Aroma1997's Dimensional World, Morph-o-Tool, Psi, Quark, AutoRegLib, Bed Bugs, Better Builder's Wands, BiblioCraft, Guide-API, Blood Magic: Alchemical Wizardry, Blood Arsenal, Bookshelf, CodeChicken Lib, Brandon's Core, Ceramics, Chameleon, Chest Transporter, Chisel, MCMultiPart, Chisels & Bits, ShadowMC, Clipboard, CodeChicken Core, Compact Solar Arrays, Cooking for Blockheads, CraftTweaker JEI Support, MineTweaker 3, Dark Utilities, DebugServerInfo, PTRModelLib, Decocraft, Forestry, ElecCore, EnderStorage, OpenComputers, DeepResonance, Discord Bridge, Draconic Evolution, Storage Drawers, Drawers & Bits, Dynmap, Elevator Mod, Embers, EnderCore, Ender IO, Engineer's Workshop, Valkyrie Lib, Environmental Tech, ET Lunar, Extra Utilities 2, Zero CORE, Extreme Reactors, Flat Colored Blocks, SonarCore, FluxNetworks, FoamFix, Forgelin, Forge Multipart CBE, Forge Microblocks, Minecraft Multipart Plugin, FTBLib, FTBUtilities, Funky Locomotion, Funnels, GenDustry, Gravestone, Gravitation Suite, Hammer Core, HelpFixer, Hopper Ducts, Mantle, Tinkers' Construct, The One Probe, Immersive Engineering, LunatriusCore, InGame Info XML, Interaction Wheel, Inventory Tweaks, Iron Backpacks, Iron Chest, JEI Bees, JourneyMap, KleeSlabs, Long Fall Boots, MalisisCore, MalisisDoors, Mercurius, Modular ForceField System, MmmMmmMmmMmm, mob_grinding_utils, MTLib, Mod Tweaker, Railcraft, More Bees, Morpheus, ModPack Utilities, ModPack Basic Tools, MrTJPCore, ShetiPhian-Core, Multi-Storage, Natura, Nether Portal Fix, Nucleus, Open Glider, p455w0rd's Library, Pam's HarvestCraft, Prism, Progenitor, ProjectBorders, ProjectRed Core, ProjectRed integration, ProjectRed Transmission, ProjectRed Illumination, ProjectRed Expansion, projectred-tansportation, ProjectRed Exploration, RebornCore, QuantumStorage, Ranged Pumps, reborncore-MCMultiPart, RedProtect, Thermal Foundation, Redstone Arsenal, Refined Relocation, Refined Storage, Reliquary, RFTools, RFTools Control, RFTools Dimensions, Roots, Signals, SimpleVoidWorld, Simple Retrogen, Simply Jetpacks 2, Sleeping Bag, Snad, Solar Flux Reborn, Steve's Carts 2, Storage Drawers Extras, Super Circuit Maker, Super Crafting Frame, TechReborn, Thermal Expansion, Tinkers Tool Leveling, TOP Addons, TorchMaster, Translocator, Twitch Plugin, Useful Nullifiers, WanionLib, Wireless Crafting Grid, Wireless Crafting Terminal, Woot, WorldEdit, WirelessRedstone-CBE, XNet, YABBA, UniDict

**What is the expected result?**
When using the Quantum Quarry, quarryed items should output into a oak chest placed onto the Quantum Quarry.

**What is the current result?**
With Sponge Installed, the quarry shows item's being mined however nothing is outputted into the oak chest.

Without Sponge installed, item's are being outputted into the chest functioning correctly.

Server logs cannot be provided because no error messages are being outputted.

**Comment by Richetoku** [comment]
Works without sponge, but mines nothing with sponge. A visit to the mining dimension shows the blocks being mined but immediately landing on the ground resulting in a chunk full of dropped items.

**Comment by fabri2000779** [comment]
oh my god thanks to report this i believed that is a Extra U problem, but sponge hehe
