### ISSUE TITLE
Adding a party API

### ISSUE THREAD

**Issue by EliterScripts** [SpongePowered/SpongeForge#1469]
I was wondering if it's any good idea to add a party API to Sponge. I mean, I've seen on a minigame server where you have friends and you have parties. Parties develop your team, and they can do all sorts of cool stuff.

I was wondering if there could be a Sponge API for this, so it would streamline any other plugins that would like to include parties in their plugin. Not necessarily built-in commands to Sponge, but an API. You know.

Thanks!

**Comment by gabizou** [comment]
What would this API *do*? There's millions of ways parties can be written, so, kinda need some context as to what the API is supposed to do, and how it's supposed to be used (pragmatically, not just concept wise).

**Comment by kashike** [comment]
This sounds like something that should be left to plugins, really.

**Comment by ryantheleach** [comment]
@EliterScripts This sounds like a good idea for a plugin provided Service, (you may have previously been familiar with Vault) This will allow multiple plugins to both register to use and supply parties, without committing any hard interfaces into SpongeAPI.

I had been thinking some sort of generic "friend" service to be able to grant permissions to people on someones friend list would be something reasonably generic, and would likely be a good starting point if you pursue this.

Other things to consider would be some form of registry for message channels, so that they can be retrieved and used by other plugins.

**Comment by EliterScripts** [comment]
The thing is when you leave things like this to a plugin, plugins don't work with other plugins. When API's like Sponge come together and make things universal, and easier to accomplish things, you get something awesome. When you don't have a universal platform, you have a bunch of chaos, bad practices used, and incooperation between plugins, and a lot of hard coding.

What I want a party API to do is to store a list of players in a party, maybe store scores or some sort of economy collaboration (like, if a team wins, they all share a prize). So basically, I was thinking of a list (pretty easy, right?) of players in a party, setting up events like PVP against own party member, party win, party lose, add point/score, party destroyed, party expanded, party game switched (party leader chooses a game, and they all teleport to the game), party member sent message in chat, party member died.

All those events can make a universal platform (which is what Sponge is) for easy development for parties for games. It will allow for players to not have to make 2 parties--one party for one plugin and make another for another plugin.

**Comment by ryantheleach** [comment]
That's already far more opinionated then what I was imagining.

**Comment by parlough** [comment]
I'd also like to point out what you described is practically there in a sense already with Minecraft's own [Scoreboards](https://jd.spongepowered.org/6.0.0-SNAPSHOT/org/spongepowered/api/scoreboard/Scoreboard.html), [Teams](https://jd.spongepowered.org/6.0.0-SNAPSHOT/org/spongepowered/api/scoreboard/Team.html), [Objectives](https://jd.spongepowered.org/6.0.0-SNAPSHOT/org/spongepowered/api/scoreboard/objective/Objective.html), and [Scores](https://jd.spongepowered.org/6.0.0-SNAPSHOT/org/spongepowered/api/scoreboard/Score.html). 

Everything else does not belong in the API as it is much too specific. If something goes in the API it needs to be applicable to most if not all cases. "Parties" outside of teams are always handled so deferentially and for many different reasons most people probably wouldn't be able to use the API or at least wouldn't want to.

**Comment by phit** [comment]
Non issue, if you actually wanna bring this forward the SpongeAPI repo would be the right place for this.
