### ISSUE TITLE
Request: Implement event for player and player collisions

### ISSUE THREAD

**Issue by Earthplate** [SpongePowered/SpongeForge#1471]

**Comment by parlough** [comment]
I believe many of the collide events are implemented already. Check out the [CollideEvent](https://jd.spongepowered.org/6.0.0-SNAPSHOT/org/spongepowered/api/event/action/CollideEvent.html) and its sub-events: [CollideBlockEvent](https://jd.spongepowered.org/6.0.0-SNAPSHOT/org/spongepowered/api/event/block/CollideBlockEvent.html), [CollideBlockEvent.Impact](https://jd.spongepowered.org/6.0.0-SNAPSHOT/org/spongepowered/api/event/block/CollideBlockEvent.Impact.html), [CollideEntityEvent](https://jd.spongepowered.org/6.0.0-SNAPSHOT/org/spongepowered/api/event/entity/CollideEntityEvent.html), [CollideEntityEvent.Impact](https://jd.spongepowered.org/6.0.0-SNAPSHOT/org/spongepowered/api/event/entity/CollideEntityEvent.Impact.html), [CollideEvent.Impact](https://jd.spongepowered.org/6.0.0-SNAPSHOT/org/spongepowered/api/event/action/CollideEvent.Impact.html). 

You can find the implementation for many of them here: https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/event/SpongeCommonEventFactory.java

**Comment by bloodmc** [comment]
This is already implemented as @Meronat stated.
