### ISSUE TITLE
I really need help with this one

### ISSUE THREAD

**Issue by PSILONCRAFT** [SpongePowered/SpongeForge#1476]
I am the creator of PROJEC PSILONCRAFTED and i use yor mod. its amazing but since i use 153 mods there are bound to be problems. Im sending you this issue because your mod is one that prints out with a error in my setup. i will send you the server log and hope for a proper answer to the adressing issue

Best regards PSILONCRAFT
[crash-2017-04-30_23.33.02-server.txt](https://github.com/SpongePowered/SpongeForge/files/967065/crash-2017-04-30_23.33.02-server.txt)

**Comment by phit** [comment]
sponge isnt even in the modlist for this crash

**Comment by gabizou** [comment]
No where does it show sponge is involved in that crash report. If you have a different crash report, by all means we'll re-open the issue.
