### ISSUE TITLE
sponge cause the same problem of quatum quarry with planters of AgriCraft 

### ISSUE THREAD

**Issue by fabri2000779** [SpongePowered/SpongeForge#1479]
**I am currently running...**

- SpongeForge version: spongeforge-1.10.2-2281-5.2.0-BETA-2291.jar
- Forge version: 12.18.3.2281
- Java version: java-1.8.0
- Operating System:

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: 
Plugins (135): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, IvToolkit, Not Enough Items, SpongeAPI, SpongeForge, CoFH ASM, ccl-entityhook, InfinityLib, AgriCraft, Baubles, Just Enough Items, CoFH Core, Extra Utilities 2, AngelRing 2 Bauble, AppleSkin, ArchitectureCraft, Avaritia, Avaritia Additions, Baconators, CraftTweaker JEI Support, MineTweaker 3, B.A.S.E, Better Builder's Wands, Biomes O' Plenty, Block Armor, Botania, CodeChicken Lib, Brandon's Core, CatClearLag, Chameleon, Chance Cubes, Chest Transporter, CodeChicken Core, ChickenChunks, Chickens, Chisel, MCMultiPart, Chisels & Bits, Clumps, Cyclops Core, Colossal Chests, 1.12 Concrete, Cooking for Blockheads, Crafting Tweaks, CropDusting, Currency Mod, PTRModelLib, Decocraft, Discord Bridge, Draconic Evolution, Elevator Mod, Enjin Minecraft Plugin, EnderCore, Waila, Ender IO, EnderStorage, Ender Zoo, FakeBlocks, Fast Leave Decay, Flat Colored Blocks, FoamFix, Forgelin, FTBLib, FTBUtilities, Gravestone, Hatchery, Hermitron, iChunUtil, Inspector, Inventory Pets, Inventory Tweaks, Iron Chest, Iskallium Reactors, JourneyMap, LibrarianLib, Loot Bags, LootTweaker, LuckPerms, MalisisCore, MalisisDoors, Mantle, RadixCore, Minecraft Comes Alive, MineTweakerRecipeMaker, Natura, Railcraft, Tinkers' Construct, MoarSigns, mob_grinding_utils, MTLib, Mod Tweaker, More Chickens, More Loot Tables, MorePlayerModels, Morpheus, Modern Warfare, Mystical Agriculture, Natural Pledge, Nether Core, NoMoreRecipeConflict, Nucleus, Pam's HarvestCraft, Thermal Foundation, PlusTiC, Progressive Automation, Recurrent Complex, Storage Drawers, Refined Storage, RFTools, Roguelike Dungeons, ShadowMC, SimpleLabels, Simply Conveyors & More, Sleeping Bag, StackBan, Subaraki's Common Library, Thermal Expansion, Tinkers Tool Leveling, Tiny Progressions, TorchMaster, Translocator, Useful Nullifiers, ViesCraft, WAILA Features, I Can See Everything, What Are We Looking At, Waystones, WeaponCaseLoot, Woot, XP-Plus, LibrarianLib Stage 2, Moo Fluids
**What is the expected result?**
i was trying to automate AgriCraft with planters, i single player works but with my sponge forge server dont work 
**What is the current result?**
same problem as quatum quarry the planters of AgriCraft dont drop the items

**Comment by phit** [comment]
AgriCraft doesn't add a planter? Can you please add a proper reproduction.

**Comment by bloodmc** [comment]
Not enough information.
