### ISSUE TITLE
Extra Utilities Quantum Quarry Crash

### ISSUE THREAD

**Issue by allanf181** [SpongePowered/SpongeForge#1480]
**I am currently running...**

- SpongeForge version: 1.11.2-2227-6.0.0-BETA-2275
- Forge version: 13.20.0.2282
- Java version: 1.8.0_121
- Operating System: 

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: 
https://hastebin.com/vatilolino
**What is the expected result?**
No crash.
**What is the current result?**
Server crash.

Crash: https://hastebin.com/ubonebifej
Server log: https://hastebin.com/uvuhagukes
FML Server log: https://paste.ee/p/jK4MG

**Comment by allanf181** [comment]
https://github.com/rwtema/extrautilities/issues/1466

**Comment by johnfriedrich** [comment]
Same with SF 2300
