### ISSUE TITLE
Can't Drop Any Item

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1484]
if i try droping any item by pressing Q, nothing happens, item is being destroyed.
here is the logs:
[fml-server-latest.log.txt](https://github.com/SpongePowered/SpongeForge/files/974021/fml-server-latest.log.txt)
using forge 2294, latest sponge 2301
sorry if it's dupe, but i couldn't see any issue about dropping item.

**Comment by bloodmc** [comment]
Remove TrashSlot since it is not compatible with Sponge due to its major hack to inject its trash slot into a player's inventory.
