### ISSUE TITLE
Error in TabComplete

### ISSUE THREAD

**Issue by KappaKiddie** [SpongePowered/SpongeForge#1487]
**I am currently running...**

- SpongeForge version: 1.10.2-2281-5.2.0-BETA-2300
- Forge version: 1.10.2 - 12.18.3.2281
- Java version: 8
- Operating System:

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

There's a error when I use Tab in the screen
Error: https://pastebin.com/E6XceVSb

**Comment by phit** [comment]
What plugin is adding the `/spawn` command you used? I can't reproduce this with just Sponge and tabcompleting usernames.

**Comment by bloodmc** [comment]
No response in months.
