### ISSUE TITLE
AE2 crashes server right after startup

### ISSUE THREAD

**Issue by Whazaaaaa** [SpongePowered/SpongeForge#1490]
My Server crashes right after the modpack has loaded up and people are able to join. I have removed spongeforge and doing this solved the issue without it crashing which made me believe it is a sponge issue. Note that it crashes without any players online.

**I am currently running...**
- SpongeForge version: spongeforge-1.10.2-2281-5.2.0-BETA-2303
- Forge version: FTBserver-1.10.2-12.18.3.2254-universal (2254)
- Java version: 64-Bit Server VM, version 1.8.0_111, running on Linux:amd64:4.4.30-mod-std-ipv6-64
- Operating System:
 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

**Plugins/Mods:** 
Running AllTheMods 2.54b with all its mods
Here is a plugin list (not that I think it matters in this case):
Clearmob, Discordbridge, EMPSonge, FastAsyncWorldEdit, Griefprevention, holograms, Luckperms, MMCReboot, Nucleus, NuVotifier, PLayershopsRPG, Prism, RankUpper, Simplebroadcast, SimpleVotifierListener, Stackban, TotalEconomy

**What is the expected result?**
The server shouldnt crash after it has started

**What is the current result?**
The server crashes

**Server Logs:**
Crash Log: https://pastebin.com/LDjwu292
Log from console when it happend: https://pastebin.com/b0Gu0ht0
Crash log when it first happend: https://pastebin.com/FLerN3SM
Actual fml-server.log: https://gist.github.com/Whazaaaaa/18acefb6b0545c8591fbb53b2f5484f7

After creating an issue here: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2903
And finding out it was a sponge issue I came here.

**Comment by gabizou** [comment]
Your crash logs are showing older versions than the version you're mentioning in the issue. The last fml-server.log is showing the *updated version* but doesn't even show that it crashes. Please reproduce the crash log on the ***new*** version of SpongeForge and paste it please :).

**Comment by phit** [comment]
>The last fml-server.log is showing the updated version but doesn't even show that it crashes. 

it does, starts line 45095

**Comment by Whazaaaaa** [comment]
Perhaps I added a fml from a different server
this is the correct one: https://gist.github.com/Whazaaaaa/7b5ae9a28fdf3fbbf793105c5d860a38
This is straight from my ftp. So if it somehow still looks like its not the version as stated above. Trust me it is: spongeforge-1.10.2-2281-5.2.0-BETA-2303.
http://image.prntscr.com/image/2051ab3322474efe8e41a2f53052f372.png

Edit just noticed the 2 gists are the same. So I did upload the correct fml log.

**Comment by bloodmc** [comment]
@Whazaaaaa Provide a copy of your world zipped.

**Comment by Whazaaaaa** [comment]
@bloodmc https://whazaaaaa.stackstorage.com/s/DiySJUcrcc1XqWL
This is my world in zip. Beware it is already 5gb big so with this host it will take 20-30 min to download I think.
Thanks for looking into this!

**Comment by Whazaaaaa** [comment]
Any progress on this issue? I'm trying to decide what to do with my server because currently I have it set to offline because i'm kind of dependable on sponge.
My question is if it is possible to be fixed the next 1-2 days or if I'll have to find another way to get my server running with sponge again.
I'm also available on Discord for quicker/direct responses 'Whazaaaaa#7259' I am in the SpongePowered Discord channel aswel.

Currently as an alternative I'm looking at removing AE2 from the modpack to remove the current issue and re-add it after. But I'm not even sure if that will fix it(confirmation if that could work would also be nice).

Thanks again!

**Comment by Whazaaaaa** [comment]
Just started my server again and it has seemed to fix itself. All we did was remove sponge and fly around to find a problem. So I have no idea what fixed it...
