### ISSUE TITLE
Possible incompatibility with Astral Sorcery

### ISSUE THREAD

**Issue by Sunconure11** [SpongePowered/SpongeForge#1491]
It seems after fixing my entity-related error, another one was found.

https://pastebin.com/smWUXG04

**Comment by Sunconure11** [comment]
It turned out to be some corrupted data, but I'll leave this open anyways, just in case something else can be gleamed from the error.

**Comment by gabizou** [comment]
This is just corrupted data from deserializing NBT, nothing that sponge could do on it's own. Thanks for the report though!
