### ISSUE TITLE
Vanilla beacon applying AbyssalCraft Plague potion effect

### ISSUE THREAD

**Issue by LemADEC** [SpongePowered/SpongeForge#1493]
**I am currently running...**
- SpongeForge version: spongeforge-1.10.2-2281-5.2.0-BETA-2300
- Forge version: 1.10.2-forge1.10.2-12.18.3.2281
- Java version: 1.8.0_92
- Operating System:
 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows
- Plugins/Mods:
AbyssalCraft-1.10.2-1.9.4-pre-2

**What is the expected result?**
1- Place a tier vanilla beacon (9 diamond block + 1 beacon on top)
2- Open beacon GUI
3- Do NOT select any effect
4- Add a diamond in the fuel slot
3- Click the apply button
=> No potion effect applied

**What is the current result?**
=> AbyssalCraft Plague potion effect is applied every 4s for 11s on every players within 20 blocks of the beacon

SSP logs:
https://gist.github.com/LemADEC/b93e13180e3861e18c9f8d0fc1992caa

In SMP, issue also happens without having to fuel the beacon. Sometime going to another dimension or restarting the server.
https://github.com/Shinoow/AbyssalCraft/issues/195

**Comment by JaSpr** [comment]
Tons of people have been reporting this bug https://github.com/Shinoow/AbyssalCraft/issues/195
