### ISSUE TITLE
A few chunks not unloading correctly and causing intense tick issues.

### ISSUE THREAD

**Issue by merjilin** [SpongePowered/SpongeForge#1494]
**I am currently running...**
- SpongeForge version: 1.10.2-2281-5.2.0-BETA-2303
- Forge version: forge-1.10.2-12.18.3.2281-universal
- Java version: 1.8.0_121
- Operating System: 

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Applied Energistics 2 Core, Aroma1997Core, Not Enough Items, OpenComputers (Core), CoFH ASM, FoamFixCore, ccl-entityhook, Nucleus Mixins, CoFH Core, Actually Additions, IndustrialCraft 2, Advanced Machines, Advanced Solar Panels, Applied Energistics 2, BD Lib, AE2 Stuff, InfinityLib, AgriCraft, Baubles, Botania, Akashic Tome, Just Enough Items, AppleSkin, Aquaculture, ArchitectureCraft, Aroma1997Core|Helper, Aroma1997's Dimensional World, Morph-o-Tool, Psi, Quark, AutoRegLib, BetterChunkLoader Forge Lib, Bed Bugs, Better Builder's Wands, BiblioCraft, Guide-API, Blood Magic: Alchemical Wizardry, Blood Arsenal, Bookshelf, CodeChicken Lib, Brandon's Core, Ceramics, Chameleon, Chest Transporter, Chisel, MCMultiPart, Chisels & Bits, ShadowMC, Clipboard, CodeChicken Core, Compact Solar Arrays, Cooking for Blockheads, CraftTweaker JEI Support, MineTweaker 3, Dark Utilities, PTRModelLib, Decocraft, Forestry, ElecCore, EnderStorage, OpenComputers, DeepResonance, Draconic Evolution, Storage Drawers, Drawers & Bits, Elevator Mod, Embers, EnderCore, Ender IO, Engineer's Workshop, Valkyrie Lib, Environmental Tech, ET Lunar, Extra Utilities 2, Zero CORE, Extreme Reactors, Flat Colored Blocks, SonarCore, FluxNetworks, FoamFix, Forgelin, Forge Multipart CBE, Forge Microblocks, Minecraft Multipart Plugin, FTBLib, FTBUtilities, Funky Locomotion, Funnels, GenDustry, Gravestone, Gravitation Suite, Hammer Core, HelpFixer, Hopper Ducts, Mantle, Tinkers' Construct, The One Probe, Immersive Engineering, LunatriusCore, InGame Info XML, Interaction Wheel, Inventory Tweaks, Iron Backpacks, Iron Chest, JEI Bees, JourneyMap, Kai's Commons, KleeSlabs, Long Fall Boots, MalisisCore, MalisisDoors, Mercurius, Modular ForceField System, MmmMmmMmmMmm, mob_grinding_utils, MTLib, Mod Tweaker, Railcraft, More Bees, ModPack Utilities, ModPack Basic Tools, MrTJPCore, ShetiPhian-Core, Multi-Storage, Natura, Nether Portal Fix, Open Glider, p455w0rd's Library, Pam's HarvestCraft, ProjectRed Core, ProjectRed integration, ProjectRed Transmission, ProjectRed Illumination, ProjectRed Expansion, projectred-tansportation, ProjectRed Exploration, RebornCore, QuantumStorage, Ranged Pumps, reborncore-MCMultiPart, Thermal Foundation, Redstone Arsenal, Refined Relocation, Refined Storage, Reliquary, RFTools, RFTools Control, RFTools Dimensions, Roots, Signals, SimpleVoidWorld, Simple Retrogen, Simply Jetpacks 2, Sleeping Bag, Snad, Solar Flux Reborn, Steve's Carts 2, Storage Drawers Extras, Super Circuit Maker, Super Crafting Frame, TechReborn, Thermal Expansion, TickProfiler, Tinkers Tool Leveling, TOP Addons, TorchMaster, Translocator, Useful Nullifiers, WanionLib, Wireless Crafting Grid, Wireless Crafting Terminal, Woot, WirelessRedstone-CBE, XNet, YABBA, AdminShop, BetterItemRestrict, ClearMob, NuVotifier, Enjin Minecraft Plugin, GriefPrevention, Holograms, LuckPerms, Nucleus, MCClans, PixelAutoMessages, RankUpper, SeriousVote, ServerListPlus, SimpleAntiAFK, SynX, Sync, Total Economy, VirtualTool, WorldEdit, UniDict

**What is the expected result?**
1. Teleport to a dimension other than the overworld (I have personally experienced it in DIM-5 which is the simplevoidworld on ftb beyond.)
2. Teleport back to the overworld.
3. All chunks are unloaded completely.

**What is the current result?**
1. Loaded chunk total fluctuated between 0 and 2, which causes intense lag (in some cases, the server skips 2000 ticks)

Log: https://gist.github.com/merjilin/83c5a66ff9a1f861d40c8c5568089112

Note: I downgraded to an older version of spongeforge (2274) and the issue seems to no-longer persists.

**Comment by bloodmc** [comment]
Figure out the EXACT build that is causing the issue then update ticket.

**Comment by ghost** [comment]
Output of sponge timings should be useful, I had similar problems with EnderIO (mod author ignore bug https://github.com/SleepyTrousers/EnderIO/issues/4037)

**Comment by merjilin** [comment]
aha! Thanks for that prompt. I just updated my beyond server and it seems to no longer cause any issues on the newest spongeforge.
