### ISSUE TITLE
Sponge crashes FTB Beyond Server

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1497]
Hello. Thank you for reading. I am running a FTB Beyond server and trying to install plugins using Sponge. On startup it just crashes and gives an error.(Log Below) Thanks!

**I am currently running Sponge with FTB Beyond on my server**
- SpongeForge version: spongeforge-1.10.2-2254-5.2.0-BETA-2254
- Forge version: FTBserver-1.10.2-12.18.3.2254-universal
- Operating System:
 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows

- Plugins/Mods: FTB Beyond

**What is the expected result?**
Server to run so I can play

**What is the current result?**
Server crashes on launch and I cant do anything to fix it

Log: https://gist.github.com/Solarmender/b29dc2266a65f4bffbd5d6ef749f248a

**Comment by phit** [comment]
See #966 & https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2482

Use this Applied Energistics [fork](https://github.com/Stonebound/Applied-Energistics-2#about) or [SpongeBootstrap](https://forums.spongepowered.org/t/spongebootstrap-fixes-ordering-issue-with-other-coremods/12275)
