### ISSUE TITLE
Botania boss (Guardian of Gaia) won't start a battle until the player move

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeForge#1498]
In the Botania mod, there is a boss called [Guardian of Gaia](https://github.com/Vazkii/Botania/blob/1.10-final/src/main/java/vazkii/botania/common/entity/EntityDoppleganger.java), which can be summoned with an ritual. On singleplayer or on a pure forge server, once the boss is summonned, it starts to teleport and spawn pixies to hit the player, but when Sponge is loaded, the Guardian will do nothing **until the player move**. When the player moves, the battle starts.

This turns the battle quite OP, since you won't need to fight, the boss will freeze and you can shoot it with any bow or long-range weapon without getting any damage.

    Minecraft: 1.10.2
    SpongeAPI: 5.2.0-SNAPSHOT-a3257a0
    SpongeForge: 1.10.2-2281-5.2.0-BETA-2274
    Minecraft Forge: 12.18.3.2239
    Botania r1.9-341.jar

**Comment by bloodmc** [comment]
Edit your sponge global config and make sure the gaia boss is ignoring entity activation range rules.
