### ISSUE TITLE
Issues with server starting up

### ISSUE THREAD

**Issue by Fortcraft** [SpongePowered/SpongeForge#1499]
[crash-2017-05-10_01.41.29-server.txt](https://github.com/SpongePowered/SpongeForge/files/988893/crash-2017-05-10_01.41.29-server.txt)
That's the crash log and disabling sponge fixes the issue. I'd like some help.

**Comment by ghost** [comment]
In the world directory you need remove zero size files level_sponge.dat or overwrite from backups.

**Comment by Fortcraft** [comment]
Didn't seem to work hmm...

**Comment by Fortcraft** [comment]
[latest.txt](https://github.com/SpongePowered/SpongeForge/files/999635/latest.txt)
New Log
Trying to run with SF 3.0.9

**Comment by phit** [comment]
your level.dat is corrupted, restore it from a backup you hopefully have

**Comment by Fortcraft** [comment]
I deleted the level.dat as this is a new server and this is the new crash log
[latest1.txt](https://github.com/SpongePowered/SpongeForge/files/999643/latest1.txt)

**Comment by phit** [comment]
`/world/DIM-1/level.dat`

**Comment by Fortcraft** [comment]
Fixed by deleting all level.dat files in every folder
