### ISSUE TITLE
Extra Utilities 2 - further Quantum Quarry Servercrash

### ISSUE THREAD

**Issue by Hodel1** [SpongePowered/SpongeForge#1502]
**I am currently running...**
- SpongeForge version: 1.10.2-2281-5.2.0-BETA-2317
- Forge version: 2281
- Java version: 8
- Operating System:
 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

We've updated the SpongeForge Version to the latest today (see below) and would testing now the quantum quarry. We had used this introductions: https://github.com/SpongePowered/SpongeForge/commit/e072623b02ccb614ca8167082498aa8af129a6db

I placed down 10 Quantum Quarry to test it extremely, after 1 Quantum Quarry worked fine.
2 Minutes later, the server is crashed.
I tuned them off with "Redstone on" Signal and once acticated 4 quantum quarrys.
The Server TPS were down to 14 TPS. Later falls down to 5. (I don't know, could be an issue by EU2)

By visiting this Dimension to view, for eventually dropped items or whatever, will crash the server.

This is tested in FTB Beyond 1.5.3 with ExtraUltilties2 1.3.3

Crashlog: https://gist.github.com/Hodel1/61a5943810ed5d871856cb0f5b5d0187

**Comment by FiveEYZ** [comment]
u gotta update ExtraUltilties2 to 1.4+ to fix this 

or simply just update ur server to the latest "release" of FTB Beyond 1.6.1

**Comment by Hodel1** [comment]
Thanks for your reply :)
We will update soon

**Comment by bloodmc** [comment]
Not a SpongeForge problem. Update to latest ExtraUtilities 2 build as FiveEYZ mentioned.

**Comment by FiveEYZ** [comment]
im sorry to say this but its still crashing with extrautils2-1.10.2-1.4.1
it just happen on my dw20 test server when i was going to check another crash im having, then this happen

https://gist.github.com/FiveEYZ/b03d83416edf669a765efc66bc63106b

**Comment by phit** [comment]
yeah, that is not Sponge's fault, I already went over that with blood before the quarry broke completely https://github.com/SpongePowered/SpongeForge/issues/1158#issuecomment-281771565
