### ISSUE TITLE
Entites filtered in DropItemEvent.Dispense and DropItemEvent.Destruct are still removed from inventories

### ISSUE THREAD

**Issue by Zerthick** [SpongePowered/SpongeForge#1505]
**I am currently running...**
- SpongeForge version: 1.11.2-2282-6.0.0-BETA-2297
- Forge version: 1.11.2-13.20.0.2282
- Java version: 1.8.0_45
- Operating System:
 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [X] Windows

**What is the expected result?**
The expected result is that if an entity, such as an `itemstack` is filtered from the event using `filterEntities()`, not only should it not be dropped, but the transaction removing it from the inventory should be cancelled as well.
**What is the current result?**
Currently, the item is not dropped, however it is still removed from the inventory.

**Comment by dogboy21** [comment]
Maybe related to SpongePowered/SpongeAPI#1403

**Comment by phit** [comment]
Please reopen in SpongeCommon if this is still an issue.
