### ISSUE TITLE
Error while running /help

### ISSUE THREAD

**Issue by Ale32bit** [SpongePowered/SpongeForge#1506]
**I am currently running...**

- SpongeForge version: 1.10.2-2123-6.0.0-BETA-1902
- Forge version: 1.10.2-12.18.3.2297
- Java version: 1.8.0_121
- Operating System:

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows

- Plugins/Mods: Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Unborked Core, <CCTweaks ASM>, ComputerCraft, CCTweaks, LuckPerms, mercurius_updater, Nucleus, Plethora Core, Plethora, Unborked

**What is the expected result?**
Can use /help without errors
**What is the current result?**
Running the command as player I get in chat "Error occurred while executing command: java.lang.IllegalArgumentException: Invalid locale format: en_us" and in console I get https://pastebin.com/1a0LCgEz

Running as server (in console) it works

Full logs: https://pastebin.com/qbCu8kPQ

**Comment by phit** [comment]
Your Sponge version is ancient, update and try to reproduce it again.

**Comment by gabizou** [comment]
This was fixed ages ago. Update your version of Sponge.
