### ISSUE TITLE
Crash after login (Ender IO problem)

### ISSUE THREAD

**Issue by mkrtes** [SpongePowered/SpongeForge#1509]
**I am currently running...**

- SpongeForge version: spongeforge-1.10.2-2281-5.2.0-BETA-2322
- Forge version: 12.18.3.2281
- Java version: 8
- Operating System:

 - [ x] Linux (Ubuntu, Debian, Fedora, etc)

- Plugins/Mods: EnderIO

Crashlog: https://pastebin.com/mCUi7wuN

Note @HenryLoenwind : 
PS: Please report this to Sponge and add this information:
This crash cannot be fixed by Ender IO. Java does not support calling non-final methods from the constructor. It isn't actively stopping you doing it, and under certain circumstances it works fine---e.g. if the method does not access this. Here, however, doing so is completely unnecessary; the World class has a init() method that is called directly after the object is constructed:

net.minecraft.server.MinecraftServer.loadAllWorlds(...) {
...
WorldServer world = new WorldServer(...).init();

**Comment by phit** [comment]
issue for reference SleepyTrousers/EnderIO/issues/4217
