### ISSUE TITLE
global.conf and sql

### ISSUE THREAD

**Issue by EmanYm** [SpongePowered/SpongeForge#1510]
**I am currently running...**
- SpongeForge version: [MC1.10.2]SpongeForge[v5.2.0β2320][Forge2281][S].jar
- Forge version: [MC1.10.2]Forge[v12.18.3.2297][U].jar
- Plugins/Mods: [Server thread/INFO]: Plugins (6): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge

- Details:
(I initially started this [on the forums](https://forums.spongepowered.org/t/half-solved-global-conf-and-mysql-persistent-issue/18849))

Before I start the server with the global.conf the way I want it, it is 19,661 bytes.

The SQL section of global.conf before server start
>
    # Configuration options related to the Sql service, including connection aliases etc
    sql {
        # Aliases for SQL connections, in the format jdbc:protocol://[username[:password]@]host/database
        aliases="jdbc:protocol://db516380:(password)@sql-7.verygames.net/db516380"
    }

After the server is started the global.conf is 19,097 bytes.
The SQL section after the server has started
>    sql {
        # Aliases for SQL connections, in the format jdbc:protocol://[username[:password]@]host/database
        aliases {}
    }

- Here are my logs:
fml-server-latest.log ([part 1](https://hastebin.com/utijoxuxes.sql)) ([Part 2](https://hastebin.com/ebiyopukot.sql))
[fml-junk-early-startup.log and latest.log](https://hastebin.com/atudaxewiw.vbs)

**Comment by phit** [comment]
you arent even naming the alias
```
sql {
    aliases {
        something=jdbc:protocol://[username[:password]@]host/databas
    }
}
```

**Comment by dualspiral** [comment]
[I posted on the forums as I figured that it would be more visible there](https://forums.spongepowered.org/t/half-solved-global-conf-and-mysql-persistent-issue/18849/9?u=dualspiral)

It's not obvious how this section is meant to work. The comment on the setting and probably Sponge Docs need updating to make it obvious.

**Comment by EmanYm** [comment]
Thank you Dualspiral.  Your post on the forum cleared up a whole lot.
