### ISSUE TITLE
Exclude annotation event filterer does not work with event supertypes

### ISSUE THREAD

**Issue by RobertHerhold** [SpongePowered/SpongeForge#1513]
**I am currently running...**
- SpongeForge version: `spongeforge-1.10.2-2281-5.2.0-BETA-2330`
- Forge version: `forge-1.10.2-12.18.3.2281`
- Plugins/Mods: 

**What is the expected result?**

The `@Exclude` event filterer should filter out all child events. For example, I include `ChangeBlockEvent.class` in the list of events to filter out, so `ChangeBlockEvent.Pre.class` should also be filtered out

**What is the current result?**

On SpongeForge specifically (not SpongeVanilla), event child classes (like `ChangeBlockEvent.Pre.class` mentioned above) pass through the filter and trigger the event listener.

**Comment by gabizou** [comment]
Please include a code sample of what it's failing with.

**Comment by RobertHerhold** [comment]
Test plugin:

```java
import org.spongepowered.api.entity.living.player.Player;
import org.spongepowered.api.event.Event;
import org.spongepowered.api.event.Listener;
import org.spongepowered.api.event.Order;
import org.spongepowered.api.event.block.ChangeBlockEvent;
import org.spongepowered.api.event.filter.cause.Root;
import org.spongepowered.api.event.filter.type.Exclude;
import org.spongepowered.api.plugin.Plugin;

@Plugin(id = "test")
public class Test {

    @Listener(order = Order.POST)
    @Exclude({ChangeBlockEvent.class})
    public void event(Event event, @Root Player player) {
        System.out.println(event.getClass().getName());
    }

}
```

And when you break a block, this is the output:

```
[17:39:16] [Server thread/INFO] [STDOUT]: [Test:event:16]: org.spongepowered.api.event.ChangeBlockEvent$Pre$Impl
```

**Comment by gabizou** [comment]
This is because `ChangeBlockEvent` is not within the hierarchy of `ChangeBlockEvent.Pre` class. If you note [the class extends only `Event` and `Cancellable`](
https://github.com/SpongePowered/SpongeAPI/blob/91e694711d777f664426c0a159800f5e16d37d10/src/main/java/org/spongepowered/api/event/block/ChangeBlockEvent.java#L94-L114). Because of this, filtering on `ChangeBlockEvent` will not function in your specific case of ignoring `ChangeBlockEvent.Pre`. Event filters are working as expected.

**Comment by RobertHerhold** [comment]
@gabizou Thanks for the reply. However, I tested the same plugin on SpongeVanilla, which seems to block all `ChangeBlockEvent` events, regardless of the hierarchy discrepancy that you pointed out.

Do you know why this might be?

**Comment by Zidane** [comment]
@RobertHerhold 

Paste new code.
