### ISSUE TITLE
Crash with zz-backpacks

### ISSUE THREAD

**Issue by iLefty** [SpongePowered/SpongeForge#1514]
Zz-backpacks mod have a pouch which can give backpack more slots. On second use, this pouch do server crash. I wrote it to mod developer, but his said, that only Sponge devs can fix crash. Without sponge (only forge) crash don't be.
Crash report: https://pastebin.com/mMjJaRm8
Mod link: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291844-backpacks-by-brad16840?comment=667

All version of mods (with sponge and forge) present in crash report.

**Comment by neadlak** [comment]
Workaround for now: backpacks+Sponge will let you upgrade once. Change your backpacks config to make the first upgrade go to maximum size, and only have one upgrade?

**Comment by iLefty** [comment]
No, I was mistaken. The first increase is also can crash server.

**Comment by iLefty** [comment]
Fixed in SpongeForge-2353.
Close this @Faithcaio
