### ISSUE TITLE
Beyond - Crashing Server

### ISSUE THREAD

**Issue by Keaton1188** [SpongePowered/SpongeForge#1515]
Hi all, our server has been crashing at random times to what seems to be a issue with DeepResonance, could be wrong though. Any idea?

SpongeForge:
Minecraft: 1.10.2
SpongeAPI: 5.2.0-SNAPSHOT-a26c654
SpongeForge: 1.10.2-2281-5.2.0-BETA-2330
![untitled](https://cloud.githubusercontent.com/assets/24898745/26081750/41369bba-39c4-11e7-9c55-d85bac8a81e0.png)

**Comment by gabizou** [comment]
Paste to https://gist.github.com/ instead of using a screenshot of a stack trace. And please, include the crashlog since this is only part of the log needed to assist in debugging.

**Comment by Keaton1188** [comment]
This what ya meant?
https://gist.github.com/Keaton1188/fcc51e8bb201819cad7c336f77aad447

If wrong, just yell at me :)

**Comment by axle2005** [comment]
Thats a completely seperate crash log <.< ... That one says Morpheus did it (which is also a thing)
[https://github.com/SpongePowered/SpongeForge/issues/830](#830)

**Comment by FiveEYZ** [comment]
update Deep Resonance by McJty (1.4.7 > 1.4.8)
- Fixed a chunk unloading crash with tanks.


FTB Beyond pack version 1.7.0 have this update

**Comment by parlough** [comment]
So you need to update DeepResonance as that issue has been fixed in version 1.4.8. Morpheus is not compatible with Sponge at the moment so remove that and check out a Sponge plugin like SleepVote.

**Comment by gabizou** [comment]
Thank you @FiveEYZ, @axle2005, and @Meronat for doing the investigating and resolution for me. As said before, update Deep Resonance and use a different mod/plugin than Morpheus until such a time when Sponge has isolated the issue with Morpheus.

**Comment by Keaton1188** [comment]
Yep, thanks all!

That was my fault. Uploaded the wrong crash report. We just disabled Morpheus for now.
Good to know its fixed in the next update.
