### ISSUE TITLE
Slot cannot be null!

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeForge#1516]
The server randomly crashed, and it's happening like 4 times per day, with different players.

**I am currently running...**
    Minecraft: 1.10.2
    SpongeAPI: 5.2.0-SNAPSHOT-a26c654
    SpongeForge: 1.10.2-2281-5.2.0-BETA-2328
    Minecraft Forge: 12.18.3.2239 
- Java version: 1.8.0_131
- Operating System: Linux Apline (docker)
- Plugins/Mods: Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, Applied Energistics 2 Core, IvToolkit, 
SpongeAPI, SpongeForge, CoFH ASM, FoamFixCore, ccl-entityhook, NoXray, Nucleus Mixins, CoFH Core, Actually Additions, AdminShop, InfinityLib, AgriCraft, Alias
es, Applied Energistics 2, Psi, Quark, AutoRegLib, Baubles, BetterChunkLoader, BiblioCraft, Biomes O' Plenty, Bookshelf, Botania, BungeeTabListPlus-SpongeBrid
ge, Buycraft, CarrotShop, CatClearLag, Chameleon, ClearMob, CodeChicken Lib, CosmeticArmorReworked, CraftTweaker JEI Support, Just Enough Items, MineTweaker 3
, CrazyFeetSponge, Dark Utilities, EconomyLite, EnderCore, Ender IO, Valkyrie Lib, Environmental Tech, Extra Utilities 2,  FastAsyncWorldEdit, WorldEdit, Fast
 Leave Decay, FoamFix, IndustrialCraft 2, Forestry, Forge Multipart CBE, Forge Microblocks, Minecraft Multipart Plugin, GeographiCraft, Gravestone, Gravitatio
n Suite, GriefPrevention, HelpMe, Mantle, Tinkers' Construct, The One Probe, Immersive Engineering, Iron Backpacks, Iron Chest, ItemAuction, Kai's Commons, Lu
ckPerms, MagiChat, MagiUtils, MMCReboot, MMCRestrict, mob_grinding_utils, MTLib, Mod Tweaker, Morpheus, MrTJPCore, Nucleus, Pam's HarvestCraft, Progressive Au
tomation, ProjectPortals, ProjectRed Core, ProjectRed integration, ProjectRed Transmission, ProjectWorlds, React, Recurrent Complex, Thermal Foundation, Redst
one Arsenal, MCMultiPart, Storage Drawers, Refined Storage, RFTools, Realistic Terrain Generation, Sampler, SignEditor, SimpleAntiAFK, SpongyCord, Thermal Exp
ansion, TitleMOTD, WanionLib, UniDict

Crash-report: https://hastebin.com/ruvuvamohu.sql

**Comment by Eufranio** [comment]
This player crashed again, and he said the inventory was an [Engineers Workbench](http://ftb.gamepedia.com/Engineer%27s_Workbench), from the Immersive Engineering mod.

**Comment by axle2005** [comment]
Can confirm. Seperate network, had the same crash and one of our players posted on our Discord: 

don't put mining drill in engineers workbench.

**Comment by iLefty** [comment]
I have the same crash, but with other mod zz-backpacks.

**Comment by FiveEYZ** [comment]
this `Exception Exiting Phase` containing `NullPointerException: Slot cannot be null!` have just started spamming
https://gist.github.com/FiveEYZ/f6d4ce06eeb2d7a89ee765b1d35df86e

**Comment by KaiKikuchi** [comment]
I tried removing [this checkNotNull](https://github.com/SpongePowered/SpongeAPI/blob/stable-5.2.0/src/main/java/org/spongepowered/api/item/inventory/transaction/SlotTransaction.java#L49), and it seems to fix the issue.

After removing that, I tried putting a mining drill in engineers workbench and it does not crash anymore:

![image](https://cloud.githubusercontent.com/assets/8842403/26285762/1db77718-3e56-11e7-8fea-f7f1bf8d218c.png)

This is on FTB SkyFactory 3 v3.0.9 | spongeforge-1.10.2-2281-5.2.0-BETA-2344.

**Comment by Faithcaio** [comment]
Sadly the solution is not that easy.
Sponge has to be able to readjust the underlying lens on an opened inventory or there wont be any events fired for that slot.

**Comment by KaiKikuchi** [comment]
Indeed. Still, I'm sure server owners prefer events not being fired for that slot instead of having servers down because they keep crashing, hence I shared this.

**Comment by FiveEYZ** [comment]
here is a log is it may help http://paste.ubuntu.com/24619710/

**Comment by FiveEYZ** [comment]
have started to see this in my console output:

`[19:14:59] [Server thread/WARN] [nucleus/]: When trying to listen for the inventory events, targetInventory#getCarrier() is null. THIS SHOULD NOT HAPPEN - this is a Sponge issue.`

same second this error happen:
https://gist.github.com/FiveEYZ/947c92546dec592ded4e80b2bdf9f23a

**Comment by Faithcaio** [comment]
Please test if this still happens with the latest build.
Its not really fixed but at least it should be less broken.

The getCarrier thing is a separate issue but it should be resolved too.

**Comment by iLefty** [comment]
Yes, it fixed. Thank you!
