### ISSUE TITLE
[1.11.2] Server crash on join.

### ISSUE THREAD

**Issue by rmnaderdev** [SpongePowered/SpongeForge#1519]
**I am currently running...**

- SpongeForge version: 1.11.2-2282-7.0.0-BETA-2340
- Forge version: 1.11.2-13.20.0.2282-universal
- Java version: 1.8.0_131
- Operating System:

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: 
    "The New Frontier" Modpack
    https://pastebin.com/yxbinWBw

**What is the expected result?**
Not to crash on join.
**What is the current result?**
Server crashes on player join. One of my community members reported putting down a chest builder from compact storage and that's where the crashing started.
#https://github.com/EPIICTHUNDERCAT/ManaWells/issues/4

https://gist.github.com/PotatoSauceVFX/1f94c40d98528a948302d8c40127458a

**Comment by EPIICTHUNDERCAT** [comment]
Last I checked sponge is very buggy or unstable in 1.11.2. Haven't had this issue on other servers running my mod without Sponge. I'll see if I can do something.

**Comment by Deamon5550** [comment]
@EPIICTHUNDERCAT The method `EntityList#func_75616_a` that your mod is calling is client only. It does not exist in the server.

**Comment by rmnaderdev** [comment]
Is that something that can be fixed?

**Comment by johnfg2610** [comment]
yes it can certainly be fixed by making that bit of the code run on client only

**Comment by rmnaderdev** [comment]
I'd try to figure it out but I don't have time right now to look into it and make a pull request.

**Comment by bloodmc** [comment]
As Deamon stated, not a sponge issue. Mod is calling a client-side method on server.
