### ISSUE TITLE
1.10.2 abandoned？

### ISSUE THREAD

**Issue by loveyanbei** [SpongePowered/SpongeForge#1520]
1.10.2 branch was gone and all downloads were found marked unsupported.

**Comment by Deamon5550** [comment]
The [1.10.2 branch](https://github.com/SpongePowered/SpongeForge/tree/stable-5) is absolutely not gone and all the [builds](http://files.minecraftforge.net/spongepowered) are [still here](https://www.spongepowered.org/downloads/spongeforge/stable/1.10.2)

**Comment by loveyanbei** [comment]
I SAW that happened（unsupported on the downloads）
Maybe just a mistake XD.
