### ISSUE TITLE
Ticks and Lags

### ISSUE THREAD

**Issue by Arlayn** [SpongePowered/SpongeForge#1523]
Hi , I've a problem with the ticks who create many lags in the server. This bugs is appears when I load many chunks in many place.

Thanks for you'r help
the problem appeared also in forge without sponge in my computer (22GB RAM, AMD FX8350 4GHz )
ps: sorry if my english isn't perfect I'm french ^^

- SpongeForge version: 1.10.2 - 2281 - 5.2.0 - BETA 2341
- Forge version: 1.10.2 2281
- Java version: 1.8
- Operating System: 

 - [X] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: 

Mods : Dynmap

Plugins : EverPlugins, Holograms, SimplePermission, Nation 2.4, WebAPI, WorldEdit, TabManager

**What is the expected result?**

No lags , smooth game

**What is the current result?**

lags and chunk didn't load

this is the logs of this day
https://gist.github.com/Arlayn/2f7480920eb845708ce8035ab5d1ca34

**Comment by ghost** [comment]
Please provide output of timings: https://docs.spongepowered.org/stable/en/server/spongineer/commands.html#timings

**Comment by Arlayn** [comment]
this is the report :

https://timings.aikar.co/?id=3d98e0203bf748d9a0837e24f1491d9d (during 30min)

**Comment by phit** [comment]
This issue tracker is for bugs not lag support, for further help please visit one of these
Forums: https://forums.spongepowered.org/
IRC: https://webchat.esper.net/?channels=sponge
Discord: https://discord.gg/PtaGRAs

**Comment by Zidane** [comment]
@phit is right on the mark.
