### ISSUE TITLE
Server trouble starting SF 3.0.9

### ISSUE THREAD

**Issue by Fortcraft** [SpongePowered/SpongeForge#1525]
I am trying to run sf 3.0.9 on a server and it gives me this error: https://pastebin.com/CgE5uGme

**Comment by Fortcraft** [comment]
I have fixed this from loading from a backup, but I'd still like to know why the error has occured. The level.dats were replaced with 0 file size files

**Comment by phit** [comment]
Server crash, harddrive issues, power loss, other mods, etc. could have caused this, unless this happened more than once I would say this isn't a SpongeForge issue.

**Comment by Zidane** [comment]
Closing as you had world corruption and this error is pointing right at that. @phit 's remarks are right on point.
