### ISSUE TITLE
[1.11.2] OpenComputers Robot crash

### ISSUE THREAD

**Issue by phit** [SpongePowered/SpongeForge#1526]
Tested with 1.11.2-2282-6.1.0-BETA-2343 & spongeforge-1.11.2-2282-6.1.0-BETA-2339

https://gist.github.com/phit/4bc450420803f85b708f5d0253bb3c79

Same crash was supposedly fixed in 1.10 #824

**Comment by Eufranio** [comment]
Not sure if it's related, but placing a Robot will crash the server, with this crash-report: https://hastebin.com/asoxamuxev.pl

    Minecraft: 1.11.2
    SpongeAPI: 6.1.0-SNAPSHOT-806a22a
    SpongeForge: 1.11.2-2282-6.1.0-BETA-2343
    Minecraft Forge: 13.20.0.2298
    OpenComputers: 1.11.2-1.7.0.24

**Comment by Zidane** [comment]
@Faithcaio 

Are your fixes in 1.11?

**Comment by Faithcaio** [comment]
They should be. 
But I'm pretty sure I do not handle player inventories with a size of [0](https://github.com/MightyPirates/OpenComputers/blob/917befcd0e8e256bc52abb038f86bc04f236645a/src/main/scala/li/cil/oc/server/agent/Inventory.scala).
Which is what seems to cause the error here.
@phit can you test this again?

**Comment by phit** [comment]
@Faithcaio still crashes
https://gist.github.com/phit/4859c3aaf75f45dd00a82012de364d09
spongeforge-1.11.2-2393-6.1.0-BETA-2468.jar
OpenComputers-MC1.11.2-1.7.0.24.jar

to crash, give yourself the creatix (creative robot), place it down and just rightclick it

**Comment by Faithcaio** [comment]
Fixed with latest build.
