### ISSUE TITLE
Ember Transmission bug

### ISSUE THREAD

**Issue by Vauxite** [SpongePowered/SpongeForge#1528]
**I am currently running...**
- SpongeForge version: 1.10.2-2281-5.2.0-beta-2344
- Forge version: 12.18.3.2281
- Java version: v8u131
- Operating System: 
Client: Windows 10, 
Server: Ubuntu Server 16.04 LTS

- Mods: 
Modpack: Nuts and Bolts: Torqued 1.6.4.7
- Plugins
DiscordBridge 2.3
Griefprevention 1.102-2.3.1.295
Luckperms-Sponge 3.2.3
MMCReboot 2.0.4
Nucleus-0.29.1-1.10.2-S5.1-plugin
Prism-3.0.0-beta2-45-gfbbeb2b
RankUpper-2.2.2-b133_Sponge

**What is the expected result?**

- Ember follow a natural pattern. 
- Ember is transmitted and received correctly

**What is the current result?**

- It shoots everywhere. 
- Stops working.
- Ember is not received at the recipient

Picture:
http://imgur.com/a/ZvmhS

**Comment by gabizou** [comment]
We're going to need steps on how to re-create this.

**Comment by Vauxite** [comment]
I'll provide a world save when I get home later today.

**Comment by Vauxite** [comment]
@gabizou 
**Worldsave link:**
https://www.dropbox.com/s/4xvggi8krz3isr5/emberBUG_Vauxite.zip?dl=0
**Virustotal for file:**
https://www.virustotal.com/sv/file/3c4845de146a65880ce4da7f9c3a528bddc6f48bd0b6b53a855c914721ba6c04/analysis/1495558225/

**In pictures**
http://imgur.com/gallery/RCpqo

You may have to attach additional ember gauges to determine if the power actually transfer between the batteries. 

Let me know if you need anything else.

**Comment by phit** [comment]
seems to be fixed, used your testworld with:
> Embers 0.104
> spongeforge-1.10.2-2281-5.2.0-BETA-2464

added an ember gauge to the battery and it seemed to be charging
![http://i.imgur.com/FLenjEg.png](http://i.imgur.com/FLenjEg.png)
