### ISSUE TITLE
[BETA-2343] Ticking entity exception

### ISSUE THREAD

**Issue by MadByteDE** [SpongePowered/SpongeForge#1529]
- **SpongeForge version**: spongeforge-1.11.2-2282-6.1.0-BETA-2343
- **Forge version**: 1.11.2-forge1.11.2-13.20.0.2282 
- **Java version**: 1.8.0_25
- **Operating System**: Windows 7 64Bit
- **Plugins/Mods**: none (except Sponge)

**Crash Log**: [here](https://gist.github.com/MadByteDE/6f843610bcffffdc2bd654cf87ca587c)

**Step 1**: Launch the game and load a world
**Step 2**: crash immediately after finishing loading the world

**What is the expected result?**
Game shouldn't crash.
Updating to newer forge versions has the same result.
When removing sponge the crash is gone.

**What is the current result?**
Game crash :p

**EDIT:**
Seems to be "fixed" with fresh config files (delete the old ones). 
Still not sure what caused it. Did something in the config changed?

**Comment by phit** [comment]
Old issue and since no one else has reported this, I'm closing this. If you run into this again, feel free to reply here or open a new issue.
