### ISSUE TITLE
Terraqueous EnderTable cannot be opened

### ISSUE THREAD

**Issue by Mohron** [SpongePowered/SpongeForge#1530]
**I am currently running...**

- SpongeForge version: spongeforge-1.11.2-2282-7.0.0-BETA-2342
- Forge version: forge-1.11.2-13.20.0.2299-universal
- Java version: 1.8.0_131
- Operating System: 

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [x] Windows

- Plugins/Mods: ```Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, Potion Core Coremod, SpongeAPI, SpongeForge, FoamFixCore, Actually Additions, Akashic Tome, Baubles, extrautils2, AngelRing 2 Bauble, Alternate Terrain Generation, Psi, Quark, Skillable, AutoRegLib, Avaritia, BetterBedroc
kGen, BD Lib, Better Achievements, Better Builder's Wands, Better Than Mending, Guide-API, Blood Magic: Alchemical Wizardry, Bookshelf, Botania, SonarCore, Calculator, Cavern, Chameleon, Chest Transporter, Chisel, Chisels & Bits, Compact Machines 2, Cooking for Blockheads, CosmeticArmorReworked, CraftTweaker JEI Support, Just Enough Items, Crafttweaker, Custom Achievements, Cyberware, Dark Utilities, Forestry, ElecCore, DeepResonance, Disenchanter, Elevator Mod, Embers, Lapis Stays in the Enchanting Table, ShetiPhian-Core, EnderTanks, Valkyrie Lib, Environmental Tech, ET Lunar, Extra Bit Manipulation, Fast Leaf Decay, FoamFix, GenDustry, Advanced Generators, Harvest, TESLA, Tesla Core Lib, Industrial Foregoing, MTLib, InitialInventory, Inventory Tweaks, Iron Chest, JEI Bees, JourneyMap, LootTweaker, Mantle, Mending Fix, MmmMmmMmmMmm, MNU, Modular Machines, Morpheus, Terraqueous, Multi-Storage, Mysterious Miscellany, Natura, NetherPortalFix, No Mob Spawning on Trees, Not Enough Wands, NuclearCraft, Ore C
ore, Potion Core, Quality Tools, Random Things, Reborn Core, reborncore-MCMultiPart, RefinedRelocation, Refined Storage, Reliquary, Restricted Portals, RF Lux, RFTools, RFTools Control, Rocky Core, Roots 2, Rustic, Silent Lib, Scaling Health, Scannable, SimpleVoidWorld, Steve's Carts 2, Storage Drawers, Substratum, Super Multi-Drills, Tinkers' Construct, The One Probe, Tiny Progressions, Tomb Many Graves, TOP Addons, TorchMaster, ViesCraft, WanionLib, The Weirding Gadget, Wither Skeleton Tweaks, Woot, WorldEdit, XNet, BadgeUp Sponge Client, Discord Bridge, EconomyLite, GriefPrevention, LuckPerms, Nucleus, SpongyCord, denseores, UniDict```

**What is the expected result?**
The Terraqueous EnderTable should open a Enchanting table type GUI. 

**What is the current result?**
The Terraqueous EnderTable GUI is immediately closed after opening on a Sponge server.

**Comment by phit** [comment]
Seems to be fixed, GUI opens and you can enchant stuff with Ender Dust, tested with
>shetiphiancore-1.11.0-3.4.6.jar
>spongeforge-1.11.2-2393-6.1.0-BETA-2471.jar
>terraqueous-1.11.0-1.3.14.jar
