### ISSUE TITLE
Setting up a older work environment.

### ISSUE THREAD

**Issue by Huckletsplay** [SpongePowered/SpongeForge#1532]
Trying to set up a developers work environment using git. I want to work on plugins for spongeforge-1.10.2-2281-5.2.0-BETA-2344 but i do not know the link to use for the # git clone --recursive . any help would be great!

**Comment by stephan-gh** [comment]
You can add the branch when cloning SpongeForge: (1.10.2 is `stable-5`)

```
git clone --recursive https://github.com/SpongePowered/SpongeForge.git --branch stable-5
```
