### ISSUE TITLE
Tough as Nails, unexpected hash

### ISSUE THREAD

**Issue by gigafunk** [SpongePowered/SpongeForge#1533]
**I am currently running...**

- SpongeForge version: spongeforge-1.10.2-2281-5.2.0-BETA-2344
- Forge version: 2281
- Java version: 8...131
- Operating System:

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: 
ToughAsNails-1.9.4-1.1.1
no other mods just ,spongeforge and Toughmod. No plugins. 
**What is the expected result?**
Load without hash error

**What is the current result?**

in the log, with spongforge, I get the below

[ToughAsNails Transformer/]: Unexpected hash 20f2d689046ef2bce53aff9618487c56 detected for class BlockCrops. Crashes or bugs may occur!
[23:19:18] [main/INFO] [mixin/]: A re-entrant transformer '$wrapper.toughasnails.asm.transformer.BlockCropsTransformer' was detected and will no longer process meta class data
happens with the World class as well. [Offending class in TAN](https://github.com/Glitchfiend/ToughAsNails/blob/TAN-1.11.x-2.0.0/src/main/java/toughasnails/asm/transformer/BlockCropsTransformer.java)
the class trying to transform World in parelel to the BlockCropsTransformer class, but the crop one is shorter, so I figured it was better example.

A similar issue was posted on the mods issue tracker and the mod author said it looks like maybe spigot(in that case) transformed those classes first, and closed the issue.  [here is a link top that](https://github.com/Glitchfiend/ToughAsNails/issues/117)

[fml-server-latest.txt](https://github.com/SpongePowered/SpongeForge/files/1017913/fml-server-latest.txt)

This only happens with sponge forge installed...i removed all other mods and deleted the world to test. should be easy to reproduce. Now the server loads and runs, and I havent been able to test the TAN mod for functionality, so i am not sure if it works a little or alot. Sounds like its not finishing its transform thought and that cant be good.   Thanks!

**Comment by Deamon5550** [comment]
You're going to have to give more information, logs? crash reports? a list of mods? an actual description?

**Comment by gigafunk** [comment]
wow your fast, i typed it and then thought maybe i tested it wrong (was like did i already move spongeforge or was it not in there while i tested) and closed it and cleared it while I retested(it was in there) ! then i reopened and started retyping, and finally  posted it 1 min after you responded! I hope i didnt waste my dev attention! i was trying to be extra sure and test twice! To be clear thats with only the TAN mod. No other mods on the server.

**Comment by simon816** [comment]
Tough As Nails appears to have a hard coded hash check on the classes it transforms. ([see here](https://github.com/Glitchfiend/ToughAsNails/blob/3d63ce83dddc461efdf1cdb67bc26708f564716c/src/main/java/toughasnails/asm/ASMHelper.java#L96)).
The message is to be expected as sponge transforms the classes. It doesn't appear to halt the game so it can be ignored.

**Comment by gigafunk** [comment]
Excellent! I was worried that the error stopped the transform from happening, but from the coded it appears it just logs and moves on. Call this closed or should wait for sponge team member to close it?

**Comment by simon816** [comment]
I will close this now
