### ISSUE TITLE
Exception caught during firing event net.minecraftforge.event.entity.player.PlayerInteractEvent$RightClickBlock@58a31ffe

### ISSUE THREAD

**Issue by FiveEYZ** [SpongePowered/SpongeForge#1537]
**I am currently running...**

- SpongeForge version: 1.10.2-2281-5.2.0-BETA-2353 
- Forge version: 12.18.3.2297 
- Java version: 8u131
- Operating System: 

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows 2012 r2

- Plugins/Mods: 
Plugins (106): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, Applied Energistics 2 Core, OpenComputers (Core), SpongeAPI, SpongeForge, CoFH ASM, FoamFixCore, ccl-entityhook, CoFH Core, Actually Additions, Baubles, Botania, Akashic Tome, Applied Energistics 2, Morph-o-Tool, Psi, Quark, AutoRegLib, Bad Wither No Cookie!, Bagginses, Better Builder's Wands, Biomes O' Plenty, Guide-API, Just Enough Items, Blood Magic: Alchemical Wizardry, Bookshelf, CodeChicken Lib, Brandon's Core, Chameleon, Chisel, MCMultiPart, Chisels & Bits, CodeChicken Core, IndustrialCraft 2, Compact Solar Arrays, CraftTweaker JEI Support, MineTweaker 3, Waila, Dark Utilities, Forestry, ElecCore, EnderStorage, OpenComputers, DeepResonance, Draconic Evolution, EnderCore, Ender IO, Extra Utilities 2, Zero CORE, Extreme Reactors, Fast Leaf Decay, Flat Colored Blocks, FoamFix, Gravestone, Mantle, Tinkers' Construct, The One Probe, Immersive Engineering, Simple Inventory sorting, Inventory Tweaks, Iron Backpacks, Iron Chest, JEI Bees, JourneyMap, Mercurius, Not Enough Wands, Pam's HarvestCraft, Railcraft, Ranged Pumps, Thermal Foundation, Redstone Arsenal, Storage Drawers, Refined Storage, RFTools, RFTools Control, RFTools Dimensions, Super Circuit Maker, Thermal Expansion, I Can See Everything, What Are We Looking At, XNet, BungeeTabListPlus-SpongeBridge, EconomyLite, NuVotifier, Enjin Minecraft Plugin, GriefPrevention, Holograms, ItemAuction, LootChest, LuckPerms, MMCReboot, MMCRestrict, MultiChat Sponge, Nucleus, PlaceholderAPI, Nucleus Gluon, PayDay, Player Glow, RankUpper, ServerListPlus, VotifierListener, SleepVote, WorldEdit

**What is the expected result?**
No NullPointerException's

**What is the current result?**
NullPointerException's

Exception caught during firing event:
https://gist.github.com/FiveEYZ/f03e50dd077e26eb1152b009e146782a

full server log:
https://gist.github.com/FiveEYZ/29b1283eaf6540d9f75196ed01e500b0

**Comment by Zidane** [comment]
Re-test without Sponge:


[15:17:48] [Server thread/ERROR] [FML/]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerInteractEvent$RightClickBlock@58a31ffe:
java.lang.NullPointerException
	at mcmultipart.item.PartPlacementWrapper.onPlayerRightClickBlock(PartPlacementWrapper.java:160) ~[PartPlacementWrapper.class:?]

Happening in this mod, not us.
