### ISSUE TITLE
Duplication bug with better with mods

### ISSUE THREAD

**Issue by johnfg2610** [SpongePowered/SpongeForge#1542]
**I am currently running...**
http://i.imgur.com/IaNCcdx.png
I have also tried with the latest version of forge and sponge the same issue occured
- Java version: 1.8.0_111
- Operating System:
 - [ X] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows
- Plugins/Mods: 
Plugins (179): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, Aroma1997Core, Micdoodle8 Core, OpenEye, Backpacks!, SpongeAPI, SpongeForge, FoamFixCore, ccl-entityhook, Actually Additions, Akashic Tome, Baubles, extrautils2, AngelRing 2 Bauble, Animal Bikes, AppleCore, Just Enough Items, AppleSkin, Forgelin, Mantle, Chisel, Tinkers' Construct, TheDragonLib, ArmorPlus, Aroma1997Core|Helper, Aroma1997sDimension, Astral Sorcery, Alternate Terrain Generation, Psi, Natura, Better With Mods, Quark, AutoRegLib, BD Lib, Bed Bugs, Bedrock-B-Gone, Better Achievements, Better Builder's Wands, BiblioCraft, Cyclic, Guide-API, Blood Magic: Alchemical Wizardry, Bloodmoon, Bookshelf, Bookshelf, Botania, SonarCore, Calculator, MrCrayfish's Furniture Mod, Chameleon, CodeChicken Lib, ChickenChunks, Chisels & Bits, Cyclops Core, IndustrialCraft 2, CommonCapabilities, Compact Solar Arrays, CompactStorage, Computality, Cooking for Blockheads, CraftTweaker JEI Support, Crafttweaker, CXLibrary, Cyberware, Dark Utilities, Forestry, ElecCore, DeepResonance, Storage Drawers, Drawers & Bits, drones, Elevator Mod, Embers, EnderStorage, Ender Utilities, Ender Zoo, Valkyrie Lib, Environmental Tech, EvilCraft, Zero CORE, Extreme Reactors, EZStorage 2, Fire's Random Things, FL, FluxNetworks, FoamFix, Forge Endertech, Not Enough Items, FTBLib, Galacticraft Core, Galacticraft Planets, Advanced Generators, Gravestone, Grue, Hammer Core, Hardcore Darkness, Hardcore ORE, HelpFixer, MTLib, InitialInventory, Inventory Pets, Inventory Tweaks, Iron Chest, JourneyMap, Just JetPacks, LimeLib, Mana Wells, Metamorph, Mike Dongles, Missing Pieces, MmmMmmMmmMmm, mob_grinding_utils, More Furnaces, Mysterious Miscellany, Mystical Agriculture, NoMoreRecipeConflict, NotEnoughIDs, Not Enough Wands, NuclearCraft, OMLib, Open Modular Turrets, Ore Dictionary Converter, OreExcavation, Overloaded, Pam's HarvestCraft, Quick Leaf Decay, Random Things, Ranged Pumps, Redstone Paste, Refined Storage, Reforged, Reliquary, RFTools, Roguelike Dungeons, Roots 2, ShetiPhian-Core, Silent Lib, Silent's Gems, Simple Fluid Tanks, Simple Generators, Simple Teleporters, Simply Conveyors & More, SlashBlade, Slurpie's Dongles, Solar Flux Reborn, Soul Shards - The Old Ways, The Spice of Life, Subaraki's Common Library, Super Crafting Frame, The One Probe, Tiny Progressions, TOP Addons, TorchMaster, Translocator, Transprot, TSON Craft, Woot, XNet, BetterChunkLoader, Buycraft, CatClearLag, Discord Bridge, EconomyLite, FoxCore, FoxGuard, GriefPrevention, LuckPerms, Nucleus, NuVotifier, PlayerShopsRPG, Prism, RankUpper, SpongeAnnounce, Spongemointor, WorldEdit, denseores

Minecraft: 1.11.2
Modpack: New frontier
Server software: Sponge
Version info: http://i.imgur.com/HBPd5am.png

When bouncy is enabled on a server the item seems to duplicate im not sure whats causing it since its throwing no errors when i disable bouncy it works perfectly fine

# Replication steps

setup forge server with sponge and betterwithmods
throw a item
the item will remain in your inventory and appear in the world

Link to mod issue: https://github.com/BeetoGuy/BetterWithMods/issues/375

Link to full(i think) server log: https://gist.github.com/johnfg10/bfca674401e027ca69c0f2893e53bfe6

**Comment by primetoxinz** [comment]
Dev of Better With Mods here, I don't know much about Sponge but I know that HCBuoy simple cancels the original EntityJoinWorldEvent and replaces the item with a custom EntityItem implementation. Whatever is going on here Sponge is still spawning the EntityItem even though the event was canceled, 
nothing I can do on my end, believe it has to be fixed on Sponge's side.

**Comment by b0bst3r** [comment]
I know this issue is old but Better with Mods is going to hit 1.12 packs a lot with what it has to offer, I know of several already.  Sponge is just not an option for a pack with BTM in.  Don't suppose this can be fixed as a priority please?

**Comment by phit** [comment]
probably related to https://github.com/SpongePowered/SpongeForge/issues/1810

**Comment by phit** [comment]
@johnfg10 still an issue on more recent versions?

**Comment by phit** [comment]
appears to be fixed
HardcoreBuoy-1.12-1.0.3.jar
spongeforge-1.12.2-2705-7.1.0-BETA-3253.jar
BetterWithMods-1.12-2.1.24.jar
