### ISSUE TITLE
villager issue with sponge ? 

### ISSUE THREAD

**Issue by wolfhound871** [SpongePowered/SpongeForge#1543]
<!villager crash when you do any damage to them 

**beyond 1.5.3...**

- SpongeForge version: 1.10.2 2281-5.2.0 beta 2353
- Forge version: 1.10.2-12.18.3.2281 universal
- Java version: v 8 update 131
- Operating System: win server 2008 r2 standard

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows

- Plugins/Mods: 
worldedit forge 1.10.2-6.1.4 snapshot
tickprofiler .20
stackban 5.1.0-0.2.5
rough-mobs mod 1.10.2
prism .3.0.0
nucleus 0.29
mmcreboot 
luckperms 3.0.32
inspector 0.6.4
griefprevention EMPSponge clearmob 1.3.2 
catclearlag 0.7.1

**What is the expected result?**for villagers to die 

**What is the current result?** they make it crash 

https://gist.github.com/anonymous/b71c68ba43f3d0ec28e489c23c461c0f

**Comment by axle2005** [comment]
Cause is different, but still the same issue as [#1467](https://github.com/SpongePowered/SpongeForge/issues/1467)
