### ISSUE TITLE
server crash creating/loading rftools world

### ISSUE THREAD

**Issue by ktole1999** [SpongePowered/SpongeForge#1545]
**I am currently running...**
Just havent gotten around to updating to latest version.

- SpongeForge version: 
spongeforge-1.10.2-2202-5.1.0-BETA-2078

- Forge version: 
forge-1.10.2-12.18.3.2202-universal

- Java version: 
Java Version: 1.8.0_102

- Operating System:

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: 
AgriculturalExpansion[1.9.4][1.10.2]-r1.2.2
ArchitectureCraft-1.7.1-mc1.10.2
Baubles-1.10.2-1.3.6
BBG-1.9.4-5.0.0
bdlib-1.12.2.17-mc1.10.2
BetterAchievements-1.10.2-0.3.2.39
Botania r1.9-339
BrandonsCore-1.10.2-2.1.1.61-universal
BuildingBricks-1.10.2-2.0.13
Chameleon-1.10-2.2.2
chickens-4.3.2
chiselsandbits-12.7
CodeChickenCore-1.10.2-2.3.5.91-universal
CoFHCore-1.10.2-4.1.1.156-universal
CodeChickenLib-1.10.2-2.5.7.241-universal
compatlayer-1.10-0.1.4
ComputerCraft1.80pr0
Draconic-Evolution-1.10.2-2.0.3.137-universal
DynamicLights-1.10.2
DynamicLights-1.10.2-sources 
ElevatorMod[V.1.3.0][MC.1.10.2]
EnderCore-1.10.2-0.4.1.65-beta
EnderIO-1.10.2-3.1.186
EnderStorage-1.10.2-2.1.5.84-universal
EnderZoo-1.10-1.2.3.43
extrautils2-1.10.2-alpha-1.2.2
ExtremeReactors-1.10.2-0.4.5.21
forestry_1.10.2-5.2.16.326
FTBLib-1.10.2-3.2.9
FTBUtilities-1.10.2-3.2.9
gendustry-1.6.4.24-mc1.10.2
generators-0.9.20.18-mc1.10.2
GraveStone Mod 1.5.9
HardcoreDarkness-MC1.9.4-1.8
hatchery-1.10.2-0.3.11
InfernalMobs-1.10
InventoryTweaks-1.61-58
ironchest-1.10.2-7.0.11.797
jefb_1.10.2-1.0.4
jei_1.10.2-3.13.6.387
jeibees-0.9.0.4-mc1.10.2
journeymap-1.10.2-5.3.0
JustEnoughResources-1.10.2-0.5.8.98
LLOverlayReloaded-1.1.1-mc[1.9-1.11]
Mantle-1.10.2-1.1.1
mcjtylib-1.1x-2.3.1
Mekanism-1.10.2-9.2.1.300
MekanismGenerators-1.10.2-9.2.1.300
MekanismTools-1.10.2-9.2.1.300
morebees-1.10.2-1.1.4
Morpheus-1.10.2-3.1.9
omlib-1.10.2-3.0.0-61
openmodularturrets-1.10.2-3.0.0-100
Pam's Clay Spawn 1.9.4-1.10.2a
Pam's Get all the Seeds! 1.9.4-1.10.2a
Pam's HarvestCraft 1.9.4-1.10.2b
PlayerAPI-1.10.2-1.1
pressure-1.3.1.18-mc1.10.2
ProgressiveAutomation-1.10.2-1.7.0
refinedstorage-1.1.3
Reliquary-1.10.2-1.3.3.585
rftools-1.1x-5.92
rftoolsctrl-1.1x-1.6.3
rftoolsdim-1.1x-4.55
RoguelikeDungeons-1.10.2-1.5.4
RTG-1.10.2-4.1.1.7
Ruins-1.10.2
simplegenerators-1.10.2-0.10.5b
StorageDrawers-1.10.2-3.5.14
StorageDrawersExtras-1.10.2-1.0.0
TConstruct-1.10.2-2.5.6b
Tesla-1.10.2-1.2.1.50
theoneprobe-1.10-1.3.3
ThermalExpansion-1.10.2-5.0.4.90-universal
ThermalFoundation-1.10.2-2.0.5.81-universal
Tinkers' Addons-1.10.x-1.0.3
topaddons-1.10.2-0.9.1b
TreeChopper-1.10.2-1.1.1
UniDict-1.10.2-2.4
valkyrielib-1.10.2-0.10.5e
WanionLib-1.10.2-1.2
woot-1.10.2-1.2.1
zerocore-1.10.2-0.0.8.2

**What is the expected result?**
world to load without crash

**What is the current result?**
server crashes when user tried to create/load rftools world on 2 separate occasions
github post:
https://github.com/McJty/RFTools/issues/1206

crashlog:
https://gist.github.com/ktole1999/3f67cf132f58cf1946f84251a9f6cc5e

**Comment by FiveEYZ** [comment]
this was fixed https://github.com/SpongePowered/SpongeForge/commit/f2f78aedddcb8d718fe5f478d9d4b55bad9b6fd7

as you can see the date, this issue was fixed over 4 MONTHS AGO!

**Comment by dualspiral** [comment]
@ktole1999 Reporting bugs on serverely outdated versions doesn't help us - a lot changes in 300 builds and there is always a good chance that updating will fix the issue - in this case, it seems like it would have been. Please make sure you check if a bug exists using the LATEST version of SpongeForge in future.

If this bug still exists when you've updated everything to the latest, please comment back here. Otherwise, I'm closing this for now.
