### ISSUE TITLE
[1.10.2] EnderIO RuntimeException

### ISSUE THREAD

**Issue by mzx987** [SpongePowered/SpongeForge#1548]
**I am currently running...**

- SpongeForge version: 5.2.0 BETA 2353
- Forge version: 12.18.3.2297
- Java version: OpenJDK Version 8, Build 131
- Operating System: Ubuntu Server (Linux:amd64:4.4.0-78-generic)

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: 
Plugins (78): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, OpenComputers (Core), Backpacks!, SpongeAPI, SpongeForge, CoFH ASM, FoamFixCore, ccl-entityhook, Psi, AutoRegLib, BiblioCraft, Chameleon, CodeChicken Lib, CodeChicken Core, ChickenChunks, MCMultiPart, Chisels & Bits, Compact Machines 2, CoFH Core, asielib, EnderCore, Ender IO, EnderStorage, OpenComputers, TIS-3D, Computronics, CraftTweaker JEI Support, MineTweaker 3, ElecCore, Extra Utilities 2, Zero CORE, Extreme Reactors, Flat Colored Blocks, FoamFix, Forge Multipart CBE, Forge Microblocks, Minecraft Multipart Plugin, HideNames, Mantle, Tinkers' Construct, Immersive Engineering, Iron Chest, JourneyMap, mercurius_updater, MTLib, Mod Tweaker, MorePlayerModels, MrTJPCore, Never Enough Currency, Storage Drawers, Refined Storage, OC RS Driver, OMLib, OC Glasses, Open Modular Turrets, OpenRadio, Pam's HarvestCraft, ProjectRed Core, ProjectRed integration, ProjectRed Transmission, ProjectRed Fabrication, ProjectRed Illumination, ProjectRed Expansion, ProjectRed Transportation, ProjectRed Exploration, RFTools, Simply Jetpacks 2, Super Circuit Maker, Thermal Foundation, Thermal Expansion, ThutCore, Thut's Tech, WirelessRedstone-CBE, GriefPrevention, LuckPerms

**What is the expected result?**
Nothing, really. Just noticed that this was popping up constantly.

**What is the current result?**
It appears that every time an update (or world interaction) occurs with the Ender IO Farmer, [this happens](https://pastebin.com/gSmc7AzT)

If a full fml log is needed, let me know.

**Comment by Zidane** [comment]
@simon816 

Take a look at this, see what you think.

**Comment by mzx987** [comment]
From the looks of things, Ender IO already fixed this issue. So I should be able to close this now.
