### ISSUE TITLE
Cause Tracker preventing entities from spawning properly after player dimension change

### ISSUE THREAD

**Issue by radfast** [SpongePowered/SpongeForge#1552]
Hi, I'm co-developer of Galacticraft and a previous contributor to Sponge.

- SpongeForge version:   spongeforge-1.10.2-2281-5.2.0-BETA-2353.jar
- Forge version:  2281
- Plugins/Mods: Galacticraft (latest), JEI

Bug:
1) Using the Forge mod (Galacticraft), transfer the player to a new dimension ...
2) If the player now does an action to cause any new entity to spawn in the world (for example, spawn any mob using a spawn egg, or use a Galacticraft rocket item to place a rocket on a launch pad) ...
3) the entity spawns on the server but does not spawn client-side - so for example the spawn egg item is used, but no mob spawns, or the rocket item is used, but no rocket entity spawns on the client - this also appears to be preventing Galacticraft Moon Lander entities from spawning correctly on Sponge servers, see https://github.com/micdoodle8/Galacticraft/issues/2779

If the player re-logs, the spawned entity is now visible on the client.  So the entity did spawn correctly on the server before, but it did not spawn client-side.

Tested with SpongeForge versions from 2212 through to 2353.

* The issue **does not** occur for Galacticraft plus standard Forge (no Sponge)
* The issue **does not** occur for Galacticraft plus all Sponge versions up to 2250
* The issue **does** occur for Sponge version 2254
* The issue **does** occur for all more recent Sponge versions after 2254 **including 1.11.2 versions**

Sponge version 2254 was the one which made [heavy CauseTracker changes](https://github.com/SpongePowered/SpongeCommon/compare/0811f5c721fe6c72add2a08728796935538670f2...266abdc078b40d2e8b32311bbf3af7880ee48fda) 
so I'm assuming it's the CauseTracker causing this issue...

Galacticraft's player dimension transfer code is identical to all the important parts of ```net.minecraft.server.management.PlayerList.transferPlayerToDimension(EntityPlayerMP player, int dimensionIn, net.minecraft.world.Teleporter teleporter)``` but without the portal rendering and without the 8 * divider / multiplier for x,z positions used going to and from the Nether.

Other major Forge mods also have similar dimension transfers, including MystCraft.

----

This issue is extremely frustrating, because:
- it's **caused** by the CauseTracker, which just seems wrong!
- there appears to be no way to disable the CauseTracker, even in global.conf
- there appears to be no way for a Forge mod to control the CauseTracker

Probably, as with some other parts of Sponge in the past (!), the CauseTracker code does not fully take account of the fact that Forge mods can change player dimensions, and there are more possible dimensions than just { -1, 0, 1 }

I've spent 3 hours of my mod development time identifying that it's Sponge version 2254 changes which caused this.  I don't have time to plow through and understand the 1157 lines of Sponge code which changed in that commit to tell you which exact line causes the problem, but obviously it must be connected with players changing dimensions, and spawn entity code.

**Comment by radfast** [comment]
Our user (server owner) who first reported the issue to us has now confirmed that multiple issues are solved by using SpongeForge version 2250 or prior, instead of the latest.

> **Ha funny thing is i try to use spongeforge-1.10.2-2254-5.2.0-BETA-2250.jar with no problem and teleporting to other dimensions not cause bugs (sometime on sponge 2353 even simple teleport to nether and back blocks commads like /spawn /home and relog fix it ) galacticraft landing modules works and advanced rocketry mining rockets landings now works !**

-----

I don't know how much Sponge sees Forge-compatibility as important - I would hope it's a primary goal? - but seems like the CauseTracker is really messed up at the moment.

I've also now tested recent Sponge versions with command line argument
>
    -Dsponge.causeTracking=false

and even with that it's still causing the above issues in 2254 and later.

**Comment by radfast** [comment]
Further testing with breakpoints client-side shows that the Sponge server is not sending any entity spawning packets to the client, in the situation described.  So the client does not receive any ```SPacketSpawnMob```, ```SPacketSpawnObject``` or ```FMLMessage$EntitySpawnMessage```.

Normally on a server all these tyoes of packets should be sent by ```net.minecraft.entity.EntityTracker.createSpawnPacket()```

**Comment by Zidane** [comment]
@gabizou 

I need you to look into this as soon as possible. We don't need regressions from massive tracker changes.

**Comment by gabizou** [comment]
@radfast sorry that it's taking me forever, time gets busy and work gets in the way. I know that disabling the cause tracker is not usable as currently there's a lot of code in place that has yet to consider that cause tracking is disabled. I'm going to try to get to this before the end of the month (due to time constraints, I can't even consider getting this done in a few days unless something IRL clears up).

**Comment by radfast** [comment]
@guys thank you for attending to this, and I appreciate that it is likely going to need a fair amount of work to fix.

I'm fairly busy IRL for the next week also, and with attending to our own mod.

Once you're in a position to look at this in more detail, if there's anything I can do to help, please do ping me - for example I'm happy to help try to narrow down the conditions further.  Right now it looks like it's simply a player dimension change and then some things are messed up.

More generally there may be a design issue, if Sponge tracker's proper operation is dependent on use of Sponge hooks to effect important transactions (e.g. dimension changes).  Forge mods obviously are agnostic of Sponge''s presence, and are using vanilla methods or Forge hooks or doing things in  their own way.  It seems possible that the tracker is "enforcing" use of certain Sponge hooks.  If so, that's simply not going to work with Forge mods...

**Comment by stephan-gh** [comment]
Can't reproduce this on latest SpongeForge 1.11.2 build. Spawning entities and placing rockets works fine after a dimension change.

What I did is:

- Use a rocket to go from Overworld to Mars
- Try to spawn cows using spawn eggs: Worked fine
- Try to place a rocket: Worked fine

**Comment by radfast** [comment]
Which exact build are you testing, @Minecrell ?   I can re-test, maybe someone fixed it :)

And I'm not sure your label is appropriate, if there is (still) an issue, it's a generic Sponge problem which will affect any Forge mod with dimension transfers.

**Comment by stephan-gh** [comment]
@radfast I've been testing in the SpongeForge development environment on the `stable-6` branch, which should be equivalent to `1.11.2-2393-6.1.0-BETA-2592` with `GalacticraftCore-1.11.2-4.0.0.116` etc.

**Comment by radfast** [comment]
Thanks, tested the latest and the issue seems to have been resolved.

I'll update our documentation accordingly.

Great job guys.  I don't see which commit fixed this but thank you to the team :)
