### ISSUE TITLE
[1.10.2] Console Spam Error "Unexpected World Change Detected"

### ISSUE THREAD

**Issue by RogueRaiden** [SpongePowered/SpongeForge#1554]
**I am currently running...**

- SpongeForge version:  spongeforge-1.10.2-2281-5.2.0-BETA-2353
- Forge Version:  forge-1.10.2-12.18.3.2297-universal
- Java version:  1.8.0_71
- Operating System:

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows

- Plugins/Mods: 
[modslist.txt](https://github.com/SpongePowered/SpongeCommon/files/1033205/modslist.txt)

**What is the expected result?**
For the server not to spam error messages?

**What is the current result?**
Spamming error messages.

Really not sure what is going on, server doesn't seem to crash or anything. (haven't loaded into the server yet, was adding Sponge back into my server while testing)

According to the log, only seems to have an effect with Applied Energistics 2 and AE2 Stuff

[server-latest.txt](https://github.com/SpongePowered/SpongeCommon/files/1033206/server-latest.txt)

**Comment by JaSpr** [comment]
We have this issue as well with FTB Beyond 1.7.0.  Seemingly the same issue.  Causes *lots* of lag while the spam is going on.

[log](https://gist.github.com/JaSpr/e078006ff5bdafd10de26427c37c90d9)

**Comment by FiveEYZ** [comment]
on 1.11.2
Mekanism's Digital Miner is also causing this spam when it digs
error:
https://gist.github.com/FiveEYZ/49eefd0b134e42533c26d3a125790d4e

server-log:
https://gist.github.com/FiveEYZ/a1c898ed6fca37d30cc52d91590c148d

**Comment by Orcinuss** [comment]
My beyond server (v1.8.0) is also being affected by this. It causes massive lag whilst occurring results in server timeouts where players can no longer get on the server without it being restarted manually.

Server Log snippet: https://pastebin.com/U2jHijqF

**Comment by JaSpr** [comment]
For the time being, go into config/sponge/global.conf and change cause-tracker.verbose to false.  Requires server restart

**Comment by RogueRaiden** [comment]
@JaSpr and what does that do?

**Comment by Orcinuss** [comment]
@JaSpr, if there is another issue that causes a crash, will the crash report not tell me what the issue is if I turn the setting off?

**Comment by JaSpr** [comment]
That setting is to turn off the ongoing logs.  It shouldn't have anything to do with a crash report.  It's just the cause tracker logging that logs pages of data at a time.

**Comment by bloodmc** [comment]
dupe #1470
