### ISSUE TITLE
Login not possible!?

### ISSUE THREAD

**Issue by Billabonga** [SpongePowered/SpongeForge#1555]
I don't seem to be able to login on the spongepowered.org pages from my computer. the login window doesn't even open. Using Linux Mint Cinnamon Sarah. - Any Ideas?

- Operating System:

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: 

**What is the expected result?**

**What is the current result?**

**Comment by gabizou** [comment]
It's a known issue, this repository is not the right place to report issues with the website.

**Comment by JBYoshi** [comment]
@Billabonga This was reported a long time ago in <s>a galaxy far far away</s> the SpongeAuth repository: SpongePowered/SpongeAuth#13.
