### ISSUE TITLE
[1.10.2-2123-6.0.0-BETA-1902] Chat lists user name twice.

### ISSUE THREAD

**Issue by JaSpr** [SpongePowered/SpongeForge#1556]
Chat now looks like:
`Username: <Username> Message....`

**I am currently running...**
    Minecraft: 1.10.2
    SpongeAPI: 6.0.0-SNAPSHOT-24eb858
    SpongeForge: 1.10.2-2123-6.0.0-BETA-1902
    Minecraft Forge: 12.18.3.2297
    Operating System: Linux (amd64) version 3.14.32-xxxx-std-ipv6-64
    Java Version: 1.8.0_131, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation

 - [X] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: 
 Aroma1997Core, Not Enough Items, OpenComputers (Core), SpongeAPI, SpongeForge, CoFH ASM, FoamFixCore, ccl-entityhook, CoFH Core, Actually Additions, IndustrialCraft 2, Advanced Machines, Advanced Solar Panels, Applied Energistics 2, BD Lib, AE2 Stuff, InfinityLib, AgriCraft, Baubles, Botania, Akashic Tome, Just Enough Items, AppleSkin, Aquaculture, ArchitectureCraft, Aroma1997Core|Helper, Aroma1997's Dimensional World, AromaBackup, AromaBackup Recovery, Morph-o-Tool, Psi, Quark, AutoRegLib, Bed Bugs, Better Builder's Wands, BiblioCraft, Guide-API, Blood Magic: Alchemical Wizardry, Blood Arsenal, Bookshelf, CodeChicken Lib, Brandon's Core, CatClearLag, Ceramics, Chameleon, Chest Transporter, Chisel, MCMultiPart, Chisels & Bits, ShadowMC, Clipboard, CodeChicken Core, Compact Solar Arrays, Cooking for Blockheads, CraftTweaker JEI Support, MineTweaker 3, Dark Utilities, PTRModelLib, Decocraft, Forestry, ElecCore, EnderStorage, OpenComputers, DeepResonance, Discord Bridge, Draconic Evolution, Storage Drawers, Drawers & Bits, Elevator Mod, Embers, EnderCore, Ender IO, Engineers Workshop, Valkyrie Lib, Environmental Tech, ET Lunar, Extra Utilities 2, Zero CORE, Extreme Reactors, Flat Colored Blocks, SonarCore, FluxNetworks, FoamFix, Forgelin, Forge Multipart CBE, Forge Microblocks, Minecraft Multipart Plugin, FTBLib, FTBUtilities, Funky Locomotion, Funnels, GenDustry, Gravestone, Gravitation Suite, Hammer Core, HelpFixer, Hopper Ducts, Mantle, Tinkers' Construct, The One Probe, Immersive Engineering, LunatriusCore, InGame Info XML, Interaction Wheel, Inventory Tweaks, Iron Backpacks, Iron Chest, JEI Bees, JourneyMap, KleeSlabs, Long Fall Boots, LuckPerms, MalisisCore, MalisisDoors, Mercurius, Modular ForceField System, MmmMmmMmmMmm, mob_grinding_utils, MTLib, Mod Tweaker, Railcraft, More Bees, Morpheus, ModPack Utilities, ModPack Basic Tools, MrTJPCore, ShetiPhian-Core, Multi-Storage, Natura, Nether Portal Fix, Nucleus, Open Glider, p455w0rd's Library, Pam's HarvestCraft, ProjectRed Core, ProjectRed integration, ProjectRed Transmission, ProjectRed Illumination, ProjectRed Expansion, ProjectRed Transportation, ProjectRed Exploration, RebornCore, QuantumStorage, Ranged Pumps, reborncore-MCMultiPart, Thermal Foundation, Redstone Arsenal, Refined Relocation, Refined Storage, Reliquary, RFTools, RFTools Control, RFTools Dimensions, Roots, Signals, SimpleVoidWorld, Simple Retrogen, Simply Jetpacks 2, Sleeping Bag, Snad, Solar Flux Reborn, Steve's Carts 2, Storage Drawers Extras, Super Circuit Maker, Super Crafting Frame, TechReborn, Thermal Expansion, TickProfiler, Tinkers Tool Leveling, TOP Addons, TorchMaster, Translocator, Useful Nullifiers, WanionLib, Wireless Crafting Grid, Wireless Crafting Terminal 2, Woot, WorldEdit, WirelessRedstone-CBE, XNet, YABBA, UniDict

**Comment by JaSpr** [comment]
Running FTB Beyond 1.7.0, however this bug started when we upgraded from the latest stable sponge to the latest experimental

**Comment by phit** [comment]
that experimental version is 6 months old and not meant for actual usage, please switch back to the stable branch

**Comment by JaSpr** [comment]
Kill it with fire.

**Comment by JaSpr** [comment]
I had (wrongly) assumed we could be using a newer build by switching to experimental branch.  I take it all builds are now classified as "stable"?

**Comment by phit** [comment]
Yes, 1.10.2 is in bugfix only mode (stable-5), then there's stable-6 for 1.11.2.
Experimental usually targets the latest version so right now 1.11.2 with the focus of developing API version 7 this is where all the breaking changes happen and I wouldn't recommend ever running experimental on a production server, even if you were on 1.11.2.

**Comment by JaSpr** [comment]
We (all of our members) were hoping there might be some progress on #1346 on a non-stable build.  It's been around for months and a lot of players (on multiple servers I've played on) have complained to me about it.

**Comment by dualspiral** [comment]
@JaSpr This isn't an issue with Sponge anyway. In Nucleus, set `chat.check-body-for-minecraft-prefix` to `true` or, if that doesn't work, `chat.overwrite-early-prefixes` to `true`. Some other plugin or mod is affecting the chat and moving the Minecraft tag into the body, rather than the prefix.

If you have any more issues, you're best off asking over in the Nucleus discord channel or filing an issue there.

**Comment by JaSpr** [comment]
Well, the reason I opened a sponge ticket was because the *only* thing that changed was I switched from latest-stable version of spongeForge to the experimental version (which I didn't realize was so old).  Sort of has to be an issue with sponge if changing sponge is what caused it.

**Comment by JaSpr** [comment]
Although, the ticket is invalid because that build is invalid.
