### ISSUE TITLE
Crash With Lost Thaumaturgy Mod

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1558]
**I am currently running...**
- SpongeForge version: 1.11.2-2282-6.1.0-BETA-2357
- Forge version: 2310
- Java version: Java 8 x64 u131
- Operating System:
 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows
- Plugins/Mods: 
Plugins: FlexibleLogin, UniverseGuard
Mods: [Lost Thaumaturgy](https://minecraft.curseforge.com/projects/lost-thaumaturgy?gameCategorySlug=mc-mods&projectID=232564)

sorry if it's not Sponge's fault.

**Comment by phit** [comment]
from the crash report
`Mod iceandfire (Ice and Fire) requires [llibrary@[1.4.1,)]`

install [llibrary](https://minecraft.curseforge.com/projects/llibrary), not a sponge issue

**Comment by ghost** [comment]
oh sorry i just reproduced the bug with only installing ice and fire, sponge and plugins to let a clear crash report. it crashed in my modpack first time. 
[crash-2017-06-01_14.59.39-server.txt](https://github.com/SpongePowered/SpongeForge/files/1044652/crash-2017-06-01_14.59.39-server.txt)
btw, it crashes LT in actual. sorry for mentioning the wrong mod.


---
and here is another crash
[crash-2017-06-01_15.39.10-server.txt](https://github.com/SpongePowered/SpongeForge/files/1044747/crash-2017-06-01_15.39.10-server.txt)

**Comment by kenijey** [comment]
hey plz don't abandon it :D

**Comment by kenijey** [comment]
and here is another crash
[crash-2017-06-01_15.39.10-server.txt](https://github.com/SpongePowered/SpongeForge/files/1044747/crash-2017-06-01_15.39.10-server.txt)

**Comment by kenijey** [comment]
hey ah, it also crashes with ice and fire mod also, i was wrong.
here is the crash report:
[crash-2017-06-01_18.40.57-server.txt](https://github.com/SpongePowered/SpongeForge/files/1045321/crash-2017-06-01_18.40.57-server.txt)

**Comment by kenijey** [comment]
hello again, sponge crashed with Animania mod. it's another crash on the same server.
[1.txt](https://github.com/SpongePowered/SpongeForge/files/1045980/1.txt)

**Comment by Deamon5550** [comment]
If its different mods crashing then open separate issues we so we can track then individually.

**Comment by ghost** [comment]
okay.

**Comment by phit** [comment]
deleted some unrelated logs to make this issue easier to read after checking if they are also reported

**Comment by phit** [comment]
Mod was taken down due to copyright infringement, which makes me unable to test this. Please let me know if the mod gets rereleased and this is still an issue and I'll reopen this issue.
