### ISSUE TITLE
Crash With Animania Mod

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1559]
**I am currently running...**
- SpongeForge version: sponge 2357
- Forge version:  2310
- Java version:  8u131
- Operating System:
 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows
[1.txt](https://github.com/SpongePowered/SpongeForge/files/1045990/1.txt)

**Comment by gigafunk** [comment]
I run animania's newer releases on sponge 1.10.2  sponge 2422  with forge 2281..and q89 other mode and its all perfect so my opinion as nobody is this gets closed.

**Comment by gigafunk** [comment]
Nevermind I didn't realize this was 1.11.
