### ISSUE TITLE
Beyond Server - Quarry Issue

### ISSUE THREAD

**Issue by Keaton1188** [SpongePowered/SpongeForge#1560]
Hi all, currently having this issue where the Quantum Quarry world goes to mine and then hits a silver-fish, this then gives the error "java.lang.IllegalArgumentException: Attempted to cancel a non cancellable event"

To fix it, we have to set the difficulty of the Quantum Dim (DIM-9999) to peaceful, if the server restarts or something, this change won't save.

Crash - https://pastebin.com/w5nKtnkg

Is this a issue with sponge or ExU?

SpongeForge:
Minecraft: 1.10.2
SpongeAPI: 5.2.0-SNAPSHOT-a26c654
SpongeForge: 1.10.2-2281-5.2.0-BETA-2353
Minecraft Forge: 12.18.3.2254

(Using latest version of the modpack - 1.8.1)

**Comment by FiveEYZ** [comment]
same issue as almost all of these in this link
https://github.com/SpongePowered/SpongeForge/issues?utf8=%E2%9C%93&q=is%3Aissue%20quantum

**Comment by phit** [comment]
This is a ExU2 issue, the quarry itself was fixed with Sponge!
This issue is ExU2 is trying to cancel a non cancellable event so this can't be fixed on Sponge's end https://github.com/SpongePowered/SpongeForge/issues/1158#issuecomment-281769315
