### ISSUE TITLE
villagers have mismatched trades

### ISSUE THREAD

**Issue by Twisted-Code** [SpongePowered/SpongeForge#1562]
**I am currently running...**

- SpongeForge version: spongeforge-1.10.2-2281-5.2.0-BETA-2353 (Last time I checked the site this was latest and I doubt you would expect people to update every time the repo is pushed, even if it might make fixing things easier)
- Forge version: forge-1.10.2-12.18.3.2185
- Java version: going by the Java control panel, Java 8 update 121 (build 1.8.0_121-b13)
- Operating System: 

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows (specifically, Windows 7 professional 64 bit, service pack 1)

- Plugins/Mods: Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Applied Energistics 2 Core, Not Enough Items, CoFH ASM, ccl-entityhook, CoFH Core, Actually Additions, Just Enough Items, AppleSkin, Applied Energistics 2, Psi, AutoRegLib, CraftTweaker JEI Support, MineTweaker 3, B.A.S.E, Base Metals, Baubles, Biomes O' Plenty, Botania, Chickens, Clay Bucket, CodeChicken Lib, CodeChicken Core, ContentTweaker, Cyclops Core, Bailey's Dailies, Forestry, ElecCore, DeepResonance, EnderCore, Waila, Ender IO, EvilCraft, Extra Utilities 2, Zero CORE, Extreme Reactors, Forge Multipart CBE, Forge Microblocks, Minecraft Multipart Plugin, Guide-API, Hatchery, Mantle, Tinkers' Construct, Immersive Engineering, Inventory Tweaks, LuckPerms, MTLib, Mod Tweaker, Thermal Foundation, More Chickens, Natura, Nucleus, Ore Spawn, Pam's HarvestCraft, ProjectWorlds, Railcraft, Redstone Arsenal, Reliquary, RFTools, RFTools Dimensions, Thermal Expansion, Vampirism, TeamLapen Library, I Can See Everything, What Are We Looking At, WirelessRedstone-CBE

**What is the expected result?**
villagers should have trades, appearance, and label corresponding to exactly 1 profession per villager
**What is the current result?**
villagers look like one specific profession but get trades from a different profession's pool (in addition to possibly starting with their normal trades). For instance, any Jam Guy villagers (from actually additions) I spawn is assigned Railcraft Trackman trades (and I initially reported the issue on the respective trackers for those repositories. See [here](https://github.com/Ellpeck/ActuallyAdditions/issues/797) & [here](https://github.com/Railcraft/Railcraft/issues/1239)). Similarly, Forestry Arborists are assigned Apiarist trades. 
I cannot reproduce this issue in single player, and therefore can only assume SF has something to do with it. It probably has something to do with whatever you did to solve the "invalid profession ID" crash several versions back.
(uncommented for context)"Please provide a *full* server log, either by uploading it to this
         issue, or to a site like https://gist.github.com/ "
will do, although I doubt it'll help much in tracking down the issue beyond verifying the list of mods, as the problem only occurs when a villager is spawned and even then there doesn't appear to be any verbose logging related to villager spawns

[fml-server-latest.log.txt](https://github.com/SpongePowered/SpongeForge/files/1049727/fml-server-latest.log.txt)

if I left anything out, please by all means let me know, as this issue is more than slightly annoying. In the meantime, I'm going to set up some Forestry Trade Stations...

**Comment by macks2008** [comment]
thread bump: I figure if it's been up for 2 days and no one has even labeled it, you probably missed it, right?

**Comment by Twisted-Code** [comment]
any progress on this issue guys? Someone in the Discord server said it was something to do with a villager registry or something along those lines? I know y'all are probably just busy maintaining this massive project between, what, 5 coders(?) but I'd really appreciate the status report. Is it fixed? Has anyone figured out at least part of the issue? Is there anything I can do to help? Err, besides stop "bugging" (heh) you guys?

**Comment by Twisted-Code** [comment]
thank you blood for the help on discord. At least now I know who to talk to if this persists on the latest (or nearly latest) Sponge. Will be testing it shortly
