### ISSUE TITLE
Failing to run Minecraft Server IntelliJ run configuration

### ISSUE THREAD

**Issue by hfreeb** [SpongePowered/SpongeForge#1566]
I have cloned the repository and run both 'setupDecompWorkspace --refresh-dependencies' and 'genIntellijRuns' and they worked successfully. But, when I try to run the 'Minecraft Server' run configuration created, I am spammed with errors from the build such as:
```
/SpongeForge/SpongeCommon/src/main/java/org/spongepowered/common/mixin/tileentityactivation/MixinChunk_TileEntityActivation.java
Error:(48, 5) java: No obfuscation mapping for @Inject target addTileEntity
```
causing the run to fail.

**Comment by kashike** [comment]
If I remember correctly, you need to disable the mixin annotation processor in your IDE.

**Comment by hfreeb** [comment]
That works! Thanks.
