### ISSUE TITLE
There was error attempting to update some data for the content

### ISSUE THREAD

**Issue by aaronegger** [SpongePowered/SpongeForge#1569]
**I am currently running...**

- SpongeForge version: spongeforge-1.11.2-2282-7.0.0-BETA-2356
- Forge version: 13.20.0.2282
- Java version: Client and Server jre1.8.0_111
- Operating System: Windows 8.1 Pro x64

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows

- Plugins/Mods: 
AbyssalCraft-1.11.2-1.9.4-pre-2.jar
AdvancedRocketry-1.11.2-1.2.0f.jar
AnimalBikes-1.11.2.jar
Baubles-Mod-1.11.2.jar
BiomesOPlenty-1.11.2-6.0.2.2167-universal.jar
Botania Mod 1.11.2.jar
ChickenChunks-1.11.2-universal.jar
CodeChickenLib-1.11.2-Recommended.jar
CosmeticArmorReworked-1.11.2.jar
ExtremeReactors-1.11.2.jar
Galacticraft-Planets-1.11.2-4.0.0.95-BETA.jar
GalacticraftCore-1.11.2-4.0.0.95-BETA.jar
Gun-1.11.2.jar
InventoryTweaks-1.62-dev-78.jar
JourneyMap-1.11.2.jar
JurassiCraft-2.0.5.jar
LLibrary-1.11.2.jar
Levels-Mod-1.11.2.jar
LibVulpes-1.11.2-0.2.3b-universal.jar
Mantle-1.11.2-1.2.0.26.jar
MicdoodleCore-1.11.2-4.0.0.95-BETA.jar
MoreAnvils-1.11-7.0.0.jar
OptiFine_1.11.2_HD_U_B7.jar
SignEditor-1.0.3-b6.jar
SimpleDimensions-MC1.11-1.3.jar
TConstruct-1.11.2-2.7.0.26.jar
aether_legacy-1.11.2-1.0.jar
compatlayer-1.11.2-0.2.9.jar
energyconverters_1.11.2-0.6.0.13.jar
extrautils2-1.11.2-1.4.1.jar
industrialcraft-2-2.7.60-ex111.jar
jei_1.11.2-4.3.5.277.jar
plustic-5.0.1.0.jar
zerocore-1.11.2-0.1.0.4.jar

**What is the expected result?**

Player should be possible to join the server.

**What is the current result?**

Server is starting correctly but players can not join.

BUT PLEASE NOTICE:
It works with spongeforge-1.11.2-2227-6.0.0-BETA-2260!
This is the last version where this problem does not exist.

All tried newer version are not working:
spongeforge-1.11.2-2282-6.0.0-BETA-2297.jar
spongeforge-1.11.2-2282-6.1.0-BETA-2357.jar
spongeforge-1.11.2-2282-7.0.0-BETA-2307.jar
spongeforge-1.11.2-2282-7.0.0-BETA-2356.jar

https://gist.github.com/aaronegger/71d8c97840f43cc1078d3e0ce757f630

I hope i didn't miss something..

Thank for making this great mod! It is our bridge from bukkit to forge :)

**Comment by aaronegger** [comment]
I fixed it by myself.

It was the entry ForgeData->SpongeData->CustomManipulators

I had to delete this tag completely to fix it.
Even if there were no sub tags it refused to let someone join the server if this tag was set.
The plugin adventureMMO added a custom tag.

It is not a big thing but i will leave it up to you if you want to leave or delete this issue.
Maybe this will help someone else who is facing the same issue..

**Comment by gabizou** [comment]
This is an issue as it's necessary to perform upgrades from pre-existing data from legacy systems. If you can provide a copy of the old player data and a copy of the new one, that'd be helpful.

**Comment by aaronegger** [comment]
@gabizou 
Sorry for my late answer.

I've uploaded two profiles on my server.
http://mc.aaronegger.de/oldOne.dat
http://mc.aaronegger.de/newOne.dat

We have now removed the plugin from our server.
After upgrading from spongeforge-1.11.2-2227-6.0.0-BETA-2260 to spongeforge-1.11.2-2282-6.1.0-BETA-2358, AdventureMMO (v2.0.7) refuses to work proberly.

There is a warning that the player profiles couldn't be saved.

Is this something sponge related? Or do you maybe know what's causing this issue?
If have an error log/stacktrace uploaded here: https://gist.github.com/aaronegger/fc18ce285e0dd808acc3d61c314c5122

Maybe I'm lucky and you recognize the problem from somewhere :)
I really miss the plugin, but downgrading to 2260 is no option anymore, since some important bugs, like tje shulker boxes are fixed with the current versions.
