### ISSUE TITLE
[1.10.2] MobSpawner Spam

### ISSUE THREAD

**Issue by Bennyboy1695** [SpongePowered/SpongeForge#1570]
**I am currently running...**

- SpongeForge version: 1.10.2-2281-5.2.0-Beta-2363
- Forge version: 12.18.3.2281
- Java version: 1.8.0_131
- Operating System:

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: 
Plugins (184): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Not Enough Items, CoFH ASM, FoamFixCore, ccl-entityhook, Deadly Monsters, Better Combat, BetterChunkLoader Forge Lib, EnderCryBreak, TickProfiler, Just Enough Items, AbyssalCraft, CoFH Core, Actually Additions, �5�m===�r �e�lThink Big Core �5�m===�r, �e�k!!�6�k]]�c�kkk�4�lAd Inferos�c�kkk�6�k]]�e�k!!, IndustrialCraft 2, Advanced Solar Panels, InfinityLib, AgriCraft, animalium, aquacreeper, Mantle, Tinkers' Construct, TESLA, TheDragonLib, ArmorPlus, Ars Magica 2, AnimationAPI, Quark, AutoRegLib, Avaritia, Avaritia Additions, Baconators, Baubles, Baubles Stuff, BD Lib, Better Questing, Guide-API, Blood Magic: Alchemical Wizardry, Blood Arsenal, Bloodmoon, Bookshelf, CodeChicken Lib, Brandon's Core, Chameleon, CodeChicken Core, ChickenChunks, Chisel, MCMultiPart, Chisels & Bits, Clarity, Classic Combat, Cyclops Core, Colossal Chests, Cooking for Blockheads, CraftTweaker JEI Support, MineTweaker 3, Creative+, Dark Utilities, Deez Nuts Creeper, Doomlike Dungeons, Draconic Evolution, Dragon Mounts, DragonRealm, Enchiridion, EnderCore, Ender IO, EnderStorage, Epic Siege Mod, Extra Utilities 2, Zero CORE, Extreme Reactors, Farming for Blockheads, Fast Leaf Decay, SonarCore, FluxNetworks, FoamFix, Forge Multipart CBE, Forge Microblocks, Minecraft Multipart Plugin, FTBLib, FTBUtilities, Advanced Generators, Grimoire of Gaia 3, iChunUtil, The One Probe, Immersive Engineering, InControl, Infernal Mobs, Inventory Pets, Iron Backpacks, Iron Chest, itank, JACB, Kitchen Sink Mod, Levels, Loot Bags, Tesla Core Lib, MekFarm, Mike Dongles, MineTweakerRecipeMaker, MmmMmmMmmMmm, Random Things, MoarSigns, Mob Properties, mob_grinding_utils, MTLib, Mod Tweaker, Morpheus, Mystical Agriculture, Natural Absorption, Nether Metals, Not Enough Wands, NuclearCraft, OMLib, Open Modular Turrets, OreExcavation, Ore Spawn, Pam's HarvestCraft, Thermal Foundation, PlusTiC, Prefab, Ranged Pumps, RebornCore, reborncore-MCMultiPart, Storage Drawers, Refined Storage, RebornStorage, Redstone Paste, Reliquary, RFTools, Rough Mobs, Silent Lib, Scaling Health, SeriousCreeper's Crafting Runes, SimpleCore API, SimpleOres 2, Simple Tinkers Construct Addon, Simply Jetpacks 2, Slugs EU and RF converters, Spartan Shields, Standard Expansion, Steve's Carts 2, Lemon's Simple Teleporters, The Beneath, Thermal Expansion, Tinker I/O, Tinkers' Addons, Tinkers Tool Leveling, TitanTrinkets, Tomb Many Graves, Tool Belt, Translocator, ViesCraft, WanionLib, AdminUtilsSponge, AdminUtilsForge, AutoBroadcaster, BetterChunkLoader, Kai's Commons, BetterItemRestrict, BetterKits, BetterOntime, BetterRestrictorItems, CatClearLag, ClearMob, EconomyLite, GriefPrevention, Holograms, LuckPerms, Market, MultiChat Sponge, Nucleus, ProjectWorlds, SleepAssist, WorldEdit, WorldList, UniDict

**What is the expected result?**
For the spam to not be there or for the mobspawner to be fixed/removed if not valid
**What is the current result?**
Huge spam in console from an "invalid spawner"

https://gist.github.com/Bennyboy1695/6d1be141f72f770b3ec0c30b17ffed36

**Comment by phit** [comment]
judging by this https://minecraft.curseforge.com/projects/craft-of-the-titans/issues/155
the mod is pretty broken, considering reporting this to the dev
https://github.com/bigbang87/deadly-monsters/issues

**Comment by Zidane** [comment]
That error also shows unregistered entities which means the mod isn't making correct use of the registries built into Forge and/or Minecraft. Not a Sponge issue.
