### ISSUE TITLE
[1.11.2] Mob Spawning in Nether issue

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1571]
**I am currently running...**
- SpongeForge version: 
spongeforge-1.11.2-2282-6.1.0-BETA-2360
- Forge version: 
forge-1.11.2-13.20.0.2282-universal
- Operating System:
 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows
- Plugins/Mods: 
minecraft{1.11.2} [Minecraft] (minecraft.jar) 
mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2282-universal.jar) 
forge{13.20.0.2282} [Minecraft Forge] (forge-1.11.2-13.20.0.2282-universal.jar) 
dmonsters{1.15} [Deadly Monsters] (1.11.2_deadly_monsters_1.15.jar) 
bettercombatmod{1.4.0} [Better Combat] ([MC 1.11.X] BetterCombatMod 1.4.jar) 
examplemod{1.0} [examplemod] ([MC 1.11.X] BetterCombatMod 1.4.jar) 
abyssalcraft{1.9.4-pre-3} [AbyssalCraft] (AbyssalCraft-1.11.2-1.9.4-pre-3.jar) 
csb_armorstand{1.0.2} [Armor Stand Configurator] (ArmorStandGUI-1.11-1.0.2.jar) 
babymobs{1.5.4} [Baby Mobs] (BabyMobs-1.11.2-1.5.4.jar) 
bettersprinting{1.1.9} [Better Sprinting] (BetterSprinting  MC-1.11.2  v1.1.9.jar) 
biomesoplenty{6.1.0.2238} [Biomes O' Plenty] (BiomesOPlenty-1.11.2-6.1.0.2238-universal.jar) 
blockarmor{2.4.3} [Block Armor] (BlockArmor-1.11.2-2.4.3.jar) 
chameleon{1.11.2-3.1.0} [Chameleon] (Chameleon-1.11.2-3.1.0.jar) 
chiselsandbits{13.10} [Chisels & Bits] (chiselsandbits-13.10.jar) 
cnoapm{1.0 by Dot_Silver} [Craftable Notch Apple Mod - MCVersion 1.11.2] (cnoapm-mcv1.11.2.jar) 
cosmeticarmorreworked{1.11.2-v1a} [CosmeticArmorReworked] (CosmeticArmorReworked-1.11.2-v1a.jar) 
extraalchemy{0.3.2-beta} [Extra Alchemy] (extraalchemy-0.3.2-beta.jar) 
flatcoloredblocks{mc1.11-5.2} [Flat Colored Blocks] (flatcoloredblocks-mc1.11-5.2.jar) 
overlord{2.3.7} [Overlord] (Overlord-1.11.2-2.3.7.jar) 
guideapi{1.11.2-2.1.1-52} [Guide-API] (Guide-API-1.11.2-2.1.1-52.jar) 
llibrary{1.7.6} [LLibrary] (llibrary-1.7.6-1.11.2.jar) 
iceandfire{1.1.0} [Ice and Fire] (iceandfire-1.1.0.jar) 
inventorypets{1.4.9.5} [Inventory Pets] (inventorypets-1.11.2-1.4.9.5.jar) 
ironchest{1.11.2-7.0.19.803} [Iron Chest] (ironchest-1.11.2-7.0.19.803.jar) 
iymts_mod{1.11.2-0.1.0} [iYAMATO's Mod] (iYAMATOs_mod-1.11.2-0.1.0.jar) 
journeymap{1.11.2-5.4.6} [JourneyMap] (journeymap-1.11.2-5.4.6.jar) 
mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
moredyes{@VERSION@} [More Dyes] (MoreDyes-1.11-1.1.1.jar) 
hellbound{1.0} [HellBound] (NetherBound 1.1.jar) 
netherbound{1.1} [NetherBound] (NetherBound 1.1.jar) 
netherportalfix{1.0} [NetherPortalFix] (NetherPortalFix_1.11-4.3.1.jar) 
roguelike{1.6.6} [Roguelike Dungeons] (RoguelikeDungeons-1.11.2-1.6.6.jar) 
com.superzanti.serversync{2.6.14} [ServerSync] (serversync-2.6.14.jar) 
simpleoregen{3.4.5} [Simple Ore Generation] (SimpleOreGeneration-3.4.5 mc 1.11.2.jar) 
flammpfeil.slashblade{mc1.11-r9} [SlashBlade] (SlashBlade-mc1.11-r9.jar) 
storagedrawers{1.11.2-4.2.7} [Storage Drawers] (StorageDrawers-1.11.2-4.2.7.jar) 
tammodized{0.9.2} [TamModized] (TamModized-1.11.2-0.9.2.jar) 
trashslot{7.4.5} [TrashSlot] (TrashSlot_1.11.2-7.4.5.jar) 
vending{1.4.3} [Vending] (vending-1.11.2-1.4.3.jar) 
villagermarket{1.0} [Villager Market] (villagermarket-0.2-HF.jar) 
voidcraft{0.19.6} [VoidCraft] (VoidCraft-1.11.2-0.19.6.jar) 
weaponcaseloot{5.0.3-beta} [WeaponCaseLoot] (weaponcaseloot-1.11.2-5.0.3-beta.jar) 
wearables{1.0.2} [Wearables] (wearables-1.0.2.jar) 
witherskelefix{1.7.0} [Wither Skeleton Tweaks] (Wither Skeleton Tweaks-1.11.2-1.7.2.jar) 
worldedit{6.1.6} [WorldEdit] (worldedit-forge-mc1.11-6.1.6-dist.jar)

----

**My server works correctly without Sponge-Forge.** But It happened if I add Sponge-Forge ( only one file named "spongeforge-1.11.2-2282-6.1.0-BETA-2360.jar" )

Many mobs ( Mainly, iYAMATO's mod mobs) spawn in the fortress. Normally, only zombie pigman, blaze, wither-skeleton, magma cube. Other mobs didn't spawn in the fortress. They spawn out of the fortress. They know where is our spawn point.

I disabled iYAMATO's mod mobs but wither-skeleton was not found. ( I tried to find around 2hours )

**Comment by phit** [comment]
possibly related to https://github.com/SpongePowered/SpongeForge/issues/1643

**Comment by ryantheleach** [comment]
Do you have any more details that would give any more details?

"Normally, only zombie pigman, blaze, wither-skeleton, magma cube. Other mobs didn't spawn in the fortress. They spawn out of the fortress. They know where is our spawn point."

Do you mean that they spawn very far away from the fortresses?

**Comment by phit** [comment]
Judging by [this comment](https://minecraft.curseforge.com/projects/iyamatos-mod?comment=65) from the mod author the mod is not compatible with Biomes O Plenty in 1.11.2, as for the no Wither Skeleton issue, see https://github.com/SpongePowered/SpongeForge/issues/1643.

Closing this for now, let me know if I misunderstood your report and I will reopen.
