### ISSUE TITLE
[1.11.2]Alternate Inventory Issue

### ISSUE THREAD

**Issue by KaleHarris** [SpongePowered/SpongeForge#1572]
- SpongeForge version: The latest version at the time of this writing, 1.11.2-2282-6.1.0-BETA-2360
- Forge version: 13.20.0.2282
- Java version: whatever version of Java minecraft 1.11.2 uses, I'm honestly not sure.
- Operating System: Run on a server through ApexMC hosting with 2 GB RAM.

- Plugins/Mods: 

Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Aether Legacy, Forgelin, Mantle, Tinkers' Construct, TheDragonLib, ArmorPlus, Quark, AutoRegLib, BiblioCraft, Chameleon Creepers, Dynamic Surroundings, Gravestone, Hardcore ORE, Iron Chest, LLibrary, Literal Ascension, MalisisCore, MalisisDoors, MineColonies, ShetiPhian-Core, Multi-Storage, Nucleus, Placeable Items Mod, Rope Bridge, Sophisticated Wolves, Stellar API, Stellar Sky, TamModized, Vein Miner, Mod Support, VoidCraft, Waystones, Wearable Backpacks

So, the only issue that is cropping up here is that when attempting to use Aether Legacy's alternate inventory function, done by clicking a small grey icon, a "fatal error" occurs and kicks said user out of the server. What's odd is that when I look in the console, it obviously displays where the error happens, but it doesn't even log the player disconnecting. But maybe that's unrelated. Anyway, the server is still fine after this happens.

**What is the expected result?**
You open your alternate inventory to use Aether I related cosmetics and items. Screenshot below. The button for doing this is the small circular grey one near my character.

![2017-06-05_22 00 07](https://cloud.githubusercontent.com/assets/26660001/26813505/e91098ea-4a3b-11e7-8016-03a53428f2bb.png)

**What is the current result?**
As stated before, the game tells me a "fatal error" occurred and that my connection was terminated. I know that this is the result of sponge being installed because I tried this without sponge (and, accordingly, Nucleus) and it worked just as normal. Below is a screenshot of the relevant console entries pertaining to where the error happened at sponge. I could not provide a full log because as I said, the server didn't crash, so there was no log to download. All I can provide is the error message and the related info the console provided.

![screenshot 7](https://cloud.githubusercontent.com/assets/26660001/26813569/54b59b72-4a3c-11e7-9edc-355d00c070d1.png)

**Comment by Zidane** [comment]
@Faithcaio 

Get this resolved please.

**Comment by Faithcaio** [comment]
This might be fixed in the latest version
@Leafygreens97 if you could test again.

**Comment by KaleHarris** [comment]
Sorry for the late response, but unfortunately no, it wasn't fixed. I took a screenshot of the new console entries, and I am including the rest of the error message this time even though they don't mention sponge at all.

Edit: I am using sponge version 1.11.2-2315-6.1.0-BETA-2318

Top half:

![screenshot 8](https://user-images.githubusercontent.com/26660001/27364957-b5f7ca80-55fa-11e7-8ef5-d8be5bde00bd.png)

Bottom half: (first line of text is part of top half)

![screenshot 9](https://user-images.githubusercontent.com/26660001/27364972-c60f64be-55fa-11e7-8e00-df11f47d08c7.png)

**Comment by Faithcaio** [comment]
ok please try again with latest build.

**Comment by KaleHarris** [comment]
Ok, confirmed working correctly. Thanks for your help!
