### ISSUE TITLE
Inventory Issue 

### ISSUE THREAD

**Issue by Keaton1188** [SpongePowered/SpongeForge#1573]
Hi all, we recently updated to SpongeForge: 1.10.2-2281-5.2.0-BETA-2363 and this caused issues with items dropping out of inventories, picking up stacks of items in your inv or any item and dropping it out your inv it will clear and not drop. Pressing Q to throw an item out is fine.

With SpongeForge: 1.10.2-2281-5.2.0-BETA-2361 this is not an issue, hope it can be fixed soon :)

**Comment by EmanYm** [comment]
Do you have NEI/JEI installed?
I can't remember which one, but if you drop items out the right side of your 'e' screen it is the same as a trash can.
