### ISSUE TITLE
SpongeForge-2360 Incompatible with SinglePlayer / Client.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeForge#1576]
**I am currently running...**

- SpongeForge version: spongeforge-1.11.2-2282-6.1.0-BETA-2360
- Forge version: forge-1.11.2-13.20.0.2282
- Java version:  1.8.0_92, Oracle Corporation
- Operating System: Windows 10 (amd64) version 10.0

- Plugins/Mods: 
```
UC	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UC	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2282.jar) 
	UC	forge{13.20.0.2282} [Minecraft Forge] (forge-1.11.2-13.20.0.2282.jar) 
	UC	spongeapi{6.1.0-SNAPSHOT-a15cc3e} [SpongeAPI] (spongeforge-1.11.2-2282-6.1.0-BETA-2360.jar) 
	UC	sponge{1.11.2-2282-6.1.0-BETA-2360} [SpongeForge] (spongeforge-1.11.2-2282-6.1.0-BETA-2360.jar) 
	UC	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
```

**What is the current result?**

Singleplayer doesn't even get past the launch phase.

I'm not using the latest forge due to the incompatibility mentioned here: https://github.com/SpongePowered/SpongeForge/issues/1574

Tried to match sponge & forge versions for maximum compatibility.

https://gist.github.com/ryantheleach/facbc2dd1539f04c076e4e580679021f

**Comment by dualspiral** [comment]
Yeah, that was my fault. @Aaron1011 fixed it on bleeding - but it never got cherry picked to stable-6. I've done that now.

https://github.com/SpongePowered/SpongeForge/commit/b51382c19bf1fac37d49ac15ddfbe43c2bf0a676

**Comment by ryantheleach** [comment]
Thanks dual.
