### ISSUE TITLE
[1.11.2] FTB Utilities Anti-Explosion option doesn't work with Sponge

### ISSUE THREAD

**Issue by Autopoietico** [SpongePowered/SpongeForge#1578]
**I am currently running...**
- SpongeForge version: spongeforge-1.11.2-2282-6.1.0-BETA-2343
- Forge version: forge-1.11.2-13.20.0.2304-universal
- Java version: 1.8.0_121
- FTB Utilities: FTBUtilities-1.1x-3.6.5
- Operating System:
 - [x] Ubuntu Linux
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: 
 - compatlayer-1.11.2-0.2.8.jar
 - FTBLib-1.1x-3.6.5.jar

**What is the expected result?**

Claimed chunks by a team ban explosions for creepers, ghast, wither heads, tnt, etc.

**What is the current result?**

Despite activating the option, creepers, ghast, whiter heads, tnt and other explosive entities cause destruction in claimed chunks.

**Comment by phit** [comment]
confirmed with 7.0.0-BETA-2729 and FTBUtilities-4.2.2, FTBLib-4.2.3

**Comment by phit** [comment]
Should be fixed by https://github.com/SpongePowered/SpongeForge/pull/1911, please reply if this is still an issue after updating to 2832+
