### ISSUE TITLE
Bug with GP and zz-backpacks

### ISSUE THREAD

**Issue by iLefty** [SpongePowered/SpongeForge#1579]
Hello! I discovered a method of stealing, using zz-backpacks mod. Here's a video:
https://youtu.be/oOqCJOmiTZ0
Will this be fixed?
My players steal items, I do not know what I must do. I have 12 banned players...
This is flags in claim:
https://cdn.discordapp.com/attachments/215593150494801930/322751436024971265/unknown.png
https://cdn.discordapp.com/attachments/215593150494801930/322751459701817344/unknown.png
This is versions:
    Minecraft: 1.10.2
    SpongeAPI: 5.2.0-SNAPSHOT-ab52c0c
    SpongeForge: 1.10.2-2281-5.2.0-BETA-2371
    Minecraft Forge: 12.18.3.2316
Running LuckPerms v3.2.12 by Luck.
griefprevention-1.10.2-2.3.1.295
Please, fix this soon, if you can!

**Comment by FiveEYZ** [comment]
you should really update forge, you have 2272. 

update to at least 2281+

**Comment by HeberonYT** [comment]
I have the same problem on my server 1.10.2 and I am using the latest versions.
SpongeForge: 1.10.2-2281-5.2.0-BETA-2379
Forge: 12.18.3.2281
Mod: zz-backpacks 1.10.2 - 3.1.5.jar

**Comment by iLefty** [comment]
@HeberonYT 
I fixed it, when set in zz-backpack config:
disable_custom_block_interfaces=true
And set another interfaces on true.
