### ISSUE TITLE
[1.11.2] Error activating TileEntity-Activation

### ISSUE THREAD

**Issue by FiveEYZ** [SpongePowered/SpongeForge#1580]
**I am currently running...**

- SpongeForge version: spongeforge-1.11.2-2282-6.1.0-BETA-2375
- Forge version: forge-1.11.2-13.20.0.2310-universal
- Java version: 1.8.0_131
- Operating System:

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows Server 2012 R2 

- Plugins/Mods: 

**What is the expected result?**
no failure

**What is the current result?**
Setting it to true in config renders server unable to start

https://gist.github.com/FiveEYZ/8b2e55d31001368680eb5417d004d9c5

**Comment by FiveEYZ** [comment]
Any update on this?
made a new test with ONLY forge, sponge and `tileentity-activation=true`:
-  SpongeForge version: spongeforge-1.11.2-2315-6.1.0-BETA-2410
-  Forge version: forge-1.11.2-13.20.0.2366-universal
-  Java version: 1.8.0_131

https://gist.github.com/FiveEYZ/ee22edcf0071b5094c0c263833b2c871

edit:
was editing a comment i stared some days ago, it now have the right SpongeForge version

**Comment by gabizou** [comment]
Mismatched forge version for sponge forge. More than likely forge has changed something. Re-test with the CORRECT version of forge that sponge forge was built with (in this case 2315) and re-test.

**Comment by FiveEYZ** [comment]
as requested:
a log with proper versions used https://gist.github.com/FiveEYZ/5dcbc74575f1dcd0e923a50c50020a88
