### ISSUE TITLE
1.10.2 strange error

### ISSUE THREAD

**Issue by mkrtes** [SpongePowered/SpongeForge#1581]
- SpongeForge version: spongeforge-1.10.2-2281-5.2.0-BETA-2344
- Forge version: 12.18.3.2297
- Java version: 8
- Operating System: 
 - [x] Linux (Ubuntu, Debian, Fedora, etc)

I don't know what happened. The server crashed with this error. Restart did force.
Spread just like that, maybe it will help in the development.
Error log https://pastebin.com/eHR0Ewx6
Full log more than 10mb, If necessary, provide.

**Comment by bloodmc** [comment]
@mkrtes Update SF to latest.
