### ISSUE TITLE
FTBUtilities buttons broken

### ISSUE THREAD

**Issue by HeberonYT** [SpongePowered/SpongeForge#1582]
**I am currently running...**

- SpongeForge version: 1.10.2-2281-5.2.0-BETA-2366
- Forge version: 12.18.3.2281
- Java version: 1.8.0_111
- Operating System:

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: 
FTBLib-1.1x-3.6.5
FTBUtilities-1.1x-3.6.5
**What is the expected result?**
I use the mod ftbUtilities to protect chunks on public servers, the mod must place buttons on the left side of the inventory gui to open the interface.
**What is the current result?**
When installing sponge, the FTBUtilities buttons are not displayed, all indications are that the mod is loading on the server, but the buttons do not appear in the inventory gui.
I read that previously this error had been reported, and the affected user solved it by updating spone. I have already downloaded the latest version available so far from both sponge and FTBUtilities and is not solved.

Server Log: https://pastebin.com/raw/1zL4Efij

**Comment by EmanYm** [comment]
You are using SpongeForge for Minecraft 1.10.2 and FTBu for Minecraft 1.11.2
You should either upgrade Sponge or downgrade FTBu

**Comment by HeberonYT** [comment]
Hello @EmanYm 
Let me correct your comment. The version I'm using applies to 1.10.2
Here is the evidence.
![screenshot_2](https://user-images.githubusercontent.com/13698597/27161789-4d831eb6-5143-11e7-8ff5-f2538d0980d3.png)

In addition to that, I comment that you already use previous versions and they did not work either.

**Comment by EmanYm** [comment]
That's what I get for only looking at the first matching version numbers...I am hereby corrected.

**Comment by HeberonYT** [comment]
**Additional information**: mod ftb utilities is loading correctly on the server, because the map backup is being performed normally, and that is a characteristic of the mod. It seems that the problem of the buttons to protect, is only visual.

**Comment by phit** [comment]
You need to OP yourself for them to show up, if you have a perms plugin `/op` will be disabled so you have to use `/minecraft:op <yourname>`.

**Comment by Zidane** [comment]
Closing as this isn't a Sponge issue and a fix is provided by @phit .
