### ISSUE TITLE
Failed to handle packet: java.util.NoSuchElementException: packet_handler

### ISSUE THREAD

**Issue by BrainStone** [SpongePowered/SpongeForge#1584]
When a Vanilla client connects to a server which only has mods which would allow a vanilla connection I get this exception:

https://pastebin.com/ivPnaR94

**I am currently running...**

- SpongeForge version: 1.12-2321-7.0.0-BETA-2386
- Forge version: 1.12-14.21.0.2324
- Java version: 1.8_131
- Operating System: Linux Debian
- Plugins/Mods: 
Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, OpenEye, SpongeAPI, SpongeForge, Broadcast, BungeeTabListPlus-SpongeBridge, EconomyLite, FastAsyncWorldEdit, WorldEdit, FoxCore, FoxGuard, Inventory Sync, Latch, LuckPerms, MMCTickets, ModBanner, Nucleus, NuVotifier, PayDay, Prism, VotifierListener, SkinsRestorer, SleepVote, Just Enough Items, Journeymap

**What is the expected result?**

That a vanilla client can connect.

**What is the current result?**

The client cannot connect due to the exception above.

*If required I'll recreate this error for a full log, as I don't have one left*

**Comment by ryantheleach** [comment]
Is there any more to this error message? It looks like it cuts off right before any useful details appear.

**Comment by ryantheleach** [comment]
Does this happen without SpongeForge, using only the forge mods?

**Comment by BrainStone** [comment]
@Mysticdrew tested it and it worked without SpongeForge @ryantheleach  
That's why he redirect me to here.

**Comment by BrainStone** [comment]
EDIT: Further test from @mysticdrew revealed it's not a SF issues as he can reproduce it on Forge 1.12.
