### ISSUE TITLE
Mod Incompatibility

### ISSUE THREAD

**Issue by HeberonYT** [SpongePowered/SpongeForge#1585]
**I am currently running...**

- SpongeForge version: 1.10.2-2281-5.2.0-BETA-2379
- Forge version: 12.18.3.2281
- Java version: 1.8.0_111
- Operating System:

 - [x] Linux (Ubuntu, Debian, Fedora, etc)

- Plugins/Mods: 
compatlayer-1.10-0.2.9.jar
ElecCore-1.10.2-1.7.421.jar
elementaldimensions-0.1.2.jar

**What is the expected result?**
The mod element dimensions adds different worlds to minecraft, requires two dependencies to function, the same ones that are already added, so the server should start without any problem.

**What is the current result?**
Currently the server begins to generate the new world but remains stuck in the attempt. It never finishes generating and I must close the server by brute force.
If I remove sponge, then the server runs smoothly. I suppose this is because sponge manages the dimensions differently, and the mod does not support it.

Server Log: https://pastebin.com/raw/Eu1whKf7

Additionally, I want to show that this is the console all the time.
![screenshot_9](https://user-images.githubusercontent.com/13698597/26851030-444aa92e-4acf-11e7-9699-21c1f4fd55d4.png)

**Comment by Zidane** [comment]
Turn off async-lighting in global.conf and try again.

**Comment by HeberonYT** [comment]
Hello! What is the location of the file that I have to modify?

**Comment by Zidane** [comment]
It is in config/sponge/global.conf

**Comment by bloodmc** [comment]
Unable to reproduce with a fresh install using latest builds.
