### ISSUE TITLE
Crash after creeper explosion (1.10.2)

### ISSUE THREAD

**Issue by mkrtes** [SpongePowered/SpongeForge#1586]
**I am currently running...**
- SpongeForge version: 1.10.2-2281-5.2.0-BETA-2353
- Forge version: 12.18.3.2297
- Java version: 8
- Operating System:
 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows
- Plugins/Mods: FTB Beyond mod-pack
Plugins (182): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, Applied Energistics 2 Core, Aroma1997Core, Not Enough Items, OpenComputers (Core), SpongeAPI, SpongeForge, CoFH ASM, ccl-entityhook, CoFH Core, Actually Additions, AdminShop, IndustrialCraft 2, Advanced Machines, Advanced Solar Panels, Applied Energistics 2, BD Lib, AE2 Stuff, InfinityLib, AgriCraft, Baubles, Botania, Akashic Tome, Just Enough Items, AppleSkin, Aquaculture, ArchitectureCraft, Aroma1997Core|Helper, Aroma1997's Dimensional World, AromaBackup, AromaBackup Recovery, AutoBroadcaster, Morph-o-Tool, Psi, Quark, AutoRegLib, Bed Bugs, Better Builder's Wands, BiblioCraft, Guide-API, Blood Magic: Alchemical Wizardry, Blood Arsenal, Bookshelf, CodeChicken Lib, Brandon's Core, BungeeTabListPlus-SpongeBridge, Ceramics, Chameleon, Chest Transporter, Chisel, ShadowMC, Clipboard, CodeChicken Core, Compact Solar Arrays, Cooking for Blockheads, CraftTweaker JEI Support, MineTweaker 3, Dark Utilities, Forestry, ElecCore, EnderStorage, OpenComputers, DeepResonance, Draconic Evolution, EconomyLite, Elevator Mod, Embers, EnderCore, Ender IO, Engineers Workshop, Valkyrie Lib, Environmental Tech, ET Lunar, Extra Utilities 2, Zero CORE, Extreme Reactors, SonarCore, FluxNetworks, FoamFix, Forgelin, Forge Multipart CBE, Forge Microblocks, Minecraft Multipart Plugin, MCMultiPart, FTBLib, FTBUtilities, Funky Locomotion, Funnels, GenDustry, Gravestone, Gravitation Suite, GriefPrevention, Hammer Core, HelpFixer, Hopper Ducts, Mantle, Tinkers' Construct, The One Probe, Immersive Engineering, LunatriusCore, InGame Info XML, Interaction Wheel, Inventory Tweaks, Iron Backpacks, Iron Chest, JEI Bees, KleeSlabs, Long Fall Boots, LuckPerms, MalisisCore, MalisisDoors, Mercurius, Modular ForceField System, mob_grinding_utils, MTLib, Mod Tweaker, Railcraft, More Bees, ModPack Utilities, ModPack Basic Tools, MrTJPCore, ShetiPhian-Core, Multi-Storage, Natura, Nether Portal Fix, Nucleus, NuVotifier, Open Glider, p455w0rd's Library, Pam's HarvestCraft, ProjectRed Core, ProjectRed integration, ProjectRed Transmission, ProjectRed Illumination, ProjectRed Expansion, ProjectRed Transportation, ProjectRed Exploration, RebornCore, QuantumStorage, Ranged Pumps, reborncore-MCMultiPart, Thermal Foundation, Redstone Arsenal, Refined Relocation, Storage Drawers, Refined Storage, Reliquary, RFTools, RFTools Control, RFTools Dimensions, Roots, SeriousVote, Signals, SimpleVoidWorld, Simple Retrogen, Simply Jetpacks 2, Sleeping Bag, Snad, Solar Flux Reborn, Steve's Carts 2, Storage Drawers Extras, Super Circuit Maker, Super Crafting Frame, TechReborn, Thermal Expansion, Tinkers Tool Leveling, TOP Addons, TorchMaster, Translocator, Useful Nullifiers, VirtualChest, WanionLib, Wireless Crafting Grid, Wireless Crafting Terminal 2, Woot, WirelessRedstone-CBE, XNet, YABBA, UniDict

**What is the expected result?**
Kaboooom!
**What is the current result?**
Crash-report: https://pastebin.com/mWJv70bY

**Comment by Zidane** [comment]
Can you re-upload your log? If no response I'll assume that this is resolved.

**Comment by Zidane** [comment]
Wrong copy-paste. Awaiting log re-upload.

**Comment by mkrtes** [comment]
Unfortunately, this log is lost. This problem no longer occurs.
