### ISSUE TITLE
[1.10.2] Crash "Don't know how to add class"

### ISSUE THREAD

**Issue by iLefty** [SpongePowered/SpongeForge#1587]
Hello Sponge dev! 
My server suffered a disaster. It turns off for a reason that I do not understand. There are crash logs, which fully describe the information about the mods, their versions and about the Sponge version.
I'm sure you will say "check without Sponge", but I can not do this. Crash appears when there is a high online, and without Sponge players will not be on server. Therefore, I can not check.
Crash logs there: 
https://pastebin.com/RXRrHjDk
https://pastebin.com/E2Q5tYKW
https://pastebin.com/aXjErjjx
https://pastebin.com/3WrQVRCw

**Comment by Zidane** [comment]
Unfortunately the issues you're posting have nothing to do with Sponge. You have to test without it otherwise we simply cannot help you.
