### ISSUE TITLE
Multiple entries with the same key

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeForge#1588]
I found another issue but it was related to heads, this one looks to be related to a random skeleton... When a specific player logs in (and loads the entity), the server crashes. Crash-report: https://hastebin.com/yujowigefa.sql

**I am currently running...**
    Minecraft: 1.11.2
    SpongeAPI: 6.1.0-SNAPSHOT-a15cc3e
    SpongeForge: 1.11.2-2315-6.1.0-BETA-2381
    Minecraft Forge: 13.20.0.2298
    Java8u121
    Operating System: Alpine (Linux)

- Plugins/Mods: 

Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, IvToolkit, Micdoodle8 Core, OpenComputer
s (Core), SpongeAPI, SpongeForge, FoamFixCore, ccl-entityhook, animalium, Quark, Animania, Psi, AutoRegLib, Baubles, BetterChunkLoader, Biomes O' Plenty, Bota
nia, Chameleon, CodeChicken Lib, CraftTweaker JEI Support, Just Enough Items, Crafttweaker, Embers, EnderStorage, ShetiPhian-Core, EnderTanks, Ender Zoo,  Fas
tAsyncWorldEdit, WorldEdit, FoamFix, IndustrialCraft 2, Forestry, Galacticraft Core, Galacticraft Planets, Gravestone Mod, GriefPrevention, The One Probe, Imm
ersive Engineering, Immersive Petroleum, Inventory Tweaks, JourneyMap, Just a Few Fish, Kai's Commons, LuckPerms, MagiChat, Nucleus, OpenComputers, Pam's Harv
estCraft, Personal Cars, Platforms, Player Glow, Reborn Core, reborncore-MCMultiPart, Recurrent Complex, Refined Storage, Roots 2, SignEditor, SimpleAntiAFK, 
Steve's Carts 2, Storage Drawers, TabManager, Wolf Armor and Storage

Full log: https://gist.github.com/Eufranio/bf3083c148518702237b789e43c98aa8
Cause-tracker error that happens when **removeErroringEntities** is disabled and the skeleton fires an arrow to a player: https://hastebin.com/kiwusasequ.md

**Comment by Eufranio** [comment]
Enabling **removeErroringEntities** is a workaround, but this still a issue when the option is disabled.

**Comment by ryantheleach** [comment]
@Eufranio Your first hastebin has been removed? 
`java.lang.IllegalArgumentException: Multiple entries with same key: `
```
  DamageModifier{
    type=SpongeDamageModifierType{id=armor_enchantment, name=Armor Enchantment}, 
    cause=Cause[
      {Name=ArmorEnchantment, Object={Enchantment{Name=enchantment.protect.all, Id=minecraft:protection}}}, 
      {Name=ItemStack, Object={SpongeItemStackSnapshot{itemType=ItemArmor{Name=helmetChain}, count=1}}}, 
      {Name=Source, Object={EntitySkeleton['Skeleton'/23833, l='world', x=192.55, y=69.41, z=-2173.32]}}
    ],
    contributing=null
  } = -0.3223999999999996 
```
and 
```
  DamageModifier{
    type=SpongeDamageModifierType{id=armor_enchantment, name=Armor Enchantment}, 
    cause=Cause[
      {Name=ArmorEnchantment, Object={Enchantment{Name=enchantment.protect.all, Id=minecraft:protection}}}, 
      {Name=ItemStack, Object={SpongeItemStackSnapshot{itemType=ItemArmor{Name=helmetChain}, count=1}}}, 
      {Name=Source, Object={EntitySkeleton['Skeleton'/23833, l='world', x=192.55, y=69.41, z=-2173.32]}}
    ], 
    contributing=null
  } = -0.48360000000000003
```

They appear to be identical other then value.

Is the player wearing this armor, or the skeleton? Strange they have 2 different values being calculated.

**Comment by Eufranio** [comment]
The sekeleton was wearing the armor, and yea hastebins seem to be deleted after 1 month, but the log still there. I could fix by killing myself the skeleton, so I dont think I can reproduce again (this crash popped up at least 5 times in different days and skeletons this month).

**Comment by phit** [comment]
@Aaron1011 assigned you because I closed the duplicate issue for this

here's the log from the other issue https://gist.github.com/phit/2f2c8e913692a4d0e5aea5a9a5338746

see also https://github.com/SpongePowered/SpongeForge/issues/1783 & https://github.com/SpongePowered/SpongeVanilla/issues/307

**Comment by phit** [comment]
just got this again with spongeforge-1.12.2-2529-7.0.0-BETA-2730

https://gist.github.com/phit/a649f5f2c7103600e777beea1f01f5e2

**Comment by ryantheleach** [comment]
This is due to Sponge making assumptions about something that is possible under Vanilla due to what is probably a bug. 

Under some conditions, mobs will spawn with the protection enchantment twice on a single piece of armor.

Moved to SpongeCommon
