### ISSUE TITLE
[1.11.2] Server Crash

### ISSUE THREAD

**Issue by ziceptor** [SpongePowered/SpongeForge#1590]
[crash-2017-06-17_04.41.49-server.txt](https://gist.github.com/ziceptor/c564b9910730f063bd6b3c4e12ae8d53)
[fml-junk-earlystartup.log](https://gist.github.com/ziceptor/8f6bad3a7be259f940d984f45a498f90)
[fml-server-latest.log](https://gist.github.com/ziceptor/73a6bf23af38e570a723ab0b22415f82)
[latest.log](https://gist.github.com/ziceptor/e159282c6edf5015feeb03ae0dfae195)

Update from
```
forge-1.11.2-13.20.0.2282-universal.jar
spongeforge-1.11.2-2227-6.0.0-BETA-2275.jar
```
to
```
forge-1.11.2-13.20.0.2315-universal.jar
spongeforge-1.11.2-2315-6.1.0-BETA-2388.jar
```
no mods/plugins

**Comment by Faithcaio** [comment]
please try with the latest version again
could be fixed with https://github.com/SpongePowered/SpongeCommon/commit/de9c49c2de6908861a697e79481ef1593892329f

**Comment by ziceptor** [comment]
@Faithcaio 
forge-1.11.2-13.20.0.2315-universal.jar
spongeforge-1.11.2-2315-6.1.0-BETA-2395.jar latest version?

[crash-2017-06-18_01.11.14-server.txt](https://gist.github.com/ziceptor/df0ed5e4b6318b07f2ee40013cc49a24)
[fml-junk-earlystartup.log](https://gist.github.com/ziceptor/47972e3a206783cc826a02e5fbab0677)
[fml-server-latest.log](https://gist.github.com/ziceptor/ca165efdea0a999455a64e41b54de613)
[latest.log](https://gist.github.com/ziceptor/29820fa32509ae076ba4cd99bc12dfc8)

**Comment by Faithcaio** [comment]
You got some old custom data from plugins left in there: `io.github.hsyyid.commandsigns.data.iscommandsign.SpongeIsCommandSignData`

With the next build it should no longer crash.

**Comment by ziceptor** [comment]
@Faithcaio 
> With the next build it should no longer crash.

Sponge? Commandsigns?

**Comment by Faithcaio** [comment]
Sponge. You should only an error including stacktrace about the old data (once per dataclass per serverstart)

**Comment by ziceptor** [comment]
@Faithcaio Works. Thank you!
