### ISSUE TITLE
Sponge plugin error

### ISSUE THREAD

**Issue by johnfg2610** [SpongePowered/SpongeForge#1594]
**I am currently running...**
- SpongeForge version: 1.11.2-2315-6.1.0-BETA-2395
- Forge version: 2315
- Java version: 1.8.0_111
- Operating System:debian(i think)

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: 
Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Aroma1997Core, Micdoodle8 Core, OpenEye, Backpacks!, CoFH ASM, FoamFixCore, ccl-entityhook, Actually Additions, Baubles, CoFH Core, extrautils2, AngelRing 2 Bauble, Animal Bikes, AppleCore, Just Enough Items, AppleSkin, Armor Overlay, Shadowfacts' Forgelin, Mantle, Chisel, Tinkers' Construct, TESLA, TheDragonLib, ArmorPlus, Aroma1997Core|Helper, Aroma1997sDimension, Astral Sorcery, Psi, Quark, AutoRegLib, BD Lib, Bed Bugs, Bedrock-B-Gone, Better Achievements, Better Builder's Wands, BiblioCraft, Biomes O' Plenty, BiblioWoodBoP, Natura, BiblioWoodNatura, Cyclic, Guide-API, Blood Magic: Alchemical Wizardry, Bookshelf, Bookshelf, Botania, SonarCore, Calculator, MrCrayfish's Furniture Mod, Chameleon, CodeChicken Lib, ChickenChunks, Chisels & Bits, IndustrialCraft 2, Compact Solar Arrays, Computality, Cooking for Blockheads, CraftTweaker JEI Support, Crafttweaker, CXLibrary, Cyberware, Cyclops Core, Dark Utilities, ElecCore, DeepResonance, Storage Drawers, Drawers & Bits, Elevator Mod, Embers, EnderStorage, Ender Utilities, Ender Zoo, Valkyrie Lib, Environmental Tech, EvilCraft, Zero CORE, Extreme Reactors, EZStorage 2, Fire's Random Things, FL, FluxNetworks, FoamFix, Not Enough Items, FTBLib, Galacticraft Core, Galacticraft Planets, Advanced Generators, GlareTorch, Gravestone Mod, Grue, Hammer Core, Hardcore Darkness, Hardcore ORE, HelpFixer, Tesla Core Lib, Industrial Foregoing, MTLib, InitialInventory, Inventory Pets, Inventory Tweaks, Iron Chest, JourneyMap, Just JetPacks, LimeLib, Mana Wells, Mekanism, MekanismGenerators, MekanismTools, Metamorph, Mike Dongles, examplemod, Missing Pieces, MmmMmmMmmMmm, mob_grinding_utils, Mod Tweaker, Mysterious Miscellany, Mystical Agriculture, NoMoreRecipeConflict, NotEnoughIDs, Not Enough Wands, NuclearCraft, OMLib, Open Modular Turrets, Ore Control, Ore Dictionary Converter, OreExcavation, Overloaded, Pam's HarvestCraft, Quick Leaf Decay, Random Utilities, Random Things, Ranged Pumps, Reborn Core, reborncore-MCMultiPart, Thermal Foundation, Thermal Expansion, Redstone Arsenal, Redstone Paste, Refined Storage, Reliquary, RFTools, Roguelike Dungeons, Roots 2, Rough Mobs, Sampling Performance Profiler, Silent Lib, Silent's Gems, Simple Teleporters, Simply Conveyors & More, SlashBlade, Slurpie's Dongles, Solar Flux Reborn, Soul Shards - The Old Ways, The Spice of Life, Steve's Carts 2, Super Crafting Frame, The One Probe, Thermal Dynamics, TickProfiler, Tinkers Tool Leveling, Tiny Progressions, TOP Addons, TorchMaster, Translocator, Transprot, Woot, XNet, BetterChunkLoader, Buycraft, Can I Join Now?, CatClearLag, Discord Bridge, GriefPrevention, LuckPerms, Morpheus, Nucleus, NuVotifier, PlayerShopsRPG, WorldEdit, denseores

**What is the expected result?**
no errors should be thrown and are thrown in my test version
**What is the current result?**
current error:
```
17.06 22:54:51 [Server] INFO Exception in thread "pool-22-thread-69" [22:54:51] [pool-22-thread-69/INFO]: [STDERR]: java.lang.IllegalArgumentException: Unable to translate object to JSON: [I@15b5769
17.06 22:54:51 [Server] pool-22-thread-69/INFO [STDERR]: 	at org.spongepowered.common.data.persistence.JsonDataFormat.write(JsonDataFormat.java:223)
17.06 22:54:51 [Server] pool-22-thread-69/INFO [STDERR]: 	at org.spongepowered.common.data.persistence.JsonDataFormat.writeMap(JsonDataFormat.java:245)
17.06 22:54:51 [Server] pool-22-thread-69/INFO [STDERR]: 	at org.spongepowered.common.data.persistence.JsonDataFormat.write(JsonDataFormat.java:217)
17.06 22:54:51 [Server] pool-22-thread-69/INFO [STDERR]: 	at org.spongepowered.common.data.persistence.JsonDataFormat.writeMap(JsonDataFormat.java:245)
17.06 22:54:51 [Server] pool-22-thread-69/INFO [STDERR]: 	at org.spongepowered.common.data.persistence.JsonDataFormat.write(JsonDataFormat.java:217)
17.06 22:54:51 [Server] pool-22-thread-69/INFO [STDERR]: 	at org.spongepowered.common.data.persistence.JsonDataFormat.writeMap(JsonDataFormat.java:245)
17.06 22:54:51 [Server] pool-22-thread-69/INFO [STDERR]: 	at org.spongepowered.common.data.persistence.JsonDataFormat.write(JsonDataFormat.java:217)
17.06 22:54:51 [Server] pool-22-thread-69/INFO [STDERR]: 	at org.spongepowered.common.data.persistence.JsonDataFormat.writeMap(JsonDataFormat.java:245)
17.06 22:54:51 [Server] pool-22-thread-69/INFO [STDERR]: 	at org.spongepowered.common.data.persistence.JsonDataFormat.write(JsonDataFormat.java:217)
17.06 22:54:51 [Server] pool-22-thread-69/INFO [STDERR]: 	at org.spongepowered.common.data.persistence.JsonDataFormat.writeView(JsonDataFormat.java:199)
17.06 22:54:51 [Server] pool-22-thread-69/INFO [STDERR]: 	at org.spongepowered.common.data.persistence.JsonDataFormat.writeTo(JsonDataFormat.java:176)
17.06 22:54:51 [Server] pool-22-thread-69/INFO [STDERR]: 	at com.amict.blockmonitor.api.Record.submitToDatabase(Record.java:176)
17.06 22:54:51 [Server] pool-22-thread-69/INFO [STDERR]: 	at com.amict.blockmonitor.api.RecordBuilder.run(RecordBuilder.java:121)
17.06 22:54:51 [Server] pool-22-thread-69/INFO [STDERR]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
17.06 22:54:51 [Server] pool-22-thread-69/INFO [STDERR]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
17.06 22:54:51 [Server] pool-22-thread-69/INFO [STDERR]: 	at java.lang.Thread.run(Thread.java:745)
17.06 22:54:51 [Server] pool-22-thread-69/INFO [STDERR]: 	Suppressed: java.io.IOException: Incomplete document
17.06 22:54:51 [Server] pool-22-thread-69/INFO [STDERR]: 		at com.google.gson.stream.JsonWriter.close(JsonWriter.java:527)
17.06 22:54:51 [Server] pool-22-thread-69/INFO [STDERR]: 		at org.spongepowered.common.data.persistence.JsonDataFormat.writeTo(JsonDataFormat.java:177)
17.06 22:54:51 [Server] pool-22-thread-69/INFO [STDERR]: 		... 5 more
17.06 22:54:51 [Server] INFO Exception in thread "pool-22-thread-70" [22:54:51] [pool-22-thread-70/INFO]: [STDERR]: net.minecraft.util.ReportedException: Saving entity NBT
17.06 22:54:51 [Server] pool-22-thread-70/INFO [STDERR]: 	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1728)
17.06 22:54:51 [Server] pool-22-thread-70/INFO [STDERR]: 	at net.minecraft.entity.Entity.toContainer(Entity.java:5716)
17.06 22:54:51 [Server] pool-22-thread-70/INFO [STDERR]: 	at com.amict.blockmonitor.api.Record.writeUser(Record.java:145)
17.06 22:54:51 [Server] pool-22-thread-70/INFO [STDERR]: 	at com.amict.blockmonitor.api.RecordBuilder.dealWithEntityType(RecordBuilder.java:37)
17.06 22:54:51 [Server] pool-22-thread-70/INFO [STDERR]: 	at com.amict.blockmonitor.api.RecordBuilder.run(RecordBuilder.java:116)
17.06 22:54:51 [Server] pool-22-thread-70/INFO [STDERR]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
17.06 22:54:51 [Server] pool-22-thread-70/INFO [STDERR]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
17.06 22:54:51 [Server] pool-22-thread-70/INFO [STDERR]: 	at java.lang.Thread.run(Thread.java:745)
```

this does not happen on the test version and even disabling the multithreaded part of the plugin makes no difference 

plugin src: https://github.com/Dawn-MC/BlockMonitor

**Comment by Zidane** [comment]
Report to the plugin author. The JSON is malformed. Not a Sponge issue.

**Comment by johnfg2610** [comment]
I am the plugins developer and this isn't a plugin issue. Im using data formats to go from for example block snapshot to json and it works on certain servers and not others(works during testing and on our "near vanilla" server but not on our new frontier server)

**Comment by Zidane** [comment]
@johnfg10 

What you've said makes no sense. It can't just work on one and not another. Check the software running on both boxes and narrow down when it happens. Even with that said, this isn't a Sponge issue else it'd break both servers.

**Comment by ryantheleach** [comment]
@johnfg10 To be specific, as you mentioned block snapshot, narrow it down to a specific tile entity / block type.

It may be that some modded block is behaving differently.

**Comment by tyler489** [comment]
I installed the plugin on the server and before any players joined it was throwing that error and he reported it here. On the vanilla no mod server it works fine.
