### ISSUE TITLE
Hello , My server keeps crashing maybe you guys can tell me why

### ISSUE THREAD

**Issue by unovalegends** [SpongePowered/SpongeForge#1597]
**I am currently running...**

- SpongeForge version: 1.10.2-2281-5.2.0-BETA-2401 
- Forge version: forge-1.10.2-12.18.3.2185-universal.jar
- Java version: 
- Operating System:

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows

- Plugins/Mods: 

**What is the expected result?**

**What is the current result?**

https://pastebin.com/pg6iMJ6s

**Comment by Zidane** [comment]
Its a bug that happens, sometimes, with the async lighting code in Sponge. If persistent, turn it off in global.conf in the config folder.
