### ISSUE TITLE
[1.11.2] Cause for decaying leaves inconsistent between API and Forge implementation

### ISSUE THREAD

**Issue by mikeprimm** [SpongePowered/SpongeForge#1598]
**I am currently running...**

- SpongeForge version: 1.11.2-2315-6.1.0-BETA-2395
- Forge version: 1.11.2-13.20.0.2315
- Java version: 1.8.0-131
- Operating System:

 - [X ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ X] macOS
 - [ ] Windows
- Plugins/Mods: None but test code to expose issue

I have encountered the following apparent inconsistency between the 'NamedCause' definitions for the API, and the corresponding causes being reported for decaying of leaves.  Specifically, the ChangeBlockEvent.Pre events report Cause values including a NamedCause with the string "LeavesDecay", which is not a cause defined within NamedCause (where DECAY is defined as the string "Decay").  Best I can tell, this define (and the "Decay" literal) are not used as NamedCauses - both the Mixins for BlockLeaves and for BlockLog use the inline string literal "LeavesDecay".

I'd suggest that the API define probably should be changed to "LeavesDecay", if for no other reason than the existing value doesn't seem to be relevant for anyone (that is, if you are using it, you're already broken), and anyone who has coded around the behavior is probably doing so by using the "LeavesDecay" literal.  I can provide a PR for this, if this would be helpful.

**Comment by Zidane** [comment]
@bloodmc 

Your thoughts?
