### ISSUE TITLE
[1.10.2] Block breaking spam updating to 2401

### ISSUE THREAD

**Issue by alicheek** [SpongePowered/SpongeForge#1599]
Since updating to 2401 it seems there is some form of debug system in place even though all the debug settings are disabled.

**I am currently running...**
spongeforge-1.10.2-2281-5.2.0-BETA-2401.jar
- SpongeForge version: 
- Forge version: 12.18.3.2297
- Java version:  1.10.2
- Operating System:
 -  Linux (Ubuntu, Debian, Fedora, etc)

Copy of some of the logs regarding the spam:
https://pastebin.com/HPBkih8e

**Comment by bloodmc** [comment]
A mod or plugin is logging this, not SpongeForge. Remove ALL Mods and Plugins and watch it go away.
