### ISSUE TITLE
latest version cofhcore breaks spounge

### ISSUE THREAD

**Issue by kain184** [SpongePowered/SpongeForge#1604]
[crash.log](http://server.jesusfreakserver.com/downloads/crash.log)
This crash is created by mod 	
CoFHCore-1.11.2-4.2.4.9-universal.jar
but not the version prior. I am unsure as to what the cause is just thought you ought to know.

**Comment by fcpwiz** [comment]
I can confirm this.

Also, here is an issue made on CoFH's repo: https://github.com/CoFH/Feedback/issues/299

**Comment by ryantheleach** [comment]
Hmm, @Mumfrey the linked issue shows a private mixin method mixing into a previously private method, that gets transformed to public is apparently causing an error?

I think a heavy handed solution would be to make all overwrites public? Or is there a way to downgrade this to a warning in a Forge environment, where access transforming is expected?

**Comment by phit** [comment]
@gabizou this issue is for 1.11.2 not 1.10.2 so the fix is needed for stable-6 not stable-5

**Comment by fcpwiz** [comment]
@phit I’m running a 1.10.2 server and this issue is present.

**Comment by phit** [comment]
yeah, it is supposed to be fixed for 1.10, download 1.10.2-2281-5.2.0-BETA-2422
my point was the initial report here was for 1.11 where the issue isn't fixed yet, but this issue was closed

**Comment by phit** [comment]
yeah, it is supposed to be fixed for 1.10, download 1.10.2-2281-5.2.0-BETA-2422
my point was the initial report here was for 1.11 where the issue isn't fixed yet, but this issue was closed

**Comment by fcpwiz** [comment]
I'm running SpongeForge version 1.10.2-2281-5.2.0-BETA-2422 and CoFH Core 1.10.2-4.1.8.12-universal but I'm still getting a startup issue.

https://gist.github.com/fcpwiz/90f26ced047ca010de63242b1829b362

**Comment by fcpwiz** [comment]
@gabizou Any idea?

**Comment by BakermanLP** [comment]
I have inital created the issue on CoFH Issue Tracker. Yes, the bug was in 1.11.2 version

**Comment by fcpwiz** [comment]
And the bug is also present in the 1.10.2 version, yes?

**Comment by gigafunk** [comment]
For what its worth, I am still getting startup crash with newest cofh with the version of last version of sponge made to fix this. I am using the spongewrapper if that helps at all. I dont have logs as I am out of the house killing time browsing issues. Can provide if it would help.

**Comment by gabizou** [comment]
@gigafunk provide a log please, I'm looking into the issue, but it's getting increasingly difficult to target the issue when it seems like multiple AT's are in play with our overwrites.

**Comment by gigafunk** [comment]
Im digging through em remotely and cant find a clean one, we tried a million combos of version 2281 forge vs 2316 and with different cofh versions and my partner handled alot of it, with me piping in remotely, researching.. I dont want to waste your time with messy, maybe not the right log. later tonight, i can make clean version with no foamfix, and with forge 2281. lol we run 2316, and for every weird error i swap out the libraries and forge back to 2281. then when its ok I switch back to the new one. I just run it because it fixed a git issue cited with a performance tag, and our server runs pretty close to its limit. But i cant really tell so I just need to leave it at 2281 already.

**Comment by phit** [comment]
@gabizou clean logs with just Sponge and CoFHCore

**1.10.2** - Forge 2281 - Sponge 2422 - CoFHCore-1.10.2-4.1.8.12
https://gist.github.com/phit/3ac13aefac00e3b739aea1ba1b38e627

**1.11.2** - Forge 2315 - Sponge 2410 - CoFHCore-1.11.2-4.2.4.9
https://gist.github.com/phit/fe99b4407c16aba1bc73b7ead0e7efe2

**edit:** the change must be introduced in these commits, this is the timeframe between latest working release and the first release that broke with Sponge

https://github.com/CoFH/CoFHCore/compare/b8e0be6646a1cfb38411ac5ccdaf8947f3609415...0043cbceb446429e5ba5377f25479b262b8f5b22

**Comment by Mumfrey** [comment]
See SpongePowered/Mixin#189 for details, but suffice to say that as far as I'm concerned the current behaviour of Mixin in this instance is **correct**, because allowing this operation to succeed would have some unexpected possibly-unpleasant side-effects.

However I consider that this scenario needs to be accomodated and will add a feature to mixin to allow live adaptation to take place, albeit with a `WARN` level log message emitted in the console to draw attention to the possible unintended side-effects of the "fix".

Frankly this is a perfect case-study for why I personally hate *Access Transformers* so much.

**Comment by tyler489** [comment]
Figured i would report this here. For 1.11.2 https://pastebin.com/h0MzJxjp removing cofh core fixed it but would be nice to be able to use cofh

**Comment by gigafunk** [comment]
You can use the previous version of cofh core...

**Comment by fcpwiz** [comment]
@gigafunk The issue is that the latest version of CoFH Core (the one Sponge has an issue with) is the version the newer releases of CoFH's mods require, including MineFactory Reloaded for 1.10.2.

**Comment by ktole1999** [comment]
you also can not use a previous version for modpacks because King Lemming does not post previous versions on Curse.

**Comment by fcpwiz** [comment]
Using `CoFHCore-1.10.2-4.1.9.13-universal.jar` and `spongeforge-1.10.2-2281-5.2.0-BETA-2424.jar` still results in a crash even with your commit: https://github.com/SpongePowered/SpongeCommon/commit/924c0acecdbae5173bbad164afb9b13f7bf8373a

**Comment by xAlicatt** [comment]
Using `CoFHCore-1.10.2-4.1.9.13-universal.jar` and `spongeforge-1.10.2-2281-5.2.0-BETA-2424.jar`

Crash report not generated, but this is the console output: https://gist.github.com/xAlicatt/5a9db4439b796b0b81e22a74057874b6

**Comment by BakermanLP** [comment]
Sorry to say that, but here seems to be a problem. The complete fml-server-latest.log can be found here: https://pastebin.com/8W2LMZf8
Used versions:
- forge-1.11.2-13.20.0.2315-universal.jar
- spongeforge-1.11.2-2315-6.1.0-BETA-2432.jar
- CoFHCore-1.11.2-4.2.5.11-universal.jar
Nothing else is installed

Michael (aka BakermanLP)

**Comment by gigafunk** [comment]
Just in case its helpful, 1.10.2 works for me, with 189 other mods. I use the sponge wrapper to launch and force sponge to laid first to handle mixins.

**Comment by Whazaaaaa** [comment]
Can confirm @BakermanLP crashlog. I'm getting the same with:
forge-1.11.2-13.20.0.2345-universal
CoFHCore-1.11.2-4.2.4.9-universal
spongeforge-1.11.2-2315-6.1.0-BETA-2432

**Comment by Mumfrey** [comment]
It looks from the log like @gabizou forgot to enable the conform option for the forge mixin set.

**Comment by BakermanLP** [comment]
I can confirm, that the following combination is working now:
- forge-1.11.2-13.20.1.2393-universal.jar
- spongeforge-1.11.2-2315-6.1.0-BETA-2434.jar
- CoFHCore-1.11.2-4.2.5.11-universal.jar

Thank you for the good work.
