### ISSUE TITLE
Insufficent Memory crashes with Spongeforge Insalled, Pixelmon 5.1.1

### ISSUE THREAD

**Issue by yahell1** [SpongePowered/SpongeForge#1608]
I have a Pixelmon server with 6GB of memory to it and I need a mod that can allow me to install plugins and I choose spongeforge-1.10.2-2171-5.1.0-BETA-2010 I have used the latest releases but they just cause my server to go into a continuous restart loop.

What happens is if I start the server it would load up fine, gets to the done part then immediately goes into a restart with only a insufficent memory error coming up and nothing else from what I can see.

**I am currently running...**

- SpongeForge version: spongeforge-1.10.2-2171-5.1.0-BETA-2010
- Forge version: 12.18.3.2185
- Java version: Java 8
- Operating System: Unsure, the server is hosted by [Servercraft](https://servercraft.co/)

- Plugins/Mods: 

Installed Mods:
Pixelmon-1.10.2-5.1.1-universal
Pokestops-1.10.2-1.0.0
Tournaments-1.10.2-2.0.0
PixelExtras-1.10.2-2.2.9-universal
PixelAnnouncer-1.10.2-1.0.3
GTS-1.10.2-2.1.3
Daycare-1.10.2-1.0.0
AnotherGymPlugin-1.10.2-0.5.0-beta

Installed Plugins:
BuycraftX
CatClearLag-0.7.1
LuckPerms-Sponge-3.2.30
Nucleus-1.0.0-1.10.2-S5.1-plugin

**What is the expected result?**
Expected?, I expected the server to start normally, In the past the server has been extremly laggy I assumed it was a mod so I started looking into it buy removing plugins that did not change anything, I removed spongeforge and the server too off and the issues stopped so I tried a earlier version one that is closer to pixelmons forge version and the server worked for a while until it crashed.

Currently, after the last server crash I cannot get the server to start again there was no warning or any reason why the crash would of occoured from what I can tell it just crashed and now when I try to restart (even a hard restart) it will simply startup, finish its startup and immediatly spit a memory error and into a restart, sometimes when it restarts it will not even finish booting it will stop at a memory error on the log.

After the last restart loop it spat out this file in the root directory of the minecraft folder
[Memory error crash report](https://pastebin.com/Rybxdde2)  https://pastebin.com/Rybxdde2

And this is a zip file with all the latest logs from the server, but my knowledge of minecraft is not at the point of understanding these logs
[Logs.zip](https://github.com/SpongePowered/SpongeForge/files/1107758/Logs.zip)

**Comment by Zidane** [comment]
You state that you've allocated 6GB of Memory but the server is unable to allocate that much:

There is insufficient memory for the Java Runtime Environment to continue.
Native memory allocation (mmap) failed to map 616562688 bytes for committing reserved memory.
Possible reasons:
The system is out of physical RAM or swap space

Not a Sponge issue beyond the fact that adding additional mods will increase memory usage. I would investigate why you can't allocate the 6GB.
