### ISSUE TITLE
world/data/scoreboard.dat not updated when using SpongeForge on stable-5

### ISSUE THREAD

**Issue by Flashback083** [SpongePowered/SpongeForge#1611]
Hello ! I have the same problem that #1400 , the issue is closed but it still doesent work in spongeforge-1.10.2-2281-5.2.0-BETA-2422.jar ! 

I quote "With SpongeForge installed, the scoreboard.dat isn't updated, neither after the commands are entered nor when the server is stopped, so the death counter doesn't persist. Without Sponge, the appropriate entries are added to the file, and the death counter is there after a restart.."
"fix is still missing for stable-5"
Thanks !

**Comment by Aaron1011** [comment]
@Flashback083: Sorry for the delay. This should be fixed in the latest `stable-5`.
