### ISSUE TITLE
[1.11.2] Crash on latest spongeforge

### ISSUE THREAD

**Issue by Tencao** [SpongePowered/SpongeForge#1613]
**I am currently running...**
- SpongeForge version: 1.11.2-2315-6.1.0-BETA-2410
- Forge version: 13.20.0.2315
- Java version: 8
- Operating System:
 - [X] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

Currently crashes when trying to launch, error doesn't help to narrow the cause

https://paste.ee/r/Gk5vW

**Comment by phit** [comment]
dupe of #1604
the version thing is not an error any sponge crash will output that misleading version comparison, read the whole thing it's listed as a *possible* cause

**Comment by Tencao** [comment]
Since this issue is a duplicate, I'm gonna close this and focus on that topic
