### ISSUE TITLE
Unable to start server

### ISSUE THREAD

**Issue by MrIngelborn** [SpongePowered/SpongeForge#1614]
**I am currently running...**

- SpongeForge version: 1.12-2368-7.0.0-BETA-2423
- Forge version: 1.12-14.21.0.2368
- Java version: openjdk version "1.8.0_131"
- Operating System: Ubuntu 16.04.2 LTS

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [x] macOS
 - [x] Windows

**What is the expected result?**
Server starting
**What is the current result?**
Server crashing

latest.log: https://pastebin.com/EawW5mV2
fml-server-latest.log: https://pastebin.com/KckPKwKJ

**Comment by BrainStone** [comment]
Having that issue too.

**Comment by Zidane** [comment]
Shouldn't be an issue now.
