### ISSUE TITLE
MC-Server can't be started due to Mixin problems

### ISSUE THREAD

**Issue by swolf91** [SpongePowered/SpongeForge#1618]
I'm working on a docker image setting up a minecraft forge server with spongeforge and the cubeengine. Unfortunately it doesn't work anymore due to one of the latest changes in spongeforge. 
You can have a look https://github.com/CubeEngine/docker to see the code for the docker image. The version only contains forge and spongeforge yet. The image is built with the newest bleeding version of spongeforge always. The version of forge is read from a spongeforge version json file. So my details below can differ from yours, when you try it.

**I am currently running...**
- SpongeForge version: 1.12-2368-7.0.0-BETA-2425
- Forge version: 1.12-14.21.0.2368
- Java version:  OpenJDK 64-Bit Server VM, version 1.8.0_131
- Operating System:

 - [x] Linux (Alpine)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: 

**What is the expected result?**
I can use the server. It worked only a few days ago. According to my docker images I tried it 6 days ago and there it worked. So a change from the last 6 days might be related to it.

**What is the current result?**
the server gets an error on startup. 

Server log can be found here: https://pastiebin.com/59576c4ddf3df

It might be an useful information that the server starts for the first time, so there are still some files missing and the world still needs the be created, ... Maybe it's related.

**Comment by phit** [comment]
same as #1614 looks like 1.12 is broken right now due to MinecraftForge/MinecraftForge/pull/4046
