### ISSUE TITLE
Spongeforge 1.11.2 for forge 2388

### ISSUE THREAD

**Issue by LuxerIThink** [SpongePowered/SpongeForge#1619]
Can you update spongeforge on version 1.11.2 for forge 2388?

**Comment by phit** [comment]
any reason why?

**Comment by LuxerIThink** [comment]
Because CoFH Core need forge 2388:/

**Comment by phit** [comment]
no it doesn't, it just doesn't work with Sponge right now
so this issue is a dupe of #1604

**Comment by KingLemming** [comment]
No, CoFHCore does actually require 2388 now, this is correct.

**Comment by phit** [comment]
Good to know, but Sponge build with Forge 2315 works fine with Forge 2388 so even that is not an issue.

**Comment by KingLemming** [comment]
Right. And that shouldn't be an issue at all. We upgraded to 2388 because it includes a couple of PRs we made that actually remove ASM, which hopefully reduces the number of conflicts. ;)
