### ISSUE TITLE
ItemPhysic Drop Item issue

### ISSUE THREAD

**Issue by CreativeMD** [SpongePowered/SpongeForge#1622]
Hey there,
lately i discovered an issue using ItemPhysic on a SpongeForge server. Dropping an item does not work, although it consumes the stack, but the EntityItem does not appear.
ItemPhysic overwrites the forge way of tossing items so it can add more power to the throw.

That's the code:
https://github.com/CreativeMD/ItemPhysic/blob/1.11/src/main/java/com/creativemd/itemphysic/packet/DropPacket.java#L53
I have no idea clue what is going on, maybe you can help out here?

**I am currently running...**

- SpongeForge version: 1.11.2-2282-7.0.0-BETA-2376
- Forge version: 13.20.0.2366
- Java version: jre1.8.0_121 64 bit
- Operating System:

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows

In Regards
CreativeMD

**Comment by Zidane** [comment]
@CreativeMD 

Why are you sending a packet to drop an item? Listen to the Forge events for Player toss and add motion to the EntityItem being spawned. If you circumvent Forge/Minecraft, Sponge will naturally break because the CauseTracker is expecting to go through the correct systems.

**Comment by CreativeMD** [comment]
Ok, still don't really get the problem behind it, but i could find a way around it. Thanks for you help anyway.
