### ISSUE TITLE
SecurityCraft incompatibilities

### ISSUE THREAD

**Issue by bl4ckscor3** [SpongePowered/SpongeForge#1623]
There are currently four incompatibilities between SpongeForge and SecurityCraft. We have tested each incident without SF and everything worked as intended.

**I am currently running...**
- SpongeForge version: 1.11.2-2315-6.1.0-BETA-2410
- Forge version: 13.20.0.2315
- Java version: 1.8.0_131 64bit
- Operating System:
 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows

I've tested this locally on my private Windows PC, which I also got the logs from but it also throws the same errors on a Linux server by a third party hoster.
- Plugins/Mods: 
Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, SecurityCraft (v1.8.2.2-beta4)

**What is the expected result?**
1. Rightclicking modifiable blocks opens the GUI to insert modules and change settings about the block.
2. Entering the correct code into a Keypad makes the Keypad output a redstone signal.
3. Mounting a camera does not output a stacktrace to the console and lets the player view the camera normally. (I should add that in order to let a player view a camera, we spawn a custom entity at the camera's position, which the player then starts riding.)
4. Dismounting from the camera correctly dismounts you and teleports you to the position you were at before mounting the camera

**What is the current result?**
1. Rightclicking modifiable blocks does not open said GUI, and sometimes the GUI shows for a fraction of a second.
2. Entering the correct code into a Keypad crashes the server. (I should note that on the third party server, the server does not crash, but still outputs the stacktrace, and the Keypad outputs a redstone signal as intended.)
3. Mounting a camera outputs a stacktrace to the console, but otherwise works as intended
4. Dismounting a camera seems to teleport you to your previous position, but puts you back onto the camera. You are still mounted to it, as moving your head around with WASD (custom code) still works, but when pressing the duck key to dismount the camera, nothing happens.

**Logs**
1. https://gist.github.com/bl4ckscor3/82fb09a8644da9e78d7bfe86cd021dce
2. https://gist.github.com/bl4ckscor3/4f4ad19aaf934b203302c802cdd02733
3. https://gist.github.com/bl4ckscor3/70361c56ae75acf1024f0275b014e44a
4. https://gist.github.com/bl4ckscor3/ac0c13d2f8dde97e0216635d649b877c

**Comment by ryantheleach** [comment]
**Right Click Block With UBM:**
No discernible error, 

**Keypad:**
Snipped Stacktrace: https://gist.github.com/ryantheleach/adc192aafc99c5bf11fd3cc8d388172f

https://github.com/Geforce132/SecurityCraft/blob/master/1.11.2/src/main/java/net/geforcemods/securitycraft/util/BlockUtils.java#L207
https://github.com/Geforce132/SecurityCraft/blob/master/1.11.2/src/main/java/net/geforcemods/securitycraft/util/BlockUtils.java#L127
https://github.com/Geforce132/SecurityCraft/blob/master/1.11.2/src/main/java/net/geforcemods/securitycraft/blocks/BlockKeypad.java#L131
https://github.com/Geforce132/SecurityCraft/blob/master/1.11.2/src/main/java/net/geforcemods/securitycraft/tileentity/TileEntityKeypad.java#L91

**Mounting a Camera outputs a stacktrace to the console:**
Only thing I could find was this error: https://gist.github.com/ryantheleach/9a28caedbc2ef4422f5c95426304a2ca

https://github.com/Geforce132/SecurityCraft/blob/60d6a8d816fc55d10aba6dd2960427fc19275d13/1.11.2/src/main/java/net/geforcemods/securitycraft/blocks/BlockSecurityCamera.java#L101

Being called directly by a packet, suspected entity spawning in network thread.

**Dismounting a camera**
Only error is same as mounting.

**Comment by bl4ckscor3** [comment]
Is there any progress on this?

**Comment by phit** [comment]
the mounting issues seem to be fixed, as for the rest: the mod seems to do a lot of things async, which it shouldn't please report this to the mod author

https://gist.github.com/phit/a762c9cb5a631137ca47fed2bd69704e

**Comment by bl4ckscor3** [comment]
The issues got fixed in SecurityCraft's code. Thanks for your hint towards the problem!

**Comment by bl4ckscor3** [comment]
Accidently clicked on close and comment, sorry. The "unexpected world change" issue is still happening.

**Comment by phit** [comment]
Mind adding a log with latest version and a reproduction for that one? otherwise this issue is getting quite cluttered with a lot of different things and I couldn't even find the log "unexpected world change".

**Comment by bl4ckscor3** [comment]
It's this log ryantheleach posted. https://gist.github.com/ryantheleach/adc192aafc99c5bf11fd3cc8d388172f
It happens whenever a correct code gets entered into the Keypad and activates it.

**Comment by phit** [comment]
seems to work fine with
spongeforge-1.12.2-2705-7.1.0-BETA-3253.jar
[1.12.x] SecurityCraft v1.8.4.1.jar

no errors when a keypad is activated
