### ISSUE TITLE
CustomNPCs items dupe [1.10.2]

### ISSUE THREAD

**Issue by kasdo** [SpongePowered/SpongeForge#1624]
Forge: 12.18.3.2297
Spongeforge-1.10.2-2281-5.2.0-BETA-2353.jar
Mods: CustomNPCs, CustomMobSpawer, Mo'Creatures

 If you drop the item and enter the inventory in the quests section (CustomNPCs), then the object will remain in inventory and will be on the ground. So we have already 2 items. You can clone items (Such a bug was not even on 1.7.10 forge etc; I havent this bug in single player). The mod maker said this is a problem in Sponge.
![1](https://user-images.githubusercontent.com/7419546/27773365-bdd52164-5f80-11e7-9510-1498fb4d7e3f.png)
![2](https://user-images.githubusercontent.com/7419546/27773364-bdd499ba-5f80-11e7-9531-4587a1cce141.png)
![3](https://user-images.githubusercontent.com/7419546/27773367-bdd72dce-5f80-11e7-832a-4863efa1f07e.png)
![4](https://user-images.githubusercontent.com/7419546/27773366-bdd66b5a-5f80-11e7-9996-f14c9d007ca8.png)

**Comment by kasdo** [comment]
In new versions its already fixed.

**Comment by ryantheleach** [comment]
New versions of what? New minor Versions, new Minecraft Version? or new Major versions?

**Comment by kasdo** [comment]
New version spongeforge

**Comment by gabizou** [comment]
Re-test with latest. You're several builds behind.
