### ISSUE TITLE
Canceling the ChangeBlockEvent for fluid pickup/placing does not prevent the bucket changing

### ISSUE THREAD

**Issue by pie-flavor** [SpongePowered/SpongeForge#1625]
e.g. if I was in survival mode, and picked up a 'protected' block of lava, it would still be replaced immediately, but I'd be holding a bucket of lava, and it's not just a ghost item.

**Comment by phit** [comment]
@pie-flavor is this still an issue? then please add some more information like versions this applies to

**Comment by phit** [comment]
moving to SpongeCommon > https://github.com/SpongePowered/SpongeCommon/issues/1609
