### ISSUE TITLE
detected missing registry entries: sponge:human

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeForge#1628]
This occurred while loading a single player save in my IDE, after updating my workspace to [bleeding](https://github.com/SpongePowered/SpongeForge/commit/7789e67bbd1ef2ed2411d08d23c1ea006ef7aa56), last used on a random 1.11.2 dev build.

![screenshot](https://user-images.githubusercontent.com/141554/27827463-94e88e90-60f6-11e7-83e0-221ba115b633.png)

> Forge Mod Loader detected missing registry entries. 
> There are 1 missing entries in this save. 
> If you continue the missing entries will get removed. 
> A world backup will be automaticallg created In your saves directory 
> Missing minecraft:entities: 
> sponge:human

**Comment by JBYoshi** [comment]
I got that as well. I traced it back to https://github.com/SpongePowered/SpongeCommon/blob/418198e4fd91714831b5b8d5796a66ba9b8f90c2/src/main/java/org/spongepowered/common/registry/type/entity/EntityTypeRegistryModule.java#L209; `git blame` says it was commented out in https://github.com/SpongePowered/SpongeCommon/commit/418198e4fd91714831b5b8d5796a66ba9b8f90c2.

**Comment by JBYoshi** [comment]
I just remembered that Forge rewrote their registry system for 1.12. I assume that's why it was commented out. I'll look into this.

**Comment by ryantheleach** [comment]
You are going ham Yoshi!!

**Comment by MJavad** [comment]
I got this when I tried to remove spongeforge-1.12.2-2705-7.1.0-BETA-3358 and load my save file from my server.
Any idea why? also, there are more errors regarding saving chunks after ignoring this.
On FTB Revelation 2.3.0

**Comment by phit** [comment]
the message is normal when you remove SpongeForge from your server

**Comment by MJavad** [comment]
@phit Thank you for the answer, so it should be ok but I get lots of errors afterwards that it can’t save chunks.
I’m not home right now, I’ll provide further information when I can.
