### ISSUE TITLE
CustomNPCs Server crash (1.10.2)

### ISSUE THREAD

**Issue by kasdo** [SpongePowered/SpongeForge#1629]
Forge Mod Loader version 12.18.3.2316
spongeforge-1.10.2-2281-5.2.0-BETA-2424
Mods: CustomNpcs, Mo'Creatures, CustomMobSpawner, LotsOfFood
Plugins: WorldEdit, RedProtect, EssentialCMDs, ProjectWorlds, ProjectPortals, Twentyticks, PermissionsEx, Holograms
Crash: https://hastebin.com/uqoluponow.xml
Noppes (custom npcs author) say its sponge bug.

**Comment by phit** [comment]
@kasdo still an issue? the log is offline

**Comment by phit** [comment]
No reply, closing this for now. Please reply with the information you have been asked for and I will reopen this issue.
