### ISSUE TITLE
Applied Energistics 2 error & flood

### ISSUE THREAD

**Issue by mkrtes** [SpongePowered/SpongeForge#1633]
Server crashes after multiple error in the console

**I am currently running...**
- SpongeForge version: spongeforge-1.10.2-2281-5.2.0-BETA-2433
- Forge version: 12.18.3.2316
- Java version: 8
- Operating System:
 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: https://pastebin.com/srhtGJHp
Error flood more than 30 mB:

https://gist.github.com/mkrtes/b07d4c0d993dc48e3b525547a73959e1

**Comment by tyler489** [comment]
Are you using spongebootstrap if not i would use t

**Comment by mkrtes** [comment]
@tyler489 yes

**Comment by YukanoXX** [comment]
hi,

i have the same problem, but when i remove the ae2 dense cable from the world , it will be fine.
https://pastebin.com/j3aREQtJ
i think "spongeforge-1.10.2-2281-5.2.0-BETA-2433" and later, AE2 Dense Cable works not correct.

same thing with : fork ae2 version rv4 alpha 11 and rv4 stable 1 
Forge 12.18.3.2422, Spongeforge 1.10.2-2281-5.2.0-BETA-2464
Testmodpack: FtB Beyond

also, sometimes comes the error when the sever shut down (/stop). the server cannot  write the item ids and destroys  the world (after restart blocks are changed)

best regards
Yukano

**Comment by bloodmc** [comment]
@mkrtes @YukanoXX Please provide a test world using only AE2 and SF with steps on how to reproduce. The id glitch was already fixed, I'm more concerned about the original error.

**Comment by YukanoXX** [comment]
Hi
?? @ boodmc 
i thought it was already worked on that problem, it was fixed after version 2515+(testet up to 2539) and higher. when i shutdown now the server the world will save correctly without any problems. sorry for the forgotten informations about that.

from my side , closed

best regards 
Yukano

**Comment by bloodmc** [comment]
@YukanoXX Thanks!
@mkrtes Please provide what I need to address your issue.

**Comment by mkrtes** [comment]
@bloodmc This problem occurs at a random time on the server where it plays 5-10 players. I could not figure out the exact cause. Now I use stable version of AE2, and the sponge version 2526. But the world itself saved from older versions. This problem sometimes (rarely) occurs and requires manual restart of the server. 
Perhaps the creation of the world anew will fix this. At the moment, the topic can be closed.

**Comment by Zidane** [comment]
Closing issue. Create new one if it reoccurs and we're given a setup to reproduce.
