### ISSUE TITLE
Sponge Crash With QUtilities Mod

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1634]
**I am currently running...**
- SpongeForge version:  2436
- Forge version: 2397
- Java version:  8u131
- Operating System: windows 10 x64
- Plugins/Mods: 
universeguard
QUtilities

**What is the expected result?**
my dedicated server should start
**What is the current result?**
it crashed just after the world generation (after %100)

here are the logs.
[fml-server-latest.log.txt](https://github.com/SpongePowered/SpongeForge/files/1128548/fml-server-latest.log.txt)
[latest.log.txt](https://github.com/SpongePowered/SpongeForge/files/1128549/latest.log.txt)
[fml-junk-earlystartup.log.txt](https://github.com/SpongePowered/SpongeForge/files/1128550/fml-junk-earlystartup.log.txt)

**Comment by phit** [comment]
relevant https://github.com/SpongePowered/SpongeCommon/pull/1244 https://github.com/SpongePowered/SpongeAPI/issues/1427

**Comment by bloodmc** [comment]
Fixed in https://github.com/SpongePowered/SpongeCommon/commit/e61a7d204c574f1383cbd1a4b1ba9c16b000a547
