### ISSUE TITLE
Crash loading in missing dimension (natura:nether)

### ISSUE THREAD

**Issue by Whazaaaaa** [SpongePowered/SpongeForge#1637]
So I'm trying to update my server which runs SkyFactory3 3.0.10 to 3.0.13. While doing this the server is not starting anymore because sponge is trying to load a dimension (natura:nether) that isnt there. I'd also like to note that in this update I also went from sponge 2379 to 2433. This doesnt make much sense as the dimension did not exist before aswell but the server started just fine. I'd like to know what config or file I have to delete to fix this issue as my server doesnt start at all anymore.

I tried deleting level_sponge.dat and the config from sponge but that didnt solve anything and the same error occured.

Note that the server starts perfectly fine when sponge is not loaded.

**I am currently running...**
- SpongeForge version: spongeforge-1.10.2-2281-5.2.0-BETA-2433
Came from SpongeCoremod (spongeforge-1.10.2-2281-5.2.0-BETA-2379.jar) where everything was fine. Going back to that one doesnt solve this issue.
- Forge version: FTBserver-1.10.2-12.18.3.2316-universal
- Java version: Java Version: 1.8.0_111, Oracle Corporation
- Operating System: 
 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: 
Cant do /sponge plugins and this would also give a list of all the mods the modpack runs but here is a list of plugins that 'might' cause troubles with dimension but I dont think a plugin is the cause.
griefprevention, fastasncworledit, nucleus, playershopsrpg, prism, skyclaims.

**What is the expected result?**
The server should start just fine

**What is the current result?**
The server crashes

**Additional crash logs:**
https://pastebin.com/jbQrZ7TC
The crashlog itself + the console at that moment.

**Comment by axle2005** [comment]
Since Im guessing this is Skyfactory 3... anyway, This will occur for anyone updating to the most recent recommended version, and can easily be solved by changing: 
```    B:"Override Nether"=false ``` to ```    B:"Override Nether"=true ``` in the natura config.

**Comment by Whazaaaaa** [comment]
@axle2005 Lifesaver thanks. The server starts up just fine again!

**Comment by Whazaaaaa** [comment]
Seeing as that is a temporary fix and it should work without having to set the config to true. I'm reopening this.

**Comment by tyler489** [comment]
Alternitvly you could just delete the nether world that works to

**Comment by xAlicatt** [comment]
Disabling Natura in the nether isn't an option. @tyler489 you're saying just deleting the DIM-1 folder will fix this crash?

EDIT:: Can confirm that I was able to get my server to start up by deleting the nether DIM folder, in case anyone else is looking for a quick "fix" for this.

**Comment by xAlicatt** [comment]
Can confirm that I was able to get my server to start up by deleting the nether DIM folder, in case anyone else is looking for a quick "fix" for this.

**Comment by bloodmc** [comment]
Anyone able to provide a test world that has this issue with as few mods as possible?
