### ISSUE TITLE
ClickInventoryEvent error[1.10.2]

### ISSUE THREAD

**Issue by PorPit** [SpongePowered/SpongeForge#1638]
- SpongeForge version: 5.2.0-BETA-2433
- Forge version: 12.18.3.2316
- Java version: 8
- Operating System: 
 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows

when i set a event to Cancelled
code like this
```
@Listener
	public void ClickInventory(ClickInventoryEvent event, @First Player p) {
		if (event.getTransactions().get(0).getOriginal().getType().equals(ItemTypes.STONE)) {
			event.setCancelled(true);
		}
	}
```
and when i click a STONE in Inventory   event is normal Cancelled

but when this item in the hotbar,  i clicked this item and close Inventory, and pause "Q" to drop this item
than open inventory and click a empty slot , this item is come back in Inventory

------------------------------------------------------------------------------------------------------
and there is other problem:
exm code:
```
@Listener
	public void ClickInventory(ClickInventoryEvent event, @First Player p) {
		if (event.getTransactions().get(0).getOriginal().getType().equals(ItemTypes.STONE)) {
			event.setCancelled(true);
			event.getTransactions().get(0).setCustom(customitem);
		}
	}
```
that not work 
 this slot not change to <customitem>
change code to this:
```
@Listener
	public void ClickInventory(ClickInventoryEvent event, @First Player p) {
		if (event.getTransactions().get(0).getOriginal().getType().equals(ItemTypes.STONE)) {
			event.getTransactions().get(0).setCustom(customitem);
		}
	}
```
this slot is change to <customitem>
but the cursor slot has item: STONE

what s the problem

**Comment by Faithcaio** [comment]
for the last 2:
If you cancel the event the transactions are rolled back to `#getOrigin`
If you only set the custom result for the slot this does **not** change the cursor-transaction which is not on a slot. You'd have to set the result on `getCursorTransaction` too

**Comment by bloodmc** [comment]
This was fixed starting at commit https://github.com/SpongePowered/SpongeCommon/commit/1386182d7c39513fb18c364ad364582059f6919e

Update to latest SF.
