### ISSUE TITLE
clear() removes more then it should

### ISSUE THREAD

**Issue by Sir-Will** [SpongePowered/SpongeForge#1639]
I'm not 100% sure if this is a sponge issue or if I'm doing something wrong.

**I am currently running...**
- SpongeForge version: 1.10.2 - 2433
- Forge version: 2281: 

**What is the expected result?**
Remove the correct itemstacks.

**What is the current result?**
I'm trying to remove itemstacks from the player inventory or other inventories.
To filter this I use `query()` which sometimes works correctly and sometimes it clears the complete inventory.
`inv.totalItems()` shows always the amount of the filtered items although it differs between 64 and 128 when I have 2 stacks of the filtered itemstack in the inventory.

I'm doing the same thing with the `InteractInventoryEvent.Close` event and I don't experience any issues there.
```java
@Listener
public void onInventoryClick(ClickInventoryEvent event, @First Player player) {
	ItemStack itemStack = event.getCursorTransaction().getFinal().createStack();

	if (itemStack.getItem() == ItemTypes.NONE) return;

	event.setCancelled(true);
	if (event.getTargetInventory().getArchetype() != InventoryArchetypes.WORKBENCH) {
		Task.builder().execute(new Runnable() {
			@Override
			public void run() {
				Inventory inv = event.getTargetInventory().query(itemStack);
				Plugin.getInstance().getLogger().info("Inv: " + inv.totalItems());
				inv.clear();
			}
		}).delayTicks(1).submit(Plugin.getInstance());
	}
}
```
Demonstration: http://i.imgur.com/WlGLEZh.gifv

**Comment by Zidane** [comment]
@Sir-Will 

Can you re-open this on SpongeCommon instead? @Faithcaio Wait for the re-open then look into fixing as that query should return a view of an Inventory as an Inventory with only the stack he clicked and the clear of it should only affect that stack.

Unless @Mumfrey says otherwise.

**Comment by Faithcaio** [comment]
Regardless of the actual issue. You can iterate through the slots and clear them.
`queryResult.slots().forEach(Inventory::clear);`

**Comment by Zidane** [comment]
Closing as a work-around was provided by @Faithcaio and we need this re-opened in the proper repo for a more correct fix.

**Comment by Sir-Will** [comment]
Done: https://github.com/SpongePowered/SpongeCommon/issues/1449
