### ISSUE TITLE
SpongeForge and ForgeEssentials W/ Pixelmon

### ISSUE THREAD

**Issue by PokemonBlack1** [SpongePowered/SpongeForge#1640]
SpongeForge crashes the server. Sponge and Forge are compatible versions. Gives an error on ForgeEssentials preloader. I am unaware how I can make this problem work. FE says they're compatible with SF, but it doesn't seem like. Any advice how to fix it?

**I am currently running...**
- SpongeForge version: 5.1.0-Beta-2100
- Forge version: 2202
- Java version: Latest
- Operating System: Unknown (assuming Windows)
Server is being ran on [www.server.pro](https://server.pro/)
Specs I have access to are: 2GB ram, 4 core processor (unknown type) Java 8 latest
Mods:
Aether Legacy 1.3.1
Mantle
NetherCore
SpongeForge ^
Pixelmon 5.1.1
AnotherGymPlugin for Pixelmon
DayCare for Pixelmon
ForgeEssentials
Gameshark for Pixelmon
GTS for Pixelmon
PixelAnnouncer for Pixelmon
PixelExtras for Pixelmon
PixelFriends for Pixelmon
SpawnofPsyduck for Pixelmon
Tournaments for Pixelmon
WonderTrade for Pixelmon

Expected result was the server to run smoothly and no errors.

Results are in the pastebin below.

https://pastebin.com/UXjvvHde

**Comment by EmanYm** [comment]
Try updating your [SpongeForge](https://www.spongepowered.org/downloads/spongeforge/stable/1.10.2) to the latest MC1.10.2.
>I am currently running...
SpongeForge version: 5.1.0-Beta-2100

and your [MinecraftForge](http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.10.2.html) to the latest MC1.10.2
>[15:51:52] [main/INFO] [Sponge/]: /*      12.18.3.2202 (you are running 12.18.3.2202)

You could also [update your Pixelmon](http://pixelmonmod.com/downloads.php) to the latest while you're at it.


>Gremlins are invading your computer. Did you feed a Mogwai after midnight?

**Comment by phit** [comment]
Your spongeforge version is ancient. Update, you dont have to match forge and sponge version,
see https://gist.github.com/phit/d097a5a4e7172e6c1e4a7616596bc7ce

**Comment by PokemonBlack1** [comment]
Still having problems. Updating them both didn't work. https://pastebin.com/TeqXJMEG Both are fully updated. Not sure what's wrong at this point.

**Comment by phit** [comment]
that looks like a forgeessentials issue, almost the same crash can be found here https://github.com/ForgeEssentials/ForgeEssentials/issues/2232

**Comment by EmanYm** [comment]
>[17:23:19] [main/INFO] [Sponge/]: /*            Caused by : com.forgeessentials.core.preloader.asminjector.MethodInjector$MethodInjectionError                                                                                                                                                                                  */
[17:23:19] [main/INFO] [Sponge/]: /*              Message : com.forgeessentials.core.preloader.asminjector.MethodInjector$MethodInjectionError: Error injecting com.forgeessentials.core.preloader.injections.MixinEntity.attackEntityFrom_event(MixinEntity.java:0) into org.spongepowered.common.mixin.core.entity.MixinEntity.func_70097_a */

**Comment by PokemonBlack1** [comment]
Bootstrap didn't work. I'm not sure what to do anymore. If there's a working alternative to ForgeEssentials that anyone knows of, let me know--or if you know any other tries to fix it.

**Comment by PokemonBlack1** [comment]
@EmanYm I'm not entirely sure what I'm supposed to take from this.

**Comment by phit** [comment]
Like I said above report the issue to ForgeEssentials and I'm sure they will fix it!
If you are willing to not have FE, what parts do you care about? pretty much everything it does also exists as sponge plugin

Commands, WorldBorder: https://nucleuspowered.org/
Permissions: https://forums.spongepowered.org/t/luckperms-an-advanced-permissions-plugin/14274
Multiworld: https://forums.spongepowered.org/t/project-worlds-world-manager/10170
Economy: https://forums.spongepowered.org/t/economy-total-economy-v1-6-0/7022
etc

**Comment by Skycon45** [comment]
PokemonBlack1 do you by any chance still have all of those pixelmon sidemods? Every since pixelmon got shut down you cant download sidemods from their site anymore, i was wondering if you still had them and would let me download a copy.
Thanks
