### ISSUE TITLE
A possible mistake feedback

### ISSUE THREAD

**Issue by 5igm** [SpongePowered/SpongeForge#1641]
**I am currently running...**

forge-1.11.2-13.20.1.2393-universal.jar
spongeforge-1.11.2-2393-6.1.0-BETA-2453.jar
jre1.8.0_131
Windows10

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows

- Plugins/Mods: 
![111](https://user-images.githubusercontent.com/11610914/28083800-fa6d5d1a-6676-11e7-8d2c-bee7badee97a.jpg)

I am not sure is it the error belonging to Sponge, but it seems to be.
https://pastebin.com/G1QPf8Zj The error part
[fml-server-latest - 1.txt](https://github.com/SpongePowered/SpongeForge/files/1139875/fml-server-latest.-.1.txt)  The whole log file.

**Comment by ryantheleach** [comment]
```
[20:04:55] [main/INFO] [mixin/]: Instancing error handler class org.spongepowered.mod.mixin.handler.MixinErrorHandler
[20:04:55] [main/WARN] [mixin/]: Mixin apply failed mixins.common.core.optional.json:util.math.MixinMutableBlockPos -> net.minecraft.util.math.BlockPos$MutableBlockPos: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Shadow field field_177997_b was not located in the target class
```

Might be due to FoamFix Anarchy?

https://asie.pl/Projects/Minecraft/Mods/FoamFix/
> Known Issues
> Sponge: The "coremod.optimizedBlockPos" option collides with Sponge's own transformations. Please disable it.

You can try this setting, switching to FoamFix-Lawful, or removing FoamFix, and see if the issue still persists.

**Comment by 5igm** [comment]
I found another one here, and I have switched to FoamFix-Lawful
https://pastebin.com/hfgL4dQR

**Comment by Zidane** [comment]
Closing as this is an incompatibility with FoamFix and @ryantheleach has provided a fix.
