### ISSUE TITLE
[1.11.2] Server crash NoSuchElementException

### ISSUE THREAD

**Issue by FiveEYZ** [SpongePowered/SpongeForge#1642]
**I am currently running...**
- SpongeForge version: spongeforge-1.11.2-2393-6.1.0-BETA-2442
- Forge version: forge-1.11.2-13.20.1.2393-universal
- Java version: 1.8.0_131
- Operating System:
 - [x] Windows Server 2012 R2

- Plugins/Mods: 
Plugins (121): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, Aroma1997Core, Muon, Backpacks!, SpongeAPI, SpongeForge, CoFH ASM, ccl-entityhook, Actually Additions, AppleCore, Just Enough Items, AppleSkin, Aroma1997Core|Helper, Aroma1997sDimension, AromaBackup, AromaBackupRecovery, Astral Sorcery, Alternate Terrain Generation, Quark, AutoRegLib, Baubles, BD Lib, BiblioCraft, Biomes O' Plenty, Guide-API, Blood Magic: Alchemical Wizardry, Bloodmoon, Botania, MrCrayfish's Furniture Mod, Chameleon, CodeChicken Lib, ChickenChunks, Chisel, Chisels & Bits, CoFH Core, Computality, CraftTweaker JEI Support, Crafttweaker, Cyberware, Dimensional Ores, Elevator Mod, Embers, EnderStorage, extrautils2, Fast Leaf Decay, Forestry, FTBLib, Funky Locomotion, GenDustry, Hammer Core, Mantle, Tinkers' Construct, TESLA, The One Probe, Immersive Engineering, Immersive Petroleum, Tesla Core Lib, Industrial Foregoing, Iron Chest, JourneyMap, MalisisCore, MalisisDoors, Master Builders Mod, Mekanism, MekanismGenerators, Metamorph, MineColonies, MineTweakerRecipeMaker, Mystical Agriculture, Mystical Agradditions, Natura, NetherPortalFix, Open Glider, OreExcavation, Pam's HarvestCraft, Reborn Core, reborncore-MCMultiPart, Refined Storage, RFTools, RFTools Control, Roguelike Dungeons, Roots 2, Ruins Mod, Solar Flux Reborn, The Spice of Life, Steve's Carts 2, SwingThroughGrass, Storage Drawers, Thermal Foundation, Thermal Dynamics, Thermal Expansion, Tinkers Tool Leveling, Tomb Many Graves, TOP Addons, XNet, NuVotifier, AurionsVoteListener, BungeeTabListPlus-SpongeBridge, EconomyLite, Enjin Minecraft Plugin, GriefPrevention, Holograms, HuskyUI, HuskyCrates, LuckPerms, Market, MMCReboot, MultiChat Sponge, Nucleus, PlaceholderAPI, Nucleus Gluon, PayDay, Player Glow, RankUpper, SleepVote, WorldEdit, denseores, YABBA

https://gist.github.com/FiveEYZ/639df6f2fe42c3bfafd2db7afe0cd2db

**Comment by Zidane** [comment]
@gabizou 

Tracker bug, can you fix this?

**Comment by Aaron1011** [comment]
@FiveEYZ: Can you upload your `fml-server-latest.log` and `latest.log`?
