### ISSUE TITLE
No wither skeletons spawning with BoP

### ISSUE THREAD

**Issue by Jay9519** [SpongePowered/SpongeForge#1643]
**I am currently running...**
- SpongeForge version:  spongeforge-1.11.2-2393-6.1.0-BETA-2463
- Forge version: forge-1.11.2-13.20.1.2393-universal
- Java version: 8
- Operating System:

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: Actually Additions, AdventureMMO, Better Achievements, BiblioCraft, Biomes O' Plenty,
BiblioWoodBoP, Buycraft, Chisels & Bits, Fast Leak Decay, FTBUtilities, FTBLib, Grim Pack, Hardcord ORE,
Industrial Craft 2, Iron Chest, Just Enough Items, JourneyMap, LuckPerms, MalisisCore, MalisisDoors, Malisis Switches, Mantle, MineColonies, MMCReboot, Morpheus, Multi-Hotbar, NuclearCraft, OreAlerts,
Tinkers Construct, Tinkers Tool Leveling, UltimateCore, Vending, waila, What Are You Looking At, WorldEdit

**What is the expected result?**
To travel through Nether Fortresses and seeing wither skeletons

**What is the current result?**
No wither skeletons spawn at all in the nether, they do spawn via spawn eggs and skeleton spawners but not naturally. I can't see a mod that I have that could cause the skeletons to not spawn.

**Comment by ghost** [comment]
I have same issue. I think its due Biomes o Plenty. I made workaround plugin for fix spawning.

**Comment by Jay9519** [comment]
Care to share?

**Comment by ghost** [comment]
https://www.rebelgames.net/fixspawning-0.1.jar

**Comment by dmarcuse** [comment]
I'm having the same issue. The mods that we have in common with you are Actually Additions, BiblioCraft, Chisels & Bits, Iron Chest, JEI, JourneyMap, LuckPerms, Morpheus, and Tinkers' Construct.

**Comment by bloodmc** [comment]
@Jay9519 @hunter688 Does this still occur in latest build?

**Comment by Jay9519** [comment]
I have updated the server to 1.12.1 now and the wither skeletons still don't spawn

**Comment by bloodmc** [comment]
@Jay9519 Try to figure out which mod is causing it. I would create a test world and add 1 mod at a time until it breaks.

**Comment by bloodmc** [comment]
@hunter688 Can you figure out what mod is breaking this?

**Comment by ghost** [comment]
I think its due mod which modify nether, in my case Biomes O Plenty and Tinkers Construct.

**Comment by dmarcuse** [comment]
I was having the same issue but I didn't have Biomes O Plenty, only TiCon.

**Comment by phit** [comment]
Welp, after not having issue ourselves in 1.10 or 1.11, we finally have a server using BOP and sure enough no Wither Skellis to be found.

Running BiomesOPlenty-1.12-7.0.0.2291 with SpongeForge 7.0.0-BETA-2640

Actually unless that's a vanilla change, not even a Skeleton spawner is giving me Wither Skeletons
![](https://i.imgur.com/gdx3gX4.png)

**Comment by ghost** [comment]
Btw in the singleplayer wither skeletons spawning normally (with bop and/or tic installed).

**Comment by tgstyle** [comment]
I could get it to work with everything but Natura.
https://github.com/progwml6/Natura/issues/385

**Comment by rob5251** [comment]
Has anyone found a temporary fix for this?
I did a bunch of config file digging, but found nothing notable.

**Comment by tgstyle** [comment]
Place a spawner in the nether and click a Wither Skeleton spawn egg on it.

**Comment by Yorkforce** [comment]
Still occurring on spongeforge-1.12.2-2529-7.0.0-BETA-2732, were using the Horizons modpack which doesn't have Tinkers in the pack, only BOP.

**Comment by ryantheleach** [comment]
@phit I'll take this one.

**Comment by ryantheleach** [comment]
Tested in a Sponge Single Player Production environment, No Mods:

SpongeForge
    Minecraft: 1.12.2
    SpongeAPI: 7.0.0-SNAPSHOT-14f459d
    SpongeForge: 1.12.2-2529-7.0.0-BETA-2732
    Minecraft Forge: 14.23.0.2537

Wither Skeletons generated on fortresses, and seemed to be spawning in fortresses.

I tried your trick with the spawner, and was able to get skeletons and wither skeletons to spawn.

Will be testing Natura shortly.

**Comment by ryantheleach** [comment]
Testing using natura-1.12-4.3.0.23.jar , Mantle-1.12-1.3.1.21.jar 

I was able to spawn skeletons and wither skeletons using a mob spawner in the nether.

However, I was unable to /locate a Fortress....

Searching manually.

Edit: Locate worked. must have just taken a tiny bit.

Wither Skeletons are at least generating... Not sure about spawning.

**Comment by Yorkforce** [comment]
To confirm, if placing a spawner then changing it to a wither skeleton spawner via a spawn egg the skeletons do spawn from those, they do not spawn naturally however, neither do blazes naturally spawn. (the blaze spawners do spawn though so it's not as bigger an issue as the wither skeletons).

Server currently has: (Horizons 3 v1.1.0)
spongeforge-1.12.2-2529-7.0.0-BETA-2732
BiomesOPlenty-1.12.2-7.0.1.2302-universal.jar

We even tried disabling all BOP Nether biomes in the BOP configs (with Nether world reset) but the issue remains.

**Comment by ryantheleach** [comment]
I've tested this with Natura and with BOP was not able to replicate.

Blazes and wither skeletons were both spawning using BiomesOPlenty-1.12.2-7.0.1.2302-universal.jar and a custom build of SpongeForge that has a few fixes that should be unrelated to this bug.

Can you test using ONLY SF, BiomesOPlenty, in both single player and multiplayer? I've spent several hours at this point chasing a bug that doesn't seem to exist.

My suspicion is that the rate they are spawning at is severely reduced, possibly due to BoP not supporting the /locate command, or a mod conflict with Sponge causing it to not support the /locate command.

**Comment by ryantheleach** [comment]
Using selectors I found was extremely helpful.

 e.g. `/kill @e[type=wither_skeleton]` `/say @e[type=wither_skeleton]` `/tp @e[type=wither_skeleton]`

**Comment by ryantheleach** [comment]
![image](https://user-images.githubusercontent.com/141554/32984657-81880f90-ccfa-11e7-9c32-c29a7cba289e.png)

**Comment by ryantheleach** [comment]
Locate is working now, with no changes. something odd is happening.

**Comment by phit** [comment]
Tested with:
SpongeCommon d65d60cceba8be1521415a7664009fa7e4806fb6
SpongeForge d53f36e1dee94514cc4bc6ec7e4fac883dacf3d5 + https://github.com/SpongePowered/SpongeForge/pull/1858
BiomesOPlenty-1.12.2-7.0.1.2309-universal.jar

Server was run through the dev enviroment as dedicated server, client was just a normal MultiMC instance with BoP.

I was in a Corrupted Sands biome with a Fortress, no Wither Skeleton spawned. Also used the testplugin from ryantheleach to verify that none spawned.

**Comment by HenrikoMagnifico** [comment]
Still not spawning... On both Singleplayer and Multiplayer without SpongeForge.

**Comment by Zidane** [comment]
If you don't have SpongeForge installed and they don't spawn, that isn't a Sponge issue?
