### ISSUE TITLE
[1.11.2] Crash: Exception while updating neighbours

### ISSUE THREAD

**Issue by FiveEYZ** [SpongePowered/SpongeForge#1650]
**I am currently running...**
- SpongeForge version: spongeforge-1.11.2-2393-6.1.0-BETA-2468
- Forge version: forge-1.11.2-13.20.1.2393-universal
- Java version: 1.8.0_131
- Operating System:
 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows Server 2012 R2

- Plugins/Mods: 
Plugins (121): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, Aroma1997Core, Muon, Backpacks!, SpongeAPI, SpongeForge, CoFH ASM, ccl-entityhook, Actually Additions, AppleCore, Just Enough Items, AppleSkin, Aroma1997Core|Helper, Aroma1997sDimension, AromaBackup, AromaBackupRecovery, Astral Sorcery, Alternate Terrain Generation, Quark, AutoRegLib, Baubles, BD Lib, BiblioCraft, Biomes O' Plenty, Guide-API, Blood Magic: Alchemical Wizardry, Bloodmoon, Botania, MrCrayfish's Furniture Mod, Chameleon, CodeChicken Lib, ChickenChunks, Chisel, Chisels & Bits, CoFH Core, Computality, CraftTweaker JEI Support, Crafttweaker, Cyberware, Dimensional Ores, Elevator Mod, Embers, EnderStorage, extrautils2, Fast Leaf Decay, Forestry, FTBLib, Funky Locomotion, GenDustry, Hammer Core, Mantle, Tinkers' Construct, TESLA, The One Probe, Immersive Engineering, Immersive Petroleum, Tesla Core Lib, Industrial Foregoing, Iron Chest, JourneyMap, MalisisCore, MalisisDoors, Master Builders Mod, Mekanism, MekanismGenerators, Metamorph, MineColonies, MineTweakerRecipeMaker, Mystical Agriculture, Mystical Agradditions, Natura, NetherPortalFix, Open Glider, OreExcavation, Pam's HarvestCraft, Reborn Core, reborncore-MCMultiPart, Refined Storage, RFTools, RFTools Control, Roguelike Dungeons, Roots 2, Ruins Mod, Solar Flux Reborn, The Spice of Life, Steve's Carts 2, SwingThroughGrass, Storage Drawers, Thermal Foundation, Thermal Dynamics, Thermal Expansion, Tinkers Tool Leveling, Tomb Many Graves, TOP Addons, XNet, NuVotifier, AurionsVoteListener, BungeeTabListPlus-SpongeBridge, EconomyLite, Enjin Minecraft Plugin, GriefPrevention, Holograms, HuskyUI, HuskyCrates, LuckPerms, Market, MMCReboot, MultiChat Sponge, Nucleus, PlaceholderAPI, Nucleus Gluon, PayDay, Player Glow, RankUpper, SleepVote, WorldEdit, denseores, YABBA

**What is the current result?**
Seems to be some wrong doings happening, resulting in NPE

crash 1:
https://gist.github.com/FiveEYZ/1cbd6bddc4934e47f325434b802dda5e

Crash 2:
https://gist.github.com/FiveEYZ/690615bcb5c98ce4fc11aec6c00e1991

**Comment by Zidane** [comment]
java.lang.NullPointerException: Exception while updating neighbours
	at net.minecraft.block.Block.getId(Block.java:2671)

This returning null means a block hasn't been registered correctly and points to a mod doing something it should not be doing. Whereas Sponge tripped the crash, we aren't changing how we're doing getId as mods need to be using Minecraft's/Forge's registries correctly.

Per this line: https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/mixin/core/block/MixinBlock.java#L167

My recommendation is to remove all mods and re-add them one at a time and figure out who is the culprit.
