### ISSUE TITLE
Sponge Tracking crashed server with chancecubes

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1651]
- SpongeForge version: spongeforge-1.11.2-2393-6.1.0-BETA-2468.jar
- Forge version: forge-1.11.2-13.20.1.2393-universal.jar
- Java version: Java 8
- Operating System:
 - Linux

- Plugins/Mods: 
ClearMob, Discord Bridge, NuVotifier, Enjin Minecraft Plugin, GriefPrevention, LuckPerms, MMCRules, Nucleus, WorldEdit, RedProtect, StatusProtocol, ServerListPlus, TabManager, Total Economy

https://gist.github.com/xKnightGamingx/08199add13522623e9e4870d4791cecf

**Comment by Zidane** [comment]
java.lang.ClassCastException: forestry.apiculture.tiles.TileHive cannot be cast to chanceCubes.tileentities.TileChanceCube
	at chanceCubes.blocks.BlockChanceCube.removedByPlayer(BlockChanceCube.java:50)

Nothing to do with Sponge.
