### ISSUE TITLE
Plugins that work with minecraft block throws errors

### ISSUE THREAD

**Issue by Pokekhan** [SpongePowered/SpongeForge#1655]
**I am currently running...**

- SpongeForge version: 1.10.2-2281-5.2.0-BETA-2464
- Forge version: forge-1.10.2-12.18.2.2099
- Java version: 8
- Operating System:

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: 

Plugins (35): [m[0;32;1mMinecraft[m, [m[0;32;1mMinecraft Coder Pack[m, [m[0;32;1mForge Mod Loader[m, [m[0;32;1mMinecraft Forge[m, [m[0;32;1mSpongeAPI[m, [m[0;32;1mSpongeForge[m, [m[0;32;1mBlock Monitor[m, [m[0;32;1mPixelmon[m, [m[0;32;1mDaycare[m, [m[0;32;1mEconomyLite[m, [m[0;32;1mGriefPrevention[m, [m[0;32;1mGlobal Trading Station[m, [m[0;32;1mHuskyUI[m, [m[0;32;1mHuskyCrates[m, [m[0;32;1mLuckPerms[m, [m[0;32;1mNucleus[m, [m[0;32;1mOblique Core[m, [m[0;32;1mOblique Sponge Core[m, [m[0;32;1mPixel Extras[m, [m[0;32;1mPixelMoney[m, [m[0;32;1mPixelmonGym[m, [m[0;32;1mPixelQuests[m, [m[0;32;1mPixelUpgrade[m, [m[0;32;1mPlaceholderAPI[m, [m[0;32;1mPocketTags[m, [m[0;32;1mPocketTokens[m, [m[0;32;1mPokestop[m, [m[0;32;1mOblique's Portals[m, [m[0;32;1mRazzle Dazzle Cosmetics[m, [m[0;32;1mRazzle Dazzle Cosmeticssponge[m, [m[0;32;1mSignEditor[m, [m[0;32;1mSpongeMarket[m, [m[0;32;1mTM Trade[m, [m[0;32;1mTournaments[m, [m[0;32;1mWondertrade

**What is the expected result?**
When place block block with a plugin. For explain using the huskycrate plugin. Place down a minecraft item block like a chest to use a crate system throw this error

**What is the current result?**

It throw this error in console: https://hastebin.com/akatipoxer.md

**Comment by ghost** [comment]
tooooo old forge imho

**Comment by Zidane** [comment]
Closing as your Forge is well out of date. Make sure before opening tickets in the future that your SpongeForge, Forge, and mods are all up to date for the Minecraft version you are targeting.
