### ISSUE TITLE
SpongeForge prevents Actually Additions GUI buttons from working

### ISSUE THREAD

**Issue by cyberdjinn** [SpongePowered/SpongeForge#1658]
I am currently running...

SpongeForge version: spongeforge-1.11.2-2393-6.1.0-BETA-2463
Forge version: forge-1.11.2-13.20.1.2393-universal
Java version: 8
Operating System:
 Linux (Ubuntu, Debian, Fedora, etc)
 macOS
 Windows
Plugins/Mods: Actually Additions, AdventureMMO, Better Achievements, BiblioCraft, Biomes O' Plenty,
BiblioWoodBoP, Buycraft, Chisels & Bits, Fast Leak Decay, FTBUtilities, FTBLib, Grim Pack, Hardcord ORE,
Industrial Craft 2, Iron Chest, Just Enough Items, JourneyMap, LuckPerms, MalisisCore, MalisisDoors, Malisis Switches, Mantle, MineColonies, MMCReboot, Morpheus, Multi-Hotbar, NuclearCraft, OreAlerts,
Tinkers Construct, Tinkers Tool Leveling, UltimateCore, Vending, waila, What Are You Looking At, WorldEdit

What is the expected result?
To be able to click between 'pages' for medium and large crates and to be able to toggle filtering options in advanced item lasers.

What is the current result?
Neither of these things happen ... literally nothing happens when pressing the GUI buttons in question. Tested with the exact same mods above but single player (so client only forge rather than server side spongeforge) and they work perfectly.

**Comment by Zidane** [comment]
https://github.com/SpongePowered/SpongeForge/issues/1602

**Comment by cyberdjinn** [comment]
Sorry, I tried looking for this already being reported and missed it.
