### ISSUE TITLE
Sponge 1.10.2 causes server to crash

### ISSUE THREAD

**Issue by Crueldog** [SpongePowered/SpongeForge#1659]
Hello,

I installed Sponge today, got the latest 1.10.2 build 1.10.2-2281-5.2.0-BETA-2464 , and even tried with an older one 1.10.2-2281-5.2.0-BETA-2456, and they both crash...
Server launches properly without sponge but it dies with sponge :frowning:
I'm using latest Forge, so it shouldnt be the issue...

Log can be found here... _https://pastebin.ca/38441272_  **https://gist.github.com/Crueldog/f9a19e2facc9f6b2762eab5f673f46f3**
If anyone could help, it'd be very nice cause we really want Sponge on our servers!

Thank you

**Comment by phit** [comment]
paste doesn't work, use https://gist.github.com/

**Comment by xTramitx** [comment]
New Link will be provided shortly sorry.

**Comment by Crueldog** [comment]
Apologies... It worked... Then stopped.. Here is the new link using the provider you suggested:
https://gist.github.com/Crueldog/f9a19e2facc9f6b2762eab5f673f46f3

**Comment by Crueldog** [comment]
I found what the issue was... It clashes with the PlayerAPI mod.

**Comment by Zidane** [comment]
@gabizou 

Looks like PlayerAPI is messing with your injection here. Please investigate.

**Comment by gabizou** [comment]
@Zidane It's [this](https://github.com/SpongePowered/SpongeCommon/blob/2b828ac9c30e11a576735b81c68106aa08f072b7/src/main/java/org/spongepowered/common/mixin/core/entity/player/MixinEntityPlayerMP.java#L1010-L1029) injection that is failing. PlayerAPI is doing some bad transformations that really don't help in mod compatibility, such as [entirely replacing methods and ditching the remainder of the method itself](https://gist.github.com/gabizou/dab8709c9f04f28331016c7768b9bc59#file-gistfile1-java-L1892). The way that this is working, the only way to get SpongeForge to work with PlayerAPI in this fashion is a ~~trial by combat~~ overwriting each other's transformations.
