### ISSUE TITLE
[1.11.2-2393-6.1.0-BETA-2468] Configuration does not accept objects of type class java.util.Optional

### ISSUE THREAD

**Issue by bhi-elliot** [SpongePowered/SpongeForge#1661]
The following came up in the server log. Not sure what caused it. Perhaps something to do with Project Inventories? The only thing I can think might have been happening at the time was OP giving an item to itself (as in, from NEI perhaps). Hope this helps! Thank you for everything!
[Pastebin of just the error](https://pastebin.com/7CahQ8ii)

I am currently running:
- SpongeForge version: spongeforge-1.11.2-2393-6.1.0-BETA-2468
- Forge version: forge-1.11.2-13.20.1.2414-universal
- Java version: 1.8.0_131
- Operating System: Windows 10

Plugins (37): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, FoamFixCore, ccl-entityhook, AdventureMMO, BiblioCraft, Biomes O' Plenty, BiblioWoodBoP, BiblioWoodForestry, BuildCraft Lib, BuildCraft, BC Builders, BC Energy, BC Factory, BC Robotics, BC Silicon, BC Transport, CodeChicken Lib, FoamFix, IndustrialCraft 2, Just Enough Items, Forestry, FoxCore, FoxGuard, Iron Chest, LuckPerms, Not Enough Items, Nucleus, Project Core, Project Inventories, Project Portals, Project Worlds, WorldEdit

**What is the expected result?**
No error.

**What is the current result?**
Error and I believe the item did not get created.

fml-server-latest.log and server.log: https://gist.github.com/bhi-elliot/0ca94c17c184974f791928de907ebcb1

**Comment by Zidane** [comment]
This isn't a Sponge bug, go report this to ProjectInventories.
