### ISSUE TITLE
Server Crash [1.10.2]

### ISSUE THREAD

**Issue by HeberonYT** [SpongePowered/SpongeForge#1663]
**I am currently running...**

- SpongeForge version: spongeforge-1.10.2-2281-5.2.0-BETA-2464.jar
- Forge version: 12.18.3.2281
- Java version: 1.8.0_111
- Operating System:

 - [x] Linux (Ubuntu, Debian, Fedora, etc)

- Plugins/Mods: 
spongeforge-1.10.2-2281-5.2.0-BETA-2464.jar
plugin-Prism-3.0.0-beta2-45-gfbbeb2b.jar

**What is the current result?**
It seems that there is an incompatibility between Sponge and Prism, the server crashes suddenly.

CrashReport: https://pastebin.com/raw/5nsqd3ZQ

**Comment by Deamon5550** [comment]
Your server timed out, either raise the max tick time or don't perform such large operations all at once.

**Comment by ryantheleach** [comment]
Considering this is prism, was it a large rollback? or a stalled database transaction on the main thread or something?
