### ISSUE TITLE
Some mobs crashing the server

### ISSUE THREAD

**Issue by kaal-1** [SpongePowered/SpongeForge#1664]
- SpongeForge version: 1.10.2-2281-5.2.0-BETA-2464
- Forge version: 2281
- Java version: 8

- Operating System:
 - [x] Linux (Debian 8)

- Crash:
https://hastebin.com/ohugajopun.http

**Comment by Zidane** [comment]
@gabizou , fix this please.

**Comment by phit** [comment]
hey, its this crash again, see https://github.com/SpongePowered/SpongeForge/issues/1467 
this time a zombie is damaging the villager, I'm mainly confused because I couldn't reproduce this myself just a few days ago on the same Sponge version

**Comment by gabizou** [comment]
Duplicate of #1467
