### ISSUE TITLE
Quantum Quarry DIM Lag

### ISSUE THREAD

**Issue by Keaton1188** [SpongePowered/SpongeForge#1666]
Hi all, we have been recently experience massive lag coming from the Quantum Quarry DIM, we have tried resetting it but this did not help as the lag just came back.

https://timings.aikar.co/?id=008b9ecb753b45239c4731c89a39b80a

Minecraft: 1.10.2
SpongeAPI: 5.2.0-SNAPSHOT-c675e80
SpongeForge: 1.10.2-2281-5.2.0-BETA-2464
Minecraft Forge: 12.18.3.2316

**Comment by Time6628** [comment]
It's an issue with the mod https://github.com/rwtema/extrautilities/issues/1224

**Comment by bloodmc** [comment]
This is not a SpongeForge issue, refer to the ticket above.
