### ISSUE TITLE
[SpongeForge 1.12] Failed to load whitelist

### ISSUE THREAD

**Issue by EmanYm** [SpongePowered/SpongeForge#1668]
SpongeForge 1.12 2397 7.0.0 beta 2474
Forge 1.12 14.21.1.2419
Java 8
Some flavour of Linux

Everything is in the hastebin
https://hastebin.com/oliqebohuy.sql

**Comment by gabizou** [comment]
Delete the whitelist and restart? Sponge doesn't alter the whitelist file, so more than likely just a random fluke when the whitelist was saving the last time and it didn't save fully (resulting in a 0 byte size file).

**Comment by EmanYm** [comment]
I never turned on whitelisting.  It's been doing this since the fresh server install.

**Comment by phit** [comment]
hastebin is deleted, and can't reproduce this with spongeforge-1.12.2-2503-7.0.0-BETA-2716

**Comment by phit** [comment]
Closing this for now. If this is still an issue for you, please let us know and provide relevant new info e.g. which mods are required to reproduce this.
