### ISSUE TITLE
AbstractMethodError: getCause on FML lifecycle events.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeForge#1671]
https://gist.github.com/ryantheleach/ac40786a3a019a16ad0d3cd900b9e925
``java.lang.AbstractMethodError: Method net/minecraftforge/fml/common/event/FMLLoadCompleteEvent.getCause()Lorg/spongepowered/api/event/cause/Cause; is abstract
``

FML Game lifecycle events have an abstract getCause

Relatively minor error, but logging it to track. Not affecting me negatively, so feel free to close if new cause refactor dodges this.

**Comment by gabizou** [comment]
Versions?

**Comment by ryantheleach** [comment]
Tested on a recent bleeding. can give exact git hash when I get home if needed.

**Comment by phit** [comment]
related to https://github.com/SpongePowered/SpongeForge/issues/1154

**Comment by Zidane** [comment]
https://github.com/SpongePowered/SpongeForge/commit/1bdfe64539910c5597cbf052907e07b3cdd16fb7
