### ISSUE TITLE
Tinker's Construct missing events 

### ISSUE THREAD

**Issue by iLefty** [SpongePowered/SpongeForge#1674]
GriefPrevention can't protect some weapons from Tinker's Construct. Players can damage mobs and another players in regions. But they must be outside of claim. So, if you stay in wilderness and use small arms (crossbow, shuriken, bow, etc.) on player (another entity), which staying in region, then he will get damage from you. 
Yes, this works if flags on damage false and PvP disable.
And all frypan can damage players in region if you use Right-click. This can fix with flag interact-item-secondary false.

**Comment by Zidane** [comment]
Go and open an issue on the GP issue tracker.

**Comment by iLefty** [comment]
@Zidane bloodshot said, that this issue must be on SF github.

**Comment by Zidane** [comment]
Then update the OP to use our template or re-create the issue and use our template instead of removing all of it.

**Comment by phit** [comment]
there is already a bug for that mod and firing events anyway https://github.com/SpongePowered/SpongeForge/issues/1209

**Comment by iLefty** [comment]
So, for 6 mounth no fix?
