### ISSUE TITLE
Errors in log [1.10.2]

### ISSUE THREAD

**Issue by kasdo** [SpongePowered/SpongeForge#1676]
Errors: https://hastebin.com/idofiboluj.rb
spongeforge-1.10.2-2281-5.2.0-BETA-2464
![image](https://user-images.githubusercontent.com/7419546/28592595-388e7612-7192-11e7-9553-9db3175223cd.png)

**Comment by kashike** [comment]
Full log file, please.

**Comment by kasdo** [comment]
Full log is too big
https://hastebin.com/oziroguruk.rb

**Comment by kashike** [comment]
Please use the issue template provided when opening an issue, as well as providing a *full* log file.

**Comment by FiveEYZ** [comment]
use http://paste.ubuntu.com/
