### ISSUE TITLE
YUNoMakeGoodMap compatibility

### ISSUE THREAD

**Issue by kaal-1** [SpongePowered/SpongeForge#1680]
**I am currently running...**
- SpongeForge version: spongeforge-1.10.2-2281-5.2.0-BETA-2464
- Forge version: 2281
- Java version: 8
- Operating System:
Debian 8
- Plugins/Mods: 
YUNoMakeGoodMap-1.10.2-6.1.0.26
**What is the expected result?**
The server not crash.
**What is the current result?**
The server crashes when I enter the nether (I have a pregenerated overworld, but if I delete it, it crashes in the overworld either).

https://hastebin.com/fayabusudo.http

**Comment by ryantheleach** [comment]
This appears to be a different issue according to the stack trace then https://github.com/SpongePowered/SpongeForge/issues/1153 .

**Comment by Tylerun** [comment]
Disable sponge. Start Server. Generate map. Enable Sponge.

**Comment by kaal-1** [comment]
That fixed the crash, but the mod still is not working... Now the overworld/end/nether get generated as if the mod was not installed.

**Comment by Tylerun** [comment]
Go into server properties and verify the world-type is set to VOID and also configure the yunomakegoodmap config to whatever tree spawn you want.
