### ISSUE TITLE
Crash when start server

### ISSUE THREAD

**Issue by 5igm** [SpongePowered/SpongeForge#1683]
**I am currently running...**

- SpongeForge version: spongeforge-1.11.2-2393-6.1.0-BETA-2471
- Forge version: forge-1.11.2-13.20.1.2393-universal
- Java version: jre1.8.0_144
- Operating System:

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows

- Plugins/Mods: 
![1](https://user-images.githubusercontent.com/11610914/28748620-8dda9c36-74bc-11e7-9ef9-a8c93ddf3934.jpg)
**What is the expected result?**
Server stops crash
**What is the current result?**
Server crash automatically

[crash-2017-07-30_06.15.48-server.txt](https://github.com/SpongePowered/SpongeForge/files/1185302/crash-2017-07-30_06.15.48-server.txt)
[fml-server-latest.txt](https://github.com/SpongePowered/SpongeForge/files/1185304/fml-server-latest.txt)
[latest.txt](https://github.com/SpongePowered/SpongeForge/files/1185303/latest.txt)

**Comment by bloodmc** [comment]
com.amict.blockmonitor.BlockMonitor.onServerStart(BlockMonitor.java:106)

This is causing the issue, remove it.
