### ISSUE TITLE
Error Ticking block entity

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1686]
**I am currently running...**

- SpongeForge version: 1.10.2-2281-5.2.0-BETA-2464-5.2.0-BETA-2464
- Forge version: 1.10.2-2281-5.2.0-BETA-2464
- Java version: 1.8.0_131
- Operating System: 

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

Crash report: https://hastebin.com/ludopotane.scala

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/SpongePowered/SpongeCommon/commit/6c750b36f6c292288c62818a05bbb4bd7163f1b6
