### ISSUE TITLE
Log-Spam (BUG)

### ISSUE THREAD

**Issue by madsenbassen** [SpongePowered/SpongeForge#1688]
**I am currently running...**
- SpongeForge version:  1.11.2-2393-6.1.0-BETA-2484
- Forge version: 13.20.1.2393
- Java version:  8
- Operating System:
 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: 
![image](https://user-images.githubusercontent.com/15655397/28799669-d24fe900-7649-11e7-9ffa-0fda56d1011c.png)

<-LOG->
https://gist.github.com/madsenbassen/2a400034bf1b2c479f7f96e3af92c821

**Comment by axle2005** [comment]
Block Monitor is broken... this honestly sounds like there is a problem with your config for the plugin.
