### ISSUE TITLE
Modded entity interaction not working

### ISSUE THREAD

**Issue by Karagra** [SpongePowered/SpongeForge#1689]
**I am currently running...**
- SpongeForge version: spongeforge-1.12-2397-7.0.0-BETA-2486
- Forge version: forge-14.12.1.2428
- Java version: 1.8.0
- Operating System: Windows
 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows
- Plugins/Mods: 
Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, CreativeCoreDummy, LittleTilesCore, SpongeAPI, SpongeForge, FoamFixCore, AntiWDL, Boop, CreativeCore, CustomNPCs, Enjin Minecraft Plugin,  FastAsyncWorldEdit, WorldEdit, FoamFix, LittleTiles, LuckPerms, Nucleus, MagiBridge, NPCs, Thut Core, In-game NBTEdit - Pokecube Edition, Pok�cube Core, Pokecube Model Loader, Thut's Wearables, Thut's Bling, Pok�cube Revival, Pok�cube Mobs, Pokecube Movess, Pokecube Origin, Pokecube Compat, Pokecube Mystery Dungeon, Pokecube Alternative, Pokecube Alternative Server Companion, Pokecube Server Utils
**What is the expected result?**
a gui is supposed to appear when the mob is right clicked
**What is the current result?**
no gui appears when the mob is right clicked

Additional Info: 
the modded entity interaction in question does so by listening for PlayerInteractEvent.EntityInteractSpecific

**Comment by Thutmose** [comment]
This issue is cause by SpongeCommon's edits to NetHandlerPlayServer.

Here is what SpongeCommon does during the CPacketUseEntity handling of INTERACT_AT:

https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/mixin/core/network/MixinNetHandlerPlayServer.java#L646-L659

```Java
                if (packetIn.getAction() == CPacketUseEntity.Action.INTERACT_AT) {
                    SpongeCommonEventFactory.lastSecondaryPacketTick = SpongeImpl.getServer().getTickCounter();
                    Vec3d hitVec = packetIn.getHitVec();
                    Optional<Vector3d> interactionPoint = hitVec == null ? Optional.empty() : Optional.of(VecHelper.toVector3d(hitVec));
                    // Is interaction allowed with item in hand
                    if(SpongeCommonEventFactory.callInteractItemEventSecondary(this.player, itemstack, hand, interactionPoint, entity).isCancelled()) {
                        return;
                    }
                    if (!SpongeCommonEventFactory.callInteractEntityEventSecondary(this.player, entity, packetIn.getHand(), interactionPoint).isCancelled()) {
                        // If INTERACT_AT returns a false result, we assume this packet was meant for interactWith
                        if (entity.applyPlayerInteraction(this.player, packetIn.getHitVec(), hand) != EnumActionResult.SUCCESS) {
                            this.player.interactOn(entity, hand);
                        }
                    }
```

Whereas here is what minecraft forge does at the same place:
```Java
                if (packetIn.getAction() == CPacketUseEntity.Action.INTERACT)
                {
                    EnumHand enumhand = packetIn.getHand();
                    ItemStack itemstack = this.playerEntity.getHeldItem(enumhand);
                    this.playerEntity.interact(entity, itemstack, enumhand);
                }
                else if (packetIn.getAction() == CPacketUseEntity.Action.INTERACT_AT)
                {
                    EnumHand enumhand1 = packetIn.getHand();
                    ItemStack itemstack1 = this.playerEntity.getHeldItem(enumhand1);
                    if(net.minecraftforge.common.ForgeHooks.onInteractEntityAt(playerEntity, entity, packetIn.getHitVec(), itemstack1, enumhand1)) return;
                    entity.applyPlayerInteraction(this.playerEntity, packetIn.getHitVec(), itemstack1, enumhand1);
                }
```

The important thing is the `net.minecraftforge.common.ForgeHooks.onInteractEntityAt(playerEntity, entity, packetIn.getHitVec(), itemstack1, enumhand1)` which allows mods to perform location specfic interaction for entities, and override default interactions by cancelling the event.

I believe your edits are ignoring the `CPacketUseEntity.Action.INTERACT` case entirely, as it appears you call the player's interaction where forge calls the entities interaction instead.

**Comment by bloodmc** [comment]
@Thutmose Thanks. However, ignoring the packet isn't an issue as I call the same method if the result of applyPlayerInteract fails. The actual issue is that I'm not handling EntityInteractSpecific event in my forge event factory. I'll push a fix in a moment.

**Comment by bloodmc** [comment]
@Karagra @Thutmose please confirm this issue is resolved in latest build

**Comment by Thutmose** [comment]
It appears to be resolved, at least when testing on single player.

**Comment by Karagra** [comment]
Everything is working fine on a multiplayer server thank you again.
