### ISSUE TITLE
AE2 mod unloading cause's ID change in level.dat

### ISSUE THREAD

**Issue by runescapejon** [SpongePowered/SpongeForge#1690]
**I am currently running...**

- SpongeForge version: 1.10.2-2281-5.2.0-BETA-2482
- Forge version: 1.10.2-12.18.3.2422
- Java version:  java 8

- Operating System:
 - [X] Linux (Ubuntu, Debian, Fedora, etc)

- Plugins/Mods: 
https://gyazo.com/874da3f926f5f99d3df2d6a987cf05ed
**What is the expected result?**
Blocks/item id change in level.dat
**What is the current result?**
Id's are being change whenever someone make an Pattern terminal or an m.e system in general, 
stop the server when your next too it and boom level.dat Id's change it seem to have been reported to the mod dev github but he does not care about sponge  :(

server logs https://pastebin.com/qQ7WdYZV
and here if it help https://pastebin.com/pN5ATGjV

**Comment by ryantheleach** [comment]
Are you 100% sure that it's related to AE2 and only reproducible when using Sponge?

We have had a number of reports about this issue, it would be great to nail it down to an exact mod combination that is incompatible, but I'm skeptical considering the size of your mod list.

You (or someone else) needs to run your reproduction steps using only SpongeForge, AE2, and whatever modifications are necessary to get the 2 to run together.

**Comment by runescapejon** [comment]
yes it only happen when spongeforge is installed

**Comment by FiveEYZ** [comment]
Tested on forge-1.12-14.21.1.2428-universal:

Installed mods:
applied-llamagistics-1.12-rv5-beta-3
RedstoneFlux-1.12-2.0.1.2-universal
spongeforge-1.12-2397-7.0.0-BETA-2486

[![Screenshot from Gyazo](https://gyazo.com/57d823e5d23660212435e1423e5f5d3c/raw)](https://gyazo.com/57d823e5d23660212435e1423e5f5d3c)
Steps to reproduce:
-  go creative mode and get:
1x Creative Energy Cell
1x Energy Acceptor
1x Me Glass Cable
1x ME Crafting Terminal
1x ME Drive
1x 4k Storage Cell
4x 64 Fluix crystal
-  Open the Terminal and put everything inside it
-  Take the Fluix crystal in 2x2 crafting pattern and shift-click craft 64x Fluix Block
-  Put them inside the Terminal
- Do /stop

Here is the log where I did everything described above:
https://gist.github.com/FiveEYZ/17e6e196ab9a7bd1cfb5f3031aafeb4d

**Comment by FiveEYZ** [comment]
Did some more testing with above setup:

numbers are how many /stop i did
2 x  with ME Crafting Terminal in place = error
2 x  with ME Crafting Terminal removed = no error
1x  with ME Crafting Terminal in place again = error
2 x  with ME Crafting Terminal removed = no error

**Comment by thiakil** [comment]
Judging by the stacktraces, it's to do with the CableBus TE marking itself for update when the network goes down, in order to trigger lighting updates.

As a note, the traces proceeded by `[Server thread/ERROR] [AE2:S]: [AppEng] Network Event caused exception:` should be ones that are caught and just logged by the `catch`

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/SpongePowered/SpongeCommon/commit/62452f30a8641ab9418a1631079151771b7090c9

**Comment by runescapejon** [comment]
@bloodmc you think you can backport this fix to 1.10.2 greatly appreciated the fix

**Comment by ryantheleach** [comment]
Wait, really? Disabling async lighting during server stop, fixes ID's changing in level.dat when used with Ae2?

Would love to have some insight into how.

**Comment by runescapejon** [comment]
I guess so xD I tested this and it really work 
i would love to know why does this work 0.0

**Comment by LazerCorn3114** [comment]
Can you back port the fix to 1.10.2 BELUUHED. I'm having the same problem.

**Comment by darkwolf2590** [comment]
Can you back port it to 1.10.2? As well as releasing the Jar.? Having the exact same problem as these handsome gentlemen. Would be greatly appreciated, cheers!

**Comment by runescapejon** [comment]
@LazerCorn3114  @darkwolf2590  there is already a fix here the jar 
http://files.minecraftforge.net/spongepowered

**Comment by JBYoshi** [comment]
That download page is outdated. Use https://spongepowered.org/downloads instead.

**Comment by runescapejon** [comment]
@JBYoshi  it's not outdated
![0fb5fd5c6dd3b4eee11a340cd8034ff7](https://user-images.githubusercontent.com/10858509/28990696-dafeb0f2-794d-11e7-8d8f-110e67d345fd.png)

**Comment by FiveEYZ** [comment]
will this fix come to 1.12.1 to?
