### ISSUE TITLE
1.12 Sponge Crash

### ISSUE THREAD

**Issue by Jay9519** [SpongePowered/SpongeForge#1692]
as discussed in the discord, I removed MalisisCore and Malisisdoors from my mod pack
but unfortunately the crash still exists

**I am currently running...**
- SpongeForge version: 1.12-2397-7.0.0-BETA-2486
- Forge version: 1.12-14.21.1.2443
- Java version: 1.8
- Operating System: Windows 10

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x ] Windows

Pastebin link:

https://pastebin.com/S4Na9m2H

**Comment by bloodmc** [comment]
dupe #1678
