### ISSUE TITLE
Spongeforge incompatible with Moving World

### ISSUE THREAD

**Issue by Shadowreaper666** [SpongePowered/SpongeForge#1694]
**I am currently running...**

- SpongeForge version: 1.12-2443-7.0.0-BETA-2494
- Forge version: 1.12-14.21.1.2443
- Java version: Java 8 U 121
- Operating System:

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [X] Windows

- Plugins/Mods: 
No plugins
Mods:
Spongeforge
Moving World
**What is the expected result?**
The server starts and Moving world and spongeforge both start successfully.
**What is the current result?**
The server starts but spongeforge never loads into the server.

Running the server with Sponge and Moving world- https://gist.github.com/Shadowreaper666/7513543b44730919738fa087d33ce854  

Running the server with only sponge - https://gist.github.com/Shadowreaper666/eb406987d3321268cd41fafda9348526

Runnign the server with only Moving world- https://gist.github.com/Shadowreaper666/6317490446234716654d9bd51b69d31c

**Comment by Aaron1011** [comment]
The important log line is https://gist.github.com/Shadowreaper666/7513543b44730919738fa087d33ce854#file-gistfile1-txt-L20. MovingWorld is loading before Sponge, and loading an older version of Mixin than Sponge supports. 

Unfortunately, the exception thrown by Mixin was supressed, making this much harder to spot than it needed to be. I've opened https://github.com/SpongePowered/Mixin/issues/203 to fix this.

Renaming your sponge jarfile to `_spongeforge-1.12-2443-7.0.0-BETA-2494.jar` will fix the issue, by causing Sponge (and therefore Sponge's Mixin version) to be loaded first.
