### ISSUE TITLE
Exception during phase body

### ISSUE THREAD

**Issue by Coolfeather2** [SpongePowered/SpongeForge#1695]
**I am currently running...**

- SpongeForge version: 1.10.2-2281-5.2.0-BETA-2464 
- Forge version: 12.18.3.2281        
- Java version: 1.8.0_131
- Operating System:

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: 
`Plugins (90): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, Applied Energistics 2 Core, OpenComputers (Core), SpongeAPI, SpongeForge, CoFH ASM, ccl-entityhook, Applied Energistics 2, Ars Magica 2, AnimationAPI, CodeChicken Lib, Avaritia, Baubles, Guide-API, Blood Magic: Alchemical Wizardry, Blood Arsenal, Botania, CoFH Core, Brandon's Core, BungeeTabListPlus-SpongeBridge, CodeChicken Core, DrZhark's CustomSpawner, Draconic Evolution, DrZhark's Mo'Creatures Mod, EnderCore, Ender IO, Extra Utilities 2, Zero CORE, Extreme Reactors, Faster Ladder Climbing, IndustrialCraft 2, Forestry, Forge Multipart CBE, Forge Microblocks, Minecraft Multipart Plugin, Gravestone Mod, Harvest, iChunUtil, Hats, Mantle, Tinkers' Construct, Immersive Engineering, Industrial Wires, Inventory Pets, Iron Chest, Long Fall Boots, LuckPerms, MCMultiPart, Mekanism, MekanismGenerators, MekanismTools, mercurius_updater, MineFactory Reloaded, MFR Compat: Vanilla, MorePlayerModels, Morpheus, MrTJPCore, MultiChat Sponge, Natura, Nether Core, OpenComputers, p455w0rd's Library, SonarCore, Practical Logistics 2, ProjectRed Core, ProjectRed integration, ProjectRed Transmission, ProjectRed Fabrication, ProjectRed Illumination, ProjectRed Expansion, ProjectRed Transportation, ProjectRed Exploration, Thermal Foundation, Thermal Expansion, Redstone Arsenal, Roots, Realistic Terrain Generation, Sync, Tails, Thermal Dynamics, TorchMaster, Vein Miner, Mod Support, I Can See Everything, What Are We Looking At, Wireless Crafting Terminal 2, Experience Rings`
**What is the expected result?**
Damage mobs
**What is the current result?**
Can't Damage mobs while holding nothing

Seems to be a problem with 'Exception during phase body'
`Something happened trying to run the main body of a phase org.spongepowered.common.event.tracking.phase.packet.AttackEntityPacketState`

https://gist.github.com/Coolfeather2/6fbf08a344794e5eb5989d9232bded6a

**Comment by gabizou** [comment]
Since the majority of the log is just startup: providing a [gist](https://gist.github.com/gabizou/5bd54715b9a9902d38f49ca8c88100e2) of the actual exceptions. The exception doesn’t seem to be from sponge but from Blood Arsenal.

**Comment by gabizou** [comment]
But in [BloodArsenal](https://github.com/Arcaratus/BloodArsenal/blob/1.10/src/main/java/arc/bloodarsenal/util/handler/EventHandler.java#L87), the item in hand is not being null checked, causing the error to occur. Presumably the item in hand is indeed an empty item, and some update or something didn’t get ported to 1.10.2 correctly where the item is not null checked. Thanks for the report! Probably want to ping @Acaratus to get a fix released.

**Comment by Coolfeather2** [comment]
Thanks, I shortened the Log and will let him now
