### ISSUE TITLE
Error trying to start up the server

### ISSUE THREAD

**Issue by Jay9519** [SpongePowered/SpongeForge#1696]
**I am currently running...**
- SpongeForge version: spongeforge-1.12.1-2444-7.0.0-BETA-2500
- Forge version: forge-1.12.1-14.22.0.2444-universal
- Java version: 
- Operating System: windows 10 and Linux
 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows

Server won't start up and won't give me a crash report or anything about it in the latest.log

https://www.dropbox.com/s/zr5ld7cegwdgaik/error.png?dl=0

**Comment by stephan-gh** [comment]
You need to run the Forge installer again after updating to a new Minecraft version. It is not enough to simply download the new `-universal.jar`.
