### ISSUE TITLE
(1.11.2) RFTools: New dims do not show up in dialing device and cannot be deleated

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1699]
I am not entirely sure who's end this is on so I figured I'd post this here as well.

Link to the RFTools bug report: https://github.com/McJty/RFTools/issues/1323

There is some strange interaction happening between sponge and the way rftools loads dimensions.

**Comment by bloodmc** [comment]
SF 1.11.2 build 2393 is an old build. Update to latest SF and try again

http://files.minecraftforge.net/maven/org/spongepowered/spongeforge/index_1.11.2.html

Make sure you provide the proper information such as fml-server-latest.log

**Comment by ghost** [comment]
Misread the version number because I'm a dumbass.

We're actually on version 2499. I will give 2507 a shot and drop a log in here once I get some coffee in my system.

Edit: Alright, I've thrown in the latest version and regenerated my configs for good measure.

I am now unable to dial any of my rftools dimensions. The dialing device throws an invalid destination error.

Newly created rftools dimensions still do not show up in the dialing device when created.

Forge log: https://mega.nz/#!9d1WyCjL!4DscM7l7iwyF37NuAcRqmgZjk7iSZCrjhVsflg8gTcg

**Comment by bloodmc** [comment]
@PsionicArchon Please test latest 1.10.2 SF and confirm if this issue is present there as well.

**Comment by ghost** [comment]
Nope, all is well on the 1.10.2 version. I was able to see and teleport into a newly created dimension.

Edit: Belay that, all is not well. While the first dimension worked perfectly fine, subsequent dimensions cannot be seen by the dialing device.

Forge log: https://mega.nz/#!hAlnEbgb!fdmb1uBPww-iiOjAJJRCShUrme7mkRSmxLqjxWvkM34

**Comment by bloodmc** [comment]
@PsionicArchon Please provide a test 1.10.2/1.11 test world with everything setup so I may reproduce the issue. Make sure to only use rftools with a fresh world so its small. Also provide steps on what to do as I don't play these mods.

**Comment by ghost** [comment]
Sponge version: 2517

World/server/everything you need: https://mega.nz/#!0E801ZRa!6s9aNVW0sxlQjC8feXjljYewYmrCpAQc-z9HNASK0XM 

Only RFTools, RFTools dimensions. and JEI were used. All of the machines and necessary materials have already been set up. There are also signs placed in game with some basic instructions on how dimensions work.

Steps:

1.) Grab a blank dimension card from the chest
2.) Insert dimension tab into the dimension inscriber's lower left hand slot, name it, and hit store.
This will create a dimension with the id 2. 
3.) Place dimension inside of the dimension builder and allow it to charge up.
4.) Access the dialing device, select the transmitter (upper most entry), then select the newest entry (the world you just created) and hit dial.

If everything goes will you should see a green beam of light emanating from the transmitter. You can step through if you want but you're going to need a way to get back out of the dimension.

For some reason, the first dimension you create works perfectly fine now.

5.) Grab a new blank dimension tab and insert that into the dimension inscriber.
6.) Grab the digit dimlet from the chest and insert that into the dimension inscriber as well
7.) Name the dimension, hit store. and place it in the dimension builder.

When you return to the dialing device you shouldn't be able to see the new dimension at all. Any other new dimensions you create will not show up now.

**Comment by phit** [comment]
this sounds exactly like how it behaved before the big rftools fix in february https://github.com/SpongePowered/SpongeForge/commit/e47758655d863f1c53ba97a3bddbe1320260fe99

**Comment by bloodmc** [comment]
@PsionicArchon I'll test this when I get some more time as it requires setting up all the sources since the release jar doesn't work properly in dev.

**Comment by ghost** [comment]
No worries, I'll keep an eye on this for updates.

**Comment by Rahmiel** [comment]
Can confirm this fixes the first issue (I live with PsionicArchon). However a new issue has come out where any RFTools dim will now jack up resource use on the server when Sponge is installed. The server's CPU was maxing out when the dimension was teleported to. Multiple DIMs were tested and the issue went away when Sponge was removed from the server. I will make a new issue involving this.
