### ISSUE TITLE
Forge Creeper Heal is not working with SpongeForge

### ISSUE THREAD

**Issue by tgstyle** [SpongePowered/SpongeForge#1700]
It works fine with just forge. It has worked in previous versions.

**I am currently running...**

- SpongeForge version: 2498
- Forge version: 2443
- Java version: 1.8.0_144-b01
- Operating System:

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows

- Plugins/Mods: 

ForgeCreeperHeal-1.12-1.3.1 [Unofficial]

https://github.com/PrinceOfAmber/ForgeCreeperHeal/issues/3#issuecomment-320484313

**Comment by Zidane** [comment]
What is broken? We need a lot more details.

**Comment by tgstyle** [comment]
It replaces the blocks after a creeper blows up. In forge it does this fine, with sponge nothing happens.

**Comment by tgstyle** [comment]
Could this be it? 

"Note: Does not currently work with Sponge, because the Forge Explosion events don't get fired with Sponge installed."

I saw it noted on this mod.

https://minecraft.curseforge.com/projects/environmental-creepers

**Comment by phit** [comment]
Doesn't seem to work

spongeforge-1.12.2-2529-7.0.0-BETA-2741.jar
creeperheal-1.12-1.3.1.jar

Spawned creeper, let them explode, broken blocks aren't slowly replaced.
relevant sources: https://github.com/PrinceOfAmber/ForgeCreeperHeal/blob/master/src/main/java/fr/eyzox/forgecreeperheal/handler/ExplosionEventHandler.java#L14

**Comment by tgstyle** [comment]
https://github.com/SpongePowered/SpongeForge/issues/1327
