### ISSUE TITLE
Spectator tracks entities in other dimensions after a dimensional teleport using the vanilla spectator menu [video]

### ISSUE THREAD

**Issue by Polyana-Fontes** [SpongePowered/SpongeForge#1702]
Video demonstration: https://youtu.be/jkQkNTJfkDc

**I am currently running...**
- SpongeForge version: 1.11.2-2393-6.1.0-BETA-2503
- Forge version: 13.20.1.2429
- Java version: 1.8.0_144
- Operating System:
 - [X] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: 
Plugins (78): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, OpenComputers (Core), SpongeAPI, SpongeForge, ccl-entityhook, Aliases, Psi, AutoRegLib, BD Lib, Better Achievements, InfinityLib, Boatifull, Broadcast, CarrotShop, Chisel, Chisels & Bits, ClearMob, CodeChicken Lib, Cyclops Core, Colossal Chests, asielib, OpenComputers, Computronics, Cooking for Blockheads, Corail Pillar - Chisel Extension, Crafting Tweaks, CraftTweaker JEI Support, Just Enough Items, Crafttweaker, CustomNPCs, DisableSkeletonHorse, EconomyLite, Fast Leaf Decay, FoamFix, Forge Multipart CBE, Forge Microblocks, Minecraft Multipart Plugin, GriefPrevention, Holograms, Immersive Engineering, Immersive Petroleum, Inventory Tweaks, Iron Chest, Just a Few Fish, Just Enough Calculation, Laborus, Lottery, LuckPerms, Nucleus, UltimateChat, MagiBridge, MCClans, MCMultiPart, MTLib, Mod Tweaker, OpenRadio, Pam's HarvestCraft, PayDay, Ping, PixelVip, PlayerShopsRPG, RankUpper, Redstone Paste, Storage Boats Mod, Survival Tweaks, Thut Core, Thut's Tech, Gliby's Voice Chat Mod, VoxelSniper, WanionLib, What Are We Looking At, WorldEdit, WirelessRedstone-CBE, Corail Pillar, UniDict

**What is the expected result?**
See only entities in my dimension after I teleport.

**What is the current result?**
See entities in my dimension and entities in the dimension that I was before teleporting

**Comment by Aaron1011** [comment]
Can you confirm that this isn't the behavior of Vanilla?

**Comment by phit** [comment]
Tested on 1.12.2 with Sponge 2529-7.0.0-BETA-2748 and then without, this appears to be vanilla behavior. You can always see all players in the spectator menu, regardless what dimension they are in.
