### ISSUE TITLE
Java failed to write core dump - exception_access_violation

### ISSUE THREAD

**Issue by bhi-elliot** [SpongePowered/SpongeForge#1711]
Might not be a Sponge or even a Forge thing. Might be strictly Java, but I know very little.

**I am currently running...**
- SpongeForge version: spongeforge-1.11.2-2393-6.1.0-BETA-2542
- Forge version: forge-1.11.2-13.20.1.2425-universal
- Java version: 1.8.0_144-b01
- Operating System: Windows 10 64-bit
 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [X] Windows

- Plugins/Mods: Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, FoamFixCore, ccl-entityhook, AdventureMMO, BiblioCraft, Biomes O' Plenty, BiblioWoodBoP, BiblioWoodForestry, BuildCraft Lib, BuildCraft, BC Builders, BC Energy, BC Factory, BC Robotics, BC Silicon, BC Transport, CodeChicken Lib, FoamFix, IndustrialCraft 2, Just Enough Items, Forestry, Iron Chest, LuckPerms, Not Enough Items, Nucleus, Project Core, Project Inventories, Project Portals, Project Worlds, WorldEdit

**What is the expected result?**
No crash

**What is the current result?**
Crash

[fml-junk-earlystartup.log, fml-server-latest.log, and latest.log](https://gist.github.com/bhi-elliot/75964b6f5499f6c342681f8f94d52e80)

Java error log: [hs_err_pid2292.log](https://gist.github.com/bhi-elliot/cebdb96ab58659e11bb4c8ad4b6f0609)

Error when server crashed:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000000006414fc80, pid=2292, tid=0x0000000000001144
#
# JRE version: Java(TM) SE Runtime Environment (8.0_144-b01) (build 1.8.0_144-b01)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.144-b01 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# V  [jvm.dll+0xafc80]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
```

**Comment by 0f-0b** [comment]
Looks like JVM has attempted to access memory that it should not. Maybe a Java bug.

**Comment by Niko-sk2x** [comment]
I also remember getting similar-looking JVM crash when I managed to make mixin "override" interface method with already existing private method (or something like that). Could be some coremod going bad and triggering similar JVM bug.

**Comment by phit** [comment]
Most likely not a Sponge issue, if you find a way to reproduce it consistently with just Sponge. Feel free to open a new issue.
