### ISSUE TITLE
Advanced Rocketry - Space Station isn't being created

### ISSUE THREAD

**Issue by phit** [SpongePowered/SpongeForge#1715]
**I am currently running...**

- SpongeForge version: 1.10.2-2281-5.2.0-BETA-2548
- Forge version: 1.10.2-12.18.3.2281
- Java version: jre1.8.0_141

**Mods**
AdvancedRocketry-1.10.2-1.0.19
LibVulpes-1.10.2-0.1.19-universal
jei_1.10.2-3.14.7.419

**What is the expected result?**
Launching a rocket with a space station in the satellite bay will make it deploy in the space dimension.

**What is the current result?**
The space station isn't being created, and the rocket falls back to the overworld (earth).

I created a test world for this, you just have to link the rocket to the "Rocket Monitoring Station" (block with the sign on it) using the "Linker". Then press "Launch" inside the monitoring station.
https://phit.link/s/advrocket-spongetest.7z

**Possible starting points**:
[The deploying is called here](https://github.com/zmaster587/AdvancedRocketry/blob/1051f57af61070642388c4ce7d2d9063c9c6dceb/src/main/java/zmaster587/advancedRocketry/entity/EntityRocket.java#L803), which calls either [this](https://github.com/zmaster587/AdvancedRocketry/blob/1051f57af61070642388c4ce7d2d9063c9c6dceb/src/main/java/zmaster587/advancedRocketry/stations/SpaceObjectBase.java#L213) or [this](https://github.com/zmaster587/AdvancedRocketry/blob/1051f57af61070642388c4ce7d2d9063c9c6dceb/src/main/java/zmaster587/advancedRocketry/stations/SpaceObject.java#L412) and the actual block placing is done [here](https://github.com/zmaster587/AdvancedRocketry/blob/1051f57af61070642388c4ce7d2d9063c9c6dceb/src/main/java/zmaster587/advancedRocketry/util/StorageChunk.java#L522)

This is a big issue making progression in this mod impossible, which is a big deal due to this mod being in the most popular 1.10.2 pack right now namely Age of Engineering.

**Comment by bloodmc** [comment]
Linker says "nothing to be linked" and Launch does nothing. Also fuel is empty, not sure if that matters.

**Comment by phit** [comment]
shift rightclick the Monitoring  Station then rightclick the rocket

**Comment by AwesomeSeal** [comment]
Does this method solve the generation issue? I'm still not able to create a space station using SpongeForge (Same versions).

**Comment by phit** [comment]
update Sponge
