### ISSUE TITLE
BetterQuesting 

### ISSUE THREAD

**Issue by mkrtes** [SpongePowered/SpongeForge#1717]
I have a server with BetterQuesting mod and Spongeforge. Modpack "craft of the titans". Players can perform only quest with conditions "bq_standard:retrieval" (have the item in inventory)
All other conditions (hunt, craft etc.) are not met. Without Sponge all good.
This problem may be related to a sponge?

**I am currently running...**
- SpongeForge version: spongeforge-1.10.2-2281-5.2.0-BETA-2555
- Forge version: 2316
- Java version: 8
- Operating System: Linux

Mod list: https://pastebin.com/p3tyPNyi

**Comment by Aaron1011** [comment]
@mkrtes: Can you list the exact steps needed to reproduce this?

**Comment by mkrtes** [comment]
@Aaron1011 I checked, even in single player it doesn't work. I think it is not sponge problem.
