### ISSUE TITLE
Can not import worlds to server.

### ISSUE THREAD

**Issue by wunder-bread** [SpongePowered/SpongeForge#1718]
**I am currently running...**
- SpongeForge version: spongeforge-1.10.2-2281-5.2.0-BETA-2548
- Forge version: forge-1.10.2-12.18.3.2281-universal
- Java version: 1.8.0_144_b01
- Operating System:
 - [X ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows
- Plugins/Mods: Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Conquest Reforged, FastAsyncWorldEdit, HelpMe, Holograms, LuckPerms, Nucleus, PlotSquared, Project Core, Project Portals, SpongyCord, WorldEdit

**What is the expected result?**
Import worlds to server
**What is the current result?**
The world appears to migrate from server root folder to the level folder, yet are not recognized by Nucleus. Also tested with ProjectWorlds with same results.

[fml-server-latest.txt](https://github.com/SpongePowered/SpongeForge/files/1220712/fml-server-latest.txt)
[latest.txt](https://github.com/SpongePowered/SpongeForge/files/1220713/latest.txt)

**Comment by Zidane** [comment]
Upload your server installation EXACTLY the way it was before you tried to do the import. Specify EXACT steps that you did up to the error.

**Comment by wunder-bread** [comment]
SpongeForge version: spongeforge-1.10.2-2281-5.2.0-BETA-2548
Forge version: forge-1.10.2-12.18.3.2281-universal
Java version: 1.8.0_144_b01
Operating System:
[X ] Linux (Ubuntu, Debian, Fedora, etc)
Plugins/Mods: Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Conquest Reforged, FastAsyncWorldEdit, HelpMe, Holograms, LuckPerms, Nucleus, PlotSquared, Project Core, Project Portals, SpongyCord, WorldEdit.

Upload a world via FTP to my server's root folder. Change ownership of the world. Restart the server. The world migrates into the "level" folder as it should. Then via Nucleus run a /world enable. Nucleus outputs, "the world does not exist".  /world load yields the same results. Then tried removing Nucleus and put in ProjectWorlds. Same process, ran /world import, "the world does not exist". Attempted the same process with custom maps, vanilla generated maps, all with same results.

**Comment by ghost** [comment]
Sponge have /world command or any importing command for worlds? Why is this problem reported here? Why not reported to plugins (nucleus, project world) issue tracker?

**Comment by wunder-bread** [comment]
Fisrt, I have tickets with both Nucleus and ProjectWorlds. Second I'm reporting here because I'm not sure where the problem lies, as the issue manifested itself around the same time for both mods. So if it is not a problem with sponge, I'm sure a dev will explain and close this ticket. Thank you for your insightful comment.

**Comment by Zidane** [comment]
@wunder-bread Can you zip up and upload your server's files so I can work on this?

**Comment by wunder-bread** [comment]
@Zidane I emailed you the link to the zipped server files.

**Comment by wunder-bread** [comment]
@Zidane , Any update on this issue? Please and thank you.

**Comment by phit** [comment]
looks like this was figured out a long time ago https://github.com/NucleusPowered/Nucleus/issues/906#issuecomment-328144453
