### ISSUE TITLE
re: Sponge 1.10.2 causes server to crash #1659

### ISSUE THREAD

**Issue by ktole1999** [SpongePowered/SpongeForge#1721]
**I am currently running...**

- SpongeForge version: spongeforge-1.10.2-2281-5.2.0-BETA-2546 
- Forge version: forge-1.10.2-12.18.3.2281-universal
- Java version: jre1.8.0_131

- Operating System:

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ x ] Windows

- Plugins/Mods: 
PlayerAPI-1.10.2-1.1

**What is the expected result?**
no crash
**What is the current result?**
crash on start

crash log:
https://gist.github.com/ktole1999/c323a8a7e38b059612aac3a20e554edf

in reference to this: https://github.com/SpongePowered/SpongeForge/issues/1659

**Comment by bloodmc** [comment]
PlayerAPI is not supported due to the amount of changes done to the player class. You would have to ask the dev for Sponge support.

**Comment by ktole1999** [comment]
there is already sponge support as it was working fine on 1.10.2-2281-5.2.0-BETA-2353.

**Comment by Zidane** [comment]
No there isn't.

Read @gabizou 's response at the end of the issue you referenced.

**Comment by ktole1999** [comment]
i understand what was mentioned. but something in sponge changed since 2353 to cause this breakage. i dont understand how it could be playerapi fault.

**Comment by Zidane** [comment]
@ktole1999 

PlayerAPI LITERALLY REPLACES VANILLA METHODS WHOLESALE. Full stop, replaces them in their earnest. We cannot make our stuff work with PlayerAPI when the methods that everyone uses are up and replaced by one mod.

It only worked before because we had no need to inject into this method. We now do.

**Comment by ktole1999** [comment]
ok. i dont claim to understand the code or how it works. i just know it was working before and now it doesnt so i look at the last thing that changed. but since sponge changed the way it now works and is no longer compatible with playerapi then it is what it is. i will try and reachout to playerapi dev for help. thanks for the info.

**Comment by gabizou** [comment]
To be more precise as to why Sponge cannot fix the compatibility issue: Sponge is attempting to take advantage of safely and accurately injecting into a specific method to make a particular functionality work, in this case health scaling from the server side. The issue that is arising with PlayerAPI being involved is that PlayerAPI is wholeheartedly erasing the entire method, preventing Sponge from adding those necessary changes to implement such a functionality, that we cannot work around the compatibility issue from our end. The compatibility would have to be worked out from the PlayerAPI side. In my previous comment closing the previous issue, I've already stated exactly where the incompatibility lies from PlayerAPI's side of things, and pointed out what the potential solution would be, but that is all I can do as there is no repository for us to suggest any sort of changes, except commenting on the MinecraftForums thread, which [has yet to be replied to in ages when the first instance of incompatibility with Sponge came about over a year ago](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1277996-player-api?comment=1751).
