### ISSUE TITLE
Chunk unload crash

### ISSUE THREAD

**Issue by phit** [SpongePowered/SpongeForge#1722]
**I am currently running...**
- SpongeForge version: 1.10.2-2281-5.2.0-BETA-2555
- Forge version: forge-1.10.2-12.18.3.2422

started happening randomly since updating to 2555
from myself
https://gist.github.com/phit/7ca80b5e704d4d8f4a91a0eb5a1b91f5

posted by LX_Gaming on discord
https://pastebin.com/ZE60BKiG

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/SpongePowered/SpongeCommon/commit/9452c75e52be395531ef8e6504f711cb7494ae40
