### ISSUE TITLE
All The Mods Expert Mode crashes with sponge.

### ISSUE THREAD

**Issue by Jager67** [SpongePowered/SpongeForge#1725]
**I am currently running...** All The Mods Expert Mode

- SpongeForge version: spongeforge-1.10.2-2281-5.2.0-BETA-2558
- Forge version: forge-1.10.2-12.18.3.2281-universal
- Java version: 1.8.0_144
- Operating System:

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - ["X"] Windows

- Plugins/Mods: 
Mod List: https://docs.google.com/spreadsheets/d/1fXRhaJmBV-ViBr1N91DHwXjvguGEhz0wU4szATPDHYE/edit?usp=sharing

**What is the expected result?**
Using: https://github.com/Stonebound/Applied-Energistics-2
Tried: https://forums.spongepowered.org/t/spongebootstrap-fixes-ordering-issue-with-other-coremods/12275

**What is the current result?**

Heres my log please if anyone has any info to help please do.
https://pastebin.com/t1HXKZB6

**Comment by phit** [comment]
remove classcachetweaker

**Comment by bloodmc** [comment]
thanks @phit
