### ISSUE TITLE
Error when running pixelmon

### ISSUE THREAD

**Issue by Pokekhan** [SpongePowered/SpongeForge#1728]
**I am currently running...**

- SpongeForge version: 1.10.2-2281-5.2.0-BETA-2558
- Forge version: 12.18.3.2316
- Java version: 8
- Operating System:

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: 
[Server thread/INFO]: Plugins (33): [m[0;32;1mMinecraft[m, [m[0;32;1mMinecraft Coder Pack[m, [m[0;32;1mForge Mod Loader[m, [m[0;32;1mMinecraft Forge[m, [m[0;32;1mSpongeAPI[m, [m[0;32;1mSpongeForge[m, [m[0;32;1mCrazyEffect[m, [m[0;32;1mEconomyLite[m, [m[0;32;1mHuskyUI[m, [m[0;32;1mHuskyCrates[m, [m[0;32;1mLuckPerms[m, [m[0;32;1mNucleus[m, [m[0;32;1mPixelmon[m, [m[0;32;1mOblique Core[m, [m[0;32;1mOblique Sponge Core[m, [m[0;32;1mPixel Auction[m, [m[0;32;1mPixel Extras[m, [m[0;32;1mPixelMoney[m, [m[0;32;1mPixelQuests[m, [m[0;32;1mPixelUpgrade[m, [m[0;32;1mPocketTags[m, [m[0;32;1mPocketTokens[m, [m[0;32;1mPokestop[m, [m[0;32;1mOblique's Poller[m, [m[0;32;1mOblique's Portals[m, [m[0;32;1mRazzle Dazzle Cosmetics[m, [m[0;32;1mRazzle Dazzle Cosmeticssponge[m, [m[0;32;1mSpongeMarket[m, [m[0;32;1mSpongeSkull[m, [m[0;32;1mTM Trade[m, [m[0;32;1mTournaments[m, [m[0;32;1mHiroku's Trivia[m, [m[0;32;1mWondertrade[m

**What is the expected result?**

**What is the current result?**
Console getting spammed. When running pixelmon on one of my server with the latest version of spongeforge and forge. 

Here what i get: https://hastebin.com/ikewamozob.md

**Comment by bloodmc** [comment]
Caused by: java.lang.NoSuchMethodError: com.pixelmonmod.pixelmon.entities.pixelmon.EntityStatue.initAnimation()V
        at com.pixelmonmod.pixelmon.entities.pixelmon.EntityStatue.init(EntityStatue.java:75) ~[EntityStatue.class:?]

Not our issue.

**Comment by EmanYm** [comment]
Didn't Pixelmon stop development on MC 1.10.2/API 5?  There are bound to be some breaking changes between that and 1.12/API 7.

I think if you insist on running Pixelmon you're going to have to leave that server as 1.10.2.
