### ISSUE TITLE
Fluid tracker crash

### ISSUE THREAD

**Issue by kaal-1** [SpongePowered/SpongeForge#1732]
**I am currently running...**
- SpongeForge version: 1.10.2-2281-5.2.0-BETA-2569
- Forge version: 2281
- Java version: 8
- Operating System: Debian 8

Whenever a player enters my server and loads a chunk containing any block that causes the fluid tracker to function, the server crashes. This doesn't happen if I downgrade to 1.10.2-2281-5.2.0-BETA-2567
Examples:
EnderIO Fluid conduits: https://hastebin.com/atuyeyoval.http
EnderStorage ender tank: https://hastebin.com/iruyerisef.http

**Comment by tgstyle** [comment]
Also happens in 1.12.1-7.0.0-BETA-2568 with ThermalDynamics
https://gist.github.com/tgstyle/686a672988c8743b20f107a6b4cb1d95

**Comment by tgstyle** [comment]
1.12.1-7.0.0-BETA-2568 also causes this crash with Mekanism
https://gist.github.com/tgstyle/e59c9ee4458dbfd746ba85b113023c17

**Comment by HenryLoenwind** [comment]
It seems this code ASMs a call to a tracker method to all methods that have the same name and signature as the tracker method without checking if they belong to a class that is compatible with the first parameter of the tracker methods.

PS: What do you want to track anyway? This approach will get you all kinds of noise from mod-internal redirects, block-private internal tanks and so on. if you want to track fluids and items transferred between blocks you better wrap the capability objects that are returned from TE.getCapability()...

**Comment by Cybermaxke** [comment]
I am working on the issue, I will get back to it later today.

**Comment by Cybermaxke** [comment]
@bloodmc Any idea about wrapping the capabilities?

**Comment by tgstyle** [comment]
Sponge 2577 still has the issue with Mekanism

**Comment by PurpleIsEverything** [comment]
Here is a server log with more information, keep in mind this log contains a variety of mods and a few ASM and Mixin patches.

https://gist.github.com/ShadowKitten/92b77705610d951e5a5d0282a205d1e5

As this is the normal configuration of our servers this is how it was tested we will not be removing these things.

**Comment by bloodmc** [comment]
Fixed in https://github.com/SpongePowered/SpongeCommon/commit/524254046b6c9440d1a43d8623ff06db9edd1ac7
