### ISSUE TITLE
MySQL driver error?

### ISSUE THREAD

**Issue by PixelmonPRO** [SpongePowered/SpongeForge#1735]
**I am currently running...**
- SpongeForge version:  1.10.2-2281-5.2.0-BETA-2567, 1.10.2-2281-5.2.0-BETA-2569, 1.10.2-2281-5.2.0-BETA-2571
- Forge version: forge-1.10.2-12.18.3.2422-universal
- Java version: 1.8.0_121
- Operating System: Debian 8 Jessie 64 bit

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

Version 1.10.2-2281-5.2.0-BETA-2567 works good, but version 1.10.2-2281-5.2.0-BETA-2569 and 2571 have next errors: https://gist.github.com/PixelmonPRO/97f705a8cfb1496f6261310faac5ef3d
All plugins for work in MySQL not connecting and work. 
MySQL | 5.6.35-1debian8

**Comment by bloodmc** [comment]
This has nothing to do with SpongeForge. LuckPerms had an exception while loading groups.

[23:03:26] [pool-2-thread-5/ERROR] [Sponge/luckperms]: The Scheduler tried to run the task luckperms-A-14 owned by Plugin{id=luckperms, name=LuckPerms, version=3.3.3, description=A permissions plugin, authors=[Luck], source=/ssd/UnowaMain/mods/LuckPerms-Sponge-3.3.3.jar}, but an error occured.

Update to latest LuckPerms.

You can also check your MySQL for logs.

**Comment by PixelmonPRO** [comment]
@bloodmc Hello, problem still exists, Lucko answered:
> Have you actually tried downgrading to the SF version which works?
I don't see how if that works, it could possibly be a LP issue.
blood is also mistaken, the error has nothing to do with loading groups.
[23:03:22] [Server thread/INFO] [STDERR/sponge]: [me.lucko.luckperms.common.storage.backing.sql.SQLBacking:init:197]: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: java.lang.NoClassDefFoundError: com/mysql/jdbc/MysqlIO

**Comment by PurpleIsEverything** [comment]
This is not resolved by updating or downgrading LuckPerms, only a Sponge downgrade resolves it.

**Comment by bloodmc** [comment]
@ShadowKitten @PixelmonPRO Did you test SF 2579?

**Comment by phit** [comment]
Definitely something in 2569 (https://github.com/SpongePowered/SpongeCommon/commit/453c290d81019e2ccf4ac3fa04e5d0cea55e46de) broke it, here's the logs:


[fml-server-latest.2567.txt](https://github.com/SpongePowered/SpongeForge/files/1236681/fml-server-latest.2567.txt) - last working
[fml-server-latest.2569.txt](https://github.com/SpongePowered/SpongeForge/files/1236680/fml-server-latest.2569.txt) - first broken
[fml-server-latest.2579.txt](https://github.com/SpongePowered/SpongeForge/files/1236682/fml-server-latest.2579.txt) - latest

**Comment by bloodmc** [comment]
@Cybermaxke can you please take a look at this? You will need to install LuckPerms and setup mysql for testing.
