### ISSUE TITLE
[1.12.1] Will not start with Mekanism - NoClassDefFoundError: buildcraft/api/fuels/IFuel

### ISSUE THREAD

**Issue by ProsperCraft** [SpongePowered/SpongeForge#1736]
**I am currently running...**

- SpongeForge version: spongeforge-1.12.1-2444-7.0.0-BETA-2577, 2573, and 2568
- Forge version: forge-1.12.1-14.22.0.2459-universal.jar, and 2444
- Java version: openjdk version "1.8.0_141"
- Operating System: Centos 7 Linux.

**What is the expected result?**
Run
**What is the current result?**
Crash

https://gist.github.com/ProsperCraft/462ed193463189d549e1dc2922148d50

**Comment by Zidane** [comment]
We need the full server log, there is likely another stack before this.

**Comment by gabizou** [comment]
Duplicate of #1732
