### ISSUE TITLE
Scrap Box Duping with Sponge

### ISSUE THREAD

**Issue by Keaton1188** [SpongePowered/SpongeForge#1737]
Hi all, having a issue on our Age of Engineering server, when you right click a scrap box its meant to drop the item and remove the scrap box from your inventory, well thats not the case, its dropping the item but keeping the box in your inv letting you get lots of items over and over. 

I tested this on single player and it worked fine so I am guessing its an issue with Sponge.
Probably happening on our other 1.10 servers though.

Sponge Version:
Minecraft: 1.10.2
SpongeAPI: 5.2.0-SNAPSHOT-c675e80
SpongeForge: 1.10.22281-5.2.0-BETA-2539
Minecraft Forge: 12.18.3.2422

**Comment by bloodmc** [comment]
@Keaton1188 Update to latest SF and post your fml-server-latest log. We do not support old SF builds.

**Comment by phit** [comment]
works fine with 1.10.2-2281-5.2.0-BETA-2558

**Comment by bloodmc** [comment]
@phit Thanks.

Update SF to fix your issue.

**Comment by ProsperCraft** [comment]
Please re-open this is happening with the build from today.  2597.

We had it happening in 2581 as well, tried without sponge, no duping, with sponge, duping.

I noticed this happened in the past as well- https://github.com/SpongePowered/SpongeForge/issues/1066

[scrapboxduplogs.zip](https://github.com/SpongePowered/SpongeForge/files/1240306/scrapboxduplogs.zip)

**Comment by Aaron1011** [comment]
I believe that this is a duplicate of https://github.com/SpongePowered/SpongeForge/issues/1066

**Comment by ProsperCraft** [comment]
This appears to only happen to servers with         drops-pre-merge=true

**Comment by ProsperCraft** [comment]
Confirmed fixed working on my sever with drops-pre-merge=false

**Comment by bloodmc** [comment]
That setting has been set to false for a long time in SpongeForge. Never set that to true with mods.
