### ISSUE TITLE
Failed startup

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1738]
https://hastebin.com/xejetocari.md
https://pastebin.com/e3EyMTNe - sorry too long for hastebin
https://hastebin.com/ojoyevubuf.md
https://hastebin.com/kimafelinu.sql

**Comment by Zidane** [comment]
The logs you posted don't point to anyone. They just state multiple mods had errors loading. Start by removing SpongeForge and try loading your server. If it loads, add it back and remove mods one by one until you find who we have problems with. If it does NOT load, this isn't a Sponge issue and you should also remove them one by one to find the offender.

**Comment by bloodmc** [comment]
Your using an outdated Forge build. Update to latest.

The mod cofhcore (CoFH Core) requires mod versions [forge@[14.21.1.2415,15.0.0.0)] to be available
