### ISSUE TITLE
sponge does not like randomthings

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1739]
My server refuses to start with random things installed.
https://hastebin.com/yinebeciqu.sql

**Comment by phit** [comment]
Please use the issue template, it's there for a reason. 

Anyway I retested this with spongeforge-1.12.1-2444-7.0.0-BETA-2582 & RandomThings-MC1.12.1-4.0.5, same crash.
[crash-2017-08-19_22.59.24-server.txt](https://github.com/SpongePowered/SpongeForge/files/1236657/crash-2017-08-19_22.59.24-server.txt)
[fml-server-latest.txt](https://github.com/SpongePowered/SpongeForge/files/1236658/fml-server-latest.txt)

**Comment by Aaron1011** [comment]
This bug isn't specific to `randomthings` - any mod or plugin which calls `Ingredient#test`
