### ISSUE TITLE
[1.12.1] Crash on startup

### ISSUE THREAD

**Issue by FiveEYZ** [SpongePowered/SpongeForge#1740]
**I am currently running...**

- SpongeForge version: spongeforge-1.12.1-2444-7.0.0-BETA-2590
- Forge version: forge-1.12.1-14.22.0.2459-universal
- Java version: 1.8.0_144
- Operating System:

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows

- Plugins/Mods: 
all mods can be seen in the crash-report

**What is the expected result?**
was working on build 2582, but had to downgrade to 2566 (cause of the mysql issue)
**What is the current result?**
crash on startup

https://gist.github.com/FiveEYZ/e44dce77ace54d938195c7cfdc826d29

**Comment by ghost** [comment]
I have same issue. latest build without problem is 2566.

**Comment by ProsperCraft** [comment]
Same issue with build 2599 build from today.

https://gist.github.com/ProsperCraft/fc253f6e9082b5d4525e84ea07bccc82

**Comment by Jay9519** [comment]
2582 works, anything above that crashes the server

**Comment by ghost** [comment]
build 2602 solved this issue for me

**Comment by bloodmc** [comment]
Closing as this should be resolved in latest.
