### ISSUE TITLE
Tile Entities with Inventory GUI error

### ISSUE THREAD

**Issue by BillyGalbreath** [SpongePowered/SpongeForge#1741]
I am looking to switch to Forge/Sponge and have started building a mod from a tutorial to learn the basics of Forge mods. Everything with the tutorial works great when SpongeForge is not installed. But as soon as I install SpongeForge opening the inventory GUI of a custom item doesnt work and throws errors in console. There are no Sponge plugins/mods installed yet, I only have the SpongeForge.jar installed because I do plan I making a few plugins/mods for it eventually, too.

**I am currently running...**

- SpongeForge version: 1.12.1-2444-7.0.0-BETA-2590
- Forge version: 14.22.0.2459
- Java version: 1.8.0_131
- Operating System: Debian 9.0 (Stretch)

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods:
[14:42:15] [Server thread/INFO]: Plugins (4): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge

**What is the expected result?**
Shift right click pedistal to open it's custom inventory GUI.

**What is the current result?**
Shift right click does nothing in game, and throws error in console

Here's the latest.log file: https://pastebin.com/NuSYepKG
Here's the error SpongeForge puts in console: https://pastebin.com/cLAxPxcL

Here's a link to the tutorial I am running: http://shadowfacts.net/tutorials/forge-modding-112/tile-entities-inventory-gui/
Here is a link to it's GitHub project/source: https://github.com/shadowfacts/TutorialMod

**Comment by ghost** [comment]
It looks like duplicate #1740 

Try build  2566.

**Comment by BillyGalbreath** [comment]
I can confirm build 2566 is working as intended.

Error still persists using build 2601

**Comment by phit** [comment]
Solved a while ago see #1740
