### ISSUE TITLE
I need help on tracking tps lag

### ISSUE THREAD

**Issue by kaal-1** [SpongePowered/SpongeForge#1749]
- SpongeForge version: 1.10.2-2281-5.2.0-BETA-2591
- Forge version: 2281
- Java version: 8_144
- Operating System: Debian 8
/sponge timings paste: https://timings.aikar.co/?id=ee2292b4851f4edfafa7f254d0b901a6

I'm running an 1.10.2 modded skyblock server and recently the TPS started to drop pretty bad, staying around 3/4. The server used to have 25/30 players with a 20 TPS (sometimes dropping between 16/18), but never this low. At first I tried removing items, monsters and xp orbs from the ground since they are often the cause of tps drops due to players doing some weird things, but that's not it. Any idea on what could be done?

**Comment by bloodmc** [comment]
You need to use forums for this. Github is reserved for actual bugs, not to help diagnose specific server issues.
