### ISSUE TITLE
Description: Exception in server tick loop Caused by: java.lang.IllegalArgumentException: Could not find a DimensionType by id: natura:nether

### ISSUE THREAD

**Issue by xAlicatt** [SpongePowered/SpongeForge#1750]
- SpongeForge version: 1.10.2-2281-5.2.0-BETA-2597 
- Forge version: 2281
- Java version: 8

Log: https://gist.github.com/xAlicatt/60b7fb5bc546a147ba8f994d2df0d44e

I'm honestly not even sure that sponge is to blame here, but my attempts at finding a fix lead me here, so I'm sharing my issue. I'm going to attempt rolling back sponge until i hit on a version that doesn't crash, and will report my findings.

**Comment by axle2005** [comment]
Duplicate of [#1637](https://github.com/SpongePowered/SpongeForge/issues/1637)

**Comment by xAlicatt** [comment]
My bad. I will comment there from here on out and close this.
