### ISSUE TITLE
Error generating Canopy Tree!

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1751]
Crash in server when generating a Canopy Tree

**I am currently running...**

- SpongeForge version: 1.10.2-2281-5.2.0-BETA-2597
- Forge version: 1.10.2-2281
- Java version: 1.8.0_144
- Operating System:

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

Crash: https://pastebin.com/r9Wg9ycL and https://pastebin.com/9UaUbUjV ( at the same time, 2 crashes )

**Comment by Deamon5550** [comment]
Your server timed out, mostly likely from recursing generation given your version and amount of mods. Raise the max tick time or update.
