### ISSUE TITLE
Sponge is not playing nice with RFTools dimensions.

### ISSUE THREAD

**Issue by BlueCyro** [SpongePowered/SpongeForge#1757]
We are currently running 1.12.1

- SpongeForge version: spongeforge-1.12.1-2444-7.0.0-BETA-2602
- Forge version: Forge 14.22.0.2462
- Java version: 1.8.0_144, Oracle Corporation
- Operating System: Windows Server 2012 R2 (amd64) version 6.3

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows

- Plugins/Mods: 
Using only the fixspawning-0.1.jar from here: https://github.com/SpongePowered/SpongeForge/issues/1643
+The mods listed in the crashlog.

**What is the expected result?**
The expected result is RFTools dimensions generating normally when created.

**What is the current result?**
90% of the time it crashes with the below crashlog:

https://gist.github.com/Xerasin/3a52eae8f6d920eb97510f08eeb0bb05

**Comment by bloodmc** [comment]
@RileyGuy Provide a test world with steps to reproduce. Make sure to use latest SpongeForge build when testing.

**Comment by BlueCyro** [comment]
@bloodmc Terribly sorry, this was a user error and not an error with Sponge. The Forge version used was the latest whereas this Sponge version was built with Forge 2444. After reverting to the appropriate version the crashes stopped and expected behavior resumed. I might not be able to provide a test world since I don't know if I have the mod pack anymore and the mod pack was custom so I don't know if I could re-download it. Do you still want me to attempt to provide a test world?

**Comment by BlueCyro** [comment]
If I might also add, I don't know if a test world is really necessary as it happens on any world whilst generating rftools dimensions most of the time. However as I've said, it resolves itself when using the appropriate Forge version. It's just the latest that it's incompatible with.

**Comment by bloodmc** [comment]
@RileyGuy Does it work without SpongeForge and latest Forge version?

**Comment by BlueCyro** [comment]
@bloodmc All mods work as expected without SpongeForge on the latest Forge version.

**Comment by phit** [comment]
Totally still crashes if you make two dimensions with a different world generator
full log https://gist.github.com/phit/ec54b8f3ce96796377301c40552fee9e

Tested with spongeforge-1.12.2-2529-7.0.0-BETA-2741.jar
mcjtylib-1.12-2.5.0.jar
rftools-1.12-7.14.jar
rftoolsdim-1.12-5.05.jar

**Comment by Zidane** [comment]
I'm labeling this as a won't fix.

Our code is what this should be, ChunkGenerators are meant to be INSTANCES, not shared. RFToolsDim is literally sharing the object for some stupid damn reason and willy nilly changing the world ref solely for this "upside down" world concept. 

Could I remove the exception? Yes I could but all that does is put back in the boilerplate that already exists in his mod.
