### ISSUE TITLE
[1.12.1] issue with creative mode destroy item slot

### ISSUE THREAD

**Issue by runescapejon** [SpongePowered/SpongeForge#1758]
**I am currently running...**
- SpongeForge version:  1.12.1 - 7.0.0-BETA-2607
- Forge version: forge-1.12.1-14.22.0.2467
- Java version:  java 8
- Operating System: 
 - [X] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [X] Windows
- Plugins/Mods: 
 Plugins (4): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge
**What is the expected result?**
Error's in console
**What is the current result?**
https://hastebin.com/ekuwonanes.md

**how to reproduce the error** 
go in creative then Shift click the Destroy Item Slot
here a GIF on what it looks like
you'll see my minecraft and the console in the background
i installed no mods just spongeforge nothing else
https://gyazo.com/a966318ea12723af96fdf8cba3c54839

**Comment by Faithcaio** [comment]
https://github.com/SpongePowered/SpongeCommon/issues/1513 
so many issues bc of this damn getPlugin() method
