### ISSUE TITLE
Sponge 1.10.2 Crash's

### ISSUE THREAD

**Issue by Snez0kRU** [SpongePowered/SpongeForge#1759]
**I am currently running...**

- SpongeForge version: spongeforge-1.10.2-2281-5.2.0-BETA-2597.jar
- Forge version: Forge-1.10.2-2281
- Java version: 8
- Operating System:

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: 
BetterFps-1.3.2.jar
BiomesOPlenty-1.10.2-5.0.0.2290-universal.jar
CatClearLag-0.8.jar
CraftTweaker-1.10.2-3.0.26.jar
CustomNPCs_1.10.2(21jul17).jar
EconomyLite-5.0.0-2.12.0.jar
griefprevention-1.10.2-4.0.0.379.jar
LuckPerms-Sponge-3.3.19.jar
MCClans-1.5.jar
MineTweakerRecipeMaker-1.10.2-1.2.1.26.jar
MMCReboot.jar
MysteryGift-1.10.2-0.3.1-universal.jar
Nucleus-1.0.1-LTS-1.10.2-S5.1-plugin.jar
PixelAuction-1.10.2-1.1.2-universal.jar
PixelExtras-1.10.2-2.2.7-universal.jar
PixelmonEconomyBridge-1.10.2-1.3.0.jar
PixelmonReborn-1.10.2-5.8.3.jar
pokexpmultiplier-1.1.3.jar
projectborders-5.0.0-0.1.4.jar
SpawnOfPsyduck-1.10.2-2.3.3-storagefix.jar
spongeforge-1.10.2-2281-5.2.0-BETA-2597.jar
stackban-5.1.0-0.2.5.jar
worldedit-forge-mc1.10.2-6.1.4-dist.jar

**What is the expected result?**
3 hours with 40 players on server, without 9999+ crash's 

**What is the current result?**
have 5-6 crash's on 1 day. 

4 of 5 ==> java.lang.Error
1 of 5 ==>java.lang. CustomNpc

Startline from here: https://forums.spongepowered.org/t/optimized-startup-flags-for-consistent-garbage-collection/13239/8

[crash-2017-09-02_15.01.15-server.txt](https://github.com/SpongePowered/SpongeForge/files/1272474/crash-2017-09-02_15.01.15-server.txt)
[crash-2017-09-02_06.03.14-server.txt](https://github.com/SpongePowered/SpongeForge/files/1272473/crash-2017-09-02_06.03.14-server.txt)
[crash-2017-09-01_23.12.51-server.txt](https://github.com/SpongePowered/SpongeForge/files/1272476/crash-2017-09-01_23.12.51-server.txt)
[crash-2017-09-02_18.58.15-server.txt](https://github.com/SpongePowered/SpongeForge/files/1272477/crash-2017-09-02_18.58.15-server.txt)
[crash-2017-09-02_16.45.35-server.txt](https://github.com/SpongePowered/SpongeForge/files/1272475/crash-2017-09-02_16.45.35-server.txt)

**Comment by Deamon5550** [comment]
The `Error`s are just your server timing out because something (pixelmon, luckperms, minetweaker) is spending too much time processing, raise or disable the `max-tick-time` in your server.properties.

The entity error is because whatever mod is adding that entity is not handling creating the spawn packet through however you do that with forge and is not a sponge issue.
