### ISSUE TITLE
SpongeForge and MultiStorage (FTB): Unexpected World Change Detected

### ISSUE THREAD

**Issue by alexmaurizio** [SpongePowered/SpongeForge#1760]
**I am currently running...**

- SpongeForge version: spongeforge-1.10.2-2281-5.2.0-BETA-2597
- Forge version: Forge 12.18.3.2316 
- Java version: 1.8.0_144, Oracle Corporation
- Minecraft Version: 1.10.2 (behind bungeecord/more 1.12.1 vanilla servers)
- FTB Server Edition, modpack FTB Beyond 1.10.2 (replaced AE2 with last version since it caused a Sponge  crash but was a already solved bug)
- Operating System:

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [X] Windows

- Plugins/Mods: 
 Plugins (192): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, Applied Energistics 2 Core, Aroma1997Core, Not Enough Items, OpenComputers (Core), SpongeAPI, SpongeForge, CoFH ASM, FoamFixCore, ccl-entityhook, CoFH Core, Actually Additions, IndustrialCraft 2, Advanced Machines, Advanced Solar Panels, Applied Energistics 2, BD Lib, AE2 Stuff, InfinityLib, AgriCraft, Baubles, Botania, Akashic Tome, Just Enough Items, AppleSkin, Aquaculture, ArchitectureCraft, Aroma1997Core|Helper, Aroma1997's Dimensional World, Morph-o-Tool, Psi, Quark, AutoRegLib, Bed Bugs, Better Builder's Wands, BiblioCraft, Guide-API, Blood Magic: Alchemical Wizardry, Blood Arsenal, Bookshelf, CodeChicken Lib, Brandon's Core, Mantle, Tinkers' Construct, Ceramics, Chameleon, Chest Transporter, Chisel, MCMultiPart, Chisels & Bits, ShadowMC, Clipboard, CodeChicken Core, Compact Solar Arrays, Cooking for Blockheads, CraftTweaker JEI Support, MineTweaker 3, Dark Utilities, PTRModelLib, Decocraft, Forestry, ElecCore, EnderStorage, OpenComputers, DeepResonance, Draconic Evolution, Storage Drawers, Drawers & Bits, Elevator Mod, Embers, EnderCore, Ender IO, Engineers Workshop, Valkyrie Lib, Environmental Tech, ET Lunar, Extra Utilities 2, Zero CORE, Extreme Reactors, Flat Colored Blocks, SonarCore, FluxNetworks, FoamFix, Shadowfacts' Forgelin, Forge Multipart CBE, Forge Microblocks, Minecraft Multipart Plugin, FTBLib, FTBUtilities, Funky Locomotion, Funnels, GenDustry, Gravestone, Gravitation Suite, Hammer Core, HelpFixer, Hopper Ducts, The One Probe, Immersive Engineering, LunatriusCore, InGame Info XML, Interaction Wheel, Inventory Tweaks, Iron Backpacks, Iron Chest, JEI Bees, JourneyMap, KleeSlabs, Long Fall Boots, MalisisCore, MalisisDoors, Mercurius, Modular ForceField System, MmmMmmMmmMmm, mob_grinding_utils, MTLib, Mod Tweaker, Railcraft, RebornCore, TechReborn, More Bees, Morpheus, ModPack Utilities, ModPack Basic Tools, MrTJPCore, ShetiPhian-Core, Multi-Storage, Natura, Nether Portal Fix, Open Glider, p455w0rd's Library, Pam's HarvestCraft, ProjectRed Core, ProjectRed integration, ProjectRed Transmission, ProjectRed Illumination, ProjectRed Expansion, ProjectRed Transportation, ProjectRed Exploration, QuantumStorage, Ranged Pumps, reborncore-MCMultiPart, Thermal Foundation, Thermal Expansion, Redstone Arsenal, Refined Relocation, Refined Storage, Reliquary, RFTools, RFTools Control, RFTools Dimensions, Roots, Signals, SimpleVoidWorld, Simple Retrogen, Simply Jetpacks 2, Sleeping Bag, Snad, Solar Flux Reborn, Steve's Carts 2, Storage Drawers Extras, Super Circuit Maker, Super Crafting Frame, Thermal Dynamics, Tinkers Tool Leveling, TOP Addons, TorchMaster, Translocator, Useful Nullifiers, WanionLib, Wireless Crafting Grid, Wireless Crafting Terminal 2, Woot, WirelessRedstone-CBE, XNet, YABBA, BungeeTabListPlus-SpongeBridge, EconomyLite, GriefPrevention, LuckPerms, MMCRestrict, Nucleus, ProjectCore for SpongeAPI 5.x, ProjectPortals for SpongeAPI 5.x, ProjectWorlds for SpongeAPI 5.x, SkinsRestorer, SpongyCord, WorldEdit, UniDict

**What is the expected result?**
Using/Creating a MultiStorage Vault Door / Vault System works nicely but causes the linked Server Log to happen. It's a non-tracked mod world change.
https://minecraft.curseforge.com/projects/multistorage

**What is the current result?**
Stuff works (badly, some minor bugs) but server console gets spammed with this and the suggestion to report this bug

Server log: https://pastebin.com/aQhedqwW

Thanks! :)

**Comment by alexmaurizio** [comment]
PS: I plan on moving on CentOS7 hosted servers when testing for this multiserver finish, so Windows is really not representative ATM

**Comment by Aaron1011** [comment]
This is a bug in MultiStorage: https://github.com/ShetiPhian/Localizations-and-Issues/issues/109. While the stacktrace might disappear when Sponge is removed, the underlying issue will still exist.

**Comment by alexmaurizio** [comment]
I don't want to open another thread since this looks related to the other one, since it works the same way.

Also Bibliocraft (used the tape meter) has the same Sponge-Related problem. Here's the ServerLog, can you look at it?

I think it's the same netty IO method. https://pastebin.com/63rUDRVP

**Comment by Aaron1011** [comment]
@destructor3: Yes, this is the same issue.
