### ISSUE TITLE
Spongeforge latest version not starting up on server (server is running in forge only)

### ISSUE THREAD

**Issue by Liiw** [SpongePowered/SpongeForge#1762]
**I am currently running...**

- SpongeForge version: 1.10.2-2281-5.2.0-BETA-2610
- Forge version: 1.10.2-12.18.3.2422-universal
- Java version: 1.8.0_144
- Operating System: 

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [X] Windows

- Plugins/Mods:  Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, Advanced Rocketry, Applied Energistics 2 Core, Aroma1997Core, CreativeCoreDummy, IvToolkit, LittleTilesCore, OpenComputers (Core), MovingWorld CORE, SpongeAPI, SpongeForge (Note that this is an older version, that runs. Used it to get the list), Backpacks!, CoFH ASM, FoamFixCore, ccl-entityhook, Fence Overhaul, Mo' Villages, CoFH Core, Actually Additions, Baubles, Actually Baubles, CodeChicken Lib, CodeChicken Core, EnderStorage, Just Enough Items, OpenComputers, ActuallyComputers, Additional Banners, libVulpes, Advanced Rocketry, Applied Energistics 2, BD Lib, AE2 Stuff, InfinityLib, AgriCraft, EnderCore, Waila, Ender IO, Shadowfacts' Forgelin, AnalyzeIO, ArchitectureCraft, Mantle, Tinkers' Construct, TESLA, TheDragonLib, ArmorPlus, Armor Stand Configurator, Aroma1997Core|Helper, Aroma1997's Dimensional World, AromaBackup, AromaBackup Recovery, Quark, AutoRegLib, AutoSapling, Base Metals, Bed Bugs, Better Achievements, Better Builder's Wands, Better Questing, Better Questing Triggerer, MalisisCore, MalisisDoors, Big Doors, Parallel, Zero CORE, Big Fusion, MCMultiPart, Chisels & Bits, Bit Replicator, Botania, Better Questing Auto Reload, Brandon's Core, Builder's Guides, Can I Join Now?, Car Mod, CashCraft, Crop-Eating Animals, MrCrayfish's Furniture Mod, Chameleon, Saplings-to-charcoal, Chest Transporter, ChickenChunks, ChunkGen, Clay Bucket, Mekanism, OMLib, Open Modular Turrets, Combat Plus, Cyclops Core, CommonCapabilities, Cooking for Blockheads, Extra Utilities 2, Forestry, Corail Pillar - Forestry Extension, Corail Pillar - Quark Extension, CosmeticArmorReworked, Simple Covers, Craftable Saddles, CraftTweaker JEI Support, MineTweaker 3, CreativeCore, CustomNPCs, Cyberware, Moving World, Davinci's Vessels, DebugServerInfo, Draconic Evolution, Storage Drawers, Drawers & Bits, Dynamic Surroundings, ElecCore, Ender Ore, Ender-Rift, Ender Zoo, Modern Metals, End Metals, Thermal Foundation, Thermal Expansion, Exchangers, Extra Bit Manipulation, Extreme Reactors, Farming for Blockheads, SonarCore, FluxNetworks, FoamFix, Food Expansion, Forge Multipart CBE, Forge Microblocks, Minecraft Multipart Plugin, Funky Locomotion, GenDustry, Glasscraft, Grappling hook mod, Growable Cells, Hammer Core, Immersive Engineering, Immersive Petroleum, Immersive Tech, Infernal Mobs, Iron Backpacks, Iron Chest, itank, Just Enough Forestry Bees, Just Enough HarvestCraft, JEI Bees, Just Enough Pattern Banners, JourneyMap, LittleTiles, Login Shield, LootTweaker, Malisis Switches, MmmMmmMmmMmm, Natura, Railcraft, MoarSigns, Moar Tinkers, Modern Lights, MTLib, Mod Tweaker, Modular Routers, More Bees, MorePlayerModels, MrTJPCore, Multifarm Crops, ShetiPhian-Core, Multi-Storage, Modern Warfare, Nether Metals, NoMoreRecipeConflict, NPC Integration, Classic Oceans, OpenComputers Sensors, OfflineSkins, Open Modular Passive Defense, OnlinePictureFrame, OpenFM, OC Glasses, Open Glider, OpenPrinter, OpenRadio, OpenSecurity, Ore Dictionary Converter, Ore Spawn, Overloaded, p455w0rd's Library, Pam's HarvestCraft, Parachute Mod, Perfect Spawn, Ping, Platforms, Practical Logistics 2, ProjectRed Core, ProjectRed integration, ProjectRed Transmission, ProjectRed Fabrication, ProjectRed Illumination, ProjectRed Exploration, RebornCore, QuantumStorage, Better Questing Quest Book, Railcraft Cosmetic Additions, reborncore-MCMultiPart, RF Expansion, RF Lux, RFTools, RFTools Control, Roguelike Dungeons, Ruins Mod, Scannable, SG Craft, ShadowMC, SignalCatcher, SimpleCore API, SimpleLabels, Simple Tinkers Construct Addon, Sleeping Bag, SleepVote, SodiumCraft, Solar Flux Reborn, Standard Expansion, Steve's Carts 2, Storage Drawers Extras, Super Ores, Super Sound Muffler, Surge, Tinkers Alloying Addon, Thermal Dynamics, Thut Core, Thut's Tech, Tinker I/O, Tinkers' Addons, Tinkers' Defense, Tinkers Tool Leveling, Corail Tombstone, TorchMaster, bspkrsCore, Treecapitator, Vending, Villager Market, WanionLib, I Can See Everything, What Are We Looking At, Wireless Crafting Terminal 2, Woot, WirelessRedstone-CBE, Zetta Industries, Corail Pillar, Just A Ore Processing Compatibility Attempt, UniDict

**What is the expected result?**
Successful start of Spongeforge and ability to use sponge commands on the server.

**What is the current result?**
Spongeforge is not starting on the server. Server is starting, the GUI pops up and when I try to run sponge commands, they are not recognized i.e. the server is just Forge. Currently running the server with spongeforge-1.10.2-2281-5.2.0-BETA-2464 as that seems to be working.

[fml-server-latest.txt](https://github.com/SpongePowered/SpongeForge/files/1277155/fml-server-latest.txt)

**Comment by dualspiral** [comment]
`[13:09:33] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.6.6 Source=file:/X:/CoT%20V%20Server/mods/movingworld-1.10.2-0007-full.jar Env=SERVER`

Newer versions of sponge use a newer version of Mixin (0.7.1?) than the one available in Moving World (0.6.6) - which is actually very old, but Moving World's version gets loaded first. Try renaming the SpongeForge jar to start with the letter a (so, something like `aspongeforge-1.10.2-2281-5.2.0-BETA-2464.jar`), and see if that loads up Mixin first, and thus, Sponge.

**Comment by Liiw** [comment]
@dualspiral It works! This was indeed the issue and adding "a" in the front let sponge start up again. Thank you!
