### ISSUE TITLE
Server crash -NPE-  handler$onGetWorldInfo 

### ISSUE THREAD

**Issue by ProsperCraft** [SpongePowered/SpongeForge#1763]
On first load, I am getting this crash, it does not happen without sponge.
It does not produce a crash report.

**I am currently running...**

- SpongeForge version: spongeforge-1.12.1-2444-7.0.0-BETA-2609
- Forge version: forge-1.12.1-14.22.0.2469-universal
- Java version: openjdk version "1.8.0_141"
- Operating System:

 - [X] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: No plugins.  

One mod that seems to be mentioned in the stacktrace - signpost-1.12-1.05.5

https://github.com/McJty/ElementalDimensions/issues/11#issuecomment-327089612

**Comment by bloodmc** [comment]
Once the mod's command name is fixed to not contain spaces and be lowercase, it will no longer crash. Wait for mod to fix.

**Comment by bloodmc** [comment]
Keeping this open so we can autocorrect bad command names instead of crashing.

**Comment by phit** [comment]
he is talking about this log https://gist.github.com/ProsperCraft/900a01dd813183ea4389d93ea9f0a00c
the command thing was already fixed from the mod

**Comment by bloodmc** [comment]
I don't have this crash issue with latest SF 1.12.1, ElementalDimensions and ElecCore.

**Comment by phit** [comment]
because it has nothing to do with those mods? this issue is about signposts, he just sucks at making that clear since he never linked the actual log he cares about in here

**Comment by bloodmc** [comment]
Tested latest SF with signpost and could not reproduce crash. Create a new ticket with EXACT steps on how to reproduce. Also do not reference completely different mods in ticket.
