### ISSUE TITLE
[1.10.2] Minefactory Reloaded Machines Crashing Server

### ISSUE THREAD

**Issue by CaptainSisko** [SpongePowered/SpongeForge#1764]
**I am currently running...**

- SpongeForge version: spongeforge-1.10.2-2281-5.2.0-BETA-2610
- Forge version: forge-1.10.2-12.18.3.2422-universal.jar
- Java version: 1.8.0_131
- Operating System: Ubuntu 16.04.3 LTS

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: 
All The Mods 1 (1.10.2)
https://hastebin.com/ehewigewix.py

**What is the expected result?**
The expected result is that the server does not crash when a MFR Machine is placed.

**What is the current result?**
The server crashes when a MFR Machine is placed.

Crash-Log: https://hastebin.com/ocoxamiruc.scala
Latest.log: https://hastebin.com/muyadokoqi.scala
Full Log: https://gist.github.com/CaptainSisko/35635ec28a62e518f5f1675c2bfa223d

This looks very similar to this issue that should have been fixed 21 days ago: https://github.com/SpongePowered/SpongeForge/issues/1720

**Comment by CaptainSisko** [comment]
This issue has been reported on the MFR Issue Tracker by another person as well.

https://github.com/skyboy/MineFactoryReloaded/issues/670

That person is also using spongeforge-1.10.2-2281-5.2.0-BETA-2610.

**Comment by bloodmc** [comment]
CoFH is doing some ASM hackery that expects all our methods to be public in WorldServer. Put it in a ticket with them as they should be able to fix this.

**Comment by bloodmc** [comment]
@CaptainSisko So I'll work on a fix for this and hope CoFH can improve their ASM =). Expect a fix soon.

**Comment by CaptainSisko** [comment]
Just got around to being able to test this out but it doesnt appear to have fixed this issue.

I have a new crash-log here https://hastebin.com/kozafituxa.scala

I havent ticketed CoFH about this yet but i will now if you still want me to.
