### ISSUE TITLE
Chunk coordinates are not valid crash!

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1765]
Every teleport, this crash appears...
**I am currently running...**

- SpongeForge version: 1.10.2-2281-5.2.0-BETA-2610
- Forge version: 1.10.2-2281
- Java version: 1.8.0_144
- Operating System:

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

Crash: https://pastebin.com/01HM2ELk

**Comment by Deamon5550** [comment]
That chunk `-1874999, 1875000` is invalid so somewhere a check must be being bypassed to allow that chunk to be attempted to be generated.

**Comment by phit** [comment]
@PretoAlbino any idea on how to reproduce this, was someone teleporting outside the border or something similar?

**Comment by ImMorpheus** [comment]
@phit I'm pretty sure you nailed it `EntityPlayerMP['ManoGamerBr'/3666, l='minerar', x=-29999983.50, y=57.00, z=29999984.50]]`

**Comment by phit** [comment]
Closing in favor of https://github.com/SpongePowered/SpongeCommon/issues/651 then, thanks @ImMorpheus totally missed that.
