### ISSUE TITLE
server crashes when flying/exploring out into the world

### ISSUE THREAD

**Issue by ozm8** [SpongePowered/SpongeForge#1769]
**I am currently running...**

- SpongeForge version:  spongeforge-1.10.2-2281-5.2.0-BETA-2610
- Forge version:  forge-1.10.2-12.18.3.2281-universal
- Java version:  8
- Operating System: centos7 64bit

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: 

blob:https://imgur.com/a4f3508b-e88a-4e30-8c97-8d1b51e657f2

Crash report: https://pastebin.com/eJ82B3v6

**Comment by bloodmc** [comment]
Update to latest and retest

**Comment by ozm8** [comment]
Ok i updated to 1.11.2 sponge forge, forge, mods and sponge plugins and new world but still happens. 

https://pastebin.com/XXUn78UD

**Comment by bloodmc** [comment]
Wait are you flying at normal speed? Because this doesn't make any sense.

**Comment by ozm8** [comment]
nah when i test it at like /speed 5-10 and start going out into the world it crashes the server.

**Comment by bloodmc** [comment]
What are the specs of this server? It seems as if the server just cant handle async lighting requests at a good enough pace and lags behind. Remove all mods/plugins except LP/Nucleus and retest in a clean world.

**Comment by ozm8** [comment]
well i just got another vps i used for my spigot server and its got 16gb of ram though im only allocating 10gb to it and 6 cpu cores. its a vps from vultr

**Comment by bloodmc** [comment]
OK replicate with LP/Nucleus only in a clean world then list the steps you took to make the bug happen.

**Comment by ozm8** [comment]
we tried with just forge sponge and Nucleus  and was unable to crash it and the world was loading faster too while going at speed 10

**Comment by bloodmc** [comment]
@ozm8 Figure out what mod/plugin breaks it by adding what you had one by one then let me know.

**Comment by ozm8** [comment]
ok well i removed -XX:+UseG1GC from the java startup falgs which is what I used when i was using a spigot server and i enabled all mod and pluigins and it hasn't crashed for some reason. weird

**Comment by bloodmc** [comment]
Interesting, can you always reproduce when you use that flag?

**Comment by FiveEYZ** [comment]
Try check ram usage before the server crash, reading the last comment got me thinking...
I'm kind of having the same issue, except I'm not crashing. 

Maybe some other flag I'm using makes it able to not crash (or something).

Using ` -XX:+UseG1GC`  ram usage goes crazy high when ppl explore
[![Screenshot from Gyazo](https://gyazo.com/e678158e26b4e833d75fb296f512eb86/raw)](https://gyazo.com/e678158e26b4e833d75fb296f512eb86)

and now when i switched from` -XX:+UseG1GC` to `-XX:+UseConcMarkSweepGC` the ram is stable and does not ramp up by ~100 MB/s when ppl explore

**Comment by bloodmc** [comment]
@FiveEYZ Can you describe the RAM usage you get with both flags?

**Comment by phit** [comment]
No reply in about 2 months, closing this for now. Please reply with the information you have been asked for and I will reopen this issue.
