### ISSUE TITLE
[1.10.2] NetherPortalFix Compatibility Issues

### ISSUE THREAD

**Issue by CaptainSisko** [SpongePowered/SpongeForge#1770]
**I am currently running...**

- SpongeForge version: spongeforge-1.10.2-2281-5.2.0-BETA-2625
- Forge version: forge-1.10.2-12.18.3.2422-universal.jar
- Java version: 1.8.0_131
- Operating System: Ubuntu 16.04.3 LTS

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: 
All The Mods 1 (1.10.2)
https://hastebin.com/ehewigewix.py

**What is the expected result?**
The mod [NetherPortalFix](https://minecraft.curseforge.com/projects/netherportalfix) is meant to "keep track of what portals a player went through in order to ensure correct destinations when the player is going back through the same portals."

**What is the current result?**
When a player enters a nether portal it will sometimes teleport them to a [strange inbetween world](https://puu.sh/xoSOq/399b7d651a.png) with [floating cubes made of random objects](https://puu.sh/xoSGg/09266172c9.png). Disconnecting and reconnecting to the server will fix the issue.

This particular issue has been reported to the [NetherPortalFix issue tracker](https://github.com/blay09/NetherPortalFix/issues/10) but the creator says that it is a sponge issue.

On top of this weird inbetween world issue there is another issue with teleporting from the nether. If the player successfully reaches the nether and then attempts to /home or a /warp (from nucleus) they will receive an [ingame error](https://puu.sh/xzxNs/5a992f1d94.png) and the console will spit out the following error.

https://hastebin.com/ocobivedav.vbs

Just some further details on the strange inbetween world.

It looks like you are in the nether but you are actually still in the overworld. You can see players who are walking around in the overworld but they cant see you. I have had issue with attempting to teleport while there, teleporting to a player will result in you slingshotting between where that players is and the location you teleported from. I have however been able to use /spawn (also using nucleus) to return to the spawn dimension(this isnt the overworld), once there using /home and /warp work again.

**Comment by Zidane** [comment]
As I mentioned on that issue, the author is re-creating server logic for transporting entities/players to other dimensions:

https://github.com/blay09/NetherPortalFix/blob/1.12/src/main/java/net/blay09/mods/netherportalfix/NetherPortalFix.java#L108

We cannot support a mod who performs their own logic over the server.

**Comment by bloodmc** [comment]
There were a few issues I noticed that could break mods including this one so I'll reopen ticket until I push some fixes.
