### ISSUE TITLE
[1.12.1] Server crashing when Tinkers axe breaks any tree

### ISSUE THREAD

**Issue by kwpugh** [SpongePowered/SpongeForge#1771]
Forge: 2479
SpongeForge: 2624 for forge 2479
Tinkers: 2.7.3.30
Mantle: 1.3.1.21

Server crashes as log breaks using a Tinkers Contruct lumber axe on any tree

Report: https://gist.github.com/kwpugh/ad76b47e4a3628c3126b41baf513ac17

**Comment by phit** [comment]
pretty annoying bug, this worked in 1.10 and 1.11

https://gist.github.com/phit/526b1611db38b736c77f9087c5cf8a18

**Comment by D3nnis3n** [comment]
We came across that yesterday, too. But it seemed to work in earlier versions (for 1.12.) of spongeforge as it appeared after we updated spongeforge - unfortunatley i do no longer know the Version we had before :/

**Comment by phit** [comment]
it probably worked prior to this https://github.com/SpongePowered/SpongeAPI/pull/1370
but you can't easily go back to before that as these changes are breaking for most plugins

**Comment by Zidane** [comment]
Patience, we'll get this fixed up. The bleeding branch is called bleeding for a reason.

**Comment by phit** [comment]
still happens after the recent refactor fixes https://gist.github.com/phit/7ff07e64f5cf7766f1566eae6aa1a0a0

**Comment by kwpugh** [comment]
Broken on spongeforge-1.12.2-2486-7.0.0-BETA-2672.jar

https://gist.github.com/kwpugh/e61ea9cf71e16319590fe8a96eb0ee72

**Comment by Zidane** [comment]
So this is happening because the phase tracker is being told to add a player to the context (as Tinker's is executing a block break on behalf of the player at tick end).

Not exactly sure the correct fix here so awaiting @gabizou 's feedback.

**Comment by liach** [comment]
I think we should probably add context overriding for this.

**Comment by kwpugh** [comment]
Just for confirmation, it works!!

And thank you for the great work on Sponge Forge.
