### ISSUE TITLE
Add configuration option to silence missing entity console spam and wipe entity/te.

### ISSUE THREAD

**Issue by Dockter** [SpongePowered/SpongeForge#1778]
Feature Requests:
* Add a configuration option to silence console spam generated from EntityList.java.  
* Add a configuration option to wipe entity or tile entity when encountered within the createEntityFromNBT method.  
* Add a configuration option to silence console spam generated from TileEntity.java.

These would be ideal options when migrating worlds from previous versions and or when pulling a plugin from a server for testing purposes.

**Comment by phit** [comment]
~move to sc

**Comment by limbo-app** [comment]
Hey @Dockter! I've moved your issue to [SpongePowered/SpongeCommon#1885](https://github.com/SpongePowered/SpongeCommon/issues/1885).
