### ISSUE TITLE
[1.11.2] Xnet mod crash, traced back to spongeforge

### ISSUE THREAD

**Issue by hugeblank** [SpongePowered/SpongeForge#1779]
Xnet was working perfectly fine on their version 1.3.2, but the moment I updated to 1.4.0, the server crashed (log provided below). I tried backporting to 1.3.2, but it still crashed in the same manner as with 1.4.0. I reported this [issue](https://github.com/McJty/XNet/issues/160#issuecomment-330450454) to mcjty, and he redirected it to you guys.

**I am currently running...**

- Minecraft Version: 1.11.2
- Forge Version: 13.20.1.2393
- Sponge Version: API: 6.1.0 - V:2471 (haven't had the chance to update, but I will come back to it and test on the latest version.)
- Java version: 1.8.0_144-b01
- Operating System: Ubuntu 14.04.5 LTS

- Plugins/Mods: 
A full list of mods currently being run on the server can be found [here](https://kaos-network.com/servers/sonarx) (scroll down a bit).
**What is the expected result?**
All mods being perfectly fine with each other.
**What is the current result?**
[this](https://github.com/McJty/XNet/files/1312757/crash-2017-09-19_02.16.03-server.txt)

**Comment by Zidane** [comment]
Sponge is only in the stacktrace because it is doing tracking around the tick. Nothing to do with us otherwise.

If you have doubts just remove Sponge and try again.

**Comment by hugeblank** [comment]
Alright, that answers that! Thanks for the swiftness!

**Comment by phit** [comment]
Closed like Zidane said, likely not a Sponge bug. If you can't reproduce it with just Forge let me know and I'll reopen.

**Comment by Arudarin** [comment]
Not reproducable with just Forge.

**Comment by Zidane** [comment]
@Arudarin 

Need a new log then of the crash.

**Comment by Arudarin** [comment]
@Zidane for me, it isn't a crash, but a kick from the server. Would you still like logs?
