### ISSUE TITLE
[1.12.1] Can't start server with SpongeForge and MovingWorld

### ISSUE THREAD

**Issue by davv1** [SpongePowered/SpongeForge#1780]
**I am currently running...**

- SpongeForge version: spongeforge-1.12.1-2444-7.0.0-BETA-2623
- Forge version: forge-1.12.1-14.22.1.2485-universal
- Java version: jre1.8.0_60 (64 bit)
- Operating System: Windows 7 Home Edition (64 bit)

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows

- Plugins/Mods: 
[Mod] davincisvessels-1.12-5.335-full
[CoreMod] movingworld-1.12-5.341-full
[CoreMod] spongeforge-1.12.1-2444-7.0.0-BETA-2623

**What is the expected result?**

Normal, bugless start of Minecraft+Forge+SpongeForge server.

**What is the current result?**

Crash in first second of start.

Logs:
[logs.zip](https://github.com/SpongePowered/SpongeForge/files/1317507/logs.zip)

**Comment by Zidane** [comment]
MovingWorld needs to update their Mixin they are targeting to be compatible with SpongeForge.
