### ISSUE TITLE
Cyclic "Inventory Upgrade" crashes server when opened

### ISSUE THREAD

**Issue by phit** [SpongePowered/SpongeForge#1781]
- SpongeForge version: spongeforge-1.12.1-2480-7.0.0-BETA-2643.jar
- Forge version: forge-1.12.1-14.22.1.2485-universal.jar
- Plugins/Mods: 
Cyclic-1.12-1.8.4.jar

**What is the expected result?**
opening your second inventory "Inventory Upgrade" `cyclicmagic:inventory_food` doesn't crash the server
**What is the current result?**
server crash

crash report https://gist.github.com/phit/4b6a520ccde98cefd2909ea2d8ac8b44

**Comment by Faithcaio** [comment]
https://github.com/SpongePowered/SpongeCommon/commit/3633da5b13e4b1a9c4454e302fcfdb94f1514f45
