### ISSUE TITLE
Actually Additions Breaker PhaseTracker issues

### ISSUE THREAD

**Issue by phit** [SpongePowered/SpongeForge#1790]
**I am currently running...**

- SpongeForge version: spongeforge-1.12.2-2486-7.0.0-BETA-2677
- Forge version: forge-1.12.2-14.23.0.2491
- Plugins/Mods: ActuallyAdditions-1.12.1-r120

**What is the expected result?**
actually additions breaker breaking stuff not creating 20mb log files after 10minutes with verbose tracking enabled

**What is the current result?**
20mb log file, its basically this over and over

https://gist.github.com/phit/82fbe553ee145a5d4538d641171a3426

**Comment by bloodmc** [comment]
@phit does this occur in latest?

**Comment by phit** [comment]
doesn't look like it, at least not since our last server restart, I assume it's fixed I'll reopen if it pops up again
