### ISSUE TITLE
[1.12] Attached blocks don't drop

### ISSUE THREAD

**Issue by phit** [SpongePowered/SpongeForge#1792]
**I am currently running...**

- SpongeForge version: spongeforge-1.12.2-2486-7.0.0-BETA-2678
- Forge version: forge-1.12.2-14.23.0.2491

- Plugins/Mods: none

**What is the expected result?**
breaking blocks attached to sideways torches, beds, ladders, cactus etc. drop the block broken and the attached block(s)
**What is the current result?**
only the block being broken drops

example video https://phit.link/s/2017-10-01_22-19-00.mp4

**Comment by Faithcaio** [comment]
Similar issue with double-flowers.
Only breaking the top half drops the item.

**Comment by phit** [comment]
@bloodmc everything else seemed fixed but double flowers still only drop when the top half is broken

https://phit.link/s/2017-10-02_18-28-19.mp4

**Comment by pen-siv** [comment]
unsure if related, but block groups broken by Tinker tools (hammer, excavator) only drop one block as well.
