### ISSUE TITLE
[1.12.2] Tinkers AoE tools not working under SpongeForge

### ISSUE THREAD

**Issue by kwpugh** [SpongePowered/SpongeForge#1799]
**I am currently running...**

- SpongeForge version:  spongeforge-1.12.2-2486-7.0.0-BETA-2679.jar
- Forge version: forge-1.12.2-14.23.0.2494-installer.jar
- Java version: 1.8 144
- Operating System: Centos 7

- Plugins/Mods: 
Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, Lockette, LuckPerms, Nucleus

**What is the expected result?**
When using a Tinkers Construct Hammer or Excavator, breaking a single block should break and 3x3 area and drop the blocks.

**What is the current result?**
These tools will break the 3x3 area but only drop a single block that was directly broken by the tool

System log:  https://gist.github.com/kwpugh/cd8a6f2e38cfb02a973752fa9123b9fc

**Comment by phit** [comment]
update this was already fixed in 2683 and 2684

**Comment by kwpugh** [comment]
Testing now.

**Comment by kwpugh** [comment]
That fixed it.  Thank you.
