### ISSUE TITLE
lightning malfunction.

### ISSUE THREAD

**Issue by pyscho974** [SpongePowered/SpongeForge#1805]
**I am currently running...**

- SpongeForge version: spongeforge-1.10.2-2477-5.2.0-BETA-2637
- Forge version: forge-1.10.2-12.18.3.2477-universal
- Java version: jre1.8.0_144
- Operating System: 

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x ] Windows (win7/ server 2008r2

- Plugins/Mods: nucleus

**What is the expected result?**
/lightning does actual damage and sound.
**What is the current result?**
sky flashes lightning strikes. no sound no damage.
found issue while playing space astronomy 2 using lightning craft. created test bed with no mods just sponge and nucleus. gave same affect.

**Comment by kashike** [comment]
Update to `5.2.0-BETA-2691`.

**Comment by pyscho974** [comment]
ty.. just checked prior to that update and did not see it. works now.
