### ISSUE TITLE
Quarry Dim - lag

### ISSUE THREAD

**Issue by Keaton1188** [SpongePowered/SpongeForge#1806]
We are getting massive lag on our Dw20 1.10.2 server.
I have reset the DIM and that fixes it, we only have about 3 people on the server and around 3 quarries running.. 
![untitled](https://user-images.githubusercontent.com/24898745/31316971-6e1a5a8e-ac30-11e7-927d-e5c13e12c9ce.png)

SpongeForge:
Minecraft: 1.10.2
SpongeAPI: 5.2.0-SNAPSHOT-c675e80
SpongeForge: 1.10.2-2281-5.2.0-BETA-2591
Minecraft Forge: 12.18.3.2316

**Comment by phit** [comment]
please test this without Sponge, pretty sure performance will be just as bad for that dimension

**Comment by tyler489** [comment]
If i remeber right this is because ex2 doesnt call for the blocks correctly. They then get left behind in the quarry dimention and also are put into chests. In adition the quarty picks arandom number and gens chunks around it so that also causes heavy preformance hits.

**Comment by phit** [comment]
Closing this as it is a mod issue, see https://github.com/rwtema/extrautilities/issues/1224
