### ISSUE TITLE
Ultimate Car Mod - Cars can't be spawned

### ISSUE THREAD

**Issue by D3nnis3n** [SpongePowered/SpongeForge#1808]
- SpongeForge version: 2696 
- Forge version: 2509
- Operating System:

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

**What is the expected result?**
The car from Ultimate Car Mod is spawned when crafted correctly and the spawn button is pressed.

**What is the current result?**
The car is not spawning and the following error occurs in the console:
https://gist.github.com/D3nnis3n/2639ffdd44272641b26f40b8bcfe882d

**Comment by phit** [comment]
please put the log on https://gist.github.com/ and dont paste it directly in the issue

**Comment by D3nnis3n** [comment]
Changed that.

**Comment by Deamon5550** [comment]
The mod is spawning entities from off the main thread, this leads to a variety of race conditions and should be fixed by the mod author (by performing the spawning on the main thread, probably through a scheduled task).

**Comment by D3nnis3n** [comment]
Thanks for your answer. I crosslinked the post to the mod authors issue tracker: https://minecraft.curseforge.com/projects/ultimate-car-mod/issues/8

Hopefully he does fix that. Or you can. Whoever wants to. :D

**Comment by D3nnis3n** [comment]
The mod author replied the following:

> I see no reason why the entity spawning should be threaded. In vanilla minecraft its also done in the main thread.

I think this means it's unlikely he is willing to "fix" that.

**Comment by ryantheleach** [comment]
@D3nnis3n it sounds like they don't realize that it's being called off of the main thread at all in the first place.

**Comment by D3nnis3n** [comment]
Yeh, i hope we could Point that out. Even i was wondering that something was a misunderstanding, though i'm not a native english Speaker. Sureley, after three People mentioning that, it should be clear :D

//EDIT:
Ah, he seems to have understood and fixed it already. Great. I'll Close this issue after testing, maybe he still Needs help.

**Comment by gabizou** [comment]
Closing as the new default configuration option presented in the latest builds will allow said entities to spawn * on the main thread*, but if disabled, Sponge will ignore the entity being spawned. The real fix will be with the mods themselves to ensure they are spawning entities on the main thread, and not on network threads.
