### ISSUE TITLE
Furnace / Inventory bug

### ISSUE THREAD

**Issue by Dockter** [SpongePowered/SpongeForge#1809]
Bug:  Furnace malfunctions.
Build:  October 6th commit of 1.12.2 (bleeding)
Forge: 1.12.2 - 2501.

Reproduce:  Place furnace, place in pork, place in coal.  The moment you place coal the furnace GUI is forced closed, the itemStack of Coal (the rest of it) will disappear from your player inventory AND the remaining of pork if you had any.  If you click on the furnace it will show all the slots empty yet it appears to be burning.

Problem immediately went away once I removed sponge from the server.  No stacktrace is printed at the server or client to help debug this issue.

**Comment by kashike** [comment]
already fixed

**Comment by Dockter** [comment]
This issue is not fixed.
