### ISSUE TITLE
IC2 Block's TileEntity gets destroyed even if block break transaction was cancelled

### ISSUE THREAD

**Issue by XsergeiX** [SpongePowered/SpongeForge#1812]
**I am currently running...**

- SpongeForge version: 2694
- Forge version: 2509
- Java version: 1.8.0_144
- Operating System: Win 10

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows

- Plugins/Mods: industrialcraft-2-2.8.16-ex112

**What is the expected result?**
When canceling block break event(making transaction invalid), it should prevent TileEntity being deleted too.
It does with vanilla blocks like furnace or brewing stand. But when you hit ic2 block, it's TileEntity gets destroyed and texture brokes.

**What is the current result?**
On the left there's block before hit and on the right there's same block after being hit by hand(Left-Click)
https://pasteboard.co/GObNaWa.png

**Comment by ryantheleach** [comment]
Related Issues:
----
https://github.com/SpongePowered/SpongeForge/issues/1383 - Reactors can explode protected areas.
https://github.com/SpongePowered/SpongeForge/issues/1811 - IC2 Tile Entities arn't available on restore.

**Comment by phit** [comment]
reproduced in dev env using 1.12.2-2705-7.1.0-BETA-3465 with industrialcraft-2-2.8.100-ex112.jar

breaks the tileentity only leaving block behind
```java
    @Listener
    public void onEvent(ChangeBlockEvent.Break event, @Root Player player) {
        for(Transaction<BlockSnapshot> transaction : event.getTransactions()){
            transaction.setValid(false);
        }
    }
```
same thing also seems to happen with simply cancelling the event

```java
    @Listener
    public void onEvent(ChangeBlockEvent.Break event, @Root Player player) {
        event.setCancelled(true);
    }
```

https://phit.link/s/2018-09-28_00-43-44.webm
