### ISSUE TITLE
CauseStack Manager called from off main thread error when server shutdown

### ISSUE THREAD

**Issue by Dockter** [SpongePowered/SpongeForge#1814]
Error from server when it was shutdown:  https://gist.github.com/Dockter/2259066ec2a61c5b4f9c6e1968703ac7

Sponge: spongeforge-1.12.2-2503-7.0.0-BETA-2696
Forge: 1.12.2 - 2509

**Comment by Aaron1011** [comment]
@Dockter: Are you able to reproduce this consistently? Based on the stacktrace, this method should have been called from the main thread.

**Comment by simon816** [comment]
I get this. It's called from the "Server Shutdown Thread"

Edit: specifically this code:
```java
            Runtime.getRuntime().addShutdownHook(new Thread("Server Shutdown Thread")
            {
                public void run()
                {
                    dedicatedserver.stopServer();
                }
            });
```

**Comment by kashike** [comment]
https://github.com/SpongePowered/SpongeCommon/commit/1a3c79f9fa78689a1a3171d77f3a056ef868b801

**Comment by kashike** [comment]
https://github.com/SpongePowered/SpongeCommon/commit/01c3ab6a73b456ed44414f3cac290623e3583b67
