### ISSUE TITLE
Advanced Rocketry Space Stations are not Saving

### ISSUE THREAD

**Issue by Aiidoneus** [SpongePowered/SpongeForge#1816]
**I am currently running...**

- SpongeForge version: _spongeforge-1.10.2-2477-5.2.0-BETA-2691
- Forge version: forge-1.10.2-12.18.3.2477-universal
- Java version: 1.8.0_131
- Operating System:

 - [x]  Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: 
Advanced Rocketry: AdvancedRocketry-1.10.2-1.0.19
LibVulpes: LibVulpes-1.10.2-0.1.19-universal

**What is the expected result?**
Space Station isn't being created or saving
**What is the current result?**
Blocks being manipulated in this dimension are not saving and the space station isn't being created at times. 
I would provide logs but I am not exactly sure what you need or what I am looking for in this case. I did see this post https://github.com/SpongePowered/SpongeForge/issues/1715 and I am still getting these types of issues. I have been trying to figure out what happens to players on my network using this post for information. https://mineyourmind.net/forum/threads/space-station-issues-for-everyone.27009/ I know my current result is a bit all over the place but any help would be appreciated. This happens on the latest version of Age of Engineering Modpack. https://minecraft.curseforge.com/projects/age-of-engineering. I did start this post a while ago on my community forums to get a collective result from players having this issue. In the end, I am not able to determine what the exact issue is.

**Comment by JoeSGT** [comment]
Having the same issue on 1.12.2
Sponge - 7.0.0-BETA-2729
Forge - 14.23.0.2529
Advanced Rocketry - 1.12.2-1.2.5a
LibVulpes - 0.2.6

**Comment by phit** [comment]
try setting `deny-chunk-requests=false` and `keep-spawn-loaded=true` for the space station dimension

**Comment by JoeSGT** [comment]
can't move in the space station but it fixes creating one
in the console it said this
`moved too quickly!`
i cannot move anywhere in the space station
and if i remove sponge i can create and move in my space station

**Comment by phit** [comment]
To quote the comment for this config:
```
# If enabled, any request for a chunk not currently loaded will be denied 
# (exceptions apply for things like world gen and player movement). 
# Note: As this is an experimental setting for performance gain, if you encounter 
# any issues then we recommend disabling it.
deny-chunk-requests=false
```

Closing this, as this is not really a bug but a side effect of an optimization, which you can disable if you have to.

**Comment by ryantheleach** [comment]
To add to this, once https://github.com/SpongePowered/SpongeCommon/pull/1592 is merged you will be able to disable those vanilla checks.
