### ISSUE TITLE
Repeating Command blocks stop looping

### ISSUE THREAD

**Issue by simibubi** [SpongePowered/SpongeForge#1817]
forge: 1.12.2-14.23.0.2503
spongeforge: 1.12.2-2486-7.0.0-BETA-2689

Any command in Repeating Command blocks stopped looping when 
reentering the chunks after a few minutes, it has to be reactivated by a player to operate again:
Always active: Command blocks have to be replaced or changed in the UI
Needs Redstone: Redstone source has to be turned off and back on

**Comment by phit** [comment]
~move to sc

**Comment by limbo-app** [comment]
Hey @simibubi! I've moved your issue to [SpongePowered/SpongeCommon#1815](https://github.com/SpongePowered/SpongeCommon/issues/1815).
