### ISSUE TITLE
Elevators behaving strangely when Sponge is installed

### ISSUE THREAD

**Issue by D3nnis3n** [SpongePowered/SpongeForge#1819]
- SpongeForge version: 2706
- Forge version: 2512
- Java version: 
- Operating System:
 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

**What is the expected result?**
ThutElevators work correctly as they should.
**What is the current result?**
ThutElevators stop working, start working again, stop working - with no log output at all.

See this Video: http://minecraft.godsofwar.de/video3.mp4
And this issue: https://github.com/Thutmose/Thut/issues/71

Maybe you have any idea why this happens and could help to resolve the issue. Unfortunatley nothing is logged at all. Just no Messages since i joined. If you Need something specific nontheless, please just ask and i provide.

**Comment by ryantheleach** [comment]
Is this near spawn? can people break blocks there? It's a bit of a stretch, but maybe it's spawn protection, or a plugin stopping interacts?

**Comment by D3nnis3n** [comment]
I don't know if he had such in his Tests, but no, i have no plugins installed atm (as i Need to remove sponge all day cause of incompatibilitites) and no, that Building is nowhere near where a spawn protection would be, if it wasn't disabled, which it is. This Building is a survial Building of one of our Players - so yes, blocks can be broken and placed.

**Comment by phit** [comment]
closing as this seems to also happen with just the mod, just more rarely
