### ISSUE TITLE
Falling Blocks Duplication Bug

### ISSUE THREAD

**Issue by heyoomimi** [SpongePowered/SpongeForge#1820]
Falling Blocks Duplicating, which includes Sand, Gravel, and Dragon Eggs. 
I have recorded a video of the duplication of a Dragon Egg:
https://youtu.be/r1XUXfnVuYU
This is only occurring on a server, not on Single Player.
I noticed that if I break the top most block, then continue breaking the lower blocks, the dupe won't happen. However, if I don't break the top-most block and continue breaking the center blocks, the block will continuously duplicate itself until there is no space left underneath it. 

**I am currently running...**
Minecraft 1.10.2 (We are running a custom 1.10.2 Modpack)
- SpongeForge version: 1.10.2-2477-5.2.0-BETA-2637
- Forge version: 12.18.3.2477
- Java version: 1.8.0_111

- Operating System:
 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows

**Plugins/Mods: **

Plugins (256): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Applied Energistics 2 Core, Aroma1997Core, OpenComputers (Core), CoFH ASM, FoamFixCore, ccl-entityhook, Nucleus Mixins, Just Enough Items, AbyssalCraft, AbyssalCraft Heads, Mantle, Tinkers' Construct, AbyssalCraft Integration, CoFH Core, Actually Additions, Forge Endertech, Advanced Chimneys, IndustrialCraft 2, Advanced Machines, Advanced Solar Panels, Advanced Swords, Applied Energistics 2, BD Lib, AE2 Stuff, InfinityLib, AgriCraft, Baubles, Botania, Akashic Tome, Animania, AppleCore, AppleSkin, Aquaculture, ArchitectureCraft, TheDragonLib, ArmorPlus, Aroma1997Core|Helper, Aroma1997's Dimensional World, AromaBackup, AromaBackup Recovery, Ars Magica 2, AnimationAPI, AutoPackager, Morph-o-Tool, Psi, Quark, AutoRegLib, CodeChicken Lib, Avaritia, Bagginses, Baubles Stuff, Bed Bugs, Better Builder's Wands, BiblioCraft, Biomes O' Plenty, Guide-API, Blood Magic: Alchemical Wizardry, Blood Arsenal, Bookshelf, Brandon's Core, Craftable Elytra Mod - MCV 1.10.2, Ceramics, Chameleon, Chest Transporter, Chisel, MCMultiPart, Chisels & Bits, ShadowMC, Clipboard, CodeChicken Core, Compact Solar Arrays, Computality, Cooking for Blockheads, CosmeticArmorReworked, Craftable Saddles, Craftable Name Tags, Crafting Tweaks, CraftTweaker JEI Support, MineTweaker 3, Crossroads, Cyclops Core, Dark Utilities, PTRModelLib, Decocraft, Extra Utilities 2, Forestry, ElecCore, EnderStorage, OpenComputers, DeepResonance, Draconic Evolution, Storage Drawers, Drawers & Bits, Elevator Mod, Embers, EnderBags, EnderCore, Ender IO, Ender-Rift, ShetiPhian-Core, EnderTanks, Ender Zoo, End Metals, Engineer's Workshop, Valkyrie Lib, Environmental Tech, ET Lunar, EvilCraft, Mekanism, Thermal Foundation, Thermal Expansion, Exchangers, Expandable Backpacks, Extra Golems, MineFactory Reloaded, Zero CORE, Extreme Reactors, FastAsyncWorldEdit, Fast Leave Decay, Flat Colored Blocks, SonarCore, FluxNetworks, FoamFix, Shadowfacts' Forgelin, Forge Multipart CBE, Forge Microblocks, Minecraft Multipart Plugin, Funky Locomotion, Funnels, GenDustry, Pressure Pipes, Advanced Generators, GeographiCraft, Gravestone Mod, Gravitation Suite, Hammer Core, HelpFixer, Hopper Ducts, The One Probe, Immersive Engineering, Immersive Petroleum, LunatriusCore, InGame Info XML, Interaction Wheel, Inventory Tweaks, Iron Chest, JEI Bees, JourneyMap, KleeSlabs, Long Fall Boots, Loot Bags, MagicBees, MalisisCore, MalisisDoors, MekanismGenerators, MekanismTools, MFR Compat: Vanilla, MineTweakerRecipeMaker, MmmMmmMmmMmm, mob_grinding_utils, MTLib, Mod Tweaker, numina, MachineMuse's Modular Powersuits, Railcraft, RebornCore, TechReborn, More Bees, Morpheus, ModPack Utilities, ModPack Basic Tools, MrTJPCore, Multi-Storage, Mystical Agriculture, Natura, Nether Metals, NetherPortalFix, NotEnoughIDs, OMLib, Open Glider, Open Modular Turrets, Ore Spawn, p455w0rd's Library, Pam's HarvestCraft, Practical Logistics 2, Progressive Automation, ProjectRed Core, ProjectRed integration, ProjectRed Transmission, ProjectRed Illumination, ProjectRed Expansion, ProjectRed Transportation, ProjectRed Exploration, QuantumStorage, Random Things, Ranged Pumps, reborncore-MCMultiPart, Redstone Arsenal, Refined Relocation, Refined Storage, Reliquary, RFTools, RFTools Control, Roguelike Dungeons, Roots, Realistic Terrain Generation, Signals, Simply Jetpacks 2, Sleeping Bag, Solar Flux Reborn, Soul Shards - The Old Ways, Steve's Carts 2, Steve's Factory Manager, Storage Drawers Extras, Super Circuit Maker, Super Crafting Frame, Thermal Dynamics, TickProfiler, Tinkers Tool Leveling, TOP Addons, TorchMaster, Translocator, Useful Nullifiers, Vein Miner, Mod Support, WanionLib, Wireless Crafting Terminal 2, Woot, WorldEdit, WirelessRedstone-CBE, XNet, Boop, Broadcast, CarrotShop, CatClearLag, CommandSigns, CrazyFeetSponge, EconomyLite, NuVotifier, Enjin Minecraft Plugin, GriefPrevention, Holograms, LuckPerms, MMCReboot, Nucleus, Project Core, SeriousVote, SpongyCord, Stack Ban, UniDict

**What is the expected result?**
Not to have the Dragon Egg Duplication.

**What is the current result?**
Dragon Egg gets duplicated.

**Server latest.log**
https://gist.github.com/heyoomimi/0954f977f51789142bb511dca37dddd4

**Comment by bloodmc** [comment]
Old SpongeForge builds are not supported. Update to latest 1.10.2 build
