### ISSUE TITLE
Sponge not letting us cancel block click events.

### ISSUE THREAD

**Issue by Raycoms** [SpongePowered/SpongeForge#1821]
**I am currently running...**

- SpongeForge version: Latest 1.10.2
- Forge version:  latest 1.10.2
- Java version: latest java 8
- Operating System:
 - [ X] Linux RedHat

- Plugins/Mods: 
AdminShop-1.10.2-1.8.2-universal.jar                EconomyLite-5.0.0-2.9.0.jar  MMCReboot-1.7.1-API-5.1.0.jar                    PlayerShopsRPG-v2.0.1.jar
AdventureMMO-v2.0.7-API5.x.jar                      EMPSponge.jar                NoDownfall-2.0.jar                               Prism-3.0.0-beta2-28-g5087827.jar
AutoBroadcaster-0.2.0.jarAutoBroadcaster-0.2.0.jar  latch-0.4.1-S5.1.0.jar       Nucleus-0.23.0-PR2-1.10.2-S5.1-plugin.jar.old    PwnFilter.jar
ClearMob-1.3.1.jar                                  LuckPerms-Sponge-3.2.44.jar  Nucleus-0.26.1-1.10.2-S5.1-plugin.jar            RankUpper-3.0.0-b200.jar.disable
CommandSigns-API-6.0.0-1.3.1.jar                    Luck-Rankup-1.1.jar          PayDay-1.1.0.jar                                 RedProtect-Sponge-6.9.0-b315.jar
deathpenalty-v1.1.jar                               MagiBridge-2.0-all.jar       PermissionManager-2.6.0-API-5.X-6.X.jar.disable  World-RTP-1.0.jar

**What is the expected result?**
Players not being able to acess iron chests since we blocked all their right click events.
**What is the current result?**
Players are able to access iron chests.

I tested this without sponge any I wasn't able to reproduce this issue.

**Comment by phit** [comment]
could you please add a snippet of how you are cancelling the event?

**Comment by phit** [comment]
can't reproduce and no reply, closed.
