### ISSUE TITLE
Advanced Rocketry Data Cable

### ISSUE THREAD

**Issue by ninja0773** [SpongePowered/SpongeForge#1822]
**I am currently running...**

SpongeForge version: _spongeforge-1.10.2-2477-5.2.0-BETA-2691
Forge version: forge-1.10.2-12.18.3.2477-universal
Java version: 1.8.0_131
Operating System:

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [x] Windows

**What is the expected result?**
Data cables attach to the satellite terminal and the data should be transmitted
**What is the current result?**
The server crashes after a short time.
**Description**
This occurs on a server with sponge, but doesn't occur in Single Player or Multiplayer, from my testing. The crash occurs on the Age of Engineering Modpack. Crash log is on paste bin: https://pastebin.com/BrRiaMnd

**Comment by phit** [comment]
Mod issue see https://github.com/zmaster587/AdvancedRocketry/issues/850, https://github.com/zmaster587/AdvancedRocketry/issues/883
