### ISSUE TITLE
Silent Gems - Dupe Bug - Sponge Issue

### ISSUE THREAD

**Issue by Keaton1188** [SpongePowered/SpongeForge#1824]
Hi there, I have noticed a dupe bug with the Chaos Altar, this dupe bug does **NOT** happen on single player so guessing its an issue with sponge.

What you do - Place down the Chaos Alter, put any item in it and break it with a pickaxe, the item that you put in it will double when you break the Altar.

FTB Horizons 3 - Newest Version (1.0.0)

**SpongeForge:**
Minecraft: 1.12.2
SpongeAPI: 7.0.0-SNAPSHOT-bb567e4
SpongeForge: 1.12.2-2503-7.0.0-BETA-2708
Minecraft Forge: 14.23.0.2515

**Comment by LXGaming** [comment]
In `config/sponge/global.conf` under `optimizations` set `drops-pre-merge` to `false`.

**Comment by Keaton1188** [comment]
Its already set to false...

**Comment by phit** [comment]
can't reproduce with spongeforge-1.12.2-2503-7.0.0-BETA-2716, SilentsGems-1.12-2.5.8-238 & SilentLib-1.12-2.2.11-92

placed altar, threw in some wool, broke the altar with diamond pickaxe, tried the same thing with the burner pylon as suggested in [this issue](https://github.com/SilentChaos512/SilentGems/issues/185) and still had no luck reproducing this

**Comment by ghost** [comment]
can't reproduce with spongeforge-1.12.2-2503-7.0.0-BETA-2706/SilentLib-1.12-2.2.10-91.jar/SilentsGems-1.12-2.5.6-232.jar on a horizons 3 server

**Comment by Keaton1188** [comment]
I'll test this again when I am home. Will update sponge then see if the issue is still happening, if it is will get a video of it.

**Comment by Keaton1188** [comment]
Fixed in latest version :) 

Closing.
