### ISSUE TITLE
Bedrock Ores don't drop ores

### ISSUE THREAD

**Issue by BakermanLP** [SpongePowered/SpongeForge#1825]
Hello,

we want to use spongeforge with bedrockores. When we excavate bedrock ores from the mod, no ores are droping. Without spongeforge this works fine.

**I am currently running...**
- SpongeForge version: spongeforge-1.11.2-2476-6.1.0-BETA-2712.jar
- Forge version: forge-1.11.2-13.20.1.2476-universal.jar
- Java version: Oracle Java 1.8.0_144
- Operating System:
 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows
- Plugins/Mods: 
No Plugins for test.

**What is the expected result?**
Harvesting bedrock ores with a pickaxe should drop the ores.

**What is the current result?**
Nothing is dropped.

Full fml-server-latest.log:
http://paste.ubuntu.com/25850428/

Thanks for reading

Michael (aka BakermanLP)

**Comment by fnuecke** [comment]
Going by the warning in the linked issue

```
[09:03:29] [Server thread/WARN] [Sponge]: No entity type is registered for class net.minecraftforge.common.util.FakePlayer
```

I'd guess this might be related to [using the default FakePlayer here](https://github.com/MightyPirates/BedrockOres/blob/9e3e0ec34b6d3d471423733dc433984afc0abd42/src/main/java/li/cil/bedrockores/common/tileentity/TileEntityBedrockOre.java#L155)? If that's not how you're supposed to use it, let me know what I need to change, thanks.

(FWIW, I don't see that warning in the linked log?)

**Comment by phit** [comment]
confirmed with 
spongeforge-1.12.2-2529-7.0.0-BETA-2753.jar
Bedrock Ores-MC1.12-1.2.5.38.jar

https://gist.github.com/phit/cab16fcd8fdeb038bd2803ec91f4205c
