### ISSUE TITLE
[1.12.2] horizons 3 armour doesnt take damge

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1827]
**I am currently running...**

- SpongeForge version:   spongeforge-1.12.2-2503-7.0.0-BETA-2706
- Forge version: forge-1.12.2-14.23.0.2515-universal.jar
- Java version: java8 latest
- Operating System: Cent Os

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods:  http://prntscr.com/h4v6w1  list in there <<<<

**What is the expected result?** armour should take damgae

**What is the current result?** it doesnt

**Comment by ghost** [comment]
https://gist.github.com/baconetworks/b7efb34618fe00d6b96f203e65243a00   <<< full log

**Comment by ghost** [comment]
tried it on a horizons 3 server without spongeforge and armour takes damage

test server is an exact copy of above

GlHf

**Comment by gabizou** [comment]
Can you provide a precise list of instructions on replicating the issue? What items specifically?

**Comment by phit** [comment]
User deleted their account and can't reproduce this with spongeforge-1.12.2-2529-7.0.0-BETA-2730 and Horizons 1.1.0, closed.
