### ISSUE TITLE
[1.11.2] Incorrect work portals

### ISSUE THREAD

**Issue by KorDum** [SpongePowered/SpongeForge#1828]
**I am currently running...**

- SpongeForge version: 1.11.2-2476-6.1.0-BETA-2715
- Forge version: 13.20.1.2476
- Java version: 1.8.0_151-b12
- Operating System:

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins: 
FlexibleLogin 0.16.2
UltimateCore 3.0.11

**What is the expected result?**
1. Portal to Nether will let players out normally.
2. Teleportation of the player to the End will be in the required coordinates.

**What is the current result?**
1. Portal to Nether:
The player from time to time stuck in the portal and does not teleport anywhere. He blocked the ability to write to the chat.

2. Portal to End
After teleportation, the player may appear not in the spawn location, but in the same coordinates as the portal in Overworld

**Comment by phit** [comment]
I have seen this myself in 1.10 and 1.11, but still haven't found a way to reproduce it consistently.

**Comment by KorDum** [comment]
Yes, I can't too. I can't even write the steps.

**Comment by phit** [comment]
just had this happen on our 1.12 server with 7.0.0-BETA-2730

**Comment by Brend-Smits** [comment]
Can confirm as well - No way to reproduce either... 1.10.2-2281-5.2.0-BETA-2597

**Comment by kherock** [comment]
It would be really nice if the End portal bug could be sorted out soon.

I'm on SpongeVanilla 1.12.2-7.0.0-BETA-356. I've noticed the following behavior so far:
* Does not happen while in creative mode
* In survival, you are teleported correctly 80% of the time if you enter through the top of the portal
  * Entering through the side or bottom of the portal will cause you the teleport incorrect as described in this issue 100% of the time

So to reproduce:
1. Start up a new Sponge server with op permission
2. Place an `end_portal` block somewhere
3. Walk into it from the side or jump up from underneath

Note that this bug also applies to the `end_portal` blocks in the bedrock fountain. I've noticed that `end_portal` blocks manually placed in the end behave strangely too, even in creative mode.

**Comment by ryantheleach** [comment]
Lame work around. build a 3x3 room of barrier blocks, at the same location in the end that the portal exists in the overworld. `/blockdata ~ ~1 ~ {Text1:"{\"text\":\"RightClick\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"tp @p 100 49 0\"}}",Text2:"{\"text\":\"ToSafety\"}"}` Put one of these bad boys in.

**Comment by ryantheleach** [comment]
BlockEndPortal::onEntityCollidedWithBlock is called once when entering from the bottom. and like, 2,3,4 times when entering from the top.

Something really funky is going on.

**Comment by phit** [comment]
https://github.com/SpongePowered/SpongeCommon/commit/edc5e0c7e7bda58bf695786de8a6a2cfefb6a9bd
