### ISSUE TITLE
[1.12.2] Dupe issue with Griefprevention cancel event's

### ISSUE THREAD

**Issue by runescapejon** [SpongePowered/SpongeForge#1830]
**I am currently running...**

griefprevention-1.12.1-4.3.0.483.jar
spongeforge-1.12.2-2503-7.0.0-BETA-2725
forge-1.12.2-14.23.0.2515
industrialforegoing-1.12.2-1.5.3-88
LuckPerms v3.4.68
- Operating System: Centos

 - [ X] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: 
https://gyazo.com/72e8c8d29e06d89ebeaa13e266a4a6d0

here is how the Dupe glitch works
you will need 2 people for this
1 person make a claim
then place a block near the claim that you want to dupe with example place a diamond block on the border of your claim
the second person that not trusted in your claim place down Block breaker from
Industrial Foregoing mod and power it if you don't know how it works then it would be easier to use Extra Utilities 2 Creative Energy Source block next the block breaker and it start duping check inside of the block breaker and you will get dupe items
here a GIF on how to do this

https://gyazo.com/a5a1e344f77af9484b5c579155908d48
as you he place a block breaker next to my diamond block and it start to dupe
you can use any source of power to power block breaker i just use Creative energy source because it was faster to show you, it really shows no logs i had report this to GriefPrevention but bloodshot told me to write it here instead because it's SpongeForge issue 

thanks

**Comment by phit** [comment]
report it to the mod author..

https://github.com/Buuz135/Industrial-Foregoing/blob/master/src/main/java/com/buuz135/industrial/tile/world/BlockDestroyerTile.java#L90

**Comment by runescapejon** [comment]
alright Thanks

**Comment by gabizou** [comment]
Closing as it's not a Sponge issue, we throw the events and the mod is not considering that it is cancelled.
