### ISSUE TITLE
Not compatible with newer version of forge

### ISSUE THREAD

**Issue by JoeSGT** [SpongePowered/SpongeForge#1831]
**I am currently running...**

- SpongeForge version: 7.0.0-BETA-2725
- Forge version:  14.23.0.2529
- Java version: java 8
- Operating System:

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [X] Windows
  Not compatible with each other https://pastebin.com/pAEHkgrA
I'll use an older version of forge until this get fix

thanks

**Comment by Tencao** [comment]
Would be nice to see this get updated, as mods have started updating to the newer versions due to the recent changes, making sponge incompatible with a few recent mod updates.

**Comment by gabizou** [comment]
Fixed by https://github.com/SpongePowered/SpongeForge/commit/d16eb67d4f640625ab28863e545757eabddbf719
