### ISSUE TITLE
[1.12.2] TinkerConstruct broke after build 2716

### ISSUE THREAD

**Issue by mblob** [SpongePowered/SpongeForge#1832]
**I am currently running...**

- SpongeForge version: spongeforge-1.12.2-2529-7.0.0-BETA-2726
- Forge version: forge-1.12.2-14.23.0.2529
- Java version: 1.8.0_151
- Operating System:
 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [X] Windows
- Plugins:  SpongeAPI, SpongeForge, Nucleus
- Mods: Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Applied Llamagistics, Applied Llamagistics Core, AutoRegLib, BD Lib, BiblioCraft, Biomes O' Plenty, Chameleon, Chest Transporter, Chisels & Bits, CoFH Core, CoFH World, CodeChicken Lib, Corail Recycleur, Forestry, Immersive Engineering, Inventory Tweaks, Iron Chest, JEI Bees, JourneyMap, Just Enough Items, Mantle, NHAVE's Core, Pressure Pipes, Psi, RFTools, RFTools Control, Redstone Flux, Storage Drawer
s, Storage Drawers Extras, TESLA, TOP Addons, The One Probe, The One Wrench, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Tinkers' Construct, WorldEdit, XNet, mercurius_updater

**What is the expected result?**

**What is the current result?**
TinkerConstruct smeltery and related items not working,assembling anymore.
Log spam of errors.

Removing sponge then TC behaves normally.
Reverting to Sponge 2716 and forge 2503 then TC behaves normally.

[latest-log](https://gist.github.com/mblob/58ccfdd7fd68ccb201e3de70f034ac68)
[fml-server-latest.log](https://gist.github.com/mblob/6f6954d5c55c13ab4ca16463a457dbda)

**Comment by phit** [comment]
update Forge (2529) and Sponge (2727) to latest, and try again @Faithcaio just pushed a fix

**Comment by mblob** [comment]
Seem to be ok.
Thanks.
