### ISSUE TITLE
OpenTerrainGenerator Incompatibility

### ISSUE THREAD

**Issue by Tkdmaster** [SpongePowered/SpongeForge#1835]
Forge Version: forge-1.12.2-14.23.0.2529-universal
SpongeForge Version: spongeforge-1.12.2-2529-7.0.0-BETA-2729
Hosting: localhost
OS: Windows
- Plugins/Mods: Modern Skyblock 2 mods + Open Terrain Generator

**What is the expected result?** 
Server should start

**What is the current result?**
Server crashes with log

https://pastebin.com/MLmmit4y

**Comment by Tkdmaster** [comment]
Issue still persists as of version 2730 of Spongeforge

**Comment by phit** [comment]
not a Sponge issue, looks like the mod is incompatible with Twilight Forest https://github.com/PG85/OpenTerrainGenerator/issues/76
