### ISSUE TITLE
Command blocks desync after switching dimension

### ISSUE THREAD

**Issue by phit** [SpongePowered/SpongeForge#1838]
- SpongeForge version: 1.10.2-2698 & 1.11.2-2484 & 1.12.2-2729
- Plugins/Mods: none

**What is the expected result?**
switch dimension through a nether portal and be able to place a commandblock and access it, without relogging or "opping yourself again"

**What is the current result?**
>when i teleport across two dimensions, after i do it i'm not able to place command blocks : i see them places but can't interact with thm and when i break it it make no particle like if it wasn't really here so i can't use it until i re-op myself even if i'm already ... 

> [logs + client side video of the bug.zip](https://github.com/SpongePowered/SpongeForge/files/1185300/logs.client.side.video.of.the.bug.zip)

originally reported by @Eldwen here https://github.com/SpongePowered/SpongeForge/issues/1684
just tested this again and confirmed this is still an issue

**Comment by ryantheleach** [comment]
Closed in favor of SpongePowered/SpongeCommon#1718 (Reproducible on SV)
