### ISSUE TITLE
[1.12.2] Open Computer issue with SpongeForge

### ISSUE THREAD

**Issue by JoeSGT** [SpongePowered/SpongeForge#1840]
**I am currently running...**

- SpongeForge version: 1.12.2-2529-7.0.0-BETA-2729
- Forge version: 1.12.2-14.23.0.2529
- Java version: 8
- Operating System:

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows
when you have opencomputer mod loaded in the server with spongeforge 
it will give you this error
https://pastebin.com/wAXDrwha
it seem this error don't not show up when i took out spongeforge
and also the opencomputer mod version that i am at is MC1.12.1-1.7.0.23 i had tried 1.7.0.20 but still getting the error

**Comment by phit** [comment]
@Mumfrey looks like a mixin issue, mind taking a look?

**Comment by jfrederickson** [comment]
Experiencing what looks like the same thing with:

- SpongeForge 1.12.2-2555-7.0.0-BETA-2799  
- Forge 1.12.2-14.23.1.2555  
- OpenComputers MC1.12.1-1.7.1.43  
- Debian 9.3  
- OpenJDK 1.8.0_151

https://gist.github.com/jfrederickson/ca64e23202fdb4d105bfb94d4a5b4b14

**Comment by mblob** [comment]
Same here

- spongeforge-1.12.2-2555-7.1.0-BETA-2842

- forge-1.12.2-14.23.1.2555
- OpenComputers-MC1.12.1-1.7.1.43
- gentoo
- oracle jdk "1.8.0_152"

https://gist.github.com/mblob/b310074f0dad5e3997b865d367d01257

**Comment by kencinder** [comment]
Same here

- spongeforge-1.12.2-2611-7.1.0-BETA-2931
- forge-1.12.2-14.23.2.2611
- OpenComputers-MC1.12.1-1.7.1.43
- Debian 9.3
- OpenJDK 1.8.0_151

[fml-server-latest.log](https://github.com/SpongePowered/SpongeForge/files/1754460/fml-server-latest.log)

**Comment by MarkTwoFive** [comment]
Confirmed
* forge-1.12.2-14.23.2.2619
* spongeforge-1.12.2-2611-7.1.0-BETA-2931
* OpenComputers-1.12.2-1.7.1.43
* Ubuntu 16.04.3 LTS (in docker container)
* Oracle-Java (build 1.8.0_161-b12)

https://gist.github.com/MarkL4YG/fec6a51ba3ca084789a0326f7396debd
(Just included one example)

**Comment by MarkTwoFive** [comment]
hmmm...
Added ``&& !transformedName.startsWith("scala")`` to [this statement](https://github.com/SpongePowered/Mixin/blob/master/src/launchwrapper/java/org/spongepowered/asm/mixin/transformer/Proxy.java#L71) and it seemed to fix the issue.
Patch included in the gist above.
I did ___not___ verify if that affects gameplay though. I just bodged around a little knowing not that much about mixins.

Oh and also in my case: MalisisCore ships Sponge mixins for whatever reason so I had to remove those.

**Comment by JoeSGT** [comment]
Still an issue 
- SpongeForge: .12.2-2611-7.1.0-BETA-2953 
- Forge: 1.12.2-14.23.2.2624
- OpenComputers: MC1.12.2-1.7.1.63

**LOGS**
Fml-server-latest.log:
[fml-server-latest.log](https://github.com/SpongePowered/SpongeForge/files/1778187/fml-server-latest.log)
fml-junk-earlystartup.log: 
[fml-junk-earlystartup.log](https://github.com/SpongePowered/SpongeForge/files/1778189/fml-junk-earlystartup.log)

**Comment by JamesMC100** [comment]
Please fix this @gabizou  or @bloodmc i am having this same issue it's really annoying!

**Comment by MarkTwoFive** [comment]
@JamesMC100 I've mentioned a work-around. Try that for the time being.

**Comment by Zidane** [comment]
Apologies for how long this took to fix for something so simple. Somehow slipped through the cracks. Once the new SpongeForge build is deployed it should be fine.

I started a server with OpenComputers and us and it launched.
