### ISSUE TITLE
Sponge Ignoring Global.conf by default

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1842]
Appears that by default the global.conf is not working, for some reason it started working as it should after I changed:     

# This setting does nothing in the global config. In dimension/world configs, it allows the config to override config(s) that it inherits from
    config-enabled=false

to

# This setting does nothing in the global config. In dimension/world configs, it allows the config to override config(s) that it inherits from
    config-enabled=true

**I am currently running...**

- SpongeForge version: spongeforge-1.10.2-2477-5.2.0-BETA-2698.jar
- Forge version: forge-1.10.2-12.18.3.2511-universal.jar
- Java version: OpenJDK Latest
- Operating System:

 - [ X] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods:
 
 Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, Advanced Rocketry, Applied Energistics 2 Core, Aroma1997Core, CreativeCoreDummy, IvToolkit, Micdoodle8 Core, Stuff A Sock In It, SpongeAPI, SpongeForge, CoFH ASM, FoamFixCore, ccl-entityhook, CoFH Core, Actually Additions, IndustrialCraft 2, Advanced Machines, Advanced Solar Panels, libVulpes, Advanced Rocketry, Applied Energistics 2, BD Lib, AE2 Stuff, Baubles, Botania, Akashic Tome, EnderCore, Just Enough Items, Ender IO, Shadowfacts' Forgelin, AnalyzeIO, Extra Utilities 2, AngelRing 2 Bauble, Guide-API, Blood Magic: Alchemical Wizardry, Animus, ArchitectureCraft, Mantle, Tinkers' Construct, TESLA, TheDragonLib, ArmorPlus, Aroma1997Core|Helper, Ars Magica 2, AnimationAPI, Astral Sorcery, Alternate Terrain Generation, Morph-o-Tool, Psi, Quark, AutoRegLib, CodeChicken Lib, Avaritia, CraftTweaker JEI Support, MineTweaker 3, B.A.S.E, Baubles-Hud, Baubles Stuff, Bed Bugs, Better Achievements, BiblioCraft, Blood Arsenal, Bookshelf, Brandon's Core, Chameleon, Chisel, MCMultiPart, Chisels & Bits, Cyclops Core, CommonCapabilities, Cooking for Blockheads, Crafting Tweaks, CreativeCore, Crossroads, Cyberware, Cyclic, Dark Utilities, DebugServerInfo, Forestry, ElecCore, DeepResonance, Draconic Evolution, Earthworks, Embers, Ender Utilities, Ender Zoo, Engineer's Workshop, Valkyrie Lib, Environmental Tech, EvilCraft, Galacticraft Core, Galacticraft Planets, Extra Planets, Mekanism, Thermal Foundation, Thermal Expansion, Zero CORE, Extreme Reactors, Uranium Big Reactor, Fast Leaf Decay, SonarCore, FluxNetworks, FoamFix, Forge Multipart CBE, Forge Microblocks, Minecraft Multipart Plugin, FTBLib, FTBUtilities, FTB Guide Book, GenDustry, Hammer Core, Hardcore Darkness, Hardcore Wither, Hatchery, Hunger Strike, iChunUtil, The One Probe, Immersive Engineering, Integrated Dynamics, Integrated Tunnels, Inventory Tweaks, Iron Backpacks, Iron Chest, It's the little things, JEI Bees, JourneyMap, Levels, LibrarianLib, LLibrary, Literal Ascension, LootTweaker, LunatriusCore, MalisisCore, Malisis Blocks, MalisisDoors, MekanismGenerators, MekanismTools, Mike Dongles, MineTweakerRecipeMaker, Storage Drawers, Refined Storage, Moar Tinkers, MTLib, Mod Tweaker, numina, MachineMuse's Modular Powersuits, Railcraft, RebornCore, TechReborn, More Bees, MoreDefaultOptions, Morpheus, ModPack Utilities, ModPack Basic Tools, MrTJPCore, ShetiPhian-Core, Multi-Storage, Mystical Agriculture, Natura, Natural Pledge, NetherPortalFix, Nice, NotEnoughIDs, Open Glider, OreExcavation, Plants, Platforms, PotionIcons, Practical Logistics 2, Progressive Automation, ProjectRed Core, ProjectRed Exploration, PSIonic Upgrades, QuantumStorage, Random Things, reborncore-MCMultiPart, RebornStorage, Recurrent Complex, Redstone Arsenal, Refined Relocation, Refraction, Reliquary, Reliquia, RFTools, RFTools Control, RFTools Dimensions, Roots, Sanguimancy, Silent Lib, Silent's Gems, Silent's Gems: Extra Parts, Simply Jetpacks 2, Solar Flux Reborn, Stackie, Steve's Carts 2, Tinkers Alloying Addon, TATW, Thermal Smeltery, Tinker I/O, Tinkers' Addons, Tinkers Tool Leveling, Tomb Many Graves, TOP Addons, Totemic, unlimitedtweaks, Vitality, WanionLib, Waystones, WIRED: More Augs, Woot, XNet, Xtones, YABBA, Fluidity, LibrarianLib Stage 2, UniDict

**What is the expected result?**
Global.conf will override the other worlds settings

**What is the current result?**

Global.conf does nothing, the sub folders are being regenerated on each startup.

**Comment by phit** [comment]
I think you are misunderstanding the configuration, global.conf will always be overridden by more specific configs be it for specific worlds or dimension types if they are enabled. And of course "subfolders" will be regenerated if you delete them at each startup, that's intentional. 

Could you please elaborate what config option you set, in which file and what exactly didn't work?

**Comment by ghost** [comment]
Doing any changes the the configs in the subfolders makes them regenerate. All I did was change the dims from loading on start to false and it always reverts to true.

**Comment by ryantheleach** [comment]
It might not have been able to parse them, or you may have unintentionally renamed them if you got the file extension incorrect.

@Astralick are you able to verify the files on http://www.hoconlint.com/ and see if they validate, before saving and seeing if they regenerate?

**Comment by ghost** [comment]
Hello, better explanation of the issue. Everything is correct with the configs/file names.

There is Advanced Rocketry + Galaticraft and extra planets, together these add around 100 dimensions and by default Sponge was loading the spawn for every single dimension causing the server instance to freeze from too much being loaded and eventually crash, isn't a server issue as it has a 5ghz i7 7700k + 25GB of RAM dedicated to it. (This also is making it gen the spawn every startup which makes loading take ~10+ minutes)

I have it set in global to not load dims on start and they still are all loading, in the worlds file that gens the dims are enabled to load on startup and manually changing it to off causes the file to be regenerated on the next boot.

The only work around I have found is that I have to disable dims being registered in global.conf, load the server, then edit global.conf to enable dims being registered and do /sponge reload -g to register the dims without loading in the spawns.

There has been one time where the server was able to load the dims without freezing long enough for the chunks to unload, but obviously the server taking at least a bit over 10 min to be playable is an issue. The server is using a 480GB PCI NVME SSD that gets 2GBps so that is not bottlenecking loading at all either.

**Comment by phit** [comment]
you have to enable the configs for them to not regenerate by setting `config-enabled=true` in each config you change

**Comment by ghost** [comment]
Thank you that was the issue.
