### ISSUE TITLE
Forestry Centrifuge ClassCastException

### ISSUE THREAD

**Issue by phit** [SpongePowered/SpongeForge#1843]
**I am currently running...**
- SpongeForge version: spongeforge-1.12.2-2529-7.0.0-BETA-2730
- Plugins/Mods: forestry_1.12.2-5.7.0.210

full log is 450mb of this https://gist.github.com/phit/8318f6c3c13a5e0f2def5bd1850568b2

https://github.com/ForestryMC/ForestryMC/blob/mc-1.12/src/main/java/forestry/factory/tiles/TileCentrifuge.java#L49

**Comment by ryantheleach** [comment]
`public class TileCentrifuge extends TilePowered implements ISocketable, ISidedInventory, IItemStackDisplay {`

`public abstract class TilePowered extends TileBase implements IRenderableTile, ISpeedUpgradable, IStreamableGui {`

`public abstract class TileBase extends TileForestry {`

`public abstract class TileForestry extends TileEntity implements IStreamable, IErrorLogicSource, ISidedInventory, IFilterSlotDelegate, ITitled, ILocatable, IGuiHandlerTile, ITickable {`


@Faithcaio My guess is IInventory or some abstract inventory vs ISidedInventory?
