### ISSUE TITLE
Exception during phase body (console spam)

### ISSUE THREAD

**Issue by Whazaaaaa** [SpongePowered/SpongeForge#1845]
**I am currently running...**
- SpongeForge version: 1.12.2-2529-7.0.0-BETA-2730   
- Forge version: 14.23.0.2532  
- Java version: 8
- Operating System:
 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows
- Plugins/Mods: 
Modpack: AllTheMods3 (4.5)
Plugins: Betterchunkloader,Discordbridge,griefprevention,luckperms,nucleus,projectcore,seriousvote,rankup,stackban,totaleconomy,worldedit
**What is the expected result?**
No console spam. Or nothing happening with what seems to be an ic2 item.
**What is the current result?**
https://pastebin.com/aLPQh3bB
https://pastebin.com/X5tzYWUq
And its creating a fml-junk file of insane size

**Comment by Keaton1188** [comment]
Maybe similar to this - https://github.com/SpongePowered/SpongeForge/issues/1773

Also have the same issues you are having on our Horizons 3 server.

**Comment by phit** [comment]
pretty much the same as https://github.com/SpongePowered/SpongeForge/issues/1843 but for IC2
