### ISSUE TITLE
[1.12.2] Tile data not saving properly

### ISSUE THREAD

**Issue by Tencao** [SpongePowered/SpongeForge#1848]
**I am currently running...**
- SpongeForge version: 1.12.2-2529-7.0.0-BETA-2730
- Forge version: 14.23.0.2529 
- Java version: 8
- Operating System: Windows 10
 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [X] Windows
- Plugins/Mods: 
Plugins (17): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, BungeeTabListPlus-SpongeBridge, LuckPerms, Nations, Nucleus, Prism, ProjectCore for SpongeAPI 7.x, ProjectPortals for SpongeAPI 7.x, ProjectWorlds for SpongeAPI 7.x, RankUpper, SpongyCord, TimeWarp, Total Economy, Universe Guard
Mods (148): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AE2 Stuff, Animania, Applied Fluidics, Applied Llamagistics, Applied Llamagistics Core, AutoPackager, AutoRegLib, BC Builders, BC Energy, BC Factory, BC Robotics, BC Silicon, BC Transport, BD Lib, Better Advancements, BiblioCraft, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Biomes O' Plenty, Bloodmoon, BuildCraft, BuildCraft Lib, Can I Join Now?, Chameleon, ChickenChunks, Chisel, Chisels & Bits, CoFH Core, CoFH World, CodeChicken Lib, Compact Solar Arrays, Compacter, ComputerCraft, Corail Pillar, Corail Pillar - Quark Extension, Coralreef, CoroUtil Library, CosmeticArmorReworked, CraftStudio API, CraftTweaker JEI Support, CraftTweaker2, Crafting Tweaks, DeepResonance, DiscordIntegration, Dynamic Surroundings, ElecCore, Elevator Mod, Ender Zoo, EnderStorage, Energy Converters, Environmental Tech, Ex Compressum, Ex Nihilo Creatio, Extended Mod Config, Extended Renderer, Extra Utilities 2, Extreme Reactors, FTBLib, Fairy Lights, FoamFix, FoamFixCore, Forestry, Funky Locomotion, GenDustry, Gravestone Mod, Hardcore Darkness, HelpFixer, Immersive Engineering, Immersive Petroleum, Industrial Wires, IndustrialCraft 2, Inventory Tweaks, Iron Chest, IvToolkit, JEI Bees, Just Enough Items, KleeSlabs, Localized Weather & Storms, Login Shield, MPUtils, MTLib, Malisis Blocks, MalisisCore, MalisisDoors, Mantle, MineTweakerRecipeMaker, Missing Pieces, Mod Tweaker, ModPack Basic Tools, More Bees, MrCrayfish's Furniture Mod, Natura, NetherPortalFix, New Age Bee Breeding, No More Drops, NoMoreRecipeConflict, Not Enough Wands, Plethora, Plethora Core, PlusTiC, ProjectE, PvPTime, Quark, Reborn Core, Recurrent Complex, Redstone Flux, Redstone Paste, Reforged, Roguelike Dungeons, SAOMC Library, Shadowfacts' Forgelin, Simply Conveyors & More, Spartan Shields, Spectrite, Steve's Carts 2, Storage Drawers, Storage Drawers Extras, SwingThroughGrass, TESLA, TOP Addons, Teslafied, The One Probe, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Tinkers Tool Leveling, Tinkers' Construct, UBC Ore Registrar, Underground Biomes, UniDict, Valkyrie Lib, WTFs Expedition, WanionLib, Wither Skeleton Tweaks, WorldEdit, XNet, Zero CORE, denseores

**Description**
Currently all tile data gets reset when either a chunk is unloaded or the server restarts, resulting in everything from vanilla chests to modded items like immersive engineering and IC2 having their entire block reset. 

**What is the expected result?**
Tile data to get saved

**What is the current result?**
Tile data not saved

**Log**
https://gist.github.com/Tencao/171b699f00abe03220c03e3bfae18d08

**Comment by Tencao** [comment]
Can you please let me know what more information is needed, as I'd be happy to provide whats needed to resolve this issue.

**Comment by phit** [comment]
sorry! basically figure out what mods are needed to reproduce this, the modlist is way too long to realistically test this for us

**Comment by Tencao** [comment]
I do know this wasn't an issue until recently, so I'm going to try downgrading sponge version to see if I can find a version that this issue started on.

**Comment by Tencao** [comment]
https://paste.ee/r/oDsT3
I'm seeing a lot of stuff like this, if this helps.

**Comment by Tencao** [comment]
Done some additional testing and turned out to be a forge bug, sponge just made it more apparent. Since the bug wasn't linked to sponge and is now fixed, I'm closing the issue.

**Comment by ryantheleach** [comment]
@Tencao I'd appreciate a link to the forge ticket if you have it handy.

**Comment by Tencao** [comment]
I haven't made one yet as it was mostly discussed via irc, and I haven't been able to pinpoint exactly what but it was either custom chunk loader settings or dormant chunk cache in the forge chunk config

**Comment by liach** [comment]
Is this related to MinecraftForge/MinecraftForge#3325?

**Comment by Tencao** [comment]
Yeah that sounds a lot like the issue I was having actually

**Comment by phit** [comment]
your forge version shouldn't be affected by this though :/

**Comment by Tencao** [comment]
Shouldn't but that's the issue I was having
