### ISSUE TITLE
Cyclic Block Placer - Dupe Bug

### ISSUE THREAD

**Issue by Keaton1188** [SpongePowered/SpongeForge#1850]
Hi all, we are having a issue with the Block Placer from Cyclic.
With this item you are able to duplicate any block.

***How to reproduce: All you have to do is place a block placer down (On a sponge server) and set it to "Always on". Place any block inside it, it will place this block then you use a pickaxe to destroy it then it will replace the block again etc etc. 

This does not happen on single player. Owner of the mod can't reproduce on SP - https://github.com/PrinceOfAmber/Cyclic/issues/570 

SpongeForge:
Minecraft: 1.12.2
SpongeAPI: 7.0.0-SNAPSHOT-14f459d
SpongeForge: 1.12.2-2529-7.0.0-BETA-2730
Minecraft Forge: 14.23.0.2528

**Comment by phit** [comment]
I'm gonna close this, it has the same cause as the Scepter dupe. For more info I posted a summary in its issue https://github.com/SpongePowered/SpongeForge/issues/1836
