### ISSUE TITLE
ClassCastException in createSpongeBlockSnapshot

### ISSUE THREAD

**Issue by rob5251** [SpongePowered/SpongeForge#1851]
**I am currently running...**

- SpongeForge version: 1.12.2-2529-7.0.0-BETA-2730
- Forge version: 14.23.0.2529
- Java version: Version 8 Update 151 (build 1.8.0_151-b12)
- Operating System:

 - [X] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

**Plugins/Mods:** 
_Plugins:_  
Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, Enjin Minecraft Plugin, GriefPrevention, LuckPerms, MMCRestrict, MagiBridge, Nucleus, Prism, PrismPlus
_Mods:_  
Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AE2 Stuff, Actually Additions, Actually Baubles, AngelRing 2 Bauble, Applied Energistics 2, Aroma1997Core, AromaBackup, AromaBackuprecovery, AutoRegLib, B.A.S.E, BD Lib, Baubles, Better Builder's Wands, BiblioCraft, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Biomes O' Plenty, Botania, Brandon's Core, Chest Transporter, ChickenChunks, Chisel, Chisels & Bits, Clumps, CoFH Core, CoFH World, CodeChicken Lib, Crafting Tweaks, Draconic Evolution, Elevator Mod, EnderStorage, Extra Utilities 2, Extreme Reactors, FTBLib, Flux Networks, Forestry, Gravestone Mod, Immersive Engineering, IndustrialCraft 2, InstantUnify, Interaction Wheel, Inventory Tweaks, Iron Backpacks, Iron Chest, JEI Bees, JourneyMap, Just Enough Items, Mantle, Morpheus, Natura, NetherPortalFix, Not Enough Wands, Quark, Quick Leaf Decay, RFTools, RFTools Control, Reborn Core, Redstone Flux, SonarCore, Steve's Carts 2, The One Probe, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Tinker I/O, Tinkers' Construct, Waystones, XNet, YABBA, Zero CORE

**What is the expected result?**
Place an item in the world by pressing a button (Part of Draconic Evolution mod)

**What is the current result?**
Item is not placed, error in server log
Issue was not present before sponge moved to forge 2529

[SERVER LOG](https://gist.github.com/rob5251/60cc20e2f5e67f76dbdad74480b2c257)

- - -
https://github.com/brandon3055/Draconic-Evolution/issues/962

**Comment by phit** [comment]
@gabizou side effect of https://github.com/SpongePowered/SpongeForge/commit/d16eb67d4f640625ab28863e545757eabddbf719 ?
