### ISSUE TITLE
Players not respawning if they didn't sleep yet.

### ISSUE THREAD

**Issue by Raycoms** [SpongePowered/SpongeForge#1860]
**I am currently running...**

- SpongeForge version: spongeforge-1.12.2-2503-7.0.0-BETA-2706.jar
- Forge version: forge-1.12.2-14.23.0.2515
- Java version: 1.8
- Operating System:

 - [X ] Linux ( Fedora)

- Plugins/Mods: 

> 1.12MoVillages-1.5.4.jar                           
> CookingForBlockheads_1.12.1-6.3.6.jar         
> journeymap-1.12.2-5.5.1.jar                    
>  roots-2-0.103.jar
> AkashicTome-1.2-10.jar                             
> CraftTweaker2-1.12-4.0.8.jar                  
> JustAFewFish-1.7_for_1.12.jar                   
> SBM-WoodenShears-1.12-0.0.1b8.jar
> AppleCore-mc1.12.2-2.2.2.jar                       
> CreativePlus_MC1.12_v1.0.1.jar                
> JustEnoughResources-1.12.2-0.8.5.26.jar         
> ShadowMC-1.12-3.8.0.jar
> AppleSkin-mc1.12-1.0.8.jar                        
>  CTM-MC1.12-1.2.3.9.jar.clientside             
> KleeSlabs_1.12-5.3.2.jar                        
> shetiphiancore-1.12.0-3.5.4.jar
> armorplus-1.12.2-11.7.2.24-beta.jar                
> CustomMainMenu-MC1.12.2-2.0.8.jar.clientside  
> LibLoader.jar                                 
> shulkerbox-1.3.0.jar
> ATLCraftCandlesModMC1.12-Ver1.9.jar                
> CustomNPCs_1.12.0(22jul17)beta.jar            
> limelib-1.12-1.7.4.jar                         
>  signpost-1.12-1.05.5.jar
> AutoRegLib-1.3-14.jar                              
> DefaultOptions_1.12.-9.2.4.jar.clientside     
> malisiscore-1.12.2-6.1.7.jar                   
>  Snad-1.12.1-1.7.09.16a.jar
> backpacks 1.12.2 - 3.3.2.jar                     
>   DefaultWorldGenerator-port-1.12-2.2.jar  
>      malisisdoors-1.12.2-7.1.1.jar                 
>   SophisticatedWolves-1.12.2-3.10.0.jar
> base-1.12-3.4.2.jar                              
>   Durability Show-1.12-5.0.0.jar.clientside    
>  Mantle-1.12-1.3.1.21.jar                        
> SpartanShields-1.12-1.3a.jar
> BedBugs-1.12-1.0.1.jar                             
> DynamicLights-1.12.1.jar.clientside           
> minecolonies-universal-1.12.2-0.8.4832.jar     
>  StandardExpansion-2.4.134.jar
> BetterAdvancements-1.12.2-0.0.3.15.jar.clientside  
> DynamicSurroundings-1.12.2-3.4.7.2.jar        
> MineMenu-1.12.2-1.6.2-universal.jar.clientside  
> StorageDrawers-1.12.1-5.3.3.jar
> BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar    
> Earthworks-1.12-1.3.6.jar                                       
> TConstruct-1.12-2.7.4.34.jar
> BetterFps-1.4.8.jar.clientside                   
>   ediblebugs-mc1.12.2_eb1.6.0.2512.jar          
> modtweaker-4.0.3.jar                            
> thedragonlib-1.12.2-5.2.0.jar
> BetterQuesting-2.5.236.jar                         
> ElevatorMod-1.12-1.3.4.jar                   
>  Morpheus-1.12-3.3.2.jar                         
> TickProfiler-1.12-0.0.1.jar
> BiomesOPlenty-1.12.2-7.0.1.2301-universal.jar     
>  EnchantingTable-1.12-1.1.2.jar               
>  MouseTweaks-2.8-mc1.12.1.jar.clientside         
> Tinkers_Addons-1.12.1-1.0.7.jar
> BirdsNests1.12.2-2.0.0.jar                         
> EnderZoo-1.12.1-1.4.0.49.jar                  
> MTLib-3.0.1.jar                                 
> TinkerToolLeveling-1.12-1.0.2b.jar
> blockdrops-1.12-1.3.0.jar.clientside               
> expandedbonemeal-1.11-1.2.1.jar              
>  NetherPortalFix_1.12.1-5.3.13.jar               
> tinyprogressions-1.12-3.2.10_-_Beta.jar
> bonsaitrees-1.0.0-b36.jar                         
>  ExtraAmbiance_MC1.12_v1.0.1.jar              
> NoMoreRecipeConflict-0.91.12.jar               
>  Toast Control-1.12-1.2.0.jar
> CarryOn_MC1.12_v1.7.jar                           
>  ExtraBitManipulation-1.12-3.2.1.jar           
> OpenEye-1.12.1-0.8.jar                        
>   TombManyGraves-1.12-4.0.2.jar
> Ceramics-1.12-1.3.3b.jar                           
> fairylights-2.1.1-1.12.jar                    
> OreExcavation-1.4.105.jar                      
>  TrashSlot_1.12.1-8.4.6.jar
> Chameleon-1.12-4.1.3.jar                          
>  FarmingForBlockheads_1.12-3.1.5.jar           
> Pams_Get_all_the_Seeds_1.12a.jar               
> TschippLib_MC1.12_v1.1.jar
> ChestTransporter-1.12-2.8.7.jar                    
> foamflower-1.12.2-1.0.0.0-beta1.jar           
> Pam's HarvestCraft 1.12.2a.jar                  
> VE-FluidHandling-1.12-0.8.0b10.jar
> Chisel-MC1.12-0.0.14.18.jar                        
> Forgelin-1.5.1.jar                           
>  Ping-1.12-1.4.2.jar                             
> vending-1.12.2-3.0.0.0.jar
> chiselsandbits-14.9.jar                            
> Guidebook-1.12.0-1.7.3.jar.old                
> platforms-1.12.0-1.4.1.jar                     
>  Waddles-1.12.2-0.5.6.jar
> clarity-1.0.jar                                    
> HoloInventory-1.12.2-2.0.2.148.jar           
>  Quark-r1.3-112.jar                              
> WailaHarvestability-mc1.12-1.1.12.jar
> Clipboard-1.12-1.3.0.jar                           
> Hwyla-1.8.20-B35_1.12.jar                     
> questbook-3.0.0-1.12.jar                    
>     Wawla-1.12.2-2.5.246.jar
> Clumps-3.0.0.jar                                  
>  InventoryTweaks-1.63.jar.clientside          
>  ReAuth-3.5.2.jar.clientside                    
>  wolfarmor-1.12.2-2.1.0.24-RELEASE.jar
> ColorUtility-universal-1.0.4.jar                 
>   ironchest-1.12.2-7.0.34.820.jar               
> RebornCore-1.12.2-3.4.8.138-universal.jar    
>    WoodenBuckets-1.12-0.2.0b10.jar
> comforts-1.12.2-0.0.8-rc2.jar                      
> itlt-1.12-1.0.0.jar                           
> redstonepaste-mc1.12-1.7.5.jar                  
> worldedit-forge-mc1.12-6.1.8-dist.jar
> Controlling-3.0.4.jar.clientside                   
> jei_1.12.2-4.8.0.110.jar                    
>   ResourceLoader-MC1.12.1-1.5.3.jar             
>   Xtones-1.12-1.0.6-9.jar
> 
> AdventureMMO-v2.0.7-API6.x.jar.notworking
>   Latch-0.4.4-S7.0.0.jar       
>     Nucleus-1.2.0-PR3-S7.0-MC1.12.2-plugin.jar  
> pwnfilter-3.4.0.jar.dis
> ClearMob-2.0.0.jar                         
> LuckPerms-Sponge-3.4.49.jar      
> Official.zip                                
> Rankup-V4392-API7-plugin.jar
> CommandSigns-API-6.0.0-1.3.1.jar           
> MagiBridge-API7-2.4.1-all.jar    
> PayDay-1.2.1.jar                            
> RedProtect-7.3.0-b53-Universal.jar
> EconomyLite-7.0.0-2.13.0.jar               
> MMCReboot-2.1.1-API-5.1-6.X.jar  
> PlayerShopsRPG-v0.2.0.jar
> holograms-2.2.jar                        
>   MMCRestrict-1.3.1-API-7.jar      
> Prism-3.0.0-beta2-61-ge0dbdbe.jar

**What is the expected result?**
Players respawn normally
**What is the current result?**
Players don't respawn when they die, if they haven't sleeped yet to set a spawmpoint.

**Comment by phit** [comment]
Find out what on your huge plugin/mod list is causing it, this is impossible to test for us. Also update Sponge and Forge, outdated versions won't get any support.

**Comment by Raycoms** [comment]
Found it 

Not sure if it is your or his fault:

https://github.com/TheIllusiveC4/Comforts/issues/4

**Comment by phit** [comment]
can you add your actual log to this issue and please not as a screenshot, use https://gist.github.com

**Comment by Raycoms** [comment]
As a Gist: https://gist.github.com/Raycoms/d005939a1edeb22e1b416efed3e851c7

**Comment by ryantheleach** [comment]
@Raycoms this should have been fixed externally by comforts, but there may still be issues we need to investigate.

**Comment by Raycoms** [comment]
Thanks a lot for the support. Will try it out later today.
