### ISSUE TITLE
VoidIslandControl and Sponge not working together.

### ISSUE THREAD

**Issue by Whazaaaaa** [SpongePowered/SpongeForge#1861]
Hello,

I'm currently running a Modern SkyBlock2 server and whenever people go to the nether it seems something breaks. And they are unable to use /warp or /home (I know thats nucleus) because something breaks on the player itself.

So when the person goes back through the nether portal, the player disconnect with an "Internal server error" and once they reconnect they can use the portal again but the commands are still not working. Then the player has to reconnect again and everything is fine again.

Now in the process of this the console gives an error which makes it clear it has to do with voidislandcontrol. Here's what I got in the console:
https://gist.github.com/Whazaaaaa/697edc4dfcd9a7628aa0cb514339bb7e

**I am currently running...**
- SpongeForge version: spongeforge-1.12.2-2529-7.0.0-BETA-2732
- Forge version: forge-1.12.2-14.23.0.2544-universal
- Java version: 8
- Operating System:
 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows
- VoidIslandControl: voidislandcontrol-1.2.5
- Plugins/Mods: 
Plugins (20): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, BetterChunkLoader, Discord Bridge, Enjin Minecraft Plugin, GoonUtils, GriefPrevention, LuckPerms, NuVotifier, Nucleus, PlayerShopsRPG, ProjectCore for SpongeAPI 7.x, SeriousVote, SkyClaims, StackBan for SpongeAPI 7.x, Total Economy, WorldEdit, f48d75cd4c5771bd

**What is the expected result?**
For Sponge to not break when people go between dimensions when using voidislandcontrol
**What is the current result?**
Sponge breaks the player, and because of that the player has to reconnect twice (minimum) to get it fixed.

Again this should be the information needed:
https://gist.github.com/Whazaaaaa/697edc4dfcd9a7628aa0cb514339bb7e

If more information is needed, please do ask but i've tested this with only spongeforge and voidislandcontrol and the same thing happens.
Its the easiest to reproduct. Just make a server with spongeforge and voidislandcontrol. Make a nether portal. go through it. You get to the nether fine. But when going back you get an internal server error. Now when joining again and going back through. You get back to the overworld. But still some things are broken.
And here another one from me only trying spongeforge + voidislandcontrol.
https://gist.github.com/Whazaaaaa/4fa0768d2bbea646f3d695c47e6f396e

Please this is an essential mod for Modern SkyBlock2, and this happening (I think it has to do with it making the nether 1:1 with the overworld) breaks the gameplay alot.

Thank you.

**Comment by ryantheleach** [comment]
https://github.com/Bartz24/VoidIslandControl/blob/master/src/main/java/com/bartz24/voidislandcontrol/EventHandler.java#L273

**Comment by Whazaaaaa** [comment]
I dont understand. Am I supposed to do something with that link? Or is it just a reference to look at later? Can I do something about this. The Nether being broken is a real problem on Modern SkyBlock2.

**Comment by Dockter** [comment]
Seems to me that this mod is handing this event all wrong.

**Comment by Whazaaaaa** [comment]
Okay so I asked the author of the mod to look at it and he said he fixed it. Feel free to close this or look into it for further problem solving.
