### ISSUE TITLE
Opening XNET controller gets you kicked from server

### ISSUE THREAD

**Issue by JackHNT2** [SpongePowered/SpongeForge#1867]
SpongeForge:
Minecraft: 1.12.2
SpongeAPI: 7.0.0-SNAPSHOT-14f459d
SpongeForge: 1.12.2-2529-7.0.0-BETA-2730
Minecraft Forge: 14.23.0.2528

When you open the XNET controller you get kicked from the server with a fatal error. Only happens on server with sponge, not in singleplayer.

**Comment by phit** [comment]
please add your fml-junk-earlystartup.log, preferably uploaded to http://gist.github.com

**Comment by JackHNT2** [comment]
The thing is it is on a server that i dont have access to the files for. I have a fml-server-latest.log, if that is any help. I could request that file, but it may take a few mins to come through.

**Comment by phit** [comment]
get the server owner to report it here, we can't really help without a log

**Comment by JackHNT2** [comment]
Remove this thread, ill get the owner to report it
