### ISSUE TITLE
Server crashes while unloading worlds while stopping

### ISSUE THREAD

**Issue by xorinzor** [SpongePowered/SpongeForge#1868]
**I am currently running...**

- SpongeForge version: spongeforge-1.12.2-2529-7.0.0-BETA-2736
- Forge version: forge-1.12.2-14.23.0.2546-universal
- Java version: 1.8.0_151
- Operating System: CentOS

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

- Plugins/Mods: All the Mods 3 modpack

**What is the expected result?**
While shutting down it should save the dimensions, then unload all of them.

**What is the current result?**
With SpongeForge: https://pastebin.com/pd7ZCmub
Without SpongeForge: https://pastebin.com/iZL7KrKA

Full SpongeForge error Log: https://pastebin.com/REancwVm

**Comment by phit** [comment]
Thank you for your report, to make it easier for us to reproduce this it would be helpful if you can isolate what mods are needed to reproduce this as it doesn't happen with just SpongeForge.

**Comment by xorinzor** [comment]
@phit I did what you asked, took me quite a while to accurately pinpoint the cause:

This combination of mods will cause the error:
- spongeforge-1.12.2-2529-7.0.0-BETA-2736
- LibVulpes-1.12.2-0.2.6-11-universal
- AdvancedRocketry-1.12.2-1.2.5a-22
- astralsorcery-1.12.2-1.8.2

As soon as AstralSorcery is combined with AdvancedRocketry it'll generate a lot of dimensions, after  shutting down the server, the error will occur.

(I recommend setting the SpongeForge watchdog to about 600.000 ticks to prevent it from prematurely shutting down the server because it thinks it crashed).

Once you remove AstralSorcery it won't cause this error anymore (although for some reason it still thinks something ERRORED).

**Comment by phit** [comment]
Thanks, that should make finding the source a lot easier!

**Comment by phit** [comment]
This should be fixed in the latest 1.12.2 versions!
