### ISSUE TITLE
 XNET Controller - fatal Error 

### ISSUE THREAD

**Issue by Keaton1188** [SpongePowered/SpongeForge#1869]
SpongeForge:
Minecraft: 1.12.2
SpongeAPI: 7.0.0-SNAPSHOT-cc44fdf0
SpongeForge: 1.12.2-2529-7.0.0-BETA-0
Minecraft Forge: 14.23.0.2528

When you open the XNET controller you get kicked from the server with a fatal error. Only happens on server with sponge, not in singleplayer.

[fml-server-latest.log](https://github.com/SpongePowered/SpongeForge/files/1486108/fml-server-latest.log)

https://gist.github.com/Keaton1188/594a56dde8e4a11ca0d050a03217d4b7

**Comment by phit** [comment]
relevant stacktraces https://gist.github.com/phit/7ec3b1666c3dd1cb9e1f897e39d77eb0
doesn't look like a Sponge issue to me, but I'll let someone else decide

**Comment by gabizou** [comment]
Did you try without sponge on the server?

**Comment by ParsaRezaei** [comment]
does this issue have a solution yet?

**Comment by Keaton1188** [comment]
@gabizou Not tried without sponge on the server but have tested in SP and it wasn't an issue.

Still is an issue at the moment.

**Comment by Zidane** [comment]
Testing in SinglePlayer literally means nothing. There are numerous things that are different on a dedicated server.

Closing until you can test this again against the latest RB of SpongeForge and without SpongeForge and compare the results. If it does crash, respond back with your logs.
