### ISSUE TITLE
Keepinventory bug with SF -2736

### ISSUE THREAD

**Issue by JoeSGT** [SpongePowered/SpongeForge#1870]
**I am currently running...**

- SpongeForge version: 7.0.0-BETA-2736.
- Forge version: 1.12.2-14.23.0.2549
- Java version: java 8
- Operating System:

 - [ ] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [X] Windows

- Plugins/Mods: 
https://gyazo.com/2847484ea987edf10c4322775eef5966

**What is the expected result?**
cleared your inventory once you die if you ran the command `/gamerule keepinventory true`
so once you have your inventory fill with items and you already have keepinventory true and if you attempt to die in anyway you will lose your items and it does not drop on the floor it just disappear from your inventory 
this only happen in SpongeForge 2736 if i go back to the old one at SF version 2732  it doesn't happen

**Comment by ryantheleach** [comment]
Duplicate of: https://github.com/SpongePowered/SpongeForge/issues/1864

**Comment by JoeSGT** [comment]
oop's sorry i didn't know I'll close this issue
