### ISSUE TITLE
LittleMaids not spawning, with or without egg

### ISSUE THREAD

**Issue by tetsune** [SpongePowered/SpongeForge#1874]
**I am currently running**
- SpongeForge version: spongeforge-1.10.2-2477-5.2.0-BETA-2698
- Forge version: forge-1.10.2-12.18.3.2477-universal
- Java version: 1.8 151
- Operating System: Windows 10

**- Plugins/Mods:**
Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, Aroma1997Core, CreativeCoreDummy, IvToolkit, SpongeAPI, SpongeForge, ccl-entityhook, Extended Workbench, EBLib, LittleMaidReengaged, Mo' Villages, Forge Endertech, Advanced Chimneys, Baubles, Just Enough Items, Extra Utilities 2, AngelRing 2 Bauble, AppleSkin, Aroma1997Core|Helper, Aroma1997's Dimensional World, AromaBackup, AromaBackup Recovery, Baby Animals Model Swapper, Backpack, Base Metals, Baubles Stuff, BetterBedrockGen, BiblioCraft, Biomes O' Plenty, MrCrayfish's Furniture Mod, Chameleon, Saplings-to-charcoal, CodeChicken Lib, CodeChicken Core, ChickenChunks, Chisel, Cooking for Blockheads, CosmeticArmorReworked, Crafting Tweaks, CreativeCore, Death Quotes, PTRModelLib, Decocraft, Dirt2Path, Disenchanter, Elevator Mod, Ender Compass, EnderStorage, Fast Leaf Decay, Ender Flowergirls, Grapple Hooks, GraveStone, GraveStone-Extended, Guide-API, Harvest, Waila, Inventory Tweaks, Just a Few Fish, Loot Bags, Mantle, Natura, Missing Pieces, MKN Utils, More Materials, MorePlayerModels, More Shearables, mxTune, Nether Core, No Mob Spawning on Trees, NoMoreRecipeConflict, Ore Dictionary Converter, Ore Spawn, Pam's HarvestCraft, Tinkers' Construct, PlusTiC, Potion Packs, GUI Library, PaintingSelectionGui, Random Things, Recurrent Complex, Ruins Spawning System, Sign Post, SophisticatedWolves, Storage Drawers, Storage Drawers Extras, Tinkers Tool Leveling, Tool Belt, Vanilla Builders Extension, I Can See Everything, What Are We Looking At, Yet Another Food Mod, Yet Another Leather Smelting Mod, Corail Pillar

**Issue Description:**
Seems there's an issue with Little Maid Reengaged. I tried loading a server with an without SpongeForge, on the server and on a local client. It worked perfectly fine without SpongeForge, but with SpongeForge, my sister attempted to summon a LittleMaid with an egg and nothing happened. She could summon a Villager just fine, and everything else was spawning naturally.
No Maids spawned naturally with SpongeForge.

Is this a problem with a config or with SpongeForge?

**Server Log:**
https://gist.github.com/tetsune/d3ba483e9c32fb7d48ecf179a6c303ab

**Comment by phit** [comment]
`Exception attempting to capture or spawn an Entity! ` https://gist.github.com/phit/b4abac66a766fea82a58c6a04d199c27

**Comment by tetsune** [comment]
I did notice that was spamming. Is there anything I can do to fix it?

**Comment by tetsune** [comment]
https://github.com/Verclene/LittleMaidReengaged/issues/125#issuecomment-346723026

**Comment by Faithcaio** [comment]
`sendContainerToPlayer` is called in `MixinEntityPlayerMP#stopActiveHand`
maybe checking for FakePlayer there?

**Comment by Deamon5550** [comment]
It looks like this was fixed by the mod developer (see the linked issue)

**Comment by ryantheleach** [comment]
It was, but this could still be a potential (I believe forge) issue for other mods.
