### ISSUE TITLE
Server Lag - tileEntityPending

### ISSUE THREAD

**Issue by Keaton1188** [SpongePowered/SpongeForge#1875]
Hi all, just quick.. we're having some lag issues.. the sponge timings report is showing "tileEntityPending" is causing some lag issues. Not actually sure what this is.. anyone know? :)
(102% TPS Loss)

Sponge Report - https://timings.aikar.co/?id=1cec25020d404732abe5aa1e43af0950

SpongeForge:
Minecraft: 1.12.2
SpongeAPI: 7.0.0-SNAPSHOT-e66ed25
SpongeForge: 1.12.2-2529-7.0.0-BETA-2744
Minecraft Forge: 14.23.0.2531

**Comment by phit** [comment]
Closed, please use the [forums](https://forums.spongepowered.org/), or [Discord](https://discord.gg/PtaGRAs) for support like this.
