### ISSUE TITLE
Expedition Mod no drops until final breaking

### ISSUE THREAD

**Issue by StoneLegion** [SpongePowered/SpongeForge#1876]
**Summery**
Expedition Mod allows you to Mine a ore say 3 times and you get a bit of material each time you mine it. But rather Sponge does not give you any materials till the very last time you mine it when the block breaks.

**I am currently running**
- SpongeForge version: 1.10.2-2477-5.2.0-BETA-2731
- Forge version: 1.10.2-12.18.3.2477
- Java version: 1.8.0_151-b12
- Operating System: Ubuntu

- Plugins/Mods:
`Plugins (145): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, Aroma1997Core, Hard Mode Tweaks Core, IvToolkit, SpongeAPI, SpongeForge, FoamFixCore, Nucleus Mixins, HardLib, Expanded Industry, Forge Endertech, Advanced Chimneys, CraftStudio API, Animania, Antique Atlas, Just Enough Items, AppleCore, AppleSkin, ArchitectureCraft, Aroma1997Core|Helper, AromaBackup, AromaBackup Recovery, Astral Sorcery, Bagginses, Bed Bugs, Mantle, Tinkers' Construct, The One Probe, Immersive Engineering, ShetiPhian-Core, Terraqueous, Better With Mods, Better Achievements, Better Questing, Better Questing Triggerer, BiblioCraft, MalisisCore, MalisisDoors, Big Doors, Bird's Nests, Bloodmoon, InfinityLib, Boatifull, Ceramics, Charcoal Pit, MCMultiPart, Chisels & Bits, Cooking for Blockheads, Coral Reef, Crafting Tweaks, CraftTweaker JEI Support, MineTweaker 3, Default World Generator, DoubleJump, Dynamic Surroundings, Edible Bugs Mod, Janus Compatibility Library, Extra Alchemy, Fairy Lights, Farming for Blockheads, Flint Instead of Wood, FoamFix, Grappling hook mod, Hardcore Darkness, Hard Mode Tweaks, Homestead Companion, How 'Bout That Furniture, Immersive Craft, Immersive Petroleum, Simple Inventory sorting, Iron Chest, Just a Few Fish, KleeSlabs, Shadowfacts' Forgelin, LLibrary, Literal Ascension, Login Shield, LootTweaker, Mod Control, MTLib, Mod Tweaker, MoreDefaultOptions, Morpheus, Mowzie's Mobs, mxTune, Nature's Compass, NetherPortalFix, Nomadic Tents, Nutrition, Open Glider, Pam's HarvestCraft, Pumpkin Carving, Quark, Railcraft, Realistic Torches, Recurrent Complex, Redstone Paste, Rockhounding Mod: Core, Rockhounding: Surface, Rope Bridge, Rough Mobs, Realistic Terrain Generation, Rustic, Signals, Tough As Nails, Slurp, SophisticatedWolves, LunatriusCore, Stackie, stacksonstacks, Standard Expansion, Steve's Carts 2, Farseek, Streams, Timberjack, Totemic, Tumbleweed, Underground Biomes, Underground Ocean, Vanilla Automation, Village Box, V-Tweaks, Waddles, WallpaperCraft, Watering Cans, Water Strainer, Wearable Backpacks, The Weirding Gadget, winterwonderland, Wolf Armor and Storage, WTFs Expedition-Homestead Edition, Yoyos, CmdControl, GriefPrevention, LuckPerms, MinecraftMarket, Nucleus, ServerListPlus, WorldEdit, AutoRegLib, Harvest Tweaks, Hunger Overhaul`

**Issue Description**
So the idea the mod is you can Mine Ores created by the mod. It allows you to Mine say Iron ore 3 times. When you mine it each time the texture changes and you get a bit of say ore dust, etc. The last time when there is almost nothing left you would get the cobblestone and a bit of the materials left. That part works for the last part when the block breaks but not for the first 2 times it gives no material at all but the blocks texture does switch and it goes down to the next level.

The Dev has stated it's a Sponge issue hes not doing any hacks only forge Hooks:
https://github.com/WhiskyTangoFawks/Expedition/issues/15

No Crash Issues nor log errors.

**Comment by StoneLegion** [comment]
More Information I stripped down everything and tested it and still broken. The mod I'm using in the list is forked so will post the details here:

1.10.2 (I think only the first one is required but I got all 3):
https://minecraft.curseforge.com/projects/wtfs-expedition-gameplay
https://minecraft.curseforge.com/projects/wtfs-tools
https://minecraft.curseforge.com/projects/wtfs-expedition-cavebiomes-ores-trees-and-tweaks

![stlr4g2](https://user-images.githubusercontent.com/425853/33226532-2374ea14-d15e-11e7-8ab0-a6517939c7a6.png)

Without Sponge it of course works just fine. Hope this helps. 

[21:27:44] [Client thread/INFO]: [CHAT] Plugins (9): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, WTFs Expedition, WTFs Gameplay Tweaks, WTFs Tools

**Comment by phit** [comment]
Closing this issue, as of today 1.10.2 and 1.11.2 are not longer supported. If a sufficiently, decent, and tested Pull Request is made to fix this bug/issue, it will still be considered, however, it is NOT to be expected that any bug fixes made for 1.12.2 will be back ported to 1.11.2 or 1.10.2.

If you can reproduce this issue with SpongeForge on Minecraft 1.12.2 and this issue was wrongly closed, please [open a new issue](https://github.com/SpongePowered/SpongeForge/issues/new) with updated information.
