### ISSUE TITLE
Couldn't use Geomastery and Spongeforge at the same time

### ISSUE THREAD

**Issue by TRLWeiss** [SpongePowered/SpongeForge#1877]
**I am currently running**

- SpongeForge version: 1.11.2-2393-6.1.0-BETA-2715
- Forge version: 13.20.1.2476
- Java version: 1.8
- Operating System: CentOS 7.1

- Plugins/Mods: Geomastery,Spongeforge

**Issue Description**
[23:12:31] [Server thread/ERROR] [Sponge]: /************************************

*******************/

/*****************************************************************************
/
/ Exception during phase body /
/****************************************************************************/
/ Something happened trying to run the main body of a phase PlayerTickPhase
/
/ PhaseContext :
/
/ - Name: Source
/
/ Object: EntityPlayerMP['test1'/256, l='world', x=133.30, y=67.68, z=9.47] /
/ - Name: CapturedBlocks
/
/ Object: CapturedBlocksSupplier{Captured=0}
/
/ - Name: CapturedEntities
/
/ Object: CapturedEntitiesSupplier{Captured=0}
/
/ Phases remaining :
/
/ - Phase: PlayerTickPhase
/
/ Context:
/
/ - Name: Source
/
/ Object: EntityPlayerMP['test1'/256, l='world', x=133.30, y=67.68, z=9.47] /
/ - Name: CapturedBlocks
/
/ Object: CapturedBlocksSupplier{Captured=0}
/
/ - Name: CapturedEntities
/
/ Object: CapturedEntitiesSupplier{Captured=0}
/
/ Stacktrace:
/
/ net.minecraft.util.ReportedException: Ticking player
/
/ net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.ja
va:406) /
/ net.minecraft.network.NetHandlerPlayServer.lambda$onPlayerTick$0(NetHandl
erPlayServer.java:1950) /
/ org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseT
racker.java:162) /
/ net.minecraft.network.NetHandlerPlayServer.redirect$onPlayerTick$zha000(N
etHandlerPlayServer.java:1949) /
/ net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlaySer
ver.java:164) /
/ net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_
73660_a(NetworkDispatcher.java:215) /
/ net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287
) /
/ net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
/
/ net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:74
                                                */
/* net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServ
er.java:384) /
/ net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:62
4) /
/ net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
/
/ java.lang.Thread.run(Unknown Source)
/
/ java.lang.IndexOutOfBoundsException: Index: 36, Size: 23
/
/ java.util.ArrayList.rangeCheck(Unknown Source)
/
/ java.util.ArrayList.get(Unknown Source)
/
/ net.minecraft.inventory.Container.func_75139_a(Container.java:114)
/
/ org.spongepowered.common.event.SpongeCommonEventFactory.callPlayerChangeI
nventoryPickupEvent(SpongeCommonEventFactory.java:161) /
/ net.minecraft.entity.item.EntityItem.handler$onPlayerItemPickup$zej000(En
tityItem.java:808) /
/ net.minecraft.entity.item.EntityItem.func_70100_b_(EntityItem.java:392)
/
/ net.minecraft.entity.player.EntityPlayer.redirect$onPlayerCollideEntity$z
ff000(EntityPlayer.java:3609) /
/ net.minecraft.entity.player.EntityPlayer.func_71044_o(EntityPlayer.java:5
82) /
/ net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:5
74) /
/ net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java
:2088) /
/ net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:
232) /
/ net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.ja
va:329) /
/ net.minecraft.network.NetHandlerPlayServer.lambda$onPlayerTick$0(NetHandl
erPlayServer.java:1950) /
/ org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseT
racker.java:162) /
/ net.minecraft.network.NetHandlerPlayServer.redirect$onPlayerTick$zha000(N
etHandlerPlayServer.java:1949) /
/ net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlaySer
ver.java:164) /
/ net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_
73660_a(NetworkDispatcher.java:215) /
/ net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287
) /
/ net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
/
/ net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:74
3) /
/ net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServ
er.java:384) /
/ net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:62
4) /
/ net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
/
/ java.lang.Thread.run(Unknown Source)
/
/
/
/ Minecraft : 1.11.2
/
/ SpongeAPI : 6.1.0-SNAPSHOT-c4a7afd
/
/ SpongeForge : spongeforge-1.11.2-2476-6.1.0-BETA-2715
/
/ Minecraft Forge : 13.20.1.2476
*/
When I was running spongeforge with gaining any drop item it will appear until i leave the item.
If I just use Original Forge, the problem would go away.
How can I run this mod by using sponge without this problem?
[2017-11-25-3.log.gz](https://github.com/SpongePowered/SpongeForge/files/1503084/2017-11-25-3.log.gz)

Chinese Goverment has blocked the gist.github.com,so i can't upload any file on it.However, i can use a upload server to make you download.Download Link: http://7xsbml.com1.z0.glb.clouddn.com/2017-11-25-3.log.gz

**Comment by ryantheleach** [comment]
Could you explain a little more on what "When I was running spongeforge with gaining any drop item it will appear until i leave the item." means? particularly, does it have to be a specific item, does it have to be an item from this mod?

Also, your log doesn't appear to have enough information to debug this issue: (for others) https://gist.github.com/ryantheleach/6400aaa6e4f5e0a34025564bf75f9505

We need the full log to debug this.

If this issue gets closed, instead of reopening a new issue, feel free to respond to this one with the addition information / editing your post so that you don't need to keep repeating the first step, and we will reopen.

Previous Ticket: https://github.com/SpongePowered/SpongeForge/issues/1873
Mod Ticket: https://github.com/JayAvery/geomastery/issues/56

**Comment by TRLWeiss** [comment]
Question 1:Could you explain a little more on what "When I was running spongeforge with gaining any drop item it will appear until i leave the item." means? 
Answer:That means when i try to pick up any item, the item will be unable to picked up.And the console will show the same information circularly.Sorry because i am not a native speaker of English so my grammer is very strange.

Quesion 2:does it have to be a specific item, does it have to be an item from this mod?
Answer:No specific item,any item will cause the bug.
This mod has a specific Inventory,may be it will cause the problem.

Question 3:Also, your log doesn't appear to have enough information to debug this issue
Answer: In fact,the problem can't be written into the log document.I can see on the console,but I can't see the same information in log document.You can just have a try. Put Spongeforge Mod and Geomastery Mod at the same time,and start the Server.When you want to pick up something,some bug information will appear.



the information are as follow:
/************************************

*******************/

/*****************************************************************************
/
/ Exception during phase body /
/****************************************************************************/
/ Something happened trying to run the main body of a phase PlayerTickPhase
/
/ PhaseContext :
/
/ - Name: Source
/
/ Object: EntityPlayerMP['test1'/256, l='world', x=133.30, y=67.68, z=9.47] /
/ - Name: CapturedBlocks
/
/ Object: CapturedBlocksSupplier{Captured=0}
/
/ - Name: CapturedEntities
/
/ Object: CapturedEntitiesSupplier{Captured=0}
/
/ Phases remaining :
/
/ - Phase: PlayerTickPhase
/
/ Context:
/
/ - Name: Source
/
/ Object: EntityPlayerMP['test1'/256, l='world', x=133.30, y=67.68, z=9.47] /
/ - Name: CapturedBlocks
/
/ Object: CapturedBlocksSupplier{Captured=0}
/
/ - Name: CapturedEntities
/
/ Object: CapturedEntitiesSupplier{Captured=0}
/
/ Stacktrace:
/
/ net.minecraft.util.ReportedException: Ticking player
/
/ net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.ja
va:406) /
/ net.minecraft.network.NetHandlerPlayServer.lambda$onPlayerTick$0(NetHandl
erPlayServer.java:1950) /
/ org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseT
racker.java:162) /
/ net.minecraft.network.NetHandlerPlayServer.redirect$onPlayerTick$zha000(N
etHandlerPlayServer.java:1949) /
/ net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlaySer
ver.java:164) /
/ net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_
73660_a(NetworkDispatcher.java:215) /
/ net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287
) /
/ net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
/
/ net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:74
/
/ net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServ
er.java:384) /
/ net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:62
4) /
/ net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
/
/ java.lang.Thread.run(Unknown Source)
/
/ java.lang.IndexOutOfBoundsException: Index: 36, Size: 23
/
/ java.util.ArrayList.rangeCheck(Unknown Source)
/
/ java.util.ArrayList.get(Unknown Source)
/
/ net.minecraft.inventory.Container.func_75139_a(Container.java:114)
/
/ org.spongepowered.common.event.SpongeCommonEventFactory.callPlayerChangeI
nventoryPickupEvent(SpongeCommonEventFactory.java:161) /
/ net.minecraft.entity.item.EntityItem.handler$onPlayerItemPickup$zej000(En
tityItem.java:808) /
/ net.minecraft.entity.item.EntityItem.func_70100_b_(EntityItem.java:392)
/
/ net.minecraft.entity.player.EntityPlayer.redirect$onPlayerCollideEntity$z
ff000(EntityPlayer.java:3609) /
/ net.minecraft.entity.player.EntityPlayer.func_71044_o(EntityPlayer.java:5
82) /
/ net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:5
74) /
/ net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java
:2088) /
/ net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:
232) /
/ net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.ja
va:329) /
/ net.minecraft.network.NetHandlerPlayServer.lambda$onPlayerTick$0(NetHandl
erPlayServer.java:1950) /
/ org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseT
racker.java:162) /
/ net.minecraft.network.NetHandlerPlayServer.redirect$onPlayerTick$zha000(N
etHandlerPlayServer.java:1949) /
/ net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlaySer
ver.java:164) /
/ net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_
73660_a(NetworkDispatcher.java:215) /
/ net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287
) /
/ net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
/
/ net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:74
3) /
/ net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServ
er.java:384) /
/ net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:62
4) /
/ net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
/
/ java.lang.Thread.run(Unknown Source)
/
/
/
/ Minecraft : 1.11.2
/
/ SpongeAPI : 6.1.0-SNAPSHOT-c4a7afd
/
/ SpongeForge : spongeforge-1.11.2-2476-6.1.0-BETA-2715
/
/ Minecraft Forge : 13.20.1.2476
*/

**Comment by phit** [comment]
Closing this issue, as of today 1.10.2 and 1.11.2 are not longer supported. If a sufficiently, decent, and tested Pull Request is made to fix this bug/issue, it will still be considered, however, it is NOT to be expected that any bug fixes made for 1.12.2 will be back ported to 1.11.2 or 1.10.2.

If you can reproduce this issue with SpongeForge on Minecraft 1.12.2 and this issue was wrongly closed, please [open a new issue](https://github.com/SpongePowered/SpongeForge/issues/new) with updated information.
