### ISSUE TITLE
Problem with sponge switching dimension

### ISSUE THREAD

**Issue by Raycoms** [SpongePowered/SpongeForge#1878]
SpongeForge version: spongeforge-1.12.2-2529-7.0.0-BETA-2741.jar
Forge version: forge-1.12.2-14.23.0.2550-universal.jar (Also happening with 2529)
Java version: OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)
Operating System: Linux (Redhat)

Our teleportation code does that:

playerToTeleport.changeDimension(colonyDimension);
playerToTeleport.setPositionAndUpdate(position.getX(), position.getY() + 2.0, position.getZ());

Which works perfectly without sponge.
As soon as we install sponge the player gets teleported to the correct position in the old dimension.

**Comment by baegmon** [comment]
Same issue confirmed on both Forge 1.12.2 and 1.12.1 with latest version of SpongeForge installed.
Pastebin: https://pastebin.com/Gagn7cyb

Code works fine with just Forge.

**Comment by Zidane** [comment]
@Raycoms 

Can you retest against our latest SpongeForge builds?

**Comment by Raycoms** [comment]
Can do =)

2018-04-19 18:22 GMT+01:00 Chris Sanders <notifications@github.com>:

**Comment by phit** [comment]
@Raycoms status?

**Comment by Raycoms** [comment]
Sorry, I wasn't able to play minecraft in the last 3 months due to
university work. I'll ask one of my players as soon as I get to it.

2018-05-21 22:47 GMT+01:00 phit <notifications@github.com>:

**Comment by phit** [comment]
gonna close this for now, if it still doesnt work reply and it will be reopened
