### ISSUE TITLE
Issue With Sponge If a Lot of Dimensions Are Being Loaded

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1879]
Using:
forge-1.12.2-14.23.1.2554-universal.jar
spongeforge-1.12.2-2529-7.0.0-BETA-2746.jar

This also happens in 1.10.2 with the latest version of forge and sponge.

Can you please give us an option to disable generate-spawn-on-load=true it off by default? This may also be a bug as the default global.conf file has this set to false, the config-enabled setting in the world.confs is set to false when it generates but it seems to be ignoring global.conf and generating it anyway.

This setting causes a very big issue if you have a mod that adds a lot of dimensions such as Advanced Rocketry or Galacticraft as it will try to load them all and will make your server freeze when it gens the world initially.

I am fully aware you can turn this off, but it must be loaded at least one time before the world.conf will be generated to do this. 

I currently have just Advanced Rocketry and a few other mods that add a handful of dims and it is still causing freezes with 20 Gigabytes of RAM dedicated because it's trying to load all these dims. The only way I can even get all these files to generate is by restarting the server multiple times.

**Comment by phit** [comment]
intentional behavior, stuff like this will always fall back to the dimension or world config

to fix your issue, go to `/config/sponge/worlds/advancedrocketry/planet/dimension.conf` set `config-enabled=true`, `load-on-startup=false` and `generate-spawn-on-load=false`

**Comment by ghost** [comment]
Hello, I just dug more into this it seems to be a conflict with Astral Sorcery.

If I use only Spongeforge and adv rocketry it doesn't try to load all the dims on a new world, as soon as you add astral sorcery sponge will load all dims at launch and it ignores the world.conf.
