### ISSUE TITLE
Conflict Between Astral Sorcery, Advanced Rocketry and SpongeForge

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1880]
This seems to be effecting at least all recent versions of SpongeForge 1.10.2 and up.

If you use Astral Sorcery and sponge it will cause all dimensions from Advanced Rocketry to load and it will ignore any related settings made to global.conf, dimension.cong and world.conf. This does not happen if Sponge is not installed or if you have Sponge and Advanced Rocketry but no Astral Sorcery.

How to reproduce:

Forge:
forge-1.12.2-14.23.1.2554-universal

I am using these mods:
AdvancedRocketry-1.12.2-1.2.6-1
astralsorcery-1.12.2-1.8.2
LibVulpes-1.12.2-0.2.6-16-universal
spongeforge-1.12.2-2529-7.0.0-BETA-2746

**## Each of these was done with brand new sponge config files and a brand new world**

Example of what is happening:

Mods: Astral Sorcery, Advanced Rocketry, Spongeforge
https://i.imgur.com/roHNt7J.png

It starts loading every single planet, it doesn't unload them and then it eventually freezes or crashes. This ignores the changes to the world.conf files for the planets to disable the gen with the config being enabled.

Mods: Advanced Rocketry, Spongeforge
https://i.imgur.com/Mo1SQGb.png

No planets loading, any changes to world.conf appears to be working.

**Comment by ghost** [comment]
Forgot to put this in the original post, it does seem to crash with this config and here is the crash log. If you use more mods it eventually just freezes instead of crashing.

https://pastebin.com/Gx1qkAry

I will test in 1.10.2 and see if it also crashes or just freezes.

Edit: Same crash in 1.10.2

https://pastebin.com/PKmBUf3s

**Comment by phit** [comment]
zip up all your sponge configs please

**Comment by ghost** [comment]
Hello, I was using the sponge files it generates from nothing so giving you them isn't going to help. I am also going to supply you the server files I am using so you can see this for yourself as it is a real problem not just me being an idiot. Seems like other people who reported it just got ignored.

Server Files:
http://www.mediafire.com/file/f9651llv6eq471f/Sponge_Server.zip

Config files it generates:
http://www.mediafire.com/file/szcohnnamv24678/sponge.zip


It crashes before it finishes, I loaded it 3 times to get these and it's still not even close to done. Not going to load the server like 20 times just to get full configs of the same world.conf.

If I edit it I do a bulk edit and change:
generate-spawn-on-load=true to generate-spawn-on-load=false
and
config-enabled=false to config-enabled=true

But like I said above changing generate-spawn-on-load=true to false does not work. It leaves config-enabled=true there but it resets it to generate-spawn-on-load=true

For now the only solution I can find is removing Astral Sorcery.

**Comment by phit** [comment]
READ what i wrote in the last issue, you don't need the world.conf's and the global.conf will do nothing.. that fully intentional.
Edit the single DIMENSION.CONF in the `/config/sponge/worlds/advancedrocketry/planet` folder and set the values there..

to quote myself
>to fix your issue, go to `/config/sponge/worlds/advancedrocketry/planet/dimension.conf` set `config-enabled=true`, `load-on-startup=false` and `generate-spawn-on-load=false`

I'm running a server with Astral Sorcery and Adv Rocketry myself using these settings and nothing loads on startup.

**Comment by ghost** [comment]
When I change the settings to that it reverts them on the next reload, this also only effects NEW servers. Go download the server files and try it yourself, it will ignore what you keep telling people to do that does not work. Setting it to read only way work though, but that is a bandaid not a fix if it did.

Once it loads once it's not a problem it seems.

**Comment by phit** [comment]
then you didn't set `config-enabled=true`

**Comment by ghost** [comment]
Do you want me to record my screen and send it to you? What you are saying doesn't work because when you load the server it keeps setting the setting back to true.

It also just outright crashes for some reason when you use only Astral Sorcery and ADV rocketry but in a modpack this doesn't happen.

**Comment by phit** [comment]
So I downloaded your server zip and still had 0 issues when setting what I asked you to set.

* start server once until overworld starts loading
* kill server
* edit `/config/sponge/worlds/advancedrocketry/planet/dimension.conf`
  set `config-enabled=true`, `load-on-startup=false` and `generate-spawn-on-load=false`
* load server again
* no new worlds generate, just some astral sorcery spam checking all dimensions, but no region files are being created

here have the configs, logs and world from this test if you don't believe me https://phit.link/s/Sponge%20Server.zip
