### ISSUE TITLE
Just Enough Dimensions Crash

### ISSUE THREAD

**Issue by HorizonsMC** [SpongePowered/SpongeForge#1881]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2529-7.0.0-BETA-2747
- Forge version: forge-1.12.2-14.23.1.2556-universal
- Java version:  Java 8 u152
- Operating System: Windows 10

- Plugins/Mods:
justenoughdimensions-1.12.1-1.5.5

When entering a dimension that was created with Just Enough Dimensions it causes an error with the world if you use the world info setting.

Example Dim that breaks it:
`{
    "dimensions": [
        {
            "dim": 100,
            "dimensiontype":
            {
                "id": 100,
                "name": "100",
                "suffix": "_dim100",
                "keeploaded": true,
                "worldprovider": "WorldProviderSurfaceJED"
            },
			"worldinfo_onetime": {
        "generatorName": "default"
      }
	}
   ]`

Removing the world info setting will then cause it to load with no errors:
`{
    "dimensions": [
        {
            "dim": 100,
            "dimensiontype":
            {
                "id": 100,
                "name": "100",
                "suffix": "_dim100",
                "keeploaded": true,
                "worldprovider": "WorldProviderSurfaceJED"
            }
	}
   ]
}`

Error:
https://gist.github.com/HorizonsMC/f7d8b45f7a38f3d6c29c1e1ecd2da458

It would not give me a crash report if I was just running the mod and sponge, but with more mods it did crash and here is that log:
https://gist.github.com/HorizonsMC/f8554676e4f1a57c958a82029ffb7300

Edit:
Got it to crash by overriding the overworld then using the world info setting. So here is a crash report with only SpongeForge and Just Enough Dims.

https://gist.github.com/HorizonsMC/9863ba38aced041edf47329c0281f19c

**Comment by phit** [comment]
https://github.com/maruohon/justenoughdimensions/issues/9

dev of the mod supposedly fixed this in their dev version, you can find more info on that issue tracker

**Comment by HorizonsMC** [comment]
Got the dev version and it appears to be working, thank you.
