### ISSUE TITLE
World Import Fail

### ISSUE THREAD

**Issue by Rasgnarok** [SpongePowered/SpongeForge#1882]
**I am currently running**
- SpongeForge version: `spongeforge-1.12.2-2529-7.0.0-BETA-2748.jar`
- Forge version: `forge-1.12.2-14.23.0.2529-universal.jar`
- Java version: `1.8.0_151`
- Operating System: `CentOS Linux 7`

Plugins/Mods:
- `Nucleus-1.2.0-PR4-S7.0-MC1.12.2-plugin.jar`

**Issue Description**
Importing a world with a level name that contains special characters (spaces, brackets) causes a mess within the main level folder. 
1. Copied a world folder into the root server folder, called `Kingdom of Thariel` (level name inside the NBT is `Kingdom of Thariel [1.7/1.8]`.
2. Started the server, imported using Nucleus' `/world create -i "Kingdom of Thariel"`
3. Though it imports and loads fine, `/worlds` output shows `Kingdom of Thariel [1.7`
4. Inside the folder of the main level, two world folders (highlighted) appeared:
![image](https://user-images.githubusercontent.com/18584380/33513170-489c53c4-d70b-11e7-9c48-59a9c92917c2.png)
Inside the second highlighted folder, a copy of the imported world:
![image](https://user-images.githubusercontent.com/18584380/33513186-8c483e58-d70b-11e7-914b-b1d60641ef1d.png)
5. A restart changes the output of `/worlds` to `Kingdom of Thariel [1.7/1.8]`
6. Couple restarts later said output shows `Kingdom of Thariel`

I can provide the server folder completely, or a copy of the world to reproduce the issue.

**Comment by Zidane** [comment]
Honestly nothing in the WorldManager does anything special here. I pass off whatever folder name that Nucleus gives me to Mojang's ``SaveHandler`` which just does ``this.worldDirectory = new File(p_i46648_1_, saveDirectoryNameIn);``

What happens if you run a Vanilla server with that name as your level-name?

**Comment by ryantheleach** [comment]
level-name=wor/ld inside "D:\s\testvanilla\server.properties"

results in D:\s\testvanilla\wor\ld

![image](https://user-images.githubusercontent.com/141554/38975015-58a243a8-43eb-11e8-8514-7274500733e8.png)

**Comment by Zidane** [comment]
@Rasgnarok 

Thinking more on this, I think Nucleus is at fault here. I use the foldername and synchronize it back to the NBT name when loading a World and migrating one via the built in WorldMigrator (that moves worlds on the root inside your world folder).

**Comment by Rasgnarok** [comment]
Alright, I'll foward this to dual, thanks!
