### ISSUE TITLE
Sponge breaking ae2stuff machines + console spam because of it.

### ISSUE THREAD

**Issue by Whazaaaaa** [SpongePowered/SpongeForge#1883]
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2529-7.0.0-BETA-2747
- Forge version: forge-1.12.2-14.23.1.2556-universal
- Java version: 8
- Operating System: Ubuntu

- Plugins/Mods: Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, BetterChunkLoader, ClearMob, Discord Bridge, Enjin Minecraft Plugin, GoonUtils, GriefPrevention, HuskyCrates, HuskyUI, LuckPerms, NuVotifier, Nucleus, PlayerShopsRPG, ProjectCore for SpongeAPI 7.x, SeriousVote, StackBan for SpongeAPI 7.x, Total Economy, WorldEdit, f48d75cd4c5771bd

**Issue Description**
Just some spam in the console about ae2stuff's inscriber I think? Perhaps something to look at? I also got a report that the ae2stuff machines were broken and that the items inside dissapear. So that basically breaks the useage of the mod :/

Here is the spam I get from it in the console
https://gist.github.com/anonymous/f0fcfa455abff7c49b7de28162af0b5c

**Comment by phit** [comment]
probably the same as https://github.com/SpongePowered/SpongeForge/issues/1807
