### ISSUE TITLE
Internal server error when picking up item's

### ISSUE THREAD

**Issue by JoeSGT** [SpongePowered/SpongeForge#1884]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2555-7.0.0-BETA-2757
- Forge version: 1.12.2-14.23.1.2559
- Java version:  8
- Operating System: Windows 10

- Plugins/Mods: 
applied-llamagistics-1.12.1-rv5-beta-10
just that mod no sponge plugins a clean test server

**Issue Description**
Okay on my clean test server i got internal server error when i pickup an item 
this only happen when i have applied-llamagistics installed on to the server
i had test this with the mod alone with no sponge plugins or other mods
here what i have done

1) get a chest and a stack of block (any blocks)
2) put the stack of block into the chest and break it
in survival and boom as you pickin up the item's you will get `internal server error`
here are the logs i can provide when this happen's

Latest.log: https://pastebin.com/6iWzkmEC
Fml-server-latest.log: https://pastebin.com/RVWR6WT9
Fml-junk-earlystartup.log: https://pastebin.com/ivtrLRXr

**Comment by thiakil** [comment]
Probably related to this: https://github.com/thiakil/Applied-Energistics-2/blob/rv5-1.12/src/main/java/appeng/items/tools/powered/ToolPortableCell.java#L277

OP has said they did not have a Portable Cell on them, so all that the handler should be doing is simulating what won't fit into the player's inv.

**Comment by Faithcaio** [comment]
should be fixed in latest
