### ISSUE TITLE
[1.12.2] Exception attempting to capture block change

### ISSUE THREAD

**Issue by Tencao** [SpongePowered/SpongeForge#1885]
**I am currently running**
- SpongeForge version: 1.12.2-2555-7.0.0-BETA-2757
- Forge version: 14.23.1.2555
- Java version: 8
- Operating System: Windows 10

- Plugins/Mods:
Plugins (15): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, BungeeTabListPlus-SpongeBridge, LuckPerms, Nations, Nucleus, Prism, ProjectCore for SpongeAPI 7.x, ProjectPortals for SpongeAPI 7.x, ProjectWorlds for SpongeAPI 7.x, RankUpper, SpongyCord, Total Economy

Mods (155): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AE2 Stuff, AngelRing 2 Bauble, Animania, Applied Fluidics, Applied Llamagistics, Applied Llamagistics Core, AutoPackager, AutoRegLib, B.A.S.E, BC Builders, BC Energy, BC Factory, BC Robotics, BC Silicon, BC Transport, BD Lib, Baubles, Better Advancements, BiblioCraft, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Biomes O' Plenty, Bloodmoon, BuildCraft, BuildCraft Lib, Can I Join Now?, Chameleon, ChickenChunks, Chisel, Chisels & Bits, Chunk Pregenerator, Clumps, CoFH Core, CoFH World, CodeChicken Lib, Compact Solar Arrays, Compacter, ComputerCraft, Corail Pillar, Corail Pillar - Quark Extension, Coralreef, CoroUtil Library, CosmeticArmorReworked, CraftStudio API, CraftTweaker JEI Support, CraftTweaker2, Crafting Tweaks, DeathCounter, DeepResonance, DiscordIntegration, Dynamic Surroundings, ElecCore, Elevator Mod, Ender Zoo, EnderStorage, Energy Converters, Environmental Tech, Ex Compressum, Ex Nihilo Creatio, Extended Mod Config, Extended Renderer, Extra Utilities 2, Extreme Reactors, FTBLib, Fairy Lights, FoamFix, Forestry, Funky Locomotion, GenDustry, Grue, Hardcore Darkness, HelpFixer, Immersive Engineering, Immersive Petroleum, Industrial Wires, IndustrialCraft 2, Inventory Tweaks, Iron Chest, IvToolkit, JEI Bees, Just Enough Items, KleeSlabs, Localized Weather & Storms, Login Shield, MPUtils, MTLib, Malisis Blocks, MalisisCore, MalisisDoors, Mantle, MineTweakerRecipeMaker, Missing Pieces, Mod Tweaker, ModPack Basic Tools, More Bees, MrCrayfish's Furniture Mod, Natura, NetherPortalFix, New Age Bee Breeding, No More Drops, NoMoreRecipeConflict, Not Enough Wands, OreExcavation, Plethora, Plethora Core, PlusTiC, ProjectE, Quark, Reborn Core, Recurrent Complex, Redstone Flux, Redstone Paste, Reforged, Roguelike Dungeons, SAOMC Library, Shadowfacts' Forgelin, Simply Conveyors & More, Spartan Shields, Spectrite, Steve's Carts 2, Storage Drawers, Storage Drawers Extras, SwingThroughGrass, TESLA, TOP Addons, Teslafied, The Beneath, The One Probe, Thermal Dynamics, Thermal Expansion, Thermal Foundation, TickProfiler, Tinkers Tool Leveling, Tinkers' Construct, UBC Ore Registrar, Underground Biomes, UniDict, Valkyrie Lib, WTFs Expedition, WanionLib, Wither Skeleton Tweaks, WorldEdit, XNet, Zero CORE, denseores

**Issue Description**
When teleporting away from a chunk with AE2 Stuff tile entities, the log begins to output said error when the chunk unloads:
https://paste.ee/r/rbdPp

Full Log: https://gist.github.com/Tencao/58d0b180ac558ca533b08e327c69e646

**Comment by Keaton1188** [comment]
Also getting massive spam for Exception attempting to capture a block change! 

Log - https://hastebin.com/catequkoqa.css

**Comment by PurpleIsEverything** [comment]
Getting this too, really annoying when you have a several gig log file with no way to even temporarily mute these errors.

**Comment by Tencao** [comment]
There is a way to mute most errors, if you go to sponge and disable verbose in the config. Note this will only silence most errors, not fix them.

**Comment by PurpleIsEverything** [comment]
Disabling verbose does not silence these errors even a little bit.

**Comment by Tencao** [comment]
Strange, it managed to silence a majority of mine, then again it depends how many AE2 tiles you have.

**Comment by PurpleIsEverything** [comment]
Forge version: 1.12.2-14.23.1.2561
Sponge Version: 1.12.2-2555-7.0.0-BETA-2763

More AE unload type cause-tracker sponge https://hastebin.com/izamowacib.md so unfortunately this is not fixed.

**Comment by gabizou** [comment]
2764 should have the bug fixes. re-test?

**Comment by PurpleIsEverything** [comment]
They were actually in 2763 according to the commits, though later in the day we bumped our build and it continued.
