### ISSUE TITLE
[1.12.2] Kick when picking up items

### ISSUE THREAD

**Issue by Tencao** [SpongePowered/SpongeForge#1889]
**I am currently running**
- SpongeForge version: 1.12.2-2555-7.0.0-BETA-2757
- Forge version: 14.23.1.2559
- Java version: 8
- Operating System: Windows 10

- Plugins/Mods:
Plugins (15): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, BungeeTabListPlus-SpongeBridge, LuckPerms, Nations, Nucleus, Prism, ProjectCore for SpongeAPI 7.x, ProjectPortals for SpongeAPI 7.x, ProjectWorlds for SpongeAPI 7.x, RankUpper, SpongyCord, Total Economy

Mods (156): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AE2 Stuff, AngelRing 2 Bauble, Animania, Applied Fluidics, Applied Llamagistics, Applied Llamagistics Core, AutoPackager, AutoRegLib, B.A.S.E, BC Builders, BC Energy, BC Factory, BC Robotics, BC Silicon, BC Transport, BD Lib, Baubles, Better Advancements, BiblioCraft, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Biomes O' Plenty, Bloodmoon, BuildCraft, BuildCraft Lib, Can I Join Now?, Chameleon, ChickenChunks, Chisel, Chisels & Bits, Chunk Pregenerator, Clumps, CoFH Core, CoFH World, CodeChicken Lib, Compact Solar Arrays, Compacter, ComputerCraft, Corail Pillar, Corail Pillar - Quark Extension, Coralreef, CoroUtil Library, CosmeticArmorReworked, CraftStudio API, CraftTweaker JEI Support, CraftTweaker2, Crafting Tweaks, DeathCounter, DeepResonance, DiscordIntegration, Dynamic Surroundings, ElecCore, Elevator Mod, Ender Zoo, EnderStorage, Energy Converters, Environmental Tech, Ex Compressum, Ex Nihilo Creatio, Extended Mod Config, Extended Renderer, Extra Utilities 2, Extreme Reactors, FTBLib, Fairy Lights, FoamFix, FoamFixCore, Forestry, Funky Locomotion, GenDustry, Grue, Hardcore Darkness, HelpFixer, Immersive Engineering, Immersive Petroleum, Industrial Wires, IndustrialCraft 2, Inventory Tweaks, Iron Chest, IvToolkit, JEI Bees, Just Enough Items, KleeSlabs, Localized Weather & Storms, Login Shield, MPUtils, MTLib, Malisis Blocks, MalisisCore, MalisisDoors, Mantle, MineTweakerRecipeMaker, Missing Pieces, Mod Tweaker, ModPack Basic Tools, More Bees, MrCrayfish's Furniture Mod, Natura, NetherPortalFix, New Age Bee Breeding, No More Drops, NoMoreRecipeConflict, Not Enough Wands, OreExcavation, Plethora, Plethora Core, PlusTiC, ProjectE, Quark, Reborn Core, Recurrent Complex, Redstone Flux, Redstone Paste, Reforged, Roguelike Dungeons, SAOMC Library, Shadowfacts' Forgelin, Simply Conveyors & More, Spartan Shields, Spectrite, Steve's Carts 2, Storage Drawers, Storage Drawers Extras, SwingThroughGrass, TESLA, TOP Addons, Teslafied, The Beneath, The One Probe, Thermal Dynamics, Thermal Expansion, Thermal Foundation, TickProfiler, Tinkers Tool Leveling, Tinkers' Construct, UBC Ore Registrar, Underground Biomes, UniDict, Valkyrie Lib, WTFs Expedition, WanionLib, Wither Skeleton Tweaks, WorldEdit, XNet, Zero CORE, denseores

**Issue Description**
When a player dies and attempts to pick up their stuff, they get disconnected with the error below

https://paste.ee/r/Cx4rd

**Comment by phit** [comment]
update to latest
