### ISSUE TITLE
Exception to Capture a Block Change - spongeforge-1.12.2-2555-7.0.0-BETA-2763 - DW20 1.12

### ISSUE THREAD

**Issue by alicheek** [SpongePowered/SpongeForge#1892]
**I am currently running**

- SpongeForge version:  spongeforge-1.12.2-2555-7.0.0-BETA-2763.jar
- Forge version: 14.23.1.2555
- Java version: OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
- Operating System: CentOS 6.8 (Final)

- Plugins/Mods:
DW20 1.12 Modpack

**Issue Description**

Still seem to be getting some spam regarding capturing block change for AE2 on chunk unload it seems.

https://gist.github.com/alicheek/23321d0d5f833f2947018824d070a818

**Comment by alicheek** [comment]
Also got this as well not sure if this one is related:

https://gist.github.com/alicheek/0efc1a90bb08768fb0c19b8d89cc17f0

**Comment by JoeSGT** [comment]
Having the same issue
here are my version..
- applied-llamagistics-1.12.1-rv5-beta-10
- forge-1.12.2-14.23.1.2562
- spongeforge-1.12.2-2555-7.0.0-BETA-2764

https://pastebin.com/M8d2Gjdr

**Comment by gabizou** [comment]
Re-test with 2764.

**Comment by JoeSGT** [comment]
@gabizou  what do you mean by re-test i have that version and it still spam with those error's
