### ISSUE TITLE
Incompatibility with GottaGoFast, plus another minor issue I'd like to report, regarding bans

### ISSUE THREAD

**Issue by Sunconure11** [SpongePowered/SpongeForge#1893]
**I am currently running**

- SpongeForge version: 1.12.2-2555-7.0.0-BETA-2764
- Forge version: 14.23.1.2560
- Java version: Java 8
- Operating System: Windows 10

- Plugins/Mods: Since I cannot get a list with this mod installed, as it prevents proper startup, I will dump a list without it: https://pastebin.com/a89Cp8Wj Yeaaah, I have a pretty beefy pack.

**Issue Description**

The mod [GottaGoFast](https://minecraft.curseforge.com/projects/gotta-go-fast), which fixes some minor issues with things like mod-provided flight, causes sponge to auto-crash on startup.

https://github.com/thiakil/GottaGoFast/issues/1

In addition to this issue, I will also provide my own log.

https://pastebin.com/tBqWNaX9

Also, another minor issue I'd like to mention is that I receive a crash if I have an old ban list from before I installed Sponge. Deleting the old player bans files solves it, but it's an annoyance, nonetheless.

https://pastebin.com/4uy2JYn7

**Comment by phit** [comment]
Sponge adds the ability to disable these checks itself, you don't need a mod for that. Which you can enable in the Sponge `global.conf`

```
    modules {
        # Allows configuring Vanilla movement and speed checks
        movement-checks=false
    }
    movement-checks {
        # Controls whether the 'player/entity moved wrongly!' check will be enforced
        moved-wrongly=false
        # Controls whether the 'player moved too quickly!' check will be enforced
        player-moved-too-quickly=false
        # Controls whether the 'vehicle of player moved too quickly!' check will be enforced
        player-vehicle-moved-too-quickly=false
    }
```

For the second issue please open a separate issue for that, otherwise it will probably get lost.

**Comment by Zidane** [comment]
Not fixing this incompatibility. The mod is causing Minecraft classes to be classloaded in the incorrect classloader.
