### ISSUE TITLE
CapturedEntity Error causing Client Crash, Login Issues, and World Loading Issues

### ISSUE THREAD

**Issue by AeoniaMC** [SpongePowered/SpongeForge#1894]
I am currently running:
- SpongeForge version: spongeforge-1.11.2-2476-6.1.0-BETA-2715
- Forge version: 1.11.2-forge1.11.2-13.20.1.2429
- Java version: Java 8
- Operating System: Not sure (hosted server)

- Plugins/Mods: Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, FoamFixCore, Better Command Signs, Buycraft, CatClearLag, MrCrayfish's Furniture Mod, CommandSigns, Discord Chat, FoamFix, LangSwitch, LuckPerms, NPCs, Nucleus, Thut Core, In-game NBTEdit - Pokecube Edition, Pokecube Core, Pokecube Model Loader, Thut's Wearables, Thut's Bling, Pokecube Revival, Pokecube Mobs, Pokecube Movess, Pokecube Origin, Pokecube Compat, Pokecube Server Utils, Pokecube Mystery Dungeon, WorldEdit, RedProtect, NuVotifier, SeriousVote, Thut's Tech, Total Economy, VillagerShops

**Issue Description**
A player reported that a Pokecube NPC sent out a particular Pokemob, causing them to crash and become unable relog onto server (see logs below). It is unknown whether this was really the cause, but the issue came out to be a huge piece of land (~1000x1000 blocks) is damaged in some way relating to CapturedEntities. I talked to the Pokecube dev, who told me this issue was a Sponge issue. Players approaching the area causes console to spam error messages (also in logs below), and the chunks fail to load properly when players approach the affected area. Entering the affected area causes world to disappear until player exits. Logging off in close enough proximity to where the console errors are being made or within the affected area will cause the LangSwitch mod to fail when the player logs back in (also in logs below). This is fixable if the player's location is edited to be far enough away from the affected area, at which point they can login again.

I would have uploaded the logs to GitHub, but they were already uploaded to pastebin and I've set them to never expire so there shouldn't be an issue there.
First server error that caused player to crash (found in server logs): https://pastebin.com/TgaCMPp1
When player tried to log back in (also found in server logs): https://pastebin.com/K5j7W74V
Error spam in console when a player approaches affected area: https://pastebin.com/031b4qHC
When I tried to log back on again after logging off in affected area (also from console): https://pastebin.com/zrzwCXPv

**Comment by phit** [comment]
Closing this issue, as of today 1.10.2 and 1.11.2 are not longer supported. If a sufficiently, decent, and tested Pull Request is made to fix this bug/issue, it will still be considered, however, it is NOT to be expected that any bug fixes made for 1.12.2 will be back ported to 1.11.2 or 1.10.2.

If you can reproduce this issue with SpongeForge on Minecraft 1.12.2 and this issue was wrongly closed, please [open a new issue](https://github.com/SpongePowered/SpongeForge/issues/new) with updated information.
