### ISSUE TITLE
PrettyPrinter limit backport breaks TileEntity CauseTracker

### ISSUE THREAD

**Issue by alicheek** [SpongePowered/SpongeForge#1898]
**I am currently running**

- SpongeForge version: spongeforge-1.10.2-2477-5.2.0-BETA-2776
- Forge version: forge-12.18.3.2511
- Java version: build 1.8.0_151-b12
- Operating System: CentOS 7

- Plugins/Mods:
The Simple Life 2 Modpack

**Issue Description**

Lots of spam since I updated from spongeforge-1.10.2-2477-5.2.0-BETA-2731.jar to spongeforge-1.10.2-2477-5.2.0-BETA-2776.jar server crashed before with the second paste link submitted below. Used removeErroringEntities=true and removeErroringTileEntities=true to stop the crash at boot up.

Spam: https://gist.github.com/alicheek/a1fad394a43cb985e779185cff3be208

Crash Report: https://gist.github.com/alicheek/90c3d9bd39d7f27fe429f2530b7b7fe1

**Comment by ryantheleach** [comment]
@Faithcaio The spam is related to hoppers.

@alicheek Do you know if any of the mods in the modpack modify the vanilla hoppers to be more efficient? Or are they just normal Minecraft hoppers?

The crash seems to be a different issue entirely.

**Comment by alicheek** [comment]
Not sure tried this now on Skyfactoy 3 and got pretty much the same results:

https://gist.github.com/alicheek/b51496045f4cba60c8f301ca001d9e67

**Comment by alicheek** [comment]
@ryantheleach  also notice at the bottom we are also getting phase spam also not guessing some changes were ported from 1.12?

**Comment by alicheek** [comment]
@ryantheleach been advised by one of my players and admin that logged in when i had this up on the skyfactory 3 server that everything from their storage was wiped even including signs. Luckily he was the only player to log on at the time.

**Comment by StoneLegion** [comment]
Thankfully you made backup 👍

**Comment by Keaton1188** [comment]
We don't keep backups.

**Comment by StoneLegion** [comment]
I assumed that!

**Comment by Keaton1188** [comment]
:)

**Comment by phit** [comment]
this has been reverted for now so the latest build i safe to download https://github.com/SpongePowered/SpongeCommon/commit/94063c5e1241b7cd8f4ca1d32dd158a94c3f9f2c

**Comment by JBYoshi** [comment]
Not quite latest yet. Once it builds, you should be good to go.

**Comment by JBYoshi** [comment]
2777 has the fix.
