### ISSUE TITLE
[1.12.2] Destroying beds, doors broken with SF 2764 and newer

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#1900]
Steps to reproduce:

goto survival mode
place bed/doors
destroy it (destroying with creative works fine)

Issue not present with builds < 2764

**Comment by vectrixdevelops** [comment]
Is this by chance related to this? https://github.com/SpongePowered/SpongeCommon/issues/1653

**Comment by ghost** [comment]
yes exactly
