### ISSUE TITLE
No WitherSkeleton Spawn in Nether

### ISSUE THREAD

**Issue by Mallalei** [SpongePowered/SpongeForge#1904]
I have install on a FTB-SkyFactory3 Server spongeforge-1.10.2-2477-5.2.0-BETA-2777 and try it with 1.10.2-2477-5.2.0-BETA-2782 and now do not spawn witherSkeletons and blazes, blazes spawn arround his spawner but thats all… Skeletons and WitherSkeletons dont spawn!

SpongeForge is the only one Plugin that i have installed after the ModPack by FTB.

If i delete sponge it works with the spawn of this Mobs.
sorry for my bad english! I hope any can understand and help me fast.

**Comment by phit** [comment]
gotta see if backporting https://github.com/SpongePowered/SpongeCommon/pull/1604 is needed

**Comment by JBYoshi** [comment]
I can't reproduce this without mods. I went to some newly generated nether fortresses (SpongeForge 1.10.2-2477-5.2.0-BETA-2782) and found multiple skeletons and wither skeletons around them, in addition to several blazes that were not near spawners.

**Comment by phit** [comment]
yeah skyfactory uses custom worldgen (all void) provided by a mod, hence the PR linked above probably needs to be backported

**Comment by JBYoshi** [comment]
Never mind then. Can reproduce with just [YUNoMakeGoodMap](https://minecraft.curseforge.com/projects/yunomakegoodmap) ([source](https://github.com/LexManos/YUNoMakeGoodMap))- make sure to flip on nether fortress generation in the configuration file.

**Comment by JBYoshi** [comment]
That fixes it.

**Comment by JBYoshi** [comment]
Fixed in SpongePowered/SpongeCommon@dfc7cb62c2d9633d25640610241cfa44e9d58024.

**Comment by JBYoshi** [comment]
Also backported to 1.11. https://github.com/SpongePowered/SpongeCommon/commit/ac6fab7818388e749221a38be6063d17846c8d67
