### ISSUE TITLE
"Shadow field _combatTracker was not located in the target class net.minecraft.entity.EntityLivingBase"

### ISSUE THREAD

**Issue by Runemoro** [SpongePowered/SpongeForge#1907]
#**I am currently running**

- SpongeForge version: 2786 dev
- Forge version: 2555
- Java version: JDK 1.8.0_144 64-bit
- Operating System: Windows 8.1

- Plugins/Mods: Sponge only

**Issue Description**

Running the dev version in IntelliJ Idea fails with the following error: https://gist.githubusercontent.com/Runemoro/93f75adf4dddc434e92d913c64824c86/raw/44bad568ed37d829c5a37183c226c8e770e351eb/gistfile1.txt (`Shadow field _combatTracker was not located in the target class net.minecraft.entity.EntityLivingBase`). I looked at the `EntityLivingBase` class, and it contains a `combatTracker` field (without the underscore).

**Comment by gabizou** [comment]
Mapping difference? What snapshot of mappings are you attempting to run based on? There's a lot more than just matching the forge version in this case.

**Comment by gabizou** [comment]
Also, why are you trying to run the dev jar of SpongeForge?

**Comment by gabizou** [comment]
For reference, Sponge is using an MCP snapshot version that is old enough where the name of the field is appropriately `_combatTracker`. The history available for the field is as follows:
```
=== Field History: field_94063_bt ===
[1.12, Staged 2017-10-08 12:31:42.889510-04:00] kashike: _combatTracker => combatTracker
[1.5.1, Committed 2013-06-21 21:12:19-04:00] Krenair: field_94063_bt => _combatTracker
[1.5.1, Committed 2013-05-24 00:38:33-04:00] skyboy: field_94063_bt => _combatTracker
```

**Comment by Runemoro** [comment]
I'm running the dev jar to debug a problem with my mod that happens only with SpongeForge enabled. I'm using the latest mappings, which mappings should I be using instead?

**Comment by phit** [comment]
https://github.com/SpongePowered/SpongeCommon/blob/bleeding/gradle.properties#L8

`snapshot_20171003` that's also the version currently shipped with the Forge MDK

**Comment by Runemoro** [comment]
Ok, thanks. That works.
