### ISSUE TITLE
Incorrect interaction of lava with water in automatic stone generator

### ISSUE THREAD

**Issue by Lantcoder** [SpongePowered/SpongeForge#1908]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2555-7.0.0-BETA-2786
- Forge version: forge-1.12.2-14.23.1.2555-universal
- Java version: Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
- Operating System: Linux Main 4.13.0-21-generic #24-Ubuntu SMP Mon Dec 18 17:29:16 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- Plugins/Mods:
flexiblelogin-0.16.5.jar
worldedit-forge-mc1.12-6.1.8-dist.jar 

**Issue Description**
Not long ago times I migrate my server from 1.11.2 version (forge-1.11.2-13.20.1.2414-universal.jar, spongeforge-1.11.2-2315-6.1.0-BETA-2377.jar ) to 1.12.2 version (forge-1.12.2-14.23.1.2555-universal.jar, spongeforge-1.12.2-2555-7.0.0-BETA-2786.jar ), and noticed, that stone generators no more work anymore.

Stone Generator (not cobblestone!) arranged so. Lava flow from up to target cell, water flow from lateral side. Automatic piston from other side - shifts block of stone (on-off) and clean cell to next filling with lava and water. With SpongeForge running this behavior is change. Stone appears not only in target cell, also stone appears on the upper adjacent cell.

But this is incorrect! On upper adjacent cell water does not flow!

I remove sponge.jar file and run server without sponge. All work fine, upper-adjacent cell does not affected with water. Therefore problem is in the SpongeForge file! I delete Sponge from my server, temporarily, run server without Sponge, this is insecure, flexiblelogin mod does not work.

Please, find this error and correct it! Stone generators does not work!

log is normal

**Comment by JBYoshi** [comment]
Fixed in https://github.com/SpongePowered/SpongeCommon/commit/a7738effbce1bceabaae964cdceb80e1db640967.
