### ISSUE TITLE
SpongeForge block place behavior not the same as Forge

### ISSUE THREAD

**Issue by Runemoro** [SpongePowered/SpongeForge#1909]
**I am currently running**

- SpongeForge version: 2791
- Forge version: 2555
- Java version: JDK 1.8.0_144 64-bit
- Operating System: Windows 8.1

- Plugins/Mods: Sponge, DimDoors

**Issue Description**
The SpongeForge block place behavior is different from Forge:
 1. Sponge calls the `onBlockAdded` method later (not sure when) than from within the `setBlockState` like Forge does. This prevents me from setting a flag that affects the `onBlockAdded` method's behavior and breaks my mod: https://github.com/DimensionalDevelopment/DimDoors/blob/02c7c61c73640318f06a366e4276b21e169c7145/src/main/java/com/zixiken/dimdoors/shared/blocks/IRiftProvider.java#L24
 2. The tile entity at the block's position is already created rather than null, like with Forge. Forge/Vanilla calls the createTileEntity method only if the `onBlockAdded` doesn't set one up.

**Comment by gabizou** [comment]
Pretty sure this is no longer an issue with the enhanced tracker on placing blocks and on various ticking phases.

If you want an explanation about where and why the `onBlockAdded` is called, I can, but not going to waste the time at this moment if it's not necessary (I'm pretty sure I've explained it somewhere somehow to someone, but I'm perfectly fine doing a full writeup of the system as it is today).
