### ISSUE TITLE
Nether chunk generation Server-Crash 

### ISSUE THREAD

**Issue by rediomand** [SpongePowered/SpongeForge#1910]
I am currently running

SpongeForge version: spongeforge-1.10.2-2477-5.2.0-BETA-2793
Forge version: 2477
Java version: 1.8
Operating System: debian

skyfactory3 Modpack
- Plugins/Mods :Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Not Enough Items, OpenComputers (Core), FoamFixCore, ccl-entityhook, Fence Overhaul, Actually Additions, CodeChicken Lib, CodeChicken Core, EnderStorage, Just Enough Items, OpenComputers, ActuallyComputers, Baubles, Extra Utilities 2, AngelRing 2 Bauble, AppleCore, apple_shields, AppleSkin, AutoPackager, Psi, AutoRegLib, Baconators, CraftTweaker JEI Support, MineTweaker 3, B.A.S.E, BD Lib, Bed Bugs, Better Builder's Wands, BiomeTweaker, BlockDispenser, Guide-API, Blood Magic: Alchemical Wizardry, Bookshelf, Botania, Brandon's Core, Mantle, Tinkers' Construct, Ceramics, Chameleon, Chance Cubes, MCMultiPart, ‽, |, /, Chest Transporter, Chickens, Chisel, Chisels & Bits, ShadowMC, Clipboard, Clumps, Cyclops Core, Colossal Chests, CommonCapabilities, Cooking for Blockheads, Waila, Dark Utilities, PTRModelLib, Decocraft, Dimensional Cake, Draconic Evolution, Dragon Mounts, Storage Drawers, Drawers & Bits, Elevator Mod, EnderCore, Ender IO, Energy Converters, Engineer's Workshop, Valkyrie Lib, Environmental Tech, ET Lunar, Ex Nihilo Adscensio, Ex Compressum, Extra Bit Manipulation, Zero CORE, Extreme Reactors, Fairy Lights, Farming for Blockheads, FastAsyncWorldEdit, Flat Colored Blocks, SonarCore, FluxNetworks, FoamFix, Shadowfacts' Forgelin, FTBLib, FTBUtilities, Funnels, Garden of Glass, Advanced Generators, Grue, Get Ya' Tanks Here, Hammer Core, Hatchery, Headcrumbs, Hopper Ducts, HydroGel, Immersive Engineering, LunatriusCore, InGame Info XML, MTLib, InitialInventory, Integrated Dynamics, Integrated Tunnels, Simple Inventory sorting, Iron Backpacks, Iron Chest, YUNoMakeGoodMap, ItsBecauseUHasNoGoodSpawn, It's Raining Food, KleeSlabs, LagMeter, LLibrary, Literal Ascension, Long Fall Boots, Loot Bags, Mercurius, MineMenu, MiniCoal, Natura, Missing Pieces, Random Things, Roots, MoarSigns, mob_grinding_utils, Mod Tweaker, More Chickens, More Shearables, More Shears, ModPack Utilities, ModPack Basic Tools, Mystical Agriculture, Nice, Not Enough Wands, OreExcavation, Packing Tape, Pam's HarvestCraft, ShetiPhian-Core, Platforms, RebornCore, QuantumStorage, Ranged Pumps, reborncore-MCMultiPart, Refined Storage, RebornStorage, Redstone Paste, Reliquia, RFTools, RFTools Control, RFTools Dimensions, Wooden Shears, Scanner, Shear Madness, Simple Achievements, Simple Barrels, Simple Corn, Simple Generators, SimpleLabels, Simply Jetpacks 2, Snad, Solar Flux Reborn, Steve's Carts 2, Super Circuit Maker, The Beneath, Tinkers Tool Leveling, Tiny Progressions, TorchMaster, Translocator, Twerk-Sim 2K16, Twitchcrumbs, voidcup, Waddles, WanionLib, I Can See Everything, What Are We Looking At, Wither Crumbs, WorldEdit, Experience Rings, Adventskalender, BackupLoader, MyFTB Core, GlobalServices, Caligula, KeepInv, MineChat, Ontime, Prism, RestartOnCrash, RestrictedServer, SimpleGamemode, SpongyKits, Storinator, TeamspeakBridge, Treepers, UrlClickFixer, WorldManagement, UniDict

**Issue Description**
I enter the nether and the server crashes after I sponge update the previous sponge version was spongeforge-1.10.2-2477-5.2.0-BETA-2698

crash-report
https://pastebin.com/z6em91dM

**Comment by phit** [comment]
Closing this issue, as of today 1.10.2 and 1.11.2 are not longer supported. If a sufficiently, decent, and tested Pull Request is made to fix this bug/issue, it will still be considered, however, it is NOT to be expected that any bug fixes made for 1.12.2 will be back ported to 1.11.2 or 1.10.2.

If you can reproduce this issue with SpongeForge on Minecraft 1.12.2 and this issue was wrongly closed, please [open a new issue](https://github.com/SpongePowered/SpongeForge/issues/new) with updated information.

**Comment by TheFlash787** [comment]
https://github.com/SpongePowered/SpongeForge/issues/2044
(For those who find this needing a fix, basically just downgrade to `1.10.2-2477-5.2.0-BETA-2788`)
