### ISSUE TITLE
Incorrect mapping of MainPlayerInventory rows

### ISSUE THREAD

**Issue by ShortCircuit908** [SpongePowered/SpongeForge#1915]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2555-7.0.0-BETA-2797
- Forge version: 14.23.1.2555
- Java version: 1.8
- Operating System: Windows 10

- Plugins/Mods: tieredkits (not released, in development)

**Issue Description**
The player's GridInventory is mapped to the top two rows of the main inventory, and the hotbar
The player's Hotbar is mapped to the bottom row of the main inventory
(as if all rows of the inventory have been shifted up by 1 position)

**Comment by phit** [comment]
@Faithcaio

**Comment by Faithcaio** [comment]
Maybe just need to swap around the lens consctruction order in MainPlayerInventoryLensImpl.
But this might then in turn break Container order.
I'll look into it this evening.
