### ISSUE TITLE
Redstone Clock (Extra Utilities) bad performance 

### ISSUE THREAD

**Issue by JoeSGT** [SpongePowered/SpongeForge#1917]
**I am currently running**

- SpongeForge version: 1.12.2-2555-7.0.0-BETA-2799
- Forge version: 1.12.2-14.23.1.2581
- Java version:  8
- Operating System: linux

- Plugins/Mods:
https://gyazo.com/4acc15bd3f2a7ce79ac1fe2ce8dba0d2

**Issue Description**
When i place down redstone clock  from Extra Utilities and put a redstone dust on top the TPS start to goes down
i saw that there a config selection in global.conf but i left it default
i will provide the what i saw and i left it default
cause i dont know it so i didn't mess with it
here how to reproduce  it 
https://gyazo.com/83be6e5e8884e9a401e5e6774dbd557f
just have those 1 or 2 and you will lag the server
just have redstone clock *(Extra Utilities)*  and redstone dust *(vanilla)* on top
i provided an gyzo GIF on how i did it
https://timings.aikar.co/?id=309ed0b7f6db440f9bba3f587e186952
https://pastebin.com/MPWuvppT

once you reproduce this the console spam this
https://pastebin.com/d1MQWp1A

**Comment by phit** [comment]
noticed this too, looks like the block-capturing ignore list no longer works as before

**Comment by CyberSpongie** [comment]
Omg this is why my server was lagging bad, thanks for reporting it, having the same issue, disabled redstone clocks and lag stop

**Comment by fhntv24** [comment]
Still an issue in latest sponge versions ( 1.12.2-2611-7.1.0-BETA-2990 , 8.0.0 snapshot ). Default config ( so block capturing is enabled for clock ). Could someone look at this issue ?

**Comment by JoeSGT** [comment]
I just remove redstone clocks from the config @fhntv24

**Comment by phit** [comment]
https://gist.github.com/phit/48f45448540c04d4cc0632f1ac24fcf3

from my rough understanding, before it hits `org.spongepowered.common.event.tracking.TrackingUtil.updateTickBlock(TrackingUtil.java:287)` (in updateTickBlock) it is supposed to hit `checkAndAssignBlockTickConfig` whatever that was supposed to do no longer does what  it used to

my best guess this broke during this https://github.com/SpongePowered/SpongeCommon/commit/b5fb6baf8a895efc5e6fa4650648373eb419f76f#diff-1f5cd6d76f93fc0d889c37748c34e56dL313

**Comment by bloodmc** [comment]
@Aaron1011 please take a look at this.

**Comment by phit** [comment]
https://github.com/SpongePowered/SpongeCommon/commit/d7275cc4d6a952177e36f90cca2364973283eb6e
