### ISSUE TITLE
multiple server crashes following crash report by sponge

### ISSUE THREAD

**Issue by cdog580** [SpongePowered/SpongeForge#1918]
**I am currently running**
- SpongeForge version: 1.12.2-2555-7.0.0-BETA-2799
- Forge version: forge-1.12.2-14.23.1.2555
- Java version: java 8 update 151
- Operating System: windows 10 home 64 bit

- Plugins/Mods:
Mods (25): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, BC Builders, BC Energy, BC Factory, BC Robotics, BC Silicon, BC Transport, BuildCraft, BuildCraft Lib, CodeChicken Lib, EnderStorage, Forestry, IndustrialCraft 2, Inventory Tweaks, Iron Chest, Just Enough Items, Mantle, Not Enough Items, Tinkers' Construct, mercurius_updater

 Plugins (8): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, Eagle Factions, Lockette, LuckPerms, Nucleus

**Issue Description**
server prints large error that eventually leads to server crash

https://gist.github.com/cdog580/2df694287cedb54cb8b9dcab4c40603a

**Comment by Faithcaio** [comment]
`io.github.aquerr.eaglefactions.listeners.PlayerMoveListener.onPlayerMove(PlayerMoveListener.java:47)`
calls setLocation during a Move or Teleport Event instead of using the method on the event. `setToTransform`
This causes infinite recursion.

**Comment by phit** [comment]
please report this to the plugin author
