### ISSUE TITLE
Chest contents disappearing Randomly

### ISSUE THREAD

**Issue by phillipinman** [SpongePowered/SpongeForge#1919]
- SpongeForge version: spongeforge-1.12.2-2555-7.0.0-BETA-2797
- Forge version: forge-1.12.2-14.23.1.2555-universal
- Java version: 1.8.0_151
- Operating System: Ubuntu 16.04 LTS

- Plugins/Mods: spongeforge-1.12.2-2555-7.0.0-BETA-2797

**Issue Description**

Chest contents inconsistency disappear when closed. Happens on world load, server restart and just being the the loaded chunks.
Does not affect all chests at once.
No error or console output is created in relation to this event.
ALL contents of affected chests are removed, not just some.

Server logs can be uploaded for more info, but no console output appears in relation to this issue.

Steps thus far to isolate this issue to spongeforge:

* removed all forge base mods and restarted server, had 3 seperate players create 4 chests each and place various items in the chest, when issue occured items disappeared for some players but not all.
* removed all sponge forge plugins and repeated the above experiment, issue persists.
* removed spongeforge from server so it is a vanilla server with only forge installed(no mods), issue appears to have stopped.

By the steps above I have traced it back to sponge forge, but I cannot confirm it is the source of the issue itself, is there a way to acquire more in depth information?

Important note: Trapped chests/ender chests are NOT affected by this issue.

**Comment by phit** [comment]
will need logs and update to latest and retest, I haven't seen this on any of personal servers nor has anyone else reported this, as it is a quite serious issue you would think someone else would have

**Comment by phillipinman** [comment]
Indeed, I suspected at first it was weirdness with my environment.

If you haven't seen this issue with any other servers ill investigate further and report back. 

The server setup does use bungeecord with a plugin to allow forge connections through the proxy but from what testing the issue persists with a direct connection bypassing the proxy. Will update shortly with a fresh world, direct connection and the latest sponge installed (1.12.2-2555-7.0.0-BETA-2810).
Anything else that would be indicative of the issue?

Additionally thank you for the work you do :)

**Comment by LemADEC** [comment]
Please provide a list of mods too

**Comment by Willynator** [comment]
Yeah, seems I am having a very similar issue which phit referenced to
https://github.com/SpongePowered/SpongeCommon/issues/1676

**Comment by phillipinman** [comment]
Can confirm I also have the same issue as @Willynator, the primary issue was the contents disappearing but we also observed the chests would unload from the chucks.

As for mod list @LemADEC there are no mods, just spongeforge itself, the issue persists.

There are also no sponge plugins loaded ether, leading me to believe the issue may be with sponge itself. If there is some way to log chest activity I am happy to, but due to the nature i have no useful logs to attach.

**Comment by phillipinman** [comment]
Addition note: This issue affects signs as well interestingly

**Comment by phillipinman** [comment]
Updated to SpongeForge 1.12.2-2555-7.1.0-BETA-2815, issue still persists

**Comment by Benedictum** [comment]
I can chime in and say we have had this issue on multiple server environments / modpacks, we attributed it to crappy mod packs, but we have definitely seen this exact issue as well.

**Comment by Faithcaio** [comment]
Just to be sure: The actual block remains there (same with signs) just all data on it is removed?

This would happen when removing the TileEntity from a position.

**Comment by LemADEC** [comment]
When issue happens, do all the chests from the same chunk loose content? or just some chests are emptied, others are fine, in the same chunk?

**Comment by phillipinman** [comment]
As a general rule both outcomes occurred,  but we tend to see one chest at a time lose contents. 

Happens to multiple chunks as well.

8 hours ago we filled a chest with colored wool. We then filled another chest next to it with another colored wool. We then went back to chest 1 only to find the contents disappeared in less than 5 seconds.

This issue does not affect ender chests i suspect because those are stored with player data.

**Comment by LemADEC** [comment]
are you sure those 2 chests are in the same chunk?
maybe try putting 12 chests on top of each others and see if those content together or separately?

**Comment by Benedictum** [comment]
I can't speak to same chunk issues as we haven't tested as exclusively as
Phillip. However the block definitely remains and just the contents are
wiped.

On Jan 2, 2018 2:14 PM, "LemADEC" <notifications@github.com> wrote:

are you sure those 2 chests are in the same chunk?
maybe try putting 12 chests on top of each others and see if those content
together or separately?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/SpongePowered/SpongeForge/issues/1919#issuecomment-354876868>,
or mute the thread

**Comment by Willynator** [comment]
For me any chests that have been loaded, unloaded, then loaded again have the issue. When it happens not all chests in the world experience the issue, as it seems the issue only happens after loading and unloading the chunk of the chests

**Comment by phillipinman** [comment]
@Faithcaio you are correct, the blocks remain but the data is wiped.

@LemADEC tried that, same result. the chest data/contents disappears even when stacked in the same chunk.

**Comment by Faithcaio** [comment]
This is really weird.
Maybe try placing a bunch of double chests right on a chunk border. (You can show them with F3+G)
Is then the entire doublechest emptied or just half of it?

**Comment by LemADEC** [comment]
so, are they all disappearing in the same chunk at the same time, or not?

**Comment by bloodmc** [comment]
If someone could provide a test world where this can be reproduced (few mods as possible), I can take a look. Make sure to list steps on what to do to trigger the bug.

**Comment by phit** [comment]
supposedly no mods needed, just load and unload areas with chests, I still haven't been able to reproduce it

**Comment by phillipinman** [comment]
Currently busy so i've delegated testing to a trusted party and they report that even with a vanilla client connected to the spongeforge server the issue persists.

You are all welcome to test the issue live at play.binarygaming.net:25520 (bypasses bungeecord)

The standard vanilla 1.12.2 client should work

Its a testing server so do whatever you feel is necessary.
  
The issue does take some time to appear as an fyi.

**Comment by phillipinman** [comment]
@LemADEC No, it appears to be random, you can fill a chest, turn around then back and the contents will be gone. Othertimes it can take awhile to happen.

**Comment by Willynator** [comment]
I was able to isolate the issue down to the config folder, I'm trying to isolate it a bit more than that though

**Comment by Willynator** [comment]
ill pm u some world files though blood

**Comment by ryantheleach** [comment]
Unless you have already talked to blood about it, I'd recommend posting your findings here, so other developers get a chance to fix the issue.

**Comment by Willynator** [comment]
alright

**Comment by Willynator** [comment]
will be a moment to download etc

**Comment by phillipinman** [comment]
Is there any additional information i can provide regarding this issue?

**Comment by Willynator** [comment]
I wasn't able to upload a world file anywhere due to it being relatively big. But testing it, the issue is able to happen even with a brand new world file

https://www.dropbox.com/s/lrvl2erda2ei4b4/borked%20world%20stuff.zip?dl=0

that has the pixelmon server jar and spongeforge-1.12.2-2555-7.0.0-BETA-2800 jar as well with the current config file used. I was able to replicate the issue using just those. 

Either logging in and out by chests, or unloading and loading chests. It isn't always consistent and sometimes requires repeating steps.

**Comment by Willynator** [comment]
ok I think I have isolated the files causing the issue, its either the **forge.cfg** or **forgeChunkLoading.cfg**
I was manually adding and removing config files, and the forge ones seemed to be the source of the issues. I let it just generate new files after deleting them and it seemed to work well. I haven't looked too far into why but I am too tired atm to do so anyways.

**Comment by phillipinman** [comment]
On that note I too have edited the forge.cfg and forgeChunkLoading.cfg

in forge.cfg
alwaysSetupTerrainOffThread=true

and forgeChunkLoading

I:dormantChunkCacheSize=200

What @Willynator found may relate to our setup as well

**Comment by bs2609** [comment]
Please see https://github.com/MinecraftForge/MinecraftForge/pull/4528.

**Comment by phillipinman** [comment]
@bs2609 Thanks for that info, would this require a forge version bump on sponges part or is this something that can be worked around in forge 2555?
  
Edit: does this issue only occur when specifying the dormantChunkCache option manually?

**Comment by johnfriedrich** [comment]
For people watching, fixed with Forge 2587.
