### ISSUE TITLE
Sponge causes elec332 to crash on loading single player worlds

### ISSUE THREAD

**Issue by LemADEC** [SpongePowered/SpongeForge#1921]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2555-7.0.0-BETA-2799.jar
- Forge version: 14.23.1.2575
- Java version: 1.8.0_25
- Operating System: Windows 10 64bits

- Plugins/Mods:
FTB Revelation 1.0.0, single player

**Issue Description**
When adding Sponge to the modpack, game will crash when loading or creating a single player world (creative, default options).
Steps to reproduce:
1- install FTB Revelation 1.0.0 with Curse launcher
2- launch, create new single player world, creative
3- close game, add Sponge, launch, reload same world => crash
4- restart game, create new world => crash
5- remove Sponge, restart game, load previous worlds => warning about sponge:human removal, loads ok

Adding sponge seems to interfere with elec332 ability to access files in the world folder.

https://gist.github.com/LemADEC/f214473f7ef58b94d3f5a8de9c750a96

**Comment by phit** [comment]
please report this to the mod author

**Comment by Elec332** [comment]
Sponge seems to be modifying the value returned by SaveHandler.getWorldDirectory(), which causes ElecCore to crash.
https://github.com/SpongePowered/SpongeForge/blob/1.12.2/src/main/java/org/spongepowered/mod/mixin/core/world/storage/MixinSaveHandler.java#L78-L91

**Comment by Zidane** [comment]
@Elec332 

Apologies for this. I have made a branch of our codebase for SpongeCommon and SpongeForge that I'll be testing further tonight/tomorrow and if it is stable I'll merge it which will fix this issue.

**Comment by phit** [comment]
Loaded up a singleplayer world, saved and reopened it, no issues. Also checked and it made a extradata folder in the saves. Looks fixed to me!

ElecCore-1.12.2-1.8.434.jar
spongeforge-1.12.2-2555-7.1.0-BETA-2840.jar
