### ISSUE TITLE
High Core Usage with 1.12 Modpacks & Sponge - 1.12.2-2555-7.0.0-BETA-2807 - Horizons 3 Details

### ISSUE THREAD

**Issue by alicheek** [SpongePowered/SpongeForge#1923]
**I am currently running**

- SpongeForge version: 1.12.2-2555-7.0.0-BETA-2807
- Forge version:  14.23.1.2566
- Java version: build 1.8.0_151-b12
- Operating System: CentOS Linux release 7.2.1511

Server details:
CPU
Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz
Cores : 8
Cache : 10240KB
RAM
4x 16384MB DDR4 @ 2400Mhz
Disks
3 x 300 GB SSD
Motherboard
X9SRE/X9SRE-3F/X9SRi/X9SRi-3F

- Plugins/Mods:

Horizons 3 1.5.0

**Issue Description**

I have noticed from moving from 1.10 mod-packs to 1.12 there has been a big jump in core usage on our servers. You can see with the profiling below that even though no players are on, we have even  made sure that there is no forced chunks on for any of the dimensions, yet we get a very high tile entity number, all of our 1.12.2 modded servers are like this whilst the 1.10 servers are pretty efficient in their core usage, one other thing i have noticed is that it seems to be the main thread that is will get locked up to 100 percent but it seems that 1.10 servers with sponge if busy could quite happily use 200% of cores with out the tps lowering. Now i have noticed that Refined storage is high on the list on the sponge profiling but these are areas that should not be loaded, is it possible that Refined storage acts unusually and keeps their systems loaded on server boot up?

Profiling at startup : https://timings.aikar.co/?id=8961aa3c50bd4c10a5546f77de9f64bc
Profiling after 5 minutes with no players or forced chunks in any dim folders: https://timings.aikar.co/?id=404038ae4607469b982cee1b99fea3b6

Full Server Log: https://gist.github.com/alicheek/fcc0f4f3496623e062b74f50aee66be3

**Comment by phit** [comment]
set `deny-chunk-requests` to false if you don't want mods to load areas, nothing sponge can do about mods using cpu otherwise

and especially refined storage is known for its bad performance regardless of Sponge installed or not
https://github.com/raoulvdberge/refinedstorage/issues/838
https://github.com/raoulvdberge/refinedstorage/issues/1525

**Comment by alicheek** [comment]
@phit  I have tested deny-chunk-requests being set to false and this still occurs for some reason

**Comment by phit** [comment]
provide a simple test world to reproduce this with as few mods as possible and I'll look at it, but right now this looks like a mod issue

**Comment by Zidane** [comment]
Closing due to lack of response.
