### ISSUE TITLE
Advancements Crash

### ISSUE THREAD

**Issue by Keaton1188** [SpongePowered/SpongeForge#1926]
**I am currently running**

- SpongeForge version: SpongeForge: 1.12.2-2555-7.1.0-BETA-2815
- Forge version: 14.23.1.2575
- Java version: build 1.8.0_151-b12
- Operating System: CentOS Linux release 7.2.1511

- Plugins/Mods:
FTB Revelations

**Issue Description**
Server randomly crashing at times with this error:
https://gist.github.com/Keaton1188/3f3a98e079c947d3b4ebbc8c724e529a

Spoke to pie_flavor on Discord and they said it was a sponge issue.

**Comment by Inscrutable** [comment]
I can confirm this also happens on a server with only forge-1.12.2-14.23.1.2583 and spongeforge-1.12.2-2555-7.1.0-BETA-2815. I traveled to the nether, and the server fell over seconds later. Copy of latest-log file here: https://pastebin.com/jaG1Lgc7

**Comment by Yeregorix** [comment]
I have the same issue. Here is my deobf crash report: https://pastebin.com/F50UEERq

**Comment by johnfriedrich** [comment]
Just want to add that these kind of crashes can mess up existing Forge mappings in level.dat. (And did in our test enviroment).

**Comment by Faithcaio** [comment]
fixed in latest API7 stable

**Comment by Yeregorix** [comment]
I had the issue with SF 1.12.2-2555-8.0.0-BETA-2814:dev, is it fixed in API8 ?

**Comment by Faithcaio** [comment]
I fixed it in bleeding too but there are currently no builds as API doesnt compile right now

**Comment by gabizou** [comment]
Bleeding should not be used at present, stable-7 builds are recommended.
