### ISSUE TITLE
Clumps EntityXPOrbBig - Timings crash when capturing

### ISSUE THREAD

**Issue by alicheek** [SpongePowered/SpongeForge#1927]
I am currently running

SpongeForge version: SpongeForge: 1.12.2-2555-7.1.0-BETA-2806
Forge version: 14.23.1.2575
Java version: build 1.8.0_151-b12
Operating System: CentOS Linux release 7.2.1511
Plugins/Mods:
FTB Revelations
Issue Description
Crash with aikar timings for calling entity on join world event for EntityXPOrbBig

https://gist.github.com/alicheek/b30acd3680107c4b80ade32a8a4661e0

**Comment by phit** [comment]
may be related to https://github.com/jaredlll08/Clumps/issues/7

**Comment by Zidane** [comment]
Investigated this a bit and is on mod side. Not a Sponge issue.
