### ISSUE TITLE
UseItemStackEvent does not fire

### ISSUE THREAD

**Issue by Zerthick** [SpongePowered/SpongeForge#1928]
**I am currently running**
- SpongeForge version: 1.12.2-2555-7.1.0-BETA-2815

**Issue Description**
As the title states, the UseItemStackEvent no longer fires as illustrated by the following code snippet:

```
@Listener
public void onItemUse(UseItemStackEvent event) {

    logger.info("Fired!");
}
```

It does however fire in SpongeVanilla, tested eating bread, drinking a regeneration potion, and drawing a bow

**Comment by phit** [comment]
@Zidane update on that branch?

**Comment by bloodmc** [comment]
UseItemStackEvent works fine for me in latest builds.
