### ISSUE TITLE
Chemical Reactor - Crash

### ISSUE THREAD

**Issue by Keaton1188** [SpongePowered/SpongeForge#1930]
**I am currently running**
 Was having a few issues with the newest build (XP orbs, still need to report, Advancements, which I see was recently fixed)
- SpongeForge version: 1.12.2-2555-7.0.0-BETA-2800
- Forge version: 14.23.1.2575
- Java version: build 1.8.0_151-b12
- Operating System: CentOS Linux release 7.2.1511

- Plugins/Mods:
FTB Revelations

**Issue Description**
This Multi-Block structure crashes the server when you open it, this is not an issue on SP.

![untitled](https://user-images.githubusercontent.com/24898745/34506485-fe05db86-f024-11e7-8161-615279606978.png)

https://gist.github.com/Keaton1188/0e7e6f1bc628dd392cfffe6782074fc2

**Comment by phit** [comment]
update to latest advanced rocketry, was fixed in https://github.com/zmaster587/AdvancedRocketry/commit/15dec4e856e4ae5ae7c74d062ad917e063c3c527
