### ISSUE TITLE
Inventory Slot Function - Crash

### ISSUE THREAD

**Issue by Keaton1188** [SpongePowered/SpongeForge#1931]
**I am currently running**
Was having a few issues with the newest build (XP orbs, still need to report, Advancements, which I see was recently fixed)
- SpongeForge version: 1.12.2-2555-7.0.0-BETA-2800
- Forge version: 14.23.1.2575
- Java version: build 1.8.0_151-b12
- Operating System: CentOS Linux release 7.2.1511

- Plugins/Mods:
FTB  Revelations

**Issue Description**
Not sure what is actually causing this crash, maybe something to do with an Inventory Slot function. 

https://gist.github.com/Keaton1188/8e1c5e86cdd05f32ba02ed372c497226

**Comment by phit** [comment]
not a sponge bug, https://github.com/mezz/JustEnoughItems/issues/1086
