### ISSUE TITLE
XNet ArithmeticException in PhaseTracker

### ISSUE THREAD

**Issue by rob5251** [SpongePowered/SpongeForge#1934]
**I am currently running**

- SpongeForge version: 1.12.2-2555-7.1.0-BETA-2817
_Also tested on (2819)_
- Forge version: 2555
- Java version:  1.8.0_152
- Operating System: Windows10 64bit

- Plugins/Mods:
Mods (115): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AE2 Stuff, Actually Additions, Actually Baubles, AppleSkin, Applied Energistics 2, Aroma1997's Dimensional World, Aroma1997Core, AromaBackup, AromaBackuprecovery, AutoRegLib, B.A.S.E, BC Builders, BC Energy, BC Factory, BC Robotics, BC Silicon, BC Transport, BD Lib, Bad Wither No Cookie! Reloaded, Baubles, Better Builder's Wands, BiblioCraft, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Biomes O' Plenty, Blockcraftery, Botania, Brandon's Core, BuildCraft, BuildCraft Lib, Calculator, Chameleon, Chest Transporter, ChickenChunks, Chisel, Chisels & Bits, Clumps, CoFH Core, CoFH World, CodeChicken Lib, Compact Solar Arrays, Crafting Tweaks, Diet Hopper, Dirt2Path, Draconic Evolution, Elevator Mod, EluCore, EluLib, EnderStorage, Extra Cells 2, Extra Utilities 2, Extreme Reactors, FTBLib, Flux Networks, Forestry, GenDustry, Gravestone Mod, Immersive Engineering, Immersive Petroleum, Industrial Foregoing, IndustrialCraft 2, InstantUnify, Interaction Wheel, Inventory Tweaks, Iron Backpacks, Iron Chest, JEI Bees, JourneyMap, Just Enough Items, KleeSlabs, Mantle, Mekanism, MekanismGenerators, MekanismTools, MineMenu, Morpheus, Natura, NetherPortalFix, NoMoreRecipeConflict, Not Enough Wands, Quark, Quick Leaf Decay, RFTools, RFTools Control, Reborn Core, Redstone Flux, Reliquary, Roguelike Dungeons, Shadowfacts' Forgelin, SonarCore, Steve's Carts 2, Storage Drawers, TOP Addons, Tesla Core Lib, Tesla Core Lib Registries, The One Probe, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Tinker I/O, Tinkers' Construct, Waystones, XNet, YABBA, Zero CORE
Plugins (8): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, GriefPrevention, LuckPerms, MMCRestrict, Nucleus

**Issue Description**
Console spam when trying to tick xnet controller (TileEntityTickPhase)
https://pastebin.com/Zmbb5qwq

_Moved from SpongeCommon to SpongeForge issue tracker_

**Comment by phit** [comment]
can't reproduce this on my server with various people using xnet, also tried in singleplayer a bit no luck
if this happens again to you, feel free to reply and I'll reopen

tested with 
xnet-1.12-1.7.1.jar
spongeforge-1.12.2-2705-7.1.0-BETA-3253.jar
