### ISSUE TITLE
Cause Stack Frame Corruption! [Client & Server Crash] - API 7.1.0 - b2821

### ISSUE THREAD

**Issue by Dockter** [SpongePowered/SpongeForge#1936]
**I am currently running**
- SpongeForge version:  spongeforge-1.12.2-2555-7.1.0-BETA-2821
- Forge version: forge-1.12.2-14.23.1.2582-universal
- Java version: 1.8
- Operating System:  Win10
 
Client Stack Trace:  https://gist.github.com/Dockter/f679752c374ab7a99189be3876e796be
Server Stack Trace: https://gist.github.com/Dockter/7208769cac108314c9bd0ce312ce7137

Server is flooded with that stack trace until you hard-kill it.

**Comment by Deamon5550** [comment]
looks like the stack manager is being called from the client thread, which is bad, but that should result in a different exception for the thread being wrong, unless something is eating that exception and then this is thrown because the frame is never created because of said exception.

**Comment by Cybermaxke** [comment]
I think I caused this issue, so I will fix it.

**Comment by Cybermaxke** [comment]
Should be fixed in the following PR: https://github.com/SpongePowered/SpongeForge/pull/1929

**Comment by smmmadden** [comment]
I got this exception last night after upgrading my test server as well - same builds.  Startup logs looked fine, but once client tried to connect - it fails.

**Comment by smmmadden** [comment]
yes, 2583-2585 all crash the client

**Comment by gabizou** [comment]
What about build 2825?

**Comment by phit** [comment]
@gabizou https://github.com/SpongePowered/SpongeForge/issues/1947#issuecomment-355880279

**Comment by gabizou** [comment]
Someone get me a log with the latest builds, I need updated stack traces to match new line numbers.

**Comment by smmmadden** [comment]
@gabizou if you are referring to 2825 shown here, then yes that build was not working either.
![image](https://user-images.githubusercontent.com/10309346/34694739-2811f908-f496-11e7-84b7-04dc7fd77d8b.png)
That with Forge 1.12.2 - 14.23.1.2586 fails as well.  For full disclosure here, I'm assuming that clicking that the row showing the "mod" download and "forge" download go together.  That's what I've been doing right along.  So the mod download goes into the mods folder on server & client and the Windows Installer that is shown is used to install it to the client and server as well.  Unless I'm doing something wrong here?

**Comment by ryantheleach** [comment]
@smmmadden Running Sponge on the client is a supported case, but is often untested outside of a single player environment. There would be a few users running Sponge on the client as well (The Almura server being a popular one), that said, running Sponge on the client as well as the server gives you additional debug on the f3 screen, and maybe a few other features I'm currently unaware of.

So, thanks for the bug report, Just that it's extremely relevant information that you were running it on the client as well.

**Comment by smmmadden** [comment]
the other advantage to having it on the client is that the client/player can also connect to my Spigot Servers without needing to change anything.  This too may be an untested scenario, but I opted for Sponge because the client could handle both Forge mods and Spigot plugins with ease.  To me, that's huge that users don't have to shut down the minecraft client only to pick a different startup option which frankly to me is annoying. :-)

I have 8 Spigot Servers and 2 Forge/Sponge Servers and a test server I use for new mods, plugins, builds, etc.

**Comment by ryantheleach** [comment]
@smmmadden FYI, Sponge isn't required on the client, unless you have client side mods or plugins that require Sponge.

In fact, you can 
1. connect completely vanilla clients to forge (provided there are no content mods required)
2. connect completely vanilla clients to SpongeVanilla
3. connect completely vanilla clients to SpongeForge (provided they don't require mods)
2. forge clients with client mods to servers without forge. (This one can be a little dicey)

**Comment by Zidane** [comment]
No longer appears to be an issue after a fix was made on 2827+
