### ISSUE TITLE
servercrash + world corruption 1.12.2 

### ISSUE THREAD

**Issue by unstablecraft** [SpongePowered/SpongeForge#1938]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2555-7.0.0-BETA-2783.jar
- Forge version: forge-1.12.2-14.23.1.2566-universal.jar
- Java version:  1.8.0_151, Oracle Corporation
- Operating System: centOS 7

- Plugins/Mods: not visible due to this https://pastebin.com/gYPGS3wR

**Issue Description**
last night on a test pack this crash occured a few times eventually currupting the world

  
https://gist.github.com/unstablecraft/22ec8391188f596588ad33fc10da7bd5

snap of world corruption after crash https://cdn.discordapp.com/attachments/398974606305787916/399142360191205376/unknown.png

snap of world how it suposed to be 
https://cdn.discordapp.com/attachments/398974606305787916/399148257562853387/unknown.png

**Comment by ryantheleach** [comment]
I'll be honest I don't understand the circumstances that would lead to this.

Was anything happening leading up to the crash?

**Comment by unstablecraft** [comment]
sponge unloading the nether as in shown log

**Comment by unstablecraft** [comment]
and then it crashed

**Comment by dualspiral** [comment]
Can you test on the latest SF to see if this is still an issue on there?

**Comment by unstablecraft** [comment]
sure gonna try that

**Comment by unstablecraft** [comment]
@dualspiral  new stacktrace spam on 1.12.2-2555-7.1.0-BETA-2824 STABLEFORGE 2555 

added mod list here: https://gist.github.com/unstablecraft/5030214473bd5eae79c10da10a2f2c5c

https://gist.github.com/unstablecraft/d938aa780602aafb8639e54d5716bf1d error log
https://gist.github.com/unstablecraft/0852616d8f0c7236699df86c6460793f more compleet log

![image](https://user-images.githubusercontent.com/33659444/34649949-e6a1abf4-f3b8-11e7-906a-0c4abfcbc432.png)
 plugins list

**Comment by unstablecraft** [comment]
https://gist.github.com/unstablecraft/0852616d8f0c7236699df86c6460793f more compleet log

**Comment by unstablecraft** [comment]
@dualspiral  https://gist.github.com/unstablecraft/94f9cb1b4b2706e423f01eb041cda81f this crash was last night with the same sponge version this could be usefull

**Comment by unstablecraft** [comment]
@phit  what info do you need ??? since you added the tag

**Comment by phit** [comment]
any way to reproduce this, right now this basically could be any mod or plugin you have installed, forge or simply a bad harddrive sector that broke your level.dat

**Comment by unstablecraft** [comment]
not really since sponge is atm on 2840 so are my servers

**Comment by unstablecraft** [comment]
with that said you can close this one ill re open it when it happens again @phit

**Comment by phit** [comment]
will do, sorry that I don't really have a solution

**Comment by unstablecraft** [comment]
dw about it
