### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by rob5251** [SpongePowered/SpongeForge#1939]
**I am currently running**

- SpongeForge version: Issue occurring from version 1.12.2-2555-7.1.0-BETA-2823 and on.
- Forge version: 2555
- Java version: 1.8.0_152
- Operating System: Linux

- Plugins/Mods:
Mods (115): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AE2 Stuff, Actually Additions, Actually Baubles, AppleSkin, Applied Energistics 2, Aroma1997's Dimensional World, Aroma1997Core, AromaBackup, AromaBackuprecovery, AutoRegLib, B.A.S.E, BC Builders, BC Energy, BC Factory, BC Robotics, BC Silicon, BC Transport, BD Lib, Bad Wither No Cookie! Reloaded, Baubles, Better Builder's Wands, BiblioCraft, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Biomes O' Plenty, Blockcraftery, Botania, Brandon's Core, BuildCraft, BuildCraft Lib, Calculator, Chameleon, Chest Transporter, ChickenChunks, Chisel, Chisels & Bits, Clumps, CoFH Core, CoFH World, CodeChicken Lib, Compact Solar Arrays, Crafting Tweaks, Diet Hopper, Dirt2Path, Draconic Evolution, Elevator Mod, EluCore, EluLib, EnderStorage, Extra Cells 2, Extra Utilities 2, Extreme Reactors, FTBLib, Flux Networks, Forestry, GenDustry, Gravestone Mod, Immersive Engineering, Immersive Petroleum, Industrial Foregoing, IndustrialCraft 2, InstantUnify, Interaction Wheel, Inventory Tweaks, Iron Backpacks, Iron Chest, JEI Bees, JourneyMap, Just Enough Items, KleeSlabs, Mantle, Mekanism, MekanismGenerators, MekanismTools, MineMenu, Morpheus, Natura, NetherPortalFix, NoMoreRecipeConflict, Not Enough Wands, Quark, Quick Leaf Decay, RFTools, RFTools Control, Reborn Core, Redstone Flux, Reliquary, Roguelike Dungeons, Shadowfacts' Forgelin, SonarCore, Steve's Carts 2, Storage Drawers, TOP Addons, Tesla Core Lib, Tesla Core Lib Registries, The One Probe, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Tinker I/O, Tinkers' Construct, Waystones, XNet, YABBA, Zero CORE

Plugins (11): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, Enjin Minecraft Plugin, GriefPrevention, LuckPerms, MMCRestrict, MagiBridge, Nucleus, Prism

**Issue Description**
Exception in server tick loop before server can fully load up, causing it to crash and generate a crash-report.

Log & Crash-report:
https://gist.github.com/rob5251/b942bc5547081b07ff7c8d83a024024d

**Comment by ryantheleach** [comment]
This was also reported in Discord with this crash log: https://gist.github.com/ryantheleach/f458297748716009887afc86404b0335

**Comment by gabizou** [comment]
This has been fixed in the latest builds.
