### ISSUE TITLE
/dank/null dupe glitch with sponge installed

### ISSUE THREAD

**Issue by tolly765** [SpongePowered/SpongeForge#1940]
**I am currently running**

- SpongeForge version: 1.12.2-2555-7.1.0-BETA-2815 (using this because the latest stable build crashes us with a nullpointer exception)
- Forge version: 
- Java version: Java 8.151.12-r0
- Operating System: Alpine

- Plugins/Mods:
Plugins: Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, @name@, BetterChunkLoader, CBG Utils, CatClearLag, EconomyLite, Enjin Minecraft Plugin, GriefPrevention, Holograms, HuskyCrates, HuskyUI, KaisCommons, LuckPerms, MMCRestrict, Nucleus, SimpleHelpTickets, SpongePrometheusExporter, Votifier, auto message

    Mods (From the Revelation pack): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, /dank/null, AE2 Stuff, Actually Additions, Actually Baubles, Akashic Tome, AppleSkin, Applied Energistics 2, ArchitectureCraft, Aroma1997's Dimensional World, Aroma1997Core, Astral Sorcery, AutoRegLib, B.A.S.E, BD Lib, Bad Wither No Cookie! Reloaded, Baubles, Bed Patch, Better Advancements, Better Builder's Wands, BetterChunkLoader Forge Lib, BiblioCraft, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Blockcraftery, Bookshelf, Botania, Brandon's Core, Chameleon, Chest Transporter, Chisel, Chisels & Bits, Clumps, CoFH Core, CoFH World, CodeChicken Lib, Comforts, Compact Machines 3, Compact Solar Arrays, Compacter, Cooking for Blockheads, CraftTweaker JEI Support, CraftTweaker2, Dark Utilities, DeepResonance, Diet Hopper, Dirt2Path, Draconic Evolution, ET Lunar, ElecCore, Elevator Mod, EluCore, EluLib, Embers, EnderStorage, Engineer's Workshop Reborn, Environmental Tech, Exchangers, Extra Cells 2, Extra Utilities 2, Extreme Reactors, FTBLib, Fence Jumper, Flat Colored Blocks, Flux Networks, FoamFix, Forestry, Gadgetry: Core, Gadgetry: Machines, GenDustry, Gravestone Mod, Guide-API, Immersive Engineering, Immersive Petroleum, Industrial Foregoing, IndustrialCraft 2, Iron Backpacks, Iron Chest, JEI Bees, JourneyMap, Just Enough HarvestCraft, Just Enough Items, KleeSlabs, Long Fall Boots, MCMultiPart, MTLib, MagicBees, MalisisCore, MalisisDoors, Mantle, MineTogether, MineTogetherServer, Mod Tweaker, Morph-o-Tool, Morpheus, Natura, Nature's Compass, NetherPortalFix, Nice, Not Enough Wands, NotEnoughIDs, NuclearCraft, OpenComputers, OpenComputers (Core), Pam's HarvestCraft, Placebo, Platforms, Quark, Quick Leaf Decay, RFTools, RFTools Control, Ranged Pumps, Reborn Core, Redstone Arsenal, Redstone Flux, Reliquary, Roots 2, Rustic, Secret Rooms 5, Shadowfacts' Forgelin, ShetiPhian-Core, Signals, SimpleVoidWorld, Snad, SonarCore, Soul Shards - The Old Ways, Steve's Carts 2, Storage Drawers, Storage Drawers Extras, TOP Addons, Tesla Core Lib, Tesla Core Lib Registries, The Lost Cities, The One Probe, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thut Core, Thut's Tech, ThutCore Compat, TickProfiler, Tinkers Tool Leveling, Tinkers' Construct, TorchMaster, Traverse, UniDict, Valkyrie Lib, Vulpes library, WanionLib, Waystones, Whoosh, Wireless Crafting Terminal 2, WorldEdit, XNet, Xtones, YABBA, Zero CORE, careerbees, mob_grinding_utils, p455w0rd's Library

**Issue Description**
As poorly mentioned in issue #1937 and mentioned in https://github.com/p455w0rd/DankNull/issues/59, there is an issue with the /dank/null that is not replicatable without SpongeForge. Basically, you can take a /dank/null from the mod that shares it's name, place a block inside it (doesn't matter what mode it is in) and then keep right clicking it on the floor, effectively duping the block infinitely. It doesn't matter how many items are placed inside, nor does it matter if you are in creative or survival. (here's a video link of it on a sponge server: https://youtu.be/6LZg7zp_6v8) This behavior isn't reproducable without sponge installed (tested in MP and SP as seen here: https://youtu.be/bWDTmQuYFwI )

**Comment by phit** [comment]
can't reproduce this with `DankNull-1.12-1.4.33` and `spongeforge-1.12.2-2611-7.1.0-BETA-2942.jar`
can you confirm this is fixed @tolly7654

**Comment by Mohron** [comment]
In my testing, this has been fixed (not the original reporter but I subscribed due to having this issue as well).

**Comment by phit** [comment]
good enough, please reply if it pops up again

**Comment by tolly765** [comment]
Can confirm, this has been fixed.
