### ISSUE TITLE
Forestry PhaseState spam

### ISSUE THREAD

**Issue by Keaton1188** [SpongePowered/SpongeForge#1941]
**I am currently running**

- SpongeForge version: 1.12.2-2555-7.1.0-BETA-2817 
- Forge version: 14.23.1.2566 
- Java version: build 1.8.0_151-b12
- Operating System: CentOS Linux release 7.2.1511

- Plugins/Mods:
Direwolf20 1.12.2

**Issue Description**
Getting this spam on our Dw20 1.12 server.
https://gist.github.com/Keaton1188/315dc7c171079b0337e7e09bdb9d35fa

**Comment by smmmadden** [comment]
https://forums.spongepowered.org/t/exception-occurred-during-a-phasestate-on-startup/21845  same issue I reported here

**Comment by phit** [comment]
Forestry bug that happens without Sponge https://github.com/ForestryMC/Binnie/issues/370
