### ISSUE TITLE
Extra Utilities 2 - BlockTeleporter Crash CME

### ISSUE THREAD

**Issue by unstablecraft** [SpongePowered/SpongeForge#1945]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2555-7.0.0-BETA-2783.jar
- Forge version: 1.12.2-14.23.1.2573.jar
- Java version: 
Java Version: 1.8.0_151, Oracle Corporation
Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
- Operating System: centos7

- Plugins/Mods: https://gist.github.com/unstablecraft/3ebf59087464ef4b61e705f4413b473e

**Issue Description**
 we had this beauty of a crash between sponge and RWThema's extra utils 2
https://gist.github.com/unstablecraft/de14ca027b7e92105d15df18ca1c2e94

 
  fixed gist link

**Comment by phit** [comment]
@unstablecraft any idea how to reproduce this? looks like a mod bug too me, but I couldn't reproduce it with any teleportation methods the mod adds

**Comment by Zidane** [comment]
Closing due to lack of response.
