### ISSUE TITLE
Sponge not persisting capabilities in onWorldTick

### ISSUE THREAD

**Issue by Raycoms** [SpongePowered/SpongeForge#1951]
**I am currently running**

- SpongeForge version: 1.12.2-2555-7.1.0-BETA-2831
- Forge version: 2555
- Java version: 1.8
- Operating System: Debian

**Issue Description**

We're using the "TickEvent.WorldTickEvent event)"
to run through some chunks we need to fill our capability with data.

This works perfectly in single player, in multiplayer (intellij) and on a dedicated server without sponge.
We ruled already all plugins out since they're not causing it.

The issue we have is that using the onWorldTick, the chunks do not persist the data we store in the capability.
It works perfectly if we do it in "onWorldLoad" and it works perfectly when we do it in "PlayerEvent.EnteringChunk event)"

It only doesn't work in "onWorldTick" using Sponge (It works perfectly without).

This is the class we do assign it in: https://github.com/Minecolonies/minecolonies/blob/feature/lagfree/src/main/java/com/minecolonies/coremod/colony/ColonyManager.java#L253

Thanks already

**Comment by gabizou** [comment]
Can it be confirmed that `TickEvent.WorldTickEvent` is actually being listened to? Not that I don't want to set up the environment, but I'm knee deep in reviewing many of the event synchronization from sponge <-> forge to resolve a few longstanding issues.

**Comment by Raycoms** [comment]
Yes it is being called accordingly, I log the event, it also reaches the
code accordingly where it should store the information, it just doesn't
persist

**Comment by Raycoms** [comment]
Did anyone start to take a look at this?

The problem is that we can't push our new feature which is important for our performance before it is fixed =/
https://github.com/Minecolonies/minecolonies/pull/1991

**Comment by gabizou** [comment]
@Raycoms I did take a glance and haven't found anything yet. As I'm working on a fix for #1259 and #1957, I'll be getting to this shortly thereafter.

**Comment by Raycoms** [comment]
Great to hear, thanks a lot.

**Comment by Raycoms** [comment]
Hey, any news yet? We're eager to move on with our changes but we rely on it working correctly on sponge servers as well =/

**Comment by marchermans** [comment]
@gabizou I am running into the same Issue, with both Minecolonies and Armory. It would be nice if we at least could get some Progress Information.

**Comment by gabizou** [comment]
I've not been able to find a solution, but I've got a hunch it may have to do with our dimension handling. Are capabilities persisting *at all* on the main overworld, but not on dimensions? Ot is it for all worlds?

**Comment by Raycoms** [comment]
@gabizou as far as I noticed it, the capability do get stored when using another even besides the "TickEvent.WorldTickEvent event" like the chunks on player enter events as it seems.
I'm not sure if they get persisted, over various sessions but it seems like they get stored at least.

**Comment by gabizou** [comment]
So further investigation:

It shows that the capabilities are definitely added,
![capabilities](https://i.imgur.com/NsmWwZh.png)

But! If I quit the world (in single player mode) and re-load said world, I see that the NBT doesn't have the owned info as shown here:
![nbt](https://i.imgur.com/B9fd8qP.png)

Which, afterwards, since the ownedChunks and closeChunks aren't being added to from NBT, the tick update doesn't actually process. Very weird. I'd imagine I'll have to investigate why saving is an issue.

**Comment by Raycoms** [comment]
Any progress on this?

**Comment by gabizou** [comment]
I believe @zidane had done some research as he ran into a similar issue on his own mod.
