### ISSUE TITLE
The PhaseState having an exception: TileEntityTickPhase 

### ISSUE THREAD

**Issue by BransonD** [SpongePowered/SpongeForge#1952]
**I am currently running**
 Was told to revert back to this SpongeForge server from the Discord as when I updated to 2824 (the latest version) my server would not start off and crash.
- SpongeForge version: spongeforge-1.12.2-2555-7.1.0-BETA-2819
- Forge version: forge-1.12.2-14.23.1.2582-universal
- Java version: Latest 1.8.0_152
- Operating System: Linux (amd64) version 4.4.0-45-generic

- Plugins/Mods:
Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, /dank/null, AE2 Stuff, Actually Additions, Actually Baubles, Advanced Rocketry, Advanced Rocketry Core, Akashic Tome, AppleSkin, Applied Energistics 2, ArchitectureCraft, Aroma1997's Dimensional World, Aroma1997Core, Astral Sorcery, AutoRegLib, B.A.S.E, BD Lib, Bad Wither No Cookie! Reloaded, Baubles, Bed Patch, Better Advancements, Better Builder's Wands, BiblioCraft, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Blockcraftery, Bookshelf, Botania, Brandon's Core, Chameleon, Chest Transporter, Chisel, Chisels & Bits, Clumps, CoFH Core, CoFH World, CodeChicken Lib, Comforts, Compact Machines 3, Compact Solar Arrays, Compacter, Cooking for Blockheads, CraftTweaker JEI Support, CraftTweaker2, Dark Utilities, DeepResonance, Diet Hopper, Dirt2Path, Draconic Evolution, ET Lunar, ElecCore, Elevator Mod, EluCore, EluLib, Embers, EnderStorage, Engineer's Workshop Reborn, Environmental Tech, Exchangers, Extra Cells 2, Extra Utilities 2, Extreme Reactors, FTBLib, FTBUtilities, Fence Jumper, Flat Colored Blocks, Flux Networks, FoamFix, Forestry, Gadgetry: Core, Gadgetry: Machines, GenDustry, Gravestone Mod, Guide-API, Immersive Engineering, Immersive Petroleum, Industrial Foregoing, IndustrialCraft 2, Inventory Tweaks, Iron Backpacks, Iron Chest, JEI Bees, JourneyMap, Just Enough HarvestCraft, Just Enough Items, KleeSlabs, Long Fall Boots, MCMultiPart, MTLib, MagicBees, MalisisCore, MalisisDoors, Mantle, MineTogether, MineTogetherServer, Mod Tweaker, Morph-o-Tool, Morpheus, Natura, Nature's Compass, NetherPortalFix, Nice, Not Enough Wands, NotEnoughIDs, NuclearCraft, OpenComputers, OpenComputers (Core), Pam's HarvestCraft, Placebo, Platforms, Quark, Quick Leaf Decay, RFTools, RFTools Control, Ranged Pumps, Reborn Core, Redstone Arsenal, Redstone Flux, Reliquary, Roots 2, Rustic, Secret Rooms 5, Shadowfacts' Forgelin, ShetiPhian-Core, Signals, SimpleVoidWorld, Snad, SonarCore, Soul Shards - The Old Ways, Steve's Carts 2, Storage Drawers, Storage Drawers Extras, TOP Addons, Tesla Core Lib, Tesla Core Lib Registries, The Lost Cities, The One Probe, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thut Core, Thut's Tech, ThutCore Compat, Tinkers Tool Leveling, Tinkers' Construct, TorchMaster, Traverse, UniDict, Valkyrie Lib, Vulpes library, WanionLib, Waystones, Whoosh, Wireless Crafting Terminal 2, XNet, Xtones, YABBA, Zero CORE, careerbees, mob_grinding_utils, p455w0rd's Library

**Issue Description**
Running FTB Revelations 1.2.0, no idea of what is happening. Had this issue with plenty of blocks and just decided to upload this one. IE Table, Industrial Foregoing Blocks.

https://gist.github.com/BransonD/7eb843845ecd3f4e87b74a72eb847c84 Error Log
https://gist.github.com/BransonD/a1f73ba07e3662a7ed844e98c639a061 Full Log

**Comment by smmmadden** [comment]
The forge-1.12.2-14.23.1.2587-universal.jar and spongeforge-1.12.2-2555-7.1.0-BETA-2831.jar should work for you.  Builds before that have game connection crashes.
