### ISSUE TITLE
[1.12.2] Random error while dropping/picking up items

### ISSUE THREAD

**Issue by polyzium** [SpongePowered/SpongeForge#1954]
**I am currently running**
*If you don't use the latest version, please tell us why.* Updates may break stuff + too lazy to update
- SpongeForge version: 1.12.2-2555-7.0.0-BETA-2758
- Forge version: 14.23.1.2560
- Java version: 1.8.0_152
- Operating System: Linux 4.14.9-1-lqx

- Plugins/Mods:
[Here](https://gist.github.com/polyzium/dd7b23e72df8abfdc5d3201e3e4fe2db) At a time writing this i had my server shut down and was too lazy to boot it up so i ran `ls` in both mods and plugins folder

**Issue Description**
Try mining, exploding a tnt or picking up a bunch of items. After that the player disconnects with "Internal server error" message.
Meanwhile [this](https://gist.github.com/polyzium/284ffde90892e1ed350da7337cdc093a) ([remapped](https://gist.github.com/ryantheleach/cdb2e07f3e1c4d61d0724b70a888dccb)) gets printed into the server's console.

**Comment by phit** [comment]
update to latest and try again, your version is quite outdated

**Comment by polyzium** [comment]
It doesn't occur on the latest spongeforge, my bad
