### ISSUE TITLE
new error stacktrace  [1.12.2]

### ISSUE THREAD

**Issue by unstablecraft** [SpongePowered/SpongeForge#1955]
**I am currently running**

- SpongeForge version: SpongeForge : 1.12.2-2555-7.1.0-BETA-2825 
- Forge version: 14.23.1.2573  
- Java version:  8
- Operating System: cenOs

- Plugins/Mods: 
![image](https://user-images.githubusercontent.com/33659444/34908864-642dfe96-f897-11e7-9175-17bb9f9110a4.png)

**Issue Description** this stack error came along filling up console 

https://gist.github.com/unstablecraft/dc013e55d49fac5de3d6fd19ecfbc81b

**Comment by phit** [comment]
mod issue https://github.com/Ordinastie/MalisisDoors/issues/210
