### ISSUE TITLE
SpongeForge Issue (Server runs fine, but the client cannot log in without timing out)

### ISSUE THREAD

**Issue by awitkowski0** [SpongePowered/SpongeForge#1956]
**I am currently running**
- SpongeForge version: 1.12.2-2555-7.1.0-BETA-2833
- Forge version: 1.12.2 - 14.23.1.2555
- Java version: 1.8.0_151
- Operating System: Ubuntu Server 16.04 “Xenial Xerus” LTS (64bits)
- Plugins/Mods:
Mods (33): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Astikoor, Backpacks!, Bad Mobs, Baubles, Baubley Heart Canisters, BiblioCraft, Chisels & Bits, CustomNPCs, Dark Roleplay Core, Dark Roleplay Medieval, Decocraft, Flat Colored Blocks, MalisisCore, MalisisDoors, Mantle, Modern Warfare, MrCrayfish's Furniture Mod, Nametags Tweaks, OMLib, Open Modular Turrets, Pam's HarvestCraft, Player Skin Mobs, Realistic Item Drops, Reforged, Tough As Nails, iChunUtil, ptrmodellib
Plugins (5): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, Nucleus

**Issue Description**
Whenever I try to join on my client I get a frozen screen that lags out. Without Spongeforge the issue isn’t existent. I’ve tried resetting the world and removing all of the mods/plugins and the problem persists.
Tried to remove gotta go fast and the issue persists.
Server: https://gist.github.com/alex5219/955a7231e8e9c3b5be4d336714b178a3

Client: https://gist.github.com/alex5219/68486ee170199c61c975341f3676bd38

The issue does not ALWAYS occur. Just most of the time.
If anyone would like to reproduce it the modpack is here: https://www.technicpack.net/modpack/walking-dead-a-new-beginning.1158629

**Comment by phit** [comment]
there is no connection in the client log, please provide your `fml-junk-earlystartup.log` for server and client

on a sidenote, as I'm not sure if you are aware, you don't need SpongeForge on your client to join a SpongeForge server

**Comment by awitkowski0** [comment]
Client: https://gist.github.com/alex5219/4850744e07d57996d73ffb508be62a74
Don't know why I had spongeforge installed on the client at that time.
Server: https://gist.github.com/alex5219/9c555ed505b59c39dc130e8e3911a992

**Comment by phit** [comment]
looks like crayfish does a lot when logging in possibly freezing your client too long so the connection times out
does your client window freeze with not responding during this?

**Comment by awitkowski0** [comment]
Yes, that's the exact thing that happens.

**Comment by phit** [comment]
I would try reporting it to the mod author and possibly giving your game more ram, there's nothing Sponge does to influence this as far as I am aware. 
See also https://github.com/MinecraftForge/MinecraftForge/issues/4671
