### ISSUE TITLE
Sponge threw an exception. 

### ISSUE THREAD

**Issue by KyleFreedomSeeds** [SpongePowered/SpongeForge#1959]
- SpongeForge version: 2800 (Latest version that is still compatible with plugins we use)
- Forge version: 2582 
- Java version: 8
- Operating System: ubuntu (Dedicated server)

- Plugins/Mods: (See gist)

- Got spammed in console. Took a SS and here i am.

https://gist.github.com/KyleCG8094/f51035fdf8a77b85e0e18629e0c7bd8e

**Comment by phit** [comment]
Reproduce it with latest and provide your `fml-junk-earlystartup.log`, then I will reopen this issue.
