### ISSUE TITLE
Sweeping Edge has no Effect.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeForge#1960]
**I am currently running**

- SpongeForge version: 1.12.2 7.1.0 2837
- Forge version: Unknown.
- Java version: Unknown.
- Operating System: Unknown

**Issue Description**
This only effects SpongeForge and not SpongeVanilla but Sweeping Edge has no effect.

It was also reported that before transferring a server from Forge to SpongeForge, that the items might have lost their enchantments? This smells like some sort of serialization issue to me.

Reported by: @Alitty in Discord.

**Comment by gabizou** [comment]
How do you mean it has no effect? It doesn't happen or it doesn't do damage?

**Comment by ryantheleach** [comment]
It fails to splash damage. I was able to reproduce it by having a group of zombies, and attacking one with a sweeping edge sword.

**Comment by Aaron1011** [comment]
I can't seem to reproduce this.
