### ISSUE TITLE
Extra Utilities Quarry error spam

### ISSUE THREAD

**Issue by unstablecraft** [SpongePowered/SpongeForge#1961]
**I am currently running**

- SpongeForge version: 1.12.2-2555-7.1.0-BETA-2837
- Forge version: 14.23.1.2577 
- Java version: 8
- Operating System: centos 7

- Plugins/Mods:

**Issue Description** yet another stack trace 
 https://gist.github.com/unstablecraft/6ef755523b209d14a5629f2b3f2453d9

**Comment by Zidane** [comment]
Joy, a fake player with a fake world.

We'll get to it in a bit when we can.

**Comment by gabizou** [comment]
Re-test with build 2839 once it's published.

**Comment by unstablecraft** [comment]
will try in a few

**Comment by unstablecraft** [comment]
@gabizou  sorry man this still exist on 2840 https://gist.github.com/unstablecraft/9ed1a55b8196daa95b0c46a8c3a25013

**Comment by phit** [comment]
so I figured out the issue set `deny-chunk-requests=false`, `load-on-startup=true`, `keep-spawn-loaded=true` and `config-enabled=true` in `config\sponge\worlds\extrautils2\extrautils2_quarry_dim\dimension.conf` otherwise the mod can't load its dimension to mine, hence the NPE

Tested with 
extrautils2-1.12-1.7.2.jar
spongeforge-1.12.2-2555-7.1.0-BETA-2840.jar

**Comment by unstablecraft** [comment]
But I don't want that dimension to load thought about that?

**Comment by ryantheleach** [comment]
It's not expected to be a long term solution, just a hint for testing and narrowing it down.

That said, it might just work with `deny-chunk-requests=false` if you want to test that.

**Comment by unstablecraft** [comment]
with deny-chunk-requests=false = spam
with load-on-startup=true = spam
with config-enabled=true in config\sponge\worlds\extrautils2\extrautils2_quarry_dim\dimension.conf = spam

with all 4 as requested/orderd by phit spam stops

but this is a work around and not really a fix since i have to keep that dim loaded on start up and its spawn 


i hope you can find it :D

**Comment by ryantheleach** [comment]
For what it's worth, config-enabled will have to be on with every setting that applies per dimension or per world or it won't have any affect at all, that's what config-enabled does, is make that config override the global config.

**Comment by unstablecraft** [comment]
idk i never messed with the spongeforge configs

**Comment by unstablecraft** [comment]
thiss isue just occured on revelations 1.3.0 since i updated to 2840 exact same stacktrace only diff forge version

**Comment by phit** [comment]
yes, its always gonna happen unless you tweak your config.. the mod assumes the dimension is gonna be always loaded, and the second one quarry is build the dimension needs to be kept loaded at all times

**Comment by unstablecraft** [comment]
hmm ill live with the spam then until you guys fixed it

**Comment by phit** [comment]
there is nothing to fix.. load the dimension or this spam is gonna keep happening
the only "fix" would be setting those settings I suggested by default for that dimension, so you dont have to manually edit them but that's about it

**Comment by unstablecraft** [comment]
ive fiexed this now by disableing the dims in the extra utils config  this may be closed but a warning should be handy so people know what to do while having this error

**Comment by ryantheleach** [comment]
Talking to Zidane, this will be fixed by changing the config defaults to work with Extra Utilities by default, in a larger refactor of the configuration.

**Comment by phit** [comment]
reposting as this issue is quite long, if you run into this

> set `deny-chunk-requests=false`, `load-on-startup=true`, `keep-spawn-loaded=true` and `config-enabled=true` in `config\sponge\worlds\extrautils2\extrautils2_quarry_dim\dimension.conf` otherwise the mod can't load its dimension for mining
