### ISSUE TITLE
[1.12.2]TileEntityTickPhase causes mass erroring with Hoppers

### ISSUE THREAD

**Issue by limbo-app** [SpongePowered/SpongeForge#1962]
This issue was originally submitted by @Rasgnarok in [SpongePowered/SpongeCommon#1679](https://github.com/SpongePowered/SpongeCommon/issues/1679).
___
**I am currently running**
Not using latest version of SF because of mapping issues mentioned in common tickets.
- SpongeForge version: 2800, Forge 2555/2529
- SpongeVanilla version: NA
- Java version: 8
- Operating System: CentOS

- Plugins/Mods: https://timings.aikar.co/?id=ecea21ad2d6c4652b21f4623604b7bc3#plugins

**Issue Description**
Hoppers feeding from modded blocks cause mass erroring in the console, which floods and creates pronounced spiking until the hopper is removed. To replicate, simply annex a hopper onto a Fossil Cleaner/Mechanical Anvil.

Before updating to Forge 2555: https://gist.github.com/Rasgnarok/6f52695e8f01c8da88890f78c826404b
After updating to Forge 2555: https://gist.github.com/Rasgnarok/b70921d570008dee22393477ef667a78

**Comment by Zidane** [comment]
As per the comment on the common issue, not a Sponge problem.
