### ISSUE TITLE
Error when inventory is missing a displayname

### ISSUE THREAD

**Issue by unstablecraft** [SpongePowered/SpongeForge#1963]
**I am currently running**

- SpongeForge version: 1.12.2 2840
- Forge version: forge-1.12.2-14.23.1.2587-universal
- Java version: 8
- Operating System: CentOs

- Plugins/Mods:

**Issue Description** found a new fatal error with sponge involved 
https://gist.github.com/unstablecraft/8ba12b04ee508077f1acbc69cb54efcf

sadly this error is not compleet (missing 30 ish lines) will add the compleet one shortly

**Comment by phit** [comment]
your log not missing anything important, here's another log from myself https://gist.github.com/phit/994f8d3917de8b17596bf72920a34fd7
already had told Faith about this, it's kinda a mod issue, but I suppose he could add a fallback when the name is missing

**Comment by unstablecraft** [comment]
I figured after some Google time and only catched this by accident otherwise I wouldn't seen it but I though I should report it anyway. 
 any clue wich item it is? 
if I know that can file another report @the mod dev

**Comment by phit** [comment]
one of these https://minecraft.curseforge.com/members/elucent/projects
my bet is on gadgetry, that's where I got my log from at least

**Comment by Faithcaio** [comment]
The name is not really missing on this one.
```
17.01 20:30:32 [Server] INFO java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
17.01 20:30:32 [Server] INFO at elucent.elulib.tile.module.ModuleInventory.func_145748_c_(ModuleInventory.java:237) ~[ModuleInventory.class:?]
17.01 20:30:32 [Server] INFO at org.spongepowered.common.item.inventory.lens.impl.fabric.ContainerFabric.getFirstDisplayName(ContainerFabric.java:124) ~[ContainerFabric.class:1.12.2-2555-7.1.0-BETA-2837]
```

The mod is trying to access `net.minecraft.client.resources.I18n`
which is ClientSide only so it will crash on the server.
