### ISSUE TITLE
Packmode Recipe Change Issue Revised

### ISSUE THREAD

**Issue by tyrobbb94** [SpongePowered/SpongeForge#1965]
I am currently running

SpongeForge version: spongeforge-1.12.2-2555-7.1.0-BETA-2840

Forge version: forge-1.12.2-14.23.1.2587

Java version: 8

Operating System: Windows 10

Plugins/Mods: https://rawgit.com/AllTheMods/ATM-3/master/modlist.html

Issue Description

Using a pack with alternate pack modes (All The Mods 3 in this case), regardless of what the packmode is set to, the server will not load the recipe changes from the script files. JEI will show the new customized recipe, but no output for the recipe will be available. Instead, the vanilla crafting requirements are needed to make the item. This only occurs when sponge is installed, and works as it should without sponge. I have attempted both the latest version of API 7 Sponge and the recommended version of the same.

**Comment by ryantheleach** [comment]
@tyrobbb94 Is there anything in the log files that would indicate something going wrong with the loading of the recipes from the scripts?

**Comment by tyrobbb94** [comment]
Not that i've seen but it is possible i have missed something, i will double check myself and link the latest log here.

**Comment by tyrobbb94** [comment]
Unfortunately the paste was too large for pastebin and i'm not familiar with other sites, hopefully a dropbox link is acceptable: https://www.dropbox.com/s/lzpwbycy4yt9qev/fml-junk-earlystartup.log?dl=0

**Comment by tyrobbb94** [comment]
Im going to close this issue because after looking through and trying something, i seem to have found the problem. It appears that since the server files i was using were a clone from our public servers, the items that were banned still existed, Apparently one of the items involving the minecolonies mod was causing the scripts to ignore a portion of the recipes suppose to be registered. Im still not quite sure why removing sponge stopped this issue, but it seems to be fixed by re-enabling the item and just banning the placement. Thank you for your help and i apologize if i wasted your time.
