### ISSUE TITLE
"Freeze"

### ISSUE THREAD

**Issue by FilipK-CZ** [SpongePowered/SpongeForge#1966]
**I am currently running**

- SpongeForge version: 8.0.0-BETA-2841
- Forge version: 1.12.2-2555
- Java version: OpenJDK Runtime Environment (build 1.8.0_151-b12)
                        OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)
- Operating System: CentOS 7

- Plugins/Mods:
```
Plugins (9): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, FlexibleLogin, InstantRespawn, LuckPerms, Nucleus, SkinsRestorer

Mods (95): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Advanced Generators, AppleSkin, BD Lib, Better Builder's Wands, BetterBedrockGen, Biomes O' Plenty, Bloodmoon, Bookshelf, Chameleon, Chisel, Chisels & Bits, CoFH Core, CoFH World, CodeChicken Lib, CommonCapabilities, Compacter, Crafting Tweaks, Cyclops Core, Dark Utilities, DebugServerInfo, DrZhark's CustomSpawner, DrZhark's Mo'Creatures Mod, Dynamic Surroundings, Ender Zoo, EnderTanks, Environmental Tech, Extra Utilities 2, FastAsyncWorldEdit, FoamFix, FoamFixCore, Foamflower, Forestry, GenDustry, Immersive Engineering, Immersive Petroleum, Industrial Foregoing, IndustrialCraft 2, Integrated Dynamics, IntegratedDynamics-Compat, Integration Foregoing, Iron Chest, JEI Bees, JourneyMap, Just Enough Items, LunatriusCore, Magneticraft, Mantle, ModelLoader, Morpheus, Multi-Storage, NetherEx, NetherPortalFix, Not Enough Items, NuclearCraft, OpenBlocks, OpenComputers, OpenComputers (Core), OpenModsLib, OpenModsLib Core, Ping, Quick Leaf Decay, Ranged Pumps, Reap Mod, Reborn Core, RebornStorage, Redstone Arsenal, Redstone Flux, Refined Storage, Refined Storage Addons, Shadowfacts' Forgelin, ShetiPhian-Core, Storage Drawers, TESLA, Tech Reborn, Tesla Core Lib, Tesla Core Lib Registries, The One Probe, The Twilight Forest, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Tinkers Tool Leveling, Tinkers' Construct, UniDict, Valkyrie Lib, Vending, WanionLib, WorldEdit

```
**Issue Description**
Server after some time (randomly, only with online players) "freeze" - kick players "NetworkDispatcher exception io.netty.handler.timeout.ReadTimeoutException: null", don't response on commands, ping on server work (show kicked players, dinnerbone.com status), tried to connect with response "You are already online"

I thought that it makes Java, but now I don't think so (I tried with and without java arguments).
I absolutely don't know.

[fml-junk-earlystartup.log](https://gist.githubusercontent.com/FilipK-CZ/8a6d79c05f3789b91035a77e05653955/raw/d714ee58e30263e8b4d3fa65fb3ab70b87770e20/fml-junk-earlystartup.log)

**Comment by phit** [comment]
what is your max-tick-time in the server.properties set to?

**Comment by FilipK-CZ** [comment]
I have set 60000

**Comment by phit** [comment]
try 7.1.0-BETA-2842
don't use the 8.0.0 builds for a production server

**Comment by FilipK-CZ** [comment]
Ok I'll try
This is alpha testing server

**Comment by Keaton1188** [comment]
Hey, we have had this issue before.. for us its usually due to people doing massive crafting jobs with RS, this causes the server to freeze up and have to be killed. Possibly the issue you are having.

**Comment by FilipK-CZ** [comment]
I switched to Stable version and still freezing. It looks like a problem with chat. I was in game and server was Ok and after send message server instantly freeze. Another freeze was that 2 players were on a server and I wrote to console and again instantly freeze.  Every freeze is random (normal chat works)

**Comment by phit** [comment]
sorry, but until you figure out what mods are needed to reproduce this there is nothing we can really do
