### ISSUE TITLE
[Mod Compat] Multi-Hotbar

### ISSUE THREAD

**Issue by ElvenChaos** [SpongePowered/SpongeForge#1967]
**I am currently running**

- SpongeForge version: 1.12.2-2555-7.1.0-BETA-2840
- Forge version: 2598
- Java version: 1.8.0_151
- Operating System: Win10 Home

- Plugins/Mods:
LuckPerms
Nucleus
[Multi-Hotbar](https://minecraft.curseforge.com/projects/multi-hotbar/files/2520321) and it's [Core](https://minecraft.curseforge.com/projects/multi-hotbar-core)

**Issue Description**
When Multi-Hotbar (and needed core mod) are installed, the server will have an internal error (index out of bounds) and not allow the player to join. The mod is installed both server and client side. The error is detailed at the very end of the posted log file.

https://gist.github.com/ElvenChaos/c36dd6cf56b2fb56124188d64e3a414c

**Comment by phit** [comment]
https://github.com/rolandoislas/multi-hotbar-core/blob/master/src/main/java/com/rolandoislas/multihotbar/asm/transformer/Transformer.java

**Comment by Faithcaio** [comment]
Should be fixed with latest API 7 build now
