### ISSUE TITLE
Phase Tracker Incompatibility with iChisel from Chisel

### ISSUE THREAD

**Issue by Whazaaaaa** [SpongePowered/SpongeForge#1972]
**I am currently running**

- SpongeForge version: SpongeForge-1.12.2-2555-7.1.0-BETA-2842 (havent had the time to update yet but I dont see newer versions fixing this problem)
- Forge version: FTBserver-1.12.2-14.23.1.2587-universal
- Java version: 8
- Operating System: Ubuntu

- Plugins/Mods: AdamantineShield, BetterChunkLoader, CatClearLag, Discord Bridge, Enjin Minecraft Plugin, GoonUtils, GriefPrevention, LuckPerms, NuVotifier, Nucleus, PlayerShopsRPG, ProjectCore for SpongeAPI 7.x, SeriousVote, StackBan for SpongeAPI 7.x, Total Economy

This is happening for me on the direwolf20 1.12 modpack and also the AllTheMods3 modpack. (latest version)

**Issue Description**
Cause tracker breaks which break functionality for plugins especially Griefprevention. People are unable to do all kinds of stuff because of it in claims. I have spoken to bloodmc and he said it wasnt his plugin but the cause tracker breaking due to chisel?
After a restart the server is fine but after a while it breaks. I have yet to find the exact cause but perhaps the server logs will help more.
https://github.com/MinecraftPortCentral/GriefPrevention/issues/577
Might give some more insight.

https://gist.githubusercontent.com/Whazaaaaa/ba87f608b0165b7e1c59c88924156ce9/raw/2f6013f23af56de587d8b1e66bb725e9eb373707/gistfile1.txt
https://gist.githubusercontent.com/bloodmc/69fcc7560e43c803c059d2ed81335304/raw/0774cdfc4a587cb3f2af0967729727bb1a75bb85/chisel_error.txt

**Comment by Whazaaaaa** [comment]
Anyone that can figure out whatsup?
I'm still having this with 1.12.2-2586-7.1.0-BETA-2881
Now I'm horrible at reading these kinds of logs so can anyone figure out whats going on? It doesnt seem like anyone else is having this either?

**Comment by phit** [comment]
https://gist.github.com/phit/57a45c144fc680b7f7ee6db439cb0ebf

looks like a bug in Chisel to me, not a Sponge issue.

**Comment by Whazaaaaa** [comment]
But sponges causetracker is the thing that breaks stuff. When without sponge the problems we get would never happen. And seeing ad modpacks dont update as often as spongeForge does. It would be really nice to have a fix for this on the sponge side of things.

**Comment by phit** [comment]
there's nothing for Sponge to fix, the mod is erroring, Sponge just tells you about it instead of it crashing the server

see https://github.com/SpongePowered/SpongeCommon/commit/bb605ed82a865d08cf7f18e67e4d90905f3f0eb8#diff-887da76c98bfd683f387bc220c615dc9R399

**Comment by Whazaaaaa** [comment]
So if it werent for sponge the server would crash then?

**Comment by phit** [comment]
most likely, yes

**Comment by tterrag1098** [comment]
Uhh no? Sponge is doing some verbose logging here and creating its own exception:

https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/event/tracking/PhaseTracker.java#L579-L582
https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/event/tracking/PhaseTracker.java#L451

There is no exception being generated by Chisel code. If we are doing something to break Sponge assumptions, this logging is very unclear and unhelpful as it gives absolutely no info on *what* exactly is unexpected.

**Comment by gabizou** [comment]
The weird thing about this issue is that sponge has had a tracking system to wrap around listeners like this, in this case, where sponge specifically knows that it has to process block changes for server and world tick listeners.

The problem here is that I'm not sure why the listener phase state is being entered to process the block changes (since otherwise, sponge doesn't have a phase state to understand how block changes are occurring). I'll re-open and investigate when time permits.

**Comment by Whazaaaaa** [comment]
I know this is an odd issue and I'm probably the only one who has had it for now. But I am still having this issue on 2944/2946. Anything I can do? Its probably some chisel block somewhere that went wrong and Sponge doesnt know how to handle. But I have no way of finding it :(

**Comment by kasdo** [comment]
I have the same problem. What to do?

**Comment by ImMorpheus** [comment]
`onServerTickEnd`
Yeah, chisel has nothing to do with this.
This was fixed by https://github.com/SpongePowered/SpongeCommon/pull/2125
