### ISSUE TITLE
World Transfer NPE

### ISSUE THREAD

**Issue by Raycoms** [SpongePowered/SpongeForge#1973]
**I am currently running**

- SpongeForge version: 2844
- Forge version: 2604
- Java version: 1.8
- Operating System: Debian.

We seem to get the following crash when executing inter dimensional teleport with sponge installed.

Our code: https://github.com/Minecolonies/minecolonies/blob/fix/dim-tp/src/main/java/com/minecolonies/coremod/util/TeleportToColony.java

> [16:29:33] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'mc home' for source EntityPlayerMP['Zyxifrash'/2859, l='Mining', x=-311.00, y=66.00, z=1114.00]: java.
> lang.NullPointerException
> java.lang.RuntimeException: java.lang.NullPointerException
>         at org.spongepowered.common.command.MinecraftCommandWrapper.tryExecute(MinecraftCommandWrapper.java:164) ~[MinecraftCommandWrapper.class:1.12.2-2555-7.1.0-BETA-2844]
>         at org.spongepowered.common.command.MinecraftCommandWrapper.process(MinecraftCommandWrapper.java:145) ~[MinecraftCommandWrapper.class:1.12.2-2555-7.1.0-BETA-2844]
>         at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:342) ~[SimpleDispatcher.class:1.12.2-2555-7.1.0-BETA-2844]
>         at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:322) [SpongeCommandManager.class:1.12.2-2555-7.1.0-BETA-2844]
>         at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
>         at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:958) [pa.class:?]
>         at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:937) [pa.class:?]
>         at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
>         at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
>         at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:149) [PacketUtil.class:1.12.2-2555-7.1.0-BETA-2844]
>         at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlb000(SourceFile:539) [hv$1.class:?]
>         at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
>         at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
>         at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:274) [SpongeImplHooks.class:1.12.2-2555-7.1.0-BETA-2844]
>         at net.minecraft.server.MinecraftServer.redirect$onRun$zjg000(MinecraftServer.java:4007) [MinecraftServer.class:?]
>         at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
>         at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
>         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
>         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
>         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
> Caused by: java.lang.NullPointerException
>         at net.minecraft.world.Teleporter.handleEntityPortalExit(SourceFile:741) ~[anc.class:?]
>         at net.minecraft.world.Teleporter.func_180620_b(SourceFile:669) ~[anc.class:?]
>         at net.minecraft.world.Teleporter.func_180266_a(SourceFile:606) ~[anc.class:?]
>         at org.spongepowered.common.entity.EntityUtil.handleDisplaceEntityPortalEvent(EntityUtil.java:389) ~[EntityUtil.class:1.12.2-2555-7.1.0-BETA-2844]
>         at org.spongepowered.common.entity.EntityUtil.teleportPlayerToDimension(EntityUtil.java:203) ~[EntityUtil.class:1.12.2-2555-7.1.0-BETA-2844]
>         at net.minecraft.entity.player.EntityPlayerMP.func_184204_a(EntityPlayerMP.java:3921) ~[oq.class:?]
>         at com.minecolonies.coremod.util.TeleportToColony.teleportPlayer(TeleportToColony.java:141) ~[TeleportToColony.class:?]
>         at com.minecolonies.coremod.util.TeleportToColony.colonyTeleport(TeleportToColony.java:92) ~[TeleportToColony.class:?]
>         at com.minecolonies.coremod.commands.colonycommands.HomeTeleportCommand.execute(HomeTeleportCommand.java:50) ~[HomeTeleportCommand.class:?]
>         at com.minecolonies.coremod.commands.AbstractSplitCommand.execute(AbstractSplitCommand.java:75) ~[AbstractSplitCommand.class:?]
>         at com.minecolonies.coremod.commands.CommandEntryPoint.func_184881_a(CommandEntryPoint.java:56) ~[CommandEntryPoint.class:?]
>         at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) ~[bj.class:?]
>         at org.spongepowered.common.command.MinecraftCommandWrapper.tryExecute(MinecraftCommandWrapper.java:160) ~[MinecraftCommandWrapper.class:1.12.2-2555-7.1.0-BETA-2844]
>         ... 21 more

**Comment by ryantheleach** [comment]
Remapped StackTrace: https://gist.github.com/ryantheleach/6ea03da4e403bf6a656835bb603b5f5c/revisions

**Comment by dualspiral** [comment]
I haven't been able to get into exactly why this is and have to disappear for a bit, but I reproduced it - [it looks like it's this line to me](https://github.com/SpongePowered/SpongeCommon/blob/7678e517fb3c79535a3d0727cc061e461f09c674/src/main/java/org/spongepowered/common/mixin/core/world/MixinTeleporter.java#L241), I think `entityIn.getLastPortalVec()` is returning `null` - though that's from a mix of reading bytecode and a stacktrace with that line number. If anyone knows what it might be from there, feel free to take it on!

**Comment by Raycoms** [comment]
We tried it only with transfer to world but it causes the same issue.

**Comment by bloodmc** [comment]
@Raycoms please provide a test world that I can use to easily reproduce this issue so I can do some further testing.

**Comment by Raycoms** [comment]
@bloodmc actually you only need to install minecolonies, place down a "Townhall" in the overworld, then go to the nether or end and do /mc home, I will send you the jar which crashes this.
https://s3.eu-central-1.amazonaws.com/minecolonies/Minecolonies/Minecolonies_Branches/7223/minecolonies-universal-1.12.2-0.8.7223.jar

**Comment by dualspiral** [comment]
@bloodmc You just need to write a small mod that has the equivalent of [this line](https://github.com/Minecolonies/minecolonies/blob/fix/dim-tp/src/main/java/com/minecolonies/coremod/util/TeleportToColony.java#L142-L143) and transfer a player to a non-end dimension **before** the player touches a portal block.

My PR fixes this (https://github.com/SpongePowered/SpongeCommon/pull/1759), but as I suggest in the PR, I don't know why Sponge causes this to be a problem in the first place, or if this is the right thing to do. Not sure why Forge doesn't have an NPE. I have no time to look into it any futher, feel free to merge, improve or abandon my PR.

**Comment by bloodmc** [comment]
@dualspiral @Raycoms So I debugged this in both Forge and SpongeForge and they both have the issue. It will ONLY work properly if the player interacts with a portal block such as Nether's portal then types "/mc home". This is due to lastPortalVec being set on collision with Nether's portal block.

If you login then teleport to another dimension via a command WITHOUT colliding with a portal block then the bug will occur as 'lastPortalVec' will be null.

Here is a stacktrace for the same bug in Forge when I quit single player in nether and reload then type "/mc home"

```java
java.lang.NullPointerException: null
	at net.minecraft.world.Teleporter.placeInExistingPortal(Teleporter.java:135) ~[Teleporter.class:?]
	at net.minecraft.world.Teleporter.placeInPortal(Teleporter.java:35) ~[Teleporter.class:?]
	at net.minecraft.server.management.PlayerList.transferEntityToWorld(PlayerList.java:707) ~[PlayerList.class:?]
	at net.minecraft.server.management.PlayerList.transferPlayerToDimension(PlayerList.java:617) ~[PlayerList.class:?]
	at com.minecolonies.coremod.util.TeleportToColony.teleportPlayer(TeleportToColony.java:143) ~[TeleportToColony.class:?]
	at com.minecolonies.coremod.util.TeleportToColony.colonyTeleport(TeleportToColony.java:92) ~[TeleportToColony.class:?]
	at com.minecolonies.coremod.commands.colonycommands.HomeTeleportCommand.execute(HomeTeleportCommand.java:50) ~[HomeTeleportCommand.class:?]
	at com.minecolonies.coremod.commands.AbstractSplitCommand.execute(AbstractSplitCommand.java:75) ~[AbstractSplitCommand.class:?]
	at com.minecolonies.coremod.commands.CommandEntryPoint.execute(CommandEntryPoint.java:56) ~[CommandEntryPoint.class:?]
	at net.minecraft.command.CommandHandler.tryExecute(CommandHandler.java:119) [CommandHandler.class:?]
	at net.minecraft.command.CommandHandler.executeCommand(CommandHandler.java:91) [CommandHandler.class:?]
	at net.minecraft.network.NetHandlerPlayServer.handleSlashCommand(NetHandlerPlayServer.java:958) [NetHandlerPlayServer.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processChatMessage(NetHandlerPlayServer.java:937) [NetHandlerPlayServer.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.processPacket(CPacketChatMessage.java:38) [CPacketChatMessage.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.processPacket(CPacketChatMessage.java:1) [CPacketChatMessage.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) [PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_60]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_60]
	at net.minecraft.util.Util.runTask(Util.java:50) [Util.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:721) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185) [IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
```

Single player freezes at "Loading terrain" and requires client to be restarted.
This is not our issue but rather an issue with how minecolonies is handling its teleport logic.

@dualspiral was correct in his findings with how it SHOULD of been happening in Forge which I confirmed to be true.

@Raycoms I would suggest opening a ticket with Forge to fix this NPE as it should be feasible to do what you are doing without the game crashing due to not having lastPortalVec set. Once Forge improves the code for your method, I can do the same on our end.

**Comment by bloodmc** [comment]
@Raycoms I've decided to fix this issue for you =) I'll have to PR Forge the same fix when I get a chance. Expect a fix soon.

**Comment by Raycoms** [comment]
Thanks that sounds great =)

2018-02-17 1:26 GMT+00:00 bloodmc <notifications@github.com>:
