### ISSUE TITLE
JEI Plus button broken with SpongeForge

### ISSUE THREAD

**Issue by JoeSGT** [SpongePowered/SpongeForge#1976]
**I am currently running**

- SpongeForge version: 1.12.2-2555-7.1.0-BETA-2854
- Forge version: 1.12.2-14.23.1.2604
- Java version: 8
- Operating System: Windows

- Plugins/Mods:
 jei_1.12.2-4.8.5.147
spongeforge-1.12.2-2555-7.1.0-BETA-2854

**Issue Description**
I made a clean server with those 2 mods 
and when you click on an item example stone brick in jei  but make sure you have the item to craft it in your inventory since stone brick you need stone so i have stone in my inventory  and you click on the plus button
and have the items move to the craftingbox and attempt to take out the output it disapper
the logs/console does not show anything here a GIF of what i am talking about
https://gyazo.com/5416b32be6ac7b1c4574588507371b69

EDIT:  When you take out SpongeForge this does not happen

**Comment by ryantheleach** [comment]
Does this happen without jei on the server and only jei on the client?

**Comment by JoeSGT** [comment]
I tried singleplayer and i can do it, Tried without SpongeForge on server and i can do it
but if you were too take jei out of Serverside the feature does not work it's disabled here a screenshot of what i am talkin about
https://gyazo.com/1f1252414f55bd2a8aaa733bbd8c2108

**Comment by Faithcaio** [comment]
Please try build 2845.
JEI might change the inventory without us noticing it in the new CraftingEvents.

**Comment by Faithcaio** [comment]
This is where stuff is set in the grid: https://github.com/mezz/JustEnoughItems/blob/4937b44c5d747600ae076b7c5f895bba2553ddf9/src/main/java/mezz/jei/transfer/BasicRecipeTransferHandlerServer.java#L73-L85

**Comment by JoeSGT** [comment]
Tried using build 2845 on a test server and it work!
but sadly i cannot use that build on my other server due to other plugins and mods work on the latest

**Comment by mezz** [comment]
When JEI opens its gui, it doesn't close the container of the old gui.
When the transfer button is pressed, it goes back to the old gui and sends a packet to the server which sets the items in the container. This works without any race conditions on a vanilla client because the old container is always open. There may be an issue with SpongeForge if it works differently when the JEI gui 
 opens.

Beyond that I don't think JEI is doing things in a weird way, so I think that is the top suspect in my mind. Let me know what you find or if you have more questions.

**Comment by Faithcaio** [comment]
Found it. I ignored changes in the crafting grid when coming from an unknown packet.
Because it caused an infinite loop with Tinkers Construct Crafting Stations when canceling a recipe.

**Comment by Faithcaio** [comment]
Somewhat fixed in latest.
We just dont fire the Preview events for now when a mod sets the crafting grid slots using non vanilla packets.

A cancel on CraftItemEvent.Craft still works.

**Comment by ryantheleach** [comment]
@Faithcaio does that mean you can no longer adjust the crafting recipe for modded packets, or does it mean it just doesn't show the changes effectively? Also the comment on the line above your change probably needs changing

**Comment by Faithcaio** [comment]
You could not do that before either. We just ignored Crafting Grid changes.
It might still be possible to do it by lying to the client about the crafting result.
