### ISSUE TITLE
Mixin is sometimes detecting my plugin, sometimes not.

### ISSUE THREAD

**Issue by Yeregorix** [SpongePowered/SpongeForge#1977]
**I am currently running**

- SpongeForge version: 1.12.2-2555-7.1.0-BETA-2844
- Forge version: 1.12.2-14.23.1.2555

- Plugins/Mods: AntiXray

**Issue Description**
I've recently developed a public Sponge plugin using Mixin which works fine for me and for most users but for some users using SpongeForge my plugin is not working at all because my mixin config does not seems to be applied or even detected. I don't know if I'm doing something wrong or it's a Mixin issue or a SpongeForge's issue and I cannot reproduce the issue on my computer that's why I'm asking for help.
I've first reported the issue on the Mixin repo but I was redirected here.

Here is my plugin: https://github.com/Yeregorix/AntiXray

**Comment by phit** [comment]
will need logs of it not loading, otherwise we can't really do anything

**Comment by Yeregorix** [comment]
I can't reproduce the issue but here is a log provided by an user:
https://gist.github.com/BrainStone/be87875d06da5ca1d48f9fd074d09553

**Comment by phit** [comment]
Plugins using Mixins have to go into the `mods` folder, the user put them in `mods/plugins` which doesn't load the Mixins.
