### ISSUE TITLE
Closing inventory while moving item causes item to be deleted instead of dropped (Forge)

### ISSUE THREAD

**Issue by rob5251** [SpongePowered/SpongeForge#1981]
**I am currently running**

- SpongeForge version: 1.12.2-2586-7.1.0-BETA-2866
- Forge version: 14.23.1.2586
- Java version: 1.8.0_161
- Operating System: Win10

**Issue Description**
In the current recommended version of forge to use with Sponge (2586) there is an issue where if you are holding an item in the inventory (moving with mouse click) and then hit esc or the inventory hotkey instead of the item getting dropped (as normal) the item just gets deleted entirely.

A bump of recommended forge is probably in order to fix this? Not sure if its been fixed in a later release of Forge or not.

**Comment by Faithcaio** [comment]
I run Forge ~2555~ 2586 in my dev environement and it works fine.
Make sure you are not in creative. Items on cursor will not drop when in creative.

**Comment by rob5251** [comment]
Is 2555 fine to use with spongeforge build 1.12.2-2586-7.1.0-BETA-2866 though or will I have to revert to spongeforge 1.12.2-2555-7.1.0-BETA-2857?

I always try to make sure I'm running the one recommended for the build.

**Comment by Faithcaio** [comment]
Oh nvm. I didnt notice it was changed to Forge 2586.

**Comment by notfood** [comment]
Using
* spongeforge-1.12.2-2586-7.1.0-BETA-2868.jar

Tried with
* forge-1.12.2-14.23.1.2586-universal.jar
* forge-1.12.2-14.23.1.2594-universal.jar
* forge-1.12.2-14.23.1.2607-universal.jar

Still happening.

My test was to grab a torch, then press escape. The torch kept disappearing.

Commit https://github.com/SpongePowered/SpongeForge/commit/25720e43901b4296b1bc1639cf92daec59f25d2c had no effect

It's not a forge bug by the way, it's not reproducible without sponge.

**Comment by Faithcaio** [comment]
@bloodmc maybe this only happens in production not dev?

@notfood that commit fixed smth. else. Calling `player.closeInventory` during some events caused exceptions.

**Comment by Faithcaio** [comment]
Please try this Sponge build: 1.12.2-2586-7.1.0-BETA-2865.
So we know for sure this is a new issue

**Comment by notfood** [comment]
Tested with 1.12.2-2586-7.1.0-BETA-2865

Same issue found

**Comment by Faithcaio** [comment]
What about the one before 1.12.2-2586-7.1.0-BETA-2863?

**Comment by notfood** [comment]
Notice, I'm testing this with 0 mods and 0 plugins.

It's literally forge and spongeforge. It's very easily reproducible.

spongeforge-1.12.2-2586-7.1.0-BETA-2863.jar FAIL
spongeforge-1.12.2-2586-7.1.0-BETA-2862.jar FAIL
spongeforge-1.12.2-2555-7.1.0-BETA-2850.jar FAIL
spongeforge-1.12.2-2555-7.1.0-BETA-2843.jar FAIL
spongeforge-1.12.2-2555-7.1.0-BETA-2842.jar PASS
spongeforge-1.12.2-2555-7.1.0-BETA-2840.jar PASS
spongeforge-1.12.2-2555-7.1.0-BETA-2837.jar PASS

**Comment by notfood** [comment]
Notice, I'm testing this with 0 mods and 0 plugins.

It's literally forge and spongeforge. It's very easily reproducible.

**Comment by notfood** [comment]
spongeforge-1.12.2-2555-7.1.0-BETA-2837.jar PASS

**Comment by notfood** [comment]
spongeforge-1.12.2-2555-7.1.0-BETA-2850.jar FAIL

**Comment by notfood** [comment]
spongeforge-1.12.2-2555-7.1.0-BETA-2843.jar FAIL

**Comment by phit** [comment]
edit your post please instead of posting 30 comments, thanks for testing this

**Comment by notfood** [comment]
Sorry. Got carried away as the time within tests was long. Won't happen again.

Last working version is spongeforge-1.12.2-2555-7.1.0-BETA-2842.jar

**Comment by phit** [comment]
2843 is https://github.com/SpongePowered/SpongeForge/commit/83bb1dd2926a527befbda235391f8e3604111c42

**Comment by Faithcaio** [comment]
huh so the captured items are just not spawned... but why was is it working for me in dev.
Thanks for testing. I'll try to fix it this evening.

**Comment by Faithcaio** [comment]
found it:
 only happened when `SpongeImpl.getGlobalConfig().getConfig().getOptimizations().doDropsPreMergeItemDrops()` is false

fixed in https://github.com/SpongePowered/SpongeCommon/compare/5858f2a99a5e...1e1597034149
