### ISSUE TITLE
Advancement crash, possibly related to the Nether

### ISSUE THREAD

**Issue by samolego** [SpongePowered/SpongeForge#1983]
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2586-7.1.0-BETA-2865.jar
/tried with 2887 too
- Forge version:  2586
- Java version: Java 8
- Operating System: Raspbian GNU/Linux 8 (jessie)

Not using the latest SF, because the issue seems to be in other versions, too...

- Plugins/Mods:
Nucleus, Luckperms, Griefprevention, Biomes O Plenty, Veinminer, Worldedit, flexiblelogin, Magibridge, Ely.by Skinsystem, Total Economy and Spongeforge of course :-)

**Issue Description**
I have joined the server, stuck in nether portal (I don't know if this is a problem.)... Sever crashed. Tried it again, quickly tped myself outside the NP, logged in ... and server crashed. i have tried with multiple sponge and forge versions, none of them seems to work...
Tried again, this time spawned outside the NP... Server crashed again...

https://gist.github.com/samolego/13835aeaab13120d0101202627ecbb63
https://gist.github.com/samolego/cf4cf49d867e0776280ad821ea6c5b6a
https://gist.github.com/samolego/ae70bd159e5889a18347936292b8434a

**Comment by phit** [comment]
@samolego try updating to SpongeForge 2881 or newer

**Comment by samolego** [comment]
I have updated, nothing happened...

**Comment by samolego** [comment]
Tried, nothing better. Still crashing

**Comment by samolego** [comment]
Actually, when I am not the Nether, it works fine... strange...

**Comment by phit** [comment]
still can't reproduce this, have you tried this on a fresh world?

**Comment by samolego** [comment]
I have, it was solved. I guess it was the advancements pack that I've installed.

**Comment by samolego** [comment]
I have, it was solved. I guess it was tge advancements pack that I've installed.

**Comment by ryantheleach** [comment]
@samolego in future, if you have a crash relating to X and you have an X Pack installed, providing X would help a ton.

In this case, if you want us to be able to reproduce, providing the Advancement pack would have allowed us to investigate.

How was it solved? Was it a workaround because we are doing something wrong still? Or was the advancement pack invalid on vanilla as well?

**Comment by samolego** [comment]
Yeah, I am really sorry, I remembered that 2 days ago when I was thinking if I have installed any custom packs...

**Comment by samolego** [comment]
I didn't try it in vanilla, so I actually don't know if this is SF problem or not.

I am sorry, I cannot find the advancement pack that I've been using anymore ... If a find it, I will comment.

Thanks for all the help. I really appreciate it!

 And sorry for all the work you (and team) have done.
