### ISSUE TITLE
Tinker's Construct Slime boots -  on bounce movement, network error.

### ISSUE THREAD

**Issue by Krosta8** [SpongePowered/SpongeForge#1984]
**I am currently running**
- SpongeForge version: 1.12.2-2586-7.1.0-BETA-2873
- Forge version: 14.23.1.2586
- Java version: 1.8.0_101
- Operating System: Linux

- Plugins/Mods:
Plugins (26): Minecraft, Minecraft Coder Pack, Sponge API, SpongeForge, FastAsyncWorldEdit, BungeeTabListPlus-SpongeBridge, CatClearLag, CmdBuilder, CmdControl, CommandUtils, DailyRewards, GriefPrevention, LuckPerms, Nucleus, Pixel Announcer, PlaceHolderAPI, ProjectCore, ProjectPortals, Total Economy, UltimateChat, VirtualChest, WorldEdit
Mods (28): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AGP, BetterQuesting, CraftTweaker2, CreativeCore, IronChest, JourneyMap, JEI, LittleTiles, Malisis Advert, Malisis Doors, Malisis Core, Mantle, ModControl, MrCrayFish Furniture Mod, NetherPortalFix, Pixel Extras, Pixelmon, Tinker's Construct, WonderTrade

**Issue Description**
When the player has equiped Slime Boots or Congealed Blood Boots from Tinkers's Construct and should get fall damage, error appears. Error appears only on Tinker's Construct version 2.9.0.55.
Posted to author of the mod and the error is Sponge related.

<!-- Please provide a *full* server log (and crash-report if applicable).
https://gist.github.com/Krosta8/c9990c94490d65fc9b671470a552145e

**Comment by phit** [comment]
please provide the full log, as asked from you in the issues template.. `fml-junk-earlystartup.log` and upload it to https://gist.github.com

**Comment by Krosta8** [comment]
Sorry,
I thought, that in this case, just error log would be better for you.
Here is the full log: https://gist.github.com/Krosta8/91b0e714e3c37d6b2fd9dd297229cf81

**Comment by phit** [comment]
you didnt add any log to your initial post

**Comment by Krosta8** [comment]
Oh, I see, sorry for this.. Here is just the error https://gist.github.com/Krosta8/c9990c94490d65fc9b671470a552145e

**Comment by ryantheleach** [comment]
This probably doesn't have anything to do with fall damage, but alternate unexpected movement of some kind.

https://github.com/SlimeKnights/TinkersConstruct/issues/3334
https://github.com/SlimeKnights/TinkersConstruct/issues/3340
https://github.com/SlimeKnights/TinkersConstruct/issues/3362

**Comment by ryantheleach** [comment]
This isn't us, @Rednesto reproduced it in pure Forge, whilst @Faithcaio and I were trying to reproduce on Sponge Forge.

We are preparing a reply for tinkers.
