### ISSUE TITLE
PMPMDescription: Exception ticking world java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by TheNimbleNinja** [SpongePowered/SpongeForge#1985]
forge 1.12.2

- SpongeForge version: none
- Forge version: forge-14.23.1.2610
- Java version: java9(64-bit)
- Operating System: windows 10

- Plugins/Mods:around 203 mods(abyssalcraft intergration,abyssalcraft,actually additions,actuallybaubles,additionalloottables,advancedrocketry,ae2stuff,aether_legacy,akashictome,alchemytrinkets,angelringtobauble,applecore,appleskin,appliedenergistics2,architect,armorplus,aroma1997core,aroma1997s-dimensional-world,aromabackup,astikoor,astralsourcery,athenaeum,autoreglib,avaritia,babymobs,base,basemetals,baubles,bdlib,bedrockbgone,betteragriculture,betterbuilderswands,betterfishing,betterquesting,bibliocraft,binnie-mods,blockcraftery,blockdrops,bookshelf,botania,botaunomy,brandonscore,buildcraft-builders,,buildcraft-compact,,buildcraft-core,,buildcraft-energy,,buildcraft-factory,,buildcraft-robotics,,buildcraft-silicon,,buildcraft-transport,calculator,chameleon,chisel,chiselsandbits,clayworldgen,clumps,codechickenlib,cofhcore,cofhworld,commoncapabilities,compacter,compactsolars,cookingforblockheads,coroutil,crafttweaker2,ctm,cucumber,custommainmenu,cyclopscore,dailies,danknull,darkutils,deathcounter,decocraft,densemetals,draconic-evolution,dropt,dynamictrees,elavatormod,elulib,enderstorage,endmetals,environmentaltech,everlastingabilities,evilcraft,extraalchemy,extracells,extrautils2,extremereactors,farmingforblockheads,farseek,fastleafdecay,flatcoloredblocksfloricraft,forestry,forgelin,frogcraft-rebirth,ftblib,ftbutilities,ftgu,gendustry,generators,hats,heavy inventories,ichunutil,immersiveengineering,immersiveengineering-core,industrialcraft-2,industrialforegoing,industrialwires,infernalmobs,intergratedtunnels,intergrateddynamics,intergrationforegoing,inventorypets,inventorytweaks,ironbackpacks,ironchest,irontanks,ivtoolkit,jei,jj races,justenoughbuttons,justenoughresources,largeveins,librarianlib,libvulpes,lycanitesmobscomplete,magical map,magicbees,mantles,mcjtylib,mistworld,mobgrindingutils,modtweaker,morph,mousetweaks,mtlib,mxtune,mysticalagradditions,mysticalagriculture,natura,netherex,nethermetals,nibbler,notenoughids,oceanfloor,opencomputers,orespawn,overpoweredinventory,p455w0rdslib,packingtape,pam's havestcraft,placebo,pllants,preston,primalcore,progressivedifficulty,psi,realisticitemdrops,reap,reborncore,recurrentcomplex,recycler4,redstonearsenal,redstoneflux,reliquary,resourceloader,rftools,rftoolsctrl,rftoolsdim,roots,scalinghealth,sgextraparts,shadowmc,silentlib,silentgems,sonarcore,soulshards-tow,standardexpansion,storagedraws,supercore,takumicraft,techreborn,tesla-core,thedragonlib,thermaldynamics,thermalexpansion,thermalfoundation,todolist,toroquest,treecapitator,tumbleweed,unidict,unifieditems,uniquecrops,valkyrielib,wanionlib,wawla,wizardry,woot,zenocore

when i load a world right when you start playing the game freezes/crashes

[2018-02-02-6.log.gz](https://github.com/SpongePowered/SpongeForge/files/1691217/2018-02-02-6.log.gz)
[crash-2018-02-02_18.10.02-server.txt](https://github.com/SpongePowered/SpongeForge/files/1691219/crash-2018-02-02_18.10.02-server.txt)

**Comment by kashike** [comment]
You aren't using Sponge. This is the wrong place to open an issue.

**Comment by TheNimbleNinja** [comment]
then where do i post it?
