### ISSUE TITLE
RefinedStorage Inventory IndexOutOfBoundsException

### ISSUE THREAD

**Issue by mihionmc** [SpongePowered/SpongeForge#1988]
**I am currently running**

- SpongeForge version: 1.12.2-2586-7.1.0-BETA-2887
- Forge version: ftb direwolf 1.12.2 1.8
- Java version: bleeding oracle
- Operating System:linux

- Plugins/Mods:

**Issue Description**

Hi! i get this after upd to the last ver.1.12.2-2586-7.1.0-BETA-2889 on direwolf https://gist.github.com/phit/9b5bb7554c615a7fcc43787cf8c5464d
the gamer thinks that it has something to do whit rebornstorage 2888 the same...no poblem when I got 2887on again.

**Comment by Faithcaio** [comment]
https://github.com/raoulvdberge/refinedstorage/blob/18b4fbe358ba12e9ece3642d6a405859169ffd27/src/main/java/com/raoulvdberge/refinedstorage/container/ContainerGrid.java#L44
Somehow we don't find the craftmatrix in the correct place?

**Comment by phit** [comment]
well it broke in build 2888 which is https://github.com/SpongePowered/SpongeForge/commit/d946afc934d5611f298102ff115f117e08ff2174

**Comment by mihionmc** [comment]
I don't know if it is important but this one is on 2887:
https://gist.github.com/mihionmc/16821e30f1ef29558454206d2b63fb84

**Comment by Faithcaio** [comment]
fixed in https://github.com/SpongePowered/SpongeCommon/commit/4802b6e3e36d20f4c44bc25ad0beef54f0dbb4e8
