### ISSUE TITLE
Pre-generation crash with a mod 

### ISSUE THREAD

**Issue by JoeSGT** [SpongePowered/SpongeForge#1990]
**I am currently running**

- SpongeForge version: 1.12.2-2586-7.1.0-BETA-2889
- Forge version:  14.23.1.2606 
- Java version:  8
- Operating System: linux

- Plugins/Mods:
both mods and plugin list are included in the crash report

**Issue Description**
Crash report: https://pastebin.com/8RuBCZi3 remapped: https://pastebin.com/mD0B2nmh

i had ask the mod developer of Lost Thaumaturgy  this his side of this issue he said it's Sponge issue not his, basically what i did was every time i pre-generate the nether using nucleus pre-generation it crashes whenever it get's to about 5%, i disable spongeforge and all related sponge plugins and used forge pregeneration instead of spongeforge and nucleus it wont crash it's seem that it's a sponge issue

**Comment by ryantheleach** [comment]
This just looks like the server stalled out during generation due to taking too long to tick, but you say it doesn't happen without Sponge.

What plugins do you have installed? Do any of them have databases?

**Comment by JoeSGT** [comment]
the plugins i installed 
CustomRestartMessage 
Nucleus 
LuckPerms
crazyfeetsponge
Auctions
and i did not have any database all of those config have been default haven't edit them yet
and i ran nucleus pre-generation command `/world border gen` 
and wait around 5% and it crashed when i took out those sponge plugins and SpongeForge out and ran just forge pregeneration command since Forge Api have there own way of pregeneration that is what i used and it does not crash

**Comment by phit** [comment]
add sponge back and try pregenerating with the forge commands again

**Comment by JoeSGT** [comment]
@phit unfortunately i cannot do what you request because Sponge breaks forge api generate command
`/forge gen`

**Comment by phit** [comment]
log? it really shouldn't if it does that's a bug by itself

**Comment by JoeSGT** [comment]
Latest.log https://pastebin.com/DhUifJgp - as you can see i generate 10000000 chunks and you can see the time in them it should NOT take a 3 seconds for 10,000,000 Chunks 
Fml-Server-latest.log https://pastebin.com/ZSUhWx0Q
Fml-Junk-earlystartup.log https://gist.github.com/JoeSGT/db26f7f149cab42fcf7eade2b84c205c

i provided all of the different types of logs and here a screenshot of nothing in the region folder when i attempt to pregen in the nether world and i stopped the server once forge gen finished
https://gyazo.com/27417fc36af8dd1e2d8a82cfcd94aa19

**Comment by JoeSGT** [comment]
Just wondering is there any more information that is needed?

**Comment by ryantheleach** [comment]
I wonder if this is a chunk loading related issue with the world configs @phit , can't gen something that can't load correctly?

**Comment by JoeSGT** [comment]
well my world configs are default in fact i did all this on a clean test server

**Comment by phit** [comment]
@ryantheleach Indeed setting `deny-chunk-requests=false` fixes this..

moved this to https://github.com/SpongePowered/SpongeForge/issues/2003

---

@JoeSGT as for your initial report, can you retest pregenning with nucleus and set `deny-chunk-requests=false` before you do and see if it still freezes?

**Comment by JoeSGT** [comment]
Yeap it's fix this issue thanks
