### ISSUE TITLE
Crash when user go to void Nether (1.10.2)

### ISSUE THREAD

**Issue by mkrtes** [SpongePowered/SpongeForge#1993]
**I am currently running**
    Minecraft: 1.10.2
    SpongeAPI: 5.2.0-SNAPSHOT-c675e80
    SpongeForge: 1.10.2-2477-5.2.0-BETA-2790
    Minecraft Forge: 12.18.3.2511
- Operating System: Debian

Crashlog https://gist.github.com/mkrtes/2fcc473a6c3d80eb9c1c8b2972ee2b9d

- Plugins/Mods: Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, Not Enough Items, OpenComputers (Core), SpongeAPI, SpongeForge, FoamFixCore, ccl-entityhook, Fence Overhaul, Actually Additions, CodeChicken Lib, CodeChicken Core, EnderStorage, Just Enough Items, OpenComputers, ActuallyComputers, Baubles, Extra Utilities 2, AngelRing 2 Bauble, AppleCore, apple_shields, AppleSkin, AutoPackager, Psi, AutoRegLib, Baconators, CraftTweaker JEI Support, MineTweaker 3, B.A.S.E, BD Lib, Better Builder's Wands, BiomeTweaker, BlockDispenser, Guide-API, Blood Magic: Alchemical Wizardry, Bookshelf, Botania, Brandon's Core, Mantle, Tinkers' Construct, Ceramics, Chameleon, Chance Cubes, MCMultiPart, ‽, |, /, Chest Transporter, ChickenChunks, Chickens, Clumps, Cyclops Core, Colossal Chests, CommonCapabilities, Cooking for Blockheads, Waila, Dark Utilities, Dimensional Cake, Draconic Evolution, Dragon Mounts, Elevator Mod, EnderCore, Ender IO, Energy Converters, Engineer's Workshop, Valkyrie Lib, Environmental Tech, ET Lunar, Ex Nihilo Adscensio, Ex Compressum, Zero CORE, Extreme Reactors, Farming for Blockheads,  FastAsyncWorldEdit, WorldEdit, Flat Colored Blocks, SonarCore, FluxNetworks, FoamFix, Shadowfacts' Forgelin, ShadowMC, Funnels, Garden of Glass, Advanced Generators, Gravestone Mod, GriefPrevention, Grue, Get Ya' Tanks Here, Hammer Core, Hatchery, Hopper Ducts, HydroGel, Immersive Engineering, Integrated Dynamics, Integrated Tunnels, Iron Backpacks, Iron Chest, It's Raining Food, KleeSlabs, LLibrary, Long Fall Boots, Loot Bags, LuckPerms, LunatriusCore, MiniCoal, Natura, Random Things, Roots, MoarSigns, mob_grinding_utils, MTLib, Mod Tweaker, Storage Drawers, Refined Storage, More Chickens, More Shearables, More Shears, Morpheus, Mystical Agriculture, Nice, Not Enough Wands, Nucleus, OreExcavation, Pam's HarvestCraft, ShetiPhian-Core, Platforms, RebornCore, QuantumStorage, Ranged Pumps, reborncore-MCMultiPart, RebornStorage, Redstone Paste, Reliquia, RFTools, RFTools Control, RFTools Dimensions, Simple Achievements, Simple Corn, Simple Generators, SimpleLabels, Simply Jetpacks 2, SkyClaims, Snad, Solar Flux Reborn, Steve's Carts 2, Super Circuit Maker, The Beneath, Tinkers Tool Leveling, Tiny Progressions, TorchMaster, Translocator, Twerk-Sim 2K16, voidcup, WanionLib, I Can See Everything, What Are We Looking At, Experience Rings, YUNoMakeGoodMap, AdminShop, AutoBroadcaster, ClearMob, EconomyLite, PlaceholderAPI, VirtualChest, UniDict

**Issue Description**
Crash when user go to Nether. Nether generated with YUNoMakeGoodMap, void. SkyFactory-style.

Crashlog https://gist.github.com/mkrtes/2fcc473a6c3d80eb9c1c8b2972ee2b9d

**Comment by phit** [comment]
1.10.2 and 1.11.2 are not longer supported. If a sufficiently, decent, and tested Pull Request is made to fix this bug/issue, it will still be considered, however, it is NOT to be expected that any bug fixes made for 1.12.2 will be back ported to 1.11.2 or 1.10.2.

If you can reproduce this issue with SpongeForge on Minecraft 1.12.2 and this issue was wrongly closed, please [open a new issue](https://github.com/SpongePowered/SpongeForge/issues/new) with updated information.

---

downgrading to 5.2.0-BETA-2788 should avoid this crash though
