### ISSUE TITLE
Client not booting with just forge

### ISSUE THREAD

**Issue by LemADEC** [SpongePowered/SpongeForge#1994]
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2586-7.1.0-BETA-2897
- Forge version: 14.23.1.2586
- Java version: 1.8.0_92
- Operating System: Windows 10

- Plugins/Mods: just Forge and Sponge

**Issue Description**
Client won't boot due to mixin issue 

https://gist.github.com/LemADEC/41b06906d8bbab48df10568bdbcf9005

**Comment by Dockter** [comment]
Issue confirmed.

**Comment by Dockter** [comment]
Fixed.
