### ISSUE TITLE
Duplication of buckets

### ISSUE THREAD

**Issue by Krosta8** [SpongePowered/SpongeForge#1998]
**I am currently running**
- SpongeForge version: 1.12.2-2586-7.1.0-BETA-2899
- Forge version: 14.23.1.2586
- Java version: 1.8.0_101
- Operating System: Linux

- Plugins/Mods:
Plugins (26): Minecraft, Minecraft Coder Pack, Sponge API, SpongeForge, FastAsyncWorldEdit, BungeeTabListPlus-SpongeBridge, CatClearLag, CmdBuilder, CmdControl, CommandUtils, DailyRewards, GriefPrevention, LuckPerms, Nucleus, Pixel Announcer, PlaceHolderAPI, ProjectCore, ProjectPortals, Total Economy, UltimateChat, VirtualChest, WorldEdit
Mods (28): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AGP, BetterQuesting, CraftTweaker2, CreativeCore, IronChest, JourneyMap, JEI, LittleTiles, Malisis Advert, Malisis Doors, Malisis Core, Mantle, ModControl, MrCrayFish Furniture Mod, NetherPortalFix, Pixel Extras, Pixelmon, Tinker's Construct, WonderTrade

**Issue Description**
If the player has more than one bucket in a stack and doesn't have permission for block-break, the player get message, that he doesn't have permission to build there and get water bucket.
This issue is with everything, that can be filled to bucket (water, lava...).
I report this to GriefPrevention and I got information, that it is a SpongeForge bug.

https://gist.github.com/Krosta8/e00ed9baeec37ac125a65e8f3ba1b02f

**Comment by RedNesto** [comment]
I can also reproduce in SpongeVanilla stable-7 and bleeding.

I'll see what I can do.

**Comment by phit** [comment]
~move to sc

**Comment by limbo-app** [comment]
Hey @Krosta8! I've moved your issue to [SpongePowered/SpongeCommon#1794](https://github.com/SpongePowered/SpongeCommon/issues/1794).
