### ISSUE TITLE
Astralsourcery mantle don't work

### ISSUE THREAD

**Issue by ilFau** [SpongePowered/SpongeForge#2001]
**I am currently running**

- SpongeForge version: 7.1.0-BETA-2900.jar
- Forge version: 2586
- Java version: 8 (1.8.0_151-8u151)
- Operating System: ubuntu server

- Plugins(0)/Mods(1):
AstralSourcery

**Issue Description**
The Mantle of Star attuned with Vicio, is a plate of Astral Sourcery which allow to flight like Elytra. But with sponge it doesn't work. The player, instead of planar, pressing space will have epileptic seizures, like when you press shift repeatedly. It's pretty funny but... 

I try to disable all module and all "control" of sponge but no happened.
If you want try in creative rember the command /astralsourcery maximize <player> or the mantle doesn't work at all

nothing report on console

**Comment by ilFau** [comment]
This problem still occurs in the new sponge version 7.1.0-BETA-2906 for forge 2611

**Comment by Aaron1011** [comment]
This is a problem with how AstralSorcery's class transformer works. I've opened an issue on the project: https://github.com/HellFirePvP/AstralSorcery/issues/644

**Comment by phit** [comment]
https://github.com/HellFirePvP/AstralSorcery/commit/7a0e16406690b136df04407f2055cccaea60127f
