### ISSUE TITLE
ServerChatEvent.setCanceled has no effect 

### ISSUE THREAD

**Issue by SquidDev** [SpongePowered/SpongeForge#2002]
### I am currently running
- SpongeForge version: 1.12.2-2611-7.1.0-BETA-2906
- Forge version: 1.12.2-14.23.2.2613
- Java version: 1.8.0_151-b12
- Operating System: Windows 
- Plugins/Mods: LuckPerms, CC: Tweaked, Plethora.

### Issue description
Cancelling Forge's `ServerChatEvent` event does not result in the equivalent `MessageEvent` being cancelled. I realise this was marked fixed in #1263, so I'm not entirely sure why it's regressed (or if I'm just doing something stupid).

### To reproduce:
Register the following event handler:
```java
@SubscribeEvent
public void onServerChat(ServerChatEvent event) {
	System.out.println("Got message " + event.getMessage());
	if(event.getMessage().contains("test")) {
		System.out.println("Cancelled!");
		event.setCanceled(true);
		return;
	}
}
```
Observe the following output:
```
[09:50:40] [Server thread/INFO] [STDOUT]: [...:onServerChat:38]: Got message test
[09:50:40] [Server thread/INFO] [STDOUT]: [...:onServerChat:40]: Cancelled!
[09:50:40] [Server thread/INFO]: <SquidDev> test
```

I've uploaded the [various server logs here](https://gist.github.com/SquidDev/b3c6265b983c81c622c223e8334f9407).

**Comment by SquidDev** [comment]
Amazing, thank you!

**Comment by Lemmmy** [comment]
This issue appears to have resurfaced in SpongeForge 3308 (works fine in 3307, still doesn't work in 3323). When a Forge mod cancels ServerChatEvent, the message is still sent in public chat (and if Nucleus is installed, it is handled by that). The reproduction case shown in the original post still works:

```
[08:44:49] [Server thread/INFO] [STDOUT]: [...:onServerChat:279]: Got message test
[08:44:49] [Server thread/INFO] [STDOUT]: [...:onServerChat:281]: Cancelled!
[08:44:49] [Server thread/INFO]: <§rLemmmy§r> §rtest§r
```

**Comment by SquidDev** [comment]
Thank you!
