### ISSUE TITLE
Futurepack - Cannot get property PropertyBool

### ISSUE THREAD

**Issue by ProsperCraft** [SpongePowered/SpongeForge#2005]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2611-7.1.0-BETA-2911
- Forge version: 2613
- Java version: java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
- Operating System:Windows 10 64 bit - running Sponge on my client.

- Plugins/Mods: Its in the crash report.

**Issue Description**
I have been playing and testing my modpack for weeks without this crash, and Futurepack has not updated recently.  I added sponge to my client, and within minutes had this crash, then restarted, and it happened again.

https://gist.github.com/ProsperCraft/480145e2da33e3f0a31e05804b3dde17

Reproduced.

https://gist.github.com/ProsperCraft/a7d253bf789a9b913a733c589328de45

Client logs attached.
[2018-02-11-3.log.gz](https://github.com/SpongePowered/SpongeForge/files/1714721/2018-02-11-3.log.gz)

This is my modpack that it happened with - https://minecraft.curseforge.com/projects/towncraft

**Comment by phit** [comment]
how do you reproduce this, were you far away from that door?

**Comment by mcenderdragon** [comment]
This crash is caused because the tileEntiy is there but not the block.

**Comment by phit** [comment]
@ProsperCraft try setting `deny-chunk-requests=false` in your `config/sponge/global.conf`

**Comment by ProsperCraft** [comment]
I was not by the door, about 50 blocks away or so.
I didn’t have to do anything but log in to make its happen.  If you want to reproduce this you would place three of those doors that raise up then add sponge to your client.

**Comment by bloodmc** [comment]
@ProsperCraft Can this be reproduced on latest SF? I fixed a recent issue that caused TE's to be created with SpongeBlockSnapshot's.

**Comment by ProsperCraft** [comment]
I am now unable to reproduce, good work :)

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/SpongePowered/SpongeCommon/commit/dae4226283882e83d19a55ceaae9156486859720
