### ISSUE TITLE
Exception occurred during a PhaseState

### ISSUE THREAD

**Issue by Siriuo** [SpongePowered/SpongeForge#2008]
**I am currently running**
- SpongeForge version: 1.12.2-2611-7.1.0-BETA-2916
- Forge version: 1.12.2-14.23.2.2611
- Java version: 1.8.0_161 64-bit
- Operating System: Centos 6.9

**Plugins:** Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, Buycraft, LuckPerms, Nucleus

**Mods:** Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AE2 Stuff, Actually Additions, Advanced Generators, Advanced Rocketry, Advanced Rocketry Core, Akashic Tome, Alternating Flux, AngelRing 2 Bauble, Animania, AppleSkin, Applied Energistics 2, ArchitectureCraft, Aroma1997's Dimensional World, Aroma1997Core, Astral Sorcery, AutoRegLib, BC Builders, BC Energy, BC Factory, BC Robotics, BC Silicon, BC Transport, BD Lib, Baubles, Baubley Heart Canisters, Better Agriculture, Better Builder's Wands, Bookshelf, Botania, BuildCraft, BuildCraft Lib, Chameleon, Chest Transporter, Chisel, Chisels & Bits, CoFH Core, CoFH World, CodeChicken Lib, CommonCapabilities, Compact Machines 3, ComputerCraft, CraftStudio API, CraftTweaker JEI Support, CraftTweaker2, Cyclic, Cyclops Core, Dark Utilities, Dynamic Surroundings, ET Lunar, EluCore, EluLib, Ender Utilities, Ender Zoo, EnderStorage, EnderTanks, Environmental Tech, Exchangers, Extra Cells 2, Extra Utilities 2, Extreme Reactors, FTBLib, FTBUtilities, Fancy Fluid Storage, Fast Leaf Decay, Flux Networks, FoamFix, FoamFixCore, Forestry, GenDustry, Gravestone Mod, Hammer Core, Immersive Cables, Immersive Engineering, Immersive Petroleum, Immersive Tech, ImmersiveRailroading, Industrial Foregoing, Industrial Wires, Integrated Dynamics, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTunnels-Compat, Integration Foregoing, Inventory Tweaks, Iron Chest, IvToolkit, JourneyMap, Just Enough HarvestCraft, Just Enough Items, MTLib, Mantle, Mekanism, MekanismGenerators, MekanismTools, Mod Tweaker, Morph-o-Tool, Morpheus, NHAVE's Core, Natura, Nature's Compass, NetherPortalFix, NoMoreRecipeConflict, NotEnoughIDs, NuclearCraft, OMLib, Open Modular Passive Defense, Open Modular Turrets, OpenBlocks, OpenModsLib, OpenModsLib Core, Pam's HarvestCraft, Platforms, Plethora, Plethora Core, PlusTiC, Pressure Pipes, QuantumStorage, Quark, RF Lux, RFTools, RFTools Control, Random Things, RandomPatches, Ranged Pumps, Reborn Core, Redstone Arsenal, Redstone Flux, Shadowfacts' Forgelin, ShetiPhian-Core, Silent Lib, Silent's Gems, Silent's Gems: Extra Parts, SimpleVoidWorld, Simply Jetpacks 2, Solar Flux Reborn, SonarCore, Storage Drawers, Storage Drawers Extras, TOP Addons, Tesla Core Lib, Tesla Core Lib Registries, The Beneath, The One Probe, The One Wrench, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Tinker I/O, Tinkers Tool Leveling, Tinkers' Construct, TorchMaster, Track API, UniDict, Universal Remote, Unlimited Chisel Works, Valkyrie Lib, Vulpes library, WanionLib, Wireless Crafting Terminal 2, XNet, Xtones, Zero CORE, mob_grinding_utils, p455w0rd's Library

**Issue Description**

Hi,

The console is repeating the message found at https://pastebin.com/EqKjy2t3

This seems to happen when the player logs in and loads the chunk where a Extra Utils Quary is placed.

**Comment by phit** [comment]
https://github.com/SpongePowered/SpongeForge/issues/1961#issuecomment-364134079
