### ISSUE TITLE
Server crashing after using new SpongeForge file

### ISSUE THREAD

**Issue by wpmidia** [SpongePowered/SpongeForge#2009]
Everytime server crashing... I don't understand the error log.

**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2611-7.1.0-BETA-2916.jar
- Forge version: 2611
- Java version: java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
- Operating System: Linux CentOS

- Plugins/Mods:

**Issue Description**

Crash-report: https://gist.github.com/wpmidia/562136449388229e7f639cebee08a491

**Comment by dualspiral** [comment]
Not a Sponge error. This is caused by Nucleus requesting a permission and LuckPerms waiting for a check to complete:

https://gist.github.com/wpmidia/562136449388229e7f639cebee08a491#file-crash-2018-02-15_10-00-23-server-txt-L84-L111
https://gist.github.com/wpmidia/562136449388229e7f639cebee08a491#file-crash-2018-02-15_10-00-23-server-txt-L153-L166

I'd report this to LuckPerms as the block is on that.

**Comment by phit** [comment]
@dualspiral probably not even that, its a watchdog crash.. could be literally anything else freezing the server this just happened to be the stack trace it chose to spit out

**Comment by dualspiral** [comment]
Normally I’d agree, but considering that the thread was blocked on a CompleteableFuture#get(), it means that main thread was waiting for the permission to come back. It might be a deadlock on LPs end looking at the trace, can’t be sure, but if it’s happening everytime then I’d be more inclined to think there is some strange locking going on.

Of course, it could be the server running out of memory during a permission check. Either way, this isn’t a Sponge issue.

**Comment by wpmidia** [comment]
So .... what I should do? 
No updates for LuckPerms.
I just downloaded a newer version of Nucleus...

Thanks guys! ♥

**Comment by ryantheleach** [comment]
The database or something probably went down during a check, I'm not sure how LP handles it, but I would expect it to fail more gracefully then this.

**Comment by wpmidia** [comment]
The problem continues. The server is crashing all the time. I do not know what else to do. Please help me!
https://gist.github.com/wpmidia/4565a40fe9a7d0683a23e9f0962d2af5

**Comment by ryantheleach** [comment]
@wpmidia Is luck perms using a database? You may find luck perms specific help in their discord: https://discord.gg/W3FzxHA but chances are it's just a connection problem between your server and your database.

If they arn't being hosted within the same cloud hosting provider / datacentre / bedroom I'd recommend doing that.

**Comment by wpmidia** [comment]
No, it doen't use database, as MySQl, etc...
But is OK. I'll keep looking for a solution to my problem.

Thanks.
