### ISSUE TITLE
Add JLine support

### ISSUE THREAD

**Issue by halvors** [SpongePowered/SpongeForge#201]
It would be really nice to add JLine support, kinda like CraftBukkit had. The minecraft console is really messy, and this would solve the log messages that interfer with your commands by threading this.

**Comment by halvors** [comment]
Will this be added to the Sponge implementation as 
well?

**Comment by Minecrell** [comment]
@halvors Unfortunately adding it to Sponge is more complicated because we have no direct control about the log4j2 configuration. That makes implementing it without a lot of hacks pretty much impossible.

**Comment by progwml6** [comment]
there are ways around that iirc @Minecrell i need to see if i can track down some code one mod dev uses to hijack log4j2

**Comment by halvors** [comment]
Any progress on this? MixinDedicatedServer.java and MixinMinecraftServer is now implemented in Sponge...

**Comment by Zidane** [comment]
@Minecrell has made a PR for the sister project Vanilla to have this capability and it seems to work well for everything but IntelliJ.

Once he fixes this, we'll look at bringing this over to Forge (or, better, place it in Common).

**Comment by Zidane** [comment]
Want to keep this open as a reminder to bring this up to Forge for Sponge.

**Comment by Minecrell** [comment]
@Zidane Oh, GitHub closed this automatically because I referenced it in the PR which was closed. :P

**Comment by Zidane** [comment]
I'm aware.

**Comment by hunter688** [comment]
Any progress? Console without tab completion, history is very bad.

**Comment by hunter688** [comment]
Tested SpongeVanilla - console works like old bukkit/spigot. Please add to Sponge too. Or will be better add to forge server?

**Comment by bloodmc** [comment]
@Minecrell  I spoke with Lex and he is fine with this being added to Forge. Can you start working on a PR for them?

**Comment by DevPlayer-** [comment]
Instead of or in addition to "colorizing" or modifying the "console" tab, perhaps a new tab to the launchers notebook, where the mod can log to that tab or some other window instead. Ideally designed where logging objects dictate target object, yet allowing the launcher to decide to create a tab or not. I couldn't find any deobfusicated classes for the launcher tabs. I did notice that a new tab in the launcher is created on certain crashes.

**Comment by Zidane** [comment]
@DevPlayer- 

https://www.java.com/en/download/faq/winxp.xml

Java 8 will still run on XP but you should really update :P.

**Comment by ryantheleach** [comment]
I didn't think sponge or forge had any control over the launcher whatsoever?

**Comment by hunter688** [comment]
I think DevPlayer-'s comment is offtopic.

**Comment by MRebhan** [comment]
I think he's talking about the GUI

**Comment by JBYoshi** [comment]
@DevPlayer- Sponge cannot control the launcher tabs. The code to create a new tab during crashes is controlled by the launcher, and it cannot be modified (as in: no colors, no input, includes the "Report to Mojang" button, etc).

Also, you're talking about the Minecraft *client*, which has *no* console interaction. This is for the Minecraft *server*, which *does* have console interaction. Also, the server does not use the Minecraft launcher.

**Comment by kashike** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/321665efff16d558696803787df0859bb5f34a92 / https://github.com/MinecraftForge/MinecraftForge/commit/cf4c0ca0011026e74a0fe93396b4b8a036276f7d
