### ISSUE TITLE
Dupe bug with Compressed Cobblestone 

### ISSUE THREAD

**Issue by JoeSGT** [SpongePowered/SpongeForge#2010]
**I am currently running**

- SpongeForge version:  1.12.2-2611-7.1.0-BETA-2916 
- Forge version: 1.12.2-14.23.2.2615
- Java version: 8
- Operating System: linux

- Plugins/Mods:
Luckperms and GriefPrevention, Draconic Evolution, Extra Utilities.  

**Issue Description**
1) place down a Compressed Cobblestone 9.0 Blocks
2) go get a modded pickaxe like Draconic staff of power or a tinkers contrust pickaxe 
3) Use GriefPrevention to make a claim then place down Compressed Cobblestone in the claim
4) go into survival and break Compressed Cobblestone it wont break but it still drop the Compressed Cobblestone and you can have endless Compressed Cobblestone

This does not happen with vanilla pickaxes!

I tried using `/gpdebug`  and everything in the debug was true that i am suppose to break compressed cobblestone but it wont it just drop the compressed cobblestone without actually breaking the compressed cobblestone this is not a GriefPrevention issue.

**Comment by RedNesto** [comment]
Sounds like the same dupe as https://github.com/SpongePowered/SpongeCommon/issues/1796 I experimented with @jd1378

**Comment by phit** [comment]
probably also related to https://github.com/SpongePowered/SpongeForge/issues/1997

**Comment by phit** [comment]
gonna assume this was fixed in latest, if not let me know and I'll reopen the issue

**Comment by JoeSGT** [comment]
yeap it's fixed. just want to put it out there
