### ISSUE TITLE
NetherUtils respawning issues

### ISSUE THREAD

**Issue by Terrails** [SpongePowered/SpongeForge#2011]
**I am currently running**
- SpongeForge version: 1.12.2-2611-7.1.0-BETA-2916
- Forge version: 1.12.2-14.23.2.2611
- Java version: 1.8.0_161-b12
- Operating System: Windows 10 Pro x64

- Mods: CodeChickenLib, NetherUtils, TerraCore

**Issue Description**
Basically NetherUtils makes players spawn in the nether, currently if you join the server for the first time you get spawned in the nether but after your first death you get respawned in the overworld. I tried to see what could be the issue in the PlayerRespawnEvent but there isn't any issue with it on forge's side, so I'm certain to its sponge's fault cause this only happens when spongeforge is used. There aren't any errors in the log and I'm pretty sure to its not the method I'm using for teleporting cause it works in the PlayerLoggedInEvent (using PlayerList#transferPlayerToDimension), you can check it here if you want to:

[RespawnEvent](https://github.com/Terrails/NetherUtils/blob/1.12.x/src/main/java/terrails/netherutils/event/SpawnEvent.java#L30-L55)
[Teleporter](https://github.com/Terrails/NetherUtils/blob/1.12.x/src/main/java/terrails/netherutils/world/TeleporterNTF.java#L34-L57)
[Log](https://gist.github.com/Terrails/c4f8b1d27933360c3161ad1444417203)

**Comment by phit** [comment]
possibly related to
https://github.com/SpongePowered/SpongeForge/issues/1973
https://github.com/SpongePowered/SpongeCommon/pull/1759

**Comment by Terrails** [comment]
Found something, in the [fml-junk-earlystartup.log](https://gist.github.com/Terrails/a2bee34c7e8d22adc7a1df3e76e1fda5),
it prints out an error called "Unexpected World Change Detected!"
Updated to latest sponge too

**Comment by phit** [comment]
@Terrails can you please retest on latest (7.1.0-BETA-2990)? there were a few fixes related to this

**Comment by Terrails** [comment]
Still nothing, but this time the error was printed straight into the log/console. Also there's no stacktrace this time. [latest.log](https://gist.github.com/Terrails/214624cde2624561d23e56bd844fbc5c)

**Comment by ryantheleach** [comment]
Other tickets recently closed had the error message, "Unexpected World Change Detected!"

It may be worth revisiting this ticket.

**Comment by phit** [comment]
respawning seems fixed, seeing some new issue though, but I'll open a new one for that as this issue has been fixed

new issue https://github.com/SpongePowered/SpongeForge/issues/2271
