### ISSUE TITLE
Draconic Evolution Mobsoul allows infinite mob spawning

### ISSUE THREAD

**Issue by tolly765** [SpongePowered/SpongeForge#2012]
**I am currently running**

- SpongeForge version: 1.12.2-2586-7.1.0-BETA-2900
- Forge version: 14.23.1.2601
- Java version: Java 8.151.12-r0
- Operating System: Alpine

- Plugins/Mods:
Plugins:
Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, @name@, BetterChunkLoader, CBG Utils, CatClearLag, EconomyLite, Enjin Minecraft Plugin, GriefPrevention, Holograms, HuskyCrates, HuskyUI, KaisCommons, LuckPerms, MMCRestrict, Nucleus, Prism, SimpleHelpTickets, SpongePrometheusExporter, Votifier, auto message

Mods (Revelation FTB pack): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, /dank/null, AE2 Stuff, Actually Additions, Actually Baubles, Advanced Rocketry, Advanced Rocketry Core, Akashic Tome, AppleSkin, Applied Energistics 2, ArchitectureCraft, Aroma1997's Dimensional World, Aroma1997Core, Astral Sorcery, AutoRegLib, B.A.S.E, BD Lib, Bad Wither No Cookie! Reloaded, Baubles, Bed Patch, Better Advancements, Better Builder's Wands, BetterChunkLoader Forge Lib, BiblioCraft, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Blockcraftery, Bookshelf, Botania, Brandon's Core, Chameleon, Chest Transporter, Chisel, Chisels & Bits, Clumps, CoFH Core, CoFH World, CodeChicken Lib, Comforts, Compact Machines 3, Compact Solar Arrays, Compacter, Cooking for Blockheads, CraftTweaker JEI Support, CraftTweaker2, Dark Utilities, DeepResonance, Diet Hopper, Dirt2Path, Draconic Evolution, ET Lunar, ElecCore, Elevator Mod, EluCore, EluLib, Embers, EnderStorage, Engineer's Workshop Reborn, Environmental Tech, Exchangers, Extra Cells 2, Extra Utilities 2, Extreme Reactors, FTBLib, Fence Jumper, Flat Colored Blocks, Flux Networks, FoamFix, Forestry, Gadgetry: Core, Gadgetry: Machines, GenDustry, Gravestone Mod, Guide-API, Immersive Engineering, Immersive Petroleum, Industrial Foregoing, IndustrialCraft 2, Iron Backpacks, Iron Chest, JEI Bees, JourneyMap, Just Enough HarvestCraft, Just Enough Items, KleeSlabs, Long Fall Boots, MCMultiPart, MTLib, MagicBees, MalisisCore, MalisisDoors, Mantle, MineTogether, MineTogetherServer, Mod Tweaker, Morph-o-Tool, Morpheus, Natura, Nature's Compass, NetherPortalFix, Nice, Not Enough Wands, NotEnoughIDs, NuclearCraft, OpenComputers, OpenComputers (Core), Pam's HarvestCraft, Placebo, Platforms, Quark, Quick Leaf Decay, RFTools, RFTools Control, Ranged Pumps, Reborn Core, Redstone Arsenal, Redstone Flux, Reliquary, Roots 2, Rustic, Secret Rooms 5, Shadowfacts' Forgelin, ShetiPhian-Core, Signals, SimpleVoidWorld, Snad, SonarCore, Soul Shards - The Old Ways, Steve's Carts 2, Storage Drawers, Storage Drawers Extras, TOP Addons, Tesla Core Lib, Tesla Core Lib Registries, The Lost Cities, The One Probe, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thut Core, Thut's Tech, ThutCore Compat, TickProfiler, Tinkers Tool Leveling, Tinkers' Construct, TorchMaster, Traverse, UniDict, Valkyrie Lib, Vulpes library, WanionLib, Waystones, Whoosh, Wireless Crafting Terminal 2, WorldEdit, XNet, Xtones, YABBA, Zero CORE, careerbees, mob_grinding_utils, p455w0rd's Library

**Issue Description**
With Draconic Evolution, if you take a mob soul that can be used to make a spawner and shift click it onto the floor, it should take the soul away and spawn the mob in question. However, with SpongeForge installed it doesn't take the soul away and spawns the mob. This means that you can spawn a certain mob infinitely.
This has been tested with and without SpongeForge as well as with just DE (and it's prerequisites) and on the FTB Revelations pack, and in both cases the issue only presented itself with Sponge installed.

**Comment by phit** [comment]
https://github.com/brandon3055/Draconic-Evolution/blob/f5789462962897ef195147f6a8f53cd46076e099/src/main/java/com/brandon3055/draconicevolution/items/MobSoul.java#L66

https://github.com/brandon3055/BrandonsCore/blob/d5514ae6b7f4a826d2d27d4a8a05f65c0efec5eb/src/main/java/com/brandon3055/brandonscore/utils/InventoryUtils.java#L89

actually can you retest with latest when you get a chance, just to make sure it wasn't fixed

**Comment by tolly765** [comment]
Sorry for the late reply, but I just tested it on sponge version 1.12.2-2611-8.0.0-BETA-2921 (latest as of this post) and the issue is still present.

**Comment by phit** [comment]
quicker than any of us here, thanks for checking!

**Comment by phit** [comment]
still an issue with
BrandonsCore-1.12.2-2.4.3.168-universal.jar
Draconic-Evolution-1.12.2-2.3.12.297-universal.jar
spongeforge-1.12.2-2705-7.1.0-BETA-3253.jar

**Comment by phit** [comment]
was probably fixed with the interaction rework a while ago, works fine with 
spongeforge-1.12.2-2768-7.1.6-RC3586.jar
CodeChickenLib-1.12.2-3.2.2.353-universal.jar
Draconic-Evolution-1.12.2-2.3.20.333-universal.jar
RedstoneFlux-1.12-2.1.0.6-universal.jar
BrandonsCore-1.12.2-2.4.9.195-universal.jar
