### ISSUE TITLE
Console Spam with errors

### ISSUE THREAD

**Issue by JoeSGT** [SpongePowered/SpongeForge#2013]
**I am currently running**

- SpongeForge version:  1.12.2-2611-7.1.0-BETA-2925
- Forge version: 1.12.2-14.23.2.2615
- Java version:  8
- Operating System: linux

- Plugins/Mods:
https://gist.github.com/JoeSGT/5ce09462999de2913cf00a12c21309a7
 

**Issue Description**
I'm not too sure how to reproduce this spam but my console keep spamming with those errors 
https://gist.github.com/JoeSGT/0ae66d66bc4cbb39e7f6b1f57d2b7751

**Comment by gabizou** [comment]
Can you enable stack trace in the cause tracker section so we can get some printouts of where the generation state is coming from?

**Comment by JoeSGT** [comment]
https://gist.github.com/JoeSGT/0a74a82902c5bae45de2e108d59ab6ee
I'm not sure if i did it right. If i did do it wrong can be more specific on what config option because i kind of guess it xD

**Comment by Zidane** [comment]
Looks like AdvancedRockery is loading chunks off the main thread.

@gabizou Don't think this is our issue

**Comment by JoeSGT** [comment]
if it's not sponge issue then
@zmaster587 mind taking a look please?

**Comment by CyberSpongie** [comment]
Getting the same issue, odd i can't seem to find what the cause of it.

**Comment by gabizou** [comment]
@Zidane appears to be correct. On a cursory glance at the error log, chunks are being loaded off thread. While I could do some thread checks on entrance and closures for the PhaseTracker, I'm not keen on it being fast enough to do that.

**Comment by JoeSGT** [comment]
So this is Not a sponge issue but a mod issue?
I though chunk that run off the main thread is fine cause of forge

**Comment by JoeSGT** [comment]
@gabizou  https://gist.github.com/JoeSGT/1b87232565ad9024b4a3cb9d4611faed
my logs got to 5GB and had to force shut my server down because of it
are you sure it's not a sponge issue?

**Comment by gabizou** [comment]
@JoeSGT Sponge is emitting errors because things are being called off thread. Yes, sponge is bringing it up as an issue, but sponge is not *causing* the issue that stuff is being done off thread. It's also not helping that the error log is reformatted from what it's supposed to look like (spacing is all over the place), did you copy it from a log file or from console?

**Comment by JoeSGT** [comment]
Oops i did copy straight out of the console, my console have double space because of the Daemon but i have took the time to reformat it for you 
https://gist.github.com/JoeSGT/1b87232565ad9024b4a3cb9d4611faed

If it indeed a mod issue should i go report it over to them ?

**Comment by gabizou** [comment]
The rest of the log from two days ago though is not well formatted, the phase tracker bit at the top is not making as much sense as possibly the lower bits of the log.

**Comment by JoeSGT** [comment]
Sorry Gabizou but this happen so random, at a point my logs was over 5GB i had to get rid of it
i don't know how to reduce it, but do you have any idea on what it could be so i can try to reduce the issue and give you more information

**Comment by JoeSGT** [comment]
You can close this, like mention above it happen random very hard to keep track, if this happen again i will get a  way to reduce it and more information
