### ISSUE TITLE
Blocks don't get dropped when being broken by Psi Guns / TiC Lumberaxe

### ISSUE THREAD

**Issue by limbo-app** [SpongePowered/SpongeForge#2015]
This issue was originally submitted by @mihionmc in [SpongePowered/SpongeCommon#1804](https://github.com/SpongePowered/SpongeCommon/issues/1804).
___
**I am currently running** FTB Direwolf20 B  FTBPresentsDirewolf20112-1.12.2-1.8.0-Server.zip

- SpongeForge version:  1.12.2-2611-7.1.0-BETA-2925
- SpongeVanilla version: 
- Java version: Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
- Operating System: linux 

- Plugins/Mods: Psi-r1.1-59.jar, Tinkers’ Construct Mod 1.12.2

**Issue Description**

Blocks  don't get dropped again when being broken by Psi Guns/Lumber Axes on the latest upd on direwolf. 1.12.2-2611-7.1.0-BETA-2911 is the last working version

**Comment by phit** [comment]
to quote @Krosta8

>Problem is with mod item drop. Example: In mod Pixelmon are Berries (example: pixelmon:starf_berry), if you want to collect them, you need to right click on them. Berries just disappear without any drop.
Another example with mod Tinker's Construct and Lumberaxe. When player use lumberaxe (like regular axe, but with ability to cut a whole tree) to cut a tree, tree just disappear without any drop (regular axe works).
I tried to every build from newest to oldest till working one. Last working build for this is 1.12.2-2611-7.1.0-BETA-2916.
>
> Should be not necessary, but here is fml-junk-earlystartup.log: https://gist.github.com/Krosta8/bbf825370bf063f3878b967fa6a7ec1d

**Comment by Pythonic-Rainbow** [comment]
I remember once I break a jungle log with TiC Lumberaxe, the block didnt break but stacks of logs flew around of the tree,it is a log generator lol and the server crashed

not quite related with this issue though XD

**Comment by johnfriedrich** [comment]
Happening since this common commit as far as I know
https://github.com/SpongePowered/SpongeCommon/commit/b847918855d05ad3c7563ff8f30592ffeb2cef6e
