### ISSUE TITLE
 Using a sword in creative mode will destroy the block

### ISSUE THREAD

**Issue by james58899** [SpongePowered/SpongeForge#2017]
**I am currently running**

- SpongeForge version: 1.12.2-2611-7.1.0-BETA-2927
- Forge version: 14.23.2.2611
- Java version: 1.8.0_144
- Operating System: Linux

- Plugins/Mods: sponge only

**Issue Description**
Using a sword in creative mode will destroy the block
![minecraft-2018-02-19_12 41 44](https://user-images.githubusercontent.com/5798637/36363045-b776b8e6-1574-11e8-8f9d-296667ad8b64.gif)

**Comment by phit** [comment]
confirmed, doesn't even make a sound when you break a block with a sword equipped
