### ISSUE TITLE
Compact Machine 3 Dimensions : Mobs won't die

### ISSUE THREAD

**Issue by QAngelusQ** [SpongePowered/SpongeForge#2018]
**I am currently running**

- SpongeForge version: 1.12.2-2611-7.1.0-BETA-2927
- Forge version: 1.12.2-14.23.2.2611
- Java version: 1.8.0_161
- Operating System: Windows 10

- Plugins/Mods: Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AI Improvements, Actually Additions, Advanced Mortars, Animania, AppleCore, Applied Energistics 2, ArmoreableMobs, Artisan Worktables, Athenaeum, Attribute Fix, AutoRegLib, Avaritia, Avaritia Tweaks, B.A.S.E, BC Builders, BC Energy, BC Factory, BC Robotics, BC Silicon, BC Transport, BD Lib, Baubles, Better Questing, BiblioCraft, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Biomes O' Plenty, Blood Debug, Bookshelf, Botania, Brandon's Core, BuildCraft, BuildCraft Lib, CXLibrary, Carry On, Chameleon, Chance Cubes, Chisel, Chisels & Bits, Chunk Pregenerator, Clay Soldiers Mod, CoFH Core, CoFH World, CodeChicken Lib, Colossal Chests, Compact Machines 3, Construct's Armory, ContentTweaker, Cooking for Blockheads, Corail Pillar, Corail Pillar - Biomes O'Plenty Extension, Corail Pillar - Chisel Extension, Corail Pillar - Forestry Extension, Corail Pillar - Quark Extension, CosmeticArmorReworked, CraftStudio API, CraftTweaker JEI Support, CraftTweaker2, Cravings, CreativeCore, CreativeCoreDummy, Cucumber, CustomNPCs, Cyclops Core, Dark Utilities, DebugServerInfo, Decocraft, Dimension Rules, DrCyano's Lootable Bodies, Draconic Evolution, Dropt, ET Lunar, EnderStorage, EnderTanks, Engineer's Workshop Reborn, Environmental Tech, Epic Siege Mod, Ex Compressum, Ex Nihilo Creatio, Extended Crafting, Extra Alchemy, Extra Cells 2, Extra Utilities 2, Extreme Reactors, Fence Overhaul, FoamFix, FoamFixCore, Foamflower, Forestry, Funky Locomotion, Game Stages, GenDustry, GeneralLaymansAestheticSpyingScreen, Grappling hook mod, GravityGun, Guidebook, Hammer Core, Hardcore Questing Mode, HideNames, Hunger Overhaul, Ice and Fire, Immersive Engineering, Immersive Petroleum, Immersive Tech, In-game NBTEdit - Pokecube Edition, InControl, Industrial Foregoing, IndustrialCraft 2, Integration Foregoing, Interaction Wheel, Inventory Pets, Iron Chest, Iron Tank, Item Stages, IvToolkit, JEI Bees, Just Enough HarvestCraft, Just Enough Items, LLibrary, LittleTiles, LittleTilesCore, Loading Profiler, Loot Bags, Loot Table Tweaker, Lore Expansion, Lycanites Arctic Mobs, Lycanites Demon Mobs, Lycanites Desert Mobs, Lycanites Elemental Mobs, Lycanites Forest Mobs, Lycanites Freshwater Mobs, Lycanites Inferno Mobs, Lycanites Jungle Mobs, Lycanites Mobs, Lycanites Mountain Mobs, Lycanites Plains Mobs, Lycanites Saltwater Mobs, Lycanites Shadow Mobs, Lycanites Swamp Mobs, MTLib, MagicBees, Magical Psi, Mantle, Mekanism, MekanismGenerators, Metamorph, MineMenu, MmmMmmMmmMmm, Moar Boats, Mod Tweaker, More Furnaces, Morph-o-Tool, Mystical Agriculture, NetherPortalFix, Not Enough Wands, NotEnoughIDs, NuclearCraft, Nutrition, OpenBlocks, OpenComputers, OpenComputers (Core), OpenModsLib, OpenModsLib Core, Pam's Get all the Seeds!, Pam's HarvestCraft, PiTweaks, Ping, Placebo, Plants, Platforms, Pokecube Compat, Pokecube Model Loader, Pokecube Movess, Pokecube Origin, Pokecube Server Utils, Pok�cube Core, Pok�cube Mobs, Pok�cube Revival, PortalGun, Potion Fingers, ProjectE, Psi, Quark, RF Lux, RFTools, RFTools Control, RFTools Dimensions, Random Things, Realistic Item Drops, Reborn Core, RecipeStages, Recurrent Complex, Redstone Arsenal, Redstone Flux, SanAndreasPs Mod Library, SanAndreasPs Player Model, Scaling Health, Scannable, Scavenge, Secret Rooms 5, ServerSync, Shadowfacts' Forgelin, ShetiPhian-Core, Silent Lib, Simply Jetpacks 2, Solar Flux Reborn, Soul Shards - The Old Ways, Spartan Shields, Standard Expansion, Steve's Carts 2, Storage Drawers, Storage Drawers Extras, Sync, Techguns, Techguns Core, Tesla Core Lib, Tesla Core Lib Registries, The Twilight Forest, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thut Core, Thut's Wearables, ThutCore Compat, Tickrate Changer, Time Stages, Tinker Stages, Tinkers Tool Leveling, Tinkers' Construct, Tool Progression, Totem Essentials, Tough As Nails, Tough Expansion, Undestructible, Universal Remote, Unlimited Chisel Works, Unlimited Chisel Works - Botany Compat, Unloader, Valkyrie Lib, Vanilla Immersion, Vending, Waila, Waila Stages, Waystones, Wearable Backpacks, What Are We Looking At, XNet, Xtones, Yoyos, Zero CORE, iChunUtil, mob_grinding_utils, p455w0rd MOTD Customizer, p455w0rd's Library, ptrmodellib

When Sponge is installed, and I enter a Compact Machines 3 Dimension (dimid=144) or Machine, Mobs can't be officially killed. I'll summon any number of mobs (passive / hostile) but the mob will not be slain. If the blow was the killing blow the appropriate drops will spawn, but the mob will still be there. This only occurs in the Compact Machines 3 Dimension and not the Overworld (DimId=0)

EDIT: This occurs in every other dimension except the overworld

If I remove my sponge plugins (Denizen2sponge / DenizenCore / Prism) , the problem persists

If I remove sponge itself, the problem goes away.

![temp](https://user-images.githubusercontent.com/35056074/36392231-46756134-1578-11e8-8802-c38ba63fd8e4.png)

**Comment by QAngelusQ** [comment]
After more digging, this issue was caused by a mod "Scaling Health"

Not a direct sponge issue

**Comment by gabizou** [comment]
Scaling Health mod? I'm curious what that mod is doing since sponge does some health scaling already.

**Comment by QAngelusQ** [comment]
Here you go!

https://github.com/SilentChaos512/ScalingHealth/issues/86
