### ISSUE TITLE
Placing a Signpost sign boots me from the server - ClassCastException: cofh

### ISSUE THREAD

**Issue by ProsperCraft** [SpongePowered/SpongeForge#2019]
**I am currently running**

- SpongeForge version:  spongeforge-1.12.2-2611-7.1.0-BETA-2933
- Forge version: forge-1.12.2-14.23.2.2618-universal
- Java version: openjdk version "1.8.0_161"
- Operating System: Centos 7 minimal install

- Plugins/Mods: Plugins (15): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, EconomyLite, LuckPerms, MMCReboot, MagiBridge, Nations, Nucleus, PayDay, PwnFilter Sponge Plugin, SendToSpawn, SleepVote, WorldEdit

Mods (166): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, /dank/null, AI Improvements, Applied Fluidics, Applied Llamagistics, Applied Llamagistics Core, Architect, Astikoor, Backpacks!, Bad Wither No Cookie! Reloaded, Bailey's Dailies, Bed Bugs, Better Animals Mod, Better Builder's Wands, Better Questing, Better Questing Quest Book, BiblioCraft, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, BiomeTweaker, Biomes O' Plenty, Bookshelf, Car Mod, Cavern II, Ceramics, Chameleon, ChinjufuMod, Chisel, Chisels & Bits, Chococraft 3, Chunk Pregenerator, CoFH Core, CoFH World, CodeChicken Lib, Cooking for Blockheads, Corail Pillar, Corail Pillar - Biomes O'Plenty Extension, Corail Pillar - Chisel Extension, Corail Pillar - Forestry Extension, CosmeticArmorReworked, CraftTweaker JEI Support, CraftTweaker2, CustomNPCs, Dark Roleplay Core, Dark Roleplay Medieval, Decocraft, DeepResonance, Default World Generator, Display, Dooglamoo Cities, Edible Bugs Mod, ElecCore, Elevator Mod, EnderTanks, EqualDragons, Extra Bit Manipulation, Farming for Blockheads, Farseek, Fast Leaf Decay, Forestry, Futurepack, Futurepack API, Futurepack Forestry Addon, Hydrophobia, Immersive Engineering, Immersive Petroleum, Immersive Railroading, Immersive Tech, Industrial Foregoing, Industrial Wires, IndustrialCraft 2, Inventory Tweaks, JEI Bees, Just Enough Items, LLibrary, LagGoggles, Landlust, Lapis Stays in the Enchanting Table, Laser Level, LibrarianLib, LibrarianLib Stage 2, Long Fall Boots, LunatriusCore, MTLib, MagicBees, Mantle, Mekanism, MekanismTools, MineColonies, MineTweakerRecipeMaker, Minecraft Transport Simulator, Mod Tweaker, MrCrayfish's Furniture Mod, MrCrayfish's Jumping Castle Mod, Multi-Beds, Multi-Storage, Natura, Nature's Compass, No FOV, NoNausea, NotEnoughIDs, OC Glasses, Open Glider, OpenComputers, OpenComputers (Core), OpenComputers Sensors, OpenEye, Pam's HarvestCraft, Personal Cars, Placebo, Platforms, Prefab, Pumpkin Carving, RC Roads, RF Lux, RandomPatches, Reborn Core, Redstone Flux, Rope Bridge, ServerObserver, Shadowfacts' Forgelin, ShetiPhian-Core, Signal-Catcher, Signpost, Standard Expansion, Steve's Carts 2, Storage Drawers, Streams, Super Sound Muffler, TOP Addons, Tech Reborn, Techguns, Techguns Core, Tell Me, Tesla Core Lib, Tesla Core Lib Registries, The One Probe, Thermal Dynamics, Thermal Expansion, Thermal Foundation, TickProfiler, Tomb Many Graves, ToroChess, Track API, Tumbleweed, Unloader, Waddles, Wearables, What Are We Looking At, Wizardry, Xtones, Zetta Industries, careerbees, mxTune, p455w0rd's Library, ptrmodellib, �9RuneCraft

**Issue Description**

When I place a signpost and name my waystone on the sign it kicks me from the server.  This did not happen in the month we were using it without sponge.

https://gist.github.com/ProsperCraft/acd0ad3259ad83a5e4ec7eaab63894db

When I get back in and click on the signpost with my waystone name on it, it kicks me from the server.

https://gist.github.com/ProsperCraft/6b3e9cfc8837db593d132320ebe7f056

My modpack - https://minecraft.curseforge.com/projects/towncraft

**Comment by Eufranio** [comment]
Looks like an issue with the mod. Does it happen without Sponge?

**Comment by ProsperCraft** [comment]
It does not happen without sponge, we have used them extensively as our only teleport on our forge only server for a month with no issues at all.

**Comment by LordRalex** [comment]
And if you remove sponge, it doesn't crash now?

This log points to a coding issue within the Sign mod, it somehow has a tile duct registered as it's own stuff and it's breaking there.

**Comment by ProsperCraft** [comment]
This isssue is really odd. It comes and goes.

When the signs don't work and give the stacktrace in console, advancements don't get sent to chat either.

**Comment by ProsperCraft** [comment]
This has been resolved, no longer happening with updates.

**Comment by parlough** [comment]
@ProsperCraft Thanks for keeping us updated, glad it's working now!
