### ISSUE TITLE
Phase State NPEs with Quarry

### ISSUE THREAD

**Issue by johnfriedrich** [SpongePowered/SpongeForge#2020]
**I am currently running**
- SpongeForge version: 2931 (But also happens with 2911)
- Forge version: 2611

Modpack: Direwolf20 1.7.1

The tile has a weird owner: Owner: SpongeUser (But this might be right)
NPE's: https://pastebin.com/nUTFLbKk
junk startup: https://gist.github.com/i9hdkill/5dac1021ca66916e85426b0c2f0cf47b

It's ridiculously spamming:D

**Comment by Eufranio** [comment]
SpongeUser is the impl of User, I guess, on your case its assigned to `Deadlocz`

**Comment by phit** [comment]
use the search please

https://github.com/SpongePowered/SpongeForge/issues/1961#issuecomment-364134079
