### ISSUE TITLE
Sponge Crash when interactinginventorycloseed

### ISSUE THREAD

**Issue by JoeSGT** [SpongePowered/SpongeForge#2022]
**I am currently running**

- SpongeForge version: 1.12.2-2611-7.1.0-BETA-2939
- Forge version:  1.12.2-14.23.2.2615
- Java version:  8
- Operating System: linux 

- Plugins/Mods:
it's in the crash report

**Issue Description**
I have no idea but my server is crashing unless 
crash report: https://pastebin.com/bhMWHrCH

**Comment by Faithcaio** [comment]
fixed in latest
