### ISSUE TITLE
unable to use Holo-projector from libvupes

### ISSUE THREAD

**Issue by JoeSGT** [SpongePowered/SpongeForge#2028]
**I am currently running**

- SpongeForge version: 1.12.2-2611-7.1.0-BETA-2946
- Forge version: 1.12.2-14.23.1.2606-universal
- Java version: 8
- Operating System: windows

- Plugins/Mods:
LibVulpes-1.12.2-0.2.8-27
AdvancedRocketry-1.12.2-1.2.6-54

**Issue Description**
Holo-Projector is an item from LibVulpes use for AdvancedRocketry to have a holographic look of a ghost blocks to give us more of a guide on how to build a multi-block structure, it seem the Textures of the ghost blocks are not showing it seem to have break on this commit here is a screenshot of what happens 
![2018-02-28_11 37 38](https://user-images.githubusercontent.com/30296350/36799724-d20e6790-1c7b-11e8-9d04-60b8ed68adc6.png)

this does not happen using 
1.12.2-2611-7.1.0-BETA-2944, it seem to have be related to an issue i reported earlier here  
issue: https://github.com/SpongePowered/SpongeCommon/issues/1822
commit: https://github.com/SpongePowered/SpongeCommon/commit/50441219291e93c6bf274f71140ae622f7878e8a

**Comment by SquidDev** [comment]
Is this also fixed by SpongePowered/SpongeCommon@2da3a726695a43137376f6e848d8a0acd87a892c? I know it's fixed similar issues I've had.

**Comment by JoeSGT** [comment]
yeap tested it's fixed :D
