### ISSUE TITLE
Forge's TileEntity timing system does not work

### ISSUE THREAD

**Issue by SquidDev** [SpongePowered/SpongeForge#2029]
- SpongeForge version: 1.12.2-2611-7.1.0-BETA-2940
- Forge version: 1.12.2-14.23.2.2613
- Java version: 1.8.0_151-b12
- Operating System: Windows

I've mentioned this on the discord, but felt it would probably be better to create an issue too:

Forge adds the `/forge track state te` command, which times how long each tile entity (and entity) takes to tick, reporting the slowest ones. When using SpongeForge, the command runs successfully, but running `/forge track te` (to list the result), does nothing.

The timings hook is added via [Forge's patch to `World.updateEntities`](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/patches/minecraft/net/minecraft/world/World.java.patch#L467). As Sponge overrides this entire method, the timing code is never called.

[discord]: https://discordapp.com/channels/142425412096491520/142425412096491520?jump=416665137504714752

**Comment by gabizou** [comment]
~move to sc

**Comment by limbo-app** [comment]
Hey @SquidDev! I've moved your issue to [SpongePowered/SpongeCommon#1823](https://github.com/SpongePowered/SpongeCommon/issues/1823).
