### ISSUE TITLE
Mods not working

### ISSUE THREAD

**Issue by Spontini** [SpongePowered/SpongeForge#2030]
**I am currently running**

- SpongeForge version: 1.12.2-2611-7.1.0-BETA-2946
- Forge version: 14.23.2.2618
- Java version: Java 8 Update 161 64bit
- Operating System: Ubuntu Server 17.10 "Artful Aardvark".

- Plugins/Mods: FTB Revelation v1.6
-Plugins
+AIImprovements-1.12-0.0.1b3
+Born+In+A+Barn+V1.8-1.12-1.0
+BuycraftX
+CatClearLag-0.8.1
+crazyfeet-sponge-Api-7-1.14
+incontrol-1.12-3.7.1
+LuckPerms-Sponge-4.1.7
+MagiBridge-API7-2.4.5.1
+MBDiscordLink-API7-1.4
+MMCReboot-2.1.3-API-7
+MMCRestrict-1.4.1-API-7
+Nucleus-1.3.1-S7.0-MC1.12.2-plugin
+PlayerGlow_1.1.1
+sampler-1.73
+SpongeBootstrap-0.6.2
+TickProfiler-1.12-0.0.2
+worldedit-forge-mc1.12-6.1.8-dist

-Issue
+ I own a server and all of my user's GP generating and NuclearCraft's RF generating stopped after i installed that version of sponge and it fixed after i downrange sponge version. I don't have any log, crash reports, it's just a issue i had.

**Comment by gabizou** [comment]
So what block do I need to place down to verify the RF generation isn’t working as it should? Is it as simple as setting up a generator and connecting to something like an MFE from IC2?

**Comment by ProsperCraft** [comment]
Screenshots can be helpful.

**Comment by ProsperCraft** [comment]
Is boostrap still required in 1.12.2? I thought AE2 was fixed.
