### ISSUE TITLE
Console error - Error while creating CraftingInventoryLensImpl for brad16840.common.ContainerStack

### ISSUE THREAD

**Issue by ProsperCraft** [SpongePowered/SpongeForge#2031]
**I am currently running**
- SpongeForge version: SpongeForge: 1.12.2-2611-7.1.0-BETA-2944
- Forge version: forge-1.12.2-14.23.2.2619-universal.jar
- Java version: openjdk version "1.8.0_161"
- Operating System:Centos 7 

- Plugins/Mods:
Plugins (15): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, EconomyLite, LuckPerms, MMCReboot, MMCRestrict, MagiBridge, Nations, Nucleus, PayDay, PwnFilter Sponge Plugin, SleepVote, rankup

 Mods (169): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, /dank/null, AI Improvements, Applied Fluidics, Applied Llamagistics, Applied Llamagistics Core, Architect, Astikoor, Backpacks!, Bad Wither No Cookie! Reloaded, Bailey's Dailies, Bed Bugs, Better Animals Mod, Better Builder's Wands, Better Questing, Better Questing Quest Book, BiblioCraft, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, BiomeTweaker, Biomes O' Plenty, Bookshelf, Car Mod, Cavern II, Ceramics, Chameleon, ChinjufuMod, Chisel, Chisels & Bits, Chococraft 3, Chunk Pregenerator, CoFH Core, CoFH World, CodeChicken Lib, Cooking for Blockheads, Corail Pillar, Corail Pillar - Biomes O'Plenty Extension, Corail Pillar - Chisel Extension, Corail Pillar - Forestry Extension, CosmeticArmorReworked, CraftTweaker JEI Support, CraftTweaker2, CustomNPCs, Dark Roleplay Core, Dark Roleplay Medieval, Decocraft, DeepResonance, Default World Generator, Display, Dooglamoo Cities, Edible Bugs Mod, ElecCore, Elevator Mod, EnderTanks, EqualDragons, Extra Bit Manipulation, Farming for Blockheads, Farseek, Fast Leaf Decay, Forestry, Futurepack, Futurepack API, Futurepack Forestry Addon, Hydrophobia, Immersive Engineering, Immersive Petroleum, Immersive Railroading, Immersive Tech, Industrial Foregoing, Industrial Wires, IndustrialCraft 2, Inventory Tweaks, JEI Bees, Just Enough Items, LLibrary, LagGoggles, Landlust, Lapis Stays in the Enchanting Table, Laser Level, LibrarianLib, LibrarianLib Stage 2, Long Fall Boots, LunatriusCore, MTLib, MagicBees, Mantle, McJtyLib, Mekanism, MekanismTools, Millenaire, MineColonies, MineTweakerRecipeMaker, Minecraft Transport Simulator, Mod Tweaker, MrCrayfish's Furniture Mod, MrCrayfish's Jumping Castle Mod, Multi-Beds, Multi-Storage, Natura, Nature's Compass, No FOV, NoNausea, NotEnoughIDs, OC Glasses, Open Glider, OpenComputers, OpenComputers (Core), OpenComputers Sensors, OpenEye, Pam's HarvestCraft, Personal Cars, Placebo, Platforms, Prefab, Pumpkin Carving, RC Roads, RF Lux, RandomPatches, Reborn Core, Redstone Flux, Rope Bridge, Sampling Performance Profiler, ServerObserver, Shadowfacts' Forgelin, ShetiPhian-Core, Signal-Catcher, Signpost, Standard Expansion, Steve's Carts 2, Storage Drawers, Streams, Super Sound Muffler, TOP Addons, Tech Reborn, Techguns, Techguns Core, Tell Me, Tesla Core Lib, Tesla Core Lib Registries, The One Probe, Thermal Dynamics, Thermal Expansion, Thermal Foundation, TickProfiler, Tomb Many Graves, ToroChess, Track API, Tumbleweed, Unloader, Waddles, Wearables, What Are We Looking At, Wizardry, Xtones, Zetta Industries, careerbees, mxTune, p455w0rd's Library, ptrmodellib, �9RuneCraft

**Issue Description**

The stacktrace attached shows up in console.  I don't know what the players were doing ingame, or if it has an effect on them.

https://gist.github.com/ProsperCraft/fd9de4e6d99a87595888e9cd1a55b3d7

**Comment by Faithcaio** [comment]
This error wont affect gameplay. But Sponge will not be able to provide the CraftingInventory for that Container.

**Comment by ProsperCraft** [comment]
I found how to reproduce it, you install this mod- 
https://minecraft.curseforge.com/projects/minetweaker-recipemaker

Then type /mtrm

Then you get this - https://gist.github.com/ProsperCraft/b8855967ca5e60a55c44cf8e15dab64c

**Comment by Faithcaio** [comment]
Did not think that a crafting inventory without output makes sense. But here it is...

**Comment by PoroUsedSnax** [comment]
I have been noticing this error too (for brad16840). I'm fairly certain it is related to the Backpacks! mod. And more specifically a crafting window that is opened by right clicking a crafting table in the players inventory, opening a custom GUI.

I have reported it to the developer, but thought I would mention it here as well as I found this issue.

Here is more information for it, same as given to brad: 
Error: https://gist.github.com/PoroUsedSnax/cf2f874d67f94d58f3ccb3bf75e56378

Versions:
Minecraft: 1.12.2
SpongeAPI: 7.1.0-SNAPSHOT-06016f2
SpongeForge: 1.12.2-2611-7.1.0-BETA-2990
Minecraft Forge: 14.23.2.2611
Backpacks!: 3.4.4

Whilst this doesn't seem to affect gameplay as explained, I am again fairly certain that is does actually cause lag issues for the server (Eventually getting to constants of 4-7 TPS) After asking players to try and avoid using it, the TPS has been keeping at it's usual 20, as it should be. When this lag kicks in, I start to notice (Using LagGoggles) that sponge's CPU usage (I think that's what the percentage is) sky rockets, to the point where it could be showing between 300-600% and possible even more, as shown in this image (Bottom right pane):
![2018-03-29_18 29 51](https://user-images.githubusercontent.com/19329455/38142951-478a65ba-3436-11e8-842d-7fd4ba9b5066.png)

**Comment by gabizou** [comment]
The problem with marking the Sponge listener as "hot" code is that it's not doing anything special except processing the tick scheduler for plugins (so naturally sponge gets the massive hit for having to run all the scheduled tasks in that listener. If possible to associate warm roast or another VM hotspot timings reader would help as the image above doesn't provide any useful information to find the source of lag in this context.

But other than that, that's room for another discussion/issue as the topic at hand is for the error with a crafting inventory lens.

**Comment by PoroUsedSnax** [comment]
My error is the same CraftingInventoryLens one that this issue was originally made for, the `Error while creating CraftingInventoryLensImpl for brad16840.common.ContainerStack` one, it's just that our lag issues seem to be **related** to this error, but I can start a new issue if you'd like, not sure what else it would be called though. I can sort out a warmroast for you to take a look at.

EDIT: brad has now fixed this with his coming latest update, so from my point of view this is free to be closed.
