### ISSUE TITLE
Bad issues after updating to spongeforge 2946 - graves without ownership, multiblocks not breaking properly.

### ISSUE THREAD

**Issue by ProsperCraft** [SpongePowered/SpongeForge#2032]
**I am currently running**
- Forge version: forge-1.12.2-14.23.2.2623-universal.jar

**Issue Description**
After updating to 2946 Tomb Many Graves would spawn with the owner of the mods name, and Immersive multiblocks would not break properly and drop.

Reverting to 2944 removed that problem.

https://github.com/M4thG33k/TombManyGraves2/issues/30

**Comment by Whazaaaaa** [comment]
Would like to add to this that items such as universal cables higher tiers when placed down will become the default basic tier.
And crates/chests that keep their inventory when broken do not keep the items anymore in 2946.
No problem in 2944 as Prosper said aswell.

**Comment by Lemmmy** [comment]
ComputerCraft monitors are also facing only one direction when being placed.
