### ISSUE TITLE
Sponge and Carry On+ on forge crash when interacting with chest

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#2033]
https://gist.github.com/ternsip/68ba1de78f56ff792c15702bc80ea72f
Sponge and Carry On+ on forge crash when interacting with chest
I'm trying to pick chest with arms and sponge crushes

**Comment by XakepSDK** [comment]
```
java.lang.NoClassDefFoundError: com/feed_the_beast/ftblib/lib/math/BlockPosContainer
```
Not a sponge issue.

**Comment by phit** [comment]
As said above, not a Sponge issue.
