### ISSUE TITLE
getVelocity returns incorrectly when player is in boat

### ISSUE THREAD

**Issue by zedwick** [SpongePowered/SpongeForge#2035]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2611-7.1.0-BETA-2931
- Forge version: forge-1.12.2-14.23.2.2611
- Java version: 1.8.0_131
- Operating System: Mac OS X

When a player is in a boat, Player.getVelocity() and Player.getVehicle().get().getVelocity() both return (0.0, 0.0, 0.0) instead of their actual velocity.

**Comment by phit** [comment]
~move to sc

**Comment by limbo-app** [comment]
Hey @zedwick! I've moved your issue to [SpongePowered/SpongeCommon#1846](https://github.com/SpongePowered/SpongeCommon/issues/1846).
