### ISSUE TITLE
clay soldiers mod, player disconnecting and server hang.

### ISSUE THREAD

**Issue by MrSkittlesROTR** [SpongePowered/SpongeForge#2036]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2611-7.1.0-BETA-2953
- Forge version: forge-1.12.2-14.23.2.2613-universal
- Java version: 8
- Operating System: Windows server 2012 R2

Mods:
- Plugins/Mods: AntiXray-1.2.3
bdlib-1.14.3.12-mc1.12.2
CodeChickenLib-1.12.2-3.1.5.331-universal
CoFHCore-1.12.2-4.3.10.5-universal
CoFHWorld-1.12.2-1.1.1.12-universal
CraftTweaker2-1.12-4.1.5
CTM-MC1.12-0.2.3.12
ElecCore-1.12.2-1.8.434
environmentaltech-1.12.2-2.0.7b
generators-0.9.20.123-mc1.7.10
gravestone-1.10.1
Hwyla-1.8.23-B38_1.12
ImmersiveEngineering-0.12-78
irontank-1.7.10-1.1.15.65
jei_1.12.2-4.8.5.147
journeymap-1.12.2-5.5.2
LangSwitch
latch-0.4.7-s7.0.0
LuckPerms-Sponge-4.1.5
MagiBridge-API7-2.4.5.1
Mantle-1.12-1.3.1.21
MBDiscordLink-API7-1.4
minecolonies-universal-1.12.2-0.8.7637
Nucleus-1.3.1-S7.0-MC1.12.2-plugin
NotEnoughItems-1.12.2-2.4.1.233-universal
openmodularturrets-1.12.2-3.0.0-236
Prism-3.0.0-beta2-46-ge820b5e-all
RedstoneFlux-1.12-2.0.1.2-universal
reptilemod-1.12.2-3.8.4-82
rftools-1.12-7.30
TConstruct-1.12.2-2.9.1.65
TotalEconomy-1.7.1-API_7
UltimateChat-1.8.6-b160-Universal
UniverseGuard-2.6-API7
VillagerShops
VoxelSniper-8.5.0-SNAPSHOT
Wawla-1.12.2-2.5.251
worldedit-forge-mc1.12-6.1.8-dist

**Issue Description**
Issue is with the mod ClaySoldiersMod-1.12.2-3.0.0-alpha.9.1
Mod and its dependency loads up fine for both server and client
on spawning in one of the clay soldiers all players on the server are disconnected with no reason logged and the server hangs.
players cannot reconnect to the server untill the mod is removed.
Iv spoke to the mods dev, he cannot replicate the bug after testing and browsing the servers log's
he suggested its a sponge issue.

Logs:
https://gist.github.com/MrSkittlesROTR/9f96fb3ea24fa5aa4554ed9e5572bfc3

**Comment by bloodmc** [comment]
@MrSkittlesROTR Remove ALL plugins and mods except ClaySoldiers and then provide a log. Make sure you do this with a FRESH world.

**Comment by bloodmc** [comment]
@MrSkittlesROTR I will be closing this if you do not respond by tomorrow.
