### ISSUE TITLE
Server crashes immediately when player enters Twilight Forest portal with OTG

### ISSUE THREAD

**Issue by LuminescentMoon** [SpongePowered/SpongeForge#2037]
**I am currently running**

- SpongeForge version: 2953 (also tested with recent previous version)
- Forge version: 2611 (also tested with a few newer versions)
- Java version: 1.8.0_161, Oracle Corporation
- Operating System: Windows 10 Pro 1709 x64

- Plugins/Mods: SpongeForge, Open Terrain Generator, The Twilight Forest

**Issue Description**
Server crashes immediately when a player enters a [Twilight Forest portal](https://ftbwiki.org/Twilight_Forest#Entering_the_Twilight_Forest). Crash does **NOT** occur when **either** SpongeForge or Open Terrain Generator is removed.

**Note:** Crash does not occur when entering a [portal](http://the-betweenlands.wikia.com/wiki/Portal_Tree) from [The Betweenlands](https://minecraft.curseforge.com/projects/angry-pixel-the-betweenlands-mod), a mod similar to Twilight Forest in that it adds a new world that has its own separate content. Nether portals additionally do not crash the server.

[Full Server Log](https://gist.github.com/LuminescentMoon/4bea459b84dbacd783f95ed8bc18aa8a)
[Crash Report](https://gist.github.com/LuminescentMoon/d8fcd2a02ff18bbfa2d256673c993446)

[Minimal Server Crash Package — the bare minimum files required to reproduce the crash](
https://www.dropbox.com/s/hn0ogxm12icdgy7/minimal-crash-server.7z?dl=1)

This issue has also been posted to PG85/OpenTerrainGenerator#141 and TeamTwilight/twilightforest#433

**Comment by bloodmc** [comment]
Does TerrainControl have this issue?

http://build.mctcp.com/job/TerrainControl%20-%20Master%20-%20Gradle/default/lastStableBuild/artifact/platforms/forge/build/distributions/terraincontrol-forge-2.8.3-SNAPSHOT.jar

**Comment by LuminescentMoon** [comment]
@bloodmc Setting ``TerrainControl`` for ``level-type`` in ``server.properties`` doesn't enable it for the default world so I can't test. Typing in ``/tc worldinfo`` results in ``TerrainControl is not enabled for this world.`` even with a fresh world with the config folder deleted.

**Comment by bloodmc** [comment]
@LuminescentMoon TerrainControl REQUIRES world configs to be setup or it will not enable. I just tested TC with latest SpongeForge and Twilight Forest, no issues teleporting. OTG must fix this as I only support TerrainControl.

https://github.com/MCTCP/TerrainControl/wiki

**Comment by LuminescentMoon** [comment]
@bloodmc ah, understandable. The installation guide for forge servers implied that it would enable but "the world will look like a default Minecraft world."
