### ISSUE TITLE
Recurent crash Structpro + sponge forge

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#2038]
- Docker: docker container openjdk:8u151-alpine
- SpongeForge version: spongeforge-1.12.2-2611-7.1.0-BETA-2953.jar
- Forge version: forge-1.12.2-14.23.2.2611-universal.jar
- Java version:  
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (IcedTea 3.6.0) (Alpine 8.151.12-r0)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)
- Operating System:
Linux v22018025835161770 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u2 (2018-02-21) x86_64

- sponge plugins: Plugins (6):  
Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, FlexibleLogin, LuckPerms

Modlist forge:
https://gist.github.com/ternsip/ac86cab2f7f0f5aee197ce97a5a1132b
You can find structpro-4.2 it works same way as 4.0

All i can select from log
https://drive.google.com/open?id=1occhZDajaQK1vG4O1EEYVrc998Q1Pk2p

Info
https://gist.github.com/ternsip/1c7b23102bdea69cd28b1c484bdf7f20
When i place structure being a player.

I use command from structpro mod
/spro paste
Maybe a few times
This mod works normally without sponge forge

**Comment by bloodmc** [comment]
Completely ignored our issue template. Closing until you can learn to follow our instructions.

**Comment by ghost** [comment]
I fixed the description. If it drawn up correct - can you please reopen issue. I want to figure out what goes improper way. Sorry for skipping the template stage.

**Comment by phit** [comment]
please retest on latest (7.1.0-BETA-2985)

**Comment by Zidane** [comment]
Closing due to lack of reply.
