### ISSUE TITLE
QuackLib Issue with SpongeForge

### ISSUE THREAD

**Issue by D3nnis3n** [SpongePowered/SpongeForge#2039]
**I am currently running**

- SpongeForge version: 2953
- Forge version: 2624
- Operating System: Linux

I'll just link you over to the issue i made on the mod authors issue tracker. If you need special information, please tell me which, i lately had no access to the server.

https://github.com/therealfarfetchd/QuackLib/issues/1#issuecomment-371522217

**Comment by dblsaiko** [comment]
To sum up the issue: I'm reflecting into my other mods' classes using the Kotlin reflection API. The function/property of the reflection API that I call is never supposed to throw an exception (either return an object or null), but with Sponge installed it does throw an exception. [This](https://github.com/therealfarfetchd/QuackLib/blob/1.12/src/main/kotlin/therealfarfetchd/quacklib/common/api/util/AutoRegistry.kt#L97) is the offending line of code and the stack trace is in the original issue in the top comment.

**Comment by Aaron1011** [comment]
I've reproduced this on the latest SpongeForge. I'm taking a look at it now.

**Comment by Aaron1011** [comment]
The root issue appears to be our `MixinIProperty`. Mixin appears to be merging the generic signatures for `BlockTrait` and `IProperty` in an odd way, which is confusing Kotlin's reflection system.

I'll investigate more tomorrow.

**Comment by Aaron1011** [comment]
It turns that our `MixinIProperty` is causing Mixin to change the generic signature of `IProperty` from `IProperty<T>` to `IProperty<T, U>`. This is confusing the Kotlin reflection API, which doesn't expect this kind of generic signature change to occur.

I've opened an issue on the Mixin repository to address this: https://github.com/SpongePowered/Mixin/issues/254

**Comment by phit** [comment]
see also https://github.com/SpongePowered/SpongeCommon/issues/1845#issuecomment-383316109
for more kotlin fun

**Comment by Aaron1011** [comment]
After bumping Mixin in https://github.com/SpongePowered/SpongeForge/commit/c9b253f68c6e1fe9eba49ad859ec5c11c925eba6, this issue appears to have been fixed.
