### ISSUE TITLE
When I start SpongeForge, the server STOPS.

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#2040]
I am currently running:
- SpongeForge version: spongeforge-1.10.2-2477-5.2.0-BETA-2790
I tried too with the new version and it's the same error (2793)
- Forge version: 1.10.2-forge1.10.2-12.18.3.2477
- Java version: Java 8 161 (64-bit)
- Operating System: Windows 8.1

- Plugins/Mods: CatClearLag-0.8, EasyScoreboards, flexiblelogin-0.16.8, spongeapi-5.1.0-shaded.

The issue (crash) it's this:
When I start my SpongeForge server, it crashes when loading the spongeforge plugin.

Server log:
https://gist.github.com/Josegamesall/56f4a9234e978244bdf12d8411188321

Server Crash:
https://gist.github.com/Josegamesall/69171c11146042456b05497adb8194a4

**Comment by RedNesto** [comment]
It seems Pokestop tries to do client stuff on the server, have you tried without it ?

**Comment by phit** [comment]
As RedNesto said, not a Sponge issue.
