### ISSUE TITLE
Extra utilities 2 quantum quarry throwing an nullpointerexception

### ISSUE THREAD

**Issue by lucasman123** [SpongePowered/SpongeForge#2042]
**I am currently running**

- SpongeForge version: 1.12.2-2586-7.1.0-BETA-2905
- Forge version: 14.23.1.2587
- Java version: 1.8.0_101
- Operating System: Windows 7 pro

- Plugins/Mods:
Mods (136): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI,SpongeForge, /dank/null, Actually Additions, Advanced Generators, Akashic Tome, AppleSkin, Applied Energistics 2, Aroma1997's Dimensional World, Aroma1997Core, Astral Sorcery, AutoRegLib, BD Lib,Bad Wither No Cookie! Reloaded, Baubles, Better Advancements, Better Builder's Wands, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Biomes O' Plenty, Blockcraftery, Bookshelf, Botania, Brandon's Core, Chameleon, ChickenChunks, Chisel, Chisels &Bits, CoFH Core, CoFH World, CodeChicken Lib, CommonCapabilities, Compact Machines 3, Compact Solar Arrays, Cooking for Blockheads, CraftTweaker JEI Support, CraftTweaker2, Cyclops Core, Dark Utilities, DeepResonance, Diet Hopper, Draconic Evolution, ElecCore, Elevator Mod, EluCore, EluLib, EnderStorage, Environmental Tech, Exchangers, Extra Utilities 2, Extreme Reactors, FTBLib, FTBUtilities, Flat Colored Blocks, FoamFix, Forestry, Funky Locomotion, GenDustry, Gravestone Mod, ImmersiveEngineering, Industrial Foregoing, IndustrialCraft 2, Integrated Dynamics, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTunnels-Compat, Iron Backpacks, Iron Chest, JEI Bees, JourneyMap, Just Enough Items, MCMultiPart, MTLib, MagicBees, Mantle, MeeCreeps, Mercurius, MineTogether, MineTogetherServer, Mod Tweaker, Morph, Morph-o-Tool, Morpheus, NetherPortalFix, Not Enough Wands, OpenComputers, OpenComputers (Core), Pam's HarvestCraft, Placebo, PortalGun, Psi,Quick Leaf Decay, RFTools, RFTools Control, RFTools Dimensions, Ranged Pumps, Reborn Core, RebornStorage, Redstone Arsenal, Redstone Flux, Refined Storage, Refined Storage Addons, Shadowfacts' Forgelin, Simple Inventory sorting, Simply Jetpacks 2, Storage Drawers, Storage Drawers Extras, SwingThroughGrass, TOP Addons, Tesla Core Lib, Tesla Core Lib Registries, The Lost Cities, The One Probe, The Twilight Forest, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Tinkers' Construct, UniDict, Valkyrie Lib, WanionLib, Wireless Crafting Terminal 2, XNet, Zero CORE, iChunUtil, mob_grinding_utils, p455w0rd's Library
>

**Issue Description**
When ever I turn on the quantum quarry the server spam throws an nullpointerexception. The quarry does not work at all.

https://gist.github.com/lucasman123/ffdfc465d5e3bfb6abf6210260133349

**Comment by phit** [comment]
https://github.com/SpongePowered/SpongeForge/issues/1961#issuecomment-364134079

---
if this doesn't resolve it please add your `fml-junk-earlystartup.log`
