### ISSUE TITLE
Server crash when any player enters Nether

### ISSUE THREAD

**Issue by Rasmun** [SpongePowered/SpongeForge#2044]
**I am currently running**
- SpongeForge version: 2.4.77-5.2.0-BETA-2793
- Forge version: 2.4.77
- Java version: 8 Update 161 for 64bit
- Operating System:  Windows 2012

**Plugins/Mods:**
The only things installed are SkyFactory 3 and SpongeForge.  Below is the list from '/sponge plugins'

> sponge plugins
[18:35:14] [Server thread/INFO]: Plugins (186): Minecraft, Minecraft Coder Pack,
 Forge Mod Loader, Minecraft Forge, Not Enough Items, OpenComputers (Core), Spon
geAPI, SpongeForge, FoamFixCore, ccl-entityhook, Fence Overhaul, Actually Additi
ons, CodeChicken Lib, CodeChicken Core, EnderStorage, Just Enough Items, OpenCom
puters, ActuallyComputers, Baubles, Extra Utilities 2, AngelRing 2 Bauble, Apple
Core, apple_shields, AppleSkin, AutoPackager, Psi, AutoRegLib, Baconators, Craft
Tweaker JEI Support, MineTweaker 3, B.A.S.E, BD Lib, Bed Bugs, Better Builder's
Wands, BiomeTweaker, BlockDispenser, Guide-API, Blood Magic: Alchemical Wizardry
, Bookshelf, Botania, Brandon's Core, Mantle, Tinkers' Construct, Ceramics, Cham
eleon, Chance Cubes, MCMultiPart, ?, |, /, Chest Transporter, ChickenChunks, Chi
ckens, Chisel, Chisels & Bits, ShadowMC, Clipboard, Clumps, Cyclops Core, Coloss
al Chests, CommonCapabilities, Cooking for Blockheads, Waila, Dark Utilities, PT
RModelLib, Decocraft, Dimensional Cake, Draconic Evolution, Dragon Mounts, Stora
ge Drawers, Drawers & Bits, Elevator Mod, EnderCore, Ender IO, Energy Converters
, Engineer's Workshop, Valkyrie Lib, Environmental Tech, ET Lunar, Ex Nihilo Ads
censio, Ex Compressum, Extra Bit Manipulation, Zero CORE, Extreme Reactors, Fair
y Lights, Farming for Blockheads, Flat Colored Blocks, SonarCore, FluxNetworks,
FoamFix, Shadowfacts' Forgelin, FTBLib, FTBUtilities, Funnels, Garden of Glass,
Advanced Generators, Gravestone Mod, Grue, Get Ya' Tanks Here, Hammer Core, Hatc
hery, Headcrumbs, Hopper Ducts, HydroGel, Immersive Engineering, LunatriusCore,
InGame Info XML, MTLib, InitialInventory, Integrated Dynamics, Integrated Tunnel
s, Simple Inventory sorting, Iron Backpacks, Iron Chest, YUNoMakeGoodMap, ItsBec
auseUHasNoGoodSpawn, It's Raining Food, JourneyMap, KleeSlabs, LLibrary, Literal
 Ascension, Long Fall Boots, Loot Bags, Mercurius, MineMenu, MiniCoal, Natura, M
issing Pieces, Random Things, Roots, MoarSigns, mob_grinding_utils, Mod Tweaker,
 More Chickens, More Shearables, More Shears, Morpheus, ModPack Utilities, ModPa
ck Basic Tools, Mystical Agriculture, Nice, Not Enough Wands, OreExcavation, Pac
king Tape, Pam's HarvestCraft, ShetiPhian-Core, Platforms, RebornCore, QuantumSt
orage, Ranged Pumps, reborncore-MCMultiPart, Refined Storage, RebornStorage, Red
stone Paste, Reliquia, RFTools, RFTools Control, RFTools Dimensions, Wooden Shea
rs, Scanner, Shear Madness, Simple Achievements, Simple Barrels, Simple Corn, Si
mple Generators, SimpleLabels, Simply Jetpacks 2, Snad, Solar Flux Reborn, Steve
's Carts 2, Super Circuit Maker, The Beneath, Tinkers Tool Leveling, Tiny Progre
ssions, TorchMaster, Translocator, Twerk-Sim 2K16, Twitchcrumbs, voidcup, Waddle
s, WanionLib, I Can See Everything, What Are We Looking At, Wither Crumbs, Exper
ience Rings, UniDict

**Issue Description**
1) Install SkyFactory 3
2) Install SpongeForge
3) Load into Minecraft
4) Create nether portal (3 block tall and 2 wide - normal size) then right-click with flint and steel.
5) Enter nether portal
Results:
1) Server crash.
2) After reboot, if the player attempts to login, the server will crash.
3) Have to TPHERE the player to an overworld location to stop them from crashing the server when they login.
Note:  If we turn off DoMobSpawning, players can get into the nether without crash

**Logs**
Crash log:  https://gist.github.com/Rasmun/3c4f4ee7a5c1adecaaf753604e190c4b

Full server log:  https://gist.github.com/Rasmun/de4c83d86b35450cf6b79fce82a52f19

**Comment by LXGaming** [comment]
Sponge no longer supports 1.10.2, This is a duplicate of https://github.com/SpongePowered/SpongeCommon/issues/1662 

Downgrade Sponge to the following version: [SpongeForge-1.10.2-2477-5.2.0-BETA-2788](https://repo.spongepowered.org/maven/org/spongepowered/spongeforge/1.10.2-2477-5.2.0-BETA-2788/spongeforge-1.10.2-2477-5.2.0-BETA-2788.jar)

**Comment by Rasmun** [comment]
That fixed the issue for us.  Thank you so much for your time!
