### ISSUE TITLE
EXP in Nether / Enchant

### ISSUE THREAD

**Issue by PixelmonPRO** [SpongePowered/SpongeForge#2046]
**I am currently running**

- SpongeForge version: `spongeforge-1.12.2-2611-7.1.0-BETA-2931`
- Forge version: `14.23.2.2611`
- Java version: `1.8.0_161`
- Operating System: `Debian 8`

- Plugins/Mods: [Plugins/Mods](https://gist.github.com/PixelmonPRO/0b61e4f6d74185645ea2682b9af2ddd4)

**Issue Description** After the player enchant any items, he goes to Nether, destroy any ore and the experience returns. Sorry for my english, [additional video with this bug](https://www.youtube.com/watch?v=qmHAFOFk2pg&feature=youtu.be).

No crashes and any errors.

**Comment by phit** [comment]
to sum up the video:

* player has X experience in overworld e.g. 31 lvls
* enchant an item (losing experience) now down to 28 lvls
* go to nether, gain experience (in this case by mining coal) 
* experience jumps up to 31 lvls again like the enchanting never happened

**Comment by JBYoshi** [comment]
Can reproduce in the latest build (build 2963). This works even without going to the Nether.

**Comment by JBYoshi** [comment]
Fixed in https://github.com/SpongePowered/SpongeForge/commit/8d6c775b5e3ce1c73fcd42824cff8a66ebb766d9.
