### ISSUE TITLE
Invalid villager profession ID

### ISSUE THREAD

**Issue by husscraft** [SpongePowered/SpongeForge#2048]
**I am currently running**

- SpongeForge version: 1.12.2-2611-2931
- Forge version: 1.12.2-14.23.2.2625
- Java version:  Java 8
- Operating System:

- Plugins/Mods:
Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Actually Additions, AE2 Stuff, Animania, Applied Energistics 2, ArchitectureCraft, AutoRegLib, BC Builders, BC Energy, BC Factory, BC Robotics, BC Silicon, BC Transport, BD Lib, Better Builder's Wands, BiblioCraft, Biomes O' Plenty, Bookshelf, Brandon's Core, BuildCraft , BuildCraft Lib, Car Mod, ChickenChunks, Chisel, Chisels & Bits, Classic Combat, CoFH Core, CoFH World, CodeChicken Lib, Cooking for Blockheads, CraftStudio API, Dark Utilities, Decocraft, Deep Sea Expansion, EnderStorage, Exotic Birds, Extra Cells 2, Extra Rails, Extreme Reactors, FTBLib, Fairy Lights, Familiar Fauna, Flat Colored Blocks, Forestry, Galacticraft Core, Galacticraft Planets, Hammer Core, HatStand, Hats, ICBM-Classic, Immersive Engineering, Immersive HempCraft, Immersive Petroleum, Immersive Tech, ImmersiveFood, Industrial Foregoing, IndustrialCraft 2, Iron Backpacks, Iron Chest, Just Enough Items, LLibrary, MalisisCore, MalisisDoors, Mantle, Mekanism, MekanismGenerators, MekanismTools, Micdoodle8 Core, Mod Support, Morph, Morph-o-Tool, MrCrayfish's Furniture Mod, MrCrayfish's Jumping Castle Mod, Mumbo's Redstone Additions, NHAVE's Core, OpenBlocks, OpenModsLib, OpenModsLib Core, Pam's HarvestCraft, Placebo, Plants, PlusTiC, PortalGun, ProjectE, Ranged Pumps, Reborn Core, Redstone Arsenal, Redstone Flux, Reptile Mod, ShadowMC, Shadowfacts' Forgelin, Solar Flux Reborn, Steve's Carts 2, Storage Boats Mod, Sync, TechStack's Heavy Machinery Mod, Tesla Core Lib, Tesla Core Lib Registries, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Tinkers Tool Leveling, Tinkers' Construct, Vein Miner, Woot, WorldEdit, YABBA, Zero CORE, iChunUtil, ptrmodellib

**Issue Description**
Server  crashes whenever someone approaches a new village. Its the Engineer Villager from Actually Additions that is causing the problem. The only ways around it have been to uninstall spongeforge and kill the villager before reinstalling,  or uninstalling Actually Additions. Neither  of which is ideal.

https://gist.github.com/husscraft/a533df0370e0852d59d915d737f4a267

**Comment by kuxiabk** [comment]
I have the same question as you
