### ISSUE TITLE
SpongeForge shouldn't be referenced as rootProject

### ISSUE THREAD

**Issue by gravityfox** [SpongePowered/SpongeForge#2049]
**I am currently running**

- SpongeForge version: all
- Forge version: n/a
- Java version: n/a
- Operating System: n/a

- Plugins/Mods: n/a

**Issue Description**
SpongeForge should not assume that it is the root gradle project, because it doesn't have to be.
It makes that assumption here: https://github.com/SpongePowered/SpongeForge/blob/bleeding/build.gradle#L89

This means if you try include SpongeForge in a wrapper gradle module, this line will fail, because `rootProject` now points somewhere else.

Instead of `rootProject`, it should just use `this`, so it always points to SpongeForge

**Comment by kashike** [comment]
Feel free to open a PR.
