### ISSUE TITLE
1.12.2 actually Additions xp / experience

### ISSUE THREAD

**Issue by demon57730** [SpongePowered/SpongeForge#2051]
forge-1.12.2-14.23.2.2627-universal.jar
spongeforge-1.12.2-2611-7.1.0-BETA-2964.jar
ActuallyAdditions-1.12.2-r132.jar

I contact you because I have a problem sponge side with a mod

here I have a mod: Actually Additions

in this mod it has an item Experience Solidifier without sponge any problem

but with sponge when we click on a digit consumes its xp but its not giving the solidified experience

the item recovered well xp on the ground is given the solidified experience

but when these player xp it does not give but it consumes the xp

video:

https://youtu.be/_XShQJShkz4

1st part: server with sponge
2nd part: solo without sponge

**Comment by kuxiabk** [comment]
I have the same question as you

**Comment by phit** [comment]
can't reproduce with 
1.12.2-2611-7.1.0-BETA-2984
ActuallyAdditions-1.12.2-r133

**Comment by kuxiabk** [comment]
ActuallyAdditions-1.12.2-R133 It seems to be repaired
