### ISSUE TITLE
tileentity-activation module not working on 1.12.2

### ISSUE THREAD

**Issue by KangYee** [SpongePowered/SpongeForge#2052]
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2611-7.1.0-BETA-2969
- Forge version: forge-1.12.2-14.23.2.2611
- Java version: java8 u163
- Operating System:windows server 2012R2

**Issue Description**
When I set the hopper block-range to 0 in the configuration, the hopper will still work.

**Comment by phit** [comment]
`0` means disabled, working as intended

**Comment by KangYee** [comment]
But when I set up block-range to 1, and I'm out of range, the hopper will still work.

**Comment by phit** [comment]
post your full global.conf to https://gist.github.com/
and put the link in here

**Comment by KangYee** [comment]
https://gist.github.com/KangYee/aff889ea6304c3fc7f8bb46401e38620

**Comment by phit** [comment]
~move to sc

**Comment by limbo-app** [comment]
Hey @KangYee! I've moved your issue to [SpongePowered/SpongeCommon#1838](https://github.com/SpongePowered/SpongeCommon/issues/1838).

**Comment by Rasgnarok** [comment]
Confirmed with a daylight sensor as well as a hopper on SF 2970, Forge 2611, no other mods. Sidenote, might be worth checking on entity-activation ranges as well - on testing, entities did not seem to stop moving, rather they would flicker and rotate, only 'walking' once in range.
