### ISSUE TITLE
Sponge crash

### ISSUE THREAD

**Issue by pdglobal** [SpongePowered/SpongeForge#2053]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2611-7.1.0-BETA-2970
- Forge version: forge-1.12.2-14.23.2.2625-universal
- Java version:  1.8.0_161
- Operating System: Windows 10 x64

- Plugins/Mods:
ae2stuff-0.7.0.4-mc1.12.2,appliedenergistics2-rv5-beta-1,bc-ore-processing-7.99.15-1,bdlib-1.14.3.12-mc1.12.2,binnie-mods-1.12.2-2.5.0.119,buildcraft-7.99.15,capabilityadapter-1.0,Chameleon-1.12-4.1.3,ChickenChunks-1.12.2,chiselsandbits-14.15,CodeChickenLib-1.12.2-3.1.6.339-universal,CoFHCore-1.12.2-4.3.10.5-universal,CoFHWorld-1.12.2-1.1.1.12-universal,CoinPurse-1.2.0,ComputerCraft1.80pr1,Dynmap-2.6-beta-1-forge-1.12,EconomyLite-7.0.0-2.13.0,energyconverters_1.12.2-1.0.2.0,ExtraBitManipulation-1.12-3.2.1,ExtremeReactors-1.12.2-0.4.5.46,flexiblelogin-0.18,forestry_1.12.2-5.8.0.252,Forgelin-1.6.0,foxcore-sponge-0.11.0-246-server,foxguard-sponge-0.21.0-405-server,gendustry-1.6.5.8-mc1.12.2,griefprevention-1.12.2-4.3.0.562,HttpsBank-0.0.1-SNAPSHOT,Hwyla-1.8.23-B38_1.12,ICBM-classic-1.12.2-3.0.0b17,ImmersiveEngineering-0.12-78-core,ImmersiveEngineering-0.12-78,irontank-1.7.10-1.1.15.65,jei_1.12.2-4.8.5.147,JustEnoughResources-1.12.2-0.8.5.27,Keys-1.2.1-1-g46a0267,LuckPerms-Sponge-4.1.30,MagicBees-1.12.2-3.1.9,mcjtylib-1.12-2.6.5,Mekanism-1.12.2-9.4.3.330,MyChunkloader-1.12-01,NPCs-3.0.0-MC1.12.2,Nucleus-1.3.3-S7.0-MC1.12.2-plugin,OpenComputers-MC1.12.2-1.7.2.67,PayDay-1.4.0,PlaceholderAPI-4.4,PlayerShopsRPG-2.1.0,RedProtect-7.3.0-b68-Universal,RedstoneArsenal-1.12.2-2.3.10.4-universal,RedstoneFlux-1.12-2.0.1.2-universal,rftools-1.12-7.30,rftoolsctrl-1.12-1.8.0,rftoolsdim-1.12-5.52,spongeforge-1.12.2-2611-7.1.0-BETA-2970,Stargate-Atlantiscraft-Mod-1.12.2,StorageDrawers-1.12.2-5.3.5,Tesla-1.12.2-1.0.63,ThermalCultivation-1.12.2-0.1.5.3-universal,ThermalDynamics-1.12.2-2.3.10.4-universal,ThermalExpansion-1.12.2-5.3.10.15-universal,ThermalFoundation-1.12.2-2.3.10.6-universal,UniDict-1.12.2-2.4,UniversalMarket-1.12.2-v1.2.1,UniverseGuard-2.3,unloader-1.0.1,WanionLib-1.12.2-1.5,webapi-4.10.8-S7.1,worldedit-sponge-6.1.9-SNAPSHOT-dist,yourcustompaintings-1.0.0.10,zerocore-1.12-0.1.1.0

**Issue Description**
After being open for 5-10 minutes the console spams the following message then crashes
Log:
https://gist.github.com/pdglobal/af2c80c31cc90f61f0c87471990f07ff
Crash report:
https://gist.github.com/pdglobal/aa3be3cd6d44568007f2033d4fdf4c75

**Comment by phit** [comment]
turn off verbose and verbose-errors in the sponge config for now

**Comment by pdglobal** [comment]
This is actually a computercraft bug, please disregard

**Comment by Lemmmy** [comment]
@pdglobal consider replacing ComputerCraft with CC:Tweaked - it is an updated fork of ComputerCraft by SquidDev which works *much* nicer with sponge.
