### ISSUE TITLE
Logging issues on Forge 2629+

### ISSUE THREAD

**Issue by phit** [SpongePowered/SpongeForge#2054]
**I am currently running**

- SpongeForge version: any 1.12
- Forge version: forge-1.12.2-14.23.2.2629-universal
- Java version: 1.8.181
- Operating System: Windows

- Plugins/Mods: any

**Issue Description**

Forge got some new logging changes, which don't seem to play nice with Sponge.
https://github.com/MinecraftForge/MinecraftForge/pull/4802

example https://gist.github.com/phit/ff5cc7169aaab31ddedbb791f27446d4
all plugin and vanilla logging seems to be screwed, color codes arent converted and owner of the log message is wrong

the dev log configs will need to be updated too
https://github.com/SpongePowered/SpongeForge/blob/bleeding/src/main/resources/log4j2.xml
https://github.com/SpongePowered/SpongeForge/blob/bleeding/src/main/resources/log4j2_server.xml

**Comment by phit** [comment]
looks like there are some issues on forge's end aswell https://github.com/MinecraftForge/MinecraftForge/issues/4808

**Comment by ghost** [comment]
forge issue, can be closed :)

forge build 2631 works fine
