### ISSUE TITLE
Crash/No GUI opening

### ISSUE THREAD

**Issue by jmac460** [SpongePowered/SpongeForge#2055]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2611-7.1.0-BETA-2970
- Forge version: forge-1.12.2-14.23.2.2629-universal
- Java version: 8_161
- Operating System: Windows 10

[minecraft, mcp, FML, forge, spongeapi, sponge, ae2stuff, applecore, appleskin, appliedenergistics2, avaritia, basemetals, baubles, bdlib, betterbedrockgen, betterbuilderswands, bibliocraft, botania, chameleon, chickenchunks, chisel, codechickenlib, cofhcore, cofhworld, crafttweaker, crafttweakerjei, cucumber, elevatorid, endercore, enderio, enderiobase, enderiointegrationforestry, enderiointegrationtic, enderiointegrationticlate, enderiomachines, enderioconduits, enderiopowertools, enderiointegrationftbl, enderstorage, exnihilocreatio, extrautils2, ftbl, iskalliumreactors, jei, lootbags, mantle, mcjtylib_ng, mob_grinding_utils, modtweaker, moofluids, mtlib, mysticalagradditions, mysticalagriculture, netherportalfix, nei, p455w0rdslib, plustic, randomthings, redstoneflux, rftools, roguelike, silentlib, silentgems, simplyjetpacks, stacksize, storagedrawers, tconstruct, thermalexpansion, thermalfoundation, tp, ts2k16, veinminer, veinminermodsupport, wanionlib, wct, zerocore]

Issue: when launching spongeforge, the GUI does not open, and somewhere along the line, the code stops randomly and sits at "Unloading World" 
https://images-ext-2.discordapp.net/external/io74-ssz5_6w85Q6w-v3LVLI4ELz5-_PjJYcwKJ9P9M/https/cdn.discordapp.com/attachments/228709204268023818/425091529452027924/unknown.png?width=1443&height=296

Next part shows missing items, and wants me to "/fml confirm" even though i cannot type if the gui does not come up. I can launch my world without mods, but everything gets corrupted. However when I add mods, the server refuses to start.

Log: https://gist.github.com/jmac460/efd9603da8637e3fa781d54135787286
Crash-Report: 

Please help! I've been trouble shooting this for hours, and cannot figure out why it does not work!

**Comment by jmac460** [comment]
Raw Log: https://gist.githubusercontent.com/jmac460/efd9603da8637e3fa781d54135787286/raw/d109a4c05f77977c7d98946c236961b469d174e1/Log

Also: https://gist.githubusercontent.com/jmac460/0e800be908c0c7e8ed0e20cfc205dd9e/raw/12e1cf75e95385387cb9e7782fcf1353fb65e405/gistfile1.txt

**Comment by phit** [comment]
the only issue i see in your logs is that you removed mods and have to run /fml confirm, for the logging issues there's https://github.com/SpongePowered/SpongeForge/issues/2054 which also changed the way the console worked

downgrade forge for now to a supported version
