### ISSUE TITLE
Crashing while the server was running

### ISSUE THREAD

**Issue by DrakEmono** [SpongePowered/SpongeForge#2056]
**I am currently running**

- SpongeForge version: 2555-7.1.0-BETA-2840
- Forge version: 14.23.1.2555
- Java version: 1.8
- Operating System: Windows 10
Not using the latest version because I started to use this one to test my plugins (which was the latest one when I downloaded)

- Plugins/Mods:
-Minecraft
-Minecraft Coder Pack
-Forge Mod Loader
-Minecraft Forge
-SpongeAPI
-SpongeForge
-Extended piston
-mercurius_updater

**Issue Description**
The server simply crashed. I was just reading my console at this moment.

https://gist.github.com/DrakEmono/6b01a32d38b2ce66b4943df8a99562f4

**Comment by phit** [comment]
update to latest recommended version 2870 and provide the full log prior to the crash

**Comment by phit** [comment]
no reply and not enough information to go off, if this happens again provide the information that was asked for and I'll reopen the issue
