### ISSUE TITLE
Server Stops Loading

### ISSUE THREAD

**Issue by jmac460** [SpongePowered/SpongeForge#2057]
I am currently running

    SpongeForge version: spongeforge-1.12.2-2611-7.1.0-BETA-2970
    Forge version: forge-1.12.2-14.23.2.2629-universal
    Java version: 8_161
    Operating System: Windows 10

[minecraft, mcp, FML, forge, spongeapi, sponge, ae2stuff, applecore, appleskin, appliedenergistics2, avaritia, basemetals, baubles, bdlib, betterbedrockgen, betterbuilderswands, bibliocraft, botania, chameleon, chickenchunks, chisel, codechickenlib, cofhcore, cofhworld, crafttweaker, crafttweakerjei, cucumber, elevatorid, endercore, enderio, enderiobase, enderiointegrationforestry, enderiointegrationtic, enderiointegrationticlate, enderiomachines, enderioconduits, enderiopowertools, enderiointegrationftbl, enderstorage, exnihilocreatio, extrautils2, ftbl, iskalliumreactors, jei, lootbags, mantle, mcjtylib_ng, mob_grinding_utils, modtweaker, moofluids, mtlib, mysticalagradditions, mysticalagriculture, netherportalfix, nei, p455w0rdslib, plustic, randomthings, redstoneflux, rftools, roguelike, silentlib, silentgems, simplyjetpacks, stacksize, storagedrawers, tconstruct, thermalexpansion, thermalfoundation, tp, ts2k16, veinminer, veinminermodsupport, wanionlib, wct, zerocore]

Game refuses to load past the following : https://gist.githubusercontent.com/jmac460/1b2e3d81e81dee6bff16018c3c8c6612/raw/ea0c3d3d023b1ce7b3d285b8914d52f81e013109/Log

Seriously dont know whats going on. The world I am loading has pre-made structures that I am trying to preserve. But, nothing is working.

**Comment by phit** [comment]
you can't just expect to drop a modlist here, no context and us somehow to figuring out what the issue is, first try a supported forge version that being 2611 for your release

**Comment by jmac460** [comment]
Just curious, why would the Watchdog value be set to -1? And on line 81, it wants to do the itemstack conversion. Is this meant to be, or is this an issue? I will attempt with Forge 2611, but I previously had an issue with that as well.

**Comment by phit** [comment]
you have set that value yourself in the `server.properties`.. fix it, line 81 is something with startup so no idea what you are talking about

**Comment by jmac460** [comment]
Okay, I will fix that. Did not know i somehow changed the server.properties file, but i will look into it

**Comment by jmac460** [comment]
There is not a value in my server.properties file with a value of -1

**Comment by phit** [comment]
what is `max-tick-time` set to?

**Comment by jmac460** [comment]
60000 is the value

**Comment by phit** [comment]
¯\\_(ツ)_/¯ either way that error is not gonna make your server not start

**Comment by jmac460** [comment]
Okay. So what should I do, I have the current forge version installed now, and it still does not start.

**Comment by phit** [comment]
in the log you provided the server finished its startup
> `[13:01:06] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Done (11.005s)! For help, type "help" or "?"`

**Comment by jmac460** [comment]
Okay, but why does the GUI not pop up? It makes it where I cannot type any command.

**Comment by phit** [comment]
there is no GUI in Sponge, please refer to our docs
https://docs.spongepowered.org/stable/en/server/getting-started/launch-script.html

**Comment by jmac460** [comment]
https://images-ext-1.discordapp.net/external/U8MTtIbjOjpCdVNcX4cR-ohymd7Xe4W_tgZtmFqth1o/https/cdn.discordapp.com/attachments/228709204268023818/425116317285351434/unknown.png

This is what iam referring to, this never pops up.

**Comment by phit** [comment]
seriously read the page i just linked, there is no GUI with Sponge
to quote
> **Note**
>The default Minecraft server GUI console is disabled by Sponge, because it is very processor-intensive.

**Comment by jmac460** [comment]
https://cdn.discordapp.com/attachments/228709204268023818/425373524882882560/unknown.png

It did not load for me. I see what you are saying, but when i launch without mods, the GUI pops up. Thats why I have been asking why it has not, because it previously did when i launched without mods.

**Comment by bloodmc** [comment]
This has nothing to do with sponge, set `max-tick-time` properly.

**Comment by jmac460** [comment]
It is properly set... its at 60000.
