### ISSUE TITLE
Some mods have Crafting Tables without CraftingOutputSlot

### ISSUE THREAD

**Issue by JoeSGT** [SpongePowered/SpongeForge#2058]
**I am currently running**

- SpongeForge version:  1.12.2-2611-7.1.0-BETA-2974
- Forge version:  1.12.2-14.23.2.2624 
- Java version:  8
- Operating System: windows 10

- Plugins/Mods:
CodeChickenLib-1.12.2-3.1.6.339-universal 
Avaritia-1.12-3.2.0.13-universal

**Issue Description**
Made a quick test server then place down a Extreme Crafting table then look in console you will get this error message 
https://pastebin.com/8pQhkBTN

**Comment by Zidane** [comment]
@Faithcaio 

Status?

**Comment by Faithcaio** [comment]
Stacktrace from another mod: https://pastebin.com/raw/kFu0Nci4
___

This happens because we fail to find the CraftingOutputSlot of a CraftingInventory.

If you don't care about Crafting events you can ignore this error.

**Comment by Tommeh1** [comment]
It can however crash the client in some cases

**Comment by Faithcaio** [comment]
Show me logs then. 
But it should not cause crashes as we literally just ignore the crafting inventory when this error comes up.
