### ISSUE TITLE
Baubles not kept on death with `DestructEntityEvent.Death#setKeepInventory(true)`

### ISSUE THREAD

**Issue by Rasmun** [SpongePowered/SpongeForge#2061]
**I am currently running**
- SpongeForge version: 1.12.2-2611-7.1.0-BETA-2931
-  Forge version: FTBserver-1.12.2-14.23.2.2618-universal
-  Java version: 8 Update 161 for 64bit
-  Operating System: Windows 2012

**Plugins/Mods:**
[11:54:28] [Server thread/INFO] [nucleus]: Server ran the command: /sponge plugi
ns
[11:54:28] [Server thread/INFO]: Plugins (15): Minecraft, Minecraft Coder Pack,
SpongeAPI, SpongeForge, AurionsVoteListener, Enjin Minecraft Plugin, GriefPreven
tion, LuckPerms, MagiBridge, NuVotifier, Nucleus, PlaceholderAPI, Total Economy,
 VirtualChest, WorldEdit

**Issue Description**
1) Run the following command:
/lp user {name} permission set nucleus.inventory.keepondeath true
2) Have the player character drop from a high height in the overworld to die.
Results:
User keeps inventory & armor, but baubles are no longer on the user's character. A grave is created with the baubles.

Created an issue with Nucleus, but they indicated:

> This isn't technically a Nucleus problem, as it's simply using 
`DestructEntityEvent.Death#setKeepInventory(true). `
> This should be reported to SpongeForge as this is a mod incompatibility with this event.

Is this something you can assist with?  Thanks.

**Comment by ryantheleach** [comment]
From memory, setKeepInventory should be following the same semantics as the gamerule.

What happens if you have the gamerule setKeepInventory on true, without Sponge with this mod?

**Comment by JoeSGT** [comment]
it seem this same issue that is causing a Duplication bug using Soul Bound enchantment from EnderIO as Dualspiral mention me this issue

**Comment by Rasmun** [comment]
@ryantheleach the gamerule works fine in single player, without Sponge or Nucleus.  On our server that have both Sponge & Nucleus, we have the issue.  Does that help?

**Comment by Zidane** [comment]
Tested on latest SpongeForge and I kept my bauble with setting that to keep inventory to true via the death event.
