### ISSUE TITLE
SpongeForge + Age Of Engineering problem

### ISSUE THREAD

**Issue by TripleZ0** [SpongePowered/SpongeForge#2064]
**I am currently running**

- SpongeForge version: 1.10.2-2477-5.2.0-BETA-2793
- Forge version: 1.10.2-12.18.3.2511
- Java version: 1.8.0_162
- Operating System: Win 7 64bit

- Plugins/Mods: Age Of Engineering modpack
Extra Plugins: LuckPerms + Nucleus

**Issue Description**
Win 7 64bit:
I can't start the server. I included a crash log. If I remove SpongeForge server starts fine.

Debian Stretch:
Server starts with SpongeForge but after an hour or two it just hangs.
Players get timed out. The console still alive but can't execute any commands.
I can see the process running. CPU usage is 0 when this happens.  Have to kill it and start again.
No crash log. Tried running Java in debug mode couldn't see any issue.

Crash log:
https://gist.github.com/TripleZ0/403e73652b5b15d4b624115942c55635

Server Log:
https://gist.github.com/TripleZ0/403e73652b5b15d4b624115942c55635

Thank you in advance!

**Comment by kashike** [comment]
As of January we no longer support 1.10.

If you can reproduce this issue with SpongeForge for Minecraft 1.12.2 please [open a new issue](https://github.com/SpongePowered/SpongeForge/issues/new).
