### ISSUE TITLE
DataSerializableTypeSerializer - IllegalArgumentException - ItemStack NBT

### ISSUE THREAD

**Issue by Sir-Will** [SpongePowered/SpongeForge#2068]
**I am currently running**
- SpongeForge version: 1.12.2-2611-7.1.0-BETA-2990
- Forge version: 1.12.2-14.23.2.2631

**Issue Description**
Getting the `java.lang.IllegalArgumentException: Configuration does not accept objects of type class [B` error when trying serialize a itemstack with this NBT data (both items cause the error):
![](https://i.imgur.com/cbzSDIc.jpg)

```java
			CommentedConfigurationNode node = loader.createEmptyNode();
			node.setComment("Kit " + kit.getName());
			node.getNode("Cooldown").setValue(TypeToken.of(Duration.class), kit.getCooldown());
line 210	->	node.getNode("Contents").setValue(new TypeToken<List<ItemStack>>() {
			}, kit.getContents());
			loader.save(node);
```

Full error: https://pastebin.com/YWvUYdCP

**Comment by phit** [comment]
~move to sc

**Comment by limbo-app** [comment]
Hey @Sir-Will! I've moved your issue to [SpongePowered/SpongeCommon#1874](https://github.com/SpongePowered/SpongeCommon/issues/1874).
