### ISSUE TITLE
ItemFishedEvent doesn't appear to be working when SpongeForge is included.

### ISSUE THREAD

**Issue by Kitsune30** [SpongePowered/SpongeForge#2069]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2611-7.1.0-BETA-2963
- Forge version: forge-1.12.2-14.23.2.2611-universal
- Java version: Java 8 JRE 1.8.0_152
- Operating System: Windows 10

- Plugins/Mods: Just Sponge and my Test Mod (included at the bottom of the post)

**Issue Description**
Started a clean Forge server.
Ran it once with no mods, tested fishing. Worked as normal.
Restarted server with my Test mod added. Fishing worked as normal. Test mod output "ItemFished occurred" to console.
Restarted with SpongeForge and my Test mod added. Fishing appeared to work as normal (Item jumps out of water towards player). Test mod did not output to console.

Latest Log: https://gist.github.com/Kitsune30/59d8841c4486b24418df3c8dbf4d7ff4
My Test Mod Source: https://gist.github.com/Kitsune30/07d40376f6000233aca2f920618c5183

**Comment by Zidane** [comment]
You may have fishies again as of that commit.

**Comment by Kitsune30** [comment]
Woo! Thank you!
