### ISSUE TITLE
Spongeforge server worldgen crash

### ISSUE THREAD

**Issue by Meesmaalt** [SpongePowered/SpongeForge#2072]
- SpongeForge version: spongeforge-1.12.2-2611-7.1.0-BETA-2996
- Forge version: forge-1.12.2-14.23.2.2611-universal
- Java version: openjdk version "1.8.0_151"
- Operating System: SMP Debian 4.9.30-2+deb9u5 (2017-09-19) x86_64 GNU/Linux

- Plugins/Mods: https://imgur.com/a/pWyUv

**Issue Description**
Going near 0;0 crashes server, error messages spam like crazy.
When i disable spongeforge and use normal forge, chunk loads fine.
is there a config option that tells spongeforge to not interfere with wordgen?

Error log:
https://pastebin.com/4qie7D3a

**Comment by Zidane** [comment]
No and OTG will never work correctly with SpongeForge as they circumvent several Forge subsystems such as the DimensionManager.
