### ISSUE TITLE
Right click crash

### ISSUE THREAD

**Issue by xxlio109** [SpongePowered/SpongeForge#2073]
SpongeForge version: spongeforge-1.12.2-2611-7.1.0-BETA-2996

Forge version: forge-1.12.2-14.23.2.2611-universal

Java version: openjdk version "1.8.0_161"

Operating System: centos 7

Plugins/Mods: 
SpongeAPI, SpongeForge, Actually Additions, Advanced Generators, BD Lib, Baubles, Bed Patch, BedFix, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Blood Magic: Alchemical Wizardry, Botania, Brandon's Core, CoFH Core, CoFH World, CodeChicken Lib, Cyclops Core, Draconic Evolution, Epic Siege Mod, Erebus, EvilCraft, EvilCraft-Compat, FTB Utilities, FTBLib, Forestry, Galacticraft Core, Galacticraft Planets, Guide-API, Immersive Engineering, Improved Extraction, Industrial Foregoing, IndustrialCraft 2, Iron Chest, Just Enough Items, MJRLegendsLib, Mantle, Mekanism, MekanismGenerators, MekanismTools, Micdoodle8 Core, More Planets, NetherPortalFix, NuclearCraft, OMLib, Open Modular Passive Defense, Open Modular Turrets, Planet Progression, PlusTiC, Reborn Core, Redstone Flux, Reforged, Shadowfacts' Forgelin, TESLA, Tech Reborn, Tesla Core Lib, Tesla Core Lib Registries, The Betweenlands, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Tinker I/O, Tinkers' Construct, UniDict, WanionLib
Issue Description
Right click item: improvedextraction:auto_cutting_table  crash

Error log:
https://gist.github.com/xxlio109/095e70a9bbe8142d450ec2bbcdcd25ee

**Comment by Zidane** [comment]
I would look ito what this mod is doing, it is causing some massive recursion

	at ru.poopycoders.improvedextraction.tile.TileEntityCuttingTable.func_189515_b(TileEntityCuttingTable.java:48)
