### ISSUE TITLE
Sevtech Modpack - Better Advancements Issue with Progression

### ISSUE THREAD

**Issue by alicheek** [SpongePowered/SpongeForge#2075]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2611-8.0.0-BETA-2993.jar
- Forge version: forge-1.12.2-14.23.2.2635-universal.jar
- Java version: Java openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

- Operating System: CentOS release 6.8 (Final)

- Plugins/Mods:

Sevtech Modpack 3.0.4

**Issue Description**
So the issue is to do with Better Advancments for the progression of the modpack, a player will be able to complete quests but the items which or forbidden origionally will still stay forbidden, so for instance if slot 8 in my inventory is highlighted i will be able to puck up the item but as soon as i move over to slot 1 it will drop out the item and say I am not able to use this item yet. 

I have tested with out sponge and do not have this problem but when sponge is installed this will occur

One Error i did see on joining: https://pastebin.com/kdtm39Fq

**Comment by dualspiral** [comment]
I notice you’re using the experimental builds. Does the same issue occur with stable builds?

https://www.spongepowered.org/downloads/spongeforge/stable/1.12.2

**Comment by alicheek** [comment]
Yes updating to that version solved the issue @dualspiral  Thanks for that :)
