### ISSUE TITLE
Chunks in CompactMachines world don't save with Sponge

### ISSUE THREAD

**Issue by Sir-Will** [SpongePowered/SpongeForge#2076]
The chunks in the region files of the compact machines world don't get saved when sponge is running (Region file gets created but always empty).

Steps to reproduce:
- Start a server with CompactMachines and SpongeForge installed
- Create a compact machine by placing one of the blocks and interacting with the Personal Shrinking Device
- Restart the server and you will see that the chunks were not saved

Doing the same steps without sponge works without any issues.

spongeforge-1.12.2-2611-7.1.0-BETA-2990
compactmachines3-1.12.2-3.0.7-b197

**Comment by bloodmc** [comment]
Paste your entire sponge global config.

**Comment by Sir-Will** [comment]
It's default configuration: https://pastebin.com/tKi7AyER

**Comment by phit** [comment]
https://github.com/SpongePowered/SpongeForge/commit/c45b1b179c58e3c78e761e27a567a64397a65237

**Comment by Sir-Will** [comment]
Works now, thanks.
