### ISSUE TITLE
tileentity-activation per-mod override requires all tiles 

### ISSUE THREAD

**Issue by Sir-Will** [SpongePowered/SpongeForge#2077]
If you create a entry in tileentity-activation.mods for a mod and don't add all tiles then all not listed tile ents never tick/activate.
So the only way to use this right now is to have auto-populate always enabled.

Would be great if not listed tiles use the default configuration.

**Comment by bloodmc** [comment]
This issue doesn't make any sense as auto-populate doesn't add all TE's to config immediately. You definitely entered the entry wrong in the config which is why it didn't work properly.

**Comment by bloodmc** [comment]
So after speaking to Sir-Will, he clarified that auto-populate is not related to issue and you simply have to add a single TE from a mod to have the bug occur. I confirmed this is indeed a bug. Fix will be coming shortly.

**Comment by bloodmc** [comment]
Proper fix in commit https://github.com/SpongePowered/SpongeCommon/commit/56677bd93203e54ebebac6efaa535e9fb2b34014
