### ISSUE TITLE
Forge EntityMobGriefingEvent broke GriefingData

### ISSUE THREAD

**Issue by Cybermaxke** [SpongePowered/SpongeForge#2078]
With the implementation of the `EntityMobGriefingEvent` in forge are the `GriefingData` mixin injections broken:
EntityMobGriefingEvent PR: https://github.com/MinecraftForge/MinecraftForge/pull/4710
Original GriefingData impl PR: https://github.com/SpongePowered/SpongeCommon/pull/432

**Comment by parlough** [comment]
A few other mixins were broke as well, will hopefully have some time tonight to work on the recent Forge changes.
