### ISSUE TITLE
SpongeForge doesn't load with latest Forge

### ISSUE THREAD

**Issue by demon57730** [SpongePowered/SpongeForge#2080]
spongeforge-1.12.2-2611-7.1.0-BETA-3002.jar

forge-1.12.2-14.23.2.2654-universal.jar

https://pastebin.com/9nA6B0Rg

not compatible with the latest version of forge

**Comment by demon57730** [comment]
for info the last version of forge solved full of bug, he even solved the problem of connection.

**Comment by gabizou** [comment]
As me mentioned in the docs, [try to match forge versions](https://docs.spongepowered.org/stable/en/server/getting-started/implementations/spongeforge.html?highlight=forge#reading-the-download-filename). Forge had a few breaking changes that requires many fixes to bring back compatibility.

**Comment by demon57730** [comment]
ok my question is simple will you release a spongrforge version compatible with the forge version I wrote ??

**Comment by gabizou** [comment]
Yes, in due time.

**Comment by phit** [comment]
reopened this until this is resolved, to hopefully avoid a bunch of other duplicates

**Comment by gabizou** [comment]
Fixed in build 3024.
