### ISSUE TITLE
Entities in every dimension except spawn world invincible

### ISSUE THREAD

**Issue by DragaoNimhe** [SpongePowered/SpongeForge#2081]
**I am currently running**
- SpongeForge version: 1.12.2-7.1.0 (beta-2990), but this problem persists on all versions of 1.12.2-7.1.0 that we have tried
- Forge version: 1.12.2-14.23.2.2611
- Java version: openjdk version "1.8.0_161"
- Operating System: CentOS 7.4.1708

**Plugins/Mods:**
While we are using plugins, the problem persists without any of the plugins present. However, these are the plugins we use.
- Aurion Vote Listener 1.0.9
- GriefPrevention 1.12.2-4.3.0.562
- LuckPerms-4.0.141
- MMCRestrict-1.4.1
- Nucleus-1.3.1
- nuvotifier-universal-2.3.6
- Prism-3.0.0-beta2
- ProjectCore-0.2.2
- ProjectWorld-0.12.2
- UniverseGuard-2.7
- https://www.atlauncher.com/pack/MechMagic - This is the full mod list. The issue is not present in single player, only on a server with sponge.

**Issue Description**
Hey there, I looked through all open issues and was unable to find another similar to mine, I apologize if this has been brought up already. I'm a developer for the Mech and Magic modpack on ATLauncher, and we're getting ready to launch a server for the pack. We are running into a major issue, however; all entities that are not in the initial spawn world will not drop in hearts or die when attacked. They appear to "die" repeatedly, as in they drop loot as if they have died every couple of hits, but do not actually die. We are able to damage mobs normally within the "main" world, but not in any other dimension. The main developer for the pack is also hosting a server, and he is having the exact same issue. (All dimensions we have tried are affected: I.E. - Nether, End, Deep Dark, Twilight Forest, as well as other overworlds added with a multiverse plugin (multiverse plugin only in use on 1 of the 2 servers in question.)

When a mob is attacked, it does not cause any errors or logs to occur in console or the files. We have loaded the server without any plugins at all and the issue still persists, so it's not due to a plugin we are using. I can post any further information you require, and any help with this issue would be greatly appreciated.

- Boot Log (plugins present)
https://gist.github.com/DragaoNimhe/d822a1611fc03ab3f3059dd1bbf79875

- Detailed Boot Log (no plugins present)
https://gist.github.com/DragaoNimhe/d8a18420a11abe1b42fdee23b28388da

**Comment by Y0ungSandwich** [comment]
This appears to have been fixed in sponge version:
spongeforge-1.12.2-2611-7.1.0-BETA-2990 
and/or in Mech & Magic version:
2.0.7

**Comment by DragaoNimhe** [comment]
Can confirm the newest version of Mech and Magic has fixed the issue, so wherever the conflict was, it's gone now! Thanks y0ung!
