### ISSUE TITLE
Mixin Crash

### ISSUE THREAD

**Issue by marineomi0204** [SpongePowered/SpongeForge#2082]
What I'm running:
- SpongeForge version: 1.12.2
- Forge version: 1.12.2 - 14.23.2.2611 
- Java version: Latest? Version 8 I believe
- Operating System: Windows

- Mods: _Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AngelRing 2 Bauble, Animania, Bailey's Dailies, Baubles, BiblioCraft, Biomes O' Plenty, Botania, Chameleon, CodeChicken Lib, CraftStudio API, CustomNPCs, DrZhark's CustomSpawner, DrZhark's Mo'Creatures Mod, Extra Utilities 2, Fairy Lights, Foamflower, Garden Stuff, Gravestone Mod, Inventory Pets, Iron Chest, JourneyMap, Just Enough Items, Just a Few Fish, Magic Clover, Minecraft Comes Alive, More Shearables, Morph, MrCrayfish's Furniture Mod, Not Enough Items, Pam's Get all the Seeds!, Pam's HarvestCraft, Pam's Simple Recipes, Pam's Weee! Flowers, RadixCore, Reliquary, The Twilight Forest, Tree Chopper, Uncrafting Table, Vending, iChunUtil_
-Plugin: holograms

Issue:
For some reason when my friend was on my modded minecraft server her game crashed and read this: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException
OpenAL library. I did read a thread addressing this issue but it was closed. I have none of the mods that the thread stated conflicted with this. We have the same version of forge, but she does not have SpongeForge as I am the one running the server. I did not get get this crash (but five minutes later my game did crash, I have no idea why). I'm afraid I can't explain this any better as I don't have any other information.

**Comment by phit** [comment]
gonna need a log file or crash report

**Comment by phit** [comment]
no reply, closed for now
