### ISSUE TITLE
Server crashing since forge 2646

### ISSUE THREAD

**Issue by broeredaan** [SpongePowered/SpongeForge#2085]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2611-7.1.0-BETA-3004
- Forge version: forge-1.12.2-14.23.2.2646-universal
- Java version: 8
- Operating System: Linux/Windows

- Plugins/Mods: None

**Issue Description**
I tried to update my SevTech Ages server today which has the newest forge version 2654. However this crashed an gave an error with incompatibility sponge issues. I have since tried older version of forge and from what I found it started at forge 2646. Would be nice if we can use it again with the newest forge version :)
Sidenote I have also tried the recommende spongeforge 2990. And the same happens here.

Forge 2646
https://gist.github.com/broeredaan/8118dff3f8c353ac75498553ee43c35a
Forge 2654
https://gist.github.com/broeredaan/be3de11b167dc2328d35dfd519c8a60b

**Comment by phit** [comment]
https://github.com/SpongePowered/SpongeForge/issues/2080
