### ISSUE TITLE
Unable to load the spongeforge

### ISSUE THREAD

**Issue by 892279645** [SpongePowered/SpongeForge#2086]
**I am currently running**

- SpongeForge version: 1.12.2-2611-7.1.0-BETA-2990
- Forge version: 14.23.2.2654
- Java version: 1.8.0_162
- Operating System:Linux

- Plugins/Mods:BetterBedrockGenerator,infinimend,TabModifier,PotionFingers,shulkerbox,SimilsaxTranstr,ctors,Tesla,AppleSkin,HatStand,owls,EnchantingTable,DailyRewards,Aroma1997s-Dimensional-World,AutoRegLib,OnlinePicFrame,SimpleQuarry,presentstand,ElevatorMod,Baubles,ChickenChunks,Traverse,Currency,CarryOn,Hats,WirelessCraftingTerminal,p455w0rdslib,IronBackpacks,Aroma1997Core,japaricraftmod,davincisvessels,iChunUtil,CodeChickenLib,CreativeCore,CyclopsCore,WaterPower,tesla-core-lib,industrialforegoing,ironchest,HammerCore,holograms,LuckPerms,movingworld,worldedit,appliedenergistics2,Forgelin,Nucleus,buildcraft,forestry,twilightforest,BiblioCraft,industrialcraft,Botania

**Issue Description**
Today, when I restart the server as usual, the server is unable to start and there is no crash log.
I don't know what happened, when I deleted spongeforge, I could start my server again, but I couldn't load the sponge plugin.
How do I reload spongeforge?
日志:https://github.com/892279645/test/files/1886474/latest.log

**Comment by phit** [comment]
downgrade forge, see https://github.com/SpongePowered/SpongeForge/issues/2080
