### ISSUE TITLE
Cause Stack poisoning on InteractBlockEvent based on proximity

### ISSUE THREAD

**Issue by codeHusky** [SpongePowered/SpongeForge#2087]
*Based on information from another user, currently not confirmed by yours truly.*
**I am currently running**

![image](https://user-images.githubusercontent.com/6946558/38458702-b9140ffc-3a66-11e8-9d75-c81b0f1112a6.png)
- Java version:
![image](https://user-images.githubusercontent.com/6946558/38458734-314f7498-3a67-11e8-88d3-df173597d9ce.png)

- Operating System: Linux
![image](https://user-images.githubusercontent.com/6946558/38458728-240d9436-3a67-11e8-8adf-6e514f783f94.png)

- Plugins/Mods:
  - HuskyCrates v2.0.0-PRE5
  - HuskyUI v0.5.2 PRE
![image](https://user-images.githubusercontent.com/6946558/38458755-6e6f472c-3a67-11e8-85df-39d2c7b46a30.png)
![image](https://user-images.githubusercontent.com/6946558/38458758-71eab2c4-3a67-11e8-9e94-5b17217dc9e6.png)

**Issue Description**
Player B stands on top of block (a crate) and interacts with this crate. The crate is set to `instant`. Player A uses 5 keys,. All 5 items are given to the Player A and also 1 of the items is given to the Player B for no reason. Player B did not interact with the crate/block.

**Comment by gabizou** [comment]
Can you show us some example code or some debugging information as to what events are causing the player b to show up as being rewarded?

**Comment by codeHusky** [comment]
As far as I've been able to tell, Sponge is firing InteractBlockEvent twice for some reason. I don't know exactly why this is happening or what's causing it as I haven't been able to isolate the problem.

**Comment by Faithcaio** [comment]
InteractBlockEvent fires twice because you have a main and offhand.
So you're getting e.g.
`InteractBlockEvent.Primary.MainHand` and
`InteractBlockEvent.Primary.OffHand`

**Comment by codeHusky** [comment]
@Faithcaio 
`public void openCrateBlock(InteractBlockEvent.Secondary.MainHand event, @Root Player player){`
Signature, so that isn't why.

**Comment by codeHusky** [comment]
The other guy wasn't able to reproduce this issue and I haven't been able to either. Doesn't seem to be a particularly reliable bug, if it is one.

**Comment by codeHusky** [comment]
Okay, i'll clear this up.

So, in my plugin, I use `%p` as the player's username and `%P` as the player's uuid.

Someone had mistakenly used `@p` in their config, and that seems to be what was happening. Oops.
If this happens again I'll reopen the issue, but it seems to be user error.
