### ISSUE TITLE
Server Crash when loading certain area (something with Woodland Mansion)

### ISSUE THREAD

**Issue by Lorrainrm** [SpongePowered/SpongeForge#2088]
**sponge 2990**

- SpongeForge version: 2990
- Forge version: 2611 i guess
- Java version: 8
- Operating System: linux

---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (spongeforge-1.12.2-2611-7.1.0-BETA-2990.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 4/8/18 1:54 AM
Description: Exception preparing structure feature

java.lang.NullPointerException: Exception preparing structure feature
	at net.minecraft.world.gen.ChunkGeneratorOverworld.func_185978_a(ChunkGeneratorOverworld.java:283)
	at net.minecraft.world.gen.ChunkGeneratorOverworld.func_185976_a(ChunkGeneratorOverworld.java:119)
	at net.minecraft.world.gen.structure.WoodlandMansion$Start.func_191092_a(SourceFile:99)
	at net.minecraft.world.gen.structure.WoodlandMansion$Start.<init>(SourceFile:92)
	at net.minecraft.world.gen.structure.WoodlandMansion.func_75049_b(SourceFile:80)
	at net.minecraft.world.gen.structure.MapGenStructure.func_180701_a(MapGenStructure.java:40)
	at net.minecraft.world.gen.MapGenBase.func_186125_a(SourceFile:34)
	at net.minecraft.world.gen.ChunkGeneratorOverworld.func_180514_a(ChunkGeneratorOverworld.java:624)
	at org.spongepowered.common.world.gen.SpongeChunkGenerator.func_180514_a(SpongeChunkGenerator.java:505)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:102)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:726)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.gen.ChunkGeneratorOverworld.func_185978_a(ChunkGeneratorOverworld.java:283)
	at net.minecraft.world.gen.ChunkGeneratorOverworld.func_185976_a(ChunkGeneratorOverworld.java:119)
	at net.minecraft.world.gen.structure.WoodlandMansion$Start.func_191092_a(SourceFile:99)
	at net.minecraft.world.gen.structure.WoodlandMansion$Start.<init>(SourceFile:92)
	at net.minecraft.world.gen.structure.WoodlandMansion.func_75049_b(SourceFile:80)

-- Feature being prepared --
Details:
	Is feature chunk: True
	Chunk location: 23,-32
	Chunk pos hash: -137438953449
	Structure type: net.minecraft.world.gen.structure.WoodlandMansion
Stacktrace:
	at net.minecraft.world.gen.structure.MapGenStructure.func_180701_a(MapGenStructure.java:40)
	at net.minecraft.world.gen.MapGenBase.func_186125_a(SourceFile:34)
	at net.minecraft.world.gen.ChunkGeneratorOverworld.func_180514_a(ChunkGeneratorOverworld.java:624)
	at org.spongepowered.common.world.gen.SpongeChunkGenerator.func_180514_a(SpongeChunkGenerator.java:505)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:102)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150)

-- Sponge PhaseTracker --
Details:
	Cause Stack: [Empty stack]
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zjg000(MinecraftServer.java:3987)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:887)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:370)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:552)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 3.14.32-xxxx-grs-ipv6-64
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3624469336 bytes (3456 MB) / 7379353600 bytes (7037 MB) up to 7379353600 bytes (7037 MB)
	JVM Flags: 2 total; -Xmx7168M -Xms7168M
	IntCache: cache: 0, tcache: 8, allocated: 20, tallocated: 86
	FML: MCP 9.42 Powered by Forge 14.23.2.2635 59 mods loaded, 59 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                           | Version                     | Source                                      | Signature                                |
	|:--------- |:---------------------------- |:--------------------------- |:------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft                    | 1.12.2                      | minecraft.jar                               | None                                     |
	| UCHIJAAAA | mcp                          | 9.42                        | minecraft.jar                               | None                                     |
	| UCHIJAAAA | FML                          | 8.0.99.99                   | forge.jar                                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                        | 14.23.2.2635                | forge.jar                                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | spongeapi                    | 7.1.0-SNAPSHOT-06016f2      | spongeforge-1.12.2-2611-7.1.0-BETA-2990.jar | None                                     |
	| UCHIJAAAA | sponge                       | 1.12.2-2611-7.1.0-BETA-2990 | spongeforge-1.12.2-2611-7.1.0-BETA-2990.jar | None                                     |
	| UCHIJAAAA | cmdcontrol                   | 1.1.0                       | CmdControl-s7.1-v1.1.0 (1).jar              | None                                     |
	| UCHIJAAAA | cmdbuilder                   | 1.2.0                       | CmdBuilder-s7.1-v1.2.0.jar                  | None                                     |
	| UCHIJAAAA | antiwdl                      | 1.1                         | AntiWDL-1.1-all.jar                         | None                                     |
	| UCHIJAAAA | categorycommands             | 1                           | CategoryCommands-1.12.2-1.0.0.jar           | None                                     |
	| UCHIJAAAA | changeskin                   | 3.1-1f61556                 | ChangeSkinSponge.jar                        | None                                     |
	| UCHIJAAAA | commanditems                 | 1.0                         | CommandItems-1.5.jar                        | None                                     |
	| UCHIJAAAA | crazyfeetsponge              | 1.14                        | crazyfeet-sponge-Api-7-1.14.jar             | None                                     |
	| UCHIJAAAA | customnpcs                   | 1.12                        | CustomNPCs_1.12.224mar18snapshot.jar        | None                                     |
	| UCHIJAAAA | dailyrewards                 |                             | DailyRewards-api7-1.2.2.jar                 | None                                     |
	| UCHIJAAAA | dynmap                       | 2.6-beta-1-3                | Dynmap-2.6-beta-1-forge-1.12.jar            | None                                     |
	| UCHIJAAAA | de_yottaflops_easyscoreboard | 2.3                         | EasyScoreboards.jar                         | None                                     |
	| UCHIJAAAA | economylite                  | 2.13.0                      | EconomyLite-7.0.0-2.13.0.jar                | None                                     |
	| UCHIJAAAA | enjin-minecraft-plugin       | 3.4.3-sponge7               | EMPSponge7.jar                              | None                                     |
	| UCHIJAAAA | griefprevention              | 4.3.0                       | griefprevention-1.12.2-4.3.0.568.jar        | None                                     |
	| UCHIJAAAA | flexiblelogin                | 0.16.8                      | flexiblelogin-0.16.8.jar                    | None                                     |
	| UCHIJAAAA | pixelmon                     | 6.2.3                       | Pixelmon-1.12.2-6.2.3-server.jar            | None                                     |
	| UCHIJAAAA | formedit                     | 1.0.0                       | FormEdit-1.0.jar                            | None                                     |
	| UCHIJAAAA | spongecommandcooldown        | 1.0                         | GlobalCooldown1.4.jar                       | None                                     |
	| UCHIJAAAA | nucleus                      | 1.3.6-S7.0                  | Nucleus-1.3.6-S7.0-MC1.12.2-plugin.jar      | None                                     |
	| UCHIJAAAA | placeholderapi               | 4.4                         | PlaceholderAPI-4.4.jar                      | None                                     |
	| UCHIJAAAA | nucleus-gluon                | 1.0.4                       | Gluon-1.0.4.jar                             | None                                     |
	| UCHIJAAAA | gts                          | 3.7.2-S7.1                  | GTS-3.7.2-S7.1.jar                          | None                                     |
	| UCHIJAAAA | holograms                    | 3.1                         | holograms-3.1.jar                           | None                                     |
	| UCHIJAAAA | hypermodbanner               | 3.3.0                       | HyperModBanner-1.12.2-3.3.0.jar             | None                                     |
	| UCHIJAAAA | luckperms                    | 4.1.57                      | LuckPerms-Sponge-4.1.57.jar                 | None                                     |
	| UCHIJAAAA | mmcprefix                    | 1.2.1                       | MMCPrefix-1.2.1-API7.jar                    | None                                     |
	| UCHIJAAAA | nbtedit                      | 1.11.2-2.0.2                | NBTEdit-1.12-2.0.2.jar                      | None                                     |
	| UCHIJAAAA | pixelannouncer               | 1.1.0                       | PixelAnnouncer-1.12.2-1.1.0.jar             | None                                     |
	| UCHIJAAAA | pixelautomessages            | 1.0.3                       | PixelAutoMessages-1.0.3-b15.jar             | None                                     |
	| UCHIJAAAA | pixelextras                  | 2.3.5                       | PixelExtras-1.12.2-2.3.5-universal.jar      | None                                     |
	| UCHIJAAAA | pixelhunt                    | 1.1                         | PixelHunt-1.1-MC1.12.2-F2611-S7.1.0.jar     | None                                     |
	| UCHIJAAAA | pixelmoneconomybridge        | 1.2.2                       | PixelmonEconomyBridge-1.12.2-1.3.0.jar      | None                                     |
	| UCHIJAAAA | pixelmoney                   | 2.1.0                       | PixelMoney-1.12.2-2.1.0.jar                 | None                                     |
	| UCHIJAAAA | pixelshout                   | 1.2.0                       | PixelShout-1.12.2-1.2.0-universal.jar       | None                                     |
	| UCHIJAAAA | pixelupgrade                 | 4.0.0 beta 1                | PixelUpgrade-1.12.2-4.0.0-beta1.jar         | None                                     |
	| UCHIJAAAA | pokedisguisemod              | 1.0                         | PokeDisguise-1.12.2-1.6.2-universal.jar     | None                                     |
	| UCHIJAAAA | pokedisguise                 | 1.6.2                       | PokeDisguise-1.12.2-1.6.2-universal.jar     | None                                     |
	| UCHIJAAAA | serverlistplus               | 3.4.8                       | ServerListPlus-3.4.8-Universal.jar          | None                                     |
	| UCHIJAAAA | shinypixelmon                | 1.6                         | ShinyPixelmon-1.12.2-1.10-universal.jar     | None                                     |
	| UCHIJAAAA | spongybackpacks              | 1.0                         | SpongyBackpacks-1.0.jar                     | None                                     |
	| UCHIJAAAA | tabmanager                   | 2.1.0-S7.0-MC1.12.2         | TabManager-2.1.0-S7.0-MC1.12.2.jar          | None                                     |
	| UCHIJAAAA | teslalibs                    | 1.0.1                       | TeslaLibs-s7.1-v1.1.0.jar                   | None                                     |
	| UCHIJAAAA | pixeltradelogger             | 1.0.0                       | TradeLogger-1.0.0.jar                       | None                                     |
	| UCHIJAAAA | trainercommands              | 2.3.1                       | TrainerCommands-1.12-2.3.1-universal.jar    | None                                     |
	| UCHIJAAAA | ultimatechat                 | 1.8.6                       | UltimateChat-1.8.6-b156-Universal.jar       | None                                     |
	| UCHIJAAAA | universalmarket              | 1.0                         | UniversalMarket-1.12.2-v1.2.1.jar           | None                                     |
	| UCHIJAAAA | variedcommodities            | 1.12.2                      | VariedCommodities_1.12.2(06nov17).jar       | None                                     |
	| UCHIJAAAA | virtualchest                 | 1.0.0-alpha                 | VirtualChest-1.0.0-alpha.jar                | None                                     |
	| UCHIJAAAA | voxelsniper                  | 8.5.0-SNAPSHOT              | VoxelSniper-8.5.0-SNAPSHOT.jar              | None                                     |
	| UCHIJAAAA | wondertrade                  | 4.5.0                       | WonderTrade-1.12.2-4.5.2-universal.jar      | None                                     |
	| UCHIJAAAA | worldedit                    | 6.1.9-SNAPSHOT              | worldedit-sponge-6.1.9-SNAPSHOT-dist.jar    | None                                     |
	| UCHIJAAAA | xppokedex                    | 0.7                         | xPPokedex-0.7-MC1.12.2-F2611-S7.1.0.jar     | None                                     |
	| UCHIJAAAA | zpixelmonplaceholders        | 1.3.1                       | zpixelmonplaceholders-1.3.1.jar             | None                                     |

	Loaded coremods (and transformers): 
SpongeCoremod (spongeforge-1.12.2-2611-7.1.0-BETA-2990.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
	Profiler Position: N/A (disabled)
	Player Count: 13 / 60; [EntityPlayerMP['RZZalky'/576, l='world', x=-3476.30, y=66.00, z=4578.30], EntityPlayerMP['TheVoid'/1562, l='world', x=-3274.24, y=244.00, z=-459.54], EntityPlayerMP['gabriel59'/1623, l='world', x=-5733.17, y=65.12, z=4941.72], EntityPlayerMP['sieugacon'/8418, l='world', x=-1317.93, y=66.00, z=840.39], EntityPlayerMP['BraesT'/11343, l='world', x=-4864.38, y=67.00, z=3989.35], EntityPlayerMP['grieblers'/13180, l='world', x=-1292.51, y=64.00, z=862.11], EntityPlayerMP['alangamer329'/14174, l='world', x=-1322.50, y=66.00, z=865.50], EntityPlayerMP['jspadafora'/16150, l='world', x=-1317.54, y=66.00, z=841.49], EntityPlayerMP['Eisenbahnn'/485, l='hoenn', x=603.55, y=143.35, z=-407.85], EntityPlayerMP['RZThug'/384, l='hoenn', x=1054.30, y=99.46, z=74.36], EntityPlayerMP['vitinhoLL'/21772, l='world', x=-1424.86, y=75.00, z=838.08], EntityPlayerMP['wagner45'/22321, l='world', x=-1286.21, y=64.00, z=831.87], EntityPlayerMP['Maxdesuper'/23764, l='world', x=-967.22, y=67.50, z=-614.79]]
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)

**Comment by phit** [comment]
https://github.com/SpongePowered/SpongeForge/issues/1946
