### ISSUE TITLE
Item skips pickup event if same item already exists in inventory

### ISSUE THREAD

**Issue by pdglobal** [SpongePowered/SpongeForge#2091]
**I am currently running**
- SpongeForge version: 4.1.30
- Forge version: forge-1.12.2-14.23.2.2611-universal
- Java version:  java version "1.8.0_161"
- Operating System: Windows Server 2016

- Plugins/Mods:

appliedenergistics2-rv5-beta-1,base-1.12.2-3.7.0,bc-ore-processing-7.99.15-1,bdlib-1.14.3.12-mc1.12.2,binnie-mods-1.12.2-2.5.0.119,BiomesOPlenty-1.12.2-7.0.1.2337-universal,buildcraft-7.99.15,capabilityadapter-1.0,CarrotShop-1.17-S7.0-MC1.12.2,Chameleon-1.12-4.1.3,ChestTransporter-1.12.2-2.8.8,ChickenChunks-1.12.2-2.4.1.71-universal,chiselsandbits-14.15,Clumps-3.0.0,CodeChickenLib-1.12.2-3.1.6.339-universal,CoFHCore-1.12.2-4.3.10.5-universal,CoFHWorld-1.12.2-1.1.1.12-universal,compactmachines3-1.12.2-3.0.7-b197,coroutil-1.12.1-1.1.24,CustomStartingGear-1.12-1.2.0.9-universal,Dynmap-2.6-beta-1-forge-1.12,energyconverters_1.12.2-1.0.2.0,ExtraBitManipulation-1.12-3.2.1,ExtremeReactors-1.12.2-0.4.5.46,flatcoloredblocks-mc1.12-6.6,flexiblelogin-0.18,forestry_1.12.2-5.8.0.252,Forgelin-1.6.0,generators-0.9.20.123-mc1.7.10,gravestone-1.10.1,griefprevention-1.12.2-4.3.0.562,HttpsBank-0.0.1-SNAPSHOT,JEHC-1.12.2-1.4.1.0,jei_1.12.2-4.8.5.147,journeymap-1.12.2-5.5.2,JustEnoughResources-1.12.2-0.8.5.27,Keys-1.2.1-1-g46a0267,KleeSlabs_1.12-5.3.2,LuckPerms-Sponge-4.1.30,MagicBees-1.12.2-3.1.9,mcjtylib-1.12-2.6.5,Mekanism-1.12.2-9.4.3.330,Mobmoney-0.0.1-SNAPSHOT,Neat+1.4-15,NetherPortalFix_1.12.1-5.3.13,NPCs-3.0.0-MC1.12.2,Nucleus-1.3.3-S7.0-MC1.12.2-plugin,ocsensors-1.0.4-b23,OpenBlocks-1.12.2-1.7.6-snapshot-823,OpenComputers-MC1.12.2-1.7.2.67,OpenModsLib-1.12.2-0.11.5-snapshot-510,OpenPeripheralAddons-1.7.10-0.6-snapshot-249,OpenPeripheralCore-1.7.10-1.4-snapshot-280,OpenPeripheralIntegration-1.7.10-0.6-snapshot-95,OpenPrinter-1.12.2-0.1.0.1,Pam's+HarvestCraft+1.12.2r,pamscookables-1.1,Passive+Aggression-1.12.2-0.0.1,Placebo-1.12.2-1.3.1,PlaceholderAPI-4.4,Plants-1.12.2-2.6.4,rangedpumps-0.5,RedstoneArsenal-1.12.2-2.3.10.4-universal,RedstoneFlux-1.12-2.0.1.2-universal,redstonepaste-mc1.12-1.7.5,rftools-1.12-7.30,rftoolsctrl-1.12-1.8.0,rftoolsdim-1.12-5.52,SimplyJetpacks2-1.12.2-2.2.2.28,spongeforge-1.12.2-2611-7.1.0-BETA-2990,Stargate-Atlantiscraft-Mod-1.12.2,Tesla-1.12.2-1.0.63,theoneprobe-1.12-1.4.21,ThermalCultivation-1.12.2-0.1.5.3-universal,ThermalDynamics-1.12.2-2.3.10.4-universal,ThermalExpansion-1.12.2-5.3.10.15-universal,ThermalFoundation-1.12.2-2.3.10.6-universal,thutcore-1.12.2-5.16.2,thuttech-1.12.2-6.0.15,TotalEconomy-1.8.0,UniDict-1.12.2-2.4,UniversalMarket-1.0-SNAPSHOT,UnlimitedChiselWorks-0.1.10,valkyrielib-1.12.2-2.0.8a,WanionLib-1.12.2-1.5,weather2-1.12.1-2.5.8,webapi-4.10.8-S7.1,worldedit-forge-mc1.12-6.1.8-dist,yourcustompaintings-1.0.0.10,zerocore-1.12-0.1.1.0

**Issue Description**

How it works is like this:

Player kills mob->mob drops gold nugget->player picks up nugget->nugget destroyed->player economy balance credited

However it seems to skip right passed the “player picks up nugget” step if the player already has gold nuggets in his inventory.

How do I go about intercepting the player picking up a gold nugget when he already has some in his inventory? Is this a bug, or is this some sort of intended behavior?

**Comment by ryantheleach** [comment]
Assigned myself to retest this over this weekend.

**Comment by Faithcaio** [comment]
Pickup events fire just fine with only Sponge. 
Relevant Sponge Code: https://github.com/SpongePowered/SpongeCommon/blob/a624e5c92e6a62cdb15df3d81624bab4863d22ed/src/main/java/org/spongepowered/common/mixin/core/entity/item/MixinEntityItem.java#L217

If you can reproduce it with minimal mods then I can investigate further.
