### ISSUE TITLE
NPE Timings when getting block ID

### ISSUE THREAD

**Issue by Bulldog83** [SpongePowered/SpongeForge#2094]
I have [same](https://github.com/SpongePowered/SpongeForge/issues/1402) crash on 1.12.2 forge server with sponge.
Crash report with list of mods:
https://gist.github.com/Bulldog83/eb800c057029cf01677440c8880e91c4

**Comment by JoeSGT** [comment]
You need to use the template in order to submit issues

**Comment by phit** [comment]
it's fine in this case, the parent issue has all the information needed

**Comment by gabizou** [comment]
Can you re-test on some newer builds of SpongeForge?

**Comment by Bulldog83** [comment]
I've made several tests. Crash causes by a combination of mods: SpongeForge + Better With Mods + Biomes O' Plenty.
Last crash-report: https://gist.github.com/Bulldog83/16a05ca35b3625feb699f08081cc688f

**Comment by Bulldog83** [comment]
SpongeForge 7.1.0-BETA-3019 causes crash too.
https://gist.github.com/Bulldog83/f928e3ab746a185f3e792028b56c3a10

**Comment by gabizou** [comment]
At this point, I can safely say you have a block that is not registered **at all with forge**.

I'll provide some more luggable warnings for this, but the NPE is happening here:
```java
        return Block.REGISTRY.getNameForObject((Block) (Object) this).toString();
```
Which can only mean that the registry does not have the block registered.

I'll comment back when I have something that will provide more information with a newer sponge build.

**Comment by Zidane** [comment]
Closing as this is not a Sponge issue.
