### ISSUE TITLE
Teleport causes "Completing Phase" spam

### ISSUE THREAD

**Issue by Sir-Will** [SpongePowered/SpongeForge#2098]
The log gets frequently spammed with the "Completing Phase" error which seems to get triggered by teleports.

**I am currently running**

- spongeforge-1.12.2-2611-7.1.0-BETA-3002
- forge-1.12.2-14.23.2.2631-universal

Completing Phase error: https://gist.github.com/Sir-Will/1e714b76b5f419dc0aa2e7f70b1b17b2

**Comment by dualspiral** [comment]
It's a bug with when runaway phases are printed. The multiple `GenerationPhases` in there are re-entrant so are in the phase stack multiple times, but the runaway phase check only checks the head of the stack for if that's re-entrant on pop. `CommandPhase` is not re-entrant (unlike the ones below) and the stack is greater than 6 items large so it triggers this spam. I could fix it by caching the number of re-entrant phases in the stack and accounting for it, though I am not completely up to speed with the phase tracker - @gabizou, thoughts?

To clarify, nothing is actually going wrong here, it's just a message that warns _something_ might be going wrong, the check for that needs updating.

(See https://github.com/NucleusPowered/Nucleus/issues/1117#issuecomment-379548224 for a similar situation on world generation where an event listener (which ironically is filtered out) triggers this.)

**Comment by Sir-Will** [comment]
Is there any way to disable this logging temporary until this is fixed? As this spam kills the sever.

**Comment by dualspiral** [comment]
Set `cause-tracker.verbose` to `false` in `global.conf`

**Comment by gabizou** [comment]
I do believe there are phases that have not been popped, in this case with generation. Chunk generation should only occur in specific instances, not during packet handling. Since world generation itself is performed long before packets are being read (which is calling a command for teleport), I do believe there is a bug somewhere. 

Is it possible to get the full server log (however large that may be)? I'm suspecting the world generation phases aren't completing on their own and are leaking.

**Comment by Sir-Will** [comment]
Truncated the log and only included the part where it started:
[server-2018-04-11-22-24-16.zip](https://github.com/SpongePowered/SpongeForge/files/1904006/server-2018-04-11-22-24-16.zip)

**Comment by Lemmmy** [comment]
> full server log
> truncated the log

**Comment by gabizou** [comment]
@Lemmmy not sure what your comment’s purpose is, but there’s no link that I’ve seen for a full log.

Edit: Oh, I see. @Sir-Will, I'll need the full log, because it's more likely an exception from earlier is causing world generation leakage.

**Comment by phit** [comment]
there was some more logging for this added since then, if this pops up again feel free to make a new issue including if possible first occurrences of the error logging which should help identifying the source
