### ISSUE TITLE
Console spam when stopping internal server with LAN players

### ISSUE THREAD

**Issue by creeper123123321** [SpongePowered/SpongeForge#2099]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2611-7.1.0-BETA-3016
- Forge version: 1.12.2-14.23.2.2611
- Java version: openjdk version "1.8.0_162"
- Operating System: Arch Linux

- Plugins/Mods: Forge, SpongeForge

**Issue Description**
Reproduction:
1 - open a world to LAN
2 - join that world with a vanilla client
3 - stop SpongeForge internal server by leaving world

https://gist.github.com/creeper123123321/889bc6cdfb42f855a52154ba5371b008

**Comment by Lemmmy** [comment]
Similar behaviour also happens when you ^C a server - not that you should, but felt it was worth mentioning.

**Comment by JBYoshi** [comment]
This seems to have been fixed. I can't reproduce it on the latest SpongeForge build (3126).

**Comment by bloodmc** [comment]
As JBYoshi stated, this is not an issue with latest builds.

**Comment by phit** [comment]
@creeper123123321 posted on discord and could still repro it
https://gist.github.com/phit/978cf20ec9568a08e481d9a82eea48bc

**Comment by Zidane** [comment]
I could not reproduce this issue on latest.
