### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#2101]
- SpongeForge version: 1.12.2-2611-7.1.0-BETA-3017
- Forge version: 14.23.2.2611
- Java version: OpenJDK 64-Bit Server VM, version 1.8.0_151
- Operating System: Linux

Plugins (17): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, CatClearLag, Eagle Factions, LuckPerms, MMCRestrict, MagiBridge, No Downfall, NuVotifier, Nucleus, Prism, SeriousVote, Total Economy, UniversalMarket, Vanish

Mods (101): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AE2 Stuff, Actually Additions, Advanced Generators, Applied Energistics 2, Aroma1997Core, AromaBackup, AromaBackuprecovery, AutoRegLib, BD Lib, Baubles, Better Builder's Wands, Biomes O' Plenty, Block Armor, Botania, CLibrary, ChickenChunks, Chisel, Chunk Pregenerator, CoFH Core, CoFH World, CodeChicken Lib, Compact Solar Arrays, ComputerCraft, CraftTweaker JEI Support, CraftTweaker2, Cucumber Library, Cyberware, DeepResonance, ElecCore, Extended Crafting, External Tweaker, Extra Cells 2, Extra Utilities 2, Extreme Reactors, Gravestone Mod, ICBM-Classic, Industrial Foregoing, IndustrialCraft 2, InstantUnify, Iron Chest, IvToolkit, Just Enough Items, Less Forgiving Void, Loot Bags, LootTweaker, Lost Souls, MTLib, Magical Psi, Mantle, MatterOverdrive, Mekanism, MekanismGenerators, MekanismTools, MmmMmmMmmMmm, Moar Tinkers, Mod Tweaker, OMLib, Open Modular Turrets, OpenBlocks, OpenComputers, OpenComputers (Core), OpenModsLib, OpenModsLib Core, OreExcavation, PlusTiC, Psi, Quick Leaf Decay, Random Things, RandomPatches, Redstone Arsenal, Redstone Flux, Refined Storage, SanAndreasPs Mod Library, SanAndreasPs Player Model, Secret Rooms 5, Shadowfacts' Forgelin, Techguns, Techguns Core, Tell Me, Tesla Core Lib, Tesla Core Lib Registries, The Lost Cities, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Tinker I/O, Tinkers Tool Leveling, Tinkers' Addons, Tinkers' Construct, UniDict, WanionLib, WorldEdit, Zero CORE, mob_grinding_utils

I'm clueless as to what caused this crash.

Crash report + log:
https://www.dropbox.com/s/rkqz1xjo2bsiqs9/crash-2018-04-13_14.22.02-server.txt?dl=0
https://www.dropbox.com/s/0a2lpqon1cqj8mr/fml-server-3.log?dl=0

**Comment by ghost** [comment]
Source found: redstone clock

**Comment by phit** [comment]
side effect of https://github.com/SpongePowered/SpongeForge/issues/1917
