### ISSUE TITLE
The advancement is not yet initialized

### ISSUE THREAD

**Issue by iridium34** [SpongePowered/SpongeForge#2103]
- SpongeForge version: 1.12.2-2611-8.0.0-BETA-3018
- Forge version: 14.23.2.2645
- Java version:  Version 8 Update 161 Build 12
- Operating System: Windows 10

**Issue Description**
it happend while using the Twilight Forest Mod.
1. moving in Twilight Forest Dim
or
2.Llogin while in Twilight Forest Dim

Crash Log:
https://gist.github.com/iridium34/1378bfd10161c1e1859d84dfb80d4dcf

**Comment by kashike** [comment]
You should be using `7.1.0`, not `8.0.0` snapshots. Try with `1.12.2-2611-7.1.0-BETA-3019`, or with `1.12.2-2655-7.1.0-BETA-3024` if you can upgrade to Forge build 2655.
