### ISSUE TITLE
Forge 1.12.2-14.23.3.2666 incompat

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/SpongeForge#2105]
SpongeForge 1.12.2-7.1.0-3024 and forge 1.12.2-14.23.3.2666 are incompatible.
Error log:
https://gist.github.com/XakepSDK/7b024a13c5c8127087fb0beaf114f85c

**Comment by Cybermaxke** [comment]
Got broken in:
https://github.com/MinecraftForge/MinecraftForge/commit/9d0771b3d736a1a1b26bcdfcbda193a626e95d59#diff-b3af1b66c89ea0b47400441c6f9a4334L393
Broken mixin:
https://github.com/SpongePowered/SpongeForge/blob/bleeding/src/main/java/org/spongepowered/mod/mixin/core/fml/common/MixinLoader.java#L58

**Comment by gabizou** [comment]
There's a problem updating, if we update, we'll break compatibility with older versions of forge I think. I'll try and see what I can do though.

**Comment by Zidane** [comment]
Closing as we bump Forge every so often anyways, don't need a ticket on this....

**Comment by FiveEYZ** [comment]
any chance this will happen in a near future?

**Comment by phit** [comment]
whenever the newer Forge versions become recommended this becomes an option, as we do not want to break compatibility with the current recommended version
