### ISSUE TITLE
[1.12.2] If the server gets improperly shut down, it will not boot again- RuntimeException: derp at net.minecraft.world.storage.SaveHandler

### ISSUE THREAD

**Issue by ProsperCraft** [SpongePowered/SpongeForge#2107]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2655-7.1.0-BETA-3025.jar
- Forge version: forge-1.12.2-14.23.3.2655-universal.jar
- Java version: openjdk version "1.8.0_161"
- Operating System: Centos 7 minimal install

**Issue Description**
I power cycled the box, and it would not come back up after.

Someone else reported the same issue a few days ago in the Sponge discord.

https://gist.github.com/ProsperCraft/efde4c9d74c422a15b8202ed3f5bae34

**Comment by gabizou** [comment]
@Zidane Should we consider to just revert if there's an older file located during the improper shutdown? The exception is pretty nondescript to many people (even us). I'd consider just raising a warning about potential corruption and move on.

**Comment by Zidane** [comment]
@gabizou 

I pushed a far more informative exception message. We aren't rolling back. The server needs to stop if this is hit as there is a pretty good chance it is just the start of the corruption and should be a red flag for the admin to start investigating world data. Just restoring the backup for them makes a very SERIOUS issue they need to investigate something that will just get ignored and hides a worse issue.
