### ISSUE TITLE
Server crash with spongeforge

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#2108]
- SpongeForge version: 1.12.2-2655-7.1.0-BETA-3029
- Forge version: 2655
- Modpack: Modern Skyblock 3

With the current version of Sponge and Modern Skyblock 3 there are problems with the NBT. I do not know exactly now but it has since been updated to Forge 2655 and the sponge version from 3024.

Here again a small screenshot with the problem.

https://screen.ichhaa.de/t8u3t7dfpo.png

**Comment by gabizou** [comment]
No sponge's fault, just making it aware for a mod developer to fix. Just not clear as to which mod is passing nulls.
