### ISSUE TITLE
StackOverflowError in PhaseTracker

### ISSUE THREAD

**Issue by rediomand** [SpongePowered/SpongeForge#2109]
- SpongeForge version:  spongeforge-1.12.2-2655-7.1.0-BETA-3029.jar
- Forge version: 14.23.3.2655
- Java version: java version "1.8.0_144"
- Operating System: Debian

- Plugins/Mods: Sevtech Modpack version 3.0.6

Sevtech server crash after join 

Crashreport: https://pastebin.com/q4q9pmef

**Comment by Zidane** [comment]
@gabizou 

I poked you on this before. Here is another situation where this happens.

**Comment by phit** [comment]
https://github.com/SpongePowered/SpongeForge/issues/2368
