### ISSUE TITLE
CustomNPCs EntityTrackerEntry crash

### ISSUE THREAD

**Issue by Lorrainrm** [SpongePowered/SpongeForge#2112]
Java8
spongeforge-1.12.2-2611-7.1.0-BETA-2990
Pixelmon reforged and stuff

Got my latest.log 2.6gb of info.

https://pastebin.com/HwcRX5U3

I'm assuming its all about this example i sent ^

**Comment by XakepSDK** [comment]
1. Mod list
2. Plugin list
3. How to reproduce.

Issue guidline(template when you create issue) made not as joke, follow it.

**Comment by Lorrainrm** [comment]
zpixelmonplaceholders-1.3.1
xPPokedex-0.7-MC1.12.2-F2611-S7.1.0
worldedit-sponge-6.1.9-SNAPSHOT-dist
WonderTrade-1.12.2-4.5.2-universal
VoxelSniper-8.5.0-SNAPSHOT
VirtualChest-1.0.0-alpha
VariedCommodities_1.12.2(06nov17)
UniversalMarket-1.12.2-v1.2.1
UltimateChat-1.8.6-b156-Universal
TrainerCommands-1.12-2.3.1-universal
TradeLogger-1.0.0
Tournaments-1.12.2-2.3.1
TickProfiler-1.12-0.0.4
TabManager-2.1.0-S7.0-MC1.12.2
SpongyBackpacks-1.0
ShinyPixelmon-1.12.2-1.10-universal
ServerListPlus-3.4.8-Universal
PlotSquared-Sponge-18.02.15-1cd30b8-1966
PlaceholderAPI-4.4
PixelUpgrade-1.12.2-4.0.0-beta1
PixelShout-1.12.2-1.2.0-universal
PixelMoney-1.12.2-2.1.0
PixelmonEconomyBridge-1.12.2-1.3.0
Pixelmon-1.12.2-6.2.3-server
PixelHunt-1.1-MC1.12.2-F2611-S7.1.0
PixelExtras-1.12.2-2.3.6-universal
PixelAutoMessages-1.0.3-b15
PixelAnnouncer-1.12.2-1.1.0
particlesaddon-1.1.3
Nucleus-1.3.6-S7.0-MC1.12.2-plugin
NBTEdit-1.12-2.0.2
LuckPerms-Sponge-4.1.57
HyperModBanner-1.12.2-3.3.0
holograms-3.1
GTS-3.7.2-S7.1
griefprevention-1.12.2-4.3.0.568
Gluon-1.0.4
GlobalCooldown1.5
FormEdit-1.0
flexiblelogin-0.16.8
entity-particles-2.0.5-v7
EMPSponge7
EconomyLite-7.0.0-2.13.0
EasyScoreboards
Dynmap-2.6-beta-1-forge-1.12
DailyRewards-api7-1.2.2
CustomNPCs_1.12.219apr18snapshot
crazyfeet-sponge-Api-7-1.14
CommandItems-1.5
CmdControl-s7.1-v1.1.0 (1)
CmdBuilder-s7.1-v1.2.0
ChangeSkinSponge
CategoryCommands-1.12.2-1.0.0
byte-items-2.0.5-v7
AntiWDL-1.1-all
LibLoader

1 and 2 ^

3. No idea, just saw the huge log file and checked the console to try to undestand.
Hopping its something obvious. Had this issue before, but it was for a moment and didnt logged Gigabytes.

**Comment by Lorrainrm** [comment]
Just happened again. Ill paste all the info i could find in the console:

fml-junk-earlystartup < 2.6gb
https://pastebin.com/NWeKUfTN

**Comment by Lorrainrm** [comment]
Sorry, no idea what trigges this :(

**Comment by Lorrainrm** [comment]
Ok, seems like i got more info when it started:

https://pastebin.com/XfkrrDLn

**Comment by Zidane** [comment]
Looks like Pixelmon keeps looping through savePlayer, almost like an infinite loop.

Go talk to them and show them this log. Not a Sponge issue.

**Comment by Lorrainrm** [comment]
It's a bit different now:
https://pastebin.com/cSNrdPZj

**Comment by Lorrainrm** [comment]
Another one but didnt give a loop
https://pastebin.com/tp3qdCdi

**Comment by Aaron1011** [comment]
@Lorrainrm: Can you upload your full server log?

**Comment by Lorrainrm** [comment]
Ok, more infos:
After 2 hours and 30 min online ~~ (depending on the amount of players online, more players, means this issue starts earlier), the server tps drops to 0 for few seconds, then few seconds goes back to 20 for few seconds then 0, then 20 until i restart. Usually players has some problems within this window of 0~20 tps. Loose items, loose pokemons, some dupe happens, etc.

latest.log:
https://pastebin.com/zpkkUv9y
console logs:
https://pastebin.com/7TxmN2PJ

**Comment by Aaron1011** [comment]
@Lorrainrm: Can you upload your `fml-server-latest.log` (or the `fml-server` log from the most recent server run that had the exception)?

**Comment by phit** [comment]
@Aaron1011 those files are no longer a thing, theres only latest.log and debug.log
you want debug.log

see https://github.com/mezz/MinecraftForge/commit/65284c5541eebec6f2e019faa141a31ade36a211#diff-b6de2700983073cf649bb620766ffce7

**Comment by Lorrainrm** [comment]
This is my latest Debug
[debug-1.log.gz](https://github.com/SpongePowered/SpongeForge/files/1958839/debug-1.log.gz)

**Comment by Lorrainrm** [comment]
Console log:
https://pastebin.com/9b30pUTs

Last lines from latest.log
https://pastebin.com/6u1X3HDJ

Crash reports from latest to earlier:
https://pastebin.com/kQpsiZme
---
https://pastebin.com/91bxr59s
---
https://pastebin.com/kXenXYDB
---

**Comment by Lorrainrm** [comment]
Didnt crashed this time but got this error once:
https://pastebin.com/GPXUXf4J

**Comment by Lorrainrm** [comment]
Got this right in time before/while crashing:
Console:
https://pastebin.com/k7sibjtU
Crash report:
https://pastebin.com/wb3MGhkK

**Comment by Aaron1011** [comment]
@Lorrainrm: The crash log is due to the [Custom NPCs](http://www.kodevelopment.nl/minecraft/customnpcs) mod not properly registering its entities with Forge's EntityRegistry.

**Comment by Lorrainrm** [comment]
Ok, already sent noppes the crash logs, let's see what he'll do. I'll update here with his infos, if thats ok.

Peace

**Comment by Noppes** [comment]
@Aaron1011 Hi, nope. My npc entity is registered the normal way and works just fine. I mean its the entity my whole mod resolves around and it goes well for hours for most until at some point usually when a player logs in, it can not resolve the entity.

My conclusion here is that it isnt my fault. I have no found a way to properly reproduce the error either.

**Comment by Lorrainrm** [comment]
Yeah.. Still crashes here and there
Specially when its friday or a day with more players..
Updated to spongeforge-1.12.2-2655-7.1.0-BETA-3064 but still..

Sometimes gets noppes custom admin error in the crash report, sometimes pixelmon...

 :(

**Comment by Lorrainrm** [comment]
FYI
I'm not getting this stupid huge log anymore
But crashes a lot with this very same issue, specially on weekends.. more players means more crashes.. :(

Getting the same generic crash report, blaming the customnpcs

Peace

**Comment by JayPeaSize** [comment]
This may be a bit dated, but also have this issue with Pixelmon Reforged entities (https://pastebin.com/yq57G2Ru)

I can also confirm that Pixelmon is properly registering the entities. (EntityList.registerModEntity)

**Comment by Zidane** [comment]
Tested with the latest SF and Pixelmon Reforged for a bit and ran into no issues with tracker crashes. if someone can get us an exact steps for reproduction respond back and let us know.

PS Also tested CustomNPCs but the two act similar in this regard.
