### ISSUE TITLE
Way too much critical damage on SpongeForge

### ISSUE THREAD

**Issue by Silver-Wulf** [SpongePowered/SpongeForge#2117]
**I am currently running**

- SpongeForge version: 1.12.2 2655 7.1.0 BETA 3047
- Forge version: 14.23.3.2655
- Java version: 1.8.0_144-b01
- Operating System: Windows 10 (also tried Ubuntu 14.04)

- Plugins/Mods:
No plugins
Only TheOneProbe installed as a mod to view damage

**Issue Description**
Critical hits with a diamond sword (or any sword) do way too much damage. I can deal 17-18 damage to creepers, skeletons, zombies, players. Spiders die in a single hit. Ect.

**Comment by Silver-Wulf** [comment]
I would like to clarify that critical hits deal normal damage usually under half of what Im experiencing above when Sponge is removed.

**Comment by parlough** [comment]
Thank you for reporting this, I am surprised we never noticed this, oops. Closed by bc381759c5467d6da477b524cc6f1d3541cc6aea

Should deal 10.5(150%) instead of 17.5(250%).
