### ISSUE TITLE
CME when setting MaximumChunksPerTicket to 0

### ISSUE THREAD

**Issue by ProsperCraft** [SpongePowered/SpongeForge#2119]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2655-7.1.0-BETA-3052.jar
- Forge version: 2655
- Java version: openjdk version "1.8.0_161"
- Operating System: Centos 7 minimal install.

- Plugins/Mods:Plugins (21): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, BetterChunkLoader, EconomyLite, LuckPerms, MMCReboot, MMCRestrict, MagiBridge, Nations, Nucleus, PayDay, Prism, PrismPlus, PwnFilter Sponge Plugin, Rankup, ServerListPlus, SleepVote, StatusProtocol, Tab Modifier

Mods- https://minecraft.curseforge.com/projects/towncraft

**Issue Description**
When I set forgeChunkLoading.cfg to include

fp {
    I:maximumChunksPerTicket=0
    I:maximumTicketCount=0
}

The server started a crashloop on boot.

When I set it to 1 ticket 1 chunk per ticket, it loaded.

java.lang.RuntimeException: java.util.ConcurrentModificationException
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:663)
	at org.spongepowered.mod.event.SpongeForgeEventFactory.callWorldLoadEvent(SpongeForgeEventFactory.java:1067)

Full crash log here-
https://gist.github.com/ProsperCraft/cb2dd354c10032fea336b46e1ee0eb62

**Comment by phit** [comment]
please test this without Sponge

**Comment by ProsperCraft** [comment]
No crash without sponge.

**Comment by Aaron1011** [comment]
@ProsperCraft: Do you have any idea which mods might be related to this? That modpack has 182 mods, which makes it somewhat difficult to test.

**Comment by phit** [comment]
I wasn't able to replicate either scenario, crash when set to 0 or CME when set to 1 with:
Futurepack-1.12.2-26.4.82
