### ISSUE TITLE
Invalid id 4096 - maximum id range exceeded.

### ISSUE THREAD

**Issue by IronworksProductions** [SpongePowered/SpongeForge#2121]
**I am currently running**

- SpongeForge version: beta 3058
- Forge version: forge-1.12.2-14.23.3.2655
- Java version: 1.8
- Operating System: ubuntu

- Plugins/Mods:ET Lunar [Environmental Tech Addon] (by ValkyrieofNight)
Baubles (by azanor)
Controlling (by jaredlll08)
Integrated Tunnels (by kroeser)
Tinkers Construct (by mDiyo)
[SBM] Wooden Shears (by darkguardsman)
Quick Leaf Decay (by lumien231)
Guide-API (by TehNut)
Actually Baubles (by Jacky1356400)
Mantle (by mDiyo)
Forestry (by SirSengir)
Ranged Pumps (by raoulvdberge)
Environmental Tech (by ValkyrieofNight)
Iron Chests (by progwml6)
ShetiPhianCore (by ShetiPhian)
Angel Ring To Bauble (by Portablejim)
Steve's Carts Reborn (by modmuss50)
JEI Bees (by bdew)
Ceramics (by KnightMiner)
Ore Excavation (by Funwayguy)
Quark (by Vazkii)
B.A.S.E (by lanse505)
CraftTweaker (by jaredlll08)
Thermal Foundation (by TeamCoFH)
NetherPortalFix (by BlayTheNinth)
Industrial Craft (by Player)
Actually Additions (by Ellpeck)
CodeChicken Lib 1.8.+ (by covers1624)
ValkyrieLib (by ValkyrieofNight)
Akashic Tome (by Vazkii)
Simple Bedrolls (by Konlii)
AutoRegLib (by Vazkii)
SwingThroughGrass (by exidex)
Fullscreen Windowed (Borderless) for Minecraft (by hancin)
Morpheus (by Quetzi)
Just Enough Items (JEI) (by mezz)
TorchMaster (by xalcon)
Custom Main Menu (by lumien231)
FTBLib (by FTB)
MTLib (by jaredlll08)
CoFH Core (by TeamCoFH)
Silent's Gems: Extra Parts (by SilentChaos512)
Natura (by mDiyo)
Iron Backpacks (by gr8pefish)
Default Options (by BlayTheNinth)
Tinkers' Addons (by oitsjustjose)
BdLib (by bdew)
AppleSkin (by squeek502)
Inventory Tweaks (by Kobata)
Immersive Engineering (by BluSunrize)
Clumps (by jaredlll08)
p455w0rd's Library (by TheRealp455w0rd)
Botania (by Vazkii)
EnderTanks (by ShetiPhian)
Refined Storage (by raoulvdberge)
Ender Storage 1.8.+ (by covers1624)
Soul Shards: The Old Ways (by SgtPunishment)
Simply Conveyors & More (by Zundrel)
Better Builder's Wands (by Portablejim)
Crafting Tweaks (by BlayTheNinth)
Bad Wither No Cookie - Reloaded (by kreezxil)
ReAuth (by TechnicianLP)
SimpleHarvest (by TehNut)
Mekanism (by aidancbrady)
FTB Utilities (by FTB)
/dank/null (by TheRealp455w0rd)
Mekanism Tools (by aidancbrady)
Thermal Cultivation (by TeamCoFH)
Silent Lib (by SilentChaos512)
BetterFps (by Guichaguri)
Hwyla (by TehNut)
Reborn Core (by modmuss50)
Silent's Gems (by SilentChaos512)
Binnie's Mods (by Binnie567)
Morph-o-Tool (by Vazkii)
Cyclops Core (by kroeser)
Aroma1997Core (by Aroma1997)
Refined Storage Addons (by raoulvdberge)
No Mob Spawning on Trees (by oldjunyi)
Chisel (by tterrag1098)
Industrial Wires (by malte0811)
Item Scroller (by masa_)
Immersive Petroleum (by theFlaxbeard)
Redstone Flux (by TeamCoFH)
Aroma1997s Dimensional World (by Aroma1997)
Chameleon (by jaquadro)
Traverse (by ProfessorProspector)
Mekanism Generators (by aidancbrady)
Resource Loader (by lumien231)
ConnectedTexturesMod (by tterrag1098)
Thermal Dynamics (by TeamCoFH)
Extra Utilities (by RWTema)
Just Enough Resources (JER) (by Way2muchnoise)
Lapis Stays in the Enchanting Table (by csb987)
Light Level Overlay Reloaded (by oldjunyi)
JEI Integration (by SnowShock35)
Thermal Expansion (by TeamCoFH)
CoFH World (by TeamCoFH)
Diet Hoppers (by RWTema)
Gendustry (by bdew)
Astral Sorcery (by HellFirePvP)
OreExcavation Integration (by BloodWorkXGaming)
Storage Drawers (by jaquadro)
Common Capabilities (by kroeser)
Placebo (by Shadows_of_Fire)
Toast Control (by Shadows_of_Fire)
Shadowfacts' Forgelin (by shadowfactsmc)
McJtyLib (by McJty)
ShadowMC (by shadowfactsmc)
Extra Rails (by shadowfactsmc)
Tomb Many Graves 2 (by M4thG33k)
EluLib (by elucent)
Blockcraftery (by elucent)
Bookshelf (by Darkhax)
Integrated Dynamics (by kroeser)
WAIM - What am I missing? (by jaredlll08)
Open Glider (by gr8pefish)
JourneyMap (by techbrew)
Reborn Storage (by modmuss50)
OpenBlocks Elevator (by VsnGamer)
FastWorkbench (by Shadows_of_Fire)
Dismantler (by BloodWorkXGaming)
FoamFix for Minecraft (by asiekierka)
Adventure Tools (by qwertypolyp)
RFTools Power (by McJty)
Bed Patch (by Mordenkainen3141)
EnderCore (by tterrag1098)
Ender IO (by CrazyPants_MC)
Security Craft (by Geforce132)
SecretRoomsMod (by AbrarSyed)
LibVulpes (by zmaster587)
Advanced Rocketry (by zmaster587)
ZeroCore (by ZeroNoRyouki)
Extreme Reactors (by ZeroNoRyouki)
Refined Avaritia (by ExpensiveKoala)
Avaritia 1.1x (by brandon3055)
Avaritia Tweaks (by Jacky1356400)
Cucumber Library (by BlakeBr0)
Mystical Agriculture (by BlakeBr0)
Mystical Agradditions (by BlakeBr0)
CLib (by Dr_Codex)
Matter Overdrive (by simeonradivoev)
Brandon's Core (by brandon3055)
Draconic Evolution (by brandon3055)
OpenComputers (by SangarWasTaken)
OMLib (by Keridos)
OpenModularTurrets (by Poenjabiesous)
OpenModsLib (by OpenMods)
OpenBlocks (by OpenMods)
Open Modular Passive Defense (by Keridos)
Random Things (by lumien231)
RFTools (by McJty)
RFTools Control (by McJty)
RFTools Dimensions (by McJty)
NuclearCraft (by TLJGames)
ProjectE (by sinkillerj)
Blood Magic (by WayofTime)
Thaumcraft (by azanor)
Buildcraft (by CovertJaguar)
Buildcraft Compat (by buildcraftchildsplay)
DiscordSuite (by Dr_Codex)
SGCraft1.12
Immersive engineering
its the little things

**Issue Description**
After launching the server the server loaded for a little bit then it crashed. I tried updating sponge forge to latest and the same thing happens.(more accurately i was on latest and i downgraded to 3052 to see if it would work since that was working before on a smaller modpack. it kept saying Invalid id 4096 - maximum id range exceeded when it crashed.

https://gist.github.com/nacjm/40e3cc36ee691b6fa39031fe2733b083
https://gist.github.com/nacjm/c83d98a7215550c403430c65eb7d0f09

**Comment by Zidane** [comment]
How is hitting the block id limit a SpongeForge issue when we don't add blocks nor affect how blocks are registered?

**Comment by Dockter** [comment]
This modpack must take 15 minutes to load....
