### ISSUE TITLE
[1.12.2] Crash on startup

### ISSUE THREAD

**Issue by Blayyke** [SpongePowered/SpongeForge#2122]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2655-7.1.0-BETA-3059
- Forge version: forge-1.12.2-14.23.3.2655
- Java version: 1.8
- Operating System: Actually not sure. This happened on one of akliz's server that a friend owns.

- Plugins/Mods:
None but sponge

**Issue Description**
Error on start that crashes the server. Doesn't require me to do anything but try starting server.

https://gist.github.com/Blayyke/c95693acc42dc5a73ad669321303190e

**Comment by gabizou** [comment]
Can you toggle `cause-tracker.generate-stacktrace-per-phase = true` in your global config and re-paste? It should have more information about the stack as to why the command state isn't completing. Also, is this the full log or only partial?

**Comment by Blayyke** [comment]
The server managed to start and hasn't had this issue since, if I get it again I'll report the crash log. This was the full error part of the log.
