### ISSUE TITLE
Some console spam

### ISSUE THREAD

**Issue by avescarelo** [SpongePowered/SpongeForge#2123]
**I am currently running**

- SpongeForge version: 3028
- Forge version: 2655
- Java version: 8
- Operating System: Windows/Linux

- Plugins/Mods:

Plugins (5): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, TimeWarp

Mods (33): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AbyssalCraft, Animania, Antique Atlas, AppleCore, Astral Sorcery, AutoRegLib, Baubles, BiblioCraft, Botania, Botaunomy, CraftStudio API, Earthworks, Example Mod, Hardcore Darkness, Hunger Overhaul, Iron Chest, Magical Psi, Nibbler, Potion Core, Psi, Quality Tools, Quark, Rustic, Tails, Thaumcraft, The Spice of Life, WorldEdit

**Issue Description**
Some console spam whith thaumcraft workbench. 

latest.log
https://gist.github.com/pingvikin/2ad6701552f5db964d36f77148735275

**Comment by phit** [comment]
https://gist.github.com/phit/b2c387b3070c410de88fb6e9333704bf

**Comment by phit** [comment]
https://github.com/SpongePowered/SpongeForge/issues/2058
