### ISSUE TITLE
[1.12.2]Crash on starting up

### ISSUE THREAD

**Issue by Tollainmear** [SpongePowered/SpongeForge#2128]
**I am currently running**

- SpongeForge version: 1.12.2-2655-7.1.0-BETA-3064
- Forge version: 14.23.3.2655
- Java version: 8
- Operating System: Windows Server Datacenter

- Plugins/Mods: [Open on gist if needed](https://gist.github.com/Tollainmear/62ff02881ba3ac96951dfe1334ae8335)

**Issue Description**
Hi, dear sponge developers, it's unpleasant that a crash has happened on my server, and after that, the server couldn't start up anymore.

Here is the [first crash report](https://gist.github.com/Tollainmear/0402629e7e1604fc58b0af2fd52c04d7), and after that server crashed each time with a same [crash-report](https://gist.github.com/Tollainmear/fef6a3471880f19415f81a71682c1a3c) which was different with further one, according to the crash-report, it seems like some thing went wrongly with AE2 or NuclearCraft, I'm not a professional developer in java, so before I post this issue, I have tried to ask NuclearCraft's developer and AE2's developer for help, but it seems like sponge server was not a environment they supported, So they suggest me to posting a issue here to ask for help.

Here is the issue I post to [AE2](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3477) and [NuclearCraft](https://github.com/turbodiesel4598/NuclearCraft/issues/305), as they said, some blockdata might be changed by Spongeforge then the crash occured.

Here is the entire [log](https://gist.github.com/Tollainmear/c24c7649188e4796d11b073944398fb4) on server crash.

and there is a weird situation happened, if I uninstall the spongeforge then run the serevr, the server crashed with a different [crash-report](https://gist.github.com/Tollainmear/af6ad57772bd8c264d8c2f82f16d7331) which was different with further two..... It seems like something has problem with forestry, so I have also post a issue to [forestry](https://github.com/ForestryMC/ForestryMC/issues/2119).....

These problem make me confused and I can't handle them, so help me plz, if any thing else was needed, I would provide more information here.

**Comment by phit** [comment]
looks like your world corrupted, make sure you have [`deny-chunk-request=false`](https://github.com/SpongePowered/SpongeForge/issues/2003) in your config/sponge/global.conf and have [dormant chunk cache disabled](https://github.com/MinecraftForge/MinecraftForge/issues/3325)

then roll back to your last working backup
