### ISSUE TITLE
SpongeForge/Bootrap error on Sprout Serveur

### ISSUE THREAD

**Issue by DucPecc** [SpongePowered/SpongeForge#2134]
**I am currently running**
- SpongeForge version: spongeforge-1.10.2-2477-5.2.0-BETA-2790
- Java version: forge-1.10.2-12.18.3.2477-universal
- Operating System: Win10/Linux

- Plugins/Mods: Sprout Modpack 

**Issue Description**
 Hello ^^ i tried to make a Sprout serveur for my Twitch Channel and host it, but i would like add some Plugins, and for this i actually need tu use SpongeBootstrap for start Sponge a first position of loading mods, and when i tried to start my serveur with this one, i got a error that said to me about one mods start before Sponge, and i have no issu of which on is it :/ and how to fix this 

Full Logs
https://pastebin.com/gwaQE3gq

Ps: Im french so srry if a make syntax error ^^

**Comment by phit** [comment]
1.10 is no longer supported and as this isn't a bug on our end please use our forums for additional help
https://forums.spongepowered.org/

**Comment by DucPecc** [comment]
okay thanks ^^

**Comment by gabizou** [comment]
To summarize the problem you're having:
Another coremod (not just a mod, but a coremod) is loading a class too early for Sponge to be able to transform said class. Try removing core mods one at a time and then you can report to the coremod that is loading that class (in this case `IProperty`).
