### ISSUE TITLE
Crash 1.12.2

### ISSUE THREAD

**Issue by SawFowl** [SpongePowered/SpongeForge#2135]
**I am currently running**
Minecraft: 1.12.2
SpongeAPI: 7.1.0-SNAPSHOT-7d8a938
SpongeForge: 1.12.2-2655-7.1.0-BETA-3065
Minecraft Forge: 14.23.3.2655
- Java version: Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
- Operating System: Debian 8

Mods (39): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AE2 Stuff, Advanced Solar Panels, Applied Energistics 2, BD Lib, CXLibrary, CoFH Core, CoFH World, CodeChicken Lib, Console Filter, Ex Nihilo Creatio, Extreme Reactors, Fishing Net Mod, Giacomo's Foundry, HoloInventory, IndustrialCraft 2, Just Enough Items, Mantle, Mod Control, More Furnaces, NoDestroy, Parachronology, PortalGun, Quick Leaf Decay, Redstone Flux, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Tinkers' Construct, Tree Chopper, Waterfree Farming, Zero CORE, iChunUtil
Plugins (28): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, BeanCore, BungeeAuthReloaded, CatClearLag, CmdCalendar, CommandSync, CommandUtils, EasyScoreboards, EconomyLite, GriefPrevention, HuskyCrates, HuskyUI, JobsLite, LuckPerms, Nucleus, PayDay, PlaceholderAPI, ProjectCore, SkyClaims, StackBan, TabManager, UltimateChat, UniversalMarket, VirtualChest, VirtualTool

I can not say what causes the problem, I do not know. Appears by accident.

[logs.zip](https://github.com/SpongePowered/SpongeForge/files/1988178/logs.zip)

**Comment by phit** [comment]
please post your `config/sponge/global.conf`

**Comment by SawFowl** [comment]
config/sponge/global.conf => https://pastebin.com/uYreDZHy

**Comment by phit** [comment]
Yup there's the cause, set `deny-chunk-requests=false` (line 552).

https://github.com/SpongePowered/SpongeForge/issues/2003

**Comment by SawFowl** [comment]
@phit Thank you.
