### ISSUE TITLE
Pixelmon leafstone tools not losing durability

### ISSUE THREAD

**Issue by fatyg5** [SpongePowered/SpongeForge#2136]
**I am currently running**

- SpongeForge version: 3064
- Forge version: 2655 
- Operating System: CentOS7

- Plugins/Mods: Pixelmon, SpongeForge

**Issue Description**
SpongeForge is causing the Pixelmon leafstone tools to not take durability damage upon using them. These tools have a special property in which durability can be traded to create a bonemeal effect on a crop. However, with SpongeForge installed, the durability is not removed from the tool and it can be used infinitely. This is not reproduce-able with pure Forge, leading me to blame SpongeForge.

This issue has existed for quite some time, earliest I can recall is SF 2990, but it may go back even further.

**Comment by gabizou** [comment]
Is there any easy way to reproduce this? I'm not terribly keen on reviewing Pixelmon code directly, but seeing as distribution of Pixelmon was made illegal, I'm only guessing that some developer input may be necessary to provide a simplified bit of code to replicate the issue.

**Comment by Rasgnarok** [comment]
@Gabizou Pixelmon received a C&D to which they complied, and so the code was never illegal to begin with, nor its distribution by persons outside the core team. Currently, the forks aren't done by that team either. Had went over it with Zidane a month or two ago.

If you have more questions, feel free to drop by our discord, its something I already spoke about with a couple others in Sponge.


That said, I'll report back and see if there is code that we can provide to fix this.

**Comment by MoeBoy76** [comment]
Did some testing, tools except the hoe are working, this also seems to cause some issues with carrot on a stick to not work correctly.

Tested on SpongeForge version: 3082, Forge 2655, LuckPerms 4.2.12
Also did secondary testing with GriefPrevention 4.3.0.579

https://luckperms.github.io/verbose/?4JaTYmoTkp
https://griefprevention.github.io/debug/?3DBka8HeG5

for reference this is called from the interact method
https://gist.github.com/MoeBoy76/3bbea35664f05f2e89da357730c040d8

**Comment by bloodmc** [comment]
The issue is caused by Pixelmon's GenericHoe class ALWAYS returning `EnumActionResult.FAIL` even when the item use succeeded. When this occurs, sponge performs a rollback causing the issue. Once Pixelmon returns the proper result of `EnumActionResult.SUCCESS`, there will be no issues with Sponge.

**Comment by MoeBoy76** [comment]
Thanks blood, completely missed that
