### ISSUE TITLE
Forge Incompatibility 2667+

### ISSUE THREAD

**Issue by CDAGaming** [SpongePowered/SpongeForge#2137]
Trying to build the stable-7 branch on Forge 14.23.3.2667 and Higher, results in a NoMethodFound for findModDirMods in MixinLoader. This is most likely due to the newer way Forge detects mods, but any chance there is a way to add support for these versions or on how I can work around it to build SpongeForge?

*Edited to Reference #2105 
*Find anything @gabizou ?

**Comment by phit** [comment]
> Closing as we bump Forge every so often anyways, don't need a ticket on this....

**Comment by gabizou** [comment]
Forge recommended builds are still pointing to 2655, so usually when the build updates, we’ll update. Because this is a backwards breaking change we can’t leave important fixes still in progress (like #2110) to only the newer forge builds if they aren’t recommended.
