### ISSUE TITLE
Techgun not supported by Sponge.

### ISSUE THREAD

**Issue by RaiKave** [SpongePowered/SpongeForge#2139]
- SpongeForge version: 1.12.2-2655-7.1.0-BETA-3065
- Forge version: 14.23.3.2655
- Java version: 8

- Plugins/Mods:
Mod - Car-1.2.11, Mod - Chisel-0.2.0.31, Mod - CLib-1.0.2.31-universal, Mod - CodeChickenLib-3.1.8.341-universal, Mod - CoFHCore-4.4.1.12-universal, Mod - CTM-MC1.12-0.2.3.12, Mod - Currency-1.3.2, Mod - CustomNPCs_(20jan18), Mod - ExtremeReactors-0.4.5.48, Mod - Fexcraft Common Library-XII.40, Mod - FSMM-2.1.0f, Mod - GalacticraftCore-4.0.1.176, Mod - Galacticraft-Planets-4.0.1.176, Mod - LycanitesMobsComplete+1.20.1.0+, Mod - MatterOverdrive-0.6.0.157-universal, Mod - MCrayfish-4.2.0, Mod - Mekanism-9.4.10.345, Mod - MekanismGenerators-9.4.10.345, Mod - MekanismGenerators-9.4.10.345, Mod - Pam's HarvestCraft, Mod - Pam's HarvestCraft, Mod - Pam's HarvestCraft, Mod - Techguns-2.0.1.1, Mod - ThermalDynamics-2.4.1.10-universal, Mod - ThermalDynamics-2.4.1.10-universal, Mod - ThermalFoundation-2.4.1.15-universal, Mod - Worldedit-6.1.8, Mod - Zerocore-0.1.2.1

When we was playing, we realise than the console was spammed from error and causing timed out, that became unplayable un all is due to sponge because without sponge there is no errors.

https://gist.github.com/phit/d7962d2f4a8ca9f8d4abc7c998ecd935

**Comment by gabizou** [comment]
Closing as it's not a Sponge issue but an issue with [Techguns2 issue where they're checking instances and then casting anyways](https://github.com/pWn3d1337/Techguns2/blob/150cef027b2e61173ac2fe5cbd9f3ec162431316/src/main/java/techguns/items/armors/GenericArmor.java#L455-L469).

Even in IDE this will be flagged as a warning:
<img width="1062" alt="screen shot 2018-05-11 at 1 25 27 pm" src="https://user-images.githubusercontent.com/1203877/39945317-e483d1ea-551e-11e8-8018-78b4f359255f.png">

If I have time I'll submit a PR to Techguns2 since the mod appears to be updated on github.

**Comment by RaiKave** [comment]
Thanks for your fast response, if the mod is fixed in githublike you said maybe i should recompile it.

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Gabriel Harris-Rouquette <notifications@github.com>
Envoyé : Friday, May 11, 2018 10:26:52 PM
À : SpongePowered/SpongeForge
Cc : RaiKave; Author
Objet : Re: [SpongePowered/SpongeForge] Techgun not supported by Sponge. (#2139)


Closing as it's not a Sponge issue but an issue with Techguns2 issue where they're checking instances and then casting anyways<https://github.com/pWn3d1337/Techguns2/blob/150cef027b2e61173ac2fe5cbd9f3ec162431316/src/main/java/techguns/items/armors/GenericArmor.java#L455-L469>.

Even in IDE this will be flagged as a warning:
[screen shot 2018-05-11 at 1 25 27 pm]<https://user-images.githubusercontent.com/1203877/39945317-e483d1ea-551e-11e8-8018-78b4f359255f.png>

If I have time I'll submit a PR to Techguns2 since the mod appears to be updated on github.

**Comment by gabizou** [comment]
https://github.com/pWn3d1337/Techguns2/issues/38. For reference.

**Comment by RaiKave** [comment]
Thanks x) i will wait a respose from the mod author.

**Comment by RaiKave** [comment]
I have this error too i just don’t know what is it and if you can help me for that ?

**Comment by gabizou** [comment]
That's more of a networking exception. You'd need to open a new issue with a full log to get some help on that.
