### ISSUE TITLE
Twilight Forest advancements crash

### ISSUE THREAD

**Issue by OneTrueVex** [SpongePowered/SpongeForge#2140]
- SpongeForge version: 1.12.2-2655-7.1.0-BETA-3065
- Forge version: 1.12.2-14.23.3.2655
- Java version: 1.8.0_51
- Operating System: Windows 10

- Plugins/Mods:
	
fenceoverhaul, baubles, bibliocraft, biomesoplenty, jei, blockdrops,  bloodmoon, cfm, cosmeticarmorreworked, customspawner, customnpcs, ptrmodellib, props, disenchanter, doggytalents, mocreatures, fastleafdecay, foamflower, gravestone, ichunutil, inventorytweaks, ironbackpacks, ironchest, jeiintegration, jeresources, longfallboots, malisiscore, malisisdoors, mantle, radixcore, mca, parachutemod, portalgun, roguelike, saltmod, lteleporters, spawnercraft, tails, thaumcraft, thutcore, thutcore_compat, thuttech, torohealthmod, twilightforest, vending

*I don't use sponge for plugins as of yet, only for optimization purposes.*

This ONLY happens if sponge is in my server's mods folder AND this has only happened while in the twilight forest, otherwise there are no crashes whatsoever. This has been tested many times with different circumstances, but the results are the same every time. My client hangs up, then the screen becomes 'sky colored,' then this crash happens:

https://gist.github.com/OneTrueVex/d58444706a385d38ea9aefa9a798f8cf

In some earlier instances I've been able to navigate the twilight forest up until specific areas, like the swamp, then the crash happens. In later instances where I've advanced farther, then install sponge, the crash still happens. Neither a fresh client, nor a fresh server can circumvent this issue. From what I've gathered, the advancements may be the culprit. It's impossible to login to the server once the crash has happened, as I'm placed back in the very spot that crashes my client. Deleting sponge solves the crashes, but this solution is problematic.. if sponge is removed/reinstalled not only do magic maps break, new twilight chunks become misaligned with existing chunks, so I must delete all existing dimension data for twilight if I want it to work properly afterwards, but I digress.

This seems to be a slightly similar issue, though my files are up to date:

https://github.com/SpongePowered/SpongeForge/issues/2103

Obviously the easy solution would be to just not install sponge for now, and even more so because I'm not using any plugins, but the performance boost on my server is just fantastic, so it's a real bummer.

**Comment by Retovath** [comment]
I believe that this could be a result of forge version updates, on the present build (5/23/18) it requests forge 2675 at a minimum for some lighting fixes. 
https://gist.github.com/Retovath/cd8747f9b622c23751302d4ce37c56d9

Spongeforge is currently updated to reccomended builds only, so spongeforge is up to forge 2655. Improperly matched forge/spongeforge versions can occasionally cause crosstalk issues.

**Comment by bloodmc** [comment]
@OneTrueVex please test latest SF.

**Comment by phit** [comment]
No reply in over a week, closing this for now. If this is still an issue, then please reply with the information you have been asked for and I will reopen this issue.
