### ISSUE TITLE
RefinedStorage GUI incompatability

### ISSUE THREAD

**Issue by Tommeh1** [SpongePowered/SpongeForge#2141]
- SpongeForge version: spongeforge-1.12.2-2655-7.1.0-BETA-3056.jar
- Forge version: 1.12.2 - 14.23.3.2655
- Java version: java8 update 161
- Operating System: Linux

Plugins (15): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, Eagle Factions, LuckPerms, MMCRestrict, MagiBridge, No Downfall, NuVotifier, Nucleus, SeriousVote, Total Economy, UniversalMarket, Vanish

Mods (105): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AE2 Stuff, Actually Additions, Advanced Generators, Applied Energistics 2, Aroma1997Core, AromaBackup, AromaBackuprecovery, AutoRegLib, BD Lib, Baubles, Better Builder's Wands, Biomes O' Plenty, Block Armor, Botania, CLibrary, ChickenChunks, Chisel, Chunk Pregenerator, CoFH Core, CoFH World, CodeChicken Lib, Compact Solar Arrays, ComputerCraft, CraftTweaker JEI Support, CraftTweaker2, Cucumber Library, Cyberware, DeepResonance, ElecCore, Extended Crafting, Extra Cells 2, Extra Utilities 2, Extreme Reactors, Flan's Mod, Flan's Mod: Apocalypse, Foamflower, ICBM-Classic, Industrial Foregoing, IndustrialCraft 2, InstantUnify, Iron Chest, IvToolkit, Just Enough Items, Less Forgiving Void, Loot Bags, LootTweaker, Lost Souls, MTLib, Magical Psi, Mantle, MatterOverdrive, McJtyLib, Mekanism, MekanismGenerators, MekanismTools, MmmMmmMmmMmm, Moar Tinkers, Mod Tweaker, OMLib, Open Modular Turrets, OpenBlocks, OpenComputers, OpenComputers (Core), OpenModsLib, OpenModsLib Core, OreExcavation, PlusTiC, Psi, Quick Leaf Decay, Random Things, RandomPatches, Redstone Arsenal, Redstone Flux, Refined Storage, SanAndreasPs Mod Library, SanAndreasPs Player Model, Secret Rooms 5, SecretRooms Hooks, Shadowfacts' Forgelin, Tell Me, Tesla Core Lib, Tesla Core Lib Registries, The Lost Cities, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Tinker I/O, Tinkers Tool Leveling, Tinkers' Addons, Tinkers' Construct, UniDict, VanillaDeathChest, Vending, WanionLib, WorldEdit, XNet, Zero CORE, mob_grinding_utils

Although items can almost always be properly crafted this issue will often appear in the console whenever someone crafts something using the refinedstorage crafting grid. https://pastebin.com/kFu0Nci4

**Comment by Faithcaio** [comment]
https://github.com/SpongePowered/SpongeForge/issues/2058
