### ISSUE TITLE
Villagers don't pick up items

### ISSUE THREAD

**Issue by PolyacovYury** [SpongePowered/SpongeForge#2142]
**I am currently running**
- SpongeForge version: 1.12.2-2655-7.1.0-BETA-3069
- Forge version: 1.12.2-14.23.3.2655-universal
- Java version: 1.8
- Operating System: Windows

- Plugins/Mods: NONE

**Issue Description**

Well, the title says it all. Villagers won't pick up anything I throw at them. Inventory stays empty (checked with `/entitydata` command), and the item just lies there until it despawns.

P.S. Would've provided more information and even a possible solution, but I spent past 7 to 8 hours setting up a debug environment, and it looks like my IDEA stopped liking me for some reason. "The bytecode does not match source code" on both forgeSrc.jar and minecraft_serverSrc.jar, and all the villager-related code in the SpongeForge itself looks fine at first glance.

**Comment by ProsperCraft** [comment]
I have never in all my time playing minecraft had a villager pick up an item, what are you talking about?

You open villagers inventory, and trade with them.

**Comment by Aaron1011** [comment]
I think it's a recent-ish feature: https://minecraft.gamepedia.com/Villager#Picking_up_items

**Comment by phit** [comment]
last time this came up we couldnt reproduce this, see https://github.com/SpongePowered/SpongeCommon/issues/1211

**Comment by PolyacovYury** [comment]
`recent-ish feature`
Yeah. Since 1.8 release, if I'm not mistaken. Did you actually build at least one functional breeder since then?
And did you know that they also can plant, harvest and share crops? And that they need food to breed?

**Comment by phit** [comment]
well our last testing of that was in january, thats was only 2-3 months ago, haven't tried since then though
will test later

**Comment by PolyacovYury** [comment]
```java
// in SpongeCommon/src/main/java/org/spongepowered/common/mixin/core/entity/MixinEntityLiving.java
    /**
     * @author gabizou - April 11th, 2018
     * @reason Instead of redirecting the gamerule request, redirecting the dead check
     * to avoid compatibility issues with Forge's change of the gamerule check to an
     * event check that doesn't exist in sponge except in the case of griefing data.
     *
     * @param thisEntity
     * @return
     */
    @Redirect(method = "onLivingUpdate", at = @At(value = "FIELD", target = "Lnet/minecraft/entity/EntityLiving;dead:Z"))
    private boolean onCanGrief(EntityLiving thisEntity) {
        return this.dead || ((IMixinGriefer) this).canGrief();
    }
```
Let me get this straight. If a villager (or, actually, ANY living entity, including skeletons, zombies, etc.) is **dead** OR **can grief** - this returns **true**.

While the original code proceeds to actually doing stuff only if this is **false**:
```java
                                                     vvvvvvvvv
if (!this.world.isRemote && this.canPickUpLoot() && !this.dead && this.world.getGameRules().getBoolean("mobGriefing"))
```

P.S. Good thing that you said you've tested this in January, because the code was written in April.
P.P.S. Looks like it's not SpongeForge issue, but SpongeCommon.

**Comment by PolyacovYury** [comment]
[14:29] Polyacov_Yury: @gabizou, why didn't you redirect the canPickUpLoot function instead?...
[18:06] gabizou: @Polyacov_Yury, probably because I was wanting the injection to be as close as possible to the previous injection position. I see the logical error now. One of the devs can fix it as [I'm currently busy].

**Comment by Faithcaio** [comment]
https://github.com/SpongePowered/SpongeCommon/commit/46c568c1639a44118eaeed4349d746887ff990c5
