### ISSUE TITLE
Sentient Pickaxe

### ISSUE THREAD

**Issue by ninja0773** [SpongePowered/SpongeForge#2143]
**I am currently running**

- Forge version: 8.0.99.99
- Operating System: Windows 10

- Plugins/Mods: Sky Factory 3

**Issue Description**
Tossing a sentient pickaxe on the ground to summon a sentient specter doesn't consume the pickaxe.

**Comment by phit** [comment]
no version info, unsupported version (we only support 1.12.2 at this point), a dupe of https://github.com/SpongePowered/SpongeForge/issues/1366 and no mod list
