### ISSUE TITLE
Structures do not generate edit=UPDATE +Code and images

### ISSUE THREAD

**Issue by Prasodym** [SpongePowered/SpongeForge#2144]
1.12.2-2655-7.1.0-BETA-3065 Spongeforge

`	| State | ID                         | Version                      | Source                                            | Signature                                |
	|:----- |:-------------------------- |:---------------------------- |:------------------------------------------------- |:---------------------------------------- |
	| U     | minecraft                  | 1.12.2                       | minecraft.jar                                     | None                                     |
	| U     | mcp                        | 9.42                         | minecraft.jar                                     | None                                     |
	| U     | FML                        | 8.0.99.99                    | forge-1.12.2-14.23.3.2655-universal.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| U     | forge                      | 14.23.3.2655                 | forge-1.12.2-14.23.3.2655-universal.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| U     | advancedrocketrycore       | 1                            | minecraft.jar                                     | None                                     |
	| U     | itemphysic                 | 1.4.0                        | minecraft.jar                                     | None                                     |
	| U     | spongeapi                  | 7.1.0-SNAPSHOT-7d8a938       | spongeforge-1.12.2-2655-7.1.0-BETA-3065.jar       | None                                     |
	| U     | sponge                     | 1.12.2-2655-7.1.0-BETA-3065  | spongeforge-1.12.2-2655-7.1.0-BETA-3065.jar       | None                                     |
	| U     | openmodscore               | 0.11.5                       | minecraft.jar                                     | None                                     |
	| U     | opencomputers|core         | 1.7.2.67                     | minecraft.jar                                     | None                                     |
	| U     | adminshop                  | 1.8.2                        | AdminShop-1.10.2-1.8.2-universal.jar              | None                                     |
	| U     | advancedrocketry           | 1.4.0.-80                    | AdvancedRocketry-1.12.2-1.4.0-80.jar              | None                                     |
	| U     | ae2stuff                   | 0.7.0.4                      | ae2stuff-0.7.0.4-mc1.12.2.jar                     | None                                     |
	| U     | appliedenergistics2        | rv5-stable-11                | appliedenergistics2-rv5-stable-11.jar             | None                                     |
	| U     | astralsorcery              | 1.8.5                        | astralsorcery-1.12.2-1.8.5.jar                    | None                                     |
	| U     | baubles                    | 1.5.2                        | Baubles-1.12-1.5.2.jar                            | None                                     |
	| U     | bdlib                      | 1.14.3.12                    | bdlib-1.14.3.12-mc1.12.2.jar                      | None                                     |
	| U     | bibliocraft                | 2.4.3                        | BiblioCraft[v2.4.3][MC1.12.0].jar                 | None                                     |
	| U     | bloodmagic                 | 1.12.2-2.2.7-90              | BloodMagic-1.12.2-2.2.7-90.jar                    | None                                     |
	| U     | bloodmoon                  | 1.5.3                        | Bloodmoon-MC1.12.2-1.5.3.jar                      | None                                     |
	| U     | bookshelf                  | 2.3.539                      | Bookshelf-1.12.2-2.3.539.jar                      | None                                     |
	| U     | brandonscore               | 2.3.7                        | BrandonsCore-1.12-2.3.7.140-universal.jar         | None                                     |
	| U     | rf-capability-adapter      | 1.0                          | capabilityadapter-1.0.jar                         | None                                     |
	| U     | catclearlag                | 0.1                          | CatClearLag-0.1.jar                               | None                                     |
	| U     | chameleon                  | 1.12-4.1.2                   | Chameleon-1.12-4.1.2.jar                          | None                                     |
	| U     | chickens                   | 6.1.0                        | chickens-6.1.0.jar                                | None                                     |
	| U     | chisel                     | MC1.12.2-0.2.0.31            | Chisel-MC1.12.2-0.2.0.31.jar                      | None                                     |
	| U     | clib                       | 1.0.2.31                     | CLib-1.0.2.31-universal.jar                       | None                                     |
	| U     | codechickenlib             | 3.1.6.339                    | CodeChickenLib-1.12.2-3.1.6.339-universal.jar     | None                                     |
	| U     | cofhcore                   | 4.3.11                       | CoFHCore-1.12.2-4.3.11.6-universal.jar            | None                                     |
	| U     | cofhworld                  | 1.1.1                        | CoFHWorld-1.12.2-1.1.1.12-universal.jar           | None                                     |
	| U     | crafttweaker               | 4.1.6                        | CraftTweaker2-1.12-4.1.6.jar                      | None                                     |
	| U     | crafttweakerjei            | 2.0.0                        | CraftTweaker2-1.12-4.1.6.jar                      | None                                     |
	| U     | customspawner              | 3.11.3                       | CustomMobSpawner-3.11.3.jar                       | None                                     |
	| U     | cyclopscore                | 0.11.5                       | CyclopsCore-1.12.2-0.11.5.jar                     | None                                     |
	| U     | darkutils                  | 1.8.208                      | DarkUtils-1.12.2-1.8.208.jar                      | None                                     |
	| U     | ptrmodellib                | 1.0.0                        | Decocraft-2.5.5_1.12.2.jar                        | None                                     |
	| U     | props                      | 2.5.5                        | Decocraft-2.5.5_1.12.2.jar                        | None                                     |
	| U     | draconicevolution          | 2.3.8                        | Draconic-Evolution-1.12-2.3.8.279-universal.jar   | None                                     |
	| U     | elevatorid                 | 1.3.6                        | ElevatorMod-1.12.2-1.3.6.jar                      | None                                     |
	| U     | embers                     | 0.230                        | embers-0.230.jar                                  | None                                     |
	| U     | endercore                  | 1.12.2-0.5.22                | EnderCore-1.12.2-0.5.22.jar                       | None                                     |
	| U     | enderio                    | 5.0.24                       | EnderIO-1.12.2-5.0.24.jar                         | None                                     |
	| U     | enderiobase                | 5.0.24                       | EnderIO-1.12.2-5.0.24.jar                         | None                                     |
	| U     | enderioconduits            | 5.0.24                       | EnderIO-1.12.2-5.0.24.jar                         | None                                     |
	| U     | enderiointegrationforestry | 5.0.24                       | EnderIO-1.12.2-5.0.24.jar                         | None                                     |
	| U     | enderiointegrationtic      | 5.0.24                       | EnderIO-1.12.2-5.0.24.jar                         | None                                     |
	| U     | enderiointegrationticlate  | 5.0.24                       | EnderIO-1.12.2-5.0.24.jar                         | None                                     |
	| U     | enderiomachines            | 5.0.24                       | EnderIO-1.12.2-5.0.24.jar                         | None                                     |
	| U     | enderiopowertools          | 5.0.24                       | EnderIO-1.12.2-5.0.24.jar                         | None                                     |
	| U     | enderstorage               | 2.4.2.126                    | EnderStorage-1.12.2-2.4.2.126-universal.jar       | None                                     |
	| U     | enderzoo                   | 1.12.1-1.4.0.49              | EnderZoo-1.12.1-1.4.0.49.jar                      | None                                     |
	| U     | environmentaltech          | 1.12.2-2.0.9c                | environmentaltech-1.12.2-2.0.9c.jar               | None                                     |
	| U     | evilcraft                  | 0.10.56                      | EvilCraft-1.12.2-0.10.56.jar                      | None                                     |
	| U     | evilcraftcompat            | 1.0.0                        | EvilCraft-1.12.2-0.10.56.jar                      | None                                     |
	| U     | extrautils2                | 1.0                          | extrautils2-1.12-1.7.5.jar                        | None                                     |
	| U     | bigreactors                | 1.12.2-0.4.5.48              | ExtremeReactors-1.12.2-0.4.5.48.jar               | None                                     |
	| U     | fluxnetworks               | 3.0.8                        | fluxnetworks-1.12.2-3.0.8.jar                     | None                                     |
	| U     | forestry                   | 5.8.0.263                    | forestry_1.12.2-5.8.0.263.jar                     | None                                     |
	| U     | forgelin                   | 1.6.0                        | Forgelin-1.6.0.jar                                | None                                     |
	| U     | ftblib                     | 5.0.1.15                     | FTBLib-5.0.1.15.jar                               | None                                     |
	| U     | ftbutilities               | 5.0.1.12                     | FTBUtilities-5.0.1.12.jar                         | None                                     |
	| U     | gendustry                  | 1.6.5.8                      | gendustry-1.6.5.8-mc1.12.2.jar                    | None                                     |
	| U     | advgenerators              | 0.9.20.12                    | generators-0.9.20.12-mc1.12.2.jar                 | None                                     |
	| U     | gravestone                 | 1.10.1                       | gravestone-1.10.1.jar                             | None                                     |
	| U     | guideapi                   | 1.12-2.1.5-60                | Guide-API-1.12-2.1.5-60.jar                       | None                                     |
	| U     | hammercore                 | 1.9.9.5.9                    | HammerCore-1.12.2-1.9.9.5.9.jar                   | None                                     |
	| U     | hatchery                   | 2.1.2                        | hatchery-1.12.2-2.1.2.jar                         | None                                     |
	| U     | waila                      | 1.8.25                       | Hwyla-1.8.25-B40_1.12.jar                         | None                                     |
	| U     | ichunutil                  | 7.0.2                        | iChunUtil-1.12.2-7.0.2.jar                        | None                                     |
	| U     | immersiveengineering       | 0.12-80                      | ImmersiveEngineering-0.12-80.jar                  | None                                     |
	| U     | immersivepetroleum         | 1.1.9                        | immersivepetroleum-1.12.2-1.1.9.jar               | None                                     |
	| U     | immersivetech              | 1.3.7                        | immersivetech-1.12-1.3.7-SevTech-Ages.jar         | None                                     |
	| U     | ic2                        | 2.8.42-ex112                 | industrialcraft-2-2.8.42-ex112.jar                | None                                     |
	| U     | industrialforegoing        | 1.12.2-1.12.2                | industrialforegoing-1.12.2-1.8.7-132.jar          | None                                     |
	| U     | integrationforegoing       | 1.12-1.6                     | IntegrationForegoing-1.12.2-1.6.jar               | None                                     |
	| U     | inventorypets              | 1.4.9.9b                     | inventorypets-1.12-1.4.9.9b.jar                   | None                                     |
	| U     | inventorytweaks            | 1.64-dev+release.110.b4fac73 | InventoryTweaks-1.64-dev.jar                      | None                                     |
	| U     | ironbackpacks              | 1.12.2-3.0.5-6               | IronBackpacks-1.12.2-3.0.5-6.jar                  | None                                     |
	| U     | ironchest                  | 1.12.2-7.0.40.824            | ironchest-1.12.2-7.0.40.824.jar                   | None                                     |
	| U     | jeibees                    | 0.9.0.5                      | jeibees-0.9.0.5-mc1.12.2.jar                      | None                                     |
	| U     | journeymap                 | 1.12.2-5.5.2                 | journeymap-1.12.2-5.5.2.jar                       | None                                     |
	| U     | jei                        | 4.8.5.159                    | Just-Enough-Items-Mod-1.12.2.jar                  | None                                     |
	| U     | librarianliblate           | 9.4                          | librarianlib-1.12.2-4.9.jar                       | None                                     |
	| U     | librarianlib               | 9.4                          | librarianlib-1.12.2-4.9.jar                       | None                                     |
	| U     | libvulpes                  | 0.2.8.-31                    | LibVulpes-1.12.2-0.2.8-31-universal.jar           | None                                     |
	| U     | luckperms                  | 4.1.7                        | LuckPerms-Sponge-4.1.7.jar                        | None                                     |
	| U     | magicbees                  | 1.0                          | MagicBees-1.12.2-3.1.9.jar                        | None                                     |
	| U     | magneticraft               | 2.2.1                        | Magneticraft_1.12-2.2.1-dev.jar                   | None                                     |
	| U     | malisisblocks              | 1.12.2-6.1.0                 | malisisblocks-1.12.2-6.1.0.jar                    | None                                     |
	| U     | malisiscore                | 1.12.2-6.4.0                 | malisiscore-1.12.2-6.4.0.jar                      | None                                     |
	| U     | malisisdoors               | 1.12.2-7.3.0                 | malisisdoors-1.12.2-7.3.0.jar                     | None                                     |
	| U     | malisisswitches            | 1.12.2-5.1.0                 | malisisswitches-1.12.2-5.1.0.jar                  | None                                     |
	| U     | mantle                     | 1.12-1.3.1.21                | Mantle-1.12-1.3.1.21.jar                          | None                                     |
	| U     | matteroverdrive            | 0.6.0.144                    | MatterOverdrive-1.12.2-0.6.0.144-universal.jar    | None                                     |
	| U     | mcef                       | 0.9                          | mcef-1.12.2-0.9.jar                               | None                                     |
	| U     | mcjtylib_ng                | 2.6.7                        | mcjtylib-1.12-2.6.7.jar                           | None                                     |
	| U     | mcmultipart                | 2.5.1                        | MCMultiPart-2.5.1.jar                             | None                                     |
	| U     | mekanism                   | 1.12.2-9.4.10.345            | Mekanism-1.12.2-9.4.10.345.jar                    | None                                     |
	| U     | mekanismgenerators         | 9.4.10                       | MekanismGenerators-1.12.2-9.4.10.345.jar          | None                                     |
	| U     | mekanismtools              | 9.4.10                       | MekanismTools-1.12.2-9.4.10.345.jar               | None                                     |
	| U     | modelloader                | 1.0.5                        | modelloader-1.0.5.jar                             | None                                     |
	| U     | modtweaker                 | 4.0.10                       | modtweaker-4.0.10.jar                             | None                                     |
	| U     | morebees                   | 1.12.2-1.4.4                 | morebees-1.12.2-1.4.4.jar                         | None                                     |
	| U     | morechickens               | 3.2.0                        | morechickens-1.12.2-3.2.0.jar                     | None                                     |
	| U     | morpheus                   | 1.12-3.3.2                   | Morpheus-1.12-3.3.2.jar                           | None                                     |
	| U     | mtlib                      | 3.0.4                        | MTLib-3.0.4.jar                                   | None                                     |
	| U     | natura                     | 1.12.2-4.3.2.42              | natura-1.12.2-4.3.2.42.jar                        | None                                     |
	| U     | notenoughwands             | 1.6.1                        | notenoughwands-1.12-1.6.1.jar                     | None                                     |
	| U     | nuclearcraft               | 2.10d                        | NuclearCraft-2.10d--1.12.2.jar                    | None                                     |
	| U     | nucleus                    | 1.3.10-S7.0                  | Nucleus-1.3.10-S7.0-MC1.12.2-plugin.jar           | None                                     |
	| U     | omlib                      | 3.0.0-138                    | omlib-1.12.2-3.0.0-138.jar                        | None                                     |
	| U     | openblocks                 | 1.7.6                        | OpenBlocks-1.12.2-1.7.6.jar                       | None                                     |
	| U     | opencomputers              | 1.7.2.67                     | OpenComputers-MC1.12.2-1.7.2.67.jar               | None                                     |
	| U     | openmods                   | 0.11.5                       | OpenModsLib-1.12.2-0.11.5.jar                     | None                                     |
	| U     | openmodularturrets         | 3.0.0-236                    | openmodularturrets-1.12.2-3.0.0-236.jar           | None                                     |
	| U     | p455w0rdslib               | 2.0.29                       | p455w0rdslib-1.12-2.0.29.jar                      | None                                     |
	| U     | harvestcraft               | 1.12.2t                      | Pam's+HarvestCraft+1.12.2t.jar                    | None                                     |
	| U     | plustic                    | 6.4.0.0                      | plustic-6.4.0.0.jar                               | None                                     |
	| U     | pneumaticcraft             | 1.12.2-0.6.1-176             | pneumaticcraft-repressurized-1.12.2-0.6.1-176.jar | None                                     |
	| U     | practicallogistics2        | 3.0.3                        | practicallogistics2-1.12.2-3.0.3.jar              | None                                     |
	| U     | pressure                   | 1.3.1.9                      | pressure-1.3.1.9-mc1.12.2.jar                     | None                                     |
	| U     | quantumstorage             | 4.4.11                       | QuantumStorage-1.12-4.4.11.jar                    | None                                     |
	| U     | randomthings               | 4.1.5                        | RandomThings-MC1.12.2-4.1.5.jar                   | None                                     |
	| U     | reborncore                 | 3.7.2.245                    | RebornCore-1.12.2-3.7.2.245-universal.jar         | None                                     |
	| U     | redstonearsenal            | 2.3.11                       | RedstoneArsenal-1.12.2-2.3.11.5-universal.jar     | None                                     |
	| U     | redstoneflux               | 2.0.1                        | RedstoneFlux-1.12-2.0.1.2-universal.jar           | None                                     |
	| U     | refinedstorage             | 1.5.33                       | refinedstorage-1.5.33.jar                         | None                                     |
	| U     | xreliquary                 | 1.12.2-1.3.4.757             | Reliquary-1.12.2-1.3.4.757.jar                    | None                                     |
	| U     | rftools                    | 7.33                         | rftools-1.12-7.33.jar                             | None                                     |
	| U     | rftoolscontrol             | 1.8.1                        | rftoolsctrl-1.12-1.8.1.jar                        | None                                     |
	| U     | rftoolsdim                 | 5.53                         | rftoolsdim-1.12-5.53.jar                          | None                                     |
	| U     | roguelike                  | 1.7.2                        | RoguelikeDungeons-1.12.2-1.7.2.jar                | None                                     |
	| U     | securitycraft              | v1.8.2.4                     | SecurityCraft-1.12.jar                            | None                                     |
	| U     | lteleporters               | 1.11.2-2.1.5                 | simpleteleporters-1.12-2.1.5.jar                  | None                                     |
	| U     | simplyjetpacks             | 2.2.2.28                     | SimplyJetpacks2-1.12.2-2.2.2.28.jar               | None                                     |
	| U     | solarfluxreborn            | 3.50r                        | SolarFluxReborn_1.12.2-3.50r.jar                  | None                                     |
	| U     | sonarcore                  | 5.0.9                        | sonarcore-1.12.2-5.0.9.jar                        | None                                     |
	| U     | testmod                    | 1.0                          | Space_Remixcore-1.0.jar                           | None                                     |
	| U     | stackban                   | 0.3.0                        | stackban-7.1.0-0.3.0.jar                          | None                                     |
	| U     | stevescarts                | 2.4.18.92                    | StevesCarts-1.12.2-2.4.18.92.jar                  | None                                     |
	| U     | storagedrawers             | 1.12-5.3.5                   | StorageDrawers-1.12.2-5.3.6.jar                   | None                                     |
	| U     | tconstruct                 | 1.12.2-2.9.1.65              | TConstruct-1.12.2-2.9.1.65.jar                    | None                                     |
	| U     | techreborn                 | 2.13.4.573                   | TechReborn-1.12.2-2.13.4.573-universal.jar        | None                                     |
	| U     | teslacorelib               | 1.0.13                       | tesla-core-lib-1.12-1.0.13.jar                    | None                                     |
	| U     | teslacorelib_registries    | 1.0.13                       | tesla-core-lib-1.12-1.0.13.jar                    | None                                     |
	| U     | thaumcraft                 | 6.1.BETA13                   | Thaumcraft-1.12.2-6.1.BETA13.jar                  | None                                     |
	| U     | thermalcultivation         | 0.1.5                        | ThermalCultivation-1.12.2-0.1.5.3-universal.jar   | None                                     |
	| U     | thermaldynamics            | 2.3.11                       | ThermalDynamics-1.12.2-2.3.11.7-universal.jar     | None                                     |
	| U     | thermalexpansion           | 5.3.11                       | ThermalExpansion-1.12.2-5.3.11.13-universal.jar   | None                                     |
	| U     | thermalfoundation          | 2.3.11                       | ThermalFoundation-1.12.2-2.3.11.8-universal.jar   | None                                     |
	| U     | thermalinnovation          | 0.1.0                        | ThermalInnovation-1.12.2-0.1.0.2-universal.jar    | None                                     |
	| U     | thutessentials             | 2.1.9                        | thutessentials-1.12.2-2.1.9.jar                   | None                                     |
	| U     | tinker_io                  | release 2.6.1                | tinker_io-1.12.2-release+2.6.1.jar                | None                                     |
	| U     | tinkertoolleveling         | 1.12-1.0.3.DEV.56fac4f       | TinkerToolLeveling-1.12-1.0.3.jar                 | None                                     |
	| U     | treechopper                | 1.2.4                        | Tree-Chopper-Mod-1.12.2.jar                       | None                                     |
	| U     | twilightforest             | 3.6.345                      | twilightforest-1.12.2-3.6.345-universal.jar       | None                                     |
	| U     | universalmodifiers         | 1.12.2-1.0.9a                | valkyrielib-1.12.2-2.0.9b.jar                     | None                                     |
	| U     | valkyrielib                | 1.12.2-2.0.9b                | valkyrielib-1.12.2-2.0.9b.jar                     | None                                     |
	| U     | veinminer                  | 0.38.1                       | VeinMiner-1.12-0.38.1.639+134fb1e.jar             | None                                     |
	| U     | veinminermodsupport        | 0.38.1                       | VeinMiner-1.12-0.38.1.639+134fb1e.jar             | None                                     |
	| U     | wawla                      | 2.5.253                      | Wawla-1.12.2-2.5.253 (1).jar                      | None                                     |
	| U     | webapi                     | 5.0.9-S7.1                   | webapi-5.0.9-S7.1.jar                             | None                                     |
	| U     | wct                        | 3.9.62                       | WirelessCraftingTerminal-1.12.2-3.9.62.jar        | None                                     |
	| U     | wizardry                   | 0.8.5                        | wizardry-0.8.5.jar                                | None                                     |
	| U     | worldedit                  | 6.1.8                        | worldedit-forge-mc1.12-6.1.8-dist.jar             | None                                     |
	| U     | worldlimiter               | 1.2.0                        | worldlimiter-1.11.2-1.2.0.jar                     | None                                     |
	| U     | xnet                       | 1.6.9                        | xnet-1.12-1.6.9.jar                               | None                                     |
	| U     | zerocore                   | 1.12-0.1.2.1                 | zerocore-1.12-0.1.2.1.jar                         | None                                     |
`

**Comment by phit** [comment]
use the issue template and try the search before opening an issue

**Comment by Prasodym** [comment]
Update: [https://pastebin.com/LbFiZDmz](url)

- I could capture the codes here to create

- Minecraft default world are also faulty see picture

![2018-05-14_08 55 22](https://user-images.githubusercontent.com/38152214/39992528-6529eaea-5773-11e8-9717-8eabec893337.png)
**Default World one** 

![2018-05-14_08 54 28](https://user-images.githubusercontent.com/38152214/39992569-8425b3f2-5773-11e8-975b-77a5ed0cf5a1.png)
**Default world two**
