### ISSUE TITLE
Visual Glitch - SevTech

### ISSUE THREAD

**Issue by Keaton1188** [SpongePowered/SpongeForge#2145]
**I am currently running**

- SpongeForge version: 1.12.2-2655-7.1.0-BETA-3065
- Forge version: 14.23.3.2655
- Java version: 1.8.0_151-b12
- Operating System: CentOS Linux release 7.2.1511

- Plugins/Mods: SevTech 

**Issue Description**
Hi there.. having a visual glitch with IE (Immersive Engineering) 
"https://www.youtube.com/watch?v=xCID_Vtu46c&feature=youtu.be"

Vid to show what its doing.

This does not happen in SP.

**Comment by Aaron1011** [comment]
Are you able to reproduce this with just IE and Sponge?

**Comment by Keaton1188** [comment]
Probably not anytime soon.. sorry.

**Comment by Keaton1188** [comment]
Doesn't seem to be an issue anymore, closing.
