### ISSUE TITLE
Hard lock on player join event

### ISSUE THREAD

**Issue by juniorjunior** [SpongePowered/SpongeForge#2146]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2655-7.1.0-BETA-3070
- Forge version: forge-1.12.2-14.23.3.2655-universal
- Java version: Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12
- Operating System: CentOS 7.4

- Plugins/Mods: 
```
[12:48:19] [Netty Epoll Server IO #5/INFO] [FML]: Client attempting to join with 70 mods :
cyclopscore@0.11.5,
ctgui@1.0.0,
astralsorcery@1.8.10,
tropicraft@7.1.3.62,
woot@1.12.2-1.2.1,
jei@4.9.1.175,
cofhcore@4.4.1,
thermalcultivation@0.2.0,
bibliocraft@2.4.3,
thermalinnovation@0.2.1,
thermalfoundation@2.4.1,
wawla@2.5.256,
mcp@9.42,
cookingforblockheads@6.3.26,
journeymap@1.12.2-5.5.2,
reauth@3.6.0,
evilcraft@0.10.56,
chameleon@1.12-4.1.3,
microblockcbe@2.4.2.58,
foamfixcore@7.7.4,
cofhworld@1.1.1,
sonarcore@5.0.9,
waila@1.8.25,
integrateddynamicscompat@1.0.0,
redstonearsenal@2.4.2,
crafttweaker@4.1.8,
enderstorage@2.4.2.126,
mcjtylib_ng@2.6.7,
mcmultipart@2.5.1,
forge@14.23.3.2655
,malisisdoors@1.12.2-7.3.0,
ironchest@1.12.2-7.0.42.827,
minecraft@1.12.2,
malisiscore@1.12.2-6.4.0,
commoncapabilities@1.4.0,
crafttweakerjei@2.0.2,
thermaldynamics@2.4.1,
biomesoplenty@7.0.1.2387,
mtlib@3.0.4,baubles@1.5.2,
redstoneflux@2.0.1,
modtweaker@4.0.12,
veinminermodsupport@0.38.2,
chickenchunks@2.4.1.71,
totemic@1.12.2-0.11.1,
eleccore@1.8.434,
evilcraftcompat@1.0.0,
actuallyadditions@1.12.2-135,
bloodmoon@1.5.3,
mantle@1.12-1.3.2.24,
integrateddynamics@0.11.11,
veinminer@0.38.2,
fluxnetworks@3.0.8,
storagedrawers@1.12-5.3.5,
deepresonance@1.6.0,
integratedtunnels@1.5.5,
natura@1.12.2-4.3.2.49,
FML@8.0.99.99,
thermalexpansion@5.4.2,
enderutilities@0.7.8,
wrcbe@2.3.0,
integratedtunnelscompat@1.0.0,
betteragriculture@1.2.3,
minecraftmultipartcbe@2.4.2.58,
forgemultipartcbe@2.4.2.58,
foamfix@0.9.9.1-1.12.2,
practicallogistics2@3.0.3,
codechickenlib@3.1.8.341,
chiselsandbits@14.16,
wailaharvestability@1.1.12
[12:48:19] [Netty Epoll Server IO #5/INFO] [FML]: Attempting connection with missing mods [
spongeapi,
sponge,
command-utils,
discordintegration,
griefprevention,
luckperms,
nucleus,
sleepvote,
tickprofiler] at CLIENT
```

**Issue Description**
The server seems to hang sometimes when a player tries to connect. This shows up as a total freeze, except that the "command prompt" comes back, just doesn't do anything (i.e. a "list" in the console gives another ">" prompt, but doesn't show anything. Same with other commands.). A warmroast debug output seems to show a lock contention issue (screenshot attached). If this is not a Sponge issue you have my apologies, but I couldn't find anything pointing elsewhere.
![spongelock](https://user-images.githubusercontent.com/1612158/40012418-9a01afb4-5778-11e8-8a3e-6c2981d85261.png)

Logs: https://gist.github.com/juniorjunior/7559d3ae505ef1874dee88492a5940c3
WarmRoast output: https://www.circlecraft.info/spongelock.png

**Comment by gabizou** [comment]
You're not listing any mods or plugins, yet the warm roast shows there are plugins/mods installed. Sponge itself only throws the event (as shown in the stack trace), but a plugin is performing a permission check and that permission check is doing some lookups. Not a SpongeForge issue. More likely either a GriefPrevention issue or whatever permissions plugin you're using.

**Comment by juniorjunior** [comment]
Hmm, the full list of both mods and Sponge plugins were on the two lines without any line-breaks. That's my bad and wouldn't expect anyone to try and parse that out.

I did just update both GriefPrevention and LuckPerms after making this issue, but saw nothing in either of their changelogs which might be addressing a lock contention or login event issue. We shall see. Thanks for the feedback.

**Comment by gabizou** [comment]
Maybe a communication failure from the database to server for fetching permissions?

**Comment by juniorjunior** [comment]
Using built-in, which I assume is SQLite. If it persists after the update and I can get no traction elsewhere I'll see if switching to MySQL/MariaDB does anything.
