### ISSUE TITLE
ClassCastException in Phase Tracker

### ISSUE THREAD

**Issue by JoeSGT** [SpongePowered/SpongeForge#2147]
**I am currently running**

- SpongeForge version: 1.12.2-2655-7.1.0-BETA-3074                                                                                                                              
- Forge version: 14.23.3.2655                                                                                                                                         
- Java version: 8
- Operating System: windows 

- Plugins/Mods:
RedstoneFlux-1.12-2.0.1.2-universal 
spongeforge-1.12.2-2655-7.1.0-BETA-3074 
CodeChickenLib-1.12.2-3.1.8.341-universal
BrandonsCore-1.12-2.4.2.157-universal
Draconic-Evolution-1.12-2.3.11.290-universal

**Issue Description**
This issue is related to this https://github.com/SpongePowered/SpongeForge/issues/1903 also i get this error whenever you attempt to mine the lootcore
here are the steps on how to do this error i did all this in singleplayer for a clean start but you can do the same on serverside
1) go into creative and get a Draconic Staff of power
2) Set the Dig A.O.E to 5x5
3) then Spam left click (Mining) on the ground and you'll manage to mine the lootcore 
4) lastly look in console you'll get the errors which ill post them here

[debug.log](https://github.com/SpongePowered/SpongeForge/files/2002862/debug.log)
[latest.log](https://github.com/SpongePowered/SpongeForge/files/2002863/latest.log)

**Comment by phit** [comment]
`java.lang.ClassCastException: org.spongepowered.common.event.tracking.PhaseContext cannot be cast to org.spongepowered.common.event.tracking.context.GeneralizedContext`

**Comment by CDAGaming** [comment]
Players on my server are reporting Elytras that are picked up vanishing from their inventories as well. No clue if it could be related to this (If not, I'll remove this comment)

**Comment by gabizou** [comment]
Fixed the class cast exception.
