### ISSUE TITLE
Sponge world crash

### ISSUE THREAD

**Issue by yyeerai** [SpongePowered/SpongeForge#2153]
**I am currently running**
- SpongeForge version:  spongeforge-1.12.2-2655-7.1.0-BETA-3074
- Forge version:  forge-1.12.2-14.23.3.2655-universal
- Java version: 1.8
- Operating System: centos 6.8

- Plugins/Mods: 
Plugins (25): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, CatClearLag, DailyRewards, EasyKits, EconomyLite, GTS, GiftCode, GriefPrevention, Holograms, LuckPerms, Nucleus, PixelAutoMessages, PixelVip, PixelmonEconomyBridge, PlaceholderAPI, Pok�Stops, ProjectCore, Tournaments, UltimateChat, VirtualChest, WorldEdit, wolrdpc
Mods (9): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Pam's HarvestCraft, Pixel Extras, Pixelmon

**Issue Description**
This is not the case for spongeforge-1.12.2-2655-7.1.0-BETA-3054, which occurs with the latest version

 - Crash report： https://gist.github.com/yyeerai/b58ca7157a8d9cabd4f6e218311ec70a

**Comment by phit** [comment]
cant reproduce on latest, please add what mods are needed to get this to happen

**Comment by phit** [comment]
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/2158
