### ISSUE TITLE
Sponge config - Plugins directory issue

### ISSUE THREAD

**Issue by Keaton1188** [SpongePowered/SpongeForge#2154]
**I am currently running**
 
- SpongeForge version: 1.12.2-2655-7.1.0-BETA-7034
- Forge version: 14.23.3.2655
- Java version: 1.8.0_151-b12
- Operating System: CentOS Linux release 7.2.1511

- Plugins/Mods: FTB Continuum 

**Issue Description**
Hi there.. I am trying to make it so sponge points to a /plugins folder and not /mods. I changed it in the config (like we've done for all our servers..) and when I reboot the server is just reverts what I do. 

![untitled](https://user-images.githubusercontent.com/24898745/40128454-907c1512-5929-11e8-918b-eee062b8d886.png)

**Comment by XakepSDK** [comment]
Does this directory exists? Show us your logs.

**Comment by phit** [comment]
Can't reproduce on 3076, gonna need more info. Please upload your global.conf and debug.log

**Comment by Keaton1188** [comment]
I tried with 3076 at first and had the same issue so decided to go back a few version to see if that would help. 

global.conf -  https://pastebin.com/0JBRfd1w

debug.log - 
[debug.zip](https://github.com/SpongePowered/SpongeForge/files/2010871/debug.zip)

Actually seems like the whole config is just resetting when I start up the server..

**Comment by Keaton1188** [comment]
Sorry all.. ignore me.

Me being stupid, closing .
