### ISSUE TITLE
Unable to make new dimension/world from forge mod

### ISSUE THREAD

**Issue by Thutmose** [SpongePowered/SpongeForge#2156]
**I am currently running**

- SpongeForge version: 3077 (was latest when I downloaded it) (Also applies to 3080)
- Forge version: 14.23.3.2655
- Java version: 1.8.0_111
- Operating System: Windows 10

- Plugins/Mods:
§cMods§r§f (§r§f22§r§f): §r§aMinecraft§r, §r§aMinecraft Coder Pack§r, §r§aForge Mod Loader§r, §r§aMinecraft Forge§r, §r§aSpongeAPI§r, §r§aSpongeForge§r, §r§aFoamFix§r, §r§aFoamFixCore§r, §r§aIn-game NBTEdit - Pokecube Edition§r, §r§aLagGoggles§r, §r§aPokecube Compat§r, §r§aPokecube Model Loader§r, §r§aPokecube Movess§r, §r§aPokecube Origin§r, §r§aPokécube Core§r, §r§aPokécube Mobs§r, §r§aPokécube Revival§r, §r§aThut Core§r, §r§aThut's Bling§r, §r§aThut's Tech§r, §r§aThut's Wearables§r, §r§aThutCore Compat§r

**Issue Description**
I try to make a new secret base dimension using the pokecube secret base block made via secretpower, and nothing happens client side.  server side there is an error logged about null world UUID.  I cannot allocate a UUID via just forge, so I don't think I can fix this one on my side.

If needed, I can see about making a test mod for this later.

debug.log: https://gist.github.com/Thutmose/d81e024015544186ec29e5df7f40c1bb#file-debug-log
latest.log: https://gist.github.com/Thutmose/d81e024015544186ec29e5df7f40c1bb#file-latest-log

**Comment by Thutmose** [comment]
Until I get around to extracting the coded needed for the dimension generation (it is fairly interconnected with a bunch of other crap), the simplest way I can get this replicate-able is as follows:

Make a server, add spongeforge to mods folder, also add this jar:
https://minecraft.curseforge.com/projects/pokecube-aoi/files/2560258

Start server, join server (client also needs that jar), select some random starter (bulbasaur works), and then run the command `/poketm secretpower` This should give you a TM.

Right click with your starter pokecube, it should be sent out, then right click the mob with the TM, and use down arrow to make sure the move is selected in the pokemob gui.

Look at a random terrain block (dirt, stone, log, etc) and press G, then open chat and click the message.  The random terrain block should turn into a chiseled stone block.  Right click that chiseled stone block, and the error should appear in the server's console/log.

**Comment by Zidane** [comment]
I need to see the exact code you're using to create the dimension.

**Comment by Thutmose** [comment]
```Java
            MinecraftServer mcServer = overworld.getMinecraftServer();
            ISaveHandler savehandler = overworld.getSaveHandler();
            world1 = (WorldServer) (new WorldServerMulti(mcServer, savehandler, dim, overworld, mcServer.profiler)
                    .init());
            WorldProviderSecretBase.initToDefaults(world1.getWorldBorder());
            world1.addEventListener(new ServerWorldEventHandler(mcServer, world1));
            MinecraftForge.EVENT_BUS.post(new WorldEvent.Load(world1));
            mcServer.setDifficultyForAllWorlds(mcServer.getDifficulty());
            registered = getInstance().dims.contains(dim);
            if (!registered)
            {
                registerDim(dim);
                PokecubeMod.core.getConfig().save();
                getInstance().syncToAll();
            }
```

https://github.com/Thutmose/Pokecube/blob/1.12.x/Pokecube%20Core/src/main/java/pokecube/core/world/dimensions/PokecubeDimensionManager.java#L60-L74

**Comment by Thutmose** [comment]
Here is a test mod for this issue:

[dimspam.zip](https://github.com/SpongePowered/SpongeForge/files/2014369/dimspam.zip)

https://github.com/Thutmose/Thut/blob/1.12.x/Misc/DimSpam/src/main/java/thut/dimspam/DimSpam.java

How to use:

it adds a command, /dimspam, used as follows:
`/dimspam <dim>` loads or creates a dimension of id <dim>, if <dim> is less than 20, it is a nether world, otherwise if less than 40, is an overworld, otherwise is an end, the player is then transfered to this dimension*
`/dimspam check` will say your current dimension.

*doesn't check if location is safe, so you should probably do this from creative mode.

Without spongeforge, it behaves as previously mentioned.  With spongeforge, it gives the error earlier up this issue.

Note: This test mod does not work on multiplayer, as it doesn't include the packets for syncing the new dimension info to the player.

**Comment by bloodmc** [comment]
@Thutmose why are you not using Forge's initDimension to hotload your dimension?

https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/common/DimensionManager.java#L227

**Comment by Thutmose** [comment]
Does the bug still occur if I use that?  Iirc I was not using it, so I could implement my own WorldServerMulti with a different borderListener, I could probably just use reflection to deal with the default one instead though

**Comment by bloodmc** [comment]
The bug should not occur if you use that as we already support Forge's DimensionManager. If you need additional functionality in Forge's DimensionManager then I would suggest opening a PR with Forge or a ticket requesting the feature. Bypassing it will cause issues for mods such as ours that don't expect other mods to bypass Forge's API.

**Comment by Thutmose** [comment]
Ahh, I found another reason, the default WorldServerMulti does not support custom worldinfo, so trying to do anything with that won't work

**Comment by bloodmc** [comment]
You should be using Forge's perWorldStorage system for custom data per dimension.

https://mcforge.readthedocs.io/en/latest/datastorage/worldsaveddata/

Both Forge and Vanilla use a single savehandler so it makes perfect sense why WorldServerMulti would delegate to overworld's WorldInfo as that represents the only level.dat in existence.

**Comment by Thutmose** [comment]
WorldInfo is not related to saving, it is things like generator options, world type (flat, default, etc)

**Comment by bloodmc** [comment]
Yes it is. WorldInfo represents level.dat which is written to disk using the world's savehandler.

https://minecraft.gamepedia.com/Level_format

The point still stands. You should be using Forge's PerWorldStorage system as shown in docs above. This is how mods get around the single savehandler.

**Comment by Thutmose** [comment]
I am letting the world save it's data to wherever it goes by default, if you look at the test mod, it uses the same savehandler that forge does

**Comment by bloodmc** [comment]
Mystcraft uses initDimension and provides dimensions with full customization. There is no reason why you cannot do the same. If you bypass Forge's API you will have problems with Sponge.

**Comment by Thutmose** [comment]
Can you direct me to their source, or an example of how they do it? I could probably get something working, but seeing theirs will help, this was the quickest implementation I came up with, they possibly have a better way

**Comment by bloodmc** [comment]
Mystcraft is closed source. You can search for other open source mods that add dimensions such as RFTools. You can also ask for help in Forge's IRC channel.

**Comment by Thutmose** [comment]
Well, if you can confirm that making that change to the test mod fixes the issue, you can close this issue, I won't be able to test this until Wednesday

**Comment by bloodmc** [comment]
I ran the command `/dimspam 11` with the following code

```java
    @Subscribe
    public void serverStarting(FMLServerStartingEvent ev)
    {
        if ((ev.getServer().getCommandManager() instanceof ServerCommandManager))
        {
            ServerCommandManager scm = (ServerCommandManager) ev.getServer().getCommandManager();
            scm.registerCommand(new CommandBase()
            {

                @Override
                public String getName()
                {
                    return "dimspam";
                }

                @Override
                public String getUsage(ICommandSender arg0) {
                    return "/dimspam <newdim|check>";
                }

                @Override
                public void execute(MinecraftServer server, ICommandSender sender, String[] args) throws CommandException {
                    if (args.length != 1) throw new CommandException(getUsage(sender));
                    EntityPlayer player = getCommandSenderAsPlayer(sender);
                    if (args[0].equals("check"))
                    {
                        player.sendMessage(new TextComponentString(
                                "Current Dim: " + player.getEntityWorld().provider.getDimension()));
                        return;
                    }
                    int dim = parseInt(args[0]);
                    createNewSecretBaseDimension(dim, dim < 20 ? DimensionType.NETHER
                            : dim < 40 ? DimensionType.OVERWORLD : DimensionType.THE_END);
                    WorldServer world1 = DimensionManager.getWorld(dim);
                    if (player.getLastPortalVec() == null) player.setPortal(player.getPosition().up(20));
                    server.getPlayerList().transferPlayerToDimension((EntityPlayerMP) player, dim,
                            new Teleporter(world1));
                }

                public boolean createNewSecretBaseDimension(int dim, DimensionType type)
                {
                    if (!DimensionManager.isDimensionRegistered(dim)) DimensionManager.registerDimension(dim, type);
                    /*WorldServer overworld = DimensionManager.getWorld(0);
                    WorldServer world1 = DimensionManager.getWorld(dim);
                    boolean registered = true;
                    if (world1 == null)
                    {
                        MinecraftServer mcServer = overworld.getMinecraftServer();
                        ISaveHandler savehandler = overworld.getSaveHandler();
                        world1 = (WorldServer) (new WorldServerMulti(mcServer, savehandler, dim, overworld,
                                mcServer.profiler).init());
                        world1.addEventListener(new ServerWorldEventHandler(mcServer, world1));
                        MinecraftForge.EVENT_BUS.post(new WorldEvent.Load(world1));
                        mcServer.setDifficultyForAllWorlds(mcServer.getDifficulty());
                    }
                    return !registered;*/
                    DimensionManager.initDimension(dim);
                    return true;
                }
            });
        }
    }
```

![Works](https://i.imgur.com/F241pk7.png "Success")
