### ISSUE TITLE
OpenBlocks/OpenModsLib Crash

### ISSUE THREAD

**Issue by OneTrueVex** [SpongePowered/SpongeForge#2157]
- SpongeForge version: 1.12.2-2655-7.1.0-BETA-3080
- Forge version: 1.12.2-14.23.3.2655
- Java version: 1.8.0_51
- Operating System: Windows 10 Home

- Plugins/Mods:
Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, §Aether Legacy, Baubles, BiblioCraft, Biomes O' Plenty, Bloodmoon, Carry On, CosmeticArmorReworked, Decocraft, Disenchanter, Doggy Talents, DrZhark's CustomSpawner, DrZhark's Mo'Creatures Mod, DungeonTactics, Fast Leaf Decay, Fence Overhaul, Foamflower, Gravestone Mod, Inventory Tweaks, Iron Backpacks, Iron Chest, Just Enough Items, Long Fall Boots, MalisisCore, MalisisDoors, Mantle, Minecraft Comes Alive, MrCrayfish's Furniture Mod, Parachute Mod, PortalGun, RadixCore, Roguelike Dungeons, Salty Mod, Simple Teleporters, SpawnerCraft, Tails, Thaumcraft, The Betweenlands, The Twilight Forest, Thut Core, Thut's Tech, ThutCore Compat, Vending, iChunUtil, mercurius_updater, ptrmodellib

The server crashes while starting up when OpenBlocks/OpenModsLib are in the server's mods folder. Client is fine, so I know it's sponge related. Here's the server log and the crash log:

https://gist.github.com/OneTrueVex/dab2adfb1dd93d85b0d8a1005cf0f5b0
https://gist.github.com/OneTrueVex/52eeff7630eafa74757e8106abe10f0f

**Comment by phit** [comment]
cant reproduce with just sponge, openmodslib and openblocks

OpenBlocks-1.12.2-1.7.6.jar 
OpenModsLib-1.12.2-0.11.5.jar
spongeforge-1.12.2-2655-7.1.0-BETA-3096.jar
