### ISSUE TITLE
sponge Crash

### ISSUE THREAD

**Issue by yyeerai** [SpongePowered/SpongeForge#2158]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2655-7.1.0-BETA-3080
- Forge version: forge-1.12.2-14.23.3.2655-universal
- Java version: 1.8
- Operating System: centos 6.8

- Plugins/Mods:
  -- Plugins (25): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, CatClearLag, DailyRewards, EasyKits, EconomyLite, GTS, GiftCode, GriefPrevention, Holograms, LuckPerms, Nucleus, PixelAutoMessages, PixelVip, PixelmonEconomyBridge, PlaceholderAPI, Pok�Stops, ProjectCore, Tournaments, UltimateChat, VirtualChest, WorldEdit, wolrdpc
  -- Mods (9): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Pam's HarvestCraft, Pixel Extras, Pixelmon
**Issue Description**
Crashes immediately after opening the server
### Crash report：https://gist.github.com/yyeerai/c88f0d9afb5c3aae9f5217e5a609656b

**Comment by gabizou** [comment]
Have you tried just sponge and mods but no plugins?

**Comment by phit** [comment]
no reply and cant reproduce with just sponge
