### ISSUE TITLE
Tinker's Construct GUI Issues

### ISSUE THREAD

**Issue by WolfeyWolfey** [SpongePowered/SpongeForge#2159]
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2655-7.1.0-BETA-3077.jar
- Forge version: 2665 
- Java version: 8
- Operating System: Linux

- Plugins/Mods:Thaumcraft (Needs Baubles)
Pam's Harvest Craft
Actual Additions
OpenBlocks (Needs Openmods)
Applied Energistics
Extra Utilities
Tinker's Construct (Needs mantle)
HWYLA
Iron Chests
IndustrialCraft 2
EnderIO (EnderCore)
Just enough Items
Gendustry (Needs BDLib and Forestry)
MineColonies
Forestry (Needed by Gendustry)
Immersive Engineering (Connected Texture mod)
More Bees
Blood Magic (Needs Guide-API)
BiblioCraft
ExtremeReactors (Needs Zerocore)
Project Red (Needs Code Chicken lib and MrTJLib and ForgeMultipartCBE)
Thermal Expansion, Dynamics, Innovation (Needs thermalfoundation and COFH core and Redstone Flux)
Tails (Needs foxlib)	ic
Avaritia (Needs CodeChickenLib)
Chisel (Requires connected texture mod)
DecoCraft (Requires PTRLib)
Storage Drawers (Requires Chameleon)
Draconic Evolution (requires Brandon's core)
Appleskin
Inventory Tweaks
Roguelike Dungeons
Fast Leaf Decay
Light Overlay
Item Scroller
Inductive Logistics Pipes (Requires CD4017BElib)
OpenComputers
Natura (needs mantle)
Advanced Solar Panels (needs IC2)
Thaumic JEI
Thaumic Inventory Scanning
Thaumic Peripheryr
MMC restrict
Nations
RandomTweaks
Nucleus
LuckPerms
World edit

**Issue Description**
Tinker's Construct GUI not able to function under latest sponge updates.

When a player right clicks a stencil table no menu appears, and an error appears in the server console. A crash does not occur.

I posted this same issue on the Tconstruct github and they concluded it's something being done on sponge's side.

When a player right clicks a stencil table:
https://pastebin.com/MpXt3P1Y

**Comment by phit** [comment]
pretty sure this is already fixed on latest (3080), if not reply and ill reopen

**Comment by WolfeyWolfey** [comment]
Confirming that updating to 3080 fixed our problem. Thank you!
