### ISSUE TITLE
Right clicking sheep doesnt drop wool since 3074

### ISSUE THREAD

**Issue by Whazaaaaa** [SpongePowered/SpongeForge#2160]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2655-7.1.0-BETA-3082 started since 3074
- Forge version: forge-1.12.2-14.23.3.2655-universal
- Java version: 8
- Operating System: Windows/Linux

- Plugins/Mods: None

**Issue Description**
I've tested this locally only on sheeps. But on modded server this also didnt work on things like seeds.
So when you for example shear a sheep, no wool drops, but the sheep is sheared. Another example I heard is that with right clicking plants it doesnt drop items aswell. Theres a mod that replaces the seed and drops the item. But yeah easiest to test on sheep.

Theres no exceptions in the console or anything.

**Comment by gabizou** [comment]
I can't verify if this fix fixes the mod item not dropping items, but it would make sense if it does due to it extending the `ItemShears` item to perform those interactions.
