### ISSUE TITLE
ItemFrame Not Dropping Items

### ISSUE THREAD

**Issue by CDAGaming** [SpongePowered/SpongeForge#2163]
**I am currently running**

- SpongeForge version: 1.12.2-2655-7.1.0-BETA-3095
- Forge version: 14.23.3.2655
- Java version: 1.8.0_161
- Operating System: Windows 10 x64

- Plugins (12): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge,  FastAsyncWorldEdit, CatClearLag, LuckPerms, Nucleus, Prism, ServerListPlus, Total Economy, WorldEdit
- Mods (12): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Aether II, Aether Legacy, FTB Guides, FTB Utilities, FTBLib, Orbis API

**Issue Description**
1. Trying to Pick up an Elytra from an Item Frame, results in it instantly vanishing upon hitting the item frame
2. Sometimes The Elytra fails to properly deploy, leading to you falling to your death

Server Crash (Experienced while Testing, but may not be relevant here): https://gist.github.com/CDAGaming/9ac4966e1adab51d40f6cc97d1acabcc

**Comment by gabizou** [comment]
The crash is a simple fix. I just need to figure out why the item frames aren't dropping items. Doesn't look like item frames in general drop anymore either.

**Comment by parlough** [comment]
Don't have a chance to look into it right now, but I made this change a while back https://github.com/SpongePowered/SpongeCommon/commit/dad0dfa6fc88baec467eb3af38d060727260289b and Forge did as well, but in my testing it worked fine and no other issues have popped up.

**Comment by gabizou** [comment]
~~@Meronat just looking over the commit, looks like you forgot to make the shift after setting the item to null. Will test again now with a potential fix.~~
Edit: did not change anything. Stepping through what's going on with hanging items and why they are not dropping items.

**Comment by the-whapow** [comment]
I am having this issue as well. 
spongeforge-1.12.2-2655-7.1.0-BETA-3082.jar
Forge: 14.23.3.2655
Game: Java 1.12.2

Any suggestions on a work around?

**Comment by seisatsu** [comment]
I can confirm this issue. I discovered the issue on my server yesterday, so I tested client-side with SpongeForge and with Forge only. Latest version of SpongeForge prevents item frames from dropping items, while Forge alone does not.

I am using spongeforge-1.12.2-2655-7.1.0-BETA-3088.jar on the server.

**Comment by ryantheleach** [comment]
`return EntityUtil.entityOnDropItem((EntityHanging) (Object) this, stack, offsetY, this.posX + xOffset, this.posZ + zOffset);`

From a far distance, having [offsetY ](https://github.com/SpongePowered/SpongeCommon/commit/888c151663e673060987a8f99f4dbe5eaf6dbb92#diff-848a957b99a542da447136cf79553609R129)not having the position added looks slightly suspect. Is it ok?
