### ISSUE TITLE
Continuum - Forge - Sponge

### ISSUE THREAD

**Issue by Keaton1188** [SpongePowered/SpongeForge#2166]
**I am currently running** 

- SpongeForge version: 1.12.2-2655-7.1.0-BETA-3080
- Forge version: 14.23.2.2655
- Java version: 1.8.0_151-b12
- Operating System: CentOS Linux release 7.2.1511

- Plugins/Mods: FTB Continuum

**Issue Description**  This is server/client related, FTB Continuum is not using a recommended version of forge this causes issues with sponge + stability, we have had to use forge version 2655 for the server to actually boot up as well as work with sponge.

Note: I did post this on FTB's github but they said they don't support sponge at this time.

**Possible Fix**
 - FTB to update Continuum to a version of forge that is stable (better if recommended)
- Forge to tag a version to recommended
- Sponge to upgrade to match recommended version

**Comment by phit** [comment]
https://github.com/SpongePowered/SpongeForge/issues/2137#issuecomment-388399032
