### ISSUE TITLE
EnderIO obelisk XP duplication. (Works only on the server)

### ISSUE THREAD

**Issue by yaroslav4167** [SpongePowered/SpongeForge#2168]
**I am currently running**
- SpongeForge version: 1.12.2-2655-7.1.0-BETA-3105
- Forge version: 1.12.2-14.23.3.2655
- Java version:  1.8.0_151-b12
- Operating System: Linux

- Plugins/Mods:
**Plugins** (17): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, AntiBot for Sponge, AntiXray, BlockyArena, CatClearLag, EconomyLite, GriefPrevention, KeepInventorySponge, LuckPerms, Nucleus, Prism, PrismPlus, ProtectionPerms, ireport

**Mods** (77): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AgriCraft, Applied Energistics 2, BD Lib, Better Builder's Wands, Better Questing, Better Questing Quest Book, Biomes O' Plenty, Chameleon, Charset, ChickenChunks, Chisel, Chisels & Bits, CodeChicken Lib, Compact Machines 3, ContainerFix, CraftTweaker JEI Support, CraftTweaker2, Cyclops Core, Dense Metals, DiscordIntegration, Dynamic Trees, Dynamic Trees BOP, Ecology Mod, Ender IO, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Powertools, EnderCore, EnergeticSheep, FastAsyncWorldEdit, FoamFix, FoamFixCore, Foamflower, Forestry, Immersive Cables, Immersive Engineering, Immersive Petroleum, Immersive Tech, Industrial Foregoing, InfinityLib, Integration Foregoing, Inventory Tweaks, Just Enough Buttons, Just Enough Items, MCMultiPart, MTLib, Mod Tweaker, Moon's Core, NetherPortalFix, Not Enough Scaffold, OreSpawn, Practical Logistics 2, Reborn Core, Sampling Performance Profiler, Shadowfacts' Forgelin, SimpleLogic, SonarCore, Standard Expansion, Steve's Carts 2, Storage Drawers, TESLA, Tech Reborn, Tesla Core Lib, Tesla Core Lib Registries, The One Probe, WorldEdit, Zoo and Wild Animals Mod: Rebuilt

**Issue Description**
Steps to reproduce:
[https://youtu.be/_uZggOybblk](https://youtu.be/_uZggOybblk)
Look at the level

**Comment by phit** [comment]
~~looks like this was already fixed in EnderIO https://github.com/SleepyTrousers/EnderIO/issues/4572~~

i take that back looks like a different issue, I replied to https://github.com/SleepyTrousers/EnderIO/issues/4652

**Comment by tyler489** [comment]
Not a sponge issue
