### ISSUE TITLE
The world is disabled, but loaded.

### ISSUE THREAD

**Issue by SawFowl** [SpongePowered/SpongeForge#2170]
**I am currently running**
Minecraft: 1.12.2
SpongeAPI: 7.1.0-SNAPSHOT-43d8496
SpongeForge: 1.12.2-2655-7.1.0-BETA-3105
Minecraft Forge: 14.23.3.2655
- Java version:  OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.18.04.1-b11)
- Operating System: Ubuntu Server 18.04

Plugins (24): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, BeanCore, CatClearLag, CommandSync, EconomyLite, GriefPrevention, HuskyCrates, HuskyUI, JobsLite, LuckPerms, Nucleus, PayDay, PlaceholderAPI, ProjectCore, SkyClaims, StackBan, UltimateChat, UniversalMarket, VirtualChest, VirtualTool, WorldEdit
Mods (36): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AE2 Stuff, Advanced Solar Panels, Applied Energistics 2, BD Lib, CXLibrary, CoFH Core, CoFH World, CodeChicken Lib, Console Filter, Ex Nihilo Creatio, Extreme Reactors, Fishing Net Mod, Giacomo's Foundry, HoloInventory, IndustrialCraft 2, Just Enough Items, Mantle, More Furnaces, NoDestroy, Parachronology, Quick Leaf Decay, Redstone Flux, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Tinkers' Construct, Tree Chopper, Waterfree Farming, Zero CORE

**Issue Description**
In the Sponge configuration, I turned off the bottom world and end. Periodically, these worlds are turned on by other mods and this creates lags on the server. I do not need these worlds, since I have a SkyBlock server.
In the case of the end, I was able to figure out how to reproduce the situation. In this fashion, there is the item "End Cake". If you eat it, then the player will be teleported to the edge, even if this world was previously turned off.
[latest.log](https://github.com/SpongePowered/SpongeForge/files/2029924/latest.log)

**Comment by ryantheleach** [comment]
If other mods are expecting the dimensions to exist, I don't think Sponge can reasonably disable them completely?

If the act of loading them (and I guess, periodically unloading them) is the issue, leaving them enabled might be better? 

Or is it the 'constant' drain on the server of ticking the other worlds?

If you don't need multi-world support, you could consider disabling the nether in server.properties, (allow-nether=false) but I'm not sure how well mods / sponge take that option into account, so your stability might potentially be affected.

**Comment by SawFowl** [comment]
I have on the server only 2 worlds, both standard, but empty. If I use the allow-nether = false option, I can not create a second empty world, and this parameter does not affect the world of the edge.
It would be acceptable to prohibit the transfer of players to these worlds and then unload them. If I unload the world with Nucleus, then it does not load until the server is restarted.

**Comment by SawFowl** [comment]
If I use allow-nether = false, then I can not create a custom world. Is it possible to make a list of worlds that should be unloaded and disconnected if there are no players in them? Access to the worlds I can limit using the plugin Nucleus.

**Comment by Zidane** [comment]
Fairly sure this is not an issue anymore as of latest stable-7.
