### ISSUE TITLE
Increased Loading Times

### ISSUE THREAD

**Issue by ljc1035** [SpongePowered/SpongeForge#2171]
**I am currently running**
- SpongeForge version:1.12.2-2690-7.1.0-BETA-3112
- Forge version:1.12.2-14.23.3.2690
- Java version:1.8.0.171 (64 Bit)
- Operating System:Windows 8.1 64-Bit

- Plugins/Mods:
- Nucleus-1.3.13-S7.0-MC1.12.2
- EconomyLite-7.1.0-2.14.3

This bug report pertains to the substantial increase in server load time when the Timings module is enabled. While this is enabled, my server (and others, I have heard), take much longer to load than when it is not enabled. Personally, my server won't even fully start when I have this module enabled. Due to this fact, I have disabled the Timings module.

**Comment by phit** [comment]
https://github.com/SpongePowered/SpongeForge/issues/2074#issuecomment-391456755
