### ISSUE TITLE
LLibrary Core crashes

### ISSUE THREAD

**Issue by Rutes** [SpongePowered/SpongeForge#2172]
I am currently running:
- SpongeForge version: spongeforge-1.12.2-2690-7.1.0-BETA-3112
- Forge version: forge-1.12.2-14.23.3.2690-universal
- Java version: 1.8.0_171-b11
- Operating System: Windows 10 x64 Pro 1803

- Plugins/Mods:
animania-1.12.2-1.4.8.jar
architecturecraft-1.12-2.68.jar
astralsorcery-1.12.2-1.8.10.jar
Baubles-1.12-1.5.2.jar
BiblioCraft[v2.4.4][MC1.12.2].jar
BiomesOPlenty-1.12.2-7.0.1.2390-universal.jar
Chameleon-1.12-4.1.3.jar
ClayWorldGen-1.1.0-1.12.0.jar
Controlling-3.0.6.jar
CosmeticArmorReworked-1.12.2-v1.jar
CraftableHorseArmour-1.3.0-1.12.jar
CraftStudio-1.0.0.93-mc1.12-alpha.jar
CustomNPCs_1.12.2(13may18).jar
DirContents.txt
DirList.bat
DungeonTactics-1.12.2-0.14.2.jar
EconomyLite-7.0.0-2.13.0.jar
Electroblob's Wizardry - 4.1.1 - MC 1.12.2.jar
elulib-0.1.12.jar
embers-0.230.jar
fairylights-2.1.2-1.12.x.jar
FastLeafDecay-v14.jar
Guide-API-1.12-2.1.5-60.jar
Hwyla-1.8.24-B39_1.12.jar
iceandfire-1.4.0-1.12.2.jar
ikwid-1.0.2.jar
ironchest-1.12.2-7.0.40.824.jar
JustAFewFish-1.7_for_1.12.jar
LangSwitch.jar
latch-0.4.8.jar
LessForgivingVoid-1.0.1.jar
llibrary-1.7.11-1.12.2.jar
LuckPerms-Sponge-4.1.7.jar
Maille1.12.2-2.0.jar
Mantle-1.12-1.3.2.24.jar
memory_repo
MMCRestrict-1.4.2-API-7.jar
mods.txt
Morpheus-1.12-3.3.2.jar
NetherEx-1.12-2.1.14.15.jar
Nucleus-1.3.10-S7.0-MC1.12.2-plugin.jar
RoguelikeDungeons-1.12.2-1.8.0.jar
roots-2-0.104.jar
rustic-1.0.3.jar
SpartanShields-1.12.2-1.4.1.jar
spongeforge-1.12.2-2690-7.1.0-BETA-3112.jar
StorageDrawers-1.12.2-5.3.6.jar
TConstruct-1.12.2-2.10.0.81.jar
tombstone-2.9.4-1.12.jar
toroquest-1.12.2-5.2.jar
Totemic-1.12.2-0.10.3.jar
Vampirism-1.12.2-1.4.2.jar
VampirismIntegrations-1.12.2-1.0.0.jar
VillagerShops.jar
Waystones_1.12.2-4.0.43.jar
WearableBackpacks-1.12.2-3.1.2.jar

Server crashes on startup when Sponge is included in the mod list. Starts up OK without Sponge.

https://gist.github.com/Rutes/82f88a373780def312da8bad7d8a6e07

**Comment by Aaron1011** [comment]
@Rutes Can you upload your full server log?

**Comment by Rutes** [comment]
Is it not all there in my gist link?
https://gist.github.com/Rutes/82f88a373780def312da8bad7d8a6e07

I cleared the logs folder before re-running to get clean version of crash log, debug, and latest. 
Here are some bookmark links if it's a lot to navigate/scroll:
https://gist.github.com/Rutes/82f88a373780def312da8bad7d8a6e07#file-crash-2018-05-24_15-08-28-server-txt
https://gist.github.com/Rutes/82f88a373780def312da8bad7d8a6e07#file-debug-log
https://gist.github.com/Rutes/82f88a373780def312da8bad7d8a6e07#file-latest-log

Was there another log I'm missing?

**Comment by Rutes** [comment]
This seems to be the start of the error:
[15:08:28] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
java.lang.AbstractMethodError: Method net/minecraft/server/dedicated/DedicatedServer.isMainThread()Z is abstract

**Comment by phit** [comment]
looks like LLibrary Core or Astral Transformer is to blame

**Comment by Aaron1011** [comment]
I'm looking into this.

**Comment by Aaron1011** [comment]
The problem appears to lie with [LLibraryCore's implementation of getCommonSuperClass](https://github.com/gegy1000/LLibraryCore/blob/06344248a3ba2964cb4c9cc5cd3efff11866bf0e/src/main/java/net/ilexiconn/llibrary/server/asm/PatchClassWriter.java#L21-L44), which can trigger re-entrant classloading.

Given that this mod works without Sponge, a simple fix would probably be to annotate the transformer with `@Resource`, to prevent Mixin from running it during Mixin preparation.

However, a better long-term solution would probably be to change LLibraryCore to avoid causing re-entrant classloading. This would require chaing the `getCommonSuperClass` implementation to avoid classloading when walking the hierarchy (using `LaunchClassLoader#getClassBytes`)

**Comment by Rutes** [comment]
aha! interesting... apparently I recently updated LLibrary, but I might not have needed to. The one mod that requires it is Ice&Fire. I'll rollback to an earlier version of LLibrary and see if it launches

**Comment by DarethZ33** [comment]
@Rutes Did that fix this for you? I'm also having this issue.

**Comment by Rutes** [comment]
Yep, reverting back to llibrary-1.7.9-1.12.2 fixed it for me. I guess I'll need to report the issue on LLibrary's github?

**Comment by phit** [comment]
was fixed by the mod https://github.com/iLexiconn/LLibrary/issues/73
https://github.com/gegy1000/LLibraryCore/commit/b0b506385d626d1e4e6a0cbd955134cd56d867bf
