### ISSUE TITLE
server fail to close properly LoaderExceptionModCrash

### ISSUE THREAD

**Issue by FiveEYZ** [SpongePowered/SpongeForge#2173]
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2690-7.1.0-BETA-3115
- Forge version: forge-1.12.2-14.23.3.2690-universal
- Java version: 1.8.0_171
- Operating System: Windows 10 Pro 1803

- Plugins/Mods:
Plugins (4): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge
mods: GalacticraftCore-1.12.2-4.0.1.176, MicdoodleCore-1.12.2-4.0.1.176

**Issue Description**
when i try to stop the server this exception occur https://gist.github.com/FiveEYZ/e21844080692d0924bf966387d5b0831
and prevents the server from fully stopping, this "uncaughtException" does not happen when SpongeForge is removed.

debug.log: https://gist.github.com/FiveEYZ/7150c60450d0ea9af5771c8ee5f56ca0
latest.log: https://gist.github.com/FiveEYZ/09afa03b2128e0938d383c16db4a0e40

**Comment by bloodmc** [comment]
@FiveEYZ @Whazaaaaa Please provide a world save with minimum mods to reproduce the issue.

**Comment by FiveEYZ** [comment]
dont need a world save
the mods i listed in first post was the minimum needed

just start the server with those mods and then do /stop should yield same result

but i think this can easily be fixed on galacticrafts side, by doing something similar to what phit did here
https://github.com/zmaster587/AdvancedRocketry/commit/5f174ff6d1608320ec61c32e3311bb59b5d7cbba

so it could look something like this:
https://github.com/FiveEYZ/Galacticraft/commit/25e2b16865f0f2ea05365124539adb43c5aa2a25

its untested but should do the trick

**Comment by Whazaaaaa** [comment]
@bloodmc  The errors and logs are always the same, but here is the world download as requested
[World download that has this crash/timeout on shutdown](https://www.dropbox.com/s/rtkre5x20xvfhz5/AdvRocketry%20Forge%202703%20shutdown%20fail.rar?dl=0)

I think the same thing happens for galacticraft( my error was with advanced rocketry)
Phits fix did indeed fix this like FiveEYZ said(edited the file and tested it, it worked) but seeing as it also happens on galacticraft and probably others, a SpongeForge sided fix would be nice to have.

The [811413e](https://github.com/LXGaming/Sledgehammer/commit/811413e4722c3f50e7e2fe4685e85c43495c5097) from LXGaming for his SledgeHammer fix mod seems to fix this aswell for galacticraft.
So @FiveEYZ download that put it in your mods folder and enable the config if you want a temp fix.

**Comment by FiveEYZ** [comment]
sure we can add if statement or try/catch to go around the issue, but i guess the question is why the DIMs are not registered in the first place.

**Comment by gabizou** [comment]
@FiveEYZ try with the newest SpongeForge with that commit from blood.

**Comment by FiveEYZ** [comment]
tried the latest build and no more exceptions when closing the server
galacticraft also seem to be able to unregister its own dimension just fine now.

```
 [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Done (4,115s)! For help, type "help" or "?"
 [Server thread/INFO] [Galacticraft]: Registered Dimension: -28
 [Thread-6/INFO] [Galacticraft]: Galacticraft remote version found: 4.0.1
 [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Stopping the server§r
 [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
 [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving players
 [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving worlds
 [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'world'/overworld
 [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'DIM-1'/the_nether
 [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'DIM1'/the_end
 [Server thread/INFO] [Sponge]: Unloading world [world] (DIM0)
 [Server thread/INFO] [Sponge]: Unloading world [DIM-1] (DIM-1)
 [Server thread/INFO] [Sponge]: Unloading world [DIM1] (DIM1)
 [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -28
 [Server Shutdown Thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
 [Server Shutdown Thread/INFO] [net.minecraft.server.MinecraftServer]: Saving players
 [Server Shutdown Thread/INFO] [net.minecraft.server.MinecraftServer]: Saving worlds

```

thx for the fix
