### ISSUE TITLE
Server timing out on shutdown (Advancedrocketry world unload)

### ISSUE THREAD

**Issue by Whazaaaaa** [SpongePowered/SpongeForge#2174]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2690-7.1.0-BETA-3115
- Forge version: forge-1.12.2-14.23.3.2702-universal
- Java version: 8
- Operating System: Both WIndows and Linux

- Plugins (4): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge
- Mods (9): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Advanced Rocketry, Advanced Rocketry Core, Vulpes library
* AdvancedRocketry-1.12.2-1.4.0-80
* LibVulpes-1.12.2-0.2.8-31-universal

**Issue Description**
When I /stop my server the process doesnt actually stop until I forcefully stop the server. It seems to timeout because of an exception. I tested this without sponge and it didnt happen. From the difference in the logs it seems the unloading of an advancedrocketryworld is the cause.

These are both logs with and without sponge.
[sponge.log](https://github.com/SpongePowered/SpongeForge/files/2040382/sponge.log)
[nosponge.log](https://github.com/SpongePowered/SpongeForge/files/2040383/nosponge.log)

**Comment by Whazaaaaa** [comment]
Just saw this was a duplicate of #2173, Sorry :( but perhaps the logs help.

**Comment by bloodmc** [comment]
dupe #2173
