### ISSUE TITLE
Client update forge2703 Unable to enter the server

### ISSUE THREAD

**Issue by Anguriaboy** [SpongePowered/SpongeForge#2176]
- SpongeForge version:  spongeforge-1.12.2-2703-7.1.0-BETA-3116
- Forge version: Forge-14.23.4.2703
- Java version: 8
- Operating System: Windows

Issue Description
 Client update Forge-14.23.4.2703 Unable to enter the server。
After the update spongeforge2703 the player digs out the dropped items will disappear。
![qq 20180526204847](https://user-images.githubusercontent.com/39192846/40576297-373138e8-6126-11e8-8122-aac029793477.jpg)

**Comment by Lemmmy** [comment]
We are also experiencing this issue in our server. It appears to be related to https://github.com/SpongePowered/SpongeCommon/issues/1823.

**Comment by Lemmmy** [comment]
We are also having this issue on our server. It appears to be related to https://github.com/MinecraftForge/MinecraftForge/pull/4942.

**Comment by gabizou** [comment]
looks Like a forge client bug. We don’t need to update recommended but I’m sure Forge will have a new recommended build soon.
