### ISSUE TITLE
Issue with umbralux and sponge

### ISSUE THREAD

**Issue by Tototi1** [SpongePowered/SpongeForge#2177]
**I am currently running**

- SpongeForge version: 1.12.2-2611-7.1.0-BETA-3002
- Forge version: 14.23.2.2611
- Java version: 
- Operating System: linux

- Plugins/Mods: ctgui@1.0.0,extendedrenderer@v1.0,creativecoredummy@1.0.0,configmod@v1.0,jei@4.8.5.147,attributefix@1.0.1,mtrm@1.2.2.30,custommainmenu@2.0.8,contenttweaker@1.12.2-4.5.0,redstonepaste@1.7.5,subcommonlib@1.2.0.1,waystones@4.0.42,mcp@9.42,ctm@MC1.12-0.2.3.12,zombieawareness@1.12.1-1.11.12,classiccombat@1.0.0,justthetips@1.12-1.0.1.1,props@2.6.0,crafttweaker@4.1.8,forge@14.23.2.2611,variedcommodities@1.12.2,weaponlevels@2.1.2,minecraft@1.12.2,stackie@1.6.0.48,ptrmodellib@1.0.2,crafttweakerjei@2.0.2,bma_addon@1.11.2 4.0.3.0,silentlib@2.2.18,creativecore@1.9.9,corpsecomplex@1.0.2.2,resourceloader@1.5.3,rpginventory@1.12.2,sophisticatedwolves@3.13.2,trapcraft@v2.4.3a,quark@r1.4-123,xaerominimap@1.14,mapgadgets@@VERSION@,waitingtime@1.0.0,lunatriuscore@1.2.0.42,autoreglib@1.3-16,reskillable@1.12.2-GRADLE:BUILD,mercurius_updater@1.0,FML@8.0.99.99,schematica@1.8.0.169,customnpcs@1.12,worldeditcuife2@2.1.2-mf-1.12-14.21.1.2387,coroutil@1.12.1-1.2.6,umbralux@1.12.2,chisel@MC1.12.2-0.2.0.31,tsquare@1.0.7,nbtedit@1.11.2-2.0.2,trade@1.0.4,scalinghealth@1.3.14,extraalchemy@0.3.8.4-release,beastmaster@$version,playerrevive@1.0,base@3.7.1,defaultoptions@9.2.5,blockyarena, chestrefill, minereset, modcontrol, morpheus, nucleus, worldedit

**Issue Description**
 When i use "gladius lux" item of mod umbralux (class-armor). Work but i have error in console log

https://gist.github.com/Tototi1/3d5dae6721160adf7f44c1555605aefb

**Comment by gabizou** [comment]
Could you test with the latest SpongeForge? It would require upgrading the Forge dependency, and I'm not sure whether your mods are dependent on the forge version specifically.

**Comment by Tototi1** [comment]
the latest version of sponge not work for me, even with the latest version of forge

**Comment by Aaron1011** [comment]
This is a bug with UmbraLux - it's not properly registering its blocks with Forge.

I've opened a PR to fix the issue: https://github.com/ArtixAllMighty/Rpg-Addon-UmbraLux/pull/4
