### ISSUE TITLE
Thermal Dynamics, the chunks are not unloaded after they are left by the player.

### ISSUE THREAD

**Issue by SawFowl** [SpongePowered/SpongeForge#2179]
**I am currently running**
- Minecraft: 1.12.2
- SpongeAPI: 7.1.0-SNAPSHOT-43d8496
- SpongeForge: 1.12.2-2703-7.1.0-BETA-3119
- Minecraft Forge: 14.23.4.2703
- Java version:  openjdk version "1.8.0_171"
- Operating System: Ubuntu Server 18.04

- Plugins (24): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, BeanCore, CatClearLag, CommandSync, EconomyLite, GriefPrevention, HuskyCrates, HuskyUI, JobsLite, LuckPerms, Nucleus, PayDay, PlaceholderAPI, ProjectCore, SkyClaims, StackBan, UltimateChat, UniversalMarket, VirtualChest, VirtualTool, WorldEdit
- Mods (37): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AE2 Stuff, Advanced Solar Panels, Applied Energistics 2, BD Lib, CXLibrary, CoFH Core, CoFH World, CodeChicken Lib, Console Filter, Ex Nihilo Creatio, Extreme Reactors, Fishing Net Mod, Giacomo's Foundry, HoloInventory, IndustrialCraft 2, Just Enough Items, Mantle, More Furnaces, NoDestroy, Parachronology, Quick Leaf Decay, Redstone Flux, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Tinkers' Construct, Tree Chopper, VanillaFix, Waterfree Farming, Zero CORE

Thermal Dynamics v2.4.1
Do not unload chunks in which there are Tile Entities.
Chunks are not unloaded even after the player leaves the server.
This creates performance problems.

[latest.log](https://github.com/SpongePowered/SpongeForge/files/2045969/latest.log)

**Comment by XakepSDK** [comment]
Report it to thermal dynamics tracker.

**Comment by SawFowl** [comment]
@XakepSDK
https://github.com/CoFH/Feedback/issues/1112#issuecomment-392589484

**Comment by bloodmc** [comment]
Turn on chunk load/unload logging in Sponge's config and show us a log.

**Comment by SawFowl** [comment]
@bloodmc 
[latest.log](https://github.com/SpongePowered/SpongeForge/files/2046071/latest.log)
[debug.log](https://github.com/SpongePowered/SpongeForge/files/2046072/debug.log)
[global.conf.txt](https://github.com/SpongePowered/SpongeForge/files/2046078/global.conf.txt)

**Comment by bloodmc** [comment]
@Mr-Krab Include all fml-* logs.

**Comment by SawFowl** [comment]
@bloodmc 
Here is the entire folder with the logs of my test server.
[logs.zip](https://github.com/SpongePowered/SpongeForge/files/2046156/logs.zip)

**Comment by JoeSGT** [comment]
Bloodmc in the recent forge they took out fml-* logs and replace them with `latest.log` and `debug.log`

**Comment by bloodmc** [comment]
@Mr-Krab Try disabling sponge's chunk gc and see if that solves the issue.

**Comment by SawFowl** [comment]
@bloodmc  With these parameters, the server is not started.

![default](https://user-images.githubusercontent.com/29023558/40873264-da681402-6665-11e8-9be4-360bef183ea5.png)

**Comment by bloodmc** [comment]
@Mr-Krab try latest SF.

**Comment by SawFowl** [comment]
@bloodmc Chunks are still not unloaded. Although the server now starts normally without crashing in both configuration options.
![default](https://user-images.githubusercontent.com/29023558/41079282-de909b22-6a29-11e8-9edc-dd775f86637d.png)
![default](https://user-images.githubusercontent.com/29023558/41079292-ea69228e-6a29-11e8-9e1e-0022a42cf334.png)

**Comment by SawFowl** [comment]
The load on the server seems to be less, TPS became better. I'll watch more.

**Comment by bloodmc** [comment]
Test on a clean install with latest SF/TE and see if the problem exists. There should be no chunk unloading issues with latest builds.

**Comment by SawFowl** [comment]
For new worlds, the problem is solved. But what about the worlds that already exist? Is there any way to forcefully unload chunks?
I do not want to delete the world, as this action will not please the players.

**Comment by bloodmc** [comment]
Fixed in https://github.com/SpongePowered/SpongeCommon/commit/0954d501d990f455af05ca2d17d4ec2ac6a123d7

**Comment by SawFowl** [comment]
The problem is again relevant.

-   SpongeAPI: 7.1.0-SNAPSHOT-9c79de1
-   SpongeForge: 1.12.2-2705-7.1.0-BETA-3421
-  Minecraft Forge: 14.23.4.2747

- Mods (52): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Better Questing, BiblioCraft, CoFH Core, CoFH World, CodeChicken Lib, Console Filter, Construct's Armory, CraftTweaker JEI Support, CraftTweaker2, CreativeCore, CreativeCoreDummy, CustomNPCs, Ex Nihilo Creatio, Fishing Net Mod, Hammer Core, HoloInventory, Immersive Engineering, Immersive Tech, InstantUnify, Iron Chest, ItemPhysic, Just Enough Items, LagGoggles, Mantle, McJtyLib, Mekanism, MrCrayfish's Furniture Mod, Parachronology, QuestUtils, Quick Leaf Decay, Reborn Core, RebornStorage, Redstone Arsenal, Redstone Flux, Refined Storage, Solar Flux Reborn, Standard Expansion, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Tinkers' Construct, Tree Chopper, UniDict, VanillaFix, WanionLib

- Plugins (25): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge,  FastAsyncWorldEdit, BeanCore, CatClearLag, CommandSync, EconomyLite, GriefPrevention, HuskyCrates, HuskyUI, LuckPerms, Nucleus, PayDay, PlaceholderAPI, ProjectCore, SkyClaims, StackBan, UltimateChat, UniversalMarket, VirtualChest, VirtualTool, WorldEdit, spark

The logs are clean. I suspect that the conflict is with the same mod.
