### ISSUE TITLE
Sponge seemingly eating errors

### ISSUE THREAD

**Issue by DatenThielt** [SpongePowered/SpongeForge#2180]
Initially reported to EnderIO but not just an ender IO issue,  Sponge appears to be eating errors, making it near impossible to find out what the actual issue is,  Conciquence is that the console is being spammed with Sponge messages

`/* The PhaseState having an exception: TileEntityTickPhase */
/* The PhaseContext: */
/* - Owner: EntityPlayerMP['DatenThielt'/1193537, l='world', x=490.96, y=66.00, z=7210.53] */
/* - Source: TileFarmStation{tileType=SpongeTileEntityType{id=enderio:enderio:tile_farm_station, name=enderio:tile_farm_station, TileEntityClass=class crazypants.enderio.machines.machine.farm.TileFarmStation}, world=WorldServer{Name=world, DimensionId=0, DimensionType=minecraft:overworld, DimensionTypeId=0}, pos=BlockPos{x=484, y=66, z=7221}, blockMetadata=-1} */
/* - CapturedBlockPosition: org.spongepowered.common.event.tracking.context.CaptureBlockPos@1f */
/* org.spongepowered.asm.util.PrettyPrinter@3ffd7383 */
/*******************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************/
/* StackTrace: */
/* java.lang.ClassCastException: null */
/* Phases Remaining: */
/* */
/* Minecraft : 1.12.2 */
/* SpongeAPI : 7.1.0-SNAPSHOT-43d8496 */
/* SpongeForge : 1.12.2-2705-7.1.0-BETA-3126 */
/* Minecraft Forge : 14.23.4.2705 */`

It is not just related to EnderIO, See Screenshot ,  Both mod authors suggested it be reported here
![screenshot_66](https://user-images.githubusercontent.com/4466326/40678780-b9c3bca6-6381-11e8-819d-daad444e935f.png)

**Comment by phit** [comment]
get us a proper full log, this means nothing without context
but due to the classcasting errors it seems most likely that you have some form of world corruption

please upload your full `logs/debug.log` and `config/sponge/global.conf` to https://gist.github.com/
then link them here

**Comment by DatenThielt** [comment]
https://gist.github.com/DatenThielt/c016bf374d560b6b6a782b11e0323677 global.conf
https://gist.github.com/DatenThielt/83477324911e4e92fe9229ebdd1d5ccc latest.log

The debug.log is to big for Gist,  (Or I am getting a 405, Not Allowed) so I have uploaded it to my Mega
https://mega.nz/#!qPoQhIpA!-8vwugORFEgyqkNUDpdkZ8cZKKv9Lap_T3jsvcGQgQg

**Comment by phit** [comment]
https://gist.github.com/DatenThielt/c016bf374d560b6b6a782b11e0323677#file-global-conf-L1378
`deny-chunk-requests=true`

dont even have to look at the rest, set that config to false and roll the world back to a working backup

https://github.com/SpongePowered/SpongeForge/issues/2003
https://github.com/SpongePowered/SpongeForge/issues/2128
https://github.com/SpongePowered/SpongeForge/issues/2135

**Comment by DatenThielt** [comment]
So we disabled it,  The world itself is fine and has never corrupted,  This is a bit more informative by the looks of it 

![screenshot_67](https://user-images.githubusercontent.com/4466326/40684255-350f9ace-6391-11e8-93ff-4a6008eda1e9.png)

**Comment by phit** [comment]
I opened a new issue for that here https://github.com/SpongePowered/SpongeForge/issues/2181
this issue has too many unrelated logs, that will just mislead devs trying to fix it
