### ISSUE TITLE
EnderIO farming station incompatibility 

### ISSUE THREAD

**Issue by phit** [SpongePowered/SpongeForge#2181]
**I am currently running**
- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3126
- Forge version: 14.23.4.2705 

- Plugins/Mods:
EnderCore-1.12.2-0.5.22.jar
EnderIO-1.12.2-5.0.22.jar

**Issue Description**
https://gist.github.com/phit/83a9b4f1eab359ad5f1fa076f71584f4

**Comment by tyler489** [comment]
https://github.com/SleepyTrousers/EnderIO/issues/4704
