### ISSUE TITLE
Unable to move or do anything when entering a portal

### ISSUE THREAD

**Issue by FC-Creations** [SpongePowered/SpongeForge#2185]
**I am currently running**

- SpongeForge version: 3135
- Forge version: 2669
- Java version: 8
- Operating System: ubuntu

- Plugins/Mods: https://minecraft.curseforge.com/projects/natures-beauty/relations/dependencies
(I don't have sponge installed anymore due to the issues, so I couldn't run that command, figured it would be easier to drop the link to the mod pack, I have no other mods installed beyond what is in the pack itself)

**Issue Description**

Not all players but some cannot go through a nether portal but instead get stuck.  The player freezes in place, and cannot move. The server itself does not log them attempting to switch dimensions, and unless the portal is broken by another player, the stuck player cannot free themselves.

There are no error logs, as the server simply doesn't seem to be registering that they're even attempting to switch dimensions. 

The only possible difference we can figure between those who have no trouble and those who do, is that those who do, have journey map installed.  I figure, it's modded... almost anything can cause the issue, so I thought maybe that'd be useful information.

And the issue does not happen when sponge is not existent, hence why I'm posting here.

**Comment by phit** [comment]
can't really test with such a big pack, please figure out what mods are needed to reproduce this

**Comment by ryantheleach** [comment]
@paulccorey Was this reproducible with only that pack, and Sponge, without any plugins?

**Comment by phit** [comment]
No reply in over two weeks, closing this for now. If this is still an issue, then please reply with the information you have been asked for and I will reopen this issue.
