### ISSUE TITLE
spongeforge Report errors

### ISSUE THREAD

**Issue by Anguriaboy** [SpongePowered/SpongeForge#2186]
**I am currently running**
- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3136
- Forge version: forge-1.12.2-14.23.4.2705-universal
- Java version: 8
- Operating System:win

**Issue Description**
I don't know why the backstage has been Report errors。
![qt z4y9m0z4 do5 8 xdp9a](https://user-images.githubusercontent.com/39192846/40774529-6815a02c-64f8-11e8-9c32-3d3ac8d3e10b.png)
![35 h bwsp83nwc6d 25715](https://user-images.githubusercontent.com/39192846/40774532-6af1a9bc-64f8-11e8-9878-7a2fa29f9951.png)
![xel nj81ue 7_aazn67jc4](https://user-images.githubusercontent.com/39192846/40774538-6cf7e12c-64f8-11e8-807a-f78e7aeefc47.png)
![2k cqz4 _ rv hoj8 8dh](https://user-images.githubusercontent.com/39192846/40774542-6f3f396c-64f8-11e8-9fd6-8a53f023ec42.png)

**Comment by XakepSDK** [comment]
![a](https://user-images.githubusercontent.com/4938483/40774923-a6cfb79a-64e8-11e8-8346-98794a23fbd7.jpg)

**Comment by Aaron1011** [comment]
@Anguriaboy Can you please upload your log to Pastebin?

**Comment by Anguriaboy** [comment]
This problem does not happen sometimes. Sometimes it appears, but it doesn't matter much.

**Comment by Aaron1011** [comment]
@Anguriaboy: If you want us to be able to help you, please upload the actual text of the logs to a site like Pastebin. Screenshots of the logs aren't very useful.

**Comment by Anguriaboy** [comment]
No problem for the time being, thank you. If there is a problem, I will keep in touch with you
