### ISSUE TITLE
General Performance

### ISSUE THREAD

**Issue by Sir-Will** [SpongePowered/SpongeForge#2187]
I did run a profiling with 29 players online and found few sponge methods which decrease the performance slightly. I thought to share them so a few of those methods can maybe be improved.

spongeforge-1.12.2-2705-7.1.0-BETA-3126
forge-1.12.2-14.23.4.2705-universal

![](https://i.imgur.com/hFHnWW6.jpg)
![](https://i.imgur.com/y9Bi2jD.jpg)
![](https://i.imgur.com/gSdhZZD.jpg)
![](https://i.imgur.com/WwqoY4L.jpg)
![](https://i.imgur.com/NglO0Wn.jpg)

**Comment by gabizou** [comment]
Reviewing all these profiling, none of them can be altered for the sake of performance as they are already optimized as best as possible and a majority of the hot code is not specifically sponge's code (guava caching is already the fastest caching, Mojang's auth lib is already it's own set of code, and HashMap is already the fastest map implementation in Java, and in the first image, you have a permission lookup done by luck perms through GriefPrevention, not sponge code at that point). Nothing here really jumps out as expected if it were underperforming, but I don't believe it is.
