### ISSUE TITLE
HarvestDropsEvent Exception 

### ISSUE THREAD

**Issue by EverNife** [SpongePowered/SpongeForge#2188]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3126.jar
- Forge version: 2705
- Java version: 8
- Operating System: Linux  - version: 4.9.87-xxxx-std-ipv6-64

Plugins (25): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge,  FastAsyncWorldEdit, BetterKits, CatClearLag, EverNifeCoreSpongy, FlexibleLogin, GriefPrevention, Holograms, HuskyCrates, HuskyUI, LuckPerms, MMCReboot, MMCRestrict, MagiBridge, NuVotifier, Nucleus, PixelVip, PlaceholderAPI, SeriousVote, Total Economy, UltimateChat, WorldEdit

Mods (75): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Actually Additions, Advanced Generators, Advanced Solar Panels, AngelRing 2 Bauble, Applied Energistics 2, AutoRegLib, Avaritia, BD Lib, Backpack, Basic Nether Ores, Baubles, Blood Magic: Alchemical Wizardry, Botania, Brandon's Core, CXLibrary, Chest Transporter, Chisel, CoFH Core, CoFH World, CodeChicken Lib, CraftTweaker JEI Support, CraftTweaker2, Cucumber Library, CustomNPCs, Draconic Evolution, Elevator Mod, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, Extra Utilities 2, Fast Leaf Decay, Flux Networks, FoamFix, Guide-API, Hats, IndustrialCraft 2, Iron Chest, Just Enough Items, LunatriusCore, Mantle, More Furnaces, Morpheus, Mystical Agradditions, Mystical Agriculture, Redstone Flux, SonarCore, Stackie, Thaumcraft, ThaumicJEI, Thermal Dynamics, Thermal Expansion, Thermal Foundation, TickProfiler, Tinkers Tool Leveling, Tinkers' Construct, UniDict, Waila, WanionLib, iChunUtil, mob_grinding_utils

**Issue Description**

Getting this error on server console https://gist.github.com/evernife/082f6b2f16e51e265c504860503acc11

Related to https://github.com/SleepyTrousers/EnderIO/issues/4673#issuecomment-393715077

**Comment by phit** [comment]
was already fixed https://github.com/SpongePowered/SpongeForge/issues/2181, update to latest
