### ISSUE TITLE
NPE in SpongeManipulatorRegistry.bake 

### ISSUE THREAD

**Issue by Inscrutable** [SpongePowered/SpongeForge#2189]
**I am currently running**
- spongeforge-1.12.2-2705-7.1.0-BETA-3126, also tried 3136
- forge-1.12.2-14.23.4.2705, also tried 2707
- Java version: 1.8.0_171, Oracle Corporation
- Operating System: Windows 10 (amd64) version 10.0
- 4GB RAM to client. Normally more than enough.

- Plugins/Mods: BiomesOPlenty-1.12.2-7.0.1.2391-universal.jar, CraftStudio-1.0.0.93-mc1.12-alpha.jar, Quark-r1.4-123.jar, animania-1.12.2-1.4.8.jar, architecturecraft-1.12-2.68.jar, AutoRegLib-1.3-17.jar, backpacks+1.12.2+-+3.5.0.jar, Chameleon-1.12-4.1.3.jar, CTM-MC1.12-0.2.3.12.jar, Chisel-MC1.12.2-0.2.0.31.jar, chiselsandbits-14.17.jar, CodeChickenLib-1.12.2-3.1.8.341-universal.jar, CookingForBlockheads_1.12.2-6.4.36.jar, CustomMobSpawner-3.11.4.jar, DrZharks MoCreatures Mod-12.0.4.jar, EnderStorage-1.12.2-2.4.3.130-universal.jar, GeographiCraft-1.12-0.8.9b.jar, ironchest-1.12.2-7.0.42.827.jar, jei_1.12.2-4.9.2.196.jar, KleeSlabs_1.12.2-5.4.10.jar, malisiscore-1.12.2-6.4.0.jar, malisisblocks-1.12.2-6.1.0.jar, malisisdoors-1.12.2-7.3.0.jar, Mantle-1.12-1.3.2.24.jar, natura-1.12.2-4.3.2.49.jar, NaturesCompass-1.12.2-1.5.1.jar, Pam's+HarvestCraft+1.12.2u.jar, realworld-1.16.jar, SGCraft-1.14.3-mc1.12.2-sponge.jar, StorageDrawers-1.12.2-5.3.6.jar, TConstruct-1.12.2-2.10.1.84.jar , theoneprobe-1.12-1.4.22.jar, TinkerToolLeveling-1.12-1.0.4.jar, twilightforest-1.12.2-3.7.424-universal.jar, worldedit-sponge-6.1.9-SNAPSHOT-dist.jar

**Issue Description**
The pack launches happily in single player without SpongeForge (although not without some ugly errors in the log). It crashes when I add SpongeForge. I have not yet tried testing a stand-alone server. I can't even get SF to work with the new TombManyGraves2-API on it's own.

Client log here: https://www.dropbox.com/s/h7jqhaddgpi3mxl/UglyCrashLog.log

**Comment by Aaron1011** [comment]
@Inscrutable I can't seem to reproduce this. Can you trying removing your `config` folder, and starting the pack again?

**Comment by Inscrutable** [comment]
OK, I can report that starting an entirely new, clean MC instance _and_ letting fresh configs generate seems to have fixed the problem. I still have no idea what the real perpetrator was, as it *worked without SpongeForge*. A test server with the same mods ran without issues.

**Comment by phit** [comment]
gonna assume this was a mod issue, if it pops up again we can reopen
