### ISSUE TITLE
Startup crash with FTBUtilities

### ISSUE THREAD

**Issue by wormzjl** [SpongePowered/SpongeForge#2190]
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3136
- Forge version: forge-1.12.2-14.23.4.2707-universal
- Java version: 1.8.0 171
- Operating System: win 7

- Plugins/Mods:
FTBLib-5.1.0.20
FTBUtilities-5.1.0.25

**Issue Description**
Crash on launch

Crash log: https://gist.github.com/wormzjl/a15796945ea3bd2d7ea23fe15891bd55
Server log: https://gist.github.com/wormzjl/c578814bbf4b0f4cdd685f7bc1bcbae9

**Comment by LatvianModder** [comment]
I will fix this in FTBUtilities, but basically, there is no limits to what the max op level can be in vanilla. I suggest defaulting to op_4 when any larger number is given or handle it somehow seperately. It works just fine if I use `getRequiredPermissionLevel() 6` and set `op-permission-level=6` in `server.properties`

**Comment by LatvianModder** [comment]
Next update will fix the issue from FTBU side but you still should consider using something like
`int level = Math.min(4, command.getRequiredPermissionLevel());`

**Comment by wormzjl** [comment]
Thanks for the quick fix!

**Comment by gabizou** [comment]
Thanks @LatvianModder for the speedy fix!
