### ISSUE TITLE
Multi-Hotbar incompatibility 

### ISSUE THREAD

**Issue by Th4nat0s1s** [SpongePowered/SpongeForge#2192]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2655-7.1.0-BETA-3105
- Forge version: forge-1.12.2-14.23.3.2655-universal
- Java version: 8
- Operating System: Win 8.1

- Plugins/Mods:
      [1.12.x]+SecurityCraft+v1.8.4.1
      appliedenergistics2-rv5-stable-11
      Aquaculture-1.12.2-1.6.2
      Aquatic-1.12.2-1.0.0-c
      Baubles-1.12-1.5.2
      BiomesOPlenty-1.12.2-7.0.1.2387-universal
      BloodMagic-1.12.2-2.2.12-97
      buildcraft-7.99.15
      Bullseye-1.12-3.0.3
      Chameleon-1.12-4.1.3
      CodeChickenLib-1.12.2-3.1.8.341-universal
      creeperheal-1.12-1.3.1
      Custom-Mob-Spawner-Mod-1.12.2
      DoggyTalents-1.12-1.14.2.314-universal
      Enchiridion-1.12.2-3.3.3
      EnderCore-1.12.2-0.5.22
      EnderStorage-1.12.2-2.4.2.126-universal
      ExtendedDays-1.12-0.2.3-17
      extrautils2-1.12-1.7.6
      forestry_1.12.2-5.8.0.290
      Grappling-Hook-Mod-1.12.2
      gravestone-1.10.1
      Guide-API-1.12-2.1.5-60
      Hwyla-1.8.25-B40_1.12
      industrialcraft-2-2.8.75-ex112
      Infinite-Fluids-1.12
      jei_1.12.2-4.9.1.179
      journeymap-1.12.2-5.5.2
      Mantle-1.12-1.3.1.21
      Mo-Creatures-Mod-1.12.2
      multihotbar-1.12.2-4.0.1-build-T116
      multihotbarcore-1.12.2-1.0.1-build-T22
      ShadowMC-1.12-3.8.0
      SilentLib-1.12-2.2.18-100
      StorageDrawers-1.12.2-5.3.6
      TConstruct-1.12.2-2.10.0.81
      Tesla-1.12.2-1.0.63
      Thaumcraft-1.12.2-6.1.BETA13
      TrashSlot_1.12.1-8.4.6
      Treecapitator-1.12-at_0.9a
      twilightforest-1.12.2-3.6.345-universal
      Wawla-1.12.2-2.5.253
      Waystones_1.12.2-4.0.43

**Issue Description**

Player connection forcibly closed only after adding SpongeForge w/ Lockette and Nucleus plugins, removal of SpongeForge and plugins allows those players to reconnect.

Was able to reconnect after deletion of player data on the server... reason unkown...

http://paste.yu8.me/?533a5994f289a00a#RTOLLTzbe0U27GRUsPbnGK3CGg1FG9IbYvXSC3aY8AY=

**Comment by phit** [comment]
would be nice to get the broken playerdata to see if its reproducable, otherwise really not much to do here with so little info :/

**Comment by Th4nat0s1s** [comment]
I mean...I may be able to recover it but is there really not much to the crash report??

**Comment by phit** [comment]
nothing apparent to me @Faithcaio may have an idea
https://gist.github.com/phit/c06acd5a48520660247ccda896d41ec3

**Comment by Th4nat0s1s** [comment]
Hey sorry it has taken me so long to get back to this, my internet has been ridiculous recently but here is my old player .dat file that I deleted.

https://mega.nz/#!nTAkBS4I!fz3eq5esMvNcTzgcks95IUVVoQCdj14rFp5GApPiQd0

**Comment by Neonit** [comment]
Could be connected: https://github.com/rolandoislas/multi-hotbar/issues/56
