### ISSUE TITLE
java.lang.NullPointerException: Exception ticking world at net.minecraft.block.Block.getId(Block.java:2830)

### ISSUE THREAD

**Issue by wormzjl** [SpongePowered/SpongeForge#2194]
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3136
- Forge version: forge-1.12.2-14.23.4.2707-universal
- Java version: 1.8.0 171
- Operating System: win 7

- Plugins/Mods:
: Mods (151): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge
, SpongeAPI, SpongeForge, Advanced Generators, Advanced Mortars, Advanced Rocket
ry, Alternating Flux, Antique Atlas, AppleSkin, Applied Energistics 2, Astral So
rcery, AutoRegLib, B.A.S.E, BC Builders, BC Energy, BC Factory, BC Robotics, BC
Silicon, BC Transport, BD Lib, BNBGamingLib, Baubles, Bedrock Ores, Better With
Mods, BiblioCraft, Biomes O' Plenty, BnBGamingCore, Bookshelf, Brandon's Core, B
uildCraft, BuildCraft Lib, CLibrary, Car Mod, Carpenter's Blocks, Chameleon, Cha
rcoal Pit, Chisel, Chisels & Bits, CoFH Core, CoFH World, CodeChicken Lib, Compa
cter, ContentTweaker, CraftTweaker JEI Support, CraftTweaker2, Despawning Spawne
rs, Dimensional Control, Draconic Evolution, EFab, Embers, Engineer's Doors, Exa
mple Mod, FTB Utilities, FTBLib, Factory Tech, Fast Leaf Decay, FastWorkbench, F
orestry, Forge Microblocks, Forge Multipart CBE, Foundry, Game Stages, Guidebook
, HardLib, Harder Ores, Immersive Cables, Immersive Craft, Immersive Engineering
, Immersive Petroleum, Immersive Railroading, Immersive Tech, InControl, Industr
ial Wires, IndustrialCraft 2, Inventory Tweaks, Iron Chest, ItemPhysic, JAOPCA,
JourneyMap, Just A Ore Processing Compatibility Attempt: Customized, Just Enough
 Items, Loot Table Tweaker, Lost Souls, MCMultiPart, MTLib, Magic Mirror, MagicB
ees, Magneticraft, MalisisCore, MalisisDoors, MatterOverdrive, McJtyLib, Minecra
ft Multipart Plugin, Mod Tweaker, ModelLoader, Modular Diversity, Modular Machin
ery, MrTJPCore, Nature's Compass, NetherPortalFix, Networks Manager, NoMoreRecip
eConflict, Not Enough Items, NuclearCraft, OpenBlocks, OpenModsLib, OpenModsLib
Core, Ore Flowers, OreDictInit, Perfect Spawn, Placebo, PneumaticCraft: Repressu
rized, PrimalCore, ProjectRed Core, ProjectRed Exploration, ProjectRed Fabricati
on, ProjectRed Illumination, ProjectRed Transmission, ProjectRed integration, Ps
i, Questionably Immersive, RecipeStages, Redstone Flux, Rockhounding Mod: Chemis
try, Rockhounding Mod: Core, Rustic, Shadowfacts' Forgelin, Signals, SimpleAutoR
un, Soot, Storage Drawers, Subterranean Waters, Survivalist, SwingThroughGrass,
TerraCart Reloaded, The Lost Cities, The Lost Quiver, Thermal Foundation, Togeth
erForever, Totemic, Track API, UniDict, Vulpes library, Waila, WanionLib, Water
Control Extreme, WrapUp, customoregen

**Issue Description**
This happens randomly after entering the world, possibly during world generation.
Disabling the timings module does not help.

Crash log: https://gist.github.com/wormzjl/959bc7f1f06902319afa7581bb9ddc3b
Server log: https://gist.github.com/wormzjl/b002c9f7bc9b2ae85be8dca5126a3d1c

**Comment by Aaron1011** [comment]
@wormzjl This is due to a mod failing to properly register its blocks with Forge.

I've improved the error message in the latest build of SpongeForge, which will allow us to determine which mod is responsible for this.

**Comment by wormzjl** [comment]
Is it 1.12.2-2705-7.1.0-BETA-3142 ?

**Comment by Aaron1011** [comment]
@wormzjl Yes, that's correct.

**Comment by wormzjl** [comment]
So betterwithmods is messing with vanilla mushroom block which causes the crash.

Crash log: https://gist.github.com/wormzjl/c3213f608d2c0bcd5ad934cefc721784
Server log: https://gist.github.com/wormzjl/b28ed5ee3603ce1ba33b557267345bcb

After disabling it's mushroom farming feature it's no longer crashing, thanks!

**Comment by Aaron1011** [comment]
@wormzjl: Please report this to BetterWithMods - this is strictly a bug on their end.
