### ISSUE TITLE
Unloader Mod Incompatibility

### ISSUE THREAD

**Issue by Rsslone** [SpongePowered/SpongeForge#2195]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3136
- Forge version: forge-1.12.2-14.23.4.2705-universal
- Java version: 1.8.0_152-b16
- Operating System: WIN-8.1

- Plugins/Mods:  Mods (169): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Advanced Rocketry, Aether Legacy, Akashic Tome, AngelRing 2 Bauble, Animania, AppleSkin, Applied Energistics 2, Aquaculture, AutoRegLib, Automated Redstone, Avaritia, Bad Wither No Cookie! Reloaded, Baubles, Bed Patch, Better Builder's Wands, BiblioCraft, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Biomes O' Plenty, Blockcraftery, Bonsai Trees, Bookshelf, Brandon's Core, CD4017BE_lib, Car Mod, CedKilleur's End Cake, Ceramics, Chameleon, Chisel, Chisels & Bits, CodeChicken Lib, CommonCapabilities, Compact Solar Arrays, Construct's Armory, Cooking for Blockheads, CosmeticArmorReworked, CraftStudio API, CraftTweaker JEI Support, CraftTweaker2, CreativeCore, CreativeCoreDummy, Cyclops Core, Despawning Spawners, Diet Hopper, Dimensional Doors, Doomlike Dungeons, Draconic Evolution, Dynamic Surroundings, EluCore, EluLib, Engineer's Workshop Reborn, Extended Days, Extra Cells 2, Extra Utilities 2, FTB Guides, FTB Utilities, FTBLib, Fairy Lights, Farseek, FastWorkbench, FoamFix, FoamFixCore, Forestry, Gravestone Mod, Immersive Engineering, Immersive Petroleum, Immersive Tech, Industrial Foregoing, Industrial Wires, IndustrialCraft 2, InitialInventory, Integration Foregoing, Inventory Tweaks, Iron Backpacks, Iron Chest, JAOPCA, JAOPCASingularities, JEI Bees, Just Enough Items, LagGoggles, MTLib, MagicBees, Magneticraft, Malisis Switches, MalisisCore, MalisisDoors, Mantle, McJtyLib, Mekanism, MekanismTools, MineTweakerRecipeMaker, Mod Tweaker, ModelLoader, Morpheus, MrCrayfish's Furniture Mod, Multi-Storage, Natura, NetherPortalFix, NuclearCraft, Nutrition, OnlinePictureFrame, OpenBlocks, OpenComputers, OpenComputers (Core), OpenModsLib, OpenModsLib Core, OreDictInit, Pam's Cookables, Pam's HarvestCraft, Placebo, Platforms, PneumaticCraft: Repressurized, Power Adapters, Quick Leaf Decay, RandomPatches, Ranged Pumps, Reborn Core, Redstone Flux, Roots 2, Shadowfacts' Forgelin, ShetiPhian-Core, Shield Parrying, Silent Lib, Spartan Shields, Spatial Server Mod, Storage Drawers, Streams, Super Sound Muffler, TESLA, TOP Addons, Tell Me, Tesla Core Lib, Tesla Core Lib Registries, Thaumcraft, The One Probe, The Twilight Forest, Thirsty Bottles, Tinkers' Complement, Tinkers' Construct, To the Bat Poles!, TogetherForever, Totemic, Tree Chopper, Tumbleweed, UniDict, Unloader, Vulpes library, Waddles, WanionLib, Water Control Extreme, Water Strainer, Waystones, Wireless Crafting Terminal 2, Wither Skeleton Tweaks, WrapUp, XNet, magma_monsters, mob_grinding_utils, p455w0rd's Library

**Issue Description** https://pastebin.com/HqnxHCU1 shortly after server startup, this log prints.

Gist was not saving the full log. Here is the lastest.log file. https://puu.sh/AytQB/2218d1dea5.log

**Comment by phit** [comment]
as a solution: remove Unloader from your mods, Sponge already does the same thing

**Comment by Rsslone** [comment]
Oh duh, I should have put that together. Well thanks for helping out a noob.

**Comment by gabizou** [comment]
While I'm able to resolve the issue of mods attempting to do better world management on their own, they are using methods available, but I'm not going to put out a fix relatively soon. I can make it where it will be "compatible" in the sense that the events thrown from the mod will be ~~intercepted~~ handled correctly by sponge, it's a little tricky with the way they are doing it. It's simple enough to replicate however, so a fix should be out soon, just no ETA.

For reference, mod's code:
https://github.com/Unnoen/Unloader/blob/master/src/main/java/com/unnoen/unloader/Unloader.java

**Comment by Rsslone** [comment]
I understand, It'd be more of a sanity check for people like me. Realistically people should just use sponge for load unloading.

**Comment by Zidane** [comment]
Closing as this is a feature in Sponge. This mod is made pointless by having SpongeForge installed.
