### ISSUE TITLE
Off main thread uncaught exception with thaumcraft

### ISSUE THREAD

**Issue by Rsslone** [SpongePowered/SpongeForge#2196]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3136
- Forge version: forge-1.12.2-14.23.4.2705-universal
- Java version:  1.8.0_152-b16
- Operating System: WIN-8.1

- Plugins/Mods: (168): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Advanced Rocketry, Aether Legacy, Akashic Tome, AngelRing 2 Bauble, Animania, AppleSkin, Applied Energistics 2, Aquaculture, AutoRegLib, Automated Redstone, Avaritia, Bad Wither No Cookie! Reloaded, Baubles, Bed Patch, Better Builder's Wands, BiblioCraft, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Biomes O' Plenty, Blockcraftery, Bonsai Trees, Bookshelf, Brandon's Core, CD4017BE_lib, Car Mod, CedKilleur's End Cake, Ceramics, Chameleon, Chisel, Chisels & Bits, CodeChicken Lib, CommonCapabilities, Compact Solar Arrays, Construct's Armory, Cooking for Blockheads, CosmeticArmorReworked, CraftStudio API, CraftTweaker JEI Support, CraftTweaker2, CreativeCore, CreativeCoreDummy, Cyclops Core, Despawning Spawners, Diet Hopper, Dimensional Doors, Doomlike Dungeons, Draconic Evolution, Dynamic Surroundings, EluCore, EluLib, Engineer's Workshop Reborn, Extended Days, Extra Cells 2, Extra Utilities 2, FTB Guides, FTB Utilities, FTBLib, Fairy Lights, Farseek, FastWorkbench, FoamFix, FoamFixCore, Forestry, Gravestone Mod, Immersive Engineering, Immersive Petroleum, Immersive Tech, Industrial Foregoing, Industrial Wires, IndustrialCraft 2, InitialInventory, Integration Foregoing, Inventory Tweaks, Iron Backpacks, Iron Chest, JAOPCA, JAOPCASingularities, JEI Bees, Just Enough Items, LagGoggles, MTLib, MagicBees, Magneticraft, Malisis Switches, MalisisCore, MalisisDoors, Mantle, McJtyLib, Mekanism, MekanismTools, MineTweakerRecipeMaker, Mod Tweaker, ModelLoader, Morpheus, MrCrayfish's Furniture Mod, Multi-Storage, Natura, NetherPortalFix, NuclearCraft, Nutrition, OnlinePictureFrame, OpenBlocks, OpenComputers, OpenComputers (Core), OpenModsLib, OpenModsLib Core, OreDictInit, Pam's Cookables, Pam's HarvestCraft, Placebo, Platforms, PneumaticCraft: Repressurized, Power Adapters, Quick Leaf Decay, RandomPatches, Ranged Pumps, Reborn Core, Redstone Flux, Roots 2, Shadowfacts' Forgelin, ShetiPhian-Core, Shield Parrying, Silent Lib, Spartan Shields, Spatial Server Mod, Storage Drawers, Streams, Super Sound Muffler, TESLA, TOP Addons, Tell Me, Tesla Core Lib, Tesla Core Lib Registries, Thaumcraft, The One Probe, The Twilight Forest, Thirsty Bottles, Tinkers' Complement, Tinkers' Construct, To the Bat Poles!, TogetherForever, Totemic, Tree Chopper, Tumbleweed, UniDict, Vulpes library, Waddles, WanionLib, Water Control Extreme, Water Strainer, Waystones, Wireless Crafting Terminal 2, Wither Skeleton Tweaks, WrapUp, XNet, magma_monsters, mob_grinding_utils, p455w0rd's Library

**Issue Description** I am not sure but the log is referencing aura which is thaumcraft. Server appears to be running fine but still reporting just in case. https://pastebin.com/ixRmwT1E

 Gist can't handle the size of my log :p https://puu.sh/AyBkO/f676af8b1d.log

**Comment by phit** [comment]
please report this to Thaumcraft

**Comment by Rsslone** [comment]
Thanks, will do.
