### ISSUE TITLE
The beneath mod not creating portal.

### ISSUE THREAD

**Issue by Pixelmnkey** [SpongePowered/SpongeForge#2197]
Using the latest version from sponge and sevtech, the beneath mod dosn't create a room when you use the portal, suffocating people, but placing a portal block inside the beneath creates the right room outside in the overworld. What can cause that? It works fine on forge.

SpongeForge Version: 1.12.2-2705-7.1.0-BETA-3143
Forge version: 2705
Plugins/mods: Runing latest version of sevtech and about plugins, luckyperms, forgedperms, nucleus.

**Comment by phit** [comment]
please post your global.conf

**Comment by Pixelmnkey** [comment]
There ya go https://pastebin.com/r8uPAzds

**Comment by Pixelmnkey** [comment]
Still nothing, seems to keep the y when you create the portal, but refuses to spawn a platform, it works fine from beneath to overworld.

**Comment by phit** [comment]
please add all relevant mod versions to your main post

- SpongeForge version
- Forge version
- Plugins/Mods

**Comment by Pixelmnkey** [comment]
Done.
