### ISSUE TITLE
Forced Disconnect with The Camping Mod

### ISSUE THREAD

**Issue by Rutes** [SpongePowered/SpongeForge#2198]
Issue also posted here: https://github.com/Rikmuld/MC-Camping/issues/116

- SpongeForge version:  spongeforge-1.12.2-2705-7.1.0-BETA-314

- Plugins/Mods:
The Camping Mod v2.4.3

Excerpt of server log showing the forced disconnect:
https://gist.github.com/Rutes/32b4e28013d93664d046b096986ce9b2

**Comment by Rutes** [comment]
The disconnect occurs when opening the "camping inventory" if one has not yet received the advancement for doing so. So, I would guess it's somehow related to advancements or inventory UI.

**Comment by phit** [comment]
looks like a mod issue
`Caused by: java.lang.IllegalStateException: CauseStackManager called from off main thread`

**Comment by Aaron1011** [comment]
This is a bug in The Camping Mod - it's trying to open a GUI off the main thread.

I've opened an issue here: https://github.com/Rikmuld/MC-RMCore/issues/1

**Comment by Aaron1011** [comment]
This has been fixed in the next version of The Camping Mod.
