### ISSUE TITLE
SGCraft TE's unable to tick TE / load chunks due to this commit

### ISSUE THREAD

**Issue by Dockter** [SpongePowered/SpongeForge#2199]
SF Working :  == 3119
SF Not Working : =>3124 

Issue,  SGCrafts TE ability to Tick/keep chunks loaded seems to be dead in SF builds => 3124.

The TE uses this chunk manager:  https://github.com/AlmuraDev/SGCraft/blob/Sponge-7.1.0/src/base/gcewing/sg/BaseTEChunkManager.java

Please advise.

**Comment by Dockter** [comment]
Ive double confirmed that the build differences between 3119 and 3124 are the issue.

**Comment by JoeSGT** [comment]
@Dockter  it seem to be the same issue here https://github.com/SpongePowered/SpongeForge/issues/2129

**Comment by phit** [comment]
https://github.com/SpongePowered/SpongeForge/commit/824dffa9714b0493baef6a3a2c10cf6c8ce7323e
