### ISSUE TITLE
Astral sorcery Mantle of Stars : Vicio -- Fatal Error

### ISSUE THREAD

**Issue by Pixelmnkey** [SpongePowered/SpongeForge#2201]
Hey there, we just switched to spongeforge and suddenly the mantle of star attuned to vicio from astral sorcery, wich works as an elytra, causes a fatal error while the vanilla elytra dosn't.

SpongeForge Version: 1.12.2-2705-7.1.0-BETA-3143
Forge version: 2705
Plugins/mods: Runing latest version of sevtech and about plugins, luckyperms, forgedperms, nucleus.

**Comment by Aaron1011** [comment]
@Pixelmnkey: Please pastebin the error and your server log.

**Comment by Aaron1011** [comment]
This is another packet handler related bug: https://github.com/HellFirePvP/AstralSorcery/issues/739.

@Pixelmnkey: In the future, please attach your crash report and server logs to any issues involving crashes.
