### ISSUE TITLE
Cannot Use Water/Lava Buckets

### ISSUE THREAD

**Issue by kristi71111** [SpongePowered/SpongeForge#2202]
**I am currently running**

- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3144
- Forge version: 14.23.4.2705
- Java version:  java version "1.8.0_121"
- Operating System: CentOS7

- Plugins/Mods: 
Plugins:
Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, BaconTowny, EconomyLite, Nucleus

  Mods:  
  Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AE2 Stuff, Actually Additions, Advanced Rocketry, Advanced Rocketry Core, AppleCore, AppleSkin, Applied Energistics 2, AutoRegLib, B.A.S.E, BD Lib, Bad Wither No Cookie! Reloaded, Baubles, Bed Patch, Better Advancements, Better Builder's Wands, Better Questing, Better Questing Triggerer, BiblioCraft, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Blockcraftery, Bookshelf, Chameleon, Charset, Chest Transporter, Chisel, Chisels & Bits, Clumps, CoFH Core, CoFH World, CodeChicken Lib, Cooking for Blockheads, CraftTweaker JEI Support, CraftTweaker2, Dark Utilities, Diet Hopper, EFab, EluCore, EluLib, EnderStorage, Engineer's Doors, Engineer's Workshop Reborn, Environmental Tech, Exchangers, Extra Cells 2, Extra Utilities 2, Extreme Reactors, FTB Guides, FTB Utilities, FTBLib, FastWorkbench, Flat Colored Blocks, Flux Networks, FoamFix, FoamFixCore, Forestry, Forge Microblocks, Forge Multipart CBE, GenDustry, Harvest, Immersive Engineering, Immersive Petroleum, Industrial Foregoing, InitialInventory, Inventory Tweaks, Iron Backpacks, Iron Chest, JEI Bees, JourneyMap, Just Enough Items, Loot Table Tweaker, MTLib, MagicBees, Mantle, McJtyLib, MineTogether, MineTogetherServer, Minecraft Multipart Plugin, Mod Tweaker, Morpheus, Natura, NetherPortalFix, OpenBlocks, OpenModsLib, OpenModsLib Core, OreExcavation, OreExcavation Integration, Pam's HarvestCraft, Pretty Beaches, ProjectE, Quark, Quick Leaf Decay, RFTools, RFTools Control, RFToolsPower, Ranged Pumps, Reborn Core, Redstone Arsenal, Redstone Flux, Refined Storage, Sampling Performance Profiler, Shadowfacts' Forgelin, SimpleLogic, Simply Jetpacks 2, Snad, SonarCore, Standard Expansion, Steve's Carts 2, Storage Drawers, Storage Drawers Extras, TESLA, TOP Addons, Tech Reborn, Tesla Core Lib, Tesla Core Lib Registries, The One Probe, The Spice of Life, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Tinkers Tool Leveling, Tinkers' Construct, TorchMaster, Translocators, Traverse, UniDict, Universal Modifiers, Valkyrie Lib, Vulpes library, WanionLib, Wireless Crafting Terminal 2, WirelessRedstone-CBE, XNet, YABBA, Zero CORE, careerbees, p455w0rd's Library

**Issue Description**
    Lava buckets and water buckets cannot be normally placed (Right clicking with the buckets on a 
    surface does not actually place the liquid however it also does not consume the liquid in the bucket). 
    Tested with sponge version 1.12.2-2705-7.1.0-BETA-3142 and it behaves normally. It seems like version 
     1.12.2-2705-7.1.0-BETA-3143 breaks it.

**Comment by Aaron1011** [comment]
@bloodmc: Based on the build numbers (and the fact that this is an interaction issue), this appears to have been caused by your change: https://github.com/SpongePowered/SpongeForge/commit/cad257e63d4c7937ce6d5497539947bc7bbe498e
