### ISSUE TITLE
not recognizing techgun zombies properly

### ISSUE THREAD

**Issue by pyscho974** [SpongePowered/SpongeForge#2204]
**I am currently running** 

- SpongeForge version: 3148
- Forge version: 2707
- Java version: 1.8.171
- Operating System:win7 x64

- Plugins/Mods:
TConstruct-1.12.2-2.10.0.81
techguns-1.12.2-2.0.1.1

**Issue Description**
tinkers bows are 1 shot killing tech gun zombies . tech gun zombies are not dropping any loot or xp.
im told has something to do with techguns registering its mobs as fake players 

https://gist.github.com/pyscho974/cae160fe5994dc1a9f78152101ed8c24

**Comment by pyscho974** [comment]
is also reported on techguns side it seems 

https://github.com/pWn3d1337/Techguns/issues/181

**Comment by Aaron1011** [comment]
This is a bug with TechGuns. Though Sponge may call `ISpecialArmor#damageArmor` in situations that Forge doesn't, it's still TechGun's responsibility to do a proper `instanceof` check before casting.
