### ISSUE TITLE
FTB Utilities chunk loader bugs

### ISSUE THREAD

**Issue by Aang23** [SpongePowered/SpongeForge#2205]
**I am currently running**

- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3136
- Forge version: 14.23.4.2705
- Java version: 8.171
- Operating System: Linux (Ubuntu Server 18.04) 

- Plugins/Mods: Nucleus, FTB Utilities, FTBLib, SpongeForge

**Issue Description**
Try to claim a chunk with FTB Utilities. It does not work. Restarting the server make the chunks load, but unclaming and them reclaiming does the same. FTB works fine without Sponge.
I tried with FTB + Sponge only, same issue.

This was already reported back in 1.10.2.

EDIT : If the player comes in the loaded chunks, and quit them, the chunkload stops working too. (In case it was loaded by restarting the server)

**Comment by bloodmc** [comment]
This was already fixed, update to latest SF.

**Comment by Aang23** [comment]
Tanks, I didn't know it because I was using the "recommended" build.
Sorry for reporting.
