### ISSUE TITLE
There seems to be a small problem with the waystone mod

### ISSUE THREAD

**Issue by philipzou** [SpongePowered/SpongeForge#2206]
**I am currently running**

- SpongeForge version: 3124 ,3133 ,3149
- Forge version: 2703 & 2705
- Java version: Java 8
- Operating System:Win 7

- Plugins/Mods: 
Plugin:
Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, CmdCalendar, FlexibleLogin, LuckPerms, Nucleus, Twenty Ticks 
Mod:
Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AE2 Stuff, Advanced Solar Panels, AppleCore, AppleSkin, Applied Energistics 2, BC Builders, BC Energy, BC Factory, BC Robotics, BC Silicon, BC Transport, BD Lib, Baubles, BetterBedrockGen, Botania, BuildCraft, BuildCraft Lib, Chest Transporter, ChineseWorkshop, ChinjufuMod, CreativeCore, CreativeCoreDummy, Doggy Talents, Extra Cells 2, FoamFix, FoamFixCore, Ice and Fire, IndustrialCraft 2, Inventory Tweaks, Iron Chest, JourneyMap, Just Enough Buttons, Just Enough Characters, Just Enough Items, LLibrary, MmmMmmMmmMmm, Modern Lights, MrCrayfish's Furniture Mod, Multiple Lights, OnlinePictureFrame, Ore Shrubs, Pam's HarvestCraft, Quick Leaf Decay, Reliquary, Roguelike Dungeons, Roost, Server Tab Info, Sit, SlashBlade, Stacksize Mod, SwingThroughGrass, Tea: The Story, Thaumcraft, The Heartwork, The Twilight Forest, Waila, Waystones, What Are We Looking At, WorldEdit

**Issue Description**
Most of the information can be found here.
https://github.com/blay09/Waystones/issues/116#issuecomment-394506597
I tried removing the sponge and it sovled the problem,so I guess it`s a problem cause by sponge,I also tried to update to the latest version of sponge or remove all the plugins but the problem continued.

There is no error log appeared while this issue happened(When a player respawn),and I`m sorry that some of them are in Chinese.
https://gist.github.com/philipzou/ab798dcb7daa45a419cd217df089f2ab

**Comment by Aaron1011** [comment]
This should be fixed in the next build of SpongeForge.
