### ISSUE TITLE
Async-lighting causing cast exception with AdvancedRocketry

### ISSUE THREAD

**Issue by LemADEC** [SpongePowered/SpongeForge#2209]
**I am currently running**

- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3148
- Forge version: 1.12.2-14.23.4.2707
- Java version: 1.8.0_171
- Operating System: CentOS

- Plugins/Mods:
FTB Continuum 1.2.0 including AdvancedRocketry-1.12.2-1.4.0-83-universal.jar
Prism (custom fixed for inventory handling) https://github.com/LemADEC/Prism

**Issue Description**
1- Build an Advanced Rocketry rocket, assemble it, sneak-right click the rocket entity
2- Open the "Guidance Computer", then move the chip id inside it.

In console, a cast exception is reported:
```
[16:45:18] [Server thread/ERROR] [Sponge]: Could not pass ClickInventoryEvent$Shift$Primary$Impl to Plugin{id=prism, name=Prism, version=3.0.0, description=A rollback/restore grief-prevention plugin., url=http://helion3.com/, authors=[viveleroi], source=/home/continuum/./plugins/Prism-3.0.0-beta3-S7.1-Lem2018-02-21a.jar}
java.lang.ClassCastException: zmaster587.advancedRocketry.world.util.WorldDummy cannot be cast to org.spongepowered.common.interfaces.world.IMixinWorldServer
>       at net.minecraft.world.chunk.Chunk.handler$onConstruct$zoo000(Chunk.java:4540) ~[axw.class:?]
>       at net.minecraft.world.chunk.Chunk.<init>(Chunk.java:95) ~[axw.class:?]
>       at zmaster587.advancedRocketry.world.util.ChunkProviderDummy.func_186025_d(ChunkProviderDummy.java:22) ~[ChunkProviderDummy.class:unspecified]
>       at net.minecraft.world.World.func_72964_e(World.java:309) ~[amu.class:?]
>       at net.minecraft.world.World.getBlockType(World.java:5462) ~[amu.class:?]
>       at org.spongepowered.api.world.extent.BlockVolume.getBlockType(BlockVolume.java:123) ~[BlockVolume.class:1.12.2-2705-7.1.0-BETA-3148]
>       at org.spongepowered.api.world.Location.toContainer(Location.java:795) ~[Location.class:1.12.2-2705-7.1.0-BETA-3148]
>       at com.helion3.prism.util.EventUtil.getLocationDataContainer(EventUtil.java:124) ~[EventUtil.class:3.0.0-beta3-S7.1-xxx+unknown-b0.git-unknown]
```
The relevant plugin line is here: https://github.com/LemADEC/Prism/blob/master/src/main/java/com/helion3/prism/util/EventUtil.java#L124

After disabling async-lighting and rebooting the computer, issue is no longer reproduced.

**Comment by Aaron1011** [comment]
Fixed in https://github.com/SpongePowered/SpongeCommon/commit/ebfb77b4079cabf5b07106b426dc45ada6051b06
