### ISSUE TITLE
Botania spark and corporea spark has limit. (config file already has the option.)

### ISSUE THREAD

**Issue by Mireu-zz** [SpongePowered/SpongeForge#2210]
- SpongeForge version: spongeforge-1.12.2-2655-7.1.0-BETA-3065
- Forge version: forge-1.12.2-14.23.3.2655
- Java version: jre-8u171-windows-x64
- Operating System: windows server 2016 (64x)

(I don't use latest version because Thaumcraft made some crash when update latest version)

Plugins (4): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge

Mods (111): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, /dank/null, AppleCore, AppleSkin, Baubles, Better Builder's Wands, BiblioCraft, Biomes O' Plenty, Blockcraftery, Botania, Brandon's Core, Chameleon, ChickenChunks, Chisel, Clay WorldGen, CoFH Core, CoFH World, CodeChicken Lib, CommonCapabilities, CompactDrawers, Cooking for Blockheads, CraftTweaker JEI Support, CraftTweaker2, Crafting Tweaks, Cyclops Core, Draconic Evolution, EluCore, EluLib, Ender IO, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Powertools, EnderCore, EnderStorage, Exchangers, Extra Utilities 2, Extreme Reactors, FTB Utilities, FTBLib, Fast Leaf Decay, FastWorkbench, Forge Microblocks, Forge Multipart CBE, Grappling hook mod, Hunger Overhaul, Immersive Cables, Immersive Engineering, Immersive Petroleum, Immersive Tech, Iron Backpacks, Iron Chest, JourneyMap, Just Enough Items, MTLib, MalisisCore, MalisisDoors, Mantle, McJtyLib, Minecraft Multipart Plugin, Mod Tweaker, Morpheus, Multiple Lights, NetherPortalFix, Not Enough Wands, OpenBlocks, OpenModsLib, OpenModsLib Core, Pam's HarvestCraft, Placebo, PortalGun, RFTools, RFToolsPower, Reborn Core, RebornStorage, Redstone Arsenal, Redstone Flux, Refined Storage, Refined Storage Addons, Signpost, Simple Inventory sorting, Simply Jetpacks 2, Storage Drawers, Storage Drawers Extras, SwingThroughGrass, TOP Addons, Thaumcraft, Thaumic Periphery, The One Probe, The Twilight Forest, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Tinkers' Construct, Translocators, UniDict, WanionLib, Waystones, Zero CORE, iChunUtil, p455w0rd's Library

Same as #1000. Botania spark and corporea spark has limit.
(config file already has the option. weird.)

max-entities-within-aabb=8
        # Per-mod overrides. Refer to the minecraft default mod for example.
        mods {
            botania {
                blocks {}
                # Default maximum collisions used for all entities/blocks unless overridden.
                defaults {}
                # If 'false', entity collision rules for this mod will be ignored.
                enabled=true
                entities {
                    botaniacorporeaspark=-1
                    botaniaspark=-1
                }

**Comment by Mireu-zz** [comment]
And another Q.
is there an option to toggle visible/invisible
for botania (force relay + warp lens) warping mana?
I can see it in singleplay world but can't in server.
(It's same world. I was copy that from server to singleplay)

**Comment by phit** [comment]
sounds like the config override for collisions broke, will need to test

**Comment by Aaron1011** [comment]
@Mireu-zz Your SpongeForge build is quite outdated. Please retest on the latest version - if there's an issue with Thaumcraft, open a separate issue for it.

**Comment by phit** [comment]
config system was reworked since then if this is still an issue on latest please open a new issue
