### ISSUE TITLE
Hopper deleting items

### ISSUE THREAD

**Issue by yepidoodles** [SpongePowered/SpongeForge#2212]
- SpongeForge version: API7 3151
- Forge version: 2707
- Java version: 8
- Operating System: Win7

- Plugins/Mods:
https://gist.github.com/yepidoodles/219eddffefb2db034e7ca8bc348a7f40

**Issue Description**
With a few modded blocks, when they output into a vanilla hopper, the items disappear (This does not happen on Single player with the same modpack). Does not happen with all modded blocks, so far we have discovered it happens with an Applied Energistics Grindstone and an Ender IO Sag Mill. It happens every time for those machines and prints out an error on console.

Full server log: https://gist.github.com/yepidoodles/a54043f0e98907fb553620d35876dc70
Relevant error from log: https://gist.github.com/yepidoodles/cf892f3648426b0ea1ef2571335c23ce

**Comment by Faithcaio** [comment]
The exception is the hopper pulling items out of an inventory.
Do the machines not allow extraction maybe?

**Comment by phit** [comment]
here's the source to the grindstone that was mentioned
https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/52d28fabe3d3de70892fba32e1e0a22bf0b174db/src/main/java/appeng/container/implementations/ContainerGrinder.java
https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/548af3c6ccef35b123bf37050389b23e8fca20fa/src/main/java/appeng/tile/grindstone/TileGrinder.java

**Comment by Faithcaio** [comment]
Try that next build.

**Comment by yepidoodles** [comment]
Hello,

I updated to SpongeForge 3167 and the issue still persists.

**Comment by Faithcaio** [comment]
You got an updated error log?

**Comment by phit** [comment]
https://i.imgur.com/5R4xpxF.png
https://i.imgur.com/HPWViDD.png

can't reproduce with appliedenergistics2-rv5-stable-11.jar
spongeforge-1.12.2-2705-7.1.0-BETA-3184.jar

edit: tried sag mill as well, even switched modes for the bottom face, still no issue https://i.imgur.com/HMbXoXt.png

**Comment by yepidoodles** [comment]
Still happening on 3190

https://gist.github.com/yepidoodles/c1fe26135509c8844c163be6d0c0cc70

**Comment by phit** [comment]
take a screenshot of the setup, we could not reproduce this at all

**Comment by yepidoodles** [comment]
Funny, as I posted that I thought I'd better add a screenshot - [![Screenshot from Gyazo](https://gyazo.com/611b31f1155decbcaedccb8600b3fdd1/raw)](https://gyazo.com/611b31f1155decbcaedccb8600b3fdd1)

**Comment by phit** [comment]
so basically the same thing i had, figure out what mods are needed to reproduce it
I was trying with just 
EnderCore-1.12.2-0.5.31.jar
EnderIO-1.12.2-5.0.26.jar
jei_1.12.2-4.10.0.198.jar
RedstoneFlux-1.12-2.0.2.3-universal.jar
spongeforge-1.12.2-2705-7.1.0-BETA-3184.jar
appliedenergistics2-rv5-stable-11.jar

and it worked fine

**Comment by yepidoodles** [comment]
I have no way to run a test server in order to try and find the culprit, and the current server I have running is public and active :/

**Comment by ryantheleach** [comment]
I've seen an issue years ago under bukkit with WorldGuard that was similar.

Make sure the area is unclaimed by protection plugins, (if you allow editing in wilderness), otherwise just double check that there isn't a conflicting claim permission on or near that boundary.

The issue it reminds me of was caused by the hopper and chest being in different regions, regardless of permissions, Off chance that it could be the case here?


Also check that you are able to reproduce this with this same setup elsewhere in the world, built by different people, or in different claims. It may be something subtle with who the block owners / notifiers are.

**Comment by yepidoodles** [comment]
Okay, so I did a little playing and I always found out that it's also deleting items when outputting into these mod blocks.
Screenshot: https://gyazo.com/97f49e9086f1b808c026b8904fb78cc8
Gist: https://gist.github.com/yepidoodles/6da08f71185562b44c7f3492c974eb52
Gist of it happening to someone else: https://gist.github.com/yepidoodles/4e2e74f7ad4421ff5469d2c41e333462

Gist of someone else trying the previous setup we've been testing: https://gist.github.com/yepidoodles/b93465ecab06487416bb72366a1781c0

I've also tried inside and outside of claims, had other people try them, none of them near claim boundaries, different types of claims, still get the same errors.

**Comment by james58899** [comment]
After https://github.com/SpongePowered/SpongeCommon/commit/922cc65c15ee80409e627b99975742b0c9606fae

console spam

```
[Server thread/WARN] [Sponge]: Unable to capture transaction from class net.minecraft.tileentity.TileEntityBrewingStand at index 0
[Server thread/WARN] [Sponge]: Unable to capture transaction from class net.minecraft.tileentity.TileEntityBrewingStand at index 1
[Server thread/WARN] [Sponge]: Unable to capture transaction from class net.minecraft.tileentity.TileEntityBrewingStand at index 2
[Server thread/WARN] [Sponge]: Unable to capture transaction from class net.minecraft.tileentity.TileEntityBrewingStand at index 3
[Server thread/WARN] [Sponge]: Unable to capture transaction from class net.minecraft.tileentity.TileEntityBrewingStand at index 0
```

**Comment by Faithcaio** [comment]
@james58899 should be fixed with latest
