### ISSUE TITLE
Droping items from any side of inventory causes them to not be droped but be voided

### ISSUE THREAD

**Issue by KingDan27** [SpongePowered/SpongeForge#2214]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3151.jar
- Forge version: FTBserver-1.12.2-14.23.3.2702-universal.jar
- Java version: openjdk version "1.8.0_171"
- Operating System: Ubuntu 16.04

- Plugins/Mods:
(mods)https://gist.github.com/KingDan27/2353f552c39cf4f220d0db5d88a5610d, (plugins)https://gist.github.com/KingDan27/4cf72d5de8d03f65f001519bcea3aabd

**Issue Description**
This has been a past issue not sure if it will help here but the ticket number is #991. When you first join a server dropping items from player inventory works fine (inconsistanly) after an amount of time it will stop working. when you click an item to the left of the player inventory the times will just vanish. Tried narrowing down the issue to a few mods with no success.

Latest.log: https://gist.github.com/KingDan27/1d463f2cf78a4e2a7f59a1a0a2669e2c
debug.log: https://gist.github.com/KingDan27/5595705975700a775439264a2b9a55e7

**Comment by bloodmc** [comment]
Reproduce with no mods or plugins then provide steps.

**Comment by phit** [comment]
seeing a lot of this in the log

```
[03:23:00] [Server thread/WARN] [FML]: Attempted to add a EntityItem to the world with a invalid item at (18632.50,  64.50, 35501.50), this is most likely a config issue between you and the server. Please double check your configs
[03:23:00] [Server thread/WARN] [net.minecraft.entity.EntityTrackerEntry]: Fetching addPacket for removed entity
[03:23:00] [Server thread/WARN] [net.minecraft.entity.EntityTrackerEntry]: Fetching addPacket for removed entity
```

**Comment by bloodmc** [comment]
Closing as I am unable to reproduce this with a clean server.

**Comment by bloodmc** [comment]
Actually, I see this is a FTB server pack. Remove all sponge plugins and retest. If issue persists then you will have to track down which mod is causing the issue.

**Comment by KingDan27** [comment]
Okay closing this ticket. Issue was narrowed down to catclearlag not sponge thanks for the assist.
