### ISSUE TITLE
Journey map issue

### ISSUE THREAD

**Issue by Zexceil** [SpongePowered/SpongeForge#2215]
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3148
- Forge version: 1.12.2-14.23.3.2702
- Java version: Java 8
- Operating System: Ubuntu server 18.04
- Reason for not upgrading: This build seems to work best with the server but only with that exception.
- Modpack: FTB Continuum

- Plugins/Mods:

Mods: 
Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AE2 Stuff, Actually Additions, Advanced Rocketry, Advanced Rocketry Core, AppleCore, AppleSkin, Applied Energistics 2, AutoRegLib, B.A.S.E, BD Lib, Bad Wither No Cookie! Reloaded, Baubles, Bed Patch, Better Advancements, Better Builder's Wands, Better Questing, Better Questing Triggerer, BiblioCraft, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Blockcraftery, Bookshelf, Chameleon, Charset, Chest Transporter, Chisel, Chisels & Bits, Clumps, CoFH Core, CoFH World, CodeChicken Lib, Cooking for Blockheads, CraftTweaker JEI Support, CraftTweaker2, Dark Utilities, Diet Hopper, EFab, EluCore, EluLib, EnderStorage, Engineer's Doors, Engineer's Workshop Reborn, Environmental Tech, Exchangers, Extra Cells 2, Extra Utilities 2, Extreme Reactors, FTB Guides, FTB Utilities, FTBLib, FastWorkbench, Flat Colored Blocks, Flux Networks, FoamFix, FoamFixCore, Forestry, Forge Microblocks, Forge Multipart CBE, GenDustry, Harvest, Immersive Engineering, Immersive Petroleum, Industrial Foregoing, InitialInventory, Inventory Tweaks, Iron Backpacks, Iron Chest, JEI Bees, JourneyMap, Just Enough Items, Loot Table Tweaker, MTLib, MagicBees, Mantle, McJtyLib, Minecraft Multipart Plugin, Mod Tweaker, Morpheus, Natura, NetherPortalFix, OpenBlocks, OpenModsLib, OpenModsLib Core, OreExcavation, OreExcavation Integration, Pam's HarvestCraft, Pretty Beaches, ProjectE, Quark, Quick Leaf Decay, RFTools, RFTools Control, RFToolsPower, Ranged Pumps, Reborn Core, Redstone Arsenal, Redstone Flux, Refined Storage, Sampling Performance Profiler, Shadowfacts' Forgelin, SimpleLogic, Simply Jetpacks 2, Snad, SonarCore, Standard Expansion, Steve's Carts 2, Storage Drawers, Storage Drawers Extras, TESLA, TOP Addons, Tech Reborn, Tesla Core Lib, Tesla Core Lib Registries, The One Probe, The Spice of Life, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Tinkers Tool Leveling, Tinkers' Construct, TorchMaster, Translocators, Traverse, UniDict, Universal Modifiers, Valkyrie Lib, Vulpes library, WanionLib, Wireless Crafting Terminal 2, WirelessRedstone-CBE, XNet, YABBA, Zero CORE, careerbees, p455w0rd's Library

Plugins: 
Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, CatClearLag, EconomyLite, LuckPerms, NuVotifier, Nucleus, SeriousVote

**Issue Description**
Everytime a player joins I keep getting an error from journey map related to sponge, I don't exactly know what it is.

<!-- Please provide a *full* server log (and crash-report if applicable).
https://gist.github.com/Zexceil/baff171af5859bd2a3d87c500fbc9953

**Comment by phit** [comment]
this was added by forge and needs to be fixed by journeymap, nothing to do with sponge https://github.com/MinecraftForge/MinecraftForge/pull/4890
https://github.com/TeamJM/journeymap/issues/42
