### ISSUE TITLE
SpongeForge messing up with configs of other mods

### ISSUE THREAD

**Issue by MCEventHorizon** [SpongePowered/SpongeForge#2216]
**I am currently running**

- SpongeForge version: 7.1.0-BETA-3151
- Forge version: 14.23.4.2707
- Java version: 1.8.0_171
- Operating System: Windows 10

- Plugins/Mods: LootBags, ArmorPlus, DrCyano's Lootable Bodies

I have found a lot of issues when sponge gets added to forge when it comes to loading mod configs, some configs aren't loaded at all and some get messed up. These are some examples:
1. LootBags - Even tho config is set to only give one bag per mob, I get 2. Types of bags that I get are 
not the once that are in the config. Sometimes, I get a bag that's not even obtainable unless specified in the config which I didn't do(also is not enabled by default). Also, sometimes I get items from bags that are in the default config but not in the one I made.

2. ArmorPlus - Config is set not to damage players wearing lava armor in water and yet it does, config is set to requiring only one peace of armor to give an effect and still some armor require all the pieces. 

3. DrCyano's Lootable Bodies - Bodies don't drop nor do I get player's inventory items when they die

I tried all of these configs without sponge and they all work like they should.

Screenshots of configs vs in-game:
-Getting 2 bags instead of one
![2018-06-11_17 33 27](https://user-images.githubusercontent.com/15619786/41241747-179d2f76-6d9e-11e8-86e4-cb0797ad1f91.png)
![screenshot_1](https://user-images.githubusercontent.com/15619786/41241802-30536ecc-6d9e-11e8-9e0b-dc5aea32ea2a.png)
Config says 100% for a Common(White) and 10% for Uncommon(Green)

-Being damaged in water with Lava Armor vs config
![2018-06-11_17 34 15](https://user-images.githubusercontent.com/15619786/41241888-622d0c3c-6d9e-11e8-825a-d3ba4e880b23.png)
![2018-06-11_17 34 20](https://user-images.githubusercontent.com/15619786/41241894-63e375ac-6d9e-11e8-80ae-031017e161ed.png)
![screenshot_2](https://user-images.githubusercontent.com/15619786/41250395-14534314-6db7-11e8-9bc3-9b1b266fa60a.png)

 https://gist.github.com/MCEventHorizon/8a1d0d301417619edc1fa05f0e2b5537

This is a local server log that I used to show this and I know that some configs are loaded cause I do get items from loot bags that I've set up and some of the other parts of configs work fine.

**Comment by bloodmc** [comment]
This has nothing to do with configs. There are probably just compatibility issues with the mods you are mentioning. Create an issue for each mod issue.
