### ISSUE TITLE
2705

### ISSUE THREAD

**Issue by tryolivier** [SpongePowered/SpongeForge#2217]
Hello, 

•SpongeForge version: API7 1.12.2-2705-7.1.0-BETA-3151
•Forge version: 2705
•Java version: 8
•Operating System: Win7
•Plugins/Mods:
Issue Description
I wanted to update spongeforge with the laste spongeforge, but I and all the players have :
https://image.noelshack.com/fichiers/2018/23/7/1528648914-2018-06-10-18-41-28.png

we have all the good forge but we have that :)

thanks to have a look =)

**Comment by phit** [comment]
use the issue template

**Comment by tryolivier** [comment]
PS bungee logs : https://paste.md-5.net/cavoxewali.pas

**Comment by liach** [comment]
@phit Issue has been updated, consider reopening it.

**Comment by phit** [comment]
@liach they already messaged me on discord, I'll quote myself

> phit: still no reproduction , either way this is not a sponge issue, im running sponge myself with bungeecord with no issues
use the support forums or discord, to figure out a solution or report it to bungeecord

Obviously I'm not the only person doing so, plenty of other servers using Bungeecord with latest SF with no issues. If there is an issue with more recent BungeeCord versions, add the last version it works with to the issue and provide proper reproduction.
Then we can see about working with Waterfall/SpongePls to fix it. As the official BungeeCord does not officially support Forge and will close all issues for it on their tracker.
