### ISSUE TITLE
Mods and plugins can not run

### ISSUE THREAD

**Issue by YaoTeacher** [SpongePowered/SpongeForge#2218]
**I am currently running**

- SpongeForge version: 
- Forge version: spongeforge-1.12.2-2705-7.1.0-BETA-3151
- Java version: forge-1.12.2-14.23.4.2707-universal
- Operating System:WIN10

- Plugins/Mods:
Mods:  zombieawareness; vampirism; telepads; mobends; immersiveEngineering; dynamictrees; customnpcs; baubles; astralsorcery;  colorchat; epicsiege; forestry
Plugins: Nucleus; placeholderAPI; UniversalMarket; latch; ServerListPlus;PixeAutoMessages; LuckPerms; griefprevention; projectcore; stackban; holograms; CommandBlockinngManager; VirtualChest; EasyScoreboards; inspector; FastAsyncWorldEdit; K4lib; QuickLeafDecay; MyCommands; felxiblelogin

**Issue Description**
[2018-06-12-7.log.gz](https://github.com/SpongePowered/SpongeForge/files/2092994/2018-06-12-7.log.gz)
[debug-5.log.gz](https://github.com/SpongePowered/SpongeForge/files/2092995/debug-5.log.gz)

**Comment by gabizou** [comment]
Plugins are definitely running there, you have some commands that aren't running, but it sounds like you have not set up your permissions correctly to be able to execute the commands. Either way, configuration error, not sponge error.
