### ISSUE TITLE
Lava Armor is still being damaged in water 

### ISSUE THREAD

**Issue by MCEventHorizon** [SpongePowered/SpongeForge#2220]
- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3151
- Forge version: 14.23.4.2707
- Java version: 1.8.0_171
- Operating System: Windows 10

- Plugins/Mods: Armor Plus and TheDragonLib

**Issue Description**
Most of the configs from the mod armor plus don't get loaded:
1. In the config I set armors to give buffs even when wearing one peace but in game, they require a full set.
2. Lava armor is set to not damage a player while in water:
https://user-images.githubusercontent.com/15619786/41250395-14534314-6db7-11e8-9bc3-9b1b266fa60a.png
And yet:
https://user-images.githubusercontent.com/15619786/41241894-63e375ac-6d9e-11e8-80ae-031017e161ed.png

Log: https://gist.github.com/MCEventHorizon/8a1d0d301417619edc1fa05f0e2b5537

**Comment by gabizou** [comment]
For reference, the armor code:
https://github.com/TheDragonTeam/ArmorPlus/blob/1.12/src/main/java/net/thedragonteam/armorplus/armors/APArmorMaterial.java#L90

**Comment by MCEventHorizon** [comment]
Excuse me but this isn't the only problem I mentioned, other configs don't work neither, all armor that I set to require only one piece still require full set.

**Comment by Aaron1011** [comment]
@MCEventHorizon: I'm unable to reproduce the water debuff issue. Can you re-test on the latest SpongeForge?

**Comment by MCEventHorizon** [comment]
@Aaron1011 With latest sponge it doesn't do damage but it does give Slowness II which is also not intended.

**Comment by MCEventHorizon** [comment]
Seems to be fixed in the latest version.
