### ISSUE TITLE
Access transformers won't applied if plugin is in custom directory

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/SpongeForge#2221]
Access transformers working only if:
1. Plugin is in mods directory
2. Plugin forced to load as mod

Repro:
1. Download packetgate https://github.com/CrushedPixel/PacketGate
2. Put it in `mods/plugins/` dir
3. ???
4. PROFIT!

**Comment by phit** [comment]
intended behavior, even mentioned in the [docs](https://docs.spongepowered.org/stable/en/server/management/plugins.html?highlight=mixin%20mods#spongeforge)

oh and for the forceloadasmod, something in forge changed, theres a mixin ticket for it https://github.com/SpongePowered/Mixin/issues/253
