### ISSUE TITLE
Crash of the server when a specific player logs on

### ISSUE THREAD

**Issue by jinkhya** [SpongePowered/SpongeForge#2223]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3172.jar
- Forge version: 2705
- Java version: 1.8.0_121-b13
- Operating System: Centos 7.3.1611

- Plugins/Mods:
Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, /dank/null, AE2 Stuff, AI Improvements, Actually Additions, Actually Baubles, Advanced Generators, Advanced Rocketry, Akashic Tome, Ancient Warfare Automation, Ancient Warfare Core, Ancient Warfare NPCs, Ancient Warfare Structures, Ancient Warfare Vehicles, Animania, AppleCore, AppleSkin, Applied Energistics 2, ArchitectureCraft, Astral Sorcery, AutoRegLib, B.A.S.E, BD Lib, Backpack, Bad Wither No Cookie! Reloaded, Baubles, Bed Patch, Better Builder's Wands, Better Questing, Better Questing Quest Book, BiblioCraft, Binnie Core,Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Biomes O' Plenty, Blockcraftery, Blood Magic: Alchemical Wizardry, Bookshelf, Botania, Brandon's Core, Carry On, Chameleon, Chisel, Chisels & Bits, Chunk Pregenerator, Clumps, CoFH Core, CoFH World, CodeChicken Lib, Colytra, CommonCapabilities, Compact Machines 3, ComputerCraft, Cooking for Blockheads, CosmeticArmorReworked, CraftStudio API, CraftTweaker JEI Support, CraftTweaker2, Cyclic, Cyclops Core, Dark Utilities, Draconic Evolution, EluCore,
EluLib, Embers, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, EnderStorage, Environmental Materials, Environmental Tech, Exchangers, Extra Bit manipulation, Extra Cells 2, Extra Rails, Extra Utilities 2, Extreme Reactors, FTB Utilities, FTBLib, Farming for Blockheads, Farseek, FastWorkbench, Flat Colored Blocks, FoamFix, FoamFixCore, Forestry, Funky Locomotion, Garden Stuff, GenDustry, Grass Burner, Guide-API, Horse Tweaks, Immersive Engineering, Immersive Petroleum, Immersive Tech, Industrial Foregoing, IndustrialCraft 2, Integrated Dynamics, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTunnels-Compat, Integration Foregoing, Inventory Tweaks, Iron Backpacks, Iron Chest, IvToolkit, JAOPCA, JEI Bees, JourneyMap, Just Enough Items, Just Enough Pattern Banners, Just Enough Reactors, KleeSlabs, LagGoggles, LibrarianLib, LibrarianLib Stage 2, MCMultiPart, MTLib, MagicBees, Magical Psi, MalisisCore, MalisisDoors, Mantle, McJtyLib, MeeCreeps, Mekanism, MekanismGenerators, MekanismTools, MineColonies, Mod Tweaker, Modular Routers, Morph-o-Tool, Natura, Nature's Compass, No Mob Spawning on Trees, Not Enough Wands, NotEnoughIDs, NuclearCraft, Nutrition, OpenBlocks, OpenComputers, OpenComputers (Core), OpenModsLib, OpenModsLib Core, OreDictInit, OreExcavation, Pam's HarvestCraft, Placebo, PlayersDropHeads, PlusTiC, PneumaticCraft: Repressurized, Pretty Beaches, Psi, Quark, Quick Leaf Decay, RFTools, RFTools Control, RFTools Dimensions, RandomPatches, Recurrent Complex, Redstone Arsenal, Redstone Flux, Roots 2, Rustic, Scannable, ShadowMC, Shadowfacts' Forgelin, Spice of Life: Carrot Edition, Standard Expansion, Storage Drawers, Streams, Super Sound Muffler, SwingThroughGrass, TESLA, Tesla Core Lib, Tesla Core Lib Registries, Thaumcrafft Inventory Scanning, Thaumcraft, The Lost Cities, The Twilight Forest, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Tinker's JEI, Tinkers Tool Leveling, Tinkers' Construct, Tomb Many Graves, TombManyGraves2 API, TombManyPlugins Backpacks, TombManyPlugins Cosmetic Armor Reworked, TorchMaster, UniDict, Universal Modifiers, Unlimited Chisel Works, Unloader, Valkyrie Lib, Villager Market, Vulpes library, Waila, WanionLib, What Are We Looking At, Wireless Charger, Wireless Crafting Terminal 2, Wizardry, WrapUp, XNet, YNot, Zero CORE, careerbees, p455w0rd's Library
----
Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, CatClearLag, Enjin Minecraft
 Plugin, LuckPerms, MMCRestrict, Nucleus

As soon as a specific player logs on the server it crashes instantly.
- It was fine for him (he said he re made his team and claim before the server restarted)
- server restarted on its schedule
- the player tried joining again after restart and now it just crashes when he logs on. 

crash log : 
https://gist.github.com/jinkhya/956f5dbefef20becdca6e6b767a24711

full log : 
https://gist.github.com/jinkhya/551d29e9663f18a8a2030415af194fbd

thanks.

**Comment by bloodmc** [comment]
@Cybermaxke can you take a look at this?

**Comment by johnfriedrich** [comment]
Doesn't crash, but no one is able to login:
Full log:
https://pastebin.com/sLhxb5gN
Error on tried join: https://pastebin.com/b6eDzDCc

SF 3221 and 3270
Before this happened, someone used a "Block Placer" that created this little spammy errors:
https://pastebin.com/LWZdtd1a
I deleted the region, but guess this broke advancements somehow.

Maybe due to not working fake palyers?

**Comment by dogboy21** [comment]
We're also experiencing this with Fakeplayers

https://pastebin.com/pXGzcrZA

EDIT: Nvm, @i9hdkill already added it to his comment
