### ISSUE TITLE
Entity spawning console spam

### ISSUE THREAD

**Issue by Y0ungSandwich** [SpongePowered/SpongeForge#2224]
**I am currently running**

spongeforge-1.12.2-2705-7.1.0-BETA-3178 (but has happened on earlier builds as well.)
forge-1.12.2-14.23.4.2705-universal
- Java version:  1.8.0_171
- Operating System: Windows 10 + Cantos 6

- Plugins/Mods: Complete modpack modlist at this link https://www.atlauncher.com/pack/MechMagic

Immediately after starting the server the console is spammed with:
`[08:53:44] [Server thread/WARN] [FML]: Attempted to add a EntityItem to the world with a invalid item at (54.63,  70.44, -97.26), this is most likely a config issue between you and the server. Please double check your configs`

Only when sponge is present. Most locations it points to are near or in villages. This happens without anyone on the server. Logging onto the server and flying around will make this spam even more as you load more areas. 

https://gist.github.com/Y0ungSandwich/2483b67ca55b3e1401b6a162c352cf3e

**Comment by gabizou** [comment]
Not sure where I copied this from, but it originated in forge, and now I can't find how it was changed recently: https://github.com/SpongePowered/SpongeForge/blob/stable-7/src/main/java/org/spongepowered/mod/event/SpongeForgeEventFactory.java#L792

**Comment by gabizou** [comment]
Nevermind, found out that that bit of code was removed:
https://github.com/MinecraftForge/MinecraftForge/commit/2bd8b95a3b95cf65a84e7299332d5892e4a879d8#diff-27e07ae0b4ecb5d6fcc27c69d92db04eL57

Will be removing, but potentially there is a mod that is attempting to spawn empty itemstacks.
