### ISSUE TITLE
Cannot interact with Snow Villagers from Ice & Fire mod

### ISSUE THREAD

**Issue by Rutes** [SpongePowered/SpongeForge#2225]
- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3178
- Forge version: forge-1.12.2-14.23.4.2705-universal

- Plugins/Mods: Ice & Fire: Dragons in a Whole New Light

When interacting with "Snow Villagers" from the mod Ice & Fire, they do nothing. The server console throws some errors:
https://gist.github.com/Rutes/6a624bf8ca253989cd234c5b7ddc37eb

but there is not a crash. This happens only with Sponge present. Removing Sponge lets the Ice villagers interact normally. Posted this issue awhile back on the mod's github, but the issue persists. 
https://github.com/Alex-the-666/Ice_and_Fire/issues/398

Also since it seems to be related to Villager professions, not sure if it could be related to my other issue:
https://github.com/SpongePowered/SpongeForge/issues/2127

**Comment by gabizou** [comment]
Attempt SpongeForge 3181 once it's built. If it fails, it should provide a nice error message from sponge and still fall back, but it should provide a lot more insight as to the issue on sponge's side.

**Comment by gabizou** [comment]
Fixed with https://github.com/SpongePowered/SpongeForge/commit/67f080fbdbb3946fb2425fef486a22c775582555

**Comment by Rutes** [comment]
actually the snow villagers are still not working... No longer throwing errors to console, though. There is also a new version of Ice & Fire out today. So, I will test with everything at latest and re-open a new if still a problem.

**Comment by gabizou** [comment]
Give 3188 a shot.
