### ISSUE TITLE
ClickInventoryEvent does not trigger for empty slots

### ISSUE THREAD

**Issue by Xemiru** [SpongePowered/SpongeForge#2227]
**I am currently running**

- SpongeForge version: 7.1.0-BETA-3169
- Forge version: 2705
- Java version: 1.8.0_144
- Operating System: Windows 7

- Plugins/Mods: Test Plugin

**Issue Description**

The `ClickInventoryEvent` does not trigger for empty slots. Presumably this happens because essentially no transaction takes place when both the cursor and target slot is empty at the time of the event. The event triggers normally if there is an item in either place.

The following snippet can be used to verify this occurrence.

```java
import org.spongepowered.api.Sponge;
import org.spongepowered.api.event.Listener;
import org.spongepowered.api.event.item.inventory.ClickInventoryEvent;
import org.spongepowered.api.plugin.Plugin;
import org.spongepowered.api.text.Text;

@Plugin(id = "test")
public class Test {

    // region Event listeners

    @Listener
    public void onClick(ClickInventoryEvent e) {
        Sponge.getServer().getBroadcastChannel().send(Text.of("click happened"));
    }

    // endregion

}
```

Opening your own inventory and clicking an empty slot will not produce the message in the in-game chat. Clicking one with an item in either place will.

**Comment by phit** [comment]
~move to sc

**Comment by limbo-app** [comment]
Hey @Xemiru! I've moved your issue to [SpongePowered/SpongeCommon#1942](https://github.com/SpongePowered/SpongeCommon/issues/1942).
