### ISSUE TITLE
Crash on startup server.

### ISSUE THREAD

**Issue by yaroslav4167** [SpongePowered/SpongeForge#2228]
**I am currently running**

- SpongeForge version: 3182
- Forge version: 2705
- Java version: 1.8.0_151-b12
- Operating System: Linux

- Plugins/Mods: [plugins](http://bit.ly/2JN9iuT)/[mods](http://bit.ly/2tduzqw)

**Issue Description**
Crash on startup server.

Full server log: [log](http://bit.ly/2tctFL4)

**Comment by gabizou** [comment]
Duplicate https://github.com/SpongePowered/SpongeForge/issues/2226
