### ISSUE TITLE
Crash at the end of every server start

### ISSUE THREAD

**Issue by jinkhya** [SpongePowered/SpongeForge#2230]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3190.jar
- Forge version: 2705
- Java version: 1.8.0_121-b13
- Operating System: Centos 7.3.1611

- Plugins/Mods:
Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, /dank/null, AE2 Stuff, AI Improvements, Actually Additions, Actually Baubles, Advanced Generators, Advanced Rocketry, Akashic Tome, Ancient Warfare Automation, Ancient Warfare Core, Ancient Warfare NPCs, Ancient Warfare Structures, Ancient Warfare Vehicles, Animania, AppleCore, AppleSkin, Applied Energistics 2, ArchitectureCraft, Astral Sorcery, AutoRegLib, B.A.S.E, BD Lib, Backpack, Bad Wither No Cookie! Reloaded, Baubles, Bed Patch, Better Builder's Wands, Better Questing, Better Questing Quest Book, BiblioCraft, Binnie Core,Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Biomes O' Plenty, Blockcraftery, Blood Magic: Alchemical Wizardry, Bookshelf, Botania, Brandon's Core, Carry On, Chameleon, Chisel, Chisels & Bits, Chunk Pregenerator, Clumps, CoFH Core, CoFH World, CodeChicken Lib, Colytra, CommonCapabilities, Compact Machines 3, ComputerCraft, Cooking for Blockheads, CosmeticArmorReworked, CraftStudio API, CraftTweaker JEI Support, CraftTweaker2, Cyclic, Cyclops Core, Dark Utilities, Draconic Evolution, EluCore,
EluLib, Embers, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, EnderStorage, Environmental Materials, Environmental Tech, Exchangers, Extra Bit manipulation, Extra Cells 2, Extra Rails, Extra Utilities 2, Extreme Reactors, FTB Utilities, FTBLib, Farming for Blockheads, Farseek, FastWorkbench, Flat Colored Blocks, FoamFix, FoamFixCore, Forestry, Funky Locomotion, Garden Stuff, GenDustry, Grass Burner, Guide-API, Horse Tweaks, Immersive Engineering, Immersive Petroleum, Immersive Tech, Industrial Foregoing, IndustrialCraft 2, Integrated Dynamics, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTunnels-Compat, Integration Foregoing, Inventory Tweaks, Iron Backpacks, Iron Chest, IvToolkit, JAOPCA, JEI Bees, JourneyMap, Just Enough Items, Just Enough Pattern Banners, Just Enough Reactors, KleeSlabs, LagGoggles, LibrarianLib, LibrarianLib Stage 2, MCMultiPart, MTLib, MagicBees, Magical Psi, MalisisCore, MalisisDoors, Mantle, McJtyLib, MeeCreeps, Mekanism, MekanismGenerators, MekanismTools, MineColonies, Mod Tweaker, Modular Routers, Morph-o-Tool, Natura, Nature's Compass, No Mob Spawning on Trees, Not Enough Wands, NotEnoughIDs, NuclearCraft, Nutrition, OpenBlocks, OpenComputers, OpenComputers (Core), OpenModsLib, OpenModsLib Core, OreDictInit, OreExcavation, Pam's HarvestCraft, Placebo, PlayersDropHeads, PlusTiC, PneumaticCraft: Repressurized, Pretty Beaches, Psi, Quark, Quick Leaf Decay, RFTools, RFTools Control, RFTools Dimensions, RandomPatches, Recurrent Complex, Redstone Arsenal, Redstone Flux, Roots 2, Rustic, Scannable, ShadowMC, Shadowfacts' Forgelin, Spice of Life: Carrot Edition, Standard Expansion, Storage Drawers, Streams, Super Sound Muffler, SwingThroughGrass, TESLA, Tesla Core Lib, Tesla Core Lib Registries, Thaumcrafft Inventory Scanning, Thaumcraft, The Lost Cities, The Twilight Forest, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Tinker's JEI, Tinkers Tool Leveling, Tinkers' Construct, Tomb Many Graves, TombManyGraves2 API, TombManyPlugins Backpacks, TombManyPlugins Cosmetic Armor Reworked, TorchMaster, UniDict, Universal Modifiers, Unlimited Chisel Works, Unloader, Valkyrie Lib, Villager Market, Vulpes library, Waila, WanionLib, What Are We Looking At, Wireless Charger, Wireless Crafting Terminal 2, Wizardry, WrapUp, XNet, YNot, Zero CORE, careerbees, p455w0rd's Library

Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, CatClearLag, Enjin Minecraft
Plugin, LuckPerms, MMCRestrict, Nucleus, GriefProtection

- The world crashes after everything seems to be loaded. So it shows online for 2-3 seconds then crash. (without having anybody logging)
- World without sponge doesn't crash
- New world with sponge doesn't crash either. 

We tried rolling back, wich didn't fix it either, even with backups before it started crashing. 

Crash log : 
https://gist.github.com/jinkhya/21ea3a12ec2e7b10be613deb7c36e8cb

log :
https://gist.github.com/jinkhya/2b77e260374c5db9636ab9b338160df1

**Comment by bloodmc** [comment]
You can either remove foamfix as it interferes with our patches OR remove our blockpos mixin found in 'mixins.common.core.optional.json'. Remove the 'util.math.MixinMutableBlockPos' line and try foamfix again.

**Comment by phit** [comment]
@bloodmc FoamFix works fine with Sponge, that BlockPos mixin error does not cause any issues, but if you want to get rid of it simply set `B:optimizedBlockPos=false` in the `foamfix.cfg`

----
in regard to that crash, seems to be happening to everyone in the recent ATM3 update no real lead yet what mod update is causing it

**Comment by bloodmc** [comment]
Try removing all plugins and retest.

**Comment by jinkhya** [comment]
Yeah I turned it optimizedBlockPos to false after looking at logs, wich didn't stop it from crashing. I tried disabling foamfix  as suggested, didn't fix it either. 

OK will do about plugins.

**Comment by jinkhya** [comment]
it's apparently GriefProtection that is crashing it. It's not compatible with latest versions of sponge then I suppose?

**Comment by liach** [comment]
it crashed in updateTimeLightAndEntities

**Comment by bloodmc** [comment]
GP works fine on latest. Backup and reset your Luckperms to see if you have bad data.

**Comment by bloodmc** [comment]
LuckPerms-Sponge-4.1.61.jar  

You are using a completely outdated version of LP which can cause problems with GP. Update to latest LP.

**Comment by jinkhya** [comment]
Right, got it to work with latest version of luckperms and GP. Thanks for your help !
