### ISSUE TITLE
OTG command fails to create dimension

### ISSUE THREAD

**Issue by LemADEC** [SpongePowered/SpongeForge#2231]
**I am currently running**
- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3190
- Forge version: 14.23.4.2707
- Java version: 1.8.0_144
- Operating System: Windows 10:amd64:10.0

- Plugins/Mods:
Biome_Bundle-1.12.2-v6.1.jar
OpenTerrainGenerator-1.12.2 - v6.jar

**Issue Description**
The command to create dimension in OTG fails with an exception regarding
```
java.lang.RuntimeException: java.lang.NullPointerException: World Properties has a null UUID
```

Logs for single player:
https://gist.github.com/LemADEC/38cdf5e3148a4705ad2c330b8dbcddc0

**Comment by phit** [comment]
https://github.com/SpongePowered/SpongeForge/issues/2072#issuecomment-377701029
