### ISSUE TITLE
Riding boat not working properly

### ISSUE THREAD

**Issue by Liiw** [SpongePowered/SpongeForge#2233]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2705-8.0.0-BETA-3202
- Forge version: forge-1.12.2-14.23.4.2705
- Java version: 8 64bit
- Operating System: Win 10 Home 64bit

- Plugins/Mods: Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AE2 Stuff, Actually Additions, ActuallyComputers, Advanced Rocketry, AgriCraft, Alternating Flux, Ancient Warfare Automation, Ancient Warfare Core, Ancient Warfare NPCs, Ancient Warfare Structures, Ancient Warfare Vehicles, AppleCore, Applied Energistics 2, ArchitectureCraft, Armory Expansion, Aroma1997Core, AromaBackup, AromaBackuprecovery, AutoRegLib, BD Lib, Baubles, Better Builder's Wands, Better Records, Botania, Builders Guides, CXLibrary, Chameleon, Chest Transporter, ChickenChunks, Chisels & Bits, Chunk Pregenerator, Clay Bucket, CoFH Core, CoFH World, CodeChicken Lib, Construct's Armory, Cooking for Blockheads, Corail Tombstone, CosmeticArmorReworked, CraftTweaker JEI Support, CraftTweaker2, CreativeCore, CreativeCoreDummy, DebugServerInfo, Deep Sea Expansion, Dense Metals, Dynamic Surroundings, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, Ender Ore, Ender Zoo, EnderCore, EnderStorage, Exchangers, Extra Cells 2, Extreme Reactors, Farming for Blockheads, Fence Overhaul, FoamFix, FoamFixCore, Forestry, Forge Microblocks, Forge Multipart CBE, GenDustry, Good Ol' Currency Mod, Guide-API, Hammer Core, Hunger Overhaul, Immersive Cables, Immersive Engineering, Immersive Petroleum, Immersive Railroading, InControl, Infernal Mobs, InfinityLib, InstantUnify, Inventory Tweaks, Iron Backpacks, Iron Chest, IvToolkit, JAOPCA, JEI Bees, JourneyMap, Just A Ore Processing Compatibility Attempt: Additions, Just Enough Items, Just Enough Reactors, Land Manager, MTLib, MTS Offical Pack, MalisisCore, MalisisDoors, Mantle, McJtyLib, Minecraft Multipart Plugin, Minecraft Transport Simulator, Mo' Villages, Mod Tweaker, More Bees, MrCrayfish's Furniture Mod, MrTJPCore, NHAVE's Core, NVL's Force Fields, Natura, Nature's Compass, NoMoreRecipeConflict, OC Glasses, OMLib, OfflineSkins, OnlinePictureFrame, Open Glider, Open Modular Passive Defense, Open Modular Turrets, OpenComputers, OpenComputers (Core), OpenComputers Sensors, OpenPrinter, OreDictInit, OreSpawn, Pam's Cookables, Pam's Get all the Seeds!, Pam's HarvestCraft, Perfect Spawn, Ping, Platforms, PlusTiC, ProjectRed Core, ProjectRed Fabrication, ProjectRed Illumination, ProjectRed Transmission, ProjectRed integration, QuantumStorage, Quark, RFTools, RFTools Power / OC Integration, Reborn Core, Recurrent Complex, Redstone Flux, SG Craft, SensorCraft, Shadowfacts' Forgelin, ShetiPhian-Core, Solar Flux Reborn, Storage Drawers, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thut Core, Thut's Tech, ThutCore Compat, Tinker I/O, Tinker's JEI, Tinkered Hegemony, Tinkers Alloying Addon, Tinkers Construct OpenComputers Driver, Tinkers Tool Leveling, Tinkers' Construct, Tool Progression, Track API, Tree Chopper, UniDict, Unloader, Villager Market, Vivecraft Forge Extensions, Vivecraft Forge Extensions Core, Vulpes library, Waila, WanionLib, What Are We Looking At, Wireless Crafting Terminal 2, WirelessRedstone-CBE, Woot, WrapUp, Zero CORE, Zetta Industries, mojo-redmetal, p455w0rd's Library, projectred-compat

**Issue Description**
       When mounting a boat, everything is seemingly fine, however the server console starts spamming: 
 "Exception occurred during a PhaseState". When moving forward with the boat, I can hear the rowing sound getting fainter (as if the boat was still at the original position, rowing in place) until it is inaudible. After moving forward furthermore, I approach the renderdistance, and the world is not rendering further. When I dismount the boat, the player character appears at the location where I initially mounted the boat, while the boat is where it arrived until dismounting. It seems like the player character is stuck in the mounting place, and the boat is moving wihtout it, although when switching to 3rd person view, everything seems fine. 

 
Providing a latest.log I found from the server logs folder. Near the end of this file, the error message and stacktrace info can be seen.
[latest.log](https://github.com/SpongePowered/SpongeForge/files/2109517/latest.log)

**Comment by phit** [comment]
do not use [api 8 ](https://docs.spongepowered.org/stable/en/server/getting-started/implementations/spongeforge.html#reading-the-download-filename)builds in production, they are unstable, will break your plugins and will quite often miss patches from the main api 7 builds

this specific issue was fixed a while ago on api 7, so please switch to the latest recommended api 7 build
https://www.spongepowered.org/downloads/spongeforge/stable/1.12.2

**Comment by Liiw** [comment]
Hello again!

That was the problem indeed. When I discovered this issue, I had 7.1.0-BETA-3169 installed. Trying to resolve the issue, I downloaded the latest "experimental" build thinking "newer sponge is better sponge". I did not realize there is an API difference. Works fine with 7.1.0-BETA-3171. Thank you for your help!
