### ISSUE TITLE
When right-clicking an Arcane Workbench, error in console

### ISSUE THREAD

**Issue by fcpwiz** [SpongePowered/SpongeForge#2234]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3201.jar 
- Forge version: forge-1.12.2-14.23.4.2705-universal.jar
- Java version: 8 64 bit
- Operating System: Linux

- Plugins/Mods:

Plugins (21): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, Aliases, CatClearLag, Denizen2Sponge, FoxCore, FoxGuard, GriefPrevention, Holograms, LuckPerms, MMCRestrict, MagiBridge, Nucleus, PlaceholderAPI, RankUpper, TabManager, Tattle, VoxelSniper, WorldEdit

Mods (110): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Advanced Generators, Advanced Solar Panels, Applied Energistics 2, Astral Sorcery, AutoRegLib, BD Lib, Baubles, BiblioCraft, Biomes O' Plenty, Blood Magic: Alchemical Wizardry, Botania, Chameleon, ChickenChunks, Chisel, CoFH Core, CoFH World, CodeChicken Lib, CommonCapabilities, Cucumber Library, Cyclops Core, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, EnderStorage, Energy Converters, Exchangers, Extra Cells 2, Extra Utilities 2, Extreme Reactors, Fluxx Stuff, FoamFix, FoamFixCore, Forestry, Forge Microblocks, Forge Multipart CBE, GenDustry, Genetics Reborn, Guide-API, Immersive Engineering, Industrial Foregoing, IndustrialCraft 2, Integrated Dynamics, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTunnels-Compat, Integration Foregoing, Inventory Tweaks, Iron Chest, IvToolkit, Just Enough Items, Mantle, McJtyLib, Mekanism, MekanismGenerators, MekanismTools, Minecraft Multipart Plugin, MrTJPCore, Mystical Agradditions, Mystical Agriculture, OpenBlocks, OpenModsLib, OpenModsLib Core, PlusTiC, ProjectRed Core, ProjectRed Exploration, ProjectRed Fabrication, ProjectRed Illumination, ProjectRed Transmission, ProjectRed integration, Psi, RFTools, Random Things, Recurrent Complex, Redstone Arsenal, Redstone Flux, Shadowfacts' Forgelin, Storage Drawers, TOP Addons, Tesla Core Lib, Tesla Core Lib Registries, Thaumcraft, The One Probe, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Tinkers' Construct, Tree Chopper, UniDict, WanionLib, Zero CORE, projectred-expansion, projectred-relocation, projectred-transportation

**Issue Description**

When a Thaumcraft 6 (beta 16) Arcane Workbench is right-clicked/accessed, the following is printed in the console:

https://gist.github.com/fcpwiz/cb3af7caf35e39b298ccc25b1a9123e2

**Comment by Faithcaio** [comment]
Try again with latest.
But the error does not actually break anything. 
We're just skipping the Grid-Support for that Inventory.
