### ISSUE TITLE
DropItemEvent.Destruct and SpawnEntityEvent are no longer called after breaking a block

### ISSUE THREAD

**Issue by caseif** [SpongePowered/SpongeForge#2236]
As of SpongeForge 3074, `DropItemEvent.Destruct` and `SpawnEntityEvent` are no longer called when an item entity is spawned from a broken block. I suspect that fd599aa3c72cf0b82bf8fec28a07ca9da7473324 is the culprit, although SF 3074 includes multiple commits, so I can't say with certainty as I've only done a bisect on precompiled builds.

**Comment by Yeregorix** [comment]
I'm experiencing the same issue. Using SpongeVanilla 1.12.2-7.1.0-BETA-105 or SpongeForge 1.12.2-2705-7.1.0-BETA-3399 or 1.12.2-2705-8.0.0-BETA-3394  `DropItemEvent.Dispense` is fired instead of `DropItemEvent.Destruct`.

**Comment by ImMorpheus** [comment]
See https://github.com/SpongePowered/SpongeCommon/pull/2062
