### ISSUE TITLE
Server Watchdog/FATAL [net.minecraft.server.dedicated.ServerHangWatchdog]: A single server tick took 60.00 seconds (should be max 0.05)

### ISSUE THREAD

**Issue by tatsudev** [SpongePowered/SpongeForge#2237]
**I am currently running**

- SpongeForge version: 1.12.2-2655-7.1.0-BETA-3065
- Forge version: 1.12.2-14.23.3.2655
- Java version: openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-1~deb9u1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)
- Operating System: Debian 9

start.sh
java -Xmx3G -Xms3G -jar forge-1.12.2-14.23.3.2655-universal.jar -d64

- Plugins/Mods:
Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, FoxCore, FoxGuard, LangSwitch, LuckPerms, Nucleus, Pieconomy, Twenty Ticks, VillagerShops, WorldEdit

Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Aether Legacy, Aquaculture, Biomes O' Plenty, Inventory Pets, IvToolkit, Just Enough Items, Mantle, MrCrayfish's Furniture Mod, Recurrent Complex, Roguelike Dungeons, Tinkers' Construct, Varied Commodities, Waila

**Issue Description**
Sometimes when starting server I have fatal error 60sec tick. It happen on VPS server and even my PC Win7 x64.
Don't change anything, just run it again. At the next starting server startup and working correctly. I copy plugins and mods list and play in minecraft - it now ok.
But next starting it happen again! Maybe I'm doing something wrong?

https://gist.github.com/phit/3141c6f9cceb44831ca7e628d8eeb7d0

**Comment by bloodmc** [comment]
SpongeForge version: 1.12.2-2655-7.1.0-BETA-3065

Over 130 builds old.... Update

**Comment by tatsudev** [comment]
Ohh my head.. Thank I try))
