### ISSUE TITLE
IP forwarding not working

### ISSUE THREAD

**Issue by Luysita** [SpongePowered/SpongeForge#2240]
**I am currently running**

**- SpongeForge version:** spongeforge-1.12.2-2705-7.1.0-BETA-3171
**- Forge version:** forge-1.12.2-14.23.4.2705-universal
**- Java version:** (build 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11)
**- Operating System:** Ubuntu 16.04.4 LTS 

**- Plugins/Mods:**
spongeforge-1.12.2-2705-7.1.0-BETA-3171.jar
BiomesOPlenty-1.12.2-7.0.1.2391-universal.jar
ServerListPlus-3.4.7-Universal.jar
statusprotocol-0.3.jar

**Issue Description**
I am trying to connect my forge server to my vanilla in the same network, but when I try to login to my modpack IP, it says "If you wish to use IP forwarding, please enable it in your Bungeecord config as well!"
I followed your Bungeecord guide, IP forward is enabled in the Bungeecord config, I installed SpongePls and added my modpack as allowed server, online mode in the server.properties are both false and enabled Bungeecord in modules in global.conf.
Not sure what I am missing.

**Modpack properties:** https://pastebin.com/zB0Qtsce
**Sponge config:** https://pastebin.com/aC7M8c85
**Bungeecord config:** https://pastebin.com/y0chF4u3

**Comment by dualspiral** [comment]
Second line in your bungee config `forge_support: false`, set to `true`.

**Comment by Luysita** [comment]
>Second line in your bungee config forge_support: false, set to true.

Worked!! I feel a bit dumb now, sorry! :')
Thank you so much!!!!!!!!!!!
