### ISSUE TITLE
Block-capturing module populates on populate=false

### ISSUE THREAD

**Issue by Rasgnarok** [SpongePowered/SpongeForge#2241]
**I am currently running**

- SpongeForge version: 3206
- Forge version: 2705
- Java version: 8
- Operating System: Centos7

- Plugins/Mods:
![image](https://user-images.githubusercontent.com/18584380/41619535-9a606ed2-73d4-11e8-8ce9-03c1edd66231.png)

**Issue Description**
1) Get a fresh Spongeforge setup with some mod (testing with Pixelmon Reforged 6.3.1). Check the `global.conf` file, where `block-capturing` is set to false.
2) Start up the server for the first time, let everything generate. Log into the game, and logout.
3) Shutdown the server.
4) Block-capturing has now populated a bunch of entries even though populate is off by default.

**Comment by phit** [comment]
will be fixed with https://github.com/SpongePowered/SpongeCommon/pull/1951

**Comment by phit** [comment]
pr was merged
