### ISSUE TITLE
Error from World Unloading during Terrain Generation with Extra Planets

### ISSUE THREAD

**Issue by RussianSanity** [SpongePowered/SpongeForge#2242]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3206
- Forge version: forge-1.12.2-14.23.4.2707-universal.jar
- Java version: 1.8.0_161, Oracle Corporation
- Operating System: Linux (amd64) version 4.9.33-mod-std-ipv6-64

- Plugins/Mods: Tick Profiler, Better Chunkloader, Universeguard, Stackban, Prism, Nucleus, LuckPerms, GriefPrevention, and a custom plugin written by developers of our staff team

**Issue Description**
This is happening with the Sevtech: Ages modpack
Whenever someone is loading chunks on the Extra Planets (this one in particular is Uranus) the console for the server continuously gets spammed with the following error you see in the pastebin links and if left unattended long enough the server eventually hangs up and crashes
It doesn't happen right away when the planet is loaded, it takes about 5 minutes or so before it begins.
This only began happening after the latest update (v3.0.8) to Sevtech. We've tried both recent recommended builds to Sponge and even an experimental build (builds 3169, 3178, and 3206) in hope this would be fixed but it's a no-go so far on that end.

Server Log:  https://gist.github.com/RussianSanity/a02cca2e57393c7b19d35ec423c6abf3 (sponge debug log, other log is too large to view in notepad++ - cut off because pasting the whole thing crashes the site)
Crashlog: https://gist.github.com/RussianSanity/a40ba8614951ba1d54f064cae512c9a6

**Comment by RussianSanity** [comment]
First reported on the Sevtech: Ages modpack github. They referred me to report it here.
Original Report [(HERE)](https://github.com/DarkPacks/SevTech-Ages/issues/2927)

**Comment by gabizou** [comment]
@RussianSanity Try SF 3211 (it's in progress of building based on that commit). 

It's uploaded now.

**Comment by RussianSanity** [comment]
Okay, will try now.

**Comment by gabizou** [comment]
@RussianSanity Also, the crash may still happen, but if it does, please re-paste the new crashlog.

**Comment by RussianSanity** [comment]
Welp I flew around Uranus for around 13 minutes, randomly /rtping here and there and it seems to be fine. No server crash at all. When the player who was making it crash before gets on I'll have them try it themselves and see the result. 

If anything changes I'll post it here. Thank you for fixing it (as far as we know lol)!

**Comment by gabizou** [comment]
I wrote more of a workaround for now which will avoid any errors, 3212 has the added null check to avoid this error, but it doesn't properly fix the issue. I'll investigate further at some point.

**Comment by gabizou** [comment]
@Zidane can you look into this potentially? It's weird that the world unload was occurring from normal areas when another world was generating chunks.

**Comment by gabizou** [comment]
@RussianSanity any noticeable differences? Any extra bugs potentially caused by my changes? If not, the workaround is pretty much silent and avoids the world unload events I'm supposing from someplace else than sponge's dimension management.
