### ISSUE TITLE
Sponges crashes on server start up

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#2243]
**I am currently running**

- SpongeForge version: Latest 
- Forge version:  2705
- Java version: 8
- Operating System: 10

- Plugins/Mods:

**Issue Description**
https://gist.github.com/SacrificialFlame/578d6fe4333077c10b94599e8a77e5f5

**Comment by phit** [comment]
https://github.com/DimensionalDevelopment/JustEnoughIDs/issues/1
