### ISSUE TITLE
Dynmap doesn't work

### ISSUE THREAD

**Issue by Luysita** [SpongePowered/SpongeForge#2246]
**I am currently running**

**- SpongeForge version:** spongeforge-1.12.2-2705-7.1.0-BETA-3171
**- Forge version:** forge-1.12.2-14.23.4.2705-universal
**- Java version:** (build 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11)
**- Operating System:** Ubuntu 16.04.4 LTS 

**- Plugins/Mods:**
spongeforge-1.12.2-2705-7.1.0-BETA-3171.jar
BiomesOPlenty-1.12.2-7.0.1.2391-universal.jar
ServerListPlus-3.4.7-Universal.jar
Dynmap-Nucleus-0.3-S7.0.jar
multichat-1.5.jar
Nucleus-1.4.3-S7.0-MC1.12.2-plugin.jar
statusprotocol-0.3.jar

**Issue Description**
I'm trying to install Dynmap in my server but somehow is not working.
Could anyone help me please? Thanks

crash-report: https://pastebin.com/56bg2Fms

**Comment by dualspiral** [comment]
> net.minecraftforge.fml.common.MissingModsException: Mod dynmap-nucleus (Dynmap-Nucleus) requires [dynmap]

You need to install the dynmap mod on your server, you've only installed the Dynmap/Nucleus bridge.

Please note that Github is not the best place for support. You will find much better support on:

* The Sponge forums: https://forums.spongepowered.org/
* IRC: #sponge on irc.esper.net
* Discord: https://discord.gg/PtaGRAs
