### ISSUE TITLE
Sponge breaks Forge LivingEntityUseItemEvent

### ISSUE THREAD

**Issue by JoeSGT** [SpongePowered/SpongeForge#2247]
**I am currently running**

- SpongeForge version: 7.1.0-BETA-3214
- Forge version: 14.23.4.2705
- Java version:  8
- Operating System: windows 

- Plugins/Mods:
https://gyazo.com/52bf997c900b0a7f0cba4bb2acff30bb

**Issue Description**
After a lot of testing to find what commit broke 
immersive engineering mod an item called "Chemical Thrower" it is an item that let you shoots various fluids. I used  Fluid Transposer  from thermal expansions mod for an quick easy way to transfer fluids into the Chemical Thrower, once i installed the latest SpongeForge and recommended this item doesn't shoot out anything then i went back to see what build number of spongeforge it was working on it was working on `spongeforge-1.12.2-2705-7.1.0-BETA-3188` and broke in `spongeforge-1.12.2-2705-7.1.0-BETA-3189 and up ` I highly believe this commit https://github.com/SpongePowered/SpongeForge/commit/5a158fd166c418c8b1266edfdf97aafa41cd0e56 broke the way Forge `LivingEntityUseItemEvent` works

**Comment by Aaron1011** [comment]
This will be fixed in the next SpongeForge build.

@JoeSGT: For future reference, please include detailed reproduction instructions whenever mod items are involved. I had to fiddle around with Immersive Engineering for a while to figure out how to actually use the Chemical Thrower.

**Comment by JoeSGT** [comment]
i will next time sorry, also it seem the commit broke startup https://pastebin.com/raw/vuCAf7mp
@Aaron1011

**Comment by Aaron1011** [comment]
@JoeSGT: My bad - I forgot to actually bump the SpongeCommon ref in my commit. The next build should fix that.
