### ISSUE TITLE
UnsupportedOperationException when pressing Shift-F3

### ISSUE THREAD

**Issue by LemADEC** [SpongePowered/SpongeForge#2250]
**I am currently running**
- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3218
- Forge version: 14.23.4.2708
- Java version: 1.8.0_162
- Operating System: Windows 10

- Plugins/Mods:
None, just Forge + SpongeForge

**Issue Description**
Create new world > press shift-F3 > crash
https://gist.github.com/LemADEC/a653d7e46668d3b376acefbf1c565b10

**Comment by phit** [comment]
https://github.com/SpongePowered/SpongeCommon/issues/1726#issuecomment-364620972
