### ISSUE TITLE
The main thread is again stuck with a different error

### ISSUE THREAD

**Issue by luenlin** [SpongePowered/SpongeForge#2251]
Crash report: https://paste.feed-the-beast.com/view/12a1de88

**Comment by Aaron1011** [comment]
@luenlin: Can you see if https://paste.feed-the-beast.com/ is unblocked for you?

**Comment by luenlin** [comment]
@Aaron1011 yes Sir https://paste.feed-the-beast.com/view/12a1de88

**Comment by Aaron1011** [comment]
@luenlin: Thanks!

**Comment by luenlin** [comment]
@Aaron1011  I should thank you for that.

**Comment by phit** [comment]
looks like a Luckperms issue if anything, nothing for Sponge to do here
