### ISSUE TITLE
infinite slowness and mining fatigue from unknown origin

### ISSUE THREAD

**Issue by IronworksProductions** [SpongePowered/SpongeForge#2253]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3206.jar
- Forge version: 2705
- Java version: 1.8
- Operating System:ubuntu

- Plugins/Mods:_..x_SecurityCraftv.jar

actuallyadditions.jar
actuallybaubles.jar
advancedRocketry.jar
adventurepack.jar
akashictome.jar
appleskin.jar
aroma1997core.jar
aroma1997sdimension.jar
astralsorcery.jar
autoreglib.jar
Avaritia.jar
avaritiatweaks.jar
badwithernocookiereloaded.jar
base.jar
baubles.jar
bdlib.jar
bedpatch.jar
betterbuilderswands.jar
BetterFps.jar
betterquesting.jar
bigreactors.jar
binniecore.jar
blockcraftery.jar
bloodmagic.jar
bookshelf.jar
botania.jar
bq_standard.jar
brandonscore.jar
buildcraftlib.jar
ceramics.jar
chameleon.jar
chancecubes.jar
chisel.jar
clib.jar
clumps.jar
codechickenlib.jar
cofhcore.jar
cofhworld.jar
commoncapabilities.jar
computercraft.jar
controlling.jar
craftingtweaks.jar
crafttweaker.jar
csb_ench_table.jar
ctm.jar
cucumber.jar
custommainmenu.jar
cyclopscore.jar
Dalek Mod
danknull.jar
darkutils.jar
defaultoptions.jar
diethopper.jar
discordsuite.jar
dismantler.jar
draconicevolution.jar
elevatorid.jar
elulib.jar
endercore.jar
enderio.jar
enderstorage.jar
endertanks.jar
environmentaltech.jar
etlunar.jar
ExtraRails.jar
extrautils2.jar
fastbench.jar
fluxnetworks.jar
flyringbaublemod.jar
foamfix.jar
forestry.jar
forgelin.jar
ftblib.jar
ftbutilities.jar
fw.jar
gendustry.jar
guideapi.jar
hammercore.jar
Harvest.jar
ic2.jar
ICBM-classic-..-..b.jar
ImmersiveEngineering-.--core.jar
immersiveengineering.jar
immersivepetroleum.jar
industrialwires.jar
integrateddynamics.jar
integratedtunnels.jar
InvTweaks.jar
ironbackpacks.jar
ironchest.jar
itemscroller.jar
itlt.jar
jei.jar
jeibees.jar
jeiintegration.jar
jeresources.jar
journeymap.jar
libVulpes.jar
llor.jar
mantle.jar
matteroverdrive.jar
mcjtylib_ng.jar
MCMultiPart.jar
mekanism.jar
mekanismgenerators.jar
mekanismtools.jar
minebot-mod.jar
morpheus.jar
morphtool.jar
mtlib.jar
mysticalagradditions.jar
mysticalagriculture.jar
natura.jar
neid.jar
netherportalfix.jar
nmsot.jar
nuclearcraft.jar
oeintegration.jar
omlib.jar
ompd.jar
openblocks.jar
opencomputers.jar
openglider.jar
openmods.jar
openmodularturrets.jar
OptiFine_1.12.2_HD_U_D3.jar
oreexcavation.jar
placebo.jar
practicallogistics2.jar
projecte.jar
pwrdslib.jar
questbook.jar
quickleafdecay.jar
randompatches.jar
randomthings.jar
randomtweaks.jar
rangedpumps.jar
reauth.jar
reborncore.jar
rebornstorage.jar
redstoneflux.jar
refined_avaritia.jar
refinedstorage.jar
refinedstorageaddons.jar
resourceloader.jar
rftools.jar
rftoolscontrol.jar
rftoolsdim.jar
rftoolspower.jar
SBM-WoodenShears-.-..b.jar
secretroomsmod.jar
SGCraft.jar
sgextraparts.jar
shadowmc.jar
shetiphiancore.jar
silentgems.jar
SilentLib.jar
simplebedrolls.jar
simplyconveyors.jar
solarfluxreborn.jar
sonarcore.jar
soulshardstow.jar
stevescarts.jar
stg.jar
storagedrawers.jar
tconstruct.jar
thaumcraft.jar
thedalekmod.jar
thermalcultivation.jar
thermaldynamics.jar
thermalexpansion.jar
thermalfoundation.jar
TinkersAddons.jar
tinkertoolleveling.jar
toastcontrol.jar
tombmanygraves.jar
torchmaster.jar
traverse.jar
twilightforest.jar
valkyrielib.jar
waila.jar
WAIM.jar
worldedit.jar
zerocore.jar
Eagle Factions, FoxCore, FoxGuard, HuskyCrates, HuskyUI, LuckPerms, NuVotifier, Nucleus, ProjectCore, ProjectInventories, ProjectWorlds, SeriousVote, XtraPunish

**Issue Description**
After a little time of playing in a new world generated by the mutiworld system any survival players are hit with infinite mining fatigue and slowness with no discernible reason on to why it is applied.

https://gist.github.com/nacjm/a850588c291fe3e6af20be54f0449c6e

**Comment by phit** [comment]
Not really our place to debug your modlist to figure out what mod is doing so. When you figure out that its somehow only happens with Sponge. feel free to add a reproduction and I'll be happy to reopen the issue.

**Comment by IronworksProductions** [comment]
Ok the modpack plays fine in singleplayer its as soon as it enters the server that it does this. and since its giving a level of mining fatigue that prevents you from even mining dirt i suspect it is spawn protection gone awry. but thats for you to figure out.

**Comment by IronworksProductions** [comment]
I updated the issue with what i did to cause the error it is sponge since its multi world only the world i generated with the multiworld system ahas this happen inside.

**Comment by gabizou** [comment]
> but thats for you to figure out.

We're here to fix bugs with our software, we're not here to prune a modlist of 100+ mods and spongeforge to figure out where the issue is coming from. You'll need to provide us with step by step reproduction instructions to even start helping us help to fix the problem since I have no understanding of your second comment is going on about:



> I updated the issue with what i did to cause the error it is sponge since its multi world only the world i generated with the multiworld system ahas this happen inside.

There's no error in the log that points to potion effects or anything like that. And your comment about "since it's multiword" means nothing to me, is this is a custom world? How did you make it? What mod is creating that extra dimension? Is it another dimension that this happens? Does it ever happen on the overworld? 


All of these are questions we need answered so we can start helping to fix the potential problem(s).

**Comment by ryantheleach** [comment]
One extremely quick test you can do to work out if it's even remotely related to sponge, is to disable SpongeForge and see if the issue persists.

If the issue persists without SpongeForge, It can't possibly be a bug with our software.

If you are using a modpack, and that modpack has a support channel / forum / comments / discord, ask them, there will be many others with your exact setup that may be able to tell you more clearly what the issue is.

**Comment by IronworksProductions** [comment]
Yeah I just removed spongeforge and the issue vanished. before i did that i removed project world and it did not go away. I wish I could go to a support channel but this is MY custom modpack I designed it.
if you want to reproduce it i can give  you my launcher that auto downloads the mods then all you need to do is setup a sponge server with a multiworld plugin and create a world. eventually this error will appear after paying on that server for a bit. and im not the only one to have this problem i just was the first one to go here and not project world, as shown here, https://github.com/trentech/ProjectWorlds/issues/85

**Comment by ryantheleach** [comment]
The issue you linked doesn't relate to "infinite slowness and mining fatigue" and is specifically talking about ["Adventure Mode"](https://minecraft.gamepedia.com/Adventure)

**Comment by IronworksProductions** [comment]
that is what it actually is.

**Comment by IronworksProductions** [comment]
can't even break dirt
probably should have edited that last comment but oh well
