### ISSUE TITLE
Specify an updateJSON URL in our mcmod.info

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/SpongeForge#2260]
Forge has [a built-in update checker](https://github.com/MinecraftForge/MinecraftForge/blob/d09a8d98d7eefe9f2d1120f9d777873b5918b042/src/main/java/net/minecraftforge/fml/common/Mod.java#L247) that checks a mod-provided URL on startup. It would be nice if Sponge opted into this system, which would allow Sponge update notifications to be shown to users.

This would require [DownloadIndexer](https://github.com/SpongePowered/DownloadIndexer) to handle the update check endpoint.

**Comment by phit** [comment]
see https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
for the format

**Comment by kashike** [comment]
https://files.minecraftforge.net/maven/org/spongepowered/spongeforge/promotions_slim.json
