### ISSUE TITLE
Migrating Old World Using SpongeForge

### ISSUE THREAD

**Issue by JanSponge** [SpongePowered/SpongeForge#2263]
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3206
- Forge version: forge-1.12.2-14.23.4.2705-universal
- Java version: Java 8
- Operating System: 64-bit

- Plugins/Mods: 
    - PixelmonGenerations-1.12.2-2.1.0-universal
    - spongeforge-1.12.2-2705-7.1.0-BETA-3206

**Issue Description:**
I am trying to migrate a 1.7.10 world from an old server to 1.12.2. My friend told me I had to run the world on a server of each major update until I reached 1.12.2. It worked. The server ran with the old world. But now whenever I add SpongeForge, it gives me the error that I would USUALLY get if I didn't pass the world through every major update and just put it straight from 1.7.10 and 1.12.2. This can not be the world's fault because if not it wouldn't run at all in 1.12.2.

**Crash Log:**
https://pastebin.com/gW0EPX1j

**Comment by Dockter** [comment]
Be advised this person pinged several members of the community already on this matter.  I personally told him that the error being received wasn't indicative of the actual issue.  

I'm not sure what part of, "You can't easily just move a 1.7.10 world to 1.12.2 with Mods and expect it to work everytime" wasn't clear.

**Comment by Dockter** [comment]
I researched this issue.  This isn't a sponge issue its a "World was generated under 1.6.4" issue and the level.dat file has some old FML entries.

Not a sponge issue.

**Comment by Dockter** [comment]
From FMLContainer.java:

 if (tag.hasKey("ModItemData") || tag.hasKey("ItemData")) // Pre 1.7
        {
        StartupQuery.notify("This save predates 1.7.10, it can no longer be loaded here. Please load in 1.7.10 or 1.8 first");
        StartupQuery.abort();
        }

**Comment by bloodmc** [comment]
@Dockter Thanks!
