### ISSUE TITLE
Dupe bug with wrenches

### ISSUE THREAD

**Issue by Sir-Will** [SpongePowered/SpongeForge#2264]
If you shift right click a tile entity while the tile is protected by a protection plugin like GP then it drops the tile and keeps it in the world causing it to duplicate.

spongeforge-1.12.2-2705-7.1.0-BETA-3247
griefprevention-1.12.2-4.3.0.633
ThermalExpansion-1.12.2-5.5.0.29-universal

**Comment by phit** [comment]
https://github.com/CoFH/ThermalExpansion/blob/fa83d130881e14bcbf20434f9bc481b7eb50f9df/src/main/java/cofh/thermalexpansion/block/BlockTEBase.java#L69

**Comment by gabizou** [comment]
Why would this be a sponge problem? The block is already checking an event, and sponge is properly delegating that event to plugins, so I don't see the problem to do with sponge but more so with grief prevention.

**Comment by Sir-Will** [comment]
blood told me to report this here: https://github.com/MinecraftPortCentral/GriefPrevention/issues/664#issuecomment-401636559
