### ISSUE TITLE
NPE with ftblib/ftbu

### ISSUE THREAD

**Issue by wormzjl** [SpongePowered/SpongeForge#2267]
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3243
- Forge version: forge-1.12.2-14.23.4.2725-universal
- Java version: 1.8.0_144
- Operating System: linux

- Plugins/Mods:
 Mods (260): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AE2 Stuff, AI Improvements, ATM Tweaks, Actually Additions, Actually Baubles, Additional Banners, Advanced Generators, Advanced Rocketry, Akashic Tome, AngelRing 2 Bauble, AppleCore, AppleSkin, Applied Energistics 2, Armory Expansion, Aroma1997's Dimensional World, Aroma1997Core, Astral Sorcery, AutoRegLib, Autoverse, BD Lib, Bad Wither No Cookie! Reloaded, Baubles, Bed Patch, Better Builder's Wands, BiblioCraft, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Biomes O' Plenty, Blockcraftery, Bookshelf, Botania, Brandon's Core, Ceramics, Chameleon, Chisel, Chisels & Bits, CoFH Core, CoFH World, CodeChicken Lib, Colossal Chests, CommonCapabilities, Compact Machines 3, ComputerCraft, Computronics, Construct's Armory, CosmeticArmorReworked, CraftTweaker JEI Support, CraftTweaker2, Crafting Tweaks, Cucumber Library, Cyclic, Cyclops Core, Dark Utilities, Default World Generator, Diet Hopper, Dismantler, Doomlike Dungeons, Draconic Evolution, EXCore, EluCore, EluLib, Embers, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, EnderStorage, Environmental Tech, Extra Cells 2, Extra Rails, Extra Utilities 2, Extreme Reactors, FTB Utilities, FTBLib, Fairy Lights, FastWorkbench, Fence Jumper, Flat Colored Blocks, FoamFix, FoamFixCore, Forestry, Forge Microblocks, Forge Multipart CBE, Funky Locomotion, GenDustry, Gotta Go Fast, Guide-API, Guidebook, Harvest, HelpFixer, Immersive Engineering, Immersive Petroleum, Industrial Foregoing, Industrial Wires, IndustrialCraft 2, InitialInventory, Integrated Dynamics, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTunnels-Compat, Integration Foregoing, Inventory Generators, Inventory Tweaks, Iron Backpacks, Iron Chest, JAOPCA, Just A Ore Processing Compatibility Attempt: Additions, Just Enough Dimensions, Just Enough Items, KJ Lib, KleeSlabs, LibrarianLib, LibrarianLib Stage 2, Lost Souls, MCMultiPart, MTLib, MagicBees, Magical Psi, Mantle, McJtyLib, Mekanism, MekanismGenerators, MekanismTools, MineColonies, Minecraft Multipart Plugin, Mob Totems, Mod Tweaker, Morph-o-Tool, Morpheus, MrTJPCore, Mystical Agradditions, Mystical Agriculture, Natura, Nature's Compass, No Mob Spawning on Trees, Not Enough Items, Not Enough Wands, NotEnoughIDs, NuclearCraft, Nutrition, OpenBlocks, OpenComputers, OpenComputers (Core), OpenComputers Xnet Driver, OpenModsLib, OpenModsLib Core, OreDictInit, OreExcavation, OreExcavation Integration, Overloaded, PackMode, Placebo, Platforms, PlusTiC, PneumaticCraft: Repressurized, PortalGun, Portality, Practical Logistics 2, Pressure Pipes, ProjectRed Core, ProjectRed Expansion, ProjectRed Exploration, ProjectRed Fabrication, ProjectRed Illumination, ProjectRed Relocation, ProjectRed Transmission, ProjectRed Transportation, ProjectRed integration, Psi, QuantumStorage, Quark, Quick Leaf Decay, RFTools, RFTools Control, RFTools Dimensions, RFToolsPower, RandomPatches, Ranged Pumps, Real Filing Cabinet, Reborn Core, RebornStorage, Redstone Arsenal, Redstone Flux, Refined Storage, Refined Storage Addons, Reliquary, Rockhounding Mod: Chemistry, Rockhounding Mod: Core, Roots 2, Rustic, ShadowMC, Shadowfacts' Forgelin, ShetiPhian-Core, Shield Parrying, Simply Jetpacks 2, SlimyBoyos, SonarCore, Soul Shards - The Old Ways, Steve's Carts 2, Storage Drawers, Storage Drawers Extras, TOP Addons, Tech Reborn, Tesla Core Lib, Tesla Core Lib Registries, Thaumcrafft Inventory Scanning, Thaumcraft, The Lost Cities, The One Probe, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Tinker I/O, Tinkers Tool Leveling, Tinkers' Construct, Tomb Many Graves, TombManyGraves2 API, Traverse, UniDict, Universal Modifiers, Useful Nullifiers, Valkyrie Lib, Vulpes library, WAIM, WanionLib, Water Strainer, Waystones, Wireless Crafting Terminal 2, WirelessCharger, Woot, WrapUp, XNet, Xtones, YNot, Zero CORE, asielib, careerbees, iChunUtil, p455w0rd's Library, projectred-compat

Plugins (13): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge,  FastAsyncWorldEdit, AdamantineShield, Holograms, MagiBridge, Nucleus, Nucleus Gluon, PlaceholderAPI, WorldEdit, spark

**Issue Description**
Not sure how it has happened but I find this in my crash logs

https://gist.github.com/wormzjl/658d21a5c9ce2ea606e0bf5c1fd55394

**Comment by phit** [comment]
FTBU issue, please report it on their issue tracker

**Comment by wormzjl** [comment]
This issue only happen with sponge installed.
Before removing sponge, some player names in chat are show as "BrokenFormatting"
After removing sponge, player names are shown as normal and claiming chunks is no longer crashing.
@phit Can you reopen this issue?

**Comment by phit** [comment]
https://github.com/LatvianModder/FTBUtilities/issues/796

**Comment by phit** [comment]
was fixed by ftbu at some point
