### ISSUE TITLE
Exception generating new chunk.

### ISSUE THREAD

**Issue by realLevTheDev** [SpongePowered/SpongeForge#2270]
The problem occurs when players on my Sky Factory 3 server enter the Nether. I think the way minecraft and sponge generate terrain are conflicting but I have no idea. I have tried to reset the nether but it seems to continue despite my efforts.
Sponge Version: spongeforge-1.10.2-2477-5.2.0-BETA-2793
Crash Report: [https://pastebin.com/inTF1y58](https://pastebin.com/inTF1y58)

**Comment by limbo-app** [comment]
Hey @PreferableFlavor! You seem to be running an unsupported version (1.10) of SpongeForge. Support for 1.10 ended in January 2018.

If you can reproduce this issue with Minecraft 1.12.2, please [open a new issue](https://github.com/User{login=SpongePowered}/SpongeForge/issues/new) with updated information.

**Comment by phit** [comment]
@PreferableFlavor downgrade to spongeforge-1.10.2-2477-5.2.0-BETA-2788
