### ISSUE TITLE
Server Stuck in Exception Loop

### ISSUE THREAD

**Issue by CreeperFace00** [SpongePowered/SpongeForge#2272]
- SpongeForge version: SpongeForge : 1.12.2-2705-7.1.0-BETA-3206 (Same result on recommended build)
- Forge version: 14.23.4.2705 
- Java version: 1.8.0_60 (Server)
- Operating System: Linux (amd64) version 3.14.32-xxxx-grs-ipv6-64 (Server)

- Plugins/Mods:  mcp, FML, forge, otgcore, randompatches, spongeapi, sponge, openmodscore, foamfixcore, opencomputers|core, albedocore, actuallyadditions, advanced_solar_panels, ae2stuff, appleskin, appliedenergistics2, armorplus, aroma1997core, aroma1997sdimension, aromabackup, aromabackuprecovery, autoreglib, avaritia, base, baubles, bdlib, betterbuilderswands, betterrecords, bibliocraft, biomesoplenty, bloodmagic, bookshelf, botania, brandonscore, buildcraftbuilders, buildcraftcore, buildcraftlib, rf-capability-adapter, chickenchunks, chisel, clef, clumps, codechickenlib, cofhcore, cofhworld, compactmachines3, computercraft, crafttweaker, crafttweakerjei, cucumber, danknull, darkutils, draconicevolution, elevatorid, endercore, enderio, enderiobase, enderioconduits, enderioconduitsappliedenergistics, enderioconduitsopencomputers, enderioconduitsrefinedstorage, enderiointegrationforestry, enderiointegrationtic, enderiointegrationticlate, enderiomachines, enderiopowertools, enderstorage, environmentaltech, equivalentenergistics, expequiv, extracells, extrautils2, bigreactors, foamfix, forgelin, microblockcbe, forgemultipartcbe, minecraftmultipartcbe, ftblib, advgenerators, gravestone, griefprevention, guideapi, hammercore, hats, waila, icbmclassic, ichunutil, ic2, inventorytweaks, iplog, ironbackpacks, ironchest, jei, landcore, landcraft, lttweaker, luckperms, magibridge, mantle, mcef, mcjtylib_ng, mekanism, mmclogger, modtweaker, morph, mrtjpcore, mtlib, mysticalagradditions, mysticalagriculture, natura, neid, nucleus, openblocks, opencomputers, openfm, openmods, openterraingenerator, p455w0rdslib, harvestcraft, plustic, portalgun, projecte, projectred-core, projectred-compat, projectred-fabrication, projectred-integration, projectred-transmission, projectred-illumination, projectred-expansion, projectred-relocation, projectred-transportation, projectred-exploration, psi, quantumstorage, randomthings, rangedpumps, reborncore, redstonearsenal, redstoneflux, refinedstorage, refinedstorageaddons, xreliquary, rftools, rftoolscontrol, rftoolsdim, roguelike, spark, sync, tconstruct, teslacorelib, teslacorelib_registries, thaumcraft, tcinventoryscan, thedragonlib, theoneprobe, thermalcultivation, thermaldynamics, thermalexpansion, thermalfoundation, thermalinnovation, tickprofiler, tinker_io, tinkertoolleveling, translocators, twilightforest, unidict, valkyriecompat, universalmodifiers, valkyrielib, veinminer, veinminermodsupport, wanionlib, wawla, webdisplays, wct, worldedit, wrcbe, zerocore, immersiveengineering

**Issue Description**
This issue started randomly a few days ago, up until that point everything was running fine with no issues.  The problem is pretty simple, I start the server and after it loads the world it immediately goes into a loop spamming the log with this error `"The PhaseState having an exception: TileEntityTickPhase"`  The server was in this state for about an hour and by the time I shut it down the latest.log file reached 78GB.  I have tried all the latest versions of SpongForge, but all have the same issue (Yes, the server runs fine as long as SpongeForge is disabled)  When connecting to the server users are disconnected with the error "Internal Server Error"

Log: [Latest.log](https://gist.github.com/CreeperFace00/ccbb6538af3695270d82afa0f8c2e615#file-sponge-log-txt-L6362) The messages start at line 6343

**Comment by phit** [comment]
is still still an issue on latest?

**Comment by bloodmc** [comment]
This has already been fixed in latest.
