### ISSUE TITLE
Instantly crashing client

### ISSUE THREAD

**Issue by Starshak3r** [SpongePowered/SpongeForge#2279]
**I am currently running** 1.12.2

- SpongeForge version: I have no clue, ask the guys at Minecolonies Mod
- Forge version: 14.23.4.2729
- Java version: 
- Operating System: W10 x64

- Plugins/Mods: Minecolonies Official Modpack 

**Issue Description**
Open client, client crashes immediately

[2018-07-07-5.log.gz](https://github.com/SpongePowered/SpongeForge/files/2172845/2018-07-07-5.log.gz)

**Comment by gabizou** [comment]
This is a MalisisCore mixin issue. SpongeForge isn't even installed on the client according to your logs.

Not to mention that MalisisCore is shipping an older Mixin version from last year, there have been many bug fixes since with Mixins specifically.

**Comment by Starshak3r** [comment]
I was told that it was a sponge issue by the mod team
so I have no clue, sorry
