### ISSUE TITLE
Startup crash with no mods on latest build

### ISSUE THREAD

**Issue by wormzjl** [SpongePowered/SpongeForge#2280]
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3272
- Forge version:  2705
- Java version: 8
- Operating System: win7

- Plugins/Mods:
none

**Issue Description**
https://gist.github.com/wormzjl/911fcce30d21c813cc0a9615b9704267

**Comment by alicheek** [comment]
Got this crash too with the most recent update regarding the advancements using the sevtech modpack  for my example

**Comment by kashike** [comment]
https://github.com/SpongePowered/SpongeCommon/issues/1981

**Comment by 3TUSK** [comment]
Issue still persists with `spongeforge-1.12.2-2705-8.0.0-BETA-3273.jar`, the newest build I can find on Sponge website at the time I am writing this. Setup:

  - SponegForge 1.12.2-2705-8.0.0-BETA-3273
  - Forge 1.12.2-14.23.4.2732
  - Java
  ```
  $ java -version
  java version "1.8.0_144"
  Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
  Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
  ```
  - macOS High Sierra 10.13.5
  - Mod/plugin list https://paste.ubuntu.com/p/SnqvVdmjN9/

Server cannot start, and will exit with this crash report left: https://paste.ubuntu.com/p/GhyKPXPqsk/

<details>
<summary>SHA256 of the spongeforge artifact I am using, just in case.</summary>

````
$ shasum -a 256 mods/spongeforge-1.12.2-2705-8.0.0-BETA-3273.jar 
80b14c451ca7b97ad7e29e0a9f4c9df4756865e265acf5d9e3cc3c33503ded12  mods/spongeforge-1.12.2-2705-8.0.0-BETA-3273.jar
````
</details>

**Comment by RedNesto** [comment]
@3TUSK The website download list may not be up to date, but [this one is](http://files.minecraftforge.net/spongepowered), and the latest (`3291`) loads fine for me.

**Comment by 3TUSK** [comment]
@RedNesto Thanks for the info. ~~However I think Sponge website acts a bit wonky - I can find the build `#3291` in the stable but not the experimental...~~ (that experimental branch is for 8.0.0... I probably need more sleep.) Anyhow, will update my mods folder right now.
