### ISSUE TITLE
Feature request // offline inventory enderchest 

### ISSUE THREAD

**Issue by 02Miki** [SpongePowered/SpongeForge#2281]
Idk if this is the right section, couldn’t create a new ticket in pull requests; can you add offline inventories for enderchest, like the same thing you did with player inventories

**Comment by phit** [comment]
~move to sc

**Comment by limbo-app** [comment]
Hey @02Miki! I've moved your issue to [SpongePowered/SpongeCommon#2018](https://github.com/SpongePowered/SpongeCommon/issues/2018).
