### ISSUE TITLE
DragonPhase Failed to process all PhaseContext captured

### ISSUE THREAD

**Issue by phit** [SpongePowered/SpongeForge#2282]
**I am currently running**

- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3265 
- Forge version: 2705

- Plugins/Mods: https://gist.github.com/phit/9dfc2a7f6a08b065c976c2b76a1165c3#file-gistfile2-txt

**Issue Description**
https://gist.github.com/phit/9dfc2a7f6a08b065c976c2b76a1165c3

**Comment by Aaron1011** [comment]
@gabizou Do we want to be doing bulk captures for `GeneralDragonPhaseState`?

**Comment by gabizou** [comment]
Depending, Dragons are very finicky... I'd say no.

**Comment by xxlio109** [comment]
Similar
SpongeForge version: 1.12.2-2705-7.1.0-BETA-3270
Forge version: 2705
Plugins/Mods: https://gist.github.com/xxlio109/c385e6b8c00ae4feb607ba777cb56ded

Issue Description
https://gist.github.com/xxlio109/e66952ad206c1c49a13fb366c617b02d

**Comment by phit** [comment]
still happens on 3748 https://pastebin.com/raw/5NbzBQ03

**Comment by Zidane** [comment]
This should be fixed now with latest stable-7.

**Comment by Shybella** [comment]
Confirmed Fixed
