### ISSUE TITLE
Failed to process all PhaseContext log spams

### ISSUE THREAD

**Issue by wormzjl** [SpongePowered/SpongeForge#2284]
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3270
- Forge version: 2705
- Java version: J8 171
- Operating System: linux

- Plugins/Mods:
Mods (255): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AE2 Stuff, AI Improvements, ATM Tweaks, Actually Additions, Actually Baubles, Additional Banners, Advanced Generators, Advanced Rocketry, Akashic Tome, AngelRing 2 Bauble, AppleCore, AppleSkin, Applied Energistics 2, Armory Expansion, Aroma1997's Dimensional World, Aroma1997Core, Astral Sorcery, AutoRegLib, Autoverse, BD Lib, Bad Wither No Cookie! Reloaded, Baubles, Bed Patch, Better Builder's Wands, BiblioCraft, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Biomes O' Plenty, Blockcraftery, Bookshelf, Botania, Brandon's Core, Ceramics, Chameleon, Charcoal Pit, Chisel, Chisels & Bits, Chunk Pregenerator, CoFH Core, CoFH World, CodeChicken Lib, Colossal Chests, CommonCapabilities, Compact Machines 3, ComputerCraft, Computronics, Construct's Armory, CosmeticArmorReworked, CraftTweaker JEI Support, CraftTweaker2, Crafting Tweaks, Cucumber Library, Cyclic, Cyclops Core, Dark Utilities, Default World Generator, Despawning Spawners, Diet Hopper, Dismantler, Doomlike Dungeons, Draconic Evolution, EXCore, EluCore, EluLib, Embers, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, EnderStorage, Environmental Tech, Extra Cells 2, Extra Rails, Extra Utilities 2, Extreme Reactors, FTB Utilities, FTBLib, Fairy Lights, FastWorkbench, Fence Jumper, Flat Colored Blocks, FoamFix, FoamFixCore, Forestry, Forge Microblocks, Forge Multipart CBE, Funky Locomotion, GenDustry, Gotta Go Fast, Guide-API, Guidebook, Harvest, HelpFixer, Immersive Engineering, Immersive Petroleum, Industrial Foregoing, Industrial Wires, IndustrialCraft 2, InitialInventory, Integrated Dynamics, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTunnels-Compat, Integration Foregoing, Inventory Generators, Inventory Tweaks, Iron Backpacks, Iron Chest, JAOPCA, Just A Ore Processing Compatibility Attempt: Additions, Just Enough Dimensions, Just Enough Items, KJ Lib, KleeSlabs, LibrarianLib, LibrarianLib Stage 2, MCMultiPart, MTLib, MagicBees, Magical Psi, Mantle, McJtyLib, Mekanism, MekanismGenerators, MekanismTools, MineColonies, Minecraft Multipart Plugin, Mob Totems, Mod Tweaker, Morph-o-Tool, Morpheus, MrTJPCore, Mystical Agradditions, Mystical Agriculture, Natura, Nature's Compass, No Mob Spawning on Trees, Not Enough Items, Not Enough Wands, NotEnoughIDs, NuclearCraft, OpenBlocks, OpenComputers, OpenComputers (Core), OpenComputers Xnet Driver, OpenModsLib, OpenModsLib Core, OreDictInit, Overloaded, PackMode, Placebo, Platforms, PlusTiC, PneumaticCraft: Repressurized, PortalGun, Portality, Practical Logistics 2, Pressure Pipes, ProjectRed Core, ProjectRed Expansion, ProjectRed Exploration, ProjectRed Fabrication, ProjectRed Illumination, ProjectRed Relocation, ProjectRed Transmission, ProjectRed Transportation, ProjectRed integration, Psi, QuantumStorage, Quark, Quick Leaf Decay, RFTools, RFTools Control, RFTools Dimensions, RFToolsPower, RandomPatches, Ranged Pumps, Real Filing Cabinet, Reborn Core, Redstone Arsenal, Redstone Flux, Reliquary, Rockhounding Mod: Chemistry, Rockhounding Mod: Core, Roots 2, Rustic, ShadowMC, Shadowfacts' Forgelin, ShetiPhian-Core, Shield Parrying, Simply Jetpacks 2, SlimyBoyos, SonarCore, Soul Shards - The Old Ways, Steve's Carts 2, Storage Drawers, Storage Drawers Extras, TOP Addons, Tech Reborn, Tesla Core Lib, Tesla Core Lib Registries, Thaumcrafft Inventory Scanning, Thaumcraft, The One Probe, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Tinker I/O, Tinkers Tool Leveling, Tinkers' Construct, Tomb Many Graves, TombManyGraves2 API, Traverse, UniDict, Universal Modifiers, Useful Nullifiers, Valkyrie Lib, VanillaFix, Vulpes library, WAIM, WanionLib, Water Strainer, Waystones, Wireless Crafting Terminal 2, WirelessCharger, WrapUp, XNet, Xtones, YNot, Zero CORE, asielib, careerbees, iChunUtil, p455w0rd's Library, projectred-compat

Plugins (16): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge,  FastAsyncWorldEdit, AdamantineShield, Holograms, LuckPerms, MagiBridge, NoMobFarm, Nucleus, Nucleus Gluon, PlaceholderAPI, Universe Guard 2, WorldEdit, spark

**Issue Description**
I've been getting a lot of Failed to process all PhaseContext in my log, and each time it happens there is a lagspike.
There are also some SimpleChannelHandlerWrapper exception
Here is a full log:
https://gist.github.com/wormzjl/fd5cd681b15af64fcb3c5d09a57b02b1

**Comment by Shybella** [comment]
This is a temp patch for #2273 until it's fixed. 

Yes, It is causing performance issues.

**Comment by Aaron1011** [comment]
@Shybella This is actually an entirely separate issue from https://github.com/SpongePowered/SpongeForge/issues/2273. You're probably thinking of [this message](https://github.com/SpongePowered/SpongeCommon/blob/e19bebe741a5bbbeca2ce485e4b0702d142a3bc6/src/main/java/org/spongepowered/common/event/tracking/PhaseTracker.java#L909).

**Comment by Shybella** [comment]
I posted in the wrong issue. Oops.

**Comment by Aaron1011** [comment]
@wormzjl All of the PhaseContext related errors should be fixed in the next build. However, the `SimpleChannelHandlerWrapper` exceptions are an entirely different issue altogether - can you please open a separate issue for them?

**Comment by wormzjl** [comment]
New issue here https://github.com/SpongePowered/SpongeForge/issues/2285

**Comment by Aaron1011** [comment]
Closing this issue since the PhaseContext errors should be fixed in the latest `stable-7`.
