### ISSUE TITLE
Problems with the craft. The conflict with the Parachronology mod.

### ISSUE THREAD

**Issue by SawFowl** [SpongePowered/SpongeForge#2287]
**I am currently running**
- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3281
- Forge version:  14.23.4.2705
- Java version:  openjdk 1.8.0_171
- Operating System: Ubuntu 18.04

- Plugins (27): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge,  FastAsyncWorldEdit, BeanCore, CatClearLag, CommandSync, EconomyLite, GriefPrevention, HuskyCrates, HuskyUI, JobsLite, LangSwitch, LuckPerms, Nucleus, PayDay, PlaceholderAPI, ProjectCore, SkyClaims, StackBan, UltimateChat, UniversalMarket, VillagerShops, VirtualChest, VirtualTool, WorldEdit

- Mods (40): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AE2 Stuff, Advanced Solar Panels, Applied Energistics 2, BD Lib, CXLibrary, Clumps, CoFH Core, CoFH World, CodeChicken Lib, Console Filter, CreativeCore, CreativeCoreDummy, Ex Nihilo Creatio, Extreme Reactors, Fishing Net Mod, Forestry, Giacomo's Foundry, HoloInventory, IndustrialCraft 2, Iron Chest, ItemPhysic, Just Enough Items, Mantle, NoDestroy, Parachronology, Quick Leaf Decay, Redstone Flux, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Tinkers' Construct, Tree Chopper, Zero CORE

**Issue Description**
I did not manage to reproduce this bug myself, I do not know what it is connected with. When a player tries crafted an item, then it somehow turns an endless pickaxe or a stick from Parachronology mod.

https://gist.github.com/Mr-Krab/86a72924002fe4b2c9c48bac7c45787f

**Comment by gabizou** [comment]
Going to need to know how to reproduce the bug to even attempt to resolve the issue. Currently all I know is that I could be crafting a torch and it turns into an unbreakable pickaxe?

**Comment by SawFowl** [comment]
@gabizou When you open the crafting window, there already is this pickaxe. Even if there is nothing in the craft grid. I tried to reproduce the problem myself, but I did not succeed.

**Comment by SawFowl** [comment]
Screenshots https://imgur.com/a/pzsWGzX

I hope this helps.

**Comment by SawFowl** [comment]
This issue does not appear at this time.
