### ISSUE TITLE
Giacomo's Fishing Net. Invalid block state.

### ISSUE THREAD

**Issue by SawFowl** [SpongePowered/SpongeForge#2288]
**I am currently running**
- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3281
- Forge version: 14.23.4.2705
- Java version: openjdk 1.8.0_171
- Operating System: Ubuntu 18.04

-  Plugins (27): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge,  FastAsyncWorldEdit, BeanCore, CatClearLag, CommandSync, EconomyLite, GriefPrevention, HuskyCrates, HuskyUI, JobsLite, LangSwitch, LuckPerms, Nucleus, PayDay, PlaceholderAPI, ProjectCore, SkyClaims, StackBan, UltimateChat, UniversalMarket, VillagerShops, VirtualChest, VirtualTool, WorldEdit

- Mods (39): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AE2 Stuff, Advanced Solar Panels, Applied Energistics 2, BD Lib, CXLibrary, Clumps, CoFH Core, CoFH World, CodeChicken Lib, Console Filter, CreativeCore, CreativeCoreDummy, Ex Nihilo Creatio, Extreme Reactors, Fishing Net Mod, Forestry, Giacomo's Foundry, HoloInventory, IndustrialCraft 2, Iron Chest, ItemPhysic, Just Enough Items, Mantle, NoDestroy, Quick Leaf Decay, Redstone Flux, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Tinkers' Construct, Tree Chopper, Zero CORE

**Issue Description**
It is impossible to break a fishing net located in the water, although the item falls out at the same time. I previously reported this problem and it was solved, but now it has arisen again.

https://gist.github.com/Mr-Krab/6db50d57487e9881c4eab0ae6f1a9df1

**Comment by phit** [comment]
previous issue https://github.com/SpongePowered/SpongeForge/issues/1989

**Comment by SawFowl** [comment]
Fixed.

Tested on: 1.12.2-2705-7.1.0-BETA-3291
