### ISSUE TITLE
Server crash on startup

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#2290]
**I am currently running**

- SpongeForge version: 1.12.2-2705-7.10-BETA-3285
- Forge version: 2705
- Java version: Java 8
- Operating System: Windows Server

- Plugins/Mods:
Cant List them as I cant get the server to launch

**Issue Description**
We start our server and it crashes right away with no reason why and then tells us it could break our world and if this does happen we are screwed.

https://gist.github.com/TacticalUniverse/e9c357c5bb9aeed302dc9d21edec265d

**Comment by gabizou** [comment]
Issue with RandomPatches. https://github.com/TheRandomLabs/RandomPatches/issues/7
