### ISSUE TITLE
Events not being triggered

### ISSUE THREAD

**Issue by Sir-Will** [SpongePowered/SpongeForge#2294]
The events from DraconicEvolution here: https://github.com/brandon3055/Draconic-Evolution/blob/master/src/main/java/com/brandon3055/draconicevolution/network/PacketPlaceItem.java#L88 are not being detected by Sponge.
Using the debug mode of GP shows that nothing is being tracked.

spongeforge-1.12.2-2705-7.1.0-BETA-3284

**Comment by Shybella** [comment]
I also have this problem and was in the process of reporting it.

**Comment by liach** [comment]
In my opinion, this is caused by draconic evolution firing events on networking threads. Not even mods are able to listen to this event fired by draconic evolution as forge event bus is single-threaded.

**Comment by Sir-Will** [comment]
@liach just tested it and it does trigger the forge `BlockEvent.PlaceEvent` event. I can also cancel it without issues.

**Comment by liach** [comment]
but a mod should not fire events in off thread.

**Comment by Zidane** [comment]
@Sir-Will 

You aren't getting it. The event they are calling is being triggered ON A NETWORK THREAD. We aren't supporting this, they need to enqueue onto the main thread (like basically all Vanilla network handlers already do).

**Comment by covers1624** [comment]
No, your assumptions of Brandon's network code are incorrect, The packet IS handled on the main thread. The packet in question is [`PacketPlacedItem`](https://github.com/brandon3055/Draconic-Evolution/blob/master/src/main/java/com/brandon3055/draconicevolution/network/PacketPlaceItem.java#L42), Notice that its Handler extends [`MessageHandlerWrapper`](https://github.com/brandon3055/BrandonsCore/blob/e6364e5b8945ca244341c81d50aec45ea1b58f82/src/main/java/com/brandon3055/brandonscore/network/MessageHandlerWrapper.java#L11) `hanleMessage` is not provided by the `IMessageHandler` interface, `onMessage` is. A new [`PacketSyncObject`](https://github.com/brandon3055/BrandonsCore/blob/f1384cd545b4d73d0c2d0001c530e57b77912adf/src/main/java/com/brandon3055/brandonscore/network/PacketSyncObject.java) anon class is created and the appropriate method, `addPacketServer` or `addPacketClient` is called, these do some sanity checking then add the `PacketSyncObject` to the respective side's 'main thread queue', that 'queue' then invokes the `run` method that the anon class overrides calling the `handleMesage` method on `PacketPlacedItem`.

**Comment by ryantheleach** [comment]
Reopening this until someone can provide absolute evidence one way or the other.

**Comment by brandon3055** [comment]
http://ss.brandon3055.com/7393c

Edit: And before you ask to see my LogHelper.
http://ss.brandon3055.com/57e7c

**Comment by ryantheleach** [comment]
@brandon3055 Thanks.

**Comment by Zidane** [comment]
@Shybella Could you re-test this for us on latest and let me know if it is still an issue?

**Comment by Shybella** [comment]
Fixed.
