### ISSUE TITLE
Unable to login due to Advancements exception

### ISSUE THREAD

**Issue by flamechair** [SpongePowered/SpongeForge#2295]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3291
- Forge version: 1.12.2 2705
- Java version: N/A
- Operating System: N/A

- Plugins/Mods:
```
> [04:23:46] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Mods (90): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AI Improvements, AbyssalCraft, AbyssalCraft Integration, Aether Legacy, Aroma1997Core, AromaBackup, AromaBackuprecovery, Astral Sorcery, AutoRegLib, Baubles, BiblioCraft, Bookshelf, Chameleon, ChickenChunks, Chisel, Chunk Pregenerator, CoFH Core, CoFH World, CodeChicken Lib, Cyclops Core, Dark Utilities, Disenchanter, Dungeon Mods, Dynamic Surroundings, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, EvilCraft, EvilCraft-Compat, Extra Utilities 2, FoamFix, FoamFixCore, Guide-API, Hammer Core, Improvable Skills, InstantUnify, Inventory Tweaks, Iron Chest, JourneyMap, Just Enough Items, LagGoggles, Less Forgiving Void, McJtyLib, Mo' Bends, Nether Foundation, NetherEx, Not Enough Items, OpenBlocks, OpenModsLib, OpenModsLib Core, Progressive Bosses, Quark, RFTools, RFTools Control, Redstone Flux, Roguelike Dungeons, Storage Drawers, TOP Addons, TeamLapen Library, Thaumcraft, The One Probe, The Twilight Forest, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, TickProfiler, Tree Chopper, UniDict, Unlimited Chisel Works, Vampirism, VampirismIntegrations, WanionLib, WorldEdit
> sponge plugins
[04:23:49] [Server thread/INFO] [nucleus]: Server ran the command: /sponge plugins
> [04:23:49] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Plugins (13): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, ActionBroadcaster, CarrotShop, ClearMob, EconomyLite, GriefPrevention, LuckPerms, MagiBridge, Nucleus, Rankup
```

**Issue Description**
As soon as i join the server, there is an internal server error and the stack trace is printed. I am unable to login to the server.

> java.lang.IllegalStateException: The advancement of this advancement progress is unloaded: minecraft:adventure_adventuring_time

https://gist.github.com/iamtpage/d9247605e3f1fa336221632934588215

**Comment by johnfriedrich** [comment]
SF 3290
Forge 2705
Modpack: FTB Continuum
Same here:
https://pastebin.com/JzRejTQk
Full log:
https://pastebin.com/HX5Cwzad

**Comment by Martmists-GH** [comment]
Potentially related:
https://hastebin.com/honubeleli.pl (incomplete due to Android, will update asap)

modpack: ATM3

**Comment by johnfriedrich** [comment]
Not 100% sure why this happens, but this seems to start happening when FakePlayers are placing blocks

**Comment by flamechair** [comment]
Doesn't happen on my server when FakePlayers place blocks, so I'm not sure thats the reason here

**Comment by flamechair** [comment]
Still present on spongeforge-1.12.2-2705-7.1.0-BETA-3304

**Comment by johnfriedrich** [comment]
Not instantly, but when FakePlayers are getting Advancements due to block placements. Thats my guess

**Comment by EscolarProgramming** [comment]
Still not fixxed :(
SF 3306
Forge 2705
The error: https://pastebin.com/FKePs9Qu
Full log: https://paste.feed-the-beast.com/view/4ade1700

**Comment by bloodmc** [comment]
@EscolarProgramming Try this test build
https://www.dropbox.com/s/x7ffc5kzdal59d2/spongeforge-1.12.2-2705-7.1.0-BETA-TEST1.jar

**Comment by flamechair** [comment]
Still happening on spongeforge-1.12.2-2705-7.1.0-BETA-3308

```
> [16:16:48] [User Authenticator #1/INFO] [net.minecraft.server.network.NetHandlerLoginServer]: UUID of player defkult is 96b9d08f-34ef-4bcd-8c7a-bf3b7bc2a45d
> [16:16:49] [Server thread/WARN] [net.minecraft.network.NetworkSystem]: Failed to handle packet for /71.14.143.168:55046
java.lang.IllegalStateException: The criterion is not yet initialized
at com.google.common.base.Preconditions.checkState(Preconditions.java:444) ~[minecraft_server.1.12.2.jar:?]
at net.minecraft.advancements.CriterionProgress.getCriterion(SourceFile:582) ~[o.class:?]
at net.minecraft.advancements.PlayerAdvancements.redirect$onUnregisterListenersGetProgress$zbc000(PlayerAdvancements.java:605) ~[np.class:?]
at net.minecraft.advancements.PlayerAdvancements.func_193764_b(PlayerAdvancements.java:263) ~[np.class:?]
at net.minecraft.advancements.PlayerAdvancements.func_192751_c(PlayerAdvancements.java:88) ~[np.class:?]
at net.minecraft.advancements.PlayerAdvancements.func_192740_f(PlayerAdvancements.java:165) ~[np.class:?]
at net.minecraft.advancements.PlayerAdvancements.<init>(PlayerAdvancements.java:56) ~[np.class:?]
at net.minecraft.server.management.PlayerList.func_192054_h(PlayerList.java:1136) ~[pl.class:?]
at net.minecraft.entity.player.EntityPlayerMP.<init>(EntityPlayerMP.java:183) ~[oq.class:?]
at net.minecraft.server.management.PlayerList.func_148545_a(PlayerList.java:503) ~[pl.class:?]
at net.minecraft.server.network.NetHandlerLoginServer.func_147326_c(NetHandlerLoginServer.java:135) ~[pc.class:?]
at net.minecraft.server.network.NetHandlerLoginServer.func_73660_a(NetHandlerLoginServer.java:63) ~[pc.class:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
> [16:16:49] [Server thread/INFO] [net.minecraft.server.network.NetHandlerLoginServer]: com.mojang.authlib.GameProfile@2bebcd0c[id=96b9d08f-34ef-4bcd-8c7a-bf3b7bc2a45d,name=defkult,properties={textures=[Property{name=textures, value=eyJ0aW1lc3RhbXAiOjE1MzE3NTc4MDgyMzQsInByb2ZpbGVJZCI6Ijk2YjlkMDhmMzRlZjRiY2Q4YzdhYmYzYjdiYzJhNDVkIiwicHJvZmlsZU5hbWUiOiJkZWZrdWx0IiwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzE5OTc5ODhmNmQyNTA5Y2Y0NTNhNTdhYzEwMzY3ZDVjZDkyMWQ1MmM2YjMxNDA3NzIxMjdhMzc4ODExMzA2ZTAifX19, signature=Optional[Z3/5NIX39lvV2N0p4gfBL+c8vTZ45QjSvUZjq0Dp+vqYZvxNi/c4Vhfcv9/VaM5IM1zYgEsrw2ejCE+AkccUDWXfORo4TqoMMfuCezjJUmsrGGkO7C7Hb/kH8NWLZOr9BaY5EPqo0kqDHJNMkfj9eSf8xE61m9avaL+oreuOdBwj0S8ueV6vskjPI4N3622rsVA1w0k937ck7PaKQhp2yzgIHjl5/KSBWWkC9+rm9x9zLba2OTG4KCh7/LxgTpi1Gu7+CQAobFLlnmpfhLlQFX4EDM7rHOjnpwEYlrmtVO7/2OkerBSUlM9Cfw4eqYEt7k9wBdNFlLwvC0p59O/fiPUC9M9GQAlQN39TTmyeBmeWAi2SBB2Kg8czo/Ug43ZKXnM+h2wk6tT0maGjLYXwE8OrxWMsn5RFR+V9S0ZO2Fa35JxgcihCdAfBuY1HdXjvH6wu1iIwykvNxx7Ghlrtuh4AlOPG/G0cy8cxZms8xhh4Xpp4Kk+RICIV6FrAseorrmQZsueFCVoCtRXoSKaliv7C80GnVmS917RZdk+7gMpAokt9jFqdSIyeQQ22L2w6C59/eZaijkzJ+o44akHwPTpURcaPmhXdpfc2WpmJoRxvQRS+ymK/q1zOv92aor/qja1l/ASE7jgvOXzsju6wjDg+biySqgMnfG89SYmjxS8=]}]},legacy=false] (/71.14.143.168:55046) lost connection: Internal server error
```

cc: @bloodmc

**Comment by Nbgreen** [comment]
Issue still isn’t fixed 
https://github.com/micdoodle8/Galacticraft/issues/3920

**Comment by radfast** [comment]
This is not a Galacticraft issue, please see my comments on the issue linked.

We get a lot of "false positive" issues being attributed to Galacticraft, which isn't great for us.  The main reason is because our mod has pass-through player `<init>` and tick-handling code and new world generation code, so that when other parts of the game error, sometimes you can see a Galacticraft class far down the stacktrace (below vanilla `<init>` or tick code and vanilla worldgen code).   People reporting issues - and **people helping the people who report issues** - need to understand that the code in the middle / end of a stacktrace is not normally the cause of an issue.  It's the first few lines at the **top** of the stacktrace which normally point to the cause.

**Comment by dualspiral** [comment]
To note: I also asked @Nbgreen to open a new issue with his issue in Discrod three days ago, as the original issue here was actually fixed and what he's reporting is actually a different issue - though the end result might be the same. I also don't think we suggested it was GC, so sorry you got involved in that.

@Nbgreen Please file a **new** issue with your problem, following the template and detailed reproduction steps. Thanks.

**Comment by radfast** [comment]
@dualspiral @Aaron1011 has pointed out that there is a potential GC issue here, because we are calling a getWorld() from a network packet handling thread, which can potentially cause an issue in a Sponge environment.  I am looking at what we can do about this, as a priority .

**Comment by Dockter** [comment]
Correct me if I am wrong but if you're calling getWorld off the main thread that alone will give you problems.  If you're calling getWorld via a packet handler, then surround it with a  this.world.getMinecraftServer().addScheduledTask(() -> {[code here]}

This above method should cause the call to execute back on the main thread.

**Comment by Nbgreen** [comment]
@dualspiral I did make a new post on yalls github no one has comment on it 
https://github.com/SpongePowered/SpongeForge/issues/3121

**Comment by dualspiral** [comment]
I apologise, I did not realise it was there. I have altered the title of that issue to be more representative.

Rather than comment on this issue (which is actually different), please direct further comments to #3121: thanks.
