### ISSUE TITLE
TileEntityTickPhase errors on the Server

### ISSUE THREAD

**Issue by MoeShimaKaze** [SpongePowered/SpongeForge#2296]
- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3291 
- Forge version: 14.23.4.2705
- Java version: jre1.8.0_171
- Operating System:Windows Server 2016
the error logs:https://pastebin.com/XC4qn4pL
when i running the 1.12.2-2705-7.1.0-BETA-3206,the problem still exist
so i update the SpongeForge,but the problem isn't sloved

Mods list:
Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Advanced Solar Panels, Applied Energistics 2, Avaritia, Baubles, Botania, ChinjufuMod, CodeChicken Lib, ContainerFix, CraftTweaker JEI Support, CraftTweaker2, CustomNPCs, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, Extra Utilities 2, FrogCraft: Rebirth, Garden of Glass, Globe, Immersive Engineering, Immersive Tech, Industrial Foregoing, IndustrialCraft 2, MTLib, Mantle, Mekanism, MekanismGenerators, MekanismTools, MineTweakerRecipeMaker, Mod Tweaker, NoMoreRecipeConflict, Reborn Core, Redstone Flux, Shadowfacts' Forgelin, Sky Resources 2, Tech Reborn, Tesla Core Lib, Tesla Core Lib Registries, Tinker I/O, Tinkers Alloying Addon, Tinkers' Construct

**Comment by gabizou** [comment]
You were right with the first title: ExtraUtils2 is doing something funky that throws an NPE (not sponge code, but extra utils 2 code) and Sponge is catching it.

For reference, here's the trimmed stack trace of where the issue lies:
```
/* java.lang.NullPointerException: null
/*     com.rwtema.extrautils2.dimensions.workhousedim.WorldProviderSpecialDim.prepareNewChunk(WorldProviderSpecialDim.java:193)
/*     com.rwtema.extrautils2.quarry.TileQuarry.getNextChunk(TileQuarry.java:428)
/*     com.rwtema.extrautils2.quarry.TileQuarry.func_73660_a(TileQuarry.java:280)
/*     org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:249) 
```

I'm pretty sure that somehow the `world` reverence does' exist......

**Comment by MoeShimaKaze** [comment]
so can you fix it?
i think this problem make my server very bad

**Comment by iPoLarA** [comment]
can i yingyingying?

**Comment by MoeShimaKaze** [comment]
hmm,i delete the nether,so cause this problem
now i fixed it by change the mod config
thank you help me
