### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by KurimuzonAkuma** [SpongePowered/SpongeForge#2298]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2705-8.0.0-BETA-3273
- Forge version: forge-1.12.2-14.23.4.2732-universal
- Java version: 1.8.0_25
- Operating System: Windows 10

- Plugins/Mods: spongeforge-1.12.2-2705-8.0.0-BETA-3273, industrialcraft-2-2.8.73-ex112

**Issue Description**
Server cant start with spongecoremod.

https://gist.github.com/KurimuzonAkuma/40060cdb5f88ed45357132fad96f6492 -crash-report
https://gist.github.com/KurimuzonAkuma/e682d4fc5049bd5133b326272e438670 -console full log

**Comment by se7kn8** [comment]
SpongePowered/SpongeCommon#1981

**Comment by gabizou** [comment]
Update SpongeForge, and don't use bleeding branches (It says 8.0.0 in your jar name, use 7.1.0 builds) in production.
