### ISSUE TITLE
ComputerCraft turtles can't move over 90% of the time outside of GP claims

### ISSUE THREAD

**Issue by Lemmmy** [SpongePowered/SpongeForge#2305]
**I am currently running**
- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3293
- Forge version: 14.23.4.2705
- Java version: openjdk version "1.8.0_172"
- Operating System: Linux barbecute 4.4.0-124-generic #148-Ubuntu SMP Wed May 2 13:00:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Plugins (6): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, GriefPrevention, LuckPerms
- Mods (7): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, CC: Tweaked

**Issue Description** 
With GriefPrevention installed, ComputerCraft turtles can only move between 1-10% of the time when in the wilderness. They can move perfectly fine inside claims. This is 100% reproducible on a fresh server with `griefprevention-1.12.2-4.3.0.643`, and started happening exactly on sponge build 3293. It still occurs on 3304.

An important thing to note is that admins cannot reproduce this bug, even with `/ignoreclaims` turned off. It can only be reproduced by users, so it's possible some GP permission node is affecting this.

Another thing to note is that turtles seem to have a higher chance of moving on our production server, but almost never moved (only once or twice) on the test server.

**Reproduction Steps**
* Install a server with the following mods:
  * `forge-1.12.2-14.23.4.2705-universal`
  * `spongeforge-1.12.2-2705-7.1.0-BETA-3293` (or any version afterwards)
  * `LuckPerms-Sponge-4.2.49`
  * `griefprevention-1.12.2-4.3.0.643`
  * [`cc-tweaked-1.80pr1.7`](https://minecraft.curseforge.com/projects/cc-tweaked/files/2581129)
* Give the default group the following permissions (e.g. `/lp group default permission set <node>`):
  * `griefprevention.user`
  * `griefprevention.admin.claim.command.debug`
  * `luckperms.verbose`
* Place a turtle of any variety in the world
* Place a lava bucket in the turtle's inventory and run `refuel all`
* **(optional)** Turn on `/gpdebug on` and `/lp verbose`
* Run [`pastebin run RHq1szT3`](https://pastebin.com/RHq1szT3) in the turtle. This program will try to move the turtle 100 times, counting the number of successes. If the turtle turns without moving forward, then a movement failed, which is a successful reproduction in this case. When 100 moves have been attempted, it will output the number of successes (e.g. `Success: 2/100`)
* **(optional)** Create a basic claim, and retry the turtle steps inside the claim. In my testing, this works 100% of the time, showing this only occurs in the wilderness.
* **(optional)** Retry all steps on 3292 - everything works exactly as expected (the turtle can move 100 times both inside and outside the wilderness)

**Logs**
`latest.log` with block tracking, `/gpdebug on` and `/lp verbose`: https://gist.github.com/Lemmmy/413542df9355b425514522ee229ec93e

**Comment by Lemmmy** [comment]
Fixed in https://github.com/MinecraftPortCentral/GriefPrevention/commit/06d1bb7a77e4f97ee38033d600b05d59953215b1

**Comment by XMaxTheKillerX** [comment]
I am experianceing the same problem, But I am running on the latest version on GriefPrevention (griefprevention-1.12.2-4.3.0.662) do you maybe know what I can do?

**Comment by Lemmmy** [comment]
@XMaxTheKillerX Are you using the latest version of CC:Tweaked instead of ComputerCraft? CC:Tweaked has many fixes to allow for Sponge compatibility (it is actually primarily developed against a Sponge server).

Also, 662 is not the latest version of GriefPrevention. Check Ore for a more up-to-date version. Our server runs GP 674, SpongeForge RC3557 (quite outdated, though) and a custom build of CC:T from the `master` branch provided by SquidDev, though 1.81 should work fine.

**Comment by phit** [comment]
this is something that was broken with 3618, see https://github.com/SpongePowered/SpongeForge/issues/2646

should be fixed soon https://github.com/SpongePowered/SpongeCommon/pull/2219

for now stick to 3616 @XMaxTheKillerX

**Comment by XMaxTheKillerX** [comment]
It fixed the issue, Thanks!
