### ISSUE TITLE
Server crash when entering Deep Dark - 1.12

### ISSUE THREAD

**Issue by Keaton1188** [SpongePowered/SpongeForge#2308]
**I am currently running**

- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3262
- Forge version: 14.23.4.2705
- Java version: Java openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)
- Operating System: CentOS Linux release 7.2.1511

- Plugins/Mods: FTB Revelations 

**Issue Description**
Whenever someone enters the Deep Dark using the portal the server crashes, we have tried resetting the deep dark etc and it didn't help.. not sure if this is sponge related but asking/posting here. 

 https://pastebin.com/DysZCbpB

**Comment by Aaron1011** [comment]
Can you retest on the latest SpongeForge?

**Comment by Keaton1188** [comment]
Testing now.

**Comment by Keaton1188** [comment]
Yep all fixed, thanks :)

Closing,
