### ISSUE TITLE
Duplicating Blocks Against Claim Edge (GP)

### ISSUE THREAD

**Issue by RussianSanity** [SpongePowered/SpongeForge#2309]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3304
- Forge version: forge-1.12.2-14.23.4.2707-universal
- Java version: 1.8.0_161, Oracle Corporation
- Operating System: Linux (amd64) version 4.9.33-mod-std-ipv6-64

- Plugins/Mods: Tick Profiler, Better Chunkloader, Universeguard, Stackban, Prism, Nucleus, LuckPerms, GriefPrevention (1.12.2-4.3.0.643), and a custom plugin written by developers of our staff team

**Issue Description**
Using the following picture (below) link as a guide: where the diamond block is located right now is the last block of the claim. When a piston pushes any block into the last block, or the edge, of a claim, it duplicates the block and leaves it on the ground. 
https://cdn.discordapp.com/attachments/468160827254505526/468161606447136793/2018-07-15_16.47.19.png
https://cdn.discordapp.com/attachments/468160827254505526/468161262082064384/2018-07-15_17.05.34.png (to show the claim boundary) 

N/A on server logs.

**Comment by bloodmc** [comment]
Fixed in forge event refactor.

https://github.com/SpongePowered/SpongeForge/commit/59ffec9539cff0462c395c2a2273ba6dd7fb370f
