### ISSUE TITLE
Sponge Forge Server getting stuck loading with flans mod

### ISSUE THREAD

**Issue by EnvyingGolem47** [SpongePowered/SpongeForge#2312]
**I am currently running**

- SpongeForge version: 1.12.2-2705-8.0.0-BETA-3302
- Forge version: 1.12.2 - 14.23.4.2705
- Java version: 1.8.0_171
- Operating System: Ubuntu 17.10 (GNU/Linux 4.13.0-43-generic x86_64)

- Plugins/Mods: SecurityCraft, AutoRegLib, BetterFps, crayfish's device mod, crayfish's furniture mod, chisels and bits, code chicken lib, CoFH Core, CoFH World, Common Capabilities, Computer Craft, Creative Core, Custom Npcs, Cyclops Core, Extra Bit Manipulation, Faction Mod, Flans Mod, Forge Multipart, Gitweb + Builder, Hide Names, Hwyla, Integrated Dynamics, Just Enough Items, Journey Map, 
Mantle, mcjtylib, MrTJPCore, Not Enough Items, Obfuscate, Online Picture Frame, p455w0rdslib, Project Red Base, Project Red Compat, Project Red Fabrication, Project Red Integration, Project Red Lighting, Project Red Mechanical, Project Red World, Quark, Redstone Flux, Secret Rooms Mod, TConstruct, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Universe Guard, Crayfish's Vehicle Mod, Waila Harvestability, Wawla, World Edit Forge, World Protector, Wireless Redstone Mod, Xnet, YNot.

So a friend and I have been trying to improve our Minecraft server network by adding bungee cord to our servers. We are using Sponge so that we can put Bungee cord onto our modded server to connect with our other servers on our network. But every time we start up Sponge it gets stuck at loading the advancements. After some troubleshooting we figured out that the problem was flans mod but that's a core part of our mod pack and we don't want to remove it. We were hoping that somebody might know how to remove/replace advancements or might know a way around our problem.
        After rough testing we figured out that with only flans mod and sponge installed it still stopped at loaded advancements. In order to stop the server we have to kill it using the command line in Linux.

1. Put flans mod and sponge into mods folder 2. Put Flans packs (Apocalypse Content, Modern Warfare Content, Simple Parts, World War 2 Content Pack, Ye Olde Content Pack, Zombie Content Pack) into Flan folder 3. Start up forge server 

 

https://gist.github.com/EnvyingGolem47/e004d7b90301cb7c429fccad2bc263fb

**Comment by bloodmc** [comment]
You are using an outdated SpongeForge build. Update to latest
http://files.minecraftforge.net/spongepowered

**Comment by EnvyingGolem47** [comment]
I just updated to latest SpongeForge build and it still got stuck at the same point, with the same text.

**Comment by phit** [comment]
use stable builds, API 8 is not meant for production if it still happens on api7 provide a new log
