### ISSUE TITLE
Server getting stuck loading with flans mod

### ISSUE THREAD

**Issue by EnvyingGolem47** [SpongePowered/SpongeForge#2313]
**I am currently running**

- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3206
- Forge version: 1.12.2 - 14.23.4.2705
- Java version: 1.8.0_171
- Operating System: Ubuntu 17.10 (GNU/Linux 4.13.0-43-generic x86_64)

- Plugins/Mods: SecurityCraft, AutoRegLib, BetterFps, crayfish's device mod, crayfish's furniture mod, chisels and bits, code chicken lib, CoFH Core, CoFH World, Common Capabilities, Computer Craft, Creative Core, Custom Npcs, Cyclops Core, Extra Bit Manipulation, Faction Mod, Flans Mod, Forge Multipart, Gitweb + Builder, Hide Names, Hwyla, Integrated Dynamics, Just Enough Items, Journey Map, 
Mantle, mcjtylib, MrTJPCore, Not Enough Items, Obfuscate, Online Picture Frame, p455w0rdslib, Project Red Base, Project Red Compat, Project Red Fabrication, Project Red Integration, Project Red Lighting, Project Red Mechanical, Project Red World, Quark, Redstone Flux, Secret Rooms Mod, TConstruct, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Universe Guard, Crayfish's Vehicle Mod, Waila Harvestability, Wawla, World Edit Forge, World Protector, Wireless Redstone Mod, Xnet, YNot.

So a friend and I have been trying to improve our Minecraft server network by adding bungee cord to our servers. We are using Sponge so that we can put Bungee cord onto our modded server to connect with our other servers on our network. But every time we start up Sponge it gets stuck at loading the advancements. After some troubleshooting we figured out that the problem was flans mod but that's a core part of our mod pack and we don't want to remove it. We were hoping that somebody might know how to remove/replace advancements or might know a way around our problem. I reposted this with API 7.0.0 because I was told to but we went to API 8 to see if it was an API 7 problem because we need API 7 for a plugin.
          After rough testing we figured out that with only flans mod and sponge installed it still stopped at loaded advancements. In order to stop the server we have to kill it using the command line in Linux.

1. Put flans mod and sponge into mods folder 2. Put Flans packs (Apocalypse Content, Modern Warfare Content, Simple Parts, World War 2 Content Pack, Ye Olde Content Pack, Zombie Content Pack) into Flan folder 3. Start up forge server 

https://gist.github.com/EnvyingGolem47/5f5aedc70c23afd9cb8b17596969dd68

**Comment by spockmenow** [comment]
Hey guys we really need your help and we don't think it's the version, we are pretty sure it is a compatibility problems but we need this to work for our mod pack to be successful. So please don't throw this away as a simple problems and try it out for yourself.

**Comment by phit** [comment]
could have just replied with that on the old issue and I would have reopened

**Comment by EnvyingGolem47** [comment]
Sorry about that. Can you still help us?

**Comment by phit** [comment]
please add the debug.log, nothing interesting in the latest.log and the advancements finish loading by the looks of it and the server is done starting

**Comment by EnvyingGolem47** [comment]
Here is the debug log that goes along with the latest log. https://gist.github.com/EnvyingGolem47/6b78d0f7a840de46a51f6c800c93ca9b

**Comment by spockmenow** [comment]
@phit Could you please remove those tags, we have provided the info you asked for.

**Comment by phit** [comment]
still don't see anything wrong in that log, what happens when you try to connect, to you see the connection coming in on the server?
what is the client message when connecting?

**Comment by JBYoshi** [comment]
When I try it, the server starts up fine. I'm using SpongeForge version 3322 (development mode) with Flan's Mod 5.5.2 and all the content packs.

**Comment by spockmenow** [comment]
So odd, we tried 3322 and that didn't work and we are running 5.5.2. Currently I am trying to get a screenshot of what it shows me when I try to log in after that (maybe later today because of school) I will try to get a video of how we set up sponge or something else to figure out if that could be the problem.

**Comment by bloodmc** [comment]
Set `max-tick-time=-1` in `server.properties` and try again.

**Comment by spockmenow** [comment]
Ok, I tried that and it didn't work. But I did see Flans try to load a bunch of stuff after it got stuck on the advancements but it deleted the lines for some reason.

**Comment by spockmenow** [comment]
@phit It gives me the same message as when it's trying to start a minecraft server normally.

**Comment by EnvyingGolem47** [comment]
Alright @phit we got flans mod to work with sponge now. I put all of the flans official content for flans mod in this time and what I did was I loaded flans and sponge together to make a new world then put all of our other mods we had into our mods folder and it works fine. We have a new problem now, every time we try to connect using bungee cord it tells me to enable IP forwarding in bungee cord's config. It is enabled but it keep saying that it is not. I would also appreciate if you can continue to help in here instead of making a new issue.

**Comment by JBYoshi** [comment]
It's a known issue with BungeeCord. See the warning box in https://docs.spongepowered.org/stable/en/server/getting-started/bungeecord.html for some workarounds.

**Comment by EnvyingGolem47** [comment]
@JBYoshi We are using linux so we changed the IPtables and our firewall rules now we are only getting this error: Internal Exception: com.google.common.util.concurrent.UncheckedExcecutionException: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Minecraft Forge (forge)

**Comment by bloodmc** [comment]
If you need other help, join our discord or use our forums. Do not use the same github ticket for multiple issues.
