### ISSUE TITLE
Items Deleted on Close Inventory

### ISSUE THREAD

**Issue by ViperzSmurfz** [SpongePowered/SpongeForge#2321]
**I am currently running**

- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3206
- Forge version: forge-1.12.2-14.23.4.2705-universal
- Java version: 1.8.0_161
- Operating System: Win10

**Issue Description**
there is an issue where if you are holding an item in the inventory and then hit esc or the inventory hotkey instead of the item getting dropped (as normal) the item just gets deleted completely.
Also, have not seen if this issue is fixed or not(Could not find one). If it is, how would i push the fix now?

**Comment by XakepSDK** [comment]
Does this happen on vanilla?

**Comment by ViperzSmurfz** [comment]
Have no tested, testing it now

**Comment by SimonFlash** [comment]
This has been resolved in later builds. Though 3206 is the most recent recommended version, it's over 100 builds behind latest. Issues should always be tested on latest as well to ensure that they haven't already been fixed prior to opening an issue.

**Comment by ViperzSmurfz** [comment]
I have tried this on 1.12.2-2705-7.1.0-BETA-3320 and it also seems to be doing the same thing.
i also git cloned the github and built it myself and it still seems to be doing the same

**Comment by ViperzSmurfz** [comment]
Tested, VanillaSponge also does this.

**Comment by ViperzSmurfz** [comment]
Ah, i believe i have found the issue on here. [CLICK HERE](https://github.com/SpongePowered/SpongeForge/issues/1981) Except it doesn't seem to be resolved for me exactly.

**Comment by Lemmmy** [comment]
Can you share your mod and plugin list?

**Comment by ViperzSmurfz** [comment]
No plugins, but modlist [here](https://www.feed-the-beast.com/projects/ftb-presents-direwolf20-1-12/files/2582361) Just Direwolf20 1.12 Pack v2.1.0 Mods
