### ISSUE TITLE
Latest builds break Caverns 2 veinmining.

### ISSUE THREAD

**Issue by ProsperCraft** [SpongePowered/SpongeForge#2323]
**I am currently running**

- SpongeForge version: 
- Forge version:  1.12.2-2705-7.1.0-BETA-3320
- Java version: openjdk version "1.8.0_171"
- Operating System: Centos 7 Minimal install

- Plugins/Mods:
Mods-
https://minecraft.curseforge.com/projects/towncraft

Plugins (21): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, BetterChunkLoader, EconomyLite, LuckPerms, MMCReboot, MMCRestrict, MagiBridge, Nations, Nucleus, PayDay, Prism, PrismPlus, PwnFilter Sponge Plugin, Rankup, ServerListPlus, SleepVote, StatusProtocol, spark

**Issue Description**

After you level up by mining you can press v and switch to a quick mode that is a veinmining mode, and you can veinmine veins.

This quit working somewhere around build 3283

**Comment by phit** [comment]
probably same as https://github.com/SpongePowered/SpongeForge/issues/2316

**Comment by ProsperCraft** [comment]
Looks like it.
