### ISSUE TITLE
IllegalStateException: The advancement is not yet initialized [SF 3320]

### ISSUE THREAD

**Issue by Dockter** [SpongePowered/SpongeForge#2324]
Hello,
Received the following error on `client` using SpongeForge build `3320` when logging into the server running the same build of SF:
* https://gist.github.com/Dockter/f84506b257e8507640888d725f23882a

**Comment by ryantheleach** [comment]
Does this still occur on 3322? 

https://github.com/SpongePowered/SpongeForge/commit/7662ccfa92bb8e9534a61aa1093206d24a6bbe7a should have fixed it, which corresponds to 3322.

**Comment by bloodmc** [comment]
Fixed in SF 3333.
