### ISSUE TITLE
Enderio Bug in spongeforge

### ISSUE THREAD

**Issue by tyler489** [SpongePowered/SpongeForge#2325]
**I am currently running**
- SpongeForge version: 3291
- Forge version: 14.23.4.2708
- Java version: ?
- Operating System: ?

This is a Cross post from enderio's github.. AS such i do not ALL have the above info. Sorry
https://github.com/SleepyTrousers/EnderIO/issues/4766

**Issue Description**
When attepting to replace a enderio conduit with a higher tier by clicking the conduit. the higher tier conduit is not consumed from the inventory. In Vanilla forge the higher tier conduit is consumed.
Seems to be a repeat of #1192 For spongeforge 1.10.2

https://i.gyazo.com/eafe88a3bee2ff89ba3edc3127b13294.mp4
Here is a GIF
the second conduit the one in slot 9 should disapear when its replaced

**Comment by tyler489** [comment]
Here is the Relevent code for conduit replacement https://github.com/SleepyTrousers/EnderIO/blob/22717941f4313ccce6faa68ac386cd2abc9d2718/enderio-conduits/src/main/java/crazypants/enderio/conduits/conduit/AbstractItemConduit.java#L119-L163

**Comment by Shybella** [comment]
I can confirm this issue on SF 3320

**Comment by phit** [comment]
was fixed on enderio's end
