### ISSUE TITLE
Incorect craft result. Dupe.

### ISSUE THREAD

**Issue by SawFowl** [SpongePowered/SpongeForge#2326]
**I am currently running**
- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3322
- Forge version: 14.23.4.2705
- Java version: Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
- Operating System: Debian 9

- Mods (48): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AE2 Stuff, Advanced Solar Panels, Applied Energistics 2, BD Lib, CXLibrary, Clumps, CoFH Core, CoFH World, CodeChicken Lib, Console Filter, CraftTweaker JEI Support, CraftTweaker2, CreativeCore, CreativeCoreDummy, Ex Nihilo Creatio, Extreme Reactors, Fishing Net Mod, FoamFix, Forestry, Giacomo's Foundry, HoloInventory, IndustrialCraft 2, Iron Chest, ItemPhysic, Just Enough Items, LagGoggles, Mantle, MrCrayfish's Furniture Mod, NoDestroy, Parachronology, Quick Leaf Decay, Redstone Flux, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Tinkers' Construct, Tree Chopper, UniDict, VanillaFix, WanionLib, Zero CORE

- Plugins (27): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge,  FastAsyncWorldEdit, BeanCore, CatClearLag, CommandSync, EconomyLite, GriefPrevention, HuskyCrates, HuskyUI, LangSwitch, LuckPerms, Nucleus, PayDay, PlaceholderAPI, ProjectCore, SkyClaims, StackBan, UltimateChat, UniversalMarket, VillagerShops, VirtualChest, VirtualTool, WorldEdit, spark

**Issue Description**
Video - https://www.youtube.com/watch?v=FcBmWqYQbSY

https://gist.github.com/Mr-Krab/0f91b205c0133fda4389802088793cf8

**Comment by phit** [comment]
does this also happen in a vanilla crafting table?

**Comment by SawFowl** [comment]
@phit Yes. And there is no bug in single mode.

**Comment by Faithcaio** [comment]
Too many mods. 
Please try to reproduce with minimal amount of mods.

I could not reproduce it locally.

**Comment by SawFowl** [comment]
@Faithcaio The minimum of mods. Without plugins. https://youtu.be/n5nD1dU-_18

SpongeForge: 1.12.2-2705-7.1.0-BETA-3334

**Comment by ryantheleach** [comment]
@Mr-Krab Thankyou for the video. However, some confusion still lies in whether any keys are being pressed. Inventory is difficult with the amount of control actions that are available..

@Faithcaio This image of BandiCam may assist in understanding what mouse presses are being pressed.

![image](https://user-images.githubusercontent.com/141554/43070888-2d3f5a42-8eb0-11e8-8b56-b6a5b6143074.png)

**Comment by SawFowl** [comment]
@ryantheleach Shift + Right Click. However, the axe enters the inventory at any click.
Here is my understanding of this bug. When crafting an item, the player gets 2 items instead of one, since under the cursor there should be an item from the mod, it remains under the cursor, but the ax goes to inventory. An error as a result of crafting. As a result of crafting, there should be only one item.
However, it is necessary to consider the mods in which, as a result of crafting, there may be several items.

**Comment by ryantheleach** [comment]
That's strange behavior, the equivalent recipes I've seen in vanilla keep the bucket for a cake recipe in the crafting grid where it originated from, (If I can rely on my memory)

**Comment by Faithcaio** [comment]
Ok.. can reproduce now. It only happens on server. 
Not when running single player.

**Comment by SawFowl** [comment]
@Faithcaio Tested on 1.12.2-2705-7.1.0-BETA-3355
The bug is present. The error appears only on the server.

**Comment by Faithcaio** [comment]
https://github.com/MrCrayfish/MrCrayfishFurnitureMod/blob/master/src/main/java/com/mrcrayfish/furniture/handler/CraftingHandler.java#L44

This is where the item gets added.
Now why does it happen with Sponge only...

https://github.com/MrCrayfish/MrCrayfishFurnitureMod/blob/61359ff650de95971dbcade5bc4e09fb5d949590/src/main/java/com/mrcrayfish/furniture/init/FurnitureCrafting.java#L147
retains the axe in the crafting grid.

Maybe Sponge is calling that event?

**Comment by Faithcaio** [comment]
somehow fixed this with something...
