### ISSUE TITLE
Worldedit error 

### ISSUE THREAD

**Issue by marekvac** [SpongePowered/SpongeForge#2329]
**I am currently running**

- SpongeForge version: 1.10.2-2477-5.2.0-BETA-2793
- Forge version: 1.10.2-12.18.3.2477
- Java version: Java 8
- Operating System: Windows 7

- Plugins/Mods: Nucleus, PEX, WorldEdit, AppleCore, AppleSkin, AutoRegLib, BiblioCraft, Blocklings, CodeChickenLib, CoFH core, CTM, CustomMobSpawner, MoCreatures, DungeonTactics, ElevatorMod, FastLeafDecay, Hats, Chisel, iChuntil, ironchest, IvToolkit, JurassiCraft, library, LootBags, MagmaMonsters, maliscore, malisdoors, Mantle, mowziesmobs, Pams HarvestCraft, RecurrentComplex, ropebridge, TConstruct, ThermalEx, ThermalFoundation, ViesCraft

**Issue Description**
I´m instal a worldedit plugin from oficial ore.sponge site. When i mark two points with wooden axe, it works. But when i type _//set 1_ nothing happened. And send me a error. `java.lang.NoClassDefFoundError` `org/spongepowered/api/world/BlockChangeFlags`

Console error:
[Here](https://gist.github.com/marekvac/cf1342424a599ca70eb878542a2d691a)

**Comment by limbo-app** [comment]
Hey @marekvac! You seem to be running an unsupported version (1.10) of SpongeForge. Support for 1.10 ended in January 2018.

If you can reproduce this issue with Minecraft 1.12.2, please [open a new issue](https://github.com/User{login=SpongePowered}/SpongeForge/issues/new) with updated information.

**Comment by phit** [comment]
you downloaded worldedit for 1.12 and are running 1.10
you can grab the 1.10 version here http://builds.enginehub.org/job/worldedit/last-successful?branch=feature/sponge-1.10.2
