### ISSUE TITLE
advancement issues

### ISSUE THREAD

**Issue by dezil** [SpongePowered/SpongeForge#2332]
**I am currently running**
- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3328 
- Forge version: 14.23.4.2725
- Java version: 1.8.0_171
- Operating System: Ubuntu

players get dropped from the server with this error in the log 
https://pastebin.com/FvajV1d1

started after we updated to 3328 but we were on 3270

**Comment by bloodmc** [comment]
Fixed in SF 3333
