### ISSUE TITLE
Not sure why the module 'real-time' reset to false after server restart

### ISSUE THREAD

**Issue by Tollainmear** [SpongePowered/SpongeForge#2334]
**I am currently running**

- SpongeForge version:  3206
- Forge version: 2705
- Java version: Java 8 (running on a remote server, can't make sure the detailed info about that)
- Operating System: Linux(as the same with above)

- Plugins/Mods:
Plugins:
Minecraft Coder Pack, SpongeAPI, SpongeForge, CommandBlockingManager, CommandSigns Reloaded, EasyScoreboards, FlexibleLogin, GriefPrevention, Holograms, KaroglanSignEditor, LuckPerms, MMCReboot, ModBanner, Nucleus, PixelAutoMessages, PlaceholderAPI, ProjectCore, ServerListPlus, SkyClaims, StackBan, Title Broadcaster, UltimateChat, VirtualChest
Mods:
Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AE2 Stuff, AI Improvements, Advanced Machines, Advanced Solar Panels, Applied Energistics 2, Avaritia, Avaritia Tweaks, BD Lib, Better Builder's Wands, Better Questing, Better Questing Quest Book, Brandon's Core, Carry On, Chisels & Bits, CoFH Core, CoFH World, CodeChicken Lib, Compact Solar Arrays, CosmeticArmorReworked, CraftTweaker JEI Support, CraftTweaker2, CreativeCore, CreativeCoreDummy, Draconic Evolution, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, Environmental Tech, Extra Utilities 2, Fast Leaf Decay, FoamFix, FoamFixCore, Gravitation Suite, Immersive Cables, Immersive Engineering, Immersive Petroleum, Immersive Tech, Industrial Foregoing, IndustrialCraft 2, InstantUnify, Integration Foregoing, Iron Chest, ItemPhysic, JAOPCA, Just Enough Items, LagGoggles, MCMultiPart, MTLib, Mantle, Mekanism, MekanismGenerators, MineTweakerRecipeMaker, Mod Tweaker, NetherPortalFix, NuclearCraft, OnlinePictureFrame, OreDictInit, PlusTiC, Redstone Flux, Shadowfacts' Forgelin, Sky Compression, Sky Resources 2, Standard Expansion, TOP Addons, Tesla Core Lib, Tesla Core Lib Registries, The One Probe, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Tinkers Tool Leveling, Tinkers' Construct, Tree Growing Simulator 2016, Tri-Addon Controller, Universal Modifiers, Valkyrie Compat, Valkyrie Lib, Wireless Crafting Terminal 2, WorldEdit, WrapUp, YUNoMakeGoodMap, p455w0rd's Library

**Issue Description** 
I tried to enable the real-time module since the loss of TPS makes players having trouble in breaking blocks, but after each restart, the value of `real-time` was reset to false.

Please help that is there any potential factor would cause this issue? As far as I know, there is an exception with mixin which was not sure what causes that.

 [Log](https://gist.github.com/Tollainmear/08fa2540ac3fa098982a086aec1f7bd4#file-gistfile1-txt-L90)

BTW, if any information else was needed, please remind me, I will upload those as soon as possible

**Comment by phit** [comment]
* either use the command to edit the config with the server running https://docs.spongepowered.org/stable/en/server/getting-started/configuration/index.html#modifying-the-config-in-game
* edit the config, then run the reload command
* stop server, then edit the config while the server is stopped

otherwise the config will always be overriden

---
the mixin error is unrelated and can be fixed by setting `B:optimizedBlockPos=false` in the foamfix.cfg
