### ISSUE TITLE
Some players lose inventory on weak connection when attempting to join

### ISSUE THREAD

**Issue by fcpwiz** [SpongePowered/SpongeForge#2335]
SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3320.jar
Forge version: forge-1.12.2-14.23.4.2705-universal.jar
Java version: 8 64 bit
Operating System: Linux
Plugins/Mods:
Plugins (21): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, Aliases, CatClearLag, Denizen2Sponge, FoxCore, FoxGuard, GriefPrevention, Holograms, LuckPerms, MMCRestrict, MagiBridge, Nucleus, PlaceholderAPI, RankUpper, TabManager, Tattle, VoxelSniper, WorldEdit, Morphius 

Mods (110): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Advanced Generators, Advanced Solar Panels, Applied Energistics 2, Astral Sorcery, AutoRegLib, BD Lib, Baubles, BiblioCraft, Biomes O' Plenty, Blood Magic: Alchemical Wizardry, Botania, Chameleon, ChickenChunks, Chisel, CoFH Core, CoFH World, CodeChicken Lib, CommonCapabilities, Cucumber Library, Cyclops Core, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, EnderStorage, Energy Converters, Exchangers, Extra Cells 2, Extra Utilities 2, Extreme Reactors, Fluxx Stuff, FoamFix, FoamFixCore, Forestry, Forge Microblocks, Forge Multipart CBE, GenDustry, Genetics Reborn, Guide-API, Immersive Engineering, Industrial Foregoing, IndustrialCraft 2, Integrated Dynamics, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTunnels-Compat, Integration Foregoing, Inventory Tweaks, Iron Chest, IvToolkit, Just Enough Items, Mantle, McJtyLib, Mekanism, MekanismGenerators, MekanismTools, Minecraft Multipart Plugin, MrTJPCore, Mystical Agradditions, Mystical Agriculture, OpenBlocks, OpenModsLib, OpenModsLib Core, PlusTiC, ProjectRed Core, ProjectRed Exploration, ProjectRed Fabrication, ProjectRed Illumination, ProjectRed Transmission, ProjectRed integration, Psi, RFTools, Random Things, Recurrent Complex, Redstone Arsenal, Redstone Flux, Shadowfacts' Forgelin, Storage Drawers, TOP Addons, Tesla Core Lib, Tesla Core Lib Registries, Thaumcraft, The One Probe, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Tinkers' Construct, Tree Chopper, UniDict, WanionLib, Zero CORE, projectred-expansion, projectred-relocation, projectred-transportation

**Issue Description**

I have the keepinv gamerule enabled on my server, and recently, a lot of my players have been losing their inventory if their connection is poor when attempting to login to the server and are killed by an entity right after logging in. this is a section of the logfile where one of the players experiencing this issue tried to join: https://gist.github.com/fcpwiz/24ea13545937d53bf42946b2b5c1a7c4

some possible related issues:
https://github.com/rwtema/Extra-Utilities-2-Source/issues/88
https://github.com/Nuchaz/BiblioCraft/issues/519

**Comment by Lemmmy** [comment]
Does this issue persist on the latest SpongeForge (3330)?

**Comment by fcpwiz** [comment]
I'll try.

**Comment by fcpwiz** [comment]
@Lemmmy yes, I’m on 3342 and it occurs often.

**Comment by gabizou** [comment]
@fcpwiz, there’s newer builds, 3353 was made this morning and has had a few more bug fixes.

Though, for clients losing items on weak connections, I don’t believe there’s anything the client even does to lose items, since the inventories are server managed. Worst case scenario is you have a mod/plugin interacting with inventories and needs to do its job better. Otherwise, I don’t see sponge interfering with inventories to cause item loss on login. 

Is there a simple way to reproduce the issue entirely and from the looks of it, it’s possible this is simply a mod issue.

**Comment by phit** [comment]
@fcpwiz is this still happening on latest (3383)?
