### ISSUE TITLE
Incorrect piston update order when panda-redstone is enabled

### ISSUE THREAD

**Issue by PolyacovYury** [SpongePowered/SpongeForge#2338]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3206
- Forge version: forge-1.12.2-14.23.4.2705-universal
- Java version: 1.8.0_181
- Operating System: Win10

- Plugins/Mods: many of them, but the issue is definitely in Sponge itself.

**Issue Description**

Various BUDed piston configurations don't work like in Vanilla, which breaks numerous contraptions. Even the most basic 2x2 flush piston door breaks.
Enabling block capturing - 
```
sponge {
    block-capturing {
        mods {
            minecraft {
                    # (I also tried true in those 3 lines)
                    piston=false
                    "piston_extension"=false
                    "sticky_piston"=false
                }
                enabled=true
            }
        }
    }
}
```
- doesn't make any difference.

Example screenshots:
Normal behaviour:

![2018-07-23_13 37 36](https://user-images.githubusercontent.com/7702239/43072166-db330352-8e7d-11e8-97ec-0807a1b0dfe8.png)
![2018-07-23_13 38 59](https://user-images.githubusercontent.com/7702239/43072167-db60d5e8-8e7d-11e8-866f-c654b018b15e.png)

What actually happens:

![2018-07-23_13 38 22](https://user-images.githubusercontent.com/7702239/43072199-eee16f38-8e7d-11e8-8e41-f95d39d1794c.png)
![2018-07-23_13 39 12](https://user-images.githubusercontent.com/7702239/43072200-ef057aa4-8e7d-11e8-8a7c-e8650e6a3203.png)

Initially I blamed Forge, but in single-player and on a server with no Sponge installed provided setups work correctly. Removing all plugins didn't help either.

**Comment by XakepSDK** [comment]
Try latest SF

**Comment by PolyacovYury** [comment]
Still the case on build 3338.

**Comment by Yeregorix** [comment]
Try disabling Panda's redstone and tell us if this bug still exists

**Comment by PolyacovYury** [comment]
Big thanks for poking me nose-first into the configs. It was panda-redstone. Disabling it brought piston behaviour back to how it should be.
I'd suggest adding some sort of a warning in the config file. I know that there is a link to a bug-report, but comments there don't mention that changes are **this** severe. Something along the lines of "If some redstone contraptions that involve pistons don't work for you - try disabling this before going around ringing bells" would be enough.
The issue may be closed.
PY out.

**Comment by bloodmc** [comment]
@PolyacovYury Please provide a test world with a few BUD switch designs that are having issues. Also make sure to explain the bugs you are seeing in detail.

**Comment by ryantheleach** [comment]
@PolyacovYury It was our understanding that the Panda Redstone changes **didn't** change the behavior of budded pistons, unless they were already directional.

You can read more about the fixes here: https://www.youtube.com/watch?v=NEMARMNvDsw

https://bugs.mojang.com/browse/MC-11193?focusedCommentId=320079&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-320079

It may be that the changes have unintended consequences, and that we should instead be looking towards bundling 'turbo redstone' instead.

https://bugs.mojang.com/browse/MC-81098?focusedCommentId=441279&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-441279

**Comment by Yeregorix** [comment]
Maybe we can add an option like : `redstone_algorithm=vanilla` (or `panda` or `turbo`)

**Comment by bloodmc** [comment]
Closing as this is an issue with panda which is not enabled by default.

**Comment by ryantheleach** [comment]
To clarify:

We are not accepting bugs in alternate redstone providers, these optimizations are provided for convenience and unless it can be proven that our implementation of them is out of date / wrong, vs the same optimization on Vanilla, e.g. CarpetMod or "Panda's Redstone Mod" then we won't be accepting bug reports for them.

**IF** there is bug that is fixed in a later version of the modification, we will consider accepting it.
