### ISSUE TITLE
plese help my extreme reactor not work

### ISSUE THREAD

**Issue by Shybella** [SpongePowered/SpongeForge#2339]
hello i need personal support for my exttreme reackers not work spongegorge 3338

**Comment by Dockter** [comment]
Please be more specific.

**Comment by Shybella** [comment]
This is why It's important to discuss issues before reporting them here. It stops this. Especially with test builds that break nearly everything sometimes.

**Comment by Lemmmy** [comment]
or you could just be like a normal person and follow the issue template; include your sponge+forge version, full mod + plugin list, a minimal reproduction case, and all relevant logs

**Comment by Shybella** [comment]
Sponge testing discord needs to be completely streamlined for testing and not setup as personal support for latest builds.
