### ISSUE TITLE
Error spam with Forge Multipart: "TileEntity is not registered"

### ISSUE THREAD

**Issue by TheOpalium** [SpongePowered/SpongeForge#2341]
**I am currently running**

- SpongeForge version:  1.12.2-2705-7.1.0-BETA-3304
- Forge version: 14.23.4.2735
- Java version: OpenJDK 1.8.0_171
- Operating System: Ubuntu 16.04 64bit

- Plugins/Mods:
Mods (172):
`Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, /dank/null, AE2 Stuff, Actually Additions, Actually Baubles, Advanced Generators, Advanced Solar Panels, AppleCore, AppleSkin, Applied Energistics 2, Astral Sorcery, AutoRegLib, Avaritia, BD Lib, Bad Wither No Cookie! Reloaded, Baubles, Better Builder's Wands, BiblioCraft, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Biomes O' Plenty, Blood Magic: Alchemical Wizardry, Bookshelf, Botania, Brandon's Core, Builders Guides, Chameleon, Chisel, Chisels & Bits, Chunk Pregenerator, Clumps, CoFH Core, CoFH World, CodeChicken Lib, Compact Machines 3, Cooking for Blockheads, CraftTweaker JEI Support, CraftTweaker2, Cucumber Library, Dark Utilities, Decocraft, DrZhark's CustomSpawner, DrZhark's Mo'Creatures Mod, Draconic Evolution, Dynmap, ET Lunar, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, EnderStorage, Environmental Tech, Erebus, Extra Cells 2, Extra Utilities 2, Extreme Reactors, Fast Leaf Decay, FastWorkbench, FindMe, Flux Networks, Foamflower, Forestry, Forge Microblocks, Forge Multipart CBE, Galacticraft Core, Galacticraft Planets, Guide-API, Hammer Core, Immersive Engineering, IndustrialCraft 2, Iron Backpacks, Just Enough Items, KleeSlabs, Lapis Stays in the Enchanting Table, MagicBees, Mantle, McJtyLib, Mekanism, Micdoodle8 Core, Minecraft Multipart Plugin, MrTJPCore, Mystical Agradditions, Mystical Agriculture, Natura, Nether Gold Ore, NetherEx, NetherPortalFix, NoMoreRecipeConflict, Not Enough Wands, NotEnoughIDs, OMLib, Open Modular Turrets, OpenBlocks, OpenComputers, OpenComputers (Core), OpenModsLib, OpenModsLib Core, Orbis API, Ordinary Coins, Overloaded, Pendant Of Life, PlusTiC, ProjectE, ProjectRed Core, ProjectRed Fabrication, ProjectRed Illumination, ProjectRed Transmission, ProjectRed integration, Quark, RFTools, RFTools Dimensions, RandomPatches, Ranged Pumps, Reborn Core, Redstone Flux, Refined Avaritia, Refined Storage, Refined Storage Addons, Roguelike Dungeons, Solar Flux Reborn, SonarCore, Spice of Life: Carrot Edition, Steve's Carts 2, Storage Drawers, Thaumcraft, The One Probe, The Twilight Forest, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thut Core, Thut's Tech, ThutCore Compat, TickProfiler, Tinkers Tool Leveling, Tinkers' Construct, Tomb Many Graves, TombManyGraves2 API, TorchMaster, UniDict, Universal Modifiers, Valkyrie Lib, VanillaFix, Vending, Vivecraft Forge Extensions, Vivecraft Forge Extensions Core, WanionLib, Woot, World Utils, WorldEdit, XNet, Zero CORE, p455w0rd's Library, projectred-compat, ptrmodellib`

Plugins (26):
`Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, BungeeTabListPlus-SpongeBridge, CatClearLag, GriefPrevention, Holograms, HomeSweetHome, KatLib, LangSwitch, LuckPerms, MMCReboot, MMCRestrict, MagiBridge, Nucleus, Pieconomy, PlaceholderAPI, ProjectCore, ProjectPortals, SleepVote, Tab Modifier, Title Broadcaster, UltimateChat, VillagerShops, latch`

**Issue Description**
Another console spam issue. When using SpongeForge together with ProjectRed/ForgeMultipart, Sponge will sometimes start to constantly spit out "TileEntity is not registered" errors in the server console around every minute. It will spit an error for every single ForgeMultipart TileEntity.

Here's the log again. Examples of this error can be seen from line 6340 onwards.
https://gist.github.com/TheOpalium/9c40fb2f913033b316b50a90c4462f66

Here as well, I first contacted the devs of ForgeMultipart, which referred me to here insisting it's a Sponge issue: https://github.com/TheCBProject/ForgeMultipart/issues/33

Your help, once again, is very appreciated!

**Comment by phit** [comment]
https://github.com/SpongePowered/SpongeCommon/commit/be074bd36d9f07b8fd2a1ec4241aa1d96cd132fe
