### ISSUE TITLE
Serious lag (>0.2TPS) on a very light modpack (No issue without SpongeForge), and insane RAM usage (+64G)

### ISSUE THREAD

**Issue by Aang23** [SpongePowered/SpongeForge#2345]
**I am currently running**

- SpongeForge version: Custom build from commit https://github.com/SpongePowered/SpongeForge/commit/e184c35b0823c8572754441c205fb909395d09e9
- Forge version: 14.23.4.2739 (I changed it in my custom build, because TE requires it now)
- Java version: Java 8
- Operating System: Debian Stretch, running on a Dedicated Ryzen 7 1700X @4.2 Ghz with 64G of RAM. (16 allocated to the server).

- Plugins/Mods:
Biome_Bundle-1.12.2-v6.1.jar
CatClearLag-0.8.jar
Chisel-MC1.12.2-0.2.0.31.jar
CoFHCore-1.12.2-4.5.3.20-universal.jar
CoFHWorld-1.12.2-1.2.0.5-universal.jar
CodeChickenLib-1.12.2-3.2.0.345-universal.jar
CustomNPCs_1.12.2(09jul18).jar
LuckPerms-Sponge-4.2.54.jar
Nucleus-1.4.6-S7.0-MC1.12.2-plugin.jar
OpenComputers-MC1.12.2-1.7.2.67.jar
OpenTerrainGenerator-1.12.2+-+v6.jar
RedstoneArsenal-1.12.2-2.5.1.13-universal.jar
RedstoneFlux-1.12-2.0.2.3-universal.jar
SimplyJetpacks2-1.12.2-2.2.7.45.jar
ThermalDynamics-1.12.2-2.5.1.14-universal.jar
ThermalExpansion-1.12.2-5.5.0.29-universal.jar
ThermalFoundation-1.12.2-2.5.0.19-universal.jar
ThermalInnovation-1.12.2-0.3.0.7-universal.jar
TickProfiler-1.12-0.0.4.jar
UndergroundBiomesConstructs-1.12-1.2.1.jar
jei_1.12.2-4.11.0.206.jar
refinedstorage-1.6.jar
spongeforge-1.12.2-2739-7.1.0-BETA-0.jar

**Issue Description**
The world have just been generated with Biome Bundle, I'm curently the only player using it. No modded tileentities are in use. Note that terrain gen is VERY slow.
Entities are laggy, generating terrain at normal walking speed makes the server drop to 4TPS, even using real time.
Opening any inventories needs 10s to be done.

As I tough it could be an OTG bug, I tried on a default world, same issue.
I tried without plugins, same issues, without Sponge, no issues at all. Note that /sponge timings and /profile does not actually show anything that could explain this kind of lag.

Logs : https://gist.github.com/Fungie2134/696a63f106f4d0d52ada62d5bdd91b4f

Bonus : A >1 TPS 
https://ibb.co/fyR9UT
I just got 0.17 TPS before being kicked for "Timed out"... And 10 - 15 minutes after, I got this : 
https://gist.github.com/Fungie2134/877773bb1622dd504d9691ed0218066c
Now the server is slowy crashing, and I am unable to stop it with killall / ^C, the only solution I have is rebooting the server. 
EDIT : 5 mins after, it crash because it had overloaded the swap and ram... It used way more than what I had allowed...

**Comment by Zidane** [comment]
Closing as we do not support custom SpongeForge builds.
