### ISSUE TITLE
Shulker duplication with PortalGun

### ISSUE THREAD

**Issue by LemADEC** [SpongePowered/SpongeForge#2346]
**I am currently running**
- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3358
- Forge version: 14.23.4.2739
- Java version: 1.8.x
- Operating System: CentOS and Windows

- Plugins/Mods:
iChunUtil-1.12.2-7.1.4
PortalGun-1.12.2-7.0.2

**Issue Description**
1- create new world in creative, flat
2- place a shulker box (any color)
3- add a diamond in the shulker box
4- select your portal gun, target the shulker box and press G to pick it up
=> with Sponge, the box is dropped as item without content. The original box can still be placed with the G key, without loosing its content.
=> without Sponge, no item is dropped.

**Comment by Shybella** [comment]
I also experience this problem, this can also be done with block breakers from several different mods.

**Comment by SawFowl** [comment]
In protected areas, the portal cannon, when the G button is pressed, deletes the blocks.

**Comment by Shybella** [comment]
There is a bigger issue here beyond just mod incompatibility. You can reproduce this same dupe effect without mods on shulker boxes. This stuff does not happen with SF uninstalled.

Even if the mods are at fault, which is 3-5 mods currently able to reproduce this same dupe in several ways, it does not happen with SF. Therefore, SF is the problem even if its the mods fault. Consideration needs to be given here.

**Comment by phit** [comment]
@Shybella write a simple reproduction without mods or a minimal mod list needed, that can help reproducing it quicker in dev env

**Comment by LemADEC** [comment]
The initial report already reproduced the bug with a single mod, what do you need more?

**Comment by phit** [comment]
sorry, I was mainly referring to this
> You can reproduce this same dupe effect without mods on shulker boxes.

**Comment by phit** [comment]
can't reproduce this with pistons.. but I did reproduce this with the portal gun

PortalGun-1.12.2-7.0.2.jar
spongeforge-1.12.2-2705-7.1.0-BETA-3460.jar
iChunUtil-1.12.2-7.1.4.jar

**Comment by LemADEC** [comment]
Issue is reproduced with Dark Matter pickaxe in any non-standard mode. Default keys are G to toggle mode, and V to increase power.

spongeforge-1.12.2-2705-7.1.0-BETA-3422 in SSP
ProjectE-1.12-PE1.3.1B

Also reproduced in SMP with full pack running spongeforge-1.12.2-2705-7.1.0-BETA-3455.

Notable difference: ProjectE is open source.

**Comment by gabizou** [comment]
Give the new build a shot. I'm almost positive the commit fixed very much the same issue with ProjectE.

**Comment by LemADEC** [comment]
Issue is still reproduced with a fresh world including:
- spongeforge-1.12.2-2705-7.1.0-BETA-3465
- ProjectE-1.12-PE1.3.1B
- jei_1.12.2-4.12.1.217

Issue is still reproduced with a fresh world including:
- ProjectE-1.12-PE1.3.1B
=> not a sponge issue

Issue is no longer reproduced with
- spongeforge-1.12.2-2705-7.1.0-BETA-3465
- PortalGun-1.12.2-7.0.2
- iChunUtil-1.12.2-7.1.4

=> issue is fixed
