### ISSUE TITLE
IC2 and SpongeForge spam in console

### ISSUE THREAD

**Issue by TriADeX** [SpongePowered/SpongeForge#2347]
- SpongeForge version:  1.12.2-2705-7.1.0-BETA-3346
- Forge version: 14.23.4.2705 
- Java version: jre-8u131

Plugins/mods - https://pastebin.com/hgR4n2Qh

Problem - https://pastebin.com/fV6KDaBe

**Comment by TriADeX** [comment]
Please, fix it https://pastebin.com/q3Cjcrkt

**Comment by phit** [comment]
https://gist.github.com/phit/afdc9c42b3c215f807361f6ac9cc33a1

still an issue on 1.12.2-2705-7.1.0-BETA-3465

repro place down an industrial workbench from IC2 and craft something in it
