### ISSUE TITLE
Time out when load a chunk (?)

### ISSUE THREAD

**Issue by andrebpessoa** [SpongePowered/SpongeForge#2348]
**I am currently running**
- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3358
- Forge version: 14.23.4.2705

**Issue Description**
When a player login in the server, or create a new chunk, all the players take time out, nothing appears on the log or debug files... If they try to login again, says they already logged in. To fix this, I have to force a stop in server and start again

**Comment by Lemmmy** [comment]
Sponge typically recommends you set a world border and pregenerate the entire world, as chunk generation is very expensive.

**Comment by phit** [comment]
no logs or mod/plugin list and it doesn't happen to others, please use our forums or discord for support

**Comment by andrebpessoa** [comment]
I can't send the log here, I send a message for phit on Discord...
