### ISSUE TITLE
Mixin error on Spongeforge upgrade.

### ISSUE THREAD

**Issue by Rsslone** [SpongePowered/SpongeForge#2351]
**I am currently running**

- SpongeForge version: From spongeforge-1.12.2-2705-7.1.0-BETA-3136 TO spongeforge-1.12.2-2705-7.1.0-BETA-3360
- Forge version: 14.23.4.2705 for Minecraft 1.12.2
- Java version: version 1.8.0_152
- Operating System: Win8.1

- Plugins/Mods: Plugins (20): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, ActiveTime, BattleLog, CatClearLag, LuckPerms, MMCLogger, MMCReboot, MMCRestrict, MMCTickets, MagiBridge, Nucleus, Plan, Prism, PrismPlus, Universe Guard 2, Web-API, WorldEdit

Mods (160): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, /dank/null, Advanced Rocketry, Akashic Tome, Alternating Flux, Animania, Antique Atlas, AppleSkin, Applied Energistics 2, Aquaculture, AutoRegLib, Automated Redstone, Avaritia, Bad Wither No Cookie! Reloaded, Baubles, Bed Patch, Better Builder's Wands, Better Records, BiblioCraft, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Biomes O' Plenty, Bonsai Trees, Bookshelf, Brandon's Core, CD4017BE_lib, Car Mod, CedKilleur's End Cake, Ceramics, Chameleon, Chisel, Chisels & Bits, CodeChicken Lib, Compact Solar Arrays, Construct's Armory, Cooking for Blockheads, CosmeticArmorReworked, CraftStudio API, CraftTweaker JEI Support, CraftTweaker2, Despawning Spawners, Diet Hopper, Doomlike Dungeons, Draconic Evolution, Dynamic Surroundings, Engineer's Workshop Reborn, Example Mod, Extra Cells 2, Extra Utilities 2, FTB Guides, FTB Utilities, FTBLib, FastWorkbench, FoamFix, FoamFixCore, Forestry, Good Ol' Currency Mod, Gravestone Mod, Immersive Engineering, Immersive Petroleum, Immersive Tech, InControl, Industrial Foregoing, Industrial Wires, IndustrialCraft 2, InitialInventory, Integration Foregoing, Inventory Tweaks, Iron Backpacks, Iron Chest, JAOPCA, JAOPCASingularities, JEI Bees, Just Enough Items, LagGoggles, MTLib, MagicBees, Magneticraft, Malisis Switches, MalisisCore, MalisisDoors, Mantle, McJtyLib, Mekanism, MekanismTools, MineTweakerRecipeMaker, Mod Tweaker, ModelLoader, Morpheus, MrCrayfish's Furniture Mod, Multi-Storage, Natura, NetherPortalFix, Networks Manager, NuclearCraft, Nutrition, OpenBlocks, OpenComputers, OpenComputers (Core), OpenModsLib, OpenModsLib Core, OreDictInit, Pam's Cookables, Pam's HarvestCraft, Placebo, Platforms, PneumaticCraft: Repressurized, Power Adapters, Quick Leaf Decay, RandomPatches, Ranged Pumps, Reborn Core, Redstone Flux, Roots 2, Shadowfacts' Forgelin, ShetiPhian-Core, Shield Parrying, Signpost, Spartan Shields, Spatial Server Mod, Steve's Carts 2, Storage Drawers, Super Sound Muffler, TESLA, TOP Addons, Tea: The Story, Tesla Core Lib, Tesla Core Lib Registries, Thaumcraft, The One Probe, The Twilight Forest, Thirsty Bottles, Tinkers' Complement, Tinkers' Construct, Totemic, Tree Chopper, UniDict, Vulpes library, Waddles, WanionLib, Water Control Extreme, Water Strainer, Waystones, Wireless Crafting Terminal 2, Wither Skeleton Tweaks, WrapUp, XNet, Zetta Industries, magma_monsters, mob_grinding_utils, p455w0rd's Library

I was upgrading from spongeforge-1.12.2-2705-7.1.0-BETA-3136 TO spongeforge-1.12.2-2705-7.1.0-BETA-3360 and it threw a error and failed to load. See log for details.

https://gist.github.com/Rsslone/9a8c7f992e7d5e3033710a03dd078dbb

**Comment by Zidane** [comment]
[16:44:54] [main/INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.7.4 Source=file:/P:/Dedotated/MCSS/servers/1.12.2/./mods/1.12.2/malisiscore-1.12.2-6.4.0.jar Service=LaunchWrapper Env=SERVER

Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Required mixin config mixins.common.api.json requires mixin subsystem version 0.7.10

MalisisCore needs to upgrade the Mixin version it uses.

**Comment by Dockter** [comment]
I provide additional assistance with this ticket.  Please PM me on Discord.

**Comment by Rsslone** [comment]
Sure, What handle can I reach you at?

**Comment by Dockter** [comment]
@Dockter

**Comment by Rsslone** [comment]
I can't add you without your full ID, mine is Tommy-sama#7966
