### ISSUE TITLE
CustomNPC silenced by 50% of sponge plugins

### ISSUE THREAD

**Issue by Headmower** [SpongePowered/SpongeForge#2352]
System is: Ubuntu 18.04, Java 1.8.0_181.
Versions is: CustomNPCs_1.12.2_09jul18 (also tried older version - same), spongeforge-1.12.2-2705-7.1.0-BETA-3355 (also tried recommended build - same),  flexiblelogin-0.17.4 (tried older version - same), RealisticChat-1.0.0. 

Issue is: 
There is a mod CustomNpc on my spongeForge server, it works great without plugins or with some of them. When I put CustomNpc together with a plugin (tested with flexiblelogin or RealisticChat, with any of it situation is the same) in a spongeForge server, NPC's created with CustomNPC stops speaking randomly. I mean you can set their speeches while configuring NPC and that NPC will say something in chat (for exapmle when he sees agro mob and starts attack, or just in random moment), and without such plugins as flexiblelogin or RealisticChat it is working. With any one of these - no, NPC's speak only if you interact with them by right-click.

Tracelogs [here](https://pastebin.com/PejVRaa4)

**Comment by Zidane** [comment]
Fixed in the latest builds.
