### ISSUE TITLE
RCON overloads all CPU cores

### ISSUE THREAD

**Issue by Ewallee** [SpongePowered/SpongeForge#2354]
- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3361
- Forge version: 1.12.2-forge1.12.2-14.23.4.2744
- Java version: 8
- Operating System: ubuntu 18.04

- Plugins/Mods: no mods, no plugins

Everything works as it should, until I start using RCON(sending messages and commands to servers console)
Steps to reproduce the error:
Start a sponge server 1.12.2 (actually all the latest sponge versions) and start sending messages  with RCON. After ca 10-12 messages/commands all of the servers CPU cores will be overloaded.

https://i.imgur.com/rgrrJ9D.jpg

The same happens on Windows:

https://i.imgur.com/0kuXLA2.jpg

Server log: https://pastebin.com/gSg81faa

**Comment by ryantheleach** [comment]
!move sc

**Comment by ryantheleach** [comment]
~move to sc

**Comment by limbo-app** [comment]
Hey @Ewallee! I've moved your issue to [SpongePowered/SpongeCommon#2038](https://github.com/SpongePowered/SpongeCommon/issues/2038).
