### ISSUE TITLE
The Nether world make server overload

### ISSUE THREAD

**Issue by MoeShimaKaze** [SpongePowered/SpongeForge#2356]
- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3357
- Forge version: forge-1.12.2-14.23.4.2705-universal
- Java version: Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
- Operating System:Windows Server 2016
- Plugins:Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge,  FastAsyncWorldEdit, AdamantineShield, AutoTabStop, CarrotShop, CatClearLag, EasyKits, EasyScoreboards, EconomyLite, GriefPrevention, Holograms, LuckPerms, MMCReboot, Mirage, Nucleus, PixelAutoMessages, PlaceholderAPI, ProjectCore, ServerListPlus, StackBan, TitleMOTD, VirtualChest, WorldEdit, latch
- Mods:Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AI Improvements, Advanced Solar Panels, AppleCore, Applied Energistics 2, Astral Sorcery, Avaritia, Baubles, Botania, Brandon's Core, ChinjufuMod, Clumps, CodeChicken Lib, CoroUtil Library, CraftTweaker JEI Support, CraftTweaker2, Draconic Evolution, DummyCoreUnofficial, Eternal Singularity, Extended Mod Config, Extended Renderer, Extra Planets, FrogCraft: Rebirth, Galacticraft Core, Galacticraft Planets, Globe, Guide-API, Hammer Core, HeatAndClimateASM, HeatAndClimateLib, HeatAndClimateMod, Hunger Overhaul, Industrial Foregoing, IndustrialCraft 2, Infernal Mobs, JapariCraftMod, Just Enough Items, MJRLegendsLib, MTLib, Micdoodle8 Core, MineTweakerRecipeMaker, Mod Tweaker, MoreSwordOnline, NoMoreRecipeConflict, Pam's HarvestCraft, Redstone Flux, Rustic, Shadowfacts' Forgelin, SpaceX, TeamLapen Library, Tesla Core Lib, Tesla Core Lib Registries, Thaumcraft, Thaumic Additions: Reconstructed, Thaumic Bases, Thaumic Potatoes 2, Thaumic Terminal, The Eight Fabled Blades, The Spice of Life, Vampirism, VampirismIntegrations, WanionLib, Weapon Levels, Zombie Players, galacticrafttweaker
- Timings:https://timings.aikar.co/?id=44fc60d1ba254c08a3cdcd4e6b2e3ad9
i don't know why the Nether world make the server running so slowy,i think the problem is about sponge
so could you fixed this bug?

**Comment by ryantheleach** [comment]
The Tiimings report fingers Fire tick updates in the nether and the HeatAndClimate mod as potential suspects. There's also a small amount of chunk unloading.

With the HeatAndClimate Mod, + other mods in your pack, Are a large number of your users using the nether?

Was the nether pregenerated along with the rest of the worlds, or are you generating as you go?

**Comment by MoeShimaKaze** [comment]
the nether pregenerated along with the rest of the worlds
however,my server's player just enter into nether world in a short time and leave,but the nether world cause so large lag and make the server overload,and no player in the nether world,but when i unload the nether world,all thing restore to normal level

**Comment by phit** [comment]
looks like HeatAndClimateLib is doing things when fire ticks which obviously happens a lot in the nether, take it to them doesn't look related to Sponge
