### ISSUE TITLE
HeatAndClimate Mod running on SpongeForge cause the Mod's item problem

### ISSUE THREAD

**Issue by MoeShimaKaze** [SpongePowered/SpongeForge#2357]
**I am currently running**
- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3364 
- Forge version: forge:1.12.2-14.23.4.2705
- Java version: Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
- Operating System:Windows Server 2016
- HeatAndClimate Version:HeatAndClimateMod_1.12.2-2.5.7(least)

- Plugins:Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, FastAsyncWorldEdit, AdamantineShield, AutoTabStop, CarrotShop, CatClearLag, EasyKits, EasyScoreboards, EconomyLite, GriefPrevention, Holograms, LuckPerms, MMCReboot, Mirage, Nucleus, PixelAutoMessages, PlaceholderAPI, ProjectCore, ServerListPlus, StackBan, TitleMOTD, VirtualChest, WorldEdit, latch

- Mods:Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AI Improvements, Advanced Solar Panels, AppleCore, Applied Energistics 2, Astral Sorcery, Avaritia, Baubles, Botania, Brandon's Core, ChinjufuMod, Clumps, CodeChicken Lib, CoroUtil Library, CraftTweaker JEI Support, CraftTweaker2, Draconic Evolution, DummyCoreUnofficial, Eternal Singularity, Extended Mod Config, Extended Renderer, Extra Planets, FrogCraft: Rebirth, Galacticraft Core, Galacticraft Planets, Globe, Guide-API, Hammer Core, HeatAndClimateASM, HeatAndClimateLib, HeatAndClimateMod, Hunger Overhaul, Industrial Foregoing, IndustrialCraft 2, Infernal Mobs, JapariCraftMod, Just Enough Items, MJRLegendsLib, MTLib, Micdoodle8 Core, MineTweakerRecipeMaker, Mod Tweaker, MoreSwordOnline, NoMoreRecipeConflict, Pam's HarvestCraft, Redstone Flux, Rustic, Shadowfacts' Forgelin, SpaceX, TeamLapen Library, Tesla Core Lib, Tesla Core Lib Registries, Thaumcraft, Thaumic Additions: Reconstructed, Thaumic Bases, Thaumic Potatoes 2, Thaumic Terminal, The Eight Fabled Blades, The Spice of Life, Vampirism, VampirismIntegrations, WanionLib, Weapon Levels, Zombie Players, galacticrafttweaker

because of my bad english,please see this Video to know what is this problem
https://youtu.be/UwhPsTappbs
The problem just like the video show,but it doen't appear in single-player game...
please fixed this problem,thank you very much

**Comment by ryantheleach** [comment]
Heat and Climate Coremod Library: https://github.com/defeatedcrow/HeatAndClimateLib
Heat and Climate Mod: https://github.com/defeatedcrow/HeatAndClimateMod

https://github.com/defeatedcrow/HeatAndClimateLib/blob/1.12.1_master/java/defeatedcrow/hac/core/base/DCItem.java#L71

I wonder why it's doing that null check on player.

**Comment by bloodmc** [comment]
No idea what this mod is attempting to do because the code makes no sense at all. The problem is the mod always returns a result of PASS which will cause Sponge to restore. The mod needs to follow the item use method contract and return SUCCESS if it was successful. Log a ticket with mod as it is their fault.

**Comment by defeatedcrow** [comment]
I apologize for making ugly code with no sense. It will be fixed by next update.
Since this is the base class of other Items, it seems correct to call the super method.
