### ISSUE TITLE
Player lost connection

### ISSUE THREAD

**Issue by MoeShimaKaze** [SpongePowered/SpongeForge#2358]
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3357
- Forge version: forge-1.12.2-14.23.4.2705-univcersal
- Java version: Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
- Operating System:Windows Server 2016
- Galacticraft Version:4.0.1-181(least)
- BungeeCord Version:HexaCord-201
- Plugins:Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, FastAsyncWorldEdit, AdamantineShield, AutoTabStop, CarrotShop, CatClearLag, EasyKits, EasyScoreboards, EconomyLite, GriefPrevention, Holograms, LuckPerms, MMCReboot, Mirage, Nucleus, PixelAutoMessages, PlaceholderAPI, ProjectCore, ServerListPlus, StackBan, TitleMOTD, VirtualChest, WorldEdit, latch

- Mods:Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AI Improvements, Advanced Solar Panels, AppleCore, Applied Energistics 2, Astral Sorcery, Avaritia, Baubles, Botania, Brandon's Core, ChinjufuMod, Clumps, CodeChicken Lib, CoroUtil Library, CraftTweaker JEI Support, CraftTweaker2, Draconic Evolution, DummyCoreUnofficial, Eternal Singularity, Extended Mod Config, Extended Renderer, Extra Planets, FrogCraft: Rebirth, Galacticraft Core, Galacticraft Planets, Globe, Guide-API, Hammer Core, HeatAndClimateASM, HeatAndClimateLib, HeatAndClimateMod, Hunger Overhaul, Industrial Foregoing, IndustrialCraft 2, Infernal Mobs, JapariCraftMod, Just Enough Items, MJRLegendsLib, MTLib, Micdoodle8 Core, MineTweakerRecipeMaker, Mod Tweaker, MoreSwordOnline, NoMoreRecipeConflict, Pam's HarvestCraft, Redstone Flux, Rustic, Shadowfacts' Forgelin, SpaceX, TeamLapen Library, Tesla Core Lib, Tesla Core Lib Registries, Thaumcraft, Thaumic Additions: Reconstructed, Thaumic Bases, Thaumic Potatoes 2, Thaumic Terminal, The Eight Fabled Blades, The Spice of Life, Vampirism, VampirismIntegrations, WanionLib, Weapon Levels, Zombie Players, galacticrafttweaker ﻿

i use the BungeeCord
and i enter into a server,and go to galacticraft Planet world,and you know, you must Press Shift to leave Landing warehouse

but when player press Shift to leave,they lost connection

the error log is:https://pastebin.com/S7kiRbfV

**Comment by Zidane** [comment]
GalacticCraft is dismounting off the main server thread. Not a Sponge issue.

**Comment by MoeShimaKaze** [comment]
ok,thank you.i will repeat at GalacticCraft
