### ISSUE TITLE
Many errors. Conflict with the CustomNPCs mod.

### ISSUE THREAD

**Issue by SawFowl** [SpongePowered/SpongeForge#2359]
**I am currently running**

- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3365
- Forge version: 14.23.4.2747
- Java version: Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
- Operating System: Debian 9

- Mods (50): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Better Questing, CoFH Core, CoFH World, CodeChicken Lib, Console Filter, Construct's Armory, CraftTweaker JEI Support, CraftTweaker2, CreativeCore, CreativeCoreDummy, CustomNPCs, Deadly Monsters, Fishing Net Mod, Forestry, Hammer Core, HoloInventory, Immersive Engineering, InstantUnify, Iron Chest, ItemPhysic, Just Enough Items, LagGoggles, Mantle, McJtyLib, MrCrayfish's Furniture Mod, Netherending Ores, QuestUtils, Quick Leaf Decay, Reborn Core, RebornStorage, Redstone Arsenal, Redstone Flux, Refined Storage, Solar Flux Reborn, Standard Expansion, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Tinkers' Construct, Tree Chopper, UniDict, VanillaFix, WanionLib

- Plugins (28): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge,  FastAsyncWorldEdit, BeanCore, CatClearLag, CommandSync, EconomyLite, GriefPrevention, HuskyCrates, HuskyUI, JobsLite, LangSwitch, LuckPerms, MineReset, Nucleus, PayDay, PlaceholderAPI, ProjectCore, StackBan, UltimateChat, UniversalMarket, VillagerShops, VirtualChest, VirtualTool, WorldEdit, spark

**Issue Description**
When working with the CustomNPCs mod, a lot of errors appear in the console.

Logs https://gist.github.com/Mr-Krab/154550f57aef7b784d9b452d6bc2f668

**Comment by SawFowl** [comment]
There is also a problem with executing commands on behalf of the console.

**Comment by ryantheleach** [comment]
Remapped Trace: https://gist.github.com/ryantheleach/888a90c77e1181d4b507750bb1c0156f

```
The PhaseState having an exception: EntityTickPhase 
The PhaseContext: 
- Owner: EntityPlayerMP ['Kirifan' / 95367, l = 'world', x = 585.60, y = 72.00, z = -789.74] 
- Source: EntityCustomNpc ['Отец Григорий' / 7419, l = 'world', x = 616.50, y = 69.00, z = -797.50] 
- CapturedBlockPosition: CaptureBlockPos {pos = null, world = Optional.empty} 


StackTrace: 
java.lang.ClassCastException: net.minecraft.util.text.TextComponentString can not be cast to net.minecraft.util.text.TextComponentTranslation 
org.spongepowered.mod.event.ForgeToSpongeEventFactory.createAndPostMessageChannelEventChat (ForgeToSpongeEventFactory.java:337) 
org.spongepowered.mod.event.ForgeToSpongeEventFactory.createAndPostSpongeEvent (ForgeToSpongeEventFactory.java:173) 
org.spongepowered.mod.event.SpongeModEventManager.post (SpongeModEventManager.java:314) 
net.minecraftforge.fml.common.eventhandler.EventBus.post (EventBus.java:665) 
net.minecraftforge.fml.common.eventhandler.EventBus.post (EventBus.java:639) 
noppes.npcs.entity.EntityNPCInterface.saySurrounding (EntityNPCInterface.java:931) 
noppes.npcs.ai.EntityAIWorldLines. startExecuting (EntityAIWorldLines.java:27) 
net.minecraft.entity.ai.EntityAITasks. onUpdateTasks (SourceFile: 102) 
net.minecraft.entity.EntityLiving. updateEntityActionState (EntityLiving.java:763) 
net.minecraft.entity.EntityLivingBase. onLivingUpdate (EntityLivingBase.java:2352) 
net.minecraft.entity.EntityLiving. onLivingUpdate (EntityLiving.java:577) 
noppes.npcs.entity.EntityNPCInterface. onLivingUpdate (EntityNPCInterface.java:403) 
net.minecraft.entity.EntityLivingBase. onUpdate (EntityLivingBase.java:2172) 
net.minecraft.entity.EntityLiving. onUpdate (EntityLiving.java:295) 
noppes.npcs.entity.EntityNPCInterface. onUpdate (EntityNPCInterface.java:291) 
noppes.npcs.entity.EntityCustomNpc. onUpdate (EntityCustomNpc.java:50) 
org.spongepowered.common.event.tracking.TrackingUtil.tickEntity (TrackingUtil.java:160) 
net.minecraft.world.WorldServer.redirect $ onCallEntityUpdate $ zlo000 (WorldServer.java:2986) 
net.minecraft.world.World. updateEntityWithOptionalForce (World.java:4154) 
net.minecraft.world.WorldServer. updateEntityWithOptionalForce (WorldServer.java:832) 
net.minecraft.world.World. updateEntity (World.java:1952) 
net.minecraft.world.World. updateEntities (World.java:6596) 
net.minecraft.world.WorldServer. updateEntities (WorldServer.java:2300) 
net.minecraft.server.MinecraftServer. updateTimeLightAndEntities (MinecraftServer.java:767) 
net.minecraft.server.dedicated.DedicatedServer. updateTimeLightAndEntities (DedicatedServer.java:396) 
net.minecraft.server.MinecraftServer. tick (MinecraftServer.java:668) 
net.minecraft.server.MinecraftServer.run (MinecraftServer.java:526) 
java.lang.Thread.run (Thread.java:748) 
Phases Remaining: 

Minecraft: 1.12.2 
SpongeAPI: 7.1.0-SNAPSHOT-7105dfc 
SpongeForge: 1.12.2-2705-7.1.0-BETA-3365 
Minecraft Forge: 14.23.4.2745 
```

**Comment by Aaron1011** [comment]
See if build `1.12.2-2705-7.1.0-BETA-3370` fixes your issues.

**Comment by SawFowl** [comment]
@Aaron1011 The next 2 days I will test, then report the results and provide logs.

**Comment by phit** [comment]
@Mr-Krab any update?

**Comment by SawFowl** [comment]
@phit Unfortunately, I did not manage to check everything myself, I have had a lot of work recently.
I do not notice any problems in the mod, this problem can be considered solved.
If there are other problems, I will prepare a bug report in the new request.
