### ISSUE TITLE
Phase context stackoverflow + eventual crash when using hatchets for digging [3361]

### ISSUE THREAD

**Issue by johnfriedrich** [SpongePowered/SpongeForge#2360]
**I am currently running**
- SpongeForge version: 3361
- Forge version: 2705

**Issue Description**

Getting PhaseContext errors that are resulting in stackoverflow errors:
https://pastebin.com/XHRxBWrL
https://gist.github.com/Flashback083/ac14e68e497a2b59730ae9ad511e1b0a
https://pastebin.com/EG7vg3u4

This happens when players are digging with a hatchet. Other tools seems to be fine (My guess)

Full log: 
https://pastebin.com/RAsE5b4V

**Comment by Aaron1011** [comment]
Fixed in https://github.com/SpongePowered/SpongeCommon/commit/22954ada090fe9609c272ea59f9f6afd3eb40c55

**Comment by Aaron1011** [comment]
@i9hdkill: There are actually two separate issues going on here - I fixed the 'Failed to process all PhaseContext captured!' one. Can you open a separate issue for the StackOverflowError?

**Comment by Aaron1011** [comment]
Try lowering your `max-block-processing-depth` setting to get a more informative error instead of a `StackOverflowError`.

**Comment by johnfriedrich** [comment]
Pretty sure the hatchet error causes the stackoverflow internally after some time.
Still, if the stackoverflow error comes back, I will let you know
