### ISSUE TITLE
Server crash~

### ISSUE THREAD

**Issue by qq591692157** [SpongePowered/SpongeForge#2361]
I am currently running

SpongeForge version: 3361
Forge version: 2705
Issue Description

The server will not be shut down directly, but will keep refreshing the error, the player all out of line.

https://pastebin.com/VSmrHADH 
https://pastebin.com/ZKqe2zeC

http://www.mediafire.com/file/ap1nccpsybadlka/debug.7z/file

**Comment by ryantheleach** [comment]
@qq591692157 The error message is very long, and you have cut off the bottom.

When the error messages are surrounded by `*`'s

We require the log, (until the first error message has completed) as well as the entire error.

e.g.

```
lots of startup lines
lots of startup lines
lots of startup lines
lots of startup lines
*********
* error *
* error *
* error *
* error *
*********
```

not 

```
lots of startup lines
*********
* error *
* error *
```

**Comment by qq591692157** [comment]
I have uploaded the complete DeBUG file.
http://www.mediafire.com/file/ap1nccpsybadlka/debug.7z/file

**Comment by ryantheleach** [comment]
The Debug Log is different, and doesn't help me in this case.

**Comment by qq591692157** [comment]
The debug log caused the server to keep flushing, so I had to shut down the server to solve the problem.

**Comment by phit** [comment]
looks the same as https://github.com/SpongePowered/SpongeForge/issues/2368
closing this as the other one has more info, so please try latest and add any new info to that issue
