### ISSUE TITLE
Switching worlds sets hotbar selection to be always slot 1 instead of remembering the selected slot

### ISSUE THREAD

**Issue by johnfriedrich** [SpongePowered/SpongeForge#2362]
- SpongeForge version: 3371
- Forge version: 2705

- Mods: Pixelmon

**Issue Description**

When entering another world, the player automatically selects the first slot in the hotbar.
Vanilla MC and Vanilla Forge keep the slot selection.

How to reproduce: Join a vanilla Forge server, build a nether portal. Select another hotbar slot than the first one. Enter the portal. Slot 2 is still selected.
Now join a SpongeForge server. Do the same stuff. You will now end up with Slot 1 selected.

It's just minor, but annoys players if they are switching worlds, try to use their tools they have selected previously and are failing/end up using the wrong tool because Sponge switched the selection back to slot 1.

**Comment by Zidane** [comment]
Tested on latest SpongeCommon and this is no longer an issue.
