### ISSUE TITLE
The server crashed and restarted automatically.

### ISSUE THREAD

**Issue by qq591692157** [SpongePowered/SpongeForge#2363]
I am currently running
SpongeForge version: 3370
Forge version: 2705

Issue Description
The server stops after an error occurs and restarts automatically.

https://pastebin.com/auvwUgez

Full log:
http://www.mediafire.com/file/w6ubdru0gddkfgt/Full%20log.txt

**Comment by qq591692157** [comment]
crash-reports
https://pastebin.com/PR7CtuCy

**Comment by phit** [comment]
see https://github.com/SpongePowered/SpongeForge/issues/2368
