### ISSUE TITLE
Item dupes, if player quit before death.

### ISSUE THREAD

**Issue by TriADeX** [SpongePowered/SpongeForge#2364]
- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3371
- Forge version: 14.23.4.2705
- Java version: jre-8u131

1 Have low hp
2. Activate creeper nearly
3. Another player must stay in same chunk, to be sure, that chunk will not be unloaded.
4. Quit late as possible, before creeper explodes
5 Items drops from your inventory, but inventory isn't cleared.

Plugins (16): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge,  FastAsyncWorldEdit, ActionBroadcaster, AdamantineShield, CatClearLag, GriefPrevention, LuckPerms, MMCReboot, MMCRestrict, Nucleus, SkinChanger, Tab Modifier, WorldEdit

Mods (75): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AE2 Stuff, Advanced Solar Panels, Applied Energistics 2, Aroma1997's Dimensional World, Aroma1997Core, BC Builders, BC Energy, BC Factory, BC Robotics, BC Silicon, BC Transport, BD Lib, Baubles, BiblioCraft, Brandon's Core, BuildCraft, BuildCraft Compat, BuildCraft Lib, Chisel, CoFH Core, CoFH World, CodeChicken Lib, Draconic Evolution, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, Extra Utilities 2, Extreme Reactors, FoamFix, FoamFixCore, Forestry, Forge Microblocks, Forge Multipart CBE, Immersive Engineering, IndustrialCraft 2, Iron Chest, Just Enough Items, Minecraft Multipart Plugin, MrTJPCore, NoDestroy, ProjectRed Core, ProjectRed Expansion, ProjectRed Exploration, ProjectRed Illumination, ProjectRed Relocation, ProjectRed Transmission, ProjectRed Transportation, ProjectRed integration, Redstone Flux, Thaumcraft, Thaumic Tinkerer, The Twilight Forest, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Tree Chopper, UniDict, WanionLib, Zero CORE, worldborder

**Comment by ryantheleach** [comment]
@TriADeX Does this occur without mods?

**Comment by TriADeX** [comment]
@ryantheleach did not check without mods.

**Comment by TriADeX** [comment]
up

**Comment by gabizou** [comment]
@TriADeX We're not likely to start trying to resolve the problem with the requirement of dozens of mods to install to try and replicate the issue. If you can narrow down the issue to as few mods as possible, that would speed up our investigation to resolve the issue.
