### ISSUE TITLE
Server spam - Transaction Class etc

### ISSUE THREAD

**Issue by Keaton1188** [SpongePowered/SpongeForge#2366]
**I am currently running**

- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3374 
- Java version:  Java openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)
- Operating System: CentOS Linux release 7.2.1511

- Plugins/Mods: FTB Continuum. 

**Issue Description**
Hi there, on our Continuum server we are getting massive spam from sponge - transaction class .. etc 

 
![untitled](https://user-images.githubusercontent.com/24898745/43690770-d6896ee2-9907-11e8-9a83-68d7dc33f581.png)

**Comment by ryantheleach** [comment]
This isn't nearly enough information to act on.

Please include the full error message, steps on how to reproduce.

If the log is too large to upload, please upload the log from the start, and ending after including the first few instances of the error you wish to report.

Screenshots of logs are rarely appropriate.

**Comment by phit** [comment]
this was introduced by https://github.com/SpongePowered/SpongeCommon/commit/922cc65c15ee80409e627b99975742b0c9606fae

see also https://github.com/SpongePowered/SpongeForge/issues/2212#issuecomment-410602176

**Comment by Faithcaio** [comment]
Should be fixed with latest
