### ISSUE TITLE
PhaseTracker StackOverflowError BlockAddedSpawns

### ISSUE THREAD

**Issue by DiamondArrow** [SpongePowered/SpongeForge#2368]
**I am currently running**

- SpongeForge version: 3361 and 3368
- Forge version: 2705
- Java version: 1.8.10_171
- Operating System: Ubuntu 16.04.4

- Plugins/Mods: Pixelmon Reforged 6.3.4 + 57 plugins (will provide list if needed). Recently updated Nucleus to 1.4.6, GriefPrevention 646, and Luckperms 4.02.58)

**Issue Description**
Not sure what’s triggering it, and its fairly inconsistent with when it happens. Since updating, I had a day with none and a day with 2 or 3 times. It just keeps spamming and causing massive lag until server restarts.

[This is what it spams a couple times before the spam below](https://gist.githubusercontent.com/DiamondArrow/8506946ee022d30ae8ca47b4500b8a67/raw/72308ab0d44572925f4c7af602a897c4b6aab678/gistfile1.txt
)

[Here’s what it looks like on recommend build 3361](https://gist.githubusercontent.com/DiamondArrow/93442ff2eadcbba7ff32fb7c807a0095/raw/c20e31ebcfee1774d91850043ce7d3966395a1a5/gistfile1.txt)

[Same thing on 3368](https://gist.githubusercontent.com/DiamondArrow/b8ca86e295a292f4dbcc84cd4ab6f9ac/raw/8052b47d3dcb4cfa567f72519a8786158b042cef/gistfile1.txt)

Never happened with previous recommended versions of Sponge 3206, although I did also update Nucleus, Luckperms, and GriefPrevention along with the new sponge build

Most Recent full log:
[2018-08-05-4.log.gz](https://github.com/SpongePowered/SpongeForge/files/2261399/2018-08-05-4.log.gz)

Can provide an old log on request, it's 20gb

Edit: Same issue as https://github.com/SpongePowered/SpongeForge/issues/2363

**Comment by Aaron1011** [comment]
The next build of SpongeForge should provide a more informative error, and stop the spam.

**Comment by gabizou** [comment]
Has there been any more logging output of the overflow or has the overflow ceased?

**Comment by phit** [comment]
posted on discord using latest as the time of writing, i dont see any additional infomation

error: https://gist.github.com/phit/aef1e7e0af6df3296b270a840475c78e
full log: https://gist.github.com/M-Andrade/0fd682da9450a2727b21840dc801f408

**Comment by phit** [comment]
just gonna assume this is fixed, until it pops up again anywhere, haven't seen it posted anywhere in the past few months
