### ISSUE TITLE
Crash with forestry & mystcraft

### ISSUE THREAD

**Issue by zhehedream** [SpongePowered/SpongeForge#2373]
I am currently running
~Forge 1.12.2 2750
~SpongeForge 3383
~mods:  Forestry , Mystcraft

Server will crash in several minutes after creating a new world.
Although the mystcraft hasn't appeared in crash log, I believe it has something to do with it.
I also notice that tons of error messages in server terminal, said
'[Server thread/ERROR] [forestry/]: tried to generate a hive in an unloaded area.'

I also test several situation:
1. sponge+mystcraft, all things are good
2. sponge+forestry, all things are good, no error message like "tried to generate a hive in an unloaded area."
3. mystcraft+forestry, all things are good, no error message like "tried to generate a hive in an unloaded area."

Possible Reason:
Mystcraft will create a dummy world after creating a new world. This dummy world is to calc the chance of minerals of other mods. Forestry will also try to generate hive in this dummy dimension. Sponge might influence the creation of mystcraft world.

Crash report: https://paste.ubuntu.com/p/sMTknFm8Sy/
Full Remapped Crash Report: https://gist.github.com/ryantheleach/21c21d1208379595235ab9e8aa3fb78b

```
java.lang.NullPointerException: Exception in server tick loop
	at org.spongepowered.common.world.WorldManager.getDimensionId(WorldManager.java:1258)
	at net.minecraft.server.MinecraftServer.redirect$onGetWorldProviderForSnooper$zjj000(MinecraftServer.java:3831)
	at net.minecraft.server.MinecraftServer.addServerStatsToSnooper(MinecraftServer.java:1104)
	at net.minecraft.server.integrated.IntegratedServer.addServerStatsToSnooper(IntegratedServer.java:325)
	at net.minecraft.profiler.Snooper.addMemoryStatsToSnooper(SourceFile:111)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:707)
```

**Comment by nickkeane** [comment]
Getting an identical issue to what you're getting, SF 3383 on All The Mods 3 + Mystcraft.

**Comment by Aaron1011** [comment]
Can you re-test on the latest SpongeForge?

**Comment by nickkeane** [comment]
Added Mystcraft and SF 3400 to my All The Mods 3 pack.

Server Loaded, Client Loaded. Created 2 Mystcraft Worlds w/ return linking books. Worlds load fine, going between the worlds multiple times seems to work.

Forestry still gives "tried to generate a hive in an unloaded area" spam on server start w/ Mystcraft and Sponge 3400 and seems to add some time to server startup. Otherwise, it seems to be working.

I do seem to be getting some PhaseTracker log spam on certain creatures or creature spawns.

**Comment by zhehedream** [comment]
I also test with 3400, myst and forestry. The game didn't crash. But the terminal still gives out tons of "tried to generate a hive in an unloaded area" when mystcraft is creating profile dimension.
And it also gives out some error message like "Illegal Async PhaseTracker Access" as well as "Illegal Async Chunk Load" when mystcraft is creating profile dimension.

After the profile dimension creating is finished, no more error message like "tried to generate a hive in an unloaded area".

**Comment by psych0d0g** [comment]
still crashing with 3402 on my end - serverside
[crash-2018-08-23_12.14.43-server.txt](https://github.com/SpongePowered/SpongeForge/files/2314018/crash-2018-08-23_12.14.43-server.txt)

**Comment by zhehedream** [comment]
re-test this on forge 2765 + sponge 3477 + forestry_1.12.2-5.8.1.322 + mystcraft-1.12.2-0.13.6.00
Still gived tons of "tried to generate a hive in an unloaded area"

I tried to generate several dimensions with mystcraft, it works pretty good.

**Comment by phit** [comment]
superseded by https://github.com/SpongePowered/SpongeForge/issues/2704
