### ISSUE TITLE
Console error, causing server to stop for 20 seconds +

### ISSUE THREAD

**Issue by qq591692157** [SpongePowered/SpongeForge#2375]
I am currently running
SpongeForge version: 3383
Forge version: 2705
Java version: 1.8.10_172
Operating System: win2012 r2
Plugins/Mods: Pixelmon Reforged 6.3.4 ironchest-1.12.2-7.0.42.827 + 30 plugins (will provide list if needed). Recently updated Nucleus to 1.4.6, GriefPrevention 646, and Luckperms 4.02.58)

Issue Description
When an error occurs, the console refreshes the error all the time, and it stops the server for 20 seconds + (and sometimes crashes), something like two times today.

console log:
  https://gist.github.com/qq591692157/9d06d9e29231f12078deadb9fb5e9f3d

**Comment by Rasgnarok** [comment]
Here's two variations of it, happens on 3358 and 3361 as well. Pixelmon 6.3.4, no IronChest mod needed: 
https://gist.githubusercontent.com/xPXpanD/460956fd472e922ac71e7fd9c6b95a3c/raw/22dd61fc7ef1c84206904a3a2d766fa670123976/gistfile1.txt
https://gist.githubusercontent.com/Rasgnarok/97e38b4f1242de72d8dae131882461ce/raw/2c05c87431fb049c821d0002f531f443fb47ce35/gistfile1.txt

**Comment by Rasgnarok** [comment]
Forwarded to Reforged's tracker, from Sponge's discord. Will look into the thread messaging.

12:26 PM] gabizou: https://github.com/SpongePowered/SpongeCommon/blob/ada51d882c621af7184be6c12cba6fb13de4a7de/src/main/java/org/spongepowered/common/mixin/core/world/MixinWorldServer.java#L850
[12:26 PM] gabizou: yeah....
[12:26 PM] gabizou: no thread checks in that method
[12:26 PM] gabizou: nowadays there are
[12:27 PM] gabizou: https://github.com/SpongePowered/SpongeCommon/blob/stable-7/src/main/java/org/spongepowered/common/mixin/core/world/MixinWorldServer.java#L925

**Comment by Aaron1011** [comment]
This is a bug in Pixelmon - their NPCLearnMove packet handler is interacting with a player off the main thread (specifically, it's calling `EntityPlayer#openGUI`

For a temporary workaround, set `broken-mod` to `true` in your `global.conf`. Then, add `pixelmon` to the `broken-network-handler-mods` list (also in `global.conf`).
