### ISSUE TITLE
Unable to capture transaction from class org.spongepowered.mod.item.inventory.adapter.IItemHandlerAdapter at index 1

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#2378]
- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3396
- Forge version: 1.12.2 2705

Why is this message always appearing in my console, what should I do: [Sponge]: Unable to capture transaction from class org.spongepowered.mod.item.inventory.adapter.IItemHandlerAdapter at index 1

**Comment by phit** [comment]
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/2366
