### ISSUE TITLE
Spatial IO Applied energistics Phase problem

### ISSUE THREAD

**Issue by beareogaming** [SpongePowered/SpongeForge#2379]
**I am currently running** 1.12.2 test server

- SpongeForge version: beta 3361
- Forge version: 14.23.4.2739
- Java version: Version 8 Update 181
- Operating System: w10 home

- Plugins/Mods: 

Plugins (9): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, Boop, MagiBridge, Nucleus, ProjectCore, StackBan

Mods (151): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AE2 Stuff, Actually Additions, Advanced Generators, Advanced Rocketry, Advanced Solar Panels, Animus, Applied Energistics 2, Astral Sorcery, AttachableGrinder, AutoRegLib, BC Builders, BC Energy, BC Factory, BC Robotics, BC Silicon, BC Transport, BD Lib, Baubles, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Blood Arsenal, Blood Magic: Alchemical Wizardry, Bookshelf, Brandon's Core, BuildCraft, BuildCraft Compat, BuildCraft Lib, Capability Adapter, Chickens, Chisel, CoFH Core, CoFH World, CodeChicken Lib, Compact Solar Arrays, Compacter, Construct's Armory, Dark Utilities, Davinci's Vessels, DeathCounter, Draconic Evolution, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, Equivalent Energistics, Exchangers, Expanded Equivalence, Extra Utilities 2, Extreme Reactors, FoamFix, FoamFixCore, Forestry, Friendship Bracelet, GenDustry, GeneralLaymansAestheticSpyingScreen, Globe, GravityGun, Guide-API, Hammer Core, HatStand, Hats, ICBM-Classic, Immersive Cables, Immersive Engineering, IndustrialCraft 2, Infernal Mobs, Inventory Generators, Iron Tank, JEI Bees, Just Enough Items, KJ Lib, LibEx, LibrarianLib, LibrarianLib Stage 2, Loot Bags, MagicBees, Mantle, MatterOverdrive, McJtyLib, Mekanism, Moar Tinkers, More Bees, More Chickens, Morph-o-Tool, Moving World, MovingWorld CORE, NetherEx, Not Enough Items, OpenBlocks, OpenComputers, OpenComputers (Core), OpenModsLib, OpenModsLib Core, Pam's HarvestCraft, PlusTiC, PortalGun, Power Adapters, ProjectE, RFTools, Redstone Flux, Shadowfacts' Forgelin, Simply Jetpacks 2, Solar Flux Reborn, Sync, Technomancy 2, Thaumcrafft Inventory Scanning, Thaumcraft, Thaumic Tinkerer, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Tinker I/O, Tinker's JEI, Tinkers Tool Leveling, Tinkers' Complement, Tinkers' Construct, Tiny Progressions, Torched, UniDict, Vulpes library, Waila, WanionLib, Waystones, What Are We Looking At, Wireless Crafting Terminal 2, Wizardry, WorldEdit, Yoyos, Zero CORE, careerbees, iChunUtil, p455w0rd's Library

**Issue Description**
When using spatial IO which transfers a region of blocks to another dimension for later retrieval 
several things happen,
1. blocks are not transfered
2. Button used to activate machine is stuck in until broken which will cause more errors in console
3. apon pressing button same error appears as 2.

Note that i have tried testing this with just sponge and applied energistics and nothing else installed, same error occures.

This is just the error itself
https://gist.github.com/beareogaming/84d26511d381968f7190efe8e4366760

and this is the whole log up unto this point
https://gist.github.com/beareogaming/71e19e6ff858efb2f1315493c3f22e35

**Comment by Shybella** [comment]
Still occurring with 3440.

Anything I can do to help provide more information on this?

**Comment by phit** [comment]
closing in favor of https://github.com/SpongePowered/SpongeForge/issues/2384
both issues are quite outdated at this point
