### ISSUE TITLE
Advancement Issue with Monk Mod

### ISSUE THREAD

**Issue by Y0ungSandwich** [SpongePowered/SpongeForge#2380]
**I am currently running**

- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3361 tested with 3399 with same results. 
- Forge version: 1.12.2-2705
- Java version: Java 8
- Operating System:CentOS

- Plugins/Mods:
https://www.atlauncher.com/pack/MechMagic
Nucleus, Economy Lite, Grief Prevention, VShops, Langswitch, Luck Perms

**Issue Description**
The Monk Mod uses its advancements as a guide and progression unlock system. Your first achievement and unlock is from breaking logs with your bare hands. This does not trigger on a server with sponge. The GUI shows up when you break more blocks under the same conditions ( meter fills up with each block until 100% triggering the next unlock.), but no advancements ever trigger thus the mod can not be progressed. This has been tested on multiple packs, with and without Better Advancements, and with and without SpongeForge. Around 19:08 in the log is when two advancements should have triggered but nothing is mentioned. 

https://gist.github.com/Y0ungSandwich/aced89706d605c27b5197c929a49839c

**Comment by phit** [comment]
for reference https://github.com/rwtema/Monk-Mod/blob/master/src/main/java/com/rwtema/monkmod/advancements/criteria/MonkRequirementBreakBlockBareHanded.java#L23

**Comment by ryantheleach** [comment]
That code seems 100% reasonable, Looks like we are doing something badly in regard to forge events.

**Comment by Y0ungSandwich** [comment]
I just found out one of our users has got the mod working by following an outside guide. He says he has advanced through some of the levels but the achievements do not update as reported in the OP. Nothing in the logs during these level progressions still. So I guess the issue is the advancements not triggering? Im sure you guys got it handled just wanted to drop that piece of new info I got. Thanks!

**Comment by Shybella** [comment]
I am also encountering this with monkmod1.4 and SF 3440

**Comment by Shybella** [comment]
http://prntscr.com/kvw13p

Seems to start working at times.

**Comment by Y0ungSandwich** [comment]
Yeah we noticed that too. In console it will spam all levels gained at once. Players can't get past I think level 18 though.

**Comment by Shybella** [comment]
Any updates on this?

**Comment by Y0ungSandwich** [comment]
Glad to see this added to the cleanup! It seems a lot more mods and packs are integrating more and more advancements so this will help a lot! Keep up the good work.

**Comment by phit** [comment]
this should have been resolved a while ago, please let us know if this comes up again

**Comment by Y0ungSandwich** [comment]
Not working as of the latest version of sponge. We have been testing over previous versions with no luck.

**Comment by Zidane** [comment]
Okay so pass over some logs/etc.

**Comment by MeltPels** [comment]
Hey! Im experiencing this on spongeforge for my players right now. I dont have any console spam, (I did see some earlier but cant reproduce this right now).

Its with the DW20 2.5.0 pack. 

What info would you need me to supply?

**Comment by phit** [comment]
make a new issue and fill out the template
