### ISSUE TITLE
Liquids and buckets dupe

### ISSUE THREAD

**Issue by limbo-app** [SpongePowered/SpongeForge#2385]
This issue was originally submitted by @ResponsibleBear in [SpongePowered/SpongeCommon#2061](https://github.com/SpongePowered/SpongeCommon/issues/2061).
___
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3400
- Java version:  64-Bit Server VM (build 25.151-b12, mixed mode)
- Operating System: Debian

- Plugins/Mods:
Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge,  FastAsyncWorldEdit, Broadcast, CarrotShop, CatClearLag, CrazyFeetSponge, DimReseter, GriefPrevention, Holograms, LuckPerms, MMCRestrict, Mirage, Nucleus, Total Economy, UltimateChat, UniversalMarket, WorldEdit

**Issue Description**
Dupe of any liquids and buckets. Details in the video. U have to stay as far away as possible and rmb with a stack of buckets. Sometimes it will destroy source block and also its dupe buckets.

https://youtu.be/T7bECqkE9ag

**Comment by ResponsibleBear** [comment]
Still working guys...
https://youtu.be/CEtXoY1Ie3U
