### ISSUE TITLE
Galacticraft NASA Workbench SpongeForge FATAL on requesting GUI

### ISSUE THREAD

**Issue by Foxgreat** [SpongePowered/SpongeForge#2386]
**I am currently running**
- SpongeForge-3403: 
- Forge-2705: 
- Java Version: 1.8.0_181, Oracle Corporation 
- Operating System: Linux (amd64) version 4.15.0-24-generic
- 113 Plugins/Mods:

Hello there!
I have an issue on my server. While i trying to call for NASA Workbench GUI from Galacticraft it sends FATAL error and not opening workbench from SpongeForge. In singlePlayer works fine, without spongeforge on server works fine too. 

Here's my crash from Debugging GC's screen.
https://gist.github.com/Foxgreat/49d84a99f0788421ac4ce3152bfea8d7

And full Debug and Latest logs (sry for MySQL errors, my bad, working on it)
[debug.log](https://github.com/SpongePowered/SpongeForge/files/2296676/debug.log)
[latest.log](https://github.com/SpongePowered/SpongeForge/files/2296677/latest.log)

**Comment by RedNesto** [comment]
I don't have any issue clicking a NASA Workbench with:
- SpongeForge `1.12.2-2705-7.1.0-BETA-3403` with according Forge version
- GalacticraftCore `1.12.2-4.0.1.181`
- Galacticraft-Planets `1.12.2-4.0.1.181`
- MicdoodleCore `1.12.2-4.0.1.181`

**Comment by gabizou** [comment]
Seeing as @RedNesto so gracefully already tested just sponge forge and galacticraft as their own environment, maybe it's a combination of some coremods along with the two that causes an issue with Galacticraft? @Foxgreat could you try to narrow down which mods are needed to reproduce the issue, testing with 117 mods isn't really within our realm of ideal bug fixing.

**Comment by Foxgreat** [comment]
i will check up now which modification causes that, give me some time please

**Comment by Foxgreat** [comment]
it caused by world-map break from several updates of modpack. In new map it worked fine. It could be closed
