### ISSUE TITLE
Deadlock with Pistons

### ISSUE THREAD

**Issue by Shybella** [SpongePowered/SpongeForge#2389]
**I am currently running**

- SpongeForge version: 3382
- Forge version: 2739
- Java version: 1.8 update 181
- Operating System: Windows Server 2012 R2

- Plugins/Mods: Mods (156): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, /dank/null, Actually Additions, Advanced Generators, Akashic Tome, AppleSkin, Applied Energistics 2, Aroma1997's Dimensional World, Aroma1997Core, Astral Sorcery, AutoRegLib, BD Lib, Bad Wither No Cookie! Reloaded, Baubles, Better Advancements, Better Builder's Wands, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Biomes O' Plenty, Blockcraftery, Blood Magic: Alchemical Wizardry, Bookshelf, Botania, Brandon's Core, Chameleon, ChickenChunks, Chisel, Chisels & Bits, CoFH Core, CoFH World, CodeChicken Lib, CommonCapabilities, Compact Machines 3, Compact Solar Arrays, Cooking for Blockheads, CraftTweaker JEI Support, CraftTweaker2, Cyclops Core, Dark Utilities, DeepResonance, Diet Hopper, Draconic Evolution, ElecCore, Elevator Mod, EluCore, EluLib, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, EnderStorage, Environmental Tech, Exchangers, Extra Utilities 2, Extreme Reactors, FastWorkbench, Flat Colored Blocks, Forestry, Funky Locomotion, GenDustry, Gravestone Mod, Guide-API, Immersive Engineering, Industrial Foregoing, IndustrialCraft 2, Integrated Dynamics, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTunnels-Compat, Iron Backpacks, Iron Chest, JEI Bees, JourneyMap, Just Enough Items, MCMultiPart, MTLib, MagicBees, Mantle, McJtyLib, MeeCreeps, Mercurius, MineTogether, MineTogetherServer, Mod Tweaker, Morph, Morph-o-Tool, Morpheus, NetherPortalFix, Not Enough Wands, OpenComputers, OpenComputers (Core), Pam's HarvestCraft, Placebo, PneumaticCraft: Repressurized, PortalGun, Psi, Quick Leaf Decay, RFTools, RFTools Control, RFTools Dimensions, Ranged Pumps, Reborn Core, RebornStorage, Redstone Arsenal, Redstone Flux, Refined Storage, Refined Storage Addons, Shadowfacts' Forgelin, Simple Inventory sorting, Simply Jetpacks 2, Storage Drawers, Storage Drawers Extras, SwingThroughGrass, TESLA, TOP Addons, Tesla Core Lib, Tesla Core Lib Registries, Thaumcraft, The Lost Cities, The One Probe, The Twilight Forest, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Tinkers' Construct, UniDict, Universal Modifiers, Valkyrie Lib, WanionLib, Wireless Crafting Terminal 2, XNet, Zero CORE, iChunUtil, mob_grinding_utils, p455w0rd's Library

**Issue Description**

Random deadlock with pistons that keeps happening. 
![download](https://user-images.githubusercontent.com/4436776/44304704-dbc12180-a33d-11e8-9a69-27969cd83788.png)
![download](https://user-images.githubusercontent.com/4436776/44304728-7e79a000-a33e-11e8-95b9-bc617921edab.png)

Unable to reproduce or find a way. Asking for method of additional debugging or potential fix.
I can try to provide more information if needed.

Thank you.

**Comment by Shybella** [comment]
![download](https://user-images.githubusercontent.com/4436776/44304724-73bf0b00-a33e-11e8-90fc-f840cd273287.png)

**Comment by Shybella** [comment]
I've not had another occurrence with this. Although, I think it may have something to do with Chisel n Bits and pistons.

**Comment by Shybella** [comment]
Happened again 
![download](https://user-images.githubusercontent.com/4436776/44694813-57138900-aa4a-11e8-9706-a9b76a76ac04.png)

Is there anything that can be done? Running SF: 3414

**Comment by Shybella** [comment]
![download](https://user-images.githubusercontent.com/4436776/45008214-f5b86080-afdb-11e8-830c-0dbed2a86aa7.png)

SF: 3422

**Comment by gabizou** [comment]
You have pistons being cancelled, likely by protections. Nothing really going wrong here on sponge's side. @bloodmc thoughts? I think for some reason we might be capturing blocks on piston movement again (or this is the block update for pistons). I'll have to triple check how they flow again.

I would try to find out where the mass amount of pistons are that are scheduling so many updates.

**Comment by Shybella** [comment]
Thank you for looking into this, gabi.

I do believe it's something to do with GP and pistons. I was able to reproduce this by chance using 3 pistons to push some Chisel n Bits stone inside of a claim.

**Comment by Shybella** [comment]
This is becoming a month old and no avail yet. 

I've allowed pistons to not be tracked by GP and still happening.

**Comment by Shybella** [comment]
As this has not reoccurred in the last 3 weeks, I have my suspicions with either malformed GP claim data or permission issues with piston:extensions being blocked by GP. Could also be caused by Redstone Panda being enabled. Those are the 3 things that has changed, and has gone away because of one of those changes.

I am closing this out if this returns, I'll reopen with more information if it does return
