### ISSUE TITLE
auto-populate broken since config rework

### ISSUE THREAD

**Issue by PorPit** [SpongePowered/SpongeForge#2393]
**I am currently running**

- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3409
- Forge version: forge-1.12.2-14.23.4.2705
- Java version: 1.8
- Operating System: windows server 2012

- Plugins/Mods:
Plugins (27): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, ActionBroadcaster, CMD Item, CarrotShop, CrazyFeetSponge, EconomyLite, EpicBanItem, GriefPrevention, LinkMe, LuckPerms, MCRMB, McrmbCommand, Nucleus, PixelVip, PlaceholderAPI, PlotSquared, ProjectCore, SpongyCord, StackBan, StopUnloadWorld, Twenty Ticks, VirtualChest, VirtualTool, World Polisher
Mods (44): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Advanced Solar Panels, Applied Energistics 2, Baubles, Better Records, Botania, CraftTweaker JEI Support, CraftTweaker2, CraftTweakerSync, CreativeCore, CreativeCoreDummy, CustomNPCs, Extra Planets, FTB Utilities, FTBLib, FoamFix, FoamFixCore, Galacticraft Core, Galacticraft Planets, Immersive Engineering, Immersive Tech, IndustrialCraft 2, Iron Chest, Just Enough Items, MJRLegendsLib, MTLib, Mekanism, MekanismGenerators, Micdoodle8 Core, MineCamera, MineCameraDummy, Mod Tweaker, OnlinePictureFrame, Pam's HarvestCraft, Shadowfacts' Forgelin, Thaumcraft, Wireless Crafting Terminal 2, WorldEdit, p455w0rd's Library

**Issue Description**
when i use the new sponge version（3361 or 3409） 
set the  global config  "tileentity-activation=true" and "auto-populate=true" and restart server
config does not add any tileentities to default settings
but when i use sponge 7.1.0-BETA-3206
the default settings can be generated normally

**Comment by phit** [comment]
this broke in https://github.com/SpongePowered/SpongeCommon/pull/1957

**Comment by phit** [comment]
~move to sc

**Comment by limbo-app** [comment]
Hey @PorPit! I've moved your issue to [SpongePowered/SpongeCommon#2076](https://github.com/SpongePowered/SpongeCommon/issues/2076).
