### ISSUE TITLE
Lag in SpongeCommonEventFactory.callCollideEntityEvent

### ISSUE THREAD

**Issue by LemADEC** [SpongePowered/SpongeForge#2394]
**I am currently running**

- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3404
- Forge version: 14.23.4.2756
- Java version: 1.8.0b171
- Operating System: CentOS

- Plugins/Mods:
https://www.technicpack.net/modpack/fsg-spectracraft.1282933/mods
Plugins (17): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, AdamantineShield, AntiWDL, BetterChunkLoader, Broadcast, Enjin Minecraft Plugin, GriefPrevention, LuckPerms, MagiBridge, Nucleus, Server Backup, SleepVote, Total Economy, WrapperPing
Mods (127): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Aether Legacy, AetherWorks, Akashic Tome, Aquaculture, Astral Sorcery, AutoRegLib, Bad Wither No Cookie! Reloaded, Baubles, Better Builder's Wands, BiblioCraft, Bird's Foods, Blockcraftery, Blood Arsenal, Blood Magic: Alchemical Wizardry, Bloodmoon, Bookshelf, Botania, Chameleon, Chameleon Creepers, Chickens, Chisel, Chop Down Updated, CodeChicken Lib, Comforts, Cooking for Blockheads, Corail Tombstone, Coralreef, CraftStudio API, CraftTweaker JEI Support, CraftTweaker2, Creeper Confetti, Cucumber Library, Cyclops Core, Diet Hopper, Doomlike Dungeons, Dungeon Mods, Dungeons2!, Electroblob's Wizardry, Elevator Mod, EluCore, EluLib, Embers, EvilCraft, EvilCraft-Compat, Exotic Birds, Farming for Blockheads, Fence Jumper, FoamFix, FoamFixCore, Garbage Bins, GottschCore, Guide-API, HardLib, Harder Farming, Harvestables, HelpFixer, Huggable Cactuses, Immersive Craft, Immersive Engineering, Immersive Petroleum, Inventory Pets, Inventory Tweaks, Iron Backpacks, Iron Chest, Just Enough Items, KleeSlabs, LadyLib, LagGoggles, Level Up! Reloaded, LibEx, Lost Souls, Lumen, McJtyLib, MmmMmmMmmMmm, Mob Totems, Mobultion, Moon's Core, Mystical Agriculture, Mystical Agriculture Tiered Crystals, Nature's Compass, NetherEx, Overlord, Placebo, ProjectE, Prospects, Reliquary, Reptile Mod, Roguelike Dungeons, Roots Classic, Runes of Wizardry, Runes of Wizardry - Classic Dusts Pack, ShetiPhian-Core, Silent Lib, Silent's Gems, Silent's Gems: Extra Parts, Simple Storage Network, Snad, Soul Shards - The Old Ways, StepUp, Storage Drawers, SwingThroughGrass, TeamLapen Library, Tell Me, Terraqueous, Thaumcrafft Inventory Scanning, Thaumcraft, Thaumic Periphery, Thaumic Tinkerer, The Lost Cities, TorchMaster, Totemic, Underground Biomes, Vampirism, VampirismIntegrations, VanillaFix, Village Names, Waila, Waystones, WorldEdit, Zoo and Wild Animals Mod: Rebuilt, aqua_creepers

**Issue Description**
After a 10mn profile with 15+ players online, significant CPU load is observed here:
![image](https://user-images.githubusercontent.com/4776032/44349293-0d043380-a49d-11e8-8905-b59b8acb0adb.png)
Upon further investigation, there's 34 different references to the same method org.spongepowered.common.event.SpongeCommonEventFactory.callCollideEntityEvent() for a total of  **2.08 %**
(0.08 + 0.20 + 0.02 + 0.07 + 0.16 + 0.07 + 0.02 + 0.02 + 0.02 + 0.02 + 0.15 + 0.02 + 0.34 + 0.08 + 0.13 + 0.03 + 0.02 + 0.03 + 0.02 + 0.02 + 0.16 + 0.05 + 0.02 + 0.02 + 0.03 + 0.02 + 0.02 + 0.03 + 0.02 + 0.03 + 0.02 + 0.07 + 0.02 + 0.05)

**Comment by LemADEC** [comment]
Is there an option to disable this module until a fix is found?

**Comment by Shybella** [comment]
That is not `significant CPU load` that's normal and yes you can disable collisions in the sponge config but you'll have issues with mob behavior.

**Comment by LemADEC** [comment]
2% is nowhere close to negligible CPU load, get your facts right.

**Comment by gabizou** [comment]
@LemADEC The problem here is that you're compounding what is already negligible CPU performance in individual sections and adding them together to say they're unperformant. Sure, if the actual method itself in a single call site would take 2%, then we'd consider it to be a serious candidate of optimization (much like the costs that were associated with `LocatableBlock.builder()`). The actual method itself is optimized as much as possible, and short of not throwing the events for varying areas of execution, there's not much that can be considered for optimization in the method itself (and the objects it uses, like frames, etc.).

Unless @bloodmc or @Zidane has an idea to make this more performant, I don't believe there's much to optimize in this area.

**Comment by LemADEC** [comment]
Keep in mind we still have 0.20% and 0.30% in there by themselves from a profiling over 5 minutes.
Also, I'm confused on why we have some many places where we trigger those events and what those events are for.

**Comment by ImMorpheus** [comment]
CollideEntityEvent is `Fired when an {@link Entity} collides with one or more {@link Entity}'s.`

Actual profiling:

![before-csm](https://user-images.githubusercontent.com/24737505/44718132-9b387500-aaae-11e8-84c7-55b92467d293.png)
 
![csm-60](https://user-images.githubusercontent.com/24737505/44718133-9bd10b80-aaae-11e8-9556-a8faf78d76bd.png)

There's nothing Sponge can do to improve this method (Part of the time is spent inside `enforceMainThread()`, but [trying to optimize that call](https://github.com/ImMorpheus/SpongeCommon/commit/ca27934f39db94c7855b90fe675d3f506a97b724) shows no considerable improvement.
I suggest you check what mod is listening to CollideEntityEvent. Sponge is not firing that event if there are no listeners.

**Comment by LemADEC** [comment]
Thanks for the explaination!
I understand the call itself can't be significantly improved.
My feeling is that we're calling it too frequently.

In our setup, CollideEntityEvent is used by GriefPrevention. I'll have to check which claim flags use it and if we actually needs those flags. As far as I remember, spawn protection depends on it.

In our profile reports, we see many (60+) references to callCollideEntityEvent().
In some cases, it'll relate to entity movement which I can understand.
In other cases it feels a bit out of place.
Here are 2 examples from a same 30 mn profiling:
1st case
![image](https://user-images.githubusercontent.com/4776032/44748388-f3ec2a00-ab0f-11e8-886a-e5b63b632e03.png)
This is an entity checking if other entities are around. It has nothing to do with an entity colliding with another entity.
Here's the related source code: https://github.com/mcpecommander/Mobultion-mod/blob/master/src/main/java/mcpecommander/mobultion/entity/entities/spiders/EntitySpiderEgg.java#L186

2nd case
![image](https://user-images.githubusercontent.com/4776032/44749062-bee0d700-ab11-11e8-9b0a-418db3ee0146.png)
This is a block pushing entities away from itself.
Assuming Sponge API considers a TileEntity as an Entity, does it make sense to trigger CollideEntityEvent in this case?
Should I understand CollideEntityEvent as way to filter what entities can be seen from a given context?
Here's the related source code: https://github.com/sinkillerj/ProjectE/blob/mc1.12.x/src/main/java/moze_intel/projecte/utils/WorldHelper.java#L525

**Comment by ImMorpheus** [comment]
Ok, I've looked at this a bit more deeply.

We fire the event at the end of `World#getEntitiesWithinAABB` which is used to `Gets all entities of the specified class type which intersect with the AABB`. (**Only if a listener for the event was registered**)

This means there's no need for a collision in the strict sense to happen. It just need something to look for entities in a bounding box. 
Ex. whenever you open a chest, it checks if there's a squid on top of it to see if you can open it.

**Comment by Shybella** [comment]
You should open a issue with ProjectE about that. 

These results don't take into account the number of entities that are causing the collisions. You can control the radius of AABB in the Sponge Config but that will probably break Project E. 

You are worrying yourself over such small impact that you wouldn't even notice if the performance was cut in half. Move on.

**Comment by phit** [comment]
gonna close this we have plenty of options to help with collisions and as gabizou said, there's nothing really left to optimize

**Comment by LemADEC** [comment]
Sounds like denial to me.

**Comment by Zidane** [comment]
@LemADEC 

Have you read the code that is running there? If so, make a PR and prove others wrong. @gabizou gave you a clear and concise definition of what is going on and some changes you can make on your end. Try doing that before running your mouth and making a fool of yourself.
