### ISSUE TITLE
GeographiCraft Support

### ISSUE THREAD

**Issue by SSKirillSS** [SpongePowered/SpongeForge#2396]
SpongeForge: spongeforge-1.12.2-2705-7.1.0-BETA-3361 ;
Forge: forge-1.12.2-14.23.4.2705-universal (and tested on forge-1.12.2-14.23.4.2750-universal) ;
Java: Version 8 Update 181 x64 (build 1.8.0_181-b13) ;
Operating System: Windows 7 Max. x64 ;

Plugins:
Don't have;
Mods:
BiomesOPlenty-1.12.2-7.0.1.2399-universal ;
GeographiCraft-1.12-0.8.9b ; 
RTG-1.12.2-6.1.0.0-beta.5 ; 
spongeforge-1.12.2-2705-7.1.0-BETA-3361 ;

I'm tried to generate new world with dev-build of RealisticTerrainGenerator and Biomes o'Plenty. For work these mods together I must launch server/client with GeographiCraft(Old - ClimateControl). In singleplayer and a vanilla forge server world generated perfectly, but if i'm use a spongeforge, biomes in Biomes o'Plenty doesn't generated, but some trees/plants or decorating blocks will be yet generated successfully.

Logs: https://gist.github.com/SSKirillSS/0a966a76bc24270250a34c7b7f7865d2
Debug: https://gist.github.com/SSKirillSS/fd02d0f955b083cc16a97b5555425ac4
Another my issues to Team-RTG: https://github.com/Team-RTG/Realistic-Terrain-Generation/issues/1293

//If I missed anything - pls, say me about this, I will add this as quickly as possible.

P.S. - Sorry for my English, I'm speak Russian.

**Comment by gabizou** [comment]
@Aaron1011 this is an issue with the map optimization, looks like someone else is accessing the map list?

You can disable the optimization to avoid the crash by turning `map-optimization` off in the global config.

**Comment by SSKirillSS** [comment]
![image](https://user-images.githubusercontent.com/38190325/44423003-85e2b880-a58d-11e8-9d29-8c7423e7f09f.png)
...\config\sponge\global.conf
SpongeForge: spongeforge-1.12.2-2705-7.1.0-BETA-3361
Forge: forge-1.12.2-14.23.4.2705-universal

**Comment by phit** [comment]
@SSKirillSS that is for the crash with 3406

**Comment by SSKirillSS** [comment]
Ok, thx. As for incompatibility - should I wait for the next releases, or did I misunderstood something?

**Comment by phit** [comment]
try again on latest, the map crash is unrelated to the mod incompatibility

gonna make a separate issue for that

**Comment by SSKirillSS** [comment]
I'm update the server spongeforge in main modpack to last build and disable map-optimization (with 2750 forge on server and client).
If you need, this is a load new world with latest spongeforge with disabled map-optimization in test modpack(with the 2705 forge build):
Logs: https://gist.github.com/SSKirillSS/adcc318cd1022e85a71d931475b79872
Debug: https://gist.github.com/SSKirillSS/40c79db5b109f689add27039793a8d81

Screenshots of generating by BOP thing in a server with latest spongeforge and 2705 forge world(It's doesn't working normally, because BOP don't generate own biomes. and only slightly changes the generation of RTG):
![2018-08-21_22 20 02](https://user-images.githubusercontent.com/38190325/44424666-7a45c080-a592-11e8-8283-cd5554457b3b.png)
![2018-08-21_22 22 32](https://user-images.githubusercontent.com/38190325/44424669-7ca81a80-a592-11e8-88a2-d7e4aa2fe8c3.png)
Screenshots of generating by RTG in a server with latest spongeforge and 2705 forge world(It's working normally):
![2018-08-21_22 24 18](https://user-images.githubusercontent.com/38190325/44424840-f0e2be00-a592-11e8-9a2b-1aaa0f7a3a9b.png)

Example of normal generating, that`s work correctly on singleplayer: http://prntscr.com/klctq7 .

**Comment by SSKirillSS** [comment]
Hello, again. I'm installed a last build of SpongeForge(spongeforge-1.12.2-2705-7.1.0-BETA-3416) and create a new test world. The new world was generated by mechanics RTG, but after restart generation is fully broken(I'm don't use /world border load (Nucleus), respectively the world was not fully loaded):
![2018-08-25_12 52 18](https://user-images.githubusercontent.com/38190325/44617153-971a1680-a866-11e8-9c9d-4d6774d297a2.png)

I flew a bit more around the world and found a biome Meadow that, if I remember correctly, belongs to the BOP list:
![2018-08-25_12 50 39](https://user-images.githubusercontent.com/38190325/44617151-93868f80-a866-11e8-97b9-42b7cf87eb60.png)


Maybe this information will somehow help you.
P.S: And, yes. Sorry, but I do not know why issue was closed, I'm don't do that.

**Comment by SSKirillSS** [comment]
Excuse for troubling. Should I'm expect to solve this problem?

**Comment by Aang23** [comment]
Same issue here. No issues with BiomeTweaker.

**Comment by IteratorW** [comment]
Anything new? I'm experiencing the same thing above (bugged chunks) after server reboot, I think. Here's how it looks from DynMap
![image](https://user-images.githubusercontent.com/30198566/58265931-574a7600-7d89-11e9-838e-cdb86adc00d1.png)

**Comment by phit** [comment]
what version are you on and can you check of the seed changed after a restart?

**Comment by IteratorW** [comment]
1. I believe this will answer all the version questions:
![image](https://user-images.githubusercontent.com/30198566/58269021-43a20e00-7d8f-11e9-9d2f-78ba686ccfa6.png)
2. Please wait for this, I will need some time to check that.

**Comment by phit** [comment]
alright so super outdated, please update to the latest version, there was a bug with seeds changing that was fixed in later versions https://github.com/SpongePowered/SpongeCommon/pull/2234

**Comment by IteratorW** [comment]
oh wow, thank you!

**Comment by IteratorW** [comment]
ok, so it took some time to figure it out, but it's NOT fixed :(
here's the version (isn't it too old?)
![image](https://user-images.githubusercontent.com/30198566/58324280-19079200-7e2f-11e9-9ea0-7961f682a17e.png)
and how it looks from dynmap
![image](https://user-images.githubusercontent.com/30198566/58324301-2b81cb80-7e2f-11e9-93cb-738807203a71.png)
forgot to say: the seed is now the same after server reboot, i've also set the exact seed in server.properties

**Comment by phit** [comment]
try on a fresh map, those boundaries should no longer show up, anyway unless you also have GeographiCraft  this is a different issue

**Comment by SSKirillSS** [comment]
Just tried to start the server with new versions of spongeforge and forge. The problem is still relevant - BOP biomes don't generating.

**Comment by IteratorW** [comment]
Is _level-type_ in your server.properties set to _BIOMESOP_ ?

**Comment by SSKirillSS** [comment]
@IteratorW, у меня совершенно другая ситуация. У меня стоит БОП с патчами РТГ. Чтоб эти патчи работали - в типе генерации должен быть указан RTG. Проблема на стороне Spongeforge, т.к. одиночная игра отлично функционирует, как и чистый сервер forge.

**Comment by IteratorW** [comment]
Ок ок, понял, не лезу. Моя проблема, вроде, устранилась.

**Comment by IteratorW** [comment]
If it's useful. GeographiCraft doesn't work on last stable build (1.12.2-2825-7.1.6-RC3716), but it worked on the recommended one. Now my only "solution" is to generate map on the recommended build (and pray that the server won't crash or something, because it will reset the seed) and update to new version after generating. This is extremely annoying.

**Comment by IteratorW** [comment]
maybe it will help - updated sponge and forge to their last versions and now everything is working!
