### ISSUE TITLE
Teleport over worlds. Bug.

### ISSUE THREAD

**Issue by rvveber** [SpongePowered/SpongeForge#2397]
**I am currently running**
- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3406
- Forge version: 1.12.2-14.23.4.2756
- Java version: 1.8.0_181
- Operating System: ubuntu(on server)/windows 10(on client)

- Plugins/Mods:
(Plugins Only:
Griefprevention, Nucleus, LuckPerms, Eaglefactions, spark, mmcrestrict, modbanner, Totaleconomy, worldedit forge)

**Issue Description**
-when i teleport player A who is currently in dimension overworld, to player B which is me currently in the nether the following will happen:
1. i get error "Intended to track block entity spawns" Please analyze the current phase context." directly after i run the command.
2.Player A meanwhile will get teleported to (seemingly the same coordinates) on the overworld. where he can't really move and blocks sometimes change to netherrack.
3.upon relog of player A, he is in the nether, but at different position (probably overworld spawn position in the nether).

LOGS:
-Phasecontext: 
https://imgur.com/a/yuST5My

-In this Situation i sent a teleport request from nether to him which he accepted and got the same error as described in 1. under issue description: 
https://ghostbin.com/paste/mxgz9

-And something that looks like it has to do with this or is otherwisely important:
https://imgur.com/a/JZmSpmq

-[updated to correct one] debug.log:
https://gist.github.com/RedCriterion/a538aeab69b2af594bac50d141faa467

**Comment by phit** [comment]
please add your `logs/debug.log`

**Comment by RedCriterion** [comment]
this is all i have, sorry

**Comment by rvveber** [comment]
updated debug.log to the correct one

**Comment by phit** [comment]
that debug log doesnt have any of the exceptions you screenshotted

oh looks like a dupe of https://github.com/SpongePowered/SpongeForge/issues/2355
