### ISSUE TITLE
CME with map optimizations turned on 

### ISSUE THREAD

**Issue by phit** [SpongePowered/SpongeForge#2398]
**I am currently running**
- SpongeForge version: 3406/3411
- Forge version: 2705

- Plugins/Mods: see gists

**Issue Description**
could reproduce this consistently by going through the twilight forest portal, was also reported in https://github.com/SpongePowered/SpongeForge/issues/2396

https://gist.github.com/SSKirillSS/13c3e097a83122fba54a8311a79ab83f.
https://gist.github.com/phit/58cc52ac923dac155ddd8fe1ea9c3250

solved by setting map-optimization=false

**Comment by Aaron1011** [comment]
@phit: I'm completely unable to reproduce this issue, after having gone through the Twilight Forest portal several times (with map optimizations enabled).

Were you running any mods besides Twilight Forest?

**Comment by liach** [comment]
Twilight forest copies vanilla code wholesale so that sponge's change that move all maps to overworld saved data does not apply. Hence the explanation in #2630 works.

**Comment by Zidane** [comment]
@phit Retest with the latest SF.

**Comment by Zidane** [comment]
I have a build I'd like tested:

https://www.dropbox.com/s/zn45b51p0unl3vv/spongeforge-1.12.2-2838-7.1.7-RC0.jar?dl=0

Should fix this issue.

**Comment by Zidane** [comment]
@phit Please test this tomorrow as I'd like to include it in release.

**Comment by phit** [comment]
@zhourui123 try the above build please

**Comment by zhourui123** [comment]
It is not convenient to test in the formal environment for the time being, and it may be updated after the summer vacation. I will timely feedback if there is any problem
