### ISSUE TITLE
Write MCP-Mapping version to manifest/dev-shaded.jar

### ISSUE THREAD

**Issue by ST-DDT** [SpongePowered/SpongeForge#2399]
Ref: https://github.com/SpongePowered/SpongeDocs/issues/585

We require that the mod authors use the same MCP-Mapping version as SpongeForge if they use the shaded jar for in IDE running. However currently it is not possible to get that version from an existing jar.

To avoid confusion and manual research in the github repository it would be nice, if we could include that information somewhere in the SpongeForge jar. The Manifest could be a good location for that.

**Comment by phit** [comment]
this may need to be moved to sc, but im not quite certain how the gradle stuff is done

though common does hold the mappings https://github.com/SpongePowered/SpongeCommon/blob/1e12f7e109010c4d1c840f726c6c298b54440a52/gradle.properties#L8

**Comment by RedNesto** [comment]
@phit Maybe someone knows for sure, but I don't think gradle can add manifest entries to jars built by parent projects. I think it has to be done on the SpongeForge buildscript.

**Comment by ST-DDT** [comment]
Maybe it would be nice to add also add an explicit entry for the target Minecraft version. (This would also be relevant for the API).

Ref: https://github.com/SpongePowered/SpongeDocs/issues/652

**Comment by phit** [comment]
~move to sc

**Comment by limbo-app** [comment]
Hey @ST-DDT! I've moved your issue to [SpongePowered/SpongeCommon#2282](https://github.com/SpongePowered/SpongeCommon/issues/2282).
