### ISSUE TITLE
[1.12.2]Nether unable to load

### ISSUE THREAD

**Issue by Tommeh1** [SpongePowered/SpongeForge#2400]
- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3413 (3413 was used to see if it would fix the issue, the issue originally occured on 3361)
- Forge version: 1.12.2 - 14.23.4.2705
- Java version:  OpenJDK 64-Bit Server VM, version 1.8.0_171
- Operating System: Linux

Mods (80): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AE2 Stuff, Applied Energistics 2, Aroma1997Core, AromaBackup, AromaBackuprecovery, BC Builders, BC Energy, BC Factory, BC Silicon, BC Transport, BD Lib, Better Builder's Wands, Biome Bundle, Bookshelf, Brandon's Core, BuildCraft, BuildCraft Compat, BuildCraft Lib, Chisel, CoFH Core, CodeChicken Lib, CommonCapabilities, CraftTweaker JEI Support, CraftTweaker2, Cyclops Core, Draconic Evolution, EnderStorage, Extra Cells 2, Extreme Reactors, ICBM-Classic, Industrial Foregoing, Inventory Tweaks, Iron Chest, Just Enough Items, Loot Bags, MCMultiPart, MTLib, Mantle, Mekanism, MekanismGenerators, MekanismTools, Mod Tweaker, Modern Warfare, OMLib, OTG Core, Open Modular Turrets, Open Terrain Generator, OpenComputers, OpenComputers (Core), OpenSecurity, OreExcavation, Pam's HarvestCraft, Placebo, Power Adapters, Quick Leaf Decay, Redstone Arsenal, Redstone Flux, Secret Rooms 5, SecretRooms Hooks, Shadowfacts' Forgelin, Simple Generators, Simply Jetpacks 2, Tesla Core Lib, Tesla Core Lib Registries, Tinker I/O, Tinkers Tool Leveling, Tinkers' Construct, UniDict, Universal Modifiers, Valkyrie Lib, Waila, WanionLib, WorldEdit, Zero CORE

Plugins (11): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, Eagle Factions, LuckPerms, MagiBridge, NuVotifier, Nucleus, SeriousVote, Total Economy

Nobody can enter the nether through neither a nether portal or by using /world teleport, no errors appear with all debug active.
When players try to use a nether portal they'll remain unable to look around or move until the portal is broken and this does not occur without spongeforge

Latest.log: https://gist.github.com/CraftalotReloaded/c8b2c3abcc6df3c6f4b2bd0701754e8e

**Comment by phit** [comment]
OTG is not supported, see https://github.com/SpongePowered/SpongeForge/issues/2072#issuecomment-377701029

**Comment by CraftalotReloaded** [comment]
OTG generated the overworld just fine and should not effect the nether, the nether uses default worldgen
