### ISSUE TITLE
Entities Breed, no offspring

### ISSUE THREAD

**Issue by tgstyle** [SpongePowered/SpongeForge#2402]
**I am currently running**
- SpongeForge version: 3413
- Forge version: 2757
- Java version: 1.8.0_171
- Operating System: Win 10

Since the change in 3403 baby entities no longer spawn. Animals go through all the motions, drop XP and that is it.

**Comment by ryantheleach** [comment]
Any mods?

**Comment by Aaron1011** [comment]
My bad - fixed in https://github.com/SpongePowered/SpongeCommon/commit/be165cc3232cc2b60669db836f643d4af59693c4.
