### ISSUE TITLE
Almost no mobs spawning; reference s#1345

### ISSUE THREAD

**Issue by lllMohandarlll** [SpongePowered/SpongeForge#2403]
**I am currently running**
1.12.2
- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3413
- Forge version: forge-1.12.2-14.23.4.2705-universal
- Java version: java build 1.8.0_161-b12
- Operating System: windows 8.1

- Plugins/Mods:

https://i.imgur.com/dYH4Wl1.png

the only plugin is listed in the mods folder as well and it's just a reward plugin that runs the command /give when the player calls for it

**Issue Description**

The Betweenlands hostiles hardly or no spawn even after setting;

 capture-async-spawning-entities=false

 If 'true', lighting updates are run asynchronously.
  enabled=false

and

         If 'true', this world will generate its spawn the moment its loaded.
        generate-spawn-on-load=true

removing sponge solved the issue...

[latest.log](https://github.com/SpongePowered/SpongeForge/files/2315433/latest.log)

**Comment by phit** [comment]
none of those settings you posted affect mob spawn counts, please post your global.conf

**Comment by lllMohandarlll** [comment]
https://pastebin.com/iHvn1Gp5

**Comment by phit** [comment]
reset `mob-spawn-range` to its default value (4)
yours is currently set to 12 spreading out the usual spawn cap of 70 (well yours is set to 75) to an area thats 576% larger..

**Comment by lllMohandarlll** [comment]
Why to close? even when the range was at 4 the problem was present.

**Comment by lllMohandarlll** [comment]
just re-open it until a solution is found.
I've just set the range at 4, again. And in fact just nothing changed.
I bet is something about light level, but I'm not sure, what is sure is that sponge interfere with the spawning in betweenlands dimension

**Comment by lllMohandarlll** [comment]
This is with spongeforge:
![xr45czd](https://user-images.githubusercontent.com/11860704/44544907-ddab2c00-a713-11e8-9bba-00d1e59fa5f7.png)

and this without sponge installed
![pmplvqq](https://user-images.githubusercontent.com/11860704/44544921-e69bfd80-a713-11e8-9cef-643abeaa8cc7.png)

you can see the red dots on journeymap

on the bottom left we can see that Lightlevel is at 15 there, the mod may spawn hostiles differently from vanilla and sponge try to force it differently

**Comment by lllMohandarlll** [comment]
Would be possible an implementation of code with a new config option that disable sponge living-entity handling entirely?
This would probably be a temporary fix.
Otherwise, should I notify this to betweenlands authors too?

**Comment by lllMohandarlll** [comment]
any news?

**Comment by Zidane** [comment]
Tested with latest SF and The Between Lands. Entities are definitely spawning and apparently the waters and what live in them are very evil.... :O.
