### ISSUE TITLE
Some server errors and client crash

### ISSUE THREAD

**Issue by avescarelo** [SpongePowered/SpongeForge#2404]
**I am currently running**

- Minecraft: 1.12.2
- SpongeAPI: 7.1.0-SNAPSHOT-2d8df24
- SpongeForge: 1.12.2-2705-7.1.0-BETA-3413
- Minecraft Forge: 14.23.4.2750
- Operating System: Linux

**- Plugins**:
FastAsyncWorldEdit, A'therys Core, A'therys Parties, ActionBroadcaster, GriefPrevention, LuckPerms, Nucleus, Prism, PrismPlus, ShabbyHolograms, Total Economy, UCFA, UltimateChat, VoxelSniper, WorldEdit

**- Mods**:
AppleCore, Applied Energistics 2, Astral Sorcery, AutoRegLib, Baubles, Cases, Chameleon, CoFH Core, CoFH World, CodeChicken Lib, ContainerFix, CraftTweaker JEI Support, CraftTweaker2, Cyclic, Earthworks, Energy Converters, Forestry, Guide-API, Immersive Engineering, Just Enough Items, LibrarianLib, LibrarianLib Stage 2, Morpheus, Ore Veins, Quark, Redstone Flux, Rough Mobs 2, Rustic, Shadowfacts' Forgelin, Spice of Life: Carrot Edition, Storage Drawers, TeamLapen Library, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Vampirism, Wizardry

**Issue Description**
Sometimes, when i interacted with monsters, i have some errors in console. 

Full server log: [https://gist.github.com/pingvikin/3a2776b09ce5ffde3001c17a782db943](https://gist.github.com/pingvikin/3a2776b09ce5ffde3001c17a782db943)

Client Crash report (with this error): [https://gist.github.com/pingvikin/7898e5385053818bd23968324736b9a7](https://gist.github.com/pingvikin/7898e5385053818bd23968324736b9a7)

**Comment by phit** [comment]
the server errors are caused by the prism plugin, please take it to their issue tracker
