### ISSUE TITLE
Sponge fails to function with Movingworld mod

### ISSUE THREAD

**Issue by Elspar2** [SpongePowered/SpongeForge#2408]
- SpongeForge version: 3361+
- Forge version: 1.12 2705
- Java version: 1.8_181
- Operating System: Windows 8.1

Mod: https://minecraft.curseforge.com/projects/movingworld
With movingworld installed, Sponge fails to function in the console and game.
Here is a log with ONLY movingworld and Sponge in mods: https://pastebin.com/AcAai1ZH

**Comment by phit** [comment]
The mod is loading an outdated Mixin version before Sponge, please report it to the mod author! For temporary solution rename the SpongeForge jar file, so its sorted alphabetically before the other mod e.g. rename `spongeforge-1.12.2-2705-7.1.0-BETA-3318.jar` to `_aspongeforge-1.12.2-2705-7.1.0-BETA-3318.jar`
