### ISSUE TITLE
Sponge fails to function with MalisisCore mods

### ISSUE THREAD

**Issue by Elspar2** [SpongePowered/SpongeForge#2409]
**I am currently running**

- SpongeForge version: 3361+
- Forge version: 1.12 2705
- Java version: 1.8_181
- Operating System: Windows 8.1

While attempting to run a server with MalisisCore, Sponge fails to function in the console and in-game. Just like it is not enabled.
Here is a log with ONLY MalisisCore and Sponge installed: https://pastebin.com/6kTuk66h

**Comment by phit** [comment]
The mod is loading an outdated Mixin version before Sponge, please report it to the mod author! For temporary solution rename the SpongeForge jar file, so its sorted alphabetically before the other mod e.g. rename `spongeforge-1.12.2-2705-7.1.0-BETA-3318.jar` to `_aspongeforge-1.12.2-2705-7.1.0-BETA-3318.jar`
