### ISSUE TITLE
Hoppers duplicating ore with EnderIO Machines

### ISSUE THREAD

**Issue by Shybella** [SpongePowered/SpongeForge#2411]
**I am currently running**

- SpongeForge version: 3414
- Forge version: 2739
- Java version: 1.8 update 181
- Operating System: Windows Server

Plugins/Mods: Mods (156): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, /dank/null, Actually Additions, Advanced Generators, Akashic Tome, AppleSkin, Applied Energistics 2, Aroma1997's Dimensional World, Aroma1997Core, Astral Sorcery, AutoRegLib, BD Lib, Bad Wither No Cookie! Reloaded, Baubles, Better Advancements, Better Builder's Wands, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Biomes O' Plenty, Blockcraftery, Blood Magic: Alchemical Wizardry, Bookshelf, Botania, Brandon's Core, Chameleon, ChickenChunks, Chisel, Chisels & Bits, CoFH Core, CoFH World, CodeChicken Lib, CommonCapabilities, Compact Machines 3, Compact Solar Arrays, Cooking for Blockheads, CraftTweaker JEI Support, CraftTweaker2, Cyclops Core, Dark Utilities, DeepResonance, Diet Hopper, Draconic Evolution, ElecCore, Elevator Mod, EluCore, EluLib, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, EnderStorage, Environmental Tech, Exchangers, Extra Utilities 2, Extreme Reactors, FastWorkbench, Flat Colored Blocks, Forestry, Funky Locomotion, GenDustry, Gravestone Mod, Guide-API, Immersive Engineering, Industrial Foregoing, IndustrialCraft 2, Integrated Dynamics, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTunnels-Compat, Iron Backpacks, Iron Chest, JEI Bees, JourneyMap, Just Enough Items, MCMultiPart, MTLib, MagicBees, Mantle, McJtyLib, MeeCreeps, Mercurius, MineTogether, MineTogetherServer, Mod Tweaker, Morph, Morph-o-Tool, Morpheus, NetherPortalFix, Not Enough Wands, OpenComputers, OpenComputers (Core), Pam's HarvestCraft, Placebo, PneumaticCraft: Repressurized, PortalGun, Psi, Quick Leaf Decay, RFTools, RFTools Control, RFTools Dimensions, Ranged Pumps, Reborn Core, RebornStorage, Redstone Arsenal, Redstone Flux, Refined Storage, Refined Storage Addons, Shadowfacts' Forgelin, Simple Inventory sorting, Simply Jetpacks 2, Storage Drawers, Storage Drawers Extras, SwingThroughGrass, TESLA, TOP Addons, Tesla Core Lib, Tesla Core Lib Registries, Thaumcraft, The Lost Cities, The One Probe, The Twilight Forest, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Tinkers' Construct, UniDict, Universal Modifiers, Valkyrie Lib, WanionLib, Wireless Crafting Terminal 2, XNet, Zero CORE, iChunUtil, mob_grinding_utils, p455w0rd's Library

**Issue Description**

1. Put a hopper on the side of the Enhanced Sag Mill/Alloy Smelter.
2. Configure the import in the GUI.
3. Put 6-7 ore into the hopper.
4. Open the GUI and monitor the amount of ore being put into the machine. It usually stacks up to 64 or more duplicating the ore does not occur without Spongeforge.

Video: https://www.youtube.com/watch?v=BvpF4pvuzEM&feature=youtu.be

EnderIO versions
- EnderIO: EnderIO-1.12.2-5.0.29
- EnderCore: EnderCore-1.12.2-0.5.35

Thank you

https://github.com/SleepyTrousers/EnderIO/issues/4853

**Comment by LXGaming** [comment]
This bug also affects blocks from:
- Actually Additions
- Applied Energistics 2
- Cyclic
- Ex Compressum
- Extra Utilities 2

**Comment by LXGaming** [comment]
The bug was introduced in `1.12.2-2705-7.1.0-BETA-3401`

**Comment by Faithcaio** [comment]
https://github.com/SpongePowered/SpongeCommon/compare/f9b0f113606d6ab0c0fb5cd9172953e4cb05e321...4fcbc235305bdfe1e401d0499b07970b9f1a8874#diff-a4b4fff4bbad85e9f3f3e4036493946c

**Comment by LXGaming** [comment]
It appears that Sponge is doing a double insert with certain modded inventories

Commenting out this line prevents the duplication from happening
https://github.com/SpongePowered/SpongeCommon/blob/cdc82f577079cc9a5f6bf527433a7ea3e30723e5/src/main/java/org/spongepowered/common/event/SpongeCommonEventFactory.java#L1346

**Comment by LXGaming** [comment]
Stacktrace: https://gist.github.com/LXGaming/75f2ba6f4b7608998f25f646711b6b1f

The 1st insert is done by Sponges transaction capture system.
The 2nd is done by [IItemHandlerAdapter.java](https://github.com/SpongePowered/SpongeForge/blob/b6f1bafb06f1b7a0111957e6a8960cf271593c71/src/main/java/org/spongepowered/mod/item/inventory/adapter/IItemHandlerAdapter.java) and [IItemHandlerFabric.java](https://github.com/SpongePowered/SpongeForge/blob/a890fd7dbaef7f2e51d553c099520c35865e9c09/src/main/java/org/spongepowered/mod/item/inventory/fabric/IItemHandlerFabric.java)

This would explain why only certain Blocks are affected as it has to be using the IItemHandlerAdapter class which is only in SpongeForge.

It also explains why commenting out the capture line prevents the issue from happening

**Comment by Faithcaio** [comment]
Thanks for investigating. 

This all actually happens because of 
`IItemHandlerFabric#setIItemHandlerStack`
which cannot reliably remove items from an IItemHandler.
As such "setting" the final item of a transaction is not possible.

Actually the `extractItem` code in there is currently never called because there is still a null check instead of isEmpty on the item.
But even fixing that will not fix all issues we have with mods.

**Comment by Faithcaio** [comment]
Fixed in latest. (tested with enderio sagmill)
I print out a warning once for every IItemHandler that I detect not allowing to remove items.
After that all `setStack` operations on it will be ignored.
As such canceling `ChangeInventoryEvent.Transfer.Post` will not work for such inventories.
Plugins could still use the `Pre` event to cancel before any items were moved.

**Comment by Faithcaio** [comment]
While investigating further I found `IItemHandlerModifiable` in Forge.
If the modded inventory would implement that I could use the `setStackInSlot` to revert stuff.

**Comment by Shybella** [comment]
Good stuff, I'll test this out later today.
