### ISSUE TITLE
Decremented listener count to -4 for field public static boolean org.spongepowered.common.event.ShouldFire.MOVE_ENTITY_EVENT

### ISSUE THREAD

**Issue by LXGaming** [SpongePowered/SpongeForge#2412]
**I am currently running**

- SpongeForge version: 
 - 1.12.2-2705-7.1.0-BETA-3415 (forge-1.12.2-14.23.4.2758)
 - 1.12.2-2705-7.1.0-BETA-3422 (forge-1.12.2-14.23.4.2758)
- Java version: 1.8
- Operating System: Linux

- Plugins/Mods: Enigmatica 2: Expert modpack

**Issue Description**
It appears that when an Advanced Rocketry world is unloaded it unregisters events which is somehow causing Nucleus events to become broken or unregistered as the AFK module is no longer able to track player movements.

Stacktrace: https://pastebin.com/hSvZtdYz

**Comment by Aaron1011** [comment]
@LXGaming: There should be a few exceptions before this one. Can you upload your entire `debug.log`?

**Comment by LXGaming** [comment]
[debug-5.log.gz](https://github.com/SpongePowered/SpongeForge/files/2350679/debug-5.log.gz)
@Aaron1011

**Comment by LemADEC** [comment]
Issue is still reproduced with spongeforge-1.12.2-2768-7.1.3-RC3498 + AdvancedRocketry-1.12.2-1.4.1-111-universal.
Any thoughts?

**Comment by LemADEC** [comment]
Any updates on this issue?

**Comment by phit** [comment]
https://gist.github.com/phit/9fd7cb11edf3bcbf484ba92e5aae888e#file-gistfile1-txt-L5063

still an issue, simple test:
* go to DIM-2
* stop server
* see exception in log

jei_1.12.2-4.13.1.225.jar
LibVulpes-1.12.2-0.3.0-45-universal.jar
AdvancedRocketry-1.12.2-1.4.1-119-universal.jar
spongeforge-1.12.2-2768-7.1.5-RC3513.jar
griefprevention-1.12.2-4.3.0.662.jar
LuckPerms-Sponge-4.3.62.jar
Nucleus-1.8.0-S7.1-MC1.12.2-plugin.jar
