### ISSUE TITLE
Testing Forge 2759 onto SpongeForge 2705 ? Crash?

### ISSUE THREAD

**Issue by HaniXP** [SpongePowered/SpongeForge#2416]
**I am currently running**

- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3361
- Forge version: 1.12.2 - 14.23.4.2759
- Java version: 8
- Operating System: Windows 7 Ultimate 64 bit

- Plugins/Mods:

Plugins:
1)CatClearLag-0.8.3.jar
2)EconomyLite-7.1.0-2.14.3.jar
3)griefprevention-1.12.2-4.3.0.590.jar
4)LuckPerms-sponge-4.2.14.jar
5)MagiBridgeAI-2.4.5.1.jar
6)Nations-2.11-S7.0-1.12.2.jar
7)Nucleus-1.3.13-S7-1.12.2-plugin.jar
8)UltimateCore.jar

Mods:
(Screenshot below)

https://imgur.com/a/iNzBYCp

**Issue Description**

Actually ive discussed my problem on discord right here in the morning with some of the community sponge members 
Screenshot of the discussion = https://imgur.com/a/U9v79mq

So i did what i did & i actually tried testing Forge 2759 onto spongeforge's 2705 it seems like it didnt turned out well and my server never started up again, The reason why i changed to forge 2759 because mods like forestry & codechickenlib have shifted to a bit higher forge version(like this for example: https://imgur.com/a/nJ4898Y) and now i am stuck on that situation with my server.

shall i instead try testing 2749 instead of 2759? (because forestry is the only mod right now that requires this much of a higher version of forge) or any alternatives regarding this problem?

Server Log = https://gist.github.com/AgentHani/4179a17da243b32fe7750998c7ce10fd

**Comment by phit** [comment]
we will update once there is a newer recommended forge version, until then you can take it to the mods that require a newer forge version and possibly see about downgrading them if they really need the newer version

**Comment by phit** [comment]
just noticed your spongeforge version is also ancient recommended is 3361, you are using 3206
the issue in the log was fixed weeks/months
http://files.minecraftforge.net/spongepowered
