### ISSUE TITLE
ClassCastException in BlockDropItemsPhaseState

### ISSUE THREAD

**Issue by Shybella** [SpongePowered/SpongeForge#2418]
**I am currently running**

- SpongeForge version: 3414
- Forge version: 2739
- Java version: 1.8 update 181
- Operating System: Windows Server 2012

- Plugins/Mods: Mods (156): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, /dank/null, Actually Additions, Advanced Generators, Akashic Tome, AppleSkin, Applied Energistics 2, Aroma1997's Dimensional World, Aroma1997Core, Astral Sorcery, AutoRegLib, BD Lib, Bad Wither No Cookie! Reloaded, Baubles, Better Advancements, Better Builder's Wands, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Biomes O' Plenty, Blockcraftery, Blood Magic: Alchemical Wizardry, Bookshelf, Botania, Brandon's Core, Chameleon, ChickenChunks, Chisel, Chisels & Bits, CoFH Core, CoFH World, CodeChicken Lib, CommonCapabilities, Compact Machines 3, Compact Solar Arrays, Cooking for Blockheads, CraftTweaker JEI Support, CraftTweaker2, Cyclops Core, Dark Utilities, DeepResonance, Diet Hopper, Draconic Evolution, ElecCore, Elevator Mod, EluCore, EluLib, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, EnderStorage, Environmental Tech, Exchangers, Extra Utilities 2, Extreme Reactors, FastWorkbench, Flat Colored Blocks, Forestry, Funky Locomotion, GenDustry, Gravestone Mod, Guide-API, Immersive Engineering, Industrial Foregoing, IndustrialCraft 2, Integrated Dynamics, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTunnels-Compat, Iron Backpacks, Iron Chest, JEI Bees, JourneyMap, Just Enough Items, MCMultiPart, MTLib, MagicBees, Mantle, McJtyLib, MeeCreeps, Mercurius, MineTogether, MineTogetherServer, Mod Tweaker, Morph, Morph-o-Tool, Morpheus, NetherPortalFix, Not Enough Wands, OpenComputers, OpenComputers (Core), Pam's HarvestCraft, Placebo, PneumaticCraft: Repressurized, PortalGun, Psi, Quick Leaf Decay, RFTools, RFTools Control, RFTools Dimensions, Ranged Pumps, Reborn Core, RebornStorage, Redstone Arsenal, Redstone Flux, Refined Storage, Refined Storage Addons, Shadowfacts' Forgelin, Simple Inventory sorting, Simply Jetpacks 2, Storage Drawers, Storage Drawers Extras, SwingThroughGrass, TESLA, TOP Addons, Tesla Core Lib, Tesla Core Lib Registries, Thaumcraft, The Lost Cities, The One Probe, The Twilight Forest, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Tinkers' Construct, UniDict, Universal Modifiers, Valkyrie Lib, WanionLib, Wireless Crafting Terminal 2, XNet, Zero CORE, iChunUtil, mob_grinding_utils, p455w0rd's Library

**Issue Description**

Phase Error: https://pastebin.com/raw/T7hLLcX3
Spark: https://sparkprofiler.github.io/?DVYMHLWUGP

It's spamming about 15-20 times a second.

If you need anything else I can assist

**Comment by ImMorpheus** [comment]
@Shybella Post you global.conf

**Comment by Shybella** [comment]
Relocated the world on a dev server with clean configs and got it to print. I had a feeling it was a config messed up. 

Stack Trace: https://pastebin.com/raw/VTKgDVJC

**Comment by ImMorpheus** [comment]
Does it happen randomly ? Do you have a way to reproduce this ?

**Comment by Shybella** [comment]
This does need some type of discard system. Phase errors sometimes take time to be fixed and having this spam at this rate is killing performance. 

<s>Maybe Implement something that prints several times and then becomes suppressed and does not print. I don't want to turn off verbose errors in the config because now that I have it printing the errors, I want to catch them all and report them.</s>

That's already a thing. I'm just blind.

This seems to be happening randomly, although, does seem to be on the player and not a TileEntity.

**Comment by Shybella** [comment]
This is related to the spam causing bad performance from the phasetracker logger. https://github.com/SpongePowered/SpongeForge/issues/2435

Same problem just a proper stack trace now.

**Comment by Shybella** [comment]
This seems to have resolved itself and maybe a fix was made in the latest builds.
