### ISSUE TITLE
Errors on Joins

### ISSUE THREAD

**Issue by sfxworks** [SpongePowered/SpongeForge#2422]
**I am currently running**
SpongeForge
  - Minecraft: 1.12.2
  - SpongeAPI: 7.1.0-SNAPSHOT-7105dfc
  - SpongeForge: 1.12.2-2705-7.1.0-BETA-3361
  - Minecraft Forge: 14.23.4.2705

Java version: 
  - openjdk version "1.8.0_181"
   - OpenJDK Runtime Environment (build 1.8.0_181-b13)
  - OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
 
Operating System:
  - CentOS Linux release 7.5.1804 (Core)

Plugins/Mods:

Plugins (27): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, Aliases, BattleLog, CarrotShop, CatClearLag, Holograms, LangSwitch, LuckPerms, MMCReboot, MMCRestrict, MMCTickets, Nucleus, Plan, ProjectCore, ProjectPortals, ProjectWorlds, ServerListPlus, SleepVote, Total Economy, Universe Guard 2, VillagerShops, Web-API, WorldEdit, spark

Mods (97): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AE2 Stuff, Actually Additions, Advanced Solar Panels, Ambience, Applied Energistics 2, AutoRegLib, BC Builders, BC Energy, BC Factory, BC Robotics, BC Silicon, BC Transport, BD Lib, Baubles, Blood Debug, Brandon's Core, BuildCraft, BuildCraft Compat, BuildCraft Lib, CoFH Core, CoFH World, CodeChicken Lib, ComputerCraft, CustomNPCs, DiscordIntegration, Draconic Evolution, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, EnderStorage, Ex Compressum, Ex Nihilo Creatio, Extra Cells 2, Extra Planets, Extreme Reactors, Faction Mod, Galacticraft Core, Galacticraft Planets, ICBM-Classic, Immersive Engineering, IndustrialCraft 2, Inventory Tweaks, Iron Chest, It's the little things, JourneyMap, Just Enough Items, MJRLegendsLib, Malisis Advert, MalisisCore, Mantle, Mekanism, MekanismGenerators, MekanismTools, Micdoodle8 Core, NoMoreRecipeConflict, NuclearCraft, OMLib, Open Glider, Open Modular Turrets, OpenBlocks, OpenModsLib, OpenModsLib Core, PlusTiC, Quark, Random Things, Reborn Core, Redstone Arsenal, Redstone Flux, SG Craft, Simply Jetpacks 2, Smooth Font Core, Steve's Carts 2, TESLA, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Tinkers' Construct, VanillaFix, What Are We Looking At, Wireless Crafting Terminal 2, Zero CORE, p455w0rd's Library

**Issue Description**
Every time a player joins the server, after a delay, they join but a large amount of errors appear in the console. Sometimes, they get disconnected.

Log / Join Log
https://gist.github.com/sfxworks/8b4d367ca921b587eed032c4d9324444

**Comment by RedNesto** [comment]
Sounds like a journeymap issue to me.

**Comment by ImMorpheus** [comment]
Can you reproduce the issue without sponge ?

**Comment by phit** [comment]
journeymap issue, see https://github.com/TeamJM/journeymap/issues/42
they need to update for https://github.com/MinecraftForge/MinecraftForge/pull/4890
