### ISSUE TITLE
Issue with hoppers pushing to a Storage Drawers block

### ISSUE THREAD

**Issue by PoroUsedSnax** [SpongePowered/SpongeForge#2429]
**I am currently running**

- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3431
- Forge version: 14.23.4.2705
- Java version: 1.8.0_181
- Operating System: Linux

- Plugins/Mods:
A lot, special mention for Storage Drawers

**Issue Description**
Had recently updated our server to the mentioned Sponge version, and was running well, then suddenly had a drop down to 2 TPS, after doing some digging, I found through LagGoggles there was a hopper showing upwards of 253,000 μs/t, ran a profile on the server also and got this: https://sparkprofiler.github.io/?WrFuuiN4pf The hopper in question (or two of them as I found) were attempting to push into a Controller Slave from Storage Drawers. I'm not certain whether this is a Sponge issue or with Storage Drawers, but thought I'd start here.

**Comment by Faithcaio** [comment]
The Lens should be reused instead of recreating a new one every time the hopper ticks.
I'll look into this later today

**Comment by Faithcaio** [comment]
Sorry took a while. 
Try again with latest. 
Haven't implemented lens reuse but this should be faster for large inventories already.

**Comment by PoroUsedSnax** [comment]
Apologies I took some time myself to try it out, got a bit busy the past few days, I've updated to Sponge 3445 currently and I'm still seeing issues between Sponge and Storage Drawers with hoppers.

**Comment by Faithcaio** [comment]
Now we reuse lenses made for IItemHandlers.
If it is still an issue with latest please provide new profiler output.
