### ISSUE TITLE
Crash on Launch org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError (Server Crash)

### ISSUE THREAD

**Issue by Tylerun** [SpongePowered/SpongeForge#2432]
- Minecraft Version 1.12.2
- SpongeForge version: 2705-7.1.0-BETA-3434
- Forge version: 2759
- Java version: Version 8 update 181
- Operating System: Windows 10 Pro

Please refer to Logs for full list of mods as I can not run sponge commands due to server crashing on launch. 

**Issue Description**
Hello. when starting up a development server i'm working on using sponge the server crashes when trying to load the nether if I am reading the logs correctly. I have not changed any configs or anything yet but reading the logs I can not see what is causing the current issue. Any insights would be greatly appreciated.

Logs: https://gist.github.com/Tylerun/224301c31dded866ec7952c769529963

**Comment by Zidane** [comment]
You are using FoamFix which has a compatibility issue with us. Contact them to get the appropriate version of their product that works fine with us.
