### ISSUE TITLE
Ghost item entity duplicate bug on TiC

### ISSUE THREAD

**Issue by Preta-Crowz** [SpongePowered/SpongeForge#2433]
**I am currently running**

- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3151
- Forge version: 14.23.4.2707
- Java version: 10.0.1 2018-04-17
- Operating System: Windows 10 Version 1709 (Build 16299.547)

- Plugins/Mods:

> Mods (104): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Actually Additions, AppleSkin, Applied Energistics 2, ArchitectureCraft, Astral Sorcery, BanHammer, Baubles, Better Builder's Wands, BiblioCraft, Bookshelf, Brandon's Core, Carpenter's Blocks, Chameleon, Chisel, Chisels & Bits, CoFH Core, CoFH World, CodeChicken Lib, Construct's Armory, Cooking for Blockheads, CraftTweaker JEI Support, CraftTweaker2, Crafting Tweaks, Cucumber Library, CustomNPCs, Dark Utilities, Draconic Evolution, Elevator Mod, EnderStorage, Environmental Tech, Extended Crafting, Extra Utilities 2, FTB Utilities, FTBLib, Forestry, Forge Microblocks, Forge Multipart CBE, Health Bar, Industrial Foregoing, Inventory Tweaks, Iron Backpacks, Iron Chest, JourneyMap, Just Enough Items, Login Shield, LunatriusCore, MTLib, Mantle, McJtyLib, Minecraft Multipart Plugin, Moar Tinkers, Mod Tweaker, MrTJPCore, Oreberries, Pam's HarvestCraft, PlusTiC, ProjectRed Core, ProjectRed Exploration, ProjectRed Fabrication, ProjectRed Illumination, ProjectRed Transmission, ProjectRed integration, RFTools, Redstone Flux, Refined Storage, Scaling Health, Shadowfacts' Forgelin, Silent Lib, Silent's Gems, Silent's Gems: Extra Parts, Stackie, Stacksize Mod, Storage Drawers, Tesla Core Lib, Tesla Core Lib Registries, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thut Essentials, Tinker I/O, Tinker's JEI, Tinkered Hegemony, Tinkers Tool Leveling, Tinkers' Addons, Tinkers' Complement, Tinkers' Construct, TinkersExtras, Tweakers Construct, Universal Modifiers, Valkyrie Lib, What Are We Looking At, WorldEdit, XNet, kythsopmoss, projectred-compat, projectred-expansion, projectred-relocation, projectred-transportation

> Plugins (4): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge

I removed all plugins for testing. It happens when I added sponge.

**Issue Description**
When user drops TiC Tools, then it duplicates to many entities. But only one entity is real item and others are not exist.
I posted on TiC Repository too. SlimeKnights/TinkersConstruct#3624

And this bug doesn't make any additional log.

**Comment by phit** [comment]
update sponge, your version is very very outdated
