### ISSUE TITLE
Crash with latest forge 2760

### ISSUE THREAD

**Issue by Pilad** [SpongePowered/SpongeForge#2434]
Forge 2760
Sponge spongeforge-1.12.2-2705-7.1.0-BETA-3361, 1.12.2-2705-7.1.0-BETA-3434
Crash log.
https://pastebin.com/pgRTPG9A

**Comment by Zidane** [comment]
We do not support any Forge builds beyond what our SpongeForge build targets.

**Comment by Pilad** [comment]
Most mods do not work on the 2705 forge. What do I do now?

**Comment by Dockter** [comment]
I haven't found one that doesn't work with 2705.

**Comment by Pilad** [comment]
Ok.
What is this?
https://imgur.com/a/MVCqpVL

**Comment by Shybella** [comment]
Update to 2739. It works fine with latest SF.

**Comment by Pilad** [comment]
2749 for latest forestry.

**Comment by Shybella** [comment]
Try 2749

**Comment by Pilad** [comment]
foamfix-0.10.1-1.12.2 - this is problem. Without this mod - good work. Forge latest.

**Comment by Dockter** [comment]
Several versions of those mods work on 2705.
