### ISSUE TITLE
[REPOST] Ghost item entity duplicate bug on TiC

### ISSUE THREAD

**Issue by Preta-Crowz** [SpongePowered/SpongeForge#2436]
Same as #2433 
It still happens on 1.12.2-2705-7.1.0-BETA-3438

**Comment by phit** [comment]
can't reproduce with
spongeforge-1.12.2-2705-7.1.0-BETA-3460.jar
TConstruct-1.12.2-2.10.1.87.jar
Mantle-1.12-1.3.2.24.jar

please add more information what mods are needed to reproduce this, and no testing a full modpack is not an option.. please figure out which minimal modset is needed!

once that information has been supplied I'll be happy to reopen the issue, thanks
