### ISSUE TITLE
Something blocking Forge's AttackEntityEvent

### ISSUE THREAD

**Issue by ginyai** [SpongePowered/SpongeForge#2439]
Forge event `AttackEntityEvent` does not fire.
#1256 is still in API6/7

**Comment by phit** [comment]
https://github.com/SpongePowered/SpongeForge/blob/stable-7/src/main/java/org/spongepowered/mod/mixin/core/fml/common/eventhandler/MixinEventBus.java#L96

**Comment by gabizou** [comment]
Originally added [*nearly* 3 years ago](https://github.com/SpongePowered/SpongeForge/commit/516ca4b07cf82795bde189c7e3cc6439ad4f0166#diff-e136d0f5f960839144bd45ccc3e2d104R67)... @bloodmc not sure if you remember why this was added, don't know how the attackentityevent was to be implemented normally...

**Comment by luenlin** [comment]
@gabizou @phit @Aaron1011 @bloodmc 
This kind of problem has caused a lot of errors, please fix it as soon as possible.

**Comment by liach** [comment]
@luenlin please do not ping so many developers at once. They are always going to fix it.
