### ISSUE TITLE
Ender IO / Sponge 

### ISSUE THREAD

**Issue by Keaton1188** [SpongePowered/SpongeForge#2441]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3442.jar
- Forge version: 14.23.4.2739
- Java version: Java openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-b12)
- Operating System: CentOS Linux release 7.2.1511

- Plugins/Mods: Direwolf20 1.12.2

**Issue Description**
When placing Ender IO energy conduits, or attempting to upgrade I should say, Right-clicking on a basic energy conduit with an Enhanced energy conduit replaces the former with the latter, however while the basic energy conduit is returned to inventory, the Enhanced is not removed, meaning I could upgrade my whole system with a single enhanced conduit.

Please note that this does not occur when on Single Player.

**Comment by phit** [comment]
update enderio, this was fixed on their end

https://github.com/SleepyTrousers/EnderIO/issues/4766#issuecomment-406801898

**Comment by ap1608** [comment]
> **I am currently running**
> 
> * SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3442.jar
> * Forge version: 14.23.4.2739
> * Java version: Java openjdk version "1.8.0_151"
>   OpenJDK Runtime Environment (build 1.8.0_151-b12)
> * Operating System: CentOS Linux release 7.2.1511
> 
> * Plugins/Mods: Direwolf20 1.12.2
> 
> **Issue Description**
> When placing Ender IO energy conduits, or attempting to upgrade I should say, Right-clicking on a basic energy conduit with an Enhanced energy conduit replaces the former with the latter, however while the basic energy conduit is returned to inventory, the Enhanced is not removed, meaning I could upgrade my whole system with a single enhanced conduit.
> 
> Please note that this does not occur when on Single Player.

**Comment by gabizou** [comment]
Yeah, that's a super old version. You could bump forge and such and retry with spongeforge 7.3.0, but not gonna even try testing/debugging on a build that old.
