### ISSUE TITLE
PhaseContext Message

### ISSUE THREAD

**Issue by Raycoms** [SpongePowered/SpongeForge#2444]
SpongeForge version: 1.12.2-2705-7.1.0-BETA-3445
Forge version: 14.23.4.2705
Java version: 1.8.0_181
Operating System: Linux

All Plugins/Mpds: https://gist.github.com/PoroUsedSnax/9ddb81c3fa6561a31d51c578d56545ca

For some reason we've recently been getting some strange messages from sponge regarding our colonists. They don't mention enough details to debug it from our side so I will report it here.

PhaseContext: https://gist.github.com/PoroUsedSnax/52a365e8f4c7553e51ba7fda8edc28b6

**Comment by phit** [comment]
I believe this may have been fixed https://github.com/SpongePowered/SpongeForge/issues/2448
can you reproduce it on 7.1.2?

**Comment by gabizou** [comment]
This is already fixed, block drops captured during entity ticks is already fixed for dynamic trees in this fashion. 7.1.2 SF will have the fix, but not 7.1.1.
