### ISSUE TITLE
Building tool Minecolonies bypasses protection

### ISSUE THREAD

**Issue by jinkhya** [SpongePowered/SpongeForge#2445]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3447.jar
- Forge version: 2751
- Java version: 1.8.0_121-b13
- Operating System: Centos 7.3.1611

- Plugins/Mods: Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, BetterChunkLoader, CatClearLag, Enjin Minecraft Plugin, GriefPrevention, LuckPerms, MMCRestrict, Nucleus, Prism
Mods are just forge and minecolonies-1.12.2-0.9.109-ALPHA-universal.jar

**Issue Description**
It looks like Sponge is not tracking events from the "building tool" from Minecolonies wich is an issue for claims. You can use the wand outside a claim, use the arrows to move it into somebody else's claim, validate and grief. 

I'll give you the log of what's tracked, after that there's nothing else about when I validated the build : 
https://pastebin.com/pjq9yGrT

**Comment by phit** [comment]
https://github.com/ldtteam/minecolonies/blob/0384d90ff1f081ef3b806c2dc7abef3d0d21509a/src/main/java/com/minecolonies/coremod/network/messages/BuildingMoveMessage.java#L141

**Comment by phit** [comment]
https://github.com/ldtteam/minecolonies/blob/0384d90ff1f081ef3b806c2dc7abef3d0d21509a/src/main/java/com/minecolonies/coremod/network/messages/BuildingMoveMessage.java#L141

**Comment by Zidane** [comment]
Closing as we cannot support mods that do their own packet system to place blocks in-which we'll never truly be able to provide the player that is doing it (and anything other info GP would need to block it).
