### ISSUE TITLE
JurassicCraft and more (some console spam)

### ISSUE THREAD

**Issue by avescarelo** [SpongePowered/SpongeForge#2447]
**I am currently running**

- SpongeForge version: 7.1.0-BETA-3440 
- Forge version: 2760
- Java version: 8
- Operating System: Linux

- Plugins:
ActionBroadcaster, AtherysCore, AtherysParties, FAWE, griefprevention, LuckPerms, Nucleus, shabbyholograms, TotalEconomy, ucfa, UltimateChat, VoxelSniper

- Mods:
Antiqueatlas, AppleCore, AutoRegLib, Carry-On, ContainerFix, Earthworks, JEI, JurassiCraft, llibrary, Quark, Roughmobs2, Solcarrot, The Betweenlands, WearableBackpacks

**Issue Description**
The server has been some console spam in **debug.log** before i install spongeforge.

debug.log - https://gist.github.com/pingvikin/fcfb7e048a2966210807e09a1712202b
latest.log - https://gist.github.com/pingvikin/905dcf5607d46b6aeef613ddcab20e2a

**Comment by phit** [comment]
possibly related to https://github.com/SpongePowered/SpongeForge/issues/2403

**Comment by Zidane** [comment]
Ran this with latest SF, GP, and JurassicCraft. Encountered no issues with it.
