### ISSUE TITLE
Bug witch DynamicTrees. Don't drop after break tree

### ISSUE THREAD

**Issue by yaroslav4167** [SpongePowered/SpongeForge#2448]
**I am currently running**

- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3454
- Forge version: 14.23.4.2758
- Java version: 8
- Operating System: Debian

- Plugins/Mods: 
Plugins (24): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge,  FastAsyncWorldEdit, AntiBot for Sponge, BlockyArena, Broadcast, CatClearLag, GriefPrevention, KeepInventorySponge, LuckPerms, MMCReboot, MMCTickets, MagiBridge, Mirage, Nucleus, Plan, ProtectionPerms, Scavenger, UltimateChat, Web-API, WebCmd, WorldEdit
Mods (78): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Aether Legacy, Ancient Warfare Automation, Ancient Warfare Core, Ancient Warfare NPCs, Ancient Warfare Structures, Ancient Warfare Vehicles, Antique Atlas, Astral Sorcery, AutoRegLib, Baubles, Better Builder's Wands, Better Questing, BiblioCraft, Bookshelf, Botania, Charset, Chisel, Chisels & Bits, CodeChicken Lib, Construct's Armory, CraftTweaker JEI Support, CraftTweaker2, Cucumber Library, Custom NPC Spawner, CustomNPCs, Dynamic Trees, Dynamic Trees TC, Dynamic Trees for Traverse, Enchanting Plus, EventHelper, Example Mod, FoamFix, FoamFixCore, Iron Chest, IvToolkit, JJ Coin, Just Enough Items, LibrarianLib, LibrarianLib Stage 2, MCMultiPart, MTLib, Mantle, Mekanism, MekanismGenerators, MekanismTools, Mod Support, Mod Tweaker, Mystical Agriculture, NPC Integration, Quark, RandomPatches, Reborn Core, RebornStorage, Recurrent Complex, Refined Storage, Shadowfacts' Forgelin, Smooth Font Core, Standard Expansion, Thaumcrafft Inventory Scanning, Thaumcraft, Thaumic Grid, Thaumic Tinkerer, The One Probe, The Twilight Forest, Tinker's JEI, Tinkers Tool Leveling, Tinkers' Construct, Traverse, V0id's Smart Backpacks, Vein Miner, Wizardry

**Issue Description**
After breaking tree. It does not drop seeds / wood.
And also the console displays: [LOG](https://hastebin.com/abicofaxin.hs)
On the version sponge 1.12.2-2705-7.1.0-BETA-3361 a bug is not observed.

**Comment by ImMorpheus** [comment]
@yaroslav4167 do not use bit.ly links

Plugins/Mods: https://hastebin.com/pucuqesawu.hs

**Comment by yaroslav4167** [comment]
Sponge: 7.1.2-RC3487 problem still not solved =/
[https://hastebin.com/oxohuhumah.hs](https://hastebin.com/oxohuhumah.hs)

**Comment by yaroslav4167** [comment]
In sponge 7.1.3-RC3495 bug don't reproduced.
Problem solved! =)
