### ISSUE TITLE
Flan's Mod invalid event annotation

### ISSUE THREAD

**Issue by FrayFox** [SpongePowered/SpongeForge#2449]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3455
- Forge version: forge-1.12.2-14.23.4.2759
- Java version: Version 8 update181
- Operating System: Windows10

- Plugins/Mods:
 Plugins (14): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, GriefPrevention, LangSwitch, Lottery, LuckPerms, MMCRestrict, Nucleus, ProjectCore, RankUpper, Total Economy, VillagerShops
Mods (47): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AppleSkin, Aroma1997's Dimensional World, Aroma1997Core, AromaBackup, AromaBackuprecovery, BiblioCraft, Biomes O' Plenty, ChickenChunks, CoFH Core, CoFH World, CodeChicken Lib, Construct's Armory, EnderStorage, Extra Utilities 2, Extreme Reactors, Flan's Mod, Flan's Mod: Apocalypse, Forestry, Industrial Foregoing, Inventory Tweaks, Iron Chest, Just Enough Items, Mantle, Morpheus, OpenBlocks, OpenComputers, OpenComputers (Core), OpenModsLib, OpenModsLib Core, Redstone Flux, Shadowfacts' Forgelin, Tesla Core Lib, Tesla Core Lib Registries, The Twilight Forest, Thermal Expansion, Thermal Foundation, Tinkers' Construct, UniDict, WanionLib, Zero CORE, mob_grinding_utils

**Issue Description**
All of the additions from Flan's Mod do not at all respect GriefPrevention protections, and after reading a bit i'm assuming that they do not fire events that GriefPrevention can handle. Looking through the server log i'm getting this:
 [Server thread/ERROR] [FML]: The mod flansmod appears to have an invalid event annotation EventHandler. This annotation can only apply to methods with recognized event arguments - it will not be called

(If needed I can run again with only flans, and SpongeForge but i don't have a reason to believe another mod/plugin is causing this.

https://gist.github.com/FrayFox/136fde51514d877c73cb85210fe384da

**Comment by RallyDanny** [comment]
Any solutions?
