### ISSUE TITLE
[Latest] WorldServer missing? Crash on updateTimeLightAndEntities()

### ISSUE THREAD

**Issue by TheFlash787** [SpongePowered/SpongeForge#2450]
**I am currently running**
- SpongeForge version: 2705-7.1.0-BETA-3448
- Forge version: 2751
- Java version: 1.8.0_171
- Operating System: Ubuntu 16.04
- Plugins/Mods:
Enigmatica 2 Expert Skyblock: https://gist.github.com/TheFlash787/a9abc11c3ff1012a498780fe79b23d77

**Plugins:** https://gist.github.com/TheFlash787/50bfa77f739d24d7c5037423559dad2b

**Issue Description**

Recently, I have been getting these anomalous exceptions upon the server launch (after player's are able to reconnect) which crashes the server. The report will be attached below. I am led to believe that there isn't a WorldServer present at the updateTimeLightAndEntities() which is why the exception is thrown and the server stops. I will attach my .mixin.out files and the crash report. This can be fixed by rolling back the server which in the end, it happens again. This is permanent and crashes the server indefinitely when it has happened once.

**Resources:**
- Class Files: https://files.modrealms.net/class.zip (https://www.virustotal.com/#/url/d9b9634586acf5e14e9309a80cce50a5797c48e08e0bd07af6bfaad0834a787d/detection)
- Crash Report: https://gist.github.com/TheFlash787/ff08f62a86f2b1bf866fdf922d12675b

**Comment by Dockter** [comment]
Offline mode server?

**Comment by TheFlash787** [comment]
@Dockter Yes, this is running with Bungee

**Comment by phit** [comment]
was caused by unloader https://minecraft.curseforge.com/projects/unloader
also see https://github.com/SpongePowered/SpongeForge/issues/2195
