### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by FrayFox** [SpongePowered/SpongeForge#2454]
I am currently running

SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3361
[crash-2018-09-23_21.09.53-server.txt](https://github.com/SpongePowered/SpongeForge/files/2409512/crash-2018-09-23_21.09.53-server.txt)

Forge version: forge-1.12.2-14.23.4.2759
Java version: Version 8 update181
Operating System: Windows10
Plugins/Mods:
Plugins (14): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, GriefPrevention, LangSwitch, Lottery, LuckPerms, MMCRestrict, Nucleus, ProjectCore, RankUpper, Total Economy, VillagerShops
Mods (47): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AppleSkin, Aroma1997's Dimensional World, Aroma1997Core, AromaBackup, AromaBackuprecovery, BiblioCraft, Biomes O' Plenty, ChickenChunks, CoFH Core, CoFH World, CodeChicken Lib, Construct's Armory, EnderStorage, Extra Utilities 2, Extreme Reactors, Flan's Mod, Flan's Mod: Apocalypse, Forestry, Industrial Foregoing, Inventory Tweaks, Iron Chest, Just Enough Items, Mantle, Morpheus, OpenBlocks, OpenComputers, OpenComputers (Core), OpenModsLib, OpenModsLib Core, Redstone Flux, Shadowfacts' Forgelin, Tesla Core Lib, Tesla Core Lib Registries, The Twilight Forest, Thermal Expansion, Thermal Foundation, Tinkers' Construct, UniDict, WanionLib, Zero CORE, mob_grinding_utils
Issure Discription:
Crash on startup without any explination i can decifer, happening multiple times now.

https://gist.github.com/FrayFox/f4e090cc5dd8a29eb2ebabd3e14dbcac

**Comment by phit** [comment]
your `sponge_level.dat` is corrupted

> `Attempt failed when reading Sponge level data for [world] from file [level_sponge.dat]!`

restore it from a backup, in the future make sure to shut down your server properly, stuff like this is usually caused by harddrive issues or server power loss
