### ISSUE TITLE
Applied Energistics 2 : memory card won't save configuration to link tunnels

### ISSUE THREAD

**Issue by jinkhya** [SpongePowered/SpongeForge#2456]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3440.jar
- Forge version: 2715
- Java version: 1.8.0_121-b13
- Operating System: Centos 7.3.1611

Plugins/Mods: Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, BetterChunkLoader, CatClearLag, Enjin Minecraft Plugin, GriefPrevention, LuckPerms, MMCRestrict, Nucleus, Prism

modpack : ATM3

**Issue Description**
When I shift right click on an P2P Tunnel to save the configuration (so that I could link it to another p2p) it doesn't save but says every time in chat : 
"Invalid Machine. Memory card cleared"

I looked at the console and nothing shows when I Shift right click the tunnel.

I tried in singleplayer (wich doesn't have sponge) and it works fine.

**Comment by Shybella** [comment]
I also encounter this on SF: 3450 

This does not happen on 3361.

**Comment by jinkhya** [comment]
oh good to know, thank you.

**Comment by jinkhya** [comment]
It seems to have fixed itself after a restart, not sure if it will or won't derp again.

**Comment by Shybella** [comment]
It will, that same-thing happens to me as-well

Yes, if theres anyway we can provide for information to speed the fix of this up we will gladly help.

**Comment by gabizou** [comment]
So, to reproduce this issue, what steps do I need to do? 
AE2 + SpongeForge
1) Place a P2P Tunnel 
2) Shift right click on placed tunnel
3) Get error?

**Comment by phit** [comment]
can't reproduce this with
appliedenergistics2-rv5-stable-11.jar
1.12.2-2705-7.1.0-BETA-3465

is there anything special you need to do to "break" it otherwise this is gonna be hard to debug

**Comment by Shybella** [comment]
I will work on getting you a reliable reproduction method for you today or tomorrow. This may take longer to get

**Comment by phit** [comment]
happens for others in singleplayer aswell and without sponge 

https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3727
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3763

**Comment by Shybella** [comment]
Okay, good. I was unable to recreate the issue or reproduce, could be related to malformed stored ae2 data. That was wiped recently.

**Comment by phit** [comment]
yeah having the same issue on my server every so often, for me a restart fixes it every time not sure what's going on

**Comment by thehobojoe** [comment]
Same issue here. Restarting client and server doesn't fix it. Enigmatica 2 Expert modpack.

Shift-right clicking on a p2p tunnel just says "memory card cleared".

**Comment by lesyriad** [comment]
Issue confirmed AE2

To recreate:  Put any item in your offhand.  With the memory card in your main hand shift-rightclick the p2p and it will say memory card cleared instead of configuring the memory card and p2p tunnel.

Workaround: remove any item from your offhand.

**Comment by phit** [comment]
I did not have any item in my offhand in testing this and it was still happening.

**Comment by richardcox13** [comment]
Just happened to me.
Restart didn't work. But removing item from off hand did.
The "device cleared" messages really don't help :-(

**Comment by Shybella** [comment]
Good luck dealing with the AE2 team. 

Apparently this is fixed in the latest AE2 but have not checked if thats true.

**Comment by kwphysics** [comment]
This thread saved me! I removed item from my off hand and the problem was solved.
Enigmatica 2 Expert Skyblock

**Comment by Yuuki-Shino** [comment]
I’m having the same issue in the latest version of the direwolf20 pack on a server however. Are there any settings on the server that might have p2p tunnels disabled? When I try it on single player it works perfectly... and its extremely frustrating. Any insight would be appreciated

**Comment by Caeas** [comment]
Same Problem for me on my own server (no sponge)

AE2 Version: appliedenergistics2-rv6-stable-7.jar
Forge: forge-1.12.2-14.23.5.2838-universal.jar

**Comment by Yuuki-Shino** [comment]
If anyone is still having the issue make sure to remove any item from your off-hand, this was the problem for me

**Comment by Caaruzo** [comment]
Greetings, i dont wear any offhand but have the same issue. Reported that also to AE2 Repo. (https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4123)

Someone know what it else could be?

**Minecraft Version:** 1.12.2
**AE2 Version:** appliedenergistics2-rv6-stable-7.jar
**Forge:** forge-1.12.2-14.23.5.2838-universal.jar
**Using Sponge?** No

**Comment by Caaruzo** [comment]
Ive recognized now, that it just happens on Server Multiplayer. If i copy the world to single player it works fine. but that cant be the solutuion. Reported that to ae2 alrewady. they closed and said its a forge / vanilla bug. After i posted it to forge they said its not an issue and closed it, i should report to theire forum. After i done that i dont get any answer anymore. Isnt there real any solution to fix that?

**Comment by Shybella** [comment]
Pretty much SOL at this point, it's a problem with AE2. It's not a problem with Forge or Vanilla or Sponge. That's the  3rd or 4th different response I've seen from yueh about it. He has no clue and either do most of us, seems to be a complicated problem to fix.

**Comment by rendragnet** [comment]
Ahhhhh, thankyou, just started using P2P tunnels on FTB Revelation, and having this issue.  Unequipped my shield from my offhand, and voila, I can now use the memory card to link my tunnels :)
