### ISSUE TITLE
Update/sponge - crash

### ISSUE THREAD

**Issue by Keaton1188** [SpongePowered/SpongeForge#2457]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3460
- Forge version: 14.23.4.2760
- Java version: Java openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-b12)
- Operating System: CentOS Linux release 7.2.1511

- Plugins/Mods: Dw20 1.12/Sponge

**Issue Description**
Hi there.. created a fresh Dw20 1.12 server, all working fine.. added the latest spongeforge and I am getting a server crash.. we have also had some issues with updating other servers due to forge being ahead but spongeForge not (I believe). 

https://pastebin.com/fcgD4CZk

**Comment by phit** [comment]
https://github.com/SpongePowered/SpongeForge/issues/2446#issuecomment-422510456
