### ISSUE TITLE
Cause Stack Frame Corruption!

### ISSUE THREAD

**Issue by FrayFox** [SpongePowered/SpongeForge#2459]
**I am currently running**
- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3461
- Forge version: 1.12.2-14.23.4.2759
- Java version: Java8U181
- Operating System: Win10

- Plugins/Mods:
 Plugins (15): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, GriefPrevention, LangSwitch, Lottery, LuckPerms, MMCRestrict, Nucleus, ProjectCore, RankUpper, Total Economy, VillagerShops, WalletDrop

Mods (47): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AppleSkin, Aroma1997's Dimensional World, Aroma1997Core, AromaBackup, AromaBackuprecovery, BiblioCraft, Biomes O' Plenty, ChickenChunks, CoFH Core, CoFH World, CodeChicken Lib, Construct's Armory, EnderStorage, Extra Utilities 2, Extreme Reactors, Flan's Mod, Flan's Mod: Apocalypse, Forestry, Industrial Foregoing, Inventory Tweaks, Iron Chest, Just Enough Items, Mantle, Morpheus, OpenBlocks, OpenComputers, OpenComputers (Core), OpenModsLib, OpenModsLib Core, Redstone Flux, Shadowfacts' Forgelin, Tesla Core Lib, Tesla Core Lib Registries, The Twilight Forest, Thermal Expansion, Thermal Foundation, Tinkers' Construct, UniDict, WanionLib, Zero CORE, mob_grinding_utils

**Issue Description**
Server constantly freezes while starting up, and while running, with the only fix seeming to be that i need to open the console and press ENTER for it to continue running. If I leave the server as is for a prolonged period of time before manually updating it, it will crash from a tick being too long. My processor and memory are not being overloaded or close to overloaded while the server is running, with it idling low while the servers encounters this issue.

https://gist.github.com/FrayFox/cf2905c76b9c07b806e7abd51d49d475

UPDATE:
Got error with the flag -Dsponge.debugcauseframes=true
When hitting Enter, before crashing, the console log was spammed with a player entering and leaving afk, as seen in the log
Cause Stack Frame Corruption!
attached is the log + crash report
https://gist.github.com/FrayFox/a19c23ab4ee254afc7de5a56d024496f

**Comment by phit** [comment]
add your full debug.log please

**Comment by FrayFox** [comment]
> add your full debug.log please

Just added to post and this comment
https://gist.github.com/FrayFox/a19c23ab4ee254afc7de5a56d024496f

**Comment by phit** [comment]
@dualspiral any idea whats happening here?

**Comment by ghost** [comment]
Hey @FrayFox my server was also having this issue beforehand, I managed to fix this issue temporarily by going into the **server.properties** and setting the `max-tick-time=` to **-1**

Further; you may want to remove some of those plugins; I had a plugin (MMCRules) that was freezing up the server whenever someone accepted the rules!

For all _SpongeForge_ developers; it may help you to check out why the servers keep freezing, _both with certain plugins and without them_

**Comment by phit** [comment]
gonna close this, as i have no way to reproduce this nor does the log mention any `Cause Stack Frame Corruption`

if this is still an issue for you please open a new issue with a way to reproduce it
