### ISSUE TITLE
 Could not pass DestructEntityEvent$Death$Impl to Plugin

### ISSUE THREAD

**Issue by FrayFox** [SpongePowered/SpongeForge#2460]
I am currently running

SpongeForge version: 1.12.2-2705-7.1.0-BETA-3461

Forge version: 1.12.2-14.23.4.2759

Java version: Java8U181

Operating System: Win10

Plugins/Mods:
Plugins (15): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, GriefPrevention, LangSwitch, Lottery, LuckPerms, MMCRestrict, Nucleus, ProjectCore, RankUpper, Total Economy, VillagerShops, WalletDrop

Mods (47): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AppleSkin, Aroma1997's Dimensional World, Aroma1997Core, AromaBackup, AromaBackuprecovery, BiblioCraft, Biomes O' Plenty, ChickenChunks, CoFH Core, CoFH World, CodeChicken Lib, Construct's Armory, EnderStorage, Extra Utilities 2, Extreme Reactors, Flan's Mod, Flan's Mod: Apocalypse, Forestry, Industrial Foregoing, Inventory Tweaks, Iron Chest, Just Enough Items, Mantle, Morpheus, OpenBlocks, OpenComputers, OpenComputers (Core), OpenModsLib, OpenModsLib Core, Redstone Flux, Shadowfacts' Forgelin, Tesla Core Lib, Tesla Core Lib Registries, The Twilight Forest, Thermal Expansion, Thermal Foundation, Tinkers' Construct, UniDict, WanionLib, Zero CORE, mob_grinding_utils
**Issue Description**
Sponge for whatever reason is unable to send Death Events to one of my plugins, making it completely useless.

unknown if related: server crashing from prolonged tick with no obvious reason

latest.log -> https://gist.github.com/FrayFox/53af0e0733864663b96e00039c4c7064
debug.log -> https://gist.github.com/FrayFox/44ce06ce9bac4fce572c58cf2f955651
crashreport.log -> https://gist.github.com/FrayFox/17242dbb823b5a7a097f3b4ee5d82793

**Comment by phit** [comment]
report the errors to `walletdrop`, the crash looks unrelated something is locking up during file saves in the windows file system
