### ISSUE TITLE
java.util.concurrent.ExecutionException: java.lang.NullPointerException

### ISSUE THREAD

**Issue by prokopiy** [SpongePowered/SpongeForge#2464]
**I am currently running**

- SpongeForge version: 3472
- Forge version: 2705
- Java version: 1,8
- Operating System: Ubuntu 16.04

java.util.concurrent.ExecutionException: java.lang.NullPointerException                                                                       
<------>at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_181]                                                         
<------>at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_181]                                                            
<------>at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]                                                                   
<------>at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:294) [SpongeImplHooks.class:1.12.2-2705-7.1.0-BETA-3472
<------>at net.minecraft.server.MinecraftServer.redirect$onRun$zjk000(MinecraftServer.java:3970) [MinecraftServer.class:?]                    
<------>at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]                              
<------>at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]                                 
<------>at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]                              
<------>at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]                                       
<------>at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]                                                                                
Caused by: java.lang.NullPointerException                                                                                                     
<------>at com.ebkr.expansiveenergy.items.ItemExpansiveWrench.func_180614_a(ItemExpansiveWrench.java:34) ~[ItemExpansiveWrench.class:?]       
<------>at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:2965) ~[aip.class:?]                                                     
<------>at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:1326) ~[or.class:?]           
<------>at net.minecraft.network.NetHandlerPlayServer.redirect$onProcessRightClickBlock$zio000(NetHandlerPlayServer.java:2415) ~[pa.class:?]  
<------>at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:739) ~[pa.class:?]         ehind, skipping 47 ti
<------>at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]                        
<------>at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]                        
<------>at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) ~[PacketPhaseUtil.cl
<------>at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlg000(SourceFile:539) ~[hv$1.class:?]                           
<------>at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]                                                        
<------>at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]                                             
<------>at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]                                                            
<------>at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]                                                                  
<------>... 7 more

**Comment by gabizou** [comment]
Steps to reproduce? Plugins? Mods? 

From the stack trace alone:
[The mod isn't checking if a TileEntity is null or not](https://github.com/ebkr/Expansive-Energy/blob/c2e3816f674078a3d009afcf58a5cf2083dbf17f/src/main/java/com/ebkr/expansiveenergy/items/ItemExpansiveWrench.java). It feels as though the line of execution would have already resulted in a null regardless if sponge is installed or not.
