### ISSUE TITLE
thrown tinkers items have duplicate textures

### ISSUE THREAD

**Issue by duhadventure** [SpongePowered/SpongeForge#2467]
**I am currently running**
- SpongeForge version:  Beta 3477
- Forge version: 2705
- Java version: Java 8
- Operating System: Linux Server

- Plugins/Mods:
`Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, Aether Legacy, Alternate Spawn, AppleCore, Applied Energistics 2, ArchitectureCraft, ArmoreableMobs, Armory Expansion, Astral Sorcery, Attribute Fix, AutoRegLib, Baubles, Baubley Heart Canisters, Better Records, BiblioCraft, Biomes O' Plenty, Blood Magic: Alchemical Wizardry, Bookshelf, Botania, Ceramics, Chameleon, Chisel, CoFH Core, CodeChicken Lib, Construct's Armory, Cooking for Blockheads, CosmeticArmorReworked, CosmeticArmorReworked Integration for TombManyGraves2, CraftTweaker JEI Support, CraftTweaker2, Cravings, CustomNPCs, Cyberware, Cyclops Core, Dakimakura Mod, Damage Control, Decocraft, DummyCoreUnofficial, Embers Rekindled, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, Erebus, EvilCraft, EvilCraft-Compat, Expanded Arcanum, Extra Alchemy, Extra Cells 2, Extra Utilities 2, ExtraBotany, Grimoire of Gaia 3, Guide-API, Harvest Tweaks, Immersive Engineering, Immersive Petroleum, In-core-poreal, Incorporeal, JourneyMap, Just Enough Items, LagGoggles, LibrarianLib, LibrarianLib Stage 2, LimeLib, Loot Bags, LootTweaker, Lost Souls, Magical Psi, Mantle, Medic Me, Not Enough Items, OpenBlocks, OpenModsLib, OpenModsLib Core, Pam's HarvestCraft, Parrot Power, Plated, PlusTiC, Potion Core, Psi, Quark, Random PSIdeas, Redstone Arsenal, Redstone Flux, Redstone Paste, Reliquary, Rough Mobs 2, Set Effect, Shadowfacts' Forgelin, Some Like It Dry, Soot, Spartan Shields, Spice of Life: Carrot Edition, Spiked Foods, Storage Drawers, Storage Drawers Extras, TOP Addons, Thaumcraft, Thaumic Bases, Thaumic Gadgets, Thaumic Periphery, Thaumic Terminal, The Lost Cities, The One Probe, The Spice of Life, The Twilight Forest, Thermal Solars, Tinker I/O, Tinker's Aether, Tinkers Alloying Addon, Tinkers Tool Leveling, Tinkers' Complement, Tinkers' Construct, TinkersExtras, Tweakers Construct, Vanishment Point, Varied Commodities, Various Oddities, Wings, Horns, and Hooves, the Ultimate Unicorn Mod!, Wizardry, WorldEdit, playerstorage`

**Issue Description**
https://gfycat.com/BestFelineCopperhead
When throwing down a built weapon or armor from Tinkers Construct or Construct's Armory, it will render as if it is dropping hundreds of the item, but you can only pick one up. This lags out the clients in visible range. I removed sponge from the server, and it fixed the problem. It will do it regardless of sponge version. When sponge is added back in the issue returns. Even when no other plugins are loaded. 

<!-- Please provide a *full* server log (and crash-report if applicable).
Error doesn't show up in console log.

**Comment by phit** [comment]
see also https://github.com/SpongePowered/SpongeForge/issues/2433

**Comment by duhadventure** [comment]
> see also #2433

Yea it is the same issue,  but they said to update SpongeForge, and this version is higher than theirs. The only difference is they are using a higher version of forge than us. I thought we couldn't use higher versions than 2705 with SpongeForge?

**Comment by phit** [comment]
yeah was just linking for reference keeping, you are on a newer version so its all good. for the forge version you can, its just not guaranteed to work! but to my knowledge sponge works fine with latest forge

**Comment by phit** [comment]
I was unable to reproduce this
TConstruct-1.12.2-2.10.1.87.jar
1.12.2-2705-7.1.0-BETA-3477 

can you please figure out which mods are required for this? I was running a quite large modpack when testing this aswell so you can maybe diff that modlist against yours, the pack i was running was StoneBlock 1.0.17

**Comment by duhadventure** [comment]
> I was unable to reproduce this
> TConstruct-1.12.2-2.10.1.87.jar
> 1.12.2-2705-7.1.0-BETA-3477
> 
> can you please figure out which mods are required for this? I was running a quite large modpack when testing this aswell so you can maybe diff that modlist against yours, the pack i was running was StoneBlock 1.0.17

it stopped happening after i removed tweakers construct
[tweakersconstruct-1.12.2-1.2.0](https://minecraft.curseforge.com/projects/tweakers-construct/files/2530249)
looks like [#2433](https://github.com/SpongePowered/SpongeForge/issues/2433) had that mod as well

**Comment by phit** [comment]
probably related to https://github.com/RCXcrafter/TweakersConstruct/blob/master/src/main/java/com/rcx/tweaconstruct/tweaks/ToolVincibility.java#L31

**Comment by RCXcrafter** [comment]
Looks like I'm a litle late to the party, for anyone still having this issue, setting "Tool Uninvincibility" to false will disable my mod from messing with dropped items.
I'll see what I can do on my end to fix this issue.

**Comment by ImMorpheus** [comment]
Still able to reproduce with TConstruct-1.12.2-2.12.0.135.jar and TweakersConstruct updated to https://github.com/RCXcrafter/TweakersConstruct/commit/e3738c6b8a8f7aeaf7986430c727749f075c2394

**Comment by ImMorpheus** [comment]
> Uninvincibility" to false will disable my mod from messing with dropped items.

The problem is on the client. I was able to reproduce this on a server with just TinkersConstruct. (TweakersConstruct was on the client)

For anyone testing this, you can't reproduce this on a server without sponge because there's a subtle bug with items drop.

https://github.com/RCXcrafter/TweakersConstruct/pull/17

**Comment by RCXcrafter** [comment]
I still haven't been able to reproduce this but [this version](https://minecraft.curseforge.com/projects/tweakers-construct/files/2727329/download) should no longer have the issue since it has ImMorpheus' pull request merged in.
