### ISSUE TITLE
[Sponge]: Failed to save configuration

### ISSUE THREAD

**Issue by FrayFox** [SpongePowered/SpongeForge#2468]
**I am currently running**

- SpongeForge version: 1.12.2-2705-7.1.0-BETA-3477
- Forge version: 1.12.2-14.23.4.2759
- Java version: 8
- Operating System: Win10

- Plugins/Mods:
 Plugins (14): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, GriefPrevention, LangSwitch, Lottery, LuckPerms, MMCRestrict, Nucleus, ProjectCore, RankUpper, Total Economy, VillagerShops

Mods (57): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AppleSkin, Applied Energistics 2, Aroma1997's Dimensional World, Aroma1997Core, AromaBackup, AromaBackuprecovery, BiblioCraft, Biomes O' Plenty, ChickenChunks, Chisel, Chisels & Bits, CoFH Core, CoFH World, CodeChicken Lib, Construct's Armory, EnderStorage, Extra Cells 2, Extra Utilities 2, Extreme Reactors, Flan's Mod, Flan's Mod: Apocalypse, Forestry, Forge Microblocks, Forge Multipart CBE, Gravestone Mod, Industrial Foregoing, Inventory Tweaks, Iron Chest, Just Enough Items, Mantle, Minecraft Multipart Plugin, Morpheus, OpenBlocks, OpenComputers, OpenComputers (Core), OpenModsLib, OpenModsLib Core, Ranged Pumps, Redstone Flux, Shadowfacts' Forgelin, Tesla Core Lib, Tesla Core Lib Registries, The Twilight Forest, Thermal Expansion, Thermal Foundation, Tinkers' Construct, TorchMaster, UniDict, WanionLib, Zero CORE, mob_grinding_utils

**Issue Description**
A good amount of lag accompanied by an error "Failed to save configuration" I usually encounter this problem when changing dimensions, re spawning, or  using an openBlocks elevator. This error is very frequent and makes it hard to actually play the game. There should be no file system problems as everything is on default perms. 

Possibly related to closed issue report [#1991](https://github.com/SpongePowered/SpongeForge/issues/1991)

Error Itself -> https://gist.github.com/FrayFox/6d384e6f91c5de2bfb10db3afb6f6b11
latest.log -> https://gist.github.com/FrayFox/035a3a765dd9faae13b1d085946de2cc
debug.log -> https://gist.github.com/FrayFox/f5b42601fc97d4cb711c70b705221d94

**Comment by phit** [comment]
can you upload your `config\sponge\custom_data.conf` please
