### ISSUE TITLE
/debug not working

### ISSUE THREAD

**Issue by FrayFox** [SpongePowered/SpongeForge#2473]
**I am currently running**

- SpongeForge version: -3477
- Forge version: 2759
- Java version: 8 U181
- Operating System: wWin10

- Plugins/Mods:
Plugins (15): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, CatClearLag, GriefPrevention, LangSwitch, Lottery, LuckPerms, MMCRestrict, Nucleus, ProjectCore, RankUpper, Total Economy, VillagerShops
Mods (57): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AppleSkin, Applied Energistics 2, Aroma1997's Dimensional World, Aroma1997Core, AromaBackup, AromaBackuprecovery, BiblioCraft, Biomes O' Plenty, ChickenChunks, Chisel, Chisels & Bits, CoFH Core, CoFH World, CodeChicken Lib, Construct's Armory, EnderStorage, Extra Cells 2, Extra Utilities 2, Extreme Reactors, Flan's Mod, Flan's Mod: Apocalypse, Forestry, Forge Microblocks, Forge Multipart CBE, Gravestone Mod, Industrial Foregoing, Inventory Tweaks, Iron Chest, Just Enough Items, Mantle, Minecraft Multipart Plugin, Morpheus, OpenBlocks, OpenComputers, OpenComputers (Core), OpenModsLib, OpenModsLib Core, Ranged Pumps, Redstone Flux, Shadowfacts' Forgelin, Tesla Core Lib, Tesla Core Lib Registries, The Twilight Forest, Thermal Expansion, Thermal Foundation, Tinkers' Construct, TorchMaster, UniDict, WanionLib, Zero CORE, mob_grinding_utils

**Issue Description**
Ive been getting a good amount of lag recently and have not at all been able to remedy it. I decided to try /debug to see if i could get any useful information, but whenever i run it, i get nothing in the dump besides this:

---- Minecraft Profiler Results ----
// I'm working as hard as I can!

Time span: 102000 ms
Tick span: 204 ticks
// This is approximately 2.00 ticks per second. It should be 20 ticks per second

--- BEGIN PROFILE DUMP ---

--- END PROFILE DUMP ---

I am able to use this command fine will all the same mods but without sponge

**Comment by phit** [comment]
please read https://minecraft.gamepedia.com/Commands/debug

also Sponge includes its own profiler you can access through [`/sponge timings`](https://docs.spongepowered.org/stable/en/server/spongineer/commands.html#timings) which may be helpful, for further support you can use our [forums](https://forums.spongepowered.org/) or [chat](https://www.spongepowered.org/chat)
