### ISSUE TITLE
Server Crash / Failed to Start - 1.12

### ISSUE THREAD

**Issue by Keaton1188** [SpongePowered/SpongeForge#2474]
**I am currently running**

- SpongeForge version:  spongeforge-1.12.2-2705-7.1.0-BETA-3477.jar
- Forge version: 14.23.5.2768
- Java version:  Java openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-b12)
- Operating System: CentOS Linux release 7.2.1511

- Plugins/Mods:
StoneBlock 1.0.20

**Issue Description**
Hey, I have updated our StoneBlock server from version 1.0.17 to 1.0.20 and an now experiencing a startup issue when booting the server, any help would be appreciated 

https://pastebin.com/zPV41A7g

**Comment by phit** [comment]
try removing laggoogles

**Comment by Keaton1188** [comment]
Removed lag goggles and got a setup further now into another issue... fun stuff

Crash Report: https://pastebin.com/nXiDeA0m

Also saw this spamming the console: 
![untitled](https://user-images.githubusercontent.com/24898745/46855765-83b61100-cdfc-11e8-8b78-cddf12198b70.png)

**Comment by Keaton1188** [comment]
Crash now fixed ^ 

But sponge is not loading on startup anymore.

Lastest.log - 
[latest.log](https://github.com/SpongePowered/SpongeForge/files/2472214/latest.log)

**Comment by dualspiral** [comment]
JEI is loading an old version of Mixin. Rename the Sponge jar to start with an `a` and try again.

**Comment by Keaton1188** [comment]
Hey Dual, so just re-name it to "aspongeforge-1.12.2-2705-7.1.0-BETA-3481.jar"

**Comment by Keaton1188** [comment]
Ah that sorted it! Strange.. lol

Do I need to report this to JEI?

**Comment by phit** [comment]
probably a good idea, theres no reason for them to use an old version
