### ISSUE TITLE
Quark appears to bypass inventory interaction protections

### ISSUE THREAD

**Issue by DrZoddiak** [SpongePowered/SpongeForge#2476]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3481
- Forge version: 2739 (Minimum required version for mods)
- Java version: 181
- Operating System: Ubuntu 18

- Plugins: https://gyazo.com/fd18aebacbcec14fbb77421301119d15
https://gyazo.com/1e1944ce2dcb3e29e969462613845265
- Mods: https://www.feed-the-beast.com/projects/ftb-revelation/relations/dependencies

**Issue Description** : [Quark](https://github.com/Vazkii/Quark) has [buttons on the side of the inventory](https://gyazo.com/82a614a10aee12b93a05254a28dfbdca) gui so you can quickly pull/push/restock items into chests. This interaction appears to go [un-checked](https://luckperms.github.io/verbose/?3b98kPxO5s) and allows me to pull items out of chests I would normally not be allowed to. For example I am using[ TeslaCrates](https://ore.spongepowered.org/Simon_Flash/TeslaCrate) and I am (as expected) unable to pull items from the gui; however, when using the quark buttons it pulls them out.

https://gist.github.com/DrZoddiak/3df5f7209e4b3c3dcfa42b7227df499c

**Comment by Faithcaio** [comment]
#2289
