### ISSUE TITLE
findByUsername performance issue

### ISSUE THREAD

**Issue by BlayzerQ** [SpongePowered/SpongeForge#2477]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3361
- Forge version: 1.12.2-14.23.4.2760
- Java version: Java 8
- Operating System: Debian 8

Mods: https://paste.dimdev.org/uceyudozif.rb
Plugins: CatClearLag-0.8, 
EconomyLite-7.1.0-2.15.1, 
LuckPerms-Sponge-4.2.103, 
MCClans-1.6, 
Nucleus-1.6.1-S7.1-MC1.12.2-plugin, 
RedProtect-7.5.4-b125-Universal, 
TabManager-1.0.4, 
UltimateChat-1.8.8-b196-Universal

When I try to enter any command with an incorrect nickname (/vanish name, /money name, etc), the server hangs(freeze) and kicks all players.

Stall-report: https://paste.dimdev.org/olakafiquf.nginx
[latest.log](https://github.com/SpongePowered/SpongeForge/files/2479338/latest.log)

**Comment by phit** [comment]
please update sponge, you are over a 100 builds behind, latest is 3481
otherwise you gonna have to figure out what mods/plugins are needed to reproduce this, as this doesn't happen to others and the sponge build you are on has been recommended for quite some time

**Comment by BlayzerQ** [comment]
> please update sponge, you are over a 100 builds behind, latest is 3481
> otherwise you gonna have to figure out what mods/plugins are needed to reproduce this, as this doesn't happen to others and the sponge build you are on has been recommended for quite some time


On last build 3481 still actual. I`am tested.

**Comment by BlayzerQ** [comment]
Check it yourself, I'm sure you will get the same result. Its a critical problem.

**Comment by simon816** [comment]
It's getting stuck at: `com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository.findProfilesByNames`
Could there be an issue connecting to `api.mojang.com`?

**Comment by phit** [comment]
@simon816 yes https://github.com/SpongePowered/SpongeForge/issues/2478
