### ISSUE TITLE
findByUsername performance issue (latest version SpongeForge)

### ISSUE THREAD

**Issue by BlayzerQ** [SpongePowered/SpongeForge#2478]
[latest.log](https://github.com/SpongePowered/SpongeForge/files/2480040/latest.log)
SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3481
Forge version: 1.12.2-14.23.4.2760
Java version: Java 8
Operating System: Debian 8
Mods: https://paste.dimdev.org/uceyudozif.rb
Plugins: CatClearLag-0.8,
EconomyLite-7.1.0-2.15.1,
LuckPerms-Sponge-4.2.103,
MCClans-1.6,
Nucleus-1.6.1-S7.1-MC1.12.2-plugin,
RedProtect-7.5.4-b125-Universal,
TabManager-1.0.4,
UltimateChat-1.8.8-b196-Universal

When I try to enter any command with an incorrect nickname (/vanish name, /money name, etc), the server hangs(freeze) and kicks all players.

Stall-report: https://paste.dimdev.org/agesavepax.nginx

**Comment by BlayzerQ** [comment]
Sorry to have created the second similar question, but I thought that there was no point in answering that there was no answer, that no one would read there.

**Comment by phit** [comment]
yes I asked the question there, so of course I read the answer..
anyway you still didn't answer my question, this works fine for me with a few hundred mods and various plugins, find out what is needed to reproduce this.

**Comment by BlayzerQ** [comment]
i`am install only plugins and spongeforge, no mods.
Plugins: EconomyLite-7.1.0-2.15.1, LuckPerms-Sponge-4.2.103 and Nucleus-1.6.1-S7.1-MC1.12.2-plugin.
Every commands with wrong nickname(offline player or no exist nickname) cause this problem.

**Comment by XakepSDK** [comment]
Performance of this method depends on you network speed, mojand services load status.

**Comment by BlayzerQ** [comment]
> Performance of this method depends on you network speed, mojand services load status.

My firewall is blocked all outgoing traffic by 80/443 ports. It turns out this causes this problem?

**Comment by phit** [comment]
yes.. the server kinda needs to talk to mojang for player profiles

anyway this should be handled more gracefully instead of locking up the server

**Comment by gabizou** [comment]
> anyway this should be handled more gracefully instead of locking up the server

We can't, unless we go and change all username lookups to be delayed until said username lookup completes. 

Networking blocking or throttling username lookups isn't caused by sponge as the vanilla server will perform the same sort of issues that sponge is running into.
