### ISSUE TITLE
Sponge isn't working but server loads 

### ISSUE THREAD

**Issue by Loneflint** [SpongePowered/SpongeForge#2484]
**I am currently running**
i5_8600k   GTX1060-6G 16 gigs of ram

- SpongeForge version:1.12.2-2768-7.1.3-RC3495  
- Forge version: 1.12.2 - 14.23.5.2768
- Java version: java 8 update 191 (64-bit)
- Operating System:windows 10

- Plugins/Mods:
I can't run the command /sponge mods because sponge won't load.

[1.12]MoVillages-1.5.4
AdditionalBanners-1.12.2-1.1.43
AdditionalLootTables-1.12-2.0.3.42
aether_legacy-1.12.2-v3.2
AIImprovements-1.12-0.0.1b3
ancientwarfare-1.12.2-2.6.1.390
animania-1.12.2-1.5.1.1
antiqueatlas-1.12.2-4.4.9
AutoRegLib-1.3-20
BackTools-1.12.2-7.0.0
Baubles-1.12-1.5.2
BetterFps-1.4.8
BiblioCraft[v2.4.5][MC1.12.2]
BiomesOPlenty-1.12.2-7.0.1.2402-universal
Bookshelf-1.12.2-2.3.559
Chunk Pregenerator V1.12-1.9.1
ClaySoldiersMod-1.12.2-3.0.0-beta.1.1
CodeChickenLib-1.12.2-3.2.2.353-universal
CombinedPotions-1.12-1.1
comforts-1.12.2-1.3.0
conarm-1.12.2-1.2.0
Controlling-3.0.6
coroutil-1.12.1-1.2.13
CraftStudio-1.0.0.93-mc1.12-alpha
CraftTweaker2-1.12-4.1.11
CSR-1.12-1.0
CustomMainMenu-MC1.12.2-2.0.8
davincisvessels-1.12-6.340-full
DeathCounter-1.12.1-1.0.0
DoomlikeDungeons-1.11.1-MC1.12.2
drpcore-1.12.2-0.4.5
drpmedieval-1.12.2-0.2.7.3
Dungeons2-mc1.12.2-f14.23.1.2555-v1.3.3
DynamicSurroundings-1.12.2-3.4.9.16
DynamicTrees-1.12.2-0.8.2
DynamicTreesBOP-1.12.2-1.3.2
DynamicTreesTC-1.12.2-1.1.2
Earthworks-1.12-1.3.6
ElecCore-1.12.2-1.8.434
EnchantingTable-1.12-1.1.3
End+Ores-1.12.2-r1
EndReborn [0.1.9]
EvilNotchLib-1.2.3-SNAPSHOT-76
ExpTranslation-1.12.2-1.2.0
FamiliarFauna-1.12.2-1.0.10
fencejumper-1.12-1.0.5
foamfix-0.10.2-1.12.2
GottschCore-mc1.12.2-f14.23.4.2705-v1.5.0
hopperducts-mc1.12-1.5
HorsePower-1.12.2-2.6.1.68
iceandfire-1.5.2
iChunUtil-1.12.2-7.1.4
InventoryTweaks-1.64-dev
ironchest-1.12.2-7.0.52.837
IvToolkit-1.3.3-1.12
jei_1.12.2-4.13.1.220
JJ+Coats+of+Arms+1.12-1.12.2-v1.0.9
JJ+Races+1.12-1.12.2-v1.0.7
JJ+Weapon+Config+1.12-1.12.2-v1.0.2
JustAFewFish-1.7_for_1.12
LibEx-1.12.2-1.0.8
llibrary-1.7.15-1.12.2
LoreExpansion-1.12-1.1.7-13
Mantle-1.12-1.3.2.24
mcjtylib-1.12-3.0.6
MenuMobs-1.12.2-1.21
movingworld-1.12-6.342-full
NameTagsTweaks-1.12
NetherEx-1.12.2-2.0.8
NoMoreRecipeConflict-0.12(1.12.2)
notenoughroofs-1.12.2-0.8.0.0
OptiFine_1.12.2_HD_U_D3 
OreController-1.12-1.0.12
overpoweredarmorbar-1.12.2-0.3.2
Pam's HarvestCraft 1.12.2za
PassthroughSigns-1.12.2-2.1.4
placeableitems-3.3
Player-API-Core-1.12.2
ProgressiveBosses-1.3.2-mc1.12.x
Quark-r1.5-130
QuickLeafDecay-MC1.12.1-1.2.4
reauth-3.6.0
RecurrentComplex-1.4.7
redstonepaste-mc1.12-1.7.5
Ruins-1.12.2
SanLib-1.12.2-1.5.0
SereneSeasons-1.12.2-1.2.6-universal
seteffect-1.12.2-2.2.0
stg-1.12.2-1.2.3
TConstruct-1.12.2-2.10.1.87
TerraCore-1.12-2.1.13
Thaumcraft-1.12.2-6.1.BETA26
ThaumicJEI-1.12.2-1.5.4-22
TheBetweenlands-3.3.13-universal
TinkersComplement-1.12.2-0.2.3b
TorchLever-1.0
TUMAT-1.12.x-1.12.0
Wood+Armors+-+MC+1.12.2+(1.1)

ALL MODS ARE UP TO DATE

Plugins
Nucleus-1.6.2-s7.1-MC1.12.2

**Issue Description**
when i start the server it starts fine. I can join the server and stuff, but sponge isn't working and either are the plugins (nucleus)  

Doesn't crash so no crash report

Server Log

After renaming the sponge file. Server Log

https://gist.github.com/phit/3a4d875ee2fad7022990da05e17f7103

**Comment by H3roDude** [comment]
How about the Crashlog instead?

**Comment by phit** [comment]
Both SpongeForge and FoamFix add various optimizations that may not work with each other! Disable the following settings in the `config/foamfix.cfg`
`B:optimizedBlockPos=false` (Sponge adds a similar performance patch)
`B:patchChunkSerialization=false` <https://github.com/asiekierka/FoamFix/issues/166>
