### ISSUE TITLE
SpongeForge crashing 1.12.2 server

### ISSUE THREAD

**Issue by Magesw** [SpongePowered/SpongeForge#2487]
**I am currently running**

- SpongeForge version: 1.12.2-2768-7.1.2
- Forge version: FTBserver-1.12.2-14.23.4.2765-universal / forge-1.12.2-14.23.5.2768-universal
- Java version: Java 8 update 181
- Operating System: Windows Server 2016

- Plugins/Mods: Stoneblock Modpack v 1.0.23 
https://minecraft.curseforge.com/projects/stoneblock/files/2629767

and FTB Sky Adventures Modpack 1.0.0
https://www.feed-the-beast.com/projects/ftb-sky-adventures/files/2628504

**Issue Description**
Adding SpongeForge to either of those modpacks put the server into a constant crash loop.

Stoneblock crashlog and logs
https://gist.github.com/Magesw/c6fc325e8f940c3e3e220527a90b2533
https://gist.github.com/Magesw/a56a3a48e277cfd020e3e99474a724a9

FTB Sky Adventures crashlog and logs
https://gist.github.com/Magesw/8f72246c601da959a50edb782b848b30
https://gist.github.com/Magesw/5f7b69a28febbf02688f976acb85ad2f

**Comment by gabizou** [comment]
Both SpongeForge and FoamFix add various optimizations that may not work with each other! Disable the following settings in the `config/foamfix.cfg`
`B:optimizedBlockPos=false` (Sponge adds a similar performance patch)
`B:patchChunkSerialization=false` <https://github.com/asiekierka/FoamFix/issues/166>

**Comment by Magesw** [comment]
ah I did disable B:optimizedBlockPos=false
didn't know there was another one to do as well, will try again, thanks!
