### ISSUE TITLE
Spongeforge breaks lambda methods somehow

### ISSUE THREAD

**Issue by liach** [SpongePowered/SpongeForge#2488]
- SpongeForge version: 1.12.2-2768-7.1.2
- Forge version: 14.23.5.2770
- Java version: 1.8.0_181
- Operating System: Linux (amd64) version 4.18.7-1.el7.elrepo.x86_64

- Plugins/Mods: https://paste.ubuntu.com/p/nKJVR3rmXG/ (Mainly Railcraft crash)
**Issue Description**
Railcraft/Railcraft#1518 Railcraft/Railcraft#1519

Broken code: https://github.com/Railcraft/Railcraft/blob/1e73836ac147069078c445c757c9524729114fe7/src/main/java/mods/railcraft/common/blocks/BlockEntityDelegate.java#L179

Ask @emo129 for more information.

https://paste.ubuntu.com/p/nKJVR3rmXG/

**Comment by Zidane** [comment]
This may sound odd but remove the method on the new line and put it all on one line and try again.

**Comment by liach** [comment]
wait, i thought i needed to expand it as mentioned in a few prs about chains... what exactly is going on

**Comment by liach** [comment]
It is actually caused by https://github.com/MinecraftForge/MinecraftForge/pull/5127.
