### ISSUE TITLE
Long receiving UUID players.

### ISSUE THREAD

**Issue by GDVE** [SpongePowered/SpongeForge#2490]
**I am currently running**
- SpongeForge version: 1.12.2-2768-7.1.2
- Forge version: 1.12.2-14.23.5.2768
- Java version: 1.8.0_181
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-1~deb9u1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
- Operating System: Debian 9
- Plugins/Mods: LuckPerms, Nucleus, RedProtect, UltimateChat, PixelAutoMessages.

**Issue Description**
For example, to call this problem, players most often click on the private block tool, a couple of clicks and the server freezes.

This can also be called up by entering the command and pressing the TAB to determine the available nicknames (for example / tp [click on TAB)

[crash-2018-10-26_13.38.46-server.txt](https://github.com/SpongePowered/SpongeForge/files/2521727/crash-2018-10-26_13.38.46-server.txt)

**Comment by phit** [comment]
might would be nice if you can get in touch with @dualspiral he's been working on something to improve this

https://github.com/SpongePowered/SpongeCommon/pull/2124

**Comment by GDVE** [comment]
UP!

**Comment by Zidane** [comment]
Closing as dual's PR phit linked above supercedes this and will definitely help this.
