### ISSUE TITLE
SpongeForge Exception generating new chunk

### ISSUE THREAD

**Issue by krisjenner** [SpongePowered/SpongeForge#2491]
**I am currently running**

- SpongeForge version: 1.12.2-2768-7.1.2
- Forge version: 1.12.2-14.23.5.2768
- Java version: 1.8.0_181
- Operating System: Windows 10 64bit

- Plugins/Mods:

Full list on crash report but plugins:
Sponge
LuckPerms

**Issue Description**
Trying to install Sponge on an All The Mods 3 Remix server and it crashes just on startup with a worldgen issue. Tried removing various mods like justenoughdimensions etc. It crashed initially on a RandomThings dimension, but on removing that it crashed on the extrautils quarry dimension. Is it something with modded dims?

<!-- Please provide a *full* server log (and crash-report if applicable).
https://pastebin.com/SPyqRx2C

**Comment by phit** [comment]
gonna need some log files to be able to help you, please upload your `debug.log` to https://gist.github.com/

**Comment by krisjenner** [comment]
> gonna need some log files to be able to help you, please upload your `debug.log` to https://gist.github.com/

[Link](https://gist.github.com/krisjenner/8d0bb15801ebcce61c3d2921c7c3e5f0#file-debug-log)

**Comment by phit** [comment]
looks like some mod is doing some unsafe core modding, possibly https://minecraft.curseforge.com/projects/notenoughids

try removing that mod and if needed replace it with https://minecraft.curseforge.com/projects/jeid

**Comment by ImMorpheus** [comment]
Update to a new version ( https://github.com/fewizz/NotEnoughIDs/issues/80 )

**Comment by krisjenner** [comment]
This works perfectly, thank you guys so much for the help and for being quick to do so.
