### ISSUE TITLE
Millenaire issues with Sponge installed

### ISSUE THREAD

**Issue by H3roDude** [SpongePowered/SpongeForge#2492]
I have a Spongeforge server on the Version: spongeforge-1.12.2-2768-7.1.1.
Millenaire is also Installed on my Server but the Villages are acting weird. Is there an option to disable all Features from Sponge exept from loading plugins or something?
My Issue is that the Signs arent loading and i cant trigger the event that NPCS want to trade with you (They dont go to you and you cant interact)

**Comment by phit** [comment]
no, please open a proper issue with logs and a description of how to reproduce it and it will get fixed eventually
