### ISSUE TITLE
SpongeForge crash on startup in SinglePlayer

### ISSUE THREAD

**Issue by Malachiel87** [SpongePowered/SpongeForge#2493]
**I am currently running**
- SpongeForge version:  1.12.2-2768-7.1.2
- Forge version:  2768
- Java version: 8
- Operating System: Windows 10

- Plugins/Mods: None, clean forge with spongeforge

**Issue Description**: Using it in singleplayer, the client crash after forge finished to load

Crash log:
https://gist.github.com/xion87/3544a4ac4b0dc7d785f967179c3e070a

**Comment by Inscrutable** [comment]
I can confirm this, I had exactly the same issue. Thanks for reporting it @xion87

**Comment by Malrama** [comment]
I have the exact same error with the same issues. :( I can confirm this

**Comment by Aaron1011** [comment]
This should be fixed as of `1.12.2-2768-7.1.3-RC3498`
