### ISSUE TITLE
Lag problem (freezes)

### ISSUE THREAD

**Issue by kasdo** [SpongePowered/SpongeForge#2494]
I have been working with these mods since version 1.6.4 and have never had any problems with them. But now I have problems. When I deleted these mods, the problems disappeared.
2-3 hours after restart my server freez every 25-35 sec for a 10-15 sec.
It also depends on the number of players.

spongeforge-1.12.2-2768-7.1.3-RC3495
Mo'Creatures 12.0.5
CustomMobSpawner 3.11.4

In the config CustomMobSpawner reduced all mobs for 2 times
No errors in the log. Mod creator is "afk", dont want see what a problem.  
Sponge forum:
https://forums.spongepowered.org/t/server-freezes-2-0/25843/16

**Comment by phit** [comment]
install sampler https://forum.industrial-craft.net/thread/10820-wip-1-7-10-fastcraft-1-25-note-all-posts-of-new-members-need-to-be-approved-firs/
can be found in the spoilers here and provide a stall report it creates when the server freezes, otherwise theres not enough information here to do anything

**Comment by kasdo** [comment]
> install sampler https://forum.industrial-craft.net/thread/10820-wip-1-7-10-fastcraft-1-25-note-all-posts-of-new-members-need-to-be-approved-firs/
> can be found in the spoilers here and provide a stall report it creates when the server freezes, otherwise theres not enough information here to do anything

Mod dont working. Server cant startup

**Comment by phit** [comment]
log?

**Comment by kasdo** [comment]
> log?

Instalet from other resource (fastcraft-2) but have errors in log:
https://hastebin.com/ociyufefus.md
Its not problem? I can run my server?

**Comment by phit** [comment]
install sampler its in the second spoiler, NOT fastcraft
http://files.player.to/sampler-1.73.jar

**Comment by kasdo** [comment]
> install sampler its in the second spoiler, NOT fastcraft
> http://files.player.to/sampler-1.73.jar

Okay. I delete Mo'Creatures and CustomMobSpawner but lags isnt gone.
And sampler tps:
![image](https://user-images.githubusercontent.com/7419546/48426327-a038c680-e777-11e8-91f3-7b21e4452c8d.png)
![image](https://user-images.githubusercontent.com/7419546/48426714-5ef4e680-e778-11e8-8435-bc0ecc500da5.png)


![image](https://user-images.githubusercontent.com/7419546/48426442-dd9d5400-e777-11e8-9291-6354a8ad44a2.png)


VisualVM:
![image](https://user-images.githubusercontent.com/7419546/48426844-a67b7280-e778-11e8-8ac8-674d06d1f067.png)
![image](https://user-images.githubusercontent.com/7419546/48427215-53ee8600-e779-11e8-9f81-aab603456132.png)

**Comment by ImMorpheus** [comment]
@kasdo Upload a CPU sampling somewhere or use [Spark](https://ore.spongepowered.org/Luck/spark) and paste the link of the profiling report

**Comment by kasdo** [comment]
> @kasdo Upload a CPU sampling somewhere or use [Spark](https://ore.spongepowered.org/Luck/spark) and paste the link of the profiling report

Spark: https://sparkprofiler.github.io/?UPbNCQAwtM

**Comment by ImMorpheus** [comment]
Try `/spark start --only-ticks-over 800`

See https://github.com/lucko/spark/wiki/Finding-the-cause-of-lag-spikes

**Comment by XakepSDK** [comment]
@ImMorpheus this happens because of GC, i think

**Comment by ImMorpheus** [comment]
10-15 sec is a bit too much for GC lag.

@kasdo Anyway, post an heap dump as well please. 
Also, the report is showing methods from CustomNPC. Can you post the entire mod list ?

**Comment by XakepSDK** [comment]
Ah, i read it like "lag every 10-15-25-35sec"

**Comment by kasdo** [comment]
> /spark start --only-ticks-over 800

https://sparkprofiler.github.io/?56y9pwCj9G

Mods (22): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AI Improvements, Chisel, Classic Combat, CustomNPCs, DrZhark's CustomSpawner, DrZhark's Mo'Creatures Mod, FoamFix, FoamFixCore, Iron Chest, LagGoggles, Sampling Performance Profiler, SpongeForge, Tree Chopper, Varied Commodities, Various Oddities, Zeron Items
[10:00:27] [Server thread/INFO] [nucleus]: Server ran the command: /mods

**Comment by phit** [comment]
that would be world saves, how big are your `Mineshaft.dat`, `Stronghold.dat`, `villages.dat` in `world/data`?

this is a vanilla issue https://bugs.mojang.com/browse/MC-33134

you can fix this by deleting the huge file after your world is fully generated and disable its saving in the sponge optimization settings

e.g. in your sponge global.conf

```
        structure-saving {
            # If 'true', newly discovered structures will be added to this config with a default value.
            auto-populate=true
            enabled=true
            # Per-mod overrides. Refer to the minecraft default mod for example.
            mods {
                minecraft {
                    # If 'false', this mod will never save its structures.
                    enabled=true
                    structures {
                        endcity=true
                        fortress=true
                        mansion=true
                        mineshaft=false
                        monument=true
                        stronghold=true
                        temple=true
                        village=false
                    }
                }
            }
```

**Comment by kasdo** [comment]
Sorry for reopen ticket, but I generate all worlds, delete this files (mineshaft has 45 600 000 size). Off save in config:
![image](https://user-images.githubusercontent.com/7419546/48664091-874b5080-eaaa-11e8-93e7-822a9967ce25.png)

But this .dat files again created and saving (mineshaft after 25 mins restart already has 40 344 size).

**Comment by XakepSDK** [comment]
Enable=true
