### ISSUE TITLE
Chunk Generation Crash

### ISSUE THREAD

**Issue by Rsslone** [SpongePowered/SpongeForge#2497]
**I am currently running**

- SpongeForge version: 1.12.2-2768-7.1.5-RC3506
- Forge version: Forge 14.23.5.2768
- Java version: 1.8.0_152
- Operating System: Win8.1

- Plugins/Mods: I believe the whole list is in the log, sponge won't work so I can't run those commands :(

I have a crash when the server starts to generate chunks. I've tried removing BiomesOP, VanillaFix, and malisisdoors switches and core. Also tried latest spongeforge and recommended spongeforge. If I remove spongeforge it works fine however. Thanks for any assistance you can provide.

https://pastebin.com/V6MH6FaK

**Comment by Shybella** [comment]
Both SpongeForge and FoamFix add various optimizations that may not work with each other! Disable the following settings in the config/foamfix.cfg
`B:optimizedBlockPos=false` (Sponge adds a similar performance patch)
`B:patchChunkSerialization=false` https://github.com/asiekierka/FoamFix/issues/166
