### ISSUE TITLE
Client crash on using "O" in Cyclic inventory crafting table

### ISSUE THREAD

**Issue by krisjenner** [SpongePowered/SpongeForge#2498]
**I am currently running**

- SpongeForge version: 7.1.0
- Forge version: 7688
- Java version: 1.8.0_181
- Operating System:Windows 10

- Plugins: SpongeAPI, Sponge, CatClearLag, Enjin Minecraft Plugin, ForgedPerms, GriefPrevention, LuckPerms, Nucleus, Total Economy
Mods (309): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, /dank/null, AE2 Stuff, AI Improvements, ATM Tweaks, Actually Additions, Actually Baubles, ActuallyComputers, Advanced Generators, Advanced Rocketry, Advanced Rocketry Core, AgriCraft, Akashic Tome, AngelRing 2 Bauble, AppleCore, AppleSkin, Applied Energistics 2, Armory Expansion, Aroma1997's Dimensional World, Aroma1997Core, Astral Sorcery, Attribute Fix, AutoRegLib, B.A.S.E, BD Lib, Backpack, Baubles, Baubley Heart Canisters, Better Builder's Wands, Better Than Mending, BiblioCraft, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Biomes O' Plenty, Bird's Foods, Blockcraftery, Blood Debug, Blood Magic: Alchemical Wizardry, BloodyLib, Bonsai Trees, Bookshelf, Botania, Brandon's Core, CC: Tweaked, Ceramics, Chameleon, Chisel, Chisels & Bits, Clumps, CoFH Core, CoFH World, CodeChicken Lib, CommonCapabilities, Compact Machines 3, Computronics, Construct's Armory, Cooking for Blockheads, Corail Tombstone, CosmeticArmorReworked, CosmeticArmorReworked Integration for TombManyGraves2, CraftTweaker JEI Support, CraftTweaker2, Crafting Tweaks, Cucumber Library, Culinary Construct, Cyclic, Cyclops Core, Dark Utilities, DeepResonance, Diet Hopper, Discord Chat, Dismantler, Draconic Evolution, ElecCore, Electroblob's Wizardry, EluCore, EluLib, Embers Rekindled, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, Ender IO endergy, EnderCore, EnderStorage, Environmental Creepers, Environmental Tech, Exchangers, Extra Cells 2, Extra Rails, Extra Utilities 2, Extreme Reactors, FTB Utilities, FTBLib, FastFurnace, FastWorkbench, Fence Jumper, Flat Colored Blocks, Floralchemy, FoamFix, FoamFixCore, Forestry, Forge Microblocks, Forge Multipart CBE, Forge Votifier, Funky Locomotion, GenDustry, Gotta Go Fast, Guide-API, Harvest, Hooked, Immersive Engineering, Immersive Petroleum, Immersive Tech, Industrial Foregoing, Industrial Wires, IndustrialCraft 2, InfinityLib, InitialInventory, Integrated Dynamics, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTunnels-Compat, Integration Foregoing, Inventory Generators, Inventory Tweaks, Iron Chest, JAOPCA, JAOPCAAgriculture, JEI Bees, JMFixer, JourneyMap, Just A Ore Processing Compatibility Attempt: Additions, Just Enough Dimensions, Just Enough Items, Just Enough Reactors, KJ Lib, KleeSlabs, LibEx, LibrarianLib, LibrarianLib Stage 2, Lost Souls, LunatriusCore, MTLib, MagicBees, MalisisCore, MalisisDoors, Mantle, McJtyLib, Mekanism, MekanismGenerators, MekanismTools, MineColonies, Minecraft Multipart Plugin, Mob Totems, Mod Tweaker, ModPack Basic Tools, ModPack Utilities, Morph-o-Tool, Morpheus, MrTJPCore, Mystical Agradditions, Mystical Agradditions Compat, Mystical Agriculture, Mystical Agriculture Tiered Crystals, Nature's Compass, NetherEx, No Mob Spawning on Trees, Not Enough Wands, NotEnoughIDs, NuclearCraft, Nutrition, OpenBlocks, OpenComputers, OpenComputers (Core), OpenModsLib, OpenModsLib Core, OreDictInit, OreExcavation, OreExcavation Integration, Overloaded, PackCrashInfo, PackMode, Pink Flamingo, Placebo, Plants, PlusTiC, PneumaticCraft: Repressurized, PortalGun, Portality, Pressure Pipes, Primitive Mobs, ProjectRed Core, ProjectRed Expansion, ProjectRed Exploration, ProjectRed Fabrication, ProjectRed Illumination, ProjectRed Relocation, ProjectRed Transmission, ProjectRed Transportation, ProjectRed integration, Psi, Quark, Quark Oddities, Quick Leaf Decay, RFTools, RFTools Control, RFTools Dimensions, RFTools Power / OC Integration, RFToolsPower, Random Things, RandomPatches, RandomTweaks, Ranged Pumps, Real Filing Cabinet, Reborn Core, RebornStorage, Redstone Arsenal, Redstone Flux, Refined Storage, Refined Storage Addons, Reliquary, Roguelike Dungeons, Roots 2, Rustic, Sampling Performance Profiler, Schematica, ShadowMC, Shadowfacts' Forgelin, Shield Parrying, Signals, Simply Jetpacks 2, Soul Shards Respawn, SpongeForge, Steve's Carts 2, Storage Drawers, Storage Drawers Extras, SwingThroughGrass, TATW, TOP Addons, Tech Reborn, Tesla Core Lib, Tesla Core Lib Registries, Thaumcrafft Inventory Scanning, Thaumcraft, Thaumic Computers, Thaumic Periphery, The Betweenlands, The Lost Cities, The One Probe, The Twilight Forest, The Weirding Gadget, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, TickProfiler, Tinker's JEI, Tinkers Construct OpenComputers Driver, Tinkers Tool Leveling, Tinkers' Construct, Transport, Traverse, UniDict, Universal Modifiers, Unloader, Valkyrie Lib, Vulpes library, WAIM, WanionLib, Water Strainer, Waystones, Wetstone, Wireless Crafting Terminal 2, WirelessCharger, Wizardry, Woot, World Utils, WorldEdit, Worley's Caves, WrapUp, XL Food Mod, XNet, Xtones, YNot, Zero CORE, actuallyaddon, asielib, careerbees, iChunUtil, p455w0rd's Library, projectred-compat

**Issue Description**
Upon eating Cyclic inventory crafting table, the 3x3 crafting table appears in your inventory. an "O" button also appears and upon clicking this the client crashes.

I was in the Nether testing this but happened in overworld too.
[2018-11-02-7.log.gz](https://github.com/SpongePowered/SpongeForge/files/2544425/2018-11-02-7.log.gz)

**Comment by phit** [comment]
actual log https://gist.github.com/phit/4dfec6dc565229c9635ddd9440a9f3c6

**Comment by krisjenner** [comment]
Async lighting is disabled and this crash still happens :( 7.1.5 RC3522

**Comment by phit** [comment]
new log please

**Comment by krisjenner** [comment]
[new log](https://gist.github.com/krisjenner/2fc1ffb2d60cbf3fab014e79cbaab815)

This time it doesn't fully crash my client, I just get booted from server with "A fatal error has occurred, this connection has been terminated"

**Comment by Faithcaio** [comment]
If this is a modified workbench with additional slots, we might be able to fix it in `MixinContainerWorkbench`
