### ISSUE TITLE
FTB SkyAdventures Crash (YUNoMakeGoodMap?)

### ISSUE THREAD

**Issue by Seshpenguin** [SpongePowered/SpongeForge#2500]
**I am currently running**

- SpongeForge version: 1.12.2-2768-7.1.5-RC3506
- Forge version: FTBserver-1.12.2-14.23.5.2770-universal
- Java version: openjdk version "1.8.0_181"
- Operating System: Debian 9.5 

- Plugins/Mods: FTB SkyAdventures 1.2.1

**Issue Description**
FTB SkyAdventures doesn't work with Sponge, according to the crash it appears to be because of the YUNoMakeGoodMap mod. The server crashes on startup.
Crash Report: https://gist.github.com/Seshpenguin/70006e966f92d60a25a7c8ac0ab0ba31

**Comment by phit** [comment]
Both SpongeForge and FoamFix add various optimizations that may not work with each other! Disable the following settings in the `config/foamfix.cfg`
`B:optimizedBlockPos=false` (Sponge adds a similar performance patch)
`B:patchChunkSerialization=false` <https://github.com/asiekierka/FoamFix/issues/166>
