### ISSUE TITLE
TheBetweelands crash and console spam

### ISSUE THREAD

**Issue by avescarelo** [SpongePowered/SpongeForge#2502]
**I am currently running**

    Minecraft: 1.12.2
    SpongeAPI: 7.1.0-4f54ce0d
    Sponge: 1.12.2-7.1.5-SNAPSHOT
    SpongeForge: 1.12.2-2768-7.1.5-RC3506
    Minecraft Forge: 14.23.5.2772

- Plugins:
ActionBroadcaster, GriefPrevention, LangSwitch, LuckPerms, NoSleep, Nucleus, ShabbyHolograms, SmoofyDungeon, Soulbound, Total Economy, UCFA, UltimateChat, VoxelSniper

- Mods:
Antique Atlas, AppleCore, AutoRegLib, Carry On, Cases, ContainerFix, CraftTweaker JEI Support, CraftTweaker2, Earthworks, Example Mod, Fast Leaf Decay, JurassiCraft, Just Enough Items, LLibrary, Ore Veins, Quark, Rough Mobs 2, Rustic, Spice of Life: Carrot Edition, SpongeForge, The Betweenlands, Wearable Backpacks

**Issue Description**
Problem 1] Very often when interacting with mobs to the console is sent very many errors. 
Problem 2] The server may crash when trying to process entities from thebetweelands mod

**Links:**
latest.log: [https://gist.github.com/pingvikin/f66313bd66a9cec8e29fe96bbe71a6f3](https://gist.github.com/pingvikin/f66313bd66a9cec8e29fe96bbe71a6f3)
crash report: [https://gist.github.com/pingvikin/9a05ef5e262dab6f17a2661cafadb5a4](https://gist.github.com/pingvikin/9a05ef5e262dab6f17a2661cafadb5a4)
original issue: [https://github.com/Angry-Pixel/The-Betweenlands/issues/769](https://github.com/Angry-Pixel/The-Betweenlands/issues/769)

**Comment by pingvikin** [comment]
up

**Comment by Zidane** [comment]
Can you retest this on the latest build of SF again?

**Comment by Zidane** [comment]
I had @Grinch do a play test of this mod and encountered zero issues with it. He attacked mobs, they killed him (easily..), he explored the world, etc.
