### ISSUE TITLE
Minecraft not showing advancements 

### ISSUE THREAD

**Issue by wesleytech** [SpongePowered/SpongeForge#2503]
**I am currently running**

Minecraft: 1.12.2 
SpongeAPI: 7.1-ff990df4 
Sponge: 1.12.2-7.1.1 
SpongeForge: 1.12.2-2768-7.1.1 
Minecraft Forge: 14.23.4.2707 

- Plugins

Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, AurionsVoteListener, CarrotShop, GriefPrevention, LuckPerms, MagiBridge, NuVotifier, Nucleus, Total Economy, WorldEdit.

Mods: (the sevtech mod pack)

Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, A Block of Charcoal, AbyssalCraft, AbyssalCraft Integration, Actually Additions, Actually Baubles, Advanced Generators, Advanced Mortars, Antique Atlas, AppleCore, AppleSkin, Applied Energistics 2, ArmoreableMobs, Aroma1997Core, AromaBackup, AromaBackuprecovery, Astikoor, Astral Sorcery, AutoRegLib, B.A.S.E, BC Builders, BC Factory, BC Robotics, BC Silicon, BC Transport, BD Lib, BNBGamingLib, Baubles, Bedrock-B-Gone, Better Builder's Wands, Better With Mods, Better with Addons, BiblioCraft, Blood Magic: Alchemical Wizardry, BnBGamingCore, Bonsai Trees, Bookshelf, BuildCraft, BuildCraft Lib, CD4017BE_lib, Caliper, Car Mod, Carry On, Ceramics, Chameleon, Chargers, Chisel, Chisels & Bits, Clumps, CodeChicken Lib, CommonCapabilities, Compact Machines 3, Construct's Armory, ContentTweaker, Cooking for Blockheads, CraftStudio API, CraftTweaker JEI Support, CraftTweaker2, Cucumber Library, Cyclic, Cyclops Core, Dark Utilities, Despawning Spawners, Dimension Stages, Dimensional Control, Dung Pipe, Elevator Mod, EmberRoot Zoo, Ender Utilities, EnderStorage, Environmental Tech, Example Mod, Extended Crafting, Extra Planets, Farming for Blockheads, Farseek, FastWorkbench, Ferdinand's Flowers, FindMe, FoamFix, FoamFixCore, Forge Microblocks, Forge Multipart CBE, Galacticraft Core, Galacticraft Planets, Game Stages, Geolosys, Gobble Core, Guide-API, Harvest, Horse Power, Hunting Dimension, Immersive Craft, Immersive Engineering, Immersive Petroleum, Immersive Tech, Improved Backpacks, InControl, Inductive Logistics, Industrial Foregoing, Info Accessories, Integrated Dynamics, IntegratedDynamics-Compat, Inventory Tweaks, Iron Backpacks, Iron Chest, Iron Jetpacks, Item Stages, IvToolkit, JourneyMap, Just A Raft Mod, Just Enough Items, Just a Few Fish, JustTheTips, KleeSlabs, Loot Table Tweaker, MJRLegendsLib, MTLib, Mantle, McJtyLib, Mekanism, Mercurius, Micdoodle8 Core, Minecraft Multipart Plugin, Mo' Bends, Mo' Villages, Mob Stages, Mod Tweaker, ModPack Basic Tools, ModPack Utilities, Modular Machinery, Modular Routers, Morpheus, Multiblockstages, Mundane Redstone, Mystical Agradditions, Mystical Agradditions Compat, Mystical Agriculture, Natura, Nature's Compass, NetherEx, No World Gen 5 You, Not Enough Items, Nutrition, Ocean Floor Classic, Ore Stages, OreExcavation, OreExcavation Integration, Overloaded, Pickle Tweaks, Placebo, Player Skin Mobs, PneumaticCraft: Repressurized, Power Adapters, Prestige, PrimalChests, PrimalCore, Progression Tweaks, Prospectors, QuantumStorage, Quark, Quick Leaf Decay, RFTools, RFTools Control, Ranged Pumps, Realistic Item Drops, Reborn Core, RebornStorage, RecipeStages, Recurrent Complex, Redstone Flux, Refined Storage, Refined Storage Addons, Road Runner, Rustic, Scannable, SevTweaks, Shadowfacts' Forgelin, Simple Generators, Simple Storage Network, SimpleAutoRun, Simply Arrows, Smooth Font Core, Spartan Shields, Spatial Server Mod, SpongeForge, Steve's Carts 2, Storage Drawers, Streams, Stuff A Sock In It, Super Sound Muffler, SwingThroughGrass, TallGates, Tesla Core Lib, Tesla Core Lib Registries, The Beneath, The Betweenlands, The Twilight Forest, The Weirding Gadget, Thirsty Bottles, Tinker Stages, Tinkers Tool Leveling, Tinkers' Complement, Tinkers' Construct, To the Bat Poles!, TogetherForever, Tomb Many Graves, Totemic, Translocators, Traverse, Triumph, Trumpet Skeleton, Tumbleweed, Universal Modifiers, Valkyrie Lib, ViesCraft, Villager Trade Tables, Waddles, Waila, Waila Stages, WanionLib, Water Control Extreme, Water Strainer, What Are We Looking At, Wild Crops, Wither Skeleton Tweaks, Wopper, XNet, YNot, Yoyos, animalium, death_compass, fat_cat, galacticrafttweaker, magma_monsters, mob_grinding_utils, primal_tech, sev_tweaks_npc, uppers

**Issue Description**
nobody (including OPs) dont have the ability to view their advancements. even when new people join they cant view their advancements.

 
latest.log: https://gist.github.com/wesleytech/24d5da27fde287eead8d1830032569b8

**Comment by XakepSDK** [comment]
Does it work without sponge?

**Comment by wesleytech** [comment]
yes, it does work without sponge
![2018-11-11_15 21 23](https://user-images.githubusercontent.com/44944379/48314138-835c9180-e5c5-11e8-9943-e9f129be83e8.png)

**Comment by wesleytech** [comment]
reinstalling sponge has managed to fix it for 1 player, but not for myself i still get this screen
![2018-11-11_15 43 11](https://user-images.githubusercontent.com/44944379/48314339-7f7e3e80-e5c8-11e8-9ae7-6d99342ddf44.png)

note: after restarting the server again, it seems like this issue went back to the old state (aka not working for anybody).

**Comment by wesleytech** [comment]
i tried to update the spongeforge to the newest (stable) version: 7.1.4, but the bug still persists. the log is as follows: https://gist.github.com/wesleytech/d3cfd2f454c9bdaeff9b78b43e464f5a

**Comment by wesleytech** [comment]
after a week i still havent figured out a solution or what could be the issue here. anybody have an idea?

**Comment by Shybella** [comment]
This is probably related with https://github.com/SpongePowered/SpongeForge/issues/2380

Also having issues with advancements not showing for certain mods.

**Comment by wesleytech** [comment]
it might maybe be related. but personally i dont think so. since with this issue it doesnt show it for any of the mods (or "ages" as its called ingame). it just gives the "There doesn't seem to be anything here..." message. and as far as i know, it does in fact trigger the advancement (according to a few players). it just doesnt show it.

**Comment by wesleytech** [comment]
just a question, does anybody have an update on this? since i have been waiting for 23 days and haven't gotten a response (like a bug fix or something). i don't know if i need to add anything else here, but hopefully the developers of sponge can fix this annoying bug.

**Comment by phit** [comment]
would be nice if you could isolate the mods needed for this to start happening, if you have some time!
 otherwise ill get to this over the next few days and see if I can reproduce it somehow as part of my [new years issue cleanup](https://github.com/SpongePowered/SpongeForge/projects/6)

**Comment by ghost** [comment]
This sounds like a mod incompatibility. 

As phit pretty much mentioned, try trial-and-error until you find out what mod is causing this issue.

**Comment by wesleytech** [comment]
Hello Phit, sorry for my late reaction. but as of today i do not have the required time to isolate an issue, but i can get you the files which we are using for our server (link to the download: https://drive.google.com/file/d/1jpkAQEgYm09IyF1zVA1TSfAuZbY5viv-/view?usp=sharing). i hope you can finally find the issue and inform us about it.

Sincerely,
Wesleytech

**Comment by dusmartijngames** [comment]
uh well, still no answer pith? we hope to get one ASAP as you'd probably understand.

Sincerely,
dusmartijngames

**Comment by Yorkforce** [comment]
Any update to this? 
Were running into the same problem on the sky factory 4 modpack

**Comment by ghost** [comment]
@Yorkforce I'm pretty sure it was fixed regarding SpongeCommon.

Try updating to latest version of SpongeForge.

**Comment by Yorkforce** [comment]
@0xEviqnn 
Were running spongeforge-1.12.2-2768-7.1.6-RC3652.jar

Its one of the latest versions isnt it?
Edit: Ha, already on 3666, dang you guys update fast!
I'll try newest version, thanks 0xEviqnn!

**Comment by Yorkforce** [comment]
Just to report after updating to 3666, advancements broke again.

**Comment by ghost** [comment]
@Yorkforce 
You'll have to wait for @phit to fix this issue.

Also; what mod is it actually breaking these? Did you find out?

**Comment by Yorkforce** [comment]
@0xEviqnn Absolutely no idea, advancementbook mod and betteradvancements are probably the 2 main contenders

**Comment by ParkerMc** [comment]
As the author of the advancement book mod, it is not the issue. The advancement book mod only adds two items to open the advancement menu the same exact way that the button in the pause menu does. It is probably Better Advancements, Together Forever, or Triumph.

**Comment by Yorkforce** [comment]
Just to confirm we have together forever disabled server side, if that causes a client issue i'm not sure but I would be surprised if every server with this issue has that disabled.

**Comment by julianubico** [comment]
Seems like [Better Advancements](https://minecraft.curseforge.com/projects/better-advancements) is a client-side only mod.


![Image](https://i.gyazo.com/1e731a55b14442dcd95be773d83cdf7d.png)

**Comment by julianubico** [comment]
I've noticed that they work when connecting after a server restart. Once the player disconnects and reconnects after that, then this shows up again. ![Image](https://user-images.githubusercontent.com/44944379/48314339-7f7e3e80-e5c8-11e8-9ae7-6d99342ddf44.png)

**Comment by Yorkforce** [comment]
We have also noticed this oddity in the advancements files:

![Advfilesave](https://user-images.githubusercontent.com/1526195/56856533-b49f0300-6954-11e9-96a0-1e18209a334c.png)

Notice the last 5 entries are modified at the same time

**Comment by TristanHva** [comment]
I get 10s of people complaining about this issue on the daily probably 100s weekly... and thats only my small little server..:( . This is a huge bug that is impacting the gameplay for many many people. Its already been longer than a week...

**Comment by Duedeguy** [comment]
t

**Comment by Duedeguy** [comment]
I get 10s of people complaining about advancements not working probably 100s weekly.... and thats only my small little server... this has to be fixed quickly it's impacting a lot of people in their core experience of modded minecraft. its already been longer than a week :(

**Comment by Aaron1011** [comment]
@Duedeguy: Can you please provide a list of all mods that you're running?

**Comment by Duedeguy** [comment]
> @Duedeguy: Can you please provide a list of all mods that you're running?

I'm running the SkyFactory 4 modpack, it's the first time so many people have joined my server! but now they are leaving :( please help

here is the modpack list: https://minecraft.curseforge.com/projects/skyfactory-4/files/2703270#additional-files

**Comment by Aaron1011** [comment]
Here's the intersection between @wesleytech's mod list and @Duedeguy's mode list:

```{'Extended Crafting', 'Mystical Agradditions', 'Waila Stages', 'FindMe', 'XNet', 'Prestige', 'Chisels & Bits', 'McJtyLib', 'FastWorkbench', 'Cooking for Blockheads', 'BiblioCraft', 'Stuff A Sock In It', 'BNBGamingLib', 'KleeSlabs', 'Aroma1997Core', 'AppleCore', 'JourneyMap', 'Farming for Blockheads', 'Caliper', 'The Twilight Forest', 'Pickle Tweaks', 'Applied Energistics 2', 'Waddles', 'Game Stages', 'Hunting Dimension', 'Bookshelf', 'Dark Utilities', 'Item Stages', 'SwingThroughGrass', 'Iron Jetpacks', 'TallGates', 'ContentTweaker', 'Mercurius', 'Industrial Foregoing', 'BnBGamingCore', "Construct's Armory", 'The Weirding Gadget', 'Horse Power', 'Ender Utilities', 'Rustic', 'Cucumber Library', "Tinkers' Complement", 'Ceramics', 'Redstone Flux', 'Carry On', 'Dimension Stages', 'Simple Generators', 'Tesla Core Lib', 'AppleSkin', 'Super Sound Muffler', 'Mekanism', 'AromaBackup', 'Chisel', 'Guide-API', 'Mantle', 'Mob Stages', 'Chargers', 'Yoyos', 'Integrated Dynamics', 'YNot', 'Ranged Pumps', 'Baubles', 'MTLib', 'Simple Storage Network', 'Clumps', "Shadowfacts' Forgelin", 'Triumph', 'Mystical Agriculture', 'Placebo', 'Bonsai Trees', 'Morpheus', 'Astral Sorcery', 'B.A.S.E', 'Cyclops Core', 'Cyclic'}```

**Comment by julianubico** [comment]
I have AromaBackup, CarryOn, and Morpheus disabled on my **Sky Factory 4** server, so those can be ruled out.

**Comment by Yorkforce** [comment]
We have astral sorcery disabled

**Comment by Aaron1011** [comment]
This is caused by one of Sponge's advancement-related mixins. I'm currently trying to narrow things down.

**Comment by Yorkforce** [comment]
Looking good so far, advancements have been working great since last night. Big thank you from us Aaron!
