### ISSUE TITLE
Conflict With Tropicraft and OpenTerrainGen Crashes Server

### ISSUE THREAD

**Issue by korlandril** [SpongePowered/SpongeForge#2505]
**I am currently running**

- SpongeForge version: 1.12.2-2768-7.1.4
- Forge version: 2768
- Java version: 1.8.0_191-b12
- Operating System: Windows 10 Pro

- Mods:   
RPG-HUD
Dynamic Sword Skills
Sword Skills Api
AbyssalCraft
Antique Atlas
AutoRegLib
Battle Towers
Baubles
BetterFPS
Biome Bundle
Blood Magic
Bloodmoon
Botania
ChopDown Updated
Clumps
CodeChickenLib
coroutil
ConnectedTexturesMod
Davinci's Vessels
Deadly Monsters
Decocraft
DefaultOptions
Dynamic Lights
Dynamic Surroundings
Dynamic Trees
Dynamic Trees Thaumcraft Compat
Embers
EnderStorage
Erebus
ExtraUtils
Extreme Reactors
Fast Workbench
Flan's Mod
FoamFix
g-regen
Guide-API
HWYLA
Ice and Fire
InventoryTweaks
IvToolkit
Just Enough Items
llibrary
Lucraft Core
Lycanites Mobs Complete
Mantle
Matter Overdrive
mctjtylib
MeeCreeps
Mekanism
Mekanism Generators
Mekanism Tools
Millenaire
Minecolonies
Morpheus
Moving World
Mowzie's Mobs
MultiBags
Not Enough Items
omlib
OpenModularTurrets
Open Terrain Generator
PTRLib
Quark
Recurrent Complex
Roguelike Dungeons
Roots 2
SkyLanterns
Tinker's Construct
Thaumcraft 6
Thaumic Inventory Scanning
Thaumic JEI
Thaumic Periphery
The Betweenlands
Tropicraft
Twilight Forest
ViesCraft
WAWLA
Weather 2
WorldEdit
ZarakLib
ZeroCore
ZombieAwareness

- Plugins:
CatClearLag
Chest Refill
CraftBook
LuckPerms
Nucleus
Pieconomy
ProjectCore
ProjectWorlds
Universe Guard 2
Web-API
spark

**Issue Description**
Client crashes the server upon entering the Tropicraft dimension. Attempt to restart and reconnect the client yields the same outcome. This has been brought to the attention of both mods in question and I have been referred here via OpenTerrainGenerator's Discord since removing SpongeForge completely removes the problem:   
https://github.com/PG85/OpenTerrainGenerator/issues/212   
https://github.com/Tropicraft/Tropicraft/issues/301   

I've included the full log here:   
https://gist.github.com/korlandril/6c558db3c1815910ea32ed84c06b5e8a

**Comment by phit** [comment]
https://github.com/PG85/OpenTerrainGenerator/issues/212#issuecomment-500244039
