### ISSUE TITLE
Certain players cant join server.

### ISSUE THREAD

**Issue by SlayerTheChikken** [SpongePowered/SpongeForge#2508]
**I am currently running**
- SpongeForge version: 2768-7.1.5-RC3506
- Forge version: 1.12.2-14.23.5.2768
- Plugins/Mods: https://docs.google.com/spreadsheets/d/e/2PACX-1vTkZG-t1afcKNyPPTd79sOlgnGVQOXTaO1UWjjIIoDbKO0bV9cuLQ1wmEhuDokIxWMJPJbpd8msj6y4/pubhtml

**Issue Description**
Certain players cant join, they are instantly kicked off. Certain players have no issues at all.
The TPS is a constant 20, the only clue we have is some log spam: io.netty.channel.unix.Errors$NativeIoException: syscall:writev(..) failed: Broken pipe
	at io.netty.channel.unix.FileDescriptor.writeAddresses(..)(Unknown Source) ~[FileDescriptor.class:?]

**Debugging log**
Log: https://gist.github.com/Slayer5934/82ef6b56994505291f656ca0c3c5eee0

**Comment by phit** [comment]
network issue unrelated to sponge, I heard mixed reports updating netty may help https://gist.github.com/phit/be5b69b76217bb8bab7b1cd752d4c39e

**Comment by SlayerTheChikken** [comment]
I updated netty and unfortunately the error only changed slightly, half the user base is still unable to connect and the lucky ones have 0 issue at all playing at 20 tps... Any further help I would be very greatful for, I cant see anything in the logs except those select spam of errors..

NetworkDispatcher exception java.io.IOException: Broken pipe
and
NetworkDispatcher exception io.netty.handler.timeout.ReadTimeoutException: null

**Comment by ZeotYT** [comment]
@Slayer5934 after all this time, did you ever resolve this issue or figure out what was causing it? I am now getting this same behavior/error on my spongeforge 1.12.2 pixelmon server. Let me know if you have any information at all! Thanks

(I have also updated to about 10 different versions of netty, including latest, and none of them fix it)

**Comment by MIGrove** [comment]
@Slayer5934 @ZeotYT receiving the same same issue on an E2:E server currently. Have already tried updating netty, to no avail.

Did anyone perhaps get anywhere with this issue?
