### ISSUE TITLE
Advanced Rocketry space dimension is saved in wrong location

### ISSUE THREAD

**Issue by takarabako** [SpongePowered/SpongeForge#2509]
**I am currently running**
- SpongeForge version:  1.12.2-2768-7.1.4 Recommended Build
- Forge version: 1.12.2-14.23.4.2759
- Java version: jre1.8.0_181
- Operating System: Windows Server 2012 R2

- Plugins/Mods:
FTB Continuum 1.5.2 mod pack(too many mods to list)
Nucleus
LuckPerms

**Issue Description**
When using native Forge the space dimension is saved in world/advRocketry/DIM2 but on Sponge it is in world/DIM2. This causes player launching from earth to space station ends up in a Fake space dimension where you can not build or break any blocks. Creating a Symbolic Link from the wrong folder to the correct one AND set load-on-startup=false somewhat fixed the problem, but you cannot let anything than the rocket itself to load the dimension otherwise you still end up in the fake one.

Version of Advanced Rocketry is 1.12.2-1.4.1-113
No server crash.

**Comment by takarabako** [comment]
After some further testing the "Fake space" part may not be related. But the saved in wrong location part is still valid.

**Comment by phit** [comment]
world still saved in the root world folder, was unable to reproduce any of the other issues you mentioned though. leaving the dimension using nucleus teleport commands and going back worked fine just like leaving/entering with a rocket.

jei_1.12.2-4.13.1.225.jar
LibVulpes-1.12.2-0.3.0-45-universal.jar
AdvancedRocketry-1.12.2-1.4.1-119-universal.jar
spongeforge-1.12.2-2768-7.1.5-RC3513.jar
griefprevention-1.12.2-4.3.0.662.jar
LuckPerms-Sponge-4.3.62.jar
Nucleus-1.8.0-S7.1-MC1.12.2-plugin.jar

**Comment by Zidane** [comment]
Tested and the data is in the right spot.
