### ISSUE TITLE
Experiencing Crash with Modpack

### ISSUE THREAD

**Issue by Enderminer** [SpongePowered/SpongeForge#2511]
Running 1.12.2
- SpongeForge version: RC3506 
- Forge version: 2768
- Java version: 8 Update: 181
- Operating System: Windows 10 Home

- Mods: (List from Crash Report):
 minecraft                         
 mcp                               
 FML                               
 forge                             
 spongeapi                         
 sponge                            
 spongeforge                       
 openmodscore                      
 foamfixcore                       
 baubles                           
 chisel                            
 endercore                         
 codechickenlib                    
 redstoneflux                      
 cofhcore                          
 cofhworld                         
 thermalfoundation                 
 thermalexpansion                  
 enderio                           
 enderiointegrationtic             
 mantle                            
 tconstruct                        
 extrautils2                       
 flyringbaublemod                  
 applecore                         
 appleskin                         
 appliedenergistics2               
 quark                             
 autoreglib                        
 badwithernocookiereloaded         
 bibliocraft                       
 biomesoplenty                     
 conarm                            
 cucumber                          
 enderiobase                       
 enderioconduits                   
 enderioconduitsappliedenergistics 
 enderioconduitsopencomputers      
 enderioconduitsrefinedstorage     
 enderiointegrationforestry        
 enderiointegrationticlate         
 ftblib                            
 enderiomachines                   
 enderiopowertools                 
 enderstorage                      
 zerocore                          
 bigreactors                       
 foamfix                           
 ftbutilities                      
 waila                             
 ironchest                         
 mekanism                          
 mekanismgenerators                
 mekanismtools                     
 mob_grinding_utils                
 mysticalagriculture               
 mysticalagradditions              
 openmods                          
 openblocks                        
 randomthings                      
 thermaldynamics                   
 tinkertoolleveling                
 waystones                         

No Plugins

**Issue Description**
I have a Forge Server that whenever I boot with spongeforge I get an error.
I run my run.bat file and let it run until I get an error.

Log File and Crash Report:
https://gist.github.com/Enderminer/f5511fcecb07ff84ad93bcd750e067a7

**Comment by phit** [comment]
Both SpongeForge and FoamFix add various optimizations that may not work with each other! Disable the following settings in the `config/foamfix.cfg`
`B:optimizedBlockPos=false` (Sponge adds a similar performance patch)
`B:patchChunkSerialization=false` <https://github.com/asiekierka/FoamFix/issues/166>
