### ISSUE TITLE
PlayerEvent.EnteringChunk throwing UnexpectedBlockChange

### ISSUE THREAD

**Issue by STRL1T** [SpongePowered/SpongeForge#2515]
spongeforge-1.12.2-2768-7.1.4
1.12.2-forge1.12.2-14.23.5.2772
Java 8

Plugins (11): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge,  FastAsyncWorldEdit, GriefPrevention, LuckPerms, Nucleus, Tab Modifier, UltimateChat, WorldEdit

Mods (58): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, A Block of Charcoal, AutoRegLib, Bedrock-B-Gone, Better With Mods, Bloodmoon, Carry On, Chest Transporter, Clay Bucket, Clumps, CoroUtil Library, CraftTweaker JEI Support, CraftTweaker2, Craftable Gunpowder, Crop-Eating Animals, Dynamic Surroundings, DynamicSurroundingsCore, Elevator Mod, Extended Mod Config, Extended Renderer, Farseek, Food Funk, Forestry, Geolosys, Hardcore Darkness, Immersive Engineering, Immersive Petroleum, Inventory Save, Just Enough Items, KleeSlabs, Localized Weather & Storms, MineTweakerRecipeMaker, Morpheus, Openable Windows, PassableLeaves, PassableLeavesCore, Quark, Rex's Additional Structures, Rotten Flesh To Leather, Serene Seasons, Snow Accumulation, SpongeForge, Stacksize Mod, Storyoflife, SwingThroughGrass, Tough As Nails, U Team Core, Useful Backpacks, Wild Crops, Worley's Caves, Wumple Util Library, iChunUtil, kinetic anti-cheat

--

I do not know the reasons for such a number of errors, but I'm afraid that the server will not get any better from this.

[log.zip](https://github.com/SpongePowered/SpongeForge/files/2592942/log.zip)

**Comment by phit** [comment]
https://gist.github.com/phit/6fa969a72133f15a7272ad2a93ec70e5

https://github.com/oitsjustjose/Geolosys/blob/master/src/main/java/com/oitsjustjose/geolosys/compat/OreConverter.java#L57

**Comment by STRL1T** [comment]
> https://github.com/oitsjustjose/Geolosys/blob/master/src/main/java/com/oitsjustjose/geolosys/compat/OreConverter.java#L57

What should i do with this? Pls :c

**Comment by phit** [comment]
sorry, nothing for you just left a reference to the code that's causing this for devs

**Comment by phit** [comment]
should be solved in 7.1.5-3534 or newer, if not leave a message and I'll reopen
