### ISSUE TITLE
SpongeData not being removed by mods

### ISSUE THREAD

**Issue by Sir-Will** [SpongePowered/SpongeForge#2516]
The ProjectE mod uses `ItemStack#setTagCompound()` to remove the nbt data from items to prevent duping but this doesn't remove the SpongeData.
Shouldn't the SpongeData get removed too?

https://github.com/sinkillerj/ProjectE/blob/47e331c5241f3b1b288b14279f24d12e66b57b2c/src/main/java/moze_intel/projecte/gameObjs/tiles/CondenserTile.java#L183
https://github.com/sinkillerj/ProjectE/blob/9d980b37ef6b585390cd32967cc9e5f3d7445321/src/main/java/moze_intel/projecte/gameObjs/container/inventory/TransmutationInventory.java#L74

spongeforge-1.12.2-2768-7.1.5-RC3506

**Comment by simon816** [comment]
Just taking a quick look. The NBT data will be removed when the `setTagCompound(new NBTTagCompound());` is made. But any data manipulators will remain, so the next serialisation will add SpongeData. Relevant file is [MixinItemStack](https://github.com/SpongePowered/SpongeCommon/blob/stable-7/src/main/java/org/spongepowered/common/mixin/core/item/MixinItemStack.java)

**Comment by Zidane** [comment]
Not understand the issue here. When the stack is told to save, manipiulators will be written. Manipulators aren't a 1:1 layer over NBT; for performance reasons, they are in memory and written when save is called.

**Comment by Sir-Will** [comment]
@Zidane how should we prevent the duping of SpongeData here then?

**Comment by Faithcaio** [comment]
Shouldn't we just clear the cached manipulators when setting nbt directly?

**Comment by Sir-Will** [comment]
Still no chance this can be looked into?
