### ISSUE TITLE
Optimization sponge 1.12.2

### ISSUE THREAD

**Issue by kasdo** [SpongePowered/SpongeForge#2517]
Hey
Advise how you can optimize my server? And then when online 30+ the situation is not very good

Mods:
> Mods (22): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AI Improvements, Chisel, Classic Combat, CustomNPCs, DrZhark's CustomSpawner, DrZhark's Mo'Creatures Mod, FoamFix, FoamFixCore, Iron Chest, LagGoggles, Sampling Performance Profiler, SpongeForge, Tree Chopper, Varied Commodities, Various Oddities, Zeron Items

Plugins:
> Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, Eagle Factions, GriefPrevention, Holograms, LuckPerms, Nucleus, PlaceholderAPI, ProjectCore, ProjectPortals, ProjectWorlds, TabManager, WorldEdit, ZeronRPG, spark

CPU:
![image](https://user-images.githubusercontent.com/7419546/48731353-8569c480-ec45-11e8-8038-97c24891c121.png)

/gc from nucleus:
![image](https://user-images.githubusercontent.com/7419546/48731534-f01b0000-ec45-11e8-8929-72627157704a.png)

LagGoggles:
![image](https://user-images.githubusercontent.com/7419546/48731867-b991b500-ec46-11e8-9a66-62ecf6385eb3.png)

https://sparkprofiler.github.io/?KX1XjxMPsK

https://timings.aikar.co/?id=c58b3f0e85624aa4be8b5ef7b27b48eb

`

**Comment by Shybella** [comment]
Your performance looks fine, same goes with reports. 

Are these reports generated when 30+ people are online?

**Comment by kasdo** [comment]
> Your performance looks fine, same goes with reports.
> 
> Are these reports generated when 30+ people are online?

Nope. But now there are sometimes server freezes and blocks are not broken the first time.

**Comment by Shybella** [comment]
Generate the reports when you have a heavy load and post them back here. 

How many players were on the server at the current time of those reports being generated?

**Comment by kasdo** [comment]
> Generate the reports when you have a heavy load and post them back here.
> 
> How many players were on the server at the current time of those reports being generated?

16 players.

Right now online is 0. But I have lags. 10 hours after start server. How its possible?

> Can't keep up! Did the system time change, or is the server overloaded? Running 7443ms behind, skipping 148 tick(s)

Log:
https://hastebin.com/upalonutuq.md

https://timings.aikar.co/?id=348ba88af9bd48fab1c1663182239e25
https://sparkprofiler.github.io/?snIBJvWxtF

**Comment by Shybella** [comment]
Based on that and your first reports.

CustomNPC's was taking up 14% thread time, that's your biggest offender.
![download](https://user-images.githubusercontent.com/4436776/48744587-5dc52d00-ec42-11e8-9d40-70bd7fd4ed09.png)

**Comment by kasdo** [comment]
> Based on that and your first reports.
> 
> CustomNPC's was taking up 14% thread time, that's your biggest offender.

it is not strange. NPC very much and that's fine. But do not you think that these 14% can not cause such problems?

Tomorrow I'll take off the timings when there are players. I can also write to the creator of the mod, what should I say?

**Comment by Shybella** [comment]
The profile at 14% for CustomNPCS was when 16 players are online and you had about 47-48% thread sleeping at that time. You had 95% thread sleeping with 0 online. If you had 30 people on, you double that 52-53% thread time for the current 16 players then add on the additional overhead 5-6% from base idle, you reach close to 100% thread load ( over, actually ) which would result in the problems you are having.

You need to start trimming the fat by cutting down whatever CustomNPC's is doing, that saves 14% ( if completely removed/fixed ) that's an additional 5-8 players before you beginning reaching your max performance per core on that processor again.

Your other choice is getting a faster single-core processor and maybe follow some other guides floating around the community on improving performance server side.

**Comment by kasdo** [comment]
> The profile at 14% for CustomNPCS was when 16 players are online and you had about 47-48% thread sleeping at that time. You had 95% thread sleeping with 0 online. If you had 30 people on, you double that 41-42% thread time for the current 16 players then add on the additional overhead 5-6% from base idle, you reach close to 100% thread load which would result in the problems you are having.
> 
> You need to start trimming the meat by cutting down whatever CustomNPC's is doing, that saves 14% ( if completely removed/fixed ) that's an additional 5-8 players before you beginning reaching your max performance per core on that processor again.
> 
> Your other choice is getting a faster single-core processor and maybe follow some other guides floating around the community on improving performance server side.

How can I find out which NPCs or in which chunks the server is most loaded? LagGoggles didnt help

**Comment by Shybella** [comment]
You should contact the mod author for CustomNPCs and send him your profile reports, you'll get better advice there.

CustomNPC's discord: https://discordapp.com/invite/0qZ6X3cHl8Pupttr

**Comment by kasdo** [comment]
The creator of the mod said that it can not help. Maybe there will be some tips on how to deal with this? In addition to removing the NPC

**Comment by phit** [comment]
https://docs.spongepowered.org/stable/en/server/management/performance-tweaks.html

**Comment by kasdo** [comment]
> https://docs.spongepowered.org/stable/en/server/management/performance-tweaks.html

did everything he could already. Any more tips?

**Comment by kasdo** [comment]
If u want to see this

https://sparkprofiler.github.io/?CVbwDbr2EJ
https://timings.aikar.co/?id=b488a484e5144085be4e68dd6766c4ee#regions

![image](https://user-images.githubusercontent.com/7419546/48835745-9885ad00-ed89-11e8-91bd-174e29ef8920.png)
