### ISSUE TITLE
Help reading logs about chunkload stacktraces

### ISSUE THREAD

**Issue by jinkhya** [SpongePowered/SpongeForge#2518]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2768-7.1.4.jar
- Forge version: 2768
- Java version: 1.8.0_121-b13
- Operating System: Centos 7.3.1611

- Plugins/Mods:
Enigmatica 2 Expert 
Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, BetterChunkLoader, CatClearLag, Enjin Minecraft Plugin, GriefPrevention, LuckPerms, MMCRestrict, Nucleus, Prism

**Issue Description**
I'm having an issue with something chunkloading players bases. Phit told me in discord to turn on sponge chunk load logging and stacktrace, wich I did.
However I need help reading those as I'm not too experienced in understanding them.
I see a lot of mods under "load chunk at ..." sections, like enderio conduits, forestry, integrated dynamics,etc. Are those actually in cause to chunk load even when players are offline? 

couldn't use gist or pastebin, file is too large.
https://wetransfer.com/downloads/796c4a6e99febde3232b7d7989cef95220181121113920/00660a3ba2db58fef38a7109c439e5f020181121113920/ff509f

**Comment by phit** [comment]
yes, more accurately in most cases they will stop the chunk from unloading

anyway please don't use the github issue tracker for support, you can use the forums or chats we have for that
