### ISSUE TITLE
ExtraUtils2 compressed blocks console spam

### ISSUE THREAD

**Issue by CreepyCre** [SpongePowered/SpongeForge#2519]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2768-7.1.4
- Forge version: forge-1.12.2-14.23.5.2768
- Java version: 1.8.0_181
- Operating System: Linux

- Plugins/Mods:
Plugins (23): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, AdamantineShield, AurionsVoteListener, Buycraft, CatClearLag, Chest Refill, DailyRewards, GriefPrevention, Holograms, HuskyCrates, HuskyUI, LuckPerms, MMCReboot, MMCRestrict, MMCTickets, MagiBridge, NuVotifier, Nucleus, RankUpper, WorldEdit
Mods (225): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, /dank/null, AE2 Stuff, Actually Additions, Actually Baubles, AngelRing 2 Bauble, AppleSkin, Applied Energistics 2, Attribute Fix, AutoRegLib, Avaritia, B.A.S.E, BC Builders, BC Energy, BC Factory, BC Robotics, BC Silicon, BC Transport, BD Lib, Bad Wither No Cookie! Reloaded, Baubles, Better Builder's Wands, Better Questing, Better Questing Triggerer, Bonsai Trees, Bookshelf, Botania, Brandon's Core, BuildCraft, BuildCraft Lib, Building Gadgets, CXLibrary, Ceramics, Chameleon, Chance Cubes, Chest Transporter, Chickens, Chisel, Chisels & Bits, Clumps, CoFH Core, CoFH World, CodeChicken Lib, Colossal Chests, Comforts, CommonCapabilities, Compact Machines 3, Compact Solar Arrays, Compacter, ComputerCraft, Cooking for Blockheads, CraftTweaker JEI Support, CraftTweaker2, Crafting Tweaks, Cucumber Library, Cyclic, Cyclops Core, Dark Utilities, Draconic Evolution, Ducky Mod, ET Lunar, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, EnderStorage, Enderman Evolution, EnergeticSheep, Environmental Tech, EvilCraft, EvilCraft-Compat, Ex Compressum, Ex Nihilo Creatio, Exchangers, Extra Cells 2, Extra Utilities 2, Extreme Reactors, FTB Utilities, FTBLib, Farming for Blockheads, Fast Leaf Decay, Flat Colored Blocks, Flux Networks, FoamFix, FoamFixCore, Forestry, Forge Microblocks, Forge Multipart CBE, Guide-API, Harvest, Hatchery, Hats, Immersive Engineering, InGame Info XML, Industrial Foregoing, Industrial Meat, IndustrialCraft 2, Integrated Dynamics, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTunnels-Compat, Integration Foregoing, Iron Backpacks, Iron Chest, JEI Bees, JMFixer, JourneyMap, Just Enough Items, JustEnoughIDs, KleeSlabs, LLibrary, Long Fall Boots, Loot Bags, LunatriusCore, MCMultiPart, MTLib, Mantle, McJtyLib, Mekanism, MekanismGenerators, MekanismTools, Mercurius, Minecraft Multipart Plugin, Missing Pieces, Mod Tweaker, Modpack Config Checker, More Chickens, More Furnaces, More Shearables, Morph-o-Tool, Morpheus, Mystical Agradditions, Mystical Agriculture, Natura, NetherPortalFix, Nice, Not Enough Wands, OpenBlocks, OpenModsLib, OpenModsLib Core, OreExcavation, OreSpawn, Oreberries, Pam's HarvestCraft, Pam's Simple Recipes, Placebo, PlusTiC, ProjectE, Psi, QuantumStorage, RF Lux, RFTools, RFTools Control, RFTools Dimensions, Random Things, RandomPatches, RandomTweaks, Realistic Item Drops, Reborn Core, RebornStorage, Redstone Arsenal, Redstone Flux, Refined Storage, Refined Storage Addons, Roost, Shadowfacts' Forgelin, Shear Madness, Simple Corn, Simple Inventory sorting, Simply Jetpacks 2, SlimyBoyos, Snad, Solar Flux Reborn, SonarCore, SpongeForge, Standard Expansion, Steve's Carts 2, StoneBlockUtilities, Storage Drawers, TESLA, Tesla Core Lib, Tesla Core Lib Registries, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, TickProfiler, Tinkers Tool Leveling, Tinkers' Construct, Tiny Progressions, TorchMaster, Translocators, Twerk-Sim 2K16, UniDict, Universal Modifiers, Valkyrie Lib, Void Island Control, Waila, WanionLib, What Are We Looking At, Whoosh, Wireless Crafting Terminal 2, Wither Skeleton Tweaks, Woot, World Primer, XNet, Xtones, Zero CORE, iChunUtil, mob_grinding_utils, p455w0rd's Library

**Issue Description**

The issue occurs on a Stoneblock server we are running.
We noticed getting spammed about unexpected block changes in console. I was able to recreate the issue by trying to mine any of the compressed blocks from Extra Utilities 2. The blocks dont have to be broken, just punching them is enough.

https://gist.github.com/CreepyCre/8cec8869cc114bc2718affc7591f6cb6

**Comment by phit** [comment]
this was already fixed before, looks like its back https://github.com/SpongePowered/SpongeForge/issues/1997

**Comment by phit** [comment]
solved in 7.1.5-3534 or newer
