### ISSUE TITLE
 Server failed due to mod power and world generation

### ISSUE THREAD

**Issue by STRL1T** [SpongePowered/SpongeForge#2523]
spongeforge-1.12.2-2768-7.1.4
1.12.2-forge1.12.2-14.23.5.2772
Java 8

Plugins (11): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, FastAsyncWorldEdit, GriefPrevention, LuckPerms, Nucleus, Tab Modifier, UltimateChat, WorldEdit

The server crashes due to the mod FoodFank. What could be the reason?
Also, the error is due to Geolosys, how can you give Sponge confidence of Geolosys (sry for my Eng.)

https://github.com/Stormwind99/FoodFunk/blob/master/src/main/java/com/wumple/foodfunk/rottables/RotTickingTileEntity.java#L48

**Comment by STRL1T** [comment]
> spongeforge-1.12.2-2768-7.1.4
> 1.12.2-forge1.12.2-14.23.5.2772
> Java 8
> 
> Plugins (11): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, FastAsyncWorldEdit, GriefPrevention, LuckPerms, Nucleus, Tab Modifier, UltimateChat, WorldEdit
> 
> The server crashes due to the mod FoodFank. What could be the reason?
> Also, the error is due to Geolosys, how can you give Sponge confidence of Geolosys (sry for my Eng.)
> 
> https://github.com/Stormwind99/FoodFunk/blob/master/src/main/java/com/wumple/foodfunk/rottables/RotTickingTileEntity.java#L48

https://gist.github.com/STRL1T/66005afae0120a873d8ac099235304ff

**Comment by phit** [comment]
please report this to the mod author https://github.com/Stormwind99/FoodFunk/issues/46
