### ISSUE TITLE
Reload doesn't reload logging settings

### ISSUE THREAD

**Issue by Sir-Will** [SpongePowered/SpongeForge#2524]
Using /sponge reload -g did always reload the logging options like `chunk-load` but this is no longer the case. I'm not sure if this is intended and if other options are affected too.

It was always helpful to enable/disable logging without restarting the server.

spongeforge-1.12.2-2768-7.1.5-RC3506

**Comment by ImMorpheus** [comment]
`/sponge reload` is broken.

Duplicate of https://github.com/SpongePowered/SpongeCommon/issues/2036
