### ISSUE TITLE
voidislandcontrol unexpected block change

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#2526]
**I am currently running**
- SpongeForge version: 1.12.2-2768-7.1.4
- Forge version: 14.23.5.2768
- Java version: 1.8.0_191
- Operating System: CentOS Linux release 7.5.1804 (Core)

StoneBlock Modpack v1.0.31
- Plugins/Mods:
      Plugins: Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge,  FastAsyncWorldEdit, AurionsVoteListener, AutoBroadcaster, BetterChunkLoader, CarrotShop, CatClearLag, CommandSigns Reloaded, CommandUtils, EconomyLite, LuckPerms, MMCRestrict, MagiBridge, NuVotifier, Nucleus, Prism, RankUpper, WorldEdit

      Mods (227): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, /dank/null, AE2 Stuff, Actually Additions, Actually Baubles, AngelRing 2 Bauble, AppleSkin, Applied Energistics 2, Aroma1997's Dimensional World, Aroma1997Core, Attribute Fix, AutoRegLib, Avaritia, B.A.S.E, BC Builders, BC Energy, BC Factory, BC Robotics, BC Silicon, BC Transport, BD Lib, Bad Wither No Cookie! Reloaded, Baubles, Better Builder's Wands, Better Questing, Better Questing Triggerer, BetterChunkLoader Forge Lib, Bonsai Trees, Bookshelf, Botania, Brandon's Core, BuildCraft, BuildCraft Lib, Building Gadgets, CXLibrary, Ceramics, Chameleon, Chance Cubes, Chest Transporter, Chickens, Chisel, Chisels & Bits, Clumps, CoFH Core, CoFH World, CodeChicken Lib, Colossal Chests, Comforts, CommonCapabilities, Compact Machines 3, Compact Solar Arrays, Compacter, ComputerCraft, Cooking for Blockheads, CraftTweaker JEI Support, CraftTweaker2, Crafting Tweaks, Cucumber Library, Custom Mod Rejection Messsage, Cyclic, Cyclops Core, Dark Utilities, Draconic Evolution, Ducky Mod, ET Lunar, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, EnderStorage, Enderman Evolution, EnergeticSheep, Environmental Tech, EvilCraft, EvilCraft-Compat, Ex Compressum, Ex Nihilo Creatio, Exchangers, Extra Cells 2, Extra Utilities 2, Extreme Reactors, FTB Utilities, FTBLib, Farming for Blockheads, Fast Leaf Decay, Flat Colored Blocks, Flux Networks, FoamFix, FoamFixCore, Forestry, Forge Microblocks, Forge Multipart CBE, Guide-API, Harvest, Hatchery, Hats, Immersive Engineering, Industrial Foregoing, Industrial Meat, IndustrialCraft 2, Integrated Dynamics, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTunnels-Compat, Integration Foregoing, Iron Backpacks, Iron Chest, JEI Bees, Just Enough Items, JustEnoughIDs, KleeSlabs, LLibrary, LagGoggles, Long Fall Boots, Loot Bags, LunatriusCore, MCMultiPart, MTLib, Mantle, McJtyLib, Mekanism, MekanismGenerators, MekanismTools, Mercurius, Minecraft Multipart Plugin, Missing Pieces, Mod Tweaker, Modpack Config Checker, More Chickens, More Furnaces, More Shearables, Morph-o-Tool, Morpheus, Mystical Agradditions, Mystical Agriculture, Natura, NetherPortalFix, Nice, Not Enough Wands, OpenBlocks, OpenModsLib, OpenModsLib Core, OreExcavation, OreSpawn, Oreberries, Pam's HarvestCraft, Pam's Simple Recipes, Placebo, PlusTiC, ProjectE, Psi, QuantumStorage, RF Lux, RFTools, RFTools Control, RFTools Dimensions, Random Things, RandomPatches, RandomTweaks, Realistic Item Drops, Reborn Core, RebornStorage, Redstone Arsenal, Redstone Flux, Refined Storage, Refined Storage Addons, Roost, Shadowfacts' Forgelin, Shear Madness, Signals, Simple Corn, Simple Inventory sorting, Simply Jetpacks 2, SlimyBoyos, Snad, Solar Flux Reborn, SonarCore, SpongeForge, Standard Expansion, Steve's Carts 2, StoneBlockUtilities, Storage Drawers, TESLA, Tesla Core Lib, Tesla Core Lib Registries, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Tinkers Tool Leveling, Tinkers' Construct, Tiny Progressions, TorchMaster, Translocators, Twerk-Sim 2K16, UniDict, Universal Modifiers, Valkyrie Lib, Void Island Control, Waila, WanionLib, What Are We Looking At, Whoosh, Wireless Crafting Terminal 2, Wither Skeleton Tweaks, Woot, World Primer, XNet, Xtones, Zero CORE, iChunUtil, mob_grinding_utils, p455w0rd's Library

**Issue Description**

Server will randomly disconnect all players after a large console spam of SPONGE console messages
Will say something like this and then lots of console spam. Will all be in log
[Server thread/ERROR] [Sponge]: /* Sponge's tracking system is very dependent on knowing when
a change to any world takes place, however there are chances
where Sponge does not know of changes that mods may perform.
In cases like this, it is best to report to Sponge to get this
change tracked correctly and accurately. */

This is the link to my google drive latest.log file as it is 48MB of console logs.
https://drive.google.com/file/d/1BSJjwyCsxcVDjIbTC92niWjfD7iIQ9et/view?usp=sharing

**Comment by phit** [comment]
i already told you the errors  have nothing to do with the disconnects..

actual error https://gist.github.com/phit/606f5b9e54565ed60ee727ada7705f19

**Comment by phit** [comment]
was unable to reproduce this with 
voidislandcontrol-1.4.3.jar
jei_1.12.2-4.13.1.225.jar
spongeforge-1.12.2-2768-7.1.5-RC3513.jar
griefprevention-1.12.2-4.3.0.662.jar
LuckPerms-Sponge-4.3.62.jar

I also tried setting this and using a custom island structure but still worked fine.

```
# Automatically give new players islands
B:autoCreate=true
```

could you please provide the island file you were using?

**Comment by Shybella** [comment]
https://pastebin.com/raw/1mzcYZxK


Install Stoneblock2 (Beta) Version 1.1.1
Add SF 3522
Add Nucleus-1.8.2-S7.1-MC1.12.2-plugin
Add LuckPerms-Sponge-4.3.76

Happens when I have 2 or more players attempting to join simultaneously. 

Update: Happens with only 1 single person joining.

**Comment by phit** [comment]
should be solved in 7.1.5-3534 or newer, if not leave a message and I'll reopen

**Comment by Shybella** [comment]
Yeap, all fixed.
