### ISSUE TITLE
fireServerConnection - Crash

### ISSUE THREAD

**Issue by Keaton1188** [SpongePowered/SpongeForge#2529]
**I am currently running**

- SpongeForge version: 1.12.2-2768-7.1.5-RC3509
- Forge version: 
- Java version: Java openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-b12)
- Operating System: CentOS Linux release 7.2.1511

- Plugins/Mods: SevTech: Ages

**Issue Description**
Hi there, recently updated to the new version of Sponge which sorted "Fire Forge ServerConnectionFromClientEvent" but our Server seems to be constantly crashing due to this, see crash report. 

https://pastebin.com/nNgFKzDs

**Comment by ImMorpheus** [comment]
Forge version ?

**Comment by Keaton1188** [comment]
14.23.4.2707

**Comment by ImMorpheus** [comment]
Method added by https://github.com/MinecraftForge/MinecraftForge/commit/1171668c25526bf360549b9670dd5b67aa45e355 on 08/16/2018.

Your version was released on 06/01/18.

Update to recommended.

https://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.12.2.html
