### ISSUE TITLE
Waterfall/Sponge/EnderIO can't connect to Waterfall lobby

### ISSUE THREAD

**Issue by krisjenner** [SpongePowered/SpongeForge#2530]
**I am currently running**

- SpongeForge version: 7.1.4
- Forge version: 2768
- Java version: 1.8.0_191
- Operating System: Windows 10

- Plugins (4): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge
-Mods (7): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, SpongeForge

**Issue Description**
I'm using Waterfall (BungeeCord fork) to connect my servers together with one main server (the hub/lobby). When users playing on the ATM3 pack are disconnected and sent to lobby, they get an [EnderIO error](https://ibb.co/YQ5YKD7). On removing Ender IO, Endergy and EnderCore from the client and trying again the player can connect perfectly regardless of all other mods installed. I reported this on [EnderIO git](https://github.com/SleepyTrousers/EnderIO/issues/4974) and was told it [not an issue on their end.](https://github.com/SleepyTrousers/EnderIO/issues/4975)

I've asked around multiple places, I'm not sure if here is the best place, but i figured it was worth a try.

[log](https://gist.github.com/krisjenner/a679a4af1b7390a1d8d7e3dc4f8355f6)
also: https://paste.ee/p/yavrN

**Comment by ImMorpheus** [comment]
@krisjenner Can you reproduce it without sponge ?

**Comment by krisjenner** [comment]
Without Sponge it has so far timed out on each attempt so yes i still can't connect to the server without Sponge but the error doesn't appear

**Comment by alicheek** [comment]
I can confirm that we get this error also on login seems to be quite a lot of issues with time outs at the moment not sure if sponge internally has a time out threshold might be worth to up a bit or give an option in the config to up with proxy servers.

**Comment by phit** [comment]
does this happen if you only have Sponge and not Bungeecord or one of its forks?

**Comment by alicheek** [comment]
@phit will do a test now for you with out travertine

**Comment by phit** [comment]
I just don't see how Sponge would cause this, it's most likely an issue with missing mods on the server. Which isn't really supported by mods, you can [fake that info](https://github.com/Stonebound/BungeeFakeForgeMods) and it may help. This is an intended safety check built into Forge.

**Comment by alicheek** [comment]
@phit So done a test with out travertine and there is no errors now seems i will need to push a comment of this over to travertine to try to fix.

In regards to your Fake info do you mean fork that into the build of proxy that we are using?

**Comment by lezargv** [comment]
I have the same issu if Ender IO is on my client I can’t connect to a server without this mod,if Vanilla it feels the same!
