### ISSUE TITLE
Sponge timings reports lead to 404 page

### ISSUE THREAD

**Issue by HFinner** [SpongePowered/SpongeForge#2533]
**I am currently running**
- SpongeForge version: 1.12.2-2768-7.1.5-RC3509.jar
- Forge version: 14.23.5.2768
- Java version: Unknown, Dedicated server being rented out
- Operating System: Windows

- Plugins/Mods: 

**MODS**: Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, /dank/null, Actually Additions, Actually Baubles, Akashic Tome, AppleSkin, Applied Energistics 2, ArchitectureCraft, Astral Sorcery, AutoRegLib, B.A.S.E, BD Lib, Bad Wither No Cookie! Reloaded, Baubles, Bed Patch, Better Advancements, Better Builder's Wands, BiblioCraft, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Blockcraftery, Blood Magic: Alchemical Wizardry, Bookshelf, Botania, Brandon's Core, Chameleon, Chest Transporter, Chisel, Chisels & Bits, Clumps, CoFH Core, CoFH World, CodeChicken Lib, Compact Machines 3, Compact Solar Arrays, Compacter, Construct's Armory, Cooking for Blockheads, CraftTweaker JEI Support, CraftTweaker2, Dark Utilities, DeepResonance, Diet Hopper, Dirt2Path, Draconic Evolution, Dynmap, ET Lunar, ElecCore, Embers Rekindled, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, EnderStorage, Engineer's Doors, Engineer's Workshop Reborn, Environmental Tech, Exchangers, Extra Cells 2, Extra Rails, Extra Utilities 2, Extreme Reactors, FTB Guides, FTB Utilities, FTBLib, FastWorkbench, Fence Jumper, Flat Colored Blocks, Flux Networks, Forestry, Forge Microblocks, Forge Multipart CBE, GenDustry, Guide-API, Harvest, Immersive Engineering, Immersive Petroleum, Industrial Foregoing, Industrial Wires, IndustrialCraft 2, InitialInventory, Integration Foregoing, Inventory Tweaks, Iron Backpacks, Iron Chest, JEI Bees, JourneyMap, Just Enough Items, KleeSlabs, Long Fall Boots, MCMultiPart, MTLib, MagicBees, Mantle, McJtyLib, MineTogether, MineTogetherServer, Minecraft Multipart Plugin, Mod Tweaker, Morph-o-Tool, Morpheus, MrTJPCore, MysticalLib, Natura, Nature's Compass, NetherPortalFix, Nice, Not Enough Wands, NotEnoughIDs, OpenBlocks, OpenComputers, OpenComputers (Core), OpenModsLib, OpenModsLib Core, Pam's HarvestCraft, Placebo, Platforms, ProjectRed Core, ProjectRed Expansion, ProjectRed Exploration, ProjectRed Fabrication, ProjectRed Illumination, ProjectRed Relocation, ProjectRed Transmission, ProjectRed Transportation, ProjectRed integration, Quark, Quick Leaf Decay, RFTools, RFTools Control, RFToolsPower, Ranged Pumps, Reborn Core, RebornStorage, Redstone Arsenal, Redstone Flux, Refined Storage, Refined Storage Addons, Reliquary, Roots 2, Rustic, Secret Rooms 5, SecretRooms Hooks, ShadowMC, Shadowfacts' Forgelin, ShetiPhian-Core, Signals, SimpleVoidWorld, Simply Jetpacks 2, Snad, SonarCore, Soot, Soul Shards - The Old Ways, SpongeForge, Steve's Carts 2, Storage Drawers, Storage Drawers Extras, TOP Addons, Tesla Core Lib, Tesla Core Lib Registries, Thaumcrafft Inventory Scanning, Thaumcraft, The Lost Cities, The One Probe, The Twilight Forest, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Thut Core, Thut's Elevators, ThutCore Compat, Tinkers Tool Leveling, Tinkers' Construct, TorchMaster, Translocators, Traverse, UniDict, Universal Modifiers, Valkyrie Lib, WanionLib, Waystones, Wireless Crafting Terminal 2, Woot, XNet, Xtones, YABBA, Zero CORE, careerbees, p455w0rd's Library

**PLUGINS**: Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge,  FastAsyncWorldEdit, AurionsVoteListener, Dynmap, GriefPrevention, Holograms, LuckPerms, NuVotifier, Nucleus, RankUpper, Total Economy, Universe Guard 2, WorldEdit

**Issue Description**
I have performed multiple sponge timings and left them running for around an hour. I then requested reports for these and they have led me to that aikar.co website and all I have received on there are 404 pages. Just wanted to notify you guys about this.

**Comment by phit** [comment]
you are probably using multicraft and its stripping `?i` from the url
add the non working links otherwise we can just guess

**Comment by HFinner** [comment]
Oh ok, so where would the "?i" be in a link like this?https://timings.aikar.co/d=efd93d20004c456d955e2c33f0c14e2f

**Comment by phit** [comment]
`https://timings.aikar.co/d=efd93d20004c456d955e2c33f0c14e2f`
should be
`https://timings.aikar.co/?id=efd93d20004c456d955e2c33f0c14e2f`

**Comment by HFinner** [comment]
Sweet thanks!
