### ISSUE TITLE
Spongeforge crashing server 

### ISSUE THREAD

**Issue by Phrixtheglitch** [SpongePowered/SpongeForge#2534]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2768-7.1.4.jar
- Forge version: 2768
- Java version: 8
- Operating System: win10 (server is hosted through Cubedhost)

- Plugins/Mods: Mystical Village 2 Modpack

[ANGRY PIXEL] The Betweenlands
by MrCompost
  
Actually Additions
by Ellpeck
  
Advanced Fishing
by NightKosh
 
Aether Legacy
by 115kino
  
Akashic Tome
by Vazkii
  
Ancient Warfare 2
by shadowmage45
 
Animania
by Purplicious_Cow
  
AppleCore
by squeek502
  
AppleSkin
by squeek502
 
ArchitectureCraft - ElytraDev Version
by bk1325
  
Astral Sorcery
by HellFirePvP
  
ATLCraft Candles Mod
by AllTheLayers
 
AutoRegLib
by Vazkii
  
B.A.S.E
by lanse505
  
Bailey's Dailies
by ToroCraft
 
Baubles
by azanor
  
BdLib
by bdew
  
BeeBetterAtBees
by HellFirePvP
 
Better Agriculture
by koxhack
  
Better Builder's Wands
by Portablejim
  
Better Questing
by Funwayguy
 
Better Questing - Quest Book
by Drethic
  
Better Questing - Standard Expansion
by Funwayguy
  
Better With Mods
by Beeto
 
BetterFps
by Guichaguri
  
BetterWithLib
by primetoxinz
  
BiblioCraft
by Nuchaz
 
Binnie's Mods
by Binnie567
  
Biome Bundle
by MC_Pitman
  
Blockcraftery
by epicsquid319
 
Bonsai Trees
by Davenonymous
  
Botania
by Vazkii
  
Ceramics
by KnightMiner
 
Chameleon
by jaquadro
  
Chest Transporter
by CubeX2
  
ChineseWorkshop
by cityofskytcd
 
Chisel
by tterrag1098
  
Chisels & Bits
by AlgorithmX2
  
Clear Water
by ExpensiveKoala
 
Clumps
by jaredlll08
  
CodeChicken Lib 1.8.+
by covers1624
  
Comforts
by TheIllusiveC4
 
Compact Drawers
by Samtrion
  
ConnectedTexturesMod
by tterrag1098
  
Cooking for Blockheads
by BlayTheNinth
 
Corail Pillar
by Corail31
  
Corail Pillar - Extension Chisel
by Corail31
  
Corail Pillar - Extension Forestry
by Corail31
 
Corail Pillar - Extension Quark & Botania
by Corail31
  
Crafting Tweaks
by BlayTheNinth
  
CraftStudio API
by ZeAmateis
 
CraftTweaker
by jaredlll08
  
Creeper Confetti
by SR2610
  
Cucumber Library
by BlakeBr0
 
Decocraft2
by RazzleberryFox
  
Dye It Yourself
by Poke1650
  
Earthworks
by Alsnder
 
Electroblob's Wizardry
by electroblob
  
EmberRoot Zoo
by Lothrazar
  
Ender Crop
by DrManganese
 
Ender Storage 1.8.+
by covers1624
  
Entity Spring
by jglrxavpok
  
Exotic Birds
by Pavocado
 
Extra Alchemy
by zabi94
  
Extra Bit Manipulation
by Phylogeny
  
Fast Leaf Decay
by Olafski
 
Flat Colored Blocks
by AlgorithmX2
  
FoamFix for Minecraft
by asiekierka
  
Foamflower
by kamildanak
 
Forestry
by SirSengir
  
FTBLib
by FTB_ModpackTeam
  
Furnus
by MrRiegel
 
Garden Stuff
by jaquadro
  
Gendustry
by bdew
  
Gendustry JEI Addon
by ninjabrain1
 
Giacomo's Bookshelf
by Zacomat
  
Giacomo's Foundry
by Zacomat
  
Gravestone mod - Extended
by NightKosh
 
Gravestone mod - Graves
by NightKosh
  
Guidebook
by gigaherz
  
Hatchery
by GenDeathrow
 
Heat And Climate
by defeatedcrow
  
Heat And Climate Lib
by defeatedcrow
  
Hopper Ducts
by FyberOptic
 
Horse Tweaks
by BlayTheNinth
  
Hwyla
by TehNut
  
Ice and Fire: Dragons in a whole new light!
by alex1the1666
 
Improved Backpacks
by DreenDex
  
Inventory Pets
by Purplicious_Cow
  
Inventory Tweaks
by Kobata
 
IvToolkit
by Ivorius
  
JEI Bees
by bdew
  
JEI Integration
by SnowShock35
 
JJ Coats of Arms
by jdijack_
  
JourneyMap
by techbrew
  
Just Enough HarvestCraft (JEHC)
by mrAppleXZ
 
Just Enough Items (JEI)
by mezz
  
Just Enough Resources (JER)
by Way2muchnoise
  
KleeSlabs
by BlayTheNinth
 
LagGoggles
by Terminator_NL_44352929
  
Level Up! Reloaded
by Beeto
  
LimeLib
by MrRiegel
 
LLibrary
by iLexiconn
  
LootBags
by Mal7690
  
LootTweaker
by Daomephsta
 
Lycanites Mobs
by Lycanite
  
Magic Bees
by MysteriousAges
  
Magic Clover
by konwboj
 
MalisisCore
by Ordinastie
  
MalisisDoors
by Ordinastie
  
Mantle
by mDiyo
 
MegaLoot
by Winter_Grave
  
MineTweaker RecipeMaker
by DoubleDoorDevelopment
  
Mo' Villages
by The_WeatherPony
 
Moar Boats
by jglrxavpok
  
More Beautiful Buttons
by Kreezxil
  
Morpheus
by Quetzi
 
Mouse Tweaks
by YaLTeR
  
MrCrayfish's Furniture Mod
by Mr_Crayfish
  
Mystical Agriculture
by BlakeBr0
 
Mystical Agriculture Tiered Crystals
by Electrolyte
  
MysticalLib
by epicsquid319
  
Natura
by mDiyo
 
Nature's Compass
by Chaosyr
  
NetherPortalFix
by BlayTheNinth
  
NotEnoughIDs
by fewizz
 
Open Terrain Generator (OTG)
by team_otg
  
Pam's HarvestCraft
by MatrexsVigil
  
Placebo
by Shadows_Of_Fire
 
Plants
by Shadows_Of_Fire
  
Platforms
by ShetiPhian
  
PrimalCore
by An_Sar
 
Primitive Mobs
by Daveyx0
  
PTRLib
by RazzleberryFox
  
Quark
by Vazkii
 
QuickHomes
by hiotewdew
  
Rainbow Oak Trees
by csb987
  
ReAuth
by TechnicianLP
 
Recurrent Complex
by Ivorius
  
Redstone Flux
by TeamCoFH
  
Reliquary v1.3
by P3pp3rF1y
 
Rockhounding Mod: Core
by GlobbyPotato
  
Rockhounding Mod: Rocks
by GlobbyPotato
  
Rockhounding Mod: Surface
by GlobbyPotato
 
Roguelike Dungeons
by Greymerk
  
Rustic
by mangoose3039
  
Shadowfacts' Forgelin
by shadowfactsmc
 
ShetiPhianCore
by ShetiPhian
  
Silent Lib
by SilentChaos512
  
Silent's Gems
by SilentChaos512
 
Silent's Gems: Extra Parts
by SilentChaos512
  
Sophisticated wolves
by NightKosh
  
Spartan Shields
by ObliviousSpartan
 
Spartan Weaponry
by ObliviousSpartan
  
Spice of Life: Carrot Edition
by LordCazsius
  
stimmedcow : NoMoreRecipeConflict
by GotoLink
 
Storage Drawers
by jaquadro
  
Storage Drawers Extras
by jaquadro
  
Switch-Bow
by White_Draco
 
Terraqueous
by ShetiPhian
  
Thaumcraft
by azanor
  
Thaumic Inventory Scanning (Thaumcraft Addon)
by BlayTheNinth
 
Thaumic JEI
by Buuz135
  
The Spice of Life
by squeek502
  
The Twilight Forest
by Benimatic
 
TrashSlot
by BlayTheNinth
  
Unlimited Chisel Works
by asiekierka
  
Unlimited Chisel Works - Botany
by asiekierka
 
Unloader
by Unnoen
  
VeinMiner
by Portablejim
  
Vending block
by kamildanak
 
Waila Harvestability
by squeek502
  
Wawla - What Are We Looking At
by Darkhax
  
Waystones
by BlayTheNinth
 
Wearable Backpacks
by InsomniaKitten
  
Wings
by pau101
  
Xtones
by TehNut
 
YABBA
by LatvianModder

Plugins:

Nucleus-1.7.0-S7.1-MC1.12.2-plugin
LuckPerms-Sponge-4.3.49
CatClearLag-0.9.0

**Issue Description**
server crash report attached, I have renamed the spongeforge jar to AAsponge so that it'll load first as it wasn't loading before but now its crashing
[crash-2018-12-15_04.11.12-server.txt](https://github.com/SpongePowered/SpongeForge/files/2682399/crash-2018-12-15_04.11.12-server.txt)
there is the crash report and I will be  completely honest i have no idea how to get the full server log...

**Comment by Shybella** [comment]
Both SpongeForge and FoamFix add various optimizations that may not work with each other! Disable the following settings in the config/foamfix.cfg
B:optimizedBlockPos=false (Sponge adds a similar performance patch)
B:patchChunkSerialization=false https://github.com/asiekierka/FoamFix/issues/166

**Comment by Phrixtheglitch** [comment]
totally worked thanks so much!
