### ISSUE TITLE
Mowzies Mobs Structures not spawning + Mobs not dropping items

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#2536]
**I am currently running**

- SpongeForge version: 1.12.2-2768-7.1.5-RC3511 
- Forge version: 1.12.2 - 14.23.5.2796
- Java version: Version 8 Update 191 [64 bit]
- Operating System: Windows 10 10.0.17134 Build 17134

- Plugins/Mods: Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, Buycraft, CatClearLag, GriefPrevention, LuckPerms, Nucleus, MMCPrefix.
(Please note; even disabling all plugins- it still affects Mowzies Mobs.)

**Issue Description**
In a normal singleplayer/server without spongeforge, structures mowzies-mobs related like where the Sun Chief spawns. Are not generated. (this excludes Ferrous Wroughtnaught structures as they are underground)
As well as this; Sun Chiefs don't actually spawn, however, Frostmaws/Foliaaths do.
SpongeForge also affects drops on these mobs; eg:
Killing a frostmaw is meant to drop a Ice Crystal, this never happens in spongeforge servers. But occurs in servers without Sponge.
Killing a Ferrous Wroughtnaut is meant to drop a Axe of a Thousand Metals or a Wrought Helm, this never occurs once again, in sponge forge servers, but occurs in normal servers without sponge.
This also happens with the tribesmen, they never drop the masks of misery, etc.

This issue overall is related to ALL Mowzies-Mobs drops; such as the Helm and Masks, Ice Crystals, etc.
and the generation of *above-ground* structures within Mowzies-Mobs

Our server log does not provide any information about not spawning.
However; if a server log is absolutely needed. I can provide one.

**Comment by phit** [comment]
on first read this sounds like mod issues, or the mod doing some odd stuff as I have not heard of any other mod having issues with mobs dropping items on death

the generation could be on either end, theres some other known compat issues with worldgen

**Comment by ghost** [comment]
Hey, phit; after doing some digging around I found a user with the same issue;
https://github.com/BobMowzie/MowziesMobs/issues/47

**
I've confirmed that this is caused from simply using SpongeForge, looking into further.
--
**

Hope this helps you out.

**Comment by ghost** [comment]
This issue could be going on in normal Sponge Servers also;
The developer actually made a bug/issue report here you can view also;

https://github.com/SpongePowered/SpongeCommon/issues/2007

Essentially meaning this could be Sponge and a SpongeForge problem.

**Comment by ghost** [comment]
Just captured a log in debug for you @phit ; You can find the log pasted below as to what is happening.

`> /***********************************************************************************************************************************************************************************************/
/*                                                                        Failed to process all PhaseContext captured!                                                                         */
/***********************************************************************************************************************************************************************************************/
/* During the processing of a phase, certain objects were captured in a PhaseContext. All of them should have been removed from the PhaseContext by this point EntityPhase{}{DeathUpdateState} */
/* PhaseContext :                                                                                                                                                                              */
/*     - Source: EntityFrostmaw['Frostmaw'/2790, l='world', x=-1106.39, y=64.00, z=1134.21]                                                                                                    */
/*     - EntityItemEntityDrops: EntityItemEntityDropsSupplier{Captured=1}                                                                                                                      */
/*     - CapturedBlockPosition: CaptureBlockPos{pos=null, world=Optional.empty}                                                                                                                */
/*     - DamageSource: null                                                                                                                                                                    */
/* Phases remaining :                                                                                                                                                                          */
/*   - Phase: EntityPhase{}{DeathUpdateState}                                                                                                                                                  */
/*     Context:                                                                                                                                                                                */
/*     - Source: EntityFrostmaw['Frostmaw'/2790, l='world', x=-1106.39, y=64.00, z=1134.21]                                                                                                    */
/*     - EntityItemEntityDrops: EntityItemEntityDropsSupplier{Captured=1}                                                                                                                      */
/*     - CapturedBlockPosition: CaptureBlockPos{pos=null, world=Optional.empty}                                                                                                                */
/*     - DamageSource: null                                                                                                                                                                    */
/*   - Phase: EntityTickPhase                                                                                                                                                                  */
/*     Context:                                                                                                                                                                                */
/*     - Owner: EntityPlayerMP['0xEviqnn_'/2026, l='world', x=-1105.89, y=64.00, z=1127.36]                                                                                                    */
/*     - Source: EntityFrostmaw['Frostmaw'/2790, l='world', x=-1106.39, y=64.00, z=1134.21]                                                                                                    */
/*     - CapturedBlockPosition: CaptureBlockPos{pos=null, world=Optional.empty}                                                                                                                */
/*                                                                                                                                                                                             */
/* Minecraft : 1.12.2                                                                                                                                                                          */
/* SpongeAPI : 7.1.0-81ce267d                                                                                                                                                                  */
/* Sponge : 1.12.2-7.1.5-SNAPSHOT                                                                                                                                                              */
/* SpongeForge : 1.12.2-2768-7.1.5-RC3522                                                                                                                                                      */
/* Minecraft Forge : 14.23.5.2807                                                                                                                                                              */
/***********************************************************************************************************************************************************************************************/`

**Comment by phit** [comment]
please retest on 7.1.5-RC3535 or newer
http://files.minecraftforge.net/spongepowered

**Comment by ghost** [comment]
Hey @phit , I have just managed to test the 7.1.5-RC3535 version of SpongeForge, I am glad to say; the "Frostmaw" mob now drops items! I have also tested this with the barakoa/other mowzies mobs and it works! Not too sure about the Sun God spawning as I haven't gotten the time yet to check this out.

Two further issues;

Upon brutally murdering the Frostmaw it produces a very large, unwanted log: You can view these below.
https://pastebin.com/1uUNa1Vh

This log repeats a fair few times and can make it quite difficult for a server manager to go back through other log files.

**There was also a "Illegal Async PhaseTracker Access" issue; which you can see below.**

https://pastebin.com/26TvNbED

After further testing this to try and re-produce this issue, it appears that this log only occurs once(?)- I cannot confirm this as of now and the time I have. But perhaps this huge log is a one-time thing.

Otherwise, thanks for fixing this issue!

**Comment by phit** [comment]
opened a [new issue](https://github.com/SpongePowered/SpongeForge/issues/2577) for that first error, the second one is a known issue with new versions https://github.com/SpongePowered/SpongeForge/issues/2574
