### ISSUE TITLE
Spongeforge Crash

### ISSUE THREAD

**Issue by DEDarkLightZ** [SpongePowered/SpongeForge#2537]
**I am currently running**

- SpongeForge version:  2768-7.1.5
- Forge version: 2768
- Java version: 8
- Operating System: Linux

- Plugins/Mods:
Mr Crayfishs Furniture mod
Mr Crayfish´s Gun Mod
Mr Crayfish´s Vehicle mod
Just Enogh Items
Chisels and Bits
Gravestone Mod
Obfuscate
Spongeforge
Industrialcraft 2
CodeChickenCore

**Issue Description**
When i Start the server with  Spongeforge the server seems to start normal but then it crashes. When i start the server without Spongeforge the server starts normally 

[latest.log](https://github.com/SpongePowered/SpongeForge/files/2707186/latest.log)

**Comment by ImMorpheus** [comment]
Your `level_sponge.dat` files are corrupted, if you've got `level_sponge.dat.old` files in the `world/` and `world/DIM-1` directories, remove your `level_sponge.dat` files and rename the `old` files as `level_sponge.dat`

**Comment by DEDarkLightZ** [comment]
Thanks for the Help, It worked.
