### ISSUE TITLE
"Shift T" feature from Quark raises IllegalStateException exception

### ISSUE THREAD

**Issue by limbo-app** [SpongePowered/SpongeForge#2542]
This issue was originally submitted by @bluelightning32 in [SpongePowered/SpongeCommon#2168](https://github.com/SpongePowered/SpongeCommon/issues/2168).
___
**I am currently running**
- SpongeForge version:  1.12.2-2768-7.1.5-RC3512
- Java version: OpenJDK 64-Bit Server VM, version 1.8.0_191, running on Linux:amd64:4.19.8-300.fc29.x86_64
- Operating System: Fedora 29

- Plugins/Mods:
Lots of mods present. The one mod relevant to the bug is Quark. I also have the ultimatechat plugin install. I'm not sure if that's a factor.

**Issue Description**
Quark has a feature where you can hover over an item in your inventory, then press shift-T to print that item in chat. The feature works fine with just forge, but with spongeforge, the player gets disconnected.

I'm hitting this with the Enigmatica Expert 2 modpack. However, I found that someone else already filed a bug report with Quark about it from a different mod pack. The Quark author closed the bug and said it's a Sponge problem, not a Quark problem.

https://github.com/Vazkii/Quark/issues/917

**Comment by Aaron1011** [comment]
This is an issue with Quark. I've opened a new issue: https://github.com/Vazkii/Quark/issues/1102

**Comment by Aaron1011** [comment]
Fixed in https://github.com/Vazkii/Quark/commit/3dc57e28112bd9982caaf8c8ec94cae68a5869bf
