### ISSUE TITLE
Minecraft Crash

### ISSUE THREAD

**Issue by DEDarkLightZ** [SpongePowered/SpongeForge#2545]
Hello, When i want to start my minecraft forge server. The server instantly crashes. Can someone help me? I am using the 1.7.10
[fml-server-latest.log](https://github.com/SpongePowered/SpongeForge/files/2719586/fml-server-latest.log)

**Comment by Aaron1011** [comment]
Unfortunately, Sponge does not support Minecraft 1.7.10. You'll need to upgrade to Minecraft 1.12.2 to be able to use Sponge.
