### ISSUE TITLE
FLan's mods airplanes disappear randomly, only happening with SpongeForge, even without plugins

### ISSUE THREAD

**Issue by dgranadam** [SpongePowered/SpongeForge#2548]
**I am currently running**

- SpongeForge version: 1.12.2-2768-7.1.5-RC3514 , also happens on 1.12.2-2768-7.1.4 Stable
- Forge version: 1.12.2-14.23.5.2768
- Java version: 1.8.0_181
- Operating System: Windows 10 64 bit and Ubuntu 16.04 LTS

- Plugins/Mods:
No plugins
Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, Ancient Warfare Automation, Ancient Warfare Core, Ancient Warfare NPCs, Ancient Warfare Structures, Ancient Warfare Vehicles, Baubles, BuildCraft, BuildCraft Builders, BuildCraft Compat, BuildCraft Energy, BuildCraft Factory, BuildCraft Lib, BuildCraft Robotics, BuildCraft Silicon, BuildCraft Transport, CoFH Core, CoFH World, CodeChicken Lib, Flan's Mod, IndustrialCraft 2, Just Enough Items, Mantle, Redstone Flux, SpongeForge, Thaumcraft, Thermal Expansion, Thermal Foundation, Tinkers' Construct

HOWEVER: I've been observing this issue ever since I was using ONLY Flan's mods (V5.6-beta) and BuildCraft (7.99.20). It is NOT mod interaction with the others.

**Issue Description**
At random times when flying a plane from flans mod (less than a minute from takeoff, usually) the plane will disappear and the user plummets to the ground. The plane doesn't drop as an item and is lost forever. Additionally, if the user then presses SHIFT, they will teleport again to the spot where the plane disappeared. 
Reproduce:
1. Load flan's mod on a spongeforge server.
2. Spawn any plane by searching on creative mode and clicking the item on the ground. start flying with W and your mouse.
3. Literally just wait, fly around, whatever. Eventually the plane disappears and you're left falling to the ground
4. (Conjecture) I THINK it only happens whenever the server is lagging somehow. I've often seen "Cant keep up! Did the...." logs whenver the plane disappears, but NOT ALWAYS.

There is NOTHING else on the logs anytime around when the plane diappears. Not on the console log or the debug log. SOMETIMES flan's will mention "[15:49:52] [Server thread/WARN] [flansmod]: Killing wheel due to invalid type tag" However this doesn't correlate to the disappearance of planes, and can happen at random times, even when you don't fly a plane.

I have tested the issue on a raw Forge Server, a SpongeForge server with a bunch of plugins and a SF server without plugins. It ONLY happens on SpongeForge servers, no matter how many mods or plugins are installed. It also doesn't happen on singleplayer.

https://gist.github.com/coldblade2000/e99766da21c83754f636c2ca832515a9

**Comment by ghost** [comment]
Hi, i was having the same exact problem but have now fixed it using the fix from this report: https://github.com/FlansMods/FlansMod/issues/993

Which was this (Credit ChrisLane)
 "SpongeForge has a config option 'max-speed' that will remove entities going over the configured value.

Please read: https://docs.spongepowered.org/stable/en/server/getting-started/configuration/sponge-conf.html"

**Comment by dgranadam** [comment]
> 
> 
> Hi, i was having the same exact problem but have now fixed it using the fix from this report: [FlansMods/FlansMod#993](https://github.com/FlansMods/FlansMod/issues/993)
> 
> Which was this (Credit ChrisLane)
> "SpongeForge has a config option 'max-speed' that will remove entities going over the configured value.
> 
> Please read: https://docs.spongepowered.org/stable/en/server/getting-started/configuration/sponge-conf.html"

Thank you so much. I'll close this now
