### ISSUE TITLE
Quark Extract Bug

### ISSUE THREAD

**Issue by Shybella** [SpongePowered/SpongeForge#2553]
**I am currently running**

- SpongeForge version: RC3505-7.10
- Forge version: 2768
- Java version: 1.8 update 191
- Operating System: Windows Server 2016

- Plugins/Mods: Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, /dank/null, Actually Additions, Advanced Generators, Akashic Tome, AppleSkin, Applied Energistics 2, Aroma1997's Dimensional World, Aroma1997Core, Astral Sorcery, AutoRegLib, BD Lib, Bad Wither No Cookie! Reloaded, Baubles, Better Advancements, Better Builder's Wands, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Biomes O' Plenty, Blockcraftery, Blood Magic: Alchemical Wizardry, Bookshelf, Botania, Brandon's Core, Chameleon, ChickenChunks, Chisel, Chisels & Bits, CoFH Core, CoFH World, CodeChicken Lib, CommonCapabilities, Compact Machines 3, Compact Solar Arrays, Cooking for Blockheads, CraftTweaker JEI Support, CraftTweaker2, Cyclops Core, Dark Utilities, DeepResonance, Diet Hopper, Draconic Evolution, ElecCore, Elevator Mod, EluCore, EluLib, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, EnderStorage, Environmental Tech, Exchangers, Extra Utilities 2, Extreme Reactors, FastWorkbench, Flat Colored Blocks, Forestry, Funky Locomotion, GenDustry, Gravestone Mod, Guide-API, Immersive Engineering, Industrial Foregoing, IndustrialCraft 2, Integrated Dynamics, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTunnels-Compat, Iron Backpacks, Iron Chest, JEI Bees, JourneyMap, Just Enough Items, MCMultiPart, MTLib, MagicBees, Mantle, McJtyLib, MeeCreeps, Mercurius, MineTogether, MineTogetherServer, Mod Tweaker, Morph, Morph-o-Tool, Morpheus, NetherPortalFix, Not Enough Wands, OpenComputers, OpenComputers (Core), Pam's HarvestCraft, Placebo, PneumaticCraft: Repressurized, PortalGun, Psi, Quick Leaf Decay, RFTools, RFTools Control, RFTools Dimensions, Ranged Pumps, Reborn Core, RebornStorage, Redstone Arsenal, Redstone Flux, Refined Storage, Refined Storage Addons, Shadowfacts' Forgelin, Simple Inventory sorting, Simply Jetpacks 2, Storage Drawers, Storage Drawers Extras, SwingThroughGrass, TESLA, TOP Addons, Tesla Core Lib, Tesla Core Lib Registries, Thaumcraft, The Lost Cities, The One Probe, The Twilight Forest, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Tinkers' Construct, UniDict, Universal Modifiers, Valkyrie Lib, WanionLib, Wireless Crafting Terminal 2, XNet, Zero CORE, iChunUtil, mob_grinding_utils, p455w0rd's Library

**Issue Description**

Steps to reproduce
1. Install Auction from Randombyte or install Huskycrates (Only two I tested and were successful)
2. Add items to the crate and open it or Auction a item and use /auction show and click "Extract" on the left hand side of the GUI.
3. You get the item using Quark extract when you should not.

You need this install server side, although, I have not tried it not installed server side. I disabled the extract server side but still able to steal from locked GUIs.

Running Quark version: Quark-r1.5-130

**Comment by Shybella** [comment]
https://github.com/Vazkii/Quark/blob/master/src/main/java/vazkii/quark/management/feature/ChestButtons.java

**Comment by phit** [comment]
try setting both `B:"Chest buttons"=false` and `B:"Store to chests"=false` for now

**Comment by phit** [comment]
merging this with https://github.com/SpongePowered/SpongeForge/issues/2289
