### ISSUE TITLE
Stoneblock 2 modpack incorrect teleport destination

### ISSUE THREAD

**Issue by krisjenner** [SpongePowered/SpongeForge#2555]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2768-7.1.5-RC3522
- Forge version: 2796

Sponge didn't work with Stoneblock 2 teleporting players to the next dimension once they reached a certain Y level - it does work now but sends players to the wrong dimensions.

**Comment by phit** [comment]
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/2266
