### ISSUE TITLE
Astral Sorcery Starlight Infuser incompatibility.

### ISSUE THREAD

**Issue by robokop92** [SpongePowered/SpongeForge#2557]
**I am currently running**
SpongeForge version: spongeforge-1.12.2-2768-7.1.5-RC3522
Forge version: forge-1.12.2-14.23.5.2781-universal
Java version: V8 U191
Operating System: Win 10

Plugins/Mods:
- astralsorcery-1.12.2-1.10.10
- Baubles-1.12-1.5.2

**Issue Description**
The Starlight Infuser does not work when running sponge. Loading the world in singleplayer, the infuser works as intended.

**Comment by phit** [comment]
please add a reproduction and assume no one here knows how to use that mod at all..

**Comment by robokop92** [comment]
Steps to reproduce: 

1. Build the Startlight Infuser multiblock as described [here](https://ftb.gamepedia.com/Starlight_Infuser) in the Structure section.
2. Place an Aquamarine on the Starlight Infuser block by right clicking with it.
3. Right click the Starlight Infuser block with a Resonating Wand

On a server running sponge nothing happens, but normally an animation will begin and the Aquamarine will turn into a Resonating Gem (Liquid Starlight might be consumed in the process and break the multiblock).

**Comment by phit** [comment]
https://github.com/HellFirePvP/AstralSorcery/blob/20844296c23c2b7d449ccf962c43f88be014a9cc/src/main/java/hellfirepvp/astralsorcery/common/block/BlockStarlightInfuser.java#L58

**Comment by phit** [comment]
can't reproduce with 
spongeforge-1.12.2-2768-7.1.6-RC3586.jar
astralsorcery-1.12.2-1.10.11.jar

1. created the infuser `/astralsorcery build patternStarlightInfuser`
2. placed aquamarine on the starlight infuser block
3. right clicked the block with a resonating wand

animation started and a resonating gem was created

**Comment by majijn** [comment]
you didn't follow the process of creating an infuser as an end-user of the mod would, it's not surprising you got different results.
@phit

**Comment by phit** [comment]
reproduce it with latest astral sorcery and ill reopen this, but im pretty sure this was fixed with https://github.com/HellFirePvP/AstralSorcery/commit/217820d129e3e1231164e305ced87620afd2cbb9

**Comment by majijn** [comment]
I'm only pointing out that your attempt of reproducing the issue was faulty if all you did was as the steps you're describing there say.
