### ISSUE TITLE
OTG sliced world generation crash.

### ISSUE THREAD

**Issue by EasterncheesE** [SpongePowered/SpongeForge#2561]
Minecraft version: 12.2.2
Forge version: 2768
Sponge version: spongeforge-1.12.2-2768-7.1.4

Issue description:
I can create OTG world with sponge installed with no issues.
However, OTG give the ability to make a height-based portal to other dimension;
If someone get to 0 height, it teleports user to other dimension.
As of worldconfig of OTG, the world is getting loaded together with overworld (which is also generated by OTG).
Seems both Sponge and OTG messes with 1 thing making server crash.

While spongeforge is installed, the overworld (OTG-created) loads fine, but when i go to 0 height, i get teleportation screen and server crashed.

The crash report can be seen at link attached: https://pastebin.com/Z1nMjAMN

If i delete spongeforge, then everything works okay and issue is resolved, but it's not a solution, because i don't those sweet sponge plugins. 

Also i have installed Nucleus and projectworlds in order to create more custom OTG world, but both show this error when i try to create OTG dimension (world create Caves -g openterraingenerator:o_t_g command)
Error: https://pastebin.com/EvsZ3w3B

**Comment by phit** [comment]
https://github.com/PG85/OpenTerrainGenerator/pull/216

**Comment by EasterncheesE** [comment]
As i can see, the world creation via plugin is addressed to OTG. I hope the crash report issue is also taken into account. Seems like there are 2 issues in one issue report:
1) Issue, which makes impossible to create and teleport to additional dimension using OTG "worldBelow" option while spongeforge is installed.
2) Issue, which makes plugins like nucleus unable to create dimensions using OTG as generator.

**Comment by phit** [comment]
both crashes on the same error right now

**Comment by EasterncheesE** [comment]
Got the updated version of OTG and world generation process now start, thanks. Another issue arose, i will post it separately.
