### ISSUE TITLE
Knot that turns 100% ??

### ISSUE THREAD

**Issue by Aathoss** [SpongePowered/SpongeForge#2564]
- Forge 1.12.2 - 2768
- Sponge 1.12.2-2768-7.1.5-RC3526 

Mods / plugin = no

New map generation vanilla
No movement during the timings : https://timings.aikar.co/?id=2f3eaa2a5735490ebae1e9ee3efc2851#timings

Host spec : 
Proc : i5-8600k 3,6Ghz
Ram : 16Go (4 GB allocation to the server)
SSD 256 Go

why is the kernel spinning as much as that ?
I have a bigger server with mods that seems to slow it down
I tested with this version also similar : Sponge 1.12.2-2768-7.1.4

Thank You

**Comment by phit** [comment]
no idea what you want or what your issue is, the timings look fairly normal, please use our forums or support chats for help https://www.spongepowered.org/chat
