### ISSUE TITLE
PO3 (3.0.35) Exception in Server Tick Loop

### ISSUE THREAD

**Issue by CrypticDivide** [SpongePowered/SpongeForge#2570]
## Server Information

**SpongeForge version:** 1.12.2-2768-7.1.5-RC3526
**Forge version:** 14.23.5.2808 
**Java version:** 1.8.0_172
**Operating System:** Windows 10 Pro ─ Version 1803 (Build 17134.320)

---
## Plugins Installed
**No Plugins Installed**

## Mods Installed
**The mods that have been installed are listed on the [Project Ozone 3 modpack webpage](https://minecraft.curseforge.com/projects/project-ozone-3-a-new-way-forward).**

---
## Issue Description
When trying to start a server for Project Ozone 3 (3.0.35) using SpongeForge, the server crashes and states "Exception in server tick loop".

Please note that I have already tried the recommended version of Forge for running PO3 (Forge ...2795), tried running the recommended version of SpongeForge (7.1.4 release), and I have already changed the version of LagGoggles from FORGE to SPONGEFORGE.

> Server Log » [2019-01-22-7.log](https://github.com/SpongePowered/SpongeForge/files/2785945/2019-01-22-7.log)
> Debug Log » [debug-1.log](https://github.com/SpongePowered/SpongeForge/files/2785949/debug-1.log)
> Crash Report » [crash-2019-01-22_23.14.07-server.txt](https://github.com/SpongePowered/SpongeForge/files/2785960/crash-2019-01-22_23.14.07-server.txt)

**Comment by phit** [comment]
Both SpongeForge and FoamFix add various optimizations that may not work with each other! Disable the following settings in `config/foamfix.cfg`

`B:optimizedBlockPos=false`
`B:patchChunkSerialization=false`
