### ISSUE TITLE
Turntable BetterWithMods bug

### ISSUE THREAD

**Issue by RussianJeb** [SpongePowered/SpongeForge#2571]
**I am currently running**

- SpongeForge version: 1.12.2-2768-7.1.5-RC3526 
- Forge version: 1.12.2-2768
- Java version: 1.8
- Operating System:

- Plugins/Mods: Better With Mods(Mod)

**Issue Description**
I have bug with betterwithmod turntable on Sponge server. With some chance clay block not transform to Unfired Pottery and begin infinite throwing clay item.
Bug video: https://youtu.be/r0VCdyXavdA

**Comment by gabizou** [comment]
Will need more information how to set this up, steps for making the machine or whatever it is that I'm guessing is the turntable (I don't know how it functions). Also, what's the expected result of the clay block to happen? Is it supposed to disappear?

**Comment by RussianJeb** [comment]
To create mechanism needs: source of energy(I used Creative Gearbox), turntable and axle for connecting source to turntable. After connecting, you need to select the speed of clay processing with the right mouse button. When everything is connected and the speed is selected, then install the clay block. The block of clay will have to be gradually transformed into Unfired Pottery and it will drop clay. Then you just need to take the form of Unfired Pottery where the clay block was. But the transformation of the clay block does not start and it always falls out pieces of clay.
Video which shows the clay processing process: https://youtu.be/-IIoBsdVdbw

**Comment by phit** [comment]
I believe this is fixed, tried this a bunch and it never got in the state of not transforming the clay block. Can you confirm @RussianJeb ?
Tested with:
BetterWithMods-1.12-2.3.20-1027.jar
BetterWithLib-1.12-1.5.jar
spongeforge-1.12.2-2838-7.1.7-RC3807.jar

**Comment by RussianJeb** [comment]
Yes, i checked and this is fixed.
