### ISSUE TITLE
Mowzies Mobs Not a mixin Entity for this implementation

### ISSUE THREAD

**Issue by phit** [SpongePowered/SpongeForge#2577]
7.1.5-RC3535

Upon brutally murdering the Frostmaw it produces a very large, unwanted log: You can view these below.
https://gist.github.com/phit/f52317c579446cdb0d3d29e6cab77fc9

This log repeats a fair few times and can make it quite difficult for a server manager to go back through other log files.

_Originally posted by @0xEviqnn in https://github.com/SpongePowered/SpongeForge/issues/2536#issuecomment-457698131_

**Comment by ghost** [comment]
<3
