### ISSUE TITLE
ambidextrous unable to place blocks

### ISSUE THREAD

**Issue by 4rz0** [SpongePowered/SpongeForge#2581]
**I am currently running**
- SpongeForge version: 2768-7.1.4
- Forge version: 14.23.5.2768
- Java version: 1.8.0_181 (No update request has appeared as of yet)
- Operating System: Windows 10

- Plugins (4): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge
- Mods (9): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, Ambidextrous, Just Enough Items, SpongeForge

The ambidextrous function "Use Main Hand" doesn't work on a server with spongeforge installed. Blocks get placed and removed from the player inventory, but instantly get removed from world and reappear in player inventory after a inventory refresh.
Full issue description available at https://github.com/AlgorithmX2/Ambidextrous/issues/4

https://gist.github.com/4rz0/69aa25f9d56cd673e3129f999a4dab7b

**Comment by 4rz0** [comment]
The logs show me logging in and using ambidextrous' "Use Main Hand" feature to try to place blocks between timestamps [13:21:44] and [13:22:40].

**Comment by ImMorpheus** [comment]
@4rz0 Try 1.12.2-2768-7.1.5-RC3540

I'm pretty sure this is fixed by the Interact events PR.

**Comment by 4rz0** [comment]
@ImMorpheus The version you mentioned does indeed fix the issue.
