### ISSUE TITLE
Trying to run PO3 with sponge

### ISSUE THREAD

**Issue by Spontini** [SpongePowered/SpongeForge#2583]
Sponge Version: 1.12.2-2768-7.1.5-RC3540 
Minecraft Version: 1.12.2
Modpack: Project Ozone 3 A New Way Foward
Forge Version: 14.23.5.2795

Issue: I'm triyng to run PO3 server with sponge, i'm draging sponge jar to the mods folder as it should be then starting the server but some reason server can not start itself with sponge so it basically ignore sponge and all plugins then start without sponge, at least this is all i can see from logs

Log: https://paste.feed-the-beast.com/view/3e1624d9

**Comment by dualspiral** [comment]
LagGoggles is loading an older version of Mixin (0.7.5) than Sponge needs - they should update LG to use the latest version.

For temporary solution rename the SpongeForge jar file, so its sorted alphabetically before the other mod e.g. rename spongeforge-1.12.2-2768-7.1.5-RC3540.jar to _aspongeforge-1.12.2-2768-7.1.5-RC3540.jar. That should ensure Sponge loads its version first, which _will_ work with LagGoggles.

**Comment by Spontini** [comment]
First of all thank for your response but right now i'm having another issue after i renamed sponge and here is the crash report;
https://paste.feed-the-beast.com/view/91717b02

**Comment by Spontini** [comment]
Okay, i fixed it too, it was about foamfix
