### ISSUE TITLE
World loading GalactiCraft crash

### ISSUE THREAD

**Issue by SSKirillSS** [SpongePowered/SpongeForge#2584]
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2768-7.1.5-RC3540
- Forge version: forge-1.12.2-14.23.5.2768
- Java version: 1.8.0_162 x64
- Operating System: Linux(Server), Windows7(Client) - x64

- Plugins/Mods:
Mods (89): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AE2 Stuff, Applied Energistics 2, Aquaculture, BD Lib, Baubles, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Biomes O' Plenty, BuildCraft, BuildCraft Builders, BuildCraft Compat, BuildCraft Energy, BuildCraft Factory, BuildCraft Lib, BuildCraft Robotics, BuildCraft Silicon, BuildCraft Transport, CoFH Core, CoFH World, CodeChicken Lib, CraftTweaker JEI Support, CraftTweaker2, CustomNPCs, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, Energy Converters, Extra Cells 2, Extra Planets, Forestry, Galacticraft Core, Galacticraft Planets, Immersive Engineering, Immersive Petroleum, Immersive Tech, IndustrialCraft 2, Iron Chest, Just Enough Items, LibrarianLib, LibrarianLib Stage 2, MJRLegendsLib, MTLib, Micdoodle8 Core, Mod Tweaker, More Bees, More Planets, NuclearCraft, OpenComputers, OpenComputers (Core), OpenFM, OpenGlasses, Pam's HarvestCraft, Redstone Flux, Serene Seasons, Shadowfacts' Forgelin, SpongeForge, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, TickProfiler, Tiquality, Treecapitator, UniDict, WanionLib, WebShop Server Mod, WorldEdit, bspkrsCore
Plugins (22): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, Boop, CarrotShop, CatClearLag, ClaimTweaks, CommandUtils, GriefPrevention, HilPack, Holograms, ItemChat, LuckPerms, MMCRestrict, Nucleus, PacketGate, PlaceholderAPI, Plan, Title Broadcaster, VoxelSniper, spark

**Issue Description**
When traveling on the moon, the server simply crashes whith this error: https://gist.github.com/SSKirillSS/5c7f2379822bd83fe06255f263fa512d (latest.log) and https://gist.github.com/SSKirillSS/c73e68988e6638d27e5cf6fc802efe2a (crash-report) . After restarting this chunk is no longer a problem, but another one appears.

GalacticraftCore-1.12.2-4.0.2.190
Galacticraft-Planets-1.12.2-4.0.2.190
MicdoodleCore-1.12.2-4.0.2.190

**Comment by phit** [comment]
https://github.com/SpongePowered/SpongeForge/issues/2405
