### ISSUE TITLE
Techguns Power Armor extra health glitch

### ISSUE THREAD

**Issue by Fishkaras** [SpongePowered/SpongeForge#2588]
Minecraft version: 1.12.2
Forge version: 2768/2808
Sponge version: spongeforge-1.12.2-2768-7.1.4
Techguns: 2.0.1.2_pre2/2.0.1.3_pre1

Server launch log: https://gist.github.com/Fishkaras/99a88364a29cbd19c3fac738e9c8e695
Client launch log: https://gist.github.com/Fishkaras/72ce30c87573ff15f2847984751409b0

**Issue Description**
Armor adds 5 points of health: 3 hearts in GUI, 2.5 of them are filled.
If a sponge is installed, 5 hearts are displayed, 2.5 of them are filled.
At the same time the last 2 hearts constantly flicker
But this flicker can not be seen in the screenshot.

Screenshots:
https://i.imgur.com/MUjP1yd.png
https://i.imgur.com/85ejCxq.png

This issue on Techguns github: https://github.com/pWn3d1337/Techguns2/issues/93

**Comment by phit** [comment]
this was probably fixed with https://github.com/SpongePowered/SpongeCommon/commit/aa2d7d1d046c03569f5ae1911c5d93f969362ea7

**Comment by phit** [comment]
was fixed according to comment on mod issue tracker
