### ISSUE TITLE
Unable to register recipe

### ISSUE THREAD

**Issue by mmis1000** [SpongePowered/SpongeForge#2592]
**I am currently running**

- SpongeForge version: 1.12.2-2768-7.1.5-RC3495
- Forge version: 2768
- Java version: openj9
- Operating System: linux

- Plugins/Mods:

**Issue Description**
startup crash

crash report: https://gist.github.com/james58899/881669a525581d14d587c82e3d32c492

crash site: https://github.com/SpongePowered/SpongeCommon/blob/79b3c2a3981d22c4c692106dda738263837b734a/src/main/java/org/spongepowered/common/item/recipe/crafting/SpongeCraftingRecipeRegistry.java#L126

**Comment by Cybermaxke** [comment]
Can you retest with the latest build?

**Comment by mmis1000** [comment]
@Cybermaxke 
Got another crash, method became privated now?
It looks like AT does not got applied correctly
https://gist.github.com/mmis1000/0b9881360689843b1b52502b65846eb2

**Comment by Zidane** [comment]
@Cybermaxke thoughts?

**Comment by Cybermaxke** [comment]
@mmis1000 Should be fixed now.
https://github.com/SpongePowered/SpongeCommon/commit/f6dfe72ddf14f23538516bcec36029f759e6befe
