### ISSUE TITLE
Cannot get property as it does not exist in BlockStateContainer

### ISSUE THREAD

**Issue by limbo-app** [SpongePowered/SpongeForge#2594]
This issue was originally submitted by @NawwDidums in [SpongePowered/Ore#742](https://github.com/SpongePowered/Ore/issues/742).
___
Was told to put this here. not sure how to reproduce it or replicate it, but it's happening alot atm.

https://pastebin.com/a72B4N5L

**Comment by phit** [comment]
@NawwDidums please post your global.conf

**Comment by NawwDidums** [comment]
Sure, I did recently delete it and re-dit it but the issue persists.

https://pastebin.com/nG2E9Umz

**Comment by phit** [comment]
try turning off tile entity activation and see if it persists

**Comment by NawwDidums** [comment]
Still persists

**Comment by NawwDidums** [comment]
This time with stone, rather than air

**Comment by phit** [comment]
closing for now if this shows up again and you have a reproduction make a new issue
