### ISSUE TITLE
Server Crash Report Unknow problem with Sponge

### ISSUE THREAD

**Issue by Xiantrius** [SpongePowered/SpongeForge#2595]
i use 1.12.2-2768-7.1.4 Stable Recommended
last test.
1.12.2-2768-7.1.5-RC3542

I can play with Sponge in a new world.
I can not continue my old world with Sponge, unfortunately only without.

Crash Report on my server here
here open Details

Read here:
Sponge Forum
https://forums.spongepowered.org/t/crash-report-unknow-problem-with-sponge/27175

> ---- Minecraft Crash Report ----
> 
> WARNING: coremods are present:
>   SpongeCoremod (_Plugins spongeforge-1.12.2-2768-7.1.4.jar)
>   ForgelinPlugin (Forgelin-1.8.0.jar)
>   IELoadingPlugin (ImmersiveEngineering-core-0.12-88.jar)
>   EnderCorePlugin (EnderCore-1.12.2-0.5.45.jar)
>   CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
> Contact their authors BEFORE contacting forge
> 
> // Daisy, daisy...
> 
> Time: 31.01.19 16:37
> Description: Exception in server tick loop
> 
> java.lang.RuntimeException: derp
> 	at net.minecraft.world.storage.SaveHandler.redirect$onLoadWorldInfo$bcl000(SaveHandler.java:1073)
> 	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:132)
> 	at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:711)
> 	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:3545)
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
> 	at java.lang.Thread.run(Unknown Source)
> Caused by: java.lang.RuntimeException: Attempt failed when reading Sponge level data for [DIM-1] from file [level_sponge.dat]!
> 	at net.minecraft.world.storage.SaveHandler.loadSpongeDatData(SaveHandler.java:619)
> 	at net.minecraft.world.storage.SaveHandler.redirect$onLoadWorldInfo$bcl000(SaveHandler.java:1071)
> 	... 6 more
> Caused by: java.io.EOFException
> 	at java.util.zip.GZIPInputStream.readUByte(Unknown Source)
> 	at java.util.zip.GZIPInputStream.readUShort(Unknown Source)
> 	at java.util.zip.GZIPInputStream.readHeader(Unknown Source)
> 	at java.util.zip.GZIPInputStream.<init>(Unknown Source)
> 	at java.util.zip.GZIPInputStream.<init>(Unknown Source)
> 	at net.minecraft.nbt.CompressedStreamTools.func_74796_a(CompressedStreamTools.java:26)
> 	at net.minecraft.world.storage.SaveHandler.loadSpongeDatData(SaveHandler.java:616)
> 	... 7 more
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Server thread
> Stacktrace:
> 	at net.minecraft.world.storage.SaveHandler.redirect$onLoadWorldInfo$bcl000(SaveHandler.java:1073)
> 	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:132)
> 
> -- Sponge PhaseTracker --
> Details:
> 	Phase Stack: [Empty stack]
> Stacktrace:
> 	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zjk000(MinecraftServer.java:3980)
> 	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:889)
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:371)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:558)
> 	at java.lang.Thread.run(Unknown Source)
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.12.2
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 1.8.0_192, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 6810368496 bytes (6494 MB) / 8265924608 bytes (7883 MB) up to 8265924608 bytes (7883 MB)
> 	JVM Flags: 2 total; -Xms8G -Xmx8G
> 	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
> 	FML: MCP 9.42 Powered by Forge 14.23.5.2807 76 mods loaded, 76 mods active
> 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
> 
> 	| State  | ID                                | Version            | Source                                             | Signature                                |
> 	|:------ |:--------------------------------- |:------------------ |:-------------------------------------------------- |:---------------------------------------- |
> 	| LCHIJA | minecraft                         | 1.12.2             | minecraft.jar                                      | None                                     |
> 	| LCHIJA | mcp                               | 9.42               | minecraft.jar                                      | None                                     |
> 	| LCHIJA | FML                               | 8.0.99.99          | forge-1.12.2-14.23.5.2807-universal.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
> 	| LCHIJA | forge                             | 14.23.5.2807       | forge-1.12.2-14.23.5.2807-universal.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
> 	| LCHIJA | spongeapi                         | 7.1.0-70763aa8     | _Plugins spongeforge-1.12.2-2768-7.1.4.jar         | None                                     |
> 	| LCHIJA | sponge                            | 1.12.2-7.1.4       | _Plugins spongeforge-1.12.2-2768-7.1.4.jar         | None                                     |
> 	| LCHIJA | spongeforge                       | 1.12.2-2768-7.1.4  | _Plugins spongeforge-1.12.2-2768-7.1.4.jar         | None                                     |
> 	| LCHIJA | animalbikes                       | 1.11.2             | AnimalBikes_1.12.2(13Jan19).jar                    | None                                     |
> 	| LCHIJA | appliedenergistics2               | rv6-stable-6       | appliedenergistics2-rv6-stable-6.jar               | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
> 	| LCHIJA | bno                               | 1.12.2-1.0.0.0     | BasicNetherOres-1.12.2-1.0.0.0.jar                 | None                                     |
> 	| LCHIJA | baubles                           | 1.5.2              | Baubles-1.12-1.5.2.jar                             | None                                     |
> 	| LCHIJA | bettermobgriefinggamerule         | 1.12.2-7.0.1       | bettermobgriefinggamerule-1.12.2-7.0.1.jar         | None                                     |
> 	| LCHIJA | bookshelf                         | 2.3.573            | Bookshelf-1.12.2-2.3.573.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
> 	| LCHIJA | codechickenlib                    | 3.2.2.353          | CodeChickenLib-1.12.2-3.2.2.353-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
> 	| LCHIJA | redstoneflux                      | 2.1.0              | RedstoneFlux-1.12-2.1.0.6-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
> 	| LCHIJA | brandonscore                      | 2.4.9              | BrandonsCore-1.12.2-2.4.9.195-universal.jar        | None                                     |
> 	| LCHIJA | chesttransporter                  | 2.8.8              | ChestTransporter-1.12.2-2.8.8.jar                  | None                                     |
> 	| LCHIJA | chickenchunks                     | 2.4.1.73           | ChickenChunks-1.12.2-2.4.1.73-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
> 	| LCHIJA | cofhcore                          | 4.6.1              | CoFHCore-1.12.2-4.6.1.22-universal.jar             | None                                     |
> 	| LCHIJA | cofhworld                         | 1.3.0              | CoFHWorld-1.12.2-1.3.0.6-universal.jar             | 8a6abf2cb9e141b866580d369ba6548732eff25f |
> 	| LCHIJA | crafttweaker                      | 4.1.14             | CraftTweaker2-1.12-4.1.14.jar                      | None                                     |
> 	| LCHIJA | mtlib                             | 3.0.5              | MTLib-3.0.5.jar                                    | None                                     |
> 	| LCHIJA | modtweaker                        | 4.0.16             | modtweaker-4.0.16.jar                              | None                                     |
> 	| LCHIJA | jei                               | 4.14.4.259         | jei_1.12.2-4.14.4.259.jar                          | None                                     |
> 	| LCHIJA | crafttweakerjei                   | 2.0.2              | CraftTweaker2-1.12-4.1.14.jar                      | None                                     |
> 	| LCHIJA | thermalfoundation                 | 2.6.1              | ThermalFoundation-1.12.2-2.6.1.22-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
> 	| LCHIJA | draconicevolution                 | 2.3.18             | Draconic-Evolution-1.12.2-2.3.18.329-universal.jar | None                                     |
> 	| LCHIJA | eplus                             | 5.0.176            | EnchantingPlus-1.12.2-5.0.176.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
> 	| LCHIJA | endercore                         | 1.12.2-0.5.45      | EnderCore-1.12.2-0.5.45.jar                        | None                                     |
> 	| LCHIJA | thaumcraft                        | 6.1.BETA26         | Thaumcraft-1.12.2-6.1.BETA26.jar                   | None                                     |
> 	| LCHIJA | thermalexpansion                  | 5.5.2              | ThermalExpansion-1.12.2-5.5.2.39-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
> 	| LCHIJA | enderio                           | 5.0.40             | EnderIO-1.12.2-5.0.40.jar                          | None                                     |
> 	| LCHIJA | enderiointegrationtic             | 5.0.40             | EnderIO-1.12.2-5.0.40.jar                          | None                                     |
> 	| LCHIJA | enderiobase                       | 5.0.40             | EnderIO-1.12.2-5.0.40.jar                          | None                                     |
> 	| LCHIJA | enderioconduits                   | 5.0.40             | EnderIO-1.12.2-5.0.40.jar                          | None                                     |
> 	| LCHIJA | enderioconduitsappliedenergistics | 5.0.40             | EnderIO-1.12.2-5.0.40.jar                          | None                                     |
> 	| LCHIJA | enderioconduitsopencomputers      | 5.0.40             | EnderIO-1.12.2-5.0.40.jar                          | None                                     |
> 	| LCHIJA | enderioconduitsrefinedstorage     | 5.0.40             | EnderIO-1.12.2-5.0.40.jar                          | None                                     |
> 	| LCHIJA | enderiointegrationforestry        | 5.0.40             | EnderIO-1.12.2-5.0.40.jar                          | None                                     |
> 	| LCHIJA | enderiointegrationticlate         | 5.0.40             | EnderIO-1.12.2-5.0.40.jar                          | None                                     |
> 	| LCHIJA | enderiomachines                   | 5.0.40             | EnderIO-1.12.2-5.0.40.jar                          | None                                     |
> 	| LCHIJA | enderiopowertools                 | 5.0.40             | EnderIO-1.12.2-5.0.40.jar                          | None                                     |
> 	| LCHIJA | enderstorage                      | 2.4.5.135          | EnderStorage-1.12.2-2.4.5.135-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
> 	| LCHIJA | extrautils2                       | 1.0                | extrautils2-1.12-1.9.8.jar                         | None                                     |
> 	| LCHIJA | zerocore                          | 1.12-0.1.2.3       | zerocore-1.12-0.1.2.3.jar                          | None                                     |
> 	| LCHIJA | bigreactors                       | 1.12.2-0.4.5.50    | ExtremeReactors-1.12.2-0.4.5.50.jar                | None                                     |
> 	| LCHIJA | fastleafdecay                     | v14                | FastLeafDecay-1.12.2v14.jar                        | None                                     |
> 	| LCHIJA | forgelin                          | 1.8.0              | Forgelin-1.8.0.jar                                 | None                                     |
> 	| LCHIJA | forgemultipartcbe                 | 2.6.0.79           | ForgeMultipart-1.12.2-2.6.0.79-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
> 	| LCHIJA | microblockcbe                     | 2.6.0.79           | ForgeMultipart-1.12.2-2.6.0.79-universal.jar       | None                                     |
> 	| LCHIJA | minecraftmultipartcbe             | 2.6.0.79           | ForgeMultipart-1.12.2-2.6.0.79-universal.jar       | None                                     |
> 	| LCHIJA | teslacorelib                      | 1.0.15             | tesla-core-lib-1.12.2-1.0.15.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
> 	| LCHIJA | industrialforegoing               | 1.12.2-1.12.2      | industrialforegoing-1.12.2-1.12.4-228.jar          | None                                     |
> 	| LCHIJA | lunatriuscore                     | 1.2.0.42           | LunatriusCore-1.12.2-1.2.0.42-universal.jar        | None                                     |
> 	| LCHIJA | mantle                            | 1.12-1.3.3.39      | Mantle-1.12-1.3.3.39.jar                           | None                                     |
> 	| LCHIJA | mtrm                              | 1.2.2.30           | MineTweakerRecipeMaker-1.12.2-1.2.2.30.jar         | None                                     |
> 	| LCHIJA | mystcraft                         | 0.13.7.02          | mystcraft-1.12.2-0.13.7.02.jar                     | None                                     |
> 	| LCHIJA | natura                            | 1.12.2-4.3.2.66    | natura-1.12.2-4.3.2.66.jar                         | None                                     |
> 	| LCHIJA | netherchest                       | 1.1.1              | netherchest-1.1.1.jar                              | None                                     |
> 	| LCHIJA | netherportalfix                   | 5.3.17             | NetherPortalFix_1.12.1-5.3.17.jar                  | None                                     |
> 	| LCHIJA | nei                               | 2.4.2              | NotEnoughItems-1.12.2-2.4.2.240-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
> 	| LCHIJA | progressivedifficulty             | 1.12_3.1           | ProgressiveDifficulty-1.12_3.1.jar                 | None                                     |
> 	| LCHIJA | redstonearsenal                   | 2.6.1              | RedstoneArsenal-1.12.2-2.6.1.15-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
> 	| LCHIJA | schematica                        | 1.8.0.169          | Schematica-1.12.2-1.8.0.169-universal.jar          | None                                     |
> 	| LCHIJA | superfactorymanager               | @VERSION@          | SuperFactoryManager-1.12.2-2.0.8.jar               | None                                     |
> 	| LCHIJA | thaumicenergistics                | 2.1.0              | thaumicenergistics-2.1.0.jar                       | None                                     |
> 	| LCHIJA | thaumictinkerer                   | 1.12.2-5.0-353c71c | thaumictinkerer-1.12.2-5.0-353c71c.jar             | None                                     |
> 	| LCHIJA | thermaldynamics                   | 2.5.3              | ThermalDynamics-1.12.2-2.5.3.16-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
> 	| LCHIJA | tombstone                         | 3.3.0              | tombstone-3.3.0-1.12.jar                           | None                                     |
> 	| LCHIJA | worldedit                         | 6.1.8              | worldedit-forge-mc1.12-6.1.8-dist.jar              | None                                     |
> 	| LCHIJA | worldprotector                    | 1.0                | WorldProtector+(1.12).jar                          | None                                     |
> 	| LCHIJA | wrcbe                             | 2.3.1              | WR-CBE-1.12.2-2.3.1.30-universal.jar               | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
> 	| LCHIJA | nucleus                           | 1.8.2-S7.1         | Nucleus-1.8.2-S7.1-MC1.12.2-plugin.jar             | None                                     |
> 	| LCHIJA | immersiveengineering              | 0.12-88            | ImmersiveEngineering-0.12-88.jar                   | 4cb49fcde3b43048c9889e0a3d083225da926334 |
> 	| LCHIJA | mysticallib                       | 1.12.2-1.0.0       | mysticallib-1.12.2-1.0.0.jar                       | None                                     |
> 	| LCHIJA | teslacorelib_registries           | 1.0.15             | tesla-core-lib-1.12.2-1.0.15.jar                   | None                                     |
> 
> 	Loaded coremods (and transformers): 
> SpongeCoremod (_Plugins spongeforge-1.12.2-2768-7.1.4.jar)
>   org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
> ForgelinPlugin (Forgelin-1.8.0.jar)
>   
> IELoadingPlugin (ImmersiveEngineering-core-0.12-88.jar)
>   blusunrize.immersiveengineering.common.asm.IEClassTransformer
> EnderCorePlugin (EnderCore-1.12.2-0.5.45.jar)
>   com.enderio.core.common.transform.EnderCoreTransformer
>   com.enderio.core.common.transform.SimpleMixinPatcher
> CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
>   team.chisel.ctm.client.asm.CTMTransformer
> 	AE2 Version: stable rv6-stable-6 for Forge 14.23.5.2768
> 	Pulsar/natura loaded Pulses: 
> 		- NaturaCommons (Enabled/Forced)
> 		- NaturaOverworld (Enabled/Not Forced)
> 		- NaturaNether (Enabled/Not Forced)
> 		- NaturaDecorative (Enabled/Not Forced)
> 		- NaturaTools (Enabled/Not Forced)
> 		- NaturaEntities (Enabled/Not Forced)
> 		- NaturaOredict (Enabled/Forced)
> 		- NaturaWorld (Enabled/Not Forced)
> 
> 	Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
>                  An unsupported base software is installed: 'sponge'. This is NOT supported.
>                  This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
> 
> 	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> 	!!!You are looking at the diagnostics information, not at the crash.       !!!
> 	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
> 	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> 
> 	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:OFF, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:ON
> 	Profiler Position: N/A (disabled)
> 	Player Count: 0 / 8; []
> 	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
> 	Type: Dedicated Server (map_server.txt)

**Comment by phit** [comment]
> Attempt failed when reading Sponge level data for [DIM-1] from file [level_sponge.dat]!

delete `world/DIM-1/level_sponge.dat` and/or replace it with a file from backup or `world/DIM-1/level_sponge.dat_old`

**Comment by Krysinski** [comment]
I have same problem, but i had to restore all files in world/DIM* folders from level_sponge.dat_old. How can system/mc server/sponge do this automaticaly? Please, reopen issue.
