### ISSUE TITLE
Villagers don't drop XP if trade result is shift-clicked out of GUI

### ISSUE THREAD

**Issue by PolyacovYury** [SpongePowered/SpongeForge#2596]
**I am currently running**
- SpongeForge version: 1.12.2-2768-7.1.4
- Forge version: 2768
- Java version: 8

**Issue Description**

As always, title has it all. If you hold Shift and press left-click on trade reult in villager's GUI - it doesn't drop any XP. However, if you just left-click the trade result - XP is dropped immediately.

Might be SpongeCommon bug. Also might have been fixed already.

**Comment by gabizou** [comment]
Can this be retested? I've got a gut feeling that it'll be warned about in the PhaseTracker on newer builds.

**Comment by JBYoshi** [comment]
I can't reproduce this on the latest version (RC3774).
