### ISSUE TITLE
Project E broken

### ISSUE THREAD

**Issue by 123Kappa** [SpongePowered/SpongeForge#2598]
Minecraft Version: 1.12.2
Modpack: Project Ozone 3
Sponge Version:  Tried with 1.12.2-2768-7.1.5,  1.12.2-2768-7.1.6-RC3561, 1.12.2-2768-7.1.6-RC3560
Issue: ProjectE completely broken, at least 95% of the items which should've EMC doesn't have EMC at all and items like Transmutation Table, Tablet, Energy Condensers doesn't work, i've tried everything in single player and in a server that i haven't installed  sponge and i have used ProjectE without zero problems so i can confirm that the problem is Sponge sided.

Edit: tome of knowledge doesnt work for any items. And items without emc work in a buggy way in a condenser

**Comment by dezil** [comment]
@123Kappa @Explosivee can you give some real examples of items not working that you would expect to so it can be tested

**Comment by 123Kappa** [comment]
It's literally 90% of the items, even stone. I can make a video showing you the items if you still want one

**Comment by dezil** [comment]
no thats fine, for reference we are running spongeforge-1.12.2-2768-7.1.5-RC3505 and Project E is running as expected

**Comment by 123Kappa** [comment]
In project ozone 3 right? I have the modpack itself, sponge and nucleus

**Comment by dezil** [comment]
yes

**Comment by 123Kappa** [comment]
hmmm, that's very odd.. any thoughts to what may be happening?

**Comment by 123Kappa** [comment]
Please do not close the thread yet I wanna see what the other guy has to say. It's weird that we both have the same problem

**Comment by dezil** [comment]
update we have tested this with spongeforge-1.12.2-2768-7.1.6-RC3561 and all is still working fine so this is not an issue with Spongeforge

    Minecraft: 1.12.2
    SpongeAPI: 7.1.0-005d9ff6
    Sponge: 1.12.2-7.1.6-SNAPSHOT
    SpongeForge: 1.12.2-2768-7.1.6-RC3561
    Minecraft Forge: 14.23.5.2811

also we tested this on a new instance as well as our current instance, values are there on both

**Comment by phit** [comment]
@123Kappa people can still reply to closed issues
thanks for testing @dezil
