### ISSUE TITLE
World Pregen Crash: world.gen.SpongeChunkGenerator

### ISSUE THREAD

**Issue by Wissi** [SpongePowered/SpongeForge#2600]
**I am currently running**

- SpongeForge version: 1.12.2-2768-7.1.6-RC3557
- Forge version: 1.12.2 - 14.23.5.2768
- Java version: 1.8.0_171
- Operating System:Windows 8.1

- Plugins/Mods:   mods only can't start server to place plugins.
AppleSkin-mc1.12-1.0.9.jar
AttributeFix-1.12.2-1.0.4.jar
backpacks+1.12.2+-+3.5.4.jar
bdlib-1.14.3.12-mc1.12.2.jar
bedpatch-2.2-1.12.2.jar
BetterAdvancements-1.12.2-0.0.17.74.jar
BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar
BetterQuesting-3.5.288.jar
ChestTransporter-1.12.2-2.8.8.jar
chiselsandbits-14.30.jar
Clipboard-1.12-1.3.0.jar
Clumps-3.1.1.jar
CodeChickenLib-1.12.2-3.2.2.353-universal.jar
conarm-1.12.2-1.2.3.jar
CookingForBlockheads_1.12.2-6.4.69.jar
CosmeticArmorReworked-1.12.2-v4.jar
CraftingTweaks_1.12.2-8.1.9.jar
CraftTweaker2-1.12-4.1.14.jar
CreativeCore_v1.9.37_mc1.12.2.jar
DankNull-1.12-1.4.46.jar
DeathCounter-1.12.1-1.0.0.jar
diamondglass-1.12.2-3.0.15.jar
diethopper-1.1.jar
Display-1.2.4.jar
ElevatorMod-1.12.2-1.3.6.jar
endercrop-1.12.2-1.6.0.jar
EnderStorage-1.12.2-2.4.5.135-universal.jar
ExCompressum_1.12.2-3.0.26.jar
exnihilocreatio-1.12-0.3.2.jar
ExtraBitManipulation-1.12.2-3.4.1.jar
ezstorage-2.5.0-[1.12.2].jar
FarmingForBlockheads_1.12.2-3.1.26.jar
FasterLadderClimbing-1.12-0.1-146.jar
FastFurnace-1.12.2-1.2.1.jar
FastWorkbench-1.12.2-1.6.0.jar
fencejumper-1.12-1.0.5.jar
foamfix-0.10.3-1.12.2.jar
Forgelin-1.8.2.jar
ForgeMultipart-1.12.2-2.6.0.79-universal.jar
Headcrumbs-1.12.2-2.0.5.17.jar
jei_1.12.2-4.14.4.264.jar
JustEnoughResources-1.12.2-0.8.10.50.jar
KleeSlabs_1.12.2-5.4.11.jar
leverbuttonlights-1.12.2-3.2.9.jar
LittleTiles_v1.5.0-pre124_mc1.12.2.jar
Mantle-1.12-1.3.3.39.jar
minecolonies-1.12.2-0.10.160-ALPHA-universal.jar
missing_pieces-1.12.2-4.3.0.jar
modtweaker-4.0.15.jar
Morpheus-1.12-3.3.2.jar
MTLib-3.0.5.jar
MultipleLights-1.12.x-1.0.2.jar
NetherPortalFix_1.12.1-5.3.17.jar
NoMobSpawningOnTrees-1.2.2-mc1.12.2.jar
NoMoreRecipeConflict-0.12(1.12.2).jar
NotEnoughIDs-1.5.4.3.jar
OreExcavation-1.4.133.jar
p455w0rdslib-1.12.2-2.0.36.jar
Pam's HarvestCraft 1.12.2zb.jar
petrock-0.3.1.jar
Ping-1.12.2-1.4.4.jar
placeableitems-3.3.jar
Placebo-1.12.2-1.5.1.jar
pressure-1.3.1.9-mc1.12.2.jar
questbook-3.1.1-1.12.jar
randompatches-1.12.2-1.13.0.0.jar
randomtweaks-1.12.2-2.4.2.1.jar
RealisticItemDrops-1.2.14.jar
ResourceLoader-MC1.12.1-1.5.3.jar
sampler-1.80.jar
ShadowMC-1.12-3.8.0.jar
SimpleStorageNetwork-1.12.2-1.5.6.jar
simplylight-0.6.0.jar
Snad-1.12.1-1.7.09.16a.jar
spongeforge-1.12.2-2768-7.1.6-RC3557.jar
StandardExpansion-3.4.149.jar
StoneBlockDimensions-1.0.2.jar
StoneBlockUtilities-2.1.4.jar
StoneChest-1.0.4.jar
TConstruct-1.12.2-2.12.0.115.jar
technicallights-1.0.0.1.jar
theoneprobe-1.12-1.4.27.jar
TinkersComplement-1.12.2-0.3.0.jar
TinkerToolLeveling-1.12.2-1.1.0.jar
tombstone-3.3.0-1.12.jar
topaddons-1.12.2-1.10.1.jar
torchmaster_1.12.2-1.7.1.74.jar
tramplestopper-1.12.2-1.2.3-universal.jar
Translocators-1.12.2-2.5.1.77-universal.jar
TrashSlot_1.12.1-8.4.6.jar
TS2K16-1.2.10.jar
unloader-1.2.0.jar
VanillaPlusTools-1.2.jar
voidislandcontrol-1.5.2.jar
WR-CBE-1.12.2-2.3.1.30-universal.jar
WrapUp-1.12-1.1.3.jar

**Issue Description**

Server is working perfectly fine as is with Forge only. When trying to install Sponge it crashes on last step of server:  "preparing load region for level 0 (world)" then crashes server.

Crash log  Gist: [Crash Log](https://gist.github.com/Wissi/269e764320abb25e45bc5a736d658ad3)
Full server log Gist:  [latest.log ](https://gist.github.com/Wissi/6b7350247e1106a67fd31f72c8d4a111)

**Comment by XakepSDK** [comment]
Both SpongeForge and FoamFix add various optimizations that may not work with each other!
Disable the following settings in `config/foamfix.cfg`
`B:optimizedBlockPos=false`
`B:patchChunkSerialization=false`

**Comment by Wissi** [comment]
Did not know that.
Tried the config settings and still crashed.
Nuked Foamfix and all is working perfectly fine.

Thank you very much for your quick and knowledgeable response.
