### ISSUE TITLE
Astral Sorcery Starlight Infuser Not Working

### ISSUE THREAD

**Issue by Spontini** [SpongePowered/SpongeForge#2601]
**I am currently running**

- SpongeForge version: 1.12.2-2768-7.1.6-RC3561
- Forge version: forge-1.12.2-14.23.5.2808
- Java version: Java 8 Update 201 (64bit)
- Operating System: Ubuntu 10.04

Astral Sorcery Starlight Infuser Not Working with sponge.

Steps to reproduce:

1. Build the Startlight Infuser multiblock as described [here](https://ftb.gamepedia.com/Starlight_Infuser) in the Structure section.
2. Place an Aquamarine on the Starlight Infuser block by right clicking with it.
3. Right click the Starlight Infuser block with a Resonating Wand
4. You've finished crafting Resonanting Gem (Not in sponge tho.)

**Comment by phit** [comment]
https://github.com/SpongePowered/SpongeForge/issues/2557
