### ISSUE TITLE
Erabus Dimension

### ISSUE THREAD

**Issue by Spontini** [SpongePowered/SpongeForge#2603]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2768-7.1.6-RC3561
- Forge version: 2808
- Java version: Java 8 Update 201 (64bit)
- Operating System: Ubuntu 18.04

- Plugins/Mods:
 Minecraft
 MinecraftCoderPack
 SpongeAPI
 Sponge
 Auction
 AurionsVoteListener
 BetterChunkLoader
 Boop
 Buycraft
 CarrotShop
 CatClearLag
 CmdBuilder
 CmdControl
 CommandSignsReloaded
 EconomyLite
 GWMLibrary
 Holograms
 InventoryKeeper
 ItemChat
 LuckPerms
 MMCReboot
 MMCRestrict
 MagiBridge
 NuVotifier
 Nucleus
 PixelAutoMessages
 PlaceholderAPI
 Prism
 PrismPlus
 RankUpper
 TabModifier
 Wasted
 Spark

**Issue Description**
Erebus dimension randomly crashes while exploring.

https://paste.feed-the-beast.com/view/ce79b04f

**Comment by phit** [comment]
as there are even people having this issue on 1.7 this is quite clearly a mod issue

**Comment by vadis365** [comment]
Hello,
Doesn't happen with a straight forge install, and I haven't had this issue reported to Erebus before.
It may well be a mod issue, but it's an interaction with sponge that causes it.
Cheers,
Me.

**Comment by phit** [comment]
ok? what is this https://github.com/vadis365/TheErebus/issues/684

**Comment by vadis365** [comment]
12 days ago - on 1.7.10 on themos - lol
ok so it's been reported twice on 2 different versions ;)

**Comment by 123Kappa** [comment]
https://github.com/vadis365/TheErebus/issues/500
 This is from 2016, similar crash. Don't know if it was fixed before and it is happening again
( commented on the other post by accident vadis)

**Comment by vadis365** [comment]
lol np
The redgem crash was fixed - this may be a similar issue - although the code does check for an offset for the gen and shouldn't cause any runaway. If it's a block on a chunk edge causing a block update then I can tell any observer blocks to ignore the state change.

**Comment by 123Kappa** [comment]
In case it has't been clarified, it's a common crash. It happens on my server too and I have talked with other owners and they said that it happens to them also :/

**Comment by vadis365** [comment]
I'll deal with this on my tracker, as the sponge guys have enough on their plates - and I'm not bouncing around 3 or 4 issue posts for 1 issue.

**Comment by phit** [comment]
I'll leave this open to keep track of this though, and if it turns out it is really our fault, which is quite possibly feel free to reach out. Sorry for the rushed closing, could be quite possible Thermos did similar edits to generation.

**Comment by vadis365** [comment]
No worries - it's always someone elses fault until it's fixed right? :)
Probably is Erebus - I'll poke about in the gen code and add some checks to make sure it's all safe.

**Comment by gabizou** [comment]
I'm more than willing to figure out what is causing the crash, usually these sort of crashes in relation to sponge's world generation ~takeover~ modifications are from assumptions that end up being violated for various reasons. From the look of the stack trace, I'm not seeing anything out of line for what Sponge is doing as it applies the same offset for every population call gathered for the various gen pops that vanilla would otherwise apply similarly. I'd be curious to find out what corner case sponge is introducing to cause the exception in Erabus's code.

**Comment by 123Kappa** [comment]
Any news on this issue?

**Comment by Zidane** [comment]
@Explosivee Give the latest a try and see if it still happens.

**Comment by phit** [comment]
This appears to be fixed, flew around for 5 minutes or so in spectator generating lots of terrain, then I generated 20k chunks using Forge `/forge generate 0 0 0 20000 66` and [it was fine](https://i.imgur.com/1yrt9i3.png) too. Versions:
Erebus-1.0.30
spongeforge-1.12.2-2838-7.1.7-RC3807

If this still happens to you please reply and we can reopen this!
