### ISSUE TITLE
Server couldn't start, it crashes everytime when try to start

### ISSUE THREAD

**Issue by Krysinski** [SpongePowered/SpongeForge#2606]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2768-7.1.5
- Forge version: forge-1.12.2-14.23.5.2768
- Java version: Oracle 1.8.0_171
- Operating System: Debian 9.5 64bit

- Plugins/Mods: view crashreport

**Issue Description**
Server couldn't start, it crashes everytime when try to start. Same issue described in #2595 
Server can't automaticaly restore empty level_sponge.dat in world/DIM* folders from files level_sponge.dat_old. That would partially solve a problem.

https://gist.github.com/Krysinski/1175e00a8200d63cf9c505918ebe0539

**Comment by Zidane** [comment]
Nor will the server automatically use those files (as you would never know there is an issue). You have corruption of those files.

Delete your level_sponge.dat
Rename level_sponge.dat_old to level_sponge.dat
Start the server

**Comment by Krysinski** [comment]
1. Other files was not corrupted, only from sponge.
2. There was shortly "power off" situation and second server 1.7.10 on Thermos without sponge starts fine. No corrupted files.
I think that it is necessary to exclude the appearance of damaged files, or to force the server to attempt to restore the files (after making a backup of the world in "world.zip". It works for me on thermos.)
Or would I have to write a script in bash that would detect this type of error and restore the files? I'm not very good at bash, unfortunately. I suggest you solve this, at least a customizable option in the config wich user will choose.

**Comment by Shybella** [comment]
Just do backups and write your own little script to restore the files. 

Or fix the problem of powering off all together.

**Comment by Krysinski** [comment]
just? Can u write some skel for a script?

**Comment by Krysinski** [comment]
@Zidane for what is used level_sponge.dat files?

**Comment by Zidane** [comment]
@Krysinski The biggest thing in that file is the World's Unique identifier (UUID). As well as it has stuff like difficulty.

I've seen many servers run Sponge and never have this problem. Ones running for months.

**Comment by Krysinski** [comment]
@Zidane If my script will copy level_sponge.dat_old to level_sponge.dat every time when server start, that is ok?
