### ISSUE TITLE
Exception in server tick loop - co.aikar.timings

### ISSUE THREAD

**Issue by LokeYourC3PH** [SpongePowered/SpongeForge#2609]
- SpongeForge version: spongeforge-1.12.2-2768-7.1.6-RC3565
- Forge version: 14.23.5.2811
- Java version: JDK 8 202
- Operating System: Windows 10 Pro (Nitrado Server crash, OS not relevant)

- Plugins/Mods:
==================== Plugins (14) =====================
 - Minecraft
 - Minecraft Coder Pack
 - SpongeAPI
 - Sponge
 -  FastAsyncWorldEdit
 - LuckPerms
 - ModBanner
 - Nucleus
 - PlayerDataReset-Plugin
 - ProjectCore
 - ProjectWorlds
 - RedProtect
 - ServerListPlus
 - WorldEdit
======================== ˠ۠=========================
===================== Mods (117) =====================
 - Minecraft
 - Minecraft Coder Pack
 - Forge Mod Loader
 - Minecraft Forge
 - SpongeAPI
 - Sponge
 - AE2 Stuff
 - Admin Weapons
 - Advanced Rocketry
 - Advanced Rocketry Core
 - Advanced Solar Panels
 - Applied Energistics 2
 - AsmodeusCore
 - BD Lib
 - Better Records
 - Brandon's Core
 - ChickenChunks
 - CoFH Core
====================== ˠ1/7 ۠=======================
===================== Mods (117) =====================
 - CoFH World
 - CodeChicken Lib
 - ComputerCraft
 - CoroUtil Library
 - CraftTweaker JEI Support
 - CraftTweaker2
 - Draconic Evolution
 - Ender IO
 - Ender IO Applied Energistics Conduits
 - Ender IO Base
 - Ender IO Conduits
 - Ender IO Integration with Forestry
 - Ender IO Integration with Tinkers' Construct
 - Ender IO Integration with Tinkers' Construct
 - Ender IO Machines
 - Ender IO Open Computers Conduits
 - Ender IO Powertools
 - Ender IO Refined Storage Conduits
====================== ˠ2/7 ۠=======================
===================== Mods (117) =====================
 - EnderCore
 - EnderStorage
 - Energy Converters
 - Extended Mod Config
 - Extended Renderer
 - Extra Cells 2
 - Extra Utilities 2
 - Forge Microblocks
 - Forge Multipart CBE
 - Galacticraft Core
 - Galacticraft Planets
 - GalaxySpace
 - GeneralLaymansAestheticSpyingScreen
 - GeographiCraft
 - Grue
 - Guide-API
 - Hex Lands
 - ICBM-Classic
====================== ˠ3/7 ۠=======================
===================== Mods (117) =====================
 - Immersive Cables
 - Immersive Engineering
 - Immersive Petroleum
 - Industrial Foregoing
 - IndustrialCraft 2
 - Integration Foregoing
 - Inventory Tweaks
 - Iron Chest
 - JustEnoughIDs
 - LagGoggles
 - MalisisCore
 - MalisisDoors
 - Mantle
 - Mekanism
 - MekanismGenerators
 - MekanismTools
 - Micdoodle8 Core
 - MineColonies
====================== ˠ4/7 ۠=======================
===================== Mods (117) =====================
 - Minecraft Chromium Embedded Framework
 - Minecraft Multipart Plugin
 - MrTJPCore
 - NuclearCraft
 - OMLib
 - Open Modular Passive Defense
 - Open Modular Turrets
 - OpenComputers
 - OpenComputers (Core)
 - Patchouli
 - PortalGun
 - ProjectRed Core
 - ProjectRed Expansion
 - ProjectRed Exploration
 - ProjectRed Fabrication
 - ProjectRed Illumination
 - ProjectRed Integration
 - ProjectRed Relocation
====================== ˠ5/7 ۠=======================
===================== Mods (117) =====================
 - ProjectRed Transmission
 - ProjectRed Transportation
 - Redstone Arsenal
 - Redstone Flux
 - Refined Relocation
 - SG Craft
 - Shadowfacts' Forgelin
 - SpongeForge
 - Structurize
 - Tesla Core Lib
 - Tesla Core Lib Registries
 - The Beneath
 - The Betweenlands
 - The Lost Cities
 - Thermal Cultivation
 - Thermal Dynamics
 - Thermal Expansion
 - Thermal Foundation
====================== ˠ6/7 ۠=======================
===================== Mods (117) =====================
 - Thermal Innovation
 - Torcherino
 - UniDict
 - Vulpes library
 - WanionLib
 - WebDisplays
 - Zombie Awareness
 - iChunUtil
 - projectred-compat
====================== ˠ7/7 ۠=======================

**Issue Description**
This one is easy, it really happens without anything anyone can do about it, it may just so happen that someone joins the server, or at any given random time really, and it crashes with the exception in server tick loop issue, and it is related to something about timing from "co.aikar.timings", but I have not found anything similar on Google yet, hence I come here to hopefully get this fixed soon before I release my Modpack and Server out there. Want to reproduce? Install all these mods and plugins on your server, join the server and see the magic happen randomly, it may or may never happen, which is why it is so unpredictable and not easy to fix.

Server Log: https://gist.github.com/LokeYourLord/2b408a836164052404a2d595ec9eced5
Crash Log: https://gist.github.com/LokeYourLord/75279e5d63a7a4f234e9deb4cc78b77c

**Comment by Aaron1011** [comment]
The offending line appears to be [here](https://github.com/SpongePowered/SpongeCommon/blob/2f73bd1d09f0f930685abfa204f2384afde5c71e/src/main/java/co/aikar/timings/TimingsPls.java#L64). However, this should be impossible, as `TILE_ENTITY_IDS` should never be null.

**Comment by Aaron1011** [comment]
Oh, I see - `co.aikar.timings.TimingsPls` is being loaded from another mod, and not from the SpongeForge jar. We should be relocating the timings code to avoid this kind of conflict.

**Comment by LokeYourC3PH** [comment]
Wait what, another mod is conflicting in trying to take over the timings system if I understood it correctly? Isn't that somehow, well not really possible, considering SpongeForge is specifically designed to run along Forge and not take over unlike, lets say Cauldron or so?

**Comment by LokeYourLord** [comment]
Oops, my mistake, I gave over the wrong Server Log, I will fix this immediately.

**Comment by LokeYourC3PH** [comment]
Please check the Server Log again and then part 2 (RAW) of that Gist, that is the total log file.

**Comment by Aaron1011** [comment]
On second though, it doesn't actually appear that the timings classes are being loaded from another mod. However, I'm still not sure how this NPE is occuring.

**Comment by Aaron1011** [comment]
@LokeYourLord: Can you please re-test on `1.12.2-2768-7.1.6-RC3570`?

**Comment by LokeYourC3PH** [comment]
> 
> 
> @LokeYourLord: Can you please re-test on `1.12.2-2768-7.1.6-RC3570`?

Sure thing, will try, it might take a while though until this happens again, however if nothing happens within the next few days, I will come back to report :)

**Comment by Aaron1011** [comment]
@LokeYourLord: You should actually update to `1.12.2-2768-7.1.6-RC3574` - I've added some extra information, as well as error recovery.

**Comment by LokeYourC3PH** [comment]
> 
> 
> @LokeYourLord: You should actually update to `1.12.2-2768-7.1.6-RC3574` - I've added some extra information, as well as error recovery.

Will do :)

**Comment by Aaron1011** [comment]
Additional debug info is in build `1.12.2-1.12.2-14.23.5.2768-7.1.6-RC3582`

**Comment by LokeYourC3PH** [comment]
As it seems so far, I have not experienced a single crash. I guess we can close this issue for now, and re-open it if necessary. Thanks for the help Aaron1011 :)

**Comment by LokeYourC3PH** [comment]
@Aaron1011 Hey Aaron, I have a question for you: Would you mind personally helping me with a Timing Issue on my server? (I don't mind paying for your time :) ) I have an issue wherein, even though there is enough RAM and CPU power for the server, there is about every 15 seconds a huge stutter, where the server hangs for almost 5 seconds and then continues as normal. Problem is, I used the Sponge Timings report and LagGoggles, none of them came back with any useful information on any of the reports. I cannot for the life of mine find out what is causing it, and so I need a professional programmer to help me (if you can). Thanks for your time even if not :)

**Comment by LokeYourC3PH** [comment]
And by the way, I think you fixed the issue by moving the Timing classes, have not had the same issue again since.

**Comment by Aaron1011** [comment]
@LokeYourLord: I would reccomend making a [Spark profile](https://ore.spongepowered.org/Luck/spark), and posting it to the Sponge discord sever.

**Comment by LokeYourC3PH** [comment]
> 
> 
> @LokeYourLord: I would reccomend making a [Spark profile](https://ore.spongepowered.org/Luck/spark), and posting it to the Sponge discord sever.

Alright, I will do that, but here is the Timings report from the timing profiler I let run over night on my server: https://timings.aikar.co/?id=d357279ce5f94a11a451ea5c60f21a18#timings
