### ISSUE TITLE
netty leak warning

### ISSUE THREAD

**Issue by zhourui123** [SpongePowered/SpongeForge#2616]
**I am currently running**

- SpongeForge version: the latest
- Forge version: 1.12.2-forge1.12.2-14.23.5.2768
- Java version: java8+
- Operating System: win10

- Plugins/Mods:
plugin: spongycord and some plugin diy, some mod diy.

**Issue Description**
```
[10:24:06] [Netty Server IO #2/ERROR] [io.netty.util.ResourceLeakDetector]: LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
WARNING: 1 leak records were discarded because the leak record count is limited to 4. Use system property io.netty.leakDetection.maxRecords to increase the limit.
Recent access records: 5
#5:
        io.netty.buffer.AdvancedLeakAwareByteBuf.readInt(AdvancedLeakAwareByteBuf.java:432)
        net.minecraft.network.PacketBuffer.readInt(PacketBuffer.java:914)
        net.minecraft.network.PacketBuffer.readInteger(PacketBuffer.java:1707)
        flavor.pie.spongycord.SpongyCord$API.lambda$getPlayerCount$7(SpongyCord.java:129)
        flavor.pie.spongycord.SpongyCord$API$ChannelListener.handlePayload(SpongyCord.java:360)
        org.spongepowered.mod.network.SpongeRawChannel.handlePacket(SpongeRawChannel.java:91)
        org.spongepowered.mod.network.SpongeRawDataInboundHandler.channelRead0(SpongeRawDataInboundHandler.java:50)
        org.spongepowered.mod.network.SpongeRawDataInboundHandler.channelRead0(SpongeRawDataInboundHandler.java:36)
        io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        `io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
```

read more: [gist](https://gist.github.com/zhourui123/4bc3a6f9c85ae72d9e687d08da077287)

**Comment by phit** [comment]
@pie-flavor what makes you think this is on Sponge's end?
ref: https://github.com/pie-flavor/SpongyCord/issues/9

**Comment by pie-flavor** [comment]
because I literally do nothing but read the fields in the API order. A Netty leak means that an internal buffer has been garbage collected before its reference counter has zeroed. Without depending on NMS I couldn't cause a Netty leak if I wanted to.

**Comment by Cybermaxke** [comment]
Should be fixed with https://github.com/SpongePowered/SpongeForge/commit/80d253acb5024fa1ec19986f336b027e01cc3e60. Can you retest?

**Comment by zhourui123** [comment]
ok,  I have been update to 1.12.2-2768-7.1.5 and ask you the result after one day.

**Comment by zhourui123** [comment]
Problem still exist at version1.12.2-2768-7.1.5.
```[20:54:53] [main/INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/usr/local/mc_work/lobby/./mods/spongeforge-1.12.2-2768-7.1.5.jar Service=LaunchWrapper Env=SERVER```

```[11:46:28] [Server thread/INFO] [minecraft/DedicatedServer]: aaa joined the game
[11:47:44] [Netty Epoll Server IO #1/ERROR] [io.netty.util.ResourceLeakDetector]: LEAK: ByteBuf.release() was not called before it's garbage-collected. Enable advanced leak reporting to find out where the leak occurred. To enable advanced leak reporting, specify the JVM option '-Dio.netty.leakDetection.level=advanced' or call ResourceLeakDetector.setLevel() See http://netty.io/wiki/reference-counted-objects.html for more information.```

**Comment by phit** [comment]
you need at least 1.12.2-2768-7.1.6-RC3594

**Comment by zhourui123** [comment]
I will test it when stable version release.

**Comment by zhourui123** [comment]
After testing at 1.12.2-2768-7.1.6-RC3594, the problem didn't happen again.
