### ISSUE TITLE
Most Advancements are impossible to complete.

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#2620]
**I am currently running**

- SpongeForge version: 1.12.2-2768-7.1.6-RC3594
- Forge version: 14.23.5.2814
- Java version: java version "1.8.0_191"
- Operating System: Windows 10

- Plugins/Mods:
Minecraft, Minecraft Coder Pack, Sponge, Sponge API, Buycraft, CatClearLag, GriefPrevention, Guardian, LuckPerms, Nucleus, mmcprefix, Precogs.
See the modpack here: https://www.technicpack.net/modpack/one-life-popular-smp.1297373

**Issue Description**
I am not 100% sure if this is a mod affecting this issue. But my guess is SpongeForge, as I have had issues in the past with SF and Advancements in 1.12.2.

The easiest example of this Advancement issue is the `Not Today, Thank You` achievement. Easy, but impossible.

Below you can find a video to what is going on in a practical way.
https://www.youtube.com/watch?v=xkvOsuBenko

Hope this helps you!

A log does not mention anything about giving advancements.

**Comment by ImMorpheus** [comment]
Fixed by https://github.com/SpongePowered/SpongeCommon/commit/198e8ce33c40adb86e79d707e8d58f29a607f1e3
