### ISSUE TITLE
Purchasing items from "Minebay" causes java.lang.Exception: Async entity spawn attempt termination.

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#2621]
**I am currently running**

- SpongeForge version: 1.12.2-2768-7.1.6-RC3594
- Forge version: 14.23.5.2814
- Java version: 191
- Operating System: Windows 10

- Plugins/Mods: Minecraft, Minecraft Coder Pack, Sponge, Sponge API, Buycraft, CatClearLag, GriefPrevention, Guardian, LuckPerms, Nucleus, mmcprefix, Precogs.
  See the modpack here: https://www.technicpack.net/modpack/one-life-popular-smp.1297373

**Issue Description**
Using the Crayfish Furniture Mod v6.2.0 (latest) and SpongeForge (latest) causes an ASync Entity Spawn issue.

Simply, to reproduce, place down a computer from CFM and well, just try purchase an item!

Upon purchasing an item from the Computer (such as terracotta) will return an immediate kick with the message: `A fatal error has occured, this connection is terminated`

Below is a crash log with the message by Sponge and what is going on.
If you need any further information let me know!

https://pastebin.com/ZCULfW1x

**Comment by XakepSDK** [comment]
Not sponge issue, report Minebay mod author.

**Comment by ImMorpheus** [comment]
What @XakepSDK is correct.

MrCrayfishFurnitureMod is spawning an entity off the "main" server thread.

https://github.com/MrCrayfish/MrCrayfishFurnitureMod/blob/master/src/main/java/com/mrcrayfish/furniture/network/message/MessageMineBayBuy.java#L71

**Comment by Aaron1011** [comment]
As a temporary workaround, you can add `cfm` to the `broken-network-handler-mods`section of your `global.conf`, and set `broken-mod=true` in your `modules`section of `global.conf`

**Comment by Aaron1011** [comment]
Issue opened: https://github.com/MrCrayfish/MrCrayfishFurnitureMod/issues/394

**Comment by ghost** [comment]
Thank you very much @Aaron1011 and @XakepSDK I just assumed it was Sponge due to the error provided.
