### ISSUE TITLE
Cancelling InteractBlockEvent Pams Harvestcraft not working

### ISSUE THREAD

**Issue by sandtechnology** [SpongePowered/SpongeForge#2623]
**I am currently running**
- SpongeForge version: 1.12.2-2768-7.1.5(latest stable version)
- Forge version: 14.23.5.2811
- Java version: 8
- Operating System:Windows 10

- Plugins/Mods:Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI,Sponge,Pam's HarvestCraft, SpongeForge

**Issue Description**
When I cancelled the InteractBlockEvent,the code of Pam 's Harvestcraft still running(dropping item):
![gif](https://user-images.githubusercontent.com/20417547/53297179-4014ee80-3855-11e9-9a74-4e4428f0be67.gif)

[`Pam 's Harvestcraft Right-Click Harvesting Code`](https://github.com/MatrexsVigil/harvestcraft/blob/master/src/main/java/com/pam/harvestcraft/addons/RightClickHarvesting.java)

Listener code:
```
    @Listener(order = Order.FIRST,beforeModifications = true)
    public void onInteractBlock(InteractBlockEvent event, @First Player player) {
        player.sendMessage(Text.of("Cancelled InteractBlockEvent ,Block:"+event.getTargetBlock()));
        event.setCancelled(true);
    
```

**Comment by ImMorpheus** [comment]
Fixed by https://github.com/SpongePowered/SpongeForge/commit/051339ada12c1aed9b47c4c78d0d0308c178fdd1
