### ISSUE TITLE
Netty Broken Pipe

### ISSUE THREAD

**Issue by HeyWinkeyFace** [SpongePowered/SpongeForge#2625]
- SpongeForge version: 1.12.2-2768-7.1.6-RC3596
- Forge version: 1.12.2-14.23.5.2768
- Java version: Java 8
- Operating System: CentOS 7

**Plugins/Mods:**
- Minecraft
- Minecraft Coder Pack
- SpongeAPI
- Sponge
- ActiveTime
- AdamantineShield
- AurionsVoteListener
- CatClearLag
- Daily Rewards
- EconomyLite
- Enjin Minecraft Plugin
- GTS
- GTS Reforged Bridge
- GriefPrevention
- Impactor API
- LuckPerms
- NuVotifier
- Nucleus
- PixelGenocide
- PixelHunt
- PixelMoney
- PixelmonBroadcasts
- PixelmonEconomyBridge
- PlaceholderAPI
- PokeTeams
- Pokedex Rewards
- SafeTrade
- TabManager
- TeslaCore
- TeslaCrate
- TeslaLibs
- TriviaQuest
- VirtualTool

**Issue Description**
My server is set up to automatically restart every 6 hours.
Sometimes around hours 2-4 following a restart (on average) all of the sudden the server becomes incredibly laggy but only in specific areas. Block lag is usually unaffected, chat is usually responsive, commands however have a second or two delay. Eventually the lag progresses to blocks and chat and the server becomes unplayable. The only thing that I've been doing to fix it is a server restart. Following a restart everything is ok.

You'll see the error at the bottom of my latest.log, it won't be hard to find.

**Server Log**
https://gist.github.com/HeyWinkeyFace/c967c9b7ac8c78a45ec9b229ae5e83fe

Updated to latest build, after a couple of hours a similar error came up.
**Server Log #2**
https://gist.github.com/HeyWinkeyFace/bca9ca641ebdb81a199f909dd0e0c273

**Comment by phit** [comment]
~~netty issue, you can try updating netty manually. however we will not support doing so~~

try the latest build once it's out

**Comment by Cybermaxke** [comment]
Is related to https://bugs.mojang.com/browse/MC-118372 ?

**Comment by HeyWinkeyFace** [comment]
Updated to latest, encountered it still!

Latest.log
https://gist.github.com/HeyWinkeyFace/bca9ca641ebdb81a199f909dd0e0c273

**Comment by HeyWinkeyFace** [comment]
Update: I enabled *use-native-transport=false* in server.properties, the error persisted here's the information on that.

Crash.log as a result of the Netty Pipe Error: https://gist.github.com/HeyWinkeyFace/84be6e250ddbab677c09fc42154c69a7


Latest.log encountering Netty Error:
https://gist.github.com/HeyWinkeyFace/87d94a4aa204606859f96a81d94ec57b

Debug.log encountering Netty Error:
https://gist.github.com/HeyWinkeyFace/248ec89bcbeb53b5ff8b33d5c6eb18e3

**Comment by EscolarProgramming** [comment]
I have the same issue. I'm running on SF 1.12.2-2768-RC3616 and Forge 2809. Every day at 0 o'clock all players on the server get kicked from the server in the lobby. 
It happened after updating Forge from 2768 and SF from 2768-RC3594.
The error in the console:
https://gist.github.com/EscolarProgramming/6df2c78645d2377cf7954e35e815d51f

**Comment by phit** [comment]
just do this https://gist.github.com/phit/be5b69b76217bb8bab7b1cd752d4c39e

i doubt this will be ever fixable on our end, the netty version shipped with 1.12.2 is just broken

**Comment by EscolarProgramming** [comment]
Thanks, I will try it and report later

**Comment by HeyWinkeyFace** [comment]
> just do this https://gist.github.com/phit/be5b69b76217bb8bab7b1cd752d4c39e
> 
> i doubt this will be ever fixable on our end, the netty version shipped with 1.12.2 is just broken

I did as phit requested and things were fine but now the lag and netty error have returned from the grave!

Latest.log: https://gist.github.com/HeyWinkeyFace/268af4223d02f62c40b6d26d1ee2e259
Debug.log: https://gist.github.com/HeyWinkeyFace/93af9057281771555d20952474cb5b1f

**Comment by EscolarProgramming** [comment]
Hello,
a little update: It worked for 6 days, but on saturday night (03/16/19 00:01) it kicked all players again.
https://gist.github.com/EscolarProgramming/bf426d2ae0bed9e127fbae58c4a22cce

**Comment by HeyWinkeyFace** [comment]
> Hello,
> a little update: It worked for 6 days, but on saturday night (03/16/19 00:01) it kicked all players again.
> https://gist.github.com/EscolarProgramming/bf426d2ae0bed9e127fbae58c4a22cce

Same here, updated netty and the issue came back after a number of days.

Quote from bloodshot "Those experiencing netty crashes, replace netty in minecraft jar with latest. also NuVotifier ships with netty, build it wiithout shading netty, this way it just uses the one in minecraft server, that should solve most issues."

I have no clue how to re-build nuvotifer without netty.

**Comment by Cybermaxke** [comment]
@HeyWinkeyFace remove the `io/netty` package from the nuvotifier jar

**Comment by EscolarProgramming** [comment]
In addition, we don't use NuVotifier. So it could not be the main problem

**Comment by HeyWinkeyFace** [comment]
> @HeyWinkeyFace remove the `io/netty` package from the nuvotifier jar

Where's it located in the jar?
nuvotifier.jar/META-INF/maven/ ?

Just delete io.netty?

**Comment by EscolarProgramming** [comment]
Netty is located in `com.vexsoftware.votifier.netty` so I don't know it it will still work if you remove it, because it's deep-nested and not in an own package. But you can try it.

But it will not solve the problem, because I have the problem too and I don't use NuVotifier.

**Comment by Cybermaxke** [comment]
If it's relocated it shouldn't affect the netty version packed with minecraft. So nuvotifier can't be the problem for these disconnections. Removing the package will break the plugin in this case.

**Comment by HeyWinkeyFace** [comment]
So now I shouldn't remove netty from nuvotifier?

**Comment by Cybermaxke** [comment]
I didn't think about relocation, I assumed that it would be the same package which could cause a conflict, which ins't the case.

**Comment by dualspiral** [comment]
@HeyWinkeyFace The answer is no, do not remove netty from nuvotifier.

**Comment by HeyWinkeyFace** [comment]
If I just use a nuvotifier substitute should the problem be solved?

**Comment by HeyWinkeyFace** [comment]
Here with my weekly update.

I disabled nuvotifier.jar and we still had the crash, here's the info:

crash-server.txt: https://gist.github.com/HeyWinkeyFace/0a590d754bbc9f188e8d7df9d34438b2
latest.log: https://gist.github.com/HeyWinkeyFace/8e7d9e0f66fe389dc9246c8af160bf46

**Comment by HeyWinkeyFace** [comment]
@EscolarProgramming possible fix, are you using swap memory?

We've set it to never use swap memory and are currently testing, might be a possible fix.

**Comment by HeyWinkeyFace** [comment]
Disabling the use of swap memory has been confirmed as a fix for me.
