### ISSUE TITLE
Vending Block Phase Tracker Error

### ISSUE THREAD

**Issue by kencinder** [SpongePowered/SpongeForge#2629]
**I am currently running**

- SpongeForge version: 1.12.2-2768-7.1.6-RC3611
- Forge version: 1.12.2-14.23.5.2768
- Java version: OpenJDK 64-Bit Server VM, version 1.8.0_181
- Operating System: Debian 9.6

- Plugins: BetterChunkLoader, CommandSigns Reloaded, CommandsDispatcher, GriefPrevention, Holograms, LuckPerms, MMCReboot, MultiChatSponge, Nucleus, SleepVote, Socket4MC, spark

- Mods: Aether Legacy, AppleSkin, Applied Energistics 2, Aroma1997's Dimensional World, Aroma1997Core, BTFU, Baubles, Better Railroads, BetterChunkLoader Forge Lib, BiblioCraft, Brandon's Core, Chameleon, Chisel, CoFH Core, CoFH World, CodeChicken Lib, Compact Drawers, CosmeticArmorReworked, CosmeticArmorReworked Integration for TombManyGraves2, CreativeCore, CreativeCoreDummy, Decocraft, Draconic Evolution, EnderStorage, Extra Utilities 2, FoamFix, FoamFixCore, Foamflower, Immersive Engineering, Industrial Foregoing, Industrial Wires, Integration Foregoing, Iron Chest, Just Enough Items, LagGoggles, LittleTiles, LittleTilesCore, MCMultiPart, Mantle, McJtyLib, Mekanism, NoMoreRecipeConflict, OpenComputers, OpenComputers (Core), RFTools, RandomPatches, Redstone Arsenal, Redstone Flux, Sampling Performance Profiler, Shadowfacts' Forgelin, Simply Jetpacks 2, SpongeForge, Storage Drawers, Tesla Core Lib, Tesla Core Lib Registries, Thaumcraft, The Lost Cities, The Twilight Forest, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Treecapitator, Tropicraft, Vending, WorldEdit, XNet, bspkrsCore

**Issue Description**

Errors in console/log when players access a Vending Block. The mod seems to work fine, but spams the log with phase tracker errors.
Dev states this is Sponge's fault here - https://github.com/kamildanak/VendingBlock/issues/37#issuecomment-415990995

Complete error from debug.log -> https://gist.github.com/kencinder/0eb9bbc646aa4e59730dc058649c16eb

**Comment by gabizou** [comment]
@Faithcaio this is mostly to do with inventories, care to take a look at how to fix?

**Comment by Faithcaio** [comment]
The mod inventory has more slots than are displayed in the GUI.
When creating our `DelegatingLens` we blindly iterate over all slots of the base inventory.
https://github.com/SpongePowered/SpongeCommon/blob/stable-7/src/main/java/org/spongepowered/common/item/inventory/lens/impl/DelegatingLens.java#L44
Instead we should use the slotList we already have in `ContainerUtil#generateAdapterLens` which would be the slots added in the mod:
https://github.com/kamildanak/VendingBlock/blob/master/src/main/java/info/jbcs/minecraft/vending/inventory/ContainerVendingMachine.java#L17

This problem would also happen for any other mod that only shows parts of an inventory in its gui.

**Comment by Faithcaio** [comment]
@kencinder should be fixed with that ^
