### ISSUE TITLE
Attempted to call MapStorage#getOrLoadData from off the main thread!

### ISSUE THREAD

**Issue by bookerthegeek** [SpongePowered/SpongeForge#2632]
**I am currently running**
- SpongeForge version: 1.12.2-2768-7.1.5
- Forge version: 1.12.2-14.23.5.2807-universal.jar
- Java version: 1.8.0_11
- Operating System: Windows 10

- [Plugins/Mods](https://gist.github.com/bookerthegeek/a0f0b398fe9563af2a6e6ffc3cb87444)

**Issue Description**
Cross Posting as this is a Sponge / Mod  interaation.
 - https://github.com/BuildCraft/BuildCraft/issues/4374
 - [Copy Of Error](https://gist.github.com/bookerthegeek/1e163ab7c9a38a7d40c0af75ce8f99af)
 - [Full Log](https://gist.github.com/bookerthegeek/c49c6a6e3b53eb47681b39229388919e)

**Comment by Grauldon** [comment]
Sponge requires Java 8 update 20 or higher to run. You may want to read [Creating a Server](https://docs.spongepowered.org/stable/en/server/index.html) in the SpongeDocs to verify your setup.

**Comment by bookerthegeek** [comment]
Damn, hold on while I update that.
