### ISSUE TITLE
Workbench result slot don't synced (mods)

### ISSUE THREAD

**Issue by yaroslav4167** [SpongePowered/SpongeForge#2636]
**I am currently running**

- SpongeForge version: 1.12.2-2768-7.1.6-RC3618
- Forge version: forge-1.12.2-14.23.5.2814-universal.jar
- Java version: 8
- Operating System: Linux

- Mods: TConstruct

**Issue Description**
[Reproduce](https://www.youtube.com/watch?v=cV0O8n70V8Q)
I'm tested this bug with mods: TConstruct, RealBench (Bug works)
Bug also work in singleplayer. 
I wrote to the developers about this bug a few months ago. But unfortunately none of them have yet answered.
Maybe it can be corrected at the level of sponge?

**Comment by Faithcaio** [comment]
Sounds like it happens without Sponge too.
https://github.com/SlimeKnights/TinkersConstruct/issues/3714
