### ISSUE TITLE
Furnace Smelting Issue

### ISSUE THREAD

**Issue by IBGnova** [SpongePowered/SpongeForge#2639]
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2768-7.1.6-RC3619
- Forge version: 14.23.5.2814
- Java version: Unknown (Rented Server)
- Operating System: Linux (Assuming)

- Plugins/Mods: 
* PixelmonReforged 7.0.3
* Nucleus 1.9.1
* Grief Prevention 4.3.0.682
* LuckPerms 4.3.101

**Issue Description**
When any items are place in the furnace, and it starts smelting, the player is then kicked out of the GUI and the items in the furnace are tossed on the ground. This issue was resolved by reverting back to the recommended version of sponge forge, so I'm assuming it's related to Sponge itself. 

Reverting back to build with issue soon, I will upload a full log when I have done so.

**Comment by IBGnova** [comment]
Server log: https://gist.github.com/IBGnova/5f60bdc716b54abb53c9f938c4d4c583

**Comment by SSKirillSS** [comment]
Also faced with this. I did not find anything in the server log.

**Comment by ghost** [comment]
This issue has occurred for me too on my server. Furnaces open fine when its a normal furnace. But when it turns into a burning furnace (by smelting) it immediately spits items out and the furnace is no longer accessible. I have reverted to **1.12.2-2768-7.1.6-RC3616** (which appears to be the most stable latest build)
