### ISSUE TITLE
Server will not start after disabling async-lighting updates. 

### ISSUE THREAD

**Issue by nzminecraftDOTcom** [SpongePowered/SpongeForge#2640]
**I am currently running**

- SpongeForge version: 1.12.2-2768-7.1.5-RC3515
- Forge version: 2808
- Java version: V8 update 201 Build 1.8.0_201-b09
- Operating System: Win server 08 r2 enterprise

- Plugins/Mods:
Mods: https://pastebin.com/sDv9Wfcq
Plugins: https://pastebin.com/8rWXSiyg

**Issue Description**
Modpack: Project Ozone 3
Was trying to find a solution to Glaticraft causing the server to crash when generating chunk packets for particular chunks whenever Jupiter was visited. The error started with this line: java.lang.RuntimeException: Exception creating chunk packet for chunk at '32 465'!
(Don't have any reports from this)
Looked it up and there was a suggestion to disable assync lighting.
Did that.
Now the server only starts, one player logs in then it decides to crash. Report below.
Reverting back to how it was originally has not stopped the crashes.
Server starts fine without sponge installed. 

https://gist.github.com/nzminecraftDOTcom/6ed5fddb55f9045c5ef33ffafbbd8e0c

**Comment by Zidane** [comment]
Can you try this again on latest SF? I can't reproduce but you were using quite a few mods..

**Comment by nzminecraftDOTcom** [comment]
Nope I can not, the server has changed so much in the time that this is now invalid and I can not reproduce it.
