### ISSUE TITLE
Entity#transferToWorld nonconforming description

### ISSUE THREAD

**Issue by zhourui123** [SpongePowered/SpongeForge#2643]
**I am currently running**

SpongeForge version: 1.12.2-2768-7.1.4
Forge version: 1.12.2-2768
Java version: java 8
Operating System: win 10

**Issue Description**
Entity#transferToWorld(String worldName, Vector3d position)  nonconforming description.
The description said allow world does not have to be loaded, but actually if the world is unloaded, transfer will return false;

**Comment by gabizou** [comment]
No where in the [javadoc does it say the world does not have to be loaded](https://github.com/SpongePowered/SpongeAPI/blob/stable-7/src/main/java/org/spongepowered/api/entity/Entity.java#L298-L309). It says that the method returns false if the teleportation failed, whether it be by a cancelled event, or not possible (in this case, the world is unloaded).
