### ISSUE TITLE
EventContextkeys value cache

### ISSUE THREAD

**Issue by zhourui123** [SpongePowered/SpongeForge#2645]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2768-7.1.5
- Forge version: 1.12.2 2768
- Java version: 1.8+
- Operating System: win10

**Issue Description**
If i use 
`Optional<ItemStackSnapshot>opItem = event.getContext().get(EventContextKeys.USED_ITEM);`
on DamageEntityEvent ,even player damaged from fail or fire, the opItem still return item that last be attacked, so i think it's wrong cache. And i have some suggestion, if move EventContextsKeys to event#getUsedItem, it's more friendly for developer.

**Comment by gabizou** [comment]
> If i use
> `Optional<ItemStackSnapshot>opItem = event.getContext().get(EventContextKeys.USED_ITEM);`
> on DamageEntityEvent ,even player damaged from fail or fire, the opItem still return item that last be attacked,

Need some minimum plugin listener code and example to reproduce this issue. From what I'm seeing in the implementation, the used item context is always provided for players attacking and players using items.
> And i have some suggestion, if move EventContextsKeys to event#getUsedItem, it's more friendly for developer.

Not all AttackEntityevents have sources from Entities that have items. Therefor, they cannot be defacto provided (reason why they're in context).

**Comment by zhourui123** [comment]
I copy minimum plugin listener code to my test plugin, the caching problem did not recur, i think i should recheck my code. thank you ~
