### ISSUE TITLE
[server crash]Exception ticking world

### ISSUE THREAD

**Issue by zhourui123** [SpongePowered/SpongeForge#2648]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2768-7.1.5
- Forge version: 1.12.2 2768
- Java version: 1.8+
- Operating System: win10

- Plugins/Mods:
mfbl_common_plugin.jar (spongeforge plugin)
holograms-3.1.5.jar (spongeforge plugin)
mfbl-1.0.jar (forge mod)

**Issue Description**
java.lang.NullPointerException: Exception ticking world at net.minecraft.server.management.PlayerChunkMapEntry.func_187272_b(PlayerChunkMapEntry.java:161)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:165)
	

more info:
https://gist.github.com/zhourui123/7d908e74649681cebd474947514ffa97

**Comment by phit** [comment]
https://github.com/SpongePowered/SpongeForge/issues/2622
