### ISSUE TITLE
ItemStackSnapshot.NONE having a null ItemType

### ISSUE THREAD

**Issue by MobKiller** [SpongePowered/SpongeForge#2649]
**I am currently running**

- SpongeForge version: 3627
- Forge version: 2809

- Plugins/Mods
:spongeapi, sponge, spongeforge, agp, autobroadcaster, carrotshop, catclearlag, cmdbuilder, cmdcontrol, commandsigns, daycare, dropparty, pixelmoneconomybridge, economylite, elrolian_backpacks, enjin-minecraft-plugin, evenmorepixelmoncommands, fastasyncworldedit, worldedit, griefprevention, gts_reforged, gts, guistatssponge, holograms, impactor, legendaryplus, luckperms, magibridge, mmcreboot, mobdrop, nucleus, nultraditto, ontimelogger, pixelextras, pixelgenocide, pixelhunt, pixelmon-wiki-gui, pixelmonbroadcasts, pixelmoney, pixelmonplaceholders, placeholderapi, pokedexrewards, pokedisguisemod, pokedisguise, pokefreaksutils, pokekibble, pokestop, poketeams, randomiv, rankup, redprotect, nuvotifier, seriousvote, tabmodifier, teslacrate, teslalibs, teslacore, tournaments, trainercommands, triviaquest, virtualchest, voxelsniper, wondertrad

**Issue Description**
so im using adamtine shield i removed it now cause it was spamming this error constantly and i had no idea why the plugin worked just constantly spammed this

https://gist.github.com/MobKiller/f5159f26e6a1f39008405ae0d79e1654

**Comment by ImMorpheus** [comment]
https://github.com/Karanum/AdamantineShield/issues/45

**Comment by gabizou** [comment]
This is actually due to ItemStackSnapshot.NONE having a null ItemType. Needs to be fixed in SpongeCommon.
