### ISSUE TITLE
ClassCastException: IMixinWorldServer

### ISSUE THREAD

**Issue by LokeYourC3PH** [SpongePowered/SpongeForge#2650]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2768-7.1.6-RC3627
- Forge version: 14.23.5.2811
- Java version: 1.8+ (Server side)
- OS: Linux (VPS)

- Plugins/Mods:
Lower bottom of this crashlog: https://pastebin.com/gLBzDm1H

**Issue Description**
Server crashes on startup after updating to the latest SpongeForge version, doesn't seem to be a mod conflict that I know about, I removed 3 mods but updated quite a few, I removed "Better Records, Immersive Railroading and Drawbridges". However I am not sure if that is caused by removing any of these.

Log:
https://pastebin.com/gLBzDm1H

**Comment by ImMorpheus** [comment]
Can you post your `debug.log` ?

**Comment by LokeYourC3PH** [comment]
Here the full latest.log: https://gist.github.com/ImMorpheus/19ae77d07a9b2d339ff9ba036995d1fe

**Comment by LokeYourC3PH** [comment]
Here the hopefully latest debug.log: https://mega.nz/#!5xkxnIbb!0Ew_3Ana7r-2hFwuIUWAlhXGGD-K-B6OOLpWbWczuk4

**Comment by LokeYourC3PH** [comment]
The issue was caused by LagGoggles as the Discord Server guys found out, thanks guys! Issue solved.
