### ISSUE TITLE
server crash when use veloctity proxy

### ISSUE THREAD

**Issue by zhourui123** [SpongePowered/SpongeForge#2651]
**I am currently running**

- SpongeForge version:  spongeforge-1.12.2-2768-7.1.5
- Forge version: 1.12.2 2768
- Java version: 1.8+
- Operating System: centos

- Plugins/Mods:
Velocity proxy, spongycord.jar, holograms,  someForgeModDiy(both side), someSpongePluginDiy

**Issue Description**
I'm submitted issue at  velocity:  https://github.com/VelocityPowered/Velocity/issues/183
Too much NPE and more easily crash when use velocity proxy, but i can't figure out it's cause by spongeforge  or velocity, So, I hope to submit the issue for you to see if there is any way to solve it cooperatively.
see log:
https://gist.github.com/zhourui123/d372e2dff1fee3ffe816826d9373d8ca

**Comment by phit** [comment]
this has been fixed on velocitys end
