### ISSUE TITLE
Neighbor redstone issue

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/SpongeForge#2653]
**I am currently running**

    Minecraft: 1.12.2
    SpongeAPI: 7.1.0-ff2baadc
    Sponge: 1.12.2-7.1.6-SNAPSHOT
    SpongeForge: 1.12.2-2768-7.1.6-RC3624
    Minecraft Forge: 14.23.5.2815

- Plugins/Mods: https://gist.github.com/XakepSDK/ce738ae6fd4c51d38123168dd682e675

**Issue Description**
1. Set time to day
2. Place redstone lamp
3. Place daylight sensor on top of redstone lamp
4. Right click on redstone lamp
5. Lamp doesn't switch off

**Comment by ktole1999** [comment]
if you remove sponge does it work?

**Comment by XakepSDK** [comment]
Yes

**Comment by XakepSDK** [comment]
Works fine with 3616
