### ISSUE TITLE
Sponge process runaway with PhaseTracker when using MovingLightSource

### ISSUE THREAD

**Issue by ianc1215** [SpongePowered/SpongeForge#2654]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2768-7.1.6-RC3628
- Forge version: forge-1.12.2-14.23.5.2768-installer
- Java version: jdk 1.8.0_201 (Oracle Java) No OpenJDK in use.
- Operating System: Windows 10 Pro 64-bit (Client), Fedora 29 (Linux 4.20.16) (Server)

- Plugins/Mods: Sponge does not allow me to run any commands. It doesn't exactly "crash" but it never returns a prompt for me to execute a command. It just keep filling the console with error messages.

**Issue Description**
The occurs at the world initialization on the server side. I have not tested the issue on a client running a client-side single-player world, only a multi-player server world.

Important things to note:
I am running FoamFix in "Anarchy Mod" (CoreMod enabled). I have tested the issue with the CoreMod functionality disabled. There was no change in the issue, still log spam indicating the same error. Besides removing each mod from the system one at a time I am not really sure what more information I could provide. The attached log file has much more information.

[2019-03-21-2.log.gz](https://github.com/SpongePowered/SpongeForge/files/2994182/2019-03-21-2.log.gz)

**Comment by ianc1215** [comment]
I think I have found a workaround for the meantime which is to disable the tracking behavior for MovingLightSource in `tracker.conf`.

```
movinglightsource {
                # Set to true to perform block bulk capturing during block ticks. (Default: true)
                block-bulk-capture {
                    movinglightsource=false
                    "movinglightsource_11"=true
                    "movinglightsource_12"=true
                    "movinglightsource_13"=true
                    "movinglightsource_14"=true
                    "movinglightsource_15"=true
                    "movinglightsource_7"=true
                    "movinglightsource_9"=true
                }
                # Set to true to create and fire block events during block ticks. (Default: true)
                block-event-creation {
                    movinglightsource=false
                    "movinglightsource_11"=true
                    "movinglightsource_12"=true
                    "movinglightsource_13"=true
                    "movinglightsource_14"=true
                    "movinglightsource_15"=true
                    "movinglightsource_7"=true
                    "movinglightsource_9"=true
                }
                # If 'false', all tracking for this mod will be ignored.
                enabled=true
                # Set to true to create and fire entity events during block ticks. (Default: true)
                entity-block-creation {
                    movinglightsource=false
                    "movinglightsource_11"=true
                    "movinglightsource_12"=true
                    "movinglightsource_13"=true
                    "movinglightsource_14"=true
                    "movinglightsource_15"=true
                    "movinglightsource_7"=true
                    "movinglightsource_9"=true
                }
                # Set to true to perform entity bulk capturing during block ticks. (Default: true)
                entity-bulk-capture {
                    movinglightsource=false
                    "movinglightsource_11"=true
                    "movinglightsource_12"=true
                    "movinglightsource_13"=true
                    "movinglightsource_14"=true
                    "movinglightsource_15"=true
                    "movinglightsource_7"=true
                    "movinglightsource_9"=true
                }
            }
```

Doing this at least allows the server to complete the startup process and remain at a prompt.

**Comment by gabizou** [comment]
Try reverting to 7.1.6-RC3616 for now. Will have to check once https://github.com/SpongePowered/SpongeCommon/pull/2219 is merged.

Also, what mods are required for this to occur?

**Comment by ianc1215** [comment]
That part I am having trouble pinning down. I tried spinning up a separate server with just Forge, Sponge, FoamFix, and MovingLightSource and it appeared to be stable. But if I run the entire pile of mods loaded up the error would occur each time requiring me to kill the server process. With that said the exact "brew" that is making the issue occur is going to take me much longer to figure out since the only way I can think to do so is pop in mod after mod then restart the server.

The best I have for now is this list of mods which I pulled from the server.
[mods_on_server.txt](https://github.com/SpongePowered/SpongeForge/files/2994944/mods_on_server.txt)

**Comment by gabizou** [comment]
Instead of doing one by one, you could do a "halving" disable/enable until the appropriate brew is found. Once you've found the brew, post and we'll be able to investigate the interactions. But in the mean time, I'll be building a jar of my branch based on SpongePowered/SpongeCommon#2219 since there's quite a bit of changes that almost guarantees a lot of fixes with the new tracker merged in 3618+

**Comment by gabizou** [comment]
Can you re-test with the following jar?

https://www.mediafire.com/file/9o40kii7x9drz1z/spongeforge-1.12.2-2768-7.1.6-RC0.jar

**Comment by gabizou** [comment]
Can you re-test on latest (7.1.6-RC3632)?

**Comment by ianc1215** [comment]
Sorry for the delay. Sure thing let me test this out and I will let you know.

**Comment by ianc1215** [comment]
So far so good on the testing. I changed out the JAR on my server and restarted it. The server did not produce the same error it did when I reported the ticket. I had a player change out the client-side JAR and test on the server. He was able to connect and walk around with a torch in his hand which uses MovingLightSource. He did not notice any immediate issues. I will continue to check on this for a day or so and report if any issues arise.

**Comment by ianc1215** [comment]
I have found another issue that is slightly related to original ticket. I have basically trade one issue for another. Now instead there being issue with the PhaseTracker freaking out about MovingLightSources now I am getting errors related to BlockTickPhase when I mine ores on the server. At least that is how it was reported to me.

As you can see towards the bottom of the file as soon as the Sponge issues started the server began to lag really bad. I was loosing 100s of the ticks to the issue with the BlockTickPhase issues.

[2019-03-28-2.log.gz](https://github.com/SpongePowered/SpongeForge/files/3023690/2019-03-28-2.log.gz)

**Comment by gabizou** [comment]
The original issue is fixed, the log you provided relates to some odd block tick interaction with fire spread. Re-test with latest (now RC-3634) as I fixed the NPE that is causing that log.
