### ISSUE TITLE
FTB Utilities mod works wrongly in the sponge server

### ISSUE THREAD

**Issue by dablackM** [SpongePowered/SpongeForge#2655]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2768-7.1.5
- Forge version: 1.12.2-forge1.12.2-14.23.5.2810
- Java version: 1.8.0_201
- Operating System:Windows Server 2016

- Plugins/Mods:FTB Utilities

**Issue Description**
I use the FTB Utilities mod in my server but when I modify the ranks.txt which is the feature of the mod ,it doesn't work. Is that possible to make this mod work well with the sponge

**Comment by phit** [comment]
no idea what doesnt work from this ticket alone, provide some reproduction and we will reopen this issue
