### ISSUE TITLE
Include Forge capabilities when serializing an ItemStack with ItemStack#toContainer

### ISSUE THREAD

**Issue by BrainStone** [SpongePowered/SpongeForge#2656]
Currently the `ItemStack#toContainer` method does not respect Forge capabilities. They naturally also need to be included too when deserializing the resulting `DataView`/`DataContainer` back to an `ItemStack`.

One item that can be tested with fairly easily is the flower bag from Botania. As that stores its contents in a Forge capability.

**Comment by BrainStone** [comment]
@gabizou, it seems like the serialization works, but not the deserialization when building an ItemStack from the respective DataView.
Should I open a new issue for it?

**Comment by bluelightning32** [comment]
Ping
