### ISSUE TITLE
Unable to resize Buffer for SPackeetChunkData

### ISSUE THREAD

**Issue by Jabulba** [SpongePowered/SpongeForge#2657]
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2768-7.1.5
- Forge version: forge-1.12.2-14.23.5.2768-universal
- Java version: 1.8 201 64bit
- Operating System: Windows 10 Pro 64bit

- Plugins (8): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, LuckPerms, Nucleus, ProjectCore, ProjectPortals
- Mods (113): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AE2 Stuff, Akashic Tome, AppleSkin, Applied Energistics 2, Aroma1997Core, AutoRegLib, BD Lib, Bad Wither No Cookie! Reloaded, Bed Patch, Better Builder's Wands, BiblioCraft, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Biomes O' Plenty, Bookworm API, Chisel, CoFH Core, CoFH World, CodeChicken Lib, Cooking for Blockheads, Diet Hopper, Doomlike Dungeons, DrZhark's CustomSpawner, DrZhark's Mo'Creatures Mod, Dynmap, DynmapBlockScan, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, Ender IO Zoo, Ender IO endergy, EnderCore, EnderStorage, Extra Cells 2, Extra Utilities 2, Extreme Reactors, FTB Utilities, FTBLib, Farming for Blockheads, Flat Colored Blocks, Forestry, Forge Microblocks, Forge Multipart CBE, Funky Locomotion, GenDustry, Gendustry JEI Addon, GeographiCraft, Harvest, Immersive Engineering, Immersive Petroleum, Immersive Tech, IndustrialCraft 2, Inventory Tweaks, JEI Bees, JourneyMap, Just Enough Items, MagicBees, Mantle, Minecraft Multipart Plugin, Morph-o-Tool, Morpheus, Natura, NetherPortalFix, OpenBlocks, OpenComputers, OpenComputers (Core), OpenModsLib, OpenModsLib Core, Pam's HarvestCraft, Pretty Beaches, Quick Leaf Decay, Redstone Flux, Rex's Additional Structures, Shadowfacts' Forgelin, Signals, Simply Jetpacks 2, SpongeForge, TATW, TOP Addons, The One Probe, The Twilight Forest, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Tinker's JEI, Tinkers' Construct, UniDict, WanionLib, Wings, Horns, and Hooves, the Ultimate Unicorn Mod!, Wolf Armor and Storage, WorldEdit, Zero CORE, Zoo and Wild Animals Mod: Rebuilt, careerbees

**Issue Description**
Server crashed twice with this error after logging in and running fast enought to load chunks(spectator max speed).
I generated a new world and had just logged in to look at it in spectator mode.
BIOMESOP was the generator with GeographiCraft modifications,
I can provide the configs if needed.

Crash: https://gist.github.com/Jabulba/744ff5542870555ddfb6707756937da8
Logs: https://gist.github.com/Jabulba/32e5d190de418363b954d45cd68686ad/revisions
Debug logs (was to big for gist): https://drive.google.com/open?id=1WDKXKMEngEQwpV5qYKkkyhV7k3GPvxVg

**Comment by Zidane** [comment]
@Cybermaxke

**Comment by Cybermaxke** [comment]
You should use at least 1.12.2-2768-7.1.6-RC3626 for this fix, but there are currently some other issues with the latest builds. Disabling async lighting will temporarily resolve this issue.
Once https://github.com/SpongePowered/SpongeCommon/pull/2219 is merged, you'll be able to use the latest builds and re-enable async lighting.

**Comment by Jabulba** [comment]
I see, we updated to the latest RC and haven't crashed for a few hours! If it does crash again I'll also disable the async lighting.

Thanks for the tips!
