### ISSUE TITLE
Crashing while starting

### ISSUE THREAD

**Issue by Spontini** [SpongePowered/SpongeForge#2659]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2768-7.1.6-RC3616.jar
- Forge version: forge-1.12.2-14.23.5.2795-universal.jar
- Java version: Java 8 Update 201 64bit
- Operating System: Ubuntu 18.04

- Plugins/Mods: Nucleus

**Issue Description**

Server doesn't start up with Sponge installed, there is the lastest.log and debug.log

lastest.log=https://drive.google.com/file/d/1dRe0bs18G2JGLpKtHdi99WrpxB0OWxop/view?usp=sharing
debug.log=https://drive.google.com/file/d/1-ZvBIL6fezmqsCcA2mjPpBbrTUujwNau/view?usp=sharing

I upload it like this because files are huge

**Comment by 123Kappa** [comment]
Happens to me too.. : /

**Comment by FiveEYZ** [comment]
By viewing the logs it looks like you just stopped the server before it was done loading, you gotta wait for the server to completely finish loading. 

https://gist.github.com/ can take files up to 100 MB

note: if the server is heavily modded it will take a couple of minutes.

**Comment by Spontini** [comment]
The server kills itself, not manually and we fixed it

**Comment by gabizou** [comment]
> and we fixed it

What was the fix?

**Comment by Spontini** [comment]
It was a Docker issue, nothing to do with Sponge

**Comment by DrZoddiak** [comment]
https://pterodactyl.io/daemon/configuration.html#output-throttles
Adding a note here since Pterodactyl is a decently popular panel. (and it took me longer than it should to find the fix)

It is triggered by Ptero's output throttle, and can be modified in the core.json.

The link explains everything you would need to know to fix it.
