### ISSUE TITLE
Chunk loading crash on startup with OTG + Biome Bundle 

### ISSUE THREAD

**Issue by limbo-app** [SpongePowered/SpongeForge#2660]
This issue was originally submitted by @Vortex67 in [SpongePowered/SpongeCommon#2226](https://github.com/SpongePowered/SpongeCommon/issues/2226).
___
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2768-7.1.6-RC3628

<details>
  <summary>- Plugins/Mods:</summary>

**Mods (197)**: Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AE2 Stuff, AI Improvements, Architect, Actually Additions, AgriCraft, Applied Energistics 2, Aroma1997Core, Attribute Fix, Auto Ore Dictionary Converter, B.A.S.E, BD Lib, Botanic Bonsai, Baubles, Bed Patch, Better Builder's Wands, BetterBedrockGen, Biome Bundle, Bibliocraft, Bonsai Trees, Botania, Botania Needs These Things!, Botania Tweaks, Botania Tweaks Core, Brandon's Core, Bookshelf, Cam's Currency, Carry On, Chameleon, Chest Transporter, ChickenChunks, Chisel, CoFH Core, CoFH World, CodeChicken Lib, Compact Drawers, Compacter, ContentTweaker, CosmeticArmorReworked, CosmeticArmorReworked Integration for TombManyGraves2, CraftTweaker JEI Support, CraftTweaker2, Crafting Tweaks, Cucumber Library, Custom Starting Gear, DebugServerInfo, Diet Hopper, Dimensional Doors, Draconic Evolution, Drawbridges, EDX Multipart, Embers Rekindled, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, Ender IO endergy, EnderCore, EnderStorage, EnderTweaker, Engineer's Workshop Reborn, Equivalent Integrations, Expanded Equivalence, Extra Cells 2, Extra Utilities 2, Enchanting Plus, Extreme Reactors, FTB Library, FTB Money, FTB Quests, FTB Utilities, FTB Utilities: Backups, FastFurnace, FastWorkbench, Fence Jumper, Flux Networks, FoamFix, FoamFixCore, Forge Microblocks, Forge Multipart CBE, GasConduits, Growable Cells, Guide-API, Hammer Core, Harvest, HelpFixer, IC2CropPlugin, Immersive Cables, Immersive Engineering, Immersive Petroleum, In-Game wiki Mod, Industrial Foregoing, Industrial Wires, IndustrialCraft 2, IndustrialExpansion, InfinityLib, InstantUnify, Integration Foregoing, Inventory Tweaks, Iron Backpacks, Item Filters, JAOPCA, JAOPCAAgriculture, Just Enough Calculation, Just Enough Energistics, Just Enough Items, Just Enough Reactors, K4Lib, Land Manager, Login Shield, Lunatrius Core, LootTweaker, MCMultiPart, MTLib, Mantle, MattDahEpic Core, McJtyLib, MekaTweaker, Mekanism, MekanismGenerators, MekanismTools, Mekanism Ores, Mike's Mods Lib, Minecraft Multipart Plugin, Mod Tweaker, ModPack Utilities, MrTJPCore, Mystical Agradditions, Mystical Agriculture, Not Enough Items, OTG Core, Open Terrain Generator, OpenBlocks, OpenComputers, OpenComputers (Core), OpenModsLib, OpenModsLib Core, OreDictInit, OreExcavation, PVP Toggle, PiTweaks, Placebo, PlusTiC, PneumaticCraft: Repressurized, Preston, ProjectE, ProjectE Integration, Quick Leaf Decay, RFTools, RFTools Power / OC Integration, Reborn Core, Refined Storage, Refined Storage Addons, Refined Storage Requestify, Redstone Arsenal, Redstone Flux, Redstone Flux Arsenal, Redstone Paste, Rex's Additional Structures, Road Runner, Schematica, ServerUtil, Shadowfacts' Forgelin, Simple Harvest, Simply Jetpacks 2, Soot, SonarCore, SpongeForge, Storage Drawers, Storage Drawers Extras, Tesla Core Lib, Tesla Core Lib Registries, Thermal Cultivation, Thermal Dynamics, Tesslocators, Thermal Expansion, Thermal Foundation, Thermal Innovation, Tinker's JEI, Tinkers' Construct, Tiny Progressions, TorchMaster, Translocators, UniDict, Unified Items, Unloader, VanillaFix, Waila, WanionLib, Waystones, What Are We Looking At, Woot, WorldEdit, Worley's Caves, WrapUp, XNet, YABBA, YNot, Zero CORE, mob_grinding_utils

**Plugins (11)**: CmdBuilder, CmdControl, CmdScheduler, CommandUtils, Greentexting, LuckPerms, MeeM, Nucleus, Pieconomy, PlaceholderAPI, SleepVote
</details>

The server was working fine, and then after replacing Mekanism with Mekanica and then replacing that with Mekanism again, I am unable to load the server because of a chunk loading exception in OTG. Removing mekanism and related mods does not fix this. I can make a new Biome Bundle world in the client with all the mods active and play normally. Transferring this to server however gives me the same error. Removing Sponge fixes the issue.
[latest.log](https://github.com/SpongePowered/SpongeCommon/files/3016083/latest.log)
[error](https://pastebin.com/puP3FmA8)

**Comment by egshels** [comment]
Disabling Streams and Farseek also fixes the issue, so it is an incompatibility with sponge and farseek I assume?

**Comment by Nadonate** [comment]
I can confirm disabling Streams and Farseek fixes the issue:

**Streams-1.12-0.4.4.jar
Farseek-1.12-2.3.1.jar
Biome_Bundle-1.12.2-v6.1.jar
OpenTerrainGenerator-1.12.2+-+v6.jar
spongeforge-1.12.2-2768-7.1.5.jar**

[latest.log](https://github.com/SpongePowered/SpongeForge/files/3041264/latest.log)

**Comment by Aang23** [comment]
Getting the same issue !
I also confirm removing Streams and Farseek fixes it.

**Comment by delvr** [comment]
Should be fixed in Farseek 2.3.2, please give it a try and let me know if there are still any issues.

**Comment by phit** [comment]
gonna close this and I assume this was fixed, if this is still an issue please reply and I'll reopen
