### ISSUE TITLE
Doomlike Dungeons world gen issue

### ISSUE THREAD

**Issue by Spontini** [SpongePowered/SpongeForge#2661]
**I am currently running**

- SpongeForge version: Spongeforge 1.12.2 2768 7.1.6 RC3616
- Forge version: Forge 2795
- Java version: Java 8 Update 201 (64bit)
- Operating System: Ubuntu 18.04
- Plugins/Mods: FTB Interactions, Nucleus, RankUpper, LuckPerms, CMDControl, CMDBuilder,
AuraBlockLimit, MMCRestrict, MMCReboot

**Issue Description**

The mod from FTB Interactions `Doomlike Dungeons` doesn't generate dungeons, i had that kind of issue with other dimensions due using sponge few months ago such as Landia from PO3 and Stoneblock dimensions from FTB Stoneblock2. I've tested the dimensions in my singleplayer world and those dungeons being generated without no problem.

**Comment by phit** [comment]
can't reproduce with the same pack and Sponge version on my own server

![](https://i.imgur.com/xsMm80D.png)
