### ISSUE TITLE
Random Portals mod not compatible

### ISSUE THREAD

**Issue by Renari** [SpongePowered/SpongeForge#2667]
**I am currently running**

- SpongeForge version: 1.12.2-7.1.5
- Forge version: 14.23.5.2824
- Java version: 1.8.0_172
- Operating System: W10

- Plugins/Mods: Random Portals

**Issue Description**
When Random Portals mod is loaded taking a portal (such as the nether portal) by that mod often warps you inside a wall and return portals are not generated. This does not happen without SpongeForge.

**Comment by Renari** [comment]
https://github.com/TheRandomLabs/RandomPortals/issues/17

**Comment by TheRandomLabs** [comment]
This probably has something to do with my [custom teleporter](https://github.com/TheRandomLabs/RandomPortals/blob/1.12.2/src/main/java/com/therandomlabs/randomportals/world/RPOTeleporter.java). Any ideas?

**Comment by gabizou** [comment]
@Zidane could you look into this potentially? I'm still working on verifying some block drop handling between capture types.

**Comment by Zidane** [comment]
@TheRandomLabs Can you link me where you take over the teleportation code to the Nether or if you change the Nether's Teleporter?

**Comment by TheRandomLabs** [comment]
[Here](https://github.com/TheRandomLabs/RandomPatches/blob/1.12/src/main/java/com/therandomlabs/randompatches/patch/WorldServerPatch.java) is the ASM transformer and [here](https://github.com/TheRandomLabs/RandomPatches/blob/1.12/src/main/java/com/therandomlabs/randompatches/common/RPTeleporter.java) is the Teleporter wrapper class.

**Comment by Zidane** [comment]
@TheRandomLabs I see you made a code change but I need to figure out where we are inadvertently replacing the World's Teleporter object by seeing where you set this on the WorldServer to begin with. The code change you made should not have been needed.

Can you link me to some code (as those links are dead) and I'll get this fixed up right now.

**Comment by TheRandomLabs** [comment]
I was using RandomPatches to replace the `Teleporter` in `WorldServer`'s constructor, but now I'm using reflection to set it to [RPOTeleporter](https://github.com/TheRandomLabs/RandomPortals/blob/1.12.2/src/main/java/com/therandomlabs/randomportals/world/RPOTeleporter.java) during `WorldEvent.Load`.
Sponge is setting the `Teleporter` [here](https://github.com/SpongePowered/SpongeCommon/blob/d84fdaec9e338a7d3b14e192be36ea94ecf2405a/src/main/java/org/spongepowered/common/mixin/core/world/MixinWorldServer.java#L307).
Replacing the `Teleporter` with my own fixed the issues that were occurring, but I'm not sure if there are any side effects.

**Comment by Zidane** [comment]
@TheRandomLabs In that case, I consider this issue closed. Granted someone should make a PR to Forge to let you set the default teleporter of a World.

We don't actually change the teleporter of the world but more set it to a Vanilla one (or mod one) if a server admin asks us too. Otherwise, it uses whatever Vanilla would give it in this case (Which is just Teleporter of course).

I have no problems with the change you made.

**Comment by TheRandomLabs** [comment]
Alright, thanks.
