### ISSUE TITLE
the mod (appliedenergistics2) works wrongly in the server

### ISSUE THREAD

**Issue by dablackM** [SpongePowered/SpongeForge#2668]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2768-7.1.6-RC3641
- Forge version: forge-1.12.2-14.23.5.2824-universal
- Java version: jre1.8.0_201
- Operating System:windows

- Plugins/Mods:appliedenergistics2-rv6-stable-6

**Issue Description**
when I make the fluix crystal which is an item in the mod(appliedenergistics2)in single game, it works. But, when I made it in onlion game , it fails.I use the sponge to hold a sever, is that relevant?

**Comment by gabizou** [comment]
Going to need a better description: What is the item supposed to do and what is it doing? Saying it works and fails, doesn't mean anything to me.

**Comment by dablackM** [comment]
Sorry for my poor description. In order to make this item, you need put three items (red stone, nether crystal and charged crystal which is also the mod’s item) into a water cube, after that the fluix crystal turn up from the water.(or maybe give to your inventory？）

**Comment by dablackM** [comment]
Is that sponge change the way of item floating?

**Comment by dablackM** [comment]
In fact the events which is relevant with water are all null, I means you drop something to water so that you can craft some items or charge something.

**Comment by HybridAvenger** [comment]
if the server has ae2stuff you can make fluix in the Crystal Growth Chamber

**Comment by dablackM** [comment]
However I just want to fix this bug. Or I can’t make any thing which is something to do with fluid block

**Comment by phit** [comment]
can you please retest on RC3648 
http://files.minecraftforge.net/spongepowered

**Comment by dablackM** [comment]
I have tested with the latest forge and spongeforge but the problem still occurs

**Comment by LemADEC** [comment]
Please share the full mods list and versions.

**Comment by gabizou** [comment]
I can't reproduce this with AE2 and SpongeForge. Can you re-test with latest

**Comment by dablackM** [comment]
That is strange then. The mods I have used are only spongeforge-1.12.2-2768-7.1.6-RC3666 and appliedenergistics2-rv6-stable-6. And the forge I have used is forge-1.12.2-14.23.5.2836. However, the problem still happened here.

**Comment by dablackM** [comment]
[debug.log](https://github.com/SpongePowered/SpongeForge/files/3106197/debug.log)

**Comment by phit** [comment]
https://github.com/SpongePowered/SpongeForge/issues/2731#issuecomment-491426805
