### ISSUE TITLE
Invaled Block State

### ISSUE THREAD

**Issue by Chronic-Reflexes** [SpongePowered/SpongeForge#2671]
- SpongeForge version:  latest stable
- Forge version:  2770 universal
- Java version: 8 64 bit
- Operating System: (host)

Harvest craft, even illegal stated for oak doors ill submit a new report

/***************************************************************************************************************************/
/* Invalid BlockState */
/***************************************************************************************************************************/
/* Someone attempted to create an ItemStack from a BlockState that does not have a valid item! */
/* BlockState : harvestcraft:pamraspberrycrop[age=0] */
/* BlockType : Block{harvestcraft:pamraspberrycrop} */
/* java.lang.Exception: Stacktrace */
/* org.spongepowered.common.item.inventory.SpongeItemStackBuilder.fromBlockState(SpongeItemStackBuilder.java:242) */
/* net.moddedminecraft.mmcrestrict.EventListener.checkBanned(EventListener.java:454) */
/* net.moddedminecraft.mmcrestrict.EventListener.onRightClick(EventListener.java:275) */
/* org.spongepowered.common.event.listener.OffHandListener_EventListener_onRightClick95.handle(Unknown Source) */
/* org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) */
/* org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383) */
/* org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:347) */
/* org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:435) */
/* net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:1220) */
/* net.minecraft.network.NetHandlerPlayServer.redirect$onProcessRightClickBlock$zjb000(NetHandlerPlayServer.java:2426) */
/* net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:741) */
/* net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) */
/* net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) */
/* org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) */
/* net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlj000(SourceFile:539) */
/* net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) */
/* java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) */
/* java.util.concurrent.FutureTask.run(FutureTask.java:266) */
/* net.minecraft.util.Util.func_181617_a(SourceFile:46) */
/* org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:301) */
/* net.minecraft.server.MinecraftServer.redirect$onRun$zjo000(MinecraftServer.java:3955) */
/* net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) */
/* net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) */
/* net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) */
/* net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) */
/* java.lang.Thread.run(Thread.java:748) */

**Comment by phit** [comment]
please report this to mmcrestrict
