### ISSUE TITLE
invalid block state (vanilla block)

### ISSUE THREAD

**Issue by Chronic-Reflexes** [SpongePowered/SpongeForge#2672]
- SpongeForge version:  spongeforge-1.12.2-2768-7.1.6-RC3641
- Forge version: 2825
- Java version: 8 64 bit
- Operating System: (host) linux?

mods: Applied energistics 2 , bonsai trees , buildcraft , Chisel , Galacticraft , Gravestone mod , IC2 , Inventory Tweaks , Iron Chest , Iron Tank , JEI , Little Tiles ,  Modular Powersuits , Mystcraft , not enough id's Numina , Pam's Harvestcraft , PiTweaks ProjectE Project Red Psi TConstruct, Uncrafting table , world edit
=====================================================================Plugins: Auriona Vote Listener , Gwmcrates , gwmlib , grief prevention , Luck Perms , MMC Restrict , NuVotifier ,  Nucleus , Total Economy , Ultimate Chat

https://gist.github.com/partridge420x/7e75982e4f702db7aa2cf605a46096b8

**Comment by phit** [comment]
please report this to mmcrestrict
