### ISSUE TITLE
EnderIO Electrical Steel Breaking Issue

### ISSUE THREAD

**Issue by selkiess** [SpongePowered/SpongeForge#2673]
**I am currently running**

- SpongeForge version: 3641
- Forge version: 2815
- Java version: Java 8 201
- Operating System: Windows 10

- Plugins/Mods: 
ModPack:
All The Mods 3 5.12.0
Plugins:
DynmapGriefPrevention
EconomyLite
GameSpleef
GriefPrevention
Holograms
LangSwitch
LuckPerms
Mega Menus
MMCReboot
Nucleus
PixelAutoMessages
ServerListPlus
UltimateChat
VillagerShops

**Issue Description**

Placing Electrical Steel Blocks from EnderIO and attempting to break it results in an error in console and does not break the block. The block appears to break in game but if you place a block where the electrical steel was, the block transforms back into electrical steel.

Relevant Error:

[https://gist.github.com/Selkie707/c454367f3bd460525f3dbb54e7b9f636](https://gist.github.com/Selkie707/c454367f3bd460525f3dbb54e7b9f636)

**Comment by gabizou** [comment]
EnderIO appears to be attempting to load a client class. This isn't supported on servers, not a sponge issue.

The stack trace literally mentions it:
```
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/gui/GuiScreen
	at com.enderio.core.common.BlockEnder.getPickBlock(BlockEnder.java:132) ~[BlockEnder.class:?]
	at shetiphian.terraqueous.common.misc.EventHandler$ForgeEventBus.onBlockBreakEvent(EventHandler.java:218) ~[EventHandler$ForgeEventBus.class:?]

```
