### ISSUE TITLE
ProjectRed Gates,Repeaters,Timers etc Broken

### ISSUE THREAD

**Issue by selkiess** [SpongePowered/SpongeForge#2674]
**I am currently running**

- SpongeForge version: 3641
- Forge version: 2815
- Java version: Java 8 201
- Operating System: N/A

- Plugins/Mods: 
ModPack:
All The Mods 3 5.12.0
Plugins:
DynmapGriefPrevention
EconomyLite
GameSpleef
GriefPrevention
Holograms
LangSwitch
LuckPerms
Mega Menus
MMCReboot
Nucleus
PixelAutoMessages
ServerListPlus
UltimateChat
VillagerShops

**Issue Description**

ProjectRed, Levers, and redstone in general seem to be having issues. Related issues are #2669 and [https://github.com/SpongePowered/SpongeCommon/issues/2227](https://github.com/SpongePowered/SpongeCommon/issues/2227).

Sometimes redstone wires/redstone remain powered or unpowered when the opposite should be true. Levers also need to be hit twice to change state. In addition sometime between build 3629 and 3641 phase issues were introduced resulting in massive log spam from ProjectRed/Redstone interactions. I reverted to build 3629 and the errors went away and I no longer have to double switch levers, but ProjectRed gates and timers still have the aforementioned "ghost" power or no power issue. 

An easily repeatable way to reproduce the weird behavior is to hook up:

Timer -> minecraft repeater -> NOT gate -> anything switching by redstone

The initial cycle works fine but the NOT gate will cease to output after the initial redstone signal disables it. Breaking redstone that is connected to the output or input of the not gate and replacing it causes the redstone to revert to correct behavior.

I tried creating a gist of the full log but gist got angry so here is a big chunk of it:
[https://gist.github.com/Selkie707/c6a11b5d710cd51394cfe38f6f7fca15](https://gist.github.com/Selkie707/c6a11b5d710cd51394cfe38f6f7fca15)

![not gate](https://user-images.githubusercontent.com/18093341/55678915-ed0c6d80-58cf-11e9-96ef-58f344b350fc.png)

**Comment by gabizou** [comment]
You pointed out that this is in relation to https://github.com/SpongePowered/SpongeCommon/issues/2227, so why open a new now duplicate issue?
