### ISSUE TITLE
Just Enough Dimensions world seed change on server restart

### ISSUE THREAD

**Issue by elementalistic** [SpongePowered/SpongeForge#2676]
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2768-7.1.6-RC3639
- Forge version: forge-1.12.2-14.23.5.2795-universal
- Java version: 1.8.0_161
- Operating System: win10

- Plugins/Mods:
FTB Interactions 1.0.1
Sponge mods: fastasyncworldedit, worldedit, luckperms, mmcprefix, nucleus, xenperms

**Issue Description**
On FTB-I after you complete the basic void island quests and make your portal, you go through to the Just Enough Dimensions world Dim100.  This is effectively the main world on a non void island game/map.  

This dimension has it's seed changed each time the server restarts/crashes.

Disabling sponge has it get the same seed as the rest of the worlds and dimensions on load.

By specifying the world seed for Dim100 in the dimensions.json config file for JED in the **worldinfo** section, on server load with Sponge, the specified seed is used as expected.

`"RandomSeed": 1234567890123456`

During server startup, I get these 2 warnings:

> [justenoughdimensions]: Unrecognized option in worldinfo.values: 'generatorName: = "customized"'

The example files for JED show the generatorName customized as acceptable and is part of the default FTB-I config, so I'm not sure if it's relevant to this.

> [Sponge]: World [DIM100] (DIM100) has specified dimension type that is not registered. Skipping...

The other thing that is odd, is the world is not loaded on startup, nor starting region is prepared until a player joins and goes to that Dimension.

**Comment by phit** [comment]
there's a pr pending for this https://github.com/SpongePowered/SpongeCommon/pull/2234

**Comment by elementalistic** [comment]
I look at the Open/Closed issues and forget the pr's.  Thanks as always phit.

**Comment by ImMorpheus** [comment]
PR merged
