### ISSUE TITLE
RealFileCabnet errors in log after update

### ISSUE THREAD

**Issue by selkiess** [SpongePowered/SpongeForge#2679]
**I am currently running**

- SpongeForge version: 3641
- Forge version: 2815
- Java version: Java 8 201
- Operating System: N/A

- Plugins/Mods: 
ModPack:
All The Mods 3 5.12.0
Plugins:
DynmapGriefPrevention
EconomyLite
GameSpleef
GriefPrevention
Holograms
LangSwitch
LuckPerms
Mega Menus
MMCReboot
Nucleus
PixelAutoMessages
ServerListPlus
UltimateChat
VillagerShops

**Issue Description**

Just updated to 3643 from 3629 and am now seeing Undefined discriminator messages in log

Log:[https://gist.github.com/Selkie707/2b99caa9941d32f5a24dbb4a6e1f32a6](https://gist.github.com/Selkie707/2b99caa9941d32f5a24dbb4a6e1f32a6)

**Comment by phit** [comment]
mod issue, report to Real Filing Cabinet
