### ISSUE TITLE
Blocks don't dropping after breaking

### ISSUE THREAD

**Issue by yaroslav4167** [SpongePowered/SpongeForge#2680]
**I am currently running**

 Minecraft: 1.12.2
 SpongeForge: 1.12.2-2768-7.1.6-RC3643
 Minecraft Forge: 14.23.5.2768
 OS: Windows10

- Plugins/Mods: only sponge and forge

**Issue Description**
Blocks don't dropping after breaking, this problem starts in sponge 1.12.2-2768-7.1.6-RC3631, and works on all versions above, up to RC3643.

**Comment by gabizou** [comment]
Verified doesn't work, can you try with `-Dsponge.shouldFireAll=true` as a startup flag?

**Comment by yaroslav4167** [comment]
With `-Dsponge.shouldFireAll=true` everything works, blocks drop out.
