### ISSUE TITLE
MixinEventBus issues

### ISSUE THREAD

**Issue by Player3324** [SpongePowered/SpongeForge#2681]
I just looked at a performance problem that pointed to a massive self time increase in [MixinEventBus.onUnregisterListener](https://github.com/SpongePowered/SpongeForge/blob/313faa9c678f1067345c2a19dfbb33e09ec002c4/src/main/java/org/spongepowered/mod/mixin/core/fml/common/eventhandler/MixinEventBus.java#L282). There may be sampling bias, so it may be a fluke. Methods may also have been inlined, counting towards the self time.

The specific scenario has a mod hammering Forge's EventBus with (apparently) register+unregister pairs, potentially several register invocations before the unregisters from a delayed tick handler follow. I can't say whether there definitely is no excess of registrations.

From taking a brief look at the code it appears that the Sponge code is obviously not thread safe, despite the event bus in its function IMO strictly requiring it. My suspicion is that either a concurrent access disturbs the state somewhere in the internals or that there's a leak that is not obvious with normal registration frequencies.

Sponge appears to be at build 2768, the server is heavily modded, but I unfortunately don't really have access to it - I'm just going off profiling data and a look at the code. I recommend to fix the concurrency issues and do some testing whether there is a leak around register/unregister.

_edit by @phit: fixed link to point at state of file when issue was made_

**Comment by dualspiral** [comment]
https://github.com/SpongePowered/SpongeForge/pull/3168
