### ISSUE TITLE
Wierd Crash in stoneblock 2

### ISSUE THREAD

**Issue by 123Kappa** [SpongePowered/SpongeForge#2683]
I am hosting latest sb2 I am getting this wierd crash, every time coordinates are different and crashes are frequent. 

https://pastebin.com/w3QA59X7

**Comment by phit** [comment]
update to latest, if it still happens open a new issue and fill out the issue template, it's there for a reason

**Comment by 123Kappa** [comment]
Hello phit! Sorry for not filling the format! I am already using the latest sponge version: 
 1.12.2-2768-7.1.6-RC3643

**Comment by phit** [comment]
latest is 3648 http://files.minecraftforge.net/spongepowered

**Comment by 123Kappa** [comment]
Oh i am sorry, that version does not exist in this website. https://www.spongepowered.org/downloads/spongeforge/stable/1.12.2
I am gonna test it with new version
