### ISSUE TITLE
Silkworm leaves create massive lag

### ISSUE THREAD

**Issue by ApolloMCC** [SpongePowered/SpongeForge#2684]
**I am currently running**

- SpongeForge version: 3648 
- Forge version: 14.23.5.2808
- Java version: 8 update 201
- Operating System: Ubuntu 18.04

Hello! 
I just updated to 3648 and when someone uses Silkworm from exnixilo Creatio on a tree - which makes the leaves turn white slowly, when you harvest them you get string - , the server goes to 1 tps. I noticed that the lag starts to happen once the leaves have reached their 100% state (full white). When this is happening, even if you break the leaves the lag wont stop and the profiler (tick profiler for example) will still see the leaves in the same coordinates. The only way to stop the lag is to unload the chunk. When you get back after you unload it its fine. 
Also this gets spammed in the console.  https://pastebin.com/u8PGgdhR
You can replicate it. 

Also this gets spammed in console too but it doesn't create any lag I think it's another bug though https://pastebin.com/wUuU1F8r

**Comment by gabizou** [comment]
Retest with 3650. If it's still not resolved, post new logs.

**Comment by ApolloMCC** [comment]
Ok I am on 3650, Issue is half solved. Now, when you break the leaves the lag stops.
Here's the log before the error starts, its in 4 parts because they are too big:
Part 1: https://pastebin.com/XBqGdmKS
Part 2: https://pastebin.com/Wx65Yf1X
Part 3: https://pastebin.com/AiRezGNb
Part 4: https://pastebin.com/x78qGdKg

After that this error starts to be spammed (this doesnt create lag) : https://pastebin.com/fbVQ53fE
And then (when i make a tree in game) This starts to spam without any message before it: https://pastebin.com/vyWZVHdL

**Comment by gabizou** [comment]
Those two logs are showing [20:55:36] [Server thread/ERROR] [Sponge]: /* SpongeForge : 1.12.2-2768-7.1.6-RC3648                                                                                                                                                                                                    */
Can you double check that you're running 3650? Also, if the log is too long for pastebin, you can use https://gist.github.com/ for longer pastes.

**Comment by ApolloMCC** [comment]
Ok i double checked and i am using 50. I have no idea why it says 48
I also checked logs and they are the correct ones.

**Comment by ApolloMCC** [comment]
Ok I used 3651, silworm issue fixed. BUT now, when you use a furnace if the fuel runs out the items inside disappear.

**Comment by phit** [comment]
unable to repro the furnace issue and you said the other issue was fixed, closing
if you can still repro the furnace thing make a new issue with updated information
I tested with spongeforge-1.12.2-2768-7.1.6-RC3657
