### ISSUE TITLE
ToroQuest Mod

### ISSUE THREAD

**Issue by ObjecT767** [SpongePowered/SpongeForge#2687]
**I am currently running**

- SpongeForge version: 1.12.2-2768-7.1.6-RC3643
- Forge version: 1.12.2 - 14.23.5.2768
- Java version: Version 8 Update 201
- Operating System: Win 10

- Plugins/Mods:
ToroQuest,
ToroHealth Damage Indicators

**Issue Description**

Sponge 7.1.6-RC3643 create infinits of Guards and Vilagers when Vilage is generated.
After restart, loaded Vilages don't spawn more Gurads and VIlagers.
This issue don't occure on Sponge 1.12.2-2768-7.1.5.
![1](https://user-images.githubusercontent.com/49611562/56111830-7e778180-5f59-11e9-8367-9f64ca97b6d1.PNG)
![2](https://user-images.githubusercontent.com/49611562/56111837-83d4cc00-5f59-11e9-866f-ac27501a6fe1.PNG)

Server log:
https://gist.github.com/ObjecT767/c7d2a34b070cb182830c1db60a780935

**Comment by phit** [comment]
update to RC3651+

http://files.minecraftforge.net/spongepowered
https://github.com/SpongePowered/SpongeForge/issues/2682
