### ISSUE TITLE
Crash in sky factory 4

### ISSUE THREAD

**Issue by ApolloMCC** [SpongePowered/SpongeForge#2690]
SpongeForge 1.12.2-2768-7.1.6-RC3616
Forge 14.23.5.2831
Modpack: SkyFactory4

Weird crash report with sponge: https://pastebin.com/8qR3fuZ4

**Comment by phit** [comment]
report to carryon, doesn't look related to sponge at all

**Comment by Explosivee** [comment]
I have tested it in singleplayer + non sponge test server, i'm 100% sure that is sponge
