### ISSUE TITLE
Sky factory 4 console spam with togethereforever mod

### ISSUE THREAD

**Issue by ApolloMCC** [SpongePowered/SpongeForge#2692]
SpongeForge 1.12.2-2768-7.1.6-RC3616
Forge 14.23.5.2831
Modpack: SkyFactory4

Here's the spam https://pastebin.com/BNCxeXD0

**Comment by phit** [comment]
at least use the search or look at the most recent issues for 30 seconds.. https://github.com/SpongePowered/SpongeForge/issues/2688

**Comment by ApolloMCC** [comment]
Sorry phit i was told in discord to upload I did not check
