### ISSUE TITLE
Crash with CompactStorage

### ISSUE THREAD

**Issue by krisjenner** [SpongePowered/SpongeForge#2693]
**I am currently running**

- SpongeForge version: RC3616
- Forge version: 2831
- Java version: 1.8.0 201
- Operating System: Windows 10

- Plugins/Mods: Sky Factory 4

**Issue Description**
Can't specify exactly when it happened but here is crash report

[here](https://gist.github.com/krisjenner/3ed675760dd195bcc77a284b2484b885)

**Comment by phit** [comment]
mod bug, report to them and tell them 
"to not to override getTileData to call writeToNbt" see https://github.com/JurassiCraftTeam/JurassiCraft2/issues/561#issuecomment-483715610
