### ISSUE TITLE
SkyFactory 4 + OreExcavation(VeinMiner) + Prestige bug

### ISSUE THREAD

**Issue by krisjenner** [SpongePowered/SpongeForge#2697]
**I am currently running**

- SpongeForge version: RC3659
- Forge version: 2831
- Java version: 1.8
- Operating System: Win10

**Issue Description**
Ore Excavation is a Vein Miner mod. When you hold down a specific key and mine a block (eg leaves on a tree) it will mine all of the same block in a radius of X.

SF4 has this disabled by default until you unlock it through Prestige.
When unlocking it through prestige on RC3616 it worked.
When unlocking it through prestige on RC3659 it did not.

Unsure if a log would help but please let me know if it would.

**Comment by HeberonYT** [comment]
I am using sponge RC3616 and unlocking does not work.
Apparently if it is unlocked in the interface, but when trying to get the crafting of the Hopping Bonsai, it does not appear.
In addition, the console throws spam when the prestige point is used and the user is ejected from the server.
https://pastebin.com/raw/0Xugz4du

**Comment by phit** [comment]
please retest on 1.12.2-2768-7.1.6-RC3682 there were various fixes to advancements and workarounds were added to fix the prestig mod

**Comment by phit** [comment]
please reply if this is still an issue and ill reopen
