### ISSUE TITLE
Crash on SF4 with RC3657

### ISSUE THREAD

**Issue by krisjenner** [SpongePowered/SpongeForge#2699]
**I am currently running**

- SpongeForge version: RC3657
- Forge version: 2831
- Java version: 1.8
- Operating System: W10

- Plugins/Mods:

**Issue Description**
Updated sponge from RC3616 to RC3657 using SkyFactory 4 and got this crash on startup

[LOG](https://gist.github.com/krisjenner/255ad3bcbf82c3560d214709097d3517)

**Comment by Zidane** [comment]
We are missing some bits of the log here. Namely a Mixin failed to apply as IMixinWorldServer was never applied to WorldServer.

**Comment by phit** [comment]
remove laggoggles https://github.com/TerminatorNL/LagGoggles/issues/56
