### ISSUE TITLE
FastFurnace Incompatibility

### ISSUE THREAD

**Issue by LemADEC** [SpongePowered/SpongeForge#2702]
**I am currently running**
- SpongeForge version: 1.12.2-2768-7.1.6-RC3662
- Forge version: 14.23.5.2824
- Java version: 1.8
- Operating System: CentOS

- Plugins/Mods:
SkyFactory4 4.0.1
Plugins (19): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, AntiWDL, BetterChunkLoader, Broadcast, CatClearLag, Enjin Minecraft Plugin, GriefPrevention, LuckPerms, MagiBridge, Nucleus, Prism, Server Backup, SkyClaims, Total Economy, WrapperPing, spark

Mods (194): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, Advancement Book, Animal Crops, Apotheosis, AppleCore, AppleSkin, Applied Energistics 2, Aroma1997Core, Astral Sorcery, B.A.S.E, BNBGamingLib, Barrels, Drums, Storage & More, Baubles, Bed Patch, BiblioCraft, BnBGamingCore, Bonsai Trees, Bookshelf, Building Gadgets, Caliper, Calm Down Zombie Guy, Carry On, Ceramics, Chargers, ChineseWorkshop, Chisel, Chisels & Bits, Click Machine, CoFH Core, CoFH World, CodeChicken Lib, ComPatchedStorage, CommonCapabilities, Compact Machines 3, CompactStorage, Construct's Armory, ContentTweaker, Cooking for Blockheads, Corail Tombstone, CraftTweaker JEI Support, CraftTweaker2, Cucumber Library, Culinary Construct, Cyclic, Cyclops Core, Dark Utilities, Deep Mob Learning, Dimension Stages, Elevator Mod, Ender Crop, Ender Utilities, EnderCore, EnderStorage, Extended Crafting, Extra Cells 2, Extra Cells Patch, Farming for Blockheads, FastFurnace, FastWorkbench, Fence Overhaul, FindMe, Flux Networks, FoamFix, FoamFixCore, Forge Microblocks, Forge Multipart CBE, Forgiving Void, Game Stages, Guide-API, Headcrumbs, Horse Power, Hunting Dimension, HydroGel, InControl, Industrial Foregoing, Inspirations, Integrated Dynamics, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTunnels-Compat, Iron Jetpacks, Item Stages, JourneyMap, Just Enough Items, KleeSlabs, Limitless Structure Blocks, MCMultiPart, MTLib, MalisisCore, MalisisDoors, Mantle, MatterOverdrive: Legacy Edition, McJtyLib, Mekanism, MekanismGenerators, Minecraft Multipart Plugin, Mob Stages, Mod Tweaker, ModPack Basic Tools, ModPack Utilities, More Buckets, More Cauldrons, Morpheus, Mystcraft, Mystical Agradditions, Mystical Agriculture, NuclearCraft, OG Dragon+, OpenComputers, OpenComputers (Core), OpenComputers Xnet Driver, OreExcavation, Parabox, Pickle Tweaks, PigUtils, Pipe Master 2000, Placebo, PortalGun, Practical Logistics 2, Prestige, Primitive Crafting, ProjectE, RFToolsPower, Ranged Pumps, Real Filing Cabinet, RecipeStages, Redstone Flux, Resource Hogs, Rustic, Shadowfacts' Forgelin, Simple Generators, Simple Inventory sorting, Simple Storage Network, Sky Grid, SkyBonsais, Slab Machines, SlimyBoyos, Smooth Font Core, Snad, SonarCore, SpongeForge, Statues mod, Stuff A Sock In It, Super Sound Muffler, Surge, SwingThroughGrass, Sync, TallGates, TelePastries, Tell Me, Tesla Core Lib, Tesla Core Lib Registries, The Lost Cities, The Twilight Forest, The Weirding Gadget, Thermal Dynamics, Thermal Foundation, Thermal Innovation, Tinkers Tool Leveling, Tinkers' Complement, Tinkers' Construct, Tiny Progressions, TogetherForever, Topography, TorchMaster, Translocators, Tree Growing Simulator 2016, Triumph, Twitchcrumbs, Universal Modifiers, Valkyrie Lib, ViesCraft, Waddles, Waila, Waila Stages, Wall-Jump!, What Are We Looking At, Wither Crumbs, World Utils, WorldEdit, XL Food Mod, XNet, YNot, Yoyos, ZenStages, bouncy_creepers, mob_grinding_utils, sky_orchards, uppers

**Issue Description**
Open a furnace, then quickly shift-click 2+ fuel and 1 sand in it, then close the GUI
=> furnace change to its heated state, but all inventory is empty according to TOP (TheOneProbe), there's also no heat
It's quite frequent but not systematic.
If you keep the GUI open, you can get your output.
If it didn't reproduce initially, then, when furnace has cooled down (no more sand to consume), then the content is lost (remaining fuel and output glass are lost).

Issue is reproduced with RC3661 & RC3662.
Issue is not reproduced with RC3616.
There's no specific logs in console when issue happens.

**Comment by ApolloMCC** [comment]
I have the same issue. Even reported it back at version 57

**Comment by LemADEC** [comment]
It's even worst with SkyFactory 4.0.2 + spongeforge-1.12.2-2768-7.1.6-RC3665 and forge-1.12.2-14.23.5.2836 as you don't need to go fast to transfer item and the GUI will close immediately.

**Comment by Shybella** [comment]
Also encountering this on RC3665 from 3616.

**Comment by Yorkforce** [comment]
FastFurnace replaces the vanilla furnace and thats where the issue is occuring, disabling fastfurnace will fix the problem, but unfortunately  if server has it disabled and client doesn't, it breaks the texture.

**Comment by xElementzx** [comment]
Furnace works fine with the Recommended version of SpongeForge - 1.12.2-2768-7.1.5
https://repo.spongepowered.org/maven/org/spongepowered/spongeforge/1.12.2-2768-7.1.5/spongeforge-1.12.2-2768-7.1.5.jar

Seems to be an issue with the TE being replaced when it shouldn't be, which occurs when the furnace changes state from lit to not lit

**Comment by LemADEC** [comment]
Mods have hard dependencies on more recent builds of Forge, notably:
Build 2816:
	bs2609: Generalise EnumRarity to an interface (#5182)
Build 2781:
	mezz: Implement rendering for item models with emissive quads (#5047)
Other builds involve tileentity handling changes.
Should we update SpongeForge dependency version here?

**Comment by gabizou** [comment]
Retest with latest (3671)

**Comment by LemADEC** [comment]
Issue is still reproduced with RC3671 and FastFurnace-1.12.2-1.2.2.

**Comment by gabizou** [comment]
So, re-evaluating the changes, FastFurnace will have to remain incompatible with SpongeForge. The only real workaround I can offer is setting in the `tracker.conf`:
```hocon

tileentity {
  minecraft {
    furnace {
      block-bulk-capture = false
    }
  }
}

```

Otherwise FastFurnace is overriding expected behavior rather interestingly that I cannot provide a valid way to work around while tracking and capturing.

**Comment by xElementzx** [comment]
If it helps,
i narrowed it down to this single commit that broke it.

https://github.com/SpongePowered/SpongeCommon/commit/ea9b745db3dc3b57309d46c3eb18418c385eef53

changing block-bulk-capture to false for the minecraft furnace does not seem to fix this issue (using auto-populate for the tracker.conf)

**Comment by LXGaming** [comment]
Here's a quick fix to this issue: https://github.com/lolnetnz/FastFurnace/releases/tag/v1.2.2

When a vanilla furnace changes its state it first stores the current TileEntity, changes the BlockState then reapplies the TileEntity using the stored value.

FastFurnace just sets the BlockState but relies on a Forge added method `shouldRefresh` to ensure the TileEntity isn't altered.

Sponge is checking the `shouldRefresh` method here:
https://github.com/SpongePowered/SpongeCommon/blob/0b29d4a4a7d84eed9a759a43300870c7f6b43bf9/src/main/java/org/spongepowered/common/mixin/core/world/MixinChunk.java#L709

**However** there appears to be tracking issue with Sponge as the PhaseTracker should be respecting the result of the `shouldRefresh` method which it doesn't appear to be doing

**Comment by gabizou** [comment]
> When a vanilla furnace changes its state it first stores the current TileEntity, changes the BlockState then reapplies the TileEntity using the stored value.

It doesn't store the `TileEntity`, it full well knows that it's `TileEntity` will be invalidated and removed when it changes it's `IBlockState`(does it twice to make sure?), and then re-validates the `TileEntity` and re-sets it back to the world at the location, but if you want to say it "stores" it by storing it as a local variable or that a Furnace is changing block states during it's own tile entity tick, then sure, it's "stored".



> FastFurnace just sets the BlockState but relies on a Forge added method `shouldRefresh` to ensure the TileEntity isn't altered.

Correct, and this is where my problem lies

> **However** there appears to be tracking issue with Sponge as the PhaseTracker should be respecting the result of the `shouldRefresh` method which it doesn't appear to be doing

This [bit of tracking](https://github.com/SpongePowered/SpongeCommon/blob/0b29d4a4a7d84eed9a759a43300870c7f6b43bf9/src/main/java/org/spongepowered/common/mixin/core/world/MixinChunk.java#L695-L703) was specifically added because I needed to be able to track the `TileEntityFurnace` being "removed", and then [detect when the `TileEntityFurnace` was being re-applied at the position](https://github.com/SpongePowered/SpongeCommon/blob/0b29d4a4a7d84eed9a759a43300870c7f6b43bf9/src/main/java/org/spongepowered/common/event/tracking/context/MultiBlockCaptureSupplier.java#L450-L472) since the tracker wouldn't know if a block break was going to request a `TileEntity` to be removed until after the fact (specifically when the [`ChangeBlock#process` would be done](https://github.com/SpongePowered/SpongeCommon/blob/0b29d4a4a7d84eed9a759a43300870c7f6b43bf9/src/main/java/org/spongepowered/common/event/tracking/context/BlockTransaction.java#L412-L420)), so I had to artificially capture the `TileEntity` when it was being removed, especially since it would be removed during the break, and then attempt to perform the block drops (inventory drops).

**Comment by ktole1999** [comment]
this still happens with even the cobble furnace with latest 3693.

**Comment by LemADEC** [comment]
Update to latest version of FastFurnace mod. If problem persist, open a new issue.

**Comment by ktole1999** [comment]
since this is from SkyFactory 4 pack i am at the mercy of the pack. thanks for the info.

**Comment by Yorkforce** [comment]
I have added a request to update the mod on skyfactory 4 github @ktole1999 
Hopefully we will see it updated in SF4 v4.0.6

**Comment by ktole1999** [comment]
most excellent and thanks for the quick response.

**Comment by Shadows-of-Fire** [comment]
Breaking the validity of shouldRefresh is going to cause a lot of problems with other mods, not just FF.  Using BlockFurnace.setState will fix the issue for FF, but a lot of mods rely on that method

**Comment by gabizou** [comment]
it’s possible we can properly obey the shouldRefresh but it’d require patching vanilla furnaces to avoid using that static flag. What I’m considering doing though is enabling a config option for enhanced tracking vs traditional tracking for certain tiles, and those config options becoming defaulted or something. Maybe a command to right click on the tile and it’d add it to the config with disabling enhanced tracking (which is the root of the problem, it performs the break method after events have been thrown)
