### ISSUE TITLE
Console Spam erroring Tile Entity

### ISSUE THREAD

**Issue by krisjenner** [SpongePowered/SpongeForge#2705]
**I am currently running**

- SpongeForge version: RC3616
- Forge version: 2831
- Java version: 1.8
- Operating System: W10

- Plugins/Mods:

**Issue Description**
Console spam causing server to stall and crash and unable to open log if it spams too much

https://gist.github.com/krisjenner/f4d8a7bbb53292af05599ffab2903bf4

**Comment by phit** [comment]
mod issue, sponge is just catching it and stopping it from crashing the server https://github.com/MinecraftModDevelopmentMods/Tesla-Core-Lib/issues/28
