### ISSUE TITLE
Crash when updating from 3616 to 3666

### ISSUE THREAD

**Issue by julianubico** [SpongePowered/SpongeForge#2706]
**I am currently running**

Sponge/Forge version:
Minecraft Forge: 14.23.5.2831
SpongeForge: 1.12.2-2768-7.1.6-RC3666
Sponge: 1.12.2-7.1.6-SNAPSHOT
SpongeAPI: 7.1.0-b2736425
Minecraft: 1.12.2
- Java version: openjdk version "1.8.0_191"
- Operating System: CentOS Linux release 7.6.1810 (Core)

**Sky Factory 4 Modpack**

- Plugins/Mods:

```
Plugins (38): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, AuraBlockLimit, AurionsVoteListener, AutoReset, BetterChunkLoader, BungeeTabListPlus-SpongeBridge, Buycraft, CarrotShop, CatClearLag, Command-Blocker, CommandUtils, Dirt keepInventory, Dirt-Join-Leave-Messages, DirtCrashFailsafe, DirtRanks, DirtRespect, EconomyLite, GriefPrevention, Holograms, HuskyCrates, HuskyUI, LuckPerms, MMCReboot, MMCRestrict, MagiBridge, NuVotifier, Nucleus, OnlineBroadcast, PixelAutoMessages, PlayerDataReset-Plugin, Prism, RankUpper, SkyClaims, UltimateChat, spark
```

```
Mods (193): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, Advancement Book, Animal Crops, Apotheosis, AppleCore, AppleSkin, Applied Energistics 2, Aroma1997Core, Astral Sorcery, B.A.S.E, BNBGamingLib, Backups, Barrels, Drums, Storage & More, Baubles, Bed Patch, BiblioCraft, BnBGamingCore, Bonsai Trees, Bookshelf, Building Gadgets, Caliper, Calm Down Zombie Guy, Ceramics, Chargers, ChineseWorkshop, Chisel, Chisels & Bits, Click Machine, CoFH Core, CoFH World, CodeChicken Lib, ComPatchedStorage, CommonCapabilities, Compact Machines 3, CompactStorage, Construct's Armory, ContentTweaker, Cooking for Blockheads, CraftTweaker JEI Support, CraftTweaker2, Cucumber Library, Culinary Construct, Custom Mod Rejection Messsage, Cyclic, Cyclops Core, Dark Utilities, Deep Mob Learning, Dimension Stages, Elevator Mod, Ender Crop, Ender Utilities, EnderCore, EnderStorage, Extended Crafting, Extra Cells 2, Extra Cells Patch, Farming for Blockheads, FastFurnace, FastWorkbench, Fence Overhaul, FindMe, Flux Networks, FoamFix, FoamFixCore, Forge Microblocks, Forge Multipart CBE, Forgiving Void, Game Stages, Guide-API, Headcrumbs, Horse Power, Hunting Dimension, HydroGel, InControl, Industrial Foregoing, Inspirations, Integrated Dynamics, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTunnels-Compat, Iron Jetpacks, Item Stages, Just Enough Items, KleeSlabs, Limitless Structure Blocks, MCMultiPart, MTLib, MalisisCore, MalisisDoors, Mantle, MatterOverdrive: Legacy Edition, McJtyLib, Mekanism, MekanismGenerators, Mercurius, Minecraft Multipart Plugin, Mob Stages, Mod Tweaker, ModPack Basic Tools, ModPack Utilities, More Buckets, More Cauldrons, Mystcraft, Mystical Agradditions, Mystical Agriculture, NuclearCraft, OG Dragon+, OpenComputers, OpenComputers (Core), OpenComputers Xnet Driver, OreExcavation, Parabox, Pickle Tweaks, PigUtils, Pipe Master 2000, Placebo, PortalGun, Practical Logistics 2, Prestige, Primitive Crafting, ProjectE, RFToolsPower, Ranged Pumps, Real Filing Cabinet, RecipeStages, Redstone Flux, Resource Hogs, Rustic, Sampling Performance Profiler, Shadowfacts' Forgelin, Simple Generators, Simple Storage Network, Sky Grid, SkyBonsais, Slab Machines, SlimyBoyos, Snad, SonarCore, SpongeForge, Squeezer Patch, Statues mod, Stuff A Sock In It, Super Sound Muffler, Surge, SwingThroughGrass, Sync, TallGates, TelePastries, Tesla Core Lib, Tesla Core Lib Registries, The Lost Cities, The Twilight Forest, The Weirding Gadget, Thermal Dynamics, Thermal Foundation, Thermal Innovation, TickProfiler, Tinkers Tool Leveling, Tinkers' Complement, Tinkers' Construct, Tiny Progressions, TogetherForever, Topography, TorchMaster, Translocators, Tree Growing Simulator 2016, Triumph, Twitchcrumbs, Universal Modifiers, Valkyrie Lib, ViesCraft, Waddles, Waila, Waila Stages, Wall-Jump!, What Are We Looking At, Wither Crumbs, World Utils, WorldEdit, XL Food Mod, XNet, YNot, Yoyos, ZenStages, bouncy_creepers, mob_grinding_utils, sky_orchards, uppers
```

**Issue Description**

Crash report when updating from SpongeForge 3616 to 3666. I loaded back in 3616 and removed the block manually, then loaded in 3666 and server started up successfully.

- Log: <https://gist.github.com/d4julian/d90923a4418cd0b17f141f98b8c4970b>
- Crash Report: <https://hastebin.com/uyuhamazub.coffeescript>

**Comment by julianubico** [comment]
Getting crash reports like these every few minutes:

- https://hastebin.com/kujadupino.makefile
- https://hastebin.com/pabavovefo.coffeescript

**Comment by gabizou** [comment]
Can you add `-Dlegacy.debugClassLoading=true` and `-Dlegacy.debugClassLoadingSave=true` to launch and zip up the `CLASS_LOADER_TEMP` folder that gets generated? Need to see if there's some transformation going on that's preventing the phase contexts being pushed.

**Comment by julianubico** [comment]
Sorry, I've been a bit busy. I'll get it done tomorrow :)

**Comment by julianubico** [comment]
This is still present on RC3680.

[Google Drive link to CLASS_LOADER_TEMP](https://drive.google.com/file/d/177RKnoNp9wpeWoH9wM_hkKz8tdQNCpFL/view?usp=sharing)
[Crash Report](https://github.com/SpongePowered/SpongeForge/files/3125102/crash-2019-04-28_16.49.13-server.txt)

**Comment by Keaton1188** [comment]
Also had the same issue, but I've stuck with build 3616 because it seems the most stable atm lol

**Comment by gabizou** [comment]
@d4julian requested access to the classloader zip file.

**Comment by gabizou** [comment]
Found the issue: When maximum processing has been reached for neighbor notifications, we don't switch into the `PhaseState`, leading to issues where the `PhaseTracker` tries to close out other phase states which then causes cascading failures of other phase states (whether they're unwinding, parented neighbor notifications, packet processing, tick processing, etc.). Will hopefully either have fixed both the recursive nature of neighbor processing in the build including [this commit](https://github.com/SpongePowered/SpongeForge/commit/fdf88ef5432fa132e394da931b1afe4177073497), and then lastly, the actual issue causing cascading failure with [this commit](https://github.com/SpongePowered/SpongeCommon/commit/6c3bc4bd3c4dc706f8ab47ef0164a11c3d31e0c0) ultimately leading to the crash due to [this line specifically](https://github.com/SpongePowered/SpongeCommon/commit/6c3bc4bd3c4dc706f8ab47ef0164a11c3d31e0c0#diff-887da76c98bfd683f387bc220c615dc9L297).
