### ISSUE TITLE
Advancements disappear occasionally 

### ISSUE THREAD

**Issue by krisjenner** [SpongePowered/SpongeForge#2707]
**I am currently running**

- SpongeForge version: RC3616
- Forge version: 2831
- Java version: 1.8
- Operating System:W10

**Issue Description**
The advancements book on Skyfactory 4 will randomly go blank for all players and will only be fixed on running /reload

probably the same thing as https://github.com/SpongePowered/SpongeForge/issues/2503 so sorry if duplicate

**Comment by phit** [comment]
yes, please post any additional info in the other issue
