### ISSUE TITLE
primitive mobs do not spawn When sponge is installed 

### ISSUE THREAD

**Issue by dezil** [SpongePowered/SpongeForge#2711]
I am currently running

- SpongeForge version: 1.12.2-2768-7.1.6-RC3671

- Forge version: 14.23.5.2836

-Java version: 1.8.0_212 | 1.8.0_201

-Operating System: Windows 10 1809 Build 17763.437 | Ubuntu 18.04 LTS

Plugins/Mods: Primitive Mobs, Multi Mob Library

issue description: no mobs from Primitive mobs spawn

expected behavior: mobs should spawn and do so with out Sponge Forge 

they also dont spawn in 3616

**Comment by gabizou** [comment]
Are there any log messages?

**Comment by xElementzx** [comment]
As i did the testing for dezil
https://gist.github.com/27549923f4813c7bcb101adb6a1872c3 here is a log file, nothing from primitive mobs in it

**Comment by dezil** [comment]
a config change in multi mob library has fixed this issue 

   S:_BewitchedTome=MULTIMOBMONSTER
    S:_BewitchedTome_Stronghold=MULTIMOBMONSTER
    S:_BlazingJuggernaut=MULTIMOBMONSTER
    S:_BrainSlime_Beach=MULTIMOBMONSTER
    S:_Chameleon_Forest=MULTIMOBPASSIVE
    S:_Chameleon_Jungle=MULTIMOBPASSIVE 

to
  S:_BewitchedTome=MONSTER
  S:_BewitchedTome_Stronghold=MONSTER
    S:_BlazingJuggernaut=MONSTER
    S:_BrainSlime_Beach=MONSTER
    S:_Chameleon_Forest=PASSIVE
    S:_Chameleon_Jungle=PASSIVE 

for the entire list

**Comment by SheroxGG** [comment]
I tried doing that and it is still not working! Any idea??

**Comment by KookosPahkina** [comment]
Yeah this doesn't seem to fix it anymore

**Comment by KookosPahkina** [comment]
> I tried doing that and it is still not working! Any idea??

did you happen to find a fix by any chance?

**Comment by SheroxGG** [comment]
I didnt find any thing, but I cant understand why for example mo creatures mobs spawn and primitive dont. Same happens with some rustic trees and other mods items. Dont quite understand.
