### ISSUE TITLE
Phase Context error - breaks most furnace type blocks

### ISSUE THREAD

**Issue by Yorkforce** [SpongePowered/SpongeForge#2713]
**I am currently running**
- SpongeForge version: 3671
- Forge version: 2831

- Plugins/Mods:
Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, Aliases, AntiWDL, AurionsVoteListener, AutoBroadcaster, CatClearLag, Discord Bridge, EconomyLite, Enjin Minecraft Plugin, GriefPrevention, LuckPerms, MMCRestrict, MultiChatSponge, NuVotifier, Nucleus, Player Glow, PlayerShopsRPG, PwnFilter, RankUpper, SkyClaims

Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, Advancement Book, Animal Crops, Apotheosis, AppleCore, AppleSkin, Applied Energistics 2, Aroma1997Core, B.A.S.E, BNBGamingLib, Barrels, Drums, Storage & More, Baubles, Bed Patch, BiblioCraft, BnBGamingCore, Bonsai Trees, Bookshelf, Building Gadgets, Caliper, Calm Down Zombie Guy, Ceramics, Chargers, ChineseWorkshop, Chisel, Chisels & Bits, Click Machine, Clumps, CoFH Core, CoFH World, CodeChicken Lib, ComPatchedStorage, CommonCapabilities, Compact Machines 3, CompactStorage, Construct's Armory, ContentTweaker, Cooking for Blockheads, Corail Tombstone, CraftTweaker JEI Support, CraftTweaker2, Cucumber Library, Culinary Construct, Cyclic, Cyclops Core, Dark Utilities, Deep Mob Learning, Dimension Stages, Elevator Mod, Ender Crop, Ender Utilities, EnderCore, EnderStorage, Extended Crafting, Extra Cells 2, Extra Cells Patch, Farming for Blockheads, FastFurnace, FastWorkbench, Fence Overhaul, FindMe, Flux Networks, FoamFix, FoamFixCore, Forge Microblocks, Forge Multipart CBE, Forgiving Void, Game Stages, Guide-API, Headcrumbs, Horse Power, Hunting Dimension, HydroGel, InControl, Industrial Foregoing, Inspirations, Integrated Dynamics, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTunnels-Compat, Iron Jetpacks, Item Stages, JourneyMap, Just Enough Items, KleeSlabs, Limitless Structure Blocks, MCMultiPart, MTLib, MalisisCore, MalisisDoors, Mantle, MatterOverdrive: Legacy Edition, McJtyLib, Mekanism, MekanismGenerators, Mercurius, Minecraft Multipart Plugin, Mob Stages, Mod Tweaker, ModPack Basic Tools, ModPack Utilities, More Buckets, More Cauldrons, Morpheus, Mystcraft, Mystical Agradditions, Mystical Agriculture, NuclearCraft, OG Dragon+, OpenComputers, OpenComputers (Core), OpenComputers Xnet Driver, OreExcavation, Parabox, Pickle Tweaks, PigUtils, Pipe Master 2000, Placebo, PortalGun, Practical Logistics 2, Prestige, Primitive Crafting, ProjectE, RFToolsPower, Ranged Pumps, Real Filing Cabinet, RecipeStages, Redstone Flux, Resource Hogs, Rustic, Shadowfacts' Forgelin, Simple Generators, Simple Inventory sorting, Simple Storage Network, Sky Grid, SkyBonsais, Slab Machines, SlimyBoyos, Smooth Font Core, Snad, SonarCore, SpongeForge, Squeezer Patch, Statues mod, Stuff A Sock In It, Super Sound Muffler, Surge, SwingThroughGrass, Sync, TallGates, TelePastries, Tesla Core Lib, Tesla Core Lib Registries, The Lost Cities, The Twilight Forest, The Weirding Gadget, Thermal Dynamics, Thermal Foundation, Thermal Innovation, Tinkers Tool Leveling, Tinkers' Complement, Tinkers' Construct, Tiny Progressions, Topography, TorchMaster, Translocators, Tree Growing Simulator 2016, Triumph, Twitchcrumbs, Universal Modifiers, Valkyrie Lib, ViesCraft, Waddles, Waila, Waila Stages, Wall-Jump!, What Are We Looking At, Wither Crumbs, World Utils, WorldEdit, XL Food Mod, XNet, YNot, Yoyos, ZenStages, bouncy_creepers, mob_grinding_utils, sky_orchards, uppers

**Issue Description**

Currently getting a PhaseContext error, it appears to be caused by many different things, in this case it was caused by ore excavating a tree. In another case a Cyclic clock.

When this occurs, it breaks all fluids, water doesnt flow etc. Only a server restart fixes the problem.

https://pastebin.com/YuTPvJxA

**Comment by Yorkforce** [comment]
Heres another one

https://pastebin.com/3PKDb9fN

**Comment by Yorkforce** [comment]
another on spongeforge 3689:
https://pastebin.com/JK1fyidX

Also breaks furnaces and manufactory, and tons of other stuff. :(

**Comment by gabizou** [comment]
Is there a full server log? It might be there's something happening far sooner that ends up causing this issue.

**Comment by Yorkforce** [comment]
I don't have a full log of the above error @gabizou but #2730 seems to be related to this and I have included a full server log in that issue, the outcome is exactly the same in both cases the manufactory and other nuclearcraft machines, including the vanilla furnace (using the fastfurnace sponge fix) cant be interacted with at all.

Also cauldrons start acting weird, some automatically fill up with water, other times it takes multiple amounts of cobble to make lava instead of the usual 4 blocks required.
Other times water and lava stop flowing.

In all cases only a full server restart will put things back to normal, until another phase type error occurs.

**Comment by Yorkforce** [comment]
Got another one, this time we disabled fastfurnace just to make sure it wasnt the cause, unfortunately it wasnt.

https://pastebin.com/CSwq9HSS

[latest.log](https://github.com/SpongePowered/SpongeForge/files/3144653/latest.log)

I have also updated the title to better reflect the issue, lava and water flow seems to be working ok now since we updated to spongeforge 3989 or possibly lower version.

**Comment by Yorkforce** [comment]
Do you want me to keep posting errors and logs @gabizou ?
