### ISSUE TITLE
Prestige + reset progress = spam

### ISSUE THREAD

**Issue by HeberonYT** [SpongePowered/SpongeForge#2717]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2768-7.1.6-RC3679.jar

- Plugins/Mods: SkyFactory 4 (v4.0.2)

**Issue Description**
I am using version RC3679 where the unlock of mods and recipes of the Prestige system has been solved, but I'm having a lot of spam on the console when someone does reset their prestige progress.
A prestige reset is required to unlock the characteristics of users who were stuck before updating sponge.

log: https://pastebin.com/raw/3ZnhLkQP

That only happens when the progress is reset from the prestige interface, the option works, but throws that message to the console

**Comment by phit** [comment]
log is thrown as a warning to inform you about a mod issue, added for https://github.com/SpongePowered/SpongeCommon/commit/2334697508ab9df37d3e35e51247ada6006b5d65#diff-9b4faa20f42570483c84b4a3c7d5876dR56
