### ISSUE TITLE
Mobs not dropping experience when killed by tamed Dogs from Doggy Talents

### ISSUE THREAD

**Issue by zukane2** [SpongePowered/SpongeForge#2718]
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2768-7.1.5.jar
- Forge version: forge-14.23.5.2825
- Java version: 1.12.2
- Operating System: Windows 10

- Plugins/Mods: Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AppleSkin, AstikorCarts, AutoRegLib, Better Combat Rebirth, Better Records, Biome Bundle, Carry On, Chameleon, ChickenChunks, Clumps, CodeChicken Lib, Cooking for Blockheads, CosmicLib, CreativeCore, CreativeCoreDummy, Decocraft, Doggy Talents, Dungeons2!, GottschCore, Gravestone Mod, Hammer Core, Inventory Tweaks, ItemPhysic, Just Enough Items, LLibrary, MalisisCore, MalisisDoors, MorePlayerModels, Mowzie's Mobs, OTG Core, Open Terrain Generator, OreLib Support Mod, Pam's HarvestCraft, Quark, Roguelike Dungeons, Shadowfacts' Forgelin, SpongeForge, Storage Drawers, Tree Chopper, Village Info Mod, Visuals, Wearable Backpacks, XP From Harvest, customxp

**Issue Description** When I was only using Forge in my server mobs drop exp when they are killed by Dogs from Doggy Talents even without me hitting the mob. After migrating from Forge to SpongeForge the mobs stop dropping experience when killed by Dogs from DoggyTalents. although skeletons do drop experience when killed by normal tamed wolf (Non-Doggy Talents)

https://gist.github.com/zukane2/236e3bae25c0f1a8c6f32d6ee267f3aa

**Comment by Zidane** [comment]
Tried this with latest SF, Forge, and Doggy Talents and had a trained Dog attack a mob and it dropped XP orbs.
