### ISSUE TITLE
Custom entity damageEntity method ignored

### ISSUE THREAD

**Issue by Naomiora** [SpongePowered/SpongeForge#2719]
- SpongeForge version: 1.12.2-2768-7.1.5
- Forge version: 1.12.2 - 14.23.5.2836
- Java version: 1.8 (don't know the exact version)
- Operating System: 

- Mods: Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, CodeChicken Lib, CoroUtil Library, Extended Mod Config, Extended Renderer, Flan's Mod, Flan's Mod: Apocalypse, Forge Microblocks, Forge Multipart CBE, InvisibLights, Localized Weather & Storms, Minecraft Multipart Plugin, MorePlayerModels, MrCrayfish's Furniture Mod, SCP: Lockdown, SecurityCraft, SpongeForge, WorldEdit, scp-addons gr (my custom mod)

- Plugins: Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, CubeEngine - LibCube, LuckPerms, Nucleus

**Issue Description**
In my own mod (source can be found here: https://github.com/Naomiora/scpaddons), I made an entity called "SCP-682" (found in entity/entity682). It overrides the damageEntity method from EntityLivingBase. This works as intended, until SpongeForge is installed on the server, then suddenly this specific part of my entity doesn't seem to function anymore.

(There are no logs which display any information about this, and it doesn't crash the server/client either.)

**Comment by ImMorpheus** [comment]
Yep, we're overwriting attackEntityFrom and calling our own damageEntity.
If a mod overrides that method, it's simply not called.
https://github.com/SpongePowered/SpongeCommon/blob/cc13221f1e6d1b0b7388df50a2b0bf8a362bfeb1/src/main/java/org/spongepowered/common/mixin/core/entity/MixinEntityLivingBase.java#L522

Same thing as https://github.com/SpongePowered/SpongeForge/issues/2546

**Comment by Naomiora** [comment]
Is there a work-around currently available that I could use currently?
