### ISSUE TITLE
NPE when advancements are reloaded by world load with pixelmon

### ISSUE THREAD

**Issue by Demiosis** [SpongePowered/SpongeForge#2720]
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2768-7.1.6-RC3616
- Forge version: forge-1.12.2-14.23.5.2768-universal
- Java version: jre-8u211-windows-x64
- Operating System: Windows 10

- Plugins/Mods:
LuckPerms-Sponge-4.3.109
Nucleus-1.9.3-S7.1-MC1.12.2-plugin
Pixelmon-1.12.2-7.0.5-universal
spongeforge-1.12.2-2768-7.1.6-RC3616

When using the world load command as a player, command block or in the console when one or more players are logged in it return me a null command, tried it on a Custom world, on the Nether and the End as well.

This is a nucleus command and if all players log off I can use the command in the console and it WILL work.

Seem this bug is related to pixelmon since if I remove the mod the aforementioned limitations are now gone and everything work as it should be.

[2019-04-27-6.log](https://github.com/SpongePowered/SpongeForge/files/3124394/2019-04-27-6.log)

https://gist.github.com/phit/900026d133145b9e4ce31ccf5be66ed5

Note: in this log I have my full mods/plugins package but as stated earlier I already isolated the conflict but if you want the mod/plugins list at that moment , here it is:

- Plugins/Mods:
CraftTweaker2-1.12-4.1.6
gameshark-1.12.2-5.2.1-universal
griefprevention-1.12.2-4.3.0.688
HyperModBanner-1.12.2-3.3.0
LuckPerms-Sponge-4.3.109
Mirage-1.3.8
Nucleus-1.9.3-S7.1-MC1.12.2-plugin
PixelExtras-1.12.2-2.4.3-universal
Pixelmon-1.12.2-7.0.5-universal
PokeBattleClauses-1.2.0
spongeforge-1.12.2-2768-7.1.6-RC3616
teleportonlogout-1.0.0
TrainerCommands-1.12.2-2.5.0-universal

**Comment by phit** [comment]
please retest with 1.12.2-2768-7.1.6-RC3680

**Comment by Demiosis** [comment]
Updated to 1.12.2-2768-7.1.6-RC3680  Tried the same exact thing as stated above with this mod/plugin list:
LuckPerms-Sponge-4.3.109
Nucleus-1.9.3-S7.1-MC1.12.2-plugin
Pixelmon-1.12.2-7.0.5-universal
spongeforge-1.12.2-2768-7.1.6-RC3680

Problem still persist 

[2019-04-28-4.log](https://github.com/SpongePowered/SpongeForge/files/3125273/2019-04-28-4.log)


[debug.log](https://github.com/SpongePowered/SpongeForge/files/3125274/debug.log)

These are the latest logs with only the 4 mods/plugins listed

**Comment by phit** [comment]
thanks, relevant section https://gist.github.com/phit/ccbefab2cb819e12ad080cc170b488ea

**Comment by Zidane** [comment]
I have not been able to reproduce this. Anyone else?

**Comment by Zidane** [comment]
Closing until someone replies back that they can reproduce this and give us steps how.
