### ISSUE TITLE
Phase Context Issues

### ISSUE THREAD

**Issue by calgray** [SpongePowered/SpongeForge#2721]
**I am currently running**

- SpongeForge version: 1.12.2-2768-7.1.5
- Forge version: 14.23.5.2768
- Java version: 1.8.0_51
- Operating System: Windows 10

- Plugins/Mods:
Mods (52): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, Applied Energistics 2, Baubles, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, ChickenChunks, CodeChicken Lib, ComputerCraft, Discord Chat, Forestry, Forge Microblocks, Forge Multipart CBE, Galacticraft Core, Galacticraft Planets, Gravitation Suite, IndustrialCraft 2, Just Enough Items, MCMultiPart, MJRLegendsLib, MagicBees, Micdoodle8 Core, Minecraft Multipart Plugin, MrTJPCore, Not Enough Items, OpenComputers, OpenComputers (Core), ProjectRed Core, ProjectRed Expansion, ProjectRed Exploration, ProjectRed Fabrication, ProjectRed Illumination, ProjectRed Relocation, ProjectRed Transmission, ProjectRed Transportation, ProjectRed integration, Rustic, Rustic Thaumaturgy, SpongeForge, Thaumcraft, Thaumic Computers, Thaumic Energistics, Thaumic Terminal, WorldEdit

Plugins (8): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, GriefPrevention, LuckPerms, Total Economy, YourCustomPaintings

**Issue Description**
 
Getting crashes flying and opening the inventory every minute or so.

Crash 1: https://gist.github.com/nallack/e5343fc1379cc8b06c030d8e88c2fc6b
Crash 2: https://gist.github.com/nallack/39a0a5e33e89e11473c1c502b74f72c1
Crash 2 Server Log: https://gist.github.com/nallack/b68500fa1f8df8755ce3d1608a0b929f

**Comment by calgray** [comment]
It appears running spongeforge in connected client causes this..

**Comment by phit** [comment]
please update sponge, also you don't need sponge on the client
