### ISSUE TITLE
Server Crash Time Out

### ISSUE THREAD

**Issue by HeberonYT** [SpongePowered/SpongeForge#2722]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2768-7.1.6-RC3682
- Forge version: 14.23.5.2831
- Java version: 1.8.0_201
- Operating System: Centos7

- Plugins/Mods: Modpack SkyFactory 4 (v4.0.2)

**Issue Description**
Our server is crashing randomly. There is no specific procedure to reproduce the problem

https://pastebin.com/raw/Z1kXhUA4

**Comment by phit** [comment]
https://github.com/SpongePowered/SpongeForge/issues/2688
