### ISSUE TITLE
Conflict with mod Applied Energistics 2.

### ISSUE THREAD

**Issue by SawFowl** [SpongePowered/SpongeForge#2724]
**I am currently running**
- SpongeForge version: 1.12.2-2768-7.1.6-RC3679
- Forge version:  14.23.5.2836
- Java version: OpenJDK 64-Bit Server VM (build 25.212-b01, mixed mode)
- Operating System: Debian 9

- Mods (59): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AE2 Stuff, AI Improvements, Applied Energistics 2, BD Lib, Better Questing, BiblioCraft, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, CoFH Core, CoFH World, CodeChicken Lib, Console Filter, Construct's Armory, CraftTweaker JEI Support, CraftTweaker2, CreativeCore, CreativeCoreDummy, CustomNPCs, Ex Nihilo Creatio, Fast Leaf Decay, Fishing Net Mod, Forestry, Future MC, HoloInventory, Iron Chest, Just Enough Items, LagGoggles, MTLib, Mantle, McJtyLib, Mekanism, Mod Tweaker, PortalGun, Redstone Arsenal, Redstone Flux, Shadowfacts' Forgelin, SpongeForge, Standard Expansion, Thermal Expansion, Thermal Foundation, Thermal Innovation, Thermal Tinkering, Tinkers' Construct, Tree Chopper, UniDict, Vanilla Builders Extension, WanionLib, XNet, iChunUtil
- Plugins (26): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge,  FastAsyncWorldEdit, BeanCore, CatClearLag, Command Sync, DupeFixer, EconomyLite, GriefPrevention, GuiShopManager, Holograms, HuskyCrates, HuskyUI, LuckPerms, Nucleus, ProjectCore, SkyClaims, StackBan, UltimateChat, UniversalMarket, VirtualTool, Wasted, WorldEdit, spark

**Issue Description**
It seems that the problem occurs when unloading chunks. It is also noted that the cables from this and similar mods become beaten and stop working.

Errors -> https://gist.github.com/Mr-Krab/2324e8a1530e7a49fed85150b9354d90

[full logs.zip](https://github.com/SpongePowered/SpongeForge/files/3127971/full.logs.zip)

**Comment by gabizou** [comment]
Retest with 1.12.2-2825-7.1.6-RC3699 It should fix  this issue or produce different results/logs. If it still throws errors, please upload new logs.

**Comment by phit** [comment]
couldn't reproduce on 1.12.2-2825-7.1.6-RC3701
build a small network across 3 chunks, left the area and waited for the area to unload and verified it by having a looping command block in the area

nothing in the console/logs
