### ISSUE TITLE
Server crash with blockstate change

### ISSUE THREAD

**Issue by krisjenner** [SpongePowered/SpongeForge#2726]
**I am currently running**

- SpongeForge version: 7.1.6-RC3682.jar Forge version: 
- Java version: 1.8
- Operating System: W10

- Plugins/Mods:
Plugins (29): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, ActiveTime, Broadcast, CarrotShop, CatClearLag, Enjin Minecraft Plugin, EntityParticles, Giveaways, GriefPrevention, Holograms, HuskyCrates, HuskyUI, Lottery, LuckPerms, MMCReboot, MMCRestrict, MagiBridge, MaintenanceSponge, Nucleus, PetBlocks, Player Glow, Prism, SkinChanger, Slash Discord, Total Economy, spark

Mods: SkyFactory4 4.0.3

**Issue Description**

Player connects near these blocks and server instantly crashes 

https://gist.github.com/krisjenner/a1a4d557d5bb8a0c4f9c065b4ca101cb

**Comment by phit** [comment]
https://github.com/SpongePowered/SpongeForge/issues/2706
