### ISSUE TITLE
NuclearCraft machines eject upgrades

### ISSUE THREAD

**Issue by krisjenner** [SpongePowered/SpongeForge#2727]
**I am currently running**

- SpongeForge version: 7.1.6-RC3682
- Forge version: 2831
- Java version: 1.8
- Operating System: W10

- Plugins/Mods:
Plugins (29): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, ActiveTime, Broadcast, CarrotShop, CatClearLag, Enjin Minecraft Plugin, EntityParticles, Giveaways, GriefPrevention, Holograms, HuskyCrates, HuskyUI, Lottery, LuckPerms, MMCReboot, MMCRestrict, MagiBridge, MaintenanceSponge, Nucleus, PetBlocks, Player Glow, Prism, SkinChanger, Slash Discord, Total Economy, spark

**Issue Description**
On RC3682 putting upgrades in to NuclearCraft machines doesn't work and they will eject them instantly

Unsure if log would help but let me know if so.

**Comment by CaptainSisko** [comment]
This is the same issue that i have reported [here](https://github.com/SpongePowered/SpongeForge/issues/2725).

The issue is effecting both default Minecraft Furnaces and NuclearCraft.
