### ISSUE TITLE
Dynamic Trees: ThaumCraft - PhaseTracker

### ISSUE THREAD

**Issue by LeonPhilips** [SpongePowered/SpongeForge#2729]
**I am currently running**
- SpongeForge version: `1.12.2-2768-7.1.6-RC3643`
- Forge version: `14.23.5.2768`
- Java version: 
```
openjdk version "1.8.0_201"
OpenJDK Runtime Environment (build 1.8.0_201-b09)
OpenJDK 64-Bit Server VM (build 25.201-b09, mixed mode)
```
- Operating System: Fedora 29, `Linux 5.0.9-200.fc29.x86_64 GNU/Linux`

- Plugins/Mods:
Mods (122): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, A Lib, Advanced Rocketry, Advanced Rocketry Core, Advanced Solar Panels, AlcatrazCore, Alchemistry, Animania, Applied Energistics 2, ArchitectureCraft, Atomic Science, B.A.S.E, Baubles, BiomeTweaker, BiomeTweakerCore, Biomes O' Plenty, CC: Tweaked, CC: Tweaked, Chisels & Bits, CoFH Core, CoFH World, CodeChicken Lib, CommonCapabilities, Compact Machines 3, CraftStudio API, CraftTweaker JEI Support, CraftTweaker2, Custom Stuff 4, Cyclops Core, Dynamic Dynamos, **Dynamic Trees**, Dynamic Trees BOP, **Dynamic Trees TC**, Ender Crop, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, Engineer's Doors, Ex Nihilo Creatio, Extreme Reactors, FTB Utilities, FTBLib, Forge Microblocks, Forge Multipart CBE, GregTech Community Edition, Guidebook, IC2Magma, Immersive Cables, Immersive Engineering, Immersive IO, Immersive Petroleum, Immersive Posts, Industrial Foregoing, Industrial Wires, IndustrialCraft 2, Integrated Dynamics, IntegratedDynamics-Compat, Integration Foregoing, Inventory Tweaks, Iron Chest, Just Enough Items, LagGoggles, MTLib, MachineMuse's Modular Powersuits, Mantle, Mekanica, Mekanica: Generators, Mekanica: Tools, MineTweakerRecipeMaker, Minecraft Multipart Plugin, Modular Diversity, Modular Machinery, MrTJPCore, NuclearCraft, Numina, OpenBlocks, OpenComputers, OpenComputers (Core), OpenModsLib, OpenModsLib Core, OreExcavation, Oreberries, ProjectRed Core, ProjectRed Exploration, ProjectRed Illumination, Prospectors, Realistic Terrain Generation, Redstone Flux, Shadowfacts' Forgelin, **SpongeForge**, Steam Age Revolution, Tesla Core Lib, Tesla Core Lib Registries, **Thaumcraft**, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Tinker's Forging, Tinker's JEI, Tinkers' Complement, Tinkers' Construct, UniDict, Vulpes library, Waila, WanionLib, Waterworks, What Are We Looking At, Zero CORE

**Issue Description**
![image](https://user-images.githubusercontent.com/13693773/57115565-04fcd300-6d50-11e9-9d85-c30a663c939b.png)
Chopping down a Dynamic Trees greatwood tree at the base seems to cause this exception. After the exception has printed, one of three things can happen:
* The server continues as normal
* The server hangs for just under a minute, timing everyone out.
* The server prints a huge list of block positions and their state (Log file was 168 megabytes and looked like the output wrapped around, rendering it useless)

The block position in the stacktrace included in the gist points to the block just above the 'rooty soil' by Dynamic Trees.

There's not much to go on here, since it's hard to reproduce the outcome of chopping a tree down reliably. I am hoping that this stack trace is enough information. If it isn't: I can do a more controlled test and come back to this.

Note that the debug log attached in the gist is a different one mentioned in this report (No printed blockstates) as that log has become unreadable.
___

[GIST
](https://gist.github.com/TerminatorNL/dcbd599fb7d8f4bd1cad118e50543522)
Debug.log is truncated, click [here](https://gist.githubusercontent.com/TerminatorNL/dcbd599fb7d8f4bd1cad118e50543522/raw/583e2a03bb2fa3675407c4896040135a3b9223fb/debug.log) for the full debug.log

Thanks in advance.

**Comment by phit** [comment]
update sponge please and see if it still happens, the build you are running is quite outdated
https://www.spongepowered.org/downloads/spongeforge/stable/1.12.2

**Comment by LeonPhilips** [comment]
The issue persists after updating.

There are multiple exceptions in here, I have included them in a new [gist](https://gist.github.com/TerminatorNL/ad653258825b28075096764d2688fc6e).

This log was created with `spongeforge-1.12.2-2825-7.1.6-RC3692.jar`
Please note I the forge version still is `14.23.5.2768`. The modpack requires this.

**Edit:**
Forgot to mention, this file is also truncated. Click [here](https://gist.github.com/TerminatorNL/ad653258825b28075096764d2688fc6e/raw/baae2e488fc20b6eb4ef69024eabae525576aff9/Debug2.log) for the full log

**Comment by LeonPhilips** [comment]
Confirmed working! Thanks a bunch

Minecraft: `1.12.2`
SpongeAPI: `7.1.0-3fdbf299`
Sponge: `1.12.2-7.1.6-SNAPSHOT`
SpongeForge: `1.12.2-2825-7.1.6-RC3698`
Minecraft Forge: `14.23.5.2825` <- updated
