### ISSUE TITLE
Maximum block processing depth exceeded

### ISSUE THREAD

**Issue by Yorkforce** [SpongePowered/SpongeForge#2730]
**I am currently running**
- SpongeForge version: 3690
- Forge version: 2831
- Java version: 8
- Operating System: Debian 9

- Plugins:
Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, Aliases, AntiWDL, AurionsVoteListener, AutoBroadcaster, CatClearLag, Discord Bridge, EconomyLite, Enjin Minecraft Plugin, GriefPrevention, LuckPerms, MMCRestrict, MultiChatSponge, NuVotifier, Nucleus, Player Glow, PlayerShopsRPG, PwnFilter, RankUpper, SkyClaims

- Mods: 
SF4

**Issue Description**
Maximum block processing depth exceeded error
Results in nuclearcraft machines and furnaces (and probably alot more things) becoming un-interactable, the gui cant be opened, anything inside gets deleted.

https://pastebin.com/SS2vSQkP

Full server log:
[latest.log](https://github.com/SpongePowered/SpongeForge/files/3140553/latest.log)

**Comment by phit** [comment]
https://github.com/SpongePowered/SpongeCommon/issues/2252
