### ISSUE TITLE
Cannot Craft Items with dropping items

### ISSUE THREAD

**Issue by MakkuroJoKeRGod** [SpongePowered/SpongeForge#2731]
**I am currently running**

- SpongeForge version: 1.12.2-2768-7.1.5
- Forge version: 2836
- Java version: Version 8 Update 211
- Operating System: Windows 10 Home

- Plugins/Mods: SpongeForge, AstralSorcery-1.12.2-1.10.17, Baubles-1.12-1.5.2.jar

**Issue Description**
I cannot craft anything that requires me to drop items on the ground or in liquid. For example, in the mod Astral Sorcery, I need to form a Celestial Crystal (A block) by dropping a Rock Crystal and one Stardust into Liquid Starlight. This is also the case when I restarted the server with only Industrial Craft 2 and Applied Energistics 2, where I needed to get a fluix crystal by dropping one nether quartz, one redstone and one charged certus quartz crystal into water. In both cases, the dropped items would stay in the liquid forever and would never turn into the desired item/block. In short, I cannot get my desired item/results despite dropping the right items in the right place.

There is no crash, just an issue that prevents us players from progressing in the mod.

**Comment by phit** [comment]
unable to reproduce on 1.12.2-2825-7.1.6-RC3692, please update

**Comment by MakkuroJoKeRGod** [comment]
> 
> 
> unable to reproduce on 1.12.2-2825-7.1.6-RC3692, please update

I have tried it with the latest version as I am writing this reply (RC3693) but I still encountered this issue, I tried crafting the said item with a new world on a fresh server as well but it does not work. Did you try it with Astral Sorcery specifically or did you use other mods?

**Comment by phit** [comment]
I tested the Applied Energistics 2 fluix crystals

**Comment by MakkuroJoKeRGod** [comment]
If that is the case, I think sponge is having issues with Astral Sorcery specifically and that in turn causes problems when we try to craft fluix crystals in Applied Energistics. The process of forming celestial crystal only takes a few seconds after the stardust and the rock crystals are dropped into liquid starlight under a floating crystal.

**Comment by phit** [comment]
I had Astral Sorcery on the server I tested, I just forgot to test the crystal too. Will test again later today.

**Comment by MakkuroJoKeRGod** [comment]
Hi, sorry for disturbing @phit, but have you tested out the celestial crystal process with sponge? I would also like to add that I tried making fluix crystals with only spongeforge, Industrial Craft 2 and Applied Energistics 2 installed and it still does not work.

**Comment by phit** [comment]
can you post your global.conf

**Comment by MakkuroJoKeRGod** [comment]
[global conf.zip](https://github.com/SpongePowered/SpongeForge/files/3155595/global.conf.zip)

**Comment by phit** [comment]
still wasn't able to reproduce this 
![](https://i.imgur.com/8PSpF95.png)

fresh world and sponge configs, both the crystal and fluix works fine, also tried it on my personal server running enigmatica 2 and it also worked there

**Comment by MakkuroJoKeRGod** [comment]
@phit okay I found the issue, turns out Nucleus is required to make those stuff work. Has anybody mentioned that Nucleus is a required plugin for those who wish to use AE2 and/or astral sorcery? I honestly do not know about this. If you don't mind, I would like to hear why Nucleus affects the "Drop crafting system". 
Thanks for everything, I highly appreciate it!

**Comment by phit** [comment]
yeah thats definitely not intentional!

@gabizou looks like we aren't firing forge events when there's no sponge plugin listening for the equivalent
