### ISSUE TITLE
#something isn't completing a phase!!!

### ISSUE THREAD

**Issue by LANCECHEN117** [SpongePowered/SpongeForge#2734]
**I am currently running**
- SpongeForge version: 1.12.2-2825-7.1.6-RC3692
- Forge version: 14.23.5.2825
- Java version: JRE8-64-202
- Operating System:Win10

- Plugins/Mods:
tconstruct{1.12.2-2.12.0.135} 
techguns{2.0.2.0} 
mmorpg{1.5.1}  
toughasnails{3.1.0.139} 

When I killed the zombie in one shoot with Tconstruct' Cleaver (which increases the chance of mob dropping head), the server lagged and steped in an error loop.
 
This might happen only when the zombie drops his head

[Crash logs.txt](https://github.com/SpongePowered/SpongeForge/files/3144042/Crash.logs.txt)
[debug.log](https://github.com/SpongePowered/SpongeForge/files/3144293/debug.log) 
[latest.log](https://github.com/SpongePowered/SpongeForge/files/3144294/latest.log)

Error starts at 7:24:41

**Comment by phit** [comment]
please attach your debug.log

**Comment by LANCECHEN117** [comment]
> 
> 
> please attach your debug.l
attached, sir

**Comment by LANCECHEN117** [comment]
> 
> 
> please attach your debug.log

attached sir.
