### ISSUE TITLE
Block Snapshot Causing crash.

### ISSUE THREAD

**Issue by DragonSlayer696** [SpongePowered/SpongeForge#2738]
**I am currently running spongeforge-1.12.2-2768-7.1.6-RC3637**

- SpongeForge version: spongeforge-1.12.2-2768-7.1.6-RC3637
- Forge version: 13.23.5.2815
- Java version:I am unsure how to check for this. 
- Operating System:All I know is my server uses Multicraft.

- Plugins/Mods Gathered with the /sponge mods and plugins command :https://gyazo.com/4ab73918ab1629d2327cdc554ac06fdb
https://gyazo.com/cb27eff93b786efc03ba81c6bb75c70e
https://gyazo.com/a223c65c79383aacf811648cbd6b1120
https://gyazo.com/8841fbd9f78ba632ef12d0023593b3c8
https://gyazo.com/d1dff6e167a580f15aacdbbf52f50bcd

Plugins:https://gyazo.com/a6c09432c708597868efe53217cd9090

I have no clue how to recreate this issue all I know is after a few weeks of the server working fine, I suddenly crash about after every 10 minuets, Looking at the error log I saw this error from Ancient warfare before the crash :https://pastebin.com/Q4xCPQTy
 in another part of the error it says: [18:57:48] [Server thread/INFO] [ancientwarfarestructure]: Generated structure: OrcRaidersGeneric at -1900, 84, -1405, time: 3ms
Which is like right next door on top of the structure that is already at coodinates in the pastebin
![2019-05-03_18 29 54](https://user-images.githubusercontent.com/46175643/57186247-e8b87d80-6e98-11e9-989e-7baeebd93c91.png)
where im standing is where the orc structure tried to generate and the waypoint is the in the pastebin
The mod devs of AW said it was a issue on sponge and I am hoping to figure out how exactly to fix this because Ancient warfare is the core of my modpack and I don't want to remove it if i can.
[2019-05-03-7.log](https://github.com/SpongePowered/SpongeForge/files/3144990/2019-05-03-7.log)
Here is the full log if you need it.
If there is anything I can do to give more detail please let me know I am very invested into this server and I have put a lot of effort into it currently sitting in offline mode to prevent further harm until this is fixed.

**Comment by gabizou** [comment]
> * spongeforge-1.12.2-2768-7.1.6-RC3637

This is an extremely old buggy version. There's newer versions available, retest with newer or 3616.

**Comment by DragonSlayer696** [comment]
Done and now it works thank you.
