### ISSUE TITLE
Lich King not dropping loot

### ISSUE THREAD

**Issue by Yorkforce** [SpongePowered/SpongeForge#2739]
**I am currently running**

- SpongeForge version: 3689
- Forge version: 2831
- Java version: 8
- Operating System: Debian 9

- Plugins:
Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, Aliases, AntiWDL, AurionsVoteListener, AutoBroadcaster, CatClearLag, Discord Bridge, EconomyLite, Enjin Minecraft Plugin, GriefPrevention, LuckPerms, MMCRestrict, MultiChatSponge, NuVotifier, Nucleus, Player Glow, PlayerShopsRPG, PwnFilter, RankUpper, SkyClaims

- Mods: 
SF4

**Issue Description**

When killing the Lich King from Twilight Forest he doesnt drop any items on death.
Tested in single player and he does drop items.

**Comment by LANCECHEN117** [comment]
Move away catclearlag then try
I've fixed this problem by doing so and catclearlag is a old plugin which needs update, so try other clear mod

**Comment by Yorkforce** [comment]
catclearlag only removes items every hour, its not that.

**Comment by LANCECHEN117** [comment]
> 
> 
> catclearlag only removes items every hour, its not that.

just try man, catclearlag has big bug when uninstalling trunks which leads to your problem

**Comment by Yorkforce** [comment]
I stand corrected, apologies @LANCECHEN117  I was just surprised it would even do anything unless its actually clearing items during its timer.

It was indeed catclearlag
Thanks man!
