### ISSUE TITLE
Entity Tracking lag

### ISSUE THREAD

**Issue by Raycoms** [SpongePowered/SpongeForge#2741]
**I am currently running**

- SpongeForge version: newest
- Forge version: newest compat
- Java version: newest
- Operating System: linux

Getting heavy lag with entities with sponge on our server
![image](https://user-images.githubusercontent.com/6438347/57346171-e7e74c00-7123-11e9-94e6-8cc8da8a982a.png)

https://sparkprofiler.github.io/?XjckQbKoIk

**Comment by phit** [comment]
newest means nothing, fill out the issue template properly
also thats just the tracking wrapper, the actual time spent is by mobs, click the 39% one none of that is sponge

**Comment by Raycoms** [comment]
1.12.2-2825-7.1.6-RC3694 this one here, and this lag only started appearing after adding in sponge

**Comment by gabizou** [comment]
![Screen Shot 2019-05-07 at 9 08 58 PM](https://user-images.githubusercontent.com/1203877/57348818-764fd380-710c-11e9-82f4-85ef5790471d.png)
Expand the profiler and you'll see the expense isn't sponge, it's just that Sponge wraps around the `entity.onUpdate()` method.
