### ISSUE TITLE
Console Spam and Lag

### ISSUE THREAD

**Issue by HeberonYT** [SpongePowered/SpongeForge#2742]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2825-7.1.6-RC3693.jar
- Forge version: 14.23.5.2831
- Java version: 1.8.0_201
- Operating System: Centos 7

- Plugins/Mods: SkyFactory 4 (v4.0.5)

**Issue Description**
Hi.
Lately I have been receiving a ton of spam in the console of my server, all this text is pite.
Also, since I upgraded sponge my server is running at 10tps, maybe it's a coincidence, but I did not have this problem before.
LagGoogles identified some blocks of users, but even removing everything, the server continued at 10 tps, it seems that the resources are spent internally, I do not know what the reason is.

Log: https://pastebin.com/raw/6wFVYzVb

Log files are generated so large that you can not load them notepad ++

**Comment by HeberonYT** [comment]
By the way, after a while, the server crashes because it does not respond. Currently my server is unplayable.
Here the last 3 reports.
https://pastebin.com/raw/EMNxqLYT
https://pastebin.com/raw/qdLwa803
https://pastebin.com/raw/LMw1CA6v

**Comment by FiveEYZ** [comment]
happens here to
using:
spongeforge-1.12.2-2825-7.1.6-RC3696
forge-1.12.2-14.23.5.2825-universal
FTB Revelation 2.7.0

lastest log can be found here: http://madback.nu/files/minecraft/latest.log
