### ISSUE TITLE
Light Level Not Resetting during a return to Previous BlockSnapshot..

### ISSUE THREAD

**Issue by Cleardragonf** [SpongePowered/SpongeForge#2745]
**I am currently running**

- SpongeForge version:  1.12.2-2705-7.1.0-BEGA-3465
- Forge version: 1.12.2-14.23.5.2816
- Java version: 8
- Operating System: Windows 10

- Plugins/Mods: 
  ExplosionGuard

**Issue Description**
Pretty much I a mod that takes a preexplosion event grabs a BlockSnapshot then places those blocks back afterwards....however..the light level seems to go from 0 to 5 or whatnot almost as if the fire from the explosions is still there...but it's not of course. only way i've been able to fix the light is by filling the area up with blocks then breaking all of them...then putting blocks back the way they were.

**Comment by gabizou** [comment]
> Pretty much I a mod that takes a preexplosion event grabs a BlockSnapshot then places those blocks back afterwards...

Could you explain how you're restoring those `BlockSnapshot`s? I'm almost sure that when restore is used, it's not actually requesting lighting updates because it's restoring...


> * SpongeForge version:  1.12.2-2705-7.1.0-BEGA-3465
> * Forge version: 1.12.2-14.23.5.2816

Also, extremely old versions. We're about 230 builds ahead now....

**Comment by Cleardragonf** [comment]
it's fairly basic but simplistic in a way
```
    public Mend(final List<Location<World>> tansactions) {
        super();
        tansactions.forEach(loc -> blockSnapshot.add(loc.createSnapshot()));
    }

    public void heal(Task t) {
        this.blockSnapshot.forEach(
                bs->bs.restore(true, BlockChangeFlags.NONE)
        );
    }
```

**Comment by Zidane** [comment]
Is it a client-side artifact? When your restore happens, if you log out and in I assume the lighting is fixed?

**Comment by Zidane** [comment]
~move to sc

**Comment by limbo-app** [comment]
Hey @Cleardragonf! I've moved your issue to [SpongePowered/SpongeCommon#2287](https://github.com/SpongePowered/SpongeCommon/issues/2287).
