### ISSUE TITLE
Console spam - latest.log filesize 1GB+ and rising

### ISSUE THREAD

**Issue by Yorkforce** [SpongePowered/SpongeForge#2746]
**I am currently running**
- SpongeForge version: 3701
- Forge version: 2831
- Java version: 8
- Operating System: Debian 9

**Issue Description**

Currently the log is being spammed by this line 2564 times per second:
[Sponge]: Unable to capture transaction from class rustic.common.tileentity.TileEntityCabinet at index 43

latest.log file is currently 1.2GB and climbing after only an hour of being online, this will result in running out of SSD space and corrupting many files and possibly leading to an unrecoverable server.

Cant upload a 1.2GB file.

**Comment by Aaron1011** [comment]
Can you upload a snippet (starting from one `[Sponge]: Unable to capture transaction from class rustic.common.tileentity.TileEntityCabinet` to beginning of the next `[Sponge]: Unable to capture transaction from class rustic.common.tileentity.TileEntityCabinet`)?

**Comment by Yorkforce** [comment]
here you go:

https://pastebin.com/HUAxvuCB

**Comment by Yorkforce** [comment]
Found the actual cabinet ingame, it was sort of full:
![Cabinet](https://user-images.githubusercontent.com/1526195/57557925-b6fd5600-7373-11e9-94a6-f55308288fd2.png)

As soon as I removed a few items the console spam stopped, however when i filled it back up again it started spamming this instead:

https://pastebin.com/ejJTZ4GU

**Comment by Faithcaio** [comment]
Should be fixed with that commit ^
