### ISSUE TITLE
Improved Backpacks crash

### ISSUE THREAD

**Issue by CaptainSisko** [SpongePowered/SpongeForge#2747]
**I am currently running**
**- SpongeForge version:**  
spongeforge-1.12.2-2825-7.1.6-RC3705

**- Forge version:** 
forge-1.12.2-14.23.5.2815-universal.jar

**- Java version:**
1.8.0_201

 **- Plugins/Mods:**
ImprovedBackpacks-1.12.2-1.4.0.0
jei_1.12.2-4.15.0.268

**Issue Description**
Placing an Improved Backpack on the ground with shift + right click crashes the game/server.

I have tested with and without sponge and the crash only occurs with sponge.

Crash log: https://hastebin.com/roleqedahe.php
Launch log: https://hastebin.com/gupuzutoce.md

**Comment by CaptainSisko** [comment]
I have also tested this with spongeforge-1.12.2-2825-7.1.6-RC3708 but have the same results.

I have found that this issue has [been reported to the ImprovedBackpacks dev](https://github.com/DreenDex/ImprovedBackpacks-Issues/issues/11) however there hasnt been a response on that end yet.

**Comment by phit** [comment]
mod bug, report to them and tell them 
"to not to override getTileData to call writeToNbt" see also https://github.com/JurassiCraftTeam/JurassiCraft2/issues/561
