### ISSUE TITLE
TAIGA Mod- Tiberium Ore Explosion problem

### ISSUE THREAD

**Issue by mrdeadlocked** [SpongePowered/SpongeForge#2750]
**I am currently running**

/* Minecraft : 1.12.2 */
/* SpongeAPI : 7.1.0-3fdbf299 */
/* Sponge : 1.12.2-7.1.6-SNAPSHOT */
/* SpongeForge : 1.12.2-2825-7.1.6-RC3708 */
/* Minecraft Forge : 14.23.5.2836 */
- Operating System: Ubuntu

- Plugins/Mods:
Mods (258): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, /dank/null, A Lib, Actually Additions, Actually Baubles, Akashic Tome, Alchemistry, Animania, AppleCore, AppleSkin, ArchitectureCraft, Aroma1997Core, Artisan Worktables, Astral Sorcery, Athenaeum, AutoPickup, AutoRegLib, Avaritia, B.A.S.E, BD Lib, Bad Mobs, Baubles, Better Questing, Better Questing Quest Book, BiblioCraft, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Blockcraftery, Blood Arsenal, Blood Magic: Alchemical Wizardry, Bonsai Trees, Bookshelf, Botania, Botanic Additions, Brandon's Core, Can I Join Now?, Ceramics, Chameleon, Chest Transporter, ChickenChunks, Chisel, Chisels & Bits, Chunk Pregenerator, CoFH Core, CoFH World, CodeChicken Lib, CommonCapabilities, Compact Drawers, ContentTweaker, CookieCore, Corail Tombstone, CosmeticArmorReworked, CraftStudio API, CraftTweaker JEI Support, CraftTweaker2, CreativeCore, CreativeCoreDummy, Cucumber Library, Custom Starting Gear, Cyclic, Cyclops Core, DDSS Utils, Dark Utilities, Doomlike Dungeons, Draconic Evolution, DungeonTactics, Dynmap, DynmapBlockScan, EnderStorage, Environmental Tech, EvilCraft, EvilCraft-Compat, Exchangers, Extended Crafting, Extra Alchemy, Extra Planets, Extra Utilities 2, Extreme Reactors, Farseek, Fast Leaf Decay, FastWorkbench, Fishing Net Mod, FluidTank, FluidTank_AE2, FluidTank_TheOneProbe, FoamFix, FoamFixCore, Forestry, Forge Microblocks, Forge Multipart CBE, Galacticraft Core, Galacticraft Planets, GenDustry, Gendustry JEI Addon, Guide-API, Guidebook, Hammer Core, HelpFixer, Hooked, Hunger Overhaul, Hunting Dimension, Ice and Fire, Immersive Engineering, Industrial Foregoing, Infernal Mobs, Integrated Dynamics, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTunnels-Compat, Integration Foregoing, Iron Chest, IvToolkit, Just Another Rotten Flesh to Leather Mod, Just Enough Items, LLibrary, LagGoggles, Lapis Stays in the Enchanting Table, LibEx, LibrarianLib, LibrarianLib Stage 2, LittleTiles, LittleTilesCore, Longer Days, Loot Bags, LootTweaker, MJRLegendsLib, MTLib, MagicBees, MalisisCore, MalisisDoors, Mantle, McJtyLib, Mekanica, Mekanica: Generators, Mekanica: Tools, MekanismOres, Micdoodle8 Core, Minecraft Multipart Plugin, Mob Properties Randomness, Mod Tweaker, More Libs, More Plates, Morpheus, Mowzie's Mobs, MrCrayfish's Furniture Mod, MrTJPCore, Multi Mob Core, Mystical Agradditions, Mystical Agriculture, Mystical Lib, Natura, NetherEx, NotEnoughIDs, NuclearCraft, OMLib, OnlinePictureFrame, Open Modular Passive Defense, Open Modular Turrets, OpenBlocks, OpenComputers, OpenComputers (Core), OpenModsLib, OpenModsLib Core, Overloaded, Pam's Cookables, Pam's HarvestCraft, Pickle Tweaks, Placebo, PlusTiC, PneumaticCraft: Repressurized, Primitive Mobs, Progressive Bosses, ProjectRed Core, ProjectRed Expansion, ProjectRed Exploration, ProjectRed Fabrication, ProjectRed Illumination, ProjectRed Relocation, ProjectRed Transmission, ProjectRed Transportation, ProjectRed integration, Quark, RFTools, RFTools Control, RFTools Dimensions, RFToolsPower, RailsPlus, RandomPatches, Reborn Core, RebornStorage, Redstone Flux, Refined Avaritia, Refined Storage, Refined Storage Addons, Rex's Additional Structures, Rockhounding Mod: Chemistry, Rockhounding Mod: Core, Roguelike Dungeons, Rough Mobs 2, Ruins Mod, Rustic, Shadowfacts' Forgelin, Simply Jetpacks 2, Solar Flux Reborn, Special AI, Spice of Life: Carrot Edition, SpongeForge, Standard Expansion, Steve's Carts 2, Storage Cabinet, Storage Drawers, Storage Drawers Extras, Storage Tech, Streams, TOP Addons, Tech Reborn, Tech Reborn Mod Compatibility, Tesla Core Lib, Tesla Core Lib Registries, The One Probe, The Spice of Life, The Twilight Forest, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Tinkers Alloying Addon, Tinkers Tool Leveling, Tinkers' Construct, TorchMaster, Traverse, Tweakers Construct, Underground Biomes, UniDict, Universal Modifiers, V0id's Smart Backpacks, Valkyrie Lib, VanillaFix, ViesCraft, Vulcanite, WanionLib, Worley's Caves, XNet, Zero CORE, Zoesteria Biomes, galacticrafttweaker, p455w0rd's Library, projectred-compat

Plugins (20): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, CatClearLag, Dynmap, ESPayMoney, EconomyLite, GriefPrevention, LuckPerms, MagiBridge, Nucleus, PlaceholderAPI, PlayerShopsRPG, Sledgehammer, SlotMachines, SpongePrometheusExporter, Spotlin, TabManager, spark

**Issue Description**
When breaking tiberium ore from TAIGA (https://minecraft.curseforge.com/projects/taiga-tinkers-alloying-addon) the server lags and we get a console error. The ore has a chance to explode so the larger vein that is mined causes more of a stutter/stall of the server.

```
Server thread/ERROR 05/12/2019 08:00:58
08:00:58/* - IgnoreCreative: false */
/* - ItemStackUsed: 1xitem.terraPick@0 */
/* - OpenContainer: null */
/* - Phase: PluginPhase{}{ScheduledTaskPhaseState} */
/* Context: */
/* - Source: com.google.common.util.concurrent.ListenableFutureTask@2766fd92 */
/* Stacktrace: */
/* java.lang.IllegalStateException: Cause Stack Proxy Corruption! Attempted to pop a proxy that was not on the stack. */
/* org.spongepowered.common.event.tracking.context.SpongeProxyBlockAccess.popProxy(SpongeProxyBlockAccess.java:155) */
/* org.spongepowered.common.event.tracking.context.SpongeProxyBlockAccess.access$600(SpongeProxyBlockAccess.java:57) */
/* org.spongepowered.common.event.tracking.context.SpongeProxyBlockAccess$Proxy.close(SpongeProxyBlockAccess.java:596) */
/* org.spongepowered.common.event.tracking.context.MultiBlockCaptureSupplier.processTransactions(MultiBlockCaptureSupplier.java:733) */
/* org.spongepowered.common.event.tracking.TrackingUtil.performBlockAdditions(TrackingUtil.java:592) */
/* org.spongepowered.common.event.tracking.TrackingUtil.processBlockCaptures(TrackingUtil.java:462) */
/* org.spongepowered.common.event.tracking.TrackingUtil.processBlockCaptures(TrackingUtil.java:389) */
/* org.spongepowered.common.event.tracking.phase.packet.player.InteractionPacketState.unwind(InteractionPacketState.java:162) */
/* org.spongepowered.common.event.tracking.phase.packet.player.InteractionPacketState.unwind(InteractionPacketState.java:78) */
/* org.spongepowered.common.event.tracking.PhaseTracker.completePhase(PhaseTracker.java:319) */
/* org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:613) */
/* org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:195) */
/* net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlj000(SourceFile:539) */
/* net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) */
/* java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) */
/* java.util.concurrent.FutureTask.run(FutureTask.java:266) */
/* net.minecraft.util.Util.func_181617_a(SourceFile:529) */
/* org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:305) */
/* net.minecraft.server.MinecraftServer.redirect$onRun$zjo000(MinecraftServer.java:3965) */
/* net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) */
/* net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) */
/* net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) */
/* net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) */
/* java.lang.Thread.run(Thread.java:748) */
/* */
/* Minecraft : 1.12.2 */
/* SpongeAPI : 7.1.0-3fdbf299 */
/* Sponge : 1.12.2-7.1.6-SNAPSHOT */
/* SpongeForge : 1.12.2-2825-7.1.6-RC3708 */
/* Minecraft Forge : 14.23.5.2836 */
/*****************************************************************************************************************************************/
```

**Comment by phit** [comment]
previous issue with same mod on 1.10 https://github.com/SpongePowered/SpongeForge/issues/1777

**Comment by gabizou** [comment]
Can you re-test with latest and possibly upload a fuller log, specifically when the warnings first start happening?

**Comment by mrdeadlocked** [comment]
It still did it on the newest. Here's a log from my login through me breaking a few sets of tiberium. https://pastebin.com/f8NDyKzr

**Comment by gabizou** [comment]
> Here's a log from my login through me breaking a few sets of tiberium.

The actual log, that log you pastebinned is not formatted and missing really important information...
```
09:37:22Can't keep up! Did the system time change, or is the server overloaded? Running 5239ms behind, skipping 104 tick(s)
Server thread/ERROR 05/30/2019 09:37:28
09:37:28/* net.minecraft.world.WorldServer.func_72885_a(WorldServer.java:3456) */
````
there should be a lot of information before a stacktrace is listed.

**Comment by mrdeadlocked** [comment]
Sorry. I grabbed that from the console panel. Here's from the latest.log

https://gist.github.com/mrdeadlocked/328bbb62b3b133fa62b7f5ef5110c6cb
