### ISSUE TITLE
Stoneblock 2 Compressed block problem

### ISSUE THREAD

**Issue by krisjenner** [SpongePowered/SpongeForge#2752]
**I am currently running**

- SpongeForge version: RC3708
- Forge version: 2836 (Stoneblock 2 V1.12.0)
- Java version: 8
- Operating System: W10

- Plugins/Mods:
 Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, ActiveTime, Broadcast, CarrotShop, CatClearLag, Enjin Minecraft Plugin, EntityParticles, GriefPrevention, Holograms, HuskyCrates, HuskyUI, Lottery, LuckPerms, MMCReboot, MMCRestrict, MagiBridge, MaintenanceSponge, Nucleus, PetBlocks, Player Glow, SkinChanger, Slash Discord, Total Economy, spark

**Issue Description**
Compressed Cobble is supposed to turn in to 9 single gravel when mined with compressed hammer but only turns in to 1 gravel

https://gyazo.com/f2941fd98611e4b1fb3f06819d67d244

**Comment by gabizou** [comment]
What mod gives you compressed cobble? You don't list that in the plugins/mods list.

**Comment by Shybella** [comment]
Ex Compressum + Ex Nihilo

**Comment by phit** [comment]
fixed in RC3731+
