### ISSUE TITLE
Severe dupe bug with TE machines

### ISSUE THREAD

**Issue by krisjenner** [SpongePowered/SpongeForge#2756]
**I am currently running**

- SpongeForge version: RC3708 
- Forge version: 
- Java version: 
- Operating System:

- Plugins/Mods:

**Issue Description**
I struggle to replicate this for a GIF but it has happened on 2 of my servers that are using RC3708, TE machines will place in world but not leave inventory leading to a ridiculous amount of duping of the machines

**Comment by gabizou** [comment]
> I struggle to replicate this for a GIF but it has happened on 2 of my servers that are using RC3708, TE machines will place in world but not leave inventory leading to a ridiculous amount of duping of the machines

Kinda need more explanation. What machines? What mods? What do you mean TE machines will be placed in a world but not leave inventory?

**Comment by gabizou** [comment]
Retest with 7.1.6-RC3709, has a very long-over-time bug fix that may very well have resolved this dupe issue you're witnessing (but again, because I don't know what you're talking about with machines, etc., I can't say for sure).

**Comment by gabizou** [comment]
Assuming no response within the next week (May 30th), I'll consider the issue resolved and close at that time.

**Comment by gabizou** [comment]
Considering the issue closed as it's been a week now (sure, one day, but no response on other issues either).
