### ISSUE TITLE
Disconnected

### ISSUE THREAD

**Issue by Crosus97** [SpongePowered/SpongeForge#2760]
**I am currently running**

- SpongeForge version: 1.12.2-2768-7.1.5
- Forge version: forge-1.12.2-14.23.5.2779-universal (i had this specific version because a mod need it and is the most near to the recommended)
- Java version: Java 8 211
- Operating System: Windows Server

- Plugins/Mods:
[modlist.txt](https://github.com/SpongePowered/SpongeForge/files/3189353/modlist.txt)

**Issue Description**
I try to connect to the server and dont connect and give me in the screen Disconected...
thats all

this is the server [latest.log] https://github.com/SpongePowered/SpongeForge/files/3189355/latest.log)

**Comment by phit** [comment]
two options:
remove mtqfix, as sponge can already do the same thing

or disable `sync-player-positions-for-vehicle-movement` in the sponge config
