### ISSUE TITLE
Proxy is now being cleared - compact machines

### ISSUE THREAD

**Issue by Yorkforce** [SpongePowered/SpongeForge#2762]
**I am currently running**

- SpongeForge version: RC3712
- Forge version: 2831
- Java version: 8
- Operating System: Debian 9

- Plugins/Mods:

**Issue Description**

When using compact machines projector multiblock, sometimes it leaves behind a ghost block in the middle of the projector area, which prevents using the projector for further recipes. It occurs quite frequently usually 1 in every 2 attempts.

To give you an overview of what this all looks like, the middle block highlighted via worldedit selection is where the ghost block remains, we can only remove it with worldedit, which obviously isn't much help to players as admins need to clear it every other time the projector is used.
![compmach](https://user-images.githubusercontent.com/1526195/57929539-8190c500-78ab-11e9-9bc4-beec25c75f2a.png)

In addition, there seems to be some issue with meta data, a player tried to make 2 maximum compact machines (13x13 blocks) but instead got 1 maximum and 1 large (9x9).
The compact machine blocks share the same ID (compactmachines3:compactmachine) but different meta, so im wondering if there is a larger issue at play here.

We did see this in the console (but the server.log isn't showing it for some reason)

https://pastebin.com/FkDWnTvb

**Comment by gabizou** [comment]
Can this be reproduced in latest builds?

**Comment by Ruukas97** [comment]
I posted fix in MinecraftPortCentral/GriefPrevention#902
