### ISSUE TITLE
Illegal Async Chunk Load

### ISSUE THREAD

**Issue by ObjecT767** [SpongePowered/SpongeForge#2763]
**I am currently running**

- SpongeForge version: 1.12.2-2825-7.1.6-RC3713
- Forge version: 14.23.5.2837
- Java version: 8 Update 211
- Operating System: Win 10

- Plugins/Mods:
![Mod List](https://user-images.githubusercontent.com/49611562/57949612-2ed3ff00-78e5-11e9-9341-a8cf2c2db5fd.JPG)

**Issue Description**

When I trying to change Constellation (Astral Sorcery) on Attunment Altar (break Spectral Relay) , this error occure.
I copy 1:1 files from dedicated server and run it on my PC, everything works fine.

Error: https://gist.github.com/ObjecT767/8803d2ce8083ee02bc0407be14bdf28f

[latest.log](https://github.com/SpongePowered/SpongeForge/files/3192688/latest.log)

**Comment by XakepSDK** [comment]
Report to astralsorcery, not a sponge bug

**Comment by ObjecT767** [comment]
But Works fine on Sponge 1.12.2-2825-7.1.6-RC3708

**Comment by phit** [comment]
this definitely didn't work ever without this warning, you probably don't have this loading new chunks usually

please report to the mod
