### ISSUE TITLE
Failed to process all PhaseContext captured!

### ISSUE THREAD

**Issue by Crosus97** [SpongePowered/SpongeForge#2766]
**I am currently running**

- SpongeForge version: 1.12.2-2768-7.1.5
- Forge version: forge-1.12.2-14.23.5.2779-universal (i had this specific version because a mod need it and is the most near to the recommended)
- Java version: Java 8 211
- Operating System: Windows Server

- Plugins/Mods:
[modlist.txt](https://github.com/SpongePowered/SpongeForge/files/3189353/modlist.txt)

**Issue Description**
The console was crazy and overlagged the server 
https://gyazo.com/3464953ad0a00a932b832c78a43378e3

in the lastest.log
[fallo 1 extra utils.txt](https://github.com/SpongePowered/SpongeForge/files/3194173/fallo.1.extra.utils.txt)

to many redstone problems we try to repeat the error and is on activate a Redstone Circuit
[latest.log](https://github.com/SpongePowered/SpongeForge/files/3194172/latest.log)
[fallo 1 extra utils.txt](https://github.com/SpongePowered/SpongeForge/files/3194173/fallo.1.extra.utils.txt)

(When i desactivated the mod there is a redstone circuit with infinite power because a repeater is connected to the same repeater, there is any option to desactivate this type of alerts ??)

**Comment by phit** [comment]
update sponge to at least 3616, your version is extremely old, while it may still be the latest recommended version there are too many changes since then
