### ISSUE TITLE
Using Crafting Manager Fallback - console/server log spam - low TPS

### ISSUE THREAD

**Issue by Yorkforce** [SpongePowered/SpongeForge#2769]
**I am currently running**

- SpongeForge version: 3712
- Forge version: 2831
- Java version: 8 
- Operating System: Debian 9

- Plugins/Mods:
Sky Factory 4

**Issue Description**

When one of our players was autocrafting a Tier 1 growth crystal from mystical agriculture in a molecular assembler from mekanism, the console started spamming the following multiple times per second:

[13:05:23] [Server thread/WARN] [AE2:S]: Using CraftingManager fallback: Recipe <tp:growth_upgrade> for output <1xtile.growth_upgrade@0> rejected inputs [1xitem.potion@0, 1xitem.netherStar@0, 1xtile.growth_block@0, 1xitem.potion@0, 1xtile.glass@0, 1xitem.potion@0, 1xtile.growth_block@0, 1xitem.netherStar@0, 1xtile.growth_block@0]. NOT FOUND, please report.

https://pastebin.com/bgPdJ2jy

This resulted in the server log file increasing in size by 300-500MBs per hour, it also resulted 4-5TPS making the server lag alot.

the original log file is too large to upload but this is a snippet of the start of it:
[latest.log](https://github.com/SpongePowered/SpongeForge/files/3198206/latest.log)

**Comment by phit** [comment]
something in your pack has a broken recipe, nothing to do with sponge https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3822
https://github.com/Darkosto/SkyFactory4Issues/issues/684
