### ISSUE TITLE
BetterWithMods - Gearbox not working with Sponge.

### ISSUE THREAD

**Issue by se7enek** [SpongePowered/SpongeForge#2770]
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2825-7.1.6-RC3713.jar
- Forge version: forge-1.12.2-14.23.5.2838-universal.jar
- Java version: 1.8.0... (latest)
- Operating System: CentOS 7

- Plugins/Mods:
No plugins.
Sevtech 3.1.1 Pack
BetterWithMods 1.12-2.3.20-1027.jar

**Issue Description**
SpongeForge denying BetterWithMods' Gearbox to work properly.

Gearbox is supposed to "transfer" mechanical power from 1 axle to another, so you can extend it.
Generation of Mechanical Power works fine. Axle with Windmill/Watermill is making it rotate. Meta Data for Axle changing from Power:0 to Power:1 once windmill/watermill is on. Adding Gearbox to this "network" doesnt break stuff, but its never getting Power:1 data,  even it IS plugged properly.

1. No sponge server
2. Placed Gearboxes
3. They work fine
4. Added Sponge
5. They still work fine (unless u place new ones)

Looking for kinda workaround, no need to be perfect solution ;)

**Would like to add the logs, but there are literally nothing in logs folder related to any kind of issue.**
Nothing in debug.log, nothing in latest.log.
Maybe need to enable logging for this particular mod to help?

Regards, se7en.

**Comment by ghost** [comment]
Do existing gearboxes work after adding Sponge? Or do they break too?

**Comment by se7enek** [comment]
1. No Sponge.
2. Placed Gearboxes (call them A)
3. Added Sponge 
4. Placed Gearboxes (call them B)

Gearboxes A working fine.
Gearboxes B not working (you can rotate them but they arent passing power).

**Comment by se7enek** [comment]
About the logs, not sure if they are any helpful but here are only ones related.

`[15:28:54] [Server thread/WARN] [Sponge]: Could not find down owning class, assigning fallback id: betterwithmods:block_gearbox_down

[15:28:54] [Server thread/WARN] [Sponge]: Could not find east owning class, assigning fallback id: betterwithmods:block_gearbox_east

[15:28:54] [Server thread/WARN] [Sponge]: Could not find north owning class, assigning fallback id: betterwithmods:block_gearbox_north

[15:28:54] [Server thread/WARN] [Sponge]: Could not find south owning class, assigning fallback id: betterwithmods:block_gearbox_south

[15:28:54] [Server thread/WARN] [Sponge]: Could not find up owning class, assigning fallback id: betterwithmods:block_gearbox_up

[15:28:54] [Server thread/WARN] [Sponge]: Could not find west owning class, assigning fallback id: betterwithmods:block_gearbox_west`

**Comment by ghost** [comment]
@se7enek I suggest reporting this to the Mod Developer. This doesn't seem to be an issue with Sponge. Just the mods ids? (assuming as Sponge assigned fallbacks)

**Comment by gabizou** [comment]
> [15:28:54] [Server thread/WARN] [Sponge]: Could not find down owning class, assigning fallback id: betterwithmods:block_gearbox_down
> 
> [15:28:54] [Server thread/WARN] [Sponge]: Could not find east owning class, assigning fallback id: betterwithmods:block_gearbox_east
> 
> [15:28:54] [Server thread/WARN] [Sponge]: Could not find north owning class, assigning fallback id: betterwithmods:block_gearbox_north
> 
> [15:28:54] [Server thread/WARN] [Sponge]: Could not find south owning class, assigning fallback id: betterwithmods:block_gearbox_south
> 
> [15:28:54] [Server thread/WARN] [Sponge]: Could not find up owning class, assigning fallback id: betterwithmods:block_gearbox_up
> 
> [15:28:54] [Server thread/WARN] [Sponge]: Could not find west owning class, assigning fallback id: betterwithmods:block_gearbox_west

Ignore that stuff. It's just sponge's auto-generated block property id's for potential configuration resolution if a plugin uses one for a value.

**Comment by gabizou** [comment]
I'll look into the issue soon, but can you just quickly re-test with 7.1.6-RC3720?

**Comment by gabizou** [comment]
Testing results so far: Could not reproduce the issue while in development with a single player instance. Will look further into server only. Tested with all should fire flags off and should fire flags on, no change.

**Comment by Yorkforce** [comment]
Still seems to be a problem with 3745

This does create abit of a big problem on SevTech modpack, because progression is staged, you need a working turntable just to make a bucket, as you can imagine playing without a bucket is pretty hardcore :D

**Comment by gabizou** [comment]
Still can't reproduce the issue in production: https://youtu.be/Iu9oVpun8nc
Placing a new gearbox and axels still works with `-Dsponge.shouldFireAll=true` and without it enabled as well.

**Comment by Yorkforce** [comment]
Test and confirmed, thank you gabizou! 
Buckets galore!
