### ISSUE TITLE
Doors duplication

### ISSUE THREAD

**Issue by SSKirillSS** [SpongePowered/SpongeForge#2775]
**I am currently running**
forge-1.12.2-14.23.5.2836-universal
spongeforge-1.12.2-2825-7.1.6-RC3716

**Mods:**
![image](https://user-images.githubusercontent.com/38190325/58375576-caf1ac00-7f5e-11e9-8ae0-a53443b4bb81.png)

**Issue Description**
If you break the skull or the door (Lower block), they just simply dupe.

**Comment by phit** [comment]
Duplicate of https://github.com/SpongePowered/SpongeCommon/issues/2259

**Comment by JBYoshi** [comment]
Doors are a separate issue. This happens only when you break the bottom half of a door. Also, the skull issue depends on tile entities; doors don't have tile entities. Reopening.

**Comment by phit** [comment]
Previous door issue: https://github.com/SpongePowered/SpongeCommon/issues/2262

**Comment by gabizou** [comment]
Skulls was fixed, doors were fixed already.
