### ISSUE TITLE
World Teleport/Loading Issue -  DimensionalEdibles

### ISSUE THREAD

**Issue by Yorkforce** [SpongePowered/SpongeForge#2776]
**I am currently running**

- SpongeForge version: 3716
- Forge version: 2838
- Java version: 8
- Operating System: Debian 9

- Plugins/Mods:

**Issue Description**

This is on the OmniFactory modpack, basically the 2 world options for the pack is a lost cities dimension (overworld) or a void dimension (accessed via [DimensionalEdibles](https://github.com/JackyyTV/DimensionalEdibles) cake). When using the dimensional edibles Cake, it takes you to the right dimension but you cant move or see anything, no terrain loads, no monsters, nothing. If you relog, everything loads fine.
It's only occurring when using cakes, /spawn /home etc all work as intended.

I checked this on single player and it works normally, just on server its having this issue.

Seems to be related to advancement errors when switching dimensions. When using the cake the console is spammed silly with tons of advancement related errors, more than usual.
This is where it starts after using the cake:
https://pastebin.com/m9VsDZaw

Full log:
[latest.log](https://github.com/SpongePowered/SpongeForge/files/3219848/latest.log)

**Comment by gabizou** [comment]
Retest with latest, Pretty sure @Zidane fixed a few things with teleportation.

**Comment by Zidane** [comment]
https://github.com/JackyyTV/DimensionalEdibles/blob/dev-1.12.2/src/main/java/jackyy/dimensionaledibles/util/TeleporterHandler.java#L30

DimensionEdibles literally re-writes the server logic for changing dimensions when they could call Entity's changeDimension or PlayerList's transferEntityToWorld or changePlayerDimension methods. There is 0 reason to do this beyond legacy code from ages back when all of this was scattered in Minecraft itself. They break not only Sponge but any mod that would have you use their teleporter to change dimensions as well.

Sponge fully supports dimension mods who call the proper hooks and will not support mods that do this.
