### ISSUE TITLE
Wireless Crafting Terminal & Sponge causing issues with EnderIO Creative Capacitor Banks

### ISSUE THREAD

**Issue by CaptainSisko** [SpongePowered/SpongeForge#2778]
**I am currently running**

**- SpongeForge version:**  
spongeforge-1.12.2-2825-7.1.6-RC3716

**- Forge version:** 
forge-1.12.2-14.23.5.2825-universal.jar

**- Java version:**
1.8.0_201

**- Operating System:** 
Windows 10

**- Plugins/Mods:**
AE2WTLib-1.12.2-1.0.6
appliedenergistics2-rv6-stable-6
EnderCore-1.12.2-0.5.57
EnderIO-1.12.2-5.0.44
jei_1.12.2-4.15.0.279
NuclearCraft-2.16f-1.12.2
p455w0rdslib-1.12.2-2.1.44
WirelessCraftingTerminal-1.12.2-3.11.88

**- Issue Description**
Initially i was attempting to troubleshoot an issue where NuclearCraft machines would stop importing into an ME System (completely unrelated to channels) however during my testing i have discovered another issue which may be the root cause of the issue i was troubleshooting.

Using the above list of mods with Sponge, if you place an EnderIO Creative Capacitor Bank on top of a NuclearCraft machine (a Manufactory for example) it will receive power, when you place items into the machine it will begin to completely drain its power. Once the power is gone, even if you remove the items the power will not go back up. The only way to get the power to go back up is to remove the Capacitor Bank and then place it again, this will fill the power back up but then continue to drain(if there are still items inside, if there are none the machine will stay at full power).
The Creative Capacitor Bank itself doesn't get all of its power drained. I also tested the Capacitor Bank on one of the EnderIO machines and the issue did not occur.

If you remove the WirelessCraftingTerminal mod and its 2 library mods this issue will stop happening.

If you keep the WirelessCraftingTerminal mod ands its 2 library mods but remove sponge this issue will stop happening.

The initial issue i was troubleshooting may need an issue tracker of its own but i will give a brief description here. If you have a NuclearCraft Melter with an ME Export Bus on one side and an ME Fluid Import Bus on the other side(one putting a meltable item in and the other taking the fluid out), when the Melter runs out of power like mentioned above, the ME Fluid Import Bus will stop taking out the fluid, even once you have replaced the Capacitor Bank. The only way to get it to start taking the fluid out again is to break and replace the ME Cable.

This issue also only occurs when the WirelessCraftingTerminal mod and Sponge are installed.

**- Logs:**
No error logs are produced but here is the latest.log
https://hastebin.com/hulejulazu.md

**Comment by phit** [comment]
probably same as https://github.com/SpongePowered/SpongeForge/issues/2758

**Comment by phit** [comment]
please retest this on RC3732+ this was most likely fixed

**Comment by CaptainSisko** [comment]
Sorry for the delay, I have just tested this again with RC3777 and both issues are no longer occurring.
