### ISSUE TITLE
Villager Trades mod - not enabling custom trades

### ISSUE THREAD

**Issue by Yorkforce** [SpongePowered/SpongeForge#2779]
**I am currently running**

- SpongeForge version: 3718
- Forge version: 2815
- Java version: 8
- Operating System: Debian 9

- Plugins:
Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, Aliases, AntiWDL, AurionsVoteListener, AutoBroadcaster, Discord Bridge, EconomyLite, Enjin Minecraft Plugin, GriefPrevention, LuckPerms, MMCRestrict, MultiChatSponge, NuVotifier, Nucleus, Player Glow, PlayerShopsRPG, RankUpper, Sledgehammer, TimeWarp

- Mods:
Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, A Block of Charcoal, AbyssalCraft, AbyssalCraft Integration, Actually Additions, Actually Baubles, Advanced Generators, Advanced Mortars, Antique Atlas, AppleCore, AppleSkin, Applied Energistics 2, ArmoreableMobs, Aroma1997Core, AstikorCarts, Astral Sorcery, AutoRegLib, B.A.S.E, BD Lib, BNBGamingLib, Baubles, Bedrock-B-Gone, Better Builder's Wands, Better With Lib, Better With Mods, Better with Addons, BiblioCraft, Blood Magic: Alchemical Wizardry, BnBGamingCore, Bonsai Trees, Bookshelf, BuildCraft, BuildCraft Builders, BuildCraft Factory, BuildCraft Lib, BuildCraft Robotics, BuildCraft Silicon, BuildCraft Transport, Building Gadgets, CD4017BE_lib, Caliper, Ceramics, Chameleon, Chargers, Chisel, Chisels & Bits, Clumps, CodeChicken Lib, CommonCapabilities, Compact Machines 3, Construct's Armory, ContentTweaker, Cooking for Blockheads, Corail Tombstone, CraftTweaker JEI Support, CraftTweaker2, Cucumber Library, Cyclic, Cyclops Core, Dark Utilities, Despawning Spawners, Dimension Stages, Dimensional Control, Dung Pipe, Elevator Mod, EmberRoot Zoo, Ender Utilities, EnderStorage, Environmental Tech, Extended Crafting, Extra Planets, Farming for Blockheads, Farseek, FastFurnace, FastWorkbench, Ferdinand's Flowers, FindMe, FoamFix, FoamFixCore, Forge Microblocks, Forge Multipart CBE, Galacticraft Core, Galacticraft Planets, Game Stages, Geolosys, Gobble Core, Guide-API, Harvest, Horse Power, Hunting Dimension, Immersive Craft, Immersive Engineering, Immersive Petroleum, Immersive Tech, Improved Backpacks, In-Game wiki Mod, InControl, Inductive Logistics, Industrial Foregoing, Info Accessories, Integrated Dynamics, IntegratedDynamics-Compat, Inventory Tweaks, Iron Backpacks, Iron Chest, Iron Jetpacks, Item Stages, IvToolkit, JourneyMap, Just A Raft Mod, Just Enough Items, Just a Few Fish, JustEnoughIDs, KleeSlabs, LibEx, Loot Table Tweaker, MJRLegendsLib, MTLib, Mantle, McJtyLib, MekaTweaks, Mekanism, Mercurius, Micdoodle8 Core, Minecraft Multipart Plugin, Mo' Bends, Mo' Villages, Mob Stages, Mod Tweaker, ModPack Basic Tools, ModPack Utilities, Modular Machinery, Modular Routers, Morpheus, Multiblockstages, Mundane Redstone, Mystical Agradditions, Mystical Agradditions Compat, Mystical Agriculture, Natura, Nature's Compass, NetherEx, No World Gen 5 You, Nutrition, Ocean Floor Classic, Ore Stages, OreExcavation, OreExcavation Integration, Overloaded, Pickle Tweaks, Placebo, Player Skin Mobs, PneumaticCraft: Repressurized, Power Adapters, Prestige, PrimalChests, PrimalCore, Progression Tweaks, Prospectors, QuantumStorage, Quark, Quick Leaf Decay, RFTools, RFTools Control, Ranged Pumps, Realistic Item Drops, Reborn Core, RebornStorage, RecipeStages, Recurrent Complex, Redstone Flux, Refined Storage, Refined Storage Addons, Road Runner, Rustic, Sampling Performance Profiler, Scannable, SevTweaks, Shadowfacts' Forgelin, Simple Generators, Simple Storage Network, SimpleAutoRun, Simply Arrows, Smooth Font Core, Spartan Shields, Spatial Server Mod, SpongeForge, Steve's Carts 2, Storage Drawers, Streams, Stuff A Sock In It, Super Sound Muffler, SwingThroughGrass, TallGates, Tesla Core Lib, Tesla Core Lib Registries, The Beneath, The Betweenlands, The Twilight Forest, The Weirding Gadget, Thirsty Bottles, Tinker Stages, Tinkers Tool Leveling, Tinkers' Complement, Tinkers' Construct, To the Bat Poles!, Totemic, Translocators, Traverse, Triumph, Trumpet Skeleton, Tumbleweed, Ultimate Car Mod, Universal Modifiers, Valkyrie Lib, ViesCraft, Villager Trade Tables, Waddles, Waila, Waila Stages, WanionLib, Water Control Extreme, Water Strainer, What Are We Looking At, Wild Crops, Wither Skeleton Tweaks, Wopper, World Stripper, WorldEdit, XNet, YNot, Yoyos, ZenStages, animalium, death_compass, fat_cat, galacticrafttweaker, magma_monsters, mob_grinding_utils, playerbosses, primal_tech, sev_tweaks_npc, uppers

**Issue Description**

Villager Trades are not adding custom villagers to villages, every village I have visited so far have all been normal vanilla villagers with standard vanilla trade options.
The Villager Trades mod works fine in SSP, just not on the server.

This is on a SevTech 3.1.1 server with level=quark_realistic

This is the error we see in the start up log:
https://pastebin.com/pK4Ns9Dm

Full server log:
[latest.log](https://github.com/SpongePowered/SpongeForge/files/3233139/latest.log)

**Comment by gabizou** [comment]
Brief overview of the VillagerTrade mod:

Reflect everything and mutate already registered objects dynamically, bypass most of the registration hooks that were written to avoid this sort of conflict. Sponge uses these hooks and registrations precisely to remain in sync with Forge's API for Villager trades. This mod just goes and bypasses most of that by using reflection. To add salt to the wound, VillagerTrades goes and makes it's own wrapper classes to "help" reflect back and forth. Good going.

When I get some time and motivation, I'll probably look at rewriting for the nth time to fallback on recreating all Sponge API objects constantly, based on a caching system of sorts, because clearly no one can figure out how to edit villager trades without breaking someone else's villager modifications. Thankfully 1.13+ already rewrote all of the villager trade handling to be straight registries in vanilla, so that can be laid to rest.

**Comment by Yorkforce** [comment]
Hmm thats a shame but not a huge problem, thankfully the advancements in the modpack that require this mod can be adjusted to work around the problem.

I noticed it was also mentioned on the Villager Trades github:
https://github.com/crazysnailboy/VillagerTrades/issues/19

**Comment by Yorkforce** [comment]
Just to update this further for anyone else wondering.

The mod is sort of working, it applies both modded and vanilla professions to villagers, not perfect but workable.
