### ISSUE TITLE
TileEntityActivation Performance

### ISSUE THREAD

**Issue by Shybella** [SpongePowered/SpongeForge#2780]
**I am currently running**

- SpongeForge version: 3720
- Forge version: 2836
- Java version: 1.8_201
- Operating System: Windows Server 2016

- Plugins/Mods: FTBRevelations 3.0.1 + https://pastebin.com/raw/QVBKZm3A

**Issue Description**

Performance impact from tile activation when controlling tick rates of entities.

I am using tile activation to control tick rates. I have the file populated and many of the mods disabled by default but still experiencing a hit from tile activation. 

Spark: https://sparkprofiler.github.io/#ThhUaANL8X
Sponge global.conf: https://pastebin.com/raw/Cxd4Nf5P

I can also provide a nps report of the same behavior. I can also provide a test build with the server configuration, this map is less than 5 days old with 30 players average, not many tile entities present.

Thanks.

**Comment by phit** [comment]
I'm confused, what are you seeing in that profiler that points at the activation feature?

**Comment by Shybella** [comment]
It's in the spark report.

"net.minecraft.world.World.updateEntities()32.74%
net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zme000()14.21%
net.minecraft.world.WorldServer.spongeTileEntityActivation()11.58%
org.spongepowered.common.mixin.plugin.tileentityactivation.TileEntityActivation.activateTileEntities()11.58%
org.spongepowered.common.mixin.plugin.tileentityactivation.TileEntityActivation.activateChunkTileEntities()11.15%
java.util.ArrayList.iterator()0.01%"

**Comment by gabizou** [comment]
Retest with latest please.

**Comment by Shybella** [comment]
https://sparkprofiler.github.io/#gse2sw790O

Running 10.5% with same count. On 3763

**Comment by Shybella** [comment]
https://github.com/SpongePowered/SpongeCommon/blob/stable-7/src/main/java/org/spongepowered/common/mixin/plugin/tileentityactivation/TileEntityActivation.java#L127

Even though I have the mods set to false in the config could activating and deactivating tile entities constantly checking player radius for those tile entities in range be problematic? I can increase the range and see what happens?

nps: https://drive.google.com/open?id=1Xxav2IVcmzByQZWx4FXR1LAFLy53wXcc
