### ISSUE TITLE
Canceling blockplace/interact events removes the item from players hand

### ISSUE THREAD

**Issue by johnfriedrich** [SpongePowered/SpongeForge#2781]
**I am currently running**

- SpongeForge version: RC3728
- Forge version: 2809

- Plugins/Mods:
Griefprevention 689

So what happens: When you have created an admin or basic claim and players that don't have trust are trying to place blocks on it, GP cancels it and the block in the players hand is gone. it does not even reappear when re-logging.
This wasn't an issue on 3616

**Comment by Zidane** [comment]
https://github.com/SpongePowered/SpongeCommon/issues/2242
