### ISSUE TITLE
RC3732 repeater ticking crash

### ISSUE THREAD

**Issue by SSKirillSS** [SpongePowered/SpongeForge#2782]
**I am currently running**
forge-1.12.2-14.23.5.2836-universal
spongeforge-1.12.2-2825-7.1.6-RC3732
Tiquality-THIN-1.12.2-GAMMA-1.4.3

**Issue Description**
I have no idea what happened, But it seems to me that the problem is in the new spongeforge and Tiquality.

https://gist.github.com/SSKirillSS/0f4341ab1ee04a9897ee2c94513afc60

**Comment by gabizou** [comment]
Do you have any log to go along with it? That crash seems to have been done with several failed/erroring phase states, specifically AttackEntityPacketState.

**Comment by SSKirillSS** [comment]
@gabizou, I understood how the crash happened. I entered in the chat "/toggledow" and pressed Tab for automatic addition to /toggledownfall, server was crashed. Crash works even if the player does not have permissions for use command. New report: https://gist.github.com/SSKirillSS/25516ae4e60bd8c2f96132b5b741972e

logs: https://gist.github.com/SSKirillSS/3ac86ed11ceb6d40525a0c4c77fe404a

**Comment by gabizou** [comment]
Yes, but there's got to be more logs than that.... Give me the entire log if you can't find where it *starts*, or give me the log where the errors/warnings *first start happening*.

For reference it says in the first part:
```
[00:43:52] [Server thread/ERROR] [Sponge]: /* Expected to exit phase: PacketPhase{}{AttackEntityPacketState}                                                     */
[00:43:52] [Server thread/ERROR] [Sponge]: /* But instead found phase: PluginPhase{}{EventListenerPhaseState}                                                    */
```
Meaning that the `EventListenerPhaseState` crashed, and then the next packet was exiting erroneously.

**Comment by SSKirillSS** [comment]
I sent absolutely everything that went after my last /rtp command. I'll check debug now.

**Comment by SSKirillSS** [comment]
It's all there, since I started to teleport around the world: https://gist.github.com/SSKirillSS/de2624591268aeec422082beea4fe5d7

Need more?
