### ISSUE TITLE
7.1.6-RC3740 Exception in server tick loop

### ISSUE THREAD

**Issue by cdcp998** [SpongePowered/SpongeForge#2784]
**I am currently running**

- SpongeForge version: 7.1.6-RC3740
- Forge version: 14.23.5.2825
- Java version: 1.8.0_211
- Operating System:centos7.6

[crash-2019-05-31_20.26.20-server.txt](https://github.com/SpongePowered/SpongeForge/files/3241507/crash-2019-05-31_20.26.20-server.txt)

Normal at spongeforge-1.12.2-2825-7.1.6-RC3731.
Change to 7.1.6-RC3740 An error occurred

**Comment by kristi71111** [comment]
Got something here aswell

- SpongeForge version: 7.1.6-RC3743
- Forge version: 14.23.5.2836
- Java version: 1.8.0_212
- Operating System: Centos 7

[crash-2019-05-31_17.23.08-server.txt](https://github.com/SpongePowered/SpongeForge/files/3242930/crash-2019-05-31_17.23.08-server.txt)
[stall-2019-05-31_17.23.06-1.txt](https://github.com/SpongePowered/SpongeForge/files/3242931/stall-2019-05-31_17.23.06-1.txt)

Also reverted back down to 1.12.2-2825-7.1.6-RC3731 and had no issue there.
Hopefully this helps in any way.

**Comment by JBYoshi** [comment]
@kristi71111 Could you open a new issue for your crash? These look like two separate issues.

**Comment by JBYoshi** [comment]
@cdcp998 How often does this happen? Does it happen when you start up your server, or is it in the middle of gameplay?

**Comment by kristi71111** [comment]
> @kristi71111 Could you open a new issue for your crash? These look like two separate issues.

I apologise done

**Comment by cdcp998** [comment]
> @cdcp998 How often does this happen? Does it happen when you start up your server, or is it in the middle of gameplay?

In games，It is expected to occur within 30 minutes.

**Comment by JBYoshi** [comment]
While I haven't been able to reproduce the crash, I think I found the bug. Try SpongeForge 3648 and see if that fixes it.
