### ISSUE TITLE
Soulshard Respawn Phase tracker error 

### ISSUE THREAD

**Issue by Shybella** [SpongePowered/SpongeForge#2787]
**I am currently running**

- SpongeForge version: 3720
- Forge version: 2836
- Java version: 1.8_201
- Operating System: Windows Server 2016

- Plugins/Mods: FTBRevelations 3.0.1 + https://pastebin.com/raw/QVBKZm3A

**Issue Description**

Error related to Soulshard Respawn mob spawner. The mob that was spawning is blazes. The block has two levers on each side of the block. 

Edit: The area was heavily on fire from the blazes.

Log: https://pastebin.com/raw/ct5R3n0U

Soulshard Respawn version: SoulShardsRespawn-1.12.2-1.1.0-12

**Comment by phit** [comment]
update sponge, too many fixes to the tracker since 3720

**Comment by Shybella** [comment]
Sorry this was on 3728, I will update.

**Comment by Shybella** [comment]
Occuring on spongeforge-1.12.2-2825-7.1.6-RC3743

**Comment by gabizou** [comment]
Did the log change at all? If not, can you re-paste a new log output?

**Comment by Shybella** [comment]
https://pastebin.com/raw/2ZG9NFR5

**Comment by gabizou** [comment]
Issue is with [SoulCage passing a null](https://github.com/TehNut/Soul-Shards-Respawn/pull/24), PR'ed a fix. I may be able to work around the issue, but the workaround isn't ideal.

**Comment by Shybella** [comment]
complied jar with gabi's fix https://drive.google.com/open?id=1WenKQr52l9kxOdRCEQ7-f98I5FS_5cC8

**Comment by Zidane** [comment]
Mod author pulled the fix so no need for a compiled jar really.
