### ISSUE TITLE
Oreexcavation Stall

### ISSUE THREAD

**Issue by kristi71111** [SpongePowered/SpongeForge#2789]
**I am currently running**

- SpongeForge version: 7.1.6-RC3743
- Forge version: 14.23.5.2836
- Java version: 1.8.0_212
- Operating System: Centos 7

- Mods (206): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AE2 Stuff, AI Improvements, Advancement Book, Animal Crops, Apotheosis, AppleCore, AppleSkin, Applied Energistics 2, Aroma1997Core, AromaBackup, AromaBackuprecovery, Astral Sorcery, B.A.S.E, BD Lib, BNBGamingLib, Barrels, Drums, Storage & More, Baubles, Bed Patch, BiblioCraft, BnBGamingCore, Bonsai Trees, Bookshelf, Building Gadgets, Caliper, Calm Down Zombie Guy, Ceramics, Chargers, ChineseWorkshop, Chisel, Chisels & Bits, Click Machine, Clumps, CoFH Core, CoFH World, CodeChicken Lib, ComPatchedStorage, CommonCapabilities, Compact Machines 3, CompactStorage, Construct's Armory, ContentTweaker, Cooking for Blockheads, Corail Tombstone, CraftTweaker JEI Support, CraftTweaker2, Cucumber Library, Culinary Construct, Cyclic, Cyclops Core, Dark Utilities, Deep Mob Learning, Dimension Stages, DragonMurder, Elevator Mod, Ender Crop, Ender Utilities, EnderCore, EnderStorage, Extended Crafting, Extra Cells 2, Farming for Blockheads, FastFurnace, FastWorkbench, Fence Overhaul, FindMe, Flux Networks, FoamFix, FoamFixCore, Forge Microblocks, Forge Multipart CBE, Forgiving Void, Game Stages, Guide-API, Headcrumbs, Horse Power, Hunting Dimension, HydroGel, InControl, Industrial Foregoing, Inspirations, Integrated Dynamics, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTunnels-Compat, Iron Jetpacks, Item Stages, JourneyMap, Just Enough Items, KleeSlabs, Limitless Structure Blocks, MCMultiPart, MTLib, MalisisCore, MalisisDoors, Mantle, MatterOverdrive: Legacy Edition, McJtyLib, Mekanism, Mekanism: Generators, Mercurius, Minecraft Multipart Plugin, Mob Stages, Mod Tweaker, ModPack Basic Tools, ModPack Utilities, More Buckets, More Cauldrons, Morpheus, Mystcraft, Mystical Agradditions, Mystical Agriculture, NuclearCraft, OG Dragon+, OpenComputers, OpenComputers (Core), OpenComputers Xnet Driver, OreExcavation, Parabox, Phosphor Lighting Engine, Pickle Tweaks, PigUtils, Pipe Master 2000, Placebo, PlaneFix, PortalGun, Practical Logistics 2, Prestige, Primitive Crafting, ProjectE, RFToolsPower, RandomPatches, Ranged Pumps, Real Filing Cabinet, RecipeStages, Redstone Flux, Resource Hogs, Rustic, Sampling Performance Profiler, Shadowfacts' Forgelin, Simple Generators, Simple Inventory sorting, Simple Storage Network, Sky Grid, SkyBonsais, Slab Machines, SlimyBoyos, Smooth Font Core, Snad, SonarCore, SpongeForge, Squeezer Patch, Statues mod, Stuff A Sock In It, Super Sound Muffler, Surge, SwingThroughGrass, Sync, TallGates, TelePastries, Tesla Core Lib, Tesla Core Lib Registries, The Lost Cities, The Twilight Forest, The Weirding Gadget, Thermal Dynamics, Thermal Foundation, Thermal Innovation, TickProfiler, Tinkers Tool Leveling, Tinkers' Complement, Tinkers' Construct, Tiny Progressions, TogetherForever, Topography, TorchMaster, Translocators, Tree Growing Simulator 2016, Triumph, Twitchcrumbs, Universal Modifiers, Valkyrie Lib, ViesCraft, Waddles, Waila, Waila Stages, Wall-Jump!, What Are We Looking At, Wither Crumbs, World Utils, WorldEdit, XC Patch, XL Food Mod, XNet, YNot, Yoyos, ZenStages, bouncy_creepers, mob_grinding_utils, sky_orchards, uppers

- Plugins (36): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, ActiveTime, AsciiEmotes, BacoMaster, BetterChunkLoader, CatClearLag, CommandUtils, EasyTexts, EconomyLite, Enjin Minecraft Plugin, GriefPrevention, Holograms, HuskyUI, KitSuiteEC, Lottery, LuckPerms, MMCRestrict, Market, NuVotifier, Nucleus, PlaceholderAPI, Player Glow, SeriousVote, SkyClaims, Sledgehammer, TabManager, TeslaCore, TeslaCrate, TeslaLibs, Unity, VoteParty, WelcomeRewards, spark

**Issue Description**
Stall does not seem to be replicable on version 1.12.2-2825-7.1.6-RC3731. I have not tested anything above this version and I have no idea what causes this stall to happen. Providing
crash and stall report from sampler.
[crash-2019-05-31_17.23.08-server.txt](https://github.com/SpongePowered/SpongeForge/files/3244241/crash-2019-05-31_17.23.08-server.txt)
[stall-2019-05-31_17.23.06-1.txt](https://github.com/SpongePowered/SpongeForge/files/3244242/stall-2019-05-31_17.23.06-1.txt)

**Comment by gabizou** [comment]
So, in the newer commits changing the structures of the phase states for server tick listeners, this shouldn't be stalling anymore, but the issue is now kinda changing, OrExcavation no longer captures block changes for undoing.

I'm writing some better handling for how the mod itself is using the flags during it's listener (I don't want to check for the boolean flags in other phase states), so it will function as it should with the mod.
