### ISSUE TITLE
Exception Exiting Phase

### ISSUE THREAD

**Issue by Shybella** [SpongePowered/SpongeForge#2793]
**I am currently running**

- SpongeForge version: 3745
- Forge version: 2836
- Java version: 201
- Operating System: Win Server 2016

- Plugins/Mods:

**Issue Description**

Mods/Plugins: https://pastebin.com/raw/QVBKZm3A

Log: https://pastebin.com/raw/Pw1WSyqN

This error especially causes a big performance hit but that may be due to the nature of the item/mod.

**Comment by gabizou** [comment]
[10:45:41] [Server thread/ERROR] [Sponge]: /* java.lang.IllegalStateException: WorldServer not found for UUID: da1c5171-83f6-4b13-85a5-40189f820572                               */

Did you recently remove configs or the `level_sponge.dat`? It looks like somehow there's a world that had a tracked block change and then it was removed before it gets to the event listener for GriefPrevention.

Overall, I wouldn't really consider it a sponge issue as something else would have to break for the tracker to get different `UUID`s for a world that no longer exists within the duration of handling a packet. Unless you have other opinions @Zidane ?

**Comment by Shybella** [comment]
I did not remove level_sponge.dat. 

Although, a world was unloaded at the time at error started to happen.

Update: This is reproducible after a player digs in a world that was unloaded while the player still exists in the world. You can use Nucleus world load/unload features.

**Comment by Zidane** [comment]
This is fixed in latest stable-7 by not allowing invalid locations (ones that have World objects we do not know about) from being set. The primary issue is on Nucleus side.

**Comment by Shybella** [comment]
Confirmed fixed
