### ISSUE TITLE
Wizardry In-World Fluid Crafting Not Working

### ISSUE THREAD

**Issue by Aiidoneus** [SpongePowered/SpongeForge#2795]
- SpongeForge version: spongeforge-1.12.2-2825-7.1.6-RC3749.jar
- Forge version: forge-1.12.2-14.23.5.2837-universal.jar
- Java version: 8
- Operating System: Ubuntu

- Plugins/Mods:
![](https://i.imgur.com/5vp5lTg.png)

**Issue Description**
It seems that the in-world fluid crafting seems to be broken with sponge. Tested this without sponge on a server and it works as intended. How the crafting works is you place mana in the world and drop a gold nugget into the pool. It then produces particles then after a few seconds, transforms into Nacre. With Sponge installed, it produces the particles but never transforms. I tested this with just Wizardry installed by itself and on FTB Interactions with the results being the same. This is a fairly big issue on FTB Interaction servers. 
The crafting recipe: https://imgur.com/a/YvJI0vM
Let me know if you need further info. 
-Aidoneus

**Comment by phit** [comment]
confirmed with 
Forgelin-1.8.3.jar
librarianlib-1.12.2-4.19.2-release.jar
wizardry-0.10.8.jar
spongeforge-1.12.2-2838-7.1.7-RC3807.jar


![](https://i.imgur.com/mpwksvo.png)

**Comment by gabizou** [comment]
Can you give 7.1.7-RC3820 a shot? I'm almost sure that it ends up fixing the issue (was using the wrong entity to force spawn to the world).

**Comment by phit** [comment]
still an issue with 3820

**Comment by phit** [comment]
doesn't work in 1.12.2-2838-7.1.7-RC3832

**Comment by phit** [comment]
crafttweaker script to add replacement recipes for FTB Interactions to bypass this issue temporarily

```
import crafttweaker.item.IItemStack;
import crafttweaker.item.IIngredient;

val manaBucket = <forge:bucketfilled>.withTag({FluidName: "mana_fluid", Amount: 1000}).onlyWithTag({FluidName: "mana_fluid", Amount: 1000});
recipes.addShapeless(<forge:bucketfilled>.withTag({FluidName: "nacre_fluid", Amount: 1000}) * 1, [<ore:nuggetGold> * 1,manaBucket.noReturn() * 1]);
recipes.addShapeless(<wizardry:wisdom_wood_log> * 1, [manaBucket.reuse() * 1,<ore:logWood> * 1]);
recipes.addShapeless(<wizardry:wisdom_stick> * 1, [manaBucket.reuse() * 1,<ore:stickWood> * 1]);
recipes.addShapeless(<wizardry:wisdom_sapling> * 1, [manaBucket.reuse() * 1,<ore:treeSapling> * 1]);
recipes.addShapeless(<wizardry:orb:1> * 1, [manaBucket.reuse() * 1,<wizardry:orb> * 1]);
```

**Comment by Zoneman1972** [comment]
Please excuse my ignorance guys, I'm still fairly new to this scripting business, but would you mind dumbing this down for me please?
Where exactly does this script go?
Is it a separate script of its own or does it get added into an existing one?
If so, which script does it get added to? FTBCustom or Wizardry?

If I'm way off the track, could you please steer me back in to the right direction.
Thanks in advance for any assistance you can provide

**Comment by phit** [comment]
just make a new file in the scripts folder, name it `literallyanyname.zs` and paste what I posted in there

**Comment by gabizou** [comment]
Literally just re-tested placing a mana bucket in the world, throwing a gold nugget in, and after a few seconds and the liquid turns into Nacre liquid.

This works with and without `-Dsponge.shouldFireAll=true`
Versions used:
SpongeForge 1.12.2-2838-7.1.7-RC3848
Forgelin 1.8.3
LibrarianLib 4.19.2
Wizardry 0.10.8

Is there any other fluid crafting that can be tested that doesn't work?

**Comment by xxlio109** [comment]
I do not understand  

This works with and without -Dsponge.shouldFireAll=true  ？？

**Comment by SamuelWAnderson45** [comment]
Hi gabizou.
I just tried that exact experiment (gold nugget in mana pool) with those exact mod versions you listed, and 0 other mods. Does not work for me.
Perhaps Forge version makes a difference? I've tried with both 2836 and 2838. Neither works.
Maybe some config setting?

**Comment by gabizou** [comment]
I'm curious if there's some sort of server vs client shenanigans going on then...

**Comment by SamuelWAnderson45** [comment]
Hmm. Well my client is the same, except without Sponge and the Forge version is 2836.

**Comment by Zoneman1972** [comment]
I tried that fix and it was working but now its not working anymore.
I'm using Forge 2838 and sponge 3847.
Is there another fix or an update to this mod coming out soon?

**Comment by xxlio109** [comment]
Github There is update
https://github.com/TeamWizardry/Wizardry
