### ISSUE TITLE
Missing version informations

### ISSUE THREAD

**Issue by LemADEC** [SpongePowered/SpongeForge#2797]
**I am currently running**
- SpongeForge version: 1.12.2-2825-7.1.6-RC0 (from #2704)
- Forge version: 14.23.5.2836
- Java version: 1.8.0_212-b04
- Operating System: CentOS

- Plugins/Mods:
n/a

**Issue Description**
Sponge provides a `/sponge version` command. It's very handy to open new issues on Sponge, except it's missing:
- Java version
- Operating system details

Please add those to the command so we can just copy/paste the command output into the issue form :)

**Comment by Zidane** [comment]
This should not have been opened on SF. Move to common.

**Comment by phit** [comment]
~move to sc

**Comment by limbo-app** [comment]
Hey @LemADEC! I've moved your issue to [SpongePowered/SpongeCommon#2281](https://github.com/SpongePowered/SpongeCommon/issues/2281).
