### ISSUE TITLE
Server boot issue with sponge

### ISSUE THREAD

**Issue by Keaton1188** [SpongePowered/SpongeForge#2798]
**I am currently running**

- SpongeForge version: aspongeforge-1.12.2-2825-7.1.6-RC3755.jar
- Forge version: 14.23.5.2838
- Java version:  Java openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-b12)
- Operating System: CentOS Linux release 7.2.1511

- Plugins/Mods: OmniFactory

**Issue Description** Server crashes on boot with sponge added, I have tried booting with SpongeBootstrap and the server is still crashing. 
![Untitled](https://user-images.githubusercontent.com/24898745/58835218-4fbe8300-864d-11e9-8b8e-1400751e6a27.png)

**Comment by Zidane** [comment]
You have a mod who is classloading classes outside of the app class loader. Start removing mods one by one to find the culprit but this is not a Sponge-specific issue.

**Comment by phit** [comment]
Known issue with LibrarianLib https://github.com/TeamWizardry/LibrarianLib/issues/77
