### ISSUE TITLE
Railcraft tunnel bore disappearing when placing [Sponge]: No entity type is registered for class mods.railcraft.common.carts.EntityTunnelBorePart

### ISSUE THREAD

**Issue by BluexRaven** [SpongePowered/SpongeForge#2799]
**I am currently running**
- SpongeForge version: 1.12.2-2825-7.1.6-RC3755
- Forge version: forge-1.12.2-14.23.5.2838-universal.jar
- Java version: Javaj 8 update 211
- Operating System: Dedicated server/ Windows 10

- Plugins/Mods:[minecraft/DedicatedServer]: Mods (102): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AE2 Stuff, AE2 Wireless Terminals (AE2WTLib), Actually Additions, Advanced Generators, AppleSkin, Applied Energistics 2, AutoRegLib, BD Lib, Baubles, Biome Bundle, Chameleon, ChickenChunks, Chisel, Chisels & Bits, CoFH Core, CoFH World, CodeChicken Lib, Ender Compass, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, EnderStorage, Extra Cells 2, Extra Utilities 2, Extreme Reactors, FTB Library, FTB Utilities, FTB Utilities: Backups, Fast Leaf Decay, Galacticraft Core, Galacticraft Planets, Gravestone Mod, Harvest, Inventory Tweaks, Iron Backpacks, Iron Chest, JAOPCA, JourneyMap, JurassiCraft, Just Enough Items, LLibrary, MalisisCore, MalisisDoors, Mantle, McJtyLib, Mekanism, Mekanism: Generators, Micdoodle8 Core, More Planets, Morpheus, MrCrayfish's Furniture Mod, Nature's Compass, NetherPortalFix, OTG Core, Open Terrain Generator, OpenComputers, OpenComputers (Core), OreDictInit, Pam's HarvestCraft, Quark, RFTools, RFTools Control, RFTools Dimensions, Railcraft, Reborn Core, Redstone Flux, Rex's Additional Structures, Simply Jetpacks 2, SpongeForge, Storage Drawers, The One Probe, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Tinkers Tool Leveling, Tinkers' Complement, Tinkers' Construct, UniDict, WanionLib, Water Strainer, Waystones, Wireless Crafting Terminal 2, WrapUp, Zero CORE, p455w0rd's Library

I'm getting an issue placing down a tunnel bore from railcraft, ends up disappearing instantly and I get this error in the server logs
[Sponge]: No entity type is registered for class mods.railcraft.common.carts.EntityTunnelBorePart
https://www.youtube.com/watch?v=ymKdfyHANus

**Comment by phit** [comment]
please add your full debug.log to the issue, upload it to https://gist.github.com/

**Comment by SSKirillSS** [comment]
I remember when I installed railcraft on my modpack, there were so many errors with spongeforge that I deleted railcraft. It will be necessary in the near future to restore it and send logs.

**Comment by phit** [comment]
[00:53] Axle: honestly if you remove Sponge from the server, does it work?
[00:53] Blue Raven: ill give that a shot
[01:04] Blue Raven: didnt work, this is strange

**Comment by liach** [comment]
That thing is just a component like a part of the dragon. It is not supposed to be summoned on its own, and I thought it had been working fine with sponge until someone says that it prevents tunnel bores from spawning.
