### ISSUE TITLE
CustomItemDropTest doesn't let pure Forge clients connect during development

### ISSUE THREAD

**Issue by JBYoshi** [SpongePowered/SpongeForge#2800]
When a client running Forge attempts to connect to a SpongeForge development server running just the test mods and test plugins, they are disconnected with the message "Fatally missing registry entries". This seems to be caused by `CustomItemDropTest`; removing the item registration in that file allows the client to connect.

**Comment by Zidane** [comment]
Yeah @gabizou removing the item being registered does let this work..........................................

**Comment by ImMorpheus** [comment]
Fixed by https://github.com/SpongePowered/SpongeForge/commit/7368e56d1017820366653264714e46446fe9e5d6

We can join the server just fine.
