### ISSUE TITLE
Server Stalls, unable to isolate, .nps included

### ISSUE THREAD

**Issue by Warhawker** [SpongePowered/SpongeForge#2801]
FTB Revelations 3.0.1 (~300+ mods)
Minecraft 1.12
8Gb RAM
~14 players with 3,500 chunks loaded

I've been trying to track down the source of varying stall between 2,500ms all the way to nearly 8,000ms. I've installed sampler, and set a trigger to capture a few. I more or less just need the input of somebody who can interpret this. I suspect garbage collecting stalls, but I have no way to tell other than seeing if the hangs occur at the same time our used memory goes back down. These stalls occur with an intensity of about 2-3,000 ms every couple minutes, and more severe ones >5,000ms every 10-15 minutes.

Using a tick profiler in game does not catch any naughty entities, so the sampler /nps files are all I have left to work on. Reading them is a bit above my skill level, any input would be very much appreciated.

![image](https://user-images.githubusercontent.com/1025748/58930385-b9f42800-8720-11e9-9c43-6d66ddcaf40a.png)

[spike-7089-40980314108.zip](https://github.com/SpongePowered/SpongeForge/files/3255506/spike-7089-40980314108.zip)

**Comment by JBYoshi** [comment]
That would be the autosave mechanism. It seems to be taking a long time to delete the temporary backup files for the player data.

**Comment by Warhawker** [comment]
Is there anyway within spongeforge I can go about fixing this? We are on an SSD, I would imagine it's not a hardware limitation. Also our community is still rather small. At the time of this sample, we have had maybe 50 unique players login.

**Comment by JBYoshi** [comment]
I just started work on some optimizations to the player data save code which might help. You can take a look at the status of those changes [here](https://github.com/SpongePowered/SpongeCommon/pull/2286).

**Comment by Warhawker** [comment]
Thank you very much for the help! Let me know if you would like me to run any builds or check anything else specifically under higher player loads.

**Comment by ImMorpheus** [comment]
PR merged (https://github.com/SpongePowered/SpongeCommon/pull/2286)
