### ISSUE TITLE
ConcurrentModificationException at Mineceraft#onEndTick

### ISSUE THREAD

**Issue by zhourui123** [SpongePowered/SpongeForge#2810]
**I am currently running**

- SpongeForge version: 7.16
- Forge version: 2768
- Java version: 1.8
- Operating System:debian

- Plugins/Mods:

**Issue Description**
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (spongeforge-1.12.2-2825-7.1.6-RC3731.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 6/8/19 8:12 AM
Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at net.minecraft.server.MinecraftServer.handler$onEndTick$bag000(MinecraftServer.java:4089)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:713)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)
```
full log is:
https://gist.github.com/zhourui123/e5ca418ddead9bf7ca176845377c9098

**Comment by Shybella** [comment]
Update your Forge to at least version 2821 and run recommended version of Spongeforge.

**Comment by zhourui123** [comment]
thank you, a question: Are forge2821 server compatible forge2705 client?

**Comment by Zidane** [comment]
Generally you shouldn't mismatch Forge on client and server but you could try it and find out.

**Comment by Zidane** [comment]
@zhourui123 Any update?

**Comment by zhourui123** [comment]
Sorry for the late reply, I did not update it, because the Chinese version official only provides 2705 client, So I don't want to push the server version up too fast. Later, the problem did not appear again, which seems to be because I updated velocity? If this problem occurs again, I will update the version according to your method

EDIT:
Sorry, i realize that not velocity solved this problem, it's due to `map optimizations` option turned on,  just turning this option off will fix the problem.  #2630

**Comment by Zidane** [comment]
Closing this until we hear otherwise then.

**Comment by zhourui123** [comment]
I reedited the reply, this is the compatibility of twilight forest, please review, thank you!

**Comment by phit** [comment]
theres already an open issue for that https://github.com/SpongePowered/SpongeForge/issues/2398
