### ISSUE TITLE
Issue loading correct moons/planets in Galacticraft/ExtraPlanets on Sponge

### ISSUE THREAD

**Issue by ROMVoid95** [SpongePowered/SpongeForge#2812]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2825-7.1.6
- Forge version: forge-1.12.2-14.23.5.2838-universal
- Java version: 1.8.0_211
- Operating System: Win10 

- Plugins/Mods:
Plugins (10): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge,  FastAsyncWorldEdit, Eagle Factions, LuckPerms, Nucleus, RNDWarp, WorldEdit

Mods (100): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, /dank/null, Applied Energistics 2, AutoRegLib, Avaritia, BD Lib, Baubles, Better Combat Rebirth, BiblioCraft, Biomes O' Plenty, Blockcraftery, Botania, Building Gadgets, Calemi's Utils, Chisel, Chisels & Bits, Clumps, CoFH Core, CoFH World, CodeChicken Lib, Corail Tombstone, CraftTweaker JEI Support, CraftTweaker2, Elevator Mod, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, Engineer's Doors, ExoCraft, Extra Planets, Fast Leaf Decay, Galacticraft Core, Galacticraft Planets, ICBM-Classic, Immersive Engineering, Immersive Vehicles (formerly MTS), IndustrialCraft 2, Inventory Tweaks, Just Enough Items, LagGoggles, MCMultiPart, MJRLegendsLib, MTLib, MTS Official Vehicle Pack, MTS military Vehicle Pack, MachineMuse's Modular Powersuits, Malisis Switches, MalisisCore, MalisisDoors, Mantle, MatterOverdrive: Legacy Edition, Mekanism, Mekanism: Generators, Mekanism: Tools, Micdoodle8 Core, Minecraft Chromium Embedded Framework, Mod Tweaker, Morpheus, Mystical Lib, Numina, OMLib, Open Modular Turrets, OpenBlocks, OpenComputers, OpenComputers (Core), OpenGlasses, OpenModsLib, OpenModsLib Core, OreExcavation, OreLib Support Mod, Platforms, Quark, Random Things, Redstone Flux, Shadowfacts' Forgelin, ShetiPhian-Core, Simply Light, SpongeForge, The Beneath, Thermal Expansion, Thermal Foundation, Tinkers Tool Leveling, Tinkers' Construct, WebDisplays, galacticrafttweaker, p455w0rd's Library

**Issue Description**
When i load a brand new world or a already used world off a server i run, going to the moon takes everyone to the moon ganymede of Jupiter, Then the screen just stays on Taking One Giant Step (loading screen for Galacticraft)

latest.log --> https://gist.github.com/ROMVoid95/54380991c71d2c1a70e00a592338e279
the server doesnt crash. this is the latest log, from creating the new world, to getting a rocket, then taking off and i select Moon of earth to launch too.

**Comment by Zidane** [comment]
Can you test without Sponge? I see nothing in the log that pertains to us. You seem to have a plethora of other mod issues.

Also this needs to be tested with just Galacticraft and SpongeForge (and any other mods necessary to trigger this)

**Comment by ROMVoid95** [comment]
i have tested without sponge and this issue does not happen without, were trying to move the server away from sponge to just normal forge because of this with the current world. 

I will go ahead and test with just sponge / GC, should i include ExtraPlanets? being it is part of the GC addon?

**Comment by Zidane** [comment]
Does ExtraPlanets add that moon? If so, yes.

I am more than happy to fix this but I need some specifics to go on for me to run in my dev environment to test with,

**Comment by ROMVoid95** [comment]
so went to test with only Galacticraft and ExtraPlanets. everything seemed to work as intended. So i started to load the plugins 1 by 1, all sponge plugins passed when test, then loaded forgemods, first one loaded was biomes o plenty, passed without issue. then corails tombstone, passed. Next i loaded these
>Applied Energistics2, Avaritia, Baubles, bdlib, calemiutils, code chiken lib, enderCore, EnderIO, IndustrialCraft2, Mekanism, MekanismGenerators, MekanismTools

i was on the moon when i loaded in (i was suppose to be there) performed `/dimensiontp` and received an error. then grabbed a rocket and launch pad, launched, at the moment i was suppose to go to the planet screen, rocket vanished, and i fell back down to the moon. Received the error stated in the logs. This one is a new one on my end but Sponge is spitting out the error. 
Errors start on line 2901
https://gist.github.com/ROMVoid95/ae26d35c352086e54b242ba96effc6cc

**Comment by ROMVoid95** [comment]
other than that, you can close this issue since the problem appeared to be caused by another mod that has yet to be found until rest are loaded in. Appreciate the time and reply!

**Comment by phit** [comment]
previous issue https://github.com/SpongePowered/SpongeForge/issues/2580

**Comment by Zidane** [comment]
@ROMVoid95 What happens if you load those mods without SpongeForge?

**Comment by ROMVoid95** [comment]
The issue never presents itself. I was at the same point that Phit was at with #2580, but i never saw any problems with AE2 in particular. The skys rendered fine the only issue was when traveling to the moon, it would throw a player to Ganymede, it was kinda clockwork.
Launch > Moon puts you on Ganymede
Launch > Mars puts you on Pluto
Jupiter just broke beyond on all and would not render.
Actually loading into any of the planets, regardless of where you launched too just kept a player in the "prepare for landing screen", then have to force disconnect, and they would be on whatever planet/moon it put you on reconnect.

I thought at one point it was plotsquared plugin we had since it was a multidimensional manager and such. But then it happened with this on a test server without that plugin so, i am not sure what happened. Loading in plugins to new server 1 by 1 and forge mods in parts (based off their uses/features) seems to have resolved the issue so far. of course it still could break as it did before.

**Comment by Zidane** [comment]
This screams a dimension id conflict of some sorts..

**Comment by ROMVoid95** [comment]
sure does, however i went through every single config file of every mod at the time, loaded every one, searched all docs for "id" and even read line by line. no duplicate id's, no conflicts on start up or anything. anyway i was first prompted to a sponge issue with this https://github.com/micdoodle8/Galacticraft/issues/3206. but still not having anymore errors. so ¯\_(ツ)_/¯

**Comment by Zidane** [comment]
https://github.com/MinecraftForge/MinecraftForge/issues/3885


Hmmmm

**Comment by ROMVoid95** [comment]
This issue so far since the time it was created has not been logged in our Support server from other mod users, nor has this reappeared in any testing performed with modpacks / development / etc.

Unless there is a preference to keep it open I'm fine closing.
