### ISSUE TITLE
Sponge could not apply one or more patches. A required class was loaded prematurely! 

### ISSUE THREAD

**Issue by aws0jam** [SpongePowered/SpongeForge#2814]
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.1.7-RC3777
- Forge version: 1.12.2-14.23.5.2836
- Java version: java8_211
- Operating System: win 10

- Plugins/Mods:
    Plugins: Nothing 

Mods: FTB Interactions

/dank/null | 1.4.43 | TheRealp455w0rd
Actually Additions | 1.12.2-r142 | Ellpeck
Actually Baubles | 1.1 | Jacky1356400
Advanced Generators | 0.9.20.12 | bdew
Advanced Rocketry | 1.4.1.-103 | No Author Given
Advanced Rocketry Core | 1 | Zmaster587
AE2 Stuff | 0.7.0.4 | bdew
AI Improvements | 0.0.1.3 | No Author Given
Akashic Tome | 1.2-10 | Vazkii
Animania | 1.5.1.1 | RazzleberryFox, Purplicious_Cow, cy4n, Tschipp, ZeAmateis, Timmypote, Raptorfarian, vroulas, and TheJurassicAlien
Animus | 1 | TeamDman, Saereth
AppleCore | 3.1.4 | squeek
AppleSkin | 1.0.9 | squeek
Applied Energistics 2 | rv6-stable-1 | AlgorithmX2
ArchitectureCraft | @VERSION@ | gcewing (Original Developer), darkevilmac (Maintainer)
ArmoreableMobs | 1.1.2 | Buuz135
Astral Sorcery | 1.9.4 | HellFirePvP, wiiv
AutoRegLib | 1.3-20 | Vazkii
Avaritia | 3.2.0 | No Author Given
Backpack | 3.0.2 | Eydamos
Bad Wither No Cookie! Reloaded | 1.12.2-3.1.14 | droidicus, kreezxil
Baubles | 1.5.2 | Azanor
BD Lib | 1.14.3.12 | bdew
Better Advancements | 0.0.14.66 | way2muchnoise
Better Builder's Wands | 0.12.0 | Portablejim
Better Questing | 3.5.269 | Funwayguy
Better Questing Quest Book | 3.1.1-1.12 | Drethic
BiblioCraft | 2.4.5 | Joseph 'Nuchaz' Sinclair
Biome Bundle | 5.1 | No Author Given
Biomes O' Plenty | 7.0.1.2402 | Adubbz, Amnet, Cheeserolls, Forstride, ted80
Block Drops | 1.4.0 | MrRiegel
Blockcraftery | 0.1.3 | Elucent
Blood Magic: Alchemical Wizardry | 1.12.2-2.3.3-101 | WayofTime, TehNut
Bookshelf | 2.3.565 | darkhax, lclc98
Botania | r1.10-356 | Vazkii, williewillus, wiiv, dylan4ever
Brandon's Core | 2.4.5 | brandon3055
Broken Wings | 1.0.0 | quaternary
Building Gadgets | 2.3.5 | Direwolf20
Capability Adapter | 1.0 | rfctksSparkle
Carry On | 1.11 | Tschipp, Purplicious_Cow, cy4n
Chameleon | 1.12-4.1.3 | jaquadro
Chisel | MC1.12.2-0.2.1.35 | tterrag, Drullkus, minecreatr
Chisels & Bits | 14.25 | AlgorithmX2
Chunk Pregenerator | 1.8 | No Author Given
Clay Bucket | 1.1 | abecderic
Clumps | 3.1.1 | Jaredlll08
CodeChicken Lib | 3.2.2.353 | ChickenBones, covers1624
CoFH Core | 4.6.1 | Team CoFH
CoFH World | 1.3.0 | Team CoFH
Colossal Chests | 1.6.11 | rubensworks (aka kroeserr)
Colytra | 1.1.0 | C4
CommonCapabilities | 1.4.0 | rubensworks (aka kroeserr)
Compact Machines 3 | 3.0.12 | Davenonymous
Compact Solar Arrays | 1.12.2-5.0.17.340 | cpw
ComputerCraft | 1.80pr1 | No Author Given
Controlling | 3.0.6 | Jaredlll08
Cooking for Blockheads | 6.4.65 | BlayTheNinth
CosmeticArmorReworked | 1.12.2-v3 | zlainsama
CosmeticArmorReworked Integration for TombManyGraves2 | 1.12.2-v3 | zlainsama
CraftStudio API | 1.0.0 | ZeAmateis, Timmypote, Elisee, IncubeSupreme
CraftTweaker JEI Support | 2.0.2 | No Author Given
CraftTweaker2 | 4.1.9 | StanHebben, Jaredlll08
CT-GUI | 1.0.0 | No Author Given
CTM | MC1.12.2-0.3.2.18 | tterrag, Drullkus, minecreatr
Cucumber Library | 1.1.1 | BlakeBr0
Custom Backgrounds | 1.0 | lumien
Custom Main Menu | 2.0.8 | lumien
Cyclic | 1.17.2 | Lothrazar
Cyclops Core | 0.11.10 | rubensworks (aka kroeserr), immortaleeb (aka _EeB_)
Dark Utilities | 1.8.211 | Darkhax
Default Options | 9.2.7 | BlayTheNinth
Demagnetize | 1.12.2-1.0.0.2 | comp500
Diet Hopper | 1.1 | RWTema
Dirt2Path | 1.7.1 | mallrat208
DiscordSuite | 2.2.4 | Coded
Draconic Evolution | 2.3.15 | brandon3055
EluCore | 1.0 | Elucent
EluLib | 0.1.12 | Elucent
EmberRoot Zoo | 1.3.9 | Lothrazar, Elucent, CrazyPants
Ender IO | 5.0.35 | CrazyPants, tterrag, HenryLoenwind, MatthiasM, CyanideX, EpicSquid
Ender IO Applied Energistics Conduits | 5.0.35 | CrazyPants, tterrag, HenryLoenwind, MatthiasM, EpicSquid
Ender IO Base | 5.0.35 | CrazyPants, tterrag, HenryLoenwind, MatthiasM, CyanideX, EpicSquid
Ender IO Conduits | 5.0.35 | CrazyPants, tterrag, HenryLoenwind, MatthiasM, CyanideX, EpicSquid
Ender IO Integration with Forestry | 5.0.35 | CrazyPants, tterrag, HenryLoenwind, MatthiasM, EpicSquid, bdew, mezz
Ender IO Integration with Tinkers' Construct | 5.0.35 | CrazyPants, tterrag, HenryLoenwind, EpicSquid
Ender IO Integration with Tinkers' Construct | 5.0.35 | CrazyPants, tterrag, HenryLoenwind, EpicSquid
Ender IO Machines | 5.0.35 | CrazyPants, tterrag, HenryLoenwind, MatthiasM, CyanideX, EpicSquid
Ender IO Open Computers Conduits | 5.0.35 | CrazyPants, tterrag, HenryLoenwind, MatthiasM, EpicSquid
Ender IO Powertools | 5.0.35 | CrazyPants, tterrag, HenryLoenwind, MatthiasM, CyanideX, EpicSquid
Ender IO Refined Storage Conduits | 5.0.35 | CrazyPants, tterrag, HenryLoenwind, MatthiasM, EpicSquid
EnderCore | 1.12.2-0.5.41 | tterrag, CrazyPants, HenryLoenwind
EnderStorage | 2.4.5.135 | ChickenBones, covers1624
Environmental Materials | @EM_VERSION@ | ValkyrieofNight
Environmental Tech | 1.12.2-2.0.17.1 | ValkyrieofNight
Ex Compressum | 3.0.26 | BlayTheNinth
Ex Nihilo Creatio | 1.12-0.3.2 | Insaneau, OhYea777, Jacky1356400, BloodWorkXGaming
Exchangers | 1.12.2-2.8 | Jackyy, Turkey2349
Extended Crafting | 1.5.0 | BlakeBr0
Extra Cells 2 | 2.6.1 | M3gaFr3ak, DrummerMC
Extra Utilities 2 | 1.0 | RWTema
Extreme Reactors | 1.12.2-0.4.5.49 | ErogenousBeef, ZeroNoRyouki, ABookFreak
Farming for Blockheads | 3.1.26 | BlayTheNinth
FastFurnace | 1.1.0 | Shadows_of_Fire
FastWorkbench | 1.5.3 | Shadows_of_Fire
Fence Jumper | 1.0.5 | p455w0rd aka TheRealp455w0rd
Flat Colored Blocks | mc1.12-6.6 | AlgorithmX2
FoamFix | 0.10.2-1.12.2 | asiekierka
FoamFixCore | 7.7.4 | asie
Forestry | 5.8.1.349 | SirSengir, mezz
Forge Mod Loader | 8.0.99.99 | cpw, LexManos, Player
FPS Reducer | 1.12.2-1.10.2 | bre2el
FTB Utilities | 5.3.0.51 | LatvianModder
FTBLib | 5.3.0.53 | LatvianModder
GenDustry | 1.6.5.8 | bdew
Gendustry JEI Addon | 1.0.2 | Ninjabrain1
Guide-API | 1.12-2.1.7-62 | Tombenpotter, TehNut
Horse Tweaks | 1.0.4 | BlayTheNinth
Hunger Persistence | 1.0.1 | squeek
Ice and Fire | 1.5.2 | Alexthe666, Raptorfarian
Immersive Engineering | 0.12-85 | BluSunrize, Damien A.W. Hazard
Immersive Petroleum | 1.1.9 | Flaxbeard
Immersive Tech | 1.3.10 | FerroO2000
Industrial Foregoing | 1.12.2-1.12.2 | Buuz135
IndustrialCraft 2 | 2.8.100-ex112 | Alblaka, Player, RichardG, Thunderdark, GregoriusT, alexthesax, Drashian, Elementalist, Feanturi, Lurch1985, SirusKing, tahu44, Aroma1997, estebes, Chocohead
Integrated Dynamics | 0.11.17 | rubensworks (aka kroeserr)
Integrated Tunnels | 1.5.6 | rubensworks (aka kroeserr)
IntegratedDynamics-Compat | 1.0.0 | No Author Given
IntegratedTunnels-Compat | 1.0.0 | No Author Given
Integration Foregoing | 1.12.2-1.7.4 | Jackyy, Buuz135
Inventory Tweaks | 1.64-dev+release.110.b4fac73 | No Author Given
Iron Backpacks | 1.12.2-3.0.8-12 | gr8pefish
Iron Chest | 1.12.2-7.0.51.836 | cpw
IvToolkit | 1.3.3-1.12 | Ivorius
JAOPCA | 1.12.2-2.2.8.94 | TheLMiffy1111
JEI Bees | 0.9.0.5 | bdew
Jeivillagers | 1.0 | Buuz135
JourneyMap | 1.12.2-5.5.2 | techbrew, mysticdrew
Just Enough HarvestCraft | 1.12.2 | mrAppleXZ
Just Enough Items | 4.13.1.220 | mezz
Just Enough Pattern Banners | 1.2.1 | Lorexe
Just Enough Petroleum | 0.1 | BordListian
Just Enough Reactors | 1.1.1.47 | The_BrainStone
Just Enough Resources | 0.8.9.48 | way2muchnoise
Just Enough Throwing In Fluids | 1.1.0 | Lykrast
JustTheTips | 1.12-1.0.1.1 | DeflatedPickle
KleeSlabs | 5.4.11 | BlayTheNinth
Lapis Stays in the Enchanting Table | 1.1.3 | crazysnailboy
LLibrary | 1.7.15 | iLexiconn, gegy1000
Loot Table Tweaker | 1.1.14 | No Author Given
LootTweaker | 0.0.8 | Leviathan143
LunatriusCore | 1.2.0.42 | Lunatrius
Magical Psi | 1.3 | wiiv, Vazkii
Mantle | 1.12-1.3.2.24 | boni, progWML6, Alexbegt
McJtyLib | 3.0.5 | McJty
MCMultiPart | 2.5.3 | No Author Given
Mekanism | 1.12.2-9.4.13.349 | No Author Given
MekanismGenerators | 9.4.11 | No Author Given
Minecraft | 1.12.2 | No Author Given
Minecraft Coder Pack | 9.42 | Searge, ProfMobius, IngisKahn, Fesh0r, r4wk, Zeux, LexManos, cpw, 303, Mr_Okushama, Cryect, Mysterio, bspkrs
Minecraft Forge | 14.23.4.2751 | LexManos, cpw, fry
Mod Tweaker | 4.0.13 | Jaredlll08
ModLister | 1.12.2-3.2.4 | iChun, Quetzi
Modular Diversity | 1.1 | BordListian, DJJBanx, superfluke
Modular Machinery | 1.9.4 | HellFirePvP, wiiv
MoreOverlays | 1.14 | feldim2425
Morph-o-Tool | 1.2-16 | Vazkii
Mouse Tweaks | 2.8 | YaLTeR
MTLib | 3.0.5 | Jaredlll08
Mystical Agradditions | 1.2.8 | BlakeBr0
Mystical Agradditions Compat | 1.2 | NicJames2378
Mystical Agriculture | 1.6.13 | BlakeBr0
Nature's Compass | 1.5.1 | ChaosTheDude
Neat | 1.4-17 | Vazkii
Netherending Ores | 1.12.2-1.2 | ICannt Team
No Mob Spawning on Trees | 1.2.2-mc1.12.2 | oldjunyi
No Night Vision Flashing | 1.2.0 | Team CoFH
NotEnoughIDs | 1.5.4.2 | fewizz, Player
NuclearCraft | 2.12d | tomdodd4598
Nutrition | 3.5.0 | Wes Cook
Open Terrain Generator | v6 | No Author Given
OpenBlocks | 1.8 | Mikee, NeverCast, boq, Lyqyd
OpenComputers | 1.7.2.67 | Sangar, Vexatos, payonel, magik6k, Lord Joda, Github Contributors
OpenComputers (Core) | 1.7.2.67 | Sangar
OpenModsLib | 0.12.1 | Mikee, NeverCast, boq, Lyqyd
OpenModsLib Core | 0.12.1 | Mikee, NeverCast, boq
OreDictInit | 1.12.2-2.2.1.71 | TheLMiffy1111
OreExcavation | 1.4.129 | Funwayguy, Darkosto
OTG Core | 1.12.2 - v7 | PG85
p455w0rd's Library | 2.0.35 | No Author Given
Pam's HarvestCraft | 1.12.2z | Pamela Collins
Placebo | 1.4.1 | Shadows_of_Fire
PlusTiC | 6.5.2.0 | Landmaster (phuong0429)
Pretty Beaches | 1.0.4 | BlayTheNinth
Psi | r1.1-59 | Vazkii
Quark | r1.5-130 | Vazkii, wiiv
Quick Leaf Decay | 1.2.4 | lumien
Random Things | 4.2.1.2 | Lumien
RandomPatches | 1.12.2-1.6.0.1 | TheRandomLabs
ReAuth | 3.6.0 | TechnicianLP
Recurrent Complex | 1.4.7 | Ivorius
Redstone Arsenal | 2.6.1 | Team CoFH
Redstone Flux | 2.1.0 | Team CoFH
Resource Loader | 1.5.3 | lumien
RFTools | 7.56 | McJty
RFTools Control | 1.9.1 | McJty
RFTools Dimensions | 5.61 | McJty
Rustic | 1.0.12 | the-realest-stu
Scannable | 1.6.3.22 | Sangar
Schematica | 1.8.0.169 | Lunatrius
Shadowfacts' Forgelin | 1.7.4 | shadowfacts
Spice of Life: Carrot Edition | 1.3.1 | Cazsius, Talonos
Standard Expansion | 3.4.145 | Funwayguy
Storage Drawers | 1.12-5.3.5 | jaquadro
Super Sound Muffler | 1.0.2.9 | EdgarAllen
SwingThroughGrass | 1.12.2-1.2.3 | Exidex
TESLA | 1.0.63 | Darkhax
Tesla Core Lib | 1.0.15 | Face_of_Cat
Tesla Core Lib Registries | 1.0.15 | Face_of_Cat
Thaumcrafft Inventory Scanning | 2.0.10 | BlayTheNinth
Thaumcraft | 6.1.BETA25 | Azanor
Thaumic Computers | 0.3.0.16 | jco2641
Thaumic Tinkerer | 1.12.2-5.0-353c71c | nekosune
ThaumicJEI | 1.2.1 | Buuz135
The Twilight Forest | 3.8.689 | Benimatic, AtomicBlom, Drullkus, Killer_Demon, quadraxis, Tamaized, williewillus
Thermal Cultivation | 0.3.1 | Team CoFH
Thermal Dynamics | 2.5.3 | Team CoFH
Thermal Expansion | 5.5.2 | Team CoFH
Thermal Foundation | 2.6.1 | Team CoFH
Tinker I/O | release 2.6.1 | GKB, tokomikea
Tinker's JEI | 1.0 | possible_triangle
Tinkers Tool Leveling | 1.12.2-1.0.5.DEV.30c7957 | boni
Tinkers' Complement | ${version} | KnightMiner
Tinkers' Construct | 1.12.2-2.10.1.87 | boni, KnightMiner
TipTheScales | 1.0.1 | Jared
Toast Control | 1.7.1 | No Author Given
Tomb Many Graves | 1.12-4.2.0 | M4thG33k, Tiffit
Tool Progression | 1.12.2-1.5.6 | tyra314
ToroHealth Damage Indicators | 1.12.2-11 | torocraft
UniDict | 1.12.2-2.8 | WanionCane
Universal Modifiers | 1.12.2-1.0.16.1 | No Author Given
Unlimited Chisel Works | 0.2.0 | asie
Unloader | 1.2.0 | Unnoen
Valkyrie Lib | 1.12.2-2.0.17.2 | ValkyrieofNight
Villager Market | 1.0.0 | Face_of_Cat
Vulpes library | 0.2.8.-39 | No Author Given
Waila | 1.8.26 | ProfMobius, TehNut
Waila Harvestability | 1.1.12 | squeek
WanionLib | 1.12.2-1.5 | WanionCane
What Are We Looking At | 2.5.264 | Darkhax
Wireless Charger | 1.3.0 | CreeperShift
Wireless Crafting Terminal 2 | 3.10.82 | TheRealp455w0rd
Woot | 1.12.2-1.4.6 | Ipsis
WrapUp | 1.12-1.1.3 | TheLMiffy1111
XNet | 1.7.4 | McJty
YNot | 0.2.3 | asie
Zero CORE | 1.12-0.1.2.2 | ZeroNoRyouki

**Issue Description**
The problem is: When we are try to start the server we got the error code what is in the title.  We are using SpongeBootstrap and  nothing. Source of the problem is unknown by the log file.  LOG:

https://pastebin.com/UkguUVWQ

**Comment by phit** [comment]
issue with LibrarianLib there's a test build [here](https://github.com/TeamWizardry/LibrarianLib/issues/99#issuecomment-500005705) that fixes the issue
