### ISSUE TITLE
CONSOLE BUG / TIMEOUT

### ISSUE THREAD

**Issue by Miki471151** [SpongePowered/SpongeForge#2815]
I am currently running

SpongeForge version: 1.12.2-2838-7.1.7-RC3777
Forge version: 1.12.2-14.23.5.2836
Java version: java8_211
Operating System: win 10
Plugins/Mods:
Plugins: Nothing
Mods: ALL THE MODS 3

Issue Description
The problem is: When we are playing on the server the server every X times timeouts, when i does not press space or enter to the console. What is the problem ? I doesnt have error,warning on the console.

**Comment by phit** [comment]
turn off quick edit in your console and stop marking stuff in it
