### ISSUE TITLE
[1.12.2] Netty Server IO #8/ERROR

### ISSUE THREAD

**Issue by Miki471151** [SpongePowered/SpongeForge#2816]
I am currently running

SpongeForge version: 1.12.2-2838-7.1.7-RC3777
Forge version: 1.12.2-14.23.5.2836
Java version: java8_211
Operating System: win 10
Plugins/Mods:
Plugins: Nothing
Mods: ALL THE MODS 3

Issue Description
I got this flooded in the console.

LOG: https://pastebin.com/HLJphfeL

**Comment by phit** [comment]
`codechicken.lib.packet.PacketCustom` nothing to do with sponge, please don't use this issue tracker for general support, if you are not sure about an issue you are having you can try or forums or chat https://www.spongepowered.org/chat
