### ISSUE TITLE
NPE on EntityPlayer.getTeam

### ISSUE THREAD

**Issue by clienthax** [SpongePowered/SpongeForge#2817]
**I am currently running**

SpongeForge: 1.12.2-2825-7.1.7-RC3768
Minecraft Forge: 14.23.5.2838
JVM: 1.8.0_202/64-bit (Oracle Corporation)
OS: Linux (4.15.0-43-generic/amd64)

- Plugins: Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, CatClearLag, EpicBanItem, GriefPrevention, LuckPerms, MMCReboot, MMCRules, Nucleus, Prism, ServerListPlus, Total Economy, VpnBeGone, spark, worldedit-sponge
- Mods: Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, Animania, AppleSkin, Applied Energistics 2, Backpack, Basic Nether Ores, Battle Towers, Baubles, BiblioCraft, Bookshelf, Botania, CC: Tweaked, CC: Tweaked, Chest Transporter, Chisel, Chococraft 3, CoFH Core, CoFH World, CodeChicken Lib, CosmeticArmorReworked, CosmeticArmorReworked Integration for TombManyGraves2, CraftStudio API, CraftTweaker JEI Support, CraftTweaker2, CreativeCore, CreativeCoreDummy, Dimensional Doors, DungeonTactics, Enchanting Plus, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, EnderStorage, Energy Converters, Extra Utilities 2, FoamFix, FoamFixCore, Forge Microblocks, Forge Multipart CBE, Galacticraft Core, Galacticraft Planets, HelpFixer, Hexxit Gear, IC2 Classic Detection Helper, Industrial Craft Classic, Industrial Foregoing, Infernal Mobs, Iron Chest, IvToolkit, Just Another Rotten Flesh to Leather Mod, Just Enough Items, LittleTiles, LittleTilesCore, MCMultiPart, Mantle, Micdoodle8 Core, Minecraft Multipart Plugin, MrCrayfish's Furniture Mod, Natura, NoMoreRecipeConflict, OpenBlocks, OpenModsLib, OpenModsLib Core, Pam's HarvestCraft, Placebo, QuackLib, Quick Homes, Quick Teleports, RandomPatches, Recurrent Complex, Redstone Arsenal, Redstone Flux, Redwoods, Reforged, Reliquary, Secret Rooms 5, SecretRooms Hooks, Shadowfacts' Forgelin, Simply Jetpacks 2, Soul Shards Respawn, SpongeForge, Tesla Core Lib, Tesla Core Lib Registries, The Twilight Forest, Thermal Dynamics, Thermal Expansion, Thermal Foundation, TickProfiler, Tinkers' Construct, Traverse, Treecapitator, UniDict, VanillaFix, WanionLib, bspkrsCore, iChunUtil, rswires

**Issue Description**

Caused by a player killing a tower boss from battletowers
crashlog: https://gist.github.com/clienthax/e40185d4fa1d3b17dbc167acfa46d020
snip from server log: https://gist.github.com/clienthax/e7d2508cc2befd0d0e3846ccb945ae55

**Comment by phit** [comment]
previous issue https://github.com/SpongePowered/SpongeForge/issues/2575

**Comment by JBYoshi** [comment]
I wrote some code that can generate a similar stack trace without any mods. It happens when a player manages to deal a killing blow to an entity which sends death messages (e.g. a tamed wolf) and then dies and respawns before the blow hits (for example, using a bow and arrow).

```java
public class DelayedDeath {
    @Listener
    public void onDamage(DamageEntityEvent e, @First DamageSource source) {
        if (!(source instanceof EntityDamageSource)) return;
        Entity entity = ((EntityDamageSource) source).getSource();
        if (source instanceof IndirectEntityDamageSource) entity = ((IndirectEntityDamageSource) source).getIndirectSource();
        if (!(entity instanceof Player)) return;
        Player player = (Player) entity;
        player.sendMessage(Text.of(e.getFinalDamage()));
        if (e.getFinalDamage() >= e.getTargetEntity().require(Keys.HEALTH)) {
            player.damage(100000, DamageSources.MAGIC);
            player.respawnPlayer();
        }
    }
}
```

This issue occurs because the player object is recreated after each respawn. I'm working on a fix for this which delegates the scoreboard methods to the new player object after a respawn.
