### ISSUE TITLE
Fake Player Tracking issue with Super Factory Manager

### ISSUE THREAD

**Issue by Aiidoneus** [SpongePowered/SpongeForge#2819]
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2838-7.1.7-RC3777.jar
- Forge version: forge-1.12.2-14.23.5.2837-universal.jar
- Java version: 8
- Operating System: Ubuntu

- Plugins/Mods:

Mods (11): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, Just Enough Items, RandomPatches, SpongeForge, Super Factory Manager, TickProfiler

Plugins (6): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, GriefPrevention, LuckPerms

**Issue Description**
I am running into the problem with Super Factory Manager's Fake Player. Not 100% how sponge tracks Fake players but it looks like Super Factory Manager (SFM) isn't being tracked correctly as I see the User being `[SFM_PLAYER]` as the user and it should be `Aidoneus` being the user. Hard to explain but will attach the GP Debug log on the bottom. What happens is that the Factory Manager drops the item entity into the world instead of actually placing the block in the world. 
Hopefully I explained this well enough for people to understand. 
Let me know if you need more info

GriefPrevention Debug Log: https://griefprevention.github.io/debug/?LcKNsIkhBn

**Comment by KorewaLidesu** [comment]
try newest version
if problem still exist, then upload console log + debug log

**Comment by clienthax** [comment]
Please retest on latest, reopen if still an issue.
