### ISSUE TITLE
Safe Teleportation Helper

### ISSUE THREAD

**Issue by Cosido** [SpongePowered/SpongeForge#2822]
- SpongeForge version: 3784
- Forge version: 2838
- Java version:  8 
- Operating System: Linux

Upgrading a server from F2809/SF3616

Modlist: https://i.imgur.com/3XkSxBh.png

Upgrading a few servers from 3616 to latest, having a small problem with sponges teleportation helper

On 3616, this config allowed for /rtp to never teleport the player onto bedrock.
https://i.imgur.com/M8oNQmz.png

After Updating, it seems to not 100% accept that config 
https://dl.dropboxusercontent.com/s/52fawqn8cgozfly/ePiSq9joTx.mp4

**Comment by Zidane** [comment]
I did not change the code for the teleport helper and as far as I am aware that code hasn't changed in ages.

@dualspiral ?

**Comment by phit** [comment]
that's not a valid id for unsafe floor, the id would be `minecraft:bedrock`, numerical ids like `7` for bedrock haven't been valid since Minecraft 1.6.4

**Comment by dualspiral** [comment]
Yup, I've not touched it in what must be years, certainly not since 3616. @phit is correct - "7" is not a valid ID.

**Comment by Cosido** [comment]
When I put in minecraft:bedrock, and restart the server, it changes it to what the picture shows.

Edit - It changes the the "7", in https://i.imgur.com/M8oNQmz.png

And It seemed to be working on 3616 as well with that config as mentioned

**Comment by Cosido** [comment]
Nevermind, I was editing it live and restarting. After doing it while server was offline it took it, my apoligies.
