### ISSUE TITLE
realtime CauseCustomNPCserror

### ISSUE THREAD

**Issue by cdcp998** [SpongePowered/SpongeForge#2823]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.1.7-RC3784
- Forge version: 14.23.5.2838
- Java version: 1.8.0_171
- Operating System:Windows 10
[latest.log](https://github.com/SpongePowered/SpongeForge/files/3307616/latest.log)

        # Use real (wall) time instead of ticks as much as possible
        realtime=true
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CustomNPCs (customnpcs)

Caused by: java.lang.NoSuchFieldError: isFake

**Comment by phit** [comment]
Duplicate of https://github.com/SpongePowered/SpongeCommon/issues/2298

**Comment by cdcp998** [comment]
But this problem works fine on the RC3775.

**Comment by cdcp998** [comment]
> 复制 [SpongePowered / SpongeCommon＃2298](https://github.com/SpongePowered/SpongeCommon/issues/2298)

But this problem works fine on the RC3775.

**Comment by phit** [comment]
yes its a bug, that's what that ticket I linked is for

**Comment by cdcp998** [comment]
> yes its a bug, that's what that ticket I linked is for

I understand. Thank you
