### ISSUE TITLE
Toolbars in Creative Mode Do Not Work

### ISSUE THREAD

**Issue by Rage-GitHub** [SpongePowered/SpongeForge#2826]
**I am currently running**

- SpongeForge version: 1.12.2-7.1.7 RC0
- Forge version: N/A
- Java version: 1.8.0_212
- Operating System: Linux

- Plugins/Mods: 
![image](https://user-images.githubusercontent.com/17907584/59952127-1d809400-9449-11e9-9b38-f70d203328af.png)
![image](https://user-images.githubusercontent.com/17907584/59952144-2a04ec80-9449-11e9-9869-958ecf502405.png)

**Issue Description**
Toolbars provided in-game, the ones you can save in creative mode do not work.

**Comment by Zidane** [comment]
@RageYT You can now bump your SF build to a released one. It has the world changes in it lol.

**Comment by Rage-GitHub** [comment]
Ah right, forgot about the released version on the website lol. Thanks for repairing that issue btw.

**Comment by Zidane** [comment]
@RageYT I cannot reproduce this on the latest SF. I saved a hotbar and restored it fine.

**Comment by Rage-GitHub** [comment]
Hmm, alright that is odd because it is happening on my other SV servers.

**Comment by Rage-GitHub** [comment]
Wait, this was supposed to be moved to the SV repo not SF. I don't know why I was directed to SF, my bad.
