### ISSUE TITLE
java.lang.NoClassDefFoundError: AccessorForgeItemStack

### ISSUE THREAD

**Issue by Shybella** [SpongePowered/SpongeForge#2827]
**I am currently running**

- SpongeForge version: 3800
- Forge version: 2836
- Java version: 1.8 201
- Operating System: winserver2016

- Plugins/Mods: FTBRevelations 3.0.1 + https://pastebin.com/raw/QVBKZm3A

**Issue Description**

Running 3800 and getting a issue when using Huskycrates. 

Log: https://pastebin.com/raw/1uT8EiBw

**Comment by Zidane** [comment]
Fixed in next build.

**Comment by Shybella** [comment]
Confirmed fixed
