### ISSUE TITLE
Kicked from server when eating

### ISSUE THREAD

**Issue by Shybella** [SpongePowered/SpongeForge#2828]
**I am currently running**

- SpongeForge version: 3800
- Forge version: 2868
- Java version: j8 201
- Operating System: winserver2016

- Plugins/Mods: FTBRevelations 3.0.1 + https://pastebin.com/raw/QVBKZm3A

**Issue Description**

Player is kicked when trying to eat.

Log: https://pastebin.com/raw/0XrEyeP9

**Comment by Zidane** [comment]
Closed in next build of SF.

**Comment by Shybella** [comment]
Confirmed fixed
