### ISSUE TITLE
Fatal Error PositionOutOfBoundsException 

### ISSUE THREAD

**Issue by Shybella** [SpongePowered/SpongeForge#2829]
**I am currently running**

- SpongeForge version: 3800
- Forge version: 2836
- Java version: j8 201
- Operating System: winsrv16

- Plugins/Mods: FTBRevelations 3.0.1 + https://pastebin.com/raw/QVBKZm3A

**Issue Description**

Log: https://pastebin.com/raw/LePTHQeY

Do not have a reproducible method, currently.

**Comment by gabizou** [comment]
Fixed in latest.

**Comment by Shybella** [comment]
Confirmed fixed
