### ISSUE TITLE
AE2 Crystal Growth Accelerator deleting Items

### ISSUE THREAD

**Issue by Shybella** [SpongePowered/SpongeForge#2830]
**I am currently running**

- SpongeForge version: 3800
- Forge version: 2836
- Java version: j8 201
- Operating System: winsrv16

- Plugins/Mods: FTBRevelations 3.0.1 + https://pastebin.com/raw/QVBKZm3A

**Issue Description**

When dropping "Certus Quartz Seed" into the "Crystal Growth Accelerator" pool it will void the items.
 Video from a player: https://cdn.discordapp.com/attachments/576956138470244387/591764779920523264/2019-06-21_18-59-31.flv

No error in logs but can upload logs via PM.

I can provide more information if needed.

**Comment by Shybella** [comment]
Update: Occurs on 3805. You do not need the crystal growth accelerator to reproduce. Drop the seeds anywhere.

This also happens with Draconic Evolution, drop a wyvern pickaxe.

video: https://cdn.discordapp.com/attachments/576956138470244387/592118456875483136/2019-06-22_18-26-36.flv

**Comment by gabizou** [comment]
Can you re-test with latest? I think in fixing #2795 I might've fixed this one as well.

**Comment by gabizou** [comment]
I'm not getting this to reproduce using latest.

**Comment by Shybella** [comment]
Yes this is fixed
