### ISSUE TITLE
Sky factory 4 server updated, now crashing

### ISSUE THREAD

**Issue by Duedeguy** [SpongePowered/SpongeForge#2831]
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2838-7.1.7-RC3775
Tried the latest Spongeforge, though this one works fine on my other sf4 server
- Forge version: Forge 14.23.5.2838
- Java version: 
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
- Operating System: CentOS 7

**Issue Description**
After updating two Skyfactory 4 servers to 4.0.8, one runs fine without issue and the other starts but then crashes after 2-3 minutes, every time. No players on. When I try a fresh world, the crash does not occur.

Crashlog
https://gist.github.com/Duedeguy/e98fa1259ea15efe5e9ba0c271576043

Console log:
https://gist.github.com/Duedeguy/8461f07fab47ce3b2c9be4e40d17db19

**Comment by phit** [comment]
please test this without Sponge

**Comment by Zidane** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/5861

We'll hold fast and await the outcome of that PR for this one.

**Comment by ichttt** [comment]
Fixed in forge
