### ISSUE TITLE
Server can not finish launch (SF4)

### ISSUE THREAD

**Issue by IC-SubiX** [SpongePowered/SpongeForge#2833]
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2838-7.1.7-RC3808
- Forge version: forge-1.12.2-14.23.5.2838
- Java version: 1.8.0_201
- Operating System: Linux - A Server

- Plugins/Mods:
NO Plugins
Modpack Skyfactory 4  4.0.8 
NO changes on the Modpack

**Issue Description**
Server starts but can not finish the Launch
Problem might be in Class loading.
I tryed out everyting i know about the topic and have not found a solution on the internet yet.

https://gist.github.com/IC-SubiX/b8167e39ae1dbbbe59919184508a0802

[latest.log](https://github.com/SpongePowered/SpongeForge/files/3317823/latest.log)

[crash-2019-06-23_11.52.10-server.txt](https://github.com/SpongePowered/SpongeForge/files/3317824/crash-2019-06-23_11.52.10-server.txt)

**Comment by phit** [comment]
Both SpongeForge and FoamFix add various optimizations that may not work with each other! Disable the following settings in `config/foamfix.cfg`

`B:optimizedBlockPos=false`
`B:patchChunkSerialization=false`
