### ISSUE TITLE
java.lang.IllegalArgumentException: Computercraft Monitor

### ISSUE THREAD

**Issue by Shybella** [SpongePowered/SpongeForge#2835]
**I am currently running**

- SpongeForge version: 3805
- Forge version: 2836
- Java version: j8 201
- Operating System: winsrv16

- Plugins/Mods: FTBRevelations 3.0.1 + https://pastebin.com/raw/QVBKZm3A

**Issue Description**

Crash: https://pastebin.com/raw/fBdnygpb

Unsure how to reproduce but computercraft monitor was sitting next to another computercraft monitor. 

Does NOT occur on RB or 3763 builds.

**Comment by gabizou** [comment]
Retry with 7.1.7-RC3809, pretty sure this is fixed.

**Comment by Zidane** [comment]
Closing due to no response.
