### ISSUE TITLE
Problem with loading chunk at (0, 0)

### ISSUE THREAD

**Issue by electron93** [SpongePowered/SpongeForge#2837]
**I am currently running**

- SpongeForge version: **1.12.2-2838-7.1.7-RC3812**
- Forge version: **14.23.5.2838**
- Java version: **1.8.0_201/64-bit (Oracle Corporation)**
- Operating System: **Linux (4.15.0-52-generic/amd64)**
- Plugins (5): Minecraft, Minecraft Coder Pack, **SpongeAPI**, **Sponge**, **NostalgiaGen**
- Mods (7): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, **SpongeAPI**, **Sponge**, **SpongeForge**

**Issue Description**

![2019-06-24_19 01 19](https://user-images.githubusercontent.com/1076914/60037538-7145e400-96ba-11e9-9a37-2f2d7bc2f374.png)

How to reproduce it:
1. Move to the chunk `(0, 0)` to generate it.
2. Exit the game and turn off the server.
3. Turn on the server, login. Now the chunk `(0, 0)` along with some of its neighbors are not loaded.

[latest.log](https://gist.github.com/electron93/2a5dfa51c9be435786d7156a70bbd25d)

**Comment by JBYoshi** [comment]
Can reproduce on 3813.

**Comment by JBYoshi** [comment]
This should be fixed in 3814 once it comes out.

**Comment by electron93** [comment]
@JBYoshi updated server to 3814, everything is fine 😸. It was very fast, thanks 😃.

**Comment by KorewaLidesu** [comment]
*And also server frozen then :/

**Comment by KorewaLidesu** [comment]
but since it be fixed now
