### ISSUE TITLE
Bug with VanillaFix (mod)

### ISSUE THREAD

**Issue by KorewaLidesu** [SpongePowered/SpongeForge#2839]
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.1.7-RC3818
- Forge version: 14.23.5.2836
- Java version: OpenJDK Runtime Environment (build 1.8.0_212-8u212-b01-1~deb9u1-b01) | OpenJDK 64-Bit Server VM (build 25.212-b01, mixed mode)
- Operating System: Linux (use Pterodactyl panel so not access alot of things)

- Plugins/Mods: https://gist.github.com/madokaorimura/c6bc493159864ea604cc16aaef07d4a0 (Since it so long so compact to a note for easy read)

**Issue Description**
I can access to inventory and take item out, or placing someblock. But break it or attack some animal isn't possible
Console log: https://gist.githubusercontent.com/madokaorimura/21451ed6ef8924068afd6f4ec5d90005/raw/f07efdc7997cda4581689cce1bd6da7de3ff762f/2019-06-25-4.log

Link of the mod issue: https://minecraft.curseforge.com/projects/vanillafix (VanillaFix is a mod that improves performance and fixes bugs and annoyances in vanilla Minecraft. )

**Comment by madokaorimura** [comment]
Not tested with new version yet (https://github.com/DimensionalDevelopment/VanillaFix/releases)

**Comment by madokaorimura** [comment]
Until the mod author online, i will close the issue temp to make sure that him working on it again :/

**Comment by KorewaLidesu** [comment]
New update of SpongeForge has break the mod so it affect to player :thinking: 
Update: Actually newest version of Sponge break my world now :/ (the world file come from client-side, then i upload it to server)

**Comment by TheRealDadbeard** [comment]
Same issue even without vanillafix. Tesing some version out which works fine again. Can place blocks but can't break them, big error message in console can't get that right now.

Edit: 3813 worked testing further.

Edit2: 3817 only throws an error with RandomPatches https://hastebin.com/ipefeseyim.rb
