### ISSUE TITLE
Slight issue with Little Tiles

### ISSUE THREAD

**Issue by TheRealDadbeard** [SpongePowered/SpongeForge#2841]
I posted this to their respective issue tracker and crossposting this here to see if it can/has to be fixed in sponge https://github.com/CreativeMD/LittleTiles/issues/191

**Comment by gabizou** [comment]
Responded on mod issue, not sponge's fault (mod developer depended on implementation interfaces that aren't versioned, or part of SpongeAPI, so recent refactorings/cleanups have broken those interfaces).
