### ISSUE TITLE
Blood Magic TileDemonCrucible cannot be cast to Inventory

### ISSUE THREAD

**Issue by phit** [SpongePowered/SpongeForge#2846]
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.1.7-RC3822                                                                                                                                                                          
- Forge version: 14.23.5.2836 

- Plugins/Mods: Blood Magic

**Issue Description**

have hopper insert into blood magics demon crucible
https://gist.github.com/phit/0c7629297acf21520e7d751ceb67149a

**Comment by Zidane** [comment]
@Faithcaio MixinTileEntityHopper makes assumptions all over the place that IInventory is castable to Inventory. Unless you somehow cache an InventoryAdapter for any IInventory implementation, I can only think that you'll have to create a VanillaAdapter should the implementation be foreign.

```java
    @Redirect(
        method = "pullItems",
        at = @At(
            value = "INVOKE",
            target = "Lnet/minecraft/tileentity/TileEntityHopper;isInventoryEmpty(Lnet/minecraft/inventory/IInventory;Lnet/minecraft/util/EnumFacing;)Z"
        )
    )
    private static boolean impl$throwTransferPreIfNotEmpty(IInventory inventory, EnumFacing facing, IHopper hopper) {
        boolean result = isInventoryEmpty(inventory, facing);
        if (result || !ShouldFire.CHANGE_INVENTORY_EVENT_TRANSFER_PRE) {
            return result;
        }

        final Inventory source;
        if (!(inventory instanceof InventoryAdapter)) {
            source = new VanillaAdapter(MinecraftFabric.of(inventory), null, null);
        } else {
            source = (Inventory) inventory;
        }

        final Inventory destination;
        if (!(inventory instanceof InventoryAdapter)) {
            destination = new VanillaAdapter(MinecraftFabric.of(hopper), null, null);
        } else {
            destination = (Inventory) hopper;
        }

        return SpongeCommonEventFactory.callTransferPre(source, destination).isCancelled();
    }
```

...except these are extremely hot events. Paper has battled them for ages.

Thoughts?

**Comment by Faithcaio** [comment]
Forge has its own impl. for that Hopper stuff. There is a separate Mixins for that in SF.
Question is why does it still go through the vanilla code?

**Comment by Faithcaio** [comment]
Vanilla code is only called when the forge code (`VanillaInventoryCodeHooks#insertHook`) determined that there is nothing to change.
Provided that the Inventory has the IItemHandler capability set up correctly our events already fired
in that case we can just ignore IInventories that do not have Inventory mixed in.

**Comment by Faithcaio** [comment]
I just fixed the casting for now.
This might cause performance problems if a mod implements IInventory but wont provide IItemHandlers that we mixed into.

**Comment by phit** [comment]
this broke with all the Mixin reshuffling, no error spam on 3785, the next version that actually starts up is 3790 and it starts spamming on there

version diff.. I fear this is not the only thing that broke during all of this https://github.com/SpongePowered/SpongeForge/compare/16495e5a5a915cdc7a59555114f4de902d8286f7...442bcc6128b8606755287a093c8ca4e28b77b793

and yes, faiths commit just now fixes the spam, but does it address the underlying issue?
