### ISSUE TITLE
OpenComputers robot console spam

### ISSUE THREAD

**Issue by IteratorW** [SpongePowered/SpongeForge#2848]
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.1.7-RC3775
- Forge version: 14.23.5.2838
- Java version: 1.8.0_201/66 bit
- Operating System: CentOS 7

- Plugins/Mods:
Mods (60): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, Applied Energistics 2, Biomes O' Plenty, Chisel, CoFH Core, CoFH World, CodeChicken Lib, Computronics, CreativeCore, CreativeCoreDummy, CustomNPCs, Dynmap, Energy Converters, Extreme Reactors, Farseek, FoamFix, FoamFixCore, Forestry, Forge Microblocks, Forge Multipart CBE, GeographiCraft, IndustrialCraft 2, Malisis Advert, MalisisCore, MalisisDoors, Mantle, Minecraft Multipart Plugin, MrCrayfish's Furniture Mod, MrTJPCore, OpenBlocks, OpenComputers, OpenComputers (Core), OpenFM, OpenModsLib, OpenModsLib Core, OpenSecurity, ProjectRed Core, ProjectRed Fabrication, ProjectRed Illumination, ProjectRed Transmission, ProjectRed integration, Realistic Terrain Generation, Redstone Flux, SpongeForge, Streams, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Tinkers' Construct, VanillaFix, World Control, WorldEdit, Zero CORE, asielib, projectred-compat

**Issue Description**
When I tried to use a robot my server console got filled with a lot of content. It was spamming until I restarted the server.
There's what it was spamming my server with: https://pastebin.com/s77B3kfx
And it's not an OpenComputers issue - there's already an issue in OC's repo: https://github.com/MightyPirates/OpenComputers/issues/3113
"it appears sponge doesn't like that we call Container.addListener on a container during its constructor. forge is okay with this" so it's Sponge issue.

**Comment by cyb0124** [comment]
This https://github.com/MightyPirates/OpenComputers/blob/859224180265d1e2eefee68c1a44a35a4472b3ca/src/main/scala/li/cil/oc/server/agent/AgentContainer.scala#L12 uses negative slot index. Might that be the cause?

**Comment by IteratorW** [comment]
I guess not if the issue does not occur without Sponge. Should I write to the above referenced issue?
