### ISSUE TITLE
No entity type is registered for Mystical Wildlife & TF2 stuff mod

### ISSUE THREAD

**Issue by LemADEC** [SpongePowered/SpongeForge#2851]
**I am currently running**
- SpongeForge version: 1.12.2-2825-7.1.6-RC3755 & 1.12.2-2838-7.1.7-RC3830
- Forge version: 14.23.5.2836
- Java version: 1.8.0_212
- Operating System: CentOS

- Plugins/Mods:
Mods (126): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AE2 Stuff, AI Improvements, Academy Craft, Advent Of Ascension, Angel of Vengeance, Apotheosis, AppleSkin, Applied Energistics 2, Aquaculture, Attribute Fix, BD Lib, BMA, Baubles, Baubley Heart Canisters, BeastMaster Class Armor, Better Than Mending, Blockcraftery, Building Gadgets, CC: Tweaked, CC: Tweaked, Chisel, CoFH Core, CoFH World, CodeChicken Lib, CraftTweaker JEI Support, CraftTweaker2, CreativeCore, CreativeCoreDummy, Cyberware, Cyclops Core, DeepResonance, ElecCore, ElecCoreLoader, End: Reborn III, EvilCraft, EvilCraft-Compat, Extreme Reactors, FastFurnace, FastWorkbench, FlashFyre's Enchantments, FoamFix, FoamFixCore, Hexxit Gear, ICBM-Classic, InControl, JAOPCA, JourneyMap, Just Enough Dimensions, Just Enough Items, LagGoggles, LambdaLib2|Core, LittleTiles, LittleTilesCore, Login Shield, MachineMuse's Modular Powersuits, Mantle, McJtyLib, Mekanism, Mekanism: Generators, Mekanism: Tools, MetalChests, Metallurgy 4: Reforged, MineTraps, MmmMmmMmmMmm, Moar Tinkers, Mystical Lib, Mystical Wildlife, NuclearCraft, Numina, OMLib, Open Modular Passive Defense, Open Modular Turrets, OreDictInit, PackCrashInfo, Patchouli, Placebo, Prodigy Tech, RandomPatches, RandomTweaks, ReWIRED, Redstone Flux, Reliquary, Rpg Inventory, SG Craft, Shield Parrying, Simple Inventory sorting, Snad, Soup Mod, Spartan Shields, Spartan Weaponry, SpongeForge, Subaraki's Common Library, Subterranean Waters, SwingThroughGrass, TBone, TF2 Stuff Mod, TamModized, Techguns, Techguns Core, Tell Me, Thermal Expansion, Thermal Foundation, Thermal Tinkering, Tinker's JEI, Tinkers Tool Leveling, Tinkers' Construct, Tomb Many Graves, Tool Belt, Trap Expansion, Trinkets and Baubles, Umbralux - Class Armor Mod, Underground Biomes, Waila, WarpDrive, WarpDriveCore, What Are We Looking At, WorldEdit, WrapUp, Zero CORE, lambdalib2

Plugins (17): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, AntiWDL, BetterChunkLoader, Broadcast, CatClearLag, ClearMob, Enjin Minecraft Plugin, GriefPrevention, LuckPerms, Nucleus, Server Backup, Total Economy, WrapperPing, spark

notably:
Mystical Wildlife 1.12.2-1.3.0
TF2 stuff mod 1.12.2-1.5.12

**Issue Description**
Console reporting some entity types aren't registered.

```
[10:58:02] [Server thread/WARN] [Sponge]: No entity type is registered for class lykrast.mysticalwildlife.common.entity.EntityCicaptera$Verdant
...
[11:07:06] [Server thread/WARN] [Sponge]: No entity type is registered for class lykrast.mysticalwildlife.common.entity.EntityCicaptera$Azure
[11:07:17] [Server thread/WARN] [Sponge]: No entity type is registered for class lykrast.mysticalwildlife.common.entity.EntityCicaptera$Crimson
[11:07:19] [Server thread/WARN] [Sponge]: No entity type is registered for class lykrast.mysticalwildlife.common.entity.EntityCicaptera$Sandy
[11:07:21] [Server thread/WARN] [Sponge]: No entity type is registered for class lykrast.mysticalwildlife.common.entity.EntityCicaptera$Wintry
...
[11:15:35] [Server thread/WARN] [Sponge]: No entity type is registered for class rafradek.TF2weapons.entity.EntityDummy
...
[11:15:59] [Server thread/WARN] [Sponge]: No entity type is registered for class lykrast.mysticalwildlife.common.entity.EntityCicaptera$Crimson
```

**Comment by LemADEC** [comment]
As of spongeforge-1.12.2-2838-7.1.7-RC3832 + NuclearCraft-2.17a-1.12.2:
NuclearCraft Feral Ghoul are also reporting the same issue:
```
[14:15:57] [Server thread/WARN] [Sponge]: No entity type is registered for class nc.entity.EntityFeralGhoul
```
Issue isn't reproduced with Krill or Vrontosaurus from MysticalWildlife. Since all entities from that mod are registered the same way, this looks like a Sponge bug here.

**Comment by gabizou** [comment]
Did this start happening since a specific build?

**Comment by LemADEC** [comment]
I've only tested recent builds. Any specific build# you want me to try?

**Comment by LemADEC** [comment]
Issue is reproduced in single player with spongeforge-1.12.2-2838-7.1.7-RC3782 + forge-14.23.5.2838 + mysticalwildlife-1.12.2-1.3.0.
Issue is reproduced in single player with spongeforge-1.12.2-2768-7.1.6-RC3611 + forge-14.23.5.2768 + mysticalwildlife-1.12.2-1.3.0.

Related source code is here: https://github.com/Lykrast/MysticalWildlife/blob/master/src/main/java/lykrast/mysticalwildlife/common/init/ModEntities.java#L140
