### ISSUE TITLE
Enity is not in Chunk error

### ISSUE THREAD

**Issue by TheRealDadbeard** [SpongePowered/SpongeForge#2852]
Hy,

I know this should not be reported but does anyone know what I can do to fix that? How I can remove this exact entity? I just searched around and can't fine anything how to do that. Maybe I'm just dumb or blind but maybe someone can just help me out with that!

**Comment by gabizou** [comment]
As the log mentioned, this is a bugfix to vanilla, it's just letting you know that it's fixing it and catching it.

You can read more [about it on the Paper patch](https://github.com/PaperMC/Paper/blob/75dd53c6ca1f90d5e6bc2cc35cbfd195b9e199ce/Spigot-Server-Patches/0304-Prevent-Saving-Bad-entities-to-chunks.patch#L6)
