### ISSUE TITLE
NoClassDefFoundError WorldGenBushAccessor

### ISSUE THREAD

**Issue by kristi71111** [SpongePowered/SpongeForge#2853]
**I am currently running**

- SpongeForge version: 7.1.7-RC3830
- Forge version: 14.23.5.2836
- Java version: 1.8.0_212
- Operating System: Centos 7

- Plugins/Mods:
**Mods (147):** Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AE2 Stuff, AI Improvements, Advanced Machines, Advanced Solar Panels, AppleSkin, Applied Energistics 2, Aroma1997's Dimensional World, Aroma1997Core, AutoRegLib, BD Lib, Baubles, BiblioCraft, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Blockcraftery, BuildCraft, BuildCraft Builders, BuildCraft Compat, BuildCraft Energy, BuildCraft Factory, BuildCraft Lib, BuildCraft Robotics, BuildCraft Silicon, BuildCraft Transport, CC: Tweaked, CC: Tweaked, Charset, Chisel, Chisels & Bits, CoFH Core, CoFH World, CodeChicken Lib, Compact Solar Arrays, Computronics, CraftTweaker JEI Support, CraftTweaker2, Crafting Tweaks, Diet Hopper, EnderStorage, Energy Converters, FTB Library, FTB Utilities, Fancy Fluid Storage, FastWorkbench, Flat Colored Blocks, FoamFix, FoamFixCore, Forestry, Forge Microblocks, Forge Multipart CBE, Gravitation Suite, GravityGun, Guide-API, Harvest, Immersive Cables, Immersive Engineering, Industrial Foregoing, IndustrialCraft 2, Integration Foregoing, Iron Chest, JEI Bees, Just Enough Energistics, Just Enough Items, Long Fall Boots, MCMultiPart, MTLib, MachineMuse's Modular Powersuits, MagicBees, MineTogether, MineTogetherServer, Minecraft Multipart Plugin, Mod Tweaker, Modular ForceField System, Modular Routers, Morph-o-Tool, Morpheus, MrTJPCore, Mystical Lib, Netherending Ores, Numina, PeripheralsPlusOne, Phosphor Lighting Engine, Placebo, Player Plates, Plethora, Plethora Core, PortalGun, ProjectRed Core, ProjectRed Expansion, ProjectRed Exploration, ProjectRed Fabrication, ProjectRed Illumination, ProjectRed Relocation, ProjectRed Transmission, ProjectRed Transportation, ProjectRed integration, ProjectX 2, Railcraft, RandomPatches, Reborn Core, Redstone Flux, Reliquary, Retro Exchange, Sampling Performance Profiler, Shadowfacts' Forgelin, Silverfish, Simple Corn, Smooth Font Core, Soul Shards Respawn, SpongeForge, Steve's Carts 2, TOP Addons, Tech Reborn, Tech Reborn Mod Compatibility, Tesla Core Lib, Tesla Core Lib Registries, Thaumcrafft Inventory Scanning, Thaumcraft, Thaumic Energistics, Thaumic Tinkerer, The Framework, The One Probe, The Twilight Forest, Thermal Dynamics, Thermal Expansion, Thermal Foundation, TickProfiler, TorchMaster, Traverse, UniDict, WanionLib, WirelessRedstone-CBE, World Control, YABBA, asielib, iChunUtil, projectred-compat
**Plugins (34):** Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, ActiveTime, AsciiEmotes, BacoMaster, BacoSkyRestrict, BaconTowny, BetterChunkLoader, CatClearLag, CommandUtils, EasyTexts, EconomyLite, Enjin Minecraft Plugin, Holograms, KitSuiteEC, Lottery, LuckPerms, MMCRestrict, NuVotifier, Nucleus, PlaceholderAPI, Prism, ProjectBorders, ProjectCore, SeriousVote, Sledgehammer, TabManager, Unity, VoteParty, WelcomeRewards, WorldEdit, spark

**Issue Description**
Upon updating to 7.1.7-RC3830 the server crashes when players generate certain terain. The crash is not present on 7.1.7-RC3821. 
[Crash report](https://gist.github.com/kristi71111/ec3de180bd58d6602568dda085137faa)
[2019-06-29-6.log](https://github.com/SpongePowered/SpongeForge/files/3342128/2019-06-29-6.log)

**Comment by gabizou** [comment]
Should be fixed in latest.
