### ISSUE TITLE
RejectedExecutionException when placing stairs

### ISSUE THREAD

**Issue by LemADEC** [SpongePowered/SpongeForge#2855]
**I am currently running**
- SpongeForge version: 1.12.2-2838-7.1.7-RC3832
- Forge version: 14.23.5.2836
- Java version: 1.8.0_212/64-bit
- Operating System: Linux

- Plugins/Mods:
Mods (127): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AE2 Stuff, AI Improvements, Academy Craft, Advent Of Ascension, Angel of Vengeance, Apotheosis, AppleSkin, Applied Energistics 2, Aquaculture, Attribute Fix, BD Lib, BMA, Baubles, Baubley Heart Canisters, BeastMaster Class Armor, Better Than Mending, Blockcraftery, Building Gadgets, CC: Tweaked, CC: Tweaked, Chisel, CoFH Core, CoFH World, CodeChicken Lib, CraftTweaker JEI Support, CraftTweaker2, CreativeCore, CreativeCoreDummy, Cyberware, Cyclops Core, DeepResonance, ElecCore, ElecCoreLoader, End: Reborn III, EvilCraft, EvilCraft-Compat, Extreme Reactors, FastFurnace, FastWorkbench, FlashFyre's Enchantments, FoamFix, FoamFixCore, Guide-API, Hexxit Gear, ICBM-Classic, InControl, Inventory Tweaks, JAOPCA, JourneyMap, Just Enough Dimensions, Just Enough Items, LagGoggles, LambdaLib2|Core, LittleTiles, LittleTilesCore, Login Shield, MachineMuse's Modular Powersuits, Mantle, McJtyLib, Mekanism, Mekanism: Generators, Mekanism: Tools, MetalChests, Metallurgy 4: Reforged, MineTraps, MmmMmmMmmMmm, Moar Tinkers, Mystical Lib, Mystical Wildlife, NuclearCraft, Numina, OMLib, Open Modular Passive Defense, Open Modular Turrets, OreDictInit, PackCrashInfo, Patchouli, Placebo, Prodigy Tech, RandomPatches, RandomTweaks, ReWIRED, Redstone Flux, Reliquary, Rpg Inventory, SG Craft, Shield Parrying, Simple Inventory sorting, Snad, Soup Mod, Spartan Shields, Spartan Weaponry, SpongeForge, Subaraki's Common Library, Subterranean Waters, SwingThroughGrass, TBone, TamModized, Techguns, Techguns Core, Tell Me, The One Probe, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Tinkering, Tinker's JEI, Tinkers Tool Leveling, Tinkers' Construct, Tool Belt, Trap Expansion, Trinkets and Baubles, Umbralux - Class Armor Mod, Underground Biomes, WarpDrive, WarpDriveCore, Woot, WorldEdit, WrapUp, Zero CORE, lambdalib2

Plugins (17): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, AntiWDL, BetterChunkLoader, Broadcast, CatClearLag, ClearMob, Enjin Minecraft Plugin, GriefPrevention, LuckPerms, Nucleus, Server Backup, Total Economy, WrapperPing, spark

**Issue Description**
Console spam whenever a stair is placed, from vanilla or a mod

 ```
[18:47:56] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.util.concurrent.RejectedExecutionException: Task net.minecraft.world.chunk.Chunk$$Lambda$2246/1799812472@1e7cd8bb rejected from java.util.concurrent.ThreadPoolExecutor@53b13e49[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 564634]
>       at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_212]
>       at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_212]
>       at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
>       at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:306) [SpongeImplHooks.class:1.12.2-2838-7.1.7-RC3832]
>       at net.minecraft.server.MinecraftServer.redirect$onRun$zjl000(MinecraftServer.java:4470) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.util.concurrent.RejectedExecutionException: Task net.minecraft.world.chunk.Chunk$$Lambda$2246/1799812472@1e7cd8bb rejected from java.util.concurrent.ThreadPoolExecutor@53b13e49[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 564634]
>       at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063) ~[?:1.8.0_212]
>       at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830) ~[?:1.8.0_212]
>       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379) ~[?:1.8.0_212]
>       at net.minecraft.world.chunk.Chunk.handler$onRelightBlock$zpa000(Chunk.java:5708) ~[axw.class:?]
>       at net.minecraft.world.chunk.Chunk.func_76615_h(Chunk.java) ~[axw.class:?]
>       at net.minecraft.world.chunk.Chunk.setBlockState(Chunk.java:3835) ~[axw.class:?]
>       at org.spongepowered.common.event.tracking.PhaseTracker.setBlockState(PhaseTracker.java:823) ~[spongeforge-1.12.2-2838-7.1.7-RC3832.jar:1.12.2-2838-7.1.7-RC3832]
>       at net.minecraft.world.WorldServer.func_180501_a(WorldServer.java:4529) ~[oo.class:?]
>       at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:180) ~[ahb.class:?]
>       at net.minecraft.item.ItemBlock.func_180614_a(ItemBlock.java:54) ~[ahb.class:?]
>       at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:187) ~[aip.class:?]
>       at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:956) ~[or.class:?]
>       at net.minecraft.network.NetHandlerPlayServer.redirect$onProcessRightClickBlock$zja000(NetHandlerPlayServer.java:2433) ~[pa.class:?]
>       at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:741) ~[pa.class:?]
>       at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
>       at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
>       at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:191) ~[PacketPhaseUtil.class:1.12.2-2838-7.1.7-RC3832]
>       at net.minecraft.network.PacketThreadUtil$1.redirect$impl$redirectToPhaseTracker$zlh000(SourceFile:540) ~[hv$1.class:?]
>       at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
>       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]
>       at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
>       at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
>       ... 7 more
```

**Comment by Zidane** [comment]
@LemADEC Can you retest on latest?

**Comment by LemADEC** [comment]
I'm unable to reproduce with async-relight off and the following:
Mods (124): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AE Net Vis Tool, AE2 Stuff, AI Improvements, Advanced Fishing, Advent Of Ascension, Angel of Vengeance, Apotheosis, AppleSkin, Applied Energistics 2, Attribute Fix, BD Lib, Bauble Wings, Baubles, Baubley Heart Canisters, Better Than Mending, Blockcraftery, Botania, Brandon's Core, Building Gadgets, CC: Tweaked, Chisel, CoFH Core, CoFH World, CodeChicken Lib, CraftTweaker JEI Support, CraftTweaker2, CreativeCore, CreativeCoreDummy, CustomNPCs, Cyberware, Cyclops Core, ElecCore, ElecCoreLoader, EvilCraft, EvilCraft-Compat, Extreme Reactors, FastFurnace, FastWorkbench, FlashFyre's Enchantments, FoamFix, FoamFixCore, Guide-API, Hexxit Gear, ICBM-Classic, InControl, Inventory Tweaks, JAOPCA, JourneyMap, Just Enough Dimensions, Just Enough Items, LLibrary, LittleTiles, LittleTilesCore, Login Shield, MTLib, MachineMuse's Modular Powersuits, Mantle, Mekanism, Mekanism: Generators, Mekanism: Tools, MetalChests, Metallurgy 4: Reforged, MineTraps, MmmMmmMmmMmm, Moar Tinkers, Mod Tweaker, Mystical Lib, Mystical Wildlife, NuclearCraft, Numina, OMLib, Open Modular Passive Defense, Open Modular Turrets, OreDictInit, PackCrashInfo, Patchouli, Placebo, Prodigy Tech, Quick Leaf Decay, RandomPatches, RandomTweaks, Redstone Flux, Reliquary, Ruins Mod, SG Craft, Shield Parrying, Simple Inventory sorting, Snad, Soup Mod, Spartan Shields, Spartan Weaponry, SpongeForge, Subterranean Waters, SwingThroughGrass, TBone, TOP Addons, TamModized, Techguns, Techguns Core, Tell Me, The One Probe, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Tinker's JEI, Tinkers Tool Leveling, Tinkers' Construct, Tool Belt, Underground Biomes, WarpDrive, WarpDriveCore, Wings, Woot, WorldEdit, Worley's Caves, WrapUp, Zero CORE

Plugins (17): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, AntiWDL, BetterChunkLoader, Broadcast, CatClearLag, ClearMob, Enjin Minecraft Plugin, GriefPrevention, LuckPerms, Nucleus, Server Backup, Total Economy, WrapperPing, spark

Sponge version
    SpongeForge: 1.12.2-2838-7.1.7-RC3832
    Minecraft Forge: 14.23.5.2836
    JVM: 1.8.0_212/64-bit (Oracle Corporation)
    OS: Linux (3.14.32-xxxx-grs-ipv6-64/amd64)

I'm also unable to reproduce with spongeforge-1.12.2-2838-7.1.7-RC3868 + LagGoggles.
It was probably due to one of the mods we've removed since initial reproduction, or from disabling async-relight in Sponge.

Do you want me to dig further or we close it 'as is'?

**Comment by ImMorpheus** [comment]
@LemADEC What's num-threads in global.conf ? (in the AsyncLightingCategory)

**Comment by LemADEC** [comment]
```
        async-lighting {
            # If 'true', lighting updates are run asynchronously.
            enabled=true
            # The amount of threads to dedicate for asynchronous lighting updates. (Default: 2)
            num-threads=2
        }
```

**Comment by Zidane** [comment]
Will close as-is for now.
