### ISSUE TITLE
java.lang.NoClassDefFoundError: org.spongepowered.common.mixin.core.world.gen.feature.WorldGenBushAccessor is a mixin class and cannot be referenced directly

### ISSUE THREAD

**Issue by clienthax** [SpongePowered/SpongeForge#2856]
**I am currently running**

Minecraft: 1.12.2
SpongeAPI: 7.1.0-a56d82c4c
Sponge: 1.12.2-7.1.7-SNAPSHOT
SpongeForge: 1.12.2-2838-7.1.7-RC3832
Minecraft Forge: 14.23.5.2838
JVM: 1.8.0_202/64-bit (Oracle Corporation)
OS: Linux (4.15.0-43-generic/amd64)

- Plugins (17): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, CatClearLag, EpicBanItem, GriefPrevention, LuckPerms, MMCReboot, MMCRules, Nucleus, Prism, ServerListPlus, Total Economy, VpnBeGone, spark, worldedit-sponge

Mods (111): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, Animania, AppleSkin, Applied Energistics 2, Backpack, Basic Nether Ores, Battle Towers, Baubles, BiblioCraft, Bookshelf, Botania, CC: Tweaked, CC: Tweaked, Chest Transporter, Chisel, Chococraft 3, CoFH Core, CoFH World, CodeChicken Lib, CosmeticArmorReworked, CosmeticArmorReworked Integration for TombManyGraves2, CraftStudio API, CraftTweaker JEI Support, CraftTweaker2, CreativeCore, CreativeCoreDummy, Dimensional Doors, DungeonTactics, Enchanting Plus, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, EnderStorage, Energy Converters, Extra Utilities 2, FoamFix, FoamFixCore, Forge Microblocks, Forge Multipart CBE, Galacticraft Core, Galacticraft Planets, HelpFixer, Hexxit Gear, IC2 Classic Detection Helper, Industrial Craft Classic, Industrial Foregoing, Infernal Mobs, Iron Chest, IvToolkit, Just Another Rotten Flesh to Leather Mod, Just Enough Items, LittleTiles, LittleTilesCore, MCMultiPart, Mantle, Micdoodle8 Core, Minecraft Multipart Plugin, MrCrayfish's Furniture Mod, Natura, NoMoreRecipeConflict, OpenBlocks, OpenModsLib, OpenModsLib Core, Pam's HarvestCraft, Placebo, QuackLib, Quick Homes, Quick Teleports, RandomPatches, Recurrent Complex, Redstone Arsenal, Redstone Flux, Redwoods, Reforged, Reliquary, Secret Rooms 5, SecretRooms Hooks, Shadowfacts' Forgelin, Simply Jetpacks 2, Soul Shards Respawn, SpongeForge, Tesla Core Lib, Tesla Core Lib Registries, The Twilight Forest, Thermal Dynamics, Thermal Expansion, Thermal Foundation, TickProfiler, Tinkers' Construct, Traverse, Treecapitator, UniDict, VanillaFix, WanionLib, bspkrsCore, iChunUtil, rswires

**Issue Description**

Last bit of server log: https://gist.github.com/clienthax/e67bbdabc91ff6dca063473114d1386c
crashlog: https://gist.github.com/clienthax/3c62d12605888d632377452a4a22ba42

[2019-06-30-5.log](https://github.com/SpongePowered/SpongeForge/files/3342846/2019-06-30-5.log)

**Comment by clienthax** [comment]
This might belong on common actually..

**Comment by phit** [comment]
https://github.com/SpongePowered/SpongeForge/issues/2853
