### ISSUE TITLE
Illegal Async Chunk Load with Enderio

### ISSUE THREAD

**Issue by clienthax** [SpongePowered/SpongeForge#2857]
**I am currently running**
Minecraft: 1.12.2
SpongeAPI: 7.1.0-a56d82c4c
Sponge: 1.12.2-7.1.7-SNAPSHOT
SpongeForge: 1.12.2-2838-7.1.7-RC3832
Minecraft Forge: 14.23.5.2838
JVM: 1.8.0_202/64-bit (Oracle Corporation)
OS: Linux (4.15.0-43-generic/amd64)

Plugins (17): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, CatClearLag, EpicBanItem, GriefPrevention, LuckPerms, MMCReboot, MMCRules, Nucleus, Prism, ServerListPlus, Total Economy, VpnBeGone, spark, worldedit-sponge
Mods (111): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, Animania, AppleSkin, Applied Energistics 2, Backpack, Basic Nether Ores, Battle Towers, Baubles, BiblioCraft, Bookshelf, Botania, CC: Tweaked, CC: Tweaked, Chest Transporter, Chisel, Chococraft 3, CoFH Core, CoFH World, CodeChicken Lib, CosmeticArmorReworked, CosmeticArmorReworked Integration for TombManyGraves2, CraftStudio API, CraftTweaker JEI Support, CraftTweaker2, CreativeCore, CreativeCoreDummy, Dimensional Doors, DungeonTactics, Enchanting Plus, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, EnderStorage, Energy Converters, Extra Utilities 2, FoamFix, FoamFixCore, Forge Microblocks, Forge Multipart CBE, Galacticraft Core, Galacticraft Planets, HelpFixer, Hexxit Gear, IC2 Classic Detection Helper, Industrial Craft Classic, Industrial Foregoing, Infernal Mobs, Iron Chest, IvToolkit, Just Another Rotten Flesh to Leather Mod, Just Enough Items, LittleTiles, LittleTilesCore, MCMultiPart, Mantle, Micdoodle8 Core, Minecraft Multipart Plugin, MrCrayfish's Furniture Mod, Natura, NoMoreRecipeConflict, OpenBlocks, OpenModsLib, OpenModsLib Core, Pam's HarvestCraft, Placebo, QuackLib, Quick Homes, Quick Teleports, RandomPatches, Recurrent Complex, Redstone Arsenal, Redstone Flux, Redwoods, Reforged, Reliquary, Secret Rooms 5, SecretRooms Hooks, Shadowfacts' Forgelin, Simply Jetpacks 2, Soul Shards Respawn, SpongeForge, Tesla Core Lib, Tesla Core Lib Registries, The Twilight Forest, Thermal Dynamics, Thermal Expansion, Thermal Foundation, TickProfiler, Tinkers' Construct, Traverse, Treecapitator, UniDict, VanillaFix, WanionLib, bspkrsCore, iChunUtil, rswires

**Issue Description**

Seems to be an issue with sponge when async lighting is in place
Conduits attempt to return a light value based on the TE, which in turn causes this to load a chunk off thread.
Raised to EnderIO under: https://github.com/SleepyTrousers/EnderIO/issues/5163

~~~~
The code in question tried to get the TileEntity for the block that is being asked for it's data. That should never trigger a chunk load, for to ask a block for its data, that block must be loaded.

Also, it's Sponge who does this outside the World thread without using a ChunkCache, which violates vanilla's rules about thread-safety.
~~~~

**Comment by clienthax** [comment]
Same issue with ic2classic
https://gist.github.com/clienthax/1c74b8715b162507fddfd8abe3a87c01

**Comment by Kantets** [comment]
Same issue with immersive engineering.
When teleporting to a player's base, client is crashing before rendering blocks in the world

**Comment by Zidane** [comment]
Unfortunately IC2 is fetching a TileEntity when light opacity is being fetched which is running on the Async Light Thread and triggers this issue. Basically as we want to fire LoadChunkEvent. Turn off the async lighting as fixing this is something that isn't a 5 minute change and Async Light is being removed (in favor of Vanilla's) in 1.14.
