### ISSUE TITLE
Players are disconnecting in large Numbers

### ISSUE THREAD

**Issue by zhourui123** [SpongePowered/SpongeForge#2862]
**I am currently running**

- SpongeForge version: 1.12.2-2825-7.1.6-RC3731.jar
- Forge version: 2768
- Java version: java8
- Operating System:debian

- Plugins/Mods:
mfbl_common_plugin-1.0.jar,
mfbl_survival_plugin-1.0-SNAPSHOT.jar,
mfbl-1.0.jar,
spongeforge-1.12.2-2825-7.1.6-RC3731.jar,
twilightforest-1.12.2-3.8.689-universal.jar,
Nucleus-1.11.0-S7.1-MC1.12.2-plugin.jar,
Ferdinand'sFlowers-1.12.x-1.10.4.1.jar

**Issue Description**
Players were disconnected in large Numbers, there was no error log printing, whether it was out of memory or a configuration file problem, I couldn't figure out what the problem was and asked for support. I expect to learn how to use spark to analyze memory tomorrow. If more information is needed, I will provide it in time.
server log position :
line`17642` or timestamp `15:44:45`;
line`18568` or timestamp `16:01:18`(There is a database exception, but it should not be caused by this);
line`19028` or timestamp`16:20:43`
line`21032` or timestamp`17:38:06`
line`28172` or timestamp`20:04:32`

**aikar timing:** 
https://timings.aikar.co/?id=fa331a0aec114b8baf1ca8b7ec4bd903

**server and velocity logs:** https://gist.github.com/zhourui123/850226c9ad41286cde3803f0c289c174

**global.conf:**
https://gist.github.com/zhourui123/5cdca1bbbe141adcc33f585fdbb1661f

**Comment by phit** [comment]
does this happen without Velocity?

**Comment by zhourui123** [comment]
Ok, I will switch to Waterfall tomorrow. Please give me a few days to observe, thank you

**Comment by zhourui123** [comment]
It was confirmed that the same problem would occur at the Waterfall

**Comment by zhourui123** [comment]
I found out that entering the twilight portal caused the timeout, and I am now confirming with the twilight team which side the problem is

**Comment by zhourui123** [comment]
It took 3 minutes to get into the TF. After using spark analysis, I found that the problem seems to be caused by the save mechanism of sponge. Could you please help me to have a look?
https://sparkprofiler.github.io/#b0KrfvizJr

**Comment by ImMorpheus** [comment]
Fixed by https://github.com/SpongePowered/SpongeCommon/commit/1436812cb1d3b504edaa56fb447ae9ac3d06d086

**Comment by zhourui123** [comment]
It has been fixed, but I can't download the latest build from the SpongeForge download page
