### ISSUE TITLE
Large Chunk

### ISSUE THREAD

**Issue by htutich** [SpongePowered/SpongeForge#2863]
When will fix this error in sponge?
https://github.com/MinecraftForge/MinecraftForge/blob/1.13.x/patches/minecraft/net/minecraft/world/chunk/storage/RegionFile.java.patch

**Comment by Zidane** [comment]
That is 1.13 code. This project is still on 1.12.2

**Comment by htutich** [comment]
Are you serious? I do not care that I gave an example 1.13. This error is relevant to the sponge.

**Comment by Zidane** [comment]
No the error is relevant to FORGE. Go ask FORGE to fix this in 1.12.2

**Comment by phit** [comment]
@Zidane [It already is](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/patches/minecraft/net/minecraft/world/chunk/storage/RegionFile.java.patch), however we should also have this in SpongeVanilla and replace https://github.com/SpongePowered/SpongeCommon/commit/0f8df35e74e1e1cce7974220e8c5e1df68acd9fa#diff-a7ebc8e2f519f9a5a1c7d570c30aaf59

see https://github.com/SpongePowered/SpongeCommon/issues/2156

**Comment by Zidane** [comment]
Then open an issue on SpongeVanilla for this. The original issue is a non-issue for SpongeForge.
