### ISSUE TITLE
[1.12.2-2838-7.1.7-RC3841] crash when trying to generate a world

### ISSUE THREAD

**Issue by lampyr** [SpongePowered/SpongeForge#2864]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.1.7-RC3841
- Forge version: forge-14.23.5.2838
- Java version: i don't know
- Operating System: i don't know

- Plugins/Mods:
0 plugins for the moment
![listeMod1](https://user-images.githubusercontent.com/7419371/60752165-8f68e980-9fc2-11e9-8ac4-d6cc3ab7cc74.png)
![listeMod2](https://user-images.githubusercontent.com/7419371/60752166-90018000-9fc2-11e9-8f3e-3295f79dbe2a.png)

**Issue Description**
same as  https://github.com/SpongePowered/SpongeForge/issues/2840#issue-460514954

crash log: https://pastebin.com/KRUCdRHE

**Comment by KorewaLidesu** [comment]
Have you update librarianlib, sir?

**Comment by lampyr** [comment]
hello yes and i think i have found the problem: DimensionalDevelopment/JustEnoughIDs/issues/73

Can you help me with that?

**Comment by KorewaLidesu** [comment]
Downgrade the SF version until NEID updated cause by the changing of Mixins

**Comment by lampyr** [comment]
i downgrade to which version?

**Comment by KorewaLidesu** [comment]
Try RC3805

**Comment by lampyr** [comment]
Thank you it function. i don't know if i must close the issue.

**Comment by BlazeRuler** [comment]
Yes RC3805 is the last Spongeforge version to be functionable with JustEnoughIDs currently.

**Comment by Zidane** [comment]
https://github.com/DimensionalDevelopment/JustEnoughIDs/issues/73

Issue fixed on JustEnoughIDs end (by a PR I made). Their team is making a new release on CurseForge.
