### ISSUE TITLE
The difficulty does not change.

### ISSUE THREAD

**Issue by taisa-vol12** [SpongePowered/SpongeForge#2865]
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.1.7-RC3841
- Forge version: 4.23.5.2838
- Java version: 1.8.0_212
- Operating System: CentOS

- Plugins/Mods:
![305a4f4eaf83f007d46dbb93a51dec66](https://user-images.githubusercontent.com/43507215/60757435-7a816a00-a045-11e9-8510-4258876369d2.png)
![caf1354c24f04ab8e90f757aa2faeae2](https://user-images.githubusercontent.com/43507215/60757436-7a816a00-a045-11e9-9a3d-14ee3199ace2.png)

**Issue Description**
The difficulty does not change.

Mode does not change with "/ difficulty"

It is written as hard mode, but it is actually peaceful mode.

**Comment by ItsDoot** [comment]
Reproduced with no mods on `1.12.2-2838-7.1.7-RC3841` and `1.12.2-2838-7.1.7-RC3847`.

**Steps to reproduce:**
- Start on a non-peaceful difficulty.
- Run `/difficulty peaceful`
- Run `/difficulty <non peaceful>`. The message is sent saying it's set, but it fails to actually set the difficulty (as either a player or the console).

**Reason:**

The `level.dat` doesn't seem to update with the new difficulty.

**Comment by Zidane** [comment]
Will be fixed in next common bump of SF.
