### ISSUE TITLE
Sponge Config reverts to default

### ISSUE THREAD

**Issue by SeaDonkey81** [SpongePowered/SpongeForge#2866]
**I am currently running**

- SpongeForge version:  spongeforge-1.12.2-2825-7.1.6
- Forge version:  forge-1.12.2-14.23.5.2825-universal
- Java version: 8
- Operating System: windows 8

- Plugins/Mods:
https://gist.github.com/SeaDonkey81/4367845714ccd278004f8c5b19802b86

**Issue Description**
Sponge Config reverts to default every time the server is restarted. This started happening a few days ago. 

-Please provide a *full* server log (and crash-report if applicable).
       https://gist.github.com/SeaDonkey81/88560c8f2fe2278f6bde4f817b3a9438

**Comment by phit** [comment]
post your edited config

**Comment by SeaDonkey81** [comment]
Edited Sponge Config

https://gist.github.com/SeaDonkey81/71ac0bb5702053ee53b94f0065168141

**Comment by phit** [comment]
https://gist.github.com/SeaDonkey81/71ac0bb5702053ee53b94f0065168141#file-edited-sponge-config-L133-L157

fix the formatting

**Comment by SeaDonkey81** [comment]
Not sure what you mean by fix the formatting.

**Comment by dualspiral** [comment]
You've tried to add something to the config and it's broken it, which has caused Sponge to reset it. I would suggest deleting the lines that phit linked to (while the server is offline) and then trying again.

**Comment by SeaDonkey81** [comment]
It's not just the formating. The Config file reverts everything to default even if i just change one item anywhere in the config file without the additional info in [entity - activation - range]

**Comment by SeaDonkey81** [comment]
The Config file reverts everything to default even if i just change one item anywhere in the config file without the additional info in [entity - activation - range]
