### ISSUE TITLE
One world hears the footsteps of another

### ISSUE THREAD

**Issue by zhourui123** [SpongePowered/SpongeForge#2868]
**I am currently running**

- SpongeForge version: maybe spongeforge-1.12.2-2768-7.1.6-RC3627.jar
- Forge version: 2768
- Java version: java8
- Operating System:debian

- Plugins/Mods:  some plugin build by myself

**Issue Description**
This is a problem I had two months ago, and gabizou suggested I file issue
https://forums.spongepowered.org/t/how-to-get-the-dimension-id/20041/2

i design one minigame plugin,  world structure is as follows:
-world
  -DIM-1
  -DIM1
  -w-mini-1
  -w-mini-2
  -w-mini-3

w-mini-* is minigame world.

if  world `w-mini-1` is playing, then one player joined `w-mini-2`,  the player in `w-mini-1` will hear footstep and zombie sounds  from `w-mini-2`, and lagging.
I found the dimensions of these mini worlds conflicted.
After a few days, I solved this problem by deleting the node `FML` and `forge` under file `w-mini-*/level.dat`
I am not sure whether this problem is a sponge problem, I hope you can confirm

**Comment by Zidane** [comment]
@zhourui123 Was the minigame world created via copying a world or?

**Comment by zhourui123** [comment]
minigame world copy from the backup via java launcher(A program that starts all the servers and copies the mini-game world),  The minigame world will be copied before the server shell runs

**Comment by Zidane** [comment]
Give this a shot again with the latest SF. I believe it should be solved. Let me know if it isn't and I'll reopen.
