### ISSUE TITLE
Error of Vending block inventory operation

### ISSUE THREAD

**Issue by Kantets** [SpongePowered/SpongeForge#2869]
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.1.7-RC3847
- Forge version: 14.23.5.2838 
- Java version: openjdk 1.8.0_212
- Operating System: Debian 9

- Plugins/Mods: FastAsyncWorldEdit, AdamantineShield, BorderProtector, DupeFixer, GriefPrevention, KeepInventorySponge, LuckPerms, MMCReboot, Nucleus, Plan, PlayTimeCounter, ProjectCore, StackBan, UltimateChat, WorldEdit, spark
- Mods: SpongeAPI, Sponge, Astral Sorcery, B.A.S.E, Baubles, BiblioCraft, Block Drops Tweaker, Blockcraftery, Blood Arsenal, Blood Magic: Alchemical Wizardry, Bonsai Trees, Botania, Botania Needs These Things!, Botanic Additions, Botanic Bonsai, Chameleon, Chisel, Construct's Armory, ContentTweaker, CraftTweaker JEI Support, CraftTweaker2, Elevator Mod, EventHelper, ExtraBotany, FTB Library, FTB Quests, Familiar Fauna, Fast Leaf Decay, Foamflower, Grimoire of Gaia 3, Guide-API, Hammer Core, Item Filters, Just Enough Items, MTLib, ManaTweaks, Mantle, MetalChests, Mystical Lib, Niisaba's cases, Ore Veins, Oreberries, Roots Classic, Serene Seasons, SpongeForge, Storage Drawers, Storage Drawers Unlimited, TBone, Thaumcrafft Inventory Scanning, Thaumcraft, Thaumic Additions: Reconstructed, The Betweenlands, Tinker's JEI, Tinkers Tool Leveling, Tinkers' Construct, Totemic, Tough As Nails, Vending, Waystones, animalium, manavisualizer, windcheck

**Issue Description** 

When working with the inventory of any of the vending machines fashion Vending block console spam similar errors.
This is mainly when interacting with the words where there is the object, the error POPs up only 1 time after opening and first interaction.

https://gist.github.com/Kantets/25ff131c33180a75c78bd906a12172ca

**Comment by Faithcaio** [comment]
Might be same fix as for #2903 
try again with latest.

**Comment by Kantets** [comment]
All normal.
