### ISSUE TITLE
Disabling the Nether in server.properties disables all worlds except main

### ISSUE THREAD

**Issue by TBlueF** [SpongePowered/SpongeForge#287]
As i already posted in this [forum thread](https://forums.spongepowered.org/t/possible-sponge-issues/7522), if you disable the nether in the server.properties and teleport via plugin in it or any other custum world, you'll be stuck in an empty world.

_Sponge: 1.8-1371-2.1DEV-472 
Forge: 1.8-11.14.2.1427
Java: 1.8.0_40
OS: Win7/64_

**Comment by bloodmc** [comment]
We will be handling "allow-nether" as allowMultipleDimensions to be consistent with Forge. Keep the setting as true if you want to support multiworlds. I'll keep this ticket open until I push a config option that supports what you need.

**Comment by bloodmc** [comment]
@TBlueF I pushed a new branch 'world-update' which has the functionality you need via our world configs. It should be pushed to master within a week after it has been tested. Feel free to test it and let me know results.

**Comment by simon816** [comment]
@bloodmc Your world-update branch has gone stale both [in Sponge](https://github.com/SpongePowered/Sponge/commit/920be48ceeb67945fe2083af85f203fa375f2ee1) and [in SpongeAPI](https://github.com/SpongePowered/SpongeAPI/commit/2a47bb107010e8d7098fc17090e698c5d31ddb73), any chance of an update?

**Comment by bloodmc** [comment]
This was fixed in commit https://github.com/SpongePowered/SpongeCommon/commit/554f4410409aeb4a387d7d52d0e42d9d81c23d31

To disable nether, set 'world-enabled' to false in config/sponge/worlds/nether/DIM-1/world.conf

**Comment by TBlueF** [comment]
@bloodmc Didn't had the time to test this yet, but thank you very much. That's going to be really useful :)
