### ISSUE TITLE
Crash with JustEnoughIDs

### ISSUE THREAD

**Issue by BlazeRuler** [SpongePowered/SpongeForge#2870]
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2838-7.1.7-RC3805 (Every version above this one just crashes and refuses to run on the server)
- Forge version: Forge v14.23.5.2838
- Java version: Java 8 update 191
- Operating System: Windows 10

- Plugins/Mods:
Plugins: FastAsyncWorldEdit, LuckPerms, Nucleus, WorldEdit

Mods: A Fistful Of Hay, ATLCraft Candles Mod, Additional Banners, Advanced Chimneys, Angel of Vengeance, ArchitectureCraft, ArmorPlus, AstikorCarts, AutoRegLib, Bagelsmore: The Return, Bailey's Dailies, Bamboozled, Bauble Wings, Baubles, BiblioCraft, Biomes O' Plenty, Blood Magic: Alchemical Wizardry, Bonsai Trees, Bookworm API, Butterfly Mod, Chinese Workshop, Chinjufu Mod, Chisel, Cooking for Blockheads, Custom Trades Mod, Dark Roleplay Core, Dark Roleplay Core Module - Materials and Automatic Resource Generation, Dark Roleplay Core Module Blueprints, Dark Roleplay Core Module Guis, Dark Roleplay Core Module Locks, Dark Roleplay Library, Dark Roleplay Medieval, Electroblob's Wizardry, Extra Utilities 2, Ferdinand's Flowers, Forge Endertech, Guide-API, Iron Backpacks, Just Enough Items, JustEnoughIDs, LLibrary, LadyLib, Landlust, Lil Critters Mod, Lumen, MCMultiPart, Magical Psi, Mantle, McJtyLib, McLib, Metamorph, MrCrayfish's Furniture Mod, MrCrayfish's Vehicle Mod, Multi-Beds, Mystical Lib, Mystical World, Natura, Natural Fauna, Not Enough Wands, Obfuscate, Pam's HarvestCraft, Psi, Reliquary, Rustic, Rustic Thaumaturgy, ShetiPhian-Core, Sonar Core, SpongeForge, TOP Addons, TamModized, TeamLapen Library, Thaumcraft, The One Probe, TheDragonLib, Traverse, Tree Chopper, Vampirism, Varied Commodities, Wallpapers Craft, Wings, Zoo and Wild Animals Mod: Rebuilt

**Issue Description**
Whenever using JustenoughIDs and any spongeforge version after spongeforge-1.12.2-2838-7.1.7-RC3805, The server crashes whenever it tries to load up the world giving an error about the ChunkProviderServer. The logs will give more info on this issue.

Steps to reproduce:
1. Put the latest spongeforge(in this case RC3847) and the latest JustEnoughIDs mod into the minecraft server.
2. Make sure you are using the latest forge which is v14.23.5.2838.
3. Start the server and watch it crash after a little bit.

If you need more info about it, Let me know what is missing and I can do my best.
Full Server Log and crash log: https://gist.github.com/BlazeRuler/92252666aa0febeba505b4c33c4d1736

**Comment by LemADEC** [comment]
https://github.com/DimensionalDevelopment/JustEnoughIDs/issues/73
