### ISSUE TITLE
Crash with Phosphor with everything after 3843

### ISSUE THREAD

**Issue by TheRealDadbeard** [SpongePowered/SpongeForge#2871]
**I am currently running**

- SpongeForge version:  any version after 3843
- Forge version: 2838
- Java version: 8
- Operating System: W10

- Plugins/Mods:https://pastebin.com/PqCGjJU1

**Issue Description**
Server crash

https://gist.github.com/TheRealDadbeard/b76b1481b75f35c11b1e5db4b7e532c5

**Comment by KorewaLidesu** [comment]
Ambermod problem

**Comment by KorewaLidesu** [comment]
Hmmmmmmmm, problem cause from chunk system
mod incompatibility

**Comment by TheRealDadbeard** [comment]
Phosphor is the issue

**Comment by BlazeRuler** [comment]
Spongeforge has a similar crash when combining any version of spongeforge after version 3805 with the mod JustEnoughIDs.
#2870

**Comment by BlazeRuler** [comment]
Only difference with the JustEnoughIDs crash is that it's saying:
java.lang.NoClassDefFoundError: net/minecraft/world/gen/ChunkProviderServer
and this Phosphor crash says:
java.lang.NoClassDefFoundError: net/minecraft/world/chunk/Chunk

It looks to me that spongeforge is at fault here since its the only one that has updated most recently.

**Comment by XakepSDK** [comment]
Sponge rewrites it's internal parts. These mods should rewrite their patches. Not a sponge problem.

**Comment by gabizou** [comment]
Phosphor needs to update for the method rename from `setBlockState` to `bridge$setBlockState`. You can roll back to earlier SF builds where the interface wasn't named that way and wait for them to update. As of right now, there's not likely going to be any further changes to tose interfaces as they're all finalized with their prefixing.
