### ISSUE TITLE
Duplication issues with event cancels

### ISSUE THREAD

**Issue by runescapejon** [SpongePowered/SpongeForge#2874]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.1.7-RC3847 (test it also with 3616 dupe work fine)
- Forge version: 1.12.2-14.23.5.2838
- Java version: 8
- Operating System: windows

- Plugins/Mods:
- Baubles-1.12-1.5.2
- Botania+r1.10-361
- griefprevention-1.12.2-4.3.0.692
- LuckPerms-Sponge-4.4.26

**Issue Description**
To perform this duplication you would need from botania, Mana lens: weight, Hovering hourglass, Mana pool Pulse Mana Spreader, Mana Tablet (to quickly gain mana). Next have your setup this like this as it shown in the video (Kind of hard to explain in words on how to setup it). Once have it setup correctly then you make a claim over that setup then you be able to duplication. I did this on a clean test server.
video:  https://youtu.be/AN_6kBwnhBg

**Comment by KorewaLidesu** [comment]
Can you provide the console log when it happen?
also the debug log

**Comment by runescapejon** [comment]
Sure but i didn't see any error or anything useful.

[latest.log](https://github.com/SpongePowered/SpongeForge/files/3389417/latest.log)
[debug.log](https://github.com/SpongePowered/SpongeForge/files/3389418/debug.log)

**Comment by KorewaLidesu** [comment]
Have you make ticket on Grief Prevention?
Since maybe problem come from the plugin where it can't handle the mana spread particle shooting

**Comment by runescapejon** [comment]
i have and bloodshot the developer of GriefPrevention told me that it's Sponge bug

**Comment by clienthax** [comment]
Is this still happening on latest?

**Comment by runescapejon** [comment]
Just tested @clienthax and this issue is fixed on spongeforge-1.12.2-2838-7.2.1
