### ISSUE TITLE
NoClassDefFoundError SPacketPlayerListHeaderFooterAccessor

### ISSUE THREAD

**Issue by kristi71111** [SpongePowered/SpongeForge#2876]
**I am currently running**
- SpongeForge version: 7.1.7-RC3848
- Forge version: 14.23.5.2838
- Java version: 1.8.0_212
- Operating System: Centos 7

- Plugins/Mods:
**Mods (205):** Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AE2 Stuff, AI Improvements, Advancement Book, Animal Crops, Apotheosis, AppleCore, AppleSkin, Applied Energistics 2, Aroma1997Core, AromaBackup, AromaBackuprecovery, Astral Sorcery, B.A.S.E, BD Lib, BNBGamingLib, Barrels, Drums, Storage & More, Baubles, Bed Patch, BiblioCraft, BnBGamingCore, Bonsai Trees, Bookshelf, Building Gadgets, Caliper, Calm Down Zombie Guy, Ceramics, Chargers, ChineseWorkshop, Chisel, Chisels & Bits, Click Machine, Clumps, CoFH Core, CoFH World, CodeChicken Lib, ComPatchedStorage, CommonCapabilities, Compact Machines 3, CompactStorage, Construct's Armory, ContentTweaker, Cooking for Blockheads, Corail Tombstone, CraftTweaker JEI Support, CraftTweaker2, Cucumber Library, Culinary Construct, Cyclic, Cyclops Core, Dark Utilities, Deep Mob Learning, Dimension Stages, DragonMurder, Elevator Mod, Ender Crop, Ender Utilities, EnderCore, EnderStorage, Extended Crafting, Extra Cells 2, Farming for Blockheads, FastFurnace, FastWorkbench, Fence Overhaul, FindMe, Flux Networks, FoamFix, FoamFixCore, Forge Microblocks, Forge Multipart CBE, Forgiving Void, Game Stages, Guide-API, Headcrumbs, Horse Power, Hunting Dimension, HydroGel, InControl, Industrial Foregoing, Inspirations, Integrated Dynamics, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTunnels-Compat, Iron Jetpacks, Item Stages, JourneyMap, Just Enough Items, KleeSlabs, Limitless Structure Blocks, MCMultiPart, MTLib, MalisisCore, MalisisDoors, Mantle, MatterOverdrive: Legacy Edition, McJtyLib, Mekanism, Mekanism: Generators, Mercurius, Minecraft Multipart Plugin, Mob Stages, Mod Tweaker, ModPack Basic Tools, ModPack Utilities, More Buckets, More Cauldrons, Morpheus, Mystcraft, Mystical Agradditions, Mystical Agriculture, NuclearCraft, OG Dragon+, OpenComputers, OpenComputers (Core), OpenComputers Xnet Driver, OreExcavation, Parabox, Patchouli, Pickle Tweaks, PigUtils, Pipe Master 2000, Placebo, PlaneFix, PortalGun, Practical Logistics 2, Prestige, Primitive Crafting, ProjectE, RFToolsPower, RandomPatches, Ranged Pumps, Real Filing Cabinet, RecipeStages, Redstone Flux, Resource Hogs, Rustic, Sampling Performance Profiler, Shadowfacts' Forgelin, Simple Generators, Simple Inventory sorting, Simple Storage Network, Sky Grid, SkyBonsais, Slab Machines, SlimyBoyos, Smooth Font Core, Snad, SonarCore, SpongeForge, Squeezer Patch, Statues mod, Stuff A Sock In It, Super Sound Muffler, Surge, SwingThroughGrass, Sync, TallGates, TelePastries, Tesla Core Lib, Tesla Core Lib Registries, The Lost Cities, The Twilight Forest, The Weirding Gadget, Thermal Dynamics, Thermal Foundation, Thermal Innovation, TickProfiler, Tinkers Tool Leveling, Tinkers' Complement, Tinkers' Construct, Tiny Progressions, TogetherForever, Topography, TorchMaster, Translocators, Tree Growing Simulator 2016, Triumph, Twitchcrumbs, Universal Modifiers, Valkyrie Lib, ViesCraft, Waddles, Waila, Waila Stages, Wall-Jump!, What Are We Looking At, Wither Crumbs, WorldEdit, XC Patch, XL Food Mod, XNet, YNot, Yoyos, ZenStages, bouncy_creepers, mob_grinding_utils, sky_orchards, uppers
**Plugins (35):** Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, ActiveTime, AsciiEmotes, BacoMaster, BetterChunkLoader, CatClearLag, CommandUtils, EasyTexts, EconomyLite, Enjin Minecraft Plugin, GriefPrevention, Holograms, HuskyUI, Lottery, LuckPerms, MBDiscordLink-API7, MMCRestrict, MagiBridge, Market, NuVotifier, Nucleus, PlaceholderAPI, SeriousVote, SkyClaims, TabManager, TeslaCore, TeslaCrate, TeslaLibs, Unity, VoteParty, WelcomeRewards, spark

**Issue Description**
Upon updating to 7.1.7-RC3848 the TabManager plugin throws an error and does not load correctly. This issues is not present on 7.1.7-RC3843. [Link to error](https://gist.github.com/kristi71111/b05e7f11ce8f9d5d2801a82f652ed888). Opening an issue here first since it references that a class definition is missing from sponge's side.

**Comment by SawFowl** [comment]
I confirm this problem.
This code only works on SpongeVanilla.
```Java
player.getTabList().setHeaderAndFooter(
	Text.of("Header Text"), 
	Text.of("Footer Text"));
```

**Comment by Zidane** [comment]
Should be fixed in latest SF.
