### ISSUE TITLE
 player  invincible due to portal event cancelled

### ISSUE THREAD

**Issue by zhourui123** [SpongePowered/SpongeForge#2877]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.1.7-RC3843.jar
- Forge version: 2738
- Java version: 
- Operating System:

- Plugins/Mods:
twilight forest
OBP

**Issue Description**

Player teleport to overworld from nether portal, if event cancelled, player will invincible.
event is: `MoveEntityEvent.Teleport.Portal`

if cancelled event that twilightforest portal -> over world, player will fall from height place at TF(like the coordinates of the overworld portal ), not invincible.

**Comment by Zidane** [comment]
Fixed in latest SF build. Nice catch on that one.
