### ISSUE TITLE
When I put down a minecart, the following problem occurred, and the minecart will not be accelerated by the gold track

### ISSUE THREAD

**Issue by DJmanito** [SpongePowered/SpongeForge#2879]
/********************************************************************************************************************/
/*                                      Exception occurred during a PhaseState                                      */
/********************************************************************************************************************/
/* Sponge's tracking system makes a best effort to not throw exceptions randomly                                    */
/* but sometimes it is inevitable. In most cases, something else triggered this                                     */
/* exception and Sponge prevented a crash by catching it. The following stacktrace                                  */
/* can be used to help pinpoint the cause.                                                                          */
/********************************************************************************************************************/
/* The PhaseState having an exception: Tick{Entity}                                                                 */
/* The PhaseContext:                                                                                                */
/*     - Owner: EntityPlayerMP['DJ_manito'/29392, l='world', x=160.35, y=69.00, z=-382.53]                          */
/*     - Source: EntityMinecartEmpty['entity.MinecartRideable.name'/83040, l='world', x=159.49, y=69.06, z=-382.50] */
/* org.spongepowered.asm.util.PrettyPrinter@467c36a6                                                                */
/*                                                                                                                  */
/*  StackTrace :                                                                                                    */
/* java.lang.ClassCastException: null                                                                               */
/*                                                                                                                  */
/* Minecraft : 1.12.2                                                                                               */
/* SpongeAPI : 7.1.0-a56d82c4c                                                                                      */
/* Sponge : 1.12.2-7.1.7-SNAPSHOT                                                                                   */
/* SpongeForge : 1.12.2-2838-7.1.7-RC3822                                                                           */
/* Minecraft Forge : 14.23.5.2838                                                                                   */
/********************************************************************************************************************/

**Comment by phit** [comment]
update, this was solved in https://github.com/SpongePowered/SpongeForge/issues/2844
