### ISSUE TITLE
Crash because of deathcount scoreboard

### ISSUE THREAD

**Issue by jinkhya** [SpongePowered/SpongeForge#2883]
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.1.7-RC3848
- Forge version: forge-14.23.5.2838
- Java version: 1.8.0_212"
- Operating System: CentOS Linux 7

- Plugins/Mods: SpongeAPI, Sponge, CatClearLag, Enjin Minecraft Plugin, LuckPerms, MMCRestrict, NuVotifier, Nucleus, Prism, Sledgehammer
 Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, /dank/null, A Lib, AE2 Wireless Terminals (AE2WTLib), Actually Additions, Actually Baubles, Akashic Tome, Alchemistry, Animania, AppleCore, AppleSkin, Applied Energistics 2, ArchitectureCraft, Aroma1997Core, Artisan Worktables, Astral Sorcery, Athenaeum, AutoPickup, AutoRegLib, Avaritia, B.A.S.E, BD Lib, Baubles, Better Questing, Better Questing Quest Book, BiblioCraft, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Blockcraftery, Blood Arsenal, Blood Magic: Alchemical Wizardry, Bonsai Trees, Bookshelf, Botania, Botanic Additions, Brandon's Core, Ceramics, Chameleon, Chest Transporter, ChickenChunks, Chisel, Chisels & Bits, Chunk Pregenerator, CoFH Core, CoFH World, CodeChicken Lib, CommonCapabilities, Compact Drawers, ContentTweaker, CookieCore, Corail Tombstone, CosmeticArmorReworked, CraftStudio API, CraftTweaker JEI Support, CraftTweaker2, CreativeCore, CreativeCoreDummy, Cucumber Library, Custom Starting Gear, Cyclic, Cyclops Core, DDSS Utils, Dark Utilities, DiscordIntegration, Doomlike Dungeons, Draconic Evolution, DungeonTactics, EnderStorage, Environmental Tech, EvilCraft, EvilCraft-Compat, Exchangers, Extended Crafting, Extra Alchemy, Extra Cells 2, Extra Planets, Extra Utilities 2, Extreme Reactors, FTB Library, FTB Utilities, Farseek, Fast Leaf Decay, FastWorkbench, Fishing Net Mod, FluidTank, FluidTank_AE2, FluidTank_TheOneProbe, FoamFix, FoamFixCore, Forestry, Forge Microblocks, Forge Multipart CBE, Galacticraft Core, Galacticraft Planets, GenDustry, Gendustry JEI Addon, Guide-API, Guidebook, Hammer Core, HelpFixer, Hooked, Hunger Overhaul, Hunting Dimension, Ice and Fire, Immersive Engineering, Industrial Foregoing, Infernal Mobs, Integrated Dynamics, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTunnels-Compat, Integration Foregoing, Iron Chest, IvToolkit, Just Another Rotten Flesh to Leather Mod, Just Enough Energistics, Just Enough Items, LLibrary, Lapis Stays in the Enchanting Table, LibEx, LibrarianLib, LibrarianLib Stage 2, LittleTiles, LittleTilesCore, Loot Bags, LootTweaker, MJRLegendsLib, MTLib, MagicBees, MalisisCore, MalisisDoors, Mantle, McJtyLib, Mekanism, Mekanism: Generators, Mekanism: Tools, MekanismOres, Micdoodle8 Core, Minecraft Multipart Plugin, Mob Properties Randomness, Mod Tweaker, More Libs, More Plates, Morpheus, Mowzie's Mobs, MrCrayfish's Furniture Mod, MrTJPCore, Multi Mob Core, Mystical Agradditions, Mystical Agriculture, Mystical Lib, Natura, NetherEx, NotEnoughIDs, NuclearCraft, OMLib, OnlinePictureFrame, Open Modular Passive Defense, Open Modular Turrets, OpenBlocks, OpenComputers, OpenComputers (Core), OpenModsLib, OpenModsLib Core, Overloaded, Pam's Cookables, Pam's HarvestCraft, Pickle Tweaks, Placebo, PlusTiC, PneumaticCraft: Repressurized, Primitive Mobs, Progressive Bosses, ProjectRed Core, ProjectRed Expansion, ProjectRed Exploration, ProjectRed Fabrication, ProjectRed Illumination, ProjectRed Relocation, ProjectRed Transmission, ProjectRed Transportation, ProjectRed integration, Quark, RFTools, RFTools Control, RFTools Dimensions, RFToolsPower, RandomPatches, Reborn Core, RebornStorage, Redstone Flux, Refined Avaritia, Refined Storage, Refined Storage Addons, Rex's Additional Structures, Rockhounding Mod: Chemistry, Rockhounding Mod: Core, Roguelike Dungeons, Rough Mobs 2, Ruins Mod, Rustic, SG Craft, Shadowfacts' Forgelin, Simply Jetpacks 2, Solar Flux Reborn, Special AI, Spice of Life: Carrot Edition, SpongeForge, Standard Expansion, Steve's Carts 2, Storage Cabinet, Storage Drawers, Storage Drawers Extras, Storage Tech, Streams, TOP Addons, Tech Reborn, Tech Reborn Mod Compatibility, Tesla Core Lib, Tesla Core Lib Registries, The One Probe, The Spice of Life, The Twilight Forest, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, TickProfiler, Tinkers Alloying Addon, Tinkers Tool Leveling, Tinkers' Construct, TorchMaster, Traverse, Tweakers Construct, U Team Core, Underground Biomes, UniDict, Universal Modifiers, Useful Railroads, V0id's Smart Backpacks, Valkyrie Lib, ViesCraft, Vulcanite, WanionLib, Wireless Crafting Terminal 2, WorldEdit, Worley's Caves, XNet, Zero CORE, Zoesteria Biomes, careerbees, galacticrafttweaker, p455w0rd's Library, projectred-compat

**Issue Description**
We have a deathcount in place on our server. After updating to 1.12.2-2838-7.1.7-RC3848, the server can't fully load, it crashes. Going back to 1.12.2-2838-7.1.7-RC3843 fixed the crash.
Those commands were ran when the server was first setup :
/scoreboard objectives add Deaths deathCount
/scoreboard objectives setdisplay list Deaths

https://gist.github.com/jinkhya/3afe414fcf3d1987b87c2643be3fa163

**Comment by Zidane** [comment]
Closed in latest SF.
