### ISSUE TITLE
Crash with Thaumcraft

### ISSUE THREAD

**Issue by SSKirillSS** [SpongePowered/SpongeForge#2884]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2825-7.1.6
I do not use the latest version, since from the moment of the upgrade to it, there were instantaneous sudden memory leaks to such an extent that the server just stop response. I do not know if this is directly related to the spongeforge, but such problems began after the update. I rolled back the version to the recommended one.
- Forge version: forge-1.12.2-14.23.5.2838-universal

- Plugins/Mods:
![image](https://user-images.githubusercontent.com/38190325/61403787-bab2d900-a8de-11e9-8ebc-c436b7e31a18.png)

**Issue Description**
Under unknown conditions, the server simply turns off. This happened more than once, but I was not able to understand the reason.
- Thaumcraft-1.12.2-6.1.BETA26

Crash-report: https://gist.github.com/SSKirillSS/528e245d08b2dde9828657f4684ffb4b

**Comment by Zidane** [comment]
There have been massive changes since that build. We need a log from the dead latest to even attempt to debug this one (if it is even still an issue). I'll reopen once this is confirmed to happen on latest.
