### ISSUE TITLE
Unable to send server icon to client.

### ISSUE THREAD

**Issue by DJmanito** [SpongePowered/SpongeForge#2887]
Newer versions of spongeforge, for example
Spongeforge - 1.12.2-2838-7.1.7 - RC3848
Spongeforge - 1.12.2-2838-7.1.7 - RC3847
Unable to send server icon to client.
Both the ServerList portion of the nucleus plug-in and the ServerListPlus plug-in are used.
Spongeforge -1.12.2-2825-7.1.6, however, is acceptable.

**Comment by mappleaf** [comment]
Same problem

**Comment by Zidane** [comment]
Can someone explain this a bit more please? I don't understand the issue.

**Comment by DJmanito** [comment]
In theclient'sselect server interface,the core of this version does not send the icon next to the title to the client
在客户端在选择服务器界面，该版本的核心不会向客户端发送标题旁边的图标

**Comment by bigenergy** [comment]
server-icon.png 
server icon does not appear next to name in multiplayer list

![Screenshot_15](https://user-images.githubusercontent.com/17977139/62428380-043a5b00-b70a-11e9-84f7-02218b85f609.png)

**Comment by Zidane** [comment]
Fixed in the latest SF. Thanks for the report.
