### ISSUE TITLE
SpongeForge affecting mob drops issue

### ISSUE THREAD

**Issue by RivaHakushia** [SpongePowered/SpongeForge#2890]
**I am currently running**

- SpongeForge version: 1.12.2-2825-7.1.7-RC3773
- Forge version: 1.12.2-14.23.5.2836
- Java version: 
- Operating System:

- Plugins/Mods: Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AgriCraft, Ancient Warfare Automation, Ancient Warfare Core, Ancient Warfare NPCs, Ancient Warfare Structures, Ancient Warfare Vehicles, AppleCore, AppleSkin, BD Lib, Baubles, Better Animals+, Better Builder's Wands, BiblioCraft, Bonsai Trees, Bookshelf, Bookworm API, Botania, Chameleon, Chest Transporter ,Chisel ,Chisels & Bits ,CodeChicken Lib ,Dark Utilities ,Decocraft ,Electroblob's Wizardry ,EnderStorage ,Exotic Birds ,Extra Utilities 2, FTB Library, FTB Utilities, FTB Utilities: Backups ,Fast Leaf Decay ,Flat Colored Blocks ,FoamFix ,FoamFixCore ,Guide-API ,Harvest ,Hats, Ice and Fire, Industrial Foregoing ,InfinityLib ,Integration Foregoing ,Inventory Tweaks ,Iron Backpacks ,Iron Chest ,JourneyMap ,Just Enough Items ,LLibrary ,LibEx ,MalisisCore ,MalisisDoors ,Mantle ,Mekanism ,Mekanism: Generators ,Mekanism: Tools ,MineColonies, Morpheus ,MrCrayfish's Furniture Mod, NaturalFauna, NetherEx, NoMoreRecipeConflict, OpenBlocks, OpenModsLib, OpenModsLib Core, OreLib Support Mod, Pam's HarvestCraft, Reborn Core, RebornStorage, Refined Storage, Roguelike Dungeons, Shadowfacts' Forgelin, SpongeForge, Storage Drawers, Structurize, Tesla Core Lib, Tesla Core Lib Registries, The Spice of Life, Tinkers Tool Leveling, Tinkers' Construct, TorchMaster, Waila, Wings, Horns, and Hooves, the Ultimate Unicorn Mod!, Wolf Armor and Storage, WorldEdit, Zoo and Wild Animals Mod: Rebuilt, iChunUtil

**Issue Description**
Since Sponge Forge version 1.12.2-2768-7.1.5 there has been a noticeable issue with Mobs upon being killed by a player that items are not dropped as they usually are, this is on a Server running on a Linux box, before this it was working just fine for mob drops, I have tested this out in Single player and found mob drops are normal, plus I have test the server by Disabling Sponge Forge and noticed mob drops have returned to normal, I have tried updating from 7.1.5 to the latest recommend 7.1.6 and then to the current version above, with no luck of any resolving the issue, I have also found very little information in regards to this issue to use to resolve it myself so any further help would be highly appreciated, since I have no clue how to look into mixins or loottables.

**Comment by phit** [comment]
try narrowing down your modlist, as this doesn't happen with just SpongeForge, see which mods cause it

**Comment by RivaHakushia** [comment]
hopefully this weekend will be setting up a test server to pin point which mod it could be, I can rule out the Mods: BetterAnimalsPlus, NaturalFauna and ZAWA Rebuilt, as I had disabled these and still had the issue, if however anyone has any of these mods and ran into the same issue please feel free to let me know so I can work on a fix or finding a fix.
Any information in regards to this is much appreciated since it's the first time I've ever seen this sort of issue myself.

**Comment by RivaHakushia** [comment]
After a lot of further testing, the issue had been Located to Cat Clear Lag plugin for Sponge Forge, Which makes sense as to why without SF everything ran fine, The issue was with the config file it's self. 

**"Hostile Limit"=500** - If this is set lower than 500, it seems  to effect boss drops and Dragon drops from Ice & Fire, I believe this also effect boss drops in other mods that bring in Bosses, Including Minecraft's Vanilla Bosses. So I hope if anyone else runs into this issue and happens to have CatClearLag that this will help narrow it down.
