### ISSUE TITLE
Sponge forge crash on server startup

### ISSUE THREAD

**Issue by Nhaaj** [SpongePowered/SpongeForge#2891]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.1.7-RC3848.jar
- Forge version: 2838
- Java version: 8
- Operating System: Windows 10 (server is hosted through mcprohosting)

- Plugins/Mods:
aether_ii-1.12.2-0.2.2+build79
BiblioCraft[v2.4.5][MC1.12.2]
biomesoplenty-1-12-2-7-0-1-2425
Bookshelf-1.12.2-2.3.585
Chisel-MC1.12.2-0.2.1.35
DarkUtils-1.12.2-1.8.226
DragonMounts2-1.12.2-1.6.2
FastLeafDecay-v14
Hexxit+Gear-1.12.2-2.8.0
jei_1.12.2-4.9.2.196
journeymap-1.12.2-5.5.5b7
llibrary-1.7.19-1.12.2
Mantle-1.12-1.3.3.55
OpenBlocks-1.12.2-1.8.1
OpenModsLib-1.12.2-0.12.2
optifine-1-12-2-hd-u-e3-jar
pixelExtras-1-12-2-2-4-6
Pixelmon-1.12.2-7.0.6
Placebo-1.12.2
Resource-Loader-Mod-1.12.2
spongeforge-1.12.2-2838-7.1.7-RC3848
Tinkers-Construct-Mod-1.12.2
TinkerToolLeveling-1.12.2-1.1.0
tombstone-3.5.5-1.12
Wawla-1.12.2-2.5.257

**Issue Description**

Server crashes on startup when sponge forge is installed, if removed, it loads fine. Log: https://gist.github.com/Nhaaj/2404222d1e39d3efcecbac8fdd2810ff

**Comment by gabizou** [comment]
ISsue with Phosphor, downgrade SpongeForge to the compatible version that Phosphor built against, or uninstall Phosphor until they update for our changes.
