### ISSUE TITLE
Hitting players causes error in console (and doesn't hit)

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#2893]
**I am currently running**
- SpongeForge version: 1.12.2-2825.717-RC3774
- Forge version: 1.12.2-14.23.5.2837
- Java version: 8 
- Operating System: 64-bit

- Plugins/Mods:
First time: Astral Sorcery, Baubles, Botania, llibrary, llibrary core, thaumcraft, wings, backpacks, luckperms, nucleus, tickprofiler, virtual tool, and world edit.

I first assumed this issue was due to Astral Sorcery, as they said it was not tested with SpongeForge and might have some issues, but then I changed the server's mods and this still continued.

Second time: backpacks, galacticcraftcore, galacticcraftplants, luckperms, micdoodlecore, nucleus, tickprofiler, virtualtool, worldedit.

I have used all the plugins (LuckPerms, WorldEdit, VirtualTool, TickProfiler, Nucleus) and the Backpacks mod before with no issues. Before changing worlds I have deleted the previous world and the information from Virtual Tool's config. I am not sure what is causing the problem - something current, or something older.

**Issue Description**
When a player hits another player, a red error logs into the console, spamming it, and the players can't actually damage each other (as if friendly fire was off).

[Latest.log](https://gist.github.com/yaeliel1/aed0ed844ddc46607642968730c6eb70)

I was wondering if anyone could help me figure out what is causing this issue and how to fix it? The only thing I can understand from the logs is links to the world and sponge.

Thanks in advance,
yaeliel.

**Comment by Faithcaio** [comment]
```
Caused by: java.lang.ClassCastException: net.minecraft.world.WorldServer cannot be cast to org.spongepowered.api.world.storage.WorldProperties
at net.minecraft.entity.player.EntityPlayerMP.handler$onCanAttackPlayer$zhb000(EntityPlayerMP.java:5000) ~[oq.class:?]
```

**Comment by ghost** [comment]
> ```
> Caused by: java.lang.ClassCastException: net.minecraft.world.WorldServer cannot be cast to org.spongepowered.api.world.storage.WorldProperties
> at net.minecraft.entity.player.EntityPlayerMP.handler$onCanAttackPlayer$zhb000(EntityPlayerMP.java:5000) ~[oq.class:?]
> ```

I can see this is the problem, but I don't understand what to do to fix it. Could you help me in any way?

**Comment by ghost** [comment]
Sorry i figured out I was on a very old version of sponge - thank you anyway!
