### ISSUE TITLE
Some IC2 TileEntity information lost after server restart

### ISSUE THREAD

**Issue by soncemvo** [SpongePowered/SpongeForge#2895]
**I am currently running**
- SpongeForge version: 1.12.2-2825-7.1.6
- Forge version: forge-1.12.2-14.23.5.2838-universal
- Java version: latest
- Operating System: win10

- Plugins/Mods: griefprevention-1.12.2-4.3.0.684, industrialcraft-2-2.8.169-ex112

So i have IndustrialCraft 2 installed, when i place a block from ic2 and then try to get BlockState, i got:

`ic2:te[facing=down,material=ic2_material_machine,transparent=false,type=nuclear_reactor]`

Then iam restart server and try to get same block BlockState and i got:

`ic2:te[facing=down,material=ic2_material_machine,transparent=false,type=invalid]`

so “type” lost after restart. Without this i cant get what actualy this block is.

**Comment by zsn741656478** [comment]
The same problem with using WE. After using the //paste function type=nuclear_reactor will also become type=invalid

**Comment by gabizou** [comment]
How are you getting the `BlockState`? I've yet to see ic2 and ic2 classic fail in dev and production. Is there a small map that can be provided as an example? Is there a reliable reproducible list of steps we can use?

**Comment by soncemvo** [comment]
*****
`    public void onBlockPlace(ChangeBlockEvent.Place event) {

        Optional<Player> optPlayer = event.getCause().first(Player.class);
        if (optPlayer.isPresent()) {

            Map<String, Integer> blocks = new HashMap<String, Integer>();

            Player player = optPlayer.get();

            int chunkX = player.getLocation().getBlockPosition().getX() >> 4;
            int chunkZ = player.getLocation().getBlockPosition().getZ() >> 4;

            Optional<Chunk> chunk = slimiter.getInstance().game.getServer().getWorld(event.getTransactions().get(0).getFinal().getWorldUniqueId()).get().getChunk(event.getTransactions().get(0).getFinal().getLocation().get().getChunkPosition().getX(), 0, event.getTransactions().get(0).getFinal().getLocation().get().getChunkPosition().getZ());

            Vector3i min = chunk.get().getBlockMin();
            Vector3i max = chunk.get().getBlockMax();
            for (int x = min.getX(); x < max.getX()+1; x++) {
                for (int y = min.getY(); y < max.getY(); y++) {
                    for (int z = min.getZ(); z < max.getZ()+1; z++) {
                        BlockState block = chunk.get().getBlock(x, y, z);
*******`

**Comment by soncemvo** [comment]
I just need to get block meta. Cause of all ic2 blocks is meta blocks so thet have one name ic2:te, all i need to get ic2:te:80

**Comment by Dockter** [comment]
This is likely fixed by this commit:  

https://github.com/SpongePowered/SpongeCommon/commit/2aaf87115c9a00e73d97adba52c56acb5af540ed

**Comment by gabizou** [comment]
Should've already been fixed, need to retest with latest versions of SpongeForge, if it still happens on newer versions, report back and we'll re-open.
