### ISSUE TITLE
AstralSorcery Discidia doesn't give exp

### ISSUE THREAD

**Issue by SSKirillSS** [SpongePowered/SpongeForge#2897]
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2838-7.1.7-RC3854.
- Forge version: forge-1.12.2-14.23.5.2838-universal

**Mods**
![image](https://user-images.githubusercontent.com/38190325/61734782-47501200-ad8b-11e9-98d0-b6a29a24507e.png)

**Issue Description**
astralsorcery-1.12.2-1.10.19

Simply doesn't give Discidia experience ater killing mobs.

How to reproduce:
- Use creative Scroll of Written Expertise to unlock all AS knowledges
- Use Irradiant Star bounded to Discidia
- Kill some hostile mobs
- Open Astral Tome, go to Perks, check the exp bar on top left pos.

In singleplayer experience gives correctly, but in the server killing mobs does nothing.

Screenshot from singleplayer:
![image](https://user-images.githubusercontent.com/38190325/61735242-3a7fee00-ad8c-11e9-9c39-6dda77f84c0c.png)

_p.S. sry for my English C:_

**Comment by phit** [comment]
see also https://github.com/HellFirePvP/AstralSorcery/issues/1040

**Comment by SSKirillSS** [comment]
Launched a local test server with parameters:
` java -jar -Xmx3G -Xms3G -XX:+UseG1GC -XX:MaxGCPauseMillis=50 -Dsponge.shouldFireAll=true forge-1.12.2-14.23.5.2838-universal.jar --nogui`
But I did not found anything interesting or specific in the game and the console. Experience still does not come.

**Comment by SSKirillSS** [comment]
Any information on this error? Perhaps I somehow incorrectly use `-Dsponge.shouldFireAll=true` flag ...

**Comment by JBYoshi** [comment]
Can reproduce. The root issue is that Sponge isn't calling `ForgeHooks.onLivingDamage()`.
