### ISSUE TITLE
Health limit (or something similiar)

### ISSUE THREAD

**Issue by SSKirillSS** [SpongePowered/SpongeForge#2898]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.1.7-RC3854.
- Forge version: forge-1.12.2-14.23.5.2838-universal

- Plugins/Mods:
![image](https://user-images.githubusercontent.com/38190325/61739878-03aed580-ad96-11e9-80e0-14d45830f121.png)

**Issue Description**

With increasing health through various modifiers, its indicators reach a certain limit, after which the amount of health ceases to increase. As an example, perks AstralSorcery, Shadow Armor ExtraBotany(Botania addon), Botaia Relic rings, and other modifier increase players HP, but on server with SF that's don't affect player health correctly. Demo:
![image](https://user-images.githubusercontent.com/38190325/61740208-b54e0680-ad96-11e9-889e-a89b725378f7.png)
![image](https://user-images.githubusercontent.com/38190325/61740218-bbdc7e00-ad96-11e9-9718-0b2eaf691685.png)
In a singleplayer, everything works fine.

Similar problems have affected a lot of things, starting with damage modifiers and ending with the digging area.

**Comment by SSKirillSS** [comment]
The problem is getting bigger ...

![image](https://user-images.githubusercontent.com/38190325/61828954-8d32d600-ae70-11e9-99e5-2330fd0fd26a.png)

**Comment by alesha229** [comment]
Additional hearts can be viriginity only half,ie if Seth maid wore,then you can be seregenti 40 HP together with the normal HP.Secondly, if for example put a ring of Odin,which gives one line of HP,you'd have a 50 HP max.But if you remove it then those HP you saragani will remain,but they disappear immediately as an indicator of HP update,for example the damage of the sword is earlier than HP reset.Hence, it is not a visual bug,but the HP really is only by some additional HP give only half as much.
Used Google translate.

**Comment by KorewaLidesu** [comment]
you can use (tinkers' constuct mod) as a solution to fix the scaled heart
