### ISSUE TITLE
Crash on boot

### ISSUE THREAD

**Issue by Shmeeb** [SpongePowered/SpongeForge#2899]
Crash on boot: https://pastebin.com/fuA2hJ3y

**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2838-7.1.7-RC3856.jar
- Forge version: 14.23.5.2838
- Java version: 8

**Comment by Shmeeb** [comment]
I downgraded to SF 3845 and it was able to boot

**Comment by ImMorpheus** [comment]
Duplicate of https://github.com/SpongePowered/SpongeCommon/issues/2324

Fixed by https://github.com/SpongePowered/SpongeCommon/pull/2327
