### ISSUE TITLE
SpongeForge is not loaded at all

### ISSUE THREAD

**Issue by ShipHeatRook** [SpongePowered/SpongeForge#2902]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2825-7.1.6
- Forge version: forge-1.12.2-14.23.5.2825
- Java version: 8
- Operating System: Windows

- Plugins/Mods:
BiomesOPlenty
Davinci's Vessels Mod
Inventory Tweaks Mod
Just Enough Items
Moving World Mod
Ruins Mod
TamModized
Traveller's Boots
Twilight Forest Mod
Useful Backpacks Mod
U-Team-Core (dependency of Useful Backpacks)
Voidcraft Mod
Xaeros Minimap Mod
Zeiyocraft Mod

**Issue Description**

When I'm trying to start the server, Forge simply does not recognise SpongeForge as a proper mod at all. The issue is named "SpongeCoreMod is not signed" and I have no idea of what that means. This also implies I'm unable to run any plugins on my server, whereas all other mods load and work just fine.

https://gist.github.com/ShipHeatRook/9e876f6a9a3d52e8b86b7f0c2c114eac

**Comment by gabizou** [comment]
You have something loading older mixins:
```
[17:16:22] [main/WARN] [mixin]: Mixin config mixins.common.api.json requires mixin subsystem version 0.7.10 but 0.7.4 was found. The mixin config will not be applied.
```
Rename spongeforge to `__aaaaaaspongeforge.jar` or something to allow it to be found earlier than another mod that is loading and older version of Mixins.
