### ISSUE TITLE
SpongeForge block break chunk boundary related issue

### ISSUE THREAD

**Issue by secondfry** [SpongePowered/SpongeForge#2905]
**I am currently running**

- SpongeForge version: 3859
- Forge version: 2838
- Java version: 1.8.0_181
- Operating System: Ubuntu 18.04.2 LTS

- Plugins (4): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge
- Mods (7): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, SpongeForge

**Issue Description**
Players can't break blocks after moving between chunks. So one can login and break blocks normally until he crosses chunk boundary. After crossing the block will "refuse" to be broken.
Video attached: https://clips.twitch.tv/GoodGenerousLlamaDerp

https://gist.github.com/secondfry/eedd13642a512d4eb0d28f6a6f6b597e

[UPD] Thread updated to indicate that issue is still there with zero mods installed.

**Comment by Zidane** [comment]
Wayyy to many mods for us to go through and find out. This has no problems with just SpongeForge. Please narrow down your mods list to find out where the incompatibility stems from. Really anything that can help us narrow it down.

**Comment by secondfry** [comment]
Well, I just found out, it is there without any mods.
- Plugins (4): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge
- Mods (7): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, SpongeForge

Video: https://clips.twitch.tv/SneakyBlazingCougarDoritosChip

**Comment by secondfry** [comment]
Affected versions:
- 3859
- 3856

Not affected versions:
- 3854
- 3848

So I guess regression happened on 3856...
