### ISSUE TITLE
Entities Stuck/Cannot be killed

### ISSUE THREAD

**Issue by kristi71111** [SpongePowered/SpongeForge#2906]
**I am currently running**
- SpongeForge version: 1.12.2-2838-7.1.7-RC3859 
- Forge version: 14.23.5.2838
- Java version: 1.8.0_211
- Operating System: Windows 10

- Plugins/Mods:
**Mods (205):** Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AE2 Stuff, Advancement Book, Animal Crops, Apotheosis, AppleCore, AppleSkin, Applied Energistics 2, Aroma1997Core, AromaBackup, AromaBackuprecovery, Astral Sorcery, B.A.S.E, BD Lib, BNBGamingLib, Barrels, Drums, Storage & More, Baubles, Bed Patch, BiblioCraft, BnBGamingCore, Bonsai Trees, Bookshelf, Building Gadgets, Caliper, Calm Down Zombie Guy, Carry On, Ceramics, Chargers, ChineseWorkshop, Chisel, Chisels & Bits, Click Machine, Clumps, CoFH Core, CoFH World, CodeChicken Lib, ComPatchedStorage, CommonCapabilities, Compact Machines 3, CompactStorage, Construct's Armory, ContentTweaker, Cooking for Blockheads, Corail Tombstone, CraftTweaker JEI Support, CraftTweaker2, Cucumber Library, Culinary Construct, Cyclic, Cyclops Core, Dark Utilities, Deep Mob Learning, Dimension Stages, DragonMurder, Elevator Mod, Ender Crop, Ender Utilities, EnderCore, EnderStorage, Extended Crafting, Extra Cells 2, Farming for Blockheads, FastFurnace, FastWorkbench, Fence Overhaul, FindMe, Flux Networks, FoamFix, FoamFixCore, Forge Microblocks, Forge Multipart CBE, Forgiving Void, Game Stages, Guide-API, Headcrumbs, Horse Power, Hunting Dimension, HydroGel, InControl, Industrial Foregoing, Inspirations, Integrated Dynamics, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTunnels-Compat, Iron Jetpacks, Item Stages, JourneyMap, Just Enough Items, KleeSlabs, Limitless Structure Blocks, MCMultiPart, MTLib, MalisisCore, MalisisDoors, Mantle, MatterOverdrive: Legacy Edition, McJtyLib, Mekanism, Mekanism: Generators, Mercurius, Minecraft Multipart Plugin, Mob Stages, Mod Tweaker, ModPack Basic Tools, ModPack Utilities, More Buckets, More Cauldrons, Morpheus, Mystcraft, Mystical Agradditions, Mystical Agriculture, NuclearCraft, OG Dragon+, OpenComputers, OpenComputers (Core), OpenComputers Xnet Driver, OreExcavation, Parabox, Patchouli, Pickle Tweaks, PigUtils, Pipe Master 2000, Placebo, PlaneFix, PortalGun, Practical Logistics 2, Prestige, Primitive Crafting, ProjectE, RFToolsPower, Ranged Pumps, Real Filing Cabinet, RecipeStages, Redstone Flux, Resource Hogs, Rustic, Shadowfacts' Forgelin, Simple Generators, Simple Inventory sorting, Simple Storage Network, Sky Grid, SkyBonsais, Slab Machines, SlimyBoyos, Smooth Font Core, Snad, SonarCore, SpongeForge, Squeezer Patch, Statues mod, Stuff A Sock In It, Super Sound Muffler, Surge, SwingThroughGrass, Sync, TallGates, TelePastries, Tesla Core Lib, Tesla Core Lib Registries, The Lost Cities, The Twilight Forest, The Weirding Gadget, Thermal Dynamics, Thermal Foundation, Thermal Innovation, Tinkers Tool Leveling, Tinkers' Complement, Tinkers' Construct, Tiny Progressions, TogetherForever, Topography, TorchMaster, Translocators, Tree Growing Simulator 2016, Triumph, Twitchcrumbs, Universal Modifiers, Unloader, Valkyrie Lib, ViesCraft, Waddles, Waila, Waila Stages, Wall-Jump!, What Are We Looking At, Wither Crumbs, XC Patch, XL Food Mod, XNet, YNot, Yoyos, ZenStages, bouncy_creepers, mob_grinding_utils, sky_orchards, uppers
**Plugins (35):** Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, BaconTowny, BungeeTabListPlus-SpongeBridge, EconomyLite, EntityParticles, GriefPrevention, LuckPerms, NuVotifier, Nucleus, Player Glow, PrestigeFixer, SeriousVote, SkyClaims

**Issue Description**
Upon updating to 7.1.7-RC3859 from RC3843 naturally spawned mobs seem to be stuck and unable to be damaged or despawned. Sometimes they can be damaged and killed while sometimes even if you damage them they eventually get stuck and cannot be killed Providing video link to explain it better.[Link to video](https://youtu.be/eT68TCyKmLQ).

**Comment by gabizou** [comment]
Can you upload the `.mixin.output` and `CLASSLOADER_TEMP` folders zipped up when you run the server with `-Dmixin.debug.export=true -Dlegacy.debugClassLoading=true -Dlegacy.debugClaassLoadingSave=true`? I have a feeling that somehow the injection points that I've written are no longer applying at the right places in some circumstances since moving away from an `@Overwrite`.

**Comment by kristi71111** [comment]
> Can you upload the `.mixin.output` and `CLASSLOADER_TEMP` folders zipped up when you run the server with `-Dmixin.debug.export=true -Dlegacy.debugClassLoading=true -Dlegacy.debugClaassLoadingSave=true`? I have a feeling that somehow the injection points that I've written are no longer applying at the right places in some circumstances since moving away from an `@Overwrite`.

As per request. Files were too big to be uploaded to github so attaching google drive link.
[Here](https://drive.google.com/drive/folders/1UZ3IZW7Bawufp-giI-uWXusQc413unKa?usp=sharing)

**Comment by Animadoria** [comment]
That happens to me too whenever entities change chunks.

**Comment by TheFlash787** [comment]
I can confirm that this happens when unloading all un-used chunks with:
```java
for(Chunk chunk : world.getLoadedChunks()){
    if(world.unloadChunk(chunk)){
        chunksUnloaded++;
    }
}
```
I noticed the same issue when using CatClearLag which uses `Chunk#unload` instead, but produced the same result where all entities (items included) would 'desync' and become unresponsive on the server, as shown in @kristi71111's video.

**EDIT:** I have also tested this whilst on SpongeVanilla and the same issue occurs.

**Comment by Pulverizer** [comment]
Can confirm on SpongeForge 1.12.2-2838-7.1.7-RC3856. @gabizou knows roughly how my plugin works.

```java
Set<Entity> entities = craft.getWorld().getIntersectingEntities(new AABB(oldHitBox.getMinX() - 0.5, oldHitBox.getMinY() - 0.5, oldHitBox.getMinZ() - 0.5, oldHitBox.getMaxX() + 1.5, oldHitBox.getMaxY() + 1.5, oldHitBox.getMaxZ()+1.5));

Movecraft.getInstance().getLogger().info("Entity Count: " + entities.size());
```

I was stood in the area but console logged no entities.

Next attempt to move the craft it moved a stack of dropped items but not me.
I picked up the moved stack of items but it left these in the old location. Can't pick them up or anything.
![](https://cdn.discordapp.com/attachments/142425521391665153/605347285794291712/unknown.png)

**Comment by Pulverizer** [comment]
Have tested and confirmed that these issues do not exist in RC3845.
