### ISSUE TITLE
Crash SpongeForge (Foamfix)

### ISSUE THREAD

**Issue by diaverso** [SpongePowered/SpongeForge#2910]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.1.7-RC3859
- Forge version: forge-1.12.2-14.23.5.2838-universal
- Java version: Version 8 Update 221 
- Operating System: Windows Server 2016

- Plugins/Mods:
Mods: Modpack SevTech
Plugins: worldedit-sponge-api7.1.0-6.1.10-SNAPSHOT-dist, webapi-5.4.2-S7.1.0, SkinsRestorer, Nucleus-1.12.2-S7.1-MC1.12.2-plugin, MMCTickets-2.0.7-API-7, MMCRestrict-1.5.1-API-7, MMCReboot-2.3.2-API-7, Maintenance, LuckPerms-Sponge-4.4.27, flexiblelogin-0.17.4

**Good, I have problems on the server.
What it looks like is when loading a new chunk.
When I walk and move, it fails. It can be seen in the video.
I am using “spongeforge-1.12.2-2838-7.1.7-RC3859”
And I have the mod “foamfix-0.10.5-1.12.2”

Make the configuration changes,
Disable the following settings in config/foamfix.cfg :
B:optimizedBlockPos=false
B:patchChunkSerialization=false

foamfix.cfg: https://gist.github.com/diaverso/128d31ed232370fa8c2ba48c05d64ff1

Error Description: Exception generating new chunk

java.lang.RuntimeException: java.lang.NoSuchMethodException: net.minecraft.world.WorldServer.updateWorldGenerator()

It seems to be a foamfix error, but I don’t know how to disable this option.
**

Crashlog: https://gist.github.com/diaverso/bfcf7dccde580fa77ac2524cfa81dacd

Debug: 

Latest: https://gist.github.com/diaverso/be6cbe84c743e61ecbb0179a0cc38b6b

Video: https://www.youtube.com/watch?v=9SROO-1WaYs&feature=youtu.be

**Comment by gabizou** [comment]
```
Caused by: java.lang.NoSuchMethodException: net.minecraft.world.WorldServer.updateWorldGenerator()
	at java.lang.Class.getMethod(Unknown Source)
	at farseek.world.gen.structure.StructureGenerationChunkProvider$.createSpongeGenerator$lzycompute(StructureGenerationChunkProvider.scala:81)
	at farseek.world.gen.structure.StructureGenerationChunkProvider$.createSpongeGenerator(StructureGenerationChunkProvider.scala:81)

```
Ask Farseek to update. Not a sponge issue.

**Comment by ImMorpheus** [comment]
Also, Duplicate of https://github.com/SpongePowered/SpongeForge/issues/2894
