### ISSUE TITLE
Extra Utilities Quarry issue. Similar to #1961  

### ISSUE THREAD

**Issue by Bertieio** [SpongePowered/SpongeForge#2911]
**I am currently running**

- SpongeForge version: 1.12.2-2825-7.1.6
- Forge version: 2825
- Java version: 1.8.0_212
- Operating System: Ubuntu 19.04 (I have also tested on Windows 10)

- Mods: I am running the [All The Mods 3 Pack](https://www.curseforge.com/minecraft/modpacks/all-the-mods-3) so too many to mention
But ExtraUtils2 is version 1.9.9
 - Plugins: AutoCommands, CatClearLag, CommandSigns Reloaded, LuckPerms, MMCReboot, Nucleus, Slash Discord. 

**Issue Description**
When powering an ExtraUtils2 Quantum Quarry it does not work and repeatedly spams 
[Log_Error.txt](https://github.com/SpongePowered/SpongeForge/files/3445637/Log_Error.txt) It created a 6GB log file in a couple of hours

I followed the fix found in #1961 but was unsure of the format for the config\sponge\worlds\extrautils2\extrautils2_quarry_dim\dimension.conf file

I posted on the discord and was told to run

/sponge config -d extrautils2:extrautils2_quarry_dim world.load-on-startup true
/sponge config -d extrautils2:extrautils2_quarry_dim world.keep-spawn-loaded true
and reboot the server. 

This did not change the dimension.conf file.

I posted on discord again and was told to add /sponge reload -g before rebooting 
This made the load-on-startup true stick but nothing else. I also tried setting it in the world.conf file but this also cleared itself.

I also tried adding deny-chunk-requests=false, load-on-startup=true, keep-spawn-loaded=true and config-enabled=true to both files but it did not help.
  

I will attach the log files later, I can't get them off the server currently

**Comment by gabizou** [comment]
Can you retry with a newer version of SpongeForge? It will require the newer version of Forge (it's built against Forge 2838, but 2825 should work maybe). There's a bit of the log that isn't being printed in that null  exception, so it's rather useless for us to know where it's coming from.

**Comment by Bertieio** [comment]
Thanks, updating to 1.12.2-2838-7.1.7-RC3863 worked straight up without having to edit the config file or update forge. I'll back up and deploy it to my server in the next couple of days. 

Do you still want the other log files? 

I am happy that this is solved in a newer version.
