### ISSUE TITLE
When should file-io-thread sleep be used? Does using it have any pros and/or cons?

### ISSUE THREAD

**Issue by yagomont** [SpongePowered/SpongeForge#2912]
Haven't found much information around this option, so I'd like to know what it's used for.

**Comment by Zidane** [comment]
@yagomont The issue tracker is not for asking questions on how something works, please use the Discord or the forums for this next time.

That setting, if enabled, will have the Vanilla file IO thread to sleep (aka not perform any processing). In Sponge, this is false by default as we feel it is better to have Vanilla process these queues to try and keep the memory usage lower. If you would like, you can experiment with turning this on and see how your results vary. It is basically trading CPU cycles (enabled) vs more memory usage.
