### ISSUE TITLE
Fake players reset skulls to skeleton heads when placed

### ISSUE THREAD

**Issue by themaster402** [SpongePowered/SpongeForge#2913]
**I am currently running**

- SpongeForge version: 2838-7.1.7-RC3866 
- Forge version: 14.23.5.2838
- Java version: OpenJ9 1.8.0_212
- Operating System: Windows 10

- Plugins/Mods:
Nucleus
CatClearLag
MagiBridge
LuckPerms

Enigmatica 2 Expert modpack
![image](https://user-images.githubusercontent.com/5889962/62212596-bb9d3d80-b3a9-11e9-9ee5-51b1ac106c83.png)
![image](https://user-images.githubusercontent.com/5889962/62212606-c1931e80-b3a9-11e9-9c94-7440cd74bb14.png)

**Issue Description**
When any fakeplayer block placer is assigned to place a wither skull (Industrial Foregoing Wither Builder, Extra Utilities Mechanical Placer, etc), the skull changes into a regular skeleton head. Upon removing Sponge, the placers work as usual.

https://gist.githubusercontent.com/themaster402/24dcc71d8c2b0db19218c473d25411a9/raw/f908718fab5e8966007541c0aa966fac941f124a/gistfile1.txt

**Comment by clienthax** [comment]
Taking a looky

**Comment by clienthax** [comment]
@themaster402 retest on latest spongeforge
