### ISSUE TITLE
AE2 cristals/fluix won't grow

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeForge#2919]
**I am currently running**
- SpongeForge version: 1.12.2-2825-7.1.6
- Forge version: 1.12.2 - 14.23.5.2838
- Java version: 1.8.0_121
- Operating System: Ubuntu 16.06

- Plugins/Mods: appliedenergistics2-rv6-stable-7, SpongeForge

**Issue Description**
When Sponge is installed, AE2 won't make fluix crystals nor grow seeds. Not sure if it's the same issue, but it's similar to https://github.com/SpongePowered/SpongeForge/issues/2731 that apparently was fixed.

**Comment by gabizou** [comment]
This was re-fixed in newer builds. Will reopen if it's reproducible on newer builds (RC-3878).
