### ISSUE TITLE
Sponge RC3880 + LagGoggles-FAT-1.12.2-4.6 = crash 

### ISSUE THREAD

**Issue by enigmaspb** [SpongePowered/SpongeForge#2922]
**I am currently running**
- SpongeForge version:   spongeforge-1.12.2-2838-7.1.7-RC3880.jar
- Forge version: 2838
- Java version: 1.8.0_191
- Operating System: Debian 10

- Plugins/Mods:
LagGoggles-FAT-1.12.2-4.6.jar

Update Sponge from RC3875 to RC3880 and get crash server , test in clear new install 
only Sponge RC3880 and LagGoggles 4.6

debug.log
[debug.log](https://github.com/SpongePowered/SpongeForge/files/3477502/debug.log)
https://gist.github.com/enigmaspb/6631fab4d91b45392b8e70b019708374

**Comment by Zidane** [comment]
LagGoggles will need to update once more. Our naming policy was not quite complete when they updated. Sorry about that!
