### ISSUE TITLE
CC: Tweaked turtles lose state and NBT when moved 

### ISSUE THREAD

**Issue by lurr** [SpongePowered/SpongeForge#2927]
**I am currently running**
- SpongeForge version: 1.12.2-2838-7.1.7-RC3885
- Forge version: 1.12.2-14.23.5.2838
- Java version: 1.8.0_222/64bit (Oracle Java)
- Operating System: Arch Linux (5.2.6 with linux-zen patchset)

Plugins:
- GriefPrevention 1.12.2-4.3.0.692
- LuckPerms 4.4.28

Mods:
- CC: Tweaked 1.84.0

**Issue Description**
When turtles move, they lose their state.
This only occurs with GriefPrevention combined with Sponge verisons above RC3854.

Logs: https://gist.github.com/lurr/099d8f61619cdd63def18c1d4cbae34c
Demonstration video: https://files.lurr.xyz/resources/bug-reports/turtle-bug.mp4

**Comment by gabizou** [comment]
Can you try with RC3886?

**Comment by lurr** [comment]
No longer occurs on RC3886, :+1:
