### ISSUE TITLE
Error when using Mine and Slash Portals

### ISSUE THREAD

**Issue by AzureDoom** [SpongePowered/SpongeForge#2931]
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2838-7.1.7-RC3892
- Forge version: forge-1.12.2-14.23.5.2838
- Java version: Java 8
- Operating System: Windows

- Plugins/Mods: Baubles-1.12-1.5.2, dotHackWeapons-1.7.5, Mine_and_Slash-1.6.20, Patchouli-1.0-18

**Issue Description**
Attempting to use the portals from the map device of Mine and Slash (requires 1 seed, 1 map (`/givemap @p 1 1 1 1` will give you a map), and the map device) does not teleport you to the generated dim. 

Full Latest Log Here: https://gist.github.com/AzureZhen/bb4214db0e871027dd9900b55ee952bc
Full Lastest Log Here: https://gist.github.com/AzureZhen/6a22c44fddb8f6a1b487c87fe3c324f1

**Comment by KorewaLidesu** [comment]
Phase not completed as it should be

**Comment by AzureDoom** [comment]
Yeah seems it's not liking `Block{InvokingTeleporter}`

**Comment by Zidane** [comment]
Actually there is a NPE going on with 

[01:00:06] [Server thread/INFO] [STDERR]: [com.robertx22.dimensions.blocks.MapPortalBlock:func_180634_a:126]: 	at net.minecraft.world.Teleporter.impl$handleEntityPortalExit(Teleporter.java:1143)

In Sponge code...I'll download this mod and investigate when I have time.

**Comment by AzureDoom** [comment]
Just seeing if you had any luck with this issue. I'd really love to use SpongeForge again as I love the plugins.

**Comment by Zidane** [comment]
I just tested with the latest SpongeForge and could not get the exception to generate, at least not in SinglePlayer. Will try server mode.

**Comment by AzureDoom** [comment]
Yeah I test with only the server. I also updated my version to `spongeforge-1.12.2-2838-7.1.7-RC3902`

**Comment by Zidane** [comment]
Okay this was a fun change and ended up with multiple issues. This mod is definitely not doing things correctly but at least Sponge will work with it now. I was able to create a table, throw a map in it, and end up at the dimension.

I made sure that Vanilla portals and plugin command teleports (via Nucleus) still function.
