### ISSUE TITLE
Redstone Bug?

### ISSUE THREAD

**Issue by Pulverizer** [SpongePowered/SpongeForge#2937]
**I am currently running**

- SpongeForge version: latest stable-7 decompWorkspace
- Java version: 8
- Operating System: Windows 10

Plugins/Mods:
 + worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist
 + Movecraft for Sponge in-dev

**Issue Description**

https://clips.twitch.tv/TalentedLivelyAmazonPhilosoraptor

Breaking and replacing the faulty block will work for one use and then need to be repeated.
Updating neighbouring blocks also seems to fix the issue for one use.

[Latest.log](https://gist.github.com/Pulverizer/2939622e22375ee193508ebc9b89a36e)
[Debug.log](https://gist.github.com/Pulverizer/961f1acac10708825aa849c6d6fbc1c8)

**Comment by gabizou** [comment]
Is this reproducible without Movecraft and with just SpongeForge/Vanilla with `-Dsponge.shouldFireAll=true`?

**Comment by Pulverizer** [comment]
Idk if I have done `-Dsponge.shouldFireAll=true` correctly but it is still an issue when running SpongeForge 1.12.2-2838-7.1.7-RC3926

The blocks just stop receiving redstone updates.

**Comment by Pulverizer** [comment]
And I just had a feeling I should try without Sponge. It's Forge :l

But then it's happening with vanilla. Could be that Sponge is causing the world to have an issue even after being disabled?

**Comment by dualspiral** [comment]
I'm closing this as you stated, it's not Sponge (and it's been some time - if there is a Sponge specific component, one for a new issue...)

**Comment by Pulverizer** [comment]
Yeah, I forgot about this. Seems to have creeped into Minecraft between 1.8 and 1.12. Seems to be fixed in 1.15.

If somebody can figure out what is causing it maybe they can write a mixin patch plugin.
