### ISSUE TITLE
Dupe with mana tesseract from Botania additions

### ISSUE THREAD

**Issue by Kantets** [SpongePowered/SpongeForge#2939]
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.1.7-RC-3896
- Forge version: 2838
- Java version: 8_212
- Operating System: Debian 9

- Mods: Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, Astral Sorcery, B.A.S.E, Baubles, Better Questing, BiblioCraft, Blockcraftery, Blood Arsenal, Blood Magic: Alchemical Wizardry, Bonsai Trees, Botania, Botania Needs These Things!, Botanic Additions, Botanic Bonsai, Chameleon, Chisel, ClientTweak, Construct's Armory, CraftTweaker JEI Support, CraftTweaker2, Elevator Mod, EventHelper, ExtraBotany, FTB Library, Familiar Fauna, Fast Leaf Decay, Foamflower, Grimoire of Gaia 3, Guide-API, Hammer Core, Harvest, Item Filters, Just Enough Items, MTLib, Mantle, MetalChests, Mod Tweaker, Morpheus, Mystical Lib, Niisaba's cases, Ore Veins, Oreberries, PlusTiC, Roots Classic, Serene Seasons, SpongeForge, Storage Drawers, Storage Drawers Unlimited, TBone, Thaumcrafft Inventory Scanning, Thaumcraft, Thaumic Additions: Reconstructed, The Betweenlands, The One Probe, Tinker's JEI, Tinkers Tool Leveling, Tinkers' Construct, Totemic, Tough As Nails, Tree Chopper, Vending, Waystones, animalium, manavisualizer

-plugins: Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge,  FastAsyncWorldEdit, AdamantineShield, BorderProtector, CatClearLag, DupeFixer, GriefPrevention, KeepInventorySponge, LuckPerms, MMCReboot, Nucleus, PlayTimeCounter, ProjectCore, StackBan, UltimateChat, WorldEdit, spark

In botanic additions there is a mana tesseract which can be assigned a unique id using a block in the workbench, but on the server the item is duplicated, although it simply should not be spent

Put a tesseract into a craft and a mana in the amount of 2 or more,
pick up craft
If we put the item in the count of 2, we will give 3 and so on, was 64 will become 127

Appears only on the server

**Comment by KorewaLidesu** [comment]
Any log?

**Comment by Kantets** [comment]
What / where is the log fold ?

**Comment by KorewaLidesu** [comment]
latest.log and debug.log
they locate in "logs" folder (server-side)

**Comment by madokaorimura** [comment]
they locate in "logs" folder

**Comment by Kantets** [comment]
[latest.log](https://github.com/SpongePowered/SpongeForge/files/3536994/latest.log)
[debug.log](https://github.com/SpongePowered/SpongeForge/files/3536996/debug.log)

**Comment by KorewaLidesu** [comment]
Weird things is that I can see other problem here
> Expected to exit phase: Plugin{ScheduledTask}                                                                                 
 But instead found phase: Packet{SecondaryInventoryClick}                                                                      
 StackTrace:                                                                                                                   
 java.lang.Exception: null                                                                                                     
> org.spongepowered.common.event.tracking.PhaseTracker.printIncorrectPhaseCompletion(PhaseTracker.java:387)                 
  org.spongepowered.common.event.tracking.PhaseTracker.completePhase(PhaseTracker.java:281)                                 
  org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:616)                                         
  org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:310)                                          
  net.minecraft.server.MinecraftServer.redirect$onRun$zjc000(MinecraftServer.java:4716)                                     
  net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723)                                               
  net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)                                     
  net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)                                               
  net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)                                                        
  java.lang.Thread.run(Thread.java:748)                                                                                     
> Phases Remaining:                                                                                                            
> - Phase: Packet{SecondaryInventoryClick}                                                                                    
>  Context:                                                                                                                  
>  - Owner: EntityPlayerMP['Berilia'/284110, l='world', x=195.78, y=68.00, z=-806.79]                                        
>  - Source: EntityPlayerMP['Berilia'/284110, l='world', x=195.78, y=68.00, z=-806.79]                                       
>  - PacketPlayer: EntityPlayerMP['Berilia'/284110, l='world', x=195.78, y=68.00, z=-806.79]                                 
>  - Packet: CPacketClickWindow{windowId=39, slotId=17, usedButton=1, actionNumber=1, clickedItem=1xtile.air@0, mode=PICKUP} 
>  - IgnoreCreative: false                                                                                                   
>  - ItemStackUsed: 1xtile.air@0                                                                                             
>  - HighlightedSlotId: 0                                                                                                    
>- Phase: Plugin{ScheduledTask}                                                                                              
>  Context:                                                                                                                  
>  - Source: com.google.common.util.concurrent.ListenableFutureTask@134fc5d8                                                 
>  
> StackTrace :                                                                                                                 
 java.lang.Exception: Incorrect Phase Completion                                                                               
>
> org.spongepowered.common.event.tracking.PhaseTracker.printIncorrectPhaseCompletion(PhaseTracker.java:390)                 
> org.spongepowered.common.event.tracking.PhaseTracker.completePhase(PhaseTracker.java:281)                                 
> org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:616)                                         
> org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:310)                                          
> net.minecraft.server.MinecraftServer.redirect$onRun$zjc000(MinecraftServer.java:4716)                                     
> net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723)                                               
> net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)                                     
> net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)                                               
> net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)                                                        
> java.lang.Thread.run(Thread.java:748)                                                                                     
>                                                                                                                          
> Minecraft : 1.12.2                                                                                                            
 SpongeAPI : 7.1.0-20b5f1b02                                                                                                   
 Sponge : 1.12.2-7.1.7-SNAPSHOT                                                                                                
 SpongeForge : 1.12.2-2838-7.1.7-RC3896                                                                                        
 Minecraft Forge : 14.23.5.2838

**Comment by Kantets** [comment]
![image](https://user-images.githubusercontent.com/44499477/63763217-79a2e100-c8ee-11e9-95e4-5a7e8636a23d.png)
![image](https://user-images.githubusercontent.com/44499477/63763227-7f002b80-c8ee-11e9-98b5-8b90ad5cbe24.png)
https://gitlab.com/DragonForge/botanic-additions/issues/6

**Comment by ImMorpheus** [comment]
Not able to reproduce with SF (https://github.com/SpongePowered/SpongeForge/commit/bf5477e787a2819f13342faf5f0bf85fa611a561)

The relevant issue on the botanic additions repo is also closed/fixed.
