### ISSUE TITLE
many chunks connected with each other load&unload in one tick too frequently.

### ISSUE THREAD

**Issue by Jecvay** [SpongePowered/SpongeForge#2941]
SpongeForge
    Minecraft: 1.12.2
    SpongeAPI: 7.1.0-fb496dbf0
    Sponge: 1.12.2-7.1.7-SNAPSHOT
    SpongeForge: 1.12.2-2825-7.1.7-RC3774
    Minecraft Forge: 14.23.5.2825
    JVM: 1.8.0_191/64-bit (Oracle Corporation)
    OS: Windows Server 2016 (10.0/amd64)

Plugins (38): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge,  FastAsyncWorldEdit, AdventureMMO, AmberShop, Boop, Brotkasten, Clearall, CommandBlockingManager, DupeFixer, ES-Webhook, ESPayMoney, EconomyLite, FlexibleLogin, GriefPrevention, Holograms, ItemCommand, LuckPerms, MMCRestrict, MaintenanceSponge, New Honor, Nucleus, OfflineServerUsernameWebRequestNetworkManager, PlaceholderAPI, Prism, SayItem, ServerListPlus, SoulClear, TeslaCore, TeslaLibs, Unity, VirtualChest, WorldEdit, YYS ScoreBoard, spark, 我的插件

Mods (52): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AI Improvements, Advanced Solar Panels, Another Common Bug Fix, Applied Energistics 2, Armourer's Workshop, Avaritia, Baubles, Better Records, Botania, Clumps, CodeChicken Lib, Console Filter, CraftTweaker JEI Support, CraftTweaker2, CreativeCore, CreativeCoreDummy, CustomNPCs, FTB Library, FTB Quests, FTB Utilities: Backups, Fast Leaf Decay, FoamFix, FoamFixCore, IndustrialCraft 2, Iron Chest, Item Filters, Just Enough Items, LagGoggles, LittleTiles, LittleTilesCore, Mantle, MineTweakerRecipeMaker, MrCrayfish's Vehicle Mod, NoDestroy, Obfuscate, Placeholder Items/Blocks, Shadowfacts' Forgelin, ShootIt, SlashBlade, SpongeForge, TOP Addons, The Last Smith, The One Probe, Tinkers Tool Leveling, Tinkers' Construct, Vanilla Food Pantry

Though my tps = 20.0
but the graph of cpu is strange.
the GC is very frequently
and after i turn on the log of chunk-load & unload & pre-gc-queue
i found that large amount of chunks connect with each other will be load or unload in one tick
and too frequently.

i9-9900K & 8 Players online.

<img width="653" alt="chunk_reload" src="https://user-images.githubusercontent.com/3610248/63458489-75f20300-c485-11e9-916e-b4d740b9a277.png">

**Comment by Jecvay** [comment]
[more details here](https://gist.github.com/Jecvay/7b66a801459a5dbb055c5dae6e0a7915)

[this time is serious](https://gist.github.com/Jecvay/7b66a801459a5dbb055c5dae6e0a7915#file-chunk_load_unload-log-L1614-L2766)

**Comment by Jecvay** [comment]
I dont know whether we have patch like this
[https://github.com/PaperMC/Paper/issues/51](https://github.com/PaperMC/Paper/issues/51)

but async chunk generation will not solve this problem.
this is not a generation's lag
it is load & unload.

**Comment by Jecvay** [comment]
is there a data structure save the relationship of these chunks, when someone stand in a range which contained large relation-chunks then keep all chunks in the range in memory.

**Comment by liach** [comment]
forge has a dormant chunk cache so that some unloaded chunks that is likely to be reloaded very soon are not recycled. you can try that (though it is considered somehow buggy)

**Comment by KorewaLidesu** [comment]
You can try set those chunk to be always loaded or somethings like that
But thing's that it isn't the best solution.....

**Comment by Jecvay** [comment]
sorry, this is the problem of Prism.jar
not cause by chunk.

**Comment by gabizou** [comment]
> sorry, this is the problem of Prism.jar

So Prism is somehow loading chunks randomly? Is this not an issue for SpongeForge then?

**Comment by Jecvay** [comment]
> So Prism is somehow loading chunks randomly? Is this not an issue for SpongeForge then?

loading chunks randomly not cause lag.
Prism cause the lag (but not cause by loading chunks) by other reasons.
