### ISSUE TITLE
Lost experience

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#2942]
### I am currently running
- SpongeForge version: 1.12.2-2838-7.1.7-RC3902 
- Forge version: 2838

This problem has existed since the past
### Issue Description
How to reproduce:

- First enable gamerule keepInventory
- When the player dies, if the player uses the `Respawn` button after about 1 minute or more, the experience will be lost , or use the `Title Screen` button to join the server again, the experience will be lost too.

**Comment by KorewaLidesu** [comment]
Have try without SF?

**Comment by ghost** [comment]
Vanilla server is fine, but it will happen with both spongevanilla and spongeforge

**Comment by ghost** [comment]
Vanilla demo (everything is normal
https://gyazo.com/3d94efe9e609fbfe9b355cc46d201124

Sponge demo (lost experience and level
https://gyazo.com/16f5bddc70bf1896e622be74668351bf

**Comment by KorewaLidesu** [comment]
Try only Forge if it work fine?

**Comment by ghost** [comment]
yes , only forge also works fine

**Comment by KorewaLidesu** [comment]
Can you take a error log?
latest.log and debug.log too (upload via gist.github.com)

**Comment by ghost** [comment]
As far as I know, it has no error message.

**Comment by ghost** [comment]
Is there any progress on this issue?

**Comment by LXGaming** [comment]
This is caused by Sponge using its own keepInventory flag, This flag is only updated on death meaning that reconnecting will cause it to be defaulted to false.

https://github.com/SpongePowered/SpongeCommon/blob/f7fce1ada4a8072815324b9d99d11582deb8e91d/src/main/java/org/spongepowered/common/mixin/core/entity/player/EntityPlayerMPMixin.java#L322-L332

**Comment by Faithcaio** [comment]
Thanks @LXGaming for the research
