### ISSUE TITLE
Request memory analysis support

### ISSUE THREAD

**Issue by zhourui123** [SpongePowered/SpongeForge#2945]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.1.7-RC3843
- Forge version: forge-1.12.2-14.23.5.2838-universal
- Java version: java8
- Operating System:debian

- Plugins/Mods:
```
			mfbl_survival_plugin-1.0-SNAPSHOT.jar,
			mfbl-1.0.jar,
			spongeforge-1.12.2-2838-7.1.7-RC3843.jar,
			twilightforest-1.12.2-3.8.689-universal.jar,
			Nucleus-1.11.0-S7.1-MC1.12.2-plugin.jar,
			Ferdinand'sFlowers-1.12.x-1.10.4.1.jar,
			spark.jar,
			LuckPerms-Sponge-4.3.75.jar,
			appliedenergistics2-rv6-stable-1.jar,
			CodeChickenLib-1.12.2-3.2.0.345-universal.jar,
			CoFHCore-1.12.2-4.6.3.27-universal.jar,
			CoFHWorld-1.12.2-1.3.1.7-universal.jar,
			Cucumber-1.12.2-1.1.3.jar,
			Mantle-1.12-1.3.3.55.jar,
			MysticalAgradditions-1.12.2-1.3.2.jar,
			MysticalAgriculture-1.12.2-1.7.5.jar,
			RedstoneFlux-1.12-2.1.0.6-universal.jar,
			SlashBlade-mc1.12-r25.jar,
			TConstruct-1.12.2-2.12.0.157.jar,
			ThermalExpansion-1.12.2-5.5.4.43-universal.jar,
			ThermalFoundation-1.12.2-2.6.3.27-universal.jar,
			SJAP-1.1.0.jar

```

**Issue Description**
Memory usage has improved since I used aikar flags, but there are still problems.

There were fewer than 20 players, but the server was running with more than 20G of memory.
I used spark to get the heap dump file, then use MAT to get the analysis results(hprof file size is 5.7G). 

Please help to see whether mods or sponge itself causes the memory to be too high.

If it's not a bug, can you give me some optimization suggestions? thank you so much!

[heap-8_26_09_System_Overview.zip](https://github.com/SpongePowered/SpongeForge/files/3549153/heap-8_26_09_System_Overview.zip)
[heap-8_26_09_Top_Components.zip](https://github.com/SpongePowered/SpongeForge/files/3549154/heap-8_26_09_Top_Components.zip)
[heap-8_26_09_Leak_Suspects.zip](https://github.com/SpongePowered/SpongeForge/files/3549156/heap-8_26_09_Leak_Suspects.zip)

**Comment by KorewaLidesu** [comment]
I would recommend you to use OpenJ9 instead since it improve momery (not too much) allocated. <Use OpenJDK 8 (LTS)>
Leak Suspects: (?)
1 is net.minecraft.world.WorldServer <---- I think it come from twilightforest and chunk loader?
2 is net.minecraft.entity.player.EntityPlayerMP <---- As it's name ;c

**Comment by zhourui123** [comment]
Thank you madokaorimura!  How do I confirm it leak from twilightforest?

**Comment by ImMorpheus** [comment]
**Github isn’t a support forum.** It is for reporting bugs in the software.

Discord and the Sponge Forums are better places for support.
