### ISSUE TITLE
Permission issue with mod self created ICommandSender 

### ISSUE THREAD

**Issue by Sir-Will** [SpongePowered/SpongeForge#2946]
**I am currently running**
spongeforge-1.12.2-2838-7.1.7-RC3902
LuckPerms-Sponge-4.4.30

**Issue Description**
The mod Topography and Triumph runs commands on specific actions which are run as self created `ICommandSender` as it can be seen here: 
https://bitbucket.org/bloodnbonesgaming/topography/src/8f4926168ce680bdcbefe0e4630d4060808cef54/src/main/java/com/bloodnbonesgaming/topography/event/EventSubscriber.java#lines-180

For `canUseCommand` it just returns true which is to sudo the commands as far as I can tell. This seems to be working fine with the vanilla permission level system but the moment the permission plugin LuckPerms is installed this is failing because of the lack of permissions.

I don't think LP can do much about this which is why I reported this issue here.

**Comment by gabizou** [comment]
There's not much we can do either I believe. It's a completely unknown "user" for all intents and purposes. It may be possible to do a debug with LP to find out waht it's detecting as the uuid or some identifiable information to be able to permit it to work.

**Comment by WillBAnders** [comment]
Related: [SpongeCommon#2375](https://github.com/SpongePowered/SpongeCommon/pull/2375)
