### ISSUE TITLE
TheBetweenlands Primordial Malevolence abilities

### ISSUE THREAD

**Issue by SSKirillSS** [SpongePowered/SpongeForge#2948]
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2838-7.1.7-RC3906 (also tested on RC3898)
- Forge version: forge-1.12.2-14.23.5.2838-universal
- TheBetweenlands: TheBetweenlands-3.4.11-universal

**Issue Description**

Primal Malevolence has one important ability - it's summon heads, which after a couple of seconds turns into projectiles flying to the player. In singleplayer everything works fine, but on the server with spongeforge heads doesn't transform into projectiles. They just disappear. This makes the boss simply "unkillable", because without these projectiles you cannot destroy his shields.

More details: https://the-betweenlands.fandom.com/wiki/Primordial_Malevolence

**Comment by KorewaLidesu** [comment]
Can you find any error log and upload it here?
also latest.log and debug.log too (upload via gist.github.com)

**Comment by SSKirillSS** [comment]
Nothing appears in the logs, as in the debug.

**Comment by SSKirillSS** [comment]
Still an issue.
spongeforge-1.12.2-2838-7.1.7-RC3924

**Comment by SSKirillSS** [comment]
Still an issue...
spongeforge-1.12.2-2838-7.1.7-RC3928
TheBetweenlands-3.4.12-universal

**Comment by SSKirillSS** [comment]
Still an issue :c
spongeforge-1.12.2-2838-7.1.7-RC3948
TheBetweenlands-3.5.1-universal


UPD: Sludge Jet Turret from latest update does not working too.

**Comment by clienthax** [comment]
https://github.com/Angry-Pixel/The-Betweenlands/issues/539

**Comment by gabizou** [comment]
Thanks @clienthax for looking into the issue and finding the solution! I'm tempted to have a warning for the entity type when it's found that it's being omitted by the two optimizations (print once, don't print for future cases).

**Comment by SSKirillSS** [comment]
Thanks. Boss now working properly, but Sludge Jet Turret still doesn't attack player, but this is not so important.
