### ISSUE TITLE
Exception occurred during a PhaseState (Pixelmon Server)

### ISSUE THREAD

**Issue by MaxSaleh** [SpongePowered/SpongeForge#2951]
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2825-7.1.6
- Forge version: forge-1.12.2-14.23.5.2838-universal
- Java version: Java 8
- Operating System: Ubuntu
(I don't use the latest but the recommended because there is major issues with the latest sponge with pixelmon)

- Plugins: https://timings.aikar.co/?id=89dc7fdd1dff48bdb84faab4e319db3e#plugins
- Mods: Pixelmon

**Issue Description** I honestly don't know how it happens but I would like to report it because it is spamming my console a little.

Issue: https://paste.gg/p/anonymous/905c2bda8bfa4cc79c80edf9b1d2a5e0

**Comment by Tangosucka** [comment]
I'm getting something very similar.   Server runs fine for a while then this spams this and everything freezes then reboots from server tick hang.

https://pastebin.com/LLPAbVCu

**Comment by MaxSaleh** [comment]
Yeah its very annoying

**Comment by Zidane** [comment]
@Tangosucka Different, make a new issue.

EDIT: nvm, I see you did. Thanks :).

**Comment by gabizou** [comment]
Can you re-test on latest? I'm almost positive this issue has already been resolved in a more recent build.

**Comment by MaxSaleh** [comment]
Will do

**Comment by MaxSaleh** [comment]
Check out my latest issue as it is similar and I am using the latest spongeforge too

**Comment by ImMorpheus** [comment]
Please don't open new issues for the same bug. Keep the discussion on the same issue.

**Comment by MaxSaleh** [comment]
Thank you for re-opening it for me I by accident closed it.
