### ISSUE TITLE
Exception occurred during a PhaseState

### ISSUE THREAD

**Issue by Tangosucka** [SpongePowered/SpongeForge#2953]
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.1.7-RC3909
- Forge version: 12.2.2838
- Java version: 8
- Operating System:windows server 2016

- Plugins/Mods:Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AetherWorks, Astral Sorcery, Atum 2, AutoRegLib, Baubles, Bewitchment, Blood Magic: Alchemical Wizardry, Bookshelf, Botania, Charm, CodeChicken Lib, Colytra, Corail Tombstone, Coralreef, CoroUtil Library, CraftStudio API, Craftable Elytra, Desire Paths, Dynamic Sword Skills, Embers Rekindled, Enchanting Plus, Exotic Birds, Extended Mod Config, Extended Renderer, Extra Bows, Fairy Lights, FoamFix, FoamFixCore, Food Expansion, Guide-API, Hostile Worlds Invasions, Illagers+, Infernal Mobs, JourneyMap, Just a Few Fish, LLibrary, LibraryEx, Localized Weather & Storms, Magical Psi, Mo' Villages, Mowzie's Mobs, MrMarnics's Animal Net, Mystical Lib, Mystical World, NetherEx, NetherPortalFix, OreLib Support Mod, Patchouli, Pet Bat, Phosphor Lighting Engine, Placebo, Project: Vibrant Journeys, Psi, Quark, Rex's Additional Structures, Roots, Rough Mobs 2, Rpg Inventory, Shadowfacts' Forgelin, Shipwrecks!, Simple Flax, Soot, SpongeForge, Subaraki's Common Library, SwingThroughGrass, Sword Skills API, TeamLapen Library, TekTopia, Telepads, Thaumcrafft Inventory Scanning, Thaumcraft, Thaumic Augmentation, Thaumic Periphery, Thaumic Wonders, Tree Chopper, Vampirism, Waila, Wearable Backpacks, Wither Skeleton Tweaks, Worley's Caves, Zombie Players

**Issue Description**

Server is running fine for a while then this spams this and everything freezes then reboots from server tick hang.  The whole world is pregenned. Server doesn't crash until around 5 minutes after this happens due to watchdog timeout.
 this is server log
https://drive.google.com/open?id=1i5G__Fk8Kvgaeyz9iYcBuWvOJFJiWfLT

**Comment by Tangosucka** [comment]
So after going over sponge version changelogs and such.  I went back to 3904 since it mentioned phase states.  3903 works fine anything after gives these errors.

**Comment by KorewaLidesu** [comment]
Phase SpongeLocatableBlock is doing somethings weird with Flowing fluid

**Comment by gabizou** [comment]
Try build 7.1.7-RC3912 (it's building at the moment). If there's a single exception trace from the log, please provide it for me, I need to know if we're capturing unintentionally in a particular instance that needs to be tracked down.

**Comment by Tangosucka** [comment]
Ok so after around 2 hours of playing and generating a few new chunks no errors so far .   The error used to happen within about 5 minutes of playing.  Will report back if anything comes up

**Comment by gabizou** [comment]
Going to close this for now as a few issues have been fixed with resetting as of late. If there's an error that does come up, do reply with the new error and we'll re-open the issue.
