### ISSUE TITLE
Incompatibility with movements and dances

### ISSUE THREAD

**Issue by HeberonYT** [SpongePowered/SpongeForge#2958]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.1.7-RC3909
- Forge version: 14.23.5.2838
- Java version: 1.8.0_201
- Operating System: Centos 7

- Plugins/Mods:
emoticons-0.3
spongeForge

**Issue Description**
There is an incompatibility with the Emotes mod, which basically adds improved movements when walking, flying, and Fornite dances.
https://www.curseforge.com/minecraft/mc-mods/emoticons

When installing spongeForge on a server the animations of walking, mining, lying down and flying continue to work, but the dances are lost and nothing else is displayed that the other player does, only the client side will see the dance.
I wish I could resolve this issue if possible, because the mod is very nice.

LOG: https://pastebin.com/raw/geTe8sRA

**Comment by HeberonYT** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/13698597/64644443-4b3a0100-d3d8-11e9-9436-81459840bd90.png)

**Comment by gabizou** [comment]
Mod is closed source, so I can't even begin to know what modifications they make on entity movement code to achieve dancing. As it isn't causing a game crash or otherwise visual inconvenience, the issue will be low priority but eventually dealt with.

**Comment by mchorse** [comment]
I think the issue might come from the fact that one of the hooks might not get called, get called incorrectly, or in the wrong order from Forge. I have following code in Emoticons: 

```java
    @SubscribeEvent
    public void ose(FMLNetworkEvent.CustomPacketRegistrationEvent<NetHandlerPlayServer> event)
    {
        for (String channel : event.getRegistrations())
        {
            if (channel.equals(Emoticons.MOD_ID))
            {
                if (event.getHandler() instanceof NetHandlerPlayServer)
                {
                    this.players.put(event.getHandler().player, true);
                }

                break;
            }
        }
    }

    /**
     * When player logs on the server, request 
     */
    @SubscribeEvent
    public void playerLogsIn(PlayerLoggedInEvent event)
    {
        if (this.players.containsKey(event.player))
        {
            this.players.remove(event.player);

            Cosmetic.get(event.player).setMode(CosmeticMode.SERVER);
            Dispatcher.sendTo(new PacketGameMode(), (EntityPlayerMP) event.player);
        }
    }
```

Which is used on the server side whether a client has Emoticons mod by checking the registration of a custom network channel. If that hook doesn't get called, then the server will consider that a player can't emote.

Hopefully that will help.

**Comment by SSKirillSS** [comment]
Any info about this? Maybe temporary locale fix?

**Comment by clienthax** [comment]
I can't reproduce this on latest sponge
forge: 1.12.2-14.23.5.2847
Sponge: 1.12.2-2838-7.1.8-RC3967
emoticons-0.3.2-1.12.2-dist.jar
mclib-1.0.4-1.12.2.jar

![image](https://user-images.githubusercontent.com/1056270/71520527-86dbd680-28b4-11ea-8e4a-f6f6adea4c02.png)

**Comment by SSKirillSS** [comment]
The swimming and flight animations of other players still do not work.

**Comment by mchorse** [comment]
That’s my or Mojang’s fault, at least flying animation. They don’t
synchronize one important regarding to flight state.

**Comment by clienthax** [comment]
@mchorse Reopen this if theres any more issues on our side :)
