### ISSUE TITLE
Twerk Sim 2K16 Errors.

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#2959]
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.1.7-RC3909 
- Forge version: forge-1.12.2-14.23.5.2836-universal
- Java version: 1.8.0_222
- Operating System: Ubuntu 18.04.3 LTS

- Plugins/Mods: Enigmatica 2 expert skyblock

**Issue Description** 

So basically when I right-click with bonemeal on grass or twerk to grow a sapling sponge is throwing errors and it doesn't work. Here https://paste2.org/0Hb42N5I

I removed sponge and it works without issues.

**Comment by ghost** [comment]
The mod link since doot was already confused ^^ https://www.curseforge.com/minecraft/mc-mods/twerk-sim-2k16

**Comment by ghost** [comment]
Works with stable 1.12.2-2825-7.1.6 :/

**Comment by KorewaLidesu** [comment]
Duplicated to #2957
