### ISSUE TITLE
Cause Stack Frame Corruption crash

### ISSUE THREAD

**Issue by 123Kappa** [SpongePowered/SpongeForge#2965]
**I am currently running**

- SpongeForge version: _Aspongeforge-1.12.2-2825-7.1.6.jar
- Forge version: forge-1.12.2-14.23.5.2838-universal
- Java version: 8
- Operating System: Ubuntu

Modpack: Project Ozone 3 and All the Mods 3 Remix

**Issue Description**: Since yesterday both project ozone 3 and all the mods 3 remix have crashed with this weird crash report. Sponge is all over. I do not really know what caused this crash.

Here's the crash report: https://pastebin.com/GVRbUSm4
Logs:  https://pastebin.com/2da2yJ22

**Comment by gabizou** [comment]
For starters, you're running a really old 7.1.6 build, Can you try updating to a newer version? There's been several bug fixes over the last several months and code cleanup that this is likely very much resolved now.

**Comment by 123Kappa** [comment]
Which version do you recommend? What's the most stable one?

**Comment by gabizou** [comment]
Give 1.12.2-2838-7.1.7-RC3903 a shot?

**Comment by gabizou** [comment]
Going to close. If you can get a new crash with a newer build (7.1.7-RC3921 is fairly stable since it's been nothing bug performance improvements and bug fixes), please reply with a new log and we'll re-open.

**Comment by 123Kappa** [comment]
Yeap no crashes so far seems like it's fixed. Thank you gabizou
