### ISSUE TITLE
Failed to use bone meal on apricorn.

### ISSUE THREAD

**Issue by wojanek** [SpongePowered/SpongeForge#2971]
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.1.7-RC3910
- Forge version: 14.23.5.2838
- Java version: 1.8.0_212/64-bit (Oracle Corporation)
- Operating System: Linux (4.4.0-161-generic/amd64)

- Plugins/Mods:
Plugins: 
 FastAsyncWorldEdit, ChangeSkin, ClearMob, FlexibleLogin, GTS, GTS Reforged Bridge, GriefPrevention, ImpactorAPI, LangSwitch, LuckPerms, MagiBridge, Mega Menus, ModBanner, Nucleus, PixelHunt, PixelMoney, ProjectCore, Total Economy, VillagerShops, WorldEdit
Mods:
Applied Energistics 2, Better Questing, Better Questing Quest Book, BiblioCraft, Biomes O' Plenty, Bookshelf, CD4017BE_lib, Chameleon, Chisel, CustomNPCs, Dark Utilities, Enchanting Plus, IndustrialCraft 2, Infernal Mobs, Iron Backpacks, Iron Chest, MCMultiPart, Mantle, Morpheus, MrCrayfish's Furniture Mod, NPC Integration, NetherPortalFix, Ordinary Coins, Pam's HarvestCraft, Pixel Extras, Pixelmon (Version 1.12.2-7.0.7), Redstone Control, Redstone Flux, Rough Mobs 2, SonarCore, SpongeForge, Standard Expansion, Storage Drawers, The Twilight Forest, Tinkers Tool Leveling, Tinkers' Construct

**Issue Description**
I want to apply bone meal to apricorn (from pixelmon mod) but nothing happens and i can see stacktrace beeing generated in logs. To be honest it stoped working after i updated sponge from RC3890 to RC3906.

https://gist.github.com/wojanek/0264b4196b907c280ffbc78a66281301

**Comment by guilhermepyva** [comment]
Same problem, this is occurring when is used just `ChangeBlockEvent event` in a event, without ChangeBlockEvent.Modify, ChangeBlockEvent.Break, etc..

**Comment by gabizou** [comment]
Fixed in https://github.com/SpongePowered/SpongeForge/commit/682f3eba281c2274063fcb1be8070e202939fc60
