### ISSUE TITLE
Error in ticking Pixelmon entity.

### ISSUE THREAD

**Issue by MaxSaleh** [SpongePowered/SpongeForge#2974]
**I am currently running**
- SpongeForge version: 1.12.2-2838-7.1.7-RC3911
- Forge version: 2838
- Java version: 8
- Operating System: Ubuntu

Issue: https://paste.gg/p/anonymous/b2cbc8fdad7549c483340b009eb99db5

**Comment by gabizou** [comment]
Add `-Dlegacy.debugClassLoading=true -Dlegacy.debugClassLoadingSave=true` to the startup flags and zip up the `CLASSLOADER_TEMP` folder for me. Also,  do you have any idea how to reproduce this? A pokemon itneracting with water? And what version of mods are installed (there's a format for a reason).

**Comment by MaxSaleh** [comment]
Mods/Plugins: https://timings.aikar.co/?id=7308a3a17dc24dd2ac6e52d4c44dbbda

(I am getting that zip for you right now.)

**Comment by clienthax** [comment]
@MaxSaleh Wheres that zip?
