### ISSUE TITLE
Phase Context server stall

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#2976]
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.1.7-RC3911
- Forge version: 14.23.5.2838
- Java version: Java 8 latest
- Operating System: Ubuntu 18.04 LTS

- Plugins/Mods:
 **Plugins (32):** Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge,  FastAsyncWorldEdit, ActionBroadcaster, Buycraft, CarrotShop, Eagle Factions, GTS, GriefPrevention, Holograms, HuskyCrates, HuskyUI, ImpactorAPI, Info, LuckPerms, MMCRestrict, MineReset, NuVotifier, Nucleus, PlaceholderAPI, ProjectCore, ProjectPortals, ProjectWorlds, RankUpper, SeriousVote, SignEditor, TabManager, Total Economy, VoxelSniper, WorldEdit
**Mods (78):** Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AE2 Stuff, Applied Energistics 2, BD Lib, Biomes O' Plenty, Classic Combat, CoFH World, CodeChicken Lib, Construct's Armory, CraftTweaker JEI Support, CraftTweaker2, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, Extra Cells 2, Extreme Reactors, FTB Library, Forge Microblocks, Forge Multipart CBE, Galacticraft Core, Galacticraft Planets, Guide-API, ICBM-Classic, Industrial Foregoing, Integration Foregoing, Just Enough Items, LagGoggles, MachineMuse's Modular Powersuits, Mantle, Mekanism, Mekanism: Generators, Mekanism: Tools, Micdoodle8 Core, Minecraft Multipart Plugin, Modular ForceField System, MrTJPCore, Netherending Ores, NoMoreRecipeConflict, Nuclear Physics, NuclearCraft, Numina, OMLib, Open Modular Turrets, OpenComputers, OpenComputers (Core), ProjectRed Core, ProjectRed Exploration, ProjectRed Integration, ProjectRed Transmission, Redstone Flux, Shadowfacts' Forgelin, SpongeForge, TESLA, Tesla Core Lib, Tesla Core Lib Registries, Tinker I/O, Tinkers Tool Leveling, Tinkers' Construct, UniDict, WanionLib, Woot, YABBA, Zero CORE, projectred-compat

**Issue Description:** I'm not sure what causes it but the server often stalls because of hangs and it's always been related to phase contexts and the phase tracker but usually with different blocks each time.

**Crash Report:** https://gist.github.com/OblivionNW/53dc2d5f3d9dd0fbbffd606f6c152d79

**Comment by Tangosucka** [comment]
use newest version

**Comment by kobliznik** [comment]
Use max-tick-time=0 in server.properties

**Comment by ghost** [comment]
> use newest version

I will try but it had only been one version out of date at the time



> Use max-tick-time=0 in server.properties

That doesn't fix the issue, when it happens the server just reaches an unplayable point with lag, the max tick time helps if anything here.

**Comment by gabizou** [comment]
Could you provide a full log? The crash log shows that there’s a lot of red stone nesting going on, but I’d be willing to bet there’s other things going on before this stalls, perhaps it’s printing a lot of phase context processes?

**Comment by ghost** [comment]
Yes, there are several. I will DM the full log to you on Discord. They're for a PvP/Raid/Grief server so if a player stumbled across them it wouldn't be great for the server since they have coordinates
