### ISSUE TITLE
Unable to load nether, causes server crash

### ISSUE THREAD

**Issue by FiveSquared25** [SpongePowered/SpongeForge#2977]
**I am currently running**
- SpongeForge version: RC2830 as that is the one compatible with both the forge version and laggoggles
- Forge version: 14.23.5.2824
- Java version: 1.8.0_212
- Operating System: Windows 10
- Plugins/Mods: Tekxit 3 modpack, with eaglefactions 0.12.0.

**Issue Description**
Upon a user, item, or mob using a nether portal, the server crashes. With the modpack alone, this doesn't happen, so we know it's a sponge/factions problem. https://gist.github.com/FiveSquared25/5a245c66e7c6a27ceaed6c54f6a74500

**Comment by clienthax** [comment]
Any reason you havn't bumped spongeforge + laggoggles version to latest?

**Comment by FiveSquared25** [comment]
Because I'm fairly new at modding Minecraft, and I wasn't sure that if I upgraded LAGGoggles, then would everyone else have to then upgrade their one client side, which would suck because everyone else also has almost no experience modding Minecraft.

When I first started the server, I deleted LAGGoggles in an attempt to use the latest spongeforge, but it didn't work with the forge version

**Comment by gabizou** [comment]
Can you re-test on latest? 7.1.7-RC3921 has several fixes involved with phases and pooling. If you still end up with a crash when going to the nether, reply with a new log (both server and the crash), and I'll re-open the issue.

**Comment by FiveSquared25** [comment]
Just tested on RC3924, server doesn't even launch, crashes in booting phase. Here's what my console tells me: https://gist.github.com/FiveSquared25/5a1a31511176b6adbd79ba36073dea01

I tested without EagleFactions, the nether still crashed it, so I tried it without spongeforge and the nether worked, so at this point I'm putting it down to a sponge problem. Let me know

**Comment by clienthax** [comment]
> Just tested on RC3924, server doesn't even launch, crashes in booting phase. Here's what my console tells me: https://gist.github.com/FiveSquared25/5a1a31511176b6adbd79ba36073dea01
> 
> I tested without EagleFactions, the nether still crashed it, so I tried it without spongeforge and the nether worked, so at this point I'm putting it down to a sponge problem. Let me know

That's because you didn't update laggoggles as mentioned.
