### ISSUE TITLE
Item air bug

### ISSUE THREAD

**Issue by bigenergy** [SpongePowered/SpongeForge#2980]
**I am currently running**

- SpongeForge version:  SpongeForge: 1.12.2-2838-7.1.7-RC3902
- Forge version: 2838
- Java version: 1.8.0_211
- Operating System: Ubuntu 19.04

- Plugins/Mods:

**MODS:**
Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, A Lib, AE2 Wireless Terminals (AE2WTLib), AI Improvements, Advanced Rocketry, Advanced Rocketry Core, Advanced Solar Panels [GamePoint Edition], Alchemistry, Animus, Applied Energistics 2, AutoRegLib, Avaritia, BD Lib, Baubles, BetterBedrockGen, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Blockcraftery, Blood Arsenal, Blood Magic: Alchemical Wizardry, Bloodmoon, Botania, Brandon's Core, Cases, Charset, ChickenChunks, Chisels & Bits, CoFH Core, CoFH World, CodeChicken Librandon's Core, Cases, Charset, ChickenChunks, Chisels & Bits, CoFH Core, CoFH World, CodeChicken Lib, Construct's Armory, CraftTweaker JEI Support, CraftTweaker2, CustomNPCs, Draconic Additions, Draconic Evolution, End: Reborn III, Ender IO, Ender IO Base, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, EnderCore, Environmental Tech, Eternal Singularity, EventHelper, Extra Cells 2, Extra Utilities 2, ExtraBotany, Forestry, GamePoint Mod, GamePoint Mod, GenDustry, Gravitation Suite, Guide-API, Hammer Core, Immersive Cables, Immersive Engineering, Immersive Petroleum, Immersive Tech, IndustrialCraft 2, Just Enough Energistics, Just Enough Items, Lazy AE2, LibrarianLib, LibrarianLib Stage 2, MCMultiPart, Mantle, McJtyLib, Mekanism, MetalChests, More Avaritia, More Bees, Mystical Lib, Mystical World, NuclearCraft, OpenBackup, OpenFM, Patchouli, PlusTiC, Progressive Automation, Project Intelligence, Proxy, Psi, RFTools, RFToolsPower, Random PSIdeas, Redstone Flux, Roots, Shadowfacts' Forgelin, SpongeForge, Surge, TBone, TOP Addons, Thaumcraft, Thaumic Additions: Reconstructed, Thaumic Augmentation, Thaumic Energistics, Thaumic Periphery, The One Probe, Thermal Expansion, Thermal Foundation, Tinkers' Construct, Tree Chopper, UniDict, Universal Modifiers, Valkyrie Lib, Vulpes library, WanionLib, Wireless Crafting Terminal 2, gpaddons, libnine, p455w0rd's Library, tileentitylimiter

**PLUGINS:**
Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge,  FastAsyncWorldEdit, AmberShop, AutoPickup, BelzShop, ClearMob, DupeFixer, ESPayMoney, EconomyLite, GriefPrevention, LuckPerms, MMCRestrict, NanoChat, Nucleus, PayDay, PixelAutoMessages, Plan, PlayTimeCounter, Simple Scavenger, WorldEdit, spark

**Issue Description**

If you throw an item into the air, it will freeze in it. Watch the video.
https://youtu.be/DdvLY5pEbQY
https://youtu.be/cCAJL6-agdw

**Comment by gabizou** [comment]
Please reduce the mod list and plugin list to reproduce. Cannot reproduce just using SpongeForge.

**Comment by bigenergy** [comment]
I seem to have found a solution. I set the values too small entity-activation-range misc.
Sorry for the report, thanks for the reply!
