### ISSUE TITLE
Update forge?

### ISSUE THREAD

**Issue by bigenergy** [SpongePowered/SpongeForge#2985]
Recently, an update has been released for some mods that require forge version 14.23.5.2847 and higher.
I would like to ask, is it planned to update the forge in the near future?

**Comment by gabizou** [comment]
Unless there's a breaking change with Forge that SpongeForge no longer starts on these newer versions of Forge, we're not bumping the forge dependency. You don't need to match *exactly* the version of forge that SpongeForge depends on, but it is recommended at least to run the version or newer.

Being that there still hasn't been any new recommended builds or reports of a breaking change, going to close this as a non-issue.
