### ISSUE TITLE
Problem with upgrading sponge

### ISSUE THREAD

**Issue by kasdo** [SpongePowered/SpongeForge#2987]
Hello! I upgrade my sponge from RC3629 into RC3924 and I have problem, My server is crashing.
I deleted all my mods, worlds and upgraded forge but its not help me.
Log:
https://pastebin.com/5uk3EwTW
Crash:
https://pastebin.com/eC2P0BAd

**Comment by JBYoshi** [comment]
Appears to be an ASM transformer mod conflict between Sponge, [LagGoggles](https://github.com/TerminatorNL/LagGoggles), and/or [ConnectedTexturesMod](https://github.com/Chisel-Team/ConnectedTexturesMod).

**Comment by kasdo** [comment]
Fixed.
