### ISSUE TITLE
Change the players' inventory

### ISSUE THREAD

**Issue by SettingDust** [SpongePowered/SpongeForge#2992]
**I am currently running**
- SpongeForge version:  spongeforge-1.12.2-2825-7.1.6
- Forge version: forge-1.12.2-14.23.5.2825
- Java version: OpenJDK Runtime Environment (build 1.8.0_222-b05)
- Operating System: Linux version 5.2.11-1-MANJARO
- Plugins/Mods: my mod

**Issue Description**

I have develop a mod that modify the MainInventory size & hotbar size. And there.
`org.spongepowered.common.item.inventory.lens.impl.comp.OrderedInventoryLensImpl cannot be cast to org.spongepowered.common.item.inventory.lens.impl.minecraft.PlayerInventoryLens`
How can I fix it? Replace the sponge's  impl with mine?
So, why sponge limit the size? It's strange.

**Comment by SettingDust** [comment]
Then I know I have to override almost whole inventory struct. To avoid the break change, I will use the Capability to do that.
BUT, I still think sponge should NOT hard code something like this. Just read is more flexible.

**Comment by ImMorpheus** [comment]
Please follow the issue template.

What Sponge version are you using ? Where's the log with the error/crash ? Where's the source code of your mod/class to reproduce the issue ?

Add these information and I will reopen the issue.

**Comment by SettingDust** [comment]
> Please follow the issue template.
> 
> What Sponge version are you using ? Where's the log with the error/crash ? Where's the source code of your mod/class to reproduce the issue ?
> 
> Add these information and I will reopen the issue.

Done

**Comment by ImMorpheus** [comment]
> Done

> Where's the log with the error/crash ? Where's the source code of your mod/class to reproduce the issue ?

**Comment by SettingDust** [comment]
```
Caused by: java.lang.ClassCastException: org.spongepowered.common.item.inventory.lens.impl.comp.OrderedInventoryLensImpl cannot be cast to org.spongepowered.common.item.inventory.lens.impl.minecraft.PlayerInventoryLens
        at net.minecraft.entity.EntityLivingBase.handler$onGetItemStackFromSlot$zeg000(EntityLivingBase.java:4000) ~[vp.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2134) ~[vp.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234) ~[aed.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?]
        ... 10 more
```

```
    public CustomInventoryPlayer(EntityPlayer player) throws IllegalAccessException {
        super(player);
        Field mainInventoryField = ObfuscationReflectionHelper
            .findField(InventoryPlayer.class, "field_70462_a");
        mainInventoryField.setAccessible(true);
        mainInventoryField.set(this, NonNullList.<ItemStack>withSize(60, ItemStack.EMPTY));

        Field armorInventoryField = ObfuscationReflectionHelper
            .findField(InventoryPlayer.class, "field_70460_b");
        armorInventoryField.setAccessible(true);
        armorInventoryField.set(this, NonNullList.<ItemStack>withSize(5, ItemStack.EMPTY));

        Field offHandInventoryField = ObfuscationReflectionHelper
            .findField(InventoryPlayer.class, "field_184439_c");
        offHandInventoryField.setAccessible(true);
        offHandInventoryField.set(this, NonNullList.<ItemStack>withSize(1, ItemStack.EMPTY));

        Field allInventoriesField = ObfuscationReflectionHelper
            .findField(InventoryPlayer.class, "field_184440_g");
        allInventoriesField.setAccessible(true);
        allInventoriesField.set(this,
            Arrays.<NonNullList<ItemStack>>asList(this.mainInventory, this.armorInventory,
                this.offHandInventory));
    }
```


I just want to know. How to provide a bigger inventory is exected

In [`org.spongepowered.common.mixin.core.entity.player.InventoryPlayerMixin:112`](https://github.com/SpongePowered/SpongeCommon/blob/4339372db7f0380258225f76e326f87a0e6a1181/src/main/java/org/spongepowered/common/mixin/core/entity/player/InventoryPlayerMixin.java#L112). There is a comment that is [`// for mods providing bigger inventories`](https://github.com/SpongePowered/SpongeCommon/blob/4339372db7f0380258225f76e326f87a0e6a1181/src/main/java/org/spongepowered/common/mixin/core/entity/player/InventoryPlayerMixin.java#L112). But I can't understand how to provide it.

```
public SlotProvider bridge$generateSlotProvider() {
        if ((Class<?>) this.getClass() == InventoryPlayer.class) { // Build Player Lens
            return new SlotCollection.Builder()
                .add(this.mainInventory.size())
                .add(this.offHandInventory.size())
                // TODO predicates for ItemStack/ItemType?
                .add(EquipmentSlotAdapter.class, index -> new EquipmentSlotLensImpl(index, i -> true, t -> true, e -> e == EquipmentTypes.BOOTS))
                .add(EquipmentSlotAdapter.class, index -> new EquipmentSlotLensImpl(index, i -> true, t -> true, e -> e == EquipmentTypes.LEGGINGS))
                .add(EquipmentSlotAdapter.class, index -> new EquipmentSlotLensImpl(index, i -> true, t -> true, e -> e == EquipmentTypes.CHESTPLATE))
                .add(EquipmentSlotAdapter.class, index -> new EquipmentSlotLensImpl(index, i -> true, t -> true, e -> e == EquipmentTypes.HEADWEAR))
                // for mods providing bigger inventories
                .add(this.armorInventory.size() - 4, EquipmentSlotAdapter.class)
                .add(this.getSizeInventory() - this.mainInventory.size() - this.offHandInventory.size() - this.armorInventory.size())
                .build();
        } else if (this.getSizeInventory() != 0) { // Fallback OrderedLens when not 0 sized inventory
            return new SlotCollection.Builder().add(this.getSizeInventory()).build();
        } else {
            return new SlotCollection.Builder().build();
        }
    }
```

**Comment by ryantheleach** [comment]
@ImMorpheus It's more a request for help, they want to know how they can make sure that their modded player inventories in their mod is Sponge compatible. It's probably not strictly an issue, Pinging @Faithcaio

**Comment by SettingDust** [comment]
> @ImMorpheus It's more a request for help, they want to know how they can make sure that their modded player inventories in their mod is Sponge compatible. It's probably not strictly an issue, Pinging @Faithcaio

So, I should post it in froum now? 
But there is not a `Mod Development` there XDD

**Comment by SettingDust** [comment]
I have resloved it with Capability.
But, why sponge limit the hotbar & others' size? Its necessary?
And, whats the comment `// for mods providing bigger inventories` mean?
I still dont konw how to add slot directly to PlayerInventory instead of a additional Inventory provided by Capability

**Comment by Faithcaio** [comment]
It's a bug in Sponge
https://github.com/SpongePowered/SpongeCommon/blob/1743b6a9feceee933060d2421d0671ba9bdbc940/src/main/java/org/spongepowered/common/mixin/core/entity/EntityLivingBaseMixin.java#L910
is doing a blind cast.

> And, whats the comment // for mods providing bigger inventories mean?

If a mod appends slots at the end of the inventory we expect Sponge handles this just fine.

If you instead completly replace the inventory by a custom one it takes the
`// Fallback OrderedLens when not 0 sized inventory`
which is why the casting fails.

**Comment by SettingDust** [comment]
> It's a bug in Sponge
> https://github.com/SpongePowered/SpongeCommon/blob/1743b6a9feceee933060d2421d0671ba9bdbc940/src/main/java/org/spongepowered/common/mixin/core/entity/EntityLivingBaseMixin.java#L910
> is doing a blind cast.
> 
> > And, whats the comment // for mods providing bigger inventories mean?
> 
> If a mod appends slots at the end of the inventory we expect Sponge handles this just fine.
> 
> If you instead completly replace the inventory by a custom one it takes the
> `// Fallback OrderedLens when not 0 sized inventory`
> which is why the casting fails.

But how can I attach slots to the Inv? Reflect?

**Comment by Faithcaio** [comment]
I think you can just add stuff to `mainInventory` etc.
