### ISSUE TITLE
Mod B3M and Sponge, crash server

### ISSUE THREAD

**Issue by MRLexanayseR** [SpongePowered/SpongeForge#2993]
**I am currently running**

- Sponge 1.12.2-2838-7.1.7-RC3926
- Forge 1.12.2-2838
- Java is OpenJDK 64-Bit Server VM, version 1.8.0_212
- Windows 10 Pro x64

- Plugins/Mods:
Plugins - 0
Mods - 1 (B3M) https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2945879-vrashenie-zemli-majnkraftskaya-longer-day-night

**Issue Description**

Sorry to post a new thread. You closed the previous topic, I did not have time to answer. https://github.com/SpongePowered/SpongeForge/issues/2991

Sorry for my English. (Google Translate)
This is very sad. That nothing can be done with compatibility. But the fact is that the stable version of sponge 1.12.2-2825-7.1.6 works with the mod without errors and crashes. In the game, the mod itself also works fine, without crashes. I wanted to update the version of the sponge to the new 1.12.2-2838-7.1.7-RC3926, since there are many changes in the new version of the sponge, but it does not work. Therefore, if it works on the old version, can you still create compatibility? Thank you in advance.

**Comment by ImMorpheus** [comment]
> Sorry to post a new thread. You closed the previous topic, I did not have time to answer. 

You can still comment on the old issue. Please do not open duplicate issues.

Duplicate of https://github.com/SpongePowered/SpongeForge/issues/2991

**Comment by MRLexanayseR** [comment]
Excuse me. I will know now.
