### ISSUE TITLE
Can't allow Cyclic Automated User to GriefPrenvention claims due to wrong ownership

### ISSUE THREAD

**Issue by jinkhya** [SpongePowered/SpongeForge#2994]
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.1.7-RC903
- Forge version: 2838
- Java version: 1.8.0_222
- Operating System: CentOS linux 7

- Plugins/Mods:
Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AE2 Stuff, Advancement Book, Animal Crops, Apotheosis, AppleCore, AppleSkin, Applied Energistics 2, Aroma1997Core, Astral Sorcery, B.A.S.E, BD Lib, BNBGamingLib, Barrels, Drums, Storage & More, Baubles, Bed Patch, BiblioCraft, BnBGamingCore, Bonsai Trees, Bookshelf, Building Gadgets, Caliper, Calm Down Zombie Guy, Carry On, Ceramics, Chargers, ChineseWorkshop, Chisel, Chisels & Bits, Click Machine, Clumps, CoFH Core, CoFH World, CodeChicken Lib, ComPatchedStorage, CommonCapabilities, Compact Machines 3, CompactStorage, Construct's Armory, ContentTweaker, Cooking for Blockheads, Corail Tombstone, CraftTweaker JEI Support, CraftTweaker2, Cucumber Library, Culinary Construct, Cyclic, Cyclops Core, Dark Utilities, Deep Mob Learning, Dimension Stages, DiscordIntegration, DragonMurder, Elevator Mod, Ender Crop, Ender Utilities, EnderCore, EnderStorage, Extended Crafting, Extra Cells 2, Farming for Blockheads, FastFurnace, FastWorkbench, Fence Overhaul, FindMe, Flux Networks, FoamFix, FoamFixCore, Forge Microblocks, Forge Multipart CBE, Forgiving Void, Game Stages, Guide-API, Headcrumbs, Horse Power, Hunting Dimension, HydroGel, InControl, Industrial Foregoing, Inspirations, Integrated Dynamics, Integrated Tunnels, IntegratedDynamics-Compat, IntegratedTunnels-Compat, Iron Jetpacks, Item Stages, JourneyMap, Just Enough Items, KleeSlabs, Limitless Structure Blocks, MCMultiPart, MTLib, MalisisCore, MalisisDoors, Mantle, MatterOverdrive: Legacy Edition, McJtyLib, Mekanism, Mekanism: Generators, Mercurius, Minecraft Multipart Plugin, Mob Stages, Mod Tweaker, ModPack Basic Tools, ModPack Utilities, More Buckets, More Cauldrons, Morpheus, Mystcraft, Mystical Agradditions, Mystical Agriculture, NuclearCraft, OG Dragon+, OpenComputers, OpenComputers (Core), OpenComputers Xnet Driver, OreExcavation, Parabox, Patchouli, Phosphor Lighting Engine, Pickle Tweaks, Pipe Master 2000, Placebo, PlaneFix, PortalGun, Practical Logistics 2, Prestige, Primitive Crafting, ProjectE, RFToolsPower, Ranged Pumps, Real Filing Cabinet, RecipeStages, Redstone Flux, Resource Hogs, Rustic, Shadowfacts' Forgelin, Simple Generators, Simple Inventory sorting, Simple Storage Network, Sky Grid, SkyBonsais, Slab Machines, SlimyBoyos, Smooth Font Core, Snad, SonarCore, SpongeForge, Squeezer Patch, Statues mod, Stuff A Sock In It, Super Sound Muffler, Surge, SwingThroughGrass, Sync, TallGates, TelePastries, Tesla Core Lib, Tesla Core Lib Registries, The Lost Cities, The Twilight Forest, The Weirding Gadget, Thermal Dynamics, Thermal Foundation, Thermal Innovation, TickProfiler, Tinkers Tool Leveling, Tinkers' Complement, Tinkers' Construct, Tiny Progressions, TogetherForever, Topography, TorchMaster, Translocators, Tree Growing Simulator 2016, Triumph, Twitchcrumbs, Universal Modifiers, Valkyrie Lib, ViesCraft, Waddles, Waila, Waila Stages, Wall-Jump!, What Are We Looking At, Wither Crumbs, World Utils, WorldEdit, XC Patch, XL Food Mod, XNet, YNot, Yoyos, ZenStages, bouncy_creepers, iChunUtil, mob_grinding_utils, sky_orchards, uppers

plugins : Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, BetterChunkLoader, CatClearLag, Enjin Minecraft Plugin, GriefPrevention, LuckPerms, MMCRestrict, NuVotifier, Nucleus, SayItem, SkyClaims

**Issue Description**
There's an issue with cyclic automated user not having the right owner making it impossible to allow in griefprevention claims. It is marked as forge:fakeplayer_fakeplayerblockuser which is not usable as source in flags.

Here are a few screenshots you might need : 
- https://i.imgur.com/FKdVaY3.png 
- https://i.imgur.com/HilEBYr.png
However /sponge blockinfo returns : https://i.imgur.com/f51nI1c.png

**Comment by gabizou** [comment]
Not sure why this is an issue on SpongeForge, sponge appears to be passing the valid information, but GP is incorrectly handling the event?

Also, please list the mod version in question and a list of steps to reproduce the fake player detection.

**Comment by mineblow** [comment]
i am also having this same issue with the skyfactory4 mod-pack version 4.10 
Cyclic-1.12.2-1.19.14
grief prevention-1.12.2-4.3.0.692
forge-1.12.2-14.23.5.2838
spongeforge-1.12.2-2838-7.1.7

when placing a block breaker from cyclic inside a claimed area it can not mine any blocks. outside of a claimed area it breaks the blocks. also seems that ae2 annihilation plane does not work inside a claim either

**Comment by clienthax** [comment]
Please retest on latest (You may need to replace the blocks in question so the owner information is set properly now)

**Comment by mineblow** [comment]
just retested this on latest version of spongeforge/GP its still attempting to break the block but not fully breaking it inside a claimed area. ( tested on a brand new server with fresh configs)
spongeforge-1.12.2-2838-7.1.8-RC3965
forge-1.12.2-14.23.5.2838
grief prevention-1.12.2-4.3.0.692

**Comment by clienthax** [comment]
> just retested this on latest version of spongeforge/GP its still attempting to break the block but not fully breaking it inside a claimed area. ( tested on a brand new server with fresh configs)
> spongeforge-1.12.2-2838-7.1.8-RC3965
> forge-1.12.2-14.23.5.2838
> grief prevention-1.12.2-4.3.0.692

Is the owner information set properly now?

**Comment by mineblow** [comment]
how would i tell that?

according to /sponge blockinfo im the owner of the block it shows the same info as above but with my name

**Comment by clienthax** [comment]
So is this now working as expected protection wise? (Check /gpdebug ?)

**Comment by mineblow** [comment]
no, its still not breaking/placing blocks

https://imgur.com/a/YtV6pWK
info on /gp debug and sponge blockinfo

**Comment by bloodmc** [comment]
GriefPrevention is no longer maintained. Update to GriefDefender and provide `/gddebug` or this issue will be closed.

See https://github.com/bloodmc/GriefDefender/wiki/GriefPrevention#sponge
