### ISSUE TITLE
NPCs are disappearing in the newest version of sponge (ver. 2)

### ISSUE THREAD

**Issue by kasdo** [SpongePowered/SpongeForge#2995]
Im opening new issue, becouse my old issue closed... Its not dublicate. That problem just with vision, NPC didnt gone, player just cant see NPCs. But this problem is other. My NPCs is gone, forever.
https://github.com/SpongePowered/SpongeForge/issues/2990

Hey guys! After updating my sponge from 2768 to 3924 and forge to 2838. Also I updated mod LagGoggless and plugins GriefPrevention I got new problem with NPCs.
From morning to evning my server lost more than 5 NPCs (from CustomNPCs). I didnt have this issue on version 2768. I already lost more than 15 npcs for 2 days. So Im going to downgrade sponge and forge. If you would fix that issue then let me know, please. Thank you.

**Comment by kasdo** [comment]
I downgrade SpongeForge to 2768 version and everything is fixed. My NPCs are not disappearing now. But I need new versions of Sponge. So please, try to fix that issue. Thanks.

**Comment by gabizou** [comment]
Going to need a simplified reduced setup to reproduce the disappearances of your NPCs. And next time, just wait for the original issue to be reopened. Even if an issue is closed, discussion can stil, happen.

**Comment by kasdo** [comment]
> Going to need a simplified reduced setup to reproduce the disappearances of your NPCs. And next time, just wait for the original issue to be reopened. Even if an issue is closed, discussion can stil, happen.

what do you mean about simplified reduce setup?

**Comment by dualspiral** [comment]
Try to get a setup where you have the smallest number of mods and plugins possible that still causes this behaviour, then tell us what mods and plugins you have, and how to cause your problem.

**Comment by kasdo** [comment]
> Try to get a setup where you have the smallest number of mods and plugins possible that still causes this behaviour, then tell us what mods and plugins you have, and how to cause your problem.

I already told what I have just changed on my server... I upgraded sponge, forge, laggoggless and griefprevention. 
But I deleted laggoggles and this issue isnt gone. I change GP to previous version and problem isnt gone too. So its can be just SpongeForge (or forge).

**Comment by LXGaming** [comment]
Have you tested on [SpongeForge 3928](https://repo.spongepowered.org/maven/org/spongepowered/spongeforge/1.12.2-2838-7.1.7-RC3928/spongeforge-1.12.2-2838-7.1.7-RC3928.jar) which includes a fix for entities disappearing which **MAY** solve your issue. (In your initial comment you said you tested 3924 which doesn't include the potential fix)?

**Comment by gabizou** [comment]
> I already told what I have just changed on my server...

We can't help you if you don't literally answer the specifics what we're asking. Mod versions, Forge versions, SpongeForge, What claims are set up, what permissions are set up, Does the issue actually require GP to be installed? Can it be reproduced with just SpongeForge, Forge, and CustomNPC's? If it can be reproduced with just those three, what are the steps to making an NPC and getting the issue to reproduce? Do I have to have the server online for x time? Do I have to leave and come back to chunks?

That's what I mean by a simplified reduced setup.

**Comment by kasdo** [comment]
> > I already told what I have just changed on my server...
> 
> We can't help you if you don't literally answer the specifics what we're asking. Mod versions, Forge versions, SpongeForge, What claims are set up, what permissions are set up, Does the issue actually require GP to be installed? Can it be reproduced with just SpongeForge, Forge, and CustomNPC's? If it can be reproduced with just those three, what are the steps to making an NPC and getting the issue to reproduce? Do I have to have the server online for x time? Do I have to leave and come back to chunks?
> 
> That's what I mean by a simplified reduced setup.

Sponge 3924
Forge 2838
U need just CustomNPCs, spongeforge and big world with too many npcs. I dont know when NPCs are gone... so I cant answer, sorry. I just know that this issue just with sponge or forge. I dont know when and how NPCs are gone.

**Comment by ImMorpheus** [comment]
> Sponge 3924
> Forge 2838

Please, try to reproduce the issue with 1.12.2-2838-7.1.7-RC3928. It introduces a fix for disappearing entities. See https://github.com/SpongePowered/SpongeForge/issues/2995#issuecomment-540830349

**Comment by ImMorpheus** [comment]
Closing until someone replies back that they can reproduce this with latest
