### ISSUE TITLE
First Aid Mod Overriding Data Manipulators?

### ISSUE THREAD

**Issue by TheFlash787** [SpongePowered/SpongeForge#2998]
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.1.7-RC3910
- Forge version: 1.12.2-14.23.5.2838
- Java version: Java 8
- Operating System: Ubuntu 18.04.3 LTS

- Plugins/Mods:
`Mods (105): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, Advanced Fishing, Advanced Hook Launchers, AlcatrazCore, Antique Atlas, Anvil Patch - Lawful, Aquaculture, Armor Underwear, AutoRegLib, BNBGamingLib, Battle Towers, Baubles, Better Combat Rebirth, Better Survival, Bloodmoon, Bountiful Baubles, Campfire Spit, Carrots Lib, Carry On, Comforts, CompatSkills, Coralreef, Corpse Complex, CraftTweaker JEI Support, CraftTweaker2, Craftable Chainmail, Craftable Horse Armour [CHA&S], CreativeCore, CreativeCoreDummy, Defiled Lands, Disenchanter, Doomlike Dungeons, Dynamic Surroundings, Dynamic Trees, Dynamic Trees for Traverse, DynamicSurroundingsCore, Enhanced Visuals, Familiar Fauna, First Aid, FoamFix, FoamFixCore, Food Expansion, Forge Endertech, Grappling hook mod, Ice and Fire, Infernal Mobs, It's the little things, ItemPhysic, IvToolkit, Just Enough Items, LLibrary, LagGoggles, Level Up! Reloaded, Lost Souls, Lycanites Mobs, Mo' Bends, No Tree Punching, OreLib Support Mod, Phosphor Lighting Engine, Potion Core, Potion Fingers, Quality Tools, Realistic Torches, Reborn Core, Reskillable, Rin's So Many Enchantments?, Roguelike Dungeons, Rough Tweaks, Ruins Mod, Sampling Performance Profiler, Scaling Health, Serene Seasons, Shadowfacts' Forgelin, Silent Lib, Simple Camp Fire, Sit, Spartan Fire, Spartan Shields, Spartan Weaponry, SpawnerControl, SpongeForge, SwingThroughGrass, Switch-Bow, TNTUtils, TNTUtils Core, The Lost Cities, Tool Belt, Tough As Nails, Traverse, Trinkets and Baubles, Trumpet Skeleton, TschippLib, Tumbleweed, Varied Commodities, Waystones, Wearable Backpacks, Wolf Armor and Storage, XP From Harvest, XP Tome, bacodifficulty`
`Plugins (25): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, CatClearLag, GriefPrevention, Holograms, HuskyUI, LuckPerms, MRAchievements, MRChat, MRChunkloading, MRCommands, MRConnectionBridge, MRPunishments, MRResourceWorld, MRRewards, MRShopMenu, MRTitles, MRUpdater, NoChat, Nucleus, Sledgehammer, WorldEdit, spark`

**Issue Description**
RLCraft contains **First Aid** which introduces body-part damaging and requires you to use bandages and other items to regenerate your health (instead of naturally). However when using `/heal` from Nucleus, the hearts seem to visually replenish but as soon as damage is taken, the player's health goes back to what it was before (with the damage taken). 

This was reported to @dualspiral but was recommended to report it to Sponge since the mod appears to be overriding the data manipulators. No errors are thrown when this takes place.

Thanks!

**Comment by dualspiral** [comment]
Thanks for doing this @TheFlash787.

For reference - [Nucleus' heal command simply offers the value of `Keys.MAX_HEALTH` to the `Keys.HEALTH` key](https://github.com/NucleusPowered/Nucleus/blob/8ca77910cc5fc326c34a339d6a7a139e57c77658/src/main/java/io/github/nucleuspowered/nucleus/modules/misc/commands/HealCommand.java#L26). I've not looked into FirstAid, but at a guess, I suspect that FirstAid is keeping its own health value and setting that, rather than using the standard fields to store it. I'm not sure if much could be done in this case, but I figured it was best to make it known here in case there was something we could do, hence why I suggested it be reported here.

All speculation though, of course - someone will need to go through it when time permits.

**Comment by TheFlash787** [comment]
Ugh. This mod also overrides the PVP setting in `server.properties` it seems, too.

**Comment by LXGaming** [comment]
> Ugh. This mod also overrides the PVP setting in `server.properties` it seems, too.

https://github.com/SpongePowered/SpongeCommon/commit/560c0c82ae42d63a1ecb304f409cccb0d8bd0a1a

> Unfortunately, server.properties PVP setting cannot be honored due to how configuration and booleans
work in them (cannot really specify "undefined"). The good news is you can still do a global setting via
global.conf.

If you want PVP disabled try setting `pvp-enabled` to `false` in your sponge `global.conf`

**Comment by TheFlash787** [comment]
I can confirm that disabling PVP via `global.conf` does indeed work. However I will close this issue because I have reported it on the mod's repository with extra information and issues that arose. Thank you!
