### ISSUE TITLE
Conflict with Monk Mod

### ISSUE THREAD

**Issue by craving-death** [SpongePowered/SpongeForge#3005]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2825-7.1.6
- Forge version: 1.12.2 - 2838
- Java version: 8
- Operating System:W10

- Plugins/Mods: 

PLUGINS: Broadcast, CatClearLag, Grief Prevention, HuskyCrates, LuckPerms, MMCReboot/Restrict, Nucleus, Total Economy

MODPACK: DIREWOLF 20 1.12.2 - 2.5.0

**Issue Description**
The monk mod allows players to progress through advancements, although players have reported that they do not gain "blocks broken" or "entities killed"

https://gist.github.com/craving-death/6deea9840b62884dbf68404b8871bcf0

https://github.com/SpongePowered/SpongeForge/issues/2380#issuecomment-515780215

**Comment by gabizou** [comment]
> spongeforge-1.12.2-2825-7.1.6

Retest with latest.

**Comment by craving-death** [comment]
it worcc thanks!

**Comment by Shybella** [comment]
Not working on 3928 for me. Anyone else having an issue? On DW20 2.5.0 pack too.

Sometimes it does work though, it's a chance, this also happened on earlier Sponge builds too in the original report.

**Comment by gabizou** [comment]
> Not working on 3928 for me. Anyone else having an issue? On DW20 2.5.0 pack too.

Going to need logs then.

**Comment by Shybella** [comment]
Not posting those logs publically anymore due to people coming on github pulling IPs and other sensitive information.

I sent you logs via PM but I can tell you no error in the logs from monk.
