### ISSUE TITLE
Config issue (when updating value config is overriden)

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#3006]
**I am currently running**

- SpongeForge version: 7.1.0-b2736425
- Forge version: forge-1.12.2-14.23.5.2768-universal
- Java version: 1.8
- Operating System: win 10 (lastest)

- Plugins/Mods:
Only my mod

**Issue Description**
PROBLEM FILE: https://gist.github.com/LambdaTheDev/loop 34d7abedf9f3e43a0b9749994d76f9ae
I have issue with config (Hocon, sharedroot = false). File describes everyting - i try to use function with correct UUID, but after that users accont if fully overriden and only value is classes=[] value

https://gist.github.com/LambdaTheDev/eef2d6ff397b4419e1431b8af374d669

**Comment by JBYoshi** [comment]
Try replacing:

```java
this.node.getNode("users", uuid, "classes").setValue(list);
```

with:

```java
this.node.getNode("users", uuid.toString(), "classes").setValue(list);
```

**Comment by ghost** [comment]
Thanks for help!
