### ISSUE TITLE
Entity movement bug

### ISSUE THREAD

**Issue by Pulverizer** [SpongePowered/SpongeForge#3007]
**I am currently running**

- SpongeForge version: stable-7 decompWorkspace
- Java version: 8
- Operating System: Windows 10

Plugins/Mods:
- Movecraft for Sponge in dev
- worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist

**Issue Description**
Entities not in the same chunk as the player cannot move or do not move smoothly.
Particularly noticeable with bats or items.

Items definitely remain where they spawned after blocks are destroyed by explosions until the player moves into the chunk.

Possibly started with the same version as #2937 .

I think these may be leftovers from #2906 ?

**Comment by phit** [comment]
you probably mean the entity activation https://docs.spongepowered.org/stable/en/server/management/performance-tweaks.html#entity-activation-range

**Comment by Pulverizer** [comment]
then you have it way too low by default.

**Comment by Pulverizer** [comment]
@phit You were correct it seems.

I would recommend the default be higher as it does not match vanilla and therefore can cause confusion.

**Comment by dualspiral** [comment]
> I would recommend the default be higher as it does not match vanilla and therefore can cause confusion.

Entity activation isn't a thing in vanilla.

I'm closing this as we do point people to changing that value where needed. It isn't a bug! The default is chosen to try to strike a balance along with performance.
