### ISSUE TITLE
Sponge crash [1.12.2, PIXELMON]

### ISSUE THREAD

**Issue by kasdo** [SpongePowered/SpongeForge#3013]
Hello everybody! Can someone help me with this crash?
https://hastebin.com/ihikudalel.rb
![image](https://user-images.githubusercontent.com/7419546/68859000-0049ac00-06ef-11ea-9d27-74c9435d70f2.png)

![image](https://user-images.githubusercontent.com/7419546/68859004-02ac0600-06ef-11ea-9d89-3af7bed2d649.png)

**Comment by kasdo** [comment]
https://hastebin.com/ewogociwuk.rb

**Comment by clienthax** [comment]
Log is gone.

**Comment by kasdo** [comment]
> Log is gone.

https://hastebin.com/otoxusudab.coffeescript

**Comment by clienthax** [comment]
Copied to site where it wont disappear https://gist.github.com/clienthax/2c986511c82ae1a740d5e80dffba8769

**Comment by clienthax** [comment]
Any idea on how this was caused?

**Comment by clienthax** [comment]
Closing due to lack of response
