### ISSUE TITLE
Squids do not spawn in a single stream of flowing down water like they do in vanilla once you add spongeforge

### ISSUE THREAD

**Issue by KillerJWB86** [SpongePowered/SpongeForge#3014]
**I am currently running**

- SpongeForge version: 1.12.2-2825-7.1.6
- Forge version: Tested on forge-1.12.2-14.23.5.2847-universal and forge-1.12.2-14.23.5.2825
- Java version: 1.8.0_221-b11
- Operating System: Win 10

- Plugins/Mods: spongeforge-1.12.2-2825-7.1.6 

**Issue Description** In a skyblock you can make a squid farm that looks like this https://prnt.sc/pxvl9p and it will spawn a squid about every 2 seconds. But as soon as you add spongeforge to the server you will be lucky to get 1 squid every 5 minutes.  I even lower the tick-rate-aquatic=400 to 50 and set the spawn-limit-aquatic=to 50

**Comment by Jirubizu** [comment]
Hey man having the exact same issue :/, I am trying to get them to spawn in a single water stream but it doesnt do it

**Comment by KillerJWB86** [comment]
Still nothing one month later?

**Comment by clienthax** [comment]
> Still nothing one month later?

Will take a look, I have an idea what it could be

**Comment by clienthax** [comment]
Ok so with the default settings it will indeed slow the spawn to a crawl with this kind of setup.
However if you set tick-rate-aquatic=1 it restores the vanilla behavior

Squid spawn between 63 and 46
World used: https://www.youtube.com/watch?v=tvOsHgkvxdg

**Comment by gabizou** [comment]
Please note that for this to properly take effect, users need to either wipe their configs or change their existing config values for `tick-rate-aquatic` to `1`.
