### ISSUE TITLE
Immersive Engineering Item Silo tick loop crash

### ISSUE THREAD

**Issue by ken1882** [SpongePowered/SpongeForge#3018]
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.1.7-RC3950
- Forge version: 1.12.2-forge1.12.2-14.23.5.2847
- Java version: 1.8.0_232
- Operating System: CentOS 8

- Plugins:
Minecraft
Minecraft Coder Pack
SpongeAPI
Sponge
CatClearLag
FoxCore-Sponge
FoxGuard-Sponge
LangSwitch
LuckPerms
Mega Menus
Nucleus
Total Economy
UltimateChat
VillagerShops
WorldEdit

- Mods:
Minecraft
Minecraft Coder Pack
Forge Mod Loader
Minecraft Forge
SpongeAPI
Sponge
A Block of Charcoal
AE2 Stuff
Advanced Fishing
Advanced Hook Launchers
Advanced Solar Panels
AlcatrazCore
Anvil Patch - Lawful
Applied Energistics 2
Aquaculture
Astral Sorcery
Atum 2
AutoRegLib
BD Lib
Battle Towers
Baubles
Better Combat Rebirth
Better Survival
BiblioCraft
Blockcraftery
Bloodmoon
Bookshelf
Botania
Bountiful Baubles
BuildCraft
BuildCraft Builders
BuildCraft Compat
BuildCraft Energy
BuildCraft Factory
BuildCraft Lib
BuildCraft Robotics
BuildCraft Silicon
BuildCraft Transport
Building Gadgets
Carry On
Chisel
Chunk Pregenerator
CoFH Core
CoFH World
CodeChicken Lib
Comforts
CommonCapabilities
CompatSkills
Coralreef
Corpse Complex
CraftTweaker JEI Support
CraftTweaker2
Craftable Chainmail
Craftable Horse Armour [CHA&S]
CreativeCore
CreativeCoreDummy
Cyclops Core
Dark Utilities
DeathCounter
Defiled Lands
Disenchanter
Doomlike Dungeons
Elevator Mod
Ender IO
Ender IO Applied Energistics Conduits
Ender IO Base
Ender IO Conduits
Ender IO Integration with Forestry
Ender IO Integration with Tinkers' Construct
Ender IO Integration with Tinkers' Construct
Ender IO Machines
Ender IO Open Computers Conduits
Ender IO Powertools
Ender IO Refined Storage Conduits
EnderCore
Extra Utilities 2
Familiar Fauna
Fancy Fluid Storage
FoamFix
FoamFixCore
Food Expansion
Forestry
Forge Endertech
Forge Microblocks
Forge Multipart CBE
Friendly Fire
Future MC
GasConduits
Global GameRules
Grappling hook mod
Gravestone Mod
Guide-API
Hunting Dimension
Ice and Fire
Immersive Engineering
Immersive Railroading
In-Game wiki Mod
InGameConfigManager
Industrial Foregoing
IndustrialCraft 2
Infernal Mobs
Integrated Dynamics
Integrated Tunnels
IntegratedDynamics-Compat
IntegratedTunnels-Compat
Integration Foregoing
Inventory Tweaks
Iron Backpacks
Iron Chest
ItemPhysic
IvToolkit
Just Enough Items
LLibrary
Level Up! Reloaded
Loot Table Tweaker
Lost Souls
Lycanites Mobs
MachineMuse's Modular Powersuits
MagicBees
Mantle
Mekanism
Minecraft Multipart Plugin
Mo' Villages
Modern Warfare 2.0 Contagion
Modular ForceField System
Modular Routers
Mystical Lib
No Damage Immunity (NoDamI)
No Tree Punching
Not Enough Cats
NuclearCraft
Numina
OpenComputers
OpenComputers (Core)
Pam's HarvestCraft
Phosphor Lighting Engine
Placebo
Player Plates
Potion Core
Potion Fingers
Potion-Craft
Progressive Bosses
Quality Tools
Railcraft
RandomPatches
Recurrent Complex
Redstone Flux
Reskillable
Rex's Additional Structures
Rin's So Many Enchantments?
Roguelike Dungeons
Ruins Mod
Scaling Health
Serene Seasons
Shadowfacts' Forgelin
Silent Lib
Simple Camp Fire
Sit
Slide'em All!
Some Like It Dry
Spartan Fire
Spartan Shields
Spartan Weaponry
SpawnerControl
SpongeForge
Stacksize Mod
SwingThroughGrass
Switch-Bow
TNTUtils
TNTUtils Core
Tesla Core Lib
Tesla Core Lib Registries
Thaumcraft
Thaumic Energistics
The Betweenlands
The Lost Cities
The Twilight Forest
Thermal Dynamics
Thermal Expansion
Thermal Foundation
Tinkers' Construct
Tool Belt
Tough As Nails
Track API
Traverse
Tree Chopper
Trinkets and Baubles
Trumpet Skeleton
Tumbleweed
Unifier
UniversalModCore
VanillaFix
Varied Commodities
Villager Trade Tables
Waila
Waystones
WirelessRedstone-CBE
Wither Skeleton Tweaks
Wolf Armor and Storage
XP From Harvest
XPBook
Bacodifficulty

**Issue Description**
It seems if there're items in the itemduct (item transport pipe from ThermalExpansion) and connected to the silo, when the chunk loaded and unload after a while, it will cause the crash.
The crash in this case is after I logged out where I was near the silos

Server Log: https://gist.github.com/ken1882/d4f0e7a5486263342a06d06c05787439
Crash Log: https://gist.github.com/ken1882/43f1ec4bdd183a4cd60856e564697616

**Comment by clienthax** [comment]
Has this been raised to immersiveengineering / cofh / thermaldynamics ?

**Comment by ken1882** [comment]
No, since this issue didn't occur when I play with the same mods in single-player, neither after I disabled SpongeForge for a few hours in order to test. So should I report this to cofh's repo too?

**Comment by gabizou** [comment]
Can you provide a small map of just the three with a setup to reproduce the issue? Need it to be able to debug further.

**Comment by ken1882** [comment]
Yes I'll see if I could reproduce it with minimal sets, it may take a while since the crash strangely will not happen immediately

**Comment by clienthax** [comment]
@ken1882 any update?

**Comment by ken1882** [comment]
Sorry for the late reply, until recently I got time back to play minecraft and tested in my single player world. After update both to latest version and I can't reproduce the bug so I'll close this issue now
