### ISSUE TITLE
Duplicate bug

### ISSUE THREAD

**Issue by mem0rz** [SpongePowered/SpongeForge#3021]
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.1.7 StableRecommendedForge 2838
- SpongeVanilla version: 
- Java version: java8 211
- Operating System:debian 10
 shift+left click can duplicate things
I know sponge fix this bug.(https://github.com/SpongePowered/SpongeCommon/pull/2414)
2 2 2 
2 2 2
48 2 2 to 48
But it's still exist in tools+material
look this pic and video(with this mod https://github.com/Tiviacz1337/Travellers-Backpack when I in single mode have no bug,when i join a server which has sponge i can do this )
![QQ截图20191123235506](https://user-images.githubusercontent.com/14276116/69481535-1ffa7600-0e4d-11ea-9873-ab7900fc88d5.png)
![QQ截图20191123235515](https://user-images.githubusercontent.com/14276116/69481536-24269380-0e4d-11ea-9cef-c64520fa2666.png)
[record-video-sponge-travelbackpacksbug.zip](https://github.com/SpongePowered/SpongeCommon/files/3882639/record-video-sponge-travelbackpacksbug.zip)

**Comment by clienthax** [comment]
Confirmed reproduce with recipe from Crayfishs Furniture mod as above using vanilla crafting bench.

Seems its returning the axe with the durability-1 to the crafting grid.
And returns the original axe to the player inventory, on both shift + standard crafting.

**Comment by clienthax** [comment]
https://github.com/MrCrayfish/MrCrayfishFurnitureMod/issues/425

**Comment by clienthax** [comment]
Bug in Furniture mod, occurs on base forge server too.
