### ISSUE TITLE
Adding SpongeForge crashes DonutCraft server

### ISSUE THREAD

**Issue by SlyScroll** [SpongePowered/SpongeForge#3024]
**I am currently running**
- SpongeForge version: 7.1.7
- Forge version: 2847 (Cause 1.12.2)
- Java version: Dedicated server so not sure?
- Operating System: Dedicated server so once again no idea...

- Plugins/Mods: 
Cant run the commands recommended because I can't run the server with spongeforge so I will link to the modpack page which has all the mods contained within.
https://atlauncher.com/pack/DonutCraft

**Issue Description**
Just bought a dedicated server to run the DonutCraft modpack and loaded it up to generate the all the files and such and realised I wanted a plugin or two just to make managing certain server aspects easier and from experience i've found having sponge installed generally can improve performance too.
I installed spongeforge into the mods folder of my dedicated server following the instructions given by NodeCraft (server host I use) and first found that it doesn't get along with FoamFix so i disabled the two settings within it that all the forum posts suggested to and when I tried to run the server, I came across a different issue and i'm at a loss as unfortunately im really no good at reading code and the NodeCraft guys just pointed me to this, I thought i'd ask here where people know exactly what they are doing.

I can tell for sure that the issue only arises once SpongeForge is installed as the server will run fine without but crash at what looks like the same point each time. For all I know, it may be a simple mod imcompatability but I wanted to ask here just to make sure that it wasnt anything seriously horrible.

P.S. I did check through all issues (both open and closed) and the website forum for anything related to donutcraft and nothing came up.

FULL Server Log and generated crash log
https://gist.github.com/SlyScroll/a440314d7a2bead454b868caa37eae76

**Comment by gabizou** [comment]
Linking the [source of the issue](https://github.com/EwyBoy/Bibliotheca/blob/2eed18c072532e64ff2fc7c0628c28f39b0cb777/src/main/java/com/ewyboy/bibliotheca/common/loaders/TileEntityLoader.java#L47-L51). I've written a workaround, but the mod author is doing some **interesting** registration that doesn't quite make sense. Since the `toString()` result is instance based, it's not a valid String id to signify a `TileEntity` being registered. That being said, this will no longer crash on startup.
