### ISSUE TITLE
Problems with PVP

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#3028]
**I am currently running**
- SpongeForge version: 7.1.7
- Forge version: 2838
- Java version: Java 8
- Operating System: Ubuntu

- Plugins/Mods:
`spongeforge`

**Issue Description**
pvp in server.properties is false
![image](https://user-images.githubusercontent.com/24543050/69901269-5179c100-13ba-11ea-9898-cd93ac163f1f.png)
pvp-enabled in sponge's global.conf is true
![image](https://user-images.githubusercontent.com/24543050/69901136-b46a5880-13b8-11ea-9252-583e9a131f9a.png)
I did not set `pvp-enabled` on version 7.1.6 (default: true), and then updated 7.1.7 the player suddenly can pvp, my server.properties pvp is false . why can players still pvp  :((
the current way to turn off pvp is to set pvp-enabled to false

**Comment by LXGaming** [comment]
This is intentional as per this commit message: https://github.com/SpongePowered/SpongeCommon/commit/560c0c82ae42d63a1ecb304f409cccb0d8bd0a1a

> Unfortunately, server.properties PVP setting cannot be honored due to how configuration and booleans work in them (cannot really specify "undefined"). The good news is you can still do a global setting via global.conf.

**Comment by Zidane** [comment]
@LXGaming is correct.
