### ISSUE TITLE
Mystcraft incompatibility?

### ISSUE THREAD

**Issue by xJon** [SpongePowered/SpongeForge#3029]
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.1.8-RC3961
- Forge version: 1.12.2-14.23.5.2847
- Java version: 1.8.0_222
- Operating System: Windows 10

- Plugins/Mods: no plugins, see crash report for mods: https://pastebin.com/Zs3TBaGa

**Issue Description**
Trying to run SpongeForge with Mystcraft results in a crash.
This was discussed before on your forums: https://forums.spongepowered.org/t/server-crashes-with-sponge-on-world-load/34243
And reported to Mystcraft: https://github.com/XCompWiz/Mystcraft-Issues/issues/379
Is there anything that could be done from your perspective?
Thank you!

**Comment by phit** [comment]
https://github.com/SpongePowered/SpongeForge/issues/2704#issuecomment-498812177

**Comment by xJon** [comment]
I see.
Is this an issue only caused due to Mystcraft's profiling?

**Comment by gabizou** [comment]
Yes and no, doing things asynchronously with worlds is all around a lot of replumbing that sponge would have to work with, and it's overall something we're not willing to do for 1.12.
