### ISSUE TITLE
SpongeForge keeps saying its unsigned when I try to load up my server.

### ISSUE THREAD

**Issue by IMerkedJFK** [SpongePowered/SpongeForge#3032]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.1.7 
- Forge version: forge-1.12.2-14.23.5.2838-universal
- Java version: java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)
- Operating System: Windows 10

- Plugins/Mods: spongeforge-1.12.2-2838-7.1.7  ,  Pixelmon-1.12.2-7.1.1-universal  ,  Nucleus-1.12.2-S7.1-MC1.12.2-plugin

**Issue Description**
Every time _I try to run my server it says the coremod SpongeCoremod (org.spongepowered.mod.SpongeCoremod) is not signed!_ then the server forces itself to shut down. 

 <script src="https://gist.github.com/IMerkedJFK/0a7e25d0b272c7ba2d7f235390f0f05f.js"></script>

[0a7e25d0b272c7ba2d7f235390f0f05f-93103dd530d70a19d91c71dfc857cfb9b34c646d.zip](https://github.com/SpongePowered/SpongeForge/files/3935883/0a7e25d0b272c7ba2d7f235390f0f05f-93103dd530d70a19d91c71dfc857cfb9b34c646d.zip)

**Comment by IMerkedJFK** [comment]
someone help me out please I just want to get my server finally working.

**Comment by clienthax** [comment]
[23:42:41] [Server thread/WARN] [net.minecraft.server.dedicated.DedicatedServer]: **** FAILED TO BIND TO PORT!
[23:42:41] [Server thread/WARN] [net.minecraft.server.dedicated.DedicatedServer]: The exception was: java.net.BindException: Cannot assign requested address: bind
[23:42:41] [Server thread/WARN] [net.minecraft.server.dedicated.DedicatedServer]: Perhaps a server is already running on that port?

Nothing todo with the issue you raised, you already have a server on that port, or your settings are wrong.

**Comment by IMerkedJFK** [comment]
> [23:42:41] [Server thread/WARN] [net.minecraft.server.dedicated.DedicatedServer]: **** FAILED TO BIND TO PORT!
> [23:42:41] [Server thread/WARN] [net.minecraft.server.dedicated.DedicatedServer]: The exception was: java.net.BindException: Cannot assign requested address: bind
> [23:42:41] [Server thread/WARN] [net.minecraft.server.dedicated.DedicatedServer]: Perhaps a server is already running on that port?
> 
> Nothing todo with the issue you raised, you already have a server on that port, or your settings are wrong.

how would I check whats wrong in my settings and how do I remove the server already running on that port?

**Comment by clienthax** [comment]
Ask in the discord, however if you are running this locally it seems you have an IP address defined in the server properties which is likely the issue
