### ISSUE TITLE
Could not pass the event DamageEntityEvent$Impl to an Event Listener! 

### ISSUE THREAD

**Issue by Keaton1188** [SpongePowered/SpongeForge#3033]
**I am currently running**
 
- SpongeForge version: spongeforge-1.12.2-2838-7.1.8-RC3963.jar
- Forge version: 14.23.5.2847
- Java version: : Java openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-b12)
- Operating System: CentOS Linux release 7.2.1511

- Plugins/Mods: Crackpack 3

**Issue Description**
Hi there, we are getting massive amounts of spam in our console/server logs about "DamageEntityEvent$Impl to an Event Listener!" see pastebin for more on this. 

 https://pastebin.com/hpT3Nq6n

**Comment by dualspiral** [comment]
`com.arckenver.nations.listener.PvpListener.onEntityDamagedByPlayer`

Not a problem with Sponge, it's a problem with the Nations plugin. I don't think it's maintained any more, so probably best to find an alternative.
