### ISSUE TITLE
[1.12.2] Hammer Core / Sponge Forge: No Fall Damage in any dimesion other than overworld.

### ISSUE THREAD

**Issue by thakyZ** [SpongePowered/SpongeForge#3036]
# I am currently running
**Minecraft Version:** `1.12.2`   
**Forge Version:** `14.23.5.2837`   
**OS:** `Windows 10` / `Ubuntu Server 18.04`   
**Java Version:** `1.8.0_231`   
**Hammer Core Version:** `2.0.5.7`   
**Sponge Forge Version:** `1.12.2 2838 7.1.8 RC3963`   

# Issue Description
There is a bug while having both Hammer Core and Sponge Forge installed on the server that disables fall damage in dimensions like the nether or end or any other modded dimension, but still works in the overworld.   
I have tested this extensively and made sure that it was reproducible with only hammer core and sponge forge installed on the server and just hammer core on the client.

Client and server logs (expires in 1 year)   
[https://paste.ee/p/ubVDh](https://paste.ee/p/ubVDh)

**Comment by Tkdmaster** [comment]
Can confirm the issue with supplied versions. Also tested with Spongeforge 7.1.6, 7.1.7, along with 7.1.8 rc 3963 for 1.12.2. Multiple hammercore versions also tested, all with same result of no fall damage in nether when used with spongeforge.

**Comment by clienthax** [comment]
I have experienced this but im not running hammercore, (The 1.12.2 pack)

**Comment by clienthax** [comment]
EntityLivingBase.fall is called with damage multipler of 1
This in turn calls ForgeHooks.onLivingFall, which posts an LivingFallEvent

Hammercore Handler for this event
https://gitlab.com/DragonForge/HammerLib/blob/1.12.2/src/main/java/com/zeitheron/hammercore/world/WorldGenHelper.java#L306
hc_falldamagemult default value is 1
as this doesn't exist on the non overworld gamerules for whatever reason GameRules.getFloat in hammercore throws and returns 0 for the multiplier

This is returning a damage multiplier of 0, which breaks the fall logic as it multiplies the damage by 0, causing 0 damage

it seems HC only injects its gamerules for the overworld here,
https://gitlab.com/DragonForge/HammerLib/blob/1.12.2/src/main/java/com/zeitheron/hammercore/api/GameRules.java#L55

It should either be injecting for each world that is loaded, or even better, returning correct default values when the gamerule is not present on the world.

**Comment by clienthax** [comment]
https://gitlab.com/DragonForge/HammerLib/issues/116

**Comment by clienthax** [comment]
Looking into further..,
Vanilla / forge use one set of gamerules over all worlds, whereas we change this to be one set of gamerules per each world, there is not much we can do for compatibility here as this is just how sponge works.

Mods should not expect gamerules to exist, and they should gracefully handle them being missing.

I would suggest that HC changes how they handle their rules, to not be added by default, and to gracefully return their default values when they are missing from the world instead.

**Comment by clienthax** [comment]
This should be resolved for current versions once SF gets bumped.

**Comment by clienthax** [comment]
This is fixed now, both in hammer core and in sponge.
