### ISSUE TITLE
Botania Mana Lens: Bore not working correctly

### ISSUE THREAD

**Issue by bigenergy** [SpongePowered/SpongeForge#3038]
https://github.com/bloodmc/GriefDefender/issues/83

**Comment by clienthax** [comment]
Why has this been raised here?

**Comment by bigenergy** [comment]
> Why has this been raised here?

Because it's a bug SpongeForge.
![image](https://user-images.githubusercontent.com/17977139/71327251-4b898280-2517-11ea-87a6-497e73dce543.png)

**Comment by clienthax** [comment]
That doesn't really tell us what exactly the bug is, What are you expecting to happen here and how do we reproduce it?

**Comment by gabizou** [comment]
Please fill out the issue format. Just pointing to another issue doesn't help us investigate what the issue is. If you do fill out the format, edit your original comment and we'll re-open the ticket.
