### ISSUE TITLE
IllegalStateException: Block Change Proxy corruption! Attempted to pop a proxy that was not on the stack. 

### ISSUE THREAD

**Issue by kristi71111** [SpongePowered/SpongeForge#3040]
**I am currently running**
- SpongeForge version: 1.12.2-2838-7.1.8-RC3965
- Forge version: 14.23.5.2838
- Java version: 1.8.0_212/64-bit (Oracle Corporation)
- Operating System: CentOS 7 (4.9.178-xxxx-std-ipv6-64/amd64)

- Plugins/Mods:
**Mods (160):** Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AI Improvements, Aether Continuation, Aether Legacy, Akashic Tome, AppleCore, AppleSkin, Aquaculture, Aroma1997's Dimensional World, Aroma1997Core, Atum 2, AutoRegLib, Baubles, BiblioCraft, Bigger Packets, please !, Biome Bundle, Bloodmoon, Bonsai Trees, Bountiful, Building Gadgets, Cavern II, Chameleon, Chance Cubes, Charm, Chest Transporter, ChickenChunks, Chisel, Clumps, CodeChicken Lib, Colossal Chests, Comforts, Cooking for Blockheads, Corail Tombstone, CosmeticArmorReworked, CraftTweaker JEI Support, CraftTweaker2, Creeper Confetti, Cucumber Library, Customized Dungeon Loot, Cyclic, Cyclops Core, Dimensional Doors, Disenchanter, Doggy Talents, Doomlike Dungeons, DungeonTactics, EZStorage 2, Electroblob's Wizardry, Embers Rekindled, Embersified, Engineer's Workshop Reborn, Extra Alchemy, Extra Utilities 2, FTB Library, FTB Money, FTB Quests, FTB Utilities, FastFurnace, FastWorkbench, FoamFix, FoamFixCore, Forge Endertech, GottschCore, Heroic Armory, Ice and Fire, Improved Backpacks, Infernal Mobs, Inventory Pets, Iron Backpacks, Item Filters, IvToolkit, Jack-O'-Launcher, Just Enough Items, LLibrary, Land Manager, Let's Encrypt Craft, Level Up! Reloaded, LibraryEx, LimeLib, Living Enchantment, Login Shield, Lost Aether Content, LunatriusCore, Mega Loot, Minerva Library, Mowzie's Mobs, Mystical Agriculture, Mystical Mechanics, Nature's Compass, NetherEx, NetherPortalFix, NoMoreRecipeConflict, Nomadic Tents, OTG Core, Open Terrain Generator, OpenBlocks, OpenModsLib, OpenModsLib Core, Ordinary Coins, OreExcavation, OreLib Support Mod, Pam's HarvestCraft, Patchouli, Phosphor Lighting Engine, PiTweaks, Portable Crafting, Potion Core, Progressive Bosses, Project: Vibrant Journeys, Pyramid Plunder, Quality Tools, Quark, Quark Oddities, Random Loot Mod, Random Things, RandomPatches, RandomTweaks, Reborn Core, Recurrent Complex, Reliquary, Roguelike Dungeons, Rope Bridge, Rough Tweaks, Rustic, Sampling Performance Profiler, Scaling Health, Shadowfacts' Forgelin, Sign Post, Silent Lib, Simple Storage Network, Skewers, Spartan Shields, Spawn Temple, Spice of Life: Carrot Edition, SpongeForge, Stackie, Storage Drawers, Straw Golem, Stuff A Sock In It, Subterranean Switcheroo, SwingThroughGrass, TerraCart Reloaded, The Beneath, The Betweenlands, The Eight Fabled Blades, The Twilight Forest, Totemic, Tropicraft, Unique Crops, V-Tweaks, Vanilla Tweaks, VanillaFix, ViesCraft, Waystones, bacodifficulty
**Plugins (35):** Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, ActiveTime, AsciiEmotes, BacoMaster, BaconTowny, Be_quiet, BetterChunkLoader, BungeeTabListPlus-SpongeBridge, CatClearLag, CommandUtils, DailyRewards, EasyTexts, EconomyLite, Enjin Minecraft Plugin, HuskyUI, Lottery, LuckPerms, MMCRestrict, Market, NuVotifier, Nucleus, PlaceholderAPI, Plan, ProjectBorders, ProjectCore, SeriousVote, Sledgehammer, Unity, VoteParty, WelcomeRewards, WorldEdit, spark

**Issue Description**
Upon updating to 1.12.2-2838-7.1.8-RC3965 from 1.12.2-2838-7.1.8-RC3963 the console throws errors when certain blocks are being placed for example trophies from openblocks.[Link to errors](https://pastebin.com/tqHSxQca).

**Comment by clienthax** [comment]
https://github.com/SpongePowered/SpongeCommon/commit/9fd6f90687fa71e3839a0bb921c80994a20e6a1d seems to of caused this

**Comment by clienthax** [comment]
Seems to of been exposed by https://github.com/SpongePowered/SpongeCommon/commit/9fd6f90687fa71e3839a0bb921c80994a20e6a1d

**Comment by clienthax** [comment]
Full log of single block placement https://gist.github.com/clienthax/644b6ad589f299a0ec9a18a1e17a8d91

**Comment by bloodmc** [comment]
This was fixed in commit https://github.com/SpongePowered/SpongeCommon/commit/cae8cbc6e77b5641cc26e601736bfe27743b4c21
