### ISSUE TITLE
Sponge and Decocraft conflict

### ISSUE THREAD

**Issue by Lunyyx** [SpongePowered/SpongeForge#3044]
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.1.8-RC3968
- Forge version: 14.23.5.2838
- Java version: Java 8
- Operating System: Ubuntu 18.04

- Plugins/Mods:
Chisel
Chisel&Bits
CTM-MC
Decocraft
ForgeEssentials
Furniture Mod
PTRLib
SkinsRestorer
WorldEdit (MOD)

Hello, i have a problem with Sponge & Decocraft, I know it because after report an issue here, i've seen in the support that the problem is by Sponge and not Decocraft:
When I try to place certain furnitures, there are automatically replaced by a small creeper.
I've tried to remove Sponge, and the error has disapeared.
I haven't any crash or console details, so if you need any additionnals informations, just tell me.
(Sorry for my bad english)

Thanks for advance

**Comment by clienthax** [comment]
Confirmed, placing the drum set items changes to a baby creeper 👀

**Comment by Lunyyx** [comment]
> Confirmed, placing the drum set items changes to a baby creeper

That's it, and not only the drum, and that's the problem

**Comment by dualspiral** [comment]
I just had an exchange with someone on the Discord channel about "transforming entities", and it sounded eerily similar to this issue.

> Hello, I am using sponge RC3969 together with the Chest transporter mod, it allows to transport the spawner mob, but when placing them they become pig spawners, the entity that was previously was not preserved.
> RC3964 works
> RC3965 [does] not work

That points to https://github.com/SpongePowered/SpongeCommon/commit/9fd6f90687fa71e3839a0bb921c80994a20e6a1d

**Comment by yaroslav4167** [comment]
RC3965 probably causes problems with [OpenBlocks](https://github.com/OpenMods/OpenBlocks/issues/993), and many other modifications.
