### ISSUE TITLE
Forestry and Sponge dupe bug

### ISSUE THREAD

**Issue by focamacho** [SpongePowered/SpongeForge#3046]
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.1.8-RC3968
- Forge version: 1.12.2 - 14.23.5.2847
- Java version: 1.8.0_232
- Operating System: Ubuntu

- Plugins/Mods:
Plugins (4): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge
Mods (8): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, Forestry, SpongeForge

**Issue Description**
1. Open and drop a Forestry backpack at the same time
2. Collect the items from the GUI
3. Collect the bag from the ground
4. Infinite items

Video: https://www.youtube.com/watch?v=EYNgstnaW5Y

**Comment by yaroslav4167** [comment]
Maybe [this](https://ore.spongepowered.org/Semenkovsky_Ivan/DupeFixer) plugin will help you.

**Comment by clienthax** [comment]
Can't reproduce,

AHK
```
j::
MouseClick, Right
Send, q
return
```

**Comment by bloodmc** [comment]
Reopen if this occurs with SF 3970+
