### ISSUE TITLE
Errors with itemStack.getType() and Prism

### ISSUE THREAD

**Issue by Sir-Will** [SpongePowered/SpongeForge#3047]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.1.8-RC3968.jar
- Forge version: forge-1.12.2-14.23.5.2846-universal

**Issue Description**
I updated from RC3962 to RC3968 and started to get the following errors with the Prism plugin and item duplication:
https://pastebin.com/raw/NtkpJLYD

Line in the error: https://github.com/prism/Prism/blob/master/src/main/java/com/helion3/prism/api/records/PrismRecord.java#L303

**Comment by dualspiral** [comment]
Can you try 3970? I suspect that may fix this issue.

**Comment by clienthax** [comment]
Not seeing this issue on my own server with 3970, reopen if still an issue after updating.

**Comment by Sir-Will** [comment]
The error still shows up with 3970.
