### ISSUE TITLE
Server thread is blocked

### ISSUE THREAD

**Issue by kasdo** [SpongePowered/SpongeForge#3049]
Hey guys! My server have been crashing and I dont know what I have to do, can someone help me? Maybe its sponge problem??
Sponge: 1.12.2-2838-7.1.8

![image](https://user-images.githubusercontent.com/7419546/71780736-e0d44e80-2fce-11ea-8315-8d70b7826b8e.png)

![image](https://user-images.githubusercontent.com/7419546/71780705-994dc280-2fce-11ea-8259-3cbbcd8c3fa5.png)

**Comment by clienthax** [comment]
I ran into this the other day, not sure on how to reproduce it however

**Comment by dualspiral** [comment]
Logs and/or text, rather than screenshots, would be helpful. We might be able to spot something. What you've posted isn't really telling us too much, it would be much easier to remap if we had text...

**Comment by kasdo** [comment]
> Logs and/or text, rather than screenshots, would be helpful. We might be able to spot something. What you've posted isn't really telling us too much, it would be much easier to remap if we had text...

[Log when crashed](https://drive.google.com/open?id=1GnghofTQj-oCKErxHGGddUSZ1GmdNitQ)

**Comment by kasdo** [comment]
Should I show something else?

**Comment by dualspiral** [comment]
Nothing obvious in that log. How often does it happen?

**Comment by kasdo** [comment]
> Nothing obvious in that log. How often does it happen?

1-3 times per day

**Comment by clienthax** [comment]
This should be fixed in the latest build.
