### ISSUE TITLE
Dimension issue - Internal Server Error

### ISSUE THREAD

**Issue by Keaton1188** [SpongePowered/SpongeForge#3051]
**I am currently running** 

- SpongeForge version: 1.12.2-2838-7.1.9-RC3977
- Forge version: 14.23.5.2847
- Java version: 1.8.0_222/64-bit (Oracle Corporation)
- Operating System: Linux (3.14.32-xxxx-grs-ipv6-64/amd64)

- Plugins/Mods: Crackpack 3

**Issue Description** Hi there, we are having an issue where if a players jumps into a portal (Lets say Benethe) then they will get kicked from the server with "Internal Server Error" and this can be seen in the pastebin, now I tested going to the DIM using the command /world teleport and it got me there so I'm wondering if you know whats going on??

 https://pastebin.com/ffFR6VXK

**Comment by Zidane** [comment]
```java
Caused by: java.lang.NoSuchFieldError: dimension
    at net.minecraft.entity.player.EntityPlayerMP.changeDimension(EntityPlayerMP.java:6803) ~[oq.class:?]
    at com.lothrazar.dimstack.transit.ActiveTransit.teleportInternal(ActiveTransit.java:73) ~[ActiveTransit.class:?]
```

Mod issue or you installed a deobfuscated build of the mod, this field gets obfuscated to:

public net.minecraft.entity.Entity field_71093_bK # dimension

**Comment by Zidane** [comment]
Looking more on this, did you install a deobfuscated build of SpongeForge? What other mods do you have installed that may touch changeDimension? Some mod is not using obfuscated names which screams not using an obfuscated mod jar.

**Comment by Keaton1188** [comment]
To be honest with you, I don't know what a "deobfuscated" build of sponge is.. lol 

I just have the second to latest version "1.12.2-2838-7.1.9-RC3977 " 

And no other mods I believe? Its just the Crackpack 3 modlist

**Comment by dualspiral** [comment]
Does it work okay on the recommended build, 7.1.8?

**Comment by Keaton1188** [comment]
I'll give it a test now.

**Comment by Keaton1188** [comment]
@dualspiral Works fine with the Recommended Build.

**Comment by gabizou** [comment]
> To be honest with you, I don't know what a "deobfuscated" build of sponge is.. lol

For your own edification, a "deobf" build is for running sponge in a development environment for other developers. 
<img width="1352" alt="Screen Shot 2020-01-05 at 1 34 57 PM" src="https://user-images.githubusercontent.com/1203877/71786459-54229400-2fc0-11ea-8afa-b7f206b5a03d.png">

**Comment by dualspiral** [comment]
https://github.com/SpongePowered/SpongeForge/blob/stable-7/src/main/java/org/spongepowered/mod/mixin/core/entity/player/EntityPlayerMPMixin_Forge.java#L78

It's our overwrite, `this.dimension` is shadow defined in a supermixin and not being reobfuscated.

See also 

* https://github.com/SpongePowered/SpongeCommon/issues/2457#issuecomment-570565129
* #3052

**Comment by Keaton1188** [comment]
> > To be honest with you, I don't know what a "deobfuscated" build of sponge is.. lol
> 
> For your own edification, a "deobf" build is for running sponge in a development environment for other developers.
> <img alt="Screen Shot 2020-01-05 at 1 34 57 PM" width="1352" src="https://user-images.githubusercontent.com/1203877/71786459-54229400-2fc0-11ea-8afa-b7f206b5a03d.png">

Ah ok, thankyou

**Comment by Keaton1188** [comment]
> https://github.com/SpongePowered/SpongeForge/blob/stable-7/src/main/java/org/spongepowered/mod/mixin/core/entity/player/EntityPlayerMPMixin_Forge.java#L78
> 
> It's our overwrite, `this.dimension` is shadow defined in a supermixin and not being reobfuscated.
> 
> See also
> 
> * [SpongePowered/SpongeCommon#2457 (comment)](https://github.com/SpongePowered/SpongeCommon/issues/2457#issuecomment-570565129)
> * #3052

Ah ok, I'll stick to the recommended build for now then

**Comment by dualspiral** [comment]
This is now correctly obfuscated in the SF 3980 and should no longer be an issue.
