### ISSUE TITLE
java.lang.NoSuchFieldError: rand

### ISSUE THREAD

**Issue by Shybella** [SpongePowered/SpongeForge#3052]
**I am currently running**

- SpongeForge version: 3977
- Forge version: 2468
- Java version: 1.8
- Operating System: Windows

https://pastebin.com/raw/deVC3VTQ
RLCraft 2.8.1

Can provide logs and any other information over PM.

**Comment by dualspiral** [comment]
Related to https://github.com/SpongePowered/SpongeForge/issues/3051

Can you please confirm this works on RB 7.1.8?

**Comment by dualspiral** [comment]
https://github.com/SpongePowered/SpongeForge/blob/stable-7/src/main/java/org/spongepowered/mod/mixin/core/entity/passive/EntityVillagerMixin_Forge.java#L65

`this.rand` is defined in a supermixin with a default priority (1001?) while the method accessing it has a priority of 1100. I have not yet tested this, but if it's anything like https://github.com/SpongePowered/SpongeCommon/issues/2457, then adjusting the priorities would workaround this.

However, there is something weird going on with the Mixin 0.8 update.

**Comment by Shybella** [comment]
This issue was not present on 3928. I can run another version. Im not surw
how to reproduce it

**Comment by Shybella** [comment]
Does not occur on Recommended.

**Comment by dualspiral** [comment]
This is now correctly obfuscated in the SF 3980 and should no longer be an issue.

**Comment by Shybella** [comment]
Fixed
