### ISSUE TITLE
When the piston is pushing out, the animation disappears.

### ISSUE THREAD

**Issue by Merrg1n** [SpongePowered/SpongeForge#3053]
**I am currently running**

- SpongeForge version: 
    * spongeforge-1.12.2-2838-7.1.9-RC3978 
    * spongeforge-1.12.2-2838-7.1.8
- Forge version: forge-1.12.2-14.23.5.2838
- Java version: 1.8.0_211
- Operating System: Windows 10 Home 1909

- Plugins/Mods:

    * Plugins (4): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge

    * Mods (7): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, SpongeForge

**Issue Description**

In the sponge server,the piston behavior looks strange. I test it on Minecraft 1.12.2 with and without Forge+Optifine both, and the result is same.

I use Minecraft 1.12.2 without Forge and Optifine to take the following screen captures.

Here is the behavior in the vanilla server and local world: 
[![vanilla.gif](https://s5.gifyu.com/images/vanilla.gif)](https://gifyu.com/image/mjFG)

And here is the behavior in the sponge server: 
[![sponge.gif](https://s5.gifyu.com/images/sponge.gif)](https://gifyu.com/image/mjFT)
(the gifs are large, may load slowly. If load fail, please click to watch this.)

Server log: [Here](https://gist.github.com/Merrg1n/04aba5de9486a19e050e97328669ae24)

**Comment by bloodmc** [comment]
Started in SF 3904 with commit https://github.com/SpongePowered/SpongeCommon/commit/1700f27c9c207bf614fd480f41130ddefe671f36
