### ISSUE TITLE
Mod BiblioCraft - NPE when placing blocks that changes TileEntity data on placement

### ISSUE THREAD

**Issue by zyczu1** [SpongePowered/SpongeForge#3055]
**I am currently running**
- SpongeForge version: 1.12.2-2838-7.1.8
- Forge version: 14.23.5.2838
- Java version: 1.8.0_201-b09
- Operating System: Debian 9, 64bit

- Plugins/Mods:
Plugins (8): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, Holograms, Nucleus, VoxelSniper, WorldEdit
Mods (14): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, BiblioCraft, CustomNPCs, Guide Book, Pam's HarvestCraft, Pixel Extras, Pixelmon, SpongeForge, Varied Commodities.

**Issue Description**

BiblioCraft is a mod which adds new blocks: custom lamps and lanterns. Lamps have various colors and can be attached to any side of adjacent block. This information is stored in a TileEntity. The mod overrides `Block.onBlockPlacedBy` in order to set the color and block rotation in a TileEntity.

When you place the lamp block, a NullPointerException is thrown: "Exception Exiting Phase". The block appears in the world, however its TE is corrupted and further exceptions are being thrown on world save. After rejoining the server we can realize the lamp lost its color and rotation data.

Steps to reproduce:

1. Find an item called "Fancy Lamp" in creative
2. Place it somewhere
3. Rejoin the server to see that TE data got lost

Important note: The issue was **not** present in SpongeForge 7.1.5!

Server log: https://gist.github.com/zyczu1/48d84e88963ba36286c9414da8ed1e65

**Comment by bloodmc** [comment]
Does this occur with SF 3982+ ?

**Comment by zyczu1** [comment]
Looks like it's fixed. Tested with SF 3986.

**Comment by dualspiral** [comment]
Thanks for dropping by to let us know!
