### ISSUE TITLE
Furnaces deleting items on first use 

### ISSUE THREAD

**Issue by Shybella** [SpongePowered/SpongeForge#3058]
**I am currently running**

- SpongeForge version: 3980
- Forge version: 2468
- Java version: 1.8
- Operating System: Win 

- Plugins/Mods: RLCraft 2.8.1

GIF: https://imgur.com/20lz9Db

The first attempt to use a furnace the the furnace will kick you out the gui and wipe the items. After this happens, the furnace will work as normally intended until the chunk unloads. On reload of the chunk the problem will occur again until something is scarified inside the furnace.

This does not occur on Recommended.

**Comment by Toakan** [comment]
Duplicated this on my server using release : 1.12.2-2838-7.1.9-RC3980

- https://github.com/SpongePowered/SpongeForge/commit/5b52f64dc6f6a49554303856f649744a0cdd2377

**Comment by dualspiral** [comment]
> This does not occur on Recommended.

Which recommended?

**Comment by Shybella** [comment]
1.12.2-2838-7.1.8 3971

**Comment by dualspiral** [comment]
My suspicion is that 3979 is the likely culprit. Would you mind checking 3978 to see if it's all okay there?

**Comment by bhi-elliot** [comment]
I had the same issue after updating to 3980, so came here, saw this thread, and tried out 3978.
**Furnaces seem to function as normal within 3978.**
Thanks for the thread and for finding the possible culprit.

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/SpongePowered/SpongeCommon/commit/3480230127f27b3df4c2a3e3b5643a14cb25cb4b

**Comment by Shybella** [comment]
Fixed.
