### ISSUE TITLE
Can't start with malisisdoors

### ISSUE THREAD

**Issue by mem0rz** [SpongePowered/SpongeForge#3059]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.1.9-RC3980.jar
- Forge version: 2847
- Java version: oracle 8_231
- Operating System:debian10

- Plugins/Mods:
malisiscore-1.12.2-6.5.1.jar
malisisdoors-1.12.2-7.3.0.jar
https://github.com/Ordinastie/MalisisDoors
https://github.com/Ordinastie/MalisisCore

**Issue Description**
Start and immedately go to crash. And  Return value: 1

[debug.log](https://github.com/SpongePowered/SpongeForge/files/4049615/debug.log)
[latest.log](https://github.com/SpongePowered/SpongeForge/files/4049616/latest.log)

**Comment by ImMorpheus** [comment]
A mod is loading an outdated Mixin version before Sponge, please report it to the mod author! For temporary solution rename the SpongeForge jar file, so its sorted alphabetically before the other mod e.g. rename spongeforge-1.12.2-2768-7.1.6-RC3616.jar to _aspongeforge-1.12.2-2768-7.1.6-RC3616.jar

**Comment by mem0rz** [comment]
> 
> 
> A mod is loading an outdated Mixin version before Sponge, please report it to the mod author! For temporary solution rename the SpongeForge jar file, so its sorted alphabetically before the other mod e.g. rename spongeforge-1.12.2-2768-7.1.6-RC3616.jar to _aspongeforge-1.12.2-2768-7.1.6-RC3616.jar

thank you very much
