### ISSUE TITLE
NPE when right clicking with a FakePlayer

### ISSUE THREAD

**Issue by SquidDev** [SpongePowered/SpongeForge#3060]
**I am currently running**
- SpongeForge: 1.12.2-2838-7.1.9-RC3980
- Forge: 1.12.2 14.23.5.2838 (Not latest, but recommended Sponge)
- Java: 1.8.0_231
- Operating System: Windows 10
- Plugins/Mods:
  - [CC: Tweaked 1.12.2-1.85.2](https://www.curseforge.com/minecraft/mc-mods/cc-tweaked/files/2834382). Similar crashes occur on later versions, but using this one as explained later.

## Reproduction steps
 - Place down a turtle.
 - Place a bucket within the first slot of the turtle's inventory.
 - Type `lua` <kbd>RET</kbd> `turtle.place()` <kbd>RET</kbd> on the turtle. This should "place" the bucket item.

One then receives the following error/crash:

```
java.lang.NullPointerException: null
  net.minecraftforge.common.ForgeHooks.handler$zpm000$forgeImpl$UpdatePacketDiff(ForgeHooks.java:2179)
  net.minecraftforge.common.ForgeHooks.onItemRightClick(ForgeHooks.java)
  dan200.computercraft.shared.turtle.core.TurtlePlaceCommand.deployOnBlock(TurtlePlaceCommand.java:373)
  dan200.computercraft.shared.turtle.core.TurtlePlaceCommand.deploy(TurtlePlaceCommand.java:131)
  dan200.computercraft.shared.turtle.core.TurtlePlaceCommand.execute(TurtlePlaceCommand.java:82)
  dan200.computercraft.shared.turtle.core.TurtleBrain.updateCommands(TurtleBrain.java:889)
  dan200.computercraft.shared.turtle.core.TurtleBrain.update(TurtleBrain.java:123)
  dan200.computercraft.shared.turtle.blocks.TileTurtle.func_73660_a(TileTurtle.java:218)
  org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:237)
  net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:4726)
```

[Full log available here](https://gist.github.com/SquidDev/e06e462967cd6a1f72fe48e132175891)

## Further notes
This crash occurs within a mixin on `ForgeHooks.onItemRightClick`:

https://github.com/SpongePowered/SpongeForge/blob/5b52f64dc6f6a49554303856f649744a0cdd2377/src/main/java/org/spongepowered/mod/mixin/core/forge/common/ForgeHooksMixin_Forge.java#L126-L128

This code does not account for `FakePlayers`, where the connection is null. We also receive a similar crash on CC:Tweaked 1.86.0, as that provides a custom connection instance which does not implement `NetHandlerPlayServerBridge`.

CC:T 1.86.1 fixes the crash by inlining `onItemRightClick` (and thus bypassing the mixin), but ideally there would be an additional FakePlayer/`instanceof NetHandlerPlayServerBridge` check within the mixin's body.

**Comment by ImMorpheus** [comment]
Fixed by https://github.com/SpongePowered/SpongeForge/commit/ac0a4a703264add8e88400ca6a1dd47ade4e1fd4

Thanks for the detailed report and sorry for the delay.

**Comment by SquidDev** [comment]
No worries, thank you!
