### ISSUE TITLE
Immersive Engineering dupe

### ISSUE THREAD

**Issue by bigenergy** [SpongePowered/SpongeForge#3061]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.1.9-RC3980
- Forge version: forge-1.12.2-14.23.5.2847
- Java version: 1.8.0_211
- Operating System: Ubuntu 19.04

- Plugins/Mods: ImmersiveEngineering-0.12-92

**Issue Description**
Blocks from IE sometimes duplicated when breaking, only happens with spongeforge

See a video: https://youtu.be/-HK52K9TTeI

**Comment by dualspiral** [comment]
Does it work okay on the recommended build 7.1.8?

**Comment by bigenergy** [comment]
As far as I remember, this bug appeared with the update spongeforge-1.12.2-2838-7.1.8-RC3964

**Comment by bigenergy** [comment]
recommended build 7.1.8 has the same problem

**Comment by theonrd** [comment]
This bug began to appear after version RC3700

**Comment by jinkhya** [comment]
This still happens in recommended 7.2.0 that came out 2 days ago and there's no error in the console when it happens. 
On our server, It happened with Engineer's workbenches and also caused a player to lose some Immersive Engineering wooden crates. Breaking the crate next to a glitched workbench dropped nothing so the crate and its content was just gone.
I tried finding some kind of pattern when this happens but it seems inconsistent.

**Comment by bigenergy** [comment]
any ideas?

**Comment by bigenergy** [comment]
how can you release stable releases if this bug is still not fixed?
it is very sad
