### ISSUE TITLE
ClassCastException crash on startup.

### ISSUE THREAD

**Issue by kristi71111** [SpongePowered/SpongeForge#3062]
**I am currently running**
- SpongeForge version: 1.12.2-2838-7.1.9-RC3984
- Forge version: 14.23.5.2838
- Java version: 1.8.0_212/64-bit (Oracle Corporation)
- Operating System: CentOS 7 (4.9.178-xxxx-std-ipv6-64/amd64)

- Plugins/Mods:
**Mods (219):** Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, /dank/null, AE2 Wireless Terminals (AE2WTLib), AI Improvements, Actually Additions, Actually Baubles, Advanced Machines, Advanced Solar Panels, Akashic Tome, AppleSkin, Applied Energistics 2, ArchitectureCraft, Aroma1997's Dimensional World, Aroma1997Core, Astral Sorcery, AutoRegLib, B.A.S.E, BD Lib, Baubles, Bed Patch, Better Builder's Wands, BiblioCraft, Bigger Packets, please !, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Biomes O' Plenty, Blockcraftery, Blood Magic: Alchemical Wizardry, Bookshelf, Botania, Brandon's Core, BuildCraft, BuildCraft Builders, BuildCraft Compat, BuildCraft Energy, BuildCraft Factory, BuildCraft Lib, BuildCraft Robotics, BuildCraft Silicon, BuildCraft Transport, CC: Tweaked, CC: Tweaked, Chameleon, Chest Transporter, Chisel, Chisels & Bits, Clumps, CoFH Core, CoFH World, CodeChicken Lib, Compact Solar Arrays, Construct's Armory, Cooking for Blockheads, CraftTweaker JEI Support, CraftTweaker2, Dark Utilities, DeepResonance, Diet Hopper, Dirt2Path, Draconic Evolution, ET Lunar, ElecCore, ElecCoreLoader, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, EnderStorage, Engineer's Doors, Engineer's Workshop Reborn, Environmental Tech, Exchangers, Extra Utilities 2, Extreme Reactors, FTB Guides, FTB Library, FTB Utilities, FastWorkbench, Fence Jumper, Flat Colored Blocks, Flux Networks, FoamFix, FoamFixCore, Forestry, Forge Microblocks, Forge Multipart CBE, GenDustry, Gravitation Suite, Guide-API, Harvest, Immersive Cables, Immersive Engineering, Immersive Petroleum, Industrial Foregoing, Industrial Wires, IndustrialCraft 2, InitialInventory, Integration Foregoing, Iron Backpacks, Iron Chest, JEI Bees, JourneyMap, Just Enough Items, Let's Encrypt Craft, Long Fall Boots, MCMultiPart, MTLib, MagicBees, Mantle, McJtyLib, Minecraft Multipart Plugin, Mod Tweaker, Morph-o-Tool, Morpheus, MrTJPCore, Mystical Lib, Natura, Nature's Compass, Nice, Not Enough Wands, NotEnoughIDs, OpenBlocks, OpenModsLib, OpenModsLib Core, Pam's HarvestCraft, Patchouli, Phosphor Lighting Engine, Placebo, Platforms, ProjectRed Core, ProjectRed Expansion, ProjectRed Exploration, ProjectRed Fabrication, ProjectRed Illumination, ProjectRed Integration, ProjectRed Relocation, ProjectRed Transmission, ProjectRed Transportation, Quark, Quick Leaf Decay, RFTools, RFTools Control, RFToolsPower, Railcraft, RandomPatches, Ranged Pumps, Reborn Core, RebornStorage, Redstone Arsenal, Redstone Flux, Refined Storage, Refined Storage Addons, Reliquary, Rustic, Sampling Performance Profiler, ShadowMC, Shadowfacts' Forgelin, ShetiPhian-Core, SimpleVoidWorld, Simply Jetpacks 2, Snad, SonarCore, Soul Shards Respawn, SpongeForge, Steve's Carts 2, Storage Drawers, Storage Drawers Extras, TOP Addons, Tesla Core Lib, Tesla Core Lib Registries, Thaumcrafft Inventory Scanning, Thaumcraft, The Lost Cities, The One Probe, The Twilight Forest, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Thut Core, Thut's Elevators, ThutCore Compat, TickProfiler, Tinkers Tool Leveling, Tinkers' Construct, TorchMaster, Translocators, UniDict, Universal Modifiers, Valkyrie Lib, WanionLib, Waystones, Wireless Crafting Terminal 2, Woot, XNet, Xtones, YABBA, Zero CORE, careerbees, p455w0rd's Library, projectred-compat
**Plugins (36):** Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, ActiveTime, AsciiEmotes, BacoMasterReborn, BaconTowny, Be_quiet, BetterChunkLoader, BungeeTabListPlus-SpongeBridge, CatClearLag, CommandUtils, DailyRewards, EasyTexts, EconomyLite, Enjin Minecraft Plugin, Holograms, HuskyUI, Lottery, LuckPerms, MMCRestrict, Market, NuVotifier, Nucleus, PlaceholderAPI, Plan, ProjectBorders, ProjectCore, SeriousVote, Sledgehammer, Unity, VoteParty, WelcomeRewards, WorldEdit, spark

**Issue Description**
Upon updating to 1.12.2-2838-7.1.9-RC3984 from 1.12.2-2838-7.1.8 (Recommended) the server crashes on startup due to ClassCastException: net.minecraft.world.WorldServer cannot be cast to org.spongepowered.common.bridge.world.WorldBridge [Link to crash](https://gist.github.com/kristi71111/adc7a0c6ebb460a60a090c7099627be3).

**Comment by LXGaming** [comment]
Remove TickProfiler

Relative issue: https://github.com/MinimallyCorrect/ModPatcher/issues/20

**Comment by kristi71111** [comment]
Confirmed.
Works fine wo tickprofiler.
