### ISSUE TITLE
Server startup issue. Update from 7.1.8-RC3969 to 7.1.9-RC3986

### ISSUE THREAD

**Issue by SSKirillSS** [SpongePowered/SpongeForge#3064]
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2838-7.1.8-RC3969
- Forge version: forge-1.12.2-14.23.5.2847-universal

- Plugins/Mods: Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AI Improvements, AetherWorks, Alternating Flux, Arcane Archives, Armory Expansion, Armory Expansion - Construct's Armory, Armory Expansion - Custom Materials, Armory Expansion - Ice and Fire, Armory Expansion - MatterOverdrive, Astral Sorcery, Athenaeum, AutoRegLib, Baubles, Better Questing, Better Questing Quest Book, Blood Magic: Alchemical Wizardry, Botania, CodeChicken Lib, Construct's Armory, CraftTweaker JEI Support, CraftTweaker2, CustomNPCs, Dropt, Dynamic Trees, Dynamic Trees TC, Embers Rekindled, Engineer's Decor, Guide-API, Guidebook, Immersive Engineering, Immersive Petroleum, Immersive Tech, Just Enough Items, LibrarianLib, LibrarianLib Stage 2, MTLib, Mantle, MetalChests, Metallurgy 4: Reforged, Mod Tweaker, Mystical Gears, Mystical Lib, Mystical Mechanics, Patchouli, Phosphor Lighting Engine, PlusTiC, Psi, Pyrotech, Quark, Random PSIdeas, RandomPatches, Shadowfacts' Forgelin, Soot, SpongeForge, Standard Expansion, TBone, Thaumcraft, Thaumic Augmentation, The Betweenlands, TickProfiler, Tinkers Tool Leveling, Tinkers' Construct, WorldEdit, libnine

**Issue Description**
I just try to update from SF 7.1.8-RC3969 to SF 7.1.9-RC3986. Server crash and restart after 2-3 seconds of loading.

Error in console: https://gist.github.com/SSKirillSS/f39704a2c076ebb646d4277dfe67342f

It should also be noted that the problem affected all my servers, but the errors are different everywhere. If necessary, I can provide them a little later.

**Comment by clienthax** [comment]
Full log please, Also please don't remove information needed from the template.

**Comment by SSKirillSS** [comment]
Full log: https://gist.github.com/SSKirillSS/26d40cb11cd86dd8a144c28a2c1bf17b

**Comment by SSKirillSS** [comment]
Accidentally closed. Oops

**Comment by ImMorpheus** [comment]
A mod is loading an outdated Mixin version before Sponge, please report it to the mod author! For temporary solution rename the SpongeForge jar file, so its sorted alphabetically before the other mod e.g. rename spongeforge-1.12.2-2768-7.1.6-RC3616.jar to _aspongeforge-1.12.2-2768-7.1.6-RC3616.jar
