### ISSUE TITLE
Server startup issue. Update from 7.1.9-RC3972 to 7.1.9-RC3986

### ISSUE THREAD

**Issue by SSKirillSS** [SpongePowered/SpongeForge#3066]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.1.9-RC3972
- Forge version: forge-1.12.2-14.23.5.2847-universal
- Java version: 1.8.0_201
- Operating System: Linux

- Plugins/Mods: Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, A Lib, Advanced Chimneys, Advanced Rocketry, Advanced Rocketry Core, Alchemistry, AutoRegLib, Chisel, CoFH Core, CoFH World, CodeChicken Lib, Computronics, CoroUtil Library, CraftTweaker JEI Support, CraftTweaker2, CustomNPCs, Cyberware, DenyBlocks, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, EventHelper, Extended Mod Config, Extended Renderer, First Aid, FoamFix, FoamFixCore, Forge Endertech, Gravestone Mod, Iblis Headshots, Just Enough Items, Localized Weather & Storms, Mekanism, Mekanism: Generators, Mekanism: Tools, MetalChests, Modern Warfare, NuclearCraft, OpenComputers, OpenComputers (Core), Patchouli, Pollution of the Realms, Portality, Quark, RandomPatches, ReWIRED, Realistic Terrain Generation, Reborn Core, Redstone Flux, Shadowfacts' Forgelin, SpongeForge, TBone, Tech Reborn, Tech Reborn Mod Compatibility, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, TickProfiler, Treecapitator, Vulpes library, WorldEdit, Zombie Awareness, asielib, bspkrsCore

**Issue Description**
After upgrading to the latest version(7.1.9-RC3986) server crashes at the world loading stage.

Crash: https://gist.github.com/SSKirillSS/6ae1b9f3e65f3c47fbd21a67fbd5761c

**Comment by dualspiral** [comment]
Remove TickProfiler - that’s been a big source of these particular crashes.
