### ISSUE TITLE
The composition table is not refreshed in time.

### ISSUE THREAD

**Issue by DJmanito** [SpongePowered/SpongeForge#3067]
### I am currently running:

- Minecraft: 1.12.2
- SpongeAPI: 7.1.0-ea50f0c2
- Sponge: 1.12.2-7.1.9-SNAPSHOT
- SpongeForge: 1.12.2-2838-7.1.9-RC3988
- Minecraft Forge: 14.23.5.2847
- JVM: 1.8.0_201/64-bit (Oracle Corporation)
- OS: Windows Server 2019 (10.0/amd64)

### Issue Description:

- Using the right mouse button to place the composite table and double-click to quickly get the same item function, to cooperate with the composite table not to refresh will lead to some strange things. It is suggested to watch the video in the compression package, and the text expression is slightly complicated.
- This will not appear in previous versions 1.12.2-2838-7.1.7-rc3889.
- For various reasons, I have been staying at version 1.12.2-2838-7.1.7-rc3889, which is a little far from the latest version. I don't have time to test which version started one by one. Sorry.
- And the latest version has a question about the head. I think other people have already given feedback. By the way, as long as the head in non mod is destroyed, two identical heads will be obtained.
- My English is not good. Please forgive me if there is any translation problem.

[Desktop 2020.01.26 - 15.34.24.09_x264.zip](https://github.com/SpongePowered/SpongeForge/files/4113227/Desktop.2020.01.26.-.15.34.24.09_x264.zip)

**Comment by DJmanito** [comment]
The last problem-free version I tested was: spongforge-1.12.2-2838-7.1.9-rc3980.jar

**Comment by dualspiral** [comment]
Did 3981 not work?

If so https://github.com/SpongePowered/SpongeCommon/commit/270d36cd4111eafd76ff184e293466b4c62cb65f is the culprit.

**Comment by DJmanito** [comment]
3981 doesn't work properly
I've tested almost every version from 3981 to the latest, and nothing works

**Comment by dualspiral** [comment]
Ok, thanks.

> And the latest version has a question about the head. I think other people have already given feedback. By the way, as long as the head in non mod is destroyed, two identical heads will be obtained.

Just to clarify, that's been dealt with.

**Comment by DJmanito** [comment]
I just deleted three modules, one of which may be the cause of this problem:
InventoryTweaks-1.63.jar
Hwyla-1.8.26-B41_1.12.2.jar
Wawla-1.12.2-2.5.273.jar
Next, I will use the latest version of 7.1.10-rc3992 to test more things. I'm sorry for the trouble caused by my personal problems
