### ISSUE TITLE
missing entries sponge:human, and crash after /fml confirm

### ISSUE THREAD

**Issue by chenxuuu** [SpongePowered/SpongeForge#3070]
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2838-7.1.9
- Forge version: forge-1.12.2-14.23.5.2838-universal
- Java version: 1.8.0_202, Eclipse OpenJ9
- Operating System:Windows Server 2016 (amd64) version 10.0

- Plugins/Mods:

	| State  | ID                    | Version           | Source                                               | Signature                                |
	|:------ |:--------------------- |:----------------- |:---------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft             | 1.12.2            | minecraft.jar                                        | None                                     |
	| LCHIJA | mcp                   | 9.42              | minecraft.jar                                        | None                                     |
	| LCHIJA | FML                   | 8.0.99.99         | forge-1.12.2-14.23.5.2838-universal.jar              | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                 | 14.23.5.2838      | forge-1.12.2-14.23.5.2838-universal.jar              | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | anothercommonbugfix   | 1.0.7             | minecraft.jar                                        | None                                     |
	| LCHIJA | customnpcs            | 1.12              | [自定义NPC]CustomNPCs_1.12.2-(01Oct19).jar              | None                                     |
	| LCHIJA | touhou_little_maid    | 1.1.9             | [东方乱码]touhoulittlemaid-1.12.2-jenkins-build-103.jar  | None                                     |
	| LCHIJA | mantle                | 1.12-1.3.3.55     | [匠魂拓展-前置]Mantle-1.12-1.3.3.55.jar                    | None                                     |
	| LCHIJA | tconstruct            | 1.12.2-2.12.0.157 | [匠魂]TConstruct-1.12.2-2.12.0.157.jar                 | None                                     |
	| LCHIJA | flammpfeil.slashblade | mc1.12-r28        | [拔刀剑]SlashBlade-mc1.12-r28.jar                       | None                                     |
	| LCHIJA | patchouli             | 1.0-20            | [帕秋莉]Patchouli-1.0-20.jar                            | None                                     |
	| LCHIJA | lastsmith             | V1.2.6.5-MC1.12.2 | [拔刀剑附加-最后的太刀匠人]TLS-V1.2.6.5-MC1.12.2.jar             | None                                     |
	| LCHIJA | slashbladetic         | V1.0.9.2-MC1.12.2 | [刀锻冶匠魂-匠魂与拔刀剑的融合]SlashBladeTic-V1.0.9.2-MC1.12.2.jar | None                                     |
	| LCHIJA | codechickenlib        | 3.2.3.358         | [前置]CodeChickenLib-1.12.2-3.2.3.358-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | laggoggles            | FAT-1.12.2-4.9    | [卡顿监测]LagGoggles-FAT-1.12.2-4.9.jar                  | None                                     |
	| LCHIJA | forgelin              | 1.8.2             | [唱片前置]Forgelin-1.8.2.jar                             | None                                     |
	| LCHIJA | betterrecords         | 1.12.2-1.6.1      | [唱片]BetterRecords-1.12.2-1.6.1.jar                   | None                                     |
	| LCHIJA | cfm                   | 6.3.1             | [家具]furniture-6.3.1-1.12.2.jar                       | None                                     |
	| LCHIJA | ironchest             | 1.12.2-7.0.67.844 | [更多箱子]ironchest-1.12.2-7.0.72.847.jar                | None                                     |
	| LCHIJA | baubles               | 1.5.2             | [植物魔法-神秘时代-前置]Baubles-1.12-1.5.2.jar                 | None                                     |
	| LCHIJA | thaumcraft            | 6.1.BETA26        | [神秘时代]Thaumcraft-1.12.2-6.1.BETA26.jar               | None                                     |
	| LCHIJA | botania               | r1.10-363         | [植物魔法]Botania+r1.10-363.jar                          | None                                     |
	| LCHIJA | cctweaked             | 1.85.2            | [电脑]cc-tweaked-1.12.2-1.85.2.jar                     | None                                     |
	| LCHIJA | computercraft         | 1.85.2            | [电脑]cc-tweaked-1.12.2-1.85.2.jar                     | None                                     |
	| LCHIJA | grimoireofgaia        | 1.6.9.3           | [盖魔亚典]GrimoireOfGaia3-1.12.2-1.6.9.3.jar             | None                                     |
	| LCHIJA | extrabotany           | 56                | [额外植物学]ExtraBotany-r1.1-56.jar                       | None                                     |
	| LCHIJA | kiwi                  | 0.5.3.32          | [料理工艺-前置]Kiwi-1.12.2-0.5.3.32.jar                    | None                                     |
	| LCHIJA | cuisine               | 0.5.17-build909   | [料理工艺]Cuisine-0.5.17-build909.jar                    | None                                     |

**Issue Description**

just update sponge from `spongeforge-1.12.2-2838-7.1.8` to `spongeforge-1.12.2-2838-7.1.9`

it show `There are 1 missing entries in this save.`, and crash after I entered `/fml confirm`

```log
[12:04:30] [Server thread/INFO] [FML]: Registry Block: Found a missing id from the world animania:block_hive
[12:04:30] [Server thread/INFO] [FML]: Registry Block: Found a missing id from the world animania:cheese_sheep
[12:04:30] [Server thread/INFO] [FML]: Registry Block: Found a missing id from the world animania:milk_friesian
[12:04:30] [Server thread/INFO] [FML]: Registry Block: Found a missing id from the world animania:milk_sheep
[12:04:30] [Server thread/INFO] [FML]: Registry Block: Found a missing id from the world animania:cheese_friesian
[12:04:30] [Server thread/INFO] [FML]: Registry Block: Found a missing id from the world animania:wool
[12:04:30] [Server thread/INFO] [FML]: Registry Block: Found a missing id from the world animania:cheese_jersey
[12:04:30] [Server thread/INFO] [FML]: Registry Block: Found a missing id from the world animania:block_trough
[12:04:30] [Server thread/INFO] [FML]: Registry Block: Found a missing id from the world animania:milk_goat
[12:04:30] [Server thread/ERROR] [FML]: Unidentified mapping from registry minecraft:entities
[12:04:30] [Server thread/ERROR] [FML]:     sponge:human: 308
[12:04:30] [Server thread/WARN] [FML]: Forge Mod Loader detected missing registry entries.

There are 1 missing entries in this save.
If you continue the missing entries will get removed.
A world backup will be automatically created in your saves directory.

Missing minecraft:entities:
    sponge:human


Run the command /fml confirm or or /fml cancel to proceed.
Alternatively start the server with -Dfml.queryResult=confirm or -Dfml.queryResult=cancel to preselect the answer.
> /fml confirm
[12:06:13] [Server thread/INFO] [FML]: confirmed
[12:10:42] [Server thread/INFO] [FML]: World backup created at D:\1.12.2-SpongeForge\world-20200131-120613.zip.
[12:10:42] [Server thread/ERROR] [FML]: There are unidentified mappings in this world - we are going to attempt to process anyway
[12:10:43] [Server thread/INFO] [FML]: Applying holder lookups
[12:10:43] [Server thread/INFO] [FML]: Holder lookups applied
[12:10:44] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.VerifyError: JVMVRFY012 堆栈形状不一致；类=net/minecraft/world/WorldServer，方法=func_147456_g()V，pc=828；类 型不匹配，签名 net/minecraft/world/WorldServer.randomBlockTickRedirectorVanilla:(Lnet/minecraft/block/Block;Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/block/state/IBlockState;Ljava/util/Random;)V 中的参数 0 不匹配
Exception Details:
  Location:
    net/minecraft/world/WorldServer.func_147456_g()V @828: JBinvokespecial
  Reason:
    Type 'net/minecraft/world/WorldServer' (current frame, stack[1]) is not assignable to 'net/minecraft/block/Block'
  Current Frame:
    bci: @828
    flags: { }
    locals: { 'net/minecraft/world/WorldServer', integer, integer, integer, 'java/util/Iterator', 'net/minecraft/world/chunk/Chunk', integer, integer, '[Lnet/minecraft/world/chunk/storage/ExtendedBlockStorage;', integer, integer, 'net/minecraft/world/chunk/storage/ExtendedBlockStorage', integer, integer, integer, integer, integer, 'net/minecraft/block/state/IBlockState', 'net/minecraft/block/Block' }
    stack: { 'net/minecraft/block/Block', 'net/minecraft/world/WorldServer' }
  Stackmap Table:
    append_frame(@25,Object[#176])
    same_frame(@50)
    chop_frame(@53,1)
    full_frame(@97,{Object[#2],integer,integer,integer,Object[#176]},{})
    full_frame(@416,{Object[#2],integer,integer,integer,Object[#176],Object[#230],integer,integer,integer,Object[#225],Object[#253]},{})
    chop_frame(@448,3)
    append_frame(@576,integer,Object[#225],Object[#225])
    same_frame(@603)
    chop_frame(@636,3)
    append_frame(@665,Object[#296],integer,integer)
    append_frame(@698,Object[#288],integer)
    full_frame(@831,{Object[#2],integer,integer,integer,Object[#176],Object[#230],integer,integer,Object[#296],integer,integer,Object[#288],integer,integer,integer,integer,integer,Object[#283],Object[#275]},{})
    full_frame(@844,{Object[#2],integer,integer,integer,Object[#176],Object[#230],integer,integer,Object[#296],integer,integer,Object[#288]},{})
    full_frame(@850,{Object[#2],integer,integer,integer,Object[#176],Object[#230],integer,integer},{})
    chop_frame(@860,3)
    full_frame(@867,{Object[#2]},{})
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:298) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:813) [?:1.8.0_202]
[12:10:44] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: D:\1.12.2-SpongeForge\.\crash-reports\crash-2020-01-31_12.10.44-server.txt
[12:10:44] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[12:10:44] [Server thread/INFO] [minecraft/MinecraftServer]: Saving players
[12:10:44] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
[12:10:44] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STARTING and forced into state SERVER_STOPPED. Errors may have been discarded.
```

**crash report**

[crash-2020-01-31_12.10.44-server.txt](https://github.com/SpongePowered/SpongeForge/files/4137574/crash-2020-01-31_12.10.44-server.txt)

**Comment by LordRalex** [comment]
Provide a full log. This means sponge did not load, and so you basically ignored that error.

**Comment by chenxuuu** [comment]
@LordRalex sorry about that, here's log file and crash report
[crash-2020-01-30_15.14.21-server.txt](https://github.com/SpongePowered/SpongeForge/files/4137762/crash-2020-01-30_15.14.21-server.txt)
[2020-01-30-2.log](https://github.com/SpongePowered/SpongeForge/files/4137763/2020-01-30-2.log)

maybe caused by `LagGoggles` ?

**Comment by LordRalex** [comment]
Rename sponge to _asponge.jar.

**Comment by chenxuuu** [comment]
oh, I see
this caused by `LagGoggles`
@LordRalex thanks a lot
