### ISSUE TITLE
Nevermine:AoA internal server error

### ISSUE THREAD

**Issue by SSKirillSS** [SpongePowered/SpongeForge#3071]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.1.9
- Forge version: forge-1.12.2-14.23.5.2847-universal
- AoA version: AoA3-3.2.3
- Java version: 1.8.0_201
- Operating System: Linux

- Plugins/Mods:
Mods (73): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AI Improvements, Advent Of Ascension, Armory Expansion, Armory Expansion - Construct's Armory, Armory Expansion - Custom Materials, Armory Expansion - Ice and Fire, Armory Expansion - MatterOverdrive, Astral Sorcery, AutoRegLib, Baubles, Bewitchment, Blood Arsenal, Blood Magic: Alchemical Wizardry, Bookshelf, Botania, Champions, Chisels & Bits, CodeChicken Lib, Construct's Armory, CraftTweaker JEI Support, CraftTweaker2, Cucumber Library, CustomNPCs, DarknessLib, Enchanting With Thaumcraft, EventHelper, ExtraBotany, Fantastic Lib, Fast Leaf Decay, FoamFix, FoamFixCore, Guide-API, Hammer Core, HilUI, Incoremod-poreal, Incorporeal, Just Enough Items, LLibrary, LibrarianLib, LibrarianLib Stage 2, MTLib, Mantle, MetalChests, Mod Tweaker, More Flowers, Mystical Agriculture, Natural Pledge, OreLib Support Mod, Patchouli, Quark, RandomPatches, Shadowfacts' Forgelin, SpongeForge, TBone, Thaumcraft, Thaumic Additions: Reconstructed, Thaumic Augmentation, Thaumic Brewing, Thaumic Periphery, Thaumic Restoration, Tinkers Tool Leveling, Tinkers' Construct, Treecapitator, Weapon Levels, WebShop Server Mod, WorldEdit, bspkrsCore

**Issue Description**
When the AoA expedition skill is triggered, it must impose a speed or saturation effect, but instead disconnects the player from the server with an internal server error

https://gist.github.com/SSKirillSS/8794c3169cb9f5086afffe4aa664f061

**Comment by Zarpyk** [comment]
My error log: https://gist.github.com/GuerreroCraft61/bb6bbe289144b81428a32f70c7611f88

**Comment by SSKirillSS** [comment]
Quite a lot of time has passed. Perhaps there is some "magic" option that can be turned off so that there are no more kicks (As a temporary measure)? :D

**Comment by SSKirillSS** [comment]
Still an issue.

spongeforge-1.12.2-2838-7.1.11-RC4007
AoA3-3.2.5

**Comment by Yeregorix** [comment]
IMO, you should ask the AoA3 mod author to fix his method: `PlayerDataManager#sendThrottledChatMessage`.
There are null elements in the array passed to the `TextComponentTranslation` constructor.

**Comment by Tslat** [comment]
Can someone point me to the 1.12.2 branch of spongeforge?

**Comment by phit** [comment]
stable-7

**Comment by Tslat** [comment]
Resolved in the next version, you can close this
