### ISSUE TITLE
ModTrinity

### ISSUE THREAD

**Issue by listofer** [SpongePowered/SpongeForge#3074]
**I am currently running**

- SpongeForge version: 
- Forge version: 
- Java version: 
- Operating System:

- Plugins/Mods:

**Issue Description**

Mod trinity not Warr works on spongeforge

https://www.youtube.com/watch?v=CeAfJYavH_4&feature=youtu.be

https://www.youtube.com/watch?v=HwKCgwqm2C0&feature=youtu.be

https://mclo.gs/C6M0TuR

https://mclo.gs/dwiteBJ

https://mclo.gs/5HkfHyb

https://mclo.gs/M4bgmJP

https://mclo.gs/AIE9Swk

https://mclo.gs/qehjvRS

Version of spongeforge 1.12.2 2838RC994

**Comment by listofer** [comment]
Java8-241, windows10

**Comment by listofer** [comment]
Mods:https://yadi.sk/d/MgHvm2WHNO_FXQ

**Comment by listofer** [comment]
Plugins:nucleus,spark.

**Comment by dualspiral** [comment]
Nearly everything that you've posted here has the following in it:

```
java.lang.OutOfMemoryError
```

Out of memory. You need to assign more memory to your server. That will likely solve all your problems.

Not a Sponge issue.

edit: See https://docs.spongepowered.org/stable/en/server/spongineer/troubleshooting.html#not-enough-free-memory
