### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Zarpyk** [SpongePowered/SpongeForge#3075]
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.1.10-RC3994
- Forge version: 14.23.5.2847
Java version: --- (Java 8 probably)
Operating System: --- (Is a Minecraft host)

- Plugins/Mods: In the Crash log: https://gist.github.com/GuerreroCraft61/55bdbfef5bf6c65eb17e20be833f441a

**Issue Description**
Server crash
The crash log says it's bloodmagic error, but is the same when I use Aether II
https://gist.github.com/GuerreroCraft61/55bdbfef5bf6c65eb17e20be833f441a

**Comment by dualspiral** [comment]
Try removing LagGoggles and try again.

**Comment by Zarpyk** [comment]
Is LagGoogles crash it
