### ISSUE TITLE
Console crashes

### ISSUE THREAD

**Issue by Unrestriction** [SpongePowered/SpongeForge#3076]
- SpongeForge version: 1.12.2-2768-7.1.6-RC3616
- Forge version: 1.12.2-14.23.5.2847
- Java version: Java 8 update 241
- Operating System: Windows 10

cant to /sponge plugins or /sponge mods because the console crashes. But I can do this.
https://i.imgur.com/Ebrlt6b.png

https://gist.github.com/Unrestriction/3ec5c1aeffadbe21af4515f812561acd

**Comment by clienthax** [comment]
Can you try this on latest sponge, you are running a fairly out of date build?

**Comment by Unrestriction** [comment]
> Can you try this on latest sponge, you are running a fairly out of date build?

Still happens even after removing sponge and plugins

**Comment by Zidane** [comment]
Erm if you remove Sponge and plugins then this is no longer a Sponge issue.

**Comment by gabizou** [comment]
Add `-Dmixin.dumpTargetOnFailure=true` to your startup command (before `-jar`) then zip up and give the `.mixin.out` folder contents here
