### ISSUE TITLE
Instant crash on 2838-7.1.9 after update

### ISSUE THREAD

**Issue by Y0ungSandwich** [SpongePowered/SpongeForge#3078]
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.1.9
- Forge version: forge-1.12.2-14.23.5.2847-universal
- Java version: 8
- Operating System: CentOS 6

- Plugins/Mods :Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, AdamantineShield(Not actually loading?), GriefPrevention, LuckPerms, MMCRestrict, Nucleus

Modpack is Mech & Magic https://atlauncher.com/pack/MechMagic

**Issue Description** I updated sponge to 1.12.2-2838-7.1.9 to see if that was the cause for a new plugin, AdamantineShield, not fully loading on the server. After updating I attempt to launch my server where it instantly crashes.

https://gist.github.com/Y0ungSandwich/01a30a847b2e5ab449b1d22eab6ab992

**Comment by JBYoshi** [comment]
> java.lang.SecurityException: class "org.spongepowered.asm.service.ServiceInitialisationException"'s signer information does not match signer information of other classes in the same package

This seems to be a conflict with DynamicSurroundings.

From a quick investigation, DynamicSurroundings uses a signed JAR file with a signed version of Mixin. The signature in its JAR seems to be preventing Mixin from loading properly.

**Comment by gabizou** [comment]
Not to mention that there could be the issue that DynamicSurroundings might be bundling an older version of Mixin than SpongeForge's version, I'd try to rename SpongeForge to `_aspongeforge.jar` to get it to class load first.

Edit: DynamicSurroundings still [hasn't updated Mixin to 0.8, which would break if they're loading first and SpongeForge loads afterwards](https://github.com/OreCruncher/DynamicSurroundings/blob/220eb3afc03d7e46935b08a194980c85a71d4d2e/build.gradle#L106). The fix I mentioned above should resolve the issue entirely.

**Comment by ImMorpheus** [comment]
As others have said this is an issue with dynamic surroundings.

If you can reproduce this with the latest RB please comment below and I will reopen.
