### ISSUE TITLE
Herrscher of The Void attack cause console spam

### ISSUE THREAD

**Issue by SSKirillSS** [SpongePowered/SpongeForge#3083]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.1.9
- Forge version: forge-1.12.2-14.23.5.2847-universal
- ExtraBotany-r1.1-57
- Java version: 1.8.0_201
- Operating System: Linux

- Plugins/Mods:
Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AI Improvements, Advent Of Ascension, Armory Expansion, Armory Expansion - Construct's Armory, Armory Expansion - Custom Materials, Armory Expansion - Ice and Fire, Armory Expansion - MatterOverdrive, Astral Sorcery, AutoRegLib, Baubles, Bewitchment, Blood Arsenal, Blood Magic: Alchemical Wizardry, Bookshelf, Botania, Champions, Chisels & Bits, CodeChicken Lib, Construct's Armory, CraftTweaker JEI Support, CraftTweaker2, Cucumber Library, CustomNPCs, DarknessLib, Enchanting With Thaumcraft, EventHelper, ExtraBotany, Fantastic Lib, Fast Leaf Decay, FoamFix, FoamFixCore, Guide-API, Hammer Core, HilUI, Incoremod-poreal, Incorporeal, Just Enough Items, LLibrary, LibrarianLib, LibrarianLib Stage 2, MTLib, Mantle, MetalChests, Mod Tweaker, More Flowers, Mystical Agriculture, Natural Pledge, OreLib Support Mod, Patchouli, Quark, RandomPatches, Shadowfacts' Forgelin, SpongeForge, TBone, Thaumcraft, Thaumic Additions: Reconstructed, Thaumic Augmentation, Thaumic Brewing, Thaumic Periphery, Thaumic Restoration, Tinkers Tool Leveling, Tinkers' Construct, Treecapitator, Weapon Levels, WebShop Server Mod, WorldEdit, bspkrsCore

**Issue Description**
Mod: ExtraBotany (Botania addon)
Herrscher of The Void subspear attack cause a lot of console spam. As result server just crash with GC overhead error.

**Steps to reproduce:**
1. Summon Herrscher of The Void (in survival gamemode)
2. Wait

Log: https://gist.github.com/SSKirillSS/9d5bdae5fa868e6311209d9b642ec759

**Comment by gabizou** [comment]
This looks like a mod bug:
The [`Herrscher` is spawning an `EntitySubSpace` with itself as the `thrower`](https://github.com/ExtraMeteorP/Extra-Botany/blob/e93592dd669454ebe845decdc1edd5d4c2138f1f/src/main/java/com/meteor/extrabotany/common/entity/gaia/EntityVoidHerrscher.java#L234) (whose [constructor accepts `EntityLivingBase`](https://github.com/ExtraMeteorP/Extra-Botany/blob/293cfc81f0b22bd72a8b99baa087f77581b426bc/src/main/java/com/meteor/extrabotany/common/entity/EntitySubspace.java#L52),  which during the [`EntitySubSpace` tick of a type `1`, it'll spawn an `EntitySubSpaceSpear`](https://github.com/ExtraMeteorP/Extra-Botany/blob/e93592dd669454ebe845decdc1edd5d4c2138f1f/src/main/java/com/meteor/extrabotany/common/entity/EntitySubspace.java#L94) (which again, accepts a [`similar constructor`](https://github.com/ExtraMeteorP/Extra-Botany/blob/e93592dd669454ebe845decdc1edd5d4c2138f1f/src/main/java/com/meteor/extrabotany/common/entity/EntitySubspaceSpear.java#L47)) and during the [`EntitySubspaceSpear`'s update, it incorrectly casts the thrower as `EntityPlayer` without checking](https://github.com/ExtraMeteorP/Extra-Botany/blob/e93592dd669454ebe845decdc1edd5d4c2138f1f/src/main/java/com/meteor/extrabotany/common/entity/EntitySubspaceSpear.java#L80-L89). 

This in itself is a mod bug that Sponge has prevented potentially crashing outright on the cast and causing a full server tick crash.

I'd go ahead and submit the bug report to the Extra-Botany repository for the dev to make the simple fix (which it looks like they do have some copy pasted code from [here, that correctly checks the thrower is an instance of `EntityPlayer`](https://github.com/ExtraMeteorP/Extra-Botany/blob/e93592dd669454ebe845decdc1edd5d4c2138f1f/src/main/java/com/meteor/extrabotany/common/entity/EntitySubspace.java#L78-L85) but I'm not an expert of what their logic is attempting to do.
