### ISSUE TITLE
Entity performance

### ISSUE THREAD

**Issue by bigenergy** [SpongePowered/SpongeForge#3085]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.1.9
- Forge version: forge-1.12.2-14.23.5.2847
- Java version: 1.8.0_211
- Operating System: Ubuntu 19.04

- Plugins/Mods:
 Mods (124): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AI Improvements, Advanced Solar Panels [GamePoint Edition], Applied Energistics 2, BD Lib, BNBGamingLib, Bad Wither No Cookie! Reloaded, Baubles, Better Questing, BetterBedrockGen, Bewitchment, Bigger Packets, please !, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Blockcraftery, Blood Arsenal, Blood Magic: Alchemical Wizardry, Botania, Botania Needs These Things!, Brandon's Core, Calm Down Zombie Guy, Cases, Champions, ChickenChunks, CoFH Core, CoFH World, CodeChicken Lib, CraftTweaker JEI Support, CraftTweaker2, CustomNPCs, Cyclops Core, Draconic Additions, Draconic Evolution, DupeFix Project, Electro-Magic Tools, Ender IO, Ender IO Base, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, EnderCore, Energy Converters, Engineered Golems, EventHelper, EvilCraft, EvilCraft-Compat, Extra Cells 2, Extra Utilities 2, ExtraBotany, FoamFix, FoamFixCore, Forestry, GamePoint Mod, GamePoint Mod, GenDustry, Grand Economy, Grand Economy Currency Provider, Gravitation Suite, Guide-API, Hammer Core, Immersive Engineering, IndustrialCraft 2, Inventory Tweaks, Just Enough Energistics, Just Enough Items, Lazy AE2, LunatriusCore, MTLib, MagicBees, Mantle, Mekanism, MetalChests, MineTweakerRecipeMaker, Mod Tweaker, Mystical Lib, NoMoreRecipeConflict, OpenBackup, OpenFM, Oxygen Core, Oxygen: Exchange, Oxygen: Friends List, Oxygen: Groups, Oxygen: Mail, Oxygen: Trade, Patchouli, Phosphor Lighting Engine, PlusTiC, Project Intelligence, RF Expansion, RandomPatches, Realistic Terrain Generation, Redstone Flux, Shadowfacts' Forgelin, SpongeForge, Standard Expansion, Surge, TBone, TOP Addons, Thaumcraft, Thaumic Additions: Reconstructed, Thaumic Energistics, Thaumic Periphery, The One Probe, Thermal Expansion, Thermal Foundation, Tinkers Tool Leveling, Tinkers' Construct, ToroHUD Damage Indicators, Trade, UniDict, Varied Commodities, WanionLib, gpaddons, libnine, tileentitylimiter

 Plugins (24): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge,  FastAsyncWorldEdit, AdamantineShield, AmberShop, AutoPickup, ClearMob, DupeFixer, EconomyLite, GriefDefender, LuckPerms, MMCRestrict, NanoChat, Night-Vision-Toggle, Nucleus, PixelAutoMessages, Plan, PlayTimeCounter, Simple Scavenger, WorldEdit, spark

**Issue Description**
Updating entities on a server with a sponge takes too much time and server power, is it possible to optimize it somehow?
I get such loads with only 900-1200 entities on my server 

https://sparkprofiler.github.io/#qAhTy5HqRB
![Screenshot_1](https://user-images.githubusercontent.com/17977139/74849143-6d518b00-5349-11ea-8093-55c50d6fd974.png)

**Comment by ImMorpheus** [comment]
TrackingUtil#tickEntity is calling other methods, its selft time is really small.
From what I can see, Sponge is not the problem there. 

A Sponge plugin, however, is taking a lot of time during a Task
```
net.minecraft.server.MinecraftServer.run() 100.00% 165980ms
io.izzel.ambershop.listener.DisplayListener$PlayerChunkChangeTask.accept() 32.04% 53184ms
```
