### ISSUE TITLE
Can't catch iron golem with entity.getType().equals(EntityTypes.IRON_GOLEM)

### ISSUE THREAD

**Issue by electron93** [SpongePowered/SpongeForge#3086]
**I am currently running**

- SpongeForge version: **1.12.2-2838-7.1.10-RC3994**
- Java version: 1.8.0_242/64-bit
- Operating System: Linux

**Issue Description**

```java
    @Listener
    public void onSpawnEntity(final SpawnEntityEvent event) {
        event.getEntities().forEach(entity -> {
            final boolean isGolem = entity.getType().equals(EntityTypes.IRON_GOLEM);
            final boolean isCreeper = entity.getType().equals(EntityTypes.CREEPER);
            final boolean isZombie = entity.getType().equals(EntityTypes.ZOMBIE);

            if (isGolem) {
                this.plugin.getLogger().warn("IRON_GOLEM!!!"); // should be displayed when an iron golem spawns
            }

            if (isCreeper) {
                this.plugin.getLogger().warn("CREEPER!!!"); // works
            }

            if (isZombie) {
                this.plugin.getLogger().warn("ZOMBIE!!!"); // works
            }

            this.plugin.getLogger().warn(entity.getType().getName()
                    + " | " + entity.getType().getId()
                    + " | " + entity.getType().getTranslation().getId()
                    + " | " + entity.getType().getTranslation().get()
                    + " | " + entity.getType().getEntityClass().getName()
            );
        });
    }
```

For example:
```
[Server thread/INFO] [plugin]: e1ectron issued server command: /summon minecraft:creeper
[Server thread/WARN] [plugin]: CREEPER!!!
[Server thread/WARN] [plugin]: creeper | minecraft:creeper | entity.Creeper.name | Creeper | net.minecraft.entity.monster.EntityCreeper
[Server thread/INFO] [minecraft/DedicatedServer]: [e1ectron: Object successfully summoned]
```
```
[Server thread/INFO] [plugin]: e1ectron issued server command: /summon minecraft:zombie
[Server thread/WARN] [plugin]: ZOMBIE!!!
[Server thread/WARN] [plugin]: zombie | minecraft:zombie | entity.Zombie.name | Zombie | net.minecraft.entity.monster.EntityZombie
[Server thread/INFO] [minecraft/DedicatedServer]: [e1ectron: Object successfully summoned]
```

But this isn't working for iron golem (villager_golem):
```
[Server thread/INFO] [plugin]: e1ectron issued server command: /summon minecraft:villager_golem
[Server thread/WARN] [plugin]: villagergolem | minecraft:villagergolem | entity.generic.name |  unknown | net.minecraft.entity.monster.EntityIronGolem
[Server thread/INFO] [minecraft/DedicatedServer]: [e1ectron: Object successfully summoned]
```

And as you can see `minecraft:<id>` is different when calling `entity.getType().getId()` for an iron golem (`minecraft:villager_golem` VS `minecraft:villagergolem`) and possibly for others like this. Is this expected?

---

After some digging, I found one of the possible causes of this problem:
```
[Server thread/ERROR] [plugin]: EntityTypes.IRON_GOLEM.toString() = SpongeEntityType{id=minecraft:villager_golem, name=villager_golem, translation=SpongeTranslation{id=entity.VillagerGolem.name}, modid=minecraft, class=net.minecraft.entity.monster.EntityIronGolem}
[Server thread/WARN] [plugin]: villagergolem | minecraft:villagergolem | SpongeEntityType{id=minecraft:villagergolem, name=villagergolem, translation=SpongeTranslation{id=entity.generic.name}, modid=minecraft, class=net.minecraft.entity.monster.EntityIronGolem}
```

https://github.com/SpongePowered/SpongeCommon/blob/a9423c7ec9f2b423b52c273f7e7a23818a8f3e41/src/main/java/org/spongepowered/common/SpongeCatalogType.java#L57-L67

**Comment by JBYoshi** [comment]
This doesn't just affect iron golems. Elder guardians print `minecraft:elderguardian`, but their actual ID is `minecraft:elder_guardian`. Magma cubes are supposed to be `minecraft:magma_cube`, but they print `minecraft:lavaslime` instead. Something is very amiss.

**Comment by electron93** [comment]
Answering my question about `minecraft:<id>` differences. No, this is not the expected behavior. Correct me if I am wrong.

So what happens under the hood? Here, on line 285, some values from [`entityClassToTypeMappings`](https://github.com/SpongePowered/SpongeCommon/blob/ae9221f088b0e57749301651808785182298209a/src/main/java/org/spongepowered/common/registry/type/entity/EntityTypeRegistryModule.java#L67) are overwritten by [`registerAdditionalCatalog(EntityType extraCatalog)`](https://github.com/SpongePowered/SpongeCommon/blob/ae9221f088b0e57749301651808785182298209a/src/main/java/org/spongepowered/common/registry/type/entity/EntityTypeRegistryModule.java#L238-L243) method call.

https://github.com/SpongePowered/SpongeForge/blob/97adabd25b311d390a309be55fb391431d3a0efa/src/main/java/org/spongepowered/mod/SpongeMod.java#L280-L287

This is because the `entityName` variable has a string value of **VillagerGolem** instead of the expected **villager_golem** (as an example). 

```java
"VillagerGolem".toLowerCase(Locale.ENGLISH) // "villagergolem"
```

"**minecraft:villagergolem**" doesn't exists in the [`entityTypeMappings`](https://github.com/SpongePowered/SpongeCommon/blob/ae9221f088b0e57749301651808785182298209a/src/main/java/org/spongepowered/common/registry/type/entity/EntityTypeRegistryModule.java#L65) Map (but at the same time, "**minecraft:villager_golem**" exists).

---

@JBYoshi My solution to this problem is most likely not entirely correct, but here are the changes I made:
```patch
--- a/src/main/java/org/spongepowered/mod/SpongeMod.java
+++ b/src/main/java/org/spongepowered/mod/SpongeMod.java
@@ -278,7 +278,7 @@ public SpongeMod() throws Exception {
             }

             // Only register non-Sponge items, and those that have not already been registered.
-            if (!SpongeImpl.ECOSYSTEM_ID.equalsIgnoreCase(modId)
+            if (!SpongeImpl.ECOSYSTEM_ID.equalsIgnoreCase(modId) && !SpongeImpl.GAME_ID.equalsIgnoreCase(modId)
                     && !EntityTypeRegistryModule.getInstance()
                             .getById(modId.toLowerCase(Locale.ENGLISH) + ":" + entityName.toLowerCase(Locale.ENGLISH)).isPresent()) {
                 final SpongeEntityType entityType = new SpongeEntityType(id, entityName, modId, obj.getEntityClass(), null);
```

This fixed the problem. The `minecraft` namespace is simply ignored.

**Comment by dualspiral** [comment]
Better solution is to just not register the class if the class is already registered, rather than just ignore everything.
