### ISSUE TITLE
Server Issue - "Exception in Server Ticking" Error when SpongeForge is added to Modpack - Possible Mod Comp Issues.

### ISSUE THREAD

**Issue by SilverHatTrick** [SpongePowered/SpongeForge#3088]
**I am currently running**

- SpongeForge version: Latest (1.12.2-2838-7.1.10-RC3998)/Recommended (1.12.2-2838-7.1.9)
- Forge version: 1.12
- Java version: 64 Bit
- Operating System: Mac OS High Sierra

- Plugins/Mods:

Larger/Main Mods:

Ancient Warfare (Core, Structure, Vehicles, NPCs, and Automation)
Armourer's Workshop
Bewitchment
BiblioCraft
Blood Magic: Alchemical Wizardry (As well as Blood Arsenal)
Botania
Ice and Fire
Thaumcraft (As well as Thaumic Augmentation)
Tinker's Construct (as well as Tinkers Tool Leveling)
Pam's HarvestCraft
Quark
Rustic
Spartan Weaponry (as well as Spartan Shields, Spartan Fire, and * Shield Weaponry Arcana)
Smaller Mods:

Animania
AstikorCarts
Backpack
Better Builder's Wands
Ceramics
Chisel
Cuisine
Dynamic Sword Skills
Fairy Lights
Grappling Hooks
JJ Coats of Arms
JourneyMap
Loot Bags
MalisisDoors
Minecraft Comes Alive
Roguelike Dungeons
Trumpet Skeleton
Storage Drawers
Waystones
Tweak-Styled Mods:

AI Improvements
AppleSkin
BedFix
BetterBedrockGen
Carry On
Colytra
Controlling
Cosmetic Beds
CraftTweaker 2 (and MineTweakerRecipeMaker)
CTM
Damage Indicators
Enchantment Descriptions
Fast Leaf Decay
Gravestones
Just Enough Items (plus Block Drops, CraftTweaker JEI Support, * JEI Integration, Just Enough Pattern Banners, Just Enough Resources, Tinker's JEI,
Lapis Stays in the Enchanting Table
Ocean Floor Classic
MorePlayerModels
NetherPortalFix
Tumbleweed
Shield Parrying
Sound Filters
Waila (or TWYLA)
Wall Jump
Libraries:

AppleCore
Baubles
Chameleon
CodeChicken Lib
CraftStudio API
FTB Library
Guide-API
LLibrary
MalisisCore
Mantle
Minecraft Coder Pack
Patchouli
Placebo
Sword Skills API
Kiwi
AutoReg
Else:

Custom Main Menu
Custom NPCs
Custom Starting Gear
CT-GUI
FoamFix
FTB Backups
FTB Utilities
Gilby's Voice Chat
Item Blacklist
Login Shield
Trade
Phosphor
Vanilla Fix
WorldEdit

**Issue Description**

**I can run the modpack fine, but as soon as I add SpongeForge to my Multicraft Config Files and attempt to run the server, the crash result always comes to "Exception in server tick loop". I've tried both the latest SpongeForge version and then the Recommended SpongeForge Version only to come to those two conclusions once more.**  

**This hadn't happened before until I've added the following mods: Phosphor, VanillaFix, Blood Arsenal, Thaumic Augmentation, Quarks, Cuisine, Tool Progression, Foamfix.**

Crashlog: https://gist.github.com/SilverHatTrick/0cc60d3991826a2b0b59dc8135acb9f1

Serverlog: https://gist.github.com/SilverHatTrick/09a80251741ccc09277f4d5feba2f3fd

**Comment by gabizou** [comment]
From your server log: 
>[10:20:54] [main/INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/home/minecraft/multicraft/servers/server50118/./mods/bewitchment-1.12.2-0.0.21.5.jar Service=LaunchWrapper Env=SERVER
>Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Required mixin config mixins.common.api.json requires mixin subsystem version 0.8

The fix is quite simple:

> A mod is loading an outdated Mixin version before Sponge; please report it to the mod author!
For a temporary solution: rename the SpongeForge jar file so that it's sorted alphabetically before any other mod.
For example, rename spongeforge-1.12.2-2838-7.1.10-RC3998.jar to _aspongeforge-1.12.2-2838-7.1.10-RC3998.jar

**Comment by SilverHatTrick** [comment]
Hi Gabizou. After doing as you suggested (renaming spongeforge) so that it was in front of all the mods aside from a folder "memory_repo", I am still running into this issue.

**Comment by gabizou** [comment]
Instead of opening a new issue (and causing duplication), just reply (as you did) and include new logs showing that you had renamed the jar as suggested. 

Edit: Just because an issue is closed doesn't mean the conversation is locked, an issue can always be re-opened at a later point in time, or closed again, or re-opened, infinite times!

**Comment by SilverHatTrick** [comment]
I'm sorry about that, as I was not aware. I'll try to avoid doing this in the future o_O
