### ISSUE TITLE
Issue 3088 Not Revised

### ISSUE THREAD

**Issue by SilverHatTrick** [SpongePowered/SpongeForge#3089]
Hiya. After doing as you suggested in "https://github.com/SpongePowered/SpongeForge/issues/3088", I am still going through the same error. 

SpongeForge is renamed so it's in front of all the mods, aside from the "memory-repo" folder. 

Crashlog: https://gist.github.com/SilverHatTrick/e37e3b786cffdc455a4d03f4a6aee0f8

Serverlog: https://gist.github.com/SilverHatTrick/f3cd6f132508daf6d69b62a420c099d4

**Comment by ImMorpheus** [comment]
This is not an issue with Sponge. EasyKits is missing pjc.

`Mod easykits (EasyKits) requires [pjc]`

**Comment by SilverHatTrick** [comment]
Thank you very much!
