### ISSUE TITLE
Server crashing at startup after installing latest or recommended SpongeForge on modpack server

### ISSUE THREAD

**Issue by DymondZ** [SpongePowered/SpongeForge#3090]
**I am currently running**

- SpongeForge version: latest (1.12.2-2838-7.1.10-RC3998; happens on recommended version, too) 
- Forge version: 2847 
- Java version: 8u241  (64-bit)
- Operating System: Windows Server 2019

- Plugins/Mods: The 1.12.2 Pack v1.1.0 (see https://the-1122-pack.com/mods for a complete mod list)

**Issue Description**
After putting the spongeforge.jar in the servers mods folder the server isn't be able to start.
It seems, for my untrained eyes, that mixin is causing the issues (??). So I tried the workaround @gabizou was mentioning in Issue #3078 with no success (tried "_aspongeforge.jar",
"[[aspongeforge.jar" since my first mod in the folder begins with "[1.12.2]" and even "zzspongeforge.jar") all changes result in the server crashing much, much sooner (within the first 10-15 secs)
Server is running in offline-mode, as this is the reason I want to install spongeforge to get an authentication plugin for the modpack/forge server.

latest.log -> https://gist.github.com/DymondZ/d488834a90b66d5d522866c5f5fa5a96
crash-report.txt -> https://gist.github.com/DymondZ/1d63ae5eac4a7795652dd781fc18cac0

**Comment by ImMorpheus** [comment]
A mod is loading an outdated Mixin version before Sponge; please report it to the mod author!
For a temporary solution: rename the SpongeForge jar file so that it's sorted alphabetically before any other mod.
For example, rename spongeforge-1.12.2-2838-7.1.10-RC3998.jar to _aspongeforge-1.12.2-2838-7.1.10-RC3998.jar


From your log:

> [22:10:20] [main/INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.7.10 Source=./mods/forgeessentials-1.12.2-12.3.73-server.jar Service=LaunchWrapper Env=SERVER

**Comment by DymondZ** [comment]
You didn't really bother to read the entire post of mine, didn't you? As stated in my detailed Issue Description, I already tried this.
Here's my console output of reproducing the "fix" as this Server Launcher error doesn't seem to create a crash report and even the latest.log doesn't seem complete: 
https://gist.github.com/DymondZ/ca5c9731c7f889a469884d13b19adf3f
The Server (AMP?) is trying to restart itself a few times with no luck.

"[[spongeforge-1.12.2-2838-7.1.10-RC3998.jar" is now the first file in my "mods" folder, followed by "[1.12]bspkrsCore-universal-7.6.0.1.jar", then "[1.12]TreeCapitator-client-1.43.0.jar" and then "Advanced Machines-61.0.1.jar" etc. 
I've even tried renaming it to _aspongeforge-1.12.2-2838-7.1.10-RC3998.jar (which would make it the 3rd in the list) and this obviously doesn't help either.

> From your log:
>[22:10:20] [main/INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.7.10 >Source=./mods/forgeessentials-1.12.2-12.3.73-server.jar Service=LaunchWrapper Env=SERVER

Will try to remove forgeessentials and report back.

**Comment by gabizou** [comment]
So since the log you provided is pointing to the server actually starting with Mixin 0.8 properly, can you give a complete log? (not whatever that reduced log you linked, because that's not even showing when the server stops, just some errors that doesn't stop the server from starting).

**Comment by ImMorpheus** [comment]
I did read you report and you didn't rename the sponge jar.

From your log: 

> [22:10:20] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from spongeforge.jar

I don't know if you posted the wrong log, but my answer was based on the evidence you showed.

From your second log: 

> [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: Caused by: java.lang.NoSuchMethodError: org.spongepowered.asm.launch.platform.MixinPlatformManager.addContainer(Ljava/net/URI;)Lorg/spongepowered/asm/launch/platform/MixinContainer;
> [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: at com.forgeessentials.core.preloader.FELaunchHandler.acceptOptions(FELaunchHandler.java:91)

Remove forgessentials

EDIT: gabi beat me to it

**Comment by DymondZ** [comment]
Sorry I didn't posted that log at all as it was causing the server to shutdown sooner as without renaming. That was my misconception. 
Here is the latest crash report after renaming spongeforge-*.jar to [[spongeforge-*.jar and renaming forgeessentials*.jar to forgeessentials*.jar.bak : https://gist.github.com/DymondZ/ec2b6fc033cd53f1673575d9104133f9

@gabizou It creates a new log in the logs folder everytime the server is crashing, so here is my complete console output: https://gist.github.com/DymondZ/f48af8863a90aa03fe0c901751e71e2c


Thanks for your help and patience.

**Comment by gabizou** [comment]
So, your log shows that JustEnoughID's is also installed, and that crash is very much the issue that https://github.com/SpongePowered/SpongeForge/issues/3069 is having. Unfortunately, JEID is trying to hook to some internals to Mixins without checking versions and because we updated our own library, well, you can read the issue to get a better understanding. I can understand if you need JEID for some mods, but we're not going to downgrade Mixin just to keep compatibility for other mod devs trying to hack around our own library as recklessly as JEID is doing.

**Comment by DymondZ** [comment]
So I simply installed 7.1.8 and now everything works fine including my desired plugins. Thanks for your help!

**Comment by gabcraftia** [comment]
> So I simply installed 7.1.8 and now everything works fine including my desired plugins. Thanks for your help!

yea this helped me to thanks for the reply i was stuck at this for 4 hours
