### ISSUE TITLE
Crash with Tick Profiler and Sponge

### ISSUE THREAD

**Issue by Aiidoneus** [SpongePowered/SpongeForge#3096]
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2838-7.1.11-RC4004.jar
- Forge version: forge-1.12.2-14.23.5.2847-universal.jar
- Java version: 1.8.0_201
- Operating System: Linux

- Plugins/Mods:
-No Plugins installed
- Only Mod is Tickprofiler 1.12-0.0.7

**Issue Description**
I was updating my production servers on my network to a more recent version of Spongeforge when I came across a crashing issue. I narrowed it down to TickProfiler being the culprit by using a test server and eliminating all plugins and mods. I disable TickProfiler and the server starts. I updated from Sponge 1.12.2-2838-7.1.8-RC3970.jar if that helps. I could try narrowing it down a bit further but could use a bit of guidance on which versions I should try. 

Crash report:
https://gist.github.com/Aiidoneus/b0fdb582ad7149748d499e71ba5864de

**Comment by clienthax** [comment]
Tickprofiler is currently incompatible with latest sponge versions due to the mixin 0.8 update, see their tracker.
