### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Spontini** [SpongePowered/SpongeForge#3099]
.

**Comment by Explosivee** [comment]
It turns out HammerCore + ExpandedEquivalence causes this problem.
ExpandedEquivalence-1.12.2-13r.jar
HammerCore-1.12.2-2.0.6.9.jar

I guess these both isn't compatible with Sponge anymore.

**Comment by Explosivee** [comment]
I've managed to fix the issue by disabling TickSlip feature in hammercore.
