### ISSUE TITLE
1.12.2 dupe with lamas and asses

### ISSUE THREAD

**Issue by kasdo** [SpongePowered/SpongeForge#3101]
Latest version of spongeforge
Video: https://www.youtube.com/watch?v=ZGnA-lip6HQ

**Comment by dualspiral** [comment]
We're not going to watch a video without all the other required fields in our template which you deleted. Also, "latest" is not a version.

I'm closing this. If you edit the issue, filling out the template and including text instructions, then I'll reopen.
