### ISSUE TITLE
Server Running Project Ozone 3 with Sponge crashes almost instantly

### ISSUE THREAD

**Issue by HadenOverlord** [SpongePowered/SpongeForge#3104]
- SpongeForge version:  spongeforge-1.12.2-2838-7.1.10
Im using this version cause this and lastest are using the same forge version but this is the recommended version on the downloads page.
- Forge version:  forge-1.12.2-14.23.5.2847-universal
- Java version:  Java 8 update 241
- Operating System: Windows 10 

- Plugins/Mods:

ClearMob plugin and Sponge  

Project Ozone 3 ver 3.2.52 
Mods:
Resource Loader (by lumien231)
Botania: Garden of Glass (by Vazkii)
ZeroCore (by ZeroNoRyouki)
Morpheus (by Quetzi)
CoFH World (by TeamCoFH)
CoFH Core (by TeamCoFH)
Chisels & Bits (by AlgorithmX2)
TESLA (by Darkhax)
AbyssalCraft (by Shinoow)
TamModized (by Tamaized)
Brandon's Core (by brandon3055)
Clumps (by jaredlll08)
LunatriusCore (by Lunatrius)
Cyclops Core (by kroeser)
RFTools Control (by McJty)
YABBA (by LatvianModder)
Draconic Evolution (by brandon3055)
Mouse Tweaks (by YaLTeR97)
InstantUnify (by KidsDontPlay)
Just Enough Items (JEI) (by mezz)
Integration Foregoing (by Jacky1356400)
Better Advancements (by Way2muchnoise)
Dimensional Edibles (by Jacky1356400)
ModTweaker (by jaredlll08)
Rock Candy (by Radient_Sora)
Thermal Dynamics (by TeamCoFH)
PackMode (by SkySomm)
OpenModularTurrets (by Keridos)
Mod Name Tooltip (by mezz)
Teslafied (by TheRealp455w0rd)
Better Questing - Standard Expansion (by Funwayguy)
OMLib (by Keridos)
BetterFps (by Guichaguri)
Client Tweaks (by BlayTheNinth)
Immersive Petroleum (by theFlaxbeard)
ExtraCells2 (by Destroyer7128)
Mob Grinding Utils (by Vadis365)
Waystones (by BlayTheNinth)
EverlastingAbilities (by kroeser)
Lord Craft (by Cobbs_3)
Chance Cubes (by turkey2349)
Ore Excavation (by Funwayguy)
Land Craft (by Landmaster_phuong0429)
Grue (by Shinoow)
Custom Main Menu (by lumien231)
Dark Utilities (by Darkhax)
Moo Fluids (by TheRoBrit)
Chameleon (by jaquadro)
Simple Void World (by modmuss50)
Mantle (by mDiyo)
Pam's HarvestCraft (by MatrexsVigil)
Tinkers' Complement (by KnightMiner)
Crafting Tweaks (by BlayTheNinth)
VoidCraft (by Tamaized)
Storage Drawers (by jaquadro)
InGame Info XML (by Lunatrius)
Solar Flux Reborn (by Zeitheron)
MPUtils (by GenDeathrow)
Mystical Agradditions (by BlakeBr0)
AbyssalCraft Integration (by Shinoow)
RiteClicker Mod (by P3PSIE)
Additional Resources (by Portablejim)
Twerk Sim 2K16 (by Funwayguy)
Natura (by mDiyo)
TipTheScales (by jaredlll08)
TheDragonLib (by sokratis12GR)
ConnectedTexturesMod (by tterrag1098)
Shadowfacts' Forgelin (by shadowfactsmc)
Bookshelf (by Darkhax)
ProjectE (by sinkillerj)
Tiny Progressions (by Kashdeya)
JourneyMap (by techbrew)
The Twilight Forest (by Benimatic)
Hwyla (by TehNut)
BiblioCraft (by JDSinclair)
Audio Death (by Portablejim)
Hammer (Lib) Core (by Zeitheron)
ModelLoader (by cout970)
QuantumStorage (by Gigabit1011)
CraftTweaker (by jaredlll08)
Iron Chests (by progwml6)
Magneticraft (by cout970)
Karat Garden (by MrAmericanMike)
Stackie (by Lunatrius)
Mystical Agriculture (by BlakeBr0)
Compacter (by bdew)
Better Builder's Wands (by Portablejim)
RFTools Dimensions (by McJty)
AttributeFix (by Darkhax)
PlusTiC (by Landmaster_phuong0429)
MCMultiPart (by amadornes)
Chicken Chunks 1.8.+ (by covers1624)
Diet Hoppers (by RWTema)
Chisel (by tterrag1098)
BdLib (by bdew)
Quark (by Vazkii)
Woot (by Ipsis)
Industrial Foregoing (by Buuz135)
Knob Control (by Kashdeya)
Netherending Ores (by ic_trab)
/dank/null (by TheRealp455w0rd)
Random Things (by lumien231)
Controlling (by jaredlll08)
Guide-API (by TehNut)
Ender Storage 1.8.+ (by covers1624)
Stacksize (by wwrpg)
Modular Diversity (by BordListian)
Extreme Reactors (by ZeroNoRyouki)
MPUtils Basic Tools (by GenDeathrow)
Waila Harvestability (by squeek502)
Reliquary v1.3 (by P3pp3rF1y)
Bonsai Trees (by Davenonymous)
Neat (by Vazkii)
Fence Jumper (by TheRealp455w0rd)
Redstone Flux (by TeamCoFH)
Inventory Tweaks (by Kobata)
Redstone Arsenal (by TeamCoFH)
AE2 Stuff (by bdew)
Botania (by Vazkii)
Open Modular Passive Defense (by Keridos)
Farming for Blockheads (by BlayTheNinth)
Baubley Heart Canisters (by Radient_Sora)
XNet (by McJty)
Ceramics (by KnightMiner)
FTB Library (by FTB)
Thermal Foundation (by TeamCoFH)
Tesla Core Lib (by Face_of_Cat)
Unforgiving Void (by The_Fireplace)
The Lost Cities (by McJty)
WanionLib (by WanionCane)
Immersive Engineering (by BluSunrize)
p455w0rd's Library (by TheRealp455w0rd)
MTLib (by jaredlll08)
Baubles (by azanor)
UniDict (by WanionCane)
LandCore (by Landmaster_phuong0429)
Wither Skeleton Tweaks (by Shadows_of_Fire)
Tinkers Construct (by mDiyo)
AutoRegLib (by Vazkii)
CodeChicken Lib 1.8.+ (by covers1624)
Overloaded (by cjm721)
Ex Nihilo: Creatio (by BloodWorkXGaming)
Actually Additions (by Ellpeck)
Cucumber Library (by BlakeBr0)
Astral Sorcery (by HellFirePvP)
Better Questing Triggerer (by MrAmericanMike)
Hunting Dimension (by Darkhax)
PneumaticCraft: Repressurized (by desht)
DiscordSuite (by HRZNStudio)
Avaritia 1.1x (by brandon3055)
YNot (by asiekierka)
Placebo (by Shadows_of_Fire)
Toast Control (by Shadows_of_Fire)
OpenModsLib (by OpenMods)
OpenBlocks (by OpenMods)
WaitingTime (by jaredlll08)
Enderman Evolution (by TheRealp455w0rd)
Simply Jetpacks 2 (by Tomson124)
Tweakers Construct (by RCXcrafter)
Mapmaker's Gadgets (by Tmtravlr)
Simple Sponge (by Jacky1356400)
McJtyLib (by McJty)
Corail Tombstone (by Corail31)
FastWorkbench (by Shadows_of_Fire)
Blood Magic (by WayofTime)
Forge MultiPart CBE (by covers1624)
Soot (by BordListian)
FoamFix for Minecraft (by asiekierka)
Progressive Bosses (by Insane96)
LootTableTweaker (by Darkhax)
CreativeCore (by CreativeMD)
ItemPhysic Full (by CreativeMD)
Thermal Innovation (by TeamCoFH)
Portality (by Buuz135)
SkyLandsForge (by Asd1995sse)
MrTJPCore (by Mr_TJP)
Project Red - Base (by Mr_TJP)
Project Red - World (by Mr_TJP)
Project Red - Mechanical (by Mr_TJP)
Broken Wings (by quat1024)
No Mob Spawning on Trees (by oldjunyi)
Galacticraft Tweaker (by MJRLegends)
MJRLegends Lib (by MJRLegends)
ExtraPlanets (by MJRLegends)
Applied Energistics 2 (by AlgorithmX2)
Epic Siege Mod (by Funwayguy)
InfinityLib (by InfinityRaider)
AgriCraft (by InfinityRaider)
Avaritia Tweaks (by Jacky1356400)
Translocators 1.8.+ (by covers1624)
Just Enough Petroleum (by BordListian)
KleeSlabs (by BlayTheNinth)
B.A.S.E (by lanse505)
Mekanism Generators (by aidancbrady)
Mekanism Tools (by aidancbrady)
Mekanism (by aidancbrady)
Extended Crafting (by BlakeBr0)
Better Questing (by Funwayguy)
Aroma1997s Dimensional World (by Aroma1997)
Aroma1997Core (by Aroma1997)
ContentTweaker (by jaredlll08)
Cooking for Blockheads (by BlayTheNinth)
Thermal Solars (by JoltEffect)
RFTools (by McJty)
NuclearCraft (by TLJGames)
Wawla - What Are We Looking At (by Darkhax)
Tinkers' Tool Leveling (by bonusboni)
Reborn Core (by modmuss50)
Expanded Equivalence (by Zeitheron)
NoFog (by Tommeh2)
More Overlays (by feldim2425)
QuantumFlux (by FantasyTeddy)
Mystical Agriculture Tiered Crystals (by Electrolyte)
LibEx (by LogicTechCorp)
NetherEx (by LogicTechCorp)
Equivalent Integrations (by pkmnfrk)
Embers Rekindled (by BordListian)
ManaVisualizer (by ExtraMeteorP)
Simple Trophies (by quat1024)
MysticalLib (by epicsquid319)
Blockcraftery (by epicsquid319)
Ender IO Endergy (by tterrag1098)
TickProfiler (by minimallycorrect)
Thermal Expansion (by TeamCoFH)
The Erebus (by Vadis365)
AE2 Wireless Terminal Library (by TheRealp455w0rd)
Wireless Crafting Terminal (by TheRealp455w0rd)
Unloader (by Unnoen)
BiomeTweaker (by superckl)
BiomeTweakerCore (by superckl)
OpenComputers (by SangarWasTaken)
Ozone Resources (by TheCazadorSniper)
Just Enough Energistics (JEE) (by TheRealp455w0rd)
Modular Machinery (by HellFirePvP)
Akashic Tome (by Vazkii)
Morph-o-Tool (by Vazkii)
AppleCore (by squeek502)
AppleSkin (by squeek502)
ElecCore (by Elec332)
NotEnoughIDs (by fewizz)
Project EX (by LatvianModder)
EnderCore (by tterrag1098)
Ender IO (by CrazyPants_MC)
Ender Tweaker (by Shadows_of_Fire)
ArmorPlus (by sokratis12GR)
Mike's Mods Library (by pkmnfrk)
Furnace Overhaul (by TheCazadorSniper)
RandomPatches (by TheRandomLabs)
ReAuth (by TechnicianLP)
Apotheosis (by Shadows_of_Fire)
Extra Utilities (by RWTema)
LootBags (by Malorolam)
Building Gadgets (by direwolf20)
Wasaila (by mrbysco)
FTB Utilities: Backups (by LatvianModder)
FTB Utilities (by FTB)
Overloaded Armor Bar (by tfarecnim)

**Issue Description**
When Starting the server it will run for a bit and them crash.

Lastest  Log:       
https://gist.github.com/HadenOverlord/a520ab5f6a1648b126a1bbaf121ff506
Debug Log:
https://gist.github.com/HadenOverlord/1a5c092b9c7afe3e26e004acba7dada9

**Comment by Krayon0** [comment]
Having the same issue, trying to run PO3 and spongeforge same versions as he is and it is crashing basically straight off the bat.
https://paste.gg/p/anonymous/c9f486e5d9794ac99abc17061f447dc0
Debug log ^

Edit:
I went through the log and all I figured out was that phospor lighting wasnt happy with sponge using their own so they wanted it disabled(disabled it) nothing changed and then mixin had some injection failure which I have no clue about.

**Comment by clienthax** [comment]
enable World.ITickable.Override in asm/hammercore.xml and try again.

also
[10:02:14] [main/WARN] [Phosphor Plugin]: We cannot currently detect if you are using Sponge's async lighting patch. If you have not already done so, please disable it in your configuration file for SpongeForge or you will run into issues.
