### ISSUE TITLE
gamerule ShowDeathMessages doesnt work

### ISSUE THREAD

**Issue by TheKlimoT** [SpongePowered/SpongeForge#3105]
-SPONGE - spongeforge-1.12.2-2838-7.1.11-RC4007(1).jar
-JAVA - 8 231
-LINUX Debian 9
The gamerule the showdeathmessages doesnt work.

**Comment by ImMorpheus** [comment]
Not able to reproduce on SF (updated to https://github.com/SpongePowered/SpongeForge/commit/272574e5da45bcc0c19e97e71d7dd985d1e158e5)

Keep in mind the gamerule is `showDeathMessages`
