### ISSUE TITLE
Config-Enabled is not exist in Global.Conf

### ISSUE THREAD

**Issue by Spontini** [SpongePowered/SpongeForge#3106]
**I am currently running**

- SpongeForge version: SpongeForge 1.12.2 2838 7.1.10
- Forge version: Forge-1.12.2-14.23.5.2847
- Java version: Java8 Update 241
- Operating System: Ubuntu 18.04 LTS

This is all i got under `Commands{}` but according to here https://docs.spongepowered.org/stable/en/server/getting-started/configuration/sponge-conf.html
there should be something called as `config-enabled`

  ```
  commands {

        # Command aliases will resolve conflicts when multiple plugins request a specific command, 
        # Correct syntax is <unqualified command>=<plugin name> e.g. "sethome=homeplugin"
        aliases {}
        # Defines how Sponge should act when a user tries to access a command they do not have
        # permission for
        command-hiding {
            # If this is true, when a user tries to tab complete a command, or use "/sponge which" or 
            # "/sponge:help" this prevents commands a user does not have permission for from being completed.
            # 
            # Note that some commands may not show up during tab complete if a user does not have permission
            # regardless of this setting.
            hide-on-discovery-attempt=true
            # If this is true, when a user tries to use a command they don't have permission for, Sponge
            # will act as if the command doesn't exist, rather than showing a no permissions message.
            hide-on-execution-attempt=false
        }
        # Some mods may not trigger a permission check when running their command. Setting this to
        # true will enforce a check of the Sponge provided permission ("<modid>.command.<commandname>").
        # Note that setting this to true may cause some commands that are generally accessible to all to
        # require a permission to run.
        # 
        # Setting this to true will enable greater control over whether a command will appear in
        # tab completion and Sponge's help command.
        # 
        # If you are not using a permissions plugin, it is highly recommended that this is set to false
        # (as it is by default).
        enforce-permission-checks-on-non-sponge-commands=false
        # Patches the specified commands to respect the world of the sender instead of applying the 
        # changes on the all worlds.
        multi-world-patches {
            ""=true
            defaultgamemode=true
            difficulty=true
            gamerule=true
            seed=true
            setdefaultspawnpoint=true
            time=true
            toggledownfall=true
            weather=true
            worldborder=true
        }
    }

```

**Comment by Explosivee** [comment]
Update: I've heard that if we go into `config>sponge>worlds>DIM>world.conf` and copy paste this should disable that dimension but it does not work.

`# 1.0
# 
# # If you need help with the configuration or have any questions related to Sponge,
# # join us at the IRC or drop by our forums and leave a post.
# 
# # IRC: #sponge @ irc.esper.net ( https://webchat.esper.net/?channel=sponge )
# # Forums: https://forums.spongepowered.org/
# 
sponge{
	world {
        # If 'true', this world will load on startup.
        load-on-startup=false
        # If 'true', this world will be registered.
        world-enabled=false
    }
}`

**Comment by ryantheleach** [comment]
This ticket's already been closed, but to anyone finding it in the future.

https://docs.spongepowered.org/stable/en/server/getting-started/configuration/sponge-conf.html states:

config-enabled
**This setting does nothing in the global config**. In dimension/world configs, it allows the config to override config(s) that it inherits from

It's purpose is to enable-disable per world and per-dimension configuration/inheritance.
