### ISSUE TITLE
Resource Hogs Truffle

### ISSUE THREAD

**Issue by Spontini** [SpongePowered/SpongeForge#3107]
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.1.10
- Forge version: 1.12.2-14.23.5.2838
- Java version: Java 8
- Operating System: Ubuntu 18.04 LTS
Logs: https://paste.ubuntu.com/p/q45NHRVKNg/

In SkyFactory4 the mod called as `Resource Hogs` can't drop a Truffle.

**Comment by clienthax** [comment]
Where are the logs :(

**Comment by Spontini** [comment]
It's so easy to reproduce this bug.

1-) Make a SF4 Server
2-) Use Sponge v1.12.2-2838-7.1.10
3-) Get a resource hog and wait for untill it drops a Truffle (It never will)

**Comment by Spontini** [comment]
With Sponge: https://streamable.com/oni4i
Without Sponge: https://streamable.com/a7j0x

(Sorry for the low fps, idk why it came like that into the video)

**Comment by Explosivee** [comment]
Here is the logs: https://paste.ubuntu.com/p/FNcpV7zGfH/

**Comment by Spontini** [comment]
Here is the Logs just in case;
https://paste.ubuntu.com/p/q45NHRVKNg/
Logs After Removing GWMCrates/ GwmLIB/ Cosmetics
https://paste.ubuntu.com/p/hbn8RMq7x7/

**Comment by Spontini** [comment]
Looks like it's a plugin, i havent found which one it is yet.

**Comment by Spontini** [comment]
After i removed every single plugins one by one i've found that Nucleus does this issue.
https://github.com/NucleusPowered/Nucleus/issues/1466
