### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by niklas2233** [SpongePowered/SpongeForge#3109]
**I am currently running**
- SpongeForge version: 1.12.2-2838-7.1.11-RC4007 
- Forge version: 14.23.5.2838
- Java version:  1.8.0.51
- Operating System: windows 10

**Issue Description**
so when i start RLCraft with spongeforge installed it crashes. im have tried to search on google but i couldn't find any help

https://gist.github.com/niklas2233/2eb05d28191cc98e9fa0d3ab15391ec8

**Comment by clienthax** [comment]
Remove tickprofiler, it has a outdated mixin dependency.

https://github.com/MinimallyCorrect/ModPatcher/issues/20
