### ISSUE TITLE
Sponge Server crashing on Tropicraft Dimention

### ISSUE THREAD

**Issue by xxsuperdreamxx** [SpongePowered/SpongeForge#3112]
**I am currently running**

- SpongeForge version: 
spongeforge-1.12.2-2838-7.1.8.jar (Because of JustEnoughIDs)
- Forge version: 
1.12.2 (modded) forge-14.23.5.2838
- Java version: 
Vesion 8 Update 241 (build 1.8.0_241-b07)
- Operating System:
Microsoft Windows 10 Enterprise Insider Preview
- Plugins/Mods:
Plugins :
Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, CatClearLag, Holograms, LuckPerms, MMCRestrict, MMCTickets, MagiBridge, Nucleus, PlaceholderAPI, Plan, UltimateChat, WorldEdit

Mods:
Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AI Improvements, Aether Continuation, Aether Legacy, Akashic Tome, AppleCore, AppleSkin, Aquaculture, Aroma1997's Dimensional World, Aroma1997Core, Atum 2, AutoRegLib, Baubles, Better Diving, BiblioCraft, Bigger Packets, please !, Biome Bundle, Bloodmoon, Bonsai Trees, Bountiful, Building Gadgets, Cavern II, Chameleon, Chance Cubes, Charm, Chest Transporter, ChickenChunks, Chisel, Clumps, CodeChicken Lib, Colossal Chests, Comforts, Cooking for Blockheads, Corail Tombstone, CosmeticArmorReworked, Creeper Confetti, Cucumber Library, Customized Dungeon Loot, Cyclic, Cyclops Core, Dimensional Doors, Disenchanter, Doggy Talents, Doomlike Dungeons, DungeonTactics, Electroblob's Wizardry, Embers Rekindled, Embersified, Engineer's Workshop Reborn, Extra Alchemy, Extra Utilities 2, FTB Backups, FTB Library, FTB Money, FTB Quests, FTB Utilities, FastFurnace, FastWorkbench, FoamFix, FoamFixCore, Forge Endertech, Heroic Armory, Hooked, Ice and Fire, Improved Backpacks, Infernal Mobs, Inventory Pets, Item Filters, IvToolkit, Jack-O'-Launcher, JourneyMap, Just Enough Items, JustEnoughIDs, LLibrary, Land Manager, Let's Encrypt Craft, Level Up! Reloaded, LibrarianLib, LibrarianLib Stage 2, LibraryEx, LimeLib, Living Enchantment, Login Shield, Lost Aether Content, LunatriusCore, Mega Loot, Meldexun's Extra Spells, Minerva Library, Mowzie's Mobs, Mystical Agriculture, Mystical Mechanics, Nature's Compass, NetherEx, NetherPortalFix, NoMoreRecipeConflict, Nomadic Tents, OTG Core, Open Terrain Generator, OpenBlocks, OpenModsLib, OpenModsLib Core, Ordinary Coins, OreExcavation, OreLib Support Mod, Pam's HarvestCraft, Patchouli, Phosphor Lighting Engine, PiTweaks, Placebo, Portable Crafting, Potion Core, Prefab, Progressive Bosses, Project: Vibrant Journeys, Pyramid Plunder, Quality Tools, Quark, Quark Oddities, Random Loot Mod, Random Things, RandomPatches, RandomTweaks, Reborn Core, Recurrent Complex, Reliquary, Roguelike Dungeons, Rope Bridge, Rough Tweaks, Rustic, Scaling Health, Shadowfacts' Forgelin, Sign Post, Silent Lib, Simple Storage Network, Skewers, Spartan Shields, Spawn Temple, Spice of Life: Carrot Edition, SpongeForge, Stackie, Storage Drawers, Straw Golem, Stuff A Sock In It, Subterranean Switcheroo, SwingThroughGrass, TerraCart Reloaded, Thaumcrafft Inventory Scanning, Thaumcraft, The Beneath, The Betweenlands, The Eight Fabled Blades, The Twilight Forest, Totemic, Tropicraft, Unique Crops, V-Tweaks, Vanilla Tweaks, VanillaFix, ViesCraft, Waystones

Server log:
[Pastebin](https://pastebin.com/qhYP6sek)
Please ignore the MMCTiket the company which hosted my database server crashed and they are not working because of corona

Issue:
When trying to teleport to tropicraft the server is crashing and because my player was in the tropicraft dim I need to load up a previous backup to fix the issue

**Comment by clienthax** [comment]
If you are using OTG you need to pregenerate the world without sponge, then remove it and add sponge.
