### ISSUE TITLE
Crash with MMD OreSpawn

### ISSUE THREAD

**Issue by D3nnis3n** [SpongePowered/SpongeForge#3113]
spon**I am currently running**

- SpongeForge version:  RC4007
- Forge version: 2847
- Java version: 1.8.0_242
- Operating System: Ubuntu 18.04

- Plugins/Mods:
> Plugins (7): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, LuckPerms, Nucleus, Pieconomy

> Mods (243): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, A Lib, Additional Banners, Advanced Chimneys, Advanced Rocketry, Advanced Rocketry Core, AlcatrazCore, Alchemistry, Animania, AppleCore, AppleSkin, ArchitectureCraft, Armory Expansion, Armory Expansion - Construct's Armory, Armory Expansion - Custom Materials, Armory Expansion - Ice and Fire, Armory Expansion - MatterOverdrive, Automated Redstone, BD Lib, Base Metals, Base Minerals, Better Questing, Better Questing Quest Book, BiblioCraft, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, BuildCraft, BuildCraft Builders, BuildCraft Compat, BuildCraft Energy, BuildCraft Factory, BuildCraft Lib, BuildCraft Robotics, BuildCraft Silicon, BuildCraft Transport, CD4017BE_lib, Carry On, Chameleon, Charcoal Pit, Charset, ChickenChunks, Chisels & Bits, Clay Soldiers Mod, CodeChicken Lib, Combined Potions, CompatSkills, Construct's Armory, Corail Pillar, Corail Pillar - Forestry Extension, Corail Tombstone, CoroUtil Library, CraftStudio API, CraftTweaker JEI Support, CraftTweaker2, Crafting Tweaks, CreativeCore, CreativeCoreDummy, CustomNPCs, Cyclic, Decocraft, Dense Metals, Disenchanter, Dynamic Surroundings, Dynmap, End Metals, Ender Compass, Ender IO, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, Ender IO endergy, EnderCore, Erosion, Extended Mod Config, Extended Renderer, Fairy Lights, Fast Leaf Decay, Felling, Flat Colored Blocks, FoamFix, FoamFixCore, Food Funk, Forestry, Forge Endertech, Forge Microblocks, Forge Multipart CBE, GasConduits, GenDustry, Good Ol' Currency, Guide-API, Hammer Core, Harvest Tweaks, ICBM-Classic, Immersive Engineering, Immersive Petroleum, Immersive Railroading, Immersive Tech, Improvable Skills, Industrial Foregoing, Infernal Mobs, InstantUnify, Iron Chest, Just Enough Items, Just Enough Pattern Banners, Lapis Stays in the Enchanting Table, Level Up! Reloaded, Localized Weather & Storms, Logistical Automation, Logistics Pipes, LootTweaker, MCMultiPart, MMD Buckets, MMDLib, MTLib, MachineMuse's Modular Powersuits, Malisis Blocks, MalisisCore, MalisisDoors, Mantle, McJtyLib, Mekanism, Mekanism: Generators, Mekanism: Tools, MetalChests, MineMenu, MineTweakerRecipeMaker, Minecraft Multipart Plugin, Moar Boats, Mod Tweaker, Modern Lights, Modern Metals, Modern Warfare 2.0 Contagion, Modular ForceField System, MrTJPCore, Multi Mine, Multi-Storage, Nether Metals, NoMoreRecipeConflict, Not Enough Items, NotEnoughIDs, NuclearCraft, Numina, OMLib, OnlinePictureFrame, Open Modular Passive Defense, Open Modular Turrets, OpenComputers, OpenComputers (Core), OreLib Support Mod, OreSpawn, Pam's HarvestCraft, PneumaticCraft: Repressurized, Pollutant Pump, Pollution of the Realms, Practical Logistics 2, ProjectRed Core, ProjectRed Expansion, ProjectRed Exploration, ProjectRed Fabrication, ProjectRed Illumination, ProjectRed Integration, ProjectRed Relocation, ProjectRed Transmission, ProjectRed Transportation, RFTools, RFTools Control, Railcraft, Realistic Torches, Reborn Core, RebornStorage, Reconstructor, Redstone Flux, Refined Storage, Refined Storage Addons, Reskillable, Rough Tweaks, SanAndreasPs Mod Library, SanAndreasPs Player Model, Scannable, Serene Seasons, SeriousCreepers Loot Chests, Shadowfacts' Forgelin, ShetiPhian-Core, Signals, Signpost, SonarCore, SpongeForge, Standard Expansion, Steve's Carts 2, Storage Boats Mod, Storage Drawers, Storage Drawers Extras, Super Sound Muffler: Revived, TBone, TOP Addons, TechStack's Heavy Machinery Mod, Tesla Core Lib, Tesla Core Lib Registries, The One Probe, The Spice of Life, The SpotLight Mod, Thut Core, Thut's Elevators, ThutCore Compat, Tinker's Forging, Tinkers Tool Leveling, Tinkers' Construct, Tool Belt, Track API, Trade, Ultimate Car Mod, UniDict, Universal Remote, UniversalModCore, Up-Sizer, Vanilla Builders Extension, Vials, Villager Trade Tables, Vulpes library, WanionLib, Water Control Extreme, Waystones, World Utils, WorldEdit, Wumple Util Library, Zero CORE, derfl007's Road Mod, projectred-compat

**Issue Description**
MMD OreSpawn seemingly tried to generate a chunk and something went wrong with Sponge. The Crashlog suggested this is a Sponge issue, so i posted it here.

https://gist.github.com/D3nnis3n/d2d9cc1e01f7a23d7bac429243a07f14 - Log
https://gist.github.com/D3nnis3n/0d8a7969b07dcf1d227cd1b095253ac1 - Crash

**Comment by D3nnis3n** [comment]
I can confirm that this issue neither happens with SpongeForge but without MMD OreSpawn nor without Sponge but with MMD OreSpawn. It happens on generation of any new chunk while playing.

**Comment by clienthax** [comment]
Very tempted to say this is a bug in the mod that sponge is catching.

**Comment by D3nnis3n** [comment]
The newest version of MMD OreSpawn actually fixes this, but i got a new issue with another mod, so i will open a seperate issue for that.
