### ISSUE TITLE
FoodFunk (+ WumpleUtil) causing crash with Spongeforge

### ISSUE THREAD

**Issue by D3nnis3n** [SpongePowered/SpongeForge#3114]
**I am currently running**

- SpongeForge version:  RC4007
- Forge version: 2847
- Java version: 1.8.0_242
- Operating System: Ubuntu 18.04

- Plugins/Mods:
> Plugins (7): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, LuckPerms, Nucleus, Pieconomy

> Mods (243): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, A Lib, Additional Banners, Advanced Chimneys, Advanced Rocketry, Advanced Rocketry Core, AlcatrazCore, Alchemistry, Animania, AppleCore, AppleSkin, ArchitectureCraft, Armory Expansion, Armory Expansion - Construct's Armory, Armory Expansion - Custom Materials, Armory Expansion - Ice and Fire, Armory Expansion - MatterOverdrive, Automated Redstone, BD Lib, Base Metals, Base Minerals, Better Questing, Better Questing Quest Book, BiblioCraft, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, BuildCraft, BuildCraft Builders, BuildCraft Compat, BuildCraft Energy, BuildCraft Factory, BuildCraft Lib, BuildCraft Robotics, BuildCraft Silicon, BuildCraft Transport, CD4017BE_lib, Carry On, Chameleon, Charcoal Pit, Charset, ChickenChunks, Chisels & Bits, Clay Soldiers Mod, CodeChicken Lib, Combined Potions, CompatSkills, Construct's Armory, Corail Pillar, Corail Pillar - Forestry Extension, Corail Tombstone, CoroUtil Library, CraftStudio API, CraftTweaker JEI Support, CraftTweaker2, Crafting Tweaks, CreativeCore, CreativeCoreDummy, CustomNPCs, Cyclic, Decocraft, Dense Metals, Disenchanter, Dynamic Surroundings, Dynmap, End Metals, Ender Compass, Ender IO, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, Ender IO endergy, EnderCore, Erosion, Extended Mod Config, Extended Renderer, Fairy Lights, Fast Leaf Decay, Felling, Flat Colored Blocks, FoamFix, FoamFixCore, Food Funk, Forestry, Forge Endertech, Forge Microblocks, Forge Multipart CBE, GasConduits, GenDustry, Good Ol' Currency, Guide-API, Hammer Core, Harvest Tweaks, ICBM-Classic, Immersive Engineering, Immersive Petroleum, Immersive Railroading, Immersive Tech, Improvable Skills, Industrial Foregoing, Infernal Mobs, InstantUnify, Iron Chest, Just Enough Items, Just Enough Pattern Banners, Lapis Stays in the Enchanting Table, Level Up! Reloaded, Localized Weather & Storms, Logistical Automation, Logistics Pipes, LootTweaker, MCMultiPart, MMD Buckets, MMDLib, MTLib, MachineMuse's Modular Powersuits, Malisis Blocks, MalisisCore, MalisisDoors, Mantle, McJtyLib, Mekanism, Mekanism: Generators, Mekanism: Tools, MetalChests, MineMenu, MineTweakerRecipeMaker, Minecraft Multipart Plugin, Moar Boats, Mod Tweaker, Modern Lights, Modern Metals, Modern Warfare 2.0 Contagion, Modular ForceField System, MrTJPCore, Multi Mine, Multi-Storage, Nether Metals, NoMoreRecipeConflict, Not Enough Items, NotEnoughIDs, NuclearCraft, Numina, OMLib, OnlinePictureFrame, Open Modular Passive Defense, Open Modular Turrets, OpenComputers, OpenComputers (Core), OreLib Support Mod, OreSpawn, Pam's HarvestCraft, PneumaticCraft: Repressurized, Pollutant Pump, Pollution of the Realms, Practical Logistics 2, ProjectRed Core, ProjectRed Expansion, ProjectRed Exploration, ProjectRed Fabrication, ProjectRed Illumination, ProjectRed Integration, ProjectRed Relocation, ProjectRed Transmission, ProjectRed Transportation, RFTools, RFTools Control, Railcraft, Realistic Torches, Reborn Core, RebornStorage, Reconstructor, Redstone Flux, Refined Storage, Refined Storage Addons, Reskillable, Rough Tweaks, SanAndreasPs Mod Library, SanAndreasPs Player Model, Scannable, Serene Seasons, SeriousCreepers Loot Chests, Shadowfacts' Forgelin, ShetiPhian-Core, Signals, Signpost, SonarCore, SpongeForge, Standard Expansion, Steve's Carts 2, Storage Boats Mod, Storage Drawers, Storage Drawers Extras, Super Sound Muffler: Revived, TBone, TOP Addons, TechStack's Heavy Machinery Mod, Tesla Core Lib, Tesla Core Lib Registries, The One Probe, The Spice of Life, The SpotLight Mod, Thut Core, Thut's Elevators, ThutCore Compat, Tinker's Forging, Tinkers Tool Leveling, Tinkers' Construct, Tool Belt, Track API, Trade, Ultimate Car Mod, UniDict, Universal Remote, UniversalModCore, Up-Sizer, Vanilla Builders Extension, Vials, Villager Trade Tables, Vulpes library, WanionLib, Water Control Extreme, Waystones, World Utils, WorldEdit, Wumple Util Library, Zero CORE, derfl007's Road Mod, projectred-compat

**Issue Description**
Regarding the Stacktrace i found out that wumpleutil, the core for FoodFunk could be causing this. After removing the mod, it's working fine. Unfortunatley it's one of the mods needed for the server concept to work and Sponge says once again it's its own fault, so i'm trying to get this fixed.

The issue was that whenever a player entered some chunk (we have no idea what is there actually or happens there), the server crashed.

https://gist.github.com/D3nnis3n/d2d9cc1e01f7a23d7bac429243a07f14 - Log
https://gist.github.com/D3nnis3n/365ae534237bf9e4d9774063c65b4aa0 - Crash

**Comment by clienthax** [comment]
Hmm.. this looks like the same crash but with a different mod

**Comment by clienthax** [comment]
Not sure if this will help, but can you disable sponges async lighting and see if that helps anything?

**Comment by D3nnis3n** [comment]
I disabled async lighting and will see if it helps.

**Comment by D3nnis3n** [comment]
Haven't had the crash again since i changed this config, but not sure if it will never happen again.
