### ISSUE TITLE
Crash on Startup caused by org.spongepowered.common.bridge.world.WorldBridge

### ISSUE THREAD

**Issue by H4mm3rb0y** [SpongePowered/SpongeForge#3115]
- SpongeForge version: 1.12.2-2838-7.1.10
- Forge version: 14.23.5.2847
- Java version: 1.8.0_241
- Operating System: Windows10

- Plugins/Mods(spongeforge missing):
forge, creativecoredummy, littletilescore, obfuscate, opencomputers|core, advanced_solar_panels, architecturecraft, aroma1997core, aromabackup, aromabackuprecovery, biomesoplenty, chickenchunks, chisel, chiselsandbits, codechickenlib, cofhcore, cofhworld, computercraft, computronics, asielib, creativecore, customnpcs, props, endercore, enderio, enderiobase, enderioconduitsappliedenergistics, enderioconduitsopencomputers, enderioconduitsrefinedstorage, enderioconduits, enderiointegrationforestry, enderiointegrationtic, enderiointegrationticlate, enderiomachines, enderiopowertools, energyconverters, excompressum, exnihilocreatio, bigreactors, forgelin, microblockcbe, forgemultipartcbe, minecraftmultipartcbe, ftblib, ftbutilities, cfm, waila, immersivepetroleum, immersiverailroading, universalmodcore, ic2, ironchest, jei, journeymap, littletiles, malisisadvert, malisiscore, malisisdoors, malisisswitches, mrtjpcore, ngtlib, opframe, opencomputers, opensecurity, harvestcraft, projectred-core, projectred-compat, projectred-fabrication, projectred-integration, projectred-transmission, projectred-illumination, projectred-expansion, projectred-relocation, projectred-transportation, projectred-exploration, redstoneflux, rtm, tesla, thermaldynamics, thermalexpansion, thermalfoundation, tickprofiler, trackapi, bspkrscore, treecapitator, vanillafix, vehicle, worldedit, wrcbe, zerocore, rendertoolkit, guitoolkit, commons0815, immersiveengineering, ocdevices

Crash-Report:
https://gist.github.com/H4mm3rb0y/c927a629812fe30939484d7b0f9ecb32
debug.log:
https://gist.github.com/H4mm3rb0y/39e40cad07c7d54af1f8b460f2625867

Hey guys,

I have ran into an issue while installing spongeforge. Since i did the server always crashes on startup with the error: java.lang.ClassCastException: net.minecraft.world.WorldServer cannot be cast to org.spongepowered.common.bridge.world.WorldBridge.

I already did some research and found out, that this could have something to do with another mod that is using an outdated version of Mixin. My problem is that i have no clue how to find out which mod is causing the problems. Neither i found an incompatiblity list to ensure all is working fine together. I also realized that there seems to be a problem with Ender IO but that does not cause the crash (i tried removing it and got the same issue). I already searched the debug.log for hints of possible crash causing mods, but i did not find anything. I am not so deep within java at all and I'm at the end of my skills to debug this. I hope you can help me. 

Thanks in advance
H4mm3r

**Comment by clienthax** [comment]
Try without vanillafix and tickprofiler.

**Comment by H4mm3rb0y** [comment]
Thank you so much. 
It was TickProfiler, i had an outdated version of it installed. With the newest release everything works fine.
