### ISSUE TITLE
[Console Error] Failed to process all PhaseContext captured!

### ISSUE THREAD

**Issue by Harjas2102** [SpongePowered/SpongeForge#3117]
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2838-7.1.11-RC4007
- Forge version: forge-1.12.2-14.23.5.2847-universal
- Java version: 1.8.0_201
- Operating System: Windows 10 (amd64) version 10.0

- Plugins/Mods: 
     - Mod List: https://gist.github.com/Harjas2102/4b3e431114ac9449f36985d041737601
     - Plugin List: https://gist.github.com/Harjas2102/de67db06a6da59725e42681cf6873959

**Issue Description**
This console error randomly appears when I monitor the server, strictly when players are online. I am unable to exactly identify during which actions the player executes, that this error occurs. But, in the server log, the sponge error provides details as follows:

- *Packet: CPacketPlayerDigging{position=BlockPos{x=710, y=70, z=-458}, facing=down, action=START_DESTROY_BLOCK}*
- *ItemStackUsed: 1xitem.hatchetIron@181*

![Screenshot_32](https://user-images.githubusercontent.com/15962611/77859602-528bf500-71d8-11ea-8e13-51cf5b52bd6c.jpg)

**Error Log (Server Logs prior to and after issue are perfectly normal)**
https://gist.github.com/Harjas2102/206b3bbdafbd2d9898d46733061366ed

**Notes**
I have made attempts to read up on issues that were very similar to this in the past, such as ones from 2019, but in those issues, the OP failed to provide adequate information on the reproduction of the issue, and there was actually less "Context" provided by the console log in their instance. That being said, I apologize for the case that posting this may be redundant. Please be sure to let me know of any other information I can provide.

**Comment by clienthax** [comment]
Full log please.
