### ISSUE TITLE
Wont launch with SpongeForge

### ISSUE THREAD

**Issue by niklas2233** [SpongePowered/SpongeForge#3119]
**I am currently running**
- SpongeForge version: 2838-7.2.1-RC4010
- Forge version: 14.23.5.2847
- Java version: 1.8.0.51
- Operating System: windows 10

**Issue Description**
so my game wont launch when i have SpongeForge installed. i dont get a crash report, and i dont know why. all i could understand of the log is that its a mixin problem.

https://gist.github.com/niklas2233/eda3f1c78f73aff2b09bc9f104ce159c

**Comment by dualspiral** [comment]
It's HammerCore.

In `hammercore.xml`, find the line that says:

```
<entry key="World.ITickable.Override">true</entry>
```

Change that `true` to `false`.
