### ISSUE TITLE
Mixin failed injection check?

### ISSUE THREAD

**Issue by wiloxe** [SpongePowered/SpongeForge#3120]
**I am currently running**
- SpongeForge version: 1.12.2-2838-7.2.0
- Forge version: 1.12.2-14.23.5.2847
- Java version: 1.8.0_221-b11
- Operating System: Windows 10 Build 1903

- Plugins/Mods: https://www.curseforge.com/minecraft/modpacks/dungeons-dragons-and-space-shuttles/files/2894292
Removed the following mods from the modpack that was recommended to make it work:
Sledgehammer, Vanillafix, Foamfix, BetterFPS

**Issue Description**
After adding the sponge forge into the modpack I first got the error suggesting rename to __a and then removed a few mods that I read online could cause issues. (Sledgehammer was not informed online but in crash log instead)

Also I would like to take this time to ask why the discord server is never repsonding with help?

Debug + Latest log: https://gist.github.com/wiloxe/53cb540d98b432c4739bf36367ff9ca7

Note: I read in a closed issue that turning World.ITickable.Override on would solve this however it's already on.

**Comment by dualspiral** [comment]
> Also I would like to take this time to ask why the discord server is never repsonding with help?

How rude. The channel is actually quite active right now, trying to help people. Someone did actually respond to you saying that the pack works fine. However, we have had a lot of people ask, and I'm sorry you feel like you were missed.

> Note: I read in a closed issue that turning World.ITickable.Override on would solve this however it's already on.

Read the issue again. It tells you to turn it OFF.
