### ISSUE TITLE
Error loading advancements when loading world

### ISSUE THREAD

**Issue by Nbgreen** [SpongePowered/SpongeForge#3121]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.2.1-RC4011
- Forge version: forge-1.12.2-14.23.5.2847
- Java version: java8
- Operating System: ubuntu7

- Plugins/Mods:

**Plugins**

ActiveTime, 
AurionsVoteListener 
Broadcast, 
Buycraft, 
CarrotShop, 
CatClearLag, 
Chest Refill, 
CmdBuilder, 
CmdControl, 
CmdScheduler, 
CommandSigns Reloaded, 
Dynamic Shops, 
Eagle Factions, 
ItemChat, 
JumpPlate, 
Lottery, 
LuckPerms, 
MMCReboot, 
MMCRestrict, 
MagiBridge, 
MeeM, 
NuVotifier, 
Nucleus, 
ProjectCore, 
Proje|ctPortals, 
ProjectWorlds, 
QuestionsTime, 
RBounty, 
RankUpper, 
RentableRegions, 
ServerMonitor,
Slash Discord, 
Total Economy, 
Universe Guard 2, 
Worldrebuilder  

**mods**
A Lib, Actually Additions, Actually Baubles, Advanced Sol|
ars Classic Edition, AsmodeusCore, BTFU, Bad Wither No Cookie! Reloaded, Baubles, Better Builder's Wands, BiblioCraft, Blood Magic: Alchemical Wizardry, Botania, Building Gadgets, CC: Tweaked, CC: Tweaked, Chameleon, |
ChickenChunks, Chisel, Chunk Pregenerator, Classic Combat, CoFH Core, CoFH World, CodeChicken Lib, Construct's Armory, CraftTweaker JEI Support, CraftTweaker2, Custom Stuff 4, CustomNPCs, EnderStorage, Engineer's Door|
s, Extra Utilities 2, Extreme Reactors, Flux Networks, FoamFix, FoamFixCore, Forestry, Forge Microblocks, Forge Multipart CBE, Galacticraft Core, Galacticraft Planets, GalaxySpace, Gravisuit Classic, Guide-API, IC2 Cl|
assic Detection Helper, ICBM-Classic, Ic2c Extras, Immersive Engineering, Industrial Craft Classic, Industrial Foregoing, Inventory Tweaks, Iron Chest, Item Blacklist, JAOPCA, JourneyMap, Just Enough Items, Just Enoug|
h Reactors, LagGoggles, MachineMuse's Modular Powersuits, Malisis Advert, MalisisCore, Mantle, McJtyLib, Mekanism, Mekanism: Generators, Mekanism: Tools, Micdoodle8 Core, Minecraft Multipart Plugin, MrTJPCore, Nuclear|
Craft, Numina, OMLib, Open Modular Passive Defense, Open Modular Turrets, OpenBlocks, OpenModsLib, OpenModsLib Core, OreDictInit, Pam's HarvestCraft, Patchouli, Plethora, Plethora Core, PlusTiC, PneumaticCraft: Repres|
surized, PortalGun, ProjectRed Core, ProjectRed Integration, ProjectRed Transmission, RFTools, Random Things, RandomPatches, Reborn Core, RebornStorage, Redstone Arsenal, Redstone Flux, Refined Storage, Refined Storag|
e Addons, SG Craft, Shadowfacts' Forgelin, Simply Jetpacks 2, Simply Tea, SonarCore, SpongeForge, Steve's Carts 2, Storage Drawers, Super Factory Manager, Tesla Core Lib, Tesla Core Lib Registries, The One Probe, Ther|
mal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Tinker I/O, Tinker's JEI, Tinkers Tool Leveling, Tinkers' Construct, VanillaFix, WanionLib, WorldEdit, WrapUp, Zero CORE, iChunUtil, mob_grindin|
g_utils, p455w0rd's Library  

**modpack** 

https://www.curseforge.com/minecraft/modpacks/lapitos-galacticraft

**Issue Description**
after a server restart players will get a random internal server error that prevents them from logging in 
the error in console says that it cant handle a packet 
the only way to fix the issue as of current is to restart the server but the issue comes back over time

http://downloads.thebobsgamingnetwork.net/2020-04-02-7.log

**Comment by dualspiral** [comment]
Copying from an issue where this was posted by @radfast:

> @dualspiral @Aaron1011 has pointed out that there is a potential GC issue here, because we are calling a getWorld() from a network packet handling thread, which can potentially cause an issue in a Sponge environment. I am looking at what we can do about this, as a priority .

cc: https://github.com/micdoodle8/Galacticraft/issues/3920

**Comment by clienthax** [comment]
Looks like GC fixed this on their side, @Nbgreen can you retest

**Comment by dualspiral** [comment]
I assume it was - due to no response, closing.
