### ISSUE TITLE
Opening a connection and logging into two servers at the same time from one client instance

### ISSUE THREAD

**Issue by Beshelmek** [SpongePowered/SpongeForge#3123]
I am currently running:

**Minecraft**: 1.12.2
**SpongeAPI**: 7.2-fe189dcf
**Sponge**: 1.12.2-7.2.0
**SpongeForge**: 1.12.2-2838-7.2.0
**Minecraft Forge**: 14.23.5.2838
**JVM**: 1.8.0_221/64-bit (Oracle Corporation)
**OS**: Linux (4.19.0-8-amd64/amd64)

**Mods** (34): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, AutoRegLib, BiblioCraft, CXLibrary, Chisel, Cucumber Library, CustomNPCs, Iron Chest, ItemPhysic, Just Enough Items, LegendaryFixer, LegendaryPlus, Mantle, More Buckets, More Furnaces, MoveSkillController, OpenFM, Pam's HarvestCraft, Pixel Extras, Pixelmon, Quark, Sampling Performance Profiler, Spawnerdisabler, SpongeForge, Trade, Tree Chopper, Varied Commodities, Vending, fishfixw

**Plugins** (32): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge,  FastAsyncWorldEdit, Auth Redirects, CatClearLag, DupeFixer, GriefPrevention, Holograms, HologramsPlus, HuskyCrates, HuskyUI, LuckPerms, MMCLogger, MMCRestrict, Mega Menus, NoAFKSpawning, Nucleus, PixelGenocide, PixelHunt, PixelmonBroadcasts, PixelmonPlaceholders, PlaceholderAPI, SimpleDexRewards, StreamCraft API, TabManager, UltimateChat, WorldEdit, pokedisguise, spark

**Very** strange and funny bug. If the player initiates a connection to the server and immediately cancels it, he remains online on the server while being in the server selection GUI. And also, if you immediately connect to another server, the player online is on two servers at the same time. You can see the whole process on the video. The TAB menu switches between the two servers same as the time of day. And also chat messages come from two servers.

When a player presses a cancel button while connecting, server throw error without stack trace. 
```
[00:10:42] [Netty Server IO #11/ERROR] [FML]: NetworkDispatcher exception
io.netty.handler.timeout.ReadTimeoutException: null
```

**Video proof**: https://www.youtube.com/watch?v=xcSWFlzgj98&feature=youtu.be

**Comment by clienthax** [comment]
Retest on latest.

**Comment by Zidane** [comment]
Closing due to lack of comment
