### ISSUE TITLE
Latest recommended stable build is detetcted as malware by Avast

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#3124]
I downloaded the latest recommended stable build (7.2.0) [here](https://repo.spongepowered.org/maven/org/spongepowered/spongeforge/1.12.2-2838-7.2.0/spongeforge-1.12.2-2838-7.2.0.jar) and Avast detected the URL as malware (URL:Blacklist) then once I whitelisted the URL thinking it was just a false positive I downloaded the file and made an analysis and the JAR was also detected as malware.

I am running the highest sensibility settings on Avast so this might be just a false positive

Avast report:

`C:\Users\[User]\Desktop\spongeforge-1.12.2-2838-7.2.0.jar|>org\spongepowered\common\event\tracking\phase\packet\PacketPhaseUtil.class [L] Java:Malware-gen [Trj] (0)
File was successfully moved to chest...
Infected files: 1
Total files: 10713
Total folders: 0
Total size: 65.9 MB`

[VirusTotal Report](https://www.virustotal.com/gui/file/531820273fd3792dcf0c526277c0e8e22e4aa5a6003467c07cf5112561eb4dbc/detection)

**Comment by XakepSDK** [comment]
1. Report avast
2. Use better antivirus

**Comment by ghost** [comment]
Very helpful

**Comment by dualspiral** [comment]
**It is a false positive.** We have had recently had people ask about this and we don't know why it's doing it now of all times. I've had this when compiling this tree using Kapersky. I imagine that the heuristics engine is just predicting wrong.

The class it's unhappy about is [`PacketPhaseUtil`](https://github.com/SpongePowered/SpongeCommon/blob/4a9742b465d095769fa4e6ca5fbf22865e3de87b/src/main/java/org/spongepowered/common/event/tracking/phase/packet/PacketPhaseUtil.java). I don't really see why, I'd have expected other classes would have been _way_ more malware like.

I have reported this as a false positive on Avast's website. If you can, you could do so via your Avast client.

**Comment by ghost** [comment]
Ok thanks! I'll add it to my exceptions for now

**Comment by ghost** [comment]
I retested the file in Avast and it looks like the Issue has been resolved
