### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by nfsc30001** [SpongePowered/SpongeForge#3125]
I know this probably isnt a problem of sponge, but i dont know where else to post this.

[latest.log](https://github.com/SpongePowered/SpongeForge/files/4434269/latest.log)

**Comment by dualspiral** [comment]
I think it's JustEnoughIDs, they ship a custom version of Mixin for what I recall and thus causes this issue... I think?

Support is better reached via our [Discord channel](https://discord.gg/sponge). Further, _please_ use our template if you report any issue in future.
