### ISSUE TITLE
Server Crash on startup

### ISSUE THREAD

**Issue by benjamin3033** [SpongePowered/SpongeForge#3129]
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2838-7.2.0
- Forge version: forge-1.12.2-14.23.5.2847-universal.jar
- Java version: Unknown/MCProhosting
- Operating System: Linux

- Plugins/Mods: 

/dank/null (by TheRealp455w0rd)
[ANGRY PIXEL] The Betweenlands (by oily_oli)
Actually Additions (by Ellpeck)
Advanced Hook Launchers (by EnderLanky)
AE2 Stuff (by bdew)
AE2 Wireless Terminal Library (by TheRealp455w0rd)
AgriCraft (by InfinityRaider)
AI Improvements (by DarkGuardsman)
Akashic Tome (by Vazkii)
AmbientSounds 3 (by CreativeMD)
AppleCore (by squeek502)
AppleSkin (by squeek502)
AttributeFix
Applied Energistics 2 (by AlgorithmX2)
ArchitectureCraft - TridentMC Version (by darkevilmac)
Armor Toughness Bar (by tfarecnim)
Armory Expansion (by AshuraNoYami)
Aroma1997Core (by Aroma1997)
AromaBackup (by Aroma1997)
AtomicStryker's Battle Towers (by atomicstrykergrumpy)
Auto Ore Dictionary Converter (by MattDahEpic)
AutoRegLib (by Vazkii)
Bad Wither No Cookie - Reloaded (by Kreezxil)
Baubles (by Azanor13)
BdLib (by bdew)
Better Builder's Wands (by Portablejim)
BetterFps (by Guichaguri)
Bewitchment (by sunconure11)
BiblioCraft (by Nuchaz)
Biome Staff (by TheRealp455w0rd)
Biomes O' Plenty (by Forstride)
Block Drops (JEI Addon) (by KidsDontPlay)
Bookshelf (by DarkhaxDev)
Botania (by Vazkii)
Buildcraft (by Covert_Jaguar)
Building Gadgets (by Direwolf20)
Chameleon (by Texelsaur)
Career Bees
Champions (by TheIllusiveC4)
Chance Cubes (by Turkey2349)
Charm (by svenhjol)
Chisel (by tterrag1098)
Chisels & Bits (by AlgorithmX2)
Chunk-Pregenerator (by Speiger)
Clumps (by Jaredlll08)
CodeChicken Lib 1.8.+ (by covers1624)
CoFH Core (by TeamCoFH)
CoFH World (by TeamCoFH)
Common Capabilities (by kroeser)
Compact Machines (by davenonymous)
ConnectedTexturesMod (by tterrag1098)
Construct's Armory (by TheIllusiveC4)
Controlling (by Jaredlll08)
Cooking for Blockheads (by BlayTheNinth)
Corail Tombstone (by Corail_31)
Cosmetic Armor Reworked (by LainMI)
Crafting Tweaks (by BlayTheNinth)
CraftTweaker (by Jaredlll08)
CreativeCore (by CreativeMD)
Cucumber Library (by BlakeBr0)
Culinary Construct (by TheIllusiveC4)
Custom Main Menu (by Lumien231)
Customized Dungeon Loot (by XxRexRaptorxX)
Cyclic (by Lothrazar)
Cyclops Core (by kroeser)
DarknessLib (by Shinoow)
Davincis Vessels (by darkevilmac)
DimensionalDoors (by DimensionalDevelopment)
Ding (by ohaiiChun)
DiscordIntegration (by TheChikachi)
Doomlike Dungeons (by JaredBGreat)
Doggy Talents
Dungeon Tactics (by PegBeard)
Dungeons2 (by gottsch)
Dynamic Surroundings (by OreCruncher)
Electroblob's Wizardry (by Electroblob)
Enchantment Descriptions (by DarkhaxDev)
Ender IO (by CrazyPants_MC)
Ender Storage 1.8.+ (by covers1624)
EnderCore (by tterrag1098)
Energy Converters (by xalcon)
Extra Bit Manipulation (by Phylogeny)
Extra Utilities (by RWTema)
ExtraCells2 (by Destroyer7128)
Fairy Lights (by pau101)
Farming for Blockheads (by BlayTheNinth)
Farseek (by delvr)
Fast Leaf Decay (by olafskiii)
FastWorkbench (by Shadows_of_Fire)
Fish's Undead Rising (by fish0016054)
Flux Networks (by sonar_sonic)
Forestry (by _ForgeUser7678633)
Forge MultiPart CBE (by covers1624)
ForgeEndertech (by EnderLanky)
FTB Library (by LatvianModder)
FTB Money (by LatvianModder)
FTB Quests (by LatvianModder)
FTB Utilities (by LatvianModder)
Gas Conduits (by pupnewfster)
Gendustry (by bdew)
Ghost's Explosives (by ghostgamingpe)
GottschCore (by gottsch)
Grue (by Shinoow)
Guide-API (by TehNut)
Hardcore Darkness (by Lumien231)
Hats (by ohaiiChun)
HunterIllager (by bagu_chan)
Hwyla (by TehNut)
ICBM - Classic (by DarkGuardsman)
Ice and Fire: Dragons in a whole new light! (by alex1the1666)
iChunUtil (by ohaiiChun)
Immersive Cables (by SanAndreasP)
Immersive Engineering (by BluSunrize)
Immersive Petroleum (by Flaxbeard)
Immersive Tech (by FerroO2000)
Improved Backpacks (by DreenDexTwitch)
In Control! (by McJty)
Industrial Foregoing (by Buuz135)
InfinityLib (by InfinityRaider)
Instrumental Mobs (by Mrbysco)
Integrated Dynamics (by kroeser)
Integrated Tunnels (by kroeser)
Integration Foregoing (by Jackyy)
Inventory Pets (by Purplicious_Cow_)
Inventory Tweaks (by JimeoWan)
Iron Chests (by ProgWML6)
It's the little things (by Zlepper)
Item Filters (by LatvianModder)
IvToolkit (by Ivorforce)
JAOPCA (by TheLMiffy1111)
JourneyMap (by techbrew)
JEI Bees
Just Enough Calculation (by towdium)
Just Enough Energistics (JEE) (by TheRealp455w0rd)
Just Enough HarvestCraft (JEHC) (by mrAppleXZ)
Just Enough Items (JEI) (by mezz)
Just Enough Resources (JER) (by way2muchnoise)
LagGoggles (by Terminator_NL)
Large Ore Deposits (by EnderLanky)
LetsEncryptCraft (by CloudyPSP)
Level Up! Reloaded (by BeetoGuy)
LittleTiles (by CreativeMD)
LLibrary (by _ForgeUser11902522)
Login Shield (by Glasspelican)
Loot Capacitor Tooltips (by tfarecnim)
Loot Games (by Time_Conqueror)
LunatriusCore (by Lunatrius)
MalisisCore (by Ordinastie)
MalisisDoors (by Ordinastie)
Mantle (by mDiyo)
MattDahEpic Core (MDECore) (by MattDahEpic)
McJtyLib (by McJty)
MCMultiPart (by amadornes)
Mekanism (by bradyaidanc)
Mekanism Generators (by bradyaidanc)
Mekanism Tools (by bradyaidanc)
MenuMobs (by Superbas11)
Minecolonies (by H3lay)
MineTweaker RecipeMaker (by DoubleDoorDev)
Moar Tinkers (by AshuraNoYami)
Mob Grinding Utils (by vadis365)
Modular Powersuits (by machinemuse)
More Overlays (by FeldiM245)
Morpheus (by Quetzi)
Mouse Tweaks (by YaLTeR)
MovingWorld (by darkevilmac)
Mowzie's Mobs (by bobmowzie)
MPUtils (by GenDeathrow)
Multi Mob Library (by Daveyx0)
Mystical Agradditions (by BlakeBr0)
Mystical Agriculture (by BlakeBr0)
Mystical World (by EpicSquid319)
MysticalLib (by EpicSquid319)
Nature's Aura (by Ellpeck)
Nature's Compass (by Chaosyr)
NetherPortalFix (by BlayTheNinth)
NotEnoughIDs (by fewizz_)
NuclearCraft (by tomdodd4598)
Numina (by machinemuse)
OldJavaWarning (by DarkhaxDev)
OMLib (by Keridos)
Open Modular Turrets (by Keridos)
OpenBlocks (by OpenMods)
OpenComputers (by Sangar_)
OpenModsLib (by OpenMods)
Ore Excavation (by Funwayguy)
OreLib (by OreCruncher)
Overloaded Armor Bar (by tfarecnim)
p455w0rd's Library (by TheRealp455w0rd)
Paintings ++ (by AbsolemJackdaw)
Pam's Cookables - Pam's Harvestcraft Addon (by BloodWorkXGaming)
Pam's HarvestCraft (by pamharvestcraft)
Patchouli (by Vazkii)
Phosphor (by jellysquid_)
Placebo (by Shadows_of_Fire)
PlusTiC (by landmaster_phuong0429)
Portal Gun (by ohaiiChun)
Practical Logistics 2 (by sonar_sonic)
Primitive Mobs (by Daveyx0)
Quark (by Vazkii)
Random Things (by Lumien231)
RandomPatches (by TheRandomLabs)
Rats (by alex1the1666)
ReAuth (by TechnicianLP)
Reborn Core (by modmuss50)
Redstone Flux (by TeamCoFH)
Reskillable (by lanse505)
Resource Loader (by Lumien231)
RFTools (by McJty)
RFTools Dimensions (by McJty)
Roots (by EpicSquid319)
Roguelike Dungeons (by greymerktv)
Ruins (Structure Spawning System) (by atomicstrykergrumpy)
Scannable (by Sangar_)
Shadowfacts' Forgelin (by ShadowfactsDev)
ShadowMC (by ShadowfactsDev)
Signpost (by Gollorum)
Simple Storage Network (by Lothrazar)
Simply Jetpacks 2 (by Tomson124)
Sonar Core (by sonar_sonic)
Spice of Life: Carrot Edition (by lordcazsius)
Steve's Carts Reborn (by modmuss50)
Storage Drawers (by Texelsaur)
Storage Drawers Extras (by Texelsaur)
Streams (by delvr)
Stupid Things (by Furgle)
TAIGA (Tinkers alloying addon) (by zkafaceTV)
Tech Reborn (by modmuss50)
Tesla Core Lib (by face_of_cat)
Thaumcraft (by Azanor13)
The Beneath (by Shinoow)
The Midnight (by cipher_zero_x)
The Summoner (by Daveyx0)
The Twilight Forest (by Benimatic)
Thaumic JEI
Thermal Cultivation (by TeamCoFH)
Thermal Dynamics (by TeamCoFH)
Thermal Expansion (by TeamCoFH)
Thermal Foundation (by TeamCoFH)
Thermal Innovation (by TeamCoFH)
Time Core (by Time_Conqueror)
Tinker's JEI (by Possible_triangle)
Tinkers Construct (by mDiyo)
Tinkers' Tool Leveling (by bonusboni)
Totemic (by ljfa2)
Treasure2! (by gottsch)
Tweakers Construct (by RCXcrafter)
UniDict (by WanionCane)
Vampirism - Become a vampire! (by maxanier)
VanillaFix (by Runemoro)
Waila Harvestability (by squeek502)
WanionLib (by WanionCane)
Waystones (by BlayTheNinth)
Wireless Crafting Terminal (by TheRealp455w0rd)
Wireless Redstone CBE (by covers1624)
Wither Skeleton Tweaks (by Shadows_of_Fire)
WrapUp (by TheLMiffy1111)
XNet (by McJty)
ZeroCore (by ZeroNoRyouki)

**Issue Description**
I start the server up and after a minute it stops.
Originally it was having an issue with another mod loading before it and I added __aa to the start of the file name to make it load first but I then got this different issue.

[Server log](https://gist.github.com/benjamin3033/45c5e16121885108dc052fb1d4984129)

**Comment by gabizou** [comment]
```
[20:58:14] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:710]: Caused by: java.lang.NoSuchFieldError: methods
[20:58:14] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:710]: at cf.terminator.laggoggles.mixinhelper.extended.DynamicMethodReplacer.transform(DynamicMethodReplacer.java:48)
```
Update or remove lag goggles.
