### ISSUE TITLE
FTBUtilities permissions dont apply to sponge plugins

### ISSUE THREAD

**Issue by leytilera** [SpongePowered/SpongeForge#3130]
**I am currently running**
- SpongeForge version: 2838-7.2.0
- Forge version: 14.23.5.2847
- Java version: 1.8.0_221
- Operating System: Windows 10 / Debian 10 (testet on both)

- Plugins/Mods:
Project Worlds
Project Core
FTB Library
FTB Utilities

**Issue Description**
With FTBUtilities I have set the permission for me true, that I can go into another dimension, but after that, I still get a message, that I dont have the permission to go there. FTBUtilities still says, that I have this permission

Log: https://gist.github.com/mpztilera/2adac907f3a811a0704f8f434f47a75d

**Comment by clienthax** [comment]
Is there any reason you are not using a sponge based permission manager (there is an option in the config to pass all forge permission checks to sponge)?

**Comment by leytilera** [comment]
Yes, because sponge permission managers cant handle things like max claimable chunks, chat format or badges from FTB Utilities

**Comment by clienthax** [comment]
Hi @mpztilera,

It will not be possible to get FTBU to handle permissions for sponge plugins as this is not something we support.
The way I would go about this would be to enable the flag in config for passing all forge permission checks to sponge, 
```
    permission {
        # If 'true', Sponge plugins will be used to handle permissions rather than any Forge mod
        forge-permissions-handler=**true**
    }
```

And use something like luckperms to handle permissions globally instead.
