### ISSUE TITLE
Issue with Sponge and Lycanite mobs’ rideable creatures 

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#3133]
I‘m running
SpongeForge version: 1.12.2-2838-7.1.10 and 1.12.2-2838-7.2.0
Forge version: forge-1.12.2-14.23.5.2838
Java version: 8
lycanitesmobs-1.12.2-2.0.7.0-aberrant14.jar
_spongeforge-1.12.2-2838-7.1.10.jar
Issue Description:
Whenever I press shift to go down while riding any creature of the mod, the mob stops moving and I can’t do anything. This only happens with sponge on the server, and with every version of the mod.

**Comment by svrdl** [comment]
I can confirm that behaviour. I was trying Spongeforge on my server when i noticed it. Had to remove spongeforge again to fix it.

**Comment by Pangamma** [comment]
Related to: https://github.com/SpongePowered/SpongeForge/issues/3118

**Comment by clienthax** [comment]
Can you try this on latest Spongeforge, I believe there were some riding changes recently.

**Comment by clienthax** [comment]
Tested on latest, seem that pressing shift just dismounts me from the roc now.

**Comment by clienthax** [comment]
Tested on latest,
It seems that with sponge on the client in single player, everything works as expected.
However with it on the server in multiplayer it bugs out, looking into.

**Comment by clienthax** [comment]
Seems that the problem is caused by attempting to dismount the Roc, (dismount / descend being the same control..), which is causing the issue.

**Comment by svrdl** [comment]
If i remember correctly the dismount button is C not shift (In Lycanite at least).

**Comment by clienthax** [comment]
> If i remember correctly the dismount button is C not shift (In Lycanite at least).

By default shift will dismount whichever entity you are on, its likely this is a conflict with one of our patches expecting this behavior (eg default dismount key to get off entity, but causes desync as its cancelled on one side but not the other)

This is further pointed towards by the fact that changing the descend keybind off of shift makes everything work fine, however EntityMountEvent isn't fired when using the shift key when the glitch occurs.

This seems to be a likely part of code, but it seems to have quantum problems with debugging, If i smack a breakpoint in the method it dismounts perfectly :'), It seems we may not be firing the event back to the forge side.
https://github.com/SpongePowered/SpongeCommon/blob/7c7c08c382110b7742f5f381b047875da1c0549f/src/main/java/org/spongepowered/common/mixin/core/entity/EntityMixin.java#L284
