### ISSUE TITLE
Plugins not Loading

### ISSUE THREAD

**Issue by Okaghana** [SpongePowered/SpongeForge#3138]
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.2.1-RC4011
- Forge version: 1.12.2-14.23.5.2838
- Java version: 1.8.0_251
- Operating System: Windows 10 Professional

- Plugins/Mods: 
Mods (111): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, Advanced Fishing, Advanced Hook Launchers, AlcatrazCore, Antique Atlas, Anvil Patch - Lawful, Aquaculture, Armor Underwear, AutoRegLib, BNBGamingLib, Battle Towers, Baubles, Better Combat Rebirth, Better Survival, Bloodmoon, Bountiful Baubles, Campfire Spit, Carrots Lib, Carry On, Comforts, CompatSkills, Coralreef, Corpse Complex, CraftTweaker JEI Support, CraftTweaker2, Craftable Chainmail, Craftable Horse Armour [CHA&S], CreativeCore, CreativeCoreDummy, Defiled Lands, Disenchanter, Doomlike Dungeons, Dynamic Surroundings, Dynamic Trees, Dynamic Trees for Traverse, Enhanced Visuals, Familiar Fauna, First Aid, FoamFix, FoamFixCore, Food Expansion, Forge Endertech, Forgotten Items, FriendlyEndermite, Global GameRules, Grappling hook mod, ISeeDragons, Ice and Fire, Infernal Mobs, Inventory Tweaks, Iron Chest, It's the little things, ItemPhysic, IvToolkit, Just Enough Items, LLibrary, Level Up! Reloaded, Lost Souls, Lycanites Mobs, Mo' Bends, Multi Mine, No Tree Punching, OreLib Support Mod, Phosphor Lighting Engine, Potion Core, Potion Fingers, Quality Tools, Realistic Torches, Reborn Core, Recurrent Complex, Reskillable, Rin's So Many Enchantments?, Roguelike Dungeons, Rough Tweaks, Ruins Mod, Scaling Health, Serene Seasons, Shadowfacts' Forgelin, Silent Lib, Simple Camp Fire, Sit, Snow! Real Magic!, Spartan Fire, Spartan Shields, Spartan Weaponry, SpawnerControl, SpongeForge, SwingThroughGrass, Switch-Bow, TNTUtils, TNTUtils Core, The Lost Cities, Tool Belt, Tough As Nails, Traverse, Trinkets and Baubles, Trumpet Skeleton, TschippLib, Tumbleweed, Varied Commodities, Waystones, Wearable Backpacks, Wolf Armor and Storage, XP From Harvest, XP Tome, bacodifficulty
Plugins (4): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge

**Issue Description**
I want to run a forge server with the RLCraft modpack and a few plugins. Here is my file structure:
* mods
   *  plugins
      * Clearlag.jar
      * SinglePlayerSleep-2.13.16.jar
      * worldedit-bukkit-6.1.9.jar
    * \# spongeforge-1.12.2-2838-7.2.1-RC4011.jar
    * AdHooks-1.12.2-3.2.2.0-build.0220.jar
    * ...

In my config file I configured that `plugins-dir="${CANONICAL_MODS_DIR}/plugins"`

However, as soon as I run the server, the plugins are not loaded and I can't use them. Also as seen above, they aren't listed when I enter `/sponge plugins`. I tried moving the plugins folder to the Game directory or putting the plugins in the "mods" folder, but they are never loading.

When you take a look in the [console output](https://gist.github.com/Okaghana/55bd5eee6c54d8ec9689d9be21049796), is states:
```
[21:59:54] [Server thread/INFO] [FML]: FML has found a non-mod file Clearlag.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.
[21:59:54] [Server thread/INFO] [FML]: FML has found a non-mod file SinglePlayerSleep-2.13.16.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.
[21:59:54] [Server thread/INFO] [FML]: FML has found a non-mod file worldedit-bukkit-6.1.9.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.
```

~Okaghana

**Comment by dualspiral** [comment]
Bukkit plugins don't work on Sponge. You need Sponge plugins, which you can get from [Ore](https://ore.spongepowered.org)
