### ISSUE TITLE
Server crash on Start

### ISSUE THREAD

**Issue by M0n7y5** [SpongePowered/SpongeForge#3141]
**I am currently running**
- SpongeForge version: **spongeforge-1.12.2-2838-7.2.1-RC4013.jar**
- Forge version: **forge-1.12.2-14.23.5.2847-universal.jar**
- Java version: **1.8**
- Operating System: **Linux**

Modpack: 
- [https://kineticnetwork.net/portfolio/infinity/](https://kineticnetwork.net/portfolio/infinity/)

Serverfiles:
- https://sleepingtea.xyz/serverfiles/Infinity%20Server%20Files.zip

**Issue Description**

Server will not start with latest version of SpongeForge. Just download Infinty serverfiles and put SpongeForge to /mods folder.
Also tested versions: 
- spongeforge-1.12.2-2838-7.1.11-RC4007.jar
- spongeforge-1.12.2-2838-7.1.11-RC4005.jar

(same error)

[https://gist.github.com/M0n7y5/1e963336cf7729cd633e795cd3f9ece5](https://gist.github.com/M0n7y5/1e963336cf7729cd633e795cd3f9ece5)

**Comment by clienthax** [comment]
Rename sponge to aaaaasponge and try again.

**Comment by M0n7y5** [comment]
@clienthax Now i get this:
https://gist.github.com/M0n7y5/a91d31333da629f7c1c3c7bd9bb857dd

**Comment by M0n7y5** [comment]
Debug log:
https://gist.github.com/M0n7y5/42888f3f00041ef2e9dbb3029fd0e957

**Comment by clienthax** [comment]
Pretty sure I said a's, not Reee..

**Comment by clienthax** [comment]
Looks like you are using an outdated version of sledgehammer

**Comment by M0n7y5** [comment]
Yes i see it now 
![obrazek](https://user-images.githubusercontent.com/17201053/80036891-e9f01980-84f2-11ea-9511-8fccada119a1.png)
There is Mixins from that plugin already so its causing conflicts ...

**Comment by clienthax** [comment]
Not a sponge issue, update the mod.

**Comment by M0n7y5** [comment]
It works now! Thx! 👍
