### ISSUE TITLE
Server freezes so that being killed by server watchdog (even on 200 seconds) randomly when player disconnects under high load

### ISSUE THREAD

**Issue by skyline918** [SpongePowered/SpongeForge#3145]
Cant use latest because some plugins break
- SpongeForge version: spongeforge-1.12.2-2838-7.1.9.jar
- Forge version: 2838
- Java version: OpenJDK Runtime Environment (build 1.8.0_242-8u242-b08-1~deb9u1-b08)
- Operating System: debian9.4, Intel i7-6700K - 32GB DDR4, dedicated server
- jvm args (aikars): java -Xms10G -Xmx10G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:G1MixedGCLiveThresholdPercent=50 -XX:+AlwaysPreTouch -cp ...

- Plugins/Mods: all can be found in threads dump crash [file](https://gist.github.com/Skyine918/031a3d47e24519e3c1f9af08cffcf5ab)

Having 80-120 players online my server sometimes freezes and main thread dies, so that after 200 seconds server is killed by watchdog. Already happened 15-16 times for last 3 days always after around 1 hour of server work. According to all debug.log files it is happened when some player disconnects from server. There is no significant server lags at all even with big amount of players online. I thought that the reason is authentication servers, so I moved them to the same host to decrease connection time, but there was no effect.  I set up world saving on disk with high interval, and chunks are not saving so each crash there is huge rollbacks and this is very painful for players. I just don't know what to do, there is literally no information in debug.log files, the last message from main thread is always: player is disconnecting.

Server Watchdog Crash Thread Dump File:
https://gist.github.com/Skyine918/031a3d47e24519e3c1f9af08cffcf5ab
I think the problem is
-- Head --
Thread: Server Watchdog
```
Stacktrace:
  at java.lang.Object.wait(Native Method)
  ...
  org.spongepowered.common.util.NetworkUtil.initializeConnectionToPlayer(NetworkUtil.java:222)
  at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:2403)
  ...
```

all debug.log files are similar, so I upload only last one (120/120 players online)
the last main thread message starts with `[16:43:32] [Server thread/INFO] [net.minecraft.server.management.PlayerList]: Disconnecting com.mojang.authlib`
https://gist.github.com/Skyine918/6ae7ed5cb2f5a132154e386cd0e59a3b

**Comment by dualspiral** [comment]
https://github.com/SpongePowered/SpongeCommon/pull/2584 - thanks to @LXGaming. This should appear on the downloads page in the next 20 minutes or so.
