### ISSUE TITLE
Crash after creating OTG dimensions.

### ISSUE THREAD

**Issue by zhourui123** [SpongePowered/SpongeForge#3150]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.1.10.jar
- Forge version: 1.12.2 2768
- Java version: 8
- Operating System:win10

- Plugins/Mods:
luckperm,
nuclear,
OTG,
dregora(otg preset)

**Issue Description**
I used the O-key to create an OTG dimension(dregora/DIM2),  but the game crashed shortly after I teleported in. 
I'm not sure if this is caused by sponge or otg.

(The O-key is the keys that open OTG gui screen,that  can create otg dimensions )

latest.log
https://gist.github.com/zhourui123/3bfe3c9f77bbdf70b2744b65b9a0f345

crash log
https://gist.github.com/zhourui123/b519d61df75e96281a03df1abd0c38d9

server.properties
https://gist.github.com/zhourui123/7386c1e16ed747112164218fbcb41ee3

**Comment by clienthax** [comment]
https://docs.spongepowered.org/stable/en/server/spongineer/incompatible.html?highlight=incompatible
