### ISSUE TITLE
Plugin depends on another, event execution order is wrong

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/SpongeForge#3153]
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2838-7.2.2-RC4024
- Forge version: forge-1.12.2-14.23.5.2854

- Plugins/Mods:
2 test plugins only. No other plugins or mods.

**Issue Description**
Plugin event execution order is not proper.

Console output:
```
[Server thread/INFO] [child]: Child loaded!
[Server thread/INFO] [parent]: Parent loaded!
```

Parent plugin:
```java
@Plugin(id = "parent")
public class Parent {
    private final Logger logger;

    @Inject
    public Parent(Logger logger) {
        this.logger = logger;
    }

    @Listener
    public void onInit(GameInitializationEvent event) {
        logger.info("Parent loaded!");
    }
}
```

Child plugin:
```java
@Plugin(id = "child", dependencies = @Dependency(id = "parent"))
public class Child {
    private final Logger logger;

    @Inject
    public Child(Logger logger) {
        this.logger = logger;
    }

    @Listener
    public void onInit(GameInitializationEvent event) {
        logger.info("Child loaded!");
    }
}
```

**Comment by gabizou** [comment]
Plugin dependencies doesn't dictate event listener ordering. You have the option of listener orders for that.

**Comment by XakepSDK** [comment]
Works as intended in SpongeVanilla

**Comment by gabizou** [comment]
No where in the Listener documentation does the contract state that listeners are registered with the plugin's dependency in consideration. By the nature that Forge's FML is instantiating plugins/mods in alphabetical order means the child plugin will get instantiated/registered before the parent.

**Comment by XakepSDK** [comment]
So if i have plugin A, that depends on plugin B and they both listen some event with `Order.PRE`, and i, for example, need to initialize something in plugin A that depends on plugin B, i need to rename plugin jars?

**Comment by Zidane** [comment]
You need to change your order in the event listener. As Gabe said, it was never in the contract that they would be fired in dependency order.

**Comment by XakepSDK** [comment]
```java
    /**
     * The dependencies required to load <strong>before</strong> this plugin.
     *
     * @return The plugin dependencies
     */
```
I assume that load also means at least game state events are called in parent before child events.
If it's not, what `load` means?

**Comment by gabizou** [comment]
> I assume that load also means at least game state events are called in parent before child events.
> If it's not, what `load` means?

Your assumption is wrong in this case. The plugin classes are expected to be loaded, but nothing about listener order is mentioned.
