### ISSUE TITLE
Integrated Dynamics breaks when SpongeForge installed.

### ISSUE THREAD

**Issue by Eckx** [SpongePowered/SpongeForge#3158]
**I am currently running**

- SpongeForge version:  7.2.1
- Forge version: 14.23.5.2847
- Java version: 8u251
- Operating System: Win10

- Plugins/Mods: MC Eternal Modpack and Server version 1.3.5.3

**Issue Description**
Downloaded and ran fresh server, set up Integrated Dynamics processing to automate flux production, tested fine. Installed spongeforge, and no longer works.

**Comment by clienthax** [comment]
This tells us nothing of how to reproduce the issue.
You havn't provided the info requested in the template either.
What are the versions of the mod etc / of sponge??

**Comment by Eckx** [comment]
Apologies. 

Mod version: 1.1.2
Spongeforge version: 1.12.2-2838-7.2.1

Steps to reproduce: 
Download and run MC Eternal Server/client version 1.3.5.3
Log into server
Set up ANY Integrated Dynamics system
Shutdown server
Install spongeforge
Reload server
Integrated Dynamics setup is now broken / no longer ticking. 



Example ID setup used to test: 

Create vanilla type cobble gen with lava/water
Place "World Block Importer" onto cobble
Place Logic Cable onto World Block Importer
Place Item Interface onto cable
Place chest onto item interface
Use Portable Logic Programmer, select "BLOCK" type, 
Place cobblestone into middle of programmer, insert variable card
insert now programmed variable card into WORLD BLOCK IMPORTER in PICK UP BLOCK slot
observe. 


Apologies, I do not normally make posts on Githubs, if you need more info I will provide it. 
![javaw_CGymDqd7Y2](https://user-images.githubusercontent.com/9084033/81987663-1685e580-9608-11ea-8d7e-c748ef9e1735.png)

**Comment by clienthax** [comment]
It seems that this is working fine for me with the latest version of integrated dynamics and sponge
Have you tried the latest versions ?

![image](https://user-images.githubusercontent.com/1056270/82314630-02eccd00-99c2-11ea-9bf0-a94b814195f9.png)

![image](https://user-images.githubusercontent.com/1056270/82314547-e05ab400-99c1-11ea-8d34-dfd452d673c9.png)

**Comment by clienthax** [comment]
Closing due to no response.
