### ISSUE TITLE
Incompatibility with LagGoggles

### ISSUE THREAD

**Issue by ken1882** [SpongePowered/SpongeForge#3159]
- SpongeForge version: 1.12.2-2838-7.2.1-RC4011
- Forge version: 1.12.2 - 14.23.5.2854
- Java version: 1.8.0_232
- Operating System: CentOS 8

Link to the issue in LagGoggles: https://github.com/TerminatorNL/LagGoggles/issues/76#issuecomment-629632572

Sometimes when running lag server profiling it'll crash afaik due to both Sponge and LagGoggles having a race condition of event listener registry as [the code mentioned by LagGoggle's author](https://github.com/SpongePowered/SpongeForge/blob/0577e1b1ecf36f5f9eea7ed8bcba562ae71d8dcd/src/main/java/org/spongepowered/mod/mixin/core/fml/common/eventhandler/EventBusMixin_Forge.java#L292-L327). And I supposed to open the issue here.

Original Crash Log: https://gist.github.com/ken1882/fae60113ffd94188701ac708d4a250ef

**Comment by Pulz-TCP** [comment]
Issue can be replicated in 1.12.2-2838-7.2.2-RC4030

**Comment by gabizou** [comment]
The fix is non-trivial, so it'll take some time before someone can make the changes necessary to support unregistering in this way. I don't believe this is a race condition, by the looks of it.

**Comment by LeonPhilips** [comment]
This is indeed not a race condition, it happens because I am unregistering my listener inside the method that calls it (valid in pure forge): https://github.com/TerminatorNL/LagGoggles/blob/master/src/main/java/com/github/terminatornl/laggoggles/util/RunInServerThread.java

**Comment by gabizou** [comment]
Should've been resolved with https://github.com/SpongePowered/SpongeForge/pull/3168. Can someone re-test? If it doesn't resolve it, will happily re-open and reinvestigate with some newer logs.

**Comment by Pulz-TCP** [comment]
Confirming fix working on 1.12.2-2838-7.2.3-RC4046
