### ISSUE TITLE
Windows Defender false positive spongeforge-1.12.2-2838-7.2.1.jar

### ISSUE THREAD

**Issue by AuroraLS3** [SpongePowered/SpongeForge#3163]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.2.1
- Forge version: none
- Java version: 8
- Operating System: Windows 10 1909 build 18363.836

- Plugins/Mods: none

**Issue Description**

I downloaded newest spongeforge jar from [the forum post](https://forums.spongepowered.org/t/sponge-javadocs-downloads/36413), and Windows defender deleted it as a false positive. Looks like misclassification by some machine learning thing.
Threat id: [Win32/Uwasson.A!ml](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Program%3aWin32%2fUwasson.A!ml&threatid=251745)

I don't know what you can do about it, but I thought you might want to know anyway.

**Comment by dualspiral** [comment]
We're aware - best to just report it as a false positive.

https://forums.spongepowered.org/t/windows-defender-thinks-spongeforge-is-a-virus/35883/11
