### ISSUE TITLE
Is it possible to add MySQL drivers

### ISSUE THREAD

**Issue by 10935336** [SpongePowered/SpongeForge#3164]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.2.1
- Forge version: forge-1.12.2-14.23.5.2854
- Java version:  zulu8.44.0.13-ca-fx-jdk8.0.242-linux_x64
- Operating System: linux(centos7) 5.6.14-1.el7.elrepo.x86_64

- Plugins/Mods: Plugins: [Plan](https://github.com/plan-player-analytics/Plan)  modpack: [Manufactio 1.3.1](https://www.curseforge.com/minecraft/modpacks/manufactio)

**Issue Description**

I'm trying to run the Plan plugin with sponge and I'm experiencing incompatibility issues with the MySQL driver, it seems sponge only has the Mariadb driver, is it any possible to add the mysql driver.

#https://github.com/plan-player-analytics/Plan/issues/1460

**Comment by dualspiral** [comment]
We've updated the MariaDB driver for the next RB - it will support MySQL 8.0.11+.

https://github.com/SpongePowered/SpongeCommon/commit/a41e8f19e619334335e87c3065d82c506c190995

You can try the latest build if you need it now.
