### ISSUE TITLE
[1.12.2] TickCentral: Server Startup Crash

### ISSUE THREAD

**Issue by CitrusHappy** [SpongePowered/SpongeForge#3171]
**I am currently running**
- SpongeForge version: 1.12.2-2838-7.2.3-RC4033
- Forge version: 14.23.5.2854
- Java version: Java 8, OpenJDK 1.8.0_242
- Operating System: Linux amd64:4.9.0-12-amd64

**Plugins/Mods**
[modlist](https://gist.github.com/CitrusHappy/3d2ee3c5d4ebcf0f21e8551b24852f9d)

**Description**
Seems to be spongeforge as the culprit. All mods work and server runs flawlessly without spongeforge's jar in the mods folder. 

- I've already tested the ###naming trick that forces sponge to load first. 

- Server still crashes even if there are no plugins installed. 

- Disabling async lighting in the global.conf does not fix this issue.

**Serverlog**
[crash1](https://gist.github.com/CitrusHappy/fe070cec86a7c162ed7e6990137579d5)

**Comment by clienthax** [comment]
https://docs.spongepowered.org/stable/en/server/spongineer/incompatible.html#farseek

**Comment by CitrusHappy** [comment]
All mod versions are updated to the latest and are past the versions listed. There should be no compatibility issues according to that documentation.

**Comment by clienthax** [comment]
Can you provide the debug log please

**Comment by CitrusHappy** [comment]
[debug1](https://gist.github.com/CitrusHappy/52c394a8e38f5a3dc63f4fbf8c19f193)

**Comment by gabizou** [comment]
Can you add `-Dmixin.dumpTargetOnFailure=true` as a startup flag and zip up the `..mixin.out` folder that gets generated after the crash?

**Comment by CitrusHappy** [comment]
[WGR.mixin.out.zip](https://github.com/SpongePowered/SpongeForge/files/4716189/WGR.mixin.out.zip)

**Comment by dualspiral** [comment]
TickCentral is looking for the method `onUpdate` [and is just renaming it](https://github.com/TerminatorNL/TickCentral/blob/master/src/main/java/com/github/terminatornl/tickcentral/asm/EntityTransformer.java#L85-L94). **There is absolutely no reason as to why they need to rename this method _at all_** and it is breaking compatiblity with SpongeForge **and** any other mod that wishes to use/merge into this method. Even if the author tried to do this in a way that SpongeForge supports, it still has the potential to break absolutely anything else. It is a stupidly dangerous thing to do.

Unfortunately, there is absolutely nothing we can do. You need to go to the TickCentral author and tell him to stop renaming methods. It breaks the assumptions of everything else in existence trying to mod Minecraft.

If you remove TickCentral, this problem should go away. I'm sorry we cannot be of any more help.
