### ISSUE TITLE
Compatibility with FirstAid since RC4029 (Death Event Cancelling)

### ISSUE THREAD

**Issue by TheFlash787** [SpongePowered/SpongeForge#3178]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.2.2-RC4029 (happens on latest, too)
- Forge version: 1.12.2-2847
- Java version: 1.8.0_241 64bit
- Operating System: Ubuntu 18.04

- Plugins/Mods:
firstaid-1.6.14
spongeforge-1.12.2-2838-7.2.2-RC4029.jar

**Issue Description**
(Conversation begins at: https://canary.discordapp.com/channels/142425412096491520/142425412096491520/726006967591501845)

It seems that since updating our Sponge to a version past RC4029 (such as RB 7.2.2), there's an issue where deaths aren't functioning normally where death messages aren't showing, and mods that use deaths in any way aren't able to function as intended. This will only occur when Firstaid is installed alongside Sponge (the Sponge version must be past RC4029, otherwise all is well). Running the server with `-Dsponge.shouldFireAll=true` also didn't change anything.

After talking with @dualspiral it seems that FirstAid isn't firing the death event, and the only indicators we have is that FA is cancelling the `LivingHurtEvent` at:
- https://github.com/ichttt/FirstAid/blob/master/src/main/java/ichttt/mods/firstaid/common/EventHandler.java#L130
- https://github.com/ichttt/FirstAid/blob/master/src/main/java/ichttt/mods/firstaid/common/EventHandler.java#L111

It was also mentioned that Sponge has adjusted some things in the recent updates that could contribute to why it's only occuring while Sponge is present and why it only occurs since then.

Thank you!

https://gist.github.com/TheFlash787/061dff055b0f9e2f1a0d33203d52a43b

**Comment by dualspiral** [comment]
I've spotted the issue, I think, I'll have a test build in a bit.

**Comment by dualspiral** [comment]
https://github.com/SpongePowered/SpongeCommon/pull/2654#issuecomment-650556898 - someone test this?

**Comment by TheFlash787** [comment]
@ImMorpheus has tested this, and I've also done the same and can confirm that all is working as intended.

Thanks a whole bunch. :heart:
