### ISSUE TITLE
[1.12.2] Cause Stack Frame Corruption Crash

### ISSUE THREAD

**Issue by BugmanBugman** [SpongePowered/SpongeForge#3179]
**I am currently running**
- SpongeForge version: 1.12.2-2838-7.2.2
- Forge version: 2854
- Java version:  Version 8 Update 251
- Operating System: W10

- Plugins/Mods:  https://pastebin.com/bRWkbWAs

**Issue Description**
While having my server loaded, it immediately crashes out of no where. This happens with 0 players btw. Looking at the debug log it seems to be because of the Gnekk from lycanites mobs and ZAWA trophies. However, i think it may be ZAWA trophies as it ended up happening again, blaming a vanilla cave spider and ZAWA trophies. This is as much as I know

crash log:
https://gist.github.com/V-Boy/68c8901202c9f68708457cb3f4088137

excerpt from debug log:
https://gist.github.com/V-Boy/fbb9e12f58bc533dd754be9435be1754

**Comment by dualspiral** [comment]
```
Caused by: java.lang.ClassNotFoundException: org.zawamod.entity.base.ZAWABaseLand
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	... 42 more
Caused by: java.lang.NullPointerException
```

Do you get a crash when doing something similar without Sponge? You may also want to try the latest build, though I don't think that's going to affect much.

**Comment by Zidane** [comment]
Closing due to no response.
