### ISSUE TITLE
OTG World not Loading when installing new Dimension mods 

### ISSUE THREAD

**Issue by vCrimez** [SpongePowered/SpongeForge#3184]
I am running a big modpack (307 mods) and decieded to add aome new dimension mods to my world.
Now the problem is that i cant load the world because i get the notification that says there is a problem with OTG.

**Comment by dualspiral** [comment]
It's a known issue: https://docs.spongepowered.org/stable/en/server/spongineer/incompatible.html#open-terrain-generator-otg. There isn't anything we can do about it - we generally recommend pre-genning the world with OTG and not Sponge, then remove OTG and re-add Sponge.
