### ISSUE TITLE
Crash with AE2 exist

### ISSUE THREAD

**Issue by scottctd** [SpongePowered/SpongeForge#3185]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.2.3
- Forge version: 2854
- Java version: 8u241
- Operating System: Win10

- Plugins/Mods: Just AE2 and Sponge

**Issue Description**
Starting few seconds and crash.
I guess the crash occurred when the world was creating.
If I use forge server create the world firstly, and then add sponge, everything works fine.
The following Log and Crash-Report is the best description.

[CrashReport](https://gist.github.com/ScottCTD/b534388b99dca7b53c8377d7f35ca803)
[Log](https://gist.github.com/ScottCTD/1dfbfb1cf3ec282e309452c03c628be6)

I dont think this will happen in the older version of sponge because previously in the March, AE2 and Sponge work finely.
Plus AE2 hadn't been update for a long time, so I guess it is triggered by Sponge

**Comment by sidboy55555** [comment]
I've exactly the same error, tried to get support from ae2. but it seems they are to "busy" to even take a look on this issue.
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4470

**Comment by hilookas** [comment]
Hey, I have the same problem.

You can try to use spongeforge-1.12.2-2838-7.2.2 . It works for me.

**Comment by dualspiral** [comment]
@JBYoshi This is related to your world serialisation behaviour changes - can you take a look at this? It's failing because AE2 checks to see if a world directory exists, basically, and if it doesn't, it bombs out. We're no longer creating world directories early enough by the looks of it.

[The error in the logs points to here in AE2 if you need to trace what's going on](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/rv6-1.12/src/main/java/appeng/core/worlddata/WorldData.java#L79).

**Comment by JBYoshi** [comment]
Based on my investigation, it seems that Sponge's overwrite of `DimensionManager.getCurrentSaveRootDirectory()` - which AE2 calls [here](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/rv6-1.12/src/main/java/appeng/core/worlddata/WorldData.java#L127) - returns a non-`null` value in cases where Forge still returns `null`; specifically, Forge only returns a value if the `WorldServer` object has already been created, while Sponge returns one as soon once the world directory is known to the engine. Removing Sponge's overwrite of that method allows the server to start up properly. (The rerouting to Sponge's `WorldManager` is handled through a separate overwrite of the `getWorld()` method used in the `getCurrentSaveRootDirectory()` method.)
