### ISSUE TITLE
User not initialised crash

### ISSUE THREAD

**Issue by CJcool06** [SpongePowered/SpongeForge#3187]
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.2.2
- Forge version: 14.23.5.2854
- Java version: 1.8.0_232
- Operating System: Ubuntu Server 18.10 "Cosmic Cuttlefish"

- Plugins/Mods: Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, AurionVoteListener, AwayFromSpawns, BoostersBossBarExtension, Buycraft, CJOptimiser, CmdBuilder, CmdCalendar, CmdControl, CraneGame-sponge, EasyScoreboards, EconomyLite, Enjin Minecraft Plugin, Even More Pixelmon Commands, GTS, GTS Reforged Bridge, GriefDefender, Holograms, HuskyCrates, HuskyUI, ImpactorAPI, ItemTrade, Looking Glass, Lottery, LuckPerms, MyNuzlocke, NuVotifier, Nucleus, PixelHunt, PixelMoney, Pixelmon Wiki Gui, PixelmonBroadcasts, PixelmonEconomyBridge, PixelmonPlaceholders, PixelmonStats, PlaceholderAPI, Plan, PokeBuilder, PokeBus, PokeDisplay, PokeHalt, PokeRanked, PokeRide, PokeTeams, PortaPets, PortaPetsPixelmonGalaxyExtension, Prism, SafeTrade, ServerListPlus, SimpleDexRewards, Spleef-sponge, TabManager, Tags, TeslaCore, TeslaLibs, Tournaments, TwitchMe, VoteForParty, VoxelSniper, WorldEdit, spark

**Issue Description**
A random crash. I have no idea why it happened or how to reproduce it.

Crash Report: https://gist.github.com/CJcool06/9ffe19755c48e8fc41520a118c68494a
Stall Report: https://gist.github.com/CJcool06/e7f537513556ea86345732f663940525
Full Log: https://gist.github.com/CJcool06/d3b7fcd6a656920ca904b01128f13a96

**Comment by clienthax** [comment]
Retest with latest
