### ISSUE TITLE
digBlockWith(ItemStack) not implimented, or am i using incorrectly

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/SpongeForge#319]
[00:58:16] [Server thread/ERROR] [Sponge]: Could not pass PlayerInteractEvent to SpongePlugin:SupertoolSuite{0.0.9}
java.lang.AbstractMethodError: net.minecraft.world.World.digBlockWith(IIILorg/spongepowered/api/item/inventory/ItemStack;)Z

Forge-1499+ Sponge-1499-532

I want to "insta-break" particular blocks, but have them drop what they would if mined (bukkit's  breakNaturally() in the BlockDamageEvent).  With no equivalent 'block-damage-event' that happens upon the first tap, I'm using the player-interact-block event to capture that first attack-tap.  And if the item held is the right type of tool, and the block is a instabreakable block.. then I am using digBlockWith() to make it break that block as if broken with a particular tool, that tool being what is being held (aka, instabreak diamond ore with wood pick = nothing, with diamond pick = diamonds, and in theory, with a silk-touch pick, diamond-ore...)

=============

event.getBlock().digBlockWith(handtool);  //handtool is the ItemStack of ..getItemInHand().getItem();

Am I interpreting the method correctly, but it is not implimented, or am I misusing it?

**Comment by JBYoshi** [comment]
`java.lang.AbstractMethodError` means the method isn't implemented.

**Comment by simon816** [comment]
@JBYoshi is correct, the simulated methods aren't implemented yet.
My pull request https://github.com/SpongePowered/SpongeCommon/pull/86 adds them, there's a few discussion points that would be good to clear up before merging. I'll take a look at it again in a few days.

**Comment by theboomer** [comment]
@simon816, @JBYoshi 
Revisiting this process in one of the first plugin port-attempts to close things out...

The new system has the dig.. methods in the PlayerSimulator, and it would 
SEEM  like it would be utilized as such:

blocklocation.getExtent().getPlayerSimulator().digBlockWith(block.getBlockPosition(), itemstack);

I'm getting an abstract-error, "Method.../PlayerSimulator is abstract"  (spongeforge 1577-867; api-167)
Is this due to still not being implimented at all, or misreading how to create/access the player simulator?

**Comment by JBYoshi** [comment]
All `AbstractMethodError`s are due to an unimplemented method.

**Comment by Aaron1011** [comment]
Closing this, as it's superseded by https://github.com/SpongePowered/SpongeCommon/pull/86
