### ISSUE TITLE
Sponge and TabList plugin

### ISSUE THREAD

**Issue by avescarelo** [SpongePowered/SpongeForge#3190]
**I am currently running**
    Minecraft: 1.12.2
    SpongeAPI: 7.2.0-94d7fb22f
    Sponge: 1.12.2-7.2.4-SNAPSHOT
    SpongeForge: 1.12.2-2838-7.2.4-RC4058
    Minecraft Forge: 14.23.5.2847
    JVM: 1.8.0_252/64-bit (Private Build)
    OS: Linux (4.19.0-041900-generic/amd64)

**Issue Description**
Hello, this issue was created at the request of the plugin developer Tab, for the sponge.
Please, check them

(In short, the request is to add new placeholders and round their values)

Link to original issue (Plugin): [https://github.com/montlikadani/TabList/issues/161](https://github.com/montlikadani/TabList/issues/161)

**Comment by dualspiral** [comment]
> (In short, the request is to add new placeholders and round their values)

That's totally on them, not us.
