### ISSUE TITLE
Bug with returning player health

### ISSUE THREAD

**Issue by avescarelo** [SpongePowered/SpongeForge#3191]
Tested now with
```java
p.get(Keys.HEALTH).get()
```
It's the same thing when you die. So if you die somehow (/kill), and respawns, then your current health returns as 0.0. 
This can reproduces in `7.2.4-RC378` version of Sponge and using api-8.

_Originally posted by @montlikadani in https://github.com/montlikadani/TabList/issues/161#issuecomment-663821784_

**Comment by gabizou** [comment]
Closing as it's a plugin issue. Explanation given in the issue. Next time please use the format.
