### ISSUE TITLE
Inconsistent NBT serialization/deserialization

### ISSUE THREAD

**Issue by LuxusDarkangel** [SpongePowered/SpongeForge#3194]
**I am currently running**
- SpongeForge version: 1.12.2-2838-7.2.4-RC4061
- Forge version: forge-1.12.2-14.23.5.2854
- Java version: Java 8 update 262
- Operating System: Windows 10 / Ubuntu Server 20.04

- Plugins/Mods:
Anvil 0.2.0
Datasync 0.7.0
CustomNPCs 05Jul20

**Issue Description**
I'm using the plugin [DataSync](https://ore.spongepowered.org/AnvilPowered/DataSync) to synchronize inventories between servers, and the mod CustomNPCs. CustomNPCs adds data to items as part of it's script system, then DataSync serializes the player's inventory and saves it on a database (xodus), and is then retrieved and deserialized on a second server. This way, the player has the same inventory on both servers.

The expected behaviour is: CustomNPC's NBT data is properly serialized/deserialized and the item has the same NBT on both servers, but I made a quick diagram to show what happens instead:

https://i.imgur.com/gHLFeE0.png

As you can see, the original NBT ends up being the "tag" package.

This is DataSync's serialization code as pointed by it's author: https://github.com/AnvilPowered/DataSync/blob/4f6ae9f053a39c2ab6a6b8332e2bf8caf203e600/datasync-sponge/src/main/java/org/anvilpowered/datasync/sponge/serializer/SpongeInventorySerializer.java#L54

Log: https://gist.github.com/LuxusDarkangel/14624359da7e136c9c2144f463cfaf7c

**Comment by dualspiral** [comment]
I'm not sure about this.

Basically, `toContainer()` tries to prune empty compounds in NBT. The key word is tries, it's not particularly good at removing compounds that only contains empty compounds. So the removal of compounds is expected (and the Minecraft coded often completely removes empty compounds) but it doesn't always prune them completely. I wonder if we _shouldn't_ do that.

I'm stumped over the addition of the `tag` compound. I can see no reason in our code as to why that might happen, and through testing I couldn't get `tag` to appear. I created an apple and shoved some data on the container, with empty compounds being one of the tests. Repeated seralisation and deserialisation did not give a `tag` compound.

(Note, to complicate this, this involves the capabilities system in Forge, though I saw nothing particularly interesting in the Forge specific mixins for ItemStack (and the associated hooks)).

**Comment by LuxusDarkangel** [comment]
Okay, i've been doing more tests based on what you told me, those are my conclusions:

1.- `customnpcs:itemscripteddata` compound is always present, if it gets deleted it's immediately re-added (this is expected as I stated before, It's needed for the scripting system). I'm not sure if this is CustomNpc's own functionality or how Forge capabilities work.

2.- Minecraft does indeed prune every empty compound. If I remove CNPCs, `customnpcs:itemscripteddata` is pruned, and the same happens with every single empty compound I create in the player's .dat. BUT, If I name the compound `tag` (yes, the same name of the compound created on deserialization), it never gets pruned.

I guess the possible fixes are: `toContainer()` doesn't prune empty compounds and lets Mojang's code handle that, or `tag` gets removed on deserialization (But I imagine there's a reason why it's not removed)

**Comment by dualspiral** [comment]
> or tag gets removed on deserialization (But I imagine there's a reason why it's not removed)

That's backwards. The question is actually "why does that appear?", not "why aren't we removing it?" I think the bug is that `tag` is appearing in the first place, that's what is confusing me.

**Comment by dualspiral** [comment]
Oh, no, I'm a fool, I see it.

Basically, it comes down to the `DataContainer` not pruning empty compounds properly, Sponge has just set an empty compound (as opposed to a `null` one) so this empty compound appears.

Gonna do some testing but I should have this fixed soon.

**Comment by dualspiral** [comment]
https://github.com/SpongePowered/SpongeCommon/commit/16b0cfa3572f9946a94a3ece56e56c14d4189503

**Comment by LuxusDarkangel** [comment]
Works perfectly now. Thank you!
