### ISSUE TITLE
CommandCallable Command Alias Issue

### ISSUE THREAD

**Issue by mrgoodrich** [SpongePowered/SpongeForge#320]
### Description
In CommandCallable, the getHelp method and other methods do not recognize all CommandService registered command aliases.

### Proof Explanation
In my example below, I show how my plugin recognizes both the /tp and /teleport commands.  They use the same class, and are simply aliases of each other.  I then do /help for each of the aliases, but only /teleport shows the help, and /tp shows as unrecognized.  There is also a picture showing the line registering the command. Note: I didn't quite catch the first command I ran, but it was /tp.

### Registering the Command
![screen shot 2015-08-01 at 11 39 56 pm](https://cloud.githubusercontent.com/assets/10081869/9025069/1f527da8-38a8-11e5-9647-9decd7de9b6e.png)

### Running the Test Process Explained Above
![spongeproof](https://cloud.githubusercontent.com/assets/10081869/9025071/2e7cee76-38a8-11e5-8d4e-b7bd6b734bf3.gif)

**Comment by Zidane** [comment]
@zml2008 or @JBYoshi

Need you to look into this

**Comment by JBYoshi** [comment]
@Zidane I'll look into this.

**Comment by JBYoshi** [comment]
I can't reproduce this. @mrgoodrich Does this still happen with the latest Sponge?

Commands:
`/echo Hello World` -> `You ran the command. Arguments: "Hello World"`
`/doecho Hello World` -> `You ran the command. Arguments: "Hello World"`
`/help echo` -> `long description`
`/help doecho` -> `long description`

Code: (Yes I know I'm not using `CommandSpec`. I wanted to get a working command quickly, so I just had my IDE generate the methods for me.)
```java
package jbyoshi.sponge.test;

import com.google.common.base.Optional;
import com.google.common.collect.ImmutableList;
import org.spongepowered.api.event.Listener;
import org.spongepowered.api.event.game.state.GameInitializationEvent;
import org.spongepowered.api.plugin.Plugin;
import org.spongepowered.api.text.Text;
import org.spongepowered.api.text.Texts;
import org.spongepowered.api.util.command.CommandCallable;
import org.spongepowered.api.util.command.CommandResult;
import org.spongepowered.api.util.command.CommandSource;

import java.util.List;

@Plugin(id = "jbyoshi.sponge.test", name="JBYoshi Sponge Test")
public final class SpongeTestPlugin implements CommandCallable {
    
    @Listener
    public void init(GameInitializationEvent e) {
        e.getGame().getCommandDispatcher().register(this, this, "echo", "doecho");
    }

    @Override
    public CommandResult process(CommandSource source, String arguments) {
        source.sendMessage(Texts.of("You ran the command. Arguments: \"" + arguments + "\""));
        return CommandResult.success();
    }

    @Override
    public List<String> getSuggestions(CommandSource source, String arguments) {
        return ImmutableList.of();
    }

    @Override
    public boolean testPermission(CommandSource source) {
        return true;
    }

    @Override
    public Optional<? extends Text> getShortDescription(CommandSource source) {
        return Optional.of(Texts.of("short description"));
    }

    @Override
    public Optional<? extends Text> getHelp(CommandSource source) {
        return Optional.of(Texts.of("long description"));
    }

    @Override
    public Text getUsage(CommandSource source) {
        return Texts.of("[args]");
    }
}
```

**Comment by Zidane** [comment]
@JBYoshi 

May be worth ensuring it isn't something wrong with CommandSpec.

**Comment by Zidane** [comment]
Also test with overwriting a Vanilla command unless echo is one lol.

**Comment by JBYoshi** [comment]
@Zidane Yep, it's a problem with overriding vanilla commands. I changed the `init()` line to:

```java
e.getGame().getCommandDispatcher().register(this, this, "tp", "echo", "give");
```

Typing `/help tp` or `/help give` fails, but typing `/help jbyoshi.sponge.test:tp` or `/help jbyoshi.sponge.test:give` works. It happens with both `/tp` and `/give`, so it's regardless of the primary alias. I'll keep looking into it.

**Comment by JBYoshi** [comment]
Actually, it's a problem anytime there are multiple commands registered with the same alias. I'm about to make a PR for it.
