### ISSUE TITLE
I just need to understand whats going on

### ISSUE THREAD

**Issue by Lazurecks** [SpongePowered/SpongeForge#3200]
Having issues with this server and here's what its yelling at me for

---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (spongeforge-1.12.2-2838-7.2.4-RC4071.jar)
Contact their authors BEFORE contacting forge

// I'm sorry, Dave.

Time: 8/20/20 7:16 PM
Description: Exception in server tick loop

Missing Mods:
	unknown : need any: have missing

Missing Mods:
	unknown : need any: have missing

net.minecraftforge.fml.common.MultipleModsErrored
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:300)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:572)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:300)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:572)

-- Sponge PhaseTracker --
Details:
	Phase Stack: [Empty stack]
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$zjf000$onCrashReport(MinecraftServer.java:4687)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:889)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:371)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:558)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.19.0-9-amd64
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1358304096 bytes (1295 MB) / 2466250752 bytes (2352 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -Xmx4096M -Xms1024M -XX:ParallelGCThreads=2 -XX:ThreadStackSize=512
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 28 mods loaded, 28 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	Mods:

	| State | ID           | Version                  | Source                                     | Signature                                |
	|:----- |:------------ |:------------------------ |:------------------------------------------ |:---------------------------------------- |
	| L     | minecraft    | 1.12.2                   | minecraft.jar                              | None                                     |
	| L     | mcp          | 9.42                     | minecraft.jar                              | None                                     |
	| L     | FML          | 8.0.99.99                | custom.jar                                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| L     | forge        | 14.23.5.2854             | custom.jar                                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| L     | spongeapi    | 7.2.0-1b3861cc7          | spongeforge-1.12.2-2838-7.2.4-RC4071.jar   | None                                     |
	| L     | sponge       | 1.12.2-7.2.4-SNAPSHOT    | spongeforge-1.12.2-2838-7.2.4-RC4071.jar   | None                                     |
	| L     | spongeforge  | 1.12.2-2838-7.2.4-RC4071 | spongeforge-1.12.2-2838-7.2.4-RC4071.jar   | None                                     |
	| L     | pixelauction | 1.2.3                    | PixelAuction-1.12.2-1.2.3-forge-server.jar | None                                     |
	| L     | pixelmon     | 8.0.2                    | Pixelmon-1.12.2-8.0.2-universal.jar        | None                                     |
	| L     | pixelrustles | 1.0.5                    | Rustles-1.12.2-1.0.5-universal.jar         | None                                     |
	| L     | wondertrade  | 4.6.2                    | WonderTrade-1.12.2-4.6.2-universal.jar     | None                                     |

	Plugins:

	| State | ID                       | Version            | Source                                             | Signature |
	|:----- |:------------------------ |:------------------ |:-------------------------------------------------- |:--------- |
	| L     | carrotshop               | 1.19-S7.1-MC1.12.2 | CarrotShop-1.19-S7.1-MC1.12.2.jar                  | None      |
	| L     | easykits                 | 0.2.0              | easykits-7.1.0-0.2.0.jar                           | None      |
	| L     | evenmorepixelmoncommands | 5.1.3              | EvenMorePixelmonCommands-1.12.2-5.1.3.jar          | None      |
	| L     | griefprevention          | 1.12.2-4.3.0.692   | griefprevention-1.12.2-4.3.0.692.jar               | None      |
	| L     | luckperms                | 5.1.93             | LuckPerms-Sponge-5.1.93.jar                        | None      |
	| L     | mirage                   | 1.3.16             | Mirage.jar                                         | None      |
	| L     | mmctickets               | 2.0.7              | MMCTickets-2.0.7-API-7.jar                         | None      |
	| L     | pixelmonbroadcasts       | 0.4.2              | PixelmonBroadcasts-1.12.2-0.4.2.jar                | None      |
	| L     | rankup                   | 7922               | Rankup-V7922-API7-plugin.jar                       | None      |
	| L     | rustles-adapter          | 1.0.0              | Rustles-1.12.2-1.0.5-universal.jar                 | None      |
	| L     | tabmodifier              | 1.4.1              | TabModifier-1.4.1.jar                              | None      |
	| L     | teslacrate               | 3.0.0-pr5          | TeslaCrate-s7.1-t1.1.6-v3.0.0-pr5.jar              | None      |
	| L     | totaleconomy             | 1.8.1              | TotalEconomy-1.8.1.jar                             | None      |
	| L     | universeguard            | 2.25               | UniverseGuard-2.25.jar                             | None      |
	| L     | vanish                   | 4.1.1              | vanish.jar                                         | None      |
	| L     | voxelsniper              | 8.5.0              | VoxelSniper-8.5.0.jar                              | None      |
	| L     | worldedit                | 6.1.10-SNAPSHOT    | worldedit-sponge-api7.1.0-6.1.10-SNAPSHOT-dist.jar | None      |

	Loaded coremods (and transformers): 
SpongeCoremod (spongeforge-1.12.2-2838-7.2.4-RC4071.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)

**Comment by dualspiral** [comment]
**Github issues are for reporting bugs and requesting features in Sponge.** As this issue is a request for support, I am closing this issue.

The following resources are available to support you in using Sponge - please use these in future unless you are reporting a bug or asking for a new feature:

* Sponge Docs (available in multiple languages): https://docs.spongepowered.org
* Sponge Forums: https://forums.spongepowered.org/
* Sponge Discord: https://discord.gg/sponge

---

This isn't anything to do with Sponge anyway. One of your mods looks like it's missing a dependency or outright failing, take a look at your log. Given you're primarily running Pixelmon, it might be worth asking their support because someone might have a better idea.
