### ISSUE TITLE
[LoadingCrash Server] (already try to rename sponge into _.asponge)

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#3207]
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.3.0
- Forge version: 1.12.2-14.23.5.2838-universal
- Java version: 8
- Operating System: Win10

- Plugins/Mods:
   Animania
   Antique Atlas
   B3M
   BackPack
   BiblioCraft
   CarryOn
   Chickens chunk
   Chisel
   CMD Cam
   CodeChickens lib
   CraftStudioApi
   CreativeCore
   CTM
   CustomNPC
   DavinciVessels
   Device Mods
   Dynamic trees
   Dynamic trees for HarvestCraft
   Fossils&Archeology
   Furniture
   HideNames
   Immersive Engineering
   Immersive RailRoading
   IronChest
   JurassicCraft
   llibrary
   Malisiscore
   Malisis Doors
   Mantle
   MinecraftChomium Embedded Frame
   Mine Jurassic
   MJRLegendsLib
   MoBends
   Modernwarfare
   MovingWorld
   Orelib
   Pam's HarvestCraft
   RemoveHudButNotHand
   SereneSeasons
   Shootit
   Snow accumulation
   Subcommonlib
   Tinkers Construct
   Telepads
   TorchMaster
   Track API
   VoiceChat
   WebDisplay Mod

**Issue Description**
Crash when launching SpongeForge

https://gist.github.com/Arkios366/757b85b32f16258f200e45f4ff93a930

**Comment by Zidane** [comment]
One of your mods is interfering with our injection. Unfortunately you'll have to pull mods 1 by 1 until you figure out the incompatibility.

**Comment by clienthax** [comment]
my bets are on B3M-TimeSpeed-1.12.2-17.jar
