### ISSUE TITLE
LLibrary Core crash

### ISSUE THREAD

**Issue by V3X-source** [SpongePowered/SpongeForge#3211]
I made a mod package in minecraft this problem occurred when using llibrary core and wearables mods together my version 1.12.2 please help

---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 9/22/20 9:39 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.entity.EntityLiving$SpawnPlacementType.canSpawnAt(Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;)Z
	at net.minecraft.world.WorldEntitySpawner.func_180267_a(WorldEntitySpawner.java:226)
	at net.minecraft.world.WorldEntitySpawner.func_77191_a(WorldEntitySpawner.java:282)
	at net.minecraft.world.gen.ChunkGeneratorOverworld.func_185931_b(ChunkGeneratorOverworld.java:466)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:999)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:344)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:173)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:196)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1479202424 bytes (1410 MB) / 2706374656 bytes (2581 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G
	IntCache: cache: 14, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_C6 37 mods loaded, 37 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                | Version                | Source                                                | Signature                                |
	|:------ |:----------------- |:---------------------- |:----------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft         | 1.12.2                 | minecraft.jar                                         | None                                     |
	| LCHIJA | mcp               | 9.42                   | minecraft.jar                                         | None                                     |
	| LCHIJA | FML               | 8.0.99.99              | forge-1.12.2-14.23.5.2854.jar                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge             | 14.23.5.2854           | forge-1.12.2-14.23.5.2854.jar                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | voxelmap          | 1.9.10                 | VoxelMap-Mod-1.12.2.jar                               | None                                     |
	| LCHIJA | ichunutil         | 7.2.2                  | iChun-Util-Mod-1.12.2.jar                             | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | backtools         | 7.0.1                  | Back-Tools-Mod-1.12.2.jar                             | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | backpack          | 3.0.2                  | Backpacks-Mod-1.12.2.jar                              | None                                     |
	| LCHIJA | battletowers      | 1.6.5                  | BattleTowers-Mod-1.12.2.jar                           | None                                     |
	| LCHIJA | baubles           | 1.5.2                  | Baubles-Mod-1.12.2.jar                                | None                                     |
	| LCHIJA | betterthanmending | 1.1.1                  | Better-Than-Mending-Mod-1.12.2.jar                    | None                                     |
	| LCHIJA | jei               | 4.15.0.297             | jei_1.12.2-4.15.0.297.jar                             | None                                     |
	| LCHIJA | botania           | r1.10-363              | Botania-Mod-1.12.2.jar                                | None                                     |
	| LCHIJA | camera            | 1.0.10                 | Camera-Mod-1.12.2.jar                                 | None                                     |
	| LCHIJA | deconstruction    | 3.0.4                  | Deconstruction-Table-Mod-1.12.2.jar                   | None                                     |
	| LCHIJA | dimdoors          | 3.0.9+287              | Dimensional-Doors-Mod-1.12.2.jar                      | None                                     |
	| LCHIJA | doubledoors       | 1.2                    | Double-Doors-Mod-1.12.2.jar                           | None                                     |
	| LCHIJA | ebwizardry        | 4.1.4                  | Wizardry-Mod-1.12.2.jar                               | None                                     |
	| LCHIJA | extra_spells      | 1.0.3                  | Extra-Spells-Mod-1.12.2.jar                           | None                                     |
	| LCHIJA | mcwfurnitures     | 1.0                    | Macaws-Furniture-Mod-1.12.2.jar                       | None                                     |
	| LCHIJA | magicclover       | 1.12-0.7.8             | Magic-Clover-Mod-1.12.2.jar                           | None                                     |
	| LCHIJA | millenaire        | Millénaire 7.2.1       | Millenaire-Mod-Universal-1.12.2.jar                   | None                                     |
	| LCHIJA | mobdismemberment  | 7.0.0                  | Mob-Dismemberment-Mod-1.12.2.jar                      | None                                     |
	| LCHIJA | movingelevators   | 1.2.4                  | Moving-Elevators-Mod-1.12.2.jar                       | None                                     |
	| LCHIJA | tinymobfarm       | 1.0.5                  | Tiny-Mob-Farm-Mod-1.12.2.jar                          | None                                     |
	| LCHIJA | torohealthmod     | 1.12.2-11              | ToroCrafts-Damage-Indicators-Mod-1.12.2.jar           | None                                     |
	| LCHIJA | uppers            | 0.0.6                  | Uppers-Mod-1.12.2.jar                                 | None                                     |
	| LCHIJA | waystones         | 4.1.0                  | Waystones-Mod-1.12.2.jar                              | None                                     |
	| LCHIJA | llibrary          | 1.7.19                 | llibrary-1.7.19-1.12.2.jar                            | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | wearables         | 1.1.3                  | wearables-1.1.3.jar                                   | None                                     |
	| LCHIJA | drplibrary        | 1.12.2-0.1.3-SNAPSHOT  | drplibrary-1.12.2-0.1.3-SNAPSHOT-20190129.104240.jar  | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| LCHIJA | drpcmblueprints   | 1.12.2-1.2.3           | drpcmblueprints-1.12.2-1.2.3.jar                      | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| LCHIJA | drpcmmaarg        | 1.12.2-0.10.0-SNAPSHOT | drpcmmaarg-1.12.2-0.10.0-SNAPSHOT-20181116.024036.jar | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| LCHIJA | drpcmguis         | 1.12.2-0.0.2-SNAPSHOT  | drpcmguis-1.12.2-0.0.1-SNAPSHOT-20181125.070253.jar   | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| LCHIJA | drpcore           | 1.12.2-0.4.7           | Dark-Roleplay-Core-1.12.2.jar                         | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| LCHIJA | drpcmlocks        | 1.12.2-1.0.1           | drpcmlocks-1.12.2-1.0.0-SNAPSHOT-20181126.061203.jar  | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| LCHIJA | drpmedieval       | 1.12.2-0.3.6           | Dark-Roleplay-Medieval-Mod-1.12.2.jar                 | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by ImMorpheus** [comment]
Please follow the issue template, it's actually rather important if you want to get dev attention to fix your issue.

Edit this issue with the required details / template, and I'll reopen and hide this comment.
