### ISSUE TITLE
[discussion] Why not using latest forge release for 1.12.2

### ISSUE THREAD

**Issue by k1r0s** [SpongePowered/SpongeForge#3222]
related: https://github.com/MysticMods/Roots/issues/604

I'd always asked my self why sponge 1.12 never gets updated to the latest forge release. Whats the main issue?

**Comment by dualspiral** [comment]
It works fine with it, we just build against 2838. Did you _try_ running Sponge on 2847? It works fine.

Further, Github issues are **not** for discussion. If you need support, visit our [Forums](https://forums.spongepowered.org/) or [Discord](https://discord.gg/sponge)
