### ISSUE TITLE
[1.12.2] Client crash with newer builds

### ISSUE THREAD

**Issue by KorewaLidesu** [SpongePowered/SpongeForge#3230]
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.3.1-RC4084 and above
- Forge version: 14.23.5.2838
- Java version: AdoptOepnJDK (jdk-8.0.272.10-openj9)
- Operating System: Window 7

- Plugins/Mods: Forge + SF

**Issue Description**
Install any build (RC4084 and above) will make game crash
[Log](https://gist.github.com/madokaorimura/b8f84ae05a2c4f977a00fb844b1857de) (only error code)

~~Note: RC4082 work out fine~~

**Comment by dualspiral** [comment]
We know, our downloads site has pushed development, rather than production builds out. We're working on a replacement. For now, please use the recommended build, that should work fine.
