### ISSUE TITLE
Incompatible with forge 1.12.2-14.23.5.2854 starting from spongeforge 1.12.2-2838-7.3.1-RC4084

### ISSUE THREAD

**Issue by Somiona** [SpongePowered/SpongeForge#3236]
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.3.1-RC4084
- Forge version: 1.12.2-14.23.5.2854
- Java version: openjdk version "1.8.0_265"
- Operating System: Windows 10 19402.685

- Plugins/Mods:
	Mods (7): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, SpongeForge

**Issue Description**

I have notice that starting from commit c131590, the spongeforge does no longer compatible with forge version 2854, but other previous version worked well. Notice that this is a early stage crash and seems to related with some missing api that sponge tried to mixin but forge 2854 removed them.

Some of mods I'm willing to run on my server are gregtech ce and animania, but they're depending on forge 2854 as minimum version so I need to either use a older version of sponge or giving up to add GTCE which I feel a sence of bad solution either way.

[2021-01-02-6.log](https://gist.github.com/Somiona/dbe666f0db7832eded30127432faafcb)
[debug.log](https://gist.github.com/Somiona/bc27ff81a010da8fcd168ee0270e2595)

**Comment by dualspiral** [comment]
That build is broken. Use the latest recommended build.
