### ISSUE TITLE
Plugin issue

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#3238]
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.3.0.jar
- Forge version: forge-1.12.2-14.23.5.2838
- Java version: 8
- Operating System: Windows 10

- Plugins/Mods: 

BetterAnimationsCollection2-v1.0.1-1.12.2
CoffeeSpawner-1.12-1.0.2
DoggyTalents-1.12.2-1.15.1.6
DynamicLights-1.12.2
Flan's Mod-1.12.2-5.5.2
InfiniteDispenserX
MCA-1.12.2-6.1.0-sources
Mob-Dismemberment-Mod-1.12.2
Music-Player-Mod-1.12.2
Pogo-Sticks-Mod-1.12.2
TreeChopper-1.12.2-1.2.4
[1.12.2]+SecurityCraft+v1.8.19.1
additional_lights-1.12.2-1.2.0
camera-1.0.8
furniture-6.3.1-1.12.2
iChunUtil-1.12.2-7.2.2
industrialcraft-2-2.8.103-ex112
ism-2.6.1 MC-1.12.2 
journeymap-1.12.2-5.7.1
malisiscore-1.12.2-6.5.1
malisisdoors-1.12.2-7.3.0
obfuscate-0.2.6-1.12.2
parachutemod-1.12.2-1.7.4-446
simplycats-1.12.2-0.0.3.1
u_team_core-1.12.2-2.2.5.147
vehicle-mod-0.41.0-1.12.2

I can use all the mods but i can't use any plugins when i try to make the plugin command it dosen't works.

**Comment by Zidane** [comment]
Closing due to no logs being provided and not following the issue format.
