### ISSUE TITLE
Spongeforge Update

### ISSUE THREAD

**Issue by XiNaru** [SpongePowered/SpongeForge#3239]
Hey I wanted to ask if there are plans to update spongeforge for 1.12.2?
i need forge 14.23.5.2854 for skyfactory 4
and the latest version dont support that

**Comment by clienthax** [comment]
It should work just fine as is

**Comment by XiNaru** [comment]
do not do it.
I wouldn't ask here if it would work.
I put the file in my mods folder and the server crashes.

without the file the server starts.

**Comment by clienthax** [comment]
And yet you didn't upload the crash log?

**Comment by XiNaru** [comment]
I can do it and don't worry, the many errors I have even without spongeforge, but it still works.

but as I said when I put spongeforge into the mods folder it crashes.

But now the crash log (okay, no crash log is created, here the server log: https://pastebin.com/9C3z5VRf

**Comment by clienthax** [comment]
https://github.com/SpongePowered/SpongeForge/issues/3221#issuecomment-719964653

**Comment by XiNaru** [comment]
thanks now it works
