### ISSUE TITLE
Serveur don't start latest build

### ISSUE THREAD

**Issue by Heriptik** [SpongePowered/SpongeForge#3258]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2838-7.3.1-RC4108
- Forge version: 14.23.5.2854
- Java version: 1.8.0_282
- Operating System: Debian 10

- Plugins/Mods: All plugins / mods is in the crash repport

**Issue Description**
Just server don't start
[crash-2021-05-28_01.17.55-server.txt](https://github.com/SpongePowered/SpongeForge/files/6557252/crash-2021-05-28_01.17.55-server.txt)

**Comment by dualspiral** [comment]
https://github.com/SpongePowered/Sponge/pull/3417 has been merged and will fix this when I bump SF.

Thanks for the report!
