### ISSUE TITLE
SpongeForge crashes with latest forge and MCEternal modpack

### ISSUE THREAD

**Issue by YShow** [SpongePowered/SpongeForge#3260]
**I am currently running**
- SpongeForge version: 1.12.2-2838-7.3.0
- Forge version: forge-1.12.2-14.23.5.2855
- Java version: java 8
- Operating System: Opensuse Tumbleweed

- Plugins/Mods: MCEternal with nucleus and luckperms

**Issue Description**
Starting the server with newest forge and sponge crashes the server before it even finishes loading
[error](https://gist.github.com/YShow/15ee861f2fdff15f3f9a8a525a02237d)

**Comment by gabizou** [comment]
since you didn't include the full log, I can only assume you have Hammercore installed, there's a way to fix it according to the [troubleshooting/incompatibilities docs page.](https://docs.spongepowered.org/stable/en/server/spongineer/incompatible.html?highlight=incompatibility#hammer-core)
