### ISSUE TITLE
Installer crash for Forge 1.12.2-14.23.5.2838

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#3262]
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.3.0 
- Forge version: 1.12.2-14.23.5.2838
- Java version: jre1.8.0_291
- Operating System: Windows 10

- Plugins/Mods: none

**Issue Description**
Everytime I run the Forge installer, it gives me an Exception etc, which doesn't open the installer at all and only gives me the log. It only applies for this specific Forge Version. May it be possible to update SpongeForge so it's compatible with Forge 1.12.2 - 14.23.5.2855. This version works for me at least, which is the latest version of Forge 1.12.2.

**Link to the Log**
https://gist.github.com/EnderB0YHD/f830fc6cbda27a9a3ec2d1b0d8188bcf

**Comment by dualspiral** [comment]
The Forge installer is nothing to do with us, it doesn't remotely touch Sponge. This is not a Sponge bug.

Sponge works with 2855 no problem. We just build against 2838.
