### ISSUE TITLE
the game crash at 3/7

### ISSUE THREAD

**Issue by alsaadiGamer** [SpongePowered/SpongeForge#3264]
**modpack i made on my own**

- SpongeForge version:
- Forge version:  1.12.2 
- Java version: 1.8.0_51, Oracle Corporation
- Operating System: Windows 10 (amd64) version 10.0

- Plugins/Mods:
- 140 mod they are mentioned in the log 

**Issue Description**
crash at 3/7 while starting + it's a new experience for me i always encounter problems at 2/7 only 

https://gist.github.com/alsaadiGamer/6b0b6c87075a07a7f9ff5a20cf20e778

**Comment by clienthax** [comment]
Not a sponge issue
java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded
