### ISSUE TITLE
Honestly idk whats happening Crash on Startup

### ISSUE THREAD

**Issue by Faloc** [SpongePowered/SpongeForge#3265]
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.3.0
- Forge version: Forge 2838
- Java version: 8
- Operating System: jre1.8.0_301

- Plugins/Mods: Its like 200+ im not finna write all the mods down

**Issue Description** The game just crashes instantly as you hit play not ever 3 seconds the loading screen cant open.

https://gist.github.com/Faloc/1ac77149c57720775253566cc4da1615

**Comment by gabizou** [comment]
One of the core mods is attempting to relocate or strip the signing information of the Mixin dependency. But, you're not even using SpongeForge on the client, ask for help with the mods support forums/discords/whatever that you have installed.
