### ISSUE TITLE
Crash Involves Sponge Powered

### ISSUE THREAD

**Issue by kicekkic** [SpongePowered/SpongeForge#3273]
I am currently running modded minecraft and i dont know why crash involves spongepowered
- SpongeForge version: n/a
- Forge version: 14.23.5.2855
- Java version: 1.8.0_311-b11
- Operating System: Windows 10 Pro, 64 bit

- Plugins/Mods:
- I have 498 mods so it would take eternity to type them all.

**Issue Description**
I don't why my minecraft keeps crashing and the crash log says something about spongepowered. Please help.

Crash Log: https://gist.github.com/kicekkic/16c949a3083d04f2de7a40b64dcc7108

**Comment by gabizou** [comment]
Not SpongeForge, some oddity in your setup, a very old version of Java 8, and mixinbootstrap isn’t a project we manage (seek out their support)
