### ISSUE TITLE
Hey, Wondering If Anyone Could Help Me With My Crashes On My CurseForge Modpack :)

### ISSUE THREAD

**Issue by EmbyExists** [SpongePowered/SpongeForge#3274]
**I am currently running**
- Forge version:  Latest
- Java version:  Latest
- Operating System: Windows 11

- Plugins/Mods:

Alex's Mobs

AppleSkin

Aquaculture 2

Artifacts

Astral Sorcery

AutoRegLib

Back Tools

Bed Benefits

Better Animations Collection

Better Diving

Better Foliage

Better Smithing

Better Than Mending

Better Third Person

BetterEnd (Forge)

Biomes O' Plenty

Blood Magic

Bookshelf

Bountiful (Forge)

BountifulBaubles

Caelus API (Forge)

Castle in the Sky

CaveBiomeAPI [Forge]

Citadel

CleanCut

Cloth Config API (Forge)

Collective (Forge)

Colytra (Forge)

Comforts (Forge)

Curios API (Forge)

Darker Depths

Dungeon Crawl

Dungeons & Artifacts (Overhaul)

Dungeons Plus

Dynamic Lights

Dynamic Surroundings

Dynamic Trees

Dynamic Trees - Biomes O' Plenty

Dynamic Trees - Quark

Dynamic Trees +

Earth Mobs

Eidolon

ExpandAbility

Extended Caves

Fast Leaf Decay

Global XP

Goblin Traders

GraveStone Mod

Hats

Ice and Fire: Dragons

iChunUtil

Improved Backpacks

Inventory HUD+

Inventory Pets

JourneyMap

Just Enough Items (JEI)

Just Enough Resources (JER)

Kotlin for Forge

MC Story Mode Armors [Forge / Fabric]

Mo' Structures (Forge)

Mowzie's Mobs

Nature's Compass

ObserverLib

Odd Water Mobs

Oh The Biomes You'll Go

Paragliders

Puzzles Lib

Quark

Random Loot Mod

Repurposed Structures (Forge)

Rev's Better Structures

Small Ships

Structure Gel API

Structures Plus II

The Abyss: Chapter II

Two Players One Horse

Valhelsia Core

Valhelsia Structures

Vein Mining (Forge)

Village Spawn Point (Forge)

Wall-Jump! [FORGE]

Waystones

YUNG's API (Forge)

YUNG's Better Caves (Forge)

YUNG's Better Dungeons (Forge)

YUNG's Better Mineshafts (Forge)

YUNG's Better Portals (Forge)

YUNG's Better Strongholds (Forge)

YUNG's Bridges (Forge)

YUNG's Extras (Forge)

- Hey! I've been working on the CurseForge, forge modpack for a bit and keep get crashes but this time I can't figure out what mod to delete to fix it. :/ It loads up just fine but when I create and enter a world it crashes after it says "entering world" i believe. Take in mind I don't know much about code at all, just made a github account for help. Thanks! <3

- The crash log: https://gist.github.com/EmbyExists/239a8ff45890cc7b65aadc1f17cb3505

**Comment by zml2008** [comment]
not a Sponge issue - looks like some core mod conflict

**Comment by EmbyExists** [comment]
> ooks like some core mod confli

where should i go for help?

**Comment by EmbyExists** [comment]
> not a Sponge issue - looks like some core mod conflict

where should i go for this? :(

**Comment by gabizou** [comment]
> betterfoliage.refmap.json

ask better foliage devs, but ultimately remove half the mods until the problem doesn't happen, then re-add them in halves until the problem happens. But still, it's a mod conflict between two mods, not SpongeForge (SpongeForge IS a mod, but it's not installed in this case).

**Comment by EmbyExists** [comment]
okay thahanks
