### ISSUE TITLE
Issue with my server

### ISSUE THREAD

**Issue by darknerea** [SpongePowered/SpongeForge#3282]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SecurityCraftLoadingPlugin (1.12.2SecurityCraftv1.9.0.2.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  CreativePatchingLoader (CreativeCore_v1.10.69_mc1.12.2.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.14-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 1/6/22 6:53 PM
Description: Exception ticking world

java.lang.NoClassDefFoundError: mod/mcreator/mcreator_zombieCreeper$ModelZombieCreeper
	at java.lang.Class.getDeclaringClass0(Native Method)
	at java.lang.Class.getDeclaringClass(Unknown Source)
	at java.lang.Class.getEnclosingClass(Unknown Source)
	at java.lang.Class.getSimpleBinaryName(Unknown Source)
	at java.lang.Class.getSimpleName(Unknown Source)
	at atomicstryker.infernalmobs.common.InfernalMobsCore.checkEntityClassAllowed(InfernalMobsCore.java:430)
	at atomicstryker.infernalmobs.common.InfernalMobsCore.isClassAllowed(InfernalMobsCore.java:404)
	at atomicstryker.infernalmobs.common.InfernalMobsCore.processEntitySpawn(InfernalMobsCore.java:366)
	at atomicstryker.infernalmobs.common.EntityEventHandler.onEntityJoinedWorld(EntityEventHandler.java:67)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_780_EntityEventHandler_onEntityJoinedWorld_EntityJoinWorldEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.world.World.func_72838_d(World.java:1209)
	at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1058)
	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:160)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:203)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: mod.mcreator.mcreator_zombieCreeper$ModelZombieCreeper
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 21 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@6dba847b from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 23 more
Caused by: java.lang.RuntimeException: Attempted to load class mod/mcreator/mcreator_zombieCreeper$ModelZombieCreeper for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
	... 25 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.lang.Class.getDeclaringClass0(Native Method)
	at java.lang.Class.getDeclaringClass(Unknown Source)
	at java.lang.Class.getEnclosingClass(Unknown Source)
	at java.lang.Class.getSimpleBinaryName(Unknown Source)
	at java.lang.Class.getSimpleName(Unknown Source)
	at atomicstryker.infernalmobs.common.InfernalMobsCore.checkEntityClassAllowed(InfernalMobsCore.java:430)
	at atomicstryker.infernalmobs.common.InfernalMobsCore.isClassAllowed(InfernalMobsCore.java:404)
	at atomicstryker.infernalmobs.common.InfernalMobsCore.processEntitySpawn(InfernalMobsCore.java:366)
	at atomicstryker.infernalmobs.common.EntityEventHandler.onEntityJoinedWorld(EntityEventHandler.java:67)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_780_EntityEventHandler_onEntityJoinedWorld_EntityJoinWorldEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.world.World.func_72838_d(World.java:1209)
	at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1058)
	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:160)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:203)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['ItzChrisUSA'/258, l='world', x=-383.90, y=70.75, z=100.54]]
	Chunk stats: ServerChunkCache: 631 Drop: 0
	Level seed: -3699634479721821092
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-248,64,256), Chunk: (at 8,4,0 in -16,16; contains blocks -256,0,256 to -241,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 9574 game time, 18758 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 91579 (now: false), thunder time: 50727 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_311, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 608304432 bytes (580 MB) / 3363307520 bytes (3207 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 1 total; -Xmx8G
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 76 mods loaded, 76 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                                | Version           | Source                                             | Signature                                |
	|:------ |:--------------------------------- |:----------------- |:-------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                         | 1.12.2            | minecraft.jar                                      | None                                     |
	| LCHIJA | mcp                               | 9.42              | minecraft.jar                                      | None                                     |
	| LCHIJA | FML                               | 8.0.99.99         | forge-1.12.2-14.23.5.2859.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                             | 14.23.5.2859      | forge-1.12.2-14.23.5.2859.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | creativecoredummy                 | 1.0.0             | minecraft.jar                                      | None                                     |
	| LCHIJA | foamfixcore                       | 7.7.4             | minecraft.jar                                      | None                                     |
	| LCHIJA | securitycraft                     | v1.9.0.2          | 1.12.2SecurityCraftv1.9.0.2.jar                    | None                                     |
	| LCHIJA | actuallyadditions                 | 1.12.2-r152       | ActuallyAdditions-1.12.2-r152.jar                  | None                                     |
	| LCHIJA | baubles                           | 1.5.2             | Baubles-1.12-1.5.2.jar                             | None                                     |
	| LCHIJA | biomesoplenty                     | 7.0.1.2445        | BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar      | None                                     |
	| LCHIJA | bookshelf                         | 2.3.590           | Bookshelf-1.12.2-2.3.590.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | bookworm                          | 1.12.2-2.5.2.1    | bookworm-1.12.2-2.5.2.1.jar                        | None                                     |
	| LCHIJA | codechickenlib                    | 3.2.3.358         | CodeChickenLib-1.12.2-3.2.3.358-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | redstoneflux                      | 2.1.1             | RedstoneFlux-1.12-2.1.1.1-universal.jar            | None                                     |
	| LCHIJA | brandonscore                      | 2.4.20            | BrandonsCore-1.12.2-2.4.20.162-universal.jar       | None                                     |
	| LCHIJA | buildcraftlib                     | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                       | None                                     |
	| LCHIJA | buildcraftcore                    | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                       | None                                     |
	| LCHIJA | buildcraftbuilders                | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                       | None                                     |
	| LCHIJA | buildcrafttransport               | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                       | None                                     |
	| LCHIJA | buildcraftsilicon                 | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                       | None                                     |
	| LCHIJA | ic2                               | 2.8.221-ex112     | industrialcraft-2-2.8.221-ex112.jar                | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | buildcraftcompat                  | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                       | None                                     |
	| LCHIJA | buildcraftenergy                  | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                       | None                                     |
	| LCHIJA | buildcraftfactory                 | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                       | None                                     |
	| LCHIJA | buildcraftrobotics                | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                       | None                                     |
	| LCHIJA | cavern                            | 1.10.6            | Cavern_1.12.2-v1.10.6.jar                          | None                                     |
	| LCHIJA | chameleon                         | 1.12-4.1.3        | Chameleon-1.12-4.1.3.jar                           | None                                     |
	| LCHIJA | chesttransporter                  | 2.8.8             | ChestTransporter-1.12.2-2.8.8.jar                  | None                                     |
	| LCHIJA | jei                               | 4.16.1.301        | jei_1.12.2-4.16.1.301.jar                          | None                                     |
	| LCHIJA | chisel                            | MC1.12.2-1.0.2.45 | Chisel-MC1.12.2-1.0.2.45.jar                       | None                                     |
	| LCHIJA | cofhcore                          | 4.6.6             | CoFHCore-1.12.2-4.6.6.1-universal.jar              | None                                     |
	| LCHIJA | cofhworld                         | 1.4.0             | CoFHWorld-1.12.2-1.4.0.1-universal.jar             | None                                     |
	| LCHIJA | creativecore                      | 1.10.0            | CreativeCore_v1.10.69_mc1.12.2.jar                 | None                                     |
	| LCHIJA | cw                                | 1.0.2             | creature_whisperer_1.0.2.jar                       | None                                     |
	| LCHIJA | cyclopscore                       | 1.6.7             | CyclopsCore-1.12.2-1.6.7.jar                       | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | dmonsters                         | 1.7               | Deadly+Monsters+1.71.jar                           | None                                     |
	| LCHIJA | thermalfoundation                 | 2.6.7             | ThermalFoundation-1.12.2-2.6.7.1-universal.jar     | None                                     |
	| LCHIJA | draconicevolution                 | 2.3.28            | Draconic-Evolution-1.12.2-2.3.28.354-universal.jar | None                                     |
	| LCHIJA | eleccore                          | 1.9.453           | ElecCore-1.12.2-1.9.453.jar                        | None                                     |
	| LCHIJA | endercore                         | 1.12.2-0.5.76     | EnderCore-1.12.2-0.5.76.jar                        | None                                     |
	| LCHIJA | tombstone                         | 4.5.2             | tombstone-4.5.2-1.12.2.jar                         | None                                     |
	| LCHIJA | enderio                           | 5.2.59            | EnderIO-1.12.2-5.2.59.jar                          | None                                     |
	| LCHIJA | mcjtylib_ng                       | 3.5.4             | mcjtylib-1.12-3.5.4.jar                            | None                                     |
	| LCHIJA | elementaldimensions               | 0.4.0             | elementaldimensions-1.12-0.4.0.jar                 | None                                     |
	| LCHIJA | enderiointegrationtic             | 5.2.59            | EnderIO-1.12.2-5.2.59.jar                          | None                                     |
	| LCHIJA | enderiobase                       | 5.2.59            | EnderIO-1.12.2-5.2.59.jar                          | None                                     |
	| LCHIJA | enderioconduits                   | 5.2.59            | EnderIO-1.12.2-5.2.59.jar                          | None                                     |
	| LCHIJA | enderioconduitsappliedenergistics | 5.2.59            | EnderIO-1.12.2-5.2.59.jar                          | None                                     |
	| LCHIJA | enderioconduitsopencomputers      | 5.2.59            | EnderIO-1.12.2-5.2.59.jar                          | None                                     |
	| LCHIJA | enderioconduitsrefinedstorage     | 5.2.59            | EnderIO-1.12.2-5.2.59.jar                          | None                                     |
	| LCHIJA | enderiointegrationforestry        | 5.2.59            | EnderIO-1.12.2-5.2.59.jar                          | None                                     |
	| LCHIJA | enderiointegrationticlate         | 5.2.59            | EnderIO-1.12.2-5.2.59.jar                          | None                                     |
	| LCHIJA | enderiomachines                   | 5.2.59            | EnderIO-1.12.2-5.2.59.jar                          | None                                     |
	| LCHIJA | enderiopowertools                 | 5.2.59            | EnderIO-1.12.2-5.2.59.jar                          | None                                     |
	| LCHIJA | evilcraft                         | 0.10.78           | EvilCraft-1.12.2-0.10.78.jar                       | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | evilcraftcompat                   | 1.0.0             | EvilCraft-1.12.2-0.10.78.jar                       | None                                     |
	| LCHIJA | extrautils2                       | 1.0               | extrautils2-1.12-1.9.9.jar                         | None                                     |
	| LCHIJA | fairylights                       | 2.1.10            | fairylights-2.2.0-1.12.2.jar                       | None                                     |
	| LCHIJA | foamfix                           | 0.10.14-1.12.2    | foamfix-0.10.14-1.12.2.jar                         | None                                     |
	| LCHIJA | howlingmoon                       | 0.9               | howlingmoon-1.12.2-0.9.jar                         | None                                     |
	| LCHIJA | huntingdim                        | 1.0.43            | HuntingDimension-1.12.2-1.0.43.jar                 | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | waila                             | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
	| LCHIJA | infernalmobs                      | 1.7.6             | Infernal-Mobs-Mod-1.12.2.jar                       | None                                     |
	| LCHIJA | ironbackpacks                     | 1.12.2-3.0.8-12   | IronBackpacks-1.12.2-3.0.8-12.jar                  | None                                     |
	| LCHIJA | ironchest                         | 1.12.2-7.0.67.844 | ironchest-1.12.2-7.0.72.847.jar                    | None                                     |
	| LCHIJA | journeymap                        | 1.12.2-5.7.1      | journeymap-1.12.2-5.7.1.jar                        | None                                     |
	| LCHIJA | mca                               | 6.1.0             | MCA-1.12.2-6.1.0-universal.jar                     | None                                     |
	| LCHIJA | netherportalfix                   | 5.3.17            | NetherPortalFix_1.12.1-5.3.17.jar                  | None                                     |
	| LCHIJA | nightmares                        | 1.0.13            | Nightmares-1.12.2-1.0.13.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | rezombiesv15ver1122jar            | 1.5               | Re-Zombies-V1.5-Ver-1.12.2.jar                     | None                                     |
	| LCHIJA | spartanshields                    | 1.5.5             | SpartanShields-1.12.2-1.5.5.jar                    | None                                     |
	| LCHIJA | zawa                              | 1.12.2-2.1.3      | zawa-1.12.2-2.1.3.jar                              | 3ee471ded1bba54aa82f4f5ca5ca82dd67b8ef42 |
	| LCHIJA | zerocore                          | 1.12.2-0.1.2.9    | zerocore-1.12.2-0.1.2.9.jar                        | None                                     |
	| LCHIJA | jade                              | 0.1.0             | Jade-0.1.0.jar                                     | None                                     |
	| LCHIJA | matteroverdrive                   | 0.7.0.0           | MatterOverdrive-1.12.2-0.7.1.0-universal.jar       | None                                     |
	| LCHIJA | eleccoreloader                    | 1.9.453           | ElecCore-1.12.2-1.9.453.jar                        | None                                     |

	Loaded coremods (and transformers): 
SecurityCraftLoadingPlugin (1.12.2SecurityCraftv1.9.0.2.jar)
  
EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
CreativePatchingLoader (CreativeCore_v1.10.69_mc1.12.2.jar)
  
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.14-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Offline mode for dedicated servers is NOT supported by Ender IO.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Authlib is : /C:/Users/chris/Desktop/Mi%20Server/minecraft_server.1.12.2.jar

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	Profiler Position: N/A (disabled)
	Player Count: 1 / 20; [EntityPlayerMP['ItzChrisUSA'/258, l='world', x=-383.90, y=70.75, z=100.54]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by dualspiral** [comment]
Sponge isn't even in that list - nothing to do with us.
