### ISSUE TITLE
Spongepowered error at world load?

### ISSUE THREAD

**Issue by ashymcwashyyy** [SpongePowered/SpongeForge#3283]
I am currently running minecraft 1.16.5 and forge 36.2.20
I am NOT using spongepowered/mixin.
Mod list: 
AbnormalsCore
Architectury
BetterAnimalsPlus
BetterFoliage
Catalogue
Citadel
Configured
Curios Forge
DragonSurvival (flight update)
DungeonCrawl
DungeonsArise
DynamicTrees
DynamicTreesPlus
Environmental
FarmingForBlockHeads
Gekolib Forge
GoblinTraiders
Jei
Kotlinforforge
Mcw Bridges
Mcw Roofs
Mowzies Mobs
Optifine
OverloadedArmorBar
Patchouli
Preformant
SpawnerFix
StrawGolem (reborn)
ToadTerror
Velhelsia Core
Velhelsia Structures
YungsAPI (forge)
YungsExtras (forge)

https://gist.github.com/AnAriesLemur/a8507cbb912effc527b4048a79885f03#file-gistfile1-txt

**Comment by zml2008** [comment]
> I am NOT using spongepowered/mixin.

yes you are (well, a mod you have installed)
at first glance, appears to be a mod conflict involving betterfoliage and optifine, not a Sponge issue.
