### ISSUE TITLE
Crash with Sponge 1.12.2-2838-7.4.7

### ISSUE THREAD

**Issue by Druwan-ctrl** [SpongePowered/SpongeForge#3284]
**I am currently running**
- SpongeForge version: spongeforge-1.12.2-2838-7.4.7
- Forge version: forge-1.12.2-14.23.5.2860
- Java version: 8
- Operating System: Linux

**Issue Description**
Moving from 7.4.4, the new update causes an instant crash and I cannot figure out why. I didn't see others reporting this and since it's a security patch this gave me quite an headache.

[Crash Log](https://gist.github.com/Druwan-ctrl/23b72262d7e4fe18a5416d1bf868b971)

**Comment by dualspiral** [comment]
Delete the libraries folder, re-install Forge - your error tells me you aren't running the updated version of Log4J (which you really need to be thanks to that nasty bug).

The Forge installer for 2860 will sort you out.
