### ISSUE TITLE
[Question]Do SpongeForge 1.12.2 Support Velocity Modern Forwarding?

### ISSUE THREAD

**Issue by Longtianmu** [SpongePowered/SpongeForge#3297]
### Version

7.4.7

### Operating System

Debian 11

### Java Version

Amazon Corretto 8 1.8.0.332

### Plugins/Mods

```shell
blockbuster-2.4.1-1.12.2.jar
deuf-1.1-1.12.2.jar
furniture-6.3.1-1.12.2.jar
mclib-2.3.7-1.12.2.jar
metamorph-1.2.13-1.12.2.jar
worldedit-forge-mc1.12.2-6.1.10-dist.jar
```

### Describe the bug

Just a question

**Comment by zml2008** [comment]
no - also this is a bug tracker not a support forum, ask further questions on Discord
