### ISSUE TITLE
Evil Chickens when EntitySpawnEvent is canceled for all Zombies

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeForge#330]
When the following code is used, "evil chickens" will occasional spawn:
````java
    @Subscribe
    public void onEntitySpawn(EntitySpawnEvent event) {
        if (event.getEntity() instanceof Monster) {
            event.setCancelled(true);
        }
    }
````

I believe these "evil chickens" were originally chicken jockies, and their chicken jockey AI persist, despite having the Zombie removed.

**Comment by bloodmc** [comment]
This shouldn't happen with latest capture logic. Reopen if it does.
