### ISSUE TITLE
Some build errors

### ISSUE THREAD

**Issue by randombyte-developer** [SpongePowered/SpongeForge#353]
Hello!

I cloned the Sponge repo to create a plugin and to test it. After setting up the run configuration I let it run. Then some errors appeared(listing only some): 

- https://github.com/SpongePowered/Sponge/blob/f718f38a12649dd2fd5b8d237cb88e21aeeeab87/src/main/java/org/spongepowered/mod/mixin/entityactivation/MixinWorld.java#L69 getPersistentChunks() isn't in net.minecraft.world.World

- https://github.com/SpongePowered/Sponge/blob/f718f38a12649dd2fd5b8d237cb88e21aeeeab87/src/main/java/org/spongepowered/mod/mixin/core/event/world/MixinEventWorldExplosion.java#L71 getPosition() isn't in net.minecraft.world.Explosion

- https://github.com/SpongePowered/Sponge/blob/f718f38a12649dd2fd5b8d237cb88e21aeeeab87/src/main/java/org/spongepowered/mod/mixin/core/entity/player/MixinEntityPlayerMP.java#L53 channel() has private access in NetworkManager

- https://github.com/SpongePowered/Sponge/blob/f718f38a12649dd2fd5b8d237cb88e21aeeeab87/src/main/java/org/spongepowered/mod/mixin/core/world/MixinChunk.java#L73 worldIn.captureBlockSnapshots: cannot resolve symbol

I have no idea what I could have done wrong... As these methods aren't in the official repo here everyone should get these errors. Should one use older versions of this repo to clone and start a server? Thanks in advance!

**Comment by twizmwazin** [comment]
Did you follow the instructions in the readme or did you just clone and use `gradle build`?

**Comment by gabizou** [comment]
These errors sound like you're using the SpongeCommon minecraft dependency instead of the forge one. If your IDE is still using the gradle wrapper included in the repo, please change that to use your own installed version of gradle, preferably 2.7.

**Comment by randombyte-developer** [comment]
Thanks for helping! But I really don't know what to do :-\

For simplicity: This will be fixed later, I think, right? So before I do this and that I could simply use a compiled version of Sponge(Vanilla).

**Comment by JBYoshi** [comment]
You also need to run `gradle eclipse` or `gradle idea`, depending on which IDE you're using, so the IDE sees the classpath change.

**Comment by gabizou** [comment]
Also, due to the upgrade to fg2, run `gradle :genIntellijRuns` will still produce invalid run configurations. Following the ReadMe specifying the VM arguments: `-Dfml.coreMods.load=org.spongepowered.mod.SpongeCoremod` is still valid.

**Comment by randombyte-developer** [comment]
So, what I did:

- Created a new project
- Closed IntelliJ
- Cloned Sponge into project, so Sponge is a module in my project
- `gradlew.bat setupDecompWorkspace --refresh-dependencies` and `gradlew.bat idea`
- Opened IntelliJ
- Attached Gradle project: Sponge
- Refreshed Gradle project
- Added run configuration(with VM options and so on)
- Ran that run configuration
-> Same errors

As I can't find any instructions that tell me to do different things, I think I do it right.

**Comment by Faithcaio** [comment]
I had the exact same problem.
By moving the Sponge Module Dependency "SpongeCommon" below "Gradle: net.minecraftforge:forgeSrc:1.8-11.14.3.1515-PROJECT(Sponge)" 
![](http://puu.sh/ksNNk/d8a336ef31.png)
these errors dissappear.

But now i get: http://pastie.org/pastes/10450907/text?key=jcijvhpgqj4ywrdvahlta

**Comment by randombyte-developer** [comment]
@Faithcaio Thanks! That fixes the problem for me, too. Note: You have to move the dependency with that up arrow on the right side of the window. Moving by mouse doesn't work(the Apply button doesn't appear).

But now I get other errors: http://pastebin.com/QCbQShWP

Again: @gabizou If this is only a temporary "bug" then let me know because I know you have better things to do than helping me fixing this errors. I could just use a compiled version of Sponge(Vanilla) until the problem is fixed.

**Comment by Faithcaio** [comment]
With some Help from @Zidane we got it working again:
Move both 
Gradle: ##########__gradle_caches_minecraft_net_minecraftforge_forge_1_8_11_14_3_1515_start
and
Gradle: net.minecraftforge:forgeSrc:1.8-11.14.3.1515-PROJECT(Sponge)
above 
SpongeCommon
and remove the Export checkmark on SpongeCommon
![](http://puu.sh/kuKdx/d49b85b2d3.png)

Hope it works for you too

**Comment by JBYoshi** [comment]
Could someone update the build script to do this automatically?

**Comment by Zidane** [comment]
@JBYoshi 

It'll be fixed when things are bumped to Gradle 2.8 which will happen a few days from now.

**Comment by randombyte-developer** [comment]
@Faithcaio Thanks! It works! :smiley:

This issue can be closed with the fixing commit.
