### ISSUE TITLE
DestructEntityEvent.Death doesn't get canceled correctly.

### ISSUE THREAD

**Issue by thomas15v** [SpongePowered/SpongeForge#364]
When cancelling this event the death screen still appears. Also the Entity gets removed even if cancelled.

(notice: this might be a forge issue)

**Comment by simon816** [comment]
That event shouldn't be cancellable, since the entity has 0 health.
Before the event refactor it wasn't cancellable https://github.com/SpongePowered/SpongeAPI/blob/78ef7829f9bcfdd46d3bb2a7b75c7d71e0a5ae76/src/main/java/org/spongepowered/api/event/entity/EntityDeathEvent.java#L36

**Comment by jk-5** [comment]
DestructEntityEvent.Death is cancellable because MessageSinkEvent which it extends is cancellable. Canceling the event cancels the death message to be shown in chat.

While a generic Cancellable interface is nice, this is a perfect example that it can be confusing some times

**Comment by simon816** [comment]
Yeah, `MessageSinkEvent` shouldn't be cancellable IMO. To 'cancel' the message the `MessageSink` could be set to `MessageSinks.toNone()`

**Comment by thomas15v** [comment]
So how do we prevent players from having the death screen than?

**Comment by ST-DDT** [comment]
Cancel the damage that would have killed the player. This happened internally as well in the old/other APIs. But wasnt a clean solution.

**Comment by simon816** [comment]
This commit fixes `MessageEvent` being cancellable https://github.com/SpongePowered/SpongeAPI/commit/a33c3993c0a96c5d7b12bc685d512890b6963025
@thomas15v Are you looking to not show the death screen and have an insta-respawn behavior or are you just wanting to stop the player dying?

**Comment by thomas15v** [comment]
I am looking for an insta-respawn behaviour.

**Comment by Zidane** [comment]
@thomas15v Cancel DamageEntityEvent.
