### ISSUE TITLE
[SOLVED] Server won't start on v 1521/711

### ISSUE THREAD

**Issue by Billabonga** [SpongePowered/SpongeForge#372]
The server wouldn't start even after I had removed all plugins/mods

http://pastebin.com/embed_js.php?i=Ns1BR5FN"></script>

**Comment by ZephireNZ** [comment]
This was fixed just recently - try updating to the most recent version of Sponge

**Comment by Billabonga** [comment]
Unfortunately, the latest version cannot be downloaded at the moment

https://forums.spongepowered.org/t/latest-sponge-download-links/9588
