### ISSUE TITLE
Command dispatcher

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/SpongeForge#380]
Is this good code for sponge?(EssentialsSponge plugin)
How can it be rewritten?(without switches)

![Uploading z9SarV4U56Q[1].jpg…]()

**Comment by XakepSDK** [comment]
Awww, i can't attach image
https://pp.vk.me/c621717/v621717432/51aa2/z9SarV4U56Q.jpg

**Comment by JBYoshi** [comment]
It's best to copy and paste your code instead of pasting a screenshot of it.

**Comment by ST-DDT** [comment]
I would use the following syntax:
````java
for (FileCommand cmd : FileCommand.values()) {
    if (cmd.condition()) { // Maybe move this inside register (checkAndRegister)
        cmd.register(cmdDispatcher or game);
    }
}
````

````java
public enum FileCommand  {

TEST() {
	@Override
	void register(...) {
		// ...
	}
};

abstract void register(...);

}
````

If you don't want to do that. Consider at least storing the commandDispatcher in a local var.

**Comment by XakepSDK** [comment]
Ok, i try to make helper class.
