### ISSUE TITLE
Execute command not detecting player with a score

### ISSUE THREAD

**Issue by chrismack** [SpongePowered/SpongeForge#382]
for example running the command "/execute @a ~ ~ ~ say hi" work fine however when you add arguments to the command it doesn't work i.e "/execute @a[score_R_min=1]  ~ ~ ~ say hi"

The score_R_min is a reference to the score board objective called R, and it looks for a minimum value of 1

@JBYoshi (tagged you because you helped last time :) )

**Comment by Aaron1011** [comment]
I'm unable to reproduce this.

Does the objective exist on the world's scoreboard, and not a player-specific one? The vanilla selectors will only look at the world scoreboard.

**Comment by ryantheleach** [comment]
Which world? It might be a cross world issue.

**Comment by chrismack** [comment]
it's all in the main world, it also works in vanilla minecraft :/ after testing it a fair bit the issue seems to be fairly inconsistent which is annoying

![2015-10-24_16 03 25](https://cloud.githubusercontent.com/assets/1420361/10711098/4413b30c-7a69-11e5-8d98-4ff54e14d43d.png)

i'll keep looking into it to see if i can find out what causes it to fail

**Comment by Aaron1011** [comment]
I've now reproduced this issue, and will be pushing a fix soon.

**Comment by JBYoshi** [comment]
@Aaron1011 Status?

**Comment by Aaron1011** [comment]
@JBYoshi: This will be addressed as part of my broader ccaners to scoreboards to properly support multiple worlds.

**Comment by chrismack** [comment]
@Aaron1011 any newson this?

**Comment by chrismack** [comment]
News*

**Comment by Aaron1011** [comment]
@chrismack: This will be in by beta.

**Comment by chrismack** [comment]
Awesome thank you

**Comment by Aaron1011** [comment]
@chrismack: Glad to see my changes fixed this :). Let me know if you have any other issues pertaining to scoreboards.

**Comment by chrismack** [comment]
Thanks @Aaron1011 :) i'll keep an eye out
