### ISSUE TITLE
betterchest & Aroma1997

### ISSUE THREAD

**Issue by gothdawid** [SpongePowered/SpongeForge#384]
I say right away that I was using google translator.
After uploading the spongeforge 749 and 750 deletes the improvement of boxes and empties them.
The latest versions.
Aroma1997Core-1.8-1.0.3.4
BetterChests-1.8-1.2.0.0
spongeforge-1.8-1521-2.1-DEV-750
forge-1.8-11.14.3.1521-universal

**Comment by ST-DDT** [comment]
Could you add the original/untranslated issue/error description?

**Comment by gothdawid** [comment]
Po dograniu modyfikacji "spongeforge" zostają skasowane ulepszenia i cała zawartość z skrzynek z modyfikacji "betterchest".

**Comment by bloodmc** [comment]
@gothdawid I do not understand the issue. Try to get your issue translated properly.

**Comment by Barteks2x** [comment]
It says something like:
After adding "spongeforge" upgrades and content of chests from "betterchest" mod are removed.

**Comment by gothdawid** [comment]
In brief:
After uploading "sponge forge" boxes are emptied. (those with betterchest)

**Comment by bloodmc** [comment]
@gothdawid Please test build 767 and let me know if problem is fixed.

**Comment by bloodmc** [comment]
@gothdawid reopen if issue happens again.
