### ISSUE TITLE
Player.spawnParticles() with no integer parameter results in no particles equalto or greater than 1.0 distance away

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/SpongeForge#386]
spongeforge-1.8-1521-2.1-DEV-750 with forge 1521, shadedAPI version 92; has been present in earlier combos.

Particles with or without the 'within-distance' parameter, when spawned via the Extent.spawnParticles() both work as expected, limiting the viewability of the particle to a limited distance if provided.

Particles with the Player.spawnParticles() work as expected when spawned with the within-distance parameter, but when spawned without the limiting parameter, are only visible when viewed under 1 block.  There may be an incorrect value set for the max-distance constant assumed in that scenario, or 
Noted in forum: https://forums.spongepowered.org/t/problem-with-particless-distance/9706/6

Enhanced test resulted in demonstration code below which produces the following: (Image shows particles rendered at distances up to but less than 1 unit away from player location with accuracy)
http://s.mpserv.net/9c39ed55ca835382f5dc02b52da594bc.png
The following code snip can demonstrates

`
			ParticleEffect myPE1 = game.getRegistry().createParticleEffectBuilder(ParticleTypes.REDSTONE).build();
			ParticleEffect myPE2 = game.getRegistry().createParticleEffectBuilder(ParticleTypes.FLAME).build();
			Vector3d origin = p.getLocation().getPosition();
			for (double incr = 0; incr < 30; incr = incr + 0.1) {
				p.spawnParticles(myPE1, origin.add(incr, 0, 0)); 
			}
			p.spawnParticles(myPE2, origin.add(0.5, 0, 0));
			p.spawnParticles(myPE2, origin.add(1.0, 0, 0));
			p.spawnParticles(myPE2, origin.add(0.5, 0, 0));
			p.spawnParticles(myPE2, origin.add(0.7, 0, 0.7));
			p.spawnParticles(myPE2, origin.add(0.8, 0, 0.8));
			p.spawnParticles(myPE2, origin.add(1.0, 0, 1.0));

`

**Comment by simon816** [comment]
Ah I found the root cause. `Player.spawnParticles` without a radius will use `Integer.MAX_VALUE` for the radius ([see here](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/mixin/core/entity/player/MixinEntityPlayerMP.java#L194))
but a little further on it [squares that value](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/mixin/core/entity/player/MixinEntityPlayerMP.java#L210) and I just found out that `Integer.MAX_VALUE *  Integer.MAX_VALUE` is 1

**Comment by JBYoshi** [comment]
@simon816 Although just changing the default value would fix that, it would be a good idea to limit the maximum radius in case a plugin specifically passes sets the radius to `Integer.MAX_VALUE`. I think it would be OK for any radius greater than 10,000 to be interpreted as "no boundaries" (I don't think it would be a good idea for clients to be able to see 10,000 blocks away :smiley:).

**Comment by Kiskae** [comment]
@JBYoshi If the server view distance is available, then it would be possible to derive an absolute maximum distance from that

**Comment by theboomer** [comment]
Even at max server view, thats the upper hard limit for distance, regardless of actual server setting distance, and better than no boundaries

**Comment by simon816** [comment]
I'm just going to do the simplest solution and cast the radius to a long. That should fix the problem
