### ISSUE TITLE
Sever won't start using v. 1524/762

### ISSUE THREAD

**Issue by Billabonga** [SpongePowered/SpongeForge#387]
http://pastebin.com/9HhPqAvz

No mods installed except for world edit

**Comment by kenzierocks** [comment]
I think a full client log might help.

**Comment by Billabonga** [comment]
Client log: 
http://pastebin.com/jvJJhq4A

**Comment by liach** [comment]
Likely to be a mixin failure.

**Comment by simon816** [comment]
Does this still happen without worldedit?

@liach I didn't see any mixin errors in the provided log.

**Comment by liach** [comment]
I should say that it is a bad mixin. Ref [the original mixin] (https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/mixin/core/block/MixinBlockState.java). The last 3 methods called another method that does not exist or is not shaded. I wonder why didn't it cause a compile error, but that must be a cause.

**Comment by bloodmc** [comment]
This bug was caused by ForgeGradle and was fixed in commit https://github.com/MinecraftForge/ForgeGradle/commit/6af0237b1656014e78792ac601cbeb11932f561b
