### ISSUE TITLE
Inventory not cleared when player die.

### ISSUE THREAD

**Issue by hunter688** [SpongePowered/SpongeForge#392]
Howto reproduce:

- teleport to unloaded part of map (not needed)
- give some items
- die
- when yours home far (chunks not loaded imho) yours inventory is not cleared

forge 1530, sponge 767

when take items from ground, have red number 0 at every duped
![deathdupe](https://cloud.githubusercontent.com/assets/1410134/10827899/a2a5d7a4-7e71-11e5-9fcc-c7c25f3a8094.png)
 item

**Comment by bloodmc** [comment]
@hunter688 If you were using a plugin to kill self, try again with latest build. I've only seen this bug happen if someone attempts to kill player by setting health to 0 and bypassing onDeath logic.

**Comment by hunter688** [comment]
No these kills are using spawned creeper, no via commands.

**Comment by hunter688** [comment]
Tested with sponge 774 and no others mods/plugins. Problem still persist.
When delete sponge from mods and test simple forge server, all works as expected. Every death player drop inventory.

**Comment by Zidane** [comment]
@bloodmc 

If you set your spawn via a bed and you kill yourself via command, you will not only have issues in respawning but you'll keep ghost items.

This bug is CONFIRMED.

**Comment by bloodmc** [comment]
@Zidane I cannot reproduce this bug. Are you sure you tested with latest Sponge and no plugins?

**Comment by simon816** [comment]
I was able to retain items after `/kill` in creative mode. The items dropped as expected in survival.

**Comment by Zidane** [comment]
I can confirm what @simon816 says.

**Comment by bloodmc** [comment]
@hunter688 Test build 781

**Comment by simon816** [comment]
@bloodmc Tested latest master and it appears to be fixed

**Comment by hunter688** [comment]
Cannot test it because all builds > 777 crashed me.

**Comment by simon816** [comment]
782 should be good
