### ISSUE TITLE
Some error in building

### ISSUE THREAD

**Issue by lk1228797452** [SpongePowered/SpongeForge#396]
Found AccessTransformer in main resources: common_at.cfg
#################################################
         ForgeGradle 2.0-SNAPSHOT-14461db
  https://github.com/MinecraftForge/ForgeGradle
#################################################
               Powered by MCP 9.10
             http://modcoderpack.com
         by: Searge, ProfMobius, Fesh0r,
         R4wk, ZeuX, IngisKahn, bspkrs
#################################################
Found AccessTransformer in dependency resources: common_at.cfg
:licenseFormatApi UP-TO-DATE
:licenseFormatMain UP-TO-DATE
:licenseFormatTest UP-TO-DATE
:licenseFormat UP-TO-DATE
:SpongeCommon:licenseFormatApi UP-TO-DATE
:SpongeCommon:licenseFormatMain UP-TO-DATE
:SpongeCommon:licenseFormatTest UP-TO-DATE
:SpongeCommon:licenseFormat UP-TO-DATE
:SpongeCommon:SpongeAPI:licenseFormatMain UP-TO-DATE
:SpongeCommon:SpongeAPI:licenseFormatTest UP-TO-DATE
:SpongeCommon:SpongeAPI:licenseFormat UP-TO-DATE
:deobfCompileDummyTask
:getVersionJson
Connection reset
:extractUserdev UP-TO-DATE
:downloadClient FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':downloadClient'.
> java.net.SocketException: Connection reset

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 26.568 secs

I live in China,
When I build SpongeForge,I always meet this problem,What can I do?

**Comment by simon816** [comment]
If it's always failing at downloadClient then maybe try accessing http://s3.amazonaws.com/Minecraft.Download/versions/1.8/1.8.jar from a browser. Does that work?

**Comment by liach** [comment]
Or you can use a VPN to connect if your country blocked the website.
