### ISSUE TITLE
Game freezes/doesn't load on start 1543/788

### ISSUE THREAD

**Issue by Billabonga** [SpongePowered/SpongeForge#400]
http://pastebin.com/9sZjBcq7

http://pastebin.com/hp8KHSkK

**Comment by Inscrutable** [comment]
I get this too. SpongeForge 776 works fine, but 788 throws up
``Could not construct the ImmutableDataManipulator: org.spongepowered.common.data.manipulator.immutable.block.ImmutableSpongeLayeredData``
which seems to relate to the formation of snow layers. It happens to all players regardless of whether they're in a snowy biome or not.

**Comment by Billabonga** [comment]
My game freezes on start and my computer too

**Comment by gabizou** [comment]
It's actually a SpongeCommon issue, but I'll get right on this.

**Comment by Billabonga** [comment]
Thanks a lot @gabizou
