### ISSUE TITLE
setupDecompWorkspace problem

### ISSUE THREAD

**Issue by LOLDERP** [SpongePowered/SpongeForge#401]
went ever i run setupDecompWorkspace it gives me a build fail

4:08:24 PM: Executing external task 'setupDecompWorkspace'...
Found AccessTransformer: common_at.cfg
Found AccessTransformer: common_at.cfg
:extractMcpData SKIPPED
:extractMcpMappings SKIPPED
:getVersionJson
:extractUserdev UP-TO-DATE
:genSrgs SKIPPED
:copySrgs UP-TO-DATE
:deobfCompileDummyTask
:deobfProvidedDummyTask
:extractDependencyATs SKIPPED
:downloadClient SKIPPED
:downloadServer SKIPPED
:splitServerJar SKIPPED
:mergeJars SKIPPED
:deobfMcSRG SKIPPED
:getFernFlower SKIPPED
:decompileMc SKIPPED
:fixMcSources SKIPPED
:applySourcePatches SKIPPED
:remapMcSources SKIPPED
:recompileMc
[ant:javac] warning: [options] bootstrap class path not set in conjunction with -source 1.6
[ant:javac] /Users/Derp/SpongeForge/build/tmp/recompileMc/sources/net/minecraftforge/client/model/obj/OBJModel.java:597: error: cannot find symbol
[ant:javac]                     material.getColor().setW(alpha);
[ant:javac]                                        ^
[ant:javac]   symbol:   method setW(float)
[ant:javac]   location: class Vector4f
[ant:javac] Note: Some input files use or override a deprecated API.
[ant:javac] Note: Recompile with -Xlint:deprecation for details.
[ant:javac] Note: Some input files use unchecked or unsafe operations.
[ant:javac] Note: Recompile with -Xlint:unchecked for details.
[ant:javac] 1 error
[ant:javac] 1 warning
:recompileMc FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':recompileMc'.
> Compile failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 23.576 secs
Compile failed; see the compiler error output for details.
4:08:47 PM: External task execution finished 'setupDecompWorkspace'.

**Comment by gabizou** [comment]
Try cleaning your workspace and cache.

**Comment by LOLDERP** [comment]
ok

**Comment by LOLDERP** [comment]
i did clean my cache and workspace and it still gives me build fail

**Comment by bloodmc** [comment]
This is not a SpongeForge issue. Post your issue on forums.
