### ISSUE TITLE
Improve player left and right click detection

### ISSUE THREAD

**Issue by DDoS** [SpongePowered/SpongeForge#402]
This is just an issue to remind me to investigate the following: https://github.com/SpongePowered/SpongeForge/commit/dc36dd6d80d86967dba23f6d90248c5824b859b2

And also in general improve the handling of this type of interaction.

**Comment by bloodmc** [comment]
@DDoS This is no longer needed as I removed the ray trace code in favor of Grum's original hack that was in 1.7. I just redid his code so it would work correctly in 1.8.

Latest code can be seen here

https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/mixin/core/network/MixinNetHandlerPlayServer.java#L417
