### ISSUE TITLE
Add a better notice if the server is not running java 8

### ISSUE THREAD

**Issue by Deamon5550** [SpongePowered/SpongeForge#408]
We should look at adding something which is compiled with java 6 and runs early to validate that the user is running java 8 and if not returns a nicer error into the console about their out of date version and the need for java 8. Anyone not familiar with java who sees a `UnsupportedClassVersionError` is likely to only see the word *Error* and report it to us assuming that it is an issue on our end rather than their end.

This could take the form of a Java 8 checking tweaker which is placed before the MixinTweaker.

**Comment by gabizou** [comment]
This is actually something @Mumfrey is adding to Mixin.

**Comment by Minecrell** [comment]
Pretty sure this should be fixed by https://github.com/SpongePowered/SpongeForge/commit/96cea16e25fe70e06aa27b9c8e14128b00c24382
