### ISSUE TITLE
Comparator crash

### ISSUE THREAD

**Issue by chrismack** [SpongePowered/SpongeForge#410]
When putting a comparator next to a hopper clock the server crashes.

![2015-11-13_23 34 50](https://cloud.githubusercontent.com/assets/1420361/11160299/d99133cc-8a5f-11e5-9ae0-5a50467f2f8e.png)

Putting a comparator with output facing towards the closest command block the server crashes.(doesn't restart either have to remove sponge and remove the block) 

Here is the crash report http://pastebin.com/ZTWbpb7G

**Comment by gabizou** [comment]
Can you re-test on the latest SpongeForge?

**Comment by chrismack** [comment]
That seems to have fixed it :) sorry didn't realise i was a version behind on forge Thanks
