### ISSUE TITLE
DamageEntityEffect

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/SpongeForge#411]
I can't get this effect to trigger for anything, is this a known not-implimented yet issue ?
Spongeforge-808 and associated currentness-correspondance of  forge, api

@Listener
public void ondamage(DamageEntityEvent event) {
	System.out.println(event.toString());
}

**Comment by gabizou** [comment]
The event isn't implemented as [event issue tracker](https://github.com/SpongePowered/SpongeCommon/issues/41) shows.
