### ISSUE TITLE
Fishing completely broken with Sponge installed

### ISSUE THREAD

**Issue by Grinch** [SpongePowered/SpongeForge#416]
Latest SpongeForge attempting to fish (just reeling in the rod causes this, doesn't have to come from water).

https://pste.me/#/P7Huk

**Comment by Zidane** [comment]
Confirmed.

@Aaron1011 this not only breaks fishing but it also has a chance of crashing the client. This needs to be fixed ASAP.

**Comment by simon816** [comment]
Testing Sponge Client in Eclipse it seems when fishing, an unknown item is returned called `item.none.name` and it's a purple/black texture.

**Comment by JBYoshi** [comment]
...And that would be Sponge's “null item” (ItemTypes.NONE).

**Comment by simon816** [comment]
Ah, doesn't help that `ItemTypes.NONE` is null at runtime. Probably something to to with the recent registry changes.
