### ISSUE TITLE
getTranslation for Klingon or Pirate

### ISSUE THREAD

**Issue by Grinch** [SpongePowered/SpongeForge#419]
We use Java locale's with getTranslation but I don't see anything for Klingon or Pirate. Was this an oversight or am I missing how to do it?

**Comment by Zidane** [comment]
If Vanilla has support for these then SpongeAPI needs it as well. We can use Java's Locale class but also create our own.

Plugin devs just need to realize that to use the special Vanilla one, there is a Sponge static class of those.

**Comment by kashike** [comment]
I was talking to @Minecrell about that the other day: https://korobi.io/network/esper/channel/lapis/logs/2015/11/13/#L333-406

**Comment by Minecrell** [comment]
Can you open an issue on SpongeAPI for this? This was available as [`Locales` class](https://github.com/SpongePowered/SpongeAPI/blob/4359272d4a1c3099206ea7a9d6be7bb2521134dc/src/main/java/org/spongepowered/api/text/translation/locale/Locales.java) in the initial Text API version, however @zml2008 removed it in https://github.com/SpongePowered/SpongeAPI/pull/563#issuecomment-91936171 (see the discussion there). My opinion on this hasn't changed, I think it was quite useful.

For the Minecraft translations (not plugin translations) it is important to know that the server **has only the English translation bundled**. All languages are only available on the client.

**Comment by Grinch** [comment]
Created a new issue on SpongeAPI for this. https://github.com/SpongePowered/SpongeAPI/issues/929
