### ISSUE TITLE
game crash when i use a bow 

### ISSUE THREAD

**Issue by LOLDERP** [SpongePowered/SpongeForge#420]
crash is here http://pastebin.com/4P0rdmTK

**Comment by LOLDERP** [comment]
btw its the half of the log  i dont want to show my username tell me if you want the hole thing

**Comment by Tzky** [comment]
I suggest using pastebin (and linking the paste) instead of posting everything directly.

**Comment by gabizou** [comment]
This has been solved in the latest build.
