### ISSUE TITLE
ClickInventoryEvent fired when press E after join to server

### ISSUE THREAD

**Issue by hunter688** [SpongePowered/SpongeForge#426]
Code of listener and console output:

http://pastebin.com/UtrZSQaa

For every item in the inventory fired event. Im joining to server in the creative mode.
Reproduce:

join to server
press E
events fired for every item in the player's inventory

when press E again, event not fired, only first time after joining to server

**Comment by simon816** [comment]
I could not reproduce this. Does it still happen on the [latest SpongeForge build](http://files.minecraftforge.net/spongepowered)?
What about without any mods?

**Comment by hunter688** [comment]
Better steps to reproduce:

join server, take something to inventory
disconnect
connect
do /gamemode 1
press E to open inventory

No others mods, only latest sponge and this plugin: http://www.mirc.cz/BlockTrackR-2.4.1.jar

**Comment by bloodmc** [comment]
@hunter688 Creative is handled in a seperate event since mojang sends a different packet to server.
Use the following when in creative mode https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/event/item/inventory/CreativeInventoryEvent.java

**Comment by bloodmc** [comment]
@hunter688 reopen if this is still an issue.

**Comment by hunter688** [comment]
I thinks it is issue, because when switch to /gamemode 1, Im not clicked to any item in the survival inventory. I think event should be called only when click to some item in the inventory.

Cannot reopen, I dont see reopen button.

**Comment by hunter688** [comment]
video of issue: http://www.twitch.tv/hunterzcz/b/683783008
client/server console
