### ISSUE TITLE
Get Custom Biomes from Mods

### ISSUE THREAD

**Issue by NitroxydeX** [SpongePowered/SpongeForge#429]
Hey guys,

is there at the moment the option to get custom biomes out of an other mod e.g. biomes o plenty to use it in the world generator?

**Comment by Deamon5550** [comment]
Yes, [GameRegistry#getType(Class,String)](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/GameRegistry.java#L90) can be used to get a BiomeType instance for any biome, including mod added biomes. The ids are formatted as modid:name.

This biome type can be used like any other when it comes to world generation.

**Comment by FabiUnne** [comment]
Is there any list of available biomes?

**Comment by Deamon5550** [comment]
Yes `gameRegistry.getAllOf(BiomeType.class)` will return all known biome types.

**Comment by FabiUnne** [comment]
Okay, in this example, I want to load a BiomesOPlenty biomeType. But e.g. the id 'BiomesOPlenty:Bayou' throws a java.util.NoSuchElementException. (i tried to get the BiomeType). 
If I print out all biomes, also BiomsOPlenty biomes are displayed. But if I invoke the #getId() method of one displayed Biome, an java.lang.AbstractMethodError is thrown.
How can I get the correct Ids?

**Comment by Deamon5550** [comment]
Ah looks like `getId` was not implemented on biomes, I'll add it to the world generation api implementation branch which should be merged soon. See: [SpongeCommon#253](https://github.com/SpongePowered/SpongeCommon/pull/253)
