### ISSUE TITLE
Server.shutdown wont stop mc process correctly.

### ISSUE THREAD

**Issue by NeumimTo** [SpongePowered/SpongeForge#432]
Calling method Server.shutdown on a clientside freezes the minecraft process instead of killing it.

**Comment by simon816** [comment]
For me, calling shutdown (within a world) left me floating in the void. I would say shutdown should exit back to main menu (as opposed to shutting down the game) since there is no active server in the menu screens.

**Comment by JBYoshi** [comment]
@simon816 I believe the easiest way to shut down a client server is by kicking the host player (if I remember correctly, that's how you get kicked out when you die in hardcore).

**Comment by simon816** [comment]
No matter what I try I can't seem to reliably make shutdown() save/quit the world and return to main menu.
It sometimes works fine and sometimes doesn't. Anyone able to find a reliable solution?

**Comment by ryantheleach** [comment]
Trace what the client does when you die in a hardcore world. It doesn't delete the world, and kicks you to main menu on 1.8.8

**Comment by ryantheleach** [comment]
It might be a vanilla bug actually. on 1.8 instead of deleting the world, it freezes the client.
