### ISSUE TITLE
Double conclusion logger.

### ISSUE THREAD

**Issue by Azatik** [SpongePowered/SpongeForge#433]
Double conclusion logger.
SpongeForge 849 And SpongeVanilla 76.
Code:
```
    @Listener
    public void onServerStarting(GameStartingServerEvent event) {
        logger.info(instance.getVersion() + " plugin loaded!");
    }

    @Listener
    public void onServerStopping(GameStoppingServerEvent event) {
        logger.info(instance.getVersion() + " plugin unloaded!");
    }
```

Result:
![image](https://cloud.githubusercontent.com/assets/10154956/11457397/6b1eb006-96c9-11e5-90ea-8f58622625ba.png)

![image](https://cloud.githubusercontent.com/assets/10154956/11457406/a3f30378-96c9-11e5-82fa-13bf66bbe16f.png)

P.S: GameStoppingServerEvent in SpongeVanilla - not work.

**Comment by simon816** [comment]
Just tested with the following code
```java
    @Listener
    public void onServerStart(GameStartingServerEvent e) {
        System.out.println(e);
    }

    @Listener
    public void onServerStop(GameStoppingServerEvent e) {
        System.out.println(e);
    }
```
Event was fired once.
```
[23:37:54] [Server thread/INFO] [STDOUT]: [com.simon816.eventtest.SpongePlugin:onServerStart:50]: net.minecraftforge.fml.common.event.FMLServerStartingEvent@774740b6
[...]
[23:44:25] [Server thread/INFO] [STDOUT]: [com.simon816.eventtest.SpongePlugin:onServerStop:55]: net.minecraftforge.fml.common.event.FMLServerStoppingEvent@6f09a3f4
``

Are you sure you're not registering the event listener class twice? (Remember if this is your main class then it's already registered)

**Comment by Azatik** [comment]
I am sure.
My main class:
https://github.com/Azatik/Grave/blob/master/src/main/java/io/github/azatik/grave/Grave.java

**Comment by Deamon5550** [comment]
[here](https://github.com/Azatik/Grave/blob/master/src/main/java/io/github/azatik/grave/Grave.java#L43) you're registering the listeners in your plugin main class twice, all listeners in your plugin class are automatically registered.

**Comment by Azatik** [comment]
Delete this line?

**Comment by Deamon5550** [comment]
Yes

**Comment by Zidane** [comment]
@Deamon5550 

Re-opening this since the EventManager really should just not double register. Can you make that change @Aaron1011 ?

**Comment by Zidane** [comment]
Actually, I've changed my mind and this should be in-valid.
