### ISSUE TITLE
Fails to Build/runServer

### ISSUE THREAD

**Issue by MikaalSky** [SpongePowered/SpongeForge#434]
https://gist.github.com/MikaalSky/b5d87dbd1967b806e90f

I've ran decomp and refreshed dependencies.

**Comment by kenzierocks** [comment]
I think runServer doesn't work in Sponge.

**Comment by MikaalSky** [comment]
runServer does in fact work. It's just that in Project Structure I had it set to 6 for some reason.
![Image of Project Structure](http://take.ms/5jqV2)
Now everything is working all fine and dandy.
