### ISSUE TITLE
Breaking certain Entities causes a message

### ISSUE THREAD

**Issue by MikaalSky** [SpongePowered/SpongeForge#435]
So, uh, this is a thing.

![Living Paintings](http://take.ms/pW4ZI)

How to reproduce Living Paintings:
 - Place Painting on Sponge Server
 - Remove Painting

Current Entities Affected (From what I can tell)
 - Paintings
 - Boats 
 - Item Frames
 - Minecarts

**Comment by MikaalSky** [comment]
Appears to be only affecting things that directly extend Entity.

**Comment by Aaron1011** [comment]
Confirmed - I'll look into this.

**Comment by Aaron1011** [comment]
@bloodmc: This is caused [here](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/mixin/core/world/MixinWorld.java#L938-L941), in `handlePostTickCaptures`. You pass in `Texts.of()` as the original and default messages, but always send the message to the player. This results in a blank line being sent when certain entities are destroyed. I'm not quite sure how you want to handle this, given that some entities might have an actual death message to display.

**Comment by MikaalSky** [comment]
Well, just making sure there is a death before attempting to post one would make sense.
