### ISSUE TITLE
Exceptions during startup

### ISSUE THREAD

**Issue by NeumimTo** [SpongePowered/SpongeForge#436]
No other monds are present.

http://pastebin.com/fWZAnDAn

forge version: 11.14.4.1557
sponge: spongeforge-1.8-1577-2.1-DEV-874

**Comment by Minecrell** [comment]
This was fixed in the latest SpongeForge version. However, we're having a few issues with the Sponge initialization we still need a fix. I'd recommend to use 1.8-1577-2.1-DEV-867 for now.

**Comment by NeumimTo** [comment]
Which api version matches 867 release?

**Comment by Minecrell** [comment]
`2.1-20151202.062427-166`
