### ISSUE TITLE
Sponge crashes during startup

### ISSUE THREAD

**Issue by NeumimTo** [SpongePowered/SpongeForge#437]
This exception follows right after https://github.com/SpongePowered/SpongeForge/issues/436  and results in a crash. 

http://pastebin.com/crn7BP3i

forge version: 11.14.4.1557
sponge: spongeforge-1.8-1577-2.1-DEV-874

**Comment by Minecrell** [comment]
Thanks, we're aware of the problem and will fix it as soon as possible. Please just comment on the other issue in the future instead of opening several ones.
