### ISSUE TITLE
Loading foreign worlds

### ISSUE THREAD

**Issue by trentech** [SpongePowered/SpongeForge#441]
It seems sponge requires the level_sponge.dat to correctly identify and load worlds. That being said, Dropping for example a bukkit world into the correct location and using the loadWorld(..) method will generate the sponge data files and load the world, however it appears to cause an dimension id conflict, generating an id of 0, thereby unloading the default world causing issues. Now I'm not %100 sure if this is a bug, or if other steps are needed before attempting to load the world.

**Comment by Inscrutable** [comment]
There is also a related issue for SpongeDocs about [migrating bukkit worlds](https://github.com/SpongePowered/SpongeDocs/issues/347). If this gets resolved then we can probably close that issue too.

**Comment by Zidane** [comment]
I've pushed the WorldMigrator to a branch @trentech and its almost ready to go.

https://github.com/SpongePowered/SpongeCommon/commit/d1122b2add09346385b9d2feefa766850caee70d

**Comment by trentech** [comment]
What's the status of this? As of late I can't load foreign worlds at all. I think it's due to the world.conf files not existing.

http://pastebin.com/G0Sv3qy7

**Comment by simon816** [comment]
@trentech this should fix your most recent issue https://github.com/SpongePowered/SpongeCommon/commit/e9e63a70fdd46aafaa10f8ba0753891388e3c2a5

As for the main issue @Zidane have you got a solution for this?

**Comment by Zidane** [comment]
@simon816 

I'll do some testing as I have changes locally.

**Comment by Aaron1011** [comment]
Closing this, as @Zidane's world migrator now fully supports migrating from bukkit/spigot world format.
