### ISSUE TITLE
Cancellation of BlockChangeEvent when placing blocks into liquids results in item loss [Confirmed by Zidane]

### ISSUE THREAD

**Issue by clucky** [SpongePowered/SpongeForge#445]
When a player attempts to place a block into water or lava, and the `BlockChangeEvent` is cancelled for them, their item is lost. I have attempted to restart the client to rule-out ghosting, and it did not resolve the issue. Note, this only appears to affect placing in water and lava; it does not occur when placing a block on the ground (in air).

**Comment by clucky** [comment]
I would also like to add, that when you place a block in water, it does not trigger `BlockChangeEvent.Place`. Not sure if this is considered a bug, or related to this issue.

**Comment by clucky** [comment]
`BlockChangeEvent.Fluid` was removed entirely as of 12/15 by blood

**Comment by bloodmc** [comment]
@clucky This issue should not happen in latest build with Fluid event removed.

**Comment by clucky** [comment]
@bloodmc Issue is confirmed to be resolved in build 915. Thank you.
