### ISSUE TITLE
Changing Blocks in Creative Mode Not Triggering ChangeBlockEvent

### ISSUE THREAD

**Issue by clucky** [SpongePowered/SpongeForge#447]
When blocks are broken or placed in creative mode, it would be expected for this line of code to be triggered, however, it is not. No exceptions appear to be thrown in the console.

````
public void onBlockChange(BlockChangeEvent event, @Root Player player) { event.setCancelled(); }
````

This was tested using SpongeForge version DEV-915.

**Comment by JBYoshi** [comment]
Is there any output when you add this listener to your code? If so, could you post it? (Add this as a separate method; make sure the `BlockChangeEvent` is the only argument.)

```java
public void testBlockChangeEvent(BlockChangeEvent event) {
    System.out.println(event);
}
```

**Comment by Deamon5550** [comment]
Not sure if you just left it out of your code example but make sure you have your `@Listener` annotation :)

**Comment by bloodmc** [comment]
[13:23:14] [Server thread/INFO] [STDOUT]: [org.spongepowered.mod.plugin.SpongeWorldTest:onChangeBlock:331]: EntityPlayerMP['Kratos_Knox'/2282, l='New WorldTest2', x=-191.83, y=71.00, z=157.06] Caused BlockBreak minecraft:grass

Works fine for me in creative mode.

**Comment by clucky** [comment]
Working again as of Build 918, I believe it was inadvertently fixed with another issue.
