### ISSUE TITLE
Monster/Hostile Mob Spawning broken as of DEV-903

### ISSUE THREAD

**Issue by playlaughlovelearn** [SpongePowered/SpongeForge#450]
No hostile mobs/monsters spawn on fresh instances running SpongeForge for me from DEV-903 until DEV-921 (current) including the version I built myself out of git yesterday. I do not know if the same issue exists in SpongeVanilla. DEV-901 seems to work without issue.

bloodshot suggested something which successfully works around the issue for me: disabling the entity-activation-range module in the global sponge config.

[**file:** `config/sponge/global.conf`]

    # note: only the relevant setting is shown
    modules {
        entity-activation-range=false
    }

---

I was finally able to track down the point at which things go wonky via binary search/brute force. The initial 1577 DEV version (DEV-843) was working, DEV-903 didn't work, and eventually found that DEV-901 (the previous CI build) did work.

Verified by going to the Nether, switching to peaceful to clear out hostile mobs, then back to Normal (Hard also works) and seeing Pigmen/Ghasts spawning, also verified that in 903 even the Blaze spawners in fortresses do not work, they'll spin up as you approach them but never spawn anything.

---

Commits referenced in changelog for CI DEV-903 (12/13/2015 01:38:44 PM)

Commit | Author | Description
-------|--------|-------------
b1ad17a8e1a6f8d1517c7001c45a82c25ffa8655 | Zidane | Bump common ref.
653f40bb749567ebcbc2c53fa4140a9bb82184b1 | bloodshot | Refactor IP Forwarding support to allow a LoginProfile property to define the FML marker. Closes #424

**Comment by playlaughlovelearn** [comment]
a couple of other things that I forgot to mention about this issue:

* in the overworld, at least some non-hostile mobs are spawning fine; I saw at a minimum: pigs, sheep, cows, and bunnies. however, there were no zombies, skellies, or creepers
* this was only applying to a client/server setup; in single-player mode, spawns seemed to work normally
* forge by itself (e.g. when the spongeforge mod is disabled) spawns things, it's not until the SpongeForge mod is added in that things go south

**Comment by simon816** [comment]
Here's a list of commits that were added when common got bumped
https://github.com/SpongePowered/SpongeCommon/compare/71f0a94bca6a9de1004e3b916bd13f8c3312ef90%5E...548debbee10a61ee5986d25abc3c7bb95e0cced5
I'm thinking the most likely to cause this issue is https://github.com/SpongePowered/SpongeCommon/commit/c71cfc5557f434a31c5a91507be11aab41426d99

**Comment by JBYoshi** [comment]
@kashike has a PR that should fix this: SpongePowered/SpongeCommon#335
