### ISSUE TITLE
Chunk.getEntities abstract method exception

### ISSUE THREAD

**Issue by NeumimTo** [SpongePowered/SpongeForge#456]
Method call UnloadChunkEvent.getChunk.getEntities(Predicate) will cause following exception:

AbstractMethodError: Method net/minecraft/world/chunk/Chunk.getEntities(Ljava/util/function/Predicate;)Ljava/util/Collection; is abstract. 
According to this https://github.com/SpongePowered/SpongeForge/issues/274 the event should've been implemented.
- build 941

**Comment by simon816** [comment]
The event is implemented, that's how your handler is getting called, It's `getEntities` that's not.

As a temporary solution, use `getChunk().getWorld().getEntities()`
