### ISSUE TITLE
My server crash with buildcraft 1.8 and spongeforge (last version)

### ISSUE THREAD

**Issue by qwertyazerty** [SpongePowered/SpongeForge#457]
I have a bug with sponge forge, when i try to use it with buildcraft 1.8 my server crash 
Crash report http://www.pastebin.com/FK3g9WFK
Logs http://pastebin.com/t3XCY1Mf

**Comment by gabizou** [comment]
Already [fixed](https://github.com/BuildCraft/BuildCraft/commit/7f92496da5973d1cad2c7de4605d7a86e4a4c0a6) but will be available in the next pre-release build of BuildCraft.

**Comment by qwertyazerty** [comment]
Where can i download it ?
