### ISSUE TITLE
Player's healthbar is not rendered correctly after respawn

### ISSUE THREAD

**Issue by NeumimTo** [SpongePowered/SpongeForge#461]
If you set player's health to 40 2 healthbars are displayed 
Then the player dies and after respawn only one healthbar is displayed,
If the player takes any damage the healtbar flashes but wont display change until player's health is bellow 20;

        @Listener
        public void onPlayerLogin(ClientConnectionEvent.Join event) {
            event.getTargetEntity().offer(Keys.MAX_HEALTH, 40D);
            event.getTargetEntity().offer(Keys.HEALTH, 40D);
        }
 
- build 941

**Comment by Zidane** [comment]
@gabizou 

Shouldn't be hard to fix scaling :P.
