### ISSUE TITLE
SpongeForge breaks TerrainControl

### ISSUE THREAD

**Issue by Inscrutable** [SpongePowered/SpongeForge#463]
I've been experimenting with TerrainControl (Forge version, b.101) and SpongeForge. It was working OK with SF921, but now it breaks using SF964. Here's the end of the server log file as it fails to start: http://pastebin.com/HMfFKAJw . The same setup works as it should without SpongeForge in the mix. 
It's all on the SoS server box, in /home/minecraft/sos8-server if you need direct access.
Here's a [zip of the TerrainControl folder](https://dl.dropboxusercontent.com/u/81927080/TerrainControl.zip) (it goes in the /mods folder because ... they're contrarians).
Another minor issue I noted was the replacesurfaceblock feature wasn't working on one of my custom biomes (RockyBeach), whereas it does work in a bukkit or forge-only environment.

**Comment by Zidane** [comment]
@Deamon5550 

Get this fixed up ASAP.
