### ISSUE TITLE
better logging

### ISSUE THREAD

**Issue by hunter688** [SpongePowered/SpongeForge#466]
Will be possible add to latest.log all what I can see in the server console? latest.log is only one rotated log and does not show any useful informations for now.

see difference:
http://pastebin.com/rqw4x21V

**Comment by ST-DDT** [comment]
IMO its just a matter of wrong config. Read about log4j2 xml config.

**Comment by Minecrell** [comment]
Forge redirects only Minecraft messages to `latest.log`, everything else is in `fml-server-latest.log`.

**Comment by hunter688** [comment]
I know, but I think all in what I see in the console should be in the latest.log

**Comment by Minecrell** [comment]
See the edit in my comment.

**Comment by hunter688** [comment]
thanks
