### ISSUE TITLE
Setting a Block to Minecraft:Air in version 974

### ISSUE THREAD

**Issue by mrgoodrich** [SpongePowered/SpongeForge#468]
To be honest I'm pretty noob with Sponge dev stuff, but from what I can tell there is an error present in Spongeforge 974 where setting blockstates to air fails.  I'm not sure if this problem is in the present in newer versions of the mod, but my plugin which used to set blocks correctly now only works for everything but air.  Just a heads up, sorry I don't know more about how forge mods work, otherwise I would figure out why this is happening and submit a pull request to fix it :frowning:

**Comment by ST-DDT** [comment]
Can you give us a short code example that can be used to show what exactly does not work and to test any potential fix?

**Comment by mrgoodrich** [comment]
I verified this problem exists in version 978 as well.  The way I found it was through saving block states to a map (I won't explain why) and subsequently setting other blocks to the saved states.  It only makes sense for states that have been saved straight from the getState method to work with setState, unless something is fishy.

When I get the block state, I use
    playerWorld.getBlock(x, y, z);

I later set blocks with
    playerWorld.setBlock(rawWorldLocation[0], rawWorldLocation[1], rawWorldLocation[2], stateToSet);
where the rawWorldLocation is just an array of int locations and the state is what I saved from the get call earlier.

I tested this with dirt, stone, grass, and air.  It works for all of them except for air, meaning I think something is messed up with the setBlock command when the state is minecraft:air.  Let me know if I'm wrong though.  Like I said, I'm not very comfortable with this stuff :smile:

**Comment by simon816** [comment]
```java

**Comment by mrgoodrich** [comment]
Isn't it different though since you're using the setBlock method with an argument of type BlockType and I'm using the version with an argument of BlockState?

**Comment by simon816** [comment]
I used `BlockTypes.AIR.getDefaultState()` so I get the block state.
Testing `setBlockType` worked too.
Are you sure it's not something else interfering? e.g. event being cancelled, position is not what it should be etc.
Perhaps you could show some more of your code so we can see whether something else is messing up.

**Comment by mrgoodrich** [comment]
Of course, here's the relevant code where it's called (with a little bit of logging I just added):

```
Map<int[], BlockChange> blocksToUndo = mostRecentEditInEffect.getBlocks();
		blocksToUndo.keySet().forEach(blockLocationToRevert -> {
	logger.info("Setting block <{}{}{}> to {}", blockLocationToRevert[0], blockLocationToRevert[1], blockLocationToRevert[2], blocksToUndo.get(blockLocationToRevert).getOldState());
	logger.info("simon's is {}", BlockTypes.AIR.getDefaultState());
	p.getWorld().setBlock(blockLocationToRevert[0], blockLocationToRevert[1], blockLocationToRevert[2], blocksToUndo.get(blockLocationToRevert).getOldState());
});
```

Both of the logs are printing minecraft:air (not sure if it's relevant)..  The command I'm using this with works for any type of block other than air, since I create the map's blockchange's oldState field through

    BlockState currentBlockType = playerWorld.getBlock(x, y, z);

Let me know if you see anything fishy from this! :fish:

**Comment by mrgoodrich** [comment]
Okay I found my problem.  I was listening to the ChangeBlockEvent.Break event elsewhere, which canceled the event, making me think it wasn't working elsewhere.  Sorry about the confusion :frowning: Thanks for your time and the learning experience!
