### ISSUE TITLE
ArchimedesShipsPlus breaks SpongeForge

### ISSUE THREAD

**Issue by Inscrutable** [SpongePowered/SpongeForge#476]
I've been testing ArchimedesShipsPlus (archimedesshipsplus-MC1.8-V1.8), which also requires MovingWorld (movingworld-MC1.8-V1.8.1). The sponge mixin tweakers inside MovingWorld appear to be killing Sponge on startup - the game works, but no Sponge commands. Here's the latest fml-client-latest log file, from using *only* spongeforge996, and the two aforementioned mods.
http://pastebin.com/jfiV3bPC

**Comment by simon816** [comment]
Problem is that MovingWorld is using an older version of Mixin (https://github.com/darkevilmac/MovingWorld/blob/master/build.gradle#L71)
Ideally they would update their version, but what if Sponge was to relocate the mixin package @Mumfrey would that play nice?

**Comment by darkevilmac** [comment]
This should be fixed in my current repo builds, take a look at the unstable build here if you want to give it a shot. http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2364835-archimedes-ships-plus-move-your-world-submarines-1?page=36#c720

**Comment by Inscrutable** [comment]
Sorry @darkevilmac it still falls over. Here are the juicy bits from the crash report:
MovingWorldCoreMod (movingworld-MC1.8.9-INDEV-full.jar)
SpongeCoremod (spongeforge-1.8.9-1694-3.1.0-BETA-1070.jar) (I get the same for SF 1050 too):

net.minecraftforge.fml.common.LoaderException: com.google.inject.CreationException: Unable to create injector, see the following errors:
1) An exception was caught and reported. Message: net.minecraftforge.fml.common.MinecraftDummyContainer cannot be cast to org.spongepowered.api.plugin.PluginContainer
  at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
2) No implementation for org.spongepowered.api.plugin.PluginContainer annotated with @com.google.inject.name.Named(value=Minecraft) was bound.
  at org.spongepowered.mod.guice.SpongeGuiceModule.configure(SpongeGuiceModule.java:67)

I can pastebin the whole thing if you need. We should probably move this issue to your repo too.

**Comment by Mumfrey** [comment]
> Ideally they would update their version, but what if Sponge was to relocate the shaded mixin package @Mumfrey would that play nice?

No! Under absolutely no circumstances is it possible to relocate the mixin package.

**Comment by simon816** [comment]
Oh this error again...

OK it seems to be a simpler one this time, [`MovingWorldCoreMod#getModContainerClass()`](https://github.com/darkevilmac/MovingWorld/blob/6db0b6e30da6c8e2991db08ab5f60012c1b5dfc7/src/main/java/darkevilmac/movingworld/common/asm/coremod/MovingWorldCoreMod.java#L26) is force loading [`MovingWorldModContainer`](https://github.com/darkevilmac/MovingWorld/blob/6db0b6e30da6c8e2991db08ab5f60012c1b5dfc7/src/main/java/darkevilmac/movingworld/common/asm/coremod/MovingWorldModContainer.java#L9) which is causing `DummyModContainer` to load outside of the mixin transformer. @darkevilmac All you need to do is use the string FQN, i.e "darkevilmac.movingworld.common.asm.coremod.MovingWorldModContainer"
I believe this is one of the reasons the method returns a `String` and not a `Class`
Note I have not tested whether this fixes it, I just took a quick look over the code on GitHub

**Comment by darkevilmac** [comment]
https://github.com/darkevilmac/MovingWorld/issues/21

@Mumfrey feel free to close this issue it's more related to MovingWorld than SpongeForge.

**Comment by gabizou** [comment]
Closing as requested.
