### ISSUE TITLE
InteractBlockEvent.Primary not firing

### ISSUE THREAD

**Issue by NeumimTo** [SpongePowered/SpongeForge#480]
..when a player left clicks into air

**Comment by JBYoshi** [comment]
That's because when the player left clicks air, they're not left clicking a block. Use `InteractEvent.Primary` instead.

**Comment by NeumimTo** [comment]
But its equivalent 
InteractBlockEvent.Secondary is fired when someone rightcliking air

**Comment by JBYoshi** [comment]
If you paste the following code into your plugin and left click air, what output does it give (if any)?

```java
@Listener
public void testInteract(InteractEvent e) {
    System.out.println(e);
}
```

**Comment by NeumimTo** [comment]
Nothing, its not called.

**Comment by Zidane** [comment]
That is because it isn't an interaction and is instead a simple animation for the left click (Minecraft's design, its really odd).

Assigning this to me, I'll make it so this works in the air.
