### ISSUE TITLE
Fatal error crash while launching plain SpongeForge

### ISSUE THREAD

**Issue by hvidstue** [SpongePowered/SpongeForge#488]
Have read and following "the docs":

1. Downloading "Latest stable version of Forge 1.8" from http://files.minecraftforge.net
   1. HTTP 403 Forbidden was returned for the files mentioned at Note 3.
   2. Installer still gives message: The server installed successfully, you should now be able to run the file forge-1.8-11.14.4.1577-universal.jar
2. Installing Forge
3. Running java -jar forge-1.8-11.14.4.1577-universal.jar nogui
4. Stopping it by "stop"-command, getting:
   * [Server thread/INFO]: An unknown error occurred while attempting to perform this command
   * [23:18:44] [Server thread/ERROR]: Couldn't process command: 'stop'
5. Accepting eula
6. Running Forge again, getting standard errors about missing .json files (whitelist and so on)
7. Stopping it by "stop"-command, clean shut down
8. Running Forge again to make sure I have no errors, getting only:
   * [main/ERROR] [FML]: FML appears to be missing any signature data. This is not a good thing
9. Stopping it by "stop"-command, clean shut down
9. Download SpongeForge Beta #1000 to mods folder
10. Running Forge again
11. Fatal crash, I have attached crash report:
[crash-2016-01-08_23.28.06-server.txt](https://github.com/SpongePowered/SpongeForge/files/83346/crash-2016-01-08_23.28.06-server.txt)

Note 1: Docs says get the Forge version matching the SpongeForge (for the Spongeforge Beta #1000 that equals to Forge#1577). I get same crash wheither I am using #1577 (latest Forge) or #1563 (recommended Forge).
Note 2: Crash report is from SF#1000 + F#1577
Note 3: Files which could not be downloaded by the forge installer:
https://libraries.minecraft.net/io/netty/netty-all/4.0.15.Final/netty-all-4.0.15.Final.jar.pack.xz
https://libraries.minecraft.net/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar.pack.xz
https://libraries.minecraft.net/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar.pack.xz
https://libraries.minecraft.net/lzma/lzma/0.0.1/lzma-0.0.1.jar.pack.xz
https://libraries.minecraft.net/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar.pack.xz

**Comment by hvidstue** [comment]
Also have same issue with latest SpongeForce#1018 + Forge#1577
[crash-2016-01-08_23.33.50-server.txt](https://github.com/SpongePowered/SpongeForge/files/83357/crash-2016-01-08_23.33.50-server.txt)

**Comment by Aaron1011** [comment]
btw, there's currently an issue with the downloads page. The latest build is actually `1025` (you have to click on 'Show all downloads')

**Comment by hvidstue** [comment]
I found the 403'ed Forge files from another machine, tried again, but same result, so the files are not the issue.

**Comment by hvidstue** [comment]
Oh BTW! Running on Linux (Slackware)

**Comment by hvidstue** [comment]
@Aaron1011 thanks for the heads up, but alas, still same problem :-/ ...
[crash-2016-01-09_00.29.58-server.txt](https://github.com/SpongePowered/SpongeForge/files/83408/crash-2016-01-09_00.29.58-server.txt)

**Comment by JBYoshi** [comment]
Ah... Here's your solution: https://forums.spongepowered.org/t/spongeforge-not-starting-on-linux/10323/10

**Comment by hvidstue** [comment]
@JBYoshi whoa, *that* was a specific answer. Will try that out! :)

**Comment by hvidstue** [comment]
@JBYoshi thanks! :)

So simple a solution!
For others, looking for the answer, the simple trick in Slackware is:
Edit in `/etc/profile.d/lang.sh`, make
`export LANG=en_US`
to
`export LANG=en_US.UTF-8`
and reboot

**Comment by simon816** [comment]
@zml I think we need to remove the requirement for the locale to be UTF-8, I think this is the forth time I've seen someone get this error now.
