### ISSUE TITLE
Chunkloaderz server crash

### ISSUE THREAD

**Issue by cauliflower69** [SpongePowered/SpongeForge#495]
http://pastebin.com/qipYnrXR

http://www.curse.com/mc-mods/minecraft/238153-chunkloaderz

**Comment by JBYoshi** [comment]
I think I found the problem: ChunkLoaderZ has a custom property class, `PropertyRange`, which extends another custom class, `PropertyBase`, which does not extend the vanilla `PropertyHelper` class.

I posted an issue on the ChunkLoaderZ repository: AEnterprise/ChunkLoaderZ#4

**Comment by cauliflower69** [comment]
Thank you so much.

**Comment by JBYoshi** [comment]
Should be fixed with the latest version.

**Comment by simon816** [comment]
Confirmed, fixed by https://github.com/AEnterprise/ChunkLoaderZ/commit/0779827a5c4d52ec311222107e08cb90323de00e
Grab the latest Chunkloaderz and it will be fine
