### ISSUE TITLE
Foundry-1.8.9-1.3.2.0 Server Crash

### ISSUE THREAD

**Issue by cauliflower69** [SpongePowered/SpongeForge#497]
http://pastebin.com/B6hkmVnf

**Comment by gabizou** [comment]
Can you try loading the server with Forge 1696 or higher? It may seem like 1695 had a bug with the deobfuscation environment.

**Comment by cauliflower69** [comment]
The server launches fine with just Forge without Sponge. Do you want me to try sponge with the latest Forge version ?

**Comment by cauliflower69** [comment]
Ok so I tried with the latest Forge 1699

http://pastebin.com/u04nLWyK

**Comment by gabizou** [comment]
@cauliflower69 Download the latest Foundry 1.3.3.0 and re-test.

**Comment by cauliflower69** [comment]
Tested with latest Foundry and sponge on Forge 1699 and it booted fine. Thanks
