### ISSUE TITLE
setupDecompWorkspace fail because of java heap space

### ISSUE THREAD

**Issue by GAMINGLOL** [SpongePowered/SpongeForge#499]
When I ran setupDecompWorkspace it gave me a build fail because of java heap can someone help
me here's the crash report http://pastebin.com/xzTmcbs6

**Comment by gabizou** [comment]
You'll need to increase the maximum memory to gradle. You can read [Gradle's build environment documentation](https://docs.gradle.org/current/userguide/build_environment.html). This isn't a bug with SpongeForge but closer to ForgeGradle 2.1 taking a bit more memory to setup than it did previously.

**Comment by DDoS** [comment]
Set jvmoption in gradle.properties to allocate more memory. Look it up, details are in the gradle documention.
