### ISSUE TITLE
--gameDir is ignored by SpongeForge

### ISSUE THREAD

**Issue by kashike** [SpongePowered/SpongeForge#502]
LegacyLauncher accepts a `--gameDir` arg, but Sponge [ignore it](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/launch/SpongeLaunch.java#L44-L46).
Forge resolves the `config` and `mods` directories from it.

**Comment by Zidane** [comment]
@kashike 

Want to look into making this work now that you have a machine again? :p.
