### ISSUE TITLE
Sponge 3.1.0-BETA-1060 Crash

### ISSUE THREAD

**Issue by alexbegt** [SpongePowered/SpongeForge#503]
My server keeps crashing due to sponge, I've ran the correct version of forge that the spongeForge Requires, but this keeps happening: http://pastebin.com/xLFA2hY8

**Comment by Aaron1011** [comment]
@alexbegt: Can you try creating a clean Forge server (with the proper version), and re-download SpongeForge? Based on your traceback, something really odd is going on.

**Comment by simon816** [comment]
Thaumic Infusion is not compatibly with sponge at the moment. I'll be looking into a fix when I have some time

**Comment by alexbegt** [comment]
@Aaron1011 I did test that, And it did work. and ahh @simon816 thanks.

**Comment by simon816** [comment]
Issue with Thaumic Infusion fixed in TI version 4.76  http://minecraft.curseforge.com/projects/thaumic-infusion/files/2276547
