### ISSUE TITLE
SpongeForge breaks Thaumcraft 5 crucible crafting and filling

### ISSUE THREAD

**Issue by phit** [SpongePowered/SpongeForge#507]
Azanor/thaumcraft-5#242

mods used:
* Forge 1.8.9-11.15.0.1709
* Baubles-1.8.9-1.1.3.0.jar
* jei_1.8.9-2.19.0.94.jar
* Thaumcraft-1.8.9-5.1.3.jar
* spongeforge-1.8.9-1694-3.1.0-BETA-1061.jar

gave myself all research, then tried to craft two nitor with 3 coal and 6 torches (enough aspects for 2 nitor crafting operations), when i throw in the catalyst (2 glowstone) the aspects get added to the crucible, instead of finalizing the crafting operation (giving me two nitor)
![screenshot](https://cloud.githubusercontent.com/assets/2097483/12429669/d213dca6-beeb-11e5-8b03-3ddc84f9d906.png)

as soon as i remove spongeforge it works as intended!

another thing when spongeforge is installed, rightclicking the crucible with a bucket of water fills it, but also places a source block of water next to it

**Comment by bloodmc** [comment]
@phit Does this still happen with latest build?

**Comment by phit** [comment]
yes, just retested with

Baubles-1.8.9-1.1.3.0.jar
JEIAddons_1.8.9-0.10.0.35.jar
jei_1.8.9-2.22.4.106.jar
spongeforge-1.8.9-1694-3.1.0-BETA-1099.jar
Thaumcraft-1.8.9-5.1.4.jar

**Comment by gabizou** [comment]
@Azanor I'm not 100% sure why, but I noticed in testing in dev that right clicking the crucible to craft with a crucible (like nitor), the crafting works. However, the normal "throw in the final crafting ingredient and the result will pop up" doesn't work, I'm not sure at all where to look for how or where we're breaking the crucible logic handling.

**Comment by phit** [comment]
sweet, thanks for the fix!
