### ISSUE TITLE
Cannot tame wolves

### ISSUE THREAD

**Issue by trentech** [SpongePowered/SpongeForge#509]
When attempting to tame a wolf, I can burn through stacks and wolf will not tame. It also sometimes throws an error when spam right clicking. Have only tested on SpongeForge.

http://pastebin.com/WV7irgmX

**Comment by Aaron1011** [comment]
@trentech: I'm unable to reproduce this on the latest SpongeForge or SpongeVanilla. I don't get any error, and I'm able to successfully tame the wolf.

Can you try again with the latest SpongeForge (and the proper Forge build)?

**Comment by trentech** [comment]
I'm already on the latest version, but it's not doing it anymore. I switched to a clean client and it stopped. I think it could have been due to Forge client not matching the server, although I don't see why it would make a difference. I have no mods installed. Either way I think it was on my end

**Comment by Aaron1011** [comment]
@trentech: Ok. Feel free to re-open this if the problem reoccurs.
