### ISSUE TITLE
BiomeGeneration with modded Biomes

### ISSUE THREAD

**Issue by FabiUnne** [SpongePowered/SpongeForge#512]
Hi there,

I currently working on a larger project. For this project I need a country-like island. I want to link each country to a biome-type -> implemented BiomeGenerator [... see https://forums.spongepowered.org/t/custom-biomegenerator-height/10069 ]

Now, I loaded forge (build 1705), spongeforge (build 1694) and in this example BiomesOPlenty (build 1642), but when I try to load a custom biome with
`game().getRegistry().getType(BiomeType.class, name).orElse(BiomeTypes.SKY);`
doesn't aktually load the biome.

I've found out that if I change the world-type, the biomes are generated, but the biome-borders look exactly like the vanilla ones in my previous post (as mentioned above).

The difference between this screenshots is only the world-type:

level-type=DEFAULT
![2016-01-22_18 50 36](https://cloud.githubusercontent.com/assets/1349885/12522277/0daffeaa-c150-11e5-86b7-67451f31c437.png)

level-type=BIOMESOP
![2016-01-22_18 47 13](https://cloud.githubusercontent.com/assets/1349885/12522276/0daf5b08-c150-11e5-94b2-fb4f9fb6a14b.png)

@Deamon5550 @Glitchfiend any idea how to fix this?

Thanks,
Fabian

**Comment by Deamon5550** [comment]
What version of spongeforge are you using? because there is no build 1694 of spongeforge, [1086 is latest](http://files.minecraftforge.net/spongepowered).

**Comment by FabiUnne** [comment]
ohh, yeah it's build 1058. the 1694 seems to be the forge one.

**Comment by NitroxydeX** [comment]
Ping @Adubbz

**Comment by NitroxydeX** [comment]
No idea or solution at the moment?

**Comment by FabiUnne** [comment]
I know every time @NitroxydeX or I ask, it takes even longer. But I didn't heard from you for 23 days. Any progress @Deamon5550 ? Or can I help you? I just don't know what it could be.

**Comment by bloodmc** [comment]
This shouldn't be an issue with latest SF builds. Create a new ticket if it persists.
