### ISSUE TITLE
Channel handlers invoked on Netty threads

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/SpongeForge#514]
This is mostly for @simon816 

After playing with handlers in Almura, I've discovered that they are invoked on Netty threads as evidenced below:

```[01:58:53] [Netty Local Client IO #0/ERROR] [almura]: World 1```

I'm unsure if this is what is happening for FML handlers in Forge but I doubt it is (but you never know). If a handler is meant to do something to a World (be it on client or server) or some other game object, this will cause issues fast.

**Comment by Zidane** [comment]
Almost all Vanilla handlers get enqueued on the main thread and I'm thinking we'll need to do the same before passing it off to the registered class...

**Comment by Minecrell** [comment]
@simon816 told me this is intended behavior, so this is currently the same on SpongeVanilla.

**Comment by simon816** [comment]
It is the same in Forge. Since 1.8 they are handled in a separate thread.
http://greyminecraftcoder.blogspot.com.au/2015/01/thread-safety-with-network-messages.html

**Comment by Zidane** [comment]
Right I'm aware that they are but, as I said above, Vanilla generally enqueues them to the sided thread.

If our desire is to preserve that thread, we should update the documentation to explain that your handler WILL NOT BE THREAD SAFE BY DEFAULT. I can see many many developers getting burned by this and wondering if Sponge has made a mistake (by sheer ignorance, this is Minecraft's design).
