### ISSUE TITLE
cannot be cast to org.spongepowered.api.event.Event

### ISSUE THREAD

**Issue by knoxhack** [SpongePowered/SpongeForge#515]
im having this issue on my server using a 1.8.9 modpack latest forge/sponge

---- Minecraft Crash Report ----

WARNING: coremods are present:
  thaumicinfusion (ThaumicInfusion-4.77.jar)
  ThaumcraftLoader (Thaumcraft-1.8.9-5.1.4.jar)
  TNTUtilities Core (tnt_utilities-mc1.8.9-1.1.2.jar)
  SpongeCoremod (spongeforge-1.8.9-1722-3.1.0-BETA-1115.jar)
  LoadingPlugin (Bloodmoon-MC1.8.8-1.4.jar)
  FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  LoadingPlugin (RandomThings-MC1.8.9-3.5.8.jar)
  DCLoadingPlugin (DummyCore-2.2.189.0 (1).jar)
Contact their authors BEFORE contacting forge

// Oops.

Time: 1/29/16 5:41 PM
Description: Exception in server tick loop

java.lang.ClassCastException: net.minecraftforge.fml.common.event.FMLConstructionEvent cannot be cast to org.spongepowered.api.event.Event
	at net.minecraftforge.fml.common.LoadController.onPost(LoadController.java:55)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:512)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:320)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:112)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Linux (amd64) version 3.16.0-30-generic
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5847099304 bytes (5576 MB) / 8039432192 bytes (7667 MB) up to 8039432192 bytes (7667 MB)
	JVM Flags: 2 total; -Xmx8000M -Xms8000M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.1726 98 mods loaded, 98 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{8.0.99.99} [Forge Mod Loader] (craftbukkit.jar) 
	UC	Forge{11.15.1.1726} [Minecraft Forge] (craftbukkit.jar) 
	UC	sponge{DEV} [Sponge] (spongeforge-1.8.9-1722-3.1.0-BETA-1115.jar) 
	UC	tnt_utilities_core{1.1.2} [TNTUtils Core] (minecraft.jar) 
	UC	ActuallyAdditions{1.8.9-r24} [Actually Additions] (ActuallyAdditions-1.8.9-r24.jar) 
	UC	ac2{1.1.3 Beta} [Alchemy Craft 2] (alchemycraft2 v1.3.0.jar) 
	UC	basemetals{1.6.0} [Base Metals] (BaseMetals-1.6.0.jar) 
	UC	BattleTowers{1.5.5} [Battle Towers] (BattleTowers-1.8.8.jar) 
	UC	bdlib{1.10.0.9} [BD Lib] (bdlib-1.10.0.9-mc1.8.9.jar) 
	UC	betterbuilderswands{0.4.2} [Better Builder's Wands] (BetterBuildersWands-0.4.2-1.8.9r73+04b6c51 (1).jar) 
	UC	BiomesOPlenty{3.0.0} [Biomes O' Plenty] (BiomesOPlenty-1.8.9-3.0.0.1759-universal.jar) 
	UC	BloodMagic{1.8.9-2.0.0-8} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.8.9-2.0.0-8.jar) 
	UC	Bloodmoon{1.2} [Bloodmoon] (Bloodmoon-MC1.8.8-1.4.jar) 
	UC	bookshelfapi{2.2.4} [Bookshelf] (Bookshelf-1.8.9-2.2.4.jar) 
	UC	BuildersGuides{1.8.9-0.1.0-alpha} [Builder's Guides] (buildersguides-1.8.9-0.1.0-alpha.jar) 
	UC	cannibalism{1.2.2} [Cannibalism] (Cannibalism-2.2.2-1.7.10.jar) 
	UC	Chameleon{1.8.8-0.2.0} [Chameleon] (Chameleon-1.8.8-0.2.0.jar) 
	UC	chancecubes{@VERSION@} [Chance Cubes] (ChanceCubes-1.8.9-1.6.2.76.jar) 
	UC	chisel{@VERSION@} [Chisel] (Chisel-MC1.8.9-0.0.2.6.jar) 
	UC	chiselsandbits{mc1.8.9-v1.8.6} [Chisels & Bits] (chiselsandbits-mc1.8.9-v1.8.6.jar) 
	UC	ComputerCraft{1.78} [ComputerCraft] (ComputerCraft1.78.jar) 
	UC	cosmeticarmorreworked{1.8.9-v1} [CosmeticArmorReworked] (CosmeticArmorReworked-1.8.9-v1.jar) 
	UC	CrissCross{1.3.8} [Criss Cross] (CrissCross-1.8.9-1.3.8.jar) 
	UC	wonderfulwands{1.8.0} [Wonderful Wands] (CyanosWonderfulWands_1.8.9-1.8.0.jar) 
	UC	DummyCore{2.2.189.0.} [DummyCore] (DummyCore-2.2.189.0 (1).jar) 
	UC	eiramoticons{3.2.3} [EiraMoticons] (eiramoticons-mc1.8.9-3.2.3.jar) 
	UC	endores{1.0-a.006} [End Ores] (End Ores-1.0-a.006.jar) 
	UC	Waila{1.6.0} [Waila] (Waila-1.6.0-B3_1.8.8.jar) 
	UC	enderrift{0.81} [Ender-Rift] (EnderRift-0.81.jar) 
	UC	ShetiPhianCore{3.0.3} [ShetiPhian-Core] (ShetiPhianCore-1.8.9-3.0.3.jar) 
	UC	EnderTanks{1.2.0} [EnderTanks] (EnderTanks-1.8.9-1.2.0.jar) 
	UC	EnderZoo{1.8.9-1.1.0} [Ender Zoo] (EnderZoo-1.8.9-1.1.2.jar) 
	UC	EnjinMinecraftPlugin{2.4.9-1.8} [EnjinMinecraftPlugin] (EnjinMinecraftForgePlugin-1.8.9-VotifierSponge.jar) 
	UC	exnihilo2{0.28} [Ex Nihilo 2] (ExNihilo2-0.28.jar) 
	UC	Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
	UC	Thaumcraft{5.1.4} [Thaumcraft] (Thaumcraft-1.8.9-5.1.4.jar) 
	UC	ExtraFood{0.7.51} [Extra Food] (ExtraFood-1.8.9-0.7.51.jar) 
	UC	ezstorage{1.0} [EZ Storage] (ezstorage-1.8.9-1.2.2.jar) 
	UC	fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-1.8-1.6.jar) 
	UC	flatcoloredblocks{mc1.8.9-v1.3} [Flat Colored Blocks] (flatcoloredblocks-mc1.8.9-v1.5.jar) 
	UC	fe{1.1} [Food Expansion] (FoodExpansion1.1-mc1.8.9.jar) 
	UC	FTBL{2.0.2} [FTBLib] (FTBLib-1.8.9-2.0.2.jar) 
	UC	FTBU{2.0.2} [FTBUtilities] (FTBUtilities-1.8.9-2.0.2.jar) 
	UC	FunOres{1.1.0-beta3} [Fun Ores] (FunOres-1.8.9-1.1.0-beta3-38.jar) 
	UC	xlib{1.0.0} [xlib] (halocraft-2.0-v1.5.jar) 
	UC	halocraft{1.5} [HaloCraft 2.0] (halocraft-2.0-v1.5.jar) 
	UC	samshorsefood{1.1.2} [Horse Upgrade Food] (HorseUpgradeFood-1.8.9-1.1.2.jar) 
	UC	howlingmoon{1.0.1} [Howling Moon] (howlingMoon-1.8.9-1.0.1.jar) 
	UC	infinitycraft{1.0-a.019} [Infinity Craft] (InfinityCraft-1.0-a.019.jar) 
	UC	samsinvcrafting{1.0.3} [Inventory Crafting] (InventoryCrafting-1.8.9-1.0.3.jar) 
	UC	IronChest{6.0.123.769} [Iron Chest] (ironchest-1.8.9-6.0.123.769.jar) 
	UC	JEI{2.23.0.108} [Just Enough Items] (jei_1.8.9-2.23.0.108.jar) 
	UC	mantle{1.8.9-0.7.jenkins72} [Mantle] (Mantle-1.8.9-0.7.jar) 
	UC	testdummy{1.0} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.9b.jar) 
	UC	mobrebirthvc{1.5} [Mob Rebirth Version Checker] (MobRebirth-4.0.1.5.jar) 
	UC	mobrebirth{4.0.1.5} [Mob Rebirth] (MobRebirth-4.0.1.5.jar) 
	UC	MoreFurnaces{1.5.0} [More Furnaces] (MoreFurnaces-1.5.0-MC1.8.9.jar) 
	UC	Morpheus{1.8.9-2.0.57} [Morpheus] (Morpheus-1.8.9-2.0.57.jar) 
	UC	MysticalCrops{1.1} [Mystical Crops] (Mystical Crops-1.1.jar) 
	UC	fodc{1.7.1} [Ore Dictionary Converter] (OreDictionaryConverter-1.7.1.jar) 
	UC	clayspawn{1.8.9a} [Pam's Clay Spawn] (Pam's Clay Spawn 1.8.9a.jar) 
	UC	getalltheseeds{1.8.9a} [Pam's Get all the Seeds!] (Pam's Get all the Seeds! 1.8.9a.jar) 
	UC	PneumaticCraft{1.13.4-5} [PneumaticCraft] (PneumaticCraft-1.8.9-1.13.4-5-universal.jar) 
	UC	poweradvantage{1.4.1} [Power Advantage] (PowerAdvantage-1.4.1.jar) 
	UC	practicalities{2.0.0-b6} [Practicalities] (practicalities-1.8.9-2.0.0-b6.jar) 
	UC	pressure{1.2.5.8} [Pressure Pipes] (pressure-1.2.5.8-mc1.8.9.jar) 
	UC	progressiveautomation{1.6.31} [Progressive Automation] (ProgressiveAutomation-1.8.9-1.6.31.jar) 
	UC	rafradek_tf2_weapons{0.4.2} [TF2 Stuff Mod] (rafradek_tf2_weapons-1.8.9-0.4.2.jar) 
	UC	RandomThings{3.5.8} [Random Things] (RandomThings-MC1.8.9-3.5.8.jar) 
	UC	rftools{4.20beta14} [RFTools] (rftools-1.8.9-4.20beta14.jar) 
	UC	rftoolsdim{4.20beta15} [RFTools Dimensions] (rftoolsdim-1.8.9-4.20beta15.jar) 
	UC	Roguelike{1.4.5} [Roguelike Dungeons] (RoguelikeDungeons-1.8.9-1.4.5.jar) 
	UC	AS_Ruins{15.6} [Ruins Spawning System] (Ruins-1.8.8.jar) 
	UC	SilentGems{1.3.9} [Silent's Gems] (SilentsGems-1.8.9-1.3.9-101.jar) 
	UC	SimpleDimensions{1.2} [Simple Dimensions] (SimpleDimensions-1.2.jar) 
	UC	steamadvantage{1.5.0} [Steam Advantage] (SteamAdvantage-1.5.0.jar) 
	UC	StorageDrawers{1.8.8-2.2.0} [Storage Drawers] (StorageDrawers-1.8.8-2.2.0.jar) 
	UC	storagenetwork{1.2} [Storage Network] (StorageNetwork-1.8.9-1.2.jar) 
	UC	superores{1.1} [Super Ores] (Super Ores V1.1 mc1.8.9.jar) 
	UC	Talismans 2{2.2.0} [Talismans 2] (Talismans2-1.8.9-2.2.0.jar) 
	UC	tconstruct{1.8.9-2.0.2.jenkins61} [Tinkers' Construct] (TConstruct-1.8.9-2.0.2.jar) 
	UC	thaumicbases{1.4.189.21} [Thaumic Bases] (ThaumicBases-2.1.189.21 (1).jar) 
	UC	thaumicinfusion{4.77} [Thaumic Infusion] (ThaumicInfusion-4.77.jar) 
	UC	thelittlethings{1.2.2-Forge1.8.9} [The Little Things] (The Little Things-v.1.2.2-mc1.8.9.jar) 
	UC	thutcore{2.2.2} [ThutCore] (thutcore-2.2.2.jar) 
	UC	thuttech{2.2.6} [Thut's Tech] (thuttech-2.2.6.jar) 
	UC	tnt_utilities{1.1.2} [TNTUtils] (tnt_utilities-mc1.8.9-1.1.2.jar) 
	UC	totemic{1.8.9-0.6.4.1} [Totemic] (Totemic-1.8.9-0.6.4.1.jar) 
	UC	CaveCraft{@VERSION@} [TSON Craft] (TSON Craft 1.5 (1).jar) 
	UC	twentyticks{1.0.0} [Twenty Ticks] (twentyticks.jar) 
	UC	ultimate_unicorn_mod{1.4.0} [Wings, Horns, and Hooves, the Ultimate Unicorn Mod!] (ultimate_unicorn_mod-1.8.9-1.4.0.jar) 
	UC	unlogicii{4.1.0.42} [UnLogic II] (UnLogicII-4.1.0.42.jar) 
	UC	unlogiciivc{1.5} [UnLogic II Version Checker] (UnLogicII-4.1.0.42.jar) 
	UC	VeinMiner{0.31.2_build.unknown} [Vein Miner] (VeinMiner-1.8.9_0.31.2.unknown.jar) 
	UC	VeinMinerModSupport{0.31.2_build.unknown} [Mod Support] (VeinMiner-1.8.9_0.31.2.unknown.jar) 
	UC	wawla{1.4.7} [What Are We Looking At] (Wawla-1.4.7-1.8+.jar) 
	UC	worldedit{6.1.1} [WorldEdit] (worldedit-forge-mc1.8.9-6.1.1.jar) 
	Loaded coremods (and transformers): 
thaumicinfusion (ThaumicInfusion-4.77.jar)
  drunkmafia.thaumicinfusion.common.asm.BlockTransformer
  drunkmafia.thaumicinfusion.common.asm.WorldTransformer
ThaumcraftLoader (Thaumcraft-1.8.9-5.1.4.jar)
  
TNTUtilities Core (tnt_utilities-mc1.8.9-1.1.2.jar)
  ljfa.tntutils.asm.ExplosionTransformer
SpongeCoremod (spongeforge-1.8.9-1722-3.1.0-BETA-1115.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
LoadingPlugin (Bloodmoon-MC1.8.8-1.4.jar)
  lumien.bloodmoon.asm.ClassTransformer
FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
LoadingPlugin (RandomThings-MC1.8.9-3.5.8.jar)
  lumien.randomthings.asm.ClassTransformer
DCLoadingPlugin (DummyCore-2.2.189.0 (1).jar)
  DummyCore.ASM.DCASMManager
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- TinkerDebug (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge,SpongeForge'
	Type: Dedicated Server (map_server.txt)

**Comment by knoxhack** [comment]
It only happens when I add spongeforge

**Comment by simon816** [comment]
One of these mods are conflicting:
```
ThaumicInfusion-4.77.jar
Thaumcraft-1.8.9-5.1.4.jar
tnt_utilities-mc1.8.9-1.1.2.jar
Bloodmoon-MC1.8.8-1.4.jar
FastLeafDecay-1.8-1.6.jar
RandomThings-MC1.8.9-3.5.8.jar
DummyCore-2.2.189.0 (1).jar
```
Remove one by one and find out which one it is

**Comment by knoxhack** [comment]
Thank you, it was DummyCore-2.2.189.0
