### ISSUE TITLE
Exception in thread "Server Watchdog"

### ISSUE THREAD

**Issue by knoxhack** [SpongePowered/SpongeForge#517]
https://gist.github.com/knoxhack/bd09d2aa9d631613fbc2

**Comment by kinggoesgaming** [comment]
My eyes my eyes...

Use a github gist or pastebin...

**Comment by simon816** [comment]
This looks like the issue I got where the cause object increases and runs out of memory. @bloodmc It seems to be recording block changes when generating the world and then as soon as an entity is about to be spawned it tries to flush the tracked transactions (which can be over 50,000 blocks in my testing)
