### ISSUE TITLE
SpongeForge does not track Mod provided generators

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeForge#518]
Mainly for @Deamon5550, mods (like Thaumcraft) that provide their own `WorldGenerator` are effectively getting bypassed with regards to tracking. This prevents us from being able to capture and throw events appropriately.

Including a screenshot of the relative things being handled.
![image](http://puu.sh/mPQfd/f6a9614bd6.png)

**Comment by gabizou** [comment]
Note that this is also likely causing issues where world seeds generate very differently between the custom mods with SpongeForge and without SpongeForge.

**Comment by Aaron1011** [comment]
Is this still an issue?

**Comment by bloodmc** [comment]
@Deamon5550 Is this still an issue?

**Comment by phit** [comment]
I couldn't find any traces left of the code mentioned here in the current codebase, gonna close this as it was probably resolved a long time ago with one of the rewrites.
