### ISSUE TITLE
Mobs cross cart track

### ISSUE THREAD

**Issue by flash4203** [SpongePowered/SpongeForge#520]
Not sure if this is a bug but mobs are able to cross cart tracks so when you are in a cart you hit a zombie and get sent backwards :-/ I have not played mc in a year or two but I remember that mojong released an update back then to stop entities crossing track blocks. 

Forgesponge I am using.

**Comment by gabizou** [comment]
Directly from the wiki: 
>Mobs no longer walk over rails unless they are pursuing the player.

**Comment by flash4203** [comment]
But I have seen sheep cross it :-/

**Comment by ST-DDT** [comment]
@flash4203 I have two different Bukkit servers, I have a Sponge server and I have a vanilla server. 
On each of them I have to wall in my rails to avoid strolling animals that block the rails.

**Comment by JBYoshi** [comment]
@flash4203 Maybe "mobs" is just referring to hostile mobs.

**Comment by kinggoesgaming** [comment]
AFAIK spawning on rails is fixed in one of the 1.9 snapshots... But yes passive mobs can always been able to walk over rails
