### ISSUE TITLE
Exception ticking world entities

### ISSUE THREAD

**Issue by knoxhack** [SpongePowered/SpongeForge#521]
I tried to make a dimension with the SimpleDimensions Mod, and I got this crash, server was in a crash loop until I removed that mod or spongeforge

https://gist.github.com/knoxhack/088090965c6be3451814

**Comment by simon816** [comment]
As a temporary solution, you can use a sponge plugin to replace SimpleDimensions, that was the solution to the same issue posted on the forums https://forums.spongepowered.org/t/solved-crash-loop-on-server-forge/10598/17?u=simon816
