### ISSUE TITLE
lumien.randomthings.worldgen.WorldGenSakanade.generate

### ISSUE THREAD

**Issue by knoxhack** [SpongePowered/SpongeForge#524]
I get this crash with the Random Things mod latest version

https://gist.github.com/knoxhack/43f70cd7ee000189d4de

**Comment by simon816** [comment]
Are you sure it only happens with Random Things and SpongeForge? It could be another mod

**Comment by knoxhack** [comment]
@simon816 Random Things just got updated today with a fix: 
Changelog:
Fixed: Sponge Server crashing while generating world
