### ISSUE TITLE
k4unl.minecraft.Hydraulicraft.world.WorldGenOil.generate(WorldGenOil.java:46)

### ISSUE THREAD

**Issue by knoxhack** [SpongePowered/SpongeForge#525]
I get this crash with lastest Haydraulicraft 

https://gist.github.com/knoxhack/a767b05ed6fd00ba7117

**Comment by simon816** [comment]
Could you post the entire `fml-server-latest.log`? Also, remove other mods so that I know they aren't interfering.

**Comment by Aaron1011** [comment]
@knoxhack: I can't seem to reproduce this. Can you try again with the latest SpongeForge and Hydraulicraft?

**Comment by knoxhack** [comment]
This is now fixed guys thank you, keep the good work
