### ISSUE TITLE
ClientConnectionEvent.Disconnect is called with an incomplete player object

### ISSUE THREAD

**Issue by Minecrell** [SpongePowered/SpongeForge#527]
If you connect with a Forge client without mods to a SpongeForge server with a mod that is required on the client side the disconnection causes the `ClientConnectionEvent.Disconnect` to be called with an incomplete player object:

For example, in this case the plugin will print `null` for the connection:

``` java
@Listener
public void onDisconnect(ClientConnectionEvent.Disconnect event) {
    Player player = event.getTargetEntity();
    System.out.println(player.getConnection());
}
```

This causes NPEs in plugins because they expect the methods to never return null.

**Comment by simon816** [comment]
I think it would be useful to add an event in the api for when a GameProfile is disconnected, before the player object is ready. The above case would use that event instead, as well as disconnecting banned users etc.

**Comment by gabizou** [comment]
Or possibly for these cases: `ClientConnectionEvent.Reject` since it's really only evident in a Forge environment when a client doesn't have particular mods.

**Comment by stephan-gh** [comment]
Fixed in https://github.com/SpongePowered/SpongeCommon/pull/1135
