### ISSUE TITLE
WorldProperties.setWorldBorderDiameter() applies to all worlds

### ISSUE THREAD

**Issue by kremi151** [SpongePowered/SpongeForge#528]
Here is my code:

WorldCreationSettings wcs = WorldCreationSettings
   .builder()
   .dimension(DimensionTypes.OVERWORLD)
   .enabled(true)
   .gameMode(GameModes.SURVIVAL)
   .generator(GeneratorTypes.OVERWORLD)
   .hardcore(false)
   .keepsSpawnLoaded(true)
   .loadsOnStartup(true)
   .name(MAP_NAME)
   .usesMapFeatures(true)
   .build();

Optional<WorldProperties> owp = getServer().createWorldProperties(wcs);

if (owp.isPresent()) {
			owp.get().setWorldBorderCenter(0, 0);
			owp.get().setWorldBorderDiameter(200);
}

It seems like this code causes that the modified border center and diameter will be applied to every world instead of applying only to the newly created or loaded world.

**Comment by simon816** [comment]
@Minecrell did https://github.com/SpongePowered/SpongeCommon/commit/ba652122e5eee121b583c1fdce62fd89e5be906c fix this?

**Comment by Minecrell** [comment]
@simon816 Quite sure it should, but someone should verify this to be sure.
