### ISSUE TITLE
Unable to mount

### ISSUE THREAD

**Issue by xChristopher210** [SpongePowered/SpongeForge#532]
Players cannot mount anything as boats or minecarts. When another player sees the mounted player, on their end it looks like the player is on the object but the player mounting can move around but will be moved back to the spot and not interact with the mountable block/entity (Pixelmon).

**Comment by gabizou** [comment]
I'm pretty sure this was fixed a while ago, what version of SpongeForge is this?

**Comment by xChristopher210** [comment]
SpongeForge-1120

**Comment by gabizou** [comment]
Yeah, update your SpongeForge to latest. This is a bug that was fixed quite a few builds ago.
