### ISSUE TITLE
Sign text disappearing when InteractBlockEvent is cancelled

### ISSUE THREAD

**Issue by Pocketkid2** [SpongePowered/SpongeForge#534]
I have an event listener that is detecting a sign with a specific line of text. I am cancelling the event so that when they try to left click (break) the sign it does not break but instead has an action. It works, but after the first break, the sign text disappears to the client. I know this because if I continue to left click and try to break it, it doesn't break and instead shows the message that I clicked it. When I reconnect to the server the text comes back.

**Comment by Aaron1011** [comment]
@Pocketkid2: I can't seem to reproduce this. Can you try again with the latest SpongeForge?

**Comment by Aaron1011** [comment]
If you're still able to reproduce this using the latest (not the recommended build) of SpongeForge, then please re-open this issue.
