### ISSUE TITLE
WorldSavedData causes data corruption in mod

### ISSUE THREAD

**Issue by bentterp** [SpongePowered/SpongeForge#536]
Hi.

I have had problems with the Backpacks! mod when visiting the Nether, and investigations done together with the developer lead to this conclusion:

> Since WorldSavedData has been a built in Minecraft class since at least version 1.2 there is no reason for them to have made such a drastic change to how it behaves, especially since I can't find any reference to it being used by their plugin system.
>
> I suggest submitting a bug report to Spongeforge, with any luck they'll be able to fix it. In any case, they are changing a piece of core functionality that my mod has been using for the last 2 years, so there is no way for me to fix it.

What happens is that I get extra copies of the mod's datafiles in the Nether data folder,  which should not happen. Mod developer has confirmed that this happens when running with only Sponge and the Backpacks! mod, but not without Sponge.

What information can I provide that would make it easier to fix the issue?

Server is forge-1.8-11.14.4.1577 with mods:

BiomesOPlenty-1.8-3.0.0.1622-universal.jar
Dynmap-2.2-forge-1.8.0.jar
EssentialCmds-6.8c.jar
Morpheus-1.8-2.0.45.jar
MrCrayfishFurnitureModv3.6(1.8).jar
MrCrayfishKeyModv1.1(1.8).jar
PermissionsEx-Sponge-b107.jar
ProjectPortals-3.1.0-v0.8.30.jar
Ruins-1.8.jar
spongeforge-1.8-1577-3.1.0-BETA-1038.jar
Thaumcraft-1.8-5.0.3.jar
UpdateCheckerMod-1.8.jar
worldedit-forge-mc1.8-6.1.jar
zz-backpacks_1.8_3.0.8beta.jar

Yes I know it's not this week's latest Sponge release, but it's hard getting all mods in sync with the same forge release..... will continue striving though, as it would be great to move to 1.8.9.

regards,
  Bent

**Comment by Aaron1011** [comment]
@bentterp: Unfortunately, we're no longer supporting Sponge for 1.8.0. Because of this, there are many bugs which have only been fixed in SpongeForge for 1.8.9

**Comment by bloodmc** [comment]
@bentterp All the developer has to do is use the following to solve this problem

https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/common/DimensionManager.java#L412

The mod is, most likely, grabbing the save handler from the world which is causing the data to be saved with it. This happens since we use a separate save handler per world to support multi-world plugins.

**Comment by bentterp** [comment]
@Aaron1011 I accept that position - Sponge is bleeding edge and beta with more focus on driving the project forward than maintaining legacy compatibility. Fair enough.

@bloodmc Thank you for that suggestion, and I have of course forwarded your information to the mod developer. Also means that merely upgrading the mod won't solve the underlying issue.
