### ISSUE TITLE
WitherSkull, SmallFireball, and LargeFireball launched incorrectly

### ISSUE THREAD

**Issue by SocraticPhoenix** [SpongePowered/SpongeForge#539]
**Tested On Build 1151**

Simply put, whenever launchProjectile is called (at least on a player), every projectile _other_ than arrows launch from the player's feet rather than the player's head. In addition, small fireballs are launched in an extremely erratic fashion, not going anywhere near the player's aim, half the time.

**Comment by bloodmc** [comment]
@SocraticPhoenix is this with SpongeForge installed on client? If so try removing it and test again.

**Comment by SocraticPhoenix** [comment]
@bloodmc 
At the time I believe it was on the server.

**Comment by modwizcode** [comment]
I suspect the source of this error is the `ProjectileLogic` class SpongeCommon uses that causes the linked issue. This is almost certainly not a SpongeForge specific issue.

**Comment by simon816** [comment]
Note that the position and velocity of a projectile when calling `launchProjectile` is calculated to be a sensible default. If you'd like more control over the position etc. then you can use `setLocation`, `setVelocity` etc for adjustment.

Most projectiles seem to work OK. I have fixed WitherSkull and the two fireballs not spawning at the player head. I have hopefully fixed SmallFireball's odd behavior, but also I noticed how the vanilla code for creating fireballs differs quite a bit from `EntityThrowable` for example, notably the randomization is greater. (Some projectiles have a slight randomization on their exact angle).
