### ISSUE TITLE
Thaumcraft 5 Error with Sponge

### ISSUE THREAD

**Issue by seanamor** [SpongePowered/SpongeForge#540]
Minecraft Forge: 11.15.1.1732
SpongeForge: DEV
SpongeAPI: 3.1.0-SNAPSHOT-4c0d27c
Minecraft: 1.8.9
SpongeForge

A couple errors listed below first of which:
http://hastebin.com/mexokuqabe.m
Secondly I am not sure if this one is because im in creative, without the proper research to be doing this. But I get an autocaster from creative, then try adding a focus to it, I have tried pech and lightning so far and both add the focus, but crash the server:
http://hastebin.com/okumobehes.avrasm

Azanar Commented on this on his git page with this:
"Azanor commented 7 hours ago
Those are both sponge related errors - nothing directly TC related in either of them."

**Comment by gabizou** [comment]
The first paste isn't actually an error, it's just a notification of fallback. It's to be expected when certain corner cases have to be resolved manually. The system otherwise will work fine regardless.

The second, I'm not quite sure how it's SpongeForge's fault since that error is only partially included, if you can provide a more complete log, that'd help a lot.

**Comment by seanamor** [comment]
Thanks I will do so asap

**Comment by seanamor** [comment]
http://hastebin.com/uyuvewinaf.avrasm

**Comment by gabizou** [comment]
@Mumfrey from the last stack trace, `MinecraftFabric` is throwing the exception due to a null check, not sure where it's getting the null from, but likely because the inventory slot isn't officially supported yet.

**Comment by seanamor** [comment]
Ill report any other bugs I find, I am testing SpongeForge Beta in a server setting. Thanks for accepting this report.

**Comment by hunter688** [comment]
I have similar crashreport:

 http://pastebin.com/7rLqimQV

**Comment by Mumfrey** [comment]
I don't have an easy way of testing this since I've not used thaum craft, can one of you guys test whether the changes in SpongePowered/SpongeCommon@83cab0dfb2f7bb90242c051b809acceeb0f6d52e have addressed the issue.

**Comment by hunter688** [comment]
Tested, looks like problem solved, thanks.

**Comment by seanamor** [comment]
Does this mean there is an updated spongeforge build with the bug fixed? If so where might we find this? I can test it out as well.

**Comment by Mumfrey** [comment]
Ok I'm considering this resolved for now then.

**Comment by seanamor** [comment]
This is indeed resolved, thanks!
