### ISSUE TITLE
Incompatibility with Thaumcraft Thaumic Shielding

### ISSUE THREAD

**Issue by Quiiliitiila** [SpongePowered/SpongeForge#545]
I originally posted this in the wrong issue section of Sponge, so I've move to here. 

Essentially Sponge appears to not be playing well with Thaumcraft's Runic Shielding. Runic shielding created something akin to additional HP which (if everything is working correctly) should be drawn from first before the players normal hearts are damaged. For whatever reason Sponge seems to be bypassing the additional HP and taking directly from the vanilla HP bar.

I've established that the issue appears to lie with Sponge, as when sponge is absent there are no issues to be found.

**Comment by Quiiliitiila** [comment]
I did a bit more testing with Golden Apples. Golden apples give a spell effect called "absorption" which functions almost identically to Runic Shielding. The extra health from the golden apples works as intended.

Perhaps it has something to do with the Thaumcraft add-on called Baubles? I'm not sure if anyone on the Sponge team is familiar with it but I'll do my best to explain. Baubles adds the functionality to equip various extra items like rings, belts and amulets. It's accessed through a special menu and the items are equipped through that portal. Perhaps Sponge isn't realizing this extra functionality exists? 

It's a half baked theory, because I'm pretty sure some other things through Baubles have worked for me but I can't be certain. I'm quite at a loss.

**Comment by Aaron1011** [comment]
After looking at this, the issue seems to be that Sponge's damage handling only adds the absorption modifier if the Absorption potion effect is active on the entity being damaged. Since Thaumcraft's runic shielding just applies absorption without the potion effect, Sponge skips over it.

@gabizou can comment more on this.
