### ISSUE TITLE
thaumcraft cause sponge server slower

### ISSUE THREAD

**Issue by gxy17886** [SpongePowered/SpongeForge#546]
Add thaumcraft mod the sponge generated map slow. But single game generating speed all normal. For example, server generates a new world. 
Obviously from the console can see the map to generate slow.
The generation time from the original half a minute extended to 5 minutes. 
Server players are often in the run chart when found the void boundary (map does not load the way), Delete thaumcraft will no longer appear that the. 

In addition, some thaumcraft addons will Cause your server to close ,some is ok , if I need to submit crash documents, please and I said, I will submit a new issue.

**Comment by Aaron1011** [comment]
@gxy17886: It would be helpful for you to submit separate issues for those other crashes (provided they only happen with Sponge installed).

As for the main issue, you may want to wait until https://github.com/SpongePowered/SpongeCommon/pull/502 is merged, as it contains some overarching changes which may resolve this issue.

**Comment by bloodmc** [comment]
@gxy17886 I just tested running the latest Thaumcraft/SpongeForge and world generation was normal on both server/client. Are you using an old 1.8 build of SpongeForge? Please provide the server log and any other relevant info.

**Comment by bloodmc** [comment]
This issue should be resolved in build 1162.
