### ISSUE TITLE
output of /sponge version - missing build number

### ISSUE THREAD

**Issue by hunter688** [SpongePowered/SpongeForge#555]
I think word DEV would be build number:

> sponge version
[09:49:21] [Server thread/INFO]: SpongeForge
    Minecraft: 1.8.9
    SpongeAPI: 3.1.0-SNAPSHOT-ecd761a
    SpongeForge: DEV
    Minecraft Forge: 11.15.1.1762

**Comment by Minecrell** [comment]
Do you have any other mode installed?

**Comment by hunter688** [comment]
yes

**Comment by Minecrell** [comment]
Can you list them here?

**Comment by hunter688** [comment]
alchemycraft2
ArchitectureCraft-1.3.1-mc1.8.9.jar
BaseMetals-1.6.1.jar
BetterPvP-1.0.jar
BiomesOPlenty-1.8.9-3.0.0.1886-universal.jar
Botania.r1.8-248-MC1.8-0.6.1.jar
buildcraft-7.2.0-pre12.jar
CraftTweaker-Customized-1.8.8-3.0.1.jar
CustomNpcs_1.8.9_beta(21feb16).jar
ElectricAdvantage-1.1.0.jar
EssentialCmds-7.4d.jar
fancy_fish_mod_1.8.9_beta_2016.01.26.jar
FGTweaks-1.0.jar
FoxCore-v0.7.0-74-SNAPSHOT-server.jar
FoxGuard-v0.17.0-210-SNAPSHOT.jar
Chameleon-1.8.9-0.2.1.jar
Chisel-MC1.8.9-0.0.2.6.jar
chiselsandbits-mc1.8.9-v1.8.2.jar
intangible-1.8.9-0.0.23.jar
Keys-1.0.0.jar
malisiscore-1.8.9-2.0.2.jar
malisisdoors-1.8.9-3.0.1.jar
MCMultiPart-1.0.6-universal.jar
mineralogy-2.6.0.jar
ModPatcher.jlib
ModTweaker2-1.0.0.jar
NameAPI-0.2.7.jar
permissionsex-sponge-2.0-SNAPSHOT.jar
PowerAdvantage-1.4.4.jar
Prism-3.0.0-beta1-1-ga202db1-all.jar
sem-mc1_8_9-1.4.3.jar
spongeforge-1.8.9-1762-3.1.0-BETA-1169.jar
SteamAdvantage-1.5.1.jar
StorageDrawers-1.8.9-2.4.0.jar
storagesilo-1.8.9-1.2.2b.jar
Thaumcraft-1.8.9-5.1.6.jar
worldedit-forge-mc1.8.9-6.1.1.jar

**Comment by hunter688** [comment]
tested build 1190, looks good:

> sponge version
[07:54:54] [Server thread/INFO]: SpongeForge
    Minecraft: 1.8.9
    SpongeAPI: 4.1.0-SNAPSHOT-7a32996
    SpongeForge: 1.8.9-1763-4.1.0-BETA-1190
    Minecraft Forge: 11.15.1.1763

**Comment by Minecrell** [comment]
Wasn't fixed. Completely depends on which mods you have installed (because it is caused by the mcmod.info conflicting from other coremods).

**Comment by hunter688** [comment]
ok, sorry

**Comment by Minecrell** [comment]
No need to be sorry, you didn't know that :P

**Comment by hunter688** [comment]
During some testing (removing mods step by step) found one mod which causing issue. Try with ic2, for example build 239.

http://jenkins.ic2.player.to/job/IC2_18/239/artifact/build/libs/industrialcraft-2-2.3.239-ex18.jar

You can debug...

**Comment by Zidane** [comment]
@Minecrell 

Status update.

**Comment by Minecrell** [comment]
@Zidane Not working on this, it's caused by resource conflicts causing SF to load the wrong `mcmod.info` (e.g. from another coremod). Not sure how to fix it, we might need to rename AF's `mcmod.info` file so it is unique or open it differently.

**Comment by kashike** [comment]
Do what the `MCP` mod does (`mcpmod.info`), create `spongemod.info`?

**Comment by JBYoshi** [comment]
https://github.com/MinecraftForge/MinecraftForge/blob/4248dbc71d77a8288029a7d4612d7a13eaef04f7/src/main/java/net/minecraftforge/fml/common/Loader.java#L207
```java
mcp = new MCPDummyContainer(MetadataCollection.from(getClass().getResourceAsStream("/mcpmod.info"), "MCP").getMetadataForId("mcp", null));
```
