### ISSUE TITLE
console errors when placing Buildcraft Quarry

### ISSUE THREAD

**Issue by hunter688** [SpongePowered/SpongeForge#557]
http://pastebin.com/NhHtftxg

**Comment by gabizou** [comment]
@hunter688 can you re-test with the very latest ci build of Buildcraft? If it is already the latest, it's more of a Buildcraft issue where a null is being passed around.

**Comment by gabizou** [comment]
Just pinging @AlexIIL for confirmation.

**Comment by Aaron1011** [comment]
I've opened an issue on BuildCraft here: https://github.com/BuildCraft/BuildCraft/issues/3213.

**Comment by AlexIIL** [comment]
The fix will be in pre13.

**Comment by gabizou** [comment]
Many thanks @AlexIIL.

**Comment by AlexIIL** [comment]
Thanks for alerting me to where the problem was :) (I've been seeing this for a while now and I had no idea what was causing it :/)
