### ISSUE TITLE
SpongeForge shuts down with no error message when running in IntelliJ

### ISSUE THREAD

**Issue by AGuyWhoSkis** [SpongePowered/SpongeForge#561]
IntelliJ log: http://hastebin.com/ojamocateb.txt
Screenshot of project: http://i.imgur.com/EinxfYq.png
Screenshot of run configuration: http://i.imgur.com/QFrCDsQ.png

Running IntelliJ 15.0.4 on Windows 10

The Mixin box appears and 5-15 seconds later the program exits.

**Comment by simon816** [comment]
Try cleaning an rebuilding the gradle files. On the command line: `gradle clean cleanIdea setupDecompWorkspace idea`

**Comment by AGuyWhoSkis** [comment]
That fixed it! Thank you :)
