### ISSUE TITLE
java.lang.NullPointerException: Exception while ticking a block of fire

### ISSUE THREAD

**Issue by AuricPolaris** [SpongePowered/SpongeForge#564]
Server Crash Log: http://pastebin.com/4pbqebZN

Sponge Version: spongeforge-1.8.9-1763-3.1.0-BETA-1179 (latest as of this post)

Forge Version: forge-1.8.9-11.15.1.1763-universal

Description:

A fire block on netherrack in the overworld crashed a server upon being ticked. Launching the server again and removing the fire block by hand was possible. Not entirely sure what else to report.

**Comment by Aaron1011** [comment]
@AuricPolaris: Sorry for the extremely long delay in getting to this. Can you still reproduce this?

**Comment by simon816** [comment]
There is an invalid item drop being created in the world, likely one of the many mods you have there is causing the problem.
If this issue is still reproducible, it would be great if you could remove mods until the crash no longer occurs. Then we can investigate further with sponge and that mod.

**Comment by Zidane** [comment]
Closing until we receive further feedback.
