### ISSUE TITLE
"Large" CPU usage by sponge thread process causing possible timeouts

### ISSUE THREAD

**Issue by AuricPolaris** [SpongePowered/SpongeForge#565]
Image of a warmroast189 CPU profile during server hanging: http://imgur.com/RmUa3l3 and http://imgur.com/cYV5re8

Sponge Version: spongeforge-1.8.9-1763-3.1.0-BETA-1179 (latest as of this post)

Forge Version: forge-1.8.9-11.15.1.1763-universal

Description:

The server will hang with sponge processes taking up a large portion of the CPU. See the above image for this. The server does not crash though, but does not allow players to connect without timing out. Let me know if you need anything else! :)

**Comment by XPownage** [comment]
Have the same problem as well, I have tried a decent amounts of versions and no luck so far so i'm guessing this problem has been around for a while...

**Comment by Zidane** [comment]
https://github.com/SpongePowered/SpongeCommon/pull/502

We're aware of the issues and are working to do an overhaul of the system to address this.
