### ISSUE TITLE
Extreme TPS lag with FTB Unstable 1.8

### ISSUE THREAD

**Issue by killerjerick** [SpongePowered/SpongeForge#569]
The original thread is here: https://forums.spongepowered.org/t/having-issues-with-tps/11755

However mumfrey has asked me to put it here, so here goes

I'm using FTB Unstable 1.8 - 3.0.37
I'm also using SpongeForge 4.1.0 BETA 1190 with forge 1763

The problem occurs whenever sponge is installed to the server, the average TPS when rendering chunks (and sometimes whilst not) drops from 18-20 to 3-7, this only happens when I install sponge on the server and when I remove it, the tps is fine.

I'm using the following plugins with sponge:
PermissionsEx-Sponge
EssentialCmds-7.7

And I'm using the following mods:
![mods](http://i.imgur.com/aw2qqyP.png)

I'm aware that some of these mods are clientsided (need to go through them again and remove them)
However the server launches fine and has no issues.

Any help would be greatly appretiated

**Comment by bloodmc** [comment]
@killerjerick I'll look into it tomorrow.

**Comment by bloodmc** [comment]
@killerjerick Please install warmroast and post your sample results when the lag occurs.

https://github.com/sk89q/WarmRoast

**Comment by killerjerick** [comment]
Unfortunately I'm unable to install that as I'm using a host (not a vps) also, the lag occurs nearly anywhere in the world, sorry for not being much help, I'll probably try it out on my own machine and see if I can find which mod is doing it, thanks anyway :)

**Comment by bloodmc** [comment]
@killerjerick I just tested it on my machine and had 0 lag running around world with sponge installed.
Note: I'm testing with a fresh install of FTB unstable. I will need your world to do a better test.

**Comment by killerjerick** [comment]
It might be worth noting, it lags a lot more if there are 2 people connected, not sure if that helps any, but I'll upload my world to dropbox now

**Comment by bloodmc** [comment]
@killerjerick give me the location where it lags the most

**Comment by killerjerick** [comment]
-50 100 291
  X    Y    Z

**Comment by killerjerick** [comment]
around that entire mountain is where I first noticed the extreme TPS issues

**Comment by killerjerick** [comment]
So have you figured anything out yet? Or is it just something wrong with my installation?

**Comment by killerjerick** [comment]
Have there been any updates that improve performance? Or am I still stuck, sorry for seeming impatient

**Comment by bloodmc** [comment]
I am unable to produce any issues on my end. Please test build 1200 and if lag still occurs, you will have to figure out a way to get WarmRoast setup.

**Comment by killerjerick** [comment]
Just tested it, random lag spike every 30 seconds - 1 minute, I can't setup WarmRoast, unfortunately, I have no idea what it is, I'll try removing PEX and Essentialcmds and see if that helps in any way.

**Comment by killerjerick** [comment]
Well, I just removed both PEX and Essentialcmds and the lag is gone -.- I'm very sorry for wasting your time and I'll need to go figure out which one is lagging and post it on the respective github, thanks a tonne for helping, and again, sorry for wasting your time.

**Comment by Minecrell** [comment]
You can try disabling EssentialsCmds's inventory saving (go to the EssentialsCmds config dir -> `data` -> `world.conf` and set `separate` to `false`), this is what was causing major lag when changing the held item on the SCS recently, might be the same for you.

**Comment by killerjerick** [comment]
Thanks minecrell, I will try that and let you know :+1:

**Comment by killerjerick** [comment]
That fixed it completely, thank you so much, I can't believe it's such a simple fix! One more thing before I go, what config option keeps the inventory when you die (and makes the items "0" quantity) I've looked but I can't see anything referencing this, if you don't know, that's fine but thanks :)

**Comment by Minecrell** [comment]
@killerjerick 
Not sure but @hsyyid might be able to help you. :)

**Comment by killerjerick** [comment]
Alright thank you!

**Comment by hsyyid** [comment]
@killerjerick Are you referring to keep inventory?

**Comment by Deamon5550** [comment]
Please take this discussion to a relevant issue.
