### ISSUE TITLE
Crash with Player API

### ISSUE THREAD

**Issue by Leeo97one** [SpongePowered/SpongeForge#570]
The server crash at startup when I add [Player API](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1277996) and SpongeForge. There is no problem without SpongeForge. 

fml-server-latest.log: http://pastebin.com/NQXPSmkf
Ubuntu Server 14.04.4 LTS
Java 8 (OpenJDK)
SpongeForge 3.1.0-BETA-1181 (and 4.1.0-BETA-1190)
Forge 11.15.1.1764
Player API 1.0

Sould I ask the developper of Player API?

**Comment by Mumfrey** [comment]
I see the problem, PlayerAPI is applying a transformer which seems to physcially remove the method used [by this injector](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/mixin/core/entity/player/MixinEntityPlayerMP.java#L163) and replace it with various proxies (`localOnDeath`, `realOnDeath`, `superOnDeath`). At least this is what I can glean from looking at the transformer code.

The transformer itself looks like it's generated/templated *(note to sponge devs reading this: the source code is in the zip file download for the mod)* but the template doesn't appear to be included in the source zip so it's difficult to tell what the desired end result is.

**Comment by Leeo97one** [comment]
Thanks for clarify this ^_^
So, should I warn [Divisor](http://www.minecraftforum.net/members/Divisor)?

**Comment by Leeo97one** [comment]
Any news?

**Comment by gabizou** [comment]
@Leeo97one did you already speak to Divisor? Otherwise, there's really nothing we can do since their transformers are clearing the methods that we inject into to perform our logic.

**Comment by Leeo97one** [comment]
OK, I've informed him: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1277996-player-api?comment=1750

**Comment by gabizou** [comment]
There's nothing we can do on our end as PlayerAPI is simply overwriting the entire method.
