### ISSUE TITLE
NullPointerException when trying to access Asset in SpongeForge

### ISSUE THREAD

**Issue by VcSaJen** [SpongePowered/SpongeForge#571]
When trying to access asset in SpongeForge 1.8.9-1763-4.1.0-BETA-1193 (forge-1.8.9-11.15.1.1763-universal), also in SpongeForge 4.1.0-SNAPSHOT-7e39463, server throws NullPointerException.

I'm accessing it like that: `plugin.getAsset(name).get()`, where `plugin` is:

    @Inject
    PluginContainer plugin;

Log: http://pastebin.com/WgsAi7zQ

This error is not present in SpongeForge 4.0.1 and SpongeVanilla 1.8.9-4.1.0-BETA-262.

**Comment by windy1** [comment]
Fixed in https://github.com/SpongePowered/SpongeForge/commit/026cbbe1de855dc1a09e15330c2e4cbef9e6b564
