### ISSUE TITLE
DamageEntityEvent not firing for Armor Stands

### ISSUE THREAD

**Issue by clucky** [SpongePowered/SpongeForge#573]
I have applied a listener to my plugin for the DamageEntityEvent event, and whenever an armor stand is "damaged", the event is not fired. Is this a bug, or an expected result? If it is not a bug, what event should be used in its place to cancel the Armor Stand from being broken?

**Comment by modwizcode** [comment]
What are you considering "damage" to an armor stand? Anything that would cause Minecraft to break it?

**Comment by clucky** [comment]
Yes.

**Comment by clucky** [comment]
@modwizcode Yes

**Comment by modwizcode** [comment]
Ok. I'll give this a look. Setting the Keys.INVISIBLE to true will set the stands to be unbreakable, but also is fairly tied into them being invisible. This might be worth separating. Thoughts @gabizou?

**Comment by bloodmc** [comment]
Use InteractEntityEvent.Primary for armor stands.
