### ISSUE TITLE
Custom event implementing MessageChannelEvent.Chat doesn't work.

### ISSUE THREAD

**Issue by VcSaJen** [SpongePowered/SpongeForge#574]
[Docs](https://docs.spongepowered.org/en/plugin/event/custom.html) says we can implement custom events not only from Event, but also from existing events.
I wrote [MutateMessageChannelChatEvent](https://github.com/VcSaJen/MutateMe/blob/master/src/main/java/com/vcsajen/mutateme/MutateMessageChannelChatEvent.java) implementing MessageChannelEvent.Chat, but when I fire it, SpongeForge throws an exception: [log](http://pastebin.com/i3KSNSmd).

SpongeForge version: 7ea7b81 .

It works as expected in SpongeVanilla without any exceptions.

**Comment by windy1** [comment]
Cannot reproduce. Make sure you extend `AbstractMessageEvent` as well as implementing `MessageChannelEvent.Chat` and you cannot set the original message to null, that's not allowed.
