### ISSUE TITLE
Poor/Sponge 

### ISSUE THREAD

**Issue by seanamor** [SpongePowered/SpongeForge#575]
Minecraft Forge: 11.15.1.1764
SpongeForge: DEV
SpongeAPI: 4.1.0-SNAPSHOT-b29342e
Minecraft: 1.8.9

http://hastebin.com/ewacifahos.avrasm

**Comment by liach** [comment]
report to http://github.com/lapisblue/pore/issues/new please. not a sponge bug.

**Comment by gabizou** [comment]
I'm pretty sure that Pore is a bit out of date with regards to the API and implementation. Closing as you should report it to Pore instead.
