### ISSUE TITLE
problem with mod MalisisDoors and Keys plugin

### ISSUE THREAD

**Issue by hunter688** [SpongePowered/SpongeForge#579]
Im experiencing problem with installed mod Malisis Doors - its very good mod and also need plugin for locking Chests and others blocks. But these two cannot coexist together. There are bug reports:

https://github.com/prism/Keys/issues/13

https://github.com/Ordinastie/MalisisDoors/issues/78

Can someone help me with this issue? What is exactly problem? Thanks a lot.

**Comment by Aaron1011** [comment]
@hunter688: Does this happen when you attempt to protect a block from MalasisDoors?

**Comment by hunter688** [comment]
NPE during server start, then Keys plugin not worked.

When set in the config of malisis doors B:config.modifyVanillaDoors=false

everything is ok and works

**Comment by hunter688** [comment]
Im not attemting to protect malisis doors blocks...

**Comment by simon816** [comment]
It's NPEing at this line: [`MixinBlock:90`](https://github.com/SpongePowered/SpongeCommon/blob/5549df9258046aa019762df38fb072d1ee0f94a7/src/main/java/org/spongepowered/common/mixin/core/block/MixinBlock.java#L90) which means the `ResourceLocation` is probably null.

**Comment by simon816** [comment]
It looks like MalisisDoors is replacing vanilla items, which is likely the problem
https://github.com/Ordinastie/MalisisDoors/blob/1.8.9/src/main/java/net/malisis/doors/Registers.java#L130-L137
It could be that the `BlockTypeRegistryModule` isn't handling blocks being replaced by other mods

**Comment by Aaron1011** [comment]
This issue is due to MalisisDoors replacing several Vanilla blocks/items during FML's `PREINIT` state. Due to the fact that Sponge maps its psuedo-enum static fields before any mods are loaded, plugins aren't able to access the replacement block/item.

Until MalisisDoors changes how they replace Vanilla blocks/items, there's unfortunately nothing Sponge can do about this.
