### ISSUE TITLE
CompletableFuture#get NPE | Internal server error

### ISSUE THREAD

**Issue by Favorlock** [SpongePowered/SpongeForge#581]
Minecraft: 1.8.9
SpongeAPI: 4.1.0-SNAPSHOT-dd7e8e2
SpongeForge: 1.8.9-1763-4.1.0-BETA-1219
Minecraft Forge: 11.15.1.1764

Steps to recreate:

1. Create a fresh instance of a server.
2. Start the server and let configs/worlds generate.
3. Login and set your gamemode to 1.
4. Place a player skull down.

I've provided the stacktrace and console output as well as the code triggering the NPE and internal server error.

Stacktrace: http://pastebin.com/v0ajDCvx
Code: http://pastebin.com/hvSmdksR
Console output after logging out and attempting to log back in: http://pastebin.com/rN7nu12p
Console output on shutdown: http://pastebin.com/W1wu0UHE

If you restart the server after triggering the error it never seems to happen again, at least not from what I could tell.

**Comment by Favorlock** [comment]
Going to go ahead and tag @Aaron1011 as he asked me to submit the issue so he could take a look tomorrow.

I'm also going to go ahead and mention that the code above is not applying the textures to the skull. Aaron was saying that he may have discovered some bugs with texture loading for GameProfile instnaces.

**Comment by gabizou** [comment]
@Aaron1011 you said so yourself, anything to go on?

**Comment by Aaron1011** [comment]
`GameProfileManager#fill` runs asynchronously, so you'll need to call `get` on it to ensure that the `GameProfile` is actually filled.

If this issue persists, please re-open this issue.
