### ISSUE TITLE
Error in console when using /help

### ISSUE THREAD

**Issue by prolix** [SpongePowered/SpongeForge#582]
I get this error in server console while attempting to using the /help command

https://gist.github.com/prolix/8ca785ff2e854825f236

Clientside same error shows while hovering over response - "Error occurred while executing command: id"

forge version forge-1.8.9-11.15.1.1765-universal
sponge version  spongeforge-1.8.9-1763-4.1.0-BETA-1219
mods installed - https://gist.github.com/prolix/758cc1cc96b1a99422ec

**Comment by Aaron1011** [comment]
@prolix: I can't seem to reproduce this. Do you have any mods installed?

**Comment by prolix** [comment]
91 mods, https://gist.github.com/prolix/758cc1cc96b1a99422ec

**Comment by Aaron1011** [comment]
@prolix: Can you give me a link to the modpack you're using, or some way to download the correct version of all of those mods?

**Comment by prolix** [comment]
Sorry for not listing mods before and giving light info, here is a thread to all the info on the modpack

https://forums.joe.to/viewtopic.php?f=226&t=73672

**Comment by Aaron1011** [comment]
@prolix: No problem :). Btw, this is almost certainly an issue with one of those mods incorrectly implementing `ICommand`. I'll be reporting an issue to the developers once I track it down.

**Comment by prolix** [comment]
Ok thanks a lot! Give it a bit to download the pack as i'm fixing a upload corruption issue. Will post when it's ready

**Comment by prolix** [comment]
Pack is updated and stable, try giving it a test now. My server info is in the forum thread for the pack

**Comment by Aaron1011** [comment]
@prolix: I'm trying the latest version, but it's hanging on a line about missing textures, when the client is starting.

**Comment by prolix** [comment]
Make sure you give the launcher more than 1.5GB of memory allocation or it
likes to hang on startup.

On Fri, Mar 25, 2016 at 5:01 PM, Aaron Hill <notifications@github.com>
wrote:

> @prolix <https://github.com/prolix>: I'm trying the latest version, but
> it's hanging on a line about missing textures, when the client is starting.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/SpongePowered/SpongeForge/issues/582#issuecomment-201500215>
>



-- 
Nic "prolix" Haney
Senior Administrator for www.joe.to - A social community since 1996

______________________________________
[image: Inline image 6]- prolix@joe.to <prolix@gmail.com>
[image: Inline image 3] - prolixj2
[image: Inline image 4] - prolixj2
[image: Inline image 5] http://steamcommunity.com/id/prolixj2
[image: Inline image 1][image: Inline image 2]

**Comment by Aaron1011** [comment]
@prolix: Thanks, allocating more ram fixed it :)

**Comment by prolix** [comment]
@Aaron1011: No problem! If you whisper me your UUID/IGN I'll PM you an IP for a whitelisted server

**Comment by Aaron1011** [comment]
@prolix: This should be fixed in the latest build of SpongeForge.
