### ISSUE TITLE
BlockRay Filters not working very well for BlockTypes.SKULL

### ISSUE THREAD

**Issue by Favorlock** [SpongePowered/SpongeForge#584]
This is the code that I am using for detecting if a player is looking at a skull: http://pastebin.com/2TFxaq59

What I'm expecting is that if the player is directly looking at a skull the skull should trigger a hit, but that is not the case most of the time. I generally have to be right next to the skull for it to even trigger a hit and even then it doesn't work some times.

If I am going about this the wrong way please inform me of a proper way to detect a skull a player is looking at, but if this should work as I expect then please take a look and see about improving support for skulls.

**Comment by Minecrell** [comment]
Block ray will return the last block that matches the filter, AIR doesn't match your filter, therefore it will only work if there is no other block between the skull and the player. You should use a `onlyAirFilter` together with a `maxDistanceFilter` of 1, then that will return the first block after the filter stops matching, so actually the block the player is looking at. Then just check if it's a skull.

**Comment by DDoS** [comment]
It's not maxDistance but continueAfter. Also skulls are partial blocks which is not really supported right now. The whole block bounding box is used, not the skull one.

**Comment by Minecrell** [comment]
Fail, that's what I wanted to write :P

**Comment by Favorlock** [comment]
Looks like your suggestion does the job @Minecrell The only explanations on the forum don't mention using continueAfterFilter.

Thanks
