### ISSUE TITLE
Cannot Cancel SendCommandEvent

### ISSUE THREAD

**Issue by Favorlock** [SpongePowered/SpongeForge#587]
Here is the code I am using: http://pastebin.com/xb39gkjC

I've verified that the setCancelled method is being trigger with logging, so the event should be cancelled, but the command is still executing.

**Comment by simon816** [comment]
Just tested with the following code and cancellation worked as expected. Are you still able to reproduce this?
```java
@Listener
public void onSendCommandEvent(SendCommandEvent e) {
    e.setCancelled(true);
}
```
