### ISSUE TITLE
[4.1.0] Compatibility issue with Agricraft

### ISSUE THREAD

**Issue by Xiaminou** [SpongePowered/SpongeForge#588]
Agricraft is incompatible with SpongeForge.
(reported on both githubs)

Crash Report: http://pastebin.com/AZxAe9uV

**Comment by Deamon5550** [comment]
For reference the Agricraft issue: InfinityRaider/AgriCraft#601

**Comment by InfinityRaider** [comment]
Issue can be closed here, error is entirely on our side.
