### ISSUE TITLE
BlockRedstoneWire server crash after timeout

### ISSUE THREAD

**Issue by KumaGetsu** [SpongePowered/SpongeForge#594]
SpongeForge 4.1.0-BETA-1229

A player on my server created a redstone clock with hoppers. When the chunk was loaded it caused the server to timeout and crash.

Crash Log:
http://paste.ubuntu.com/15579395/

**Comment by Aaron1011** [comment]
@KumaGetsu: This was caused by `UserDiscoverer` failing to cache user instances, and repeatedly triggering a disk lookup. It should be fixed in the latest SpongeForge.
