### ISSUE TITLE
Unable to launch

### ISSUE THREAD

**Issue by MrQwer** [SpongePowered/SpongeForge#595]
Hi !
I've downloaded 

Forge version: forge-1.8.9-11.15.1.1808-universal.jar 

Sponge version: spongeforge-1.8.9-1808-4.1.0-BETA-1230-dev.jar 

but when I want to start the server, it interrupts with an error: Unable to launch [...] Class not found [...] caused by: FMLSecurityManager -> http://pastebin.com/APrq5kRU
I thought, maybe it's the version so I tried it with an older version, but the same error apeared.
I hope you can help me.

**Comment by Minecrell** [comment]
Please post the full error.

**Comment by Minecrell** [comment]
You downloaded the wrong JAR, you need to download the main (Mod) JAR, not the dev JAR.
