### ISSUE TITLE
Opening CustomInventory doesn't work?

### ISSUE THREAD

**Issue by NiceDev** [SpongePowered/SpongeForge#597]
Hey!
When I try to open a simple inventory like this:
`        CustomInventory inventory = CustomInventory.builder().name(new FixedTranslation(TextColors.RED.getId() + "Test")).size(45).build();
        player.openInventory(inventory, null);`
it throws an exception:
`[14:29:50] [Server thread/ERROR] [Sponge]: Could not pass InteractBlockEvent$Secondary$Impl to org.spongepowered.mod.plugin.SpongeModPluginContainer@5782053d
java.lang.IllegalArgumentException: Could not find a Supplier for the provided class: org.spongepowered.api.item.inventory.custom.CustomInventory.Builder
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:125) ~[minecraft_server.1.8.9.jar:?]
        at org.spongepowered.common.registry.SpongeGameRegistry.createBuilder(SpongeGameRegistry.java:250) ~[SpongeGameRegistry.class:1.8.9-1808-4.1.0-BETA-1236]`

Is this a bug?

**Comment by Deamon5550** [comment]
Custom inventories aren't implemented yet so there is no builder for it to find.

**Comment by Zidane** [comment]
Closing this as custom inventories are in progress and there is an open PR available.
