### ISSUE TITLE
SpongeForge build 1232-1241 crash

### ISSUE THREAD

**Issue by StevenB83** [SpongePowered/SpongeForge#599]
Hi,

Using Forge build 1808 SpongeForge build 1232 through 1240 crash with the same error.
http://pastebin.com/vafJ3mM5

Build 1226 and 1231 works fine, haven't tested 1227-1230.

Regards,
Steven

Edit: This doesn't occur on new world generation, if you want me to test anything let me know.
Edit 2: 1241 crashes with the error mentioned in #598

**Comment by simon816** [comment]
The crash was hiding the actual error so if you have an issue again then re-open.
For the other issue, wait until #598 is resolved
