### ISSUE TITLE
Spongeforge and Agricraft 

### ISSUE THREAD

**Issue by dh47** [SpongePowered/SpongeForge#603]
@bloodmc requested me to make this ticket.

Hey guys trying to run Spongeforge but I'm getting a crash on start up running forge 1.8.9 1808 and with sponge 1249 what am I doing wrong. http://pastebin.com/xkTp6GxW

Error seems to be Agricraft removing it has allowed the server to start.

My gut said that mod because it caught my eye in the console. > http://pastebin.com/RGw9rF9s

**Comment by simon816** [comment]
Issue with Agricraft, see https://github.com/SpongePowered/SpongeForge/issues/588 and https://github.com/InfinityRaider/AgriCraft/issues/601
