### ISSUE TITLE
Items showing negative number

### ISSUE THREAD

**Issue by KumaGetsu** [SpongePowered/SpongeForge#604]
SpongeForge 4.1.0-BETA-1253

Plugin which takes an item away is causing the item to go negative instead of removing from inventory.

**Comment by ST-DDT** [comment]
Could you please post your code that is causing this issue?

**Comment by KumaGetsu** [comment]
It's not my plugin, here is the source. https://github.com/terrainwax/LootCrate/releases

**Comment by bloodmc** [comment]
Then post a ticket on his github. If he thinks its a bug on our end he can create the ticket. As of now this ticket is useless.

**Comment by KumaGetsu** [comment]
Without your pleasant response I wouldn't have had the suggestion to post a ticket on his github. You have made my ticket very useful, thank you.
