### ISSUE TITLE
spawn-protection behavior

### ISSUE THREAD

**Issue by hunter688** [SpongePowered/SpongeForge#605]
When set spawn-protection in the server.properties, expect vanilla behavior - protect only overworld.

Ok, there is another behavior, in the spongeforge is protected all dimensions. I've found permission:
_minecraft.spawn-protection.override_ but howto set to vanilla like? override only in the nether and the end. In this thread: https://forums.spongepowered.org/t/guide-pex-quick-command-reference/ is example howto add world specific permission:

_/pex user MoeBoy76 perm minecraft.command.kill 1 world=DIM-1_

but this does not work now, tried:

_pex group Default perm minecraft.spawn-protection.override 1 world=DIM-1_

Will be possible add for example:

_minecraft.spawn-protection.override.dim1_
_minecraft.spawn-protection.override.dim-1_

or something similar?

**Comment by hunter688** [comment]
found some related PR: https://github.com/SpongePowered/SpongeCommon/pull/128

**Comment by zml2008** [comment]
The command is `/pex group Default perm minecraft.spawn-protection.override true --context world=DIM-1`
