### ISSUE TITLE
BOP berrries crashes server

### ISSUE THREAD

**Issue by hunter688** [SpongePowered/SpongeForge#607]
When player collect and eat berries, server can crash.

I've created ticket at BOP, but they said its sponge problem.

See: https://github.com/Glitchfiend/BiomesOPlenty/issues/740

**Comment by Aaron1011** [comment]
@hunter688: Try updating to the latest SpongeForge - the issue should be fixed there.

**Comment by hunter688** [comment]
Ok I will try, then report, thanks.

**Comment by hunter688** [comment]
Looks like build 1262 fixed this issue. Thanks a lot!
