### ISSUE TITLE
an issue where EnderCore and Sponge don't seem to play nice. 

### ISSUE THREAD

**Issue by jpiermarini** [SpongePowered/SpongeForge#610]
Not sure if this has something to do with https://github.com/SpongePowered/SpongeForge/issues/511#issuecomment-209773409 but i did try the bootloader that was put out yesterday and I also tried renaming sponge as _sponge and endercore as zzzzzendercore and the issue still remains.   

What is happening is when endercore is present on the server permissionsex and essentialscmd stop working or loading all together. . and example is typing /pex user jpier99 info results in 

Server thread/INFO 04/14/2016 09:36:57
09:36:57Unknown command. Try /help for a list of commands

Here is a paste of my log file. https://paste.ee/p/rVF57

**Comment by Aaron1011** [comment]
@jpiermarini: I'm not actually sure what's causing this. What are the steps to reproduce it?

**Comment by rob5251** [comment]
Steps to reproduce is to just try loading up a SpongeForge server with EnderCore and the two Plugins (EssentialsCmds, PermissionsEx)

Then try to use commands from the two plugins, they will fail to work.
Running the command "/sponge plugins" will show the two plugins as if they loaded though.

**Comment by jpiermarini** [comment]
@Aaron1011, @rob5251   is correct loading up sponge permissionsEx, EssentialsCmds and Endercore will result in this issue happening. I'm running forge 1764 sponge 1218 and the latest versions of PermissionsEx, EssentialCmds, and EnderCore.

**Comment by Aaron1011** [comment]
@rob5251: I'm unable to reproduce this issue. I'm using EssentialCmds, PEX, and EnderZoo.

@jpiermarini: Can you try again with the latest SpongeForge?

**Comment by rob5251** [comment]
Still happening for me on latest version of SpongeForge (spongeforge-1.8.9-1808-4.1.0-BETA-1268)

I tried using the latest builds for EnderCore, EnderZoo, and EnderIO from the Jenkins repositories and the issue still persists.

Prism commands are the only ones that continue to work for me. PEX and EssentialsCmds get broken.

**Comment by jpiermarini** [comment]
@aaron1011 I've upsa

**Comment by jpiermarini** [comment]
Woops

**Comment by jpiermarini** [comment]
@aaron1011 I've updated to forge 1808 and the latest sponge anf still have the issue. You need to make sure to have endercore loaded in. No real need to load in enderio or enderzoo

**Comment by Aaron1011** [comment]
@jpiermarini: My bad - I had accidently used the EnderCore API jar the first time, and thought that it required EnderZoo or EnderIO to load. I've reproduced the issue, and I'm looking into it.

**Comment by Aaron1011** [comment]
@jpiermarini: The issue is in EnderCore. I've opened a PR to solve it: https://github.com/SleepyTrousers/EnderCore/pull/37

**Comment by Zidane** [comment]
Issue is on EnderCore's side. They'll need to issue a fix.
