### ISSUE TITLE
Repeater Crash

### ISSUE THREAD

**Issue by KumaGetsu** [SpongePowered/SpongeForge#611]
Player had a looping redstone setup with repeaters which caused the server to crash.

Crash Log:
http://paste.ubuntu.com/15883199/

**Comment by gabizou** [comment]
Could you provide the server log as well as the crash report? Also, any mods installed?

**Comment by simon816** [comment]
> WARNING: coremods are present:
  Java8CheckerCoremod (Pixelmon-1.8.9-4.2.3-universal.jar)
  SpongeCoremod (spongeforge-1.8.9-1808-4.1.0-BETA-1243.jar)

Likely caused by Pixelmon

**Comment by Aaron1011** [comment]
@simon816: Yes, pixelmon has a bad reputation for causing `ConcurrentModificationException`s.

**Comment by KumaGetsu** [comment]
Here's another ConcurrentModificationException which happened today along with the server log for when it happened.

Crash-Report: http://paste.ubuntu.com/15917141/
Server Log: http://paste.ubuntu.com/15917473/

**Comment by Zidane** [comment]
Issue with Pixelmon. Report it to them please.
