### ISSUE TITLE
Lag Spike Issues with Player Leaving and Joining

### ISSUE THREAD

**Issue by xChristopher210** [SpongePowered/SpongeForge#612]
When a player leaves and join there is a 3 - 5 second lag spike. I tested this out with clienthax MusicBox plugin. When someone leaves and joins the music stops. Then resumes at a fast pace. Nothing is in my console as from crashes. Just the regular information given when someone joins.

http://paste.ubuntu.com/15901697/

The issue seems to go on when someone leaves or join.

**Comment by bloodmc** [comment]
@xChristopher210 this isn't a sponge problem or else it would happen with only sponge. Remove all your plugins and mods then start adding 1 by 1 until you find the culprit.
