### ISSUE TITLE
SpongeForge的性能问题

### ISSUE THREAD

**Issue by yyeerai** [SpongePowered/SpongeForge#613]
中文：
1.8.9的forge性能很不好
加入的时候或者快速飞行的时候总是发生：
Can't keep up! Did the system time change, or is the server overloaded?
发生此信息的时候地图加载不出来要等待一段时间才能加载出来
以前的mcpc+ 和kc都没有这个问题
我认为是优化问题
运行的forge版本：forge-1.8.9-11.15.1.1855
运行的SpongeForge版本：spongeforge-1.8.9-1808-4.1.0-BETA-1276.jar
没有加任何插件和mod
服务器cpu：e5 v3
RAM :64g
ssd: 520g

English:
forge a very bad performance 1.8.9
Join or when fast when flying always happens:
Can not keep up! Did the system time change, or is the server overloaded?
When this information does not come out when the map loads to wait a while to load up
Previous mcpc+  and kc have not had this problem
I think the problem is to optimize
forge version running: forge-1.8.9-11.15.1.1855
SpongeForge running version: spongeforge-1.8.9-1808-4.1.0-BETA-1276.jar
Did not add any plug-ins and mod
Server cpu: e5 v3
RAM: 64g
ssd: 520g

English is not good, use the Google translation, I hope you can understand

**Comment by liach** [comment]
老兄等等，1.8.9暂时没有优化mod，SpongeForge并不像PaperSpigot一样有很多优化，虽然他们也在[加优化] (SpongePowered/SpongeCommon#621)。

You need to wait as there's not yet any performance mod for Minecraft 1.8.9. Unlike Paper, SpongeForge does not have a lot of optimizations, although they are [adding optimizations] (SpongePowered/SpongeCommon#621).

Better Translation: 
Minecraft Forge for Minecraft 1.8.9 has a very bad performance.
When the player joins or the player flies the console spams:

> Can not keep up! Did the system time change, or is the server overloaded?

When the server spams it will take a while to load the map.
This does not happen in MCPC+ or KCauldron.
I think this is related to optimizations.
Forge version: forge-1.8.9-11.15.1.1855
SpongeForge version: spongeforge-1.8.9-1808-4.1.0-BETA-127
Clean server without other plugins or mods.
Server cpu: e5 v3
RAM: 64G
ssd: 520G

> English is not good, use the Google translation, I hope you can understand

He's not good at English, and he's using the Google translation. He hopes that you can understand.

**Comment by bloodmc** [comment]
I'll work on fixing this soon. I'm aware of the issue as I've experienced it myself.

**Comment by liach** [comment]
@bloodmc Might this also be related to cause tracking refactor? Unfortunately it would not be available for 1.8.9.

**Comment by bloodmc** [comment]
@liach no the same issues occur.

**Comment by bloodmc** [comment]
@liach @yyeerai I'll be pushing a new build shortly with a few optimizations including an important bug fix to my entity activation patch which wasn't working correctly. You should see a big perf gain with a server like pixelmon.

**Comment by liach** [comment]
Thanks @bloodmc for adding optimizations, and also for porting GriefPreventions.

**Comment by yyeerai** [comment]
@bloodmc good job，To address performance issues, sponge will become very popular.

**Comment by bloodmc** [comment]
@liach @yyeerai I had to rewrite entity activation since it was broken. This delayed my release =). I'm just finishing up a collision performance patch then I'll be pushing it to master. Should be by the end of today.

Here is how the new entity-activation config looks

https://gist.github.com/bloodmc/e4c21dd343c6a2a2b01ad715f749ba66
