### ISSUE TITLE
InteractEntityEvent.Secondary Bug

### ISSUE THREAD

**Issue by DoomedScar** [SpongePowered/SpongeForge#615]
When I right click with a Water Bucket an entity, a Sheep for example, **InteractEntityEvent.Secondary** still runs when cancelled and the water is placed.

Canceling the **InteractBlockEvent.Secondary** event seems to work but of course only when the player right clicks a block.

_Output:
true
net.minecraft.item.ItemBucket@705dc1a6
Is Banned_

I'm using **SpongeForge 1.8.9 - 4.1.0-BETA-1285**.

```
	@Listener
	public void OnInteractEntityEventSecondary(InteractEntityEvent.Secondary event)
	{
    	Player player = event.getCause().first(Player.class).get();
    	player.sendMessage(Text.of("" + player.getItemInHand().isPresent()));
		if(!player.getItemInHand().isPresent()) return;

		ItemType type = player.getItemInHand().get().getItem();
    	player.sendMessage(Text.of("" + type));
		
		if(type != ItemTypes.LAVA_BUCKET && type != ItemTypes.WATER_BUCKET && type != ItemTypes.ICE) return;

    	player.sendMessage(Text.of("Is Banned"));
    	event.setCancelled(true);
	}
```

**Comment by bloodmc** [comment]
You need to cancel UseItemStackEvent for this case.

**Comment by DoomedScar** [comment]
@bloodmc UseItemStackEvent does not fire when right clicking with a Water Bucket
