### ISSUE TITLE
"./gradlew genIntelliJRuns" creates an incorrect configuration

### ISSUE THREAD

**Issue by MarkL4YG** [SpongePowered/SpongeForge#616]
Hey, as stated here [https://forums.spongepowered.org/t/error-spongecoremod/6145](url)
gradle is generating a configuration that's not working at least in IntelliJ 16.

The configuration sets "Use classpath of module" to "SpongeForge" (which does not have the gradleStart<Insert> classes)

If you change that option to "SpongeForge-main" (as one could guess should be the correct value) you get CnF for SpongeCoremod (which really does not exist in "main")

Only if you change it to "SpongeForge_java6" it runs correctly. (Misleading name here)

**Comment by Minecrell** [comment]
We have no control about the generated run configurations, this is handled completely by ForgeGradle which needs to be updated to generate them with the correct module. There is a PR at https://github.com/MinecraftForge/ForgeGradle/pull/351, but we can't do anything to fix this until @AbrarSyed merges it.
