### ISSUE TITLE
Entity Crash

### ISSUE THREAD

**Issue by KumaGetsu** [SpongePowered/SpongeForge#619]
Just updated from Build 1298 to 1302 and my server is now getting these frequent crashes every time someone loads the chunk.

Crash-Report:
http://paste.ubuntu.com/16151361/

**Comment by kinggoesgaming** [comment]
I think this a Pixelmon issue afaik 
`Entity EntityPixelmon['Eevee'/246, l='world', x=-641.00, y=69.00, z=-2328.00] already spawned in the world!`

**Comment by KumaGetsu** [comment]
Yeah, it's definitely caused by a pixelmon thing. But this only started after updating SpongeForge.

**Comment by KumaGetsu** [comment]
Reverting the SpongeForge to 1298 fixed it.

**Comment by kinggoesgaming** [comment]
You might want to contact them and double check if its something they can fix..

**Comment by kenzierocks** [comment]
Seems like the check that was added to protect plugin developers is revealing bugs in other mods?

**Comment by simon816** [comment]
It's possibly more complicated than that.
Pixelmon is checking `World.loadedEntityList` before spawning in the world. With Sponge's cause tracking system, the entity may not appear in the list until the next tick. As far as pixelmon is concerned the entity is being added for the first time.

**Comment by ryantheleach** [comment]
Suppress the error if the entity is queued to spawn?

**Comment by simon816** [comment]
This commit fixes the issue, but I'm not sure whether there may be more issue further down the line
https://github.com/simon816/SpongeCommon/commit/16f9288efddcc419e2cbb56d40706864110568b4

**Comment by xChristopher210** [comment]
Reported this on the PixelmonMod Site with the information given here and the crash logs from this issue on my server.

http://pixelmonmod.com/tracker.php?p=2&t=8469

**Comment by xChristopher210** [comment]
The issue still occurs on SpongeForge 1311
http://paste.ubuntu.com/16209084/

It says the "Block entity being ticked" is a Ranch Block so I disabled that in the pixelmon.hocon but the issue still occurs.

**Comment by KumaGetsu** [comment]
I confirm it still occurs using 1311.

**Comment by simon816** [comment]
This is primarily a Pixelmon issue. 
They should not be looking in `loadedEntityList` to determine whether their entity spawned. Rather, it should be possible to keep track of the state by using a boolean for example.

**Comment by bloodmc** [comment]
@KumaGetsu @xChristopher210 @kinggoesgaming @simon816 my next push to master will have this issue resolved.
