### ISSUE TITLE
Crash on "/summon Item"

### ISSUE THREAD

**Issue by DoomedScar** [SpongePowered/SpongeForge#623]
I'm calling the **CreateParty** method from a command and it works fine however it has the tendency to randomly crash the server.
Sometimes it would run through the whole process without any issues and sometimes it would crash almost instantly after the command was executed.

**Crash Log**: http://paste.ubuntu.com/16209332/

Using **SpongeForge 1.8.9 - 4.1.0-BETA-1311**
```
	private static Timer timer = null;
	private static int spawnAmount;

	private static final int defaultSpawnAmount = 180;
	private static final int height = 80;
	private static final int X1 = 757;
	private static final int X2 = 775;
	private static final int Z1 = 144;
	private static final int Z2 = 162;

	public static void CreateParty()
	{
		spawnAmount = defaultSpawnAmount;
		
		if(timer == null)
		{
			timer = new java.util.Timer();
			ExecuteDropPartyTimer();
		}
	}

	private static void ExecuteDropPartyTimer()
	{
		timer.schedule(new java.util.TimerTask()
		{
			@Override
			public void run()
			{
				int x = -getRandom(X1, X2);
				int z = -getRandom(Z1, Z2);

				PokeEvents.CMDHandler.process(PokeEvents.server.getConsole(), getItemCommand(x, z));
				spawnAmount -= 1;

				if(spawnAmount <= 0)
					timer = null;
				else
					ExecuteDropPartyTimer();
			}
		}, 1000);
	}

	private static String getItemCommand(int x, int z)
	{
		return "summon Item " + x + " " + height + " " + z + " {Item:{id:minecraft:diamond,Count:1,tag:{}}}";
	}
```

**Comment by kenzierocks** [comment]
You can only spawn items in the main thread. Use the synchronous scheduler.

**Comment by DoomedScar** [comment]
@kenzierocks It works, the items are being spawned however it sometimes crashes the server.

**Comment by simon816** [comment]
It crashes because you're not on the thread that synchronizes with game ticks.
Instead of using `java.util.Timer`, try using sponge's scheduler https://docs.spongepowered.org/master/en/plugin/scheduler.html as @kenzierocks suggested.

**Comment by DoomedScar** [comment]
@simon816 Alright thank you, I'll try that.

**Comment by DoomedScar** [comment]
@kenzierocks @simon816 That fixed my problem, thank you very much!
