### ISSUE TITLE
Sponge is stopping Tinkers Construct from loading cobal and ardite in the nether. 

### ISSUE THREAD

**Issue by jpiermarini** [SpongePowered/SpongeForge#628]
Currently running spong-1.8.9-1808-1305 and forge 1808 . Although I did just test this with the latest sponge-1855-BETA 1317 and Forge 1855 to make sure it was still an issue. I experienced the same issue with the latest and greatest sponge has to offer. 

Loading Sponge, Tinkers Construct 1.8.9 2.2.1 and Mantle 1.8.9 0.9.2 going to to the nether there is no cobalt or ardite to be found. To be sure I edited the tconstruct.cfg file to have cobalt and ardite spawn at 500 per chunk. Still none to be found.   

shutting down the server, disabling sponge and deleting the world to regen. Enter the nether and you immediately see cobalt and ardite.

**Comment by jpiermarini** [comment]
@bloodmc tried sponge 4.1.0-BETA-1318 and 4.1.0-BETA-1320 neither have fixed this issue.

**Comment by bloodmc** [comment]
I'll look into it soon.

**Comment by jpiermarini** [comment]
Thanks, appreciate it.

**Comment by bloodmc** [comment]
@Deamon5550 
https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/shared/worldgen/NetherOreGenerator.java#L38

**Comment by Zidane** [comment]
Closed as issue on Tinker's end.

https://github.com/SlimeKnights/TinkersConstruct/issues/2071
