### ISSUE TITLE
[1.9.4] Rewrite Forge Event Handling to translate Sponge thrown Events

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeForge#630]
There are enough changes now in 1.9 that most of the "use" events are now distinctly different.

They need to be either rewritten or re-managed where the forge events are thrown separately from the Sponge events.

**Comment by bloodmc** [comment]
This is already done for many events as seen in SpongeForgeEventFactory. I'll finish the rest soon.

**Comment by Zidane** [comment]
@bloodmc has finished this up in latest bleeding.
