### ISSUE TITLE
ticking player error when a player tries to enter a world via netherportal that is disabled by forge/sponge

### ISSUE THREAD

**Issue by i9hdkill** [SpongePowered/SpongeForge#633]
Steps to reproduce this:
Forge: 1.8.9-11.15.1.1855
SpongeForge: 1855-4.1.0-BETA-1318

Start server and build a nether portal.
config/sponge/worlds/nether/DIM-1/world.conf gets created.
enter the nether portal
stop the server.
start the server and enter the netherportal again
config/sponge/worlds/nether/Nether/world.conf gets created.
stop the server.
change
config/sponge/worlds/nether/Nether/world.conf
to http://pastebin.com/bAYHhckK
start the server and enter the netherportal.

The following minecraft error is showing up and is spamming the logs. Server hangs.
http://pastebin.com/WFymUEsn

Forge log:
http://pastebin.com/hfYpmKMz

**Comment by Zidane** [comment]
@bloodmc 

I'll fix this in 1.8.9.

**Comment by bloodmc** [comment]
@Zidane ok thanks.

**Comment by Zidane** [comment]
@i9hdkill 

My intention was to resolve this sooner but my main dev machine's GPU decided to go take a walk. That has been somewhat resolved so you'll have a fix this evening.

**Comment by i9hdkill** [comment]
No worries mate. Thanks for for fixing this in 1.8.9 at all!:)

**Comment by Zidane** [comment]
I've made some headway this evening on this issue. Mod dimensions (and Vanilla) now disable but the dimension type isn't right when you join the server. We ran into other unforseen issues on 1.8,9 that I also fixed in regards to multi-world.

I should have this fixed up by the afternoon my time tomorrow.

**Comment by Zidane** [comment]
@i9hdkill 

I have successfully resolved the issue for both regular entities and players. Here is a jar from my dev environment, can you test and see if it works for you?

https://www.dropbox.com/s/5m2o12v3lombe2m/spongeforge-1.8.9-1890-4.1.0-BETA-0.jar?dl=0

BACKUP your worlds first.

**Comment by i9hdkill** [comment]
Thank you, it works!
Disabled the nether in dimension.conf:
world-enabled=false
load-on-startup=false
and disabling works. No errors etc.

Tried to push some items and chickens into the portal and it denies to work for them aswell. 
Thanks for your hard work!

**Comment by Zidane** [comment]
@i9hdkill 

No problem :). Code will be cleaned up and pushed to master later on today.
