### ISSUE TITLE
StackOverflowError when cancelling an InventoryClickEvent and sending a message afterwards

### ISSUE THREAD

**Issue by Milchshakee** [SpongePowered/SpongeForge#637]
The following simple event listener gets caught in an endless loop somehow:

```
@Listener
public void onServerInit(GameInitializationEvent event) {
    Sponge.getGame().getEventManager().registerListener(this, ClickInventoryEvent.class, new EventListener<ClickInventoryEvent>() {
        @Override
        public void handle(ClickInventoryEvent event) throws Exception {
            event.setCancelled(true);
            Sponge.getGame().getCommandManager().process(event.getCause().first(Player.class).get(), "me message here");
        }
    });
}
```

**Comment by Zidane** [comment]
We need a log please.

**Comment by Milchshakee** [comment]
There you go: [https://gist.github.com/anonymous/9f6fec46737d579c93fdf9e18ca68ab1](url)

**Comment by bloodmc** [comment]
I see no point in cancelling the base event like this...especially when you are attempting to send a message directly after. Do you know the ClickInventoryEvent will trigger a ton as that handles ALL clicks within a container. Please provide a proper use-case for what you are attempting to do because currently it makes no sense.

**Comment by Milchshakee** [comment]
The code I use in my plugin is of course more complicated and filters out the ClickInventoryEvents it wants to cancel. The example code above is just used to reproduce the issue that cancelled ClickInventoryEvents are sent again if a message is send after cancellation.

**Comment by Zidane** [comment]
Re-test with stable-5 and re-open if it still occurs.
