### ISSUE TITLE
trackBlockPositionCausePreTick

### ISSUE THREAD

**Issue by KumaGetsu** [SpongePowered/SpongeForge#638]
Crashed the server twice today with trackBlockPositionCausePreTick.

Crash-reports:
http://paste.ubuntu.com/16484844/
http://paste.ubuntu.com/16484845/

**Comment by bloodmc** [comment]
@KumaGetsu update to latest SpongeForge and post a new crash report if it happens.

**Comment by KumaGetsu** [comment]
I'm on the latest and had two more crashes this morning.

Crash-reports:
http://paste.ubuntu.com/16496954/
http://paste.ubuntu.com/16496954/

**Comment by bloodmc** [comment]
@KumaGetsu Try 1331 and post report if it crashes.

**Comment by KumaGetsu** [comment]
@bloodmc Am doing that now, will report back if issue persists.

**Comment by KumaGetsu** [comment]
@bloodmc It just happened again.

Crash-report:
http://paste.ubuntu.com/16501176/

**Comment by KumaGetsu** [comment]
And again

Crash-report:
http://paste.ubuntu.com/16501325/

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/SpongePowered/SpongeCommon/commit/8baf146e990ccf5a54c0c1bd602adbc06edb6e62
