### ISSUE TITLE
SpongeForge 1337 - preTrackBlock

### ISSUE THREAD

**Issue by KumaGetsu** [SpongePowered/SpongeForge#640]
Server crashed.

Crash-report:
http://paste.ubuntu.com/16512906/

**Comment by KumaGetsu** [comment]
Another trackEntityCausePreTick crash, but this time a concurrent crash-report was given shortly before the tracking one.

Crash-reports:
http://paste.ubuntu.com/16513384/ - concurrent
http://paste.ubuntu.com/16513417/ - trackEntityCausePreTick

**Comment by zyradyl** [comment]
I wasn't sure if I should branch this out to a new bug or not, but the issues are so similar I figured I would post it here first. I'm getting a server crash on PostTrackBlock:

http://pastebin.com/da0RptTA

Thank you guys for all your work on sponge. :)

**Comment by bloodmc** [comment]
@KumaGetsu @zyradyl I'll have a fix soon.

**Comment by bloodmc** [comment]
@KumaGetsu @zyradyl build 1338 working ok?

**Comment by KumaGetsu** [comment]
@bloodmc I'll upload it now... It may take some time to see a result.

**Comment by KumaGetsu** [comment]
@bloodmc Here is a new pretick crash on 1338

Crash-report:
http://paste.ubuntu.com/16533433/

**Comment by zyradyl** [comment]
I'm on 1343, no issues yet. However I am getting a "Silently Catching" Ticking error. Should I open a new bug for that or post it here? No crashes, just a notice in console.
