### ISSUE TITLE
java.lang.NullPointerException: The property 'initialWeather' was not provided //crash 

### ISSUE THREAD

**Issue by i9hdkill** [SpongePowered/SpongeForge#643]
SpongeForge 1339
http://pastebin.com/Yi04tNYy
Getting this error/crash after the server loaded sucessfully.

**Comment by bloodmc** [comment]
@i9hdkill Use 1338 for now.

**Comment by Zidane** [comment]
@bloodmc 

This was caused by this dumb separation occurring in these mixins and I missed it. I'll push a fix shortly.

**Comment by bloodmc** [comment]
dupe #642
