### ISSUE TITLE
Heads not updating skins after restart

### ISSUE THREAD

**Issue by Favorlock** [SpongePowered/SpongeForge#645]
So I have a utility class I made for updating skulls which you can find here: http://pastebin.com/uTxzCHzx

The heads just show as steve heads.

**Comment by Favorlock** [comment]
So I've updated my code a bit, here is a working version for setting the heads of a player: http://pastebin.com/ZZVbFYk7

Filling the profile only works with the cache disabled it would seem. If I try fill(profile, true, true) player skins are not set to the profile properly.

**Comment by Aaron1011** [comment]
Fixed in https://github.com/SpongePowered/SpongeCommon/commit/6574605746bc4a8aff177e985e56a76c9a2f0f91
