### ISSUE TITLE
Sponge 1343 - Concurrent Modification Exception

### ISSUE THREAD

**Issue by zyradyl** [SpongePowered/SpongeForge#646]
Crash log is here: http://pastebin.com/CFYjUSVf

I just recently added dynmapForge alpha 2.3-1. Wondering if it is mod incompatibility.

**Comment by JosephRymer** [comment]
What version of [SpongeForge](https://github.com/SpongePowered/SpongeForge) are you running and can you link the file to 
> dynmapForge alpha 2.3-1.

**Comment by zyradyl** [comment]
SpongeForge 1343, Link to Dynmap is at http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1286593-dynmap-dynamic-web-based-maps-for-minecraft

Thanks for looking into this.

**Comment by zyradyl** [comment]
Had another crash last night, Without Dynmap installed. Details are here:
http://pastebin.com/kZyGva9x

**Comment by Zidane** [comment]
Hmm, I'm seeing Biomes O Plenty in all these stacks but I doubt they are doing something odd here...

**Comment by Zidane** [comment]
I'll discuss with @Deamon5550 to see about the best way to resolve this. I see the issue. Thanks for the reply.

**Comment by Zidane** [comment]
@zyradyl 

What is your server's view distance?

**Comment by zyradyl** [comment]
View distance is set at six.

**Comment by Zidane** [comment]
@zyradyl 

I made a commit that adds mob-spawn-range to your config files. Basically, Vanilla has a bug where a view distance under 8 will still load chunks page your view distance when spawning mobs around the player.

This is now fixed to be capped to your view distance. At view distance of 6 mobs will now spawn between 0 and 6 chunks around each player.

**Comment by Zidane** [comment]
Let me push a ref bump for Forge

**Comment by zyradyl** [comment]
Thank you very much! :)

**Comment by zyradyl** [comment]
Seems fixed, Gonna close this now. Thank you!
