### ISSUE TITLE
Any tools with the Collector effect can destroy locked blocks which placed

### ISSUE THREAD

**Issue by bunSakurAing** [SpongePowered/SpongeForge#647]
Thaumcraft 5.2.4, the server is running with sponge 1347
I lock a block, and then I use the wand with the Collector effect destroying the block, the block will be destroyed and then recover, it will drop as an entity and players who have been collected.
I don't know to whom I should report this problem, if this is the problem of the sponge, please repair it.

**Comment by ryantheleach** [comment]
How are you locking the block?

**Comment by bunSakurAing** [comment]
@ryantheleach With the sponge plugin keys

**Comment by bloodmc** [comment]
This has nothing to do with SpongeForge. The issue is with keys not handling this specific mod case.

**Comment by ryantheleach** [comment]
https://github.com/prism/Keys/blob/master/src/main/java/com/helion3/keys/listeners/ChangeBlockListener.java#L45

So at a guess there is no player present in the cause when a tool with collector is used.

**Comment by vectrixdevelops** [comment]
Correct.
