### ISSUE TITLE
doors and gates not closing

### ISSUE THREAD

**Issue by aglarcz** [SpongePowered/SpongeForge#648]
Hello,
doors and gates are not closing with hand on my server with latest spongeforge. When you rightclick some doors not made from oak, they will not close. They are closing in 1 of 10 tries. No error, no fps drops - just not working. Oak doors are ok and opening with button/lever/pressure plate works too. Any ideas?

**Comment by Zidane** [comment]
@aglarcz 

Cannot reproduce. Remove all plugins/mods besides SpongeForge and retest.

**Comment by aglarcz** [comment]
Found interaction with RedProtect - will communicate with its owner. Thanks for tip.
