### ISSUE TITLE
World Border not saving

### ISSUE THREAD

**Issue by KumaGetsu** [SpongePowered/SpongeForge#650]
Using /worldborder set on other dimensions is not persistent after a restart. Only the main world saves it's worldborder.

This issue started a couple version back.

**Comment by Zidane** [comment]
@KumaGetsu 

Unfortunately, this was a side effect of fixing many other issues with storage not being shared globally for global map/etc storage...now the WorldBorder isn't synced to overworld.

I'll push up a fix, apologies!

**Comment by KumaGetsu** [comment]
Thank you. Please @ me when it's pushed. @Zidane

**Comment by Zidane** [comment]
@KumaGetsu 

I fixed up the WorldBorder implementation. It now changes per world and persists :).

**Comment by ryantheleach** [comment]
So nether / end don't use the overworlds border by default? We should document this on the docs somewhere.
