### ISSUE TITLE
Server crash - removeFirst

### ISSUE THREAD

**Issue by KumaGetsu** [SpongePowered/SpongeForge#651]
SpongeForge 4.1.0-BETA-1352

Crash-report:
http://paste.ubuntu.com/16670044/

**Comment by Zidane** [comment]
Heh, blood's favorite bug.

**Comment by bloodmc** [comment]
@KumaGetsu I need a crash report using latest build.

**Comment by KumaGetsu** [comment]
@bloodmc Using 1365 since this morning and haven't seen the crash yet. Going to update to 1367 later. Will keep you informed if those crash-reports show up.

**Comment by KumaGetsu** [comment]
@bloodmc Just had the same crash using 1365. I have just updated to the latest 1370, will update again if it still happens.

Crash-report:
http://paste.ubuntu.com/16860369/

**Comment by KumaGetsu** [comment]
Nvm I am using 1368 because of this issue during startup: http://paste.ubuntu.com/16860434/

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/SpongePowered/SpongeCommon/commit/de314482135c462d4fbd9bdde48e8c3bb1e8912f
