### ISSUE TITLE
Double Generation Events

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeForge#652]
From the [thread](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=2255), Realistic Terrain Generation is receiving double ore generation events.

@srs_bsns could likely explain more, but I'm willing to bet it has to do with the fact that the ore events are thrown on a different event bus than the main events.

Link to RTG: https://github.com/Team-RTG/1.8.9-Realistic-Terrain-Generation

@bloodmc I can look into fixing this, but I think you're the most familiar with the synchronizing of the events.

**Comment by topisani** [comment]
i remember looking into this (hi, im topi, another TeamRTG member (yes thats a terrible name, blame @WhichOnesPink44)), but i forgot what i found out, so thats kinda sad. Does this affect all mc versions? cause theres a pretty big difference between our mod versions.

**Comment by Inscrutable** [comment]
There still seem to be issues with RTG and Sponge [reported on the RTG thread at MCF](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=3550) and also on [Sponge Forums](https://forums.spongepowered.org/t/spongeforge-conflicting-with-world-entity-generation-in-realistic-terrain-generation-mod/14955). Has there been any progress on this?

**Comment by topisani** [comment]
I have kinda left the team, but i will ping the grand @WhichOnesPink44 once again

**Comment by srs-bsns** [comment]
We're already in communication with @gabizou on [our discord server](https://discord.gg/0wIG7mz3g6Qynq4E) for issues relating to RTG.
This specific issue (double decoration events) was noticed by myself in 1.8.9 and I'm not sure it even applies anymore with the current version of Sponge*. The current issue that we are exploring is with random chunks __not__ being decorated (decoration events being supressed?).

**Comment by gabizou** [comment]
@srs-bsns SpongeForge for 1.8.9 is under LTS so it's still supported, however, if you're saying that RTG for 1.8.9 is not supported, then that's fine as well.

**Comment by srs-bsns** [comment]
@gabizou Well, we've received 0 complaints in respect to this issue, and I think they if anyone is still using SpongeForge with RTG, they've either moved on from 1.8.9, or haven't seen or taken issue with duplicate decoration events. (Server operators may be encountering this, but unless they are specifically looking for it, they probably just assume it's intended behavior.)

We're still supporting RTG for 1.8.9, but focus has been on 1.10.2, so I don't think it prudent to spend much time on this without complaint. However, if there are still concerns about this I can try to explore it more when I have the time.

**Comment by gabizou** [comment]
So, I've found already a bug that has probably gone by unnoticed for a while now:

![image](https://puu.sh/rw0dQ/34c58c9a10.png)

This probably has to do with the duplication of certain events for the same objects and lack thereof of gravel generation. I'm doing some more investigating, but I'm failing to find any specific duplication of events for the same chunk at the current time with 1.10.2's bleeding branch for SF and 1.10.2-master for RTG.

I'll definitely keep this issue up to date.

**Comment by gabizou** [comment]
From my testing, I have not found issues with RTG and SpongeForge for 1.10.2, I have fixed the issue noted in the previous comment, but for now I feel that this can be closed.

**Comment by srs-bsns** [comment]
I'll try and do some more testing at some point in the future, and if I notice anything wrong I'll let you know.
