### ISSUE TITLE
Random server crash

### ISSUE THREAD

**Issue by MrJoki007** [SpongePowered/SpongeForge#653]
Just played on my modpack server and it accidently crashed with following crash report:
[fml-server-latest.txt](https://github.com/SpongePowered/SpongeForge/files/287327/fml-server-latest.txt)

**Comment by simon816** [comment]
You have pore which unfortunately isn't fully implemented and will likely crash with bukkit plugins.
Remove Pore to see if it helps fix the issue

**Comment by bloodmc** [comment]
Caused by Pore which is a dead plugin and unsupported.
