### ISSUE TITLE
Cancelling an InventoryClickEvent and clicking repeatedly causes ItemStacks to disappear

### ISSUE THREAD

**Issue by Milchshakee** [SpongePowered/SpongeForge#654]
When using the event listener below in a plugin and trying to click on an ItemStack in an inventory nothing happens as expected, since the event is cancelled. However, if you spam your left and right mouse button simultaneously long and hard enough, the ItemStack will somehow disappear. Even after a relog, the ItemStack is gone. Note that you have to spam the mouse buttons both at the same time and really fast for some time.

        Sponge.getGame().getEventManager().registerListener(this, ClickInventoryEvent.class, new EventListener<ClickInventoryEvent>() {
            @Override
            public void handle(ClickInventoryEvent event) throws Exception {
                if (event instanceof ClickInventoryEvent.Primary || event instanceof ClickInventoryEvent.Secondary) {                
                    if (event.getCursorTransaction().getFinal() != null) {
                        event.setCancelled(true);
                    }
                }
            }            
        });

The code above is just an example to reproduce the issue and not a real use case but there are real use cases that are affected by this issue.

**Comment by bloodmc** [comment]
Fixed in commits
https://github.com/SpongePowered/SpongeCommon/commit/b810920e12ca40c5c98c37811eb8d341fe8d452a
https://github.com/SpongePowered/SpongeCommon/commit/1217e1d4628b2c8da21e5c632e5253715830bee9
