### ISSUE TITLE
1377 Teleport errors

### ISSUE THREAD

**Issue by KumaGetsu** [SpongePowered/SpongeForge#656]
@bloodmc 1377 causing issues with teleporting

Not able to copy text of the errors in chat mouse-over info so here's 2 screenshots of the issues.

setLocation
http://puu.sh/pcnxi/57a1cbf9ca.png

setTransform
http://puu.sh/pcnzw/24bbe28286.png

**Comment by Zidane** [comment]
@KumaGetsu 

Hassan will need to update his plugins.

**Comment by KumaGetsu** [comment]
@Zidane Okay thanks, I'll inform him
