### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by seanamor** [SpongePowered/SpongeForge#659]
Currently this is my set up:

 SpongeForge
 Minecraft: 1.8.9
 SpongeAPI: 4.1.0-SNAPSHOT-8c015f8
 SpongeForge: DEV
 Minecraft Forge: 11.15.1.1902

When I try to use Sponge 4.1.0-BETA-1385, it crashes. I am pretty certain its because its not built on forge 11.15.1.1902 (*latest)

Id like to stay on the bleeding edge, as there are bug fixes so frequently. If you guys can update sponge to play nice with the latest forge that would be amazing :D I understand its time consuming, so if its not priority, no big deal!

Also one thing to note, when adjusting the world sponge config file, for example disabling a specific mob, it doesnt seem to work.

**Comment by JBYoshi** [comment]
Could you post the crash report?

**Comment by seanamor** [comment]
Sure let me switch over to Sponge 4.1.0-BETA-1385 to get the report.

**Comment by seanamor** [comment]
My apologies, it worked this time. This can be closed, aside from the spawning issue in the config.

**Comment by bloodmc** [comment]
Disabling a specific mob? There is nothing in our configs that support this. You can disable entity activation but that has NOTHING to do with spawning. Read the docs.
