### ISSUE TITLE
[1.8.9] ConstructEntityEvent.POST meaningless Cause object 

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/SpongeForge#663]
This issue was closed months ago, but was not completed and the followup was never acknowledged, so I'm reposting to make sure it was seen again with the current Spongeforge/forge 1.8.9 (just prior to api 4.2.0 pushoout) combo              https://github.com/SpongePowered/SpongeForge/issues/589

The ConstructEntityPost event is thrown but the CAUSE is useless:
Cause.toString ::
`Cause[{Name=Source, Object={SpongeModGame{platform=SpongeModPlatform{type=SERVER, executionType=SERVER, api=Plugin{id=spongeapi, name=SpongeAPI, version=4.1.0-SNAPSHOT-60438ad}, impl=sponge, minecraftVersion=SpongeMinecraftVersion{name=1.8.9, protocol=47}}}}}]`

Cause.root. toString ::
`SpongeModGame{platform=SpongeModPlatform{type=SERVER, executionType=SERVER, api=Plugin{id=spongeapi, name=SpongeAPI, version=4.1.0-SNAPSHOT-60438ad}, impl=sponge, minecraftVersion=SpongeMinecraftVersion{name=1.8.9, protocol=47}}}`

Cause.root.getClass: 
`org.spongepowered.mod.SpongeModGame`

**Comment by gabizou** [comment]
@Zidane @bloodmc I'm guessing that this is going to be chalked up to the `CauseTracker` to determine what the cause of the construction should be?

**Comment by gabizou** [comment]
Is this still a thing?

**Comment by theboomer** [comment]
Yes, there is  no change, except in the current spongeforge and 4.2.0 api we get:

`[Server thread/INFO] [STDOUT]: [com.prennet.boomod.testplatformc.TestplatformC:ps:38]: Cause[{Name=Source, Object={SpongeModGame{platform=SpongeModPlatform{type=SERVER, executionType=SERVER, api=Plugin{id=spongeapi, name=SpongeAPI, version=4.2.0-SNAPSHOT-768e91f}, impl=sponge, minecraftVersion=SpongeMinecraftVersion{name=1.8.9, protocol=47}}}}}]`

**Comment by Zidane** [comment]
1.8.9 is no longer supported. Check this against stable-5 and reopen if still an issue.
