### ISSUE TITLE
[1.9.4] Crash with some mods installed

### ISSUE THREAD

**Issue by LuxusDarkangel** [SpongePowered/SpongeForge#665]
Crash-Report: http://pastebin.com/9rqFG6H4
SpongeForge version: 5.0.0-BETA-1406

In this case i used Forestry to reproduce the crash, but works with Extrautilities too.

**Comment by gabizou** [comment]
Fixed with https://github.com/SpongePowered/SpongeForge/commit/c910096bce1a189f1ed19ac2b37b4b2c0c6c14a8 the build should be [#1409](http://files.minecraftforge.net/maven/org/spongepowered/spongeforge/index_1.9.4.html).
