### ISSUE TITLE
[1.9.4] Massive spam generating a world with Pam's Harvestcraft.

### ISSUE THREAD

**Issue by LuxusDarkangel** [SpongePowered/SpongeForge#668]
Log  (only a chunk, becase it's waaaaaay bigger): http://pastebin.com/rBgZN7Nk
SpongeForge version: 5.0.0-BETA-1412

**Comment by Zidane** [comment]
@LuxusDarkangel 

We need the log from start and up to the FIRST print of the runaway phase.

**Comment by gabizou** [comment]
@LuxusDarkangel Can you give build 1414 a try? I've added some helpful debugging in the cases where terrain recurses into multiple chunks (which mods apparently want), Do report back if it still ends up spamming with the same type of stack trace as https://gist.github.com/gabizou/547830b48abdec0a39121eb56fc37ac2#file-gistfile1-txt-L115-L201 exemplifies. (What you're looking for is when you see the phases for `TERRAIN_GENERATION` and or `POPULATOR_RUNNING` etc.)

**Comment by LuxusDarkangel** [comment]
Hmm... you mean build 1413 or is it still building and uploading to the forge servers?

**Comment by gabizou** [comment]
Sorry, build 1417 which just built (should show up in the next few minutes) has the fixes and then some.

**Comment by LuxusDarkangel** [comment]
You only added debug? Because i'm not able to reproduce it using build 1417, only build 1413.
Guess it's fixed, thank you!

**Comment by LuxusDarkangel** [comment]
Well, i was wrong, this keeps happening. Here's a log using the latest sponge version so you can see the debug; https://mega.nz/#!wRkkkQhJ!TV8KPEpR3jcFD2gvPfrIipDQcNWateGVTKFCLw-fzns

**Comment by gabizou** [comment]
@LuxusDarkangel Could you just use gist.github.com to include the startup and the first few sets of reports from the cause tracker? I don't really need the rest of the log.

**Comment by LuxusDarkangel** [comment]
Of course: https://gist.github.com/LuxusDarkangel/73be4b556cb557fd6735299a34a878d7

**Comment by gabizou** [comment]
You're still using an older SpongeForge, your'e running 1412, the build that fixed this issue is 1417+.

**Comment by LuxusDarkangel** [comment]
You're totally right, I uploaded the latest version knowing it should fix this, but made it to the wrong server (I'm using two dedicated servers, with the same name). Sorry for bothering you!
