### ISSUE TITLE
[1.9.4] Incompatibility with ExtraBitManipulation

### ISSUE THREAD

**Issue by LuxusDarkangel** [SpongePowered/SpongeForge#670]
When you use some of the functions of this mod, it shows this error in the console log and the changes you made are not saved (they're only reflected in your client, and disappear when you relog)

A chunk of the log: http://pastebin.com/DacTdU0g
Full log: https://mega.nz/#!hNsz1A5Q!_bvac-xl1q3z1osd4aJYd6gZeSg53zEwWyM8F5MWUqQ

**Comment by LuxusDarkangel** [comment]
The same problem happens with other mods, FE: using Tinkers Contruct's EFLN.
Any news? @gabizou

**Comment by gabizou** [comment]
I know of a solution, but whether it's a good one is unknown, I have to do some finer testing.

**Comment by bloodmc** [comment]
@LuxusDarkangel Can you please provide a test world and steps to reproduce this issue.

**Comment by LuxusDarkangel** [comment]
Oh, I forgot this issue was still open. I tested it in 1.12.1 with SpongeForge 2634 and works fine. This was probably fixed in 1.10 with a bunch of bugs of the same type.
