### ISSUE TITLE
Make SpongeForge configuration configurable through Forge mod configuration menu

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeForge#673]
A few mods have already started doing this for clients, and I believe that as many options we provide, we should be able to configure the global configurations of Sponge (granted, mixin disabling barred since that's a more runtime start up thing) through such menus. This is a low priority but still an enhanced feature.

Perhaps later on as well, we could provide a sponge like GUI menu for in world configurations. There are many ways to go about this.

**Comment by Zidane** [comment]
I've elected to make the decision to not do this as running on the client comes as a happy consequence. The config file is easy enough to modify.
