### ISSUE TITLE
[1.9.4] SpongeForge incompatible with EnderCore

### ISSUE THREAD

**Issue by Mohron** [SpongePowered/SpongeForge#674]
Mod Versions
EnderCore-1.9.4-0.4.0.23-alpha.jar
spongeforge-1.9.4-1954-5.0.0-BETA-1417.jar

[Crash Report](http://pastebin.com/xrrtiB9U)

https://github.com/SleepyTrousers/EnderCore/issues/44

**Comment by Mohron** [comment]
https://github.com/SpongePowered/SpongeForge/issues/674

**Comment by gabizou** [comment]
It's a known issue, it requires a single class change of which a PR was made some time ago to fix it: https://github.com/SleepyTrousers/EnderCore/pull/37 There's nothing SpongeForge can do by itself.
