### ISSUE TITLE
[1.9.4] Start-up crash with Stellar API/Sky

### ISSUE THREAD

**Issue by ruyanve** [SpongePowered/SpongeForge#677]
Forge 1954
Sponge 1418
Stellar API 0.4.3.2b
Stellar Sky 0.4.4.1

With Stellar API: https://gist.github.com/ruyanve/e9138db618f5d477ac2583d70dfcc552
With Stellar API + Stellar Sky: https://gist.github.com/ruyanve/43ce5a9bbc16284490bc591221eb6915

Opened a ticket here as well: https://github.com/Abastro/StellarAPI/issues/2

**Comment by Zidane** [comment]
Fixed locally, will be pushed up tonight with a big amount of multi-world fixes

**Comment by Zidane** [comment]
Fixed in next SF bleeding build.
