### ISSUE TITLE
[1.9.4] Incompatibility with CodeChickenCore

### ISSUE THREAD

**Issue by LuxusDarkangel** [SpongePowered/SpongeForge#681]
Log: https://gist.github.com/LuxusDarkangel/9ceb2b4ed5b203c80ee8266e329fb512
SpongeForge version: 5.0.0-BETA-1418

**Comment by Aaron1011** [comment]
This will be fixed when https://github.com/SpongePowered/Mixin/issues/134 is closed.

**Comment by Mumfrey** [comment]
@Aaron1011 no it won't because you need to update to 0.5.7 for the fix.

**Comment by Aaron1011** [comment]
@Mumfrey: My bad - I meant 'we will fix it after this issue is closed', not 'it will be automatically fixed'.

**Comment by Aaron1011** [comment]
This is resolved in the latest SpongeForge.
