### ISSUE TITLE
[1.9.4] Game breaking duplication glitch

### ISSUE THREAD

**Issue by dakattack** [SpongePowered/SpongeForge#682]
Sponge is causing items to duplicate on my server. It is very easy to recreate, just open your inventory, click an item, then (without closing the inventory screen) click and drop it off to the side. I am on spongeforge-1.9.4-1954-5.0.0-BETA-1429.  I know the problem is with sponge since it doesn't work in single player when I tried.  The only other mod I use is Biomes O Plenty.

EDIT: It is a problem with every sponge version compatible with 1.9.4, not just version 1429.

**Comment by Zidane** [comment]
I've tested the latest SpongeForge bleeding code and I cannot reproduce this. No duplication occurs.

**Comment by Zidane** [comment]
@gabizou 

I stand corrected. This only affects survival.
