### ISSUE TITLE
Server crash on startup when allow-nether=true

### ISSUE THREAD

**Issue by mikroskeem** [SpongePowered/SpongeForge#683]
Hello!

When I set `allow-nether=true` in server.properties, my server crashes with log: http://ix.io/S4P

I have tried everything:
* Reinstalling whole server
* Removing Sponge (server runs without it fine)
* Removing anything but Sponge (still crashes)
* Regenerating world(s)
* Setting `allow-nether=false`, which disables all worlds (server runs fine, but I want other worlds too)
* Updating/downgrading Forge. Same error occurs on `11.15.1.1890` and `11.15.1.1902`

System is running on btrfs and CentOS 7 amd64, JVM is Oracle JRE 8u92

If it helps, I'm running server inside Docker container

EDIT: added information about forge version

**Comment by Zidane** [comment]
Erm, that build is actually a fair bit old and behind our latest recommended build as well.

```
[08:48:05] [main/INFO] [FML/]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from spongeforge-1.8.9-1890-4.1.0-BETA-1339.jar
```

Please download 1402 at the minimum http://files.minecraftforge.net/spongepowered and run it again.

**Comment by mikroskeem** [comment]
Whoops, my bad (more sleep needed) :)
