### ISSUE TITLE
[1.8.9] Offline server return "null" instead of name of player ? 

### ISSUE THREAD

**Issue by Flashback083** [SpongePowered/SpongeForge#684]
Hello ! Since i updated sponge, we have an issue, i think the uuid is break , for example, i use foxguard plugin and when a add member to region , the member wasnt add and in list, we see : "null" instead of name of player, any idea for this problem or you need more information ? thanks!!

PS :  i already make issue on spongeapi, but i think its not the good place, so i repost here my problem
i dont know with which version i have this issue cause with 1329 this bug is here ^^'
Thanks for your help !

**Comment by Zidane** [comment]
@Flashback083 

This sounds like a FoxGuard issue, report it to its maintainer and they can work with us on a resolution.
