### ISSUE TITLE
[1.9.4] Can't use water bucket in survival

### ISSUE THREAD

**Issue by dakattack** [SpongePowered/SpongeForge#685]
When I right click with the bucket the water block appears and then disappears and my bucket is still a "water bucket".  On the latest bleeding version in survival mode.  Tested it and it also affects the version released before this.

**Comment by kinggoesgaming** [comment]
do you have any mods/ plugins? Try without any if yes

**Comment by dakattack** [comment]
only biomes o plenty.  i did try it without any mods and it did not work.  damn shame cause i've got some water that needs a movin.

**Comment by Aaron1011** [comment]
Bizarrely enough, this is a [**feature**](https://bugs.mojang.com/browse/MC-99561?jql=text%20~%20%22filling%20bucket%20creative%22). However, given how counterintuitive it is, it might actually be worth it to add a config option to use the old behavior.

**Comment by Zidane** [comment]
@Aaron1011 

He said this is happening in SURVIVAL mode.

**Comment by Aaron1011** [comment]
Ah, my bad - I read the issue the opposite way by mistake.

**Comment by Aaron1011** [comment]
Fixed for real in https://github.com/SpongePowered/SpongeForge/commit/b1b0fd702402573b865b18af9fc42fe621a7f8c7.
