### ISSUE TITLE
[1.9.4] You respawn with all of your items in survival

### ISSUE THREAD

**Issue by dakattack** [SpongePowered/SpongeForge#686]
On the latest bleeding version and possibly other versions compatible with 1.9.4, you respawn with your inventory intact.  Then you can go to your body and all of your items are there as well.  When you proceed to pick up those items, it seems to negate all of the items, and it writes in a 0 as the amount of that item you have, effectively deleting the item altogether.

**Comment by gabizou** [comment]
Update to the latest SF bleeding.
