### ISSUE TITLE
Compatability - Crafting Harmonics

### ISSUE THREAD

**Issue by Mohron** [SpongePowered/SpongeForge#687]
Version: spongeforge-1.9.4-1954-5.0.0-BETA-1436
Also Installed: craftingharmonics-1.9.4-1.4.6.29

Don't know if there is any hope of compatibility with Crafting Harmonics given what it interacts with but one can hope!

https://github.com/legendblade/CraftingHarmonics/issues/109

**Comment by Aaron1011** [comment]
@Mohron: The issue is in CraftingHarmonics. I've left a comment.

**Comment by Zidane** [comment]
Closing as issue is on the mod author's end.
