### ISSUE TITLE
[1.9.4] Weird item drop behavior.

### ISSUE THREAD

**Issue by LuxusDarkangel** [SpongePowered/SpongeForge#691]
Actually two problems exist with item drops:

1.- Opening the inventory GUI and dropping items in one of the sides will cause them to disappear (like throwing them to NEI in cheat mode)
2.- Trying to drop anything using Q can cause two behaviors:
  - If you open your inventory GUI and drop anything using Q, it will delete the item (no matter if in survival or creative mode)
  - If you select the item in the hotbar and try to drop it using Q, it will revert the item back to your inventory instantly.

NOTE: Picking the item using the middle mouse button looking at some block will allow you to drop it, not reproducing the bug.

May be related to #682

**Comment by gabizou** [comment]
Should all be fixed now. Report back if still broken in build 1472.

**Comment by LuxusDarkangel** [comment]
One of the problems is fixed, another one partially fixed and the last one keeps happening as before. I edited my first post to mark them.

**Comment by Zidane** [comment]
Moving discussion over here:

https://github.com/SpongePowered/SpongeCommon/issues/803
