### ISSUE TITLE
[1.9.4] Incompatibility with ExtraUtilities2

### ISSUE THREAD

**Issue by LuxusDarkangel** [SpongePowered/SpongeForge#693]
Log: https://gist.github.com/LuxusDarkangel/d69d4b7d43e7d6217efa83bc4a0feeeb
SpongeForge version: 5.0.0-BETA-1450

**Comment by Aaron1011** [comment]
Pending on https://github.com/rwtema/extrautilities/issues/888.

**Comment by Zidane** [comment]
Closing as this is a mod author issue and not a Sponge issue.
