### ISSUE TITLE
[1.9.4] ChunkPreGenerate not working properly.

### ISSUE THREAD

**Issue by LuxusDarkangel** [SpongePowered/SpongeForge#694]
I made two tests using a plugin which implements ChunkPreGenerate (ProjectBorders: https://github.com/trentech/ProjectBorders/releases/tag/0.1.0), one in SpongeForge 1.8.9 (working fine, used to compare) and another one using SpongeForge 1.9.4 (bugged one)

I generated a new world for each test and used the following commands:

/border center world [x] [z]
/border diameter world 2500 (2500 = world diameter)
/border generate world

Using SpongeForge 1.8.9:
Started generation at: [18:54:05] [Server thread/INFO] [com.gmail.trentech.pjb/]: Generated 27 chunks in 0s 123ms, 2% complete
Finished generation at: [19:11:27] [Server thread/INFO] [com.gmail.trentech.pjb/]: Done! Generated a total of 24887 chunks in 282s 946ms

World folder size at the start: ~ 5 Mb
World folder size at the end: ~ 110 Mb

It took ~15 minutes to fully generate the world, I guess a reasonable time, being a "vanilla forge" server (without mods).

Using SpongeForge 1.9.4:
Started generation at: [19:27:40] [Server thread/INFO] [com.gmail.trentech.pjb/]: Generated 813 chunks in 0s 043ms, 3% complete
Finished generation at: [19:27:43] [Server thread/INFO] [com.gmail.trentech.pjb/]: Done! Generated a total of 24887 chunks in 0s 610ms

World folder size at the start: ~ 5 Mb
World folder size at the end: ~ 9 Mb

It took literally 3 seconds to "fully" generate the world, which is obviously impossible.

This affects a lot the performance in production servers, where is almost 100% necessary to pre-generate the world in order to keep it stable with a big quantity of players.

**Comment by Zidane** [comment]
I've tested latest bleeding and this is indeed fixed.
