### ISSUE TITLE
Server not starting

### ISSUE THREAD

**Issue by MrJoki007** [SpongePowered/SpongeForge#697]
Just created a FTB Unstable 1.9.4 server with forge version forge-1.9.4-12.17.0.1965-universal.jar and sponge version spongeforge-1.9.4-1965-5.0.0-BETA-1472.jar.
But the server wont start
[fml-server-latest.txt](https://github.com/SpongePowered/SpongeForge/files/322038/fml-server-latest.txt)

**Comment by LuxusDarkangel** [comment]
You have two problems:
1.- Update EnderCore (See [this](https://github.com/SleepyTrousers/EnderCore/pull/45))
2.- Remove ExtraUtilities 2, it's not compatible with SpongeForge (Requires a mod change, see [this](https://github.com/rwtema/extrautilities/issues/888))

**Comment by Zidane** [comment]
Closing as this is a mod issue and not us.
