### ISSUE TITLE
[1.9.4] Chunks never get unloaded

### ISSUE THREAD

**Issue by LuxusDarkangel** [SpongePowered/SpongeForge#698]
I noticed an issue with chunks, where as i was moving around the world and using the command /sponge chunks -w world the number never decreased, even if I stopped for a few minutes in the same spot to prevent more chunk loading. Turned on chunk unload debug, and confirmed the issue.

This mean two things:

1.- Natural chunk unload is not working, leading to massive lag and, finally, the server running out of memory.
2.- Chunk gc is not working either.

**Comment by gabizou** [comment]
Fixed in https://github.com/SpongePowered/SpongeForge/commit/f355e5798ace5b25f2540121f99f8a249c04b323.

**Comment by LuxusDarkangel** [comment]
Seems like chunk gc is broken again. If i move around the world it unloads inactive chunks when i get far from them, but if i'm using a chunk pre generator, chunk gc does nothing and the number of loaded chunks keeps growing until it runs out of memory.

**Comment by gabizou** [comment]
Chunk GC is disabled. there's nothing that we're preventing chunks from unloading or loading. Are any mods installed?

**Comment by LuxusDarkangel** [comment]
You mean chunk gc is not available in Sponge atm?

And no, I always test issues without mods (or only the specific mod causing the issue) to make sure it's a problem with sponge or the mod in question.

It looks like only chunks loaded by players are being unloaded. Not sure how minecraft manages that, but i remember some kind of ticket mechanics to force chunk loading? Maybe there is the problem.

Timings (In this timings i'm using ProjectBorders to generate the world): https://timings.aikar.co/v2/?id=0105cb3b9cc1414eaf3682f8ade48145

**Comment by gabizou** [comment]
I hate to say it, but would you be able to re-test with the latest 1.10.2 versions released?  There have been quite a few bug fixes in various systems, and I'm wondering if the version of SF you downloaded had not been updated for that commit. And yes, there is a force chunk load ticket system, but I don't see any of Sponge's internals doing anything to keep chunks loaded itself, unless Project Portals is explicitly keeping chunks loaded.

**Comment by LuxusDarkangel** [comment]
Tested with the 1.10.2 version, the same thing happens. It has nothing to do with ProjectBorders, as i'm using the same versions as i was using when we closed this issue (and it worked fine back then, chunks generated -> then unloaded)

**Comment by gabizou** [comment]
And without ProjectBorders?

**Comment by LuxusDarkangel** [comment]
Well... without ProjectBorders I can't reproduce the bug. I know there's another plugin which does the same, you want me to test using it?

**Comment by Zidane** [comment]
@LuxusDarkangel 

I would do so. This is why we always request removing plugins and testing as we MUST make sure that it really is a Sponge issue.

**Comment by LuxusDarkangel** [comment]
Well, yeah, but I needed it to test. Anyway, tried with ChunkPreGenUtil (Another plugin for the same purpose) and the same happens. Both are opensource and very small, if you want to take a look at them?

**Comment by gabizou** [comment]
Should be fixed with the latest builds.
