### ISSUE TITLE
NullPointException when entering nether

### ISSUE THREAD

**Issue by MrJoki007** [SpongePowered/SpongeForge#699]
When I enter the nether I get kicked with the reason Internal Server Error and this error in the console: http://hastebin.com/rodadojeme.avrasm

Modpack: FTB Unstable 1.9.4 Forge version: forge-1.9.4-12.17.0.1965-universal.jar Sponge version: spongeforge-1.9.4-1965-5.0.0-BETA-1472.jar

Edit: Nether is enabled in server.server.properties and the dimension.conf of sponge

**Comment by Aaron1011** [comment]
@MrJoki007: I'm unable to reproduce this with the latest FTB unstable pack. Were you using the latest version (I had to disable extrautilities and manually upgrade EnderCore to get it to work with Sponge).

**Comment by MrJoki007** [comment]
Yeah did those two too. Also I have installed enderstorage and chickenchunks

**Comment by MrJoki007** [comment]
It seems to be the fault of chickenchunks

**Comment by Zidane** [comment]
@MrJoki007 

Re-test with the latest 1.10 build of Sponge and give me the log if it happens again.
