### ISSUE TITLE
[1.9.4] Sheering Sheep does not produce wool

### ISSUE THREAD

**Issue by dakattack** [SpongePowered/SpongeForge#702]
Sheered a sheep, got no wool.  Killed a sheep and the wool spawned.  Only other mod is biomes o plenty.  On latest version of sponge 1.9.4.

**Comment by gabizou** [comment]
Fixed in https://github.com/SpongePowered/SpongeForge/commit/f6f78052f1934181624bf73c3be491b20553984e
