### ISSUE TITLE
Random Crash with maximum players online.

### ISSUE THREAD

**Issue by Xwaffle1** [SpongePowered/SpongeForge#707]
Server was running just fine with no lag, not latency issues. Then boom. Servers modded, but the crash report seems to be coming from SpongeCommon.

http://pastebin.com/TUGT96Gh

**Comment by Aaron1011** [comment]
@Xwaffle1: Could you post the entire server log?

**Comment by Xwaffle1** [comment]
Sorry for late response. 

We are running Pixelmon (i'm sure you get many many crash reports that may because by them)
The stack trace points to sponge, but we're sending it to Pixelmon as well. Thanks!

http://pastebin.com/V0ZZ1LzW

**Comment by gabizou** [comment]
If you can give it a shot, update Java as there might be a bug in the JVM causing the error.

**Comment by Xwaffle1** [comment]
BTW, this is on SpongeForge-1.8.9-1402, the last recommended version not 1.9.

**Comment by Xwaffle1** [comment]
This error seems to be quite common for us now, after the servers left online for a while. We have a good 40-100 players online at all times.

**Comment by Zidane** [comment]
@Xwaffle1 

Do you have a timings paste from when you have near 100 players online? Would love to see it.

**Comment by Xwaffle1** [comment]
https://timings.aikar.co/v2/?id=be54136a680b4ea9b2ccd6a60c490443

The servers appear to be crashing upong restarts. Constantly. We had 4 crashes within a minute of each reboot. This timing report has 92 players online.

This time we got some more interesting crash reports. Here's  a pastebin with the stacktrace.
http://pastebin.com/AGSXAyDw

**Comment by Xwaffle1** [comment]
Also we are using Multicraft, and it's auto reboot feature. But, that shouldn't matter because it's a simple stop command.

**Comment by Aaron1011** [comment]
@Xwaffle1: Would you be able to join IRC (`#sponge` on `irc.freenode.net` - [webchat](https://webchat.freenode.net/)) to help me debug this issue?

**Comment by bloodmc** [comment]
@Xwaffle1 update to latest SpongeForge as it fixed a memory leak which could be the cause of your issues.
