### ISSUE TITLE
Cannot launch with ExtraUtils2

### ISSUE THREAD

**Issue by devryb** [SpongePowered/SpongeForge#708]
Mod name: EXTRAUTILS2-1.9.4-ALPHA-1.0.0A.jar
Link: http://minecraft.curseforge.com/projects/extra-utilities/files

Log: http://pastebin.com/bDvjgdDT

**Comment by Zidane** [comment]
@devryb 

ExtraUtils is causing ModMetadata to be classloaded in their transformer. They need to not do this as it doesn't give us a chance to perform a transformation on that class too.

Closing as this is not a Sponge issue.

**Comment by devryb** [comment]
@Zidane do we have an issue open on the extrautil tracker for this?

**Comment by Zidane** [comment]
@devryb 

https://github.com/rwtema/extrautilities/issues/888
