### ISSUE TITLE
SpongeForge generates Nether and End in singleplayer

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/SpongeForge#714]
Normally, only the Overworld is generated in singleplayer, while the Nether and End are generated when the player first travels to them.

With SpongeForge installed, all three dimensions are generated when the world is first created, which can increase the world load time by several seconds.

Unless there's a specific reason to do this, we should probably stick to how Vanilla handles it, and only generate the Overworld in singleplayer.

**Comment by Zidane** [comment]
@Aaron1011 

This should actually apply no matter the platform but is only really an issue for the Nether. For example, you always teleport to a location around 0, 0 in The End so generating it at server start makes sense as that means a quick teleport.

Nether is different, we generate around spawn point of Nether which, like End, would be at 0 I believe and you won't see the benefit of this UNLESS your portal you go through puts you within the spawned chunks. Keep in mind I'm purposely ignoring commands, I'm aware you could teleport to Nether's spawn which would be in the generated chunks.

**Comment by Zidane** [comment]
I've decided that I'll just make the Nether's archetype to not generate-on-load which will fix this issue.

**Comment by Zidane** [comment]
@bloodmc has fixed this in bleeding.
