### ISSUE TITLE
Errors in Items, Block Placing, Chunk Loading.

### ISSUE THREAD

**Issue by xChristopher210** [SpongePowered/SpongeForge#715]
I'm having some weird things going on in my server being reported from many different people. Players are saying that blocks can't be placed, that they cannot pick up items, and chunks just don't load.

Sadly I dont have the fml-server-latest.log but I do have the regular log in the tar.gz file. It shows alot of errors and can hardly see players chatting.

https://drive.google.com/file/d/0B4r2-vZp69xEVjJVQ3pmZjVNc1E/view?usp=sharing

_I just downgraded back to SpongeForge 1484 and everything is back to normal_

**Comment by bloodmc** [comment]
@xChristopher210 Fixed in latest build.

**Comment by cartman-2000** [comment]
There's still some issues with item pickup, but it's usually fixed when a player reconnects to the server.
