### ISSUE TITLE
[bleeding] Sponge breaking world when mod gets removed

### ISSUE THREAD

**Issue by MrJoki007** [SpongePowered/SpongeForge#716]
I just removed mods from my server and sponge messed up the world by mixing all the block ids.
Error: http://hastebin.com/ohokeyakec.vbs

But if i remove sponge and then the other mods the world is fine until I add sponge again to the server.
[fml-server-latest.txt](https://github.com/SpongePowered/SpongeForge/files/334703/fml-server-latest.txt)
Sponge version: spongeforge-1.9.4-1968-5.0.0-BETA-1503.jar
Forge version: forge-1.9.4-12.17.0.1968-universal.jar

**Comment by SnowBlitzz** [comment]
Just a fyi I don't think they support old sponge builds anymore. Update to the latest.

**Comment by MrJoki007** [comment]
Its the recent version

**Comment by SnowBlitzz** [comment]
Ah, fuzzy. Read it all wrong. Sorry about that XD never should have commented lol

**Comment by bloodmc** [comment]
@MrJoki007 please zip your mods so we can troubleshoot the issue on our end. Also state the exact steps you took to reproduce this issue.

**Comment by MrJoki007** [comment]
With the mods I removed or without?

**Comment by MrJoki007** [comment]
Here a link of all mods zipped together: http://glplayers.de/Daten/mods.rar
The steps: Create a world :D
Then stop the server and remove mods (EnderStorage, ChickenChunks and CodeChickenCore for me)
Start the server again
Then the normal message that some blocks are missing appears, confirm that with /fml confirm
After that an error appears that theres an error in the level.dat and you have to confirm that with /fml confirm too.
The last step is the one that breaks the world

**Comment by bloodmc** [comment]
@MrJoki007 Provide the log again as your hastebin link has expired.

**Comment by MrJoki007** [comment]
http://pastebin.com/UC3WpzeX

**Comment by mrAppleXZ** [comment]
Same issue on SpongeForge 5.0.0-BETA-1534.

**Comment by XileForce** [comment]
Happens on the 1.10.2 builds as well. Basically at one point we removed neotech several days ago. But if I add in sponge, it says that the backup level.dat is being used and scrambles everything around if you confirm it. ie, certain trees becoming blocks from other mods. Adding sponge to worlds where no mods have ever been removed is fine however.

**Comment by gabizou** [comment]
Yeah, I know the fix, a bit of an annoyance, but will fix for 1.10.2, not for 1.9.4 sadly.

**Comment by mrAppleXZ** [comment]
It's still happening on SpongeForge 5.0.0-BETA-1543 for 1.10.2.

**Comment by XileForce** [comment]
I don't think the fix has been pushed yet. Likely this issue would have been referenced in the commit or closed if it had.

**Comment by gabizou** [comment]
> I don't think the fix has been pushed yet. Likely this issue would have been referenced in the commit or closed if it had.

Correct.

**Comment by LuxusDarkangel** [comment]
Good news then, this is a critical bug.

**Comment by Zidane** [comment]
This will be addressed today by either gabizou or me.
