### ISSUE TITLE
[bleeding] Sponge breaking FTB Utilities

### ISSUE THREAD

**Issue by MrJoki007** [SpongePowered/SpongeForge#718]
If you have installed FTB Utilities on both (client and server) sides, some buttons will appear on the top left corner of the inventory gui. But if you have sponge installed, the buttons wont appear.

Sponge version: spongeforge-1.9.4-1968-5.0.0-BETA-1503.jar
Forge version: forge-1.9.4-12.17.0.1968-universal.jar
FTB Utilities version: FTBUtilities-1.9.4-2.1.0-pre1.jar

**Comment by gabizou** [comment]
There's not really anything we do with GUIs, so I'm not at all sure of how we're breaking it per say.

**Comment by MrJoki007** [comment]
I think the mod is checking if the mod is on the server too and that check fails

**Comment by gabizou** [comment]
Can you gist the full FML log?

**Comment by MrJoki007** [comment]
Here you go
[fml-server-latest.txt](https://github.com/SpongePowered/SpongeForge/files/340015/fml-server-latest.txt)

**Comment by Zidane** [comment]
Try with just Sponge + FTB utilities. See if it happens.

**Comment by phit** [comment]
Same thing on 1.10.2, not sure if helpful but there seems to be another mod in my pack that does a similar check: craftingtweaks-mc1.9.4-5.0.6

When I log on it says in chat: "This server does not have Crafting Tweaks installed. Functionality may be limited."

Well anyway here's the rest of the versions:
FTBLib-1.9.4-2.1.0-pre2.jar
FTBUtilities-1.9.4-2.1.0-pre2.jar
spongeforge-1.10.2-2026-5.0.0-BETA-1599.jar
forge-12.18.1.2026

I'm gonna open issue for those mods aswell and see if it's maybe on their end.

**Comment by Etheras** [comment]
They're probably gonna need logs, if you can provide in a gist like stated above.

**Comment by LatvianModder** [comment]
It shouldnt break buttons, weird

**Comment by Eufranio** [comment]
It was not detecting server-side mods, here InventoryTweaks stopped work in client-server-side too. But seems fixed in latest SpongeForge builds.
