### ISSUE TITLE
Forge HarvestDropsEvent being passed as ChangeBlockEvent

### ISSUE THREAD

**Issue by dags-** [SpongePowered/SpongeForge#719]
> **Forge:** forge-1.8.9-11.15.1.1890
> **Sponge:** spongeforge-1.8.9-1890-4.2.0-BETA-1509
> **Logs:** [Error log](https://gist.github.com/dags-/3faf396fa9af19b0145adc90f437dd93#file-error-log)
> **Plugins:** [Test plugin](https://gist.github.com/dags-/3faf396fa9af19b0145adc90f437dd93#file-test-java)

Forge's `BlockEvent.HarvestDropsEvent` is being sent to listeners of Sponge's `ChangeBlockEvent`. The latter being cancellable, and the former not. This causes the above error when attempting to cancel the block event.

Seems to be occurring when blocks decay and potentially drop items (unsustainable leaves dropping saplings/apples or w/e).

**Comment by dags-** [comment]
Ok, so: [`HarvestDropsEvent`](https://github.com/MinecraftForge/MinecraftForge/blob/1.8.9/src/main/java/net/minecraftforge/event/world/BlockEvent.java#L45) extends [`BlockEvent`](https://github.com/MinecraftForge/MinecraftForge/blob/1.8.9/src/main/java/net/minecraftforge/event/world/BlockEvent.java#L20), which inherits [`ChangeBlockEvent`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/event/block/ChangeBlockEvent.java#L49) from [`MixinEventBlock`](https://github.com/SpongePowered/SpongeForge/blob/master/src/main/java/org/spongepowered/mod/mixin/core/event/block/MixinEventBlock.java#L52).

There doesn't look to be a Sponge equivalent for `BlockEvent.HarvestDropsEvent`. The forge event just gets passed straight through the eventbus and on to listeners of `ChangeBlockEvent` without being changed to something Cancellable.

Looks like it was [considered here](https://github.com/SpongePowered/SpongeForge/blob/master/src/main/java/org/spongepowered/mod/event/SpongeForgeEventFactory.java#L166) at some point, but the event doesn't pass through this method currently (at-least, not in the trace posted above).

**Comment by Aaron1011** [comment]
This should no longer be an issue, since we no longer mix into Forge events.
