### ISSUE TITLE
[1.8.9] Task Nullpointer Error

### ISSUE THREAD

**Issue by GershonR** [SpongePowered/SpongeForge#721]
Not sure what's causing this error:
http://pastebin.com/5u62XkKw

It just shows up randomly after several hours

Minecraft: 1.8.9
SpongeAPI: 4.2.0-SNAPSHOT-bd51b3a
SpongeForge: 1.8.9-1890-4.2.0-BETA-1511
Minecraft Forge: 11.15.1.1890

Plugins (33): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeForge, ActionBroadcaster, AdminShop, ChangeSkin, Easy Scoreboards, EconomyLite, EssentialCmds, Pixelmon, IVsEVs, ExplosionGuard, FlexibleLogin, Gameshark (Pixelmon), Holograms, keys, Kits, MinecraftMarket, NoFallDamage, NuVotifier, PermissionsEx, Pixel Announcer, Pixel Extras, Pixel Shout, Polis, Project Worlds, RedProtect, Restart Notifier, VotifierListener, SpawnOfPsyduck, Wondertrade

**Comment by Aaron1011** [comment]
@GershonR: It appears to be caused by a null `Slot` being used internally.

Looking at the stack trace, this was caused by attempting to use an item on a block, or attempting to place a block. Do you know if you were using any item in particular when this happened?

**Comment by GershonR** [comment]
Unfortunately I don't know, its caused by the players, i'm not sure what they are doing to cause this, I tried out the latest 1518 build but it still happens on it

**Comment by Aaron1011** [comment]
@GershonR: Would you be able to join `#spongedev` on `irc.esper.net` to help debug this further?

**Comment by GershonR** [comment]
It could be adminshop since it's the only plugin that I updated recently, here's the commits for it:
https://github.com/hsyyid/AdminShop/commit/6954f6e135312f1cf6fafb1e9905b7dcf9bf8ecb

I downgraded now and will see if it pop-up again but I can't reproduce it on my test server

**Comment by GershonR** [comment]
Downgraded but still seems to be showing up, looks like it's the current world state that's the issue
