### ISSUE TITLE
[1.8.9] Crash report on startup

### ISSUE THREAD

**Issue by SnowBlitzz** [SpongePowered/SpongeForge#723]
http://pastebin.com/hN9g4z3x

SpongeForge: 1.8.9-1890-4.2.0-BETA-1521 (on older versions as well, not sure which)
Forge: 11.15.1.1890

**Comment by Aaron1011** [comment]
@SnowBlitzz: Someone else is having this issue, and I've been having an incredibly difficult time tracking it down.

Could you please paste your full logs, along with all plugins/mods (with versions numbers) that you're using?

Also, how frequently does this happen? Does it always occur on startup, or does it happen at random times?

**Comment by SnowBlitzz** [comment]
[2016-07-02-4.log.gz](https://github.com/SpongePowered/SpongeForge/files/344785/2016-07-02-4.log.gz)
[2016-07-02-5.log.gz](https://github.com/SpongePowered/SpongeForge/files/344786/2016-07-02-5.log.gz)
The first one is the logs for a manual restart, the next one is after that manual restart until a crash happened 5 hours later (same crash log)

**Comment by SnowBlitzz** [comment]
clearing the usercache seems to have fixed this, however it needs further testing to be confirmed. I'll update the ticket whenever

**Comment by Zidane** [comment]
1.8.9 is no longer supported. Check this against stable-5 and reopen if still an issue.
