### ISSUE TITLE
[1.10.2] Server crash on player join

### ISSUE THREAD

**Issue by mrAppleXZ** [SpongePowered/SpongeForge#724]
Crash-report: http://pastebin.com/PFHXu4k2
SpongeForge version: 1.10.2-2002-5.0.0-BETA-1529.

**Comment by gabizou** [comment]
Could you zip up the folders for me to test? There's a mod's profession that isn't being registered correctly, which is a problem.

**Comment by mrAppleXZ** [comment]
@gabizou This is not FTB modpack.
Client.zip: [https://drive.google.com/open?id=0B3_ewppkJd3oYW5hdHF4SlJNR2M](url).
Server.zip: [https://drive.google.com/open?id=0B3_ewppkJd3ock1scnBuME5rRW8](url)

**Comment by gabizou** [comment]
Fixed in the next build of SpongeForge (should be build 1534).
