### ISSUE TITLE
[1.10.2] LeavesDecay not being sent to the client automatically.

### ISSUE THREAD

**Issue by cartman-2000** [SpongePowered/SpongeForge#725]
LeavesDecay events aren't being sent to the clients automatically, you have to right click on the block, or do something else to update it for it to fade after you cut down a tree.

Tested on a fresh server with just SpongeForge. The decay works properly when you're running the server without sponge, but appears when you run the server with spong.

**Comment by gabizou** [comment]
Version info?

**Comment by cartman-2000** [comment]
[15:16:43] [Server thread/INFO]: SpongeForge
    Minecraft: 1.10.2
    SpongeAPI: 5.0.0-SNAPSHOT-c641c6c
    SpongeForge: 1.10.2-2002-5.0.0-BETA-1525
    Minecraft Forge: 12.18.0.2005

OS is windows 10 with 1.8.0_91 build of Java.

**Comment by majix560** [comment]
I think I'm having the same problem.
My mods are listed [here](https://www.atlauncher.com/pack/Psionics)

**Comment by cartman-2000** [comment]
Well you can forcibly sync the updates to the client by holding right click on the leaf blocks, but that's a bit annoying to do.

**Comment by majix560** [comment]
Leaf decay is still not being sync'ed to client.
And I'm currently using Beta 1544

**Comment by cartman-2000** [comment]
They added an option to disable it(as an optimization), but but the bug itself hasn't been fixed yet.

**Comment by Aaron1011** [comment]
Moving to SpongeCommon: https://github.com/SpongePowered/SpongeCommon/issues/837
