### ISSUE TITLE
(1.9.4) Block19a101 - Gamerules not applying to nether/end.

### ISSUE THREAD

**Issue by belmenel** [SpongePowered/SpongeForge#727]
As in the title, gamerules set for the server are not functioning in the nether or end. keepInventory isn't a big deal in vanilla where the most you can loose is a bit of diamond nonsense, but in heavily modded games loosing inventory on death kills the fun. Setting keepInventory to true works in the overworld, but doesn't apply to other dimensions, and there doesn't seem to be a way to set gamerules to other dimensions. Would be happy to set it on each dimension if needed, as it seems sponge separates worlds, but being unable to set it for nether/end at all is an obvious problem.

**Comment by Zidane** [comment]
I'll take this as the Vanilla commands are meant to touch all worlds (unless you toggle it off with a mixin plugin found in a PR).

**Comment by belmenel** [comment]
I would think it should. Or at least that there should be some non vanilla commands to use instead. It works in the overworld, and seems to work for other dimensions in other mod packs and in vanilla. The only info i can find is that it seems to be related to something with sponge for handling multiple worlds. Pretty much everything is set to the defaults for block19.
