### ISSUE TITLE
[1.10. 2] Server crash when something is burning(fire spread.)

### ISSUE THREAD

**Issue by cartman-2000** [SpongePowered/SpongeForge#728]
This is triggered when running the 1.10 branch of GriefPrevention on a server, and something is burning on the server(fire spread.). 

I posted the crashlog and trace in the issue report in GP's repository. 
https://github.com/MinecraftPortCentral/GriefPrevention/issues/90

**Comment by gabizou** [comment]
Should be fixed in the latest commits.
