### ISSUE TITLE
Timings report/paste error

### ISSUE THREAD

**Issue by aglarcz** [SpongePowered/SpongeForge#730]
/sponge timings report
/sponge timings paste

Not working for me, error here:
http://pastebin.com/raw/rEmB7vd5

**Comment by ST-DDT** [comment]
This looks like the server is not reachable from your server or the server is currently down/overloaded.

**Comment by aglarcz** [comment]
And whats the adress which is it connecting to?

**Comment by simon816** [comment]
It makes a connection to http://timings.aikar.co

**Comment by ST-DDT** [comment]
Maybe this should be added to the exception message to make it easier to get for admins to check/reproduce.

**Comment by bloodmc** [comment]
Not our issue.
