### ISSUE TITLE
[1.9.4] Forestry farms not working properly.

### ISSUE THREAD

**Issue by LuxusDarkangel** [SpongePowered/SpongeForge#732]
Error Log: https://gist.github.com/LuxusDarkangel/0974c034796f688c88c49cf2a9fd74d3
SpongeForge version: 5.0.0-BETA-1503

It simply can't place or break blocks.

**Comment by gabizou** [comment]
Fixed in newer builds targeting 1.10.2. Not fixing for 1.9.4 as support for 1.9.4 was dropped.
