### ISSUE TITLE
[1.9.4] NPE using Bagginses.

### ISSUE THREAD

**Issue by LuxusDarkangel** [SpongePowered/SpongeForge#734]
Error Log: https://gist.github.com/LuxusDarkangel/8cdf8e888c660b4be27c412d055457e5
SpongeForge version: 5.0.0-BETA-1503

Not sure if it really affects the mod usage, as i'm not able to manually reproduce it, but spams console as hell.

**Comment by gabizou** [comment]
Fixed in newer builds targeting 1.10.2. 1.9.4 support was dropped.

**Comment by LuxusDarkangel** [comment]
Ew... No chance it can be commited to 1.9.4 too?

**Comment by gabizou** [comment]
Unfortunately, it's regardless whether the changes are easily back ported to 1.9.4, we simply don't want to be supporting a system that we've already elected to replace with 1.10.2. With mods already making the jump to 1.10.2, it's futile to keep both 1.9.4 and 1.10.2 up to date with bug fixes.

**Comment by JBYoshi** [comment]
https://forums.spongepowered.org/t/psa-dropping-1-9-4-support/13374
