### ISSUE TITLE
[1.10] Nullpointer in StaticMixinForgeHelper - Armor Modifier

### ISSUE THREAD

**Issue by maxanier** [SpongePowered/SpongeForge#735]
Hello,

my server frequently crashes with the following crashreport:
[http://pastebin.com/PBc5aR0R](http://pastebin.com/PBc5aR0R)

I don't now what happens in game, when the crash occurs, but according to the crashreports its always a EntityTippedArrow.

I'm using spongeforge-1.10.2-2002-5.0.0-BETA-1534, which is not the most recent version, but after checking the changelog, the commits and the StaticMixinForgeHelper itself, I don't think there were any changes made to this since the version was released.

Thank you,
Maxanier

**Comment by gabizou** [comment]
The crash report actually says that a living entity is being attacked, and the NPE is pointing to a mod saying there's an armor property available for an `ItemStack` in a slot, but the `ItemStack` is null when retrieved. This means a mod is doing some side effect stuff or improperly doing something with the armor of an entity when being attacked by an arrow. I'll look into resolving this with the mods listed in the crash report.

**Comment by maxanier** [comment]
Is there a way I can help?

Only thing I can tell you right now is that the hit creature is not a creature of Vampirism since none of Vampirism's entities extends EntityMob

**Comment by maxanier** [comment]
Alright, I've build my own version of SpongeForge containing a try-catch at that position as a workaround. It also includes a logger which logs as much as possible when the NPE is thrown.
I will post the result here when it happens again

**Comment by maxanier** [comment]
Looks like this was fixed (by simply adding a null check).
