### ISSUE TITLE
[1.10]EntityAttribute is missing

### ISSUE THREAD

**Issue by maxanier** [SpongePowered/SpongeForge#736]
Does SpongeForge somehow mess with Minecraft's EntityAttributes?
I'm developing the mod Vampirism and use them there in the same way as Vanilla does by registering them in the entity constructor (within the attach capability event) and then access them using player.getEntityAttribute(VReference.biteDamage) . This works fine by itself, but when it runs on a SpongeForge powered server. player.getEntityAttribute(VReference.bloodExhaustion) sometimes returns null.

Any idea how this can happen? I'm still trying to figure out in which exact cases that happens.

**Comment by gabizou** [comment]
Does the player die at any point in time, or get teleported between worlds?

**Comment by maxanier** [comment]
No, sometimes it e.g. starts happening right after a player connects

I guess you are getting at the fact that entities are recreated (new instance) on death and on changing dimensions.
But the capability instance is also recreated by Vampirism then (which registers the attribute again).

**Comment by maxanier** [comment]
Maybe it is actually a bug in Vampirism, but because it only happened in conjuction with a Sponge powered server yet and I can't explain how this can happen without any external modification, I decided to create a issue here.

If you don't think that SpongeForge messes with them, I will continue my search elsewhere.

**Comment by gabizou** [comment]
Well, I can say that Sponge does prevent the game from recreating entities for teleports and players for deaths. I'm not sure that we do anything specific to attributes, but if there's an event being listened to, it's worthwhile to mention which event as it's possible SpongeForge is silently suppressing the events unintentionally.

**Comment by maxanier** [comment]
OK, I investigated the issue further with that information in mind. It definitively happens also happens when a player dies (not sure about the above mentioned player reconnect anymore, maybe I've misinterpreted the messy log or that is another issue).
As you said the EntityPlayer is not recreated (entity id does not change), but the `AbstractAttributeMap attributeMap` is a new one (at least it's hashcode changes). I guess Sponge is somehow creating a new instance, but Vampirism does not know that it has to re-register the attributes, because the EntityPlayer is not recreated.

I looked through the source of SpongeForge, but could not find anything like that, but since Sponge makes the field public (probably via AT) I suppose it is used somewhere.

**Comment by maxanier** [comment]
This also causes another problem:
All modifier to the vanilla attributes are reset. Thereby vampire players in my mod Vampirism loose their extra health etc., because it is applied only on entity creation or on changes.

Can you make the attributeMap persistent over death, if you are already making the EntityPlayer persist?
