### ISSUE TITLE
[1.10.2] StackOverflow using the chat.

### ISSUE THREAD

**Issue by LuxusDarkangel** [SpongePowered/SpongeForge#737]
Log: https://gist.github.com/LuxusDarkangel/c79c6d18c0403d087bd70efa47897480

**Comment by LuxusDarkangel** [comment]
Ok, not only with plugins but simple chat messages too.

**Comment by kinggoesgaming** [comment]
@LuxusDarkangel mind changing the title accordingly?

**Comment by zml2008** [comment]
This issue was fixed in common -- I just forgot to bump common in SpongeForge

**Comment by Zidane** [comment]
Closing as SF was bumped.
