### ISSUE TITLE
[1.10.2] Drops bug with Forestry installed.

### ISSUE THREAD

**Issue by LuxusDarkangel** [SpongePowered/SpongeForge#738]
Installing Forestry alongside with SpongeForge causes "the Q drop" bug to reappear (You can't drop anything using Q or shift + Q)

No errors appear in console.

**Comment by XileForce** [comment]
can confirm this as well on latest sponge builds. I will add, if you drop something with only one in your hand it appears to duplicate it and give you 2, but it doesnt work beyond that.

**Comment by XileForce** [comment]
further testing with build 1560 seems to show that dropping works fine for most things if there is only 1 in the stack. Example: dropping 1 glass fiber cable works fine, but if i have a stack of 10 glass fiber cables and hit Q it just immediately returns it to my inventory. Sometimes dropping the item makes it disappear as well.

**Comment by Mechy71** [comment]
Build 1570 still has the same issue

**Comment by MastaC729** [comment]
See mezz's comments in the Forestry issue: https://github.com/ForestryMC/ForestryMC/issues/1365

**Comment by kosakriszi** [comment]
Okay, after some further testing, I think I've discovered a potential culprit.
https://github.com/SpongePowered/SpongeForge/blob/bleeding/src/main/java/org/spongepowered/mod/mixin/core/entity/item/MixinEntityItem.java

In this mixin, the EntityItem#onEntityCollideWithPlayer() method is triggering the ForgeEventFactory#onItemPickup(). My theory is that when an item is dropped, the item collides with the players hitbox which immediately triggers the pickup event.
