### ISSUE TITLE
[1.10.02] Can't grow trees

### ISSUE THREAD

**Issue by dakattack** [SpongePowered/SpongeForge#742]
I plant a sapling and they don't ever turn into trees given amble time or even bone meal.  I am on the latest version of sponge, am in survival mode, and the only other mod I have is biomes o plenty.

**Comment by LuxusDarkangel** [comment]
I can't reproduce this. Are you trying it with BoP saplings or vanilla saplings?

**Comment by dakattack** [comment]
you're right it is a BOP issue, my bad

**Comment by Aaron1011** [comment]
@dakattack: Does the issue only occur when Sponge is installed along with BOP? If so, you should re-open this issue.
