### ISSUE TITLE
[1.10.2]Plugins that use mixins are not enabled.

### ISSUE THREAD

**Issue by thomas15v** [SpongePowered/SpongeForge#743]
For my [plugin](https://github.com/thomas15v/NoXray) I used mixins. The mixins itself apply perfectly fine. But the plugin itself doesn't get enabled.

Server Log: http://pastebin.com/zbweANa0. On Sponge Vanilla it works fine.

**Comment by kashike** [comment]
Could you provide a full server log (debug enabled)?

**Comment by thomas15v** [comment]
https://drive.google.com/file/d/0B4cT1XPmcnpKMHVVVHdkQlRzTjQ/view?usp=sharing

**Comment by simon816** [comment]
>
```
[16:40:20] [Server thread/TRACE] [FML/]: Skipping already parsed coremod or tweaker NoXray.jar
```

I think you need to add `FMLCorePluginContainsFMLMod: true` to the `MANIFEST.MF`

**Comment by kashike** [comment]
Add `ForceLoadAsMod: true` or (`FMLCorePlugin: <coremod class>` if it is a coremod) to your `MANIFEST.MF`.

**Comment by thomas15v** [comment]
That did the trick. Thank you.
