### ISSUE TITLE
[SOLVED] Server Crash at start

### ISSUE THREAD

**Issue by Billabonga** [SpongePowered/SpongeForge#745]
http://pastebin.com/1iMQnGe5

**Comment by gabizou** [comment]
Does it still crash without sponge?

**Comment by simon816** [comment]
Looks like it crashed when trying to tell you that there are missing mods.
From the log file:
```
[20:17:02] [Client thread/ERROR] [FML/]: Mod FEI (Forever Enough Items) requires [JEI@[3.7.3,), excore@[1.6.1,2.0)]
```

**Comment by Billabonga** [comment]
Looks like Forever Enough Items was the culprit.... Thanks folks
