### ISSUE TITLE
[1.8.9] Books not keeping format after signing.

### ISSUE THREAD

**Issue by xChristopher210** [SpongePowered/SpongeForge#747]
I was creating a server guide for new players. 40 pages later I finally signed it and saw the horrible format it gave me. It did not stick to the format it was before the signing.
http://i.imgur.com/6h5Hfp4.png

Server Versions:
SpongeForge: 1547
Forge: 1890
Minecraft: 1.8.9
Pixelmon: 4.2.7

**Comment by xChristopher210** [comment]
I tested this on a regular 1.8.9 server by transferring my player file to a new minecraft vanilla world.

The same issue occurs. So it might be a mc bug then? Is it still possible to fix?

**Comment by Zidane** [comment]
1.8.9 is no longer supported. Check this against stable-5 and reopen if still an issue.
