### ISSUE TITLE
[1.10] Can't use water bucket in survival

### ISSUE THREAD

**Issue by maxanier** [SpongePowered/SpongeForge#748]
When I right click with the bucket the water block appears and then disappears and my bucket is still a "water bucket". On the latest bleeding version in survival mode. (No other plugins)
Same problem as [https://github.com/SpongePowered/SpongeForge/issues/685](https://github.com/SpongePowered/SpongeForge/issues/685),
but on 1.10 and apparently caused by something else, because I've checked the code and the fix for the other issue seems to be applied in the latest bleeding code as well.

Interestingly it sometimes works if I spam right click all over the place (persists reconnect, so no sync issue).
I've tested a few code changes in Sponge, but since I don't really now what I'm looking for it did not help

**Comment by maxanier** [comment]
Something else I've noticed, which might be related to this issue:
If you want to eat something you must not look at a block. If you look at one the player starts eating over and over again

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/SpongePowered/SpongeCommon/commit/7563e42f05ac48d72754d28f88c4a14a6b1f4ad9
