### ISSUE TITLE
too many chunks

### ISSUE THREAD

**Issue by aglarcz** [SpongePowered/SpongeForge#749]
Server with java 8 and latest sponge 1.8.9 (build 1547)
Mods used: http://prntscr.com/brl5oh
Timings: https://timings.aikar.co/v2/?id=bb8aa6cddb9541ad930c711ee30e6b1a

Problem:
Few minutes after restart i got too many chunks loaded, for example now with 15 players there are 5500 chunks loaded and server is getting to low TPS. I tried to lower view-distance but without any success to solve this issue - any ideas what could be the problem?

**Comment by LuxusDarkangel** [comment]
Turn on chunk unload logging in sponge config to see if chunks are getting unloaded. If they are, probably a plugin or mod is forcing the chunks to load.

**Comment by aglarcz** [comment]
Few chunks get unloaded but much more is loaded at the same time.
Log with 5 players online, almost 2000 chunks already loaded. 
Any other idea?

**Comment by bloodmc** [comment]
Lower the 'chunk-gc-tick-interval' and raise the 'max-chunk-unloads-per-tick' in sponge's global.conf

**Comment by aglarcz** [comment]
10 players online, still 6500 chunks loaded even with recommended settings
