### ISSUE TITLE
build 1509+ bugs

### ISSUE THREAD

**Issue by aglarcz** [SpongePowered/SpongeForge#752]
When digging into previous issue #749 i found some interesting facts:
1) old build 1508 is stable and without any issues
2) builds 1509 to 1511 have teleport issue, player see sky and nothing more after using any teleport command (home, tp, warp etc.)
3) from build 1518 to 1547 i got TPS drops with more chunks loaded (i made it better by chunk-gc-tick-interval and max-chunk-unloads-per-tick but its still not 100% solved)

Any ideas? Please dont close this issue before its really solved.

**Comment by Aaron1011** [comment]
I'm not quite sure what could be causing this.

@bloodmc: Here are the relevant commit ranges (from 1508 to 1547): https://github.com/SpongePowered/SpongeCommon/compare/6a8a15e9acb08e1a114c3...master and https://github.com/SpongePowered/SpongeForge/compare/3e74daf5744cbf021cd8fae3ed31de5d3aa37b86...master

**Comment by bloodmc** [comment]
@aglarcz Try setting chunk-gc-tick-interval to 0 and also I would need to see a timings report during lag.
Make sure to turn on verbose in your global.conf before running /sponge timings.

**Comment by aglarcz** [comment]
Interval set to 0, problem continues..
Timings during lag (which starts immediately after startup): https://timings.aikar.co/v2/?id=3a4bad39eaa24227a923102e025d2f4e&section=all
It drops from 17-20 TPS (build 1508) to something like 3 TPS (build 1518+) so its not small drop but huge one.

**Comment by bloodmc** [comment]
@aglarcz Hrmm another pixelmon server experienced a similar issue only on restarts and the lag would clear up after a few minutes. The server i'm referring to gets up to 70+ players and has been at 20 TPS using latest builds. Looking at the timings, the pixelmon spawner is using a ton of resources. First try waiting a few minutes to see if lag clears up. If it still happens, try testing with a fresh world. Build 1508 as I said before denied ALL chunk load requests which caused quite a few problems.

**Comment by aglarcz** [comment]
Interesting.. thanks for reply, i will try 4.2.7 and see if it helps. If not i will try other options.. and let you know..

**Comment by bloodmc** [comment]
Make sure you are using latest SpongeForge build. If you still experience issues, report to plugin dev since you are using essentials. Closing as the issue at hand is solved.
