### ISSUE TITLE
Crash with coremod farseek (mod: streams)

### ISSUE THREAD

**Issue by EnderStar** [SpongePowered/SpongeForge#754]
https://github.com/delvr/Farseek/blob/f4c446523b1b4883dba16a9ee401b08d013ebb01/src/main/scala/farseek/world/gen/ChunkGeneratorExtensions.scala

crash log: http://pastebin.com/k24nygqA

**Comment by Aaron1011** [comment]
@EnderStar:The issue is that Farseek completely replaces `GameRegistry#generateWorld`, which Spoonge needs to inject into.

I'll look into submitting a fix.

**Comment by Aaron1011** [comment]
I've opened an issue: https://github.com/delvr/Farseek/issues/16

**Comment by Zidane** [comment]
Closing as this isn't a Sponge issue.
