### ISSUE TITLE
[1.9.4} Forestry multiblock farm cause severe lag

### ISSUE THREAD

**Issue by devryb** [SpongePowered/SpongeForge#755]
Using sponge 1503 and Forestry 1.9.4-5.0.20.167

When the multiblock farm is planting the server log is spammed repeatedly with this and the server lag incredibly hard http://pastebin.com/xbg6rpf2

This is what I see in VisualVM when it lags from this: http://puu.sh/pZSqT/045e803468.png

**Comment by gabizou** [comment]
Already fixed in newer releases.

**Comment by devryb** [comment]
@gabizou is it possible for this fix to be ported to the 1.9.4 branch?

**Comment by kinggoesgaming** [comment]
1.9.4 is no longer supported
