### ISSUE TITLE
Sponge Mixin to FML Launcher prevents mod_list.json mods to be loaded

### ISSUE THREAD

**Issue by Xiphoseer** [SpongePowered/SpongeForge#756]
### Introduction
While testing the new mod_list.json feature in forge, i've encountered the strange behavior, that no other mods have been loaded from a mod_list.json file in a sponge directory, except Sponge. It was even weirder as the first other mod I tried was IC2 which printed stuff to the console, but didn't show up in the mods list. Loading sponge from mod_list.json and other mods from the mods directory works just fine though. And loading all mods (including sponge) from the mods folder works as expected.

### Reproduction
1. Create a mod_list compatible directory structure with some mods.
2. Create a mod_list.json, linking to those mods and put it into the mods folder of a forge 1.10.2-12.18.1.2011 profile
3. Put Spongeforge (I used 1.10.2:2002-5.0.0-BETA-1553, but the issue should be in since January) into the mods folder or the mod_list.json
4. Run the game

### Likely Cause
Sponge mixes into the FML Loader in order to make the plugins directory configurable. [here](https://github.com/SpongePowered/SpongeForge/blob/bleeding/src/main/java/org/spongepowered/mod/mixin/core/fml/common/MixinLoader.java#L75), it redirects a call to the ModDiscoverer to a custom function, recieving the discoverer, the mods directory and an optional array of additional mods, calls the original function, but does not pass on the additional mods array to the function call it replaces.

I believe it is just a matter of replacing `modDiscoverer.findModDirMods(modsDir);` with `modDiscoverer.findModDirMods(modsDir, additionalMods);`. This way, the second argument is not ignored, and the information can pass through.

I guess for the IC2 issue, tweakers/coremods do get loaded before, so the don't get blocked by this problem.

**I am currently running...**
* SpongeForge version: 1.10.2:2002-5.0.0-BETA-1553
* MinecraftForge version: 1.10.2-12.18.1.2011
* Java version: x64 1.8.0_25
* Operating System(s)
 - [x] Windows
 - [ ] Linux (Ubuntu, Debian, Fedora, etc...)
 - [ ] OS X
  
**What is the expected result?** 
All mods from mod_list.json appear in the Mods list
  
**What is the current result?** 
The mods from mod_list.json except Sponge don't appear

**Comment by Mumfrey** [comment]
Oops, I think this is my derp, sorry about that.

On the other hand, it's good to know that people are using the `mod_list` functionality in the wild, this is useful to know.

Also, +1 for such a detailed report, wish we had more of these.
