### ISSUE TITLE
[1.10.2] Egg drop bug with chickens.

### ISSUE THREAD

**Issue by cartman-2000** [SpongePowered/SpongeForge#757]
Chickens on the server don't drop any eggs at all when you have sponge on it.

Tested on a clean test server, it works as expected when running with forge itself, but the chickens no longer dorp any eggs as soon as the server is loaded up with sponge.

Server versions:
[18:40:23] [Server thread/INFO]: SpongeForge
    Minecraft: 1.10.2
    SpongeAPI: 5.0.0-SNAPSHOT-f8895a9
    SpongeForge: 1.10.2-2011-5.0.0-BETA-1560
    Minecraft Forge: 12.18.1.2011

**Comment by LuxusDarkangel** [comment]
Fixed in https://github.com/SpongePowered/SpongeForge/commit/9f85a521315762fe5444f5932079c31ec3429ffe

@Aaron1011 Please, close this.
