### ISSUE TITLE
[1.8.9] Sponge server crash with evilcraft

### ISSUE THREAD

**Issue by NightOps007** [SpongePowered/SpongeForge#759]
Forge log link: Forge log latest only says starting server. Here is link to crashlog: http://pastebin.com/35kfwmc7

Problem: Spong server won't run with evilcraft on it. Evilcraft and spong will work just fine without the other but I can't get them to run together on a server. Did some troubleshooting to be certain it is a conflict with those two. Stripped away all other mods and try to run a server with just evilcraft and it ran fine; with only spong and cyclopscore(required for evilcraft) it also ran fine. Then I put spong together with evilcraft and I got the error again. Unsure if the problem is with spong or evilcraft; am posting to both.

**Comment by ST-DDT** [comment]
Here the remote issue for reference: https://github.com/CyclopsMC/EvilCraft/issues/434
