### ISSUE TITLE
[1.10.2] Sponge not registering Chisel&Bits events.

### ISSUE THREAD

**Issue by LuxusDarkangel** [SpongePowered/SpongeForge#765]
This issue is divided in 2 parts:

1.- If you try to chisel a block inside a protected region (GP, RedProtect, etc), you will get the drop but the block won't be modified.

2.- If the block inside a protected region IS ALREADY chiseled, you will be able to modify it and you will also get the drop.

Chisel and Bits source: https://github.com/AlgorithmX2/Chisels-and-Bits

**Comment by Zidane** [comment]
Re-test with stable-5 and report back if still an issue and we will re-open.

**Comment by xhatz** [comment]
Hello! Still a thing in 1.12.2 latest beta release of Sponge(Forge), using the Chisel (from C&B) in a protected region still gives the bits of the blocks, but does not modify it.

**Comment by TeKGameR950** [comment]
Still happening on latest.

**Comment by TeKGameR950** [comment]
Also we can still modify the block if its already chiseled

**Comment by phit** [comment]
open a new issue please
