### ISSUE TITLE
[1.10.2] Sponge prevents Psi to load player data.

### ISSUE THREAD

**Issue by LuxusDarkangel** [SpongePowered/SpongeForge#766]
If SpongeForge is installed alongside with Psi, the mod won't be able to load your data and you will loose your progress each time you relog.

Steps to reproduce:
1.- Get one Psi level (This can be easily done: Get a CAD Assembler, an Iron CAD Assembly and some redstone dust. Place the CAD Assembler in the world and put the CAD Assembly inside, then get the Casting Assistance Device, throw redstone dust to the ground and right click it with the Casting Assistance Device)
2.- Use your level (Press C, click on the first tutorial and then the check at the right).
3.- Relog and press C again, you will see you've lost the progress.

**Comment by Eufranio** [comment]
Tested and happens here too.

**Comment by Eufranio** [comment]
Tested here, confirm.

**Comment by AnimadorX** [comment]
Same issue here ratata

**Comment by LuxusDarkangel** [comment]
@gabizou Just reminding this exist, there's a workaround for this, but it's very dirty and allows players to cheat levels.

**Comment by josh6259** [comment]
I'm running into something that might be the same as this.... whenever I press "c" to bring up the menu to learn anything it acts as if I haven't made psidust or leveled, even though I did create the cad and psidust, this is preventing me from progressing, and I even tried using admin commands to force myself to "learn" the first tutorial and psidust levels but was unable to progress.

**Comment by Aaron1011** [comment]
I can't reproduce this with the latest SpongeForge. Please re-open this issue if it occurs again.
