### ISSUE TITLE
[1.10.2] Crash with CorrelatedPotentialistics

### ISSUE THREAD

**Issue by LuxusDarkangel** [SpongePowered/SpongeForge#767]
The following crash can happen while treating with CoP disks: https://gist.github.com/LuxusDarkangel/0a70ae544cd508afc13ced14ae7dbbdf

**Comment by LuxusDarkangel** [comment]
This issue was driving me mad, so did a lot of testing with each feature to find what was causing it.

How to reproduce:
1.- Get any drive from Correlated Potentialistics.
2.- Right click with it to open the disk GUI.
3.- Click the Partitioning mode button.

**Comment by LuxusDarkangel** [comment]
Using this patch fixes the issue: https://unascribed.com/f/b52c88f4_CorrelatedPotentialistics-1.1.3-spongefix.jar

**Comment by ryantheleach** [comment]
For anyone curious: https://github.com/elytra/CorrelatedPotentialistics/issues/32
