### ISSUE TITLE
[1.10.2] Psi ticking entity crash

### ISSUE THREAD

**Issue by LuxusDarkangel** [SpongePowered/SpongeForge#769]
Crash report: https://gist.github.com/LuxusDarkangel/c855eaef082d54fb8503a13d34407cd6

**Comment by Aaron1011** [comment]
@LuxusDarkangel: I'm unable to reproduce this with the latest SpongeForge (I created a simple explosive spell, and put in in a projectile bullet). Can you please list the exact steps you took to trigger this crash?

**Comment by LuxusDarkangel** [comment]
It's a crash I got on my production server, so I don't know how it happened (that's why it's not explained in the first post)

I know it's hard to fix if you can't reproduce it, but I had to try.

**Comment by Aaron1011** [comment]
@LuxusDarkangel: From looking at the stacktrace, it's definitely related to using the 'Projectile Bullet' (the item you right-click the Spell Programmer with) - let me know if you're able to consistently reproduce it.

**Comment by bloodmc** [comment]
@LuxusDarkangel This is a mod issue. Tell the dev to add a NPE check.

**Comment by LuxusDarkangel** [comment]
Vazkii just fixed this, update to Psi-r1.0-38 to get the fix.
