### ISSUE TITLE
[1.8.9] SpongeForge 1578 Lookup Service Spam

### ISSUE THREAD

**Issue by GershonR** [SpongePowered/SpongeForge#771]
http://pastebin.com/WmEMD6sU

After the server finishes starting up it spams this until the server runs out of memory

And crash report it made:
http://pastebin.com/3mu2ayH0

**Comment by kashike** [comment]
Should be fixed with https://github.com/SpongePowered/SpongeCommon/commit/13f0bc2ea73943152aed38d944a32786f341b65b.

**Comment by GershonR** [comment]
This still happens with build 1580

**Comment by kashike** [comment]
Try with 1581, please.

**Comment by GershonR** [comment]
22.07 15:20:26 [Server] INFO at org.spongepowered.common.profile.query.UniqueIdQuery$SingleGet.call(UniqueIdQuery.java:64) ~[UniqueIdQuery$SingleGet.class:1.8.9-1890-4.2.0-BETA-1581]
22.07 15:20:26 [Server] INFO at org.spongepowered.common.profile.query.UniqueIdQuery$SingleGet.call(UniqueIdQuery.java:45) ~[UniqueIdQuery$SingleGet.class:1.8.9-1890-4.2.0-BETA-1581]
22.07 15:20:26 [Server] INFO at org.spongepowered.api.util.Functional.lambda$asyncFailableFuture$1(Functional.java:131) ~[Functional.class:1.8.9-1890-4.2.0-BETA-1581]
22.07 15:20:26 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_92]
22.07 15:20:26 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_92]
22.07 15:20:26 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]

**Comment by GershonR** [comment]
Same with 1585:
22.07 23:52:34 [Server] pool-2-thread-3/WARN Couldn't look up profile properties for com.mojang.authlib.GameProfile@5fb41090[id=309b3832-b82c-346e-aa2e-0f2427a3c1ce,name=,properties={},legacy=false]
22.07 23:52:34 [Server] INFO com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
22.07 23:52:34 [Server] INFO at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[YggdrasilAuthenticationService.class:?]
22.07 23:52:34 [Server] INFO at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:175) ~[YggdrasilMinecraftSessionService.class:?]
22.07 23:52:34 [Server] INFO at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:168) ~[YggdrasilMinecraftSessionService.class:?]
22.07 23:52:34 [Server] INFO at net.minecraft.server.management.PlayerProfileCache.lookupByIds(SourceFile:249) ~[lt.class:?]
22.07 23:52:34 [Server] INFO at net.minecraft.server.management.PlayerProfileCache.getOrLookupByIds(SourceFile:284) ~[lt.class:?]
22.07 23:52:34 [Server] INFO at org.spongepowered.common.profile.query.Query.fromUniqueIds(Query.java:70) ~[Query.class:1.8.9-1890-4.2.0-BETA-1585]
22.07 23:52:34 [Server] INFO at org.spongepowered.common.profile.query.UniqueIdQuery$SingleGet.call(UniqueIdQuery.java:64) ~[UniqueIdQuery$SingleGet.class:1.8.9-1890-4.2.0-BETA-1585]
22.07 23:52:34 [Server] INFO at org.spongepowered.common.profile.query.UniqueIdQuery$SingleGet.call(UniqueIdQuery.java:45) ~[UniqueIdQuery$SingleGet.class:1.8.9-1890-4.2.0-BETA-1585]
22.07 23:52:34 [Server] INFO at org.spongepowered.api.util.Functional.lambda$asyncFailableFuture$1(Functional.java:131) ~[Functional.class:1.8.9-1890-4.2.0-BETA-1585]
22.07 23:52:34 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_92]
22.07 23:52:34 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_92]
22.07 23:52:34 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
22.07 23:52:34 [Server] pool-2-thread-1/WARN Couldn't look up profile properties for com.mojang.authlib.GameProfile@1b3d696c[id=bac5f907-0a21-3585-a7e1-f131be7df2c8,name=,properties={},legacy=false]
22.07 23:52:34 [Server] INFO com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
22.07 23:52:34 [Server] INFO at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[YggdrasilAuthenticationService.class:?]
22.07 23:52:34 [Server] INFO at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:175) ~[YggdrasilMinecraftSessionService.class:?]
22.07 23:52:34 [Server] INFO at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:168) ~[YggdrasilMinecraftSessionService.class:?]
22.07 23:52:34 [Server] INFO at net.minecraft.server.management.PlayerProfileCache.lookupByIds(SourceFile:249) ~[lt.class:?]
22.07 23:52:34 [Server] INFO at net.minecraft.server.management.PlayerProfileCache.getOrLookupByIds(SourceFile:284) ~[lt.class:?]
22.07 23:52:34 [Server] INFO at org.spongepowered.common.profile.query.Query.fromUniqueIds(Query.java:70) ~[Query.class:1.8.9-1890-4.2.0-BETA-1585]
22.07 23:52:34 [Server] INFO at org.spongepowered.common.profile.query.UniqueIdQuery$SingleGet.call(UniqueIdQuery.java:64) ~[UniqueIdQuery$SingleGet.class:1.8.9-1890-4.2.0-BETA-1585]
22.07 23:52:34 [Server] INFO at org.spongepowered.common.profile.query.UniqueIdQuery$SingleGet.call(UniqueIdQuery.java:45) ~[UniqueIdQuery$SingleGet.class:1.8.9-1890-4.2.0-BETA-1585]
22.07 23:52:34 [Server] INFO at org.spongepowered.api.util.Functional.lambda$asyncFailableFuture$1(Functional.java:131) ~[Functional.class:1.8.9-1890-4.2.0-BETA-1585]
22.07 23:52:34 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_92]
22.07 23:52:34 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_92]
22.07 23:52:34 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
22.07 23:52:35 [Server] pool-2-thread-1/WARN Couldn't look up profile properties for com.mojang.authlib.GameProfile@70f4073[id=31bb482e-64b5-37f6-94f7-79a7877ecaf6,name=,properties={},legacy=false]
22.07 23:52:35 [Server] INFO com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
22.07 23:52:35 [Server] INFO at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[YggdrasilAuthenticationService.class:?]
22.07 23:52:35 [Server] INFO at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:175) ~[YggdrasilMinecraftSessionService.class:?]
22.07 23:52:35 [Server] INFO at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:168) ~[YggdrasilMinecraftSessionService.class:?]
22.07 23:52:35 [Server] INFO at net.minecraft.server.management.PlayerProfileCache.lookupByIds(SourceFile:249) ~[lt.class:?]
22.07 23:52:35 [Server] INFO at net.minecraft.server.management.PlayerProfileCache.getOrLookupByIds(SourceFile:284) ~[lt.class:?]
22.07 23:52:35 [Server] INFO at org.spongepowered.common.profile.query.Query.fromUniqueIds(Query.java:70) ~[Query.class:1.8.9-1890-4.2.0-BETA-1585]
22.07 23:52:35 [Server] INFO at org.spongepowered.common.profile.query.UniqueIdQuery$SingleGet.call(UniqueIdQuery.java:64) ~[UniqueIdQuery$SingleGet.class:1.8.9-1890-4.2.0-BETA-1585]
22.07 23:52:35 [Server] INFO at org.spongepowered.common.profile.query.UniqueIdQuery$SingleGet.call(UniqueIdQuery.java:45) ~[UniqueIdQuery$SingleGet.class:1.8.9-1890-4.2.0-BETA-1585]
22.07 23:52:35 [Server] INFO at org.spongepowered.api.util.Functional.lambda$asyncFailableFuture$1(Functional.java:131) ~[Functional.class:1.8.9-1890-4.2.0-BETA-1585]
22.07 23:52:35 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_92]
22.07 23:52:35 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_92]
22.07 23:52:35 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]

It spams hundreds of these it pops up every second on the console

**Comment by GershonR** [comment]
The above commit would just slow it down, but it still shows up, anyway to suppress it?

**Comment by inklit** [comment]
This seems very similar to the bug report I posted #776, which was just fixed.  The symptoms were almost exactly the same so maybe you should check if it was fixed in the commit that fixed #776.

**Comment by ST-DDT** [comment]
Maybe being able to specify a proxy/mirror profile resolver can reduce the load on the mojang server.
This might be useful if using multiple servers behind a NAT or on the same server/IP-address.

Each server would ask the mirror profile resolver. If the profile was requested before, its already available on that mirror and can be returned automatically. If not it will be forwarded to the mojang server and the response stored locally.

**Comment by GershonR** [comment]
1591 didn't work as a fix for me:

```
24.07 08:46:19 [Server] pool-2-thread-5/WARN Couldn't look up profile properties for com.mojang.authlib.GameProfile@42e014eb[id=b23fc745-6382-344d-ae93-fc66747ee83c,name=,properties={},legacy=false]
24.07 08:46:19 [Server] INFO com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
24.07 08:46:19 [Server] INFO at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[YggdrasilAuthenticationService.class:?]
24.07 08:46:19 [Server] INFO at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:175) ~[YggdrasilMinecraftSessionService.class:?]
24.07 08:46:19 [Server] INFO at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:168) ~[YggdrasilMinecraftSessionService.class:?]
24.07 08:46:19 [Server] INFO at net.minecraft.server.management.PlayerProfileCache.lookupByIds(SourceFile:249) ~[lt.class:?]
24.07 08:46:19 [Server] INFO at net.minecraft.server.management.PlayerProfileCache.getOrLookupByIds(SourceFile:284) ~[lt.class:?]
24.07 08:46:19 [Server] INFO at org.spongepowered.common.profile.query.Query.fromUniqueIds(Query.java:70) ~[Query.class:1.8.9-1890-4.2.0-BETA-1591]
24.07 08:46:19 [Server] INFO at org.spongepowered.common.profile.query.UniqueIdQuery$SingleGet.call(UniqueIdQuery.java:64) ~[UniqueIdQuery$SingleGet.class:1.8.9-1890-4.2.0-BETA-1591]
24.07 08:46:19 [Server] INFO at org.spongepowered.common.profile.query.UniqueIdQuery$SingleGet.call(UniqueIdQuery.java:45) ~[UniqueIdQuery$SingleGet.class:1.8.9-1890-4.2.0-BETA-1591]
24.07 08:46:19 [Server] INFO at org.spongepowered.api.util.Functional.lambda$asyncFailableFuture$1(Functional.java:131) ~[Functional.class:1.8.9-1890-4.2.0-BETA-1591]
24.07 08:46:19 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_92]
24.07 08:46:19 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_92]
24.07 08:46:19 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
24.07 08:46:27 [Server] Server thread/INFO [io.github.hsyyid.essentialcmds]: [pokemon] executed command tpa beto
24.07 08:46:29 [Server] pool-2-thread-5/WARN Couldn't look up profile properties for com.mojang.authlib.GameProfile@21daa269[id=b23fc745-6382-344d-ae93-fc66747ee83c,name=,properties={},legacy=false]
24.07 08:46:29 [Server] INFO com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
24.07 08:46:29 [Server] INFO at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[YggdrasilAuthenticationService.class:?]
24.07 08:46:29 [Server] INFO at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:175) ~[YggdrasilMinecraftSessionService.class:?]
24.07 08:46:29 [Server] INFO at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:168) ~[YggdrasilMinecraftSessionService.class:?]
24.07 08:46:29 [Server] INFO at net.minecraft.server.management.PlayerProfileCache.lookupByIds(SourceFile:249) ~[lt.class:?]
24.07 08:46:29 [Server] INFO at net.minecraft.server.management.PlayerProfileCache.getOrLookupByIds(SourceFile:284) ~[lt.class:?]
24.07 08:46:29 [Server] INFO at org.spongepowered.common.profile.query.Query.fromUniqueIds(Query.java:70) ~[Query.class:1.8.9-1890-4.2.0-BETA-1591]
24.07 08:46:29 [Server] INFO at org.spongepowered.common.profile.query.UniqueIdQuery$SingleGet.call(UniqueIdQuery.java:64) ~[UniqueIdQuery$SingleGet.class:1.8.9-1890-4.2.0-BETA-1591]
24.07 08:46:29 [Server] INFO at org.spongepowered.common.profile.query.UniqueIdQuery$SingleGet.call(UniqueIdQuery.java:45) ~[UniqueIdQuery$SingleGet.class:1.8.9-1890-4.2.0-BETA-1591]
24.07 08:46:29 [Server] INFO at org.spongepowered.api.util.Functional.lambda$asyncFailableFuture$1(Functional.java:131) ~[Functional.class:1.8.9-1890-4.2.0-BETA-1591]
24.07 08:46:29 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_92]
24.07 08:46:29 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_92]
24.07 08:46:29 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
24.07 08:46:31 [Server] Server thread/INFO [Trainer] Beto: my
24.07 08:46:34 [Server] Server thread/INFO [Trainer] Beto: just pokemon :D
24.07 08:46:34 [Server] pool-2-thread-5/WARN Couldn't look up profile properties for com.mojang.authlib.GameProfile@6a7e217[id=45b421db-e143-391d-b0a6-0e171ceeca6a,name=,properties={},legacy=false]
24.07 08:46:34 [Server] INFO com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
24.07 08:46:34 [Server] INFO at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[YggdrasilAuthenticationService.class:?]
24.07 08:46:34 [Server] INFO at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:175) ~[YggdrasilMinecraftSessionService.class:?]
24.07 08:46:34 [Server] INFO at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:168) ~[YggdrasilMinecraftSessionService.class:?]
24.07 08:46:34 [Server] INFO at net.minecraft.server.management.PlayerProfileCache.lookupByIds(SourceFile:249) ~[lt.class:?]
24.07 08:46:34 [Server] INFO at net.minecraft.server.management.PlayerProfileCache.getOrLookupByIds(SourceFile:284) ~[lt.class:?]
24.07 08:46:34 [Server] INFO at org.spongepowered.common.profile.query.Query.fromUniqueIds(Query.java:70) ~[Query.class:1.8.9-1890-4.2.0-BETA-1591]
24.07 08:46:34 [Server] INFO at org.spongepowered.common.profile.query.UniqueIdQuery$SingleGet.call(UniqueIdQuery.java:64) ~[UniqueIdQuery$SingleGet.class:1.8.9-1890-4.2.0-BETA-1591]
24.07 08:46:34 [Server] INFO at org.spongepowered.common.profile.query.UniqueIdQuery$SingleGet.call(UniqueIdQuery.java:45) ~[UniqueIdQuery$SingleGet.class:1.8.9-1890-4.2.0-BETA-1591]
24.07 08:46:34 [Server] INFO at org.spongepowered.api.util.Functional.lambda$asyncFailableFuture$1(Functional.java:131) ~[Functional.class:1.8.9-1890-4.2.0-BETA-1591]
24.07 08:46:34 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_92]
24.07 08:46:34 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_92]
24.07 08:46:34 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
```

**Comment by inklit** [comment]
The UUID b23fc745-6382-344d-ae93-fc66747ee83cand and 
45b421db-e143-391d-b0a6-0e171ceeca6a do not belong to any Minecraft players (thus invalid) do you know if they belong to a mod's fakeplayer?

**Comment by GershonR** [comment]
I'm not sure, could be an economy or pixelmon

**Comment by GershonR** [comment]
Looks like sometimes it can actually kill the server:
`6.07 22:23:17 [Server] pool-2-thread-846/WARN Couldn't look up profile properties for com.mojang.authlib.GameProfile@10cfbe8d[id=2d5d0cd4-7faa-3a5e-bb48-2d24915d7b46,name=,properties={},legacy=false]
26.07 22:23:17 [Server] INFO com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
26.07 22:23:17 [Server] INFO at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[YggdrasilAuthenticationService.class:?]
26.07 22:23:17 [Server] INFO at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:175) ~[YggdrasilMinecraftSessionService.class:?]
26.07 22:23:17 [Server] INFO at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:168) ~[YggdrasilMinecraftSessionService.class:?]
26.07 22:23:17 [Server] INFO at net.minecraft.server.management.PlayerProfileCache.lookupByIds(SourceFile:249) ~[lt.class:?]
26.07 22:23:17 [Server] INFO at net.minecraft.server.management.PlayerProfileCache.getOrLookupByIds(SourceFile:284) ~[lt.class:?]
26.07 22:23:17 [Server] INFO at org.spongepowered.common.profile.query.Query.fromUniqueIds(Query.java:70) ~[Query.class:1.8.9-1890-4.2.0-BETA-1595]
26.07 22:23:17 [Server] INFO at org.spongepowered.common.profile.query.UniqueIdQuery$SingleGet.call(UniqueIdQuery.java:64) ~[UniqueIdQuery$SingleGet.class:1.8.9-1890-4.2.0-BETA-1595]
26.07 22:23:17 [Server] INFO at org.spongepowered.common.profile.query.UniqueIdQuery$SingleGet.call(UniqueIdQuery.java:45) ~[UniqueIdQuery$SingleGet.class:1.8.9-1890-4.2.0-BETA-1595]
26.07 22:23:17 [Server] INFO at org.spongepowered.api.util.Functional.lambda$asyncFailableFuture$1(Functional.java:131) ~[Functional.class:1.8.9-1890-4.2.0-BETA-1595]
26.07 22:23:17 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_92]
26.07 22:23:17 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_92]
26.07 22:23:17 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
26.07 22:23:21 [Server] Server thread/INFO [nuvotifier]: Votifier disabled.
26.07 22:23:21 [Server] Server thread/INFO Redprotect: [RedProtect disabled.]
26.07 22:23:21 [Server] Server thread/INFO Stopping server
26.07 22:23:21 [Server] Server thread/INFO Saving players
26.07 22:23:21 [Server] Server thread/INFO Saving worlds`

**Comment by GershonR** [comment]
For SpongeForge 1617:

```
27.07 18:16:55 [Server] INFO com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
27.07 18:16:55 [Server] INFO at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[YggdrasilAuthenticationService.class:?]
27.07 18:16:55 [Server] INFO at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:175) ~[YggdrasilMinecraftSessionService.class:?]
27.07 18:16:55 [Server] INFO at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:168) ~[YggdrasilMinecraftSessionService.class:?]
27.07 18:16:55 [Server] INFO at net.minecraft.server.management.PlayerProfileCache.lookupByIds(SourceFile:249) ~[lt.class:?]
27.07 18:16:55 [Server] INFO at net.minecraft.server.management.PlayerProfileCache.getOrLookupByIds(SourceFile:284) ~[lt.class:?]
27.07 18:16:55 [Server] INFO at org.spongepowered.common.profile.query.Query.fromUniqueIds(Query.java:70) ~[Query.class:1.8.9-1890-4.2.0-BETA-1617]
27.07 18:16:55 [Server] INFO at org.spongepowered.common.profile.query.UniqueIdQuery$SingleGet.call(UniqueIdQuery.java:64) ~[UniqueIdQuery$SingleGet.class:1.8.9-1890-4.2.0-BETA-1617]
27.07 18:16:55 [Server] INFO at org.spongepowered.common.profile.query.UniqueIdQuery$SingleGet.call(UniqueIdQuery.java:45) ~[UniqueIdQuery$SingleGet.class:1.8.9-1890-4.2.0-BETA-1617]
27.07 18:16:55 [Server] INFO at org.spongepowered.api.util.Functional.lambda$asyncFailableFuture$1(Functional.java:131) ~[Functional.class:1.8.9-1890-4.2.0-BETA-1617]
27.07 18:16:55 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_92]
27.07 18:16:55 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_92]
27.07 18:16:55 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
27.07 18:17:00 [Server] pool-2-thread-5/WARN Couldn't look up profile properties for com.mojang.authlib.GameProfile@15521080[id=8c72d538-c82d-38ef-bb35-7c46dc0736ff,name=,properties={},legacy=false]
27.07 18:17:00 [Server] INFO com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
27.07 18:17:00 [Server] INFO at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[YggdrasilAuthenticationService.class:?]
27.07 18:17:00 [Server] INFO at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:175) ~[YggdrasilMinecraftSessionService.class:?]
27.07 18:17:00 [Server] INFO at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:168) ~[YggdrasilMinecraftSessionService.class:?]
27.07 18:17:00 [Server] INFO at net.minecraft.server.management.PlayerProfileCache.lookupByIds(SourceFile:249) ~[lt.class:?]
27.07 18:17:00 [Server] INFO at net.minecraft.server.management.PlayerProfileCache.getOrLookupByIds(SourceFile:284) ~[lt.class:?]
27.07 18:17:00 [Server] INFO at org.spongepowered.common.profile.query.Query.fromUniqueIds(Query.java:70) ~[Query.class:1.8.9-1890-4.2.0-BETA-1617]
27.07 18:17:00 [Server] INFO at org.spongepowered.common.profile.query.UniqueIdQuery$SingleGet.call(UniqueIdQuery.java:64) ~[UniqueIdQuery$SingleGet.class:1.8.9-1890-4.2.0-BETA-1617]
27.07 18:17:00 [Server] INFO at org.spongepowered.common.profile.query.UniqueIdQuery$SingleGet.call(UniqueIdQuery.java:45) ~[UniqueIdQuery$SingleGet.class:1.8.9-1890-4.2.0-BETA-1617]
27.07 18:17:00 [Server] INFO at org.spongepowered.api.util.Functional.lambda$asyncFailableFuture$1(Functional.java:131) ~[Functional.class:1.8.9-1890-4.2.0-BETA-1617]
27.07 18:17:00 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_92]
27.07 18:17:00 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_92]
27.07 18:17:00 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
```

**Comment by inklit** [comment]
I've confirmed that this is an issue with FakePlayer's created by mods.
I've let a developer of a mod that is affected by this know about the bug and hopefully this can be fixed.
https://github.com/SquidDev-CC/plethora/issues/11
Here is the same issue opened on that specific mod's github for reference.

In particular this code is causing this spam to happen:
https://github.com/SquidDev-CC/plethora/blob/50ddf64b9834ace4b0b1802148b15ffbf0f82142/src/main/java/org/squiddev/plethora/gameplay/PlethoraFakePlayer.java

**Comment by inklit** [comment]
According to the developer of that mod, the way to fix this is to add the mod's UUID to the `invalid-lookup-uuids` configuration option in Sponge.

**Comment by GershonR** [comment]
This seems to still be happening with

SpongeForge: 1.10.2-2107-6.0.0-BETA-1873

http://pastebin.com/2K5Ckh9Z
