### ISSUE TITLE
[1.10.02] Sleeping at night does not change time

### ISSUE THREAD

**Issue by dakattack** [SpongePowered/SpongeForge#775]
This happens very often but not every single night, so obviously needs more testing to see what is the cause.  Sometimes, when everybody on the server is in bed, even if there is only one person on the server, the time does not turn to day.  I have to manually use slash time set which is obviously a problem because I am not on the server all of the time, and I don't want to allow my friends to use that command.  Issue is resolved upon a server restart, which once again is clearly not optimal.

**Comment by gabizou** [comment]
Any mods or plugins installed?

**Comment by dakattack** [comment]
biomesoplenty as far as forge goes, essentialcmds, permissionsex for sponge.  sometimes it will happen even when I am the only one on the server, being OP, so I dont think it is a permissions issue of any sort

**Comment by bloodmc** [comment]
@dakattack I cannot reproduce this. Open another ticket if you reproduce it with latest builds.
