### ISSUE TITLE
1.10 incorrect explosion effect

### ISSUE THREAD

**Issue by loveyanbei** [SpongePowered/SpongeForge#777]
I was blown up by creeper and flied in to high sky,unreasonable high.

**Comment by loveyanbei** [comment]
Look different from spigot implementation uhhh.

**Comment by loveyanbei** [comment]
OK,I tried again and got this 
![2016-07-24_11 28 25](https://cloud.githubusercontent.com/assets/7147471/17081615/5894291e-5192-11e6-9e0a-d0ea5b5ef010.png)
![2016-07-24_11 28 29](https://cloud.githubusercontent.com/assets/7147471/17081614/58913628-5192-11e6-9e98-e71aab8232b9.png)
Explosion by creeper brought me to Y = 130.

**Comment by Aaron1011** [comment]
@loveyanbei: Thanks for reporting this! It should be fixed in the latest SpongeForge.
