### ISSUE TITLE
NPE when a player joins, crashes server. [1.8.9-1890-4.2.0-BETA-1583]

### ISSUE THREAD

**Issue by Xwaffle1** [SpongePowered/SpongeForge#779]
Super weird crash, it's entirely Base Minecraft, so I assume those editing base Minecraft might know a thing or two about this crash report. I am running Pixelmon, yet this stack trace contains nothing from Pixelmon that would make me assume it's Pixelmon.

The issue did not occur until we updated.

http://pastebin.com/aWu4Ynsq

**Comment by JBYoshi** [comment]
@Xwaffle1 Sponge does add some methods to base Minecraft classes; `setLocationAndAngles` is one of them. So yes, it is Sponge's fault.

**Comment by Zidane** [comment]
Retest with latest build.
