### ISSUE TITLE
[1.10.2] - Too Many Monsters

### ISSUE THREAD

**Issue by loveyanbei** [SpongePowered/SpongeForge#780]
![2016-07-24_11 33 59](https://cloud.githubusercontent.com/assets/7147471/17081635/98db3008-5192-11e6-8148-d2faf053d4fd.png)
They are naturally generated.
![2016-07-24_11 37 42](https://cloud.githubusercontent.com/assets/7147471/17081648/16e6d0d8-5193-11e6-9ac4-0caf389adefb.png)

**Comment by gabizou** [comment]
Version info?

**Comment by loveyanbei** [comment]
1.10.2server

**Comment by gabizou** [comment]
Any mods/plugins installed?

**Comment by loveyanbei** [comment]
I hooked lightning strike event and create explosion or zombie pigmen by chance.But I found the world full of zombies and creepers.

**Comment by loveyanbei** [comment]
Source

package dogop.bloodmoon;

import com.flowpowered.math.vector.Vector3d;
import org.spongepowered.api.Server;
import org.spongepowered.api.block.BlockType;
import org.spongepowered.api.block.BlockTypes;
import org.spongepowered.api.data.key.Keys;
import org.spongepowered.api.data.type.HandTypes;
import org.spongepowered.api.data.value.mutable.Value;
import org.spongepowered.api.entity.Entity;
import org.spongepowered.api.entity.EntityTypes;
import org.spongepowered.api.entity.living.monster.Skeleton;
import org.spongepowered.api.entity.living.monster.ZombiePigman;
import org.spongepowered.api.entity.weather.Lightning;
import org.spongepowered.api.event.Listener;
import org.spongepowered.api.event.action.LightningEvent;
import org.spongepowered.api.event.cause.Cause;
import org.spongepowered.api.event.cause.entity.spawn.EntitySpawnCause;
import org.spongepowered.api.event.cause.entity.spawn.SpawnType;
import org.spongepowered.api.event.cause.entity.spawn.SpawnTypes;
import org.spongepowered.api.item.ItemType;
import org.spongepowered.api.item.ItemTypes;
import org.spongepowered.api.item.inventory.ItemStack;
import org.spongepowered.api.item.inventory.ItemStackGenerator;
import org.spongepowered.api.text.BookView;
import org.spongepowered.api.world.Location;
import org.spongepowered.api.world.World;
import org.spongepowered.api.world.explosion.Explosion;
import org.spongepowered.api.world.extent.Extent;

import java.util.Optional;
import java.util.Random;
import java.util.Vector;

public class LightningStrikeListener
{
    @Listener
    public void onLightningStrike(LightningEvent.Strike event)
    {
        System.out.println(event.getClass());
        LightningEvent.Strike e = event;

        Lightning bolt = (Lightning) e.getCause().all().get(0);
        BloodMoonSummonController.LightningEventControl(bolt);
    }
}
class PositionCheckHelper{
    static boolean check_can_cube_spawn(World world, Location location, int size)
    {
        int beginX = (int)(location.getX() - Math.ceil(size / 2));
        int beginY = (int)(location.getY());
        int beginZ = (int)(location.getZ() - Math.ceil(size / 2));
        int xy_count = (int)(2 * Math.ceil(size / 2));
        for(int i = 0; i < xy_count; i++)
        {
            for(int j = 0; j < size; j++)
            {
                for(int k = 0 ; k < xy_count; k++)
                {
                    if(world.getBlock(beginX + i, beginY + j, beginZ + k).getType() != BlockTypes.AIR)
                    {
                        beginY = beginY + j + 1;
                        Vector3d pos = new Vector3d(location.getX(),beginY,location.getZ());
                        location.setPosition(pos);
                        i = 0;
                        j = 0;
                        k = 0;
                    }
                }
            }
        }
        return true;
    }
}
class BloodMoonSummonController
{
    static Explosion.Builder bu = Explosion.builder()
            .canCauseFire(true)
            .shouldBreakBlocks(true)
            .shouldPlaySmoke(true);
    static float spawn_zombie_pigman_general = 0.1f;
    static float spawn_zombie_pigman_elite = 0.15f;
    static float spawn_magma_cube = 0.2f;
    static float spawn_blaze = 0.3f;
    static float spawn_wither_skull = 0.4f;
    static float spawn_elite_skull = 0.5f;
    static float spawn_creeper_powered = 0.6f;
    static float spawn_ghast = 0.7f;
    static float spawn_ghast_elite = 0.75f;
    static float spawn_killer_rabbit = 0.9f;
    static float spawn_zombie_elite = 1;

    static boolean BloodMoon = false;

    static float chance_nothing = 0.8f;
    static float chance_explosion = 0.9f;
    static float chance_big_explosion = 0.95f;
    static ItemStack.Builder ItemStackBuilder = ItemStack.builder();
    static Random random = new Random(System.currentTimeMillis());
    static void LightningEventControl(Entity entity) {
        float roll = random.nextFloat();
        Location location = entity.getLocation();
        System.out.println(roll);
        if(roll < chance_nothing)
        {
            return;
        }
        else if(roll > chance_nothing && roll <= chance_explosion) {
            bu.radius(1);
            bu.location(location);
            Explosion ex = bu.build();
            ex.getWorld().triggerExplosion(ex);
            System.out.println("explode_small");
        }
        else if(roll > chance_explosion && roll < chance_big_explosion)
        {
            bu.radius(5);
            bu.location(location);
            Explosion ex = bu.build();
            ex.getWorld().triggerExplosion(ex);
            System.out.println("explode_big");
        }
        else
        {
            //spawn monster
            int max = 0;
            if(BloodMoon)
            {
                max = (int) Math.ceil(3 * random.nextFloat());
            }
            else
            {
                max = (int) Math.ceil(6 * random.nextFloat());
            }
            Extent ext = location.getExtent();
            Optional<Entity> opt = ext.createEntity(EntityTypes.SKELETON,location.getPosition());
            if(opt.isPresent())
            {
                Skeleton skt = (Skeleton) opt.get();

                ItemStack PlainBow = ItemStack.builder()
                        .itemType(ItemTypes.BOW).build();
                skt.setItemInHand(HandTypes.MAIN_HAND, PlainBow);
                ext.spawnEntity(skt, Cause.source(EntitySpawnCause.builder().entity(skt).type(SpawnTypes.PLUGIN).build()).build());
            }
            roll = random.nextFloat();
            for(int i = 0; i < max; i++)
            {
                if(roll < spawn_zombie_pigman_general)
                {
                    opt = ext.createEntity(EntityTypes.PIG_ZOMBIE,location.getPosition());
                    if(opt.isPresent()) {
                        ZombiePigman pigmman = (ZombiePigman)opt.get();
                        ItemStack PlainGoldSword = ItemStack.builder()
                                .itemType(ItemTypes.GOLDEN_SWORD).build();
                        pigmman.setItemInHand(HandTypes.MAIN_HAND, PlainGoldSword);
                        pigmman.setScaleForAge();
                        pigmman.offer(Keys.ANGRY,true);
                        System.out.println(pigmman.getValues());
                        ext.spawnEntity(pigmman, Cause.source(EntitySpawnCause.builder().entity(pigmman).type(SpawnTypes.PLUGIN).build()).build());
                    }
                }
                else if(roll > spawn_zombie_pigman_general && roll < spawn_zombie_pigman_elite)
                {
                    opt = ext.createEntity(EntityTypes.PIG_ZOMBIE,location.getPosition());
                    if(opt.isPresent()) {
                        ZombiePigman pigmman = (ZombiePigman)opt.get();
                        float mroll = random.nextFloat();
                        ItemStack ItemInHand = null;
                        if(mroll < 0.1) {
                            ItemInHand = ItemStackBuilder.itemType(ItemTypes.BOW).build();
                            //ItemInHand.
                        }
                        else
                        {
                            ItemInHand = ItemStack.builder()
                                    .itemType(ItemTypes.DIAMOND_SWORD).build();
                        }
                        pigmman.setItemInHand(HandTypes.MAIN_HAND, ItemInHand);
                        pigmman.offer(Keys.ANGRY,true);
                        System.out.println(pigmman.getValues());
                        ext.spawnEntity(pigmman, Cause.source(EntitySpawnCause.builder().entity(pigmman).type(SpawnTypes.PLUGIN).build()).build());
                    }
                }

                //else if(roll > spawn_zombie_pigman_general && roll < spawn_zombie_pigman_elite)
                //{

                //}
            }


        }
    }
}

**Comment by loveyanbei** [comment]
package dogop.bloodmoon;
import org.spongepowered.api.Sponge;
import org.spongepowered.api.entity.Entity;
import org.spongepowered.api.event.Listener;
import org.spongepowered.api.event.action.LightningEvent;
import org.spongepowered.api.event.game.state.GameStartedServerEvent;
import org.spongepowered.api.event.game.state.GameStoppedServerEvent;
import org.spongepowered.api.plugin.Plugin;
/**
 * Created by lyt on 16-7-22.
 */
@Plugin(id="bloodmoon-dogeop",name="BloodMoon",version="1.0")
public class BloodMoon {
    @Listener
    public void onServerStart(GameStartedServerEvent event)
    {
        Sponge.getEventManager().registerListeners(this,new LightningStrikeListener());
    }
    @Listener
    public void onServerStop(GameStoppedServerEvent event)
    {

    }
}

**Comment by gabizou** [comment]
Please use https://gist.github.com/ to paste classes such as that to preserve indentation properly.

**Comment by LuxusDarkangel** [comment]
I can confirm mob spanwing rate is higher in sponge than vanilla. Probably a few options to configure mob spawning such as maximum mobs per world, maximum mobs per type, near the user, etc would be helpful (Spigot/Bukkit implemented some of this options too).

Here a few more screenshots one of the users took in my server:

https://i.gyazo.com/e17c32c8bfd43161d5a3574aaec88023.jpg
https://i.gyazo.com/702305e769b59ac106504b00493ce4eb.jpg

(In the second one, look at the entities in F3)

**Comment by LuxusDarkangel** [comment]
@gabizou Any progress on this? It's killing TPS very hard.

**Comment by Zidane** [comment]
@LuxusDarkangel 

For the life of me, I cannot reproduce.

**Comment by LuxusDarkangel** [comment]
@Zidane You can't trigger it, it just... happen. As I said, config options to limit mobs should fix it, but I guess it's not easy to implementación.

**Comment by Zidane** [comment]
@LuxusDarkangel 

Its easy to implement but the fact of the matter is Vanilla DOES have spawn limits so why are they not working...

**Comment by LuxusDarkangel** [comment]
@Zidane Oh, nice point.

**Comment by Zidane** [comment]
@LuxusDarkangel 

Any mods/plugins installed?

**Comment by LuxusDarkangel** [comment]
Yeah, a lot: https://timings.aikar.co/v2/?id=4fe12a0839e9493c8a2da1395aacecf4&section=plugins

**Comment by bloodmc** [comment]
Update to latest SF builds.
