### ISSUE TITLE
[1.8.9] Tinkers Construct inventory events

### ISSUE THREAD

**Issue by hunter688** [SpongePowered/SpongeForge#781]
Found bug related or similar to #738 but with TinkerConstruct for 1.8.9 (items from Creative tab named Tinkers' Tools)

When try to drop any item from this tab using Q, item is duplicated - dropped to ground and stay in the inventory too.

Im tried make workaroud cancelling DropItemEvent.Dispense event for affected items, but when try drag item from the creative inventory, cannot, due item use this event. Without my workaround these items are immediatelly dropped to ground when try take from creative inventory to player inventory.
Maybe it is due TC items contains some NBT data...

http://pastebin.com/676pDRa3

Others items/blocks are ok (others mods, vanilla etc).

Spongeforge 1586

**Comment by bloodmc** [comment]
This is no longer an issue in latest 1.10.2 builds.
