### ISSUE TITLE
[1.10.2] Some interaction between Progressive Automation and SpongeForge causes remapping issues with overridden Redirects.

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeForge#783]
Error: http://prntscr.com/bx1txs
Running 1.10.2 server with latest SpongeForge, and latest Progressive Automation (1.6.49).

**Comment by allanf181** [comment]
same issue here

**Comment by AnimadorX** [comment]
Same issue here!

**Comment by gabizou** [comment]
Can you start the server with the flags: `-Dmixin.debug.export=true` at which point in the server's run directory, you'll find a folder that's generated named `.mixin.out`, please zip the contents of the folder and upload it for us to analyze.

**Comment by Eufranio** [comment]
I put it in my server start script, here:
```
while :
do
java -noverify -d64 -server -XX:+UseNUMA -XX:StringTableSize=10003 -XX:+UseG1GC -XX:+OptimizeStringConcat -XX:+TieredCompilation -XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=1024m  -XX:+AggressiveOpts -XX:MaxGCPauseMillis=100 -XX:+UseStringDeduplication -Xms3G -Xmx3G -XX:hashCode=5 -Dfile.encoding=UTF-8 -jar custom.jar nogui --log-strip-color -Daffinity.reserved=80 -Dmixin.debug.export=true
sleep 2
done
```
But it didn't generate any folders.

**Comment by kenzierocks** [comment]
It must go before the `-jar`.

**Comment by Eufranio** [comment]
Done. All the files in .mixin.out and directories are [here.](http://accretion.us/frani/report.zip)

**Comment by gabizou** [comment]
Thank you very much for the zip. We've found that this is in fact an issue with Mixins, however really well hidden, so a fix will be available soon. For now however, you can use the flag: `-Dmixin.debug.disableHandlerRename=true` and the server should start up without the crash. It's not a fix, just a workaround for now.

**Comment by Eufranio** [comment]
Okay, thank you!
What will be stopped by using this?

**Comment by Eufranio** [comment]
Happening with Hovering Hourglass too. http://prntscr.com/bxtscv
I'll keep that issue open by a while

**Comment by gabizou** [comment]
Are you using the same flags?

**Comment by Eufranio** [comment]
I deleted -Dmixin.debug.export=true and put -Dmixin.debug.disableHandlerRename=true

**Comment by gabizou** [comment]
IF you can have both flags, and if it still crashes, re-upload that `.mixin.out` folder.

**Comment by Eufranio** [comment]
Yeah, the server started with no errors, but the world disapppeared and everyone is freezed. I think this is a sponge security feature, right?
Well, we can't play that way, so i'll wait the fix.

**Comment by gabizou** [comment]
Uhhhh, no, that's not a feature..... Please zip up that classes folder and the log so we can look into that as a possible separate issue.

**Comment by Eufranio** [comment]
Nothing appeared in the folder .mixin.out: http://prntscr.com/bxuhdx
Here is the world, when i or other person join the server: http://prntscr.com/bxuhvc
[Here](http://accretion.us/frani/fml-server-3.log) is the latest forge log (since start to i type /stop)
And here is the start script:
```
while :
do
java -noverify -d64 -server -XX:+UseNUMA -XX:StringTableSize=10003 -XX:+UseG1GC -XX:+OptimizeStringConcat -XX:+TieredCompilation -XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=1024m  -XX:+AggressiveOpts -XX:MaxGCPauseMillis=100 -XX:+UseStringDeduplication -Xms3G -Xmx3G -XX:hashCode=5 -Dfile.encoding=UTF-8 -Dmixin.debug.export=true -Dmixin.debug.disableHandlerRename=true -jar custom.jar nogui --log-strip-color -Daffinity.reserved=80
sleep 2
done
```

**Comment by gabizou** [comment]
Your vm flag `-Daffinity.reserved=80` should be before the `-jar` flag. Otherwise it's a program argument, which likely isn't what whatever is looking for that is looking for.

**Comment by Eufranio** [comment]
Okay, the classes are [here.](http://accretion.us/frani/report2.zip)

**Comment by gabizou** [comment]
Even with classes exported, there shouldn't be an issue, but on join, nothing loads?

**Comment by Eufranio** [comment]
Yep. I can talk, run commands, teleport, etc, but the world doesn't load. Even after a restart. It happens only if SpongeForge is loaded/installed.

**Comment by gabizou** [comment]
And without the mixin flags and only SpongeForge + ProgressiveAutomation, the server still crashes?

**Comment by Eufranio** [comment]
@gabizou  Nope, the server doesn't crash since i use the last mixin flag, but it doesn't load the world.
With only SpongeForge and Progressive Automation: http://prntscr.com/bxvpat
There is no errors in console.

**Comment by Eufranio** [comment]
GOD!!! It's fixed in the last version of SpongeForge!

**Comment by gabizou** [comment]
@Eufranio is that with the mixin flags or without?

**Comment by Eufranio** [comment]
@gabizou without mixin flags it works and load but still spamming errors, with the flags it worked fine. But the errors still present, i created a new and separated issue for it: #790

**Comment by gabizou** [comment]
It's still the same issue.
