### ISSUE TITLE
NoSuchMethodException

### ISSUE THREAD

**Issue by kinggoesgaming** [SpongePowered/SpongeForge#784]
https://gist.github.com/kinggoesgaming/41e03078a9adef87a87fbf7ffbb63fef

I am running dev environment with latest bleeding branch of SF

**Comment by gabizou** [comment]
Check your plugin is using the right API dependency. It sounds as though your plugin compiled against an older version of the methods or a version of which the method had a certain signature. Not a sponge issue.

**Comment by kinggoesgaming** [comment]
This seemingly works in production server

**Comment by kinggoesgaming** [comment]
ok i think i figured it out
