### ISSUE TITLE
[1.8.9] Server not saving on crash

### ISSUE THREAD

**Issue by xChristopher210** [SpongePowered/SpongeForge#785]
I have an issue with the server crashing but when it does it rolls back to the last point the world was saved. Dont get me wrong but I know it would save right before it did and everything was just fine. I updated about 40 builds and this issue started occurring. 

Im currently on:
Spongeforge 1584
Forge 1890
Pixelmon 4.2.7

**Comment by gabizou** [comment]
The game never is able to save during a hard crash. That's why the game crashes and there's a rollback. Unless there's a stack trace or crash report that we can look at and maybe identify whether it's Sponge's fault for the game crashing, there's not much to fix here.

**Comment by bloodmc** [comment]
As gabizou stated, there is nothing we can do about that. If you want to protect yourself from crashes then save more frequently by altering the autosave tick interval in your config. You are also using a bugged version with pistons causing crashes, update to latest.
