### ISSUE TITLE
[1.10.2] Visual bug

### ISSUE THREAD

**Issue by FiveEYZ** [SpongePowered/SpongeForge#786]
Placing the Eye of Ender in End Portal dont show the open portal.
(it still works tho and you can jump thru, but you cant see it)

relogging or change dimension fixes it and you will see the portal

Killing the ender dragon dont visual show the portal
(it still works tho and you can jump thru, but you cant see it)
https://i.gyazo.com/8c5de7e67cb9094c9f90267b5930be08.png

relogging or change dimension fixes it and you will see the portal

Also i would like to add that nothing happens when i walk over a pressure plate not even a redstone signal, and placing them next to a door makes the door bug out (can hear the door open/close when i walk on and off it).
other players cant see a door being used by others.

All was tested with:
spongeforge-1.10.2-2026-5.0.0-BETA-1599
forge-1.10.2-12.18.1.2026-universal

**Comment by TBlueF** [comment]
Note: Another case where this happens is the frost_walker enchantment.

**Comment by TBlueF** [comment]
@gabizou 
The frost_walker enchantment still creates ghost-blocks. _(it also does not fire any BlockChangeEvent)_

_(tested with a freshly pulled version through eclipse, so the version should be up to date, i hope)_
