### ISSUE TITLE
HQM-Sponge server crash MC-1.10.2

### ISSUE THREAD

**Issue by knoxhack** [SpongePowered/SpongeForge#787]
https://gist.github.com/knoxhack/2a17fda98004e7b2a5641330d2b3287d

**Comment by Aaron1011** [comment]
The issue appears to be that Sponge is firing `WorldEvent.Load` for a world before it's added to `MinecraftServer#worldServers`. On a plain Forge servers, the world has already been added to that array.

**Comment by gabizou** [comment]
@Zidane I think this is your realm of expertise.
