### ISSUE TITLE
[1.10.2] Exception trying to process over a phase (EnderIO)

### ISSUE THREAD

**Issue by LuxusDarkangel** [SpongePowered/SpongeForge#789]
Sometimes EnderIO's capactior banks will stop sending/receiving energy and console shows this in the log: https://gist.github.com/LuxusDarkangel/ce8d7521719fa1e440c75720fc4b6eae

**Comment by gabizou** [comment]
Sponge version info?

**Comment by LuxusDarkangel** [comment]
Latest (1601)

**Comment by gabizou** [comment]
Alright, I'll give a look over, I was sure that I fixed this sort of issue before.

**Comment by LuxusDarkangel** [comment]
I reported a few from different mods. In which versión you added the fix?

**Comment by gabizou** [comment]
I added the fix quite a few builds back, namely with resolving #710

**Comment by LuxusDarkangel** [comment]
I'm not at home, so I thought maybe I made a mistake and it's not latest, but that fix is from the 1.9.4 era.

**Comment by gabizou** [comment]
Nope, this is a different event handling. I'll have a fix out momentarily.

**Comment by gabizou** [comment]
@LuxusDarkangel look out for the next build with that fix (you should see the commit message in the changelog for that build).

**Comment by gabizou** [comment]
@LuxusDarkangel wait to use that build as there's a bug that I forgot to fix in relation to the event.

**Comment by gabizou** [comment]
@LuxusDarkangel 1604 should do the trick.

**Comment by LuxusDarkangel** [comment]
Oh, okay. This isn't something I could reproduce, just happened sometimes, so I guess we can close this.

I will report back if it happens again.
