### ISSUE TITLE
[1.10.2] Can't catch some block changes

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeForge#790]
This is being spamming in my log: http://prntscr.com/bxwh30
Everything is working fine, at least what i realized.
It throw a new error when someone stand in a pressure plate too, or a door: http://prntscr.com/bxwiir
Or when a turtle try to move: http://prntscr.com/bxwk9g

**Comment by LuxusDarkangel** [comment]
Sponge version?

**Comment by Eufranio** [comment]
SpongeForge version: 5.0.0-BETA-1604
Forge version: 12.18.1.2026
