### ISSUE TITLE
[1.10.2] Item drop is very fast

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeForge#791]
In 1.10.2, running SpongeForge build 1606, i can't drop items, they return to my inventory.
Easili reproducible just pressing Q with a item in hand. The 'collect' is very fast, then the item is not even throwed.

**Comment by FiveEYZ** [comment]
if there is only 1 of the item you wanna throw on the hotbar and none in the inventory then u can throw it with Q
as soon as you have multiple of the same item in your inventory there will be problems when you try to drop it

**Comment by LuxusDarkangel** [comment]
This is a problem with Forestry, next time test if you can reproduce it without mods/plugins and without sponge to determine the problem.

Here is the issue: [#738](https://github.com/SpongePowered/SpongeForge/issues/738)

**Comment by FiveEYZ** [comment]
forestry with sponge = bug
forestry without sponge = no bug
sponge without forestry = no bug

nothing in logs

tested with: 
forestry_1.10.2-5.2.3.212
spongeforge-1.10.2-2026-5.0.0-BETA-1604

**Comment by hunter688** [comment]
It looks like something wrong with dropping items not only in the 1.10. See #781

**Comment by LuxusDarkangel** [comment]
@hunter688 #781 doesn't happen in 1.10.2. It's not something wrong with dropping items in general, only with Forestry.

**Comment by Zidane** [comment]
@Aaron1011 Test this with ONLY us + Forestry.

**Comment by kosakriszi** [comment]
As commented on a previous bug report for this same issue (not sure why there are 2), here are Mezz' comments and some further testing info: https://github.com/ForestryMC/ForestryMC/issues/1365

**Comment by Eufranio** [comment]
@gabizou

**Comment by gabizou** [comment]
Closing since this is a duplicate of #738
