### ISSUE TITLE
[1.10.2] Botania flowers can't interact with world

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeForge#792]
In my server using SpongeForge b1606, my Botania flowers can't interact with the world:
Screenshots:
http://prntscr.com/bxxqgh
http://prntscr.com/bxxrbg

**Comment by FiveEYZ** [comment]
they also cant make living stone/wood 

you can see the "effect" but nothing happens with the stone/wood

**Comment by gabizou** [comment]
Any errors or exceptions in the log? What is supposed to happen versus what's happening in this picture?

**Comment by Eufranio** [comment]
First picture: The Gourmaryllis is supposed to eat the foods, but they stay there, dropped, nothing happens.
Second picture: Hopperhock should collect dropped items from the ground, but they still there, it can't collect.
About livingrock/stone, Pure Daisies are supposed to change WOOD to LIVINGWOOD, but the block doesn't change. The particles shows like if it is being changed, but nothing happens and the blocks doesnt change.

**Comment by Eufranio** [comment]
Still present in latest SpongeForge build.

**Comment by LuxusDarkangel** [comment]
A bit more of info: The change causing this bug was added between builds 1570 (works fine) and 1588 (the bug appears). I can't point to the exact build because they're not available to download.

**Comment by inklit** [comment]
http://files.minecraftforge.net/maven/org/spongepowered/spongeforge/
Click the "Show All Downloads" button.

**Comment by LuxusDarkangel** [comment]
@inklit I did. Builds 1571 to 1587 are still missing. Probably failed builds or something.

**Comment by FiveEYZ** [comment]
@LuxusDarkangel look at 1.8.9 then u will find Build 1571 to 1587

**Comment by Aaron1011** [comment]
@Eufranio: I'm unable to reproduce this with the latest SpongeForge for 1.10.2 (build 1632). Can you re-test on that build?

**Comment by LuxusDarkangel** [comment]
@Aaron1011 Keeps happening. Used a Pure Daisy to test: surrounded it with stone and waited until it did the animation, but stone is not converted into livingrock.

**Comment by Aaron1011** [comment]
Sorry, I should have been more specific - I wasn't able to reproduce the Gourmaryllis issue. Let me test the Pure Daisy issue again.

**Comment by Aaron1011** [comment]
@LuxusDarkangel: I'm also unable to reproduce the Pure Daisy issue with SpongeForge (stone converted into livingrock just fine).

**Comment by FiveEYZ** [comment]
seems to have been pre-313 botania issue...

on the latest release from 1 day ago https://github.com/williewillus/Botania/releases/tag/r1.8-314

- Fix blocks turning into other blocks when being placed (Forge fixed a vanilla bug I was unintentionally relying on)

**Comment by LuxusDarkangel** [comment]
It keeps happening for me, using Botania Unofficial r1.8 314, SpongeForge 1633 and Forge 12.18.1.2043.
Deleted the world, the config folder and every single file generated by the server but the eula, and it's still there.

Server folder if you want to test it with the same setup I used: https://mega.nz/#!wZcEza5R!KRR97t9vpiIxHvOJZOChE12TVQGCA6jhmBEL9BDTTDs

@FiveEYZ Nope, as I said above, it's happening in 314 too.

**Comment by Eufranio** [comment]
Still happening for me too, latest release from Botania and latest build of SpongeForge, even in a clean installation.

**Comment by Zidane** [comment]
Someone needs to remove all mods besides Botania + SpongeForge and re-test. I suspect this is what @Aaron1011 did and he can't reproduce as its another mod triggering it.

**Comment by FiveEYZ** [comment]
i did that but can try it again now when everything been updated

**Comment by FiveEYZ** [comment]
nothing happens with the flowers

tested with only:
forge-1.10.2-12.18.1.2044-universal
spongeforge-1.10.2-2044-5.0.0-BETA-1649
Botania-unofficial.r1.8-314
Baubles-1.9.4-1.2.1.0

**Comment by Zidane** [comment]
@FiveEYZ 

Please provide exact steps for reproduction of this issue.

**Comment by FiveEYZ** [comment]
1.  Get yourself a Pure Daisy
2.  Place it on the ground
3. Place Stone or Wood Logs around the flower in 3x3 (you can mix)
like this: http://imgur.com/yShsIw4

It can take up to 5-30 seconds for the Pure Daisy to transform the blocks.

**Comment by Eufranio** [comment]
Tested here and is happening same as @FiveEYZ .

**Comment by gabizou** [comment]
@FiveEYZ Anything appear in console or in FML's log?

**Comment by FiveEYZ** [comment]
nothing shows up in console or logs

posting the logs again: https://gist.github.com/FiveEYZ/4c1a031f73625c5512be47eb4366312a

**Comment by gabizou** [comment]
I can't reproduce this using latest builds of both SF and Botania.

**Comment by FiveEYZ** [comment]
Sorry if it sounds like im on repeat but I don't know whats going on anymore... is there a special config I missed? Advanced java flag setup I didn't do? Ready odd that it's only working for sponge devs?!

What i did? same as I said in previous post, after a while I placed pure daisy around all stones like this:
![688331f709707b58ae551c036d389061](https://cloud.githubusercontent.com/assets/9557442/17368493/8a23b6ac-5994-11e6-9ba7-c08ba3bf0266.png)

Still nothing happens with the stone after the block change "effect".

Tested again with:
forge-1.10.2-12.18.1.2045-universal
spongeforge-1.10.2-2044-5.0.0-BETA-1655
Botania-unofficial.r1.8-314
Baubles-1.9.4-1.2.1.0

Client was using forge 2044

Here is a DL to the test server i used:
https://drive.google.com/open?id=0B47wGOooeWGIeGFpY0FmWjhueFk
If anyone do spot the problem, please tell!

**Comment by gabizou** [comment]
Ok, so I've been finally able to reproduce, as it only happens server side.

**Comment by Eufranio** [comment]
And... Needs be fixed by SpongeForge or?

**Comment by AnimadorX** [comment]
is it fixed_

**Comment by bloodmc** [comment]
@Eufranio @FiveEYZ @LuxusDarkangel This issue should now be resolved. Grab latest build for fix.

**Comment by williewillus** [comment]
I'm curious why this happens, can someone give me a bit of insight?

The Pure Daisy is a `SubTilePureDaisy`, housed within a `TileSpecialFlower`, which is just your standard ITickable TE. not sure why this problem arises but I'm curious to know

**Comment by Eufranio** [comment]
Thank you very much ! :smiley:

**Comment by AnimadorX** [comment]
Thanks ratata!

**Comment by bloodmc** [comment]
@williewillus I was looking at old source. It seems the issue was caused by 
```java
Class<?> declaringClazz = clazz.getMethod(mapping).getDeclaringClass();
```
If the target class had a client class, it would throw an exception and skip the canTick check causing your TE not to tick.

**Comment by williewillus** [comment]
cool, thanks!

**Comment by bloodmc** [comment]
@williewillus Looks like the following caused it to throw an exception

https://github.com/williewillus/Botania/blob/master/src/main/java/vazkii/botania/common/block/tile/TileSpecialFlower.java#L168

This is missing a SideOnly.CLIENT annotation
