### ISSUE TITLE
[1.10.2] refinedstorage unusable

### ISSUE THREAD

**Issue by phit** [SpongePowered/SpongeForge#793]
from https://github.com/raoulvdberge/refinedstorage/issues/223
>Several things are messed up. The grid GUI is acting very strangely, I put it 5 buckets it shows 10, I take one out it shows 8, stuff like that. If I configure an interface to keep one bucket in it, I can't remove that bucket from the GUI. There are probably more issues that I don't know about.

could reproduce with these versions, havent tried it in newer ones: 
refinedstorage-0.8.12.jar
spongeforge-1.10.2-2026-5.0.0-BETA-1599.jar.dis
forge-12.18.1.2026

**Comment by FiveEYZ** [comment]
Did a test with only these mods installed:
refinedstorage-0.8.12
spongeforge-1.10.2-2026-5.0.0-BETA-1607

1.  Made a simple setup with a interface connected to a RSsystem
2.  Placed a stack of redstone on 1 of the export slots
3.  When i tried to remove that "ghost" stack from the slot i got this in console: http://pastebin.com/raw/tkvcNTDj

The interface wont reset unless i break it.

**This also happen without sponge installed**, then it shows this in the console: http://pastebin.com/raw/H49VPqFF
Same as above but without sponge.

**Comment by gabizou** [comment]
Going to need full logs for that the.

**Comment by FiveEYZ** [comment]
same setup as my comment above but with a new world

logs here:
https://gist.github.com/FiveEYZ/2ffb293e89a5c0ca08a354e9e5398a3f

**Comment by gabizou** [comment]
It sounds like the mod is using client classes while on the server. So not a Sponge issue directly.
