### ISSUE TITLE
[1.10.2] Crash at server startup due to "A required class was loaded prematurely!"

### ISSUE THREAD

**Issue by MastaC729** [SpongePowered/SpongeForge#796]
I'm not sure if maybe I have an old version of one of these mods that's incompatible with Sponge, or if it's a newly found mod that is incompatible. Here is the log:

http://pastebin.com/EGK0XxiS

**Comment by LuxusDarkangel** [comment]
CodeChickenCore is not compatible with 1.10.2. 

First test your mods without Sponge. If everything works fine add Sponge, and if you get any errors, remove your mods one by one until you find the one causing the error. Then, report it.

**Comment by gabizou** [comment]
Also, CodeChickenCore is class loading `ModContainer` really early, far earlier than Sponge can finish loading to attach mixins.

**Comment by MastaC729** [comment]
Even after I removed CodeChickenCore, it still crashes.

**Comment by MastaC729** [comment]
OK, I figured this out last night then after posting this report. I'll contact ChickenBones and let him know that there's an incompatibility.

**Comment by LuxusDarkangel** [comment]
Follow what I told you in muy last post.

**Comment by Starza4TW** [comment]
Just came across this too, Masta posted in an outdated repo: here is someone's issue from about two weeks ago on the same issue: https://github.com/TheCBProject/CodeChickenCore/issues/2

**Comment by MastaC729** [comment]
Ah derp, thanks for letting me know,

**Comment by covers1624** [comment]
Im the new dev of CB's stuff, i believe i have found the issue, it was indeed CCC loading the class to early, iv'e moved some stuff around and it should be fixed.
