### ISSUE TITLE
[1.10.2] Ticking entity

### ISSUE THREAD

**Issue by FiveEYZ** [SpongePowered/SpongeForge#797]
i was shooting some arrows on skeletal horses, 1 of them made the server crash

https://gist.github.com/FiveEYZ/d8faa05f1cfaefcb2c9c53f96aac0db6

spongeforge-1.10.2-2026-5.0.0-BETA-1622

**Comment by LuxusDarkangel** [comment]
@Aaron1011 maybe this is the same as #769 but with vanilla projectiles instead of modded projectiles?

**Comment by FiveEYZ** [comment]
Dont know what mods it is but its a skeleton rider on a skeleton horse, when approached a lightning will hit it and it will split to 4 horses with 1 rider each and will shoot arrows at you.

feels this is the same issue:
https://github.com/SpongePowered/SpongeForge/issues/735

**Comment by JBYoshi** [comment]
That's not a mod, it's vanilla Minecraft: http://minecraft.gamepedia.com/Horse#Skeleton_trap

**Comment by FiveEYZ** [comment]
oh, i actually didnt know about those traps :S

Now this crash may look the same as above 
https://gist.github.com/FiveEYZ/751c6973ee138710b14c9f52beefa6b3
but this time i was shooting them on my friend.

Dont know if it will help but i was using spongeforge-1.10.2-2026-5.0.0-BETA-1626
