### ISSUE TITLE
[1.10.2] Incompatibility with graves mod.

### ISSUE THREAD

**Issue by XileForce** [SpongePowered/SpongeForge#798]
Upon death, a copy of the players inventory is stored in the grave, but they also retain their inventory upon respawn effectively duplicating it.

Spongeforge 1624

using this graves mod. http://minecraft.curseforge.com/projects/gravestone-mod

**Comment by MastaC729** [comment]
I can confirm this as well.

**Comment by bloodmc** [comment]
@XileForce Is keepInventory on? if so turn it off and retest.

**Comment by XileForce** [comment]
Keep inventory is not on. The graves actually dont even spawn if keep inventory is on.

**Comment by MastaC729** [comment]
Well that's a feature with the Gravestone mod, if keepInventory is on.

**Comment by XileForce** [comment]
Yea I was just pointing it out fot bloodmc.

**Comment by bloodmc** [comment]
@XileForce @MastaC729 I just looked at Gravestone mod code and I don't understand how this doesn't happen WITHOUT sponge. Please test without SpongeForge, the same issue should occur.

**Comment by XileForce** [comment]
Sounds good!

**Comment by mkiplm** [comment]
anyone have fix, so players dont have to have keepinventory on.

**Comment by lilmoefow** [comment]
Issue still present with:

forge-1.10.2-12.18.2.2098
spongeforge-1.10.2-2098-5.0.0-BETA-1798.jar
GraveStone Mod 1.5.7.jar

Let me know if there is a way i can provide more info for this.

**Comment by ProsperCraft** [comment]
This is still a problem with: 

[11:24:24] [Server thread/INFO]: SpongeForge
    Minecraft: 1.10.2
    SpongeAPI: 6.0.0-SNAPSHOT-73050f3
    SpongeForge: 1.10.2-2098-6.0.0-BETA-1819
    Minecraft Forge: 12.18.2.2099

**Comment by gabizou** [comment]
@ProsperCraft Can you re-test with 1836?

**Comment by ProsperCraft** [comment]
Resolved! This issue can now be closed.

**Comment by ProsperCraft** [comment]
@gabizou players are reporting that items are still remaining in their inventores with 1836.

**Comment by Vauxite** [comment]
Stilla problem with:
Minecraft 1.10.2
spongeAPI: 6.0.0-SNAPSHOT-cebc736
SpongeForge 1.10.2-2107-6.0+.0-BETA-1836
Minecraftforge 12.18.2.2107

**Comment by ProsperCraft** [comment]
Update to 1846 its fixed.

**Comment by lilmoefow** [comment]
GraveStone Mod 1.5.8.jar
forge-1.10.2-12.18.2.2107-universal.jar
spongeforge-1.10.2-2107-6.0.0-BETA-1846.jar

Can Confirm it is Fixed.
