### ISSUE TITLE
[1.10.2] UseItemStackEvent have no effect in SpongeForge.

### ISSUE THREAD

**Issue by webrsb** [SpongePowered/SpongeForge#801]
I tried same code like below in SpongeForge and SpongeVanilla.

``` JAVA
   @Listener
    public void PlayerUseItemEvent(UseItemStackEvent event, @First Player player) {
        player.sendMessage(Text.of(TextColors.GOLD, "You Use Item Stack"));
    }
```

SpongeVanilla functioned normally but SpongeForge does not. Is it SpongeForge's bug?

Environment :
spongeforge-1.10.2-2026-5.0.0-BETA-1632
forge-1.10.2-12.18.1.2011-universal

spongevanilla-1.10.2-5.0.0-BETA-93.jar

**Comment by ST-DDT** [comment]
> SpongeVanilla functioned normally but SpongeForge does not. Is it SpongeForge's bug?

@webrsb Can you explain that a little bit more in detail?

What does not work
* Listen to that event?
* Sending the message?
* Sending the message colored?

Maybe a screenshot can help to understand your issue a little bit better.

Do you have any plugins/mods installed (besides this one)?

**Comment by webrsb** [comment]
Just the "UseItemStackEvent" can't be listened.  No error fond and had no other mods. You can check the source on [github](https://github.com/webrsb/EventTest).

Test in SpongeForge:
http://i.imgur.com/LHyPypn.png
Test in SpongeVanilla:
http://i.imgur.com/undefined.png

**Comment by Zidane** [comment]
I believe @bloodmc resolved this issue as well as API5 now has InteractItemEvent.

**Comment by RobertHerhold** [comment]
I'm seeing this same issue on spongeforge-1.10.2-2281-5.2.0-BETA-2274. It doesn't seem like this was ever fixed
