### ISSUE TITLE
[1.10.2] Ticking entity item frame

### ISSUE THREAD

**Issue by i9hdkill** [SpongePowered/SpongeForge#803]
Server crashes with this error when player logs in at this position:
http://pastebin.com/nJMU6WZh

**Comment by i9hdkill** [comment]
After removing this specific block/entity with world edit, I am getting this crash when entering the region:
http://pastebin.com/hwxj0iM4

**Comment by gabizou** [comment]
Bug with pixelmon, they fixed already.

**Comment by i9hdkill** [comment]
I guess in it's fixed in Beta 4 that is not released? Because crash happens with Beta 3

**Comment by gabizou** [comment]
I'm going to assume so, yes.
