### ISSUE TITLE
[1.10.2] pressure plates not detecting player

### ISSUE THREAD

**Issue by hunter688** [SpongePowered/SpongeForge#806]
Found strange issue with pressureplates. When use wooden pressure plate and wooden doors, cannot open doors using restone, when stay on pressure plate. When throw item to plate, it works. When doors are opened, and then I stay to pressure plate, can close door.

**Comment by FiveEYZ** [comment]
its really odd
You can hear the pressure plate being triggered when walked over
the redstone wont light up but the piston will trigger
piston will also trigger if placed next to a pressure plate but not the door

After installing https://minecraft.curseforge.com/projects/malisisdoors the doors now work properly
but redstone will only light up if i throw an item on it.
