### ISSUE TITLE
[1.10.2] ExceptionInInitializerError and NullPointerException: Exception in server tick loop

### ISSUE THREAD

**Issue by AuricPolaris** [SpongePowered/SpongeForge#807]
When trying to start up a server with the below versions of forge and sponge, the server will crash upon initial initialization. I disabled the mod causing the error but another mod took it's place. So here I am to report it! Please let me know if I am missing anything and I will get said information here as soon as possible.

Forge Version: forge-1.10.2-12.18.1.2043-universal
Sponge Version: spongeforge-1.10.2-2043-5.0.0-BETA-1644 (latest as of this post)

Example Crash Reports:
First) http://pastebin.com/Cz0H37xC
Second) http://pastebin.com/BRQLQLjC

(Okay, that is a massive title, my apologies if it is too excessive)

**Comment by FiveEYZ** [comment]
first crash is a mod called "Natural Pledge" and its not working on this new forge i would suggest try forge 2031

the second is the mod psi update 36 does now work, u need to update to 37
https://minecraft.curseforge.com/projects/psi/files/2319176

**Comment by AuricPolaris** [comment]
It is like you are already playing this same modpack that I am. I am just one step behind you.

I will report back after I do the above. ^^

**Comment by AuricPolaris** [comment]
Alright, after also updating Mantle (that needed an update with TiCon) and running 2043 forge on my client as well, everything seemed alright. The server and client both loaded. Thank you FiveEYZ. :)
