### ISSUE TITLE
[1.10.2] Exception while ticking a block

### ISSUE THREAD

**Issue by FiveEYZ** [SpongePowered/SpongeForge#808]
1.  Place a Dropper anywhere
2.  Activate it with any redstone signal
3.  Watch server crash

https://gist.github.com/FiveEYZ/ee5513b1f6b03f4ed2c9f49c896a4842

Used:
spongeforge-1.10.2-2043-5.0.0-BETA-1644
forge-1.10.2-12.18.1.2044-universal

**Comment by gabizou** [comment]
Already fixed.
