### ISSUE TITLE
[1.8.9] server crash java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by hunter688** [SpongePowered/SpongeForge#811]
http://pastebin.com/1RizdJ9h

**Comment by ST-DDT** [comment]
Which plugins and versions do you use?
Is that bug reproducible? How?
Is it reproducible without mods?
Could you remove them them all and check one plugin at a time? To check which one is causing this?

**Comment by hunter688** [comment]
plugins/mods are in the stacktrace
IDK howto reproduce - i think its during generating new map chunks

**Comment by hunter688** [comment]
Yesterday this issue occur when player teleported to /home - chunks loaded.

**Comment by ghost** [comment]
I think 1.8.9 become unmaintained...
