### ISSUE TITLE
[1.10.2] SpongeForge fails to load a number of dimensions added by various mods

### ISSUE THREAD

**Issue by Leasara** [SpongePowered/SpongeForge#813]
Error:
04.08 11:16:22 [Server] Server thread/ERROR [Sponge]: An attempt was made to load a world with dimension id [53] that has no registered world folder!
04.08 11:16:22 [Server] Server thread/ERROR [Sponge]: An attempt was made to load a world with dimension id [52] that has no registered world folder!
04.08 11:16:22 [Server] Server thread/ERROR [Sponge]: An attempt was made to load a world with dimension id [51] that has no registered world folder!
04.08 11:16:22 [Server] Server thread/ERROR [Sponge]: An attempt was made to load a world with dimension id [50] that has no registered world folder!
04.08 11:16:22 [Server] Server thread/ERROR [Sponge]: An attempt was made to load a world with dimension id [-343800852] that has no registered world folder!

In the All The Mods 1.8 modpack and the latest SpongeForge (not certain of the number, CubeHost just downloaded it and installed it for me) I believe this is making these dimensions inaccessible when running SpongeForge on the server.  They work fine without SpongeForge.

**Comment by LuxusDarkangel** [comment]
1.- Use `/sponge version` to see the version you're running and post it.
2.- I gues you're using SpongeForge for 1.8.9 based in the name of the modpack. If it's true, please correct the title.

**Comment by FiveEYZ** [comment]
first startup with AbyssalCraft-1.10.2-1.9.2.8 works fine. but when i restart the server it fails to load the dimensions and crashes: https://gist.github.com/FiveEYZ/fd5fe5dd6b7dde44830a799c6f1981b0

using:
spongeforge-1.10.2-2044-5.0.0-BETA-1661
forge-1.10.2-12.18.1.2050

**Comment by bloodmc** [comment]
@FiveEYZ Is this issue resolved in latest build? I pushed some more fixes earlier today that should fix your issue.

**Comment by FiveEYZ** [comment]
Yea it works alright, only thing now is im wondering,
is it supposed to create so many folders per dimension?

This is inside config/sponge/worlds
https://gyazo.com/605796ca9669eca27732db6b5abfc72f

**Comment by bloodmc** [comment]
@FiveEYZ hrmm no, I'll look into that.

**Comment by bloodmc** [comment]
@FiveEYZ Please test build 1667 when it is finished building. Make sure to clean out your config folder so you can see what it produces. It should store everything by modid now.

**Comment by FiveEYZ** [comment]
@bloodmc looks much better now, once again awesome work
