### ISSUE TITLE
[1.8.9-1890-4.2.0-BETA-1653] Server Crash/Lockup

### ISSUE THREAD

**Issue by Rhonim** [SpongePowered/SpongeForge#817]
Had about 4-5+ Crashes/lock ups from this so far

http://pastebin.com/m0puTEw7

**Comment by LuxusDarkangel** [comment]
For me it doesn't look like a problem with SpongeForge. Steps to reproduce? Can you try without Sponge?

**Comment by Rhonim** [comment]
Not really viable for me to reproduce. Looks like its triggered off of a ClientConnectionEvent.Login event returning false (i.e. this line: https://github.com/SpongePowered/SpongeCommon/blob/31fde9f031a5141add3bd24244e96559c0ccbaaa/src/main/java/org/spongepowered/common/mixin/core/server/MixinPlayerList.java#L237)

**Comment by Rhonim** [comment]
Moving this issue to SpongeCommon.
