### ISSUE TITLE
[1.10.2] offering PoweredData to supporting blocks always rejected

### ISSUE THREAD

**Issue by trentech** [SpongePowered/SpongeForge#818]
After updating to API 5.0.0 I can no longer change PoweredData key for supportting blocks such as buttons and levers. Also when printing the Container I noticed the Key is always false even when interacting with the supporting blocks such as toggling the lever on and off.

https://forums.spongepowered.org/t/powereddata-problem-api-5-x/14032

I've tested this with latest SpongeVanilla and SpongeForge. This only became a problem after targetting API 5.0.0

**Comment by me4502** [comment]
From the thread it's noted that a Cause is required to perform this action. If this is intentional (And it probably is), should we mention that in the JavaDocs for the offer method that doesn't have a Cause?

**Comment by gabizou** [comment]
I already updated the javadocs for this, if a `BlockState` change is required for a location, the same method that has an additional parameter for a `Cause` is required. You can read more here: https://github.com/SpongePowered/SpongeAPI/pull/1315.

**Comment by ryantheleach** [comment]
I think it's more about the similar naming of the methods, yet distinct behaviour that's causing the issue. Principal of least surprise would make people suspect that the cause is optional, not that the method without a cause can only affect tile entities.
