### ISSUE TITLE
[1.8.9] I do not work minecraft:detector_rail. Not activated trolley.

### ISSUE THREAD

**Issue by ziceptor** [SpongePowered/SpongeForge#819]
I do not work minecraft:detector_rail. Not activated trolley. [Video](https://cloud.mail.ru/public/4JwF/mLZiMdFVa)

spongeforge-1.8.9-1890-4.2.0-BETA-1662.jar

**Comment by ziceptor** [comment]
Without sponge-1.8.9 rails work.

**Comment by bloodmc** [comment]
@Aaron1011 you want to push a fix for this? Same one you did in 1.10

**Comment by ziceptor** [comment]
Not all plugins are ready for 1.10. Will it be fixed in sponge-1.8.9?
