### ISSUE TITLE
[1.8.9] Bibliocraft crash server with SpongeForge

### ISSUE THREAD

**Issue by hunter688** [SpongePowered/SpongeForge#820]
without spongeforge server starts ok

with SF build 1653:

http://pastebin.com/pzh7NbJ1

**Comment by gabizou** [comment]
From a quick look, Bibliocraft is constructing it's enchantments with `null` `ResourceLocation`s, which means the enchantments themselves are going to have no proper id's to refer them to. The issue with this is of course that Sponge will not be able to understand what they are properly named as. I'm unaware that it's a good thing to have null resource locations, would have to ask @Nuchaz as to why the enchantments have null id's.

**Comment by bloodmc** [comment]
@hunter688 apparently this was fixed by mod dev.
