### ISSUE TITLE
[1.10.2] Ender IO lighting bugs when chunk is unloaded

### ISSUE THREAD

**Issue by Nentify** [SpongePowered/SpongeForge#821]
Screenshot:

![](http://puu.sh/qyOxO/d7c651fb4b.jpg)

SpongeForge on the server, when unloading a chunk with the Ender IO lamp and reloading it, the lighting appears odd like this.

**Comment by gabizou** [comment]
Version info?

**Comment by Nentify** [comment]
```
SpongeForge
    Minecraft: 1.10.2
    SpongeAPI: 5.0.0-SNAPSHOT-d41be56
    SpongeForge: 1.10.2-2044-5.0.0-BETA-1655
    Minecraft Forge: 12.18.1.2045
```

EnderIO-1.10.2-3.0.1.81_beta

**Comment by Nentify** [comment]
May have been due to the world plugin we were using, it had odd issues saving or something. Nucleus seems to give better results. Will re-open if I have more information/it occurs again.

Thanks!
