### ISSUE TITLE
[1.10.2] Packing Tape dupe

### ISSUE THREAD

**Issue by Nentify** [SpongePowered/SpongeForge#823]
Containers spit out items as well as retain them in the inventory when packed with packing tape (the mod). The items shouldn't spit out and they should remain in the inventory.

![](http://i.nentify.me/EUw6VA1i.png)

**Comment by gigaherz** [comment]
Author of the mod, here. I use a dirty hack to prevent the items from spilling: https://github.com/gigaherz/PackingTape/blob/master/src/main/java/gigaherz/packingtape/tape/ItemTape.java#L54,L70

I guess this does not behave the same when Sponge is installed.

This may be an opportunity to use a better method. Any suggestions?

**Comment by gabizou** [comment]
I guess the first question is whether this is reproducible on 1.8.9, then the next step is to figure out where basically `CauseTracker` is causing the dupe. Secondly, I'm guessing that the `worldIn.restoringBlockSnapshots` is not only forge specific, but also something that forge hooks to prevent `block.onRemoved` logic to be performed (which I'm guessing is causing this dupe).

**Comment by Zidane** [comment]
Re-test with stable-5 and re-open if it still occurs.

**Comment by Time6628** [comment]
Still occurs with:
SpongeForge: 1.10.2-2171-5.1.0-BETA-2010
Minecraft Forge: 12.18.3.2202

on the sky factory 3 modpack.

**Comment by gabizou** [comment]
@Time6628 is it reproducible on 2042?

**Comment by FiveEYZ** [comment]
this is still happening @gabizou 

using: spongeforge-1.10.2-2202-5.1.0-BETA-2078
here is a error that gets generated when placing the "packing tape" on a chest
https://hastebin.com/wuretogizi.vbs

full server log: http://paste.ubuntu.com/23866896/

**Comment by bookerthegeek** [comment]
Reproduced on spongeforge-1.10.2-2221-5.1.0-BETA-2128

**Comment by BlackBeltPanda** [comment]
Still dupes on SpongeForge 1.10.2-2477-5.2.0-BETA-2782

**Comment by phit** [comment]
As of January 1st 1.10.2 and 1.11.2 are not longer supported. If a sufficiently, decent, and tested Pull Request is made to fix this bug/issue, it will still be considered, however, it is NOT to be expected that any bug fixes made for 1.12.2 will be back ported to 1.11.2 or 1.10.2.

If you can reproduce this issue with SpongeForge on Minecraft 1.12.2 and this issue was wrongly closed, please open a new issue with updated information.
