### ISSUE TITLE
Player inventory bug

### ISSUE THREAD

**Issue by maxanier** [SpongePowered/SpongeForge#827]
I'm working on/modifiying a shop plugin and found something strange:

Executing `Player.getInventory().offer(Item.createStack())` does not work during  (no item is added) InteractBlockEvent (Primary) under a certain condition:
1. The player already has a stack (containing 1-x items) on his hotbar
2. That slot is selected
3. Left of that slot on the hotbar is no slot that item could fit in (empty or same item)

Screenshots of the most basic setup:
**1 Case: No items at hotbar (Works)**
Before:   
<img src="https://picload.org/image/rrccprco/2016-08-14_12.13.50.png" width=500px>
After:   
<img src="https://picload.org/image/rrccprcc/2016-08-14_12.13.53.png" width=500px>

**2 Case: Already an item on hotbar and selected (Does not work)**      
Before:   
<img src="https://picload.org/image/rrccprcc/2016-08-14_12.13.53.png" width=500px>  
After:    
<img src="https://picload.org/image/rrccprcp/2016-08-14_12.13.56.png" width=500px>  

_The item is not added (also not to the rest of the inventory) and a reconnect also does not help._

**3 Case: Already an item on hotbar, but not selected (Works)**    
Before:  
<img src="https://picload.org/image/rrccprig/2016-08-14_12.14.04.png" width=500px>  
After: 
<img src="https://picload.org/image/rrccprid/2016-08-14_12.14.06.png" width=500px> 

EDIT: Forgot to mention versions and stuff:
Minecraft: 1.10.2
Spongeforge: bleeding branch (from yesterday)

**Comment by Nentify** [comment]
Posted the same issue on SpongeCommon with my findings: https://github.com/SpongePowered/SpongeCommon/issues/891

Hopefully something can be sorted.
