### ISSUE TITLE
Botania Alchemy does not work on SpongeForge Servers

### ISSUE THREAD

**Issue by Starza4TW** [SpongePowered/SpongeForge#829]
Using a SpongeForge server, any items dropped into a Mana Pool + Alchemy Catalyst will not alchemize. They will simply drop onto the ground like any other item. Ex: http://g.recordit.co/l9EQM9WWjT.gif

This does not occur on any client using SpongeForge, only servers using SpongeForge. Removing SpongeForge from the server also allows the alchemy. This is what it should look like: http://g.recordit.co/AiyVvDNst7.gif

Installed:

- MC 1.10.2

- Forge 12.18.1.2052

- SpongeForge Build 1670

- Botania r1.8-315

- Baubles 1.2.1.0 (Pre-req of Botania)

I've also made an issue on the Botania Issue Tracker: https://github.com/williewillus/Botania/issues/442

**Comment by Eufranio** [comment]
Confirm.

**Comment by williewillus** [comment]
Sponge devs: I just use Block.onEntityCollidedWithBlock(World, BlockPos, IBlockState, Entity), which calls to the TE. no special magic here.
