### ISSUE TITLE
[1.10.2] crash ConcurrentModificationException

### ISSUE THREAD

**Issue by FiveEYZ** [SpongePowered/SpongeForge#834]
i did a /rtp from the plugin Nucleus, server crashed when loading destination

using:
forge-1.10.2-12.18.1.2061-universal
1.10.2-2052-5.0.0-BETA-1673
and `all the mods` listed in the crash-report

https://gist.github.com/FiveEYZ/f15c7a5793c55f751ead9bd2126711cf

here kind of the same crash again, but much longer:
https://gist.github.com/FiveEYZ/6188f7ba125d394f9a4f66fbd25042ba

**Comment by bloodmc** [comment]
Update to latest SF builds.
