### ISSUE TITLE
[1.10.2] Startup crash when data folder is present

### ISSUE THREAD

**Issue by floh22** [SpongePowered/SpongeForge#842]
Spongeforge causes the server to crash if there are any data folders present in the world folder. 

Deleting the data folders in all worlds and then starting the server works fine.

Issue present on all recent spongeforge builds on 1.10.2, including bleeding bleeding branch.
Happens with a clean install

Crashlogs:

http://pastebin.com/wXxDuRYq

**Comment by Aaron1011** [comment]
What version of Forge are you using?

**Comment by floh22** [comment]
Using build 2065, though I haven't had any different experiences with previous builds

**Comment by bloodmc** [comment]
Unable to reproduce this issue using latest builds.
