### ISSUE TITLE
[1.8.9 and 1.10.2] Couldn't look up profile properties for com.mojang.authlib.GameProfile

### ISSUE THREAD

**Issue by ziceptor** [SpongePowered/SpongeForge#843]
Without spongeforge there are no errors!
If I add it to the mods folder, then in the log: http://pastebin.com/F503z3QR
Immediately after starting the server.
How to fix?

spongeforge-1.10.2-2052-5.0.0-BETA-1675.jar
forge-1.10.2-12.18.1.2052-universal.jar

**Comment by ziceptor** [comment]
Hmmm.. Have previously installed the plugin ChangeSkin.jar. He may have made to the world changes. I installed it and the error disappeared. Maybe it's a coincidence.

**Comment by games647** [comment]
> I installed it and the error disappeared

Do I understand that correctly that after you installed ChangeSkin you won't get this error?

**Comment by FiveEYZ** [comment]
Seen this error to, went to the nether and died then this error appeared:
https://gist.github.com/FiveEYZ/25dd150950fe31c9e2adab118e4f7c18

**Comment by games647** [comment]
@FiveEYZ What plugins do you use?

**Comment by ziceptor** [comment]
@games647 I'm not sure. Maybe coincidence. There are no more errors.
