### ISSUE TITLE
Suggestion: grant highest permission to command block

### ISSUE THREAD

**Issue by 5igm** [SpongePowered/SpongeForge#845]
Now, if players don't have permission, command block do nothing for them. I think it is better to grant all permission to command block.

**Comment by bookerthegeek** [comment]
I think this is a stupid idea that will cause servers who use command blocks a multitude of issues.

**Comment by 5igm** [comment]
I think if sponge set "only op in creative mode can edit commandblock" as precondition, this idea will not cause problems. @bookerthegeek

**Comment by bookerthegeek** [comment]
What is wrong with the way it is now?

**Comment by 5igm** [comment]
I tried to make several questions for players before they begin the game to ensure players can get all of the informations they need to know. In the past, I used customnpc to help questions working. If the player choose correct answer, he/she will be teleporated to next question until finishing all of the questions. If the player answers wrongly, he/she will be teleporated to last question position. However, recently, I found a critical bug in my server and mod author stopped to support 1.8.9, I have to update my server to higher version. Unfortunately, customnps hasn't support 1.10 or 1.9.4. For my question working, I decided to use command blocks replacing npcs. But, I found command block only can execute the commands which users have related permissions.
Of course, maybe I can find some plugins like commandsign to work for some functions, yet I think command block is very powerful, and maybe there are some potential errors in plugins. I think using command block is safer. Moreover, plugin authors may update their plugins very slowly or they are also possible to abondon their projects.
Thereby, I think it is necessary to make command block own all of permissions like console with precondition that only op in creative mode can edit commandblock.

**Comment by JBYoshi** [comment]
@5igm Sponge already does this.
https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/mixin/core/command/MixinCommandBlockSource.java#L54

**Comment by 5igm** [comment]
@JBYoshi Sorry, I am a little confused. Is that mean my suggestion has been adopted or Sponge already has this function?

**Comment by JBYoshi** [comment]
@5igm Sponge already has this function. Unless you take away permissions via a permissions plugin, a command block will have full permissions.
