### ISSUE TITLE
[1.10.2] Teleporting between worlds doesn't seem to work properly

### ISSUE THREAD

**Issue by Haidyn** [SpongePowered/SpongeForge#847]
When teleporting between worlds, it seems to not update the world properly for the client or something.

For example, in the video, The One Probe works fine, but teleporting to the `market` world is showing blocks from the main world and vice versa. This is also reproducible with the Ender IO coordinate picker; the dimension name is always the world you first log in to, so I believe it may be an issue with Sponge.

Video: http://i.nentify.me/AYAWarVt.mp4

Thanks!

**Comment by ryantheleach** [comment]
Source for the mod: 1.10 branch https://github.com/McJty/TheOneProbe/tree/1.10/src/main/java/mcjty/theoneprobe
