### ISSUE TITLE
[1.10.2] Crash on latest sponge version - 1676

### ISSUE THREAD

**Issue by Tencao** [SpongePowered/SpongeForge#849]
When I use the recommended forge for sponge alongside the latest sponge, it crashes on load. 

I have no mods other than sponge, and only two plugins, BungeeTabList, and SpongyCord.

http://pastebin.com/CZ8UJya6

I would also like to say that this is a fresh install, with no world generated

**Comment by Deamon5550** [comment]
@gabizou https://github.com/SpongePowered/SpongeCommon/commit/cd9655f83216f0c206543b28d58e46e607553e6c#diff-aa177db6b85f010b8ddd5019f285ab5aR95

**Comment by FiveEYZ** [comment]
getting this using build 1677

https://gist.github.com/FiveEYZ/0bb9b3a5ffcd0e03bbead8f1a91850d6

**Comment by Deamon5550** [comment]
@FiveEYZ It was fixed for real in build 1678, update to that.
