### ISSUE TITLE
Interact error spamming console

### ISSUE THREAD

**Issue by SnowBlitzz** [SpongePowered/SpongeForge#851]
http://pastebin.com/PyCKuhcf - yes you might tell me to update to latest. I was on the latest gp b66 and sf 1666 for a week now and keep getting this, just downgraded to gp56 and sf1653 just now to test if it still happens, thus this console log.

**Comment by gabizou** [comment]
Could you paste the fml-log?

**Comment by bloodmc** [comment]
20.08 22:04:32 [Server] INFO at com.helion3.keys.listeners.InteractBlockListener.onUse(InteractBlockListener.java:49) ~[InteractBlockListener.class:1.2+unknown-b0.git-unknown]
20.08 22:04:32 [Server] INFO at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_91]

Prism's issue. Report to them.

**Comment by SnowBlitzz** [comment]
Uhmm I'm not using Prism atm

**Comment by bloodmc** [comment]
@SnowBlitzz I meant to say "Keys".
