### ISSUE TITLE
Crash at launch [1.10.2 - 1681 server]

### ISSUE THREAD

**Issue by LotuxPunk** [SpongePowered/SpongeForge#855]
Hello, can you help me please ? :)

http://pastebin.com/TQWCvY80

[crash-2016-08-22_23.00.59-server.txt](https://github.com/SpongePowered/SpongeForge/files/431917/crash-2016-08-22_23.00.59-server.txt)

**Comment by hunter688** [comment]
step by step remove mods, then you can find which mod causing problem

**Comment by LotuxPunk** [comment]
But, on 1675, the server don't crash

**Comment by LuxusDarkangel** [comment]
It's by far easier to find the issue knowing which mod causes It, and the way to find It is removing mods one by one.

**Comment by gabizou** [comment]
```
spongeforge-1.10.2-2052-5.0.0-BETA-1681.jar
Forge{12.18.1.2064}
```
The forge build that that version of SF was built against is not matching the forge build you're running the server off of. I'd recommend trying with Forge 2052 and see if it still occurs, otherwise, update to the latest Forge and SF (we updated versions), and test against that.

**Comment by bloodmc** [comment]
dupe #853

**Comment by LotuxPunk** [comment]
Ok ! Thank you for your awesome job ! ;)
