### ISSUE TITLE
[1.10.2] EnderIO's Broken Spawner not dropping.

### ISSUE THREAD

**Issue by LuxusDarkangel** [SpongePowered/SpongeForge#857]
Using SpongeForge and EnderIO results in Broken Spawner not dropping. Works fine only with Forge.

Steps:

1.- Place a vanilla Mob Spawner (ID: 52)
2.- Break it using a pickaxe.
3.- It should drop a Broken Spawner, but it doesn't.

Versions: Latest SpongeForge, EnderIO and EnderCore.

EDIT: Relevant code: https://github.com/SleepyTrousers/EnderIO/blob/c70377e3e3325f701630d9cd46b70257a41fcf2f/src/main/java/crazypants/enderio/machine/spawner/BlockPoweredSpawner.java#L145

**Comment by bloodmc** [comment]
@LuxusDarkangel  Did you test without any plugins?

**Comment by gabizou** [comment]
I'm pretty sure I have an understanding what's going on. I'll need to test my theory but it more than likely has to do with harvest events being misfired for forge mods.

**Comment by LuxusDarkangel** [comment]
I know you're already looking into It, but yeah @bloodmc, I forgot to say It, but I always test this kind lf issues without plugins or other mods not directly related.

**Comment by Jasems** [comment]
If it helps in fixing, I do notice the broken spawner drop in the air for a split second, then vanish.

**Comment by viper2g1** [comment]
I can confirm this happens, I'm not sure if you need any logs to fix it at this point but I'd be happy to provide some if you do.

**Comment by dogboy21** [comment]
It looks like the tileentity for the spawner is being removed before the BreakBlock event is being fired

**Comment by Aaron1011** [comment]
@dogboy21: You're absolutely correct. This issue is due to Sponge's capturing system, which fires a bulk event after all of the changes have been performed for a particular action (e.g. breaking a block).

@gabizou: What do you think is the best way to deal with this?

**Comment by Vauxite** [comment]
Confirmed the bug running FTB Hermitpack 1.0.1 with spongeforge
[16:53:18] [Server thread/INFO]: SpongeForge
    Minecraft: 1.10.2
    SpongeAPI: bleeding-SNAPSHOT-b550bfa
    SpongeForge: 1.10.2-2098-bleeding-BETA-0
    Minecraft Forge: 12.18.2.2098

**Comment by bloodmc** [comment]
@Vauxite Test using LATEST SF build.

**Comment by Vauxite** [comment]
@bloodmc Does that include the tps fix in bleeding-beta?

**Comment by bloodmc** [comment]
@Vauxite yes, my changes were merged.

**Comment by dogboy21** [comment]
Broken Spawners still don't drop with the latest SF build

**Comment by Vauxite** [comment]
Didn't fix the issue. Spawners still give me Spawner Shard when broken.

**Comment by gabizou** [comment]
@bloodmc this is back to the HarvestDrops event not being fired correctly.

**Comment by ProsperCraft** [comment]
Dragon's breath from the roots mod is also not dropping from the ender dragon

**Comment by Vauxite** [comment]
Still a problem in:
Minecraft 1.10.2
spongeAPI: 6.0.0-SNAPSHOT-cebc736
SpongeForge 1.10.2-2107-6.0+.0-BETA-1836
Minecraftforge 12.18.2.2107

**Comment by lilmoefow** [comment]
forge-1.10.2-12.18.2.2107-universal.jar
spongeforge-1.10.2-2107-6.0.0-BETA-1846.jar
EnderCore-1.10.2-0.4.1.56-beta.jar
EnderIO-1.10.2-3.0.1.120_beta.jar

Yeup still an issue in these versions aswell,  If i can provide anything else to help just let me know.

**Comment by ProsperCraft** [comment]
Guardian scales do not drop from elder guardians (or normal ones) in multiplayer, but in single player they drop 3 per elder guardian and 1 for each few normal guardians. https://www.youtube.com/watch?v=wLANjiEyios https://www.youtube.com/watch?v=7sQiWVCCrqE

Versions-  
SpongeAPI: 6.0.0-SNAPSHOT-f247c80
SpongeForge: 1.10.2-2107-6.0.0-BETA-1852
Minecraft Forge: 12.18.2.2114

**Comment by ProsperCraft** [comment]
Still an issue with 

```
SpongeAPI: 6.0.0-SNAPSHOT-f247c80
SpongeForge: 1.10.2-2107-6.0.0-BETA-1856
Minecraft Forge: 12.18.2.2114
```

**Comment by ProsperCraft** [comment]
Also Draconic Evolution hearts don't drop when killing the ender dragon which stops progress in the draconic evolution mod.

```
SpongeAPI: 6.0.0-SNAPSHOT-f247c80
SpongeForge: 1.10.2-2107-6.0.0-BETA-1862
Minecraft Forge: 12.18.2.2116
```
