### ISSUE TITLE
[1.10.2] Keeping entity Villager that already exists with UUID ... Spam

### ISSUE THREAD

**Issue by Nentify** [SpongePowered/SpongeForge#859]
When launching the server, this spams when SpongeForge is installed:

http://pastebin.com/4jYyZJXb

It stops after a little while and normally stops after the first user logs in. Sometimes it's about an XPOrb as well. I'm not sure where/what this villager/xp orb is or why it's doing this though.

When I remove SpongeForge, the messages appears once:

http://pastebin.com/C2kxK4St

Edit: When it spams about xp orbs, it seems they all have different UUIDs: http://pastebin.com/ib5Gzyfb

**Comment by gabizou** [comment]
Any mods?

**Comment by Nentify** [comment]
If that's so, I'll have a poke around with the mods and get back to you. Thank you!

**Comment by bloodmc** [comment]
This is probably related to 
https://github.com/SpongePowered/SpongeCommon/issues/872

**Comment by Nentify** [comment]
Maybe related to https://bugs.mojang.com/browse/MC-95649 ?

Still happening with XPOrbs and sometimes villagers on latest SF.
