### ISSUE TITLE
Error feedback about Command_block

### ISSUE THREAD

**Issue by 5igm** [SpongePowered/SpongeForge#861]
If there are two or more people in server. command block cannot execute the command used @p. For example, I typed "/tppos @p -175 182 -110" in command space. If there is only one player in the server, command block can transport the player to the position of -175 182 -110. If there are two or more players in the server, command block will just warn "[00:27:37] Usage: /tppos <player> [<world>] x(-2147483648-2147483647) y(0-255) z(-2147483648-2147483647) [-f <f>] ".

**Comment by Zidane** [comment]
Re-test with stable-5 and report back if still an issue and we will re-open.
