### ISSUE TITLE
Sponge doesn't recognize a thrown Eye of Ender as a valid EntityFire Item

### ISSUE THREAD

**Issue by MastaC729** [SpongePowered/SpongeForge#862]
The following is produced in console after I throw an Eye of Ender: 

http://pastebin.com/qvrZeTu6

(Sorry that the pastebin looks like crap, I think it doesn't like how big the box is haha)

Then because of this, the eye of ender does not fully drop to the ground.

**Comment by Aaron1011** [comment]
I'm unable to reproduce this with the latest SpongeForge.
