### ISSUE TITLE
Player is transported into the wall

### ISSUE THREAD

**Issue by 5igm** [SpongePowered/SpongeForge#863]
5igm
> When I issues /rtp in server, sometimes, I will be killed because of being suffocated in a wall.
> Could you give players who is being transported a god buff?

dualspiral 
> No, becuase /rtp should not be putting players into a wall. It uses Sponge's safe teleportation routine, so if you're ending up in a wall, we need to be reporting this to Sponge.

https://github.com/NucleusPowered/Nucleus/issues/329#issuecomment-242373842

I have reported this problem to the plugin author, and he said it is caused by sponge. When players tried to use random transportation in server, sometimes players will be transported into the wall and be killed.

**Comment by 5igm** [comment]
https://youtu.be/gBOMgqN0NBk

**Comment by Zidane** [comment]
@5igm @dualspiral 

The safe teleportation code is pretty wretched in Sponge. @dualspiral I'd appreciate it if you wanted to re-write it and submit a PR (as your plugin uses it).

**Comment by dualspiral** [comment]
@Zidane Alrighty, I'll see what I can do when I get time.

**Comment by 5igm** [comment]
@Zidane  Hi. I saw you have closed https://github.com/SpongePowered/SpongeCommon/commit/2365863f1e0b2feda5ba8893b98c0f78601c57d3. Does it mean new safe teleportation will appear in latest sponge?

**Comment by Aaron1011** [comment]
@5igm: Yes, that's correct.

**Comment by 5igm** [comment]
@Aaron1011  Thank you very much. Thanks for your contribution.

**Comment by Aaron1011** [comment]
@5igm: Don't thank me, thank @dualspiral :). He's the one who wrote it.

**Comment by 5igm** [comment]
@dualspiral Thanks for your work very much.(^_^)
And thanks for all of sponge contributors work for sponge as well.
