### ISSUE TITLE
[1.10.2] Random crash related to WorldGeneration (Chunk / Populating)

### ISSUE THREAD

**Issue by Pymous** [SpongePowered/SpongeForge#864]
Hey !

I manage a Pixelmon Server, using Sponge Forge, and we have a lot of crashes (2-3 every hour, sometimes 3 in a row in the span of 10 minutes).

All of them either talk about World or Chunk, and almost all reports are different, so I will add some, but here is the list for the day : https://files.pymous.xyz/MC/

[crash-2016-08-25_01.49.50-server.txt](https://github.com/SpongePowered/SpongeForge/files/437264/crash-2016-08-25_01.49.50-server.txt)
[crash-2016-08-25_01.10.42-server.txt](https://github.com/SpongePowered/SpongeForge/files/437265/crash-2016-08-25_01.10.42-server.txt)

Hope you guys can do something, I'm uterrly lost :)

**Comment by Dysthymic** [comment]
We're getting this exact same issue. Exact same crash report as well. Using forge 2073 and sponge 2686

**Comment by Deamon5550** [comment]
Obviously you are generating chunks and for some reasons its taking longer than your watchdog timeout time so the watchdog is killing the server, get some timings data during chunk generation.

**Comment by Dysthymic** [comment]
max-tick-time=90000
I've raised it a few days ago in an attempt to fix the issue. We're running on an i7-4700K so there really should not be any reason for timeouts for chunk generation. I think it just needs optimized a bit to support the intensive mods such as Pixelmon. 
https://timings.aikar.co/v2/?id=8f6c937683df469583236368ec6e002c&section=all

I've contacted the devs there as well about this issue to see if they can try and optimize the PokeBall Manager on save

**Comment by phit** [comment]
the watchdog is pretty broken even on vanilla forge, ran into frequent crashes when worldgen happened with [the pack](https://principium.stonebound.net/modlist) i help maintaining 
I ended up fixing it by just setting ```max-tick-time=-1``` as recommended by mojang in their bugtracker https://bugs.mojang.com/browse/MC-63590

**Comment by Nentify** [comment]
Just started getting this on latest SF/Forge versions as well.

**Comment by Deamon5550** [comment]
@bloodmc found some points where cause tracking was not being properly disabled during generation that may help this.

**Comment by bloodmc** [comment]
@Pymous set max-tick-time to -1 and update to latest SF.
