### ISSUE TITLE
[1.10.2] Enchanting - Crash on Illegal Argument

### ISSUE THREAD

**Issue by Rasgnarok** [SpongePowered/SpongeForge#865]
So, this has been ever since last night - when we started using the `/enchant` with Nucleus, after moving to spongeforge 1683, with Forge 2073.

Server Crash - http://pastebin.com/g6CgTpqA
Server Crash - http://pastebin.com/SXKMP2nA
On world-loading - http://pastebin.com/24XmWhM0

**EDIT**: Offending items are not able to be deleted through creative panel, Player needs to have inventory cleared.

**Comment by kashike** [comment]
https://github.com/SpongePowered/SpongeAPI/issues/1337
https://github.com/SpongePowered/SpongeAPI/issues/1338

**Comment by Rasgnarok** [comment]
Lovely, known bug. Hopefully the extra info in the last pastebin will help resolving it.

**Comment by mbax** [comment]
Recently known bug, to be fair. For now, don't enchant with a value higher than 32,767.
