### ISSUE TITLE
tbh idk what happened but pixelmon devs told me to report here

### ISSUE THREAD

**Issue by TheHimayLegend** [SpongePowered/SpongeForge#866]
http://pastebin.com/fvPeiS6c

**Comment by TheHimayLegend** [comment]
one of my my mods said they killed the ender dragon

**Comment by ZephireNZ** [comment]
I can't replicate this with just Forge 1890 and Sponge 1662. Went to end, killed dragon, and hopped back in the portal with no problems (and the part in the code the error occurs was fine for me).

I assume this happened while in the end? If possible could you try removing mods and see if that fixes it. The problem appears to be that a world wasn't registered properly and so Sponge was unable to fetch the world.

**Comment by bloodmc** [comment]
Update to latest SF build.
