### ISSUE TITLE
shop invisible items

### ISSUE THREAD

**Issue by aglarcz** [SpongePowered/SpongeForge#867]
Hello,
i am using https://forums.spongepowered.org/t/adminshop-v1-8-1-server-shops/8867 and items bought are not invisible in inventory, players have to relog to see them. Propably api problem as plugin author said.

**Comment by kinggoesgaming** [comment]
Inventory sync issues. AFAIK @mumfrey will get it sorted sometime

**Comment by Zidane** [comment]
Re-test with stable-5 and re-open if it still occurs.
