### ISSUE TITLE
Several Crashes

### ISSUE THREAD

**Issue by SnowBlitzz** [SpongePowered/SpongeForge#868]
Attached below
[crash-2016-08-25_22.13.21-server.txt](https://github.com/SpongePowered/SpongeForge/files/440396/crash-2016-08-25_22.13.21-server.txt)
[crash-2016-08-25_22.14.29-server.txt](https://github.com/SpongePowered/SpongeForge/files/440397/crash-2016-08-25_22.14.29-server.txt)
[crash-2016-08-26_06.51.18-server.txt](https://github.com/SpongePowered/SpongeForge/files/440398/crash-2016-08-26_06.51.18-server.txt)
[crash-2016-08-26_07.01.39-server.txt](https://github.com/SpongePowered/SpongeForge/files/440399/crash-2016-08-26_07.01.39-server.txt)
[crash-2016-08-26_12.09.24-server.txt](https://github.com/SpongePowered/SpongeForge/files/440400/crash-2016-08-26_12.09.24-server.txt)
[crash-2016-08-26_14.57.47-server.txt](https://github.com/SpongePowered/SpongeForge/files/440401/crash-2016-08-26_14.57.47-server.txt)
[crash-2016-08-26_16.08.13-server.txt](https://github.com/SpongePowered/SpongeForge/files/440402/crash-2016-08-26_16.08.13-server.txt)
[crash-2016-08-26_17.12.58-server.txt](https://github.com/SpongePowered/SpongeForge/files/440403/crash-2016-08-26_17.12.58-server.txt)
[crash-2016-08-26_21.08.07-server.txt](https://github.com/SpongePowered/SpongeForge/files/440404/crash-2016-08-26_21.08.07-server.txt)

**Comment by Deamon5550** [comment]
Please upload these to gist or pastebin or anything that doesn't require downloading files to our computers in order to view them.

**Comment by SnowBlitzz** [comment]
I'll assure you they are safe, but alright.

1. http://pastebin.com/WZm8kijM
2. http://pastebin.com/5MXFb5fx
3. http://pastebin.com/QmWFFSF3
4. http://pastebin.com/xPHR9GFZ
5. http://pastebin.com/sgETQ6tR
6. http://pastebin.com/FNjTZEF0
7. http://pastebin.com/wTVkT0ZL
8 similar to 7 so i didn't paste it
9. http://pastebin.com/UbxVkx5R

These are all different btw and all happened within 12 hours

**Comment by bloodmc** [comment]
1.8.9 is no longer supported. Update to latest SF 1.10.2+ builds.
