### ISSUE TITLE
[1.10.2] Boats are 12.6% of tick

### ISSUE THREAD

**Issue by Rasgnarok** [SpongePowered/SpongeForge#869]
Finally got my sponge timings working (s/o to Aikar for making this a thing), and I have somehow found that `minecraft:boats` are taking a whooping 12.6% of a server tick, greater than `tile.Entity` check or `BlockUpdates`.

Here's the report:
https://timings.aikar.co/v2/?id=0c1922d4d6284191bec8bbc45993a4cc&section=lagsummary

**Running:**
`spongeforge-1.10.2-2073-5.0.0-BETA-1683.jar
Nucleus-0.7.2-S5-1.10-plugin.jar
Polis-2.6.9-1.10.2.jar
Forge 2073`

**Comment by ryantheleach** [comment]
check for elytra launchers using boats.

**Comment by Aaron1011** [comment]
This is most likely an issue in Vanilla(possibly caused by the collision detection boats now do to auto-mount entities). However, we could look into ways to improve the performance in Sponge.

**Comment by bloodmc** [comment]
@Rasgnarok Unable to reproduce this with latest SF builds.
