### ISSUE TITLE
[1.10.2] minecraft:stop doesn't stop

### ISSUE THREAD

**Issue by Rasgnarok** [SpongePowered/SpongeForge#870]
Ever since moving to 1683, I have had to deal with my server frequently being unable to shutdown by itself, through console or in-game command. Normally, you can wait around 2-3 minutes (which is still too long), and it will shutdown eventually, but more often that needed, I have to manually kill screens or java processes. [So, here's an example of how long it can take for stop to work (and in this case, to not work)](https://gyazo.com/22ef5db89bf43904d9ac039469b13497).

**Comment by gabizou** [comment]
The log is showing that nucleus is performing the shutdown command, not the vanilla stop command.

**Comment by ryantheleach** [comment]
https://github.com/NucleusPowered/Nucleus/blob/1aed4e9912b0f492f12a35caed609201c4028117/src/main/java/io/github/nucleuspowered/nucleus/modules/admin/commands/StopCommand.java#L38

**Comment by Rasgnarok** [comment]
I have sent it over to Nucleus as well, and they've reported the same issue. This wasn't causing a problem until I updated to `sf 1683`, so this is why I am here and not there.

**Comment by Nentify** [comment]
Also having this issue, I typed /minecraft:stop to ensure it wasn't nucleus (which I think just logs all commands) and it doesn't work. Experienced it in the recent builds; it worked fine before.

**Comment by Zidane** [comment]
I've typed /stop at least 50 times today on latest bleeding, works every time.

**Comment by Nentify** [comment]
It's been alright recently, it could just be when the server is overloaded - In my case anyway. I'll update if I can find anything else.

**Comment by Nentify** [comment]
It seems running the command from console doesn't work properly, but running /stop in-game works fine.

**Comment by Zidane** [comment]
@Nentify 

I've did it both in-game and in console. Primarily from console. No issues.
