### ISSUE TITLE
[1.10.2] Pistons are flashing

### ISSUE THREAD

**Issue by ziceptor** [SpongePowered/SpongeForge#872]
Pistons are flashing. During the return movement.  [video](https://cloud.mail.ru/public/DvoD/NtmXKGks1)

**Comment by kosakriszi** [comment]
I may be wrong, but this is vanilla rendering behavior, and is not an issue with SponeForge.

**Comment by Cybermaxke** [comment]
@kosakriszi This isn't a rendering issue, when the piston is supposed to retract, the block state is set. So the retracting animation is never played, causing the flash.

**Comment by kosakriszi** [comment]
@Cybermaxke So... a rendering issue? :joy:

**Comment by ryantheleach** [comment]
@kosakriszi I can't reproduce this on vanilla.

**Comment by kosakriszi** [comment]
@ryantheleach Okay, then I was wrong. Thanks for the confirmation!

**Comment by superon** [comment]
i can reproduce this with OptiFine;)

**Comment by ziceptor** [comment]
Not a problem sponge. It affects NoXray. https://cloud.mail.ru/public/8jX6/xm1C9ekid
