### ISSUE TITLE
[1.10.2] Rabbits are 2.43% of server tick

### ISSUE THREAD

**Issue by Rasgnarok** [SpongePowered/SpongeForge#873]
Title says it all - whilst looking into my server's timings, I found that rabbits seem to cause quite a fair amount of issues, especially in high quantities. With a normal amount of them (eg, only as natural spawns) they count for [2% of the server tick](https://gyazo.com/f05567258ebf42c9fcb6ba02ba854835), more than any other mob.

While this might be core Minecraft issues, could Spongeforge deal with entity optimization? Or at least, provide a way to block off entities like these that seem to cost performance, even if just a little bit.

https://timings.aikar.co/v2/?id=01ea69b04b364f4ead9a13e9bc36346d&section=all

```
Spongeforge: 1683
Forge: 2073
```

**Comment by bloodmc** [comment]
[+]Minecraft::tickEntity - minecraft:rabbitcount(7044) total(0.10% 0.338s, 0.15% of tick)  avg(0.05ms per - 0.07ms/1.52 per tick)

0.10%, always look at the entire duration and not just a spike. Also, entity activation settings are in config for a reason, use them if you want to improve performance with entities. Read docs on how to configure.
