### ISSUE TITLE
[1.10.2]People can drop items before they login into the account

### ISSUE THREAD

**Issue by 5igm** [SpongePowered/SpongeForge#874]
The problem is still existing. Now, if people use "q" to try to drop some items before login, items will not be dropped on the ground, but items will be deleted.
https://github.com/games647/FlexibleLogin/issues/35
spongeforge-1.10.2-2073-5.0.0-BETA-1689

**Comment by ryantheleach** [comment]
Possible duplicate: https://github.com/SpongePowered/SpongeAPI/issues/1346

**Comment by Zidane** [comment]
@Faithcaio 

Is this old issue still an issue?

**Comment by Faithcaio** [comment]
I tested canceling `ClickInventoryEvent.Drop.Single` in API7 and 5 both working as expected.
