### ISSUE TITLE
gravel crash

### ISSUE THREAD

**Issue by aglarcz** [SpongePowered/SpongeForge#875]
Hello,
using build 1653 i got this crash on my server: http://pastebin.com/raw/fUbupsXP

I googled and find its sponge related, happening when chunks with gravel are generated, is it true? Any fix for that?

**Comment by ST-DDT** [comment]
Could you test it again with the latest build?
http://files.minecraftforge.net/maven/org/spongepowered/spongeforge/
Maybe this helps, although there aren't any changes in that class you are having issues with.

Ref: [CauseTracker.java#L1112](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/event/CauseTracker.java#L1112)

**Comment by Zidane** [comment]
Re-test with stable-5 and re-open if it still occurs.
