### ISSUE TITLE
[1.10.2] EntityJoinWorldEvent Error

### ISSUE THREAD

**Issue by Rasgnarok** [SpongePowered/SpongeForge#877]
I have been having a recurring issue with Sponge not liking the handling of a forge mod's EntityJoinWorldEvent, giving an error on console that rather spams the place. Here's the [pastebin of the error](http://pastebin.com/JvmdghnC). It needs to be relaying the event, yet it struggles to do so. If it is of any relevance, the handle of the event is often cancelled, which might be the actual issue.

Currently using `spongeforge-1.10.2-2073-5.0.0-BETA-1692.jar` and `Forge 2073`

**Comment by bloodmc** [comment]
Fixed in latest builds.
