### ISSUE TITLE
[1.10.2] TickNextTick exception

### ISSUE THREAD

**Issue by lenis0012** [SpongePowered/SpongeForge#879]
I have an issue on SpongeForge when i paste in relatively small schematics,and its not running out of ram.
Our server runs on 16GB of ram and a perm gen of 512MB.
WorldEdit: 6.1.4-SNAPSHOT (Sponge API edition)
Sponge: 1.10.2-2073-5.0.0-BETA-1687
Forge: 12.17.1.2073

Error: http://pastebin.com/Zrf9VT5P

Note: I first reported this to WorldEdit, but i was told this is a sponge issue.

**Comment by Aaron1011** [comment]
@lenis0012: Can you list the steps you too to reproduce this?

As a side note, the perm gen setting was removed in JRE 8, so setting that won't do anything.

**Comment by lenis0012** [comment]
@Aaron1011 oh, i forgot. I thought it used to give you a warning tho.

1. Install forge
2. Install sponge
3. Install worldedit
4. Paste any decently sized schematic.
5. witness as your server crashes without even consuming 5% of its resources

All the versions are listed above.
It may be worth noting I also installed Pixelmon, TConstruct and a bunch of other small mods.
I tried using the WorldEdit forge edition, but that was even worse.

**Comment by Rasgnarok** [comment]
I haven't had an issue with Forge's worldedit - got any logs? If in doubt, try removing mods one by one and see if it works; if it does, you got your culprit.

**Comment by lenis0012** [comment]
@Rasgnarok no errors, just pastes one array of chunks and does not finish the paste.
It alsos eems to paste in a beacon for some reason.

Point is tho, WorldEdit should work on sponge, or so the dev said. but it doesnt

**Comment by wizjany** [comment]
i've been unable to reproduce this either. my guess is that a certain block (probably from one of your mods) in the schematic is causing issues.

**Comment by lenis0012** [comment]
@wizjany It is a schematic made in vanilla.
ill upload it tonight so you can try it out

**Comment by bloodmc** [comment]
closing as there has been no response for over a month.
