### ISSUE TITLE
Command block clock is broken

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/SpongeForge#883]
Using a command block, it's possible to make a fast redstone clock. However, Sponge currently breaks this.

Steps to reproduce:
1. Place down a command block with this command: `setblock ~1 ~ ~ minecraft:redstone_block 0 destroy`
2. Place down a redstone block +1 blocks away on the x axis. If in doubt, power the command block to see where it places a redstone block. Then, remove the power source, and the placed redstone block, and place a new redstone block where the old one was placed.
3. Observe that the command block replaces the redstone block once (causing a breaking sound, and a dropped item), and then stops.

Repeat the above steps in Vanilla, and observe that the command block rapidly breaks and replaces the redstone block (causing break noises to rapidly play, and items to rapidly drop).

**Comment by ghost** [comment]
I can confirm this. Using a regular command block ("impulse" mode, "needs redstone").

Forge Version: 1.10.2-12.18.2.2171
SpongeForge Version: 1.10.2-2171-5.1.0-BETA-1933
Mod(s): Extra Utilities v2-1.10.2-1.1.1

No important logs, just information about block placing from command.

**Comment by Zidane** [comment]
@Aaron1011 

Is this still an issue?

**Comment by gabizou** [comment]
@Zidane reproduced the issue, unsure how to actually resolve it since other similar block style clocks work, just not this one. You can find out how to make them here: http://minecraft.gamepedia.com/Clock_circuit#Setblock_clock

**Comment by bloodmc** [comment]
@Aaron1011 See if you can track down this bug and fix.

**Comment by phit** [comment]
still an issue with spongeforge-1.12.2-2529-7.0.0-BETA-2741.jar

**Comment by ryantheleach** [comment]
I'll retest this tonight considering the latest refactors.

**Comment by ryantheleach** [comment]
Still applicable to spongeforge-1.12.2-2705-7.1.0-BETA-3355.jar 

I tried disabling (production sponge configs) to disable tracking and a few others, but it still continued to fail.

will take debugging or disabling random mixins.

I tested Mojang Vanilla: Works.

Tested Forge: Works.

Tested Sponge with Panda's redstone, also fails.

**Comment by phit** [comment]
fixed in 1.12.2-2825-7.1.6-RC3740
thanks to @i9hdkill for testing
