### ISSUE TITLE
[1.8.9] Item duplication with itemframes and signs

### ISSUE THREAD

**Issue by Varijon** [SpongePowered/SpongeForge#884]
When a sign is placed over an itemframe containing an item and the block behind it is broken, both the itemframe and the item will duplicate. This does not occur in vanilla, where the itemframe will stay in the air for a bit there and pop normally after.

A quick gif demonstrating:
http://i.imgur.com/1xx0k7A.gifv

To confirm, made a clean server:
forge-1.8.9-11.15.1.1902-1.8.9-universal
spongeforge-1.8.9-1890-4.2.0-BETA-1693

This is also posted in the support section, but by now I confirmed this is a spongeforge issue.

**Comment by Varijon** [comment]
I'll add a bit more info:
Does not occur in vanilla (base game)
Does not occur with just forge (no mods)
It works with any item

This is a pretty serious issue for a server's economy, I'm worried this issue is going unnoticed.

**Comment by Aaron1011** [comment]
@Varijon: Sorry for the very long delay in getting this. It should be fixed on the latest SpongeForge.
