### ISSUE TITLE
Spongeforge and Veinminer don't work together

### ISSUE THREAD

**Issue by BakermanLP** [SpongePowered/SpongeForge#889]
Here is my setup:
- forge 2073
- spongeforge 2073...1705
- veinminer 0.34.1.1.9r571...

Without spongeforge it is working, with spongeforge it doesn't.

Do you know why?

Cross Ref: https://github.com/portablejim/VeinMiner/issues/76

Thanks for reading

Michael (aka BakermanLP)

**Comment by Zidane** [comment]
What doesn't work? Server logs?

We need a LOT more information before any attempts of investigation.

**Comment by BakermanLP** [comment]
It is simple ... Veinminer is working in server environment without sponge. If I start the server with spongeforge, veinminer doesn't work. Sorry, but no error logs, no crashlogs, neither on server or client side.

This can be really easy be achieved by only using:
- forge 2073
- spongeforge 2073...1705
- veinminer 0.34.1.1.9r571...
on server side, 
- forge 2073
- veinminer 0.34.1.1.9r571...
on client side. No additional configuration needed. Just delete spongeforge on server side and it works.

**Comment by Zidane** [comment]
Okay now tell us WHAT doesn't work.

**Comment by BakermanLP** [comment]
Simple as is ... vein mining doesn't work. Press the configured key in the key bindings with an axe in the hand and chopping the lowest log. That should cut down the whole tree. But only the lowest block will be cut down as usual

**Comment by BakermanLP** [comment]
Just forgot one thing. Source code of modern is available at https://github.com/portablejim/VeinMiner
Mod is available  at https://minecraft.curseforge.com/projects/veinminer/files

**Comment by bookerthegeek** [comment]
Veinminer: a mod for mining multiple blocks of the same type as the first one broken as long as they are connected. For example to mine out a complete vein of iron ore. Usually bound to holding a jey, but can be a toggle on/off.

When on forge if you take an axe and chop (mine) the bottom block of a tree it will chop the entire tree down.

On SpongeForge this does not happen.

**Comment by Aaron1011** [comment]
The cause of this issue is Sponge's block capturing. VeinMiner explicitly compares the blockstate in Forge's `BreakEvent` to the actual block in the world, probably to detect changse by other mods. In Sponge, the actual block in the world will always be `AIR`, so VeinMiner won't perform its actions.

**Comment by Aaron1011** [comment]
I don't think this issue is fixed - I have some code in a branch that I need to revist.

**Comment by xorinzor** [comment]
@Aaron1011 is this still an actual issue? or has it been solved in a recent build/release?

**Comment by phit** [comment]
working fine, no stacktraces in the consoler either! tested with 

spongeforge-1.11.2-2393-6.1.0-BETA-2468.jar
VeinMiner-1.11-0.36.0.621+8499b73.jar

and 

spongeforge-1.10.2-2281-5.2.0-BETA-2464.jar
VeinMiner-1.9-0.36.0.609+0056a96.jar

@Aaron1011 unless you still want to revisit this I consider this fixed
