### ISSUE TITLE
ChangeBlockEvent.Pre doesn't fire for modded fluids

### ISSUE THREAD

**Issue by cosmocosma** [SpongePowered/SpongeForge#892]
```
SpongeForge
    Minecraft: 1.10.2
    SpongeAPI: 5.0.0-SNAPSHOT-ecade96
    SpongeForge: 1.10.2-2073-5.0.0-BETA-1700
    Minecraft Forge: 12.18.1.2076
```

**Comment by Aaron1011** [comment]
@bloodmc: I'm not sure exactly where the hooks should go in Forge's base Fluid block classes. Can you take care of this?

**Comment by phit** [comment]
Minecraft Forge: 14.23.0.2529
Sponge https://github.com/SpongePowered/SpongeForge/commit/3541ce62d63fc516b1b0fd859e2103b31d0c8d19

Still an issue, tested by placing a bucket of water and then a Tinker's Construct Bucket

**Comment by ryantheleach** [comment]
Still applies to spongeforge-1.12.2-2705-7.1.0-BETA-3355.jar , forge-1.12.2-14.23.4.2739-universal.jar
