### ISSUE TITLE
[1.10.2] Nether Portals

### ISSUE THREAD

**Issue by Rasgnarok** [SpongePowered/SpongeForge#895]
When using a Nether Portal and on creative mode, you get stuck in a teleporting loop due to the instanteneous teleporting, which doesn't allow you to leave the portal's zone before teleporting you again. Furthermore, if you've manually set the Nether's world border, you will have instances where players can create Nether portals that teleport them over the world border, suffocating them upon usage.
```
Spongeforge 1687
Forge 2076
```

**Comment by bloodmc** [comment]
This was fixed in later builds.
