### ISSUE TITLE
[1.10.2] chunk 0, 0 not loading!

### ISSUE THREAD

**Issue by FiveEYZ** [SpongePowered/SpongeForge#898]
Chunk 0, 0 stopped loading for some reason.

https://gyazo.com/b9c66f7a8622c7f9baf35acf8e255a50

https://gyazo.com/1a53e48e6b7f786f077a785204cb5041

updated to from SpongeForge Build 1705 -> 1709

**Comment by Aaron1011** [comment]
It looks like the chunk may be corrupted. Can you pastebin your full `fml-server-latest.log`?

**Comment by FiveEYZ** [comment]
sorry for not including it, here it is:
https://gist.github.com/FiveEYZ/1080ee5b97c602bd3d155c6f69a2bbe8

**Comment by bloodmc** [comment]
@FiveEYZ Can you let me know which build this started to occur in? Thanks!
