### ISSUE TITLE
[1.10.2] experience of minecraft:mob_spawner

### ISSUE THREAD

**Issue by ziceptor** [SpongePowered/SpongeForge#899]
The player can fill his experience of minecraft:mob_spawner. [Video](https://cloud.mail.ru/public/8MFV/BwADmKkL4). Protected plugin foxguard. [gravityfox response](https://forums.spongepowered.org/t/api-4-2-x-5-x-foxguard-the-flexible-world-protection-solution/9952/613?u=ziceptor)

**Comment by Zidane** [comment]
Re-test with stable-5 and re-open if it still occurs.

**Comment by FabioZumbi12** [comment]
More users reporting this same issue with experience drops without break the block, but now with Redprotect.

https://forums.spongepowered.org/t/shield-anti-grief-with-flag-gui-redprotect-1-8-9-1-11/11846/454

**Comment by bloodmc** [comment]
@JBYoshi is this still an issue?

**Comment by JBYoshi** [comment]
Can reproduce on latest bleeding.
