### ISSUE TITLE
[1.10.2] No structure Dungeons/Village generated

### ISSUE THREAD

**Issue by fpoulet73** [SpongePowered/SpongeForge#906]
Forge 2079
SpongeForge 7032
Without the mod village/dungeons are generated correcly but the spongeForge is there, no structure are generated.
There are no other mod activated, only spongeForge.
My server is running on Fedora 22
Except this issue the server is very stable.

**Comment by ST-DDT** [comment]
Could you provide a seed and a location for testing purposes?

**Comment by fpoulet73** [comment]
atout.be:25566
seed: -1276505101678576079

**Comment by fpoulet73** [comment]
is the above information enough ? 
 I have no idea from which build it is there.
I just start working with sponge on 1.10.2 since 2 weeks, before it was on 1.8 long time ago.

**Comment by fpoulet73** [comment]
I just make a new test, with a full installation from scratch.
Same issue, village is there without spongeForge but not there if mod is activate. Using same seed

**Comment by Deamon5550** [comment]
I'll look into it.

**Comment by nalllen** [comment]
I'm having the exact same issue
