### ISSUE TITLE
Mod dimension registration/unregistration needs improvements

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/SpongeForge#910]
While trying to reproduce a bug with [RFToolsDimensions](https://github.com/McJty/RFToolsDimensions), I discovered a couple of problems in the way that Sponge currently handles mod dimensions:
- We currently [assume that a given DimensionType is only used for one provider id](https://github.com/SpongePowered/SpongeForge/blob/bleeding/src/main/java/org/spongepowered/mod/mixin/core/forge/MixinDimensionManager.java#L197). However, mods such as RFToolsDimensions register a DimensionType multiple times for different providers, which creates duplicate `WorldArchetype` ids.
- We assume that unregistered dimensions can never be re-registered. However, RFToolsDimensions [explicitly re-uses its own unregistered ids](https://github.com/McJty/RFToolsDimensions/blob/1.10/src/main/java/mcjty/rftoolsdim/dimensions/RfToolsDimensionManager.java#L366). I'm not entirely certain if Forge intended to allow this - but if it does, we may need to re-think how we handle `WorldArchetype`s. Does it make sense to remove a `CatalogType` after it's been added?

Pinging @Zidane and @gabizou for feedback.

**Comment by Inferius77** [comment]
Yes this issue occurs on my server too.  Player tried to enter a new dimension made with Rftools Dimensions and the server crashed.   I hope spongeforge and/or @McJty find a solution to this.

**Comment by McJty** [comment]
Reusing a DimensionType for different providers is certainly how it is supposed to work and can't be avoided in the case of rftools dimensions. There is a readon DimensionType is distinct (and has a different ID) from dimensions themselves.

As to the second (reregistering) not sure but the api is there in forge to do this (unregister dimensions) so I don't see why it wouldn't be allowed?

**Comment by Aaron1011** [comment]
@McJty: This is a bug in how Sponge handles dimensions internally. Mods shouldn't have to change anything - this is purely a Sponge issue.

**Comment by Inferius77** [comment]
Actually I was just reading the patch notes and the latest stable spongeforge says this:
1.10.2-2202-5.1.0-BETA-2059 
https://github.com/SpongePowered/SpongeCommon/commit/876d09be834a8a4c06a80fe73fb75931cebbbb66
https://github.com/SpongePowered/SpongeCommon/commit/ee116d6c1cea21c46e2b5fc002566c9c8607854c

Those are links to the "fixes" referenced on the downloads page for that spongeforge version I listed.  I couldn't copy paste the notes on my phone.   That was 21 hours ago.  Does this fix what you said is the issue @Aaron1011  ?

**Comment by Aaron1011** [comment]
@Inferius77: Unfortunately, no - this is a separate issue, and will require much more extensive changes than those issues.

**Comment by bloodmc** [comment]
SpongeCommon commit https://github.com/SpongePowered/SpongeCommon/commit/dbf3c828d24cba094ef118b6e5aa1086a3db2b17
