### ISSUE TITLE
[1.10.2] Another Ticking player

### ISSUE THREAD

**Issue by FiveEYZ** [SpongePowered/SpongeForge#911]
A player were mining using a tinker's pickaxe with fortune 2 modifier on a trier 2 Pillar from the mod [Roots](https://minecraft.curseforge.com/projects/roots/files/2328890)

https://gist.github.com/FiveEYZ/d4e27e792e2913a59f313ce43d3351dd

**Comment by Aaron1011** [comment]
@FiveEYZ: Are you able to reproduce this with just those two mods, on the latest SpongeForge?

**Comment by Zidane** [comment]
Re-test with stable-5 and re-open if it still occurs.
