### ISSUE TITLE
[1.10.2] Roots drops

### ISSUE THREAD

**Issue by FiveEYZ** [SpongePowered/SpongeForge#912]
When using a tool (Bark Knife) from this mod in forge+sponge environment you don't get any loot (bark)

expected to happen:
Use Bark Knife on Oak Wood to get Oak Bark.

happens instead:
Use Bark Knife on Oak Wood yields no Oak Bark.

Logs:
[fml-server-latest.log](https://gist.github.com/FiveEYZ/b8f9d359f918fcc36cd0d6ad4221cb24)
[latest.log](https://gist.github.com/FiveEYZ/c1d85f535e82d7e3c454bc78aedc5e2f)

Using:
    Minecraft: 1.10.2
    SpongeAPI: 5.0.0-SNAPSHOT-b88f5eb
    SpongeForge: 1.10.2-2092-5.0.0-BETA-1746
    Minecraft Forge: 12.18.1.2092
and 
    [roots-1.10.2-0.202.0](https://minecraft.curseforge.com/projects/roots/files/2328890)

**Comment by ryantheleach** [comment]
Can you split the description into what you expected to happen, and what happens instead?

**Comment by Stuart74** [comment]
This also occurs on my server image below of what occurs 

[Inage](http://files.enjin.com.s3.amazonaws.com/499751/modules/forum/attachments/output_oldex4_1472056107.gif)

Supposed to be able to retrieve bark when you use the bark knife but currently we get nothing back at all with sponge installed as i tested this in single player and non sponge server and it works as it normally would. 

Sponge Version spongeforge-1.10.2-2092-5.0.0-BETA-1752
Forge Version 12.18.1.2092
Root Version 1.10.2-0.203.0

Link to Roots GITHUB Issue raised https://github.com/RootsTeam/Roots/issues/111

Really do not know how much simpler we need to be to say it though for you 

With sponge installed - Use bark knife get no bark in return 
Without sponge installed - Use bark knife get bark in return,

**Comment by ryantheleach** [comment]
https://github.com/RootsTeam/Roots/blob/master/src/main/java/elucent/roots/item/ItemDruidKnife.java

**Comment by Stuart74** [comment]
This means ?

**Comment by ryantheleach** [comment]
Just a convenient link for anyone else attempting to look into the issue.

**Comment by Aaron1011** [comment]
Fixed in https://github.com/SpongePowered/SpongeCommon/commit/11a395e468b175d37db0e5bbcdf7d9b827f3e2d4. Sorry for the long delay in getting to this.
