### ISSUE TITLE
Couldn't save chunk; already in use by another instance of Minecraft?

### ISSUE THREAD

**Issue by ThornsOfire** [SpongePowered/SpongeForge#913]
Error throws on save-all and plugin world save events. Spams for a bit then stops, worlds do not save.

Debian MineOS-Node

Installed Plugins:
 permissionsex
 Version: 2.0-SNAPSHOT-b142

 sponge
 Version: 1.10.2-2079-5.0.0-BETA-1737

 foxcore
 Version: 0.9.4-api5-157

 FML
 Version: 8.0.99.99

 spongeapi
 Version: 5.0.0-SNAPSHOT-fd6816c

 foxguard
 Version: 0.19.3-dev-api5-319

 pjp
 Version: 0.12.4

 Forge
 Version: 12.18.1.2079

 mcp
 Version: 9.19

 pjw
 Version: 0.10.4

 Minecraft
 Version: 1.10.2

Lastest.log
http://pastebin.com/L5d9dBA0

fml-server-latest.log
http://pastebin.com/xmETGfeq

**Comment by Zidane** [comment]
@ThornsOfire 

Remove PJP and PJW, install Nucleus, have it create your worlds and see if this happens.

**Comment by ThornsOfire** [comment]
Will test that when I get home!

**Comment by ThornsOfire** [comment]
Works fine with Nucleus! Not a sponge error I'll talk to the author.
