### ISSUE TITLE
Server console - Catched unhandled exception : [class net.blay09.mods.cookingforblockheads.tile.TileToaster] java.lang.NullPointerException

### ISSUE THREAD

**Issue by ProsperCraft** [SpongePowered/SpongeForge#915]
I started getting this in console after installing spongeforge-1.10.2-2092-5.0.0-BETA-1746.jar

http://pastebin.com/aSaWQvBa

**Comment by ProsperCraft** [comment]
Thank happens when opening the cooking table.

**Comment by Zidane** [comment]
Fixed as of latest build.

**Comment by ProsperCraft** [comment]
Please re-open

http://pastebin.com/FVjbbS1V

Not fixed in 1747.

After updating it removed the block from the server as well as the drying rack above it with pans, when a new cooking table was placed down, it started showing the error in console again.

**Comment by Aaron1011** [comment]
@ProsperCraft: That should be fixed in https://github.com/SpongePowered/SpongeCommon/commit/dba74a15555931edbbff84fcec252cc8c3f1108e. It turns out that some mods set `Slot.inventory` to null.

**Comment by ProsperCraft** [comment]
Thank you for adding that patch.

Forgive my ignorance, but do the new builds that just came out now have that patch?

**Comment by Aaron1011** [comment]
@ProsperCraft: Yes, they do :)

You can check the changelog (available on the main downloads page) to see the commit messages included in a particular build - though the messages themselves aren't always that helpful (e.g. `Update SpongeCommon`).

**Comment by ProsperCraft** [comment]
http://pastebin.com/jkV2DShT

Here is a new one from the calculator mod using build 1749

**Comment by ProsperCraft** [comment]
Perhaps we shouldn't close this till its really fixed? :)  please reopen.

**Comment by Zidane** [comment]
@ProsperCraft 

Your previous issues were fixed. While we fixed those, this mod is causing us to code definitively to fix more things.

**Comment by ProsperCraft** [comment]
ok, this looks just like the others, thought it was the same, I Will post a new issue.  Thank you.

**Comment by ProsperCraft** [comment]
https://github.com/SpongePowered/SpongeForge/issues/917
