### ISSUE TITLE
Null pointer on server console - at org.spongepowered.common.item.inventory.lens.impl.fabric.ContainerFabric.getFirstDisplayName

### ISSUE THREAD

**Issue by ProsperCraft** [SpongePowered/SpongeForge#917]
http://pastebin.com/jkV2DShT

Minecraft version 1.10.2

Modpack - Allthemods 

Sponge version 1749

**Comment by Aaron1011** [comment]
This is a bug in the mod - I've opened an issue [here](https://github.com/SonarSonic/Sonar-Core/issues/8).

**Comment by Aaron1011** [comment]
@ProsperCraft: The issue [has now been fixed in SonarCore](https://github.com/SonarSonic/Sonar-Core/commit/f109c54d9264a6f42e9322edb944f6f0f0a4abce)
