### ISSUE TITLE
EntityEvent#getTargetEntity() returns null for PlaySoundAtEntityEvent

### ISSUE THREAD

**Issue by caseif** [SpongePowered/SpongeForge#919]
Simple as that. Seeing as this method does not return an `Optional`, it is implied that it is guaranteed to return a non-`null` value, an assumption which is violated in this case.

Additionally, it seems odd to pass Forge events to plugins which aren't exposed in any  by the API - perhaps a filter could be implemented which only passes events which have an appropriate representation in the API?

**Comment by Zidane** [comment]
Paste your plugin's code.

**Comment by caseif** [comment]
It's not strictly relevant - it just listens to the `TargetEntityEvent` and calls `getTargetEntity`.

**Comment by simon816** [comment]
It seems odd that the event has a null entity. Could you print the stacktrace when the error occurs so we can see where the null entity is being passed in.
I did a quick test (on 1.8.9) and could not reproduce this

Also some version numbers would be good.

**Comment by kashike** [comment]
The `player` parameter of `playSound` [is `@Nullable`](https://github.com/MinecraftForge/MinecraftForge/blob/1.10.x/patches/minecraft/net/minecraft/world/World.java.patch#L178-L180).
```
05:13:37 MCPBot_Reborn | === MC 1.10.2: net/minecraft/world/World.playSound (aid.a) UNLOCKED ===
05:13:37 MCPBot_Reborn | Name       : a => func_184148_a => playSound
05:13:37 MCPBot_Reborn | Descriptor : (Lzs;DDDLni;Lnk;FF)V => (Lnet/minecraft/entity/player/EntityPlayer;DDDLnet/minecraft/util/SoundEvent;Lnet/minecraft/util/SoundCategory;FF)V
05:13:37 MCPBot_Reborn | Comment    : None
05:13:37 MCPBot_Reborn | SRG Params : EntityPlayer p_184148_1_, D p_184148_2_, D p_184148_4_, D p_184148_6_, SoundEvent p_184148_8_, SoundCategory p_184148_9_, F p_184148_10_, F p_184148_11_
05:13:37 MCPBot_Reborn | MCP Params : EntityPlayer player, double x, double y, double z, SoundEvent soundIn, SoundCategory category, float volume, float pitch
05:13:37 MCPBot_Reborn | Last Change: 2016-03-03 19:19:27.519330-05:00 (kashike)
```

**Comment by simon816** [comment]
right, looks like something changed in recent versions.
I guess the sponge event bus should just ignore this event then

**Comment by ryantheleach** [comment]
Assigning myself to create a test plugin that's able to catch when this happens, verify it still happens, and to reply with a test plugin/mod.

**Comment by liach** [comment]
I suggest moving that event to another category (network events that have specified receivers)
