### ISSUE TITLE
Server Crash - RFTools - author kicked it back to sponge.

### ISSUE THREAD

**Issue by ProsperCraft** [SpongePowered/SpongeForge#920]
https://github.com/McJty/RFTools/issues/749

**Comment by hunter688** [comment]
Try replicate without sponge, if success report to mod author back.

**Comment by bloodmc** [comment]
Fixed in latest. SpongeCommon commit can be found here
https://github.com/SpongePowered/SpongeCommon/commit/dbf3c828d24cba094ef118b6e5aa1086a3db2b17
