### ISSUE TITLE
Armour plus end dragon zombies take no damage with sponge installed.

### ISSUE THREAD

**Issue by ProsperCraft** [SpongePowered/SpongeForge#921]
With sponge 1752 installed end dragon zombies take no damage from players.

Remove sponge, and they take damage.

Modpack- allthemods version 1.28

**Comment by Zidane** [comment]
We need way more information on this. EnderDragon + Zombies + whoever take damage just fine on a test server I have with SpongeForge.

**Comment by FiveEYZ** [comment]
"end dragon zombies" is a custom mob created by the mod ArmourPlus
https://github.com/TheDragonTeam/ArmorPlus/blob/1.10.2/src/main/java/net/thedragonteam/armorplus/entity/entityzombie/EntityEnderDragonZombie.java

**Comment by ProsperCraft** [comment]
This is still happening with the 5.0 Release - Build 1808

**Comment by phit** [comment]
can't reproduce this, tested with 

armorplus-1.11.2-10.7.0.1.jar
Forgelin-1.5.0.jar
jei_1.11.2-4.5.0.291.jar
spongeforge-1.11.2-2393-6.1.0-BETA-2468.jar
thedragonlib-1.11.2-3.2.2.jar

and

armorplus-1.10.2-8.7.1.2.jar
jei_1.10.2-3.14.7.419.jar
spongeforge-1.10.2-2281-5.2.0-BETA-2464.jar
thedragonlib-1.10.2-1.0.3.1.jar
