### ISSUE TITLE
KeepInventory Dimensions

### ISSUE THREAD

**Issue by Dysthymic** [SpongePowered/SpongeForge#922]
KeepInventory mode only works in the Overworld. It does not follow rules in the Nether or The End. We've applied keepinventory true in the End and Nether for our tests.

Using 1692 and tested on latest 1752 as well

**Comment by Vauxite** [comment]
Confirmed with this version.

Minecraft 1.10.2
spongeAPI: 6.0.0-SNAPSHOT-cebc736
SpongeForge 1.10.2-2107-6.0+.0-BETA-1836
Minecraftforge 12.18.2.2107

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/SpongePowered/SpongeCommon/commit/4be85ed231ccedd8326761f0aa314b65b21749ae
