### ISSUE TITLE
Mob drops not working?

### ISSUE THREAD

**Issue by Abelatox** [SpongePowered/SpongeForge#924]
Hello, I'm Abelatox and I have a problem, I want to host a Kingdom Keys server with Sponge so it can have some plugins, The thing is that mobs do not drop the mod loot.
Any help?
I'm using:
spongeforge-1.10.2-2073-5.0.0-BETA-1710
forge-1.10.2-12.18.1.2073

**Comment by bloodmc** [comment]
You are using an outdated build. Update to latest SF build.

**Comment by Abelatox** [comment]
It keeps happening with this one: spongeforge-1.10.2-2092-5.0.0-BETA-1756
