### ISSUE TITLE
Console warn: Unable to find InventoryPacketState

### ISSUE THREAD

**Issue by aso824** [SpongePowered/SpongeForge#925]
I see in console that I get this warning sometimes:

`[Server thread/WARN] [Sponge]: Unable to find InventoryPacketState handler for click window packet: CPacketClickWindow{windowId=29, slotId=-999, used
Button=4, actionNumber=20, clickedItem=null, mode=QUICK_CRAFT}`

Where `windowId` and `actionNumber` changes.
This warning occured to my friend, I was unable to reproduce this.
Also, this not affect game in any way, only spams console.

Server:
`Minecraft: 1.10.2`
`SpongeAPI: 5.0.0-SNAPSHOT-906f7ab`
`SpongeForge: 1.10.2-2092-5.0.0-BETA-1756`
`Minecraft Forge: 12.18.1.2094`

`Plugins (9): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, keys, SignEditor, SimpleTags`

**Comment by Aaron1011** [comment]
This has been fixed in the latest SpongeForge/SpongeVanilla.
