### ISSUE TITLE
[1.10.2] Crach: Ticking block entity

### ISSUE THREAD

**Issue by FiveEYZ** [SpongePowered/SpongeForge#928]
updated from:
`spongeforge-1.10.2-2092-5.0.0-BETA-1759`
to
`spongeforge-1.10.2-2092-5.0.0-BETA-1770`

and now im getting this crash just after the world loads:
https://gist.github.com/FiveEYZ/6bb868478952c7d3984eddd5a2881c24

**Comment by gabizou** [comment]
This is actually a FakePlayer having an invalid `EntityType`, @simon816 I believe you know more than I do to fix this issue, if not @Zidane or @Aaron1011.

**Comment by Aaron1011** [comment]
Should be fixed in https://github.com/SpongePowered/SpongeCommon/commit/bd1b26b8b25d76339c87c447c8baa3c8e5f1bc63.
