### ISSUE TITLE
Issues with Ender Dragon, some mods and a lot of broken things...

### ISSUE THREAD

**Issue by Korvynus** [SpongePowered/SpongeForge#933]
Forge Version: 1.10.2-12.18.1.2092

Sponge Version: 1.10.2-2092-5.0.0-BETA-1759

I'm currently running 70 mods in my modpack. Since I installed Sponge on my server, a lot of things are broken.

1. Right after respawning the Ender Dragon. I can't destroy the End Crystal that are on the top of each obsidian tower, they are invincible entities unless I use the kill command. Also, it should give me some loot from the Draconic Evolution mod but since Sponge is installed, it gives nothing.

2. Sometime, the Transmutation Table from the ProjectE mod is empty. I must unlearn few items on it before getting everything back. Again, it was working fine before installing Sponge.

3. At the first launch after Sponge was installed, I wasn't able to go in my RFTools dimensions using the Dialing Device. It was necessary to restart the server after dialing a dimension. So... restarted the server 7 times (because I currently have 7 RFTools dimension in my world). Frustrating...

I'm probably forget a lot of things but currently, I only remember those.

Here is my server log from today: https://dl.dropboxusercontent.com/u/11797022/mc/fml-server-latest.log

Unfornately, I found nothing in my log about an error or something for the Transmutation Table or the invicible End Crystal... That's really weird.

**Comment by Zidane** [comment]
Number 3 is already a known issue.

**Comment by Zidane** [comment]
Please split number 1 and 2 into their own issues.
