### ISSUE TITLE
[1.10.1] console spam "Could not pass events"

### ISSUE THREAD

**Issue by FiveEYZ** [SpongePowered/SpongeForge#934]
Here i have a fml-server-latest.log that i copied after 3 min 34 sec uptime

updated from build 1776 to 1778
same spam happens on 1780

https://gist.githubusercontent.com/FiveEYZ/368fd923c8b3e7507e929b890bd14927/raw/b7b9e46ed73e0499816ad07aa23f850712a9dfb5/fml-server-latest.log

what i can see are:
`Could not pass CollideBlockEvent$Impl`
`Could not pass ChangeBlockEvent$Pre$Impl`
`Could not pass ChangeBlockEvent$Break$Impl`
`Could not pass ClientConnectionEvent$Join$Impl`
`Could not pass LoadWorldEvent$Impl`
Could not pass InteractBlockEvent$Secondary$MainHand$Impl

when i shutdown the server i get:
Could not pass UnloadWorldEvent$Impl

SpongeForge
   Minecraft: 1.10.2
   SpongeAPI: 5.0.0-SNAPSHOT-acfbf67
   SpongeForge: 1.10.2-2092-5.0.0-BETA-1778
   Minecraft Forge: 12.18.1.2094

griefprevention-1.10.2-2.1.0.76

**Comment by Aaron1011** [comment]
@FiveEYZ This is an issue with GriefPrevention - @bloodmc  needs to update it for the latest SpongeAPI.
