### ISSUE TITLE
[1.10.2] Crash on Startup with Tinkers and other mods

### ISSUE THREAD

**Issue by bonii-xx** [SpongePowered/SpongeForge#935]
See https://github.com/SlimeKnights/TinkersConstruct/issues/2430

Crashlog: http://pastebin.com/VSBKK6uW
Corresponding line in TiC: https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/library/TinkerRegistry.java#L69

It doesn't happen with only TiC and Sponge, it seems to be a constellation of mods or plugins.

**Comment by hunter688** [comment]
Why You using outdated spongeforge?

**Comment by Aaron1011** [comment]
@bonii-xx: As @hunter688 said, please test this again using the latest SpongeForge.

**Comment by jules552** [comment]
@hunter688 I have updated my SpongeForge today, I have tested and the server still crashing,

**Comment by jules552** [comment]
I think definitely it's a problem with one's of my mods or plugins. I will make some test when I have the time and when I finished the tests, I'll say you the results and what was the problems and which mods or plugins does this crash ;) 

And I forgot to said, sorry for my very bad English ;)

**Comment by hunter688** [comment]
Paste actual crashlog, then try step by step remove mods/plugins to find what mod causing problem.
I have Tinkers on my SpongeForge server and does not crashing.

**Comment by jules552** [comment]
@hunter688 

My crashlog: 
http://pastebin.com/gV4fnfqk

And yes I will test to remove the mods/plugins one by one ;)

**Comment by hunter688** [comment]
Looks like problem is Building bricks mod not Tinkers/Sponge
<pre>
java.lang.RuntimeException: Could not load material from tconstruct:materials/vine.json
    at com.hea3ven.buildingbricks.core.materials.loader.MaterialResourceLoader.loadResources(MaterialResourceLoader.java:30)
    at com.hea3ven.buildingbricks.core.ProxyCommonBuildingBricks.onPreInitEvent(ProxyCommonBuildingBricks.java:86)
</pre>

**Comment by jules552** [comment]
I will try without BuildingBricks

**Comment by hunter688** [comment]
Can be closed, not a SF problem.

**Comment by ryantheleach** [comment]
Are you saying you reproduced this using those mods, but without SF?
