### ISSUE TITLE
Bark from Roots mod doesn't drop with SpongeForge

### ISSUE THREAD

**Issue by dogboy21** [SpongePowered/SpongeForge#936]
When using Sponge, bark from the Roots mod doesn't drop when right-clicking a log with the bark knife.

**Steps to reproduce:**

- Place log

- Right click with bark knife

Per click it normally drops one bark.

**Relevant code:**
- https://github.com/RootsTeam/Roots/blob/master/src/main/java/elucent/roots/item/ItemDruidKnife.java#L47
- https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/entity/EntityUtil.java#L909

**Comment by FiveEYZ** [comment]
this was fixed in one of the latest builds
im currently using spongeforge-1.10.2-2092-5.0.0-BETA-1784 and roots-1.10.2-0.203.0 and it works all fine

**Comment by dogboy21** [comment]
I'm currently using Sponge in my dev environment with SpongeForge on 0cdc55d and SpongeCommon on a5e8616. Currently updating to master to see if the problem is solved

**Comment by dogboy21** [comment]
Okay, problem is solved on master. Thank you!
