### ISSUE TITLE
Sponge gets into problems with ender eye.

### ISSUE THREAD

**Issue by Raycoms** [SpongePowered/SpongeForge#937]
When I use the enderEye on our server it writes

6:44:50 PM CONSOLE: thread/FATAL]: Error executing task

We generated the strongholds before adding sponge so we're pretty sure they are there.
We removed sponge and throwing the ender pearls worked after adding again the pearl won't fly.

**Comment by Aaron1011** [comment]
@Raycoms: Can you pastebin the full error message that you get?

**Comment by Raycoms** [comment]
That's unfortunately the full error message.

**Comment by Aaron1011** [comment]
@Raycoms: I'm pretty sure that there should be more to it. Can you pastebin your full `latest.log` and `fml-server-latest.log`?

**Comment by Raycoms** [comment]
http://pastebin.com/7Nc5DNMK

Seems to be a problem with RTG even after we deactivated that RTG generates these structures.

**Comment by Raycoms** [comment]
I also noticed that using sponge and RTG structures won't be generated at all, even if we deactivate the participation in structures in the RTG config.

**Comment by Aaron1011** [comment]
@Raycoms: I'm unable to reproduce this with a freshly created world with RTG and Sponge. What kind of world were you trying this on?

**Comment by Raycoms** [comment]
WorldType is realistic and we're using it in SMP.

**Comment by Aaron1011** [comment]
Does this happen when you generate a fresh world with Sponge and RTG?

**Comment by lilmoefow** [comment]
Also Having this issue on my Server.  I am not using RTG

FML Latest: https://gist.github.com/lilmoefow/8032533c48462c4b6e9be32e713324c2

Latest Log: https://gist.github.com/lilmoefow/65d9c575b7e2c1033c3613bd17034ab9

spongeforge-1.10.2-2098-5.1.0-BETA-1814.jar
forge-1.10.2-12.18.2.2098-universal.jar

**Comment by ryantheleach** [comment]
Unable to reproduce without any mods other then Sponge.

Unknown if world was generated with SF or SV however.

Tested on 

```
SpongeVanilla
    Minecraft: 1.10.2
    SpongeAPI: 5.1.0-SNAPSHOT-385344f
    SpongeVanilla: 1.10.2-5.1.0-BETA-355
```

```
 SpongeForge
    Minecraft: 1.10.2
    SpongeAPI: 5.1.0-SNAPSHOT-385344f
    SpongeForge: 1.10.2-2098-5.1.0-BETA-1814
    Minecraft Forge: 12.18.2.2116
```

**Comment by ghost** [comment]
I too am have the same issue my logs - http://pastebin.com/rbhd9Vwr - http://pastebin.com/EQdBhRbk
I am using BIOMESOP - and a custom seed. My pack is FTB Infinity Lite 1.3.3 
SpongeForge
Minecraft: 1.10.2
SpongeAPI: 5.1.0-SNAPSHOT-682caf3
SpongeForge: 1.10.2-2171-5.1.0-BETA-1973
Minecraft Forge: 12.18.2.2166

Plugins installed
CommandScheduler-2.3.jar
griefprevention-1.10.2-2.2.0.185.jar
Nucleus-0.15.0-S5-1.10.2-plugin.jar
PermissionManager-2.5.2-API.5.X-6.X.jar
worldedit-sponge-mc1.10.2-6.1.5-SNAPSHOT-dist.jar

**Comment by ghost** [comment]
also updated the MC forge version to 2171 and took out all plugins and I am still aable to reproduce the errors

**Comment by ghost** [comment]
any update on this?

**Comment by MastaC729** [comment]
I can confirm this on Forge 2202 and Sponge 2022.

**Comment by MastaC729** [comment]
http://pastebin.com/UFPq8LLy

I can confirm the issue still exists as of Forge 2234 and Sponge 2177.

**Comment by mrapplexz** [comment]
Sill exists in Sponge 2221

**Comment by Yorkforce** [comment]
Confirming issue still exists on `spongeforge-1.10.2-2221-5.2.0-BETA-2215` with BIomesOPlenty world
http://pastebin.com/vzwpZZeW

**Comment by LemADEC** [comment]
Issue still exists with RTG-1.10.2-4.1.2.4.jar and spongeforge-1.10.2-2254-5.2.0-BETA-2264.jar
https://pastebin.com/RsDHutRh

```
Exception during phase body
java.lang.NullPointerException: null
net.minecraft.world.gen.structure.MapGenStructure.func_143027_a(MapGenStructure.java:224)
rtg.world.gen.structure.MapGenStrongholdRTG.generatePositions(MapGenStrongholdRTG.java:138)
```

What do we miss to move forward on this issue?
Is there any known workaround?

**Comment by ryantheleach** [comment]
If people are able to reproduce this issue, please post the seeds involved, Thanks.

**Comment by Sunconure11** [comment]
4112307981209916893

This is the seed used by my map.

**Comment by ryantheleach** [comment]
@Sunconure11 Using ender eyes / ender compass, what happens? do the eyes lead in one constant direction? create an error? or take you to a location that doesn't contain a stronghold?

**Comment by ryantheleach** [comment]
Using seed -6374430409410178659 in my single player dev environment, on Sponge Forge https://github.com/SpongePowered/SpongeForge/commit/726992c2595aab5d2fa9d80a5efb4bf52033035b I was able to find a stronghold portal at -2206 34 340.

Will now test with Sunconure11's seed, without other mods, then with mods.

If you could test with my seed, and see if you can find the stronghold, or experiment with the results of '/locate Stronghold' that might help as well.

**Comment by Sunconure11** [comment]
Ender eyes simply do not launch in the first place, as if I was on a flat map, effectively.

I'll test that command, though.

**Comment by ryantheleach** [comment]
Testing with your seed, without other mods, using my version resulted in a stronghold at /tp -1976 41 -315

**Comment by ryantheleach** [comment]
@Sunconure11 I'm currently on the SpongePowered Discord, if you want to walk me through installing your mods.
https://discord.gg/rshrjA

**Comment by Sunconure11** [comment]
Unfortunately, I'm still on 1.10.2, and thus, cannot use that command. If there is an equivalent that I can use, whether added by a mod, or otherwise, let me know.

**Comment by tgstyle** [comment]
I can confirm in 1.12 sponge 2486. It work's fine on a fresh server, shutting down the server and starting back up causes the error.

https://gist.github.com/tgstyle/123c62e40ea0cce25729ae2a812b7697

**Comment by tgstyle** [comment]
Result of running /locate stronghold.

https://gist.github.com/tgstyle/b8fa78aed5be4c965fc750790e74f09a

**Comment by ryantheleach** [comment]
@tgstyle thanks for the reproduction steps, it's appreciated, this would explain why I wasn't able to replicate.

**Comment by bloodmc** [comment]
@tgstyle I cannot reproduce this on latest 1.12 using BOP and command. Please test on latest SF and if reproduced, provide your test world zipped with steps.

**Comment by tgstyle** [comment]
Here is a server in it's broken state with the mods. If you launch and run "locate stronghold" you will see it gives the error. To reproduce, delete the region files for the overworld and start the server. It will now work. Stop the server then start again and it will be broken.

https://www.dropbox.com/s/00w7nxfes6hifer/Server.7z?dl=1

Running latest SF

**Comment by bloodmc** [comment]
@tgstyle reproduce issue with as few mods as possible. Makes it easier for us to debug this in dev.

**Comment by tgstyle** [comment]
@bloodmc easy, take the same server delete the DIM folders (they will be broken from removing mods) I kept these three. Same steps to reproduce.

BOP
sponge
worldedit

**Comment by tgstyle** [comment]
@bloodmc I updated the zip, I was even able to reproduce just using BOP and SF. Out of curiosity on your tests did you ever set level-type=BIOMESOP ?

**Comment by bloodmc** [comment]
@tgstyle Tested it again, no errors. This must be an issue on release jar as I cannot reproduce it in dev at all.

And yes, level-type is always set to BIOMESOP

**Comment by tgstyle** [comment]
@bloodmc I was able to reproduce on this zipped server with level-type default.

**Comment by Sunconure11** [comment]
Still occurs on 1.11.2, as well. Both the Ender Compass mod and Ender Eyes get into this issue.

**Comment by Sunconure11** [comment]
I have an associated log, too.

https://pastebin.com/442iArzF

**Comment by Sunconure11** [comment]
https://pastebin.com/8Y45Z9yS

Found this with the stronghold, as well.

**Comment by LuxusDarkangel** [comment]
This is still happening in 1.12.1 with Biomes O' Plenty, and probably with other mods with custom world generation, so let's try and throw some light.

@bloodmc Let's see if this helps you to reproduce it:
Mods used in this test:
- SpongeForge 2624 (Latest)
- Biomes O' Plenty 7.0.0.2291 (Latest, from Maven repository)
- Forge 14.22.1.2479 (Latest)

Steps to reproduce the bug:
1.- Install the above mods in a fresh Forge server.
2.- Change level type to "level-type=BIOMESOP" (This is probably not needed, but just to make sure as I did it this way)
3.- Start the sever to generate a new world. Ender Eyes, the /locate stronghold and derivates suffering this issue **WILL WORK** fine, we still have one more step.
4.- Restart the server, using the **same world** you created in step 3. If you delete the world and create a fresh one you won't be able to reproduce the issue.
5.- Try to use an Ender Eye or the /locate stronghold command. You will get an error in the console (I can't paste this error because it's shown in the console but not reflected in the logs. I have no clue why this happens)

The test server I made:
https://mega.nz/#!ldF1VYzY!D2Q-MdL3HkKJAQkr7f8v4K1MmBxsRAH3pEE_T3HJnkU

**Note:** The world inside this rar is **already broken**, if you want to try it in a new world (Or in your dev environment) you have to follow the steps described above.

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/SpongePowered/SpongeCommon/commit/bacfb232c62a173fb2718e12964a4e986d77e968

**Comment by ryantheleach** [comment]
@bloodmc Woo! Under what conditions was it null?

**Comment by kashike** [comment]
This is a vanilla bug.
It's worth noting that we had to patch this in Paper, too: https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0197-Assign-the-World-in-WorldGenStronghold.patch
