### ISSUE TITLE
SpongeForge 1.10.2-2092-5.0.0-BETA-1785 ignores NetherPortalFix Mod

### ISSUE THREAD

**Issue by SmallSansSerif** [SpongePowered/SpongeForge#942]
I can't this mod to function while running latest (1.10.2-2092-5.0.0-BETA-1785) SpongeForge for 1.10.2. Works fine using Forge 2092

https://minecraft.curseforge.com/projects/netherportalfix?gameCategorySlug=mc-mods&projectID=241160

**Comment by ryantheleach** [comment]
For reference for anyone investigating:

Replaces vanilla teleporters on world load, for overworld and nether, based on hard coded dimension id's.

https://github.com/blay09/NetherPortalFix/blob/1.10/src/main/java/net/blay09/mods/netherportalfix/NetherPortalFix.java#L23

Possibly buggy for Sponge generated dimensions. 

New teleporter sets new NBT data on the player tracking which portal they came from.

https://github.com/blay09/NetherPortalFix/blob/1.10/src/main/java/net/blay09/mods/netherportalfix/BetterTeleporter.java

**Comment by ghost** [comment]
NetherPortalFix does not work with SpongeForge.

**Comment by ktole1999** [comment]
confirmed. pathing is back to original crap but no errors in log. it just doesnt work. bummer because this was an awesome mod.

**Comment by BlayTheNinth** [comment]
The latest NetherPortalFix versions for 1.11.2 and 1.12 should work fine with Sponge now.

**Comment by kashike** [comment]
Thanks, @blay09!
