### ISSUE TITLE
Soul Shard Dupe

### ISSUE THREAD

**Issue by dogboy21** [SpongePowered/SpongeForge#943]
When a Soul Shard from [Soul Shards: The Old Ways](https://minecraft.curseforge.com/projects/soul-shards-the-old-ways) is inserted into a Soul Cage, the shard remains in the player's inventory instead of being used.

SpongeForge 1.10.2-2092-5.0.0-BETA-1784
Forge 12.18.1.2092
Soul Shards 1.10.2-2.6.3-43

**Steps to reproduce:**

- Place down soul cage

- Insert soul shard which is bound to a mob into the cage

**Comment by Aaron1011** [comment]
This is an issue with Soul Shards: https://github.com/TehNut/Soul-Shards-The-Old-Ways/issues/33

**Comment by Aaron1011** [comment]
Update: This has been fixed in the mod itself.

**Comment by TehNut** [comment]
Just going to say: This was 100% not my issue. The next time you ***break*** something, fix it yourself instead of shoving it on the mod developers.
