### ISSUE TITLE
[1.8.9] World names + copying woes.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeForge#944]
I'm sorry for the bad issue report in advanced, I'm repeating it second hand from a server operator I'm working with.

They had been running a test server using SpongeForge 1.8.9 and using the default world name of "world"

They later received a map from a builder named "worldo"

They copied worldo over, and renamed it to world to fit with their naming.

Something in the world remembered that it was named worldo originally.

GreifPrevention created a GriefPreventionData folder inside a new folder called worldo, going to the nether froze the client, and the server created a dim-1 inside worldo.

They do not believe that the builder was running Sponge, possibly Spigot.

Maybe a bad import? Maybe a natural Sponge bug?

**Comment by Zidane** [comment]
@ryantheleach 

It is cause renaming the folder isn't enough. level.dat has the field for the worldname as well. I'll separate these concepts in bleeding but would be a break in 1.8.9.

**Comment by ryantheleach** [comment]
I worked around it with an NBT editor.
