### ISSUE TITLE
[1.10.2] Unusable Command Blocks

### ISSUE THREAD

**Issue by Rasgnarok** [SpongePowered/SpongeForge#945]
So, referring to the Forums post: https://forums.spongepowered.org/t/opening-command-blocks/14211/12 ; I still cannot open command blocks on the newest spongeforge versions (using 1772). I was able to before, and nothing in my PEX config has changed.

Is there a node that was introduced? Because as of early August, all command blocks were unable to open, but they are running and working.

**Comment by Aaron1011** [comment]
Possibly related to https://github.com/SpongePowered/SpongeCommon/issues/893.

**Comment by Rasgnarok** [comment]
yes, aware. I wanted to start a new ticket since that one refers to old builds.

**Comment by Rasgnarok** [comment]
Using the latest you provided, I still cannot open them (`sf 1792`).

**Comment by Aaron1011** [comment]
@Rasgnarok: You've given the user the `minecraft.commandblock` permission, right (Sponge adds that).

**Comment by Rasgnarok** [comment]
No... which is why I was referring to "Is there a node that was introduced? " - before the versions released in August, we set the command block permission through the level of permission in PEX. There was no need for nodes.

Thank you, it is now fixed.
