### ISSUE TITLE
[1.10.2/spongeforge] Adding sponge to server dropping tps to unplayable levels

### ISSUE THREAD

**Issue by Bebabo10** [SpongePowered/SpongeForge#948]
With build 5.0.0-BETA-1788
https://gyazo.com/f9497191e70b1528f04ad361fd4a1860
https://timings.aikar.co/v2/?id=3dcf1ba0542c4327b50a63ea3acb143c << running since server start
https://timings.aikar.co/v2/?id=38f24078ac2041b7af0fbaaf9b85f908 << running for a few min 
Still the same issue when adding sponge to a world that has 20 tps the world will start experiencing major lag. 
with tps dropping to 1-.68 tps

Also after disabling sponge the tps resumed to its normal level at 20
https://gyazo.com/a3f73dd8035e40dc9f32c537e03ba70e

**Comment by Bebabo10** [comment]
@Aaron1011 
i can supply anything that is needed including a [world download](https://drive.google.com/open?id=0B7nzOkVIC8ApSXVGWGwxZzNJYUU).[ Pack link ](https://mods.curse.com/modpacks/minecraft/242462-all-the-mods)

**Comment by Rasgnarok** [comment]
https://github.com/SpongePowered/SpongeForge/issues/946

**Comment by Bebabo10** [comment]
lol pastebin crashes when u try to paste in more then a million lines 
so heres a google doc folder with them in it https://drive.google.com/open?id=0B7nzOkVIC8ApZjFYQW9fOGFyN1U

**Comment by Aaron1011** [comment]
@Bebabo10: There's quite a few exceptions in that log. Would you be open separate issues for each (I think many are duplicates).

**Comment by Bebabo10** [comment]
i was only posting the logs because @Rasgnarok asked

**Comment by Bebabo10** [comment]
greped sponge in ./logs http://pastebin.com/Ch8XbWAj

**Comment by Rasgnarok** [comment]
Aside from the apparent HikariPool spam (which I know for a fact causes major issues in performance), line 1884 also shows the start of a sponge error.

**Comment by bloodmc** [comment]
@Bebabo10 disable ALL your plugins and retest.

**Comment by Bebabo10** [comment]
still drops down to under 1 tps without plugins.
https://drive.google.com/open?id=0B7nzOkVIC8ApSXVGWGwxZzNJYUU
https://mods.curse.com/modpacks/minecraft/242462-all-the-mods

**Comment by hunter688** [comment]
Try add tickprofiler mod, then do _/profile e_ and you can see which chunks cost cpu power.

**Comment by Bebabo10** [comment]
@hunter688 Tick profiler has not been working for us for quite some time all it shows is blank spots where info used to be. I I'll be happy to try it again if u know of a working copy for 1.10.2

**Comment by hunter688** [comment]
https://jenkins.nallar.me/job/TickProfiler/job/1.10.2/

**Comment by Bebabo10** [comment]
@hunter688 
https://gyazo.com/b4a559390357ae4a79e4514ad094c679 << before sponge with 12 players online
https://gyazo.com/04a6ec354cf4ff77e2f82deb60a8fd6d << with sponge no players online 
https://gyazo.com/61bd4aac1b886d6b5262d9422ee6bd6a << sponge with 9 players
https://timings.aikar.co/v2/?id=c2e823600f054e7d8ad050a1ab9ea396 << timmings since start
https://gyazo.com/603006843e1c9ec515e7bc53b65cf511 << warmroast with sponge
tick profiler will not output or even run  for some reason.

**Comment by hunter688** [comment]
Profiler is for finding problematic chunks/entities - reason of low tps, screesnshots with tps rate is unvaluable information.

Show **full output** of _/profile e_ command.

**Comment by Bebabo10** [comment]
Warmroast without sponge https://gyazo.com/5c49943abe20eaa581eb30df8db9cfbc
warmroast with sponge https://gyazo.com/603006843e1c9ec515e7bc53b65cf511

**Comment by Aaron1011** [comment]
@Bebabo10: Could you expand the warmroast with Sponge all the way past `NetworkedInventory#insertItem` (e.g. click '+' until you reach the bottom).

**Comment by Aaron1011** [comment]
@Bebabo10: Can you try to build a similar item conduit network on a fresh world, with only EnderIO? That world and pack are way to large to reasonable debug.

**Comment by Bebabo10** [comment]
warm roast with latest build fully expanded >> https://drive.google.com/file/d/1kESg1Mc361CWOnJvRdqTKhwEC33UGmSC0n2tRZbIHgJPHtLqYI_beHriiGBKWp82f72FeVL18tcTRj--/view?usp=sharing

**Comment by bloodmc** [comment]
@Bebabo10 Looking at the timings, the main culprit seems to be ComputerCraft

[-]Minecraft::tickTileEntity - blockConduitBundleTileEntitycount(22060) total(56.58% 7.666s, 528.68% of tick)  avg(0.35ms per - 264.34ms/760.69 per tick)

Try removing CC and see if that solves your issue.

**Comment by Bebabo10** [comment]
There is no computer craft on the server.

**Comment by bloodmc** [comment]
Ah yes, that is actually EnderIO's BlockConduitBundle. See if you can reproduce this issue just using EnderIO and a few other mods on a fresh server. The less mods the better.

**Comment by Bebabo10** [comment]
Tomorrow I'll test on hermit pack instead of allthemods hermit has about 40 less mods, was just waiting to test to let people build up a bit

**Comment by LemADEC** [comment]
Similar issue has been posted on EnderIO here: https://github.com/SleepyTrousers/EnderIO/issues/3769

**Comment by bloodmc** [comment]
@LemADEC You able to provide me with a test world with as FEW mods as possible to reproduce the slow down with enderio? If so, please provide link and i'll test it on my end.

**Comment by LemADEC** [comment]
From what we suspect so far, it's related to a base mixing EnderIO + Refined Storage + Mekanism + QuantumStorage + EnvironmentalTech + ExtraUtils + Tinker's + IronChest + Storage Drawers and 2 chunkloaders.
Map is 1.5GB compressed with 94 mods (HermitPack on Curse), available here http://mc.funsquaregames.com/download/Harry-20161013.zip without the chunkloaders at -88 91 472 and -99 89 739.

We'll work on trim that setup tonight.

**Comment by LemADEC** [comment]
In SinglePlayer, with just Sponge and EnderIO, setting next to a simple setup for 4+ hours, lag isn't reproduced. If I go back and forth into the nether, lag seems to build up (very) slowly.

On the main server, since the base at -88 91 742 is no longer used, we've observed an heavy lag coming from Mekanism, similar to the original EnderIO one:
![image](https://cloud.githubusercontent.com/assets/4776032/19379385/fd1fe5fa-91f1-11e6-91c7-80078979201c.png)

**Comment by LemADEC** [comment]
I'm observing some lag in Sponge cause tracker every now and then:
![image](https://cloud.githubusercontent.com/assets/4776032/19404305/4cb6ab6e-926d-11e6-9420-10d0652cbcd2.png)
same a bit later
![image](https://cloud.githubusercontent.com/assets/4776032/19404394/f5d20c3e-926d-11e6-800e-caef728bb1a9.png)

**Comment by LemADEC** [comment]
Here's another lag pattern seen a few times:
![image](https://cloud.githubusercontent.com/assets/4776032/19405520/9765c928-9278-11e6-9ad3-5bda634edba8.png)
I see at least 2 issues here:
1- a block event is fired in an unloaded chunk (memory leak?)
2- RefinedStorage is scanning all recipes on chunk loading through onCraftMatrixChanged

**Comment by ghost** [comment]
I have similar issue with enderIO conduits. Trying now world.chunk-gc-tick-interval=0 as workaround mentioned here: https://github.com/SpongePowered/SpongeForge/issues/905#issuecomment-251570906

**Comment by LemADEC** [comment]
Disabling the chunk gc helped, but the lag spikes remains when going into the faulty base.
So the server no longer reachs the 180 s timeout, but it still lags for up to 10 s every now and then.

**Comment by bloodmc** [comment]
@LemADEC I tested your Harry map with latest SF/GP/PEX and cannot reproduce your issue with lag. I tested at location -88 91 742. Test on your end and reproduce the issue then list steps.

**Comment by bloodmc** [comment]
@Bebabo10 confirmed allthemods has severe tps issues. I'll see if I can find what's causing it in Sponge.

**Comment by bloodmc** [comment]
@LemADEC It took a bit but the lag finally started to happen. I'm looking into it.

**Comment by bloodmc** [comment]
@Bebabo10 @LemADEC as others have mentioned, as a temporary workaround set your chunk-gc-tick-interval to 0 in global.conf then run the command "sponge reload -g" to reload the config. This should fix the lag issues until I figure out what is causing it.

**Comment by bloodmc** [comment]
@Bebabo10 @LemADEC @hunter688 Please test the following build

https://www.dropbox.com/s/ra3hrlz5uw7xbhf/spongeforge-1.10.2-2098-bleeding-BETA-TEST1.jar?dl=0

It should solve the issue you all are experiencing. Make sure to set "chunk-gc-tick-interval" back to 1.
Also, please test to make sure chunks are unloading properly. If it works, I'll push to bleeding.

**Comment by Vauxite** [comment]
I'm trying this version now. I'm the one who reported the issue over at EnderIO.

**Comment by ghost** [comment]
Testing too about half hour, looks fine for now, soon I will report how performance changed after long time.

**Comment by LemADEC** [comment]
We've tried it for 30 mn or so and lag is back without having to load the faulty base:
![image](https://cloud.githubusercontent.com/assets/4776032/19456393/835a0e58-94c1-11e6-8fab-da67e28d913a.png)
![image](https://cloud.githubusercontent.com/assets/4776032/19456420/a7d43312-94c1-11e6-97db-a881d0cfb854.png)

Something seems to constantly unload/reload the chunks.
I'm rebooting now and disabling chunk gc again.

**Comment by NyleGarcia** [comment]
@bloodmc It's looking good atm but its only been up for about 25 min with 13 players online with a solid 20tps and plugins.

will keep testing for now

**Comment by bloodmc** [comment]
@hunter688 @Bebabo10 Did lag return?

**Comment by NyleGarcia** [comment]
https://timings.aikar.co/v2/?id=26ea12ecfe8b440c9e15562b4ed4fac4 << hermit

https://timings.aikar.co/v2/?id=b5f7ee9302444d2eb88ceb8bd98ecc4d << allthemods

**Comment by NyleGarcia** [comment]
looking good @bloodmc thank you it also fixed issue #950

**Comment by bloodmc** [comment]
@Bebabo10 OK there still seems to be a problem with hermit modpack. I'll have LemADEC create another ticket for it. I'll push the changes for this ticket shortly.
@LemADEC can you open a separate ticket for hermit? The original issue in this ticket has been resolved and I would like to keep these issues separate.

**Comment by Bebabo10** [comment]
@bloodmc thats strange its been reporting 20tps in console for /forge tps /sponge tps and /gc

**Comment by bloodmc** [comment]
@Bebabo10 oh great! I'll try to figure out what issue LemADEC is experiencing then in a separate ticket. Thanks for the update.

**Comment by NyleGarcia** [comment]
nvm all the mods is lagging but no block lag let me know if i can do anything to help you investigate on hermitpack @bloodmc

**Comment by ghost** [comment]
Lag not returned. Thanks for fixing the issue!

**Comment by Vauxite** [comment]
No lag for me, has been running for over 4 hours. Just an overpopulation of skeleton horses to deal with.
