### ISSUE TITLE
[1.10.2] Pixelmon and Mob Malfunction #2

### ISSUE THREAD

**Issue by Dysthymic** [SpongePowered/SpongeForge#949]
Continued from a previous report https://github.com/SpongePowered/SpongeForge/issues/901

This issue is very similar if not exactly the same issue as before. 

Sponge: We first experienced this 2 days ago on 1776. It happened approximately 4 times on that build since. We've recently updated to the latest Sponge to debug and see if the issue still occurs. We are now **currently running 1787** (this issue also happens on 1787). The issue was supposed to be fixed on 1776, which it was for a few days, and now it's happening more and more frequently.
Forge: 2095

**What we've experienced when effected**
All players are effected once this occurs. No players can send out or retrieve currently active Pokemon they have out. When they throw their Pokemon out by pushing the normal "R" key, a PokeBall is displayed being thrown, yet no Pokemon appears, followed by a "You've sent out xxx!" message.

**The cause**
I could not quite tell what the exact cause is. I would believe it is chunk unloading entities. However I could not be certain nor do I have a way to track this down. When this occurs, we have approximately 50 to 100 players online- then suddenly ALL players are unable to send/retrieve Pokemon. Due to the large number of players we can not necessarily track down which one caused the issue.

Prior to updating we were on 1692, where this issue only effected ONE player and not ALL. It appears all builds of 1693 and above make this issue more severe by effecting ALL players at once.

Quote from @Rasgnarok 's diagnostics which we are experiencing the exact same issue on builds 1776 and 1787.
> What I know:
1. Only happens past builds 1692 of Spongeforge on the 1.10.2 branch.
2. Servers with these builds can run for hours without the bug occurring - I ran 1713 for 8 hours straight with no issues, until it did finally happen. The next time I restarted, it only took 5 minutes to get the issue. The next time, an hour and some passed before it happened again.
3. Bug happens in normally the same way: the player hits R and the chat message saying 'You've sent out X!' fires off; though you cannot see said pokémon. Subsequent attempts at throwing the same pokémon out will similarly fail, but the chat message does not appear ever again. Nonetheless, all pokémon can be 'sent out' once, meaning you can reproduce this behaviour with all pokémon in your party once the bug occurs. This would apply to all players online, and any other that join/leave and restart client.
4. Only a server restart can restore the game mechanic; for this very reason, most Pixelmon servers wanting performant 1.10.2 builds have to have restarts every hour.
5. There is no common denominator in console logs as to what exactly causes it; regardless of the sf version used or the plugin list.
6. As reported to @bloodmc ; I have tried setting verbose=true and seeing if anything appears in console, but nothing does happen - you can check for yourself here, where the bug was reported to me at around [21:41:59].
6. Bug can be 'reproduced' with consistency on anything having sf 1693 and up, with Pixelmon BETA7.
7. So far, 3 other server managers have reported the same issue, proving the consistency across versions; and that it is not a particularity with the setup I run.
8. Around the same time the pokémon started to malfunction (along SF versions), the mobs and other vanilla creatures also started to - issues even manifesting in the same manner. Indeed, I have found that past 1692, you can hit once mobs, and they will receive damage - but all subsequent attempts won't actually hit the mob, who seems to be stuck in place.
9. Bugs can be reproduced with Forge versions 2073 to 2076.
10. This is not a Pixelmon bug. Servers running Forge2076 with BETA7 without any spongeforge are not getting nothing of this issue.

Now, what's interesting is once we put 1776 on our server initially it worked like magic. The issue was gone completely for approximately 4-6 days. Then suddenly, the issue comes back. We have changed nothing in our configs since then as we've been reworking our entire backend on a separate server the last few days. It just suddenly happened and ever since it has started to become more and more frequent just as the builds prior to 1776's apparent fix.

What's different with us is we have hourly restarts to fix up overwhelming amounts of lag due to our larger player count. The issue used to happen every few hours minimum but it's effecting us within an hour time frame with our hourly restarts.

**Comment by Rasgnarok** [comment]
I had previously reported it fixed for 1772, but it seems that it's only become rarer. Note, that this kind of exponential appearance could also be seen on 1692 and up - issue happens once, ok. Second, third, fourth, fifth will happen more often.

**Comment by Aaron1011** [comment]
> When they throw their Pokemon out by pushing the normal "R" key, a PokeBall is displayed being thrown, yet no Pokemon appears, followed by a "You've sent out xxx!" message.

Wait - the chat message always appears? That's different from what @Rasgnarok was reporting, where no message would display at all after the first time.

**Comment by Dysthymic** [comment]
I'm getting a couple mixed stories. It's been happening a lot overnight when I'm not available. 

After reviewing with my team it seems they can not recall seeing the "You've sent out xxx!" message. Therefore only displaying the Pokeball and nothing else.

This happened last night and also it's been reported to me that when a player relogs- it fixes the whole issue for them. I'm going to have to wait until the next time this happens to confirm this 100% as this would be an entire new issue and less severe if that is the case. 

One of my administrators experienced the issue around 7:20AM this morning and it was a bit different than any prior. Players were not only unable to send out Pokemon, but they also could not break any blocks until a restart was taken place. That was very severe so they did not do much testing and resorted to a quick restart as we had a decent amount of players online. This is a completely new report and concerned me so I went to the logs to check for any errors although there was no log generated for approximately 3 hours in that time window which was extremely weird. 

One message we have that spams console constantly is related to entity tracking so this may be an eventual cause for the send out issue- maybe check into that as well: http://pastebin.com/iLhFyy4B

**Comment by Aaron1011** [comment]
@Dysthymic: That error looks very relevant. I'm going to push up a new build that will add more information to that error message.

**Comment by Aaron1011** [comment]
@Dysthymic: The next build of SpongeForge will print include the actual entity in that erorr message, which should help us to determine what's going on.

**Comment by Dysthymic** [comment]
http://pastebin.com/wC6StDBS

**Comment by Aaron1011** [comment]
@Dysthymic: Try [build 1791](http://files.minecraftforge.net/maven/org/spongepowered/spongeforge/1.10.2-2098-5.0.0-BETA-1791/spongeforge-1.10.2-2098-5.0.0-BETA-1791.jar).

**Comment by Dysthymic** [comment]
Here is a log of the last 10 minutes on 1791
http://pastebin.com/vzR0ps3s

**Comment by Aaron1011** [comment]
@Dysthymic: Thanks - that's very helpful. I'm looking into the cause of it.

**Comment by Aaron1011** [comment]
@Dysthymic: Would you be able to come on #spongedev on EsperNet?

**Comment by Rasgnarok** [comment]
@Aaron1011 @Dysthymic I have seen the error before, as I detailed in other posts. I happens pretty often, but it is not a precursor to the bug itself.

**Comment by Aaron1011** [comment]
@Rasgnarok: I suspect that they may be connected, even if the issue takes a while to manifest after seeing that error.

**Comment by Rasgnarok** [comment]
That'd be great if it is - let me know if you need anything on my end as well, able to run latest builds as well.

**Comment by Aaron1011** [comment]
@Dysthymic: Can you try this build, and report your new stacktraces: http://files.minecraftforge.net/maven/org/spongepowered/spongeforge/1.10.2-2098-5.0.0-BETA-1792/spongeforge-1.10.2-2098-5.0.0-BETA-1792.jar

**Comment by Dysthymic** [comment]
http://pastebin.com/hhPawrCL
On build 1792

**Comment by Rasgnarok** [comment]
Posted same thing on the Discord where we talked last, Aaron.
`[5:14 PM] RasBot: @Aaron1011  There's the error`
`[5:14 PM] RasBot: http://pastebin.com/cCfeVc5d  `

**Comment by Dysthymic** [comment]
Still occurs on latest snapshot- Different issue now
It tells the player "You have sent out xxx" No pokeball appears though

**Comment by bloodmc** [comment]
@Dysthymic Re-test with latest build as it should fix this issue.

**Comment by bloodmc** [comment]
OK, assuming this issue is resolved. Re-open if it persists.

**Comment by ghost** [comment]
I believe it persists.
