### ISSUE TITLE
[1.10.2] with sponge stop command 1min vs 3 sec

### ISSUE THREAD

**Issue by Bebabo10** [SpongePowered/SpongeForge#950]
http://pastebin.com/0A6tLbK9 << 1min 5s with sponge 

http://pastebin.com/f4y8iM1A << 3 sec

**Comment by Aaron1011** [comment]
@Bebabo10: By itself, that doesn't tell us much. Can you please post either a timings like or a screenshot of WarmRoast?

**Comment by Bebabo10** [comment]
https://gyazo.com/5cabc7cca3c4978fd8bc2096443fc259 <<warmroast directly after /stop executed

**Comment by Aaron1011** [comment]
@Bebabo10: Could you post another warmroast with all of the nodes fully expanded (especially ItemPattern#create).

**Comment by NyleGarcia** [comment]
fixed in #948
