### ISSUE TITLE
Reconsider how block capturing is done

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/SpongeForge#951]
Recently, I've become aware that several issues, such as [this one with Extrautils2](https://github.com/SpongePowered/SpongeForge/issues/941) and [this one with VeinMiner](https://github.com/SpongePowered/SpongeForge/issues/889), are being directly caused by Sponge's capturing system. While the exact reasons may vary (the former is caused by neighbor notifications not happening when expected, the latter is caused by Sponge firing Forge's `BreakBlockEvent`after the world has changed).

All of these issues are caused by how block capturing fundamentally works - we have to delay processing, so that we can fire a bulk event for plugins. However, the only way to fix this currently is to entirely disable the cause tracker  - which prevents almost all events from being fired..

[@gabiou previously suggested](https://github.com/SpongePowered/SpongeForge/issues/941#issuecomment-251872400) allow server owners to turn off capturing when specific blocks are ticking. I propose that we expand on this, and allow capturing to be disabled entirely for a specific block type. If we wanted, we could provide fine-grained controls, such as being able to individually disable tick capturing or break/place capturing.

This option would work in much the same was as `TrackingPhase#spawnEntityOrCapture` does now - if capturing is disabled, a `ChangeBlockEvent` is immediately fired for that change. If it isn't cancelled, neighbor notifications and other changes happen immediately.

There are two ways we could go about doing this (not mutually exclusive):
- Provide a config file to disable capturing for specific block types. It might make sense to maintain our own list of mods which need bypasses, and include those in the default config.
- Allow mod developer to specify that their mod block needs a bypass. While this wouldn't work for everything (for example, VeinMiner listens to break events for vanilla blocks, like iron ore), it would reduce the need for Sponge to keep up-to-date with changes in mods.Taking inspiration from how Mixin allows mod transformers to bypass the initial transform pass by using `@Resource`, we could re-use an existing annotation, or have mods implement a method in their block class. Neither would require a dependency on Sponge, since the method would be automatically implemented when we mix an interface into `Block`.

Pinging @gabizou, @bloodmc, and @Zidane for feedback.

**Comment by bloodmc** [comment]
I'll just recap what I stated on IRC...

For first issue, provide a config to disable capturing and fire events immediately similar to how we handle entity spawns.

For second issue, Forge fires their break event for players before setting the blockstate. To workaround this, we could fire a Forge BreakEvent when we fire our ChangeBlockEvent.Pre event for player breaks. We would also have to make sure to not fire a Forge BreakEvent during ChangeBlockEvent.Break for players.

**Comment by bloodmc** [comment]
This shouldn't be an issue with our latest builds.
