### ISSUE TITLE
Player moved wrongly!? [1.10.2][Pixelmon]

### ISSUE THREAD

**Issue by Xwaffle1** [SpongePowered/SpongeForge#952]
I leave this issue that I believe is highly related to
https://forums.spongepowered.org/t/1-10-2-too-quickly-error-performance-issue/14376

Pixelmon has a block(warp plate) that once being placed you can link to teleport a player that stands on it. I've tested it with just Forge and it works fine, but once linked with Sponge it doesn't work and non-opped players can not  use it, it then spams console with "PLAYERNAME moved wrongly" I've set fly to true in server properties to see if that may be a temporary fix yet it doesn't seem to work. This block use to work on Sponge build 1772 and prior to.

**Comment by Rasgnarok** [comment]
It does indeed cause performance issues, and this even happens with `1792 spongeforge`. You do not need to be using any warp plates, simply moving fast enough that it would be kicking you had the `server.properties` not been on 'allow-fly=true'.

**Comment by Zidane** [comment]
Re-test with stable-5 and re-open if it still occurs.
