### ISSUE TITLE
[1.10.2] Strange behavior of right-click interact

### ISSUE THREAD

**Issue by hunter688** [SpongePowered/SpongeForge#956]
I would like using plugin deny use of mining laser from the IC2 mod when is player at Y>40.

I have this code:

http://pastebin.com/33ew8GVY

When laser points to air or water, all works as expected.

When point to block, event looks like isnt cancelled, but red message about Y see in the chat (line 46 in the pastebin).

Is my plugin wrong or in the SF is a bug?

As workaround I added my another forge mod, which cancel event without problem.

**Comment by Zidane** [comment]
So does the laser beam still spawn is what you are saying?

**Comment by Zidane** [comment]
@Aaron1011 

Look into this, should be simple to resolve.

**Comment by hunter688** [comment]
Zidane yes.

**Comment by Aaron1011** [comment]
This issue is due to our filtering of right click air events. Unfortunately, our assumptions about the `EnumActionResult` that mods return was incorrect, as IC2 returns `EnumActionResult.FALSE` from `onItemUseFirst` while still performing logic in `onItemRightClick`

**Comment by liach** [comment]
I'd ping @sfPlayer1 for this.

**Comment by sfPlayer1** [comment]
The reason behind returning FAIL is to prevent the use animation from playing.

**Comment by Aaron1011** [comment]
@sfPlayer1: This isn't a problem with IC2 at all - it's a sponge problem. We'll be working on a fix for this.

**Comment by bloodmc** [comment]
Fixed in

https://github.com/SpongePowered/SpongeForge/commit/97b8c5040edf38a55cf789d402892876b8d43b3d

and

https://github.com/SpongePowered/SpongeCommon/commit/d68412db39cddc6f35b647c3d945184c25af6523
