### ISSUE TITLE
Client Dissconects instantly after connecting

### ISSUE THREAD

**Issue by lilmoefow** [SpongePowered/SpongeForge#958]
Player was trying to collect Demonic Wills from Blood Magic, when he was disconnected from the server.
Now when ever he trys to rejoin it kicks him instantly.  Not sure how but he has managed to get back on.

Here is the error in the FML logs when he tried to connect
https://gist.github.com/lilmoefow/aa2f59ccb79e743e19a306759e648549

forge-1.10.2-12.18.2.2098-universal.jar
spongeforge-1.10.2-2098-5.0.0-BETA-1798.jar

Its referencing so many things, I am not really sure where to report this issue. I have a feeling it might have something to do with Blood Arsenal not being updated to the newest Baubles, but the player was not using any baubles nor did he have any equipped.  

Any help is appreciated, or if you can point me in the right direction of who to report this to that would be good to.

**Comment by kashike** [comment]
>Caused by: java.lang.ClassNotFoundException: baubles.common.lib.PlayerHandler

Is Baubles installed?

**Comment by lilmoefow** [comment]
Yeah, like i said before  " I have a feeling it might have something to do with Blood Arsenal not being updated to the newest Baubles, but the player was not using any baubles nor did he have any equipped." 

If that is 100% the issue, i will just rollback baubles.  But the error is referencing "at biomesoplenty.common.block.BlockBOPPlant.func_180634_a(BlockBOPPlant.java:455) [BlockBOPPlant.class:?]" and i didnt think BOP had baubles support? The whole error is confusing tbh, cause he was not able to log on then all of a sudden it just let him log on.  Still would like to figure out the cause of the issue so i can try to prevent it further on my end.

**Comment by bloodmc** [comment]
The issue is either you are using a different version of baubles that blood arsenal expects or baubles is not installed. This is not a sponge issue.

**Comment by lilmoefow** [comment]
Ok cool.  I thought so, just wanted to just some extra confirmation.  Thanks for humoring me :)
