### ISSUE TITLE
server won't boot with sponge 5.0.0-BETA-1806

### ISSUE THREAD

**Issue by TheMrCaveman** [SpongePowered/SpongeForge#961]
updatde sponge from 5.0.0-BETA-1798 to 5.0.0-BETA-1806

And server won't boot anymore

/********************************************************************************************************/
/* */
/* Oh dear. Something went wrong and the server had to shut down! */
/* */
/*------------------------------------------------------------------------------------------------------*/
/* */
/* A critical error was encountered while blending Sponge with Forge! */
/* */
/* Possible causes are: */
/* */
/* * An incompatible Forge "core mod" is present. Try removing other mods to */
/* see if the problem goes away. */
/* */
/* * You are using the wrong version of Minecraft Forge. You must use the */
/* correct version of Forge when running Sponge, this version is for */
/* 12.18.2.2098 (you are running 12.18.2.2098) */
/* */
/* * An error exists in Sponge itself. Ensure you are running the latest version */
/* of Sponge. */
/* */
/* * Gremlins are invading your computer. Did you feed a Mogwai after midnight? */
/* */
/*------------------------------------------------------------------------------------------------------*/
/* */
/* Technical details: */
/* */
/* Failed on class : net.minecraft.entity.monster.EntityZombie */
/* During phase : DEFAULT */
/* Mixin : entity.living.MixinEntityZombie */
/* Config : mixins.forge.core.json */
/* Error Type : org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException */
/* Caused by : Unknown */
/* Message : @Shadow method getZombieType was not located in the target class */
/* */
/********************************************************************************************************/
Attempting to shut down the VM cleanly

**Comment by ZephireNZ** [comment]
Looking into this now, was my PR that broke it

**Comment by ZephireNZ** [comment]
Fixed in #963
