### ISSUE TITLE
[1.10.2] Right click place block instead open chest gui (GP installed)

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeForge#967]
In the wilderness:

Take wooden planks to hand and click right button to wooden chest. Planks are placed to world as new block next to chest instead only open chest gui.

In the own claim is ok.

**Comment by ghost** [comment]
Placing enderIO facades to conduits have related problem. Facade is placed twice.

**Comment by FiveEYZ** [comment]
can confirm with the Coduit Facades being placed twice.

it happen to a player where he had 1 conduit facade on hotbar and when he placed it 2 appeared placed in world, the one facade he had on hotbar turned in to -1 and the player got kicked with "internal server error"
this happen in the players own GP claim

http://pastebin.com/raw/uw7KknLv

**Comment by ghost** [comment]
pls retest with latest SF

**Comment by bloodmc** [comment]
@hunter688 @FiveEYZ This is not an issue with only Sponge/GP installed. Please determine what mod is causing this issue so I can fix.

**Comment by bloodmc** [comment]
This turned out to be a GP bug.

**Comment by ghost** [comment]
Works now as expected! Many thanks!
