### ISSUE TITLE
Spice of Life causing client crash when eating food after user dies. Repeatable.

### ISSUE THREAD

**Issue by Siigari** [SpongePowered/SpongeForge#969]
Using Spice of Life 1.9.4-1.3.6.jar and AppleCore-mc1.10.2-2.0.1 on 1.10.2.

When I eat food before dying, food is processed normally.

When I eat food after dying, I crash with the following server log:

http://pastebin.com/7nPbwWQF

**Comment by squeek502** [comment]
Relevant issue on the mod's issue tracker: https://github.com/squeek502/SpiceOfLife/issues/99

**Comment by kashike** [comment]
Relevant issue on the AppleCore repository: https://github.com/squeek502/AppleCore/issues/78

**Comment by simon816** [comment]
Pretty sure this is a duplicate of https://github.com/SpongePowered/SpongeForge/issues/916

**Comment by kashike** [comment]
https://github.com/SpongePowered/SpongeForge/issues/916
