### ISSUE TITLE
java.lang.NoClassDefFoundError: net/minecraft/client/gui/FontRenderer

### ISSUE THREAD

**Issue by Siigari** [SpongePowered/SpongeForge#971]
Immersive Engineering

http://pastebin.com/ujvTfWyX

**Comment by kashike** [comment]
This was an issue with Immersive Engineering which was fixed in https://github.com/BluSunrize/ImmersiveEngineering/commit/bbc17a499058534dde361835570ac96c8111b4af, and reported in https://github.com/BluSunrize/ImmersiveEngineering/issues/1614.

**Comment by Siigari** [comment]
Why won't the server launch?

**Comment by kashike** [comment]
Download a newer version of Immersive Engineering.

**Comment by Dockter** [comment]
Is that a font renderer class being attempted to be loaded on the server?  Someone dun screwed up.
