### ISSUE TITLE
[1.10.2] Never have hunger

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeForge#973]
No matter what happen, death, a long sprinting time, regen, I never have hunger. The hunger bar won't never. The difficulty is hard, and started since I updated to SpongeForge build 1817.
Using Forge 1.10.2-12.18.2.2107

**Comment by kashike** [comment]
Do you have any mods installed? Plugins?

**Comment by Eufranio** [comment]
Yes. Mods: http://www.technicpack.net/modpack/magitech-server-beta-pack.883332/mods
Plugins: Nucleus, LuckPerms and GriefPrevention

**Comment by ghost** [comment]
try without mods/plugins...

**Comment by bloodmc** [comment]
@Eufranio test latest SF build.

**Comment by bloodmc** [comment]
This shouldn't be an issue in latest builds.
