### ISSUE TITLE
Botania Mana Pools - HermitPack

### ISSUE THREAD

**Issue by axle2005** [SpongePowered/SpongeForge#974]
We recently updated our SpongeForge version from:
spongeforge-1.10.2-2098-5.0.0-BETA-1788

to:
spongeforge-1.10.2-2098-6.0.0-BETA-1819

I also tried 1818, as we wanted a version after build 1815 for the Chunk support. 

Following this update, dropping any items in a Botania Mana Pool produce the particles, but no item is dropped. Ive confirmed a few times nothing is picking up the items, even went off in the middle of no where and used a Guilty Pool. 

After rolling back the version to 1788, the pools worked again. 

HermitPack 1.0.1

**Comment by ProsperCraft** [comment]
Same problem here on versions

```
SpongeAPI: 6.0.0-SNAPSHOT-cebc736
SpongeForge: 1.10.2-2107-6.0.0-BETA-1830
Minecraft Forge: 12.18.2.2107
```

**Comment by Vauxite** [comment]
Confirmed running:
    Minecraft: 1.10.2
    SpongeAPI: 6.0.0-SNAPSHOT-cebc736
    SpongeForge: 1.10.2-2107-6.0.0-BETA-0
    Minecraft Forge: 12.18.2.2098

**Comment by axle2005** [comment]
It is at minimum any version after 1815 (Just to save some people some time), which means all the 6.0.0 API builds. We current;y are using 1808, which still has Botania working.

**Comment by Aaron1011** [comment]
This should be fixed in build 1831 onwards.

**Comment by ProsperCraft** [comment]
Confirmed fixed, thank you!
