### ISSUE TITLE
Feature request - All plugin configs saved in a /pluginconfigs/ folder.

### ISSUE THREAD

**Issue by ProsperCraft** [SpongePowered/SpongeForge#975]
It would make updating modpacks much easier if all of plugins would save their configs in a pluginconfigs folder so we didn't have to do surgery on the configs folder every single update.  If they were all in one folder like the plugins are all in the /mods/plugins folder we can automate the copying of the folders with a script when we update the server.

**Comment by kashike** [comment]
@Mumfrey https://github.com/SpongePowered/SpongeCommon/issues/427#issuecomment-171442512

https://github.com/SpongePowered/SpongeForge/commit/dc658830635ac4afc5f22ce6e8192911df2bfcf0 added support for adding an additional directory to load plugins from

**Comment by ProsperCraft** [comment]
ok, so I read that very long and upsetting discussion where people who apparently don't run and maintain large server networks were fighting with people that actually do.  I am still confused as to where it all landed.

I don't see any mention of locations for configs/mods in the documentation yet. 
In the thread I saw mention of maven-style formatting, this is programmer speak, I don't comprehend sorry.

The bottom line is this- 
Modpacks don't come with sponge

updating my server right now I am having to pick through mountains of config files every few days due to the rapid development of 1.10.2.

I see that sponge can be placed outside the mods folder with a flag on loading forge, that is fantastic.

The configs are a giant jumble of garbage- this is what I am looking at when updating.
https://gyazo.com/a8ae64841dfd55779edc6e6fc5f5f42b
on one server, and

https://gyazo.com/64d1be36a15cc149e7a0e02deb1bb4ad

On another.

Picking through the files one by one and moving them over to the new folder is not a good use of time, when all of the configs for the plugins which are never provided with the modpack could be outside the configs folder.

Please just listen to the people in the trenches- we want the plugins and configs folders outside the modpack mods and configs folders which would make updating only take a few seconds with a simple script.   Isn't that the ultimate purpose of a coder?  To provide something in a way that users want to use it?

 If this is possible thank you, please describe exactly how do do so, and I will shoot a video tutorial on it and post it so you won't ever have to answer this question again.

**Comment by Deamon5550** [comment]
And its overly combative responses like that that forever drop this issue in priority. 

[quote from SpongeCommon#427](https://github.com/SpongePowered/SpongeCommon/issues/427#issuecomment-171442512)

> I will make the base shared config dir for plugins configurable in the same way as per Zidane's suggestion above.

Simply asking what happened to this feature without flying off the handle and just being plain insulting would have been the correct way to phrase your above response.

(As for moving the plugins themselves if you open your config you will see [a large comment telling you exactly how to change that](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/config/category/GeneralCategory.java#L36) and its [even in our documentation too](https://docs.spongepowered.org/master/en/server/getting-started/configuration/sponge-conf.html))

**Comment by phit** [comment]
The documentation reads like it only applies to mods (referred to as plugins) and not configs?

**Comment by Deamon5550** [comment]
@phit That config is only for the plugins themselves, a new config entry to specify a root for the plugin configs is still required.

**Comment by phit** [comment]
Okay, well that's at least half way there! Ignoring the tone of some people asking for this feature, I think their reasoning still holds some truth. I would love to see a config-dir config implemented in a similar manner at some point.

**Comment by NyleGarcia** [comment]
Basically all we are asking for is the option to have plugins configs go into 
./config/plugins/ and not ./configs
to mirror what they have done with plugins ./mods/plugins

or to have an option like \"${CANONICAL_MODS_DIR}/plugins\"" to redirect the configs of the plugins to where we see fit

**Comment by NyleGarcia** [comment]
or to have it in ./config/sponge/plugins
@kashike

**Comment by kashike** [comment]
Quote from @Mumfrey in https://github.com/SpongePowered/SpongeCommon/issues/427#issuecomment-171442512:

> I will make the base shared config dir for plugins configurable in the same way as per @Zidane's suggestion above.

It will get done in the same fashion as the directory to load plugins from - as a configuration option. It's just a matter of someone either submitting a pull request, or someone on the core development team pushing a change.

**Comment by NyleGarcia** [comment]
@kashike yes we see that that's not the issue the issue is that no one has made that pull request or pushed the change. It has been over 9 months since that conversation happened AND we have not seen what has been promised by @Mumfrey regarding this issue. #https://github.com/SpongePowered/SpongeCommon/issues/427

**Comment by kashike** [comment]
Someone can feel free to submit a pull request Otherwise, wait for someone to push a change for this when someone has time.

**Comment by kashike** [comment]
https://github.com/SpongePowered/SpongeCommon/commit/86f2f3ca6cfa230ebd81c80588d9e56638338773

**Comment by kashike** [comment]
@ProsperCraft :)
