### ISSUE TITLE
Boats moving too quickly

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeForge#976]
When I use a boat, the message spams in the console:
`Boat (vehicle of Foxgameplays) moved too quickly! -6.97142847120449,0.0,7.49881407108262`
No issues without SpongeForge.

Forge 12.18.2.2107
SpongeForge 5.1.0-BETA-1814
Plugins: Nucleus, GriefPrevention and LuckPerms

**Comment by NyleGarcia** [comment]
that happens without sponge too

**Comment by Zidane** [comment]
This happens without Sponge as I've confirmed it.
