### ISSUE TITLE
[1.10.2] Players aren't able to use commands/chat using Forced Hosts

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeForge#977]
I'm using a Sponge server in a Bungee network. When a player join the server trough Forced Hosts, he isn't able to use commands, or chat. Nothing appears in the logs (commands issued, errors, etc).

Using BungeeCord from HexagonMC
Forge 12.18.2.2107
SpongeForge 5.1.0-BETA-1814
Plugins: Nucleus, GriefPrevention and LuckPerms

**Comment by Zidane** [comment]
This needs further testing on your end by testing with just that mod, Forced Hosts, and SpongeForge.

**Comment by NyleGarcia** [comment]
sponge provides full use with waterfall bungee and a few others that i have tested
