### ISSUE TITLE
server crashed while using the cyclic standard exchange cepter

### ISSUE THREAD

**Issue by TheMrCaveman** [SpongePowered/SpongeForge#979]
Sponge version 1.10.2 - 6.0.0-BETA-1826
Forge 1.10.2 - 12.18.2.2107

Server crash report: http://pastebin.com/N2FZ1WiD

**Comment by gabizou** [comment]
My best guess is that a new world was created which didn't exist before, only reason why completing the worlds processing would fail. If you can explain what was going on and how to reproduce, that'd be great.

**Comment by TheMrCaveman** [comment]
With the standard exchange cepter you can exchange blocks that you touch with the cepter with blocks from your own inventory. You can set it to 1 block, 3x3, 5x5, 7x7, or 9x9. It worked with 1 block. So i tried 3x3 exchanged stone with dirt and server crashed.

4 people here on the server tried to reproduce it but failed doing so. But we found this cepter to be very bugy. It works first few times but stops working after a little bit. So this might need a bit further investigation.

**Comment by Zidane** [comment]
Re-test with stable-5 and report back if still an issue and we will re-open.
