### ISSUE TITLE
Performance issues - org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity()

### ISSUE THREAD

**Issue by ProsperCraft** [SpongePowered/SpongeForge#981]
mekanism.common.block.BlockBasic.getActualState

[15:11:31] [pool-3-thread-28/INFO]: There are 19/40 players online.

[15:10:55] [Server thread/INFO]: World [world-hermitpack](DIM0) TPS: 11.934, Mean: 83.796ms
[15:10:55] [Server thread/INFO]: World [DIM-1](DIM-1) TPS: 20.000, Mean: 4.117ms
[15:10:55] [Server thread/INFO]: World [DIM1](DIM1) TPS: 20.000, Mean: 2.115ms
[15:10:55] [Server thread/INFO]: World [gather](DIM2) TPS: 20.000, Mean: 2.628ms
[15:10:55] [Server thread/INFO]: Overall TPS: 10.351, Mean: 96.605ms

![915f8a0be40b1b752125cd51183b9802](https://cloud.githubusercontent.com/assets/4427684/19622704/460bd702-986d-11e6-80e3-e66c6c9291d4.png)

[WarmRoast.zip](https://github.com/SpongePowered/SpongeForge/files/546047/WarmRoast.zip)

6.0.0-BETA-1827

**Comment by ProsperCraft** [comment]
![e3bff4e48fa3cc612b695afe96788ca5](https://cloud.githubusercontent.com/assets/4427684/19622791/f700ad60-986f-11e6-8c3a-2129e5e24685.png)

[WarmRoast.zip](https://github.com/SpongePowered/SpongeForge/files/546058/WarmRoast.zip)

   SpongeAPI: 6.0.0-SNAPSHOT-cebc736
    SpongeForge: 1.10.2-2098-6.0.0-BETA-1823
    Minecraft Forge: 12.18.2.2099

**Comment by ProsperCraft** [comment]
More tracking tileentity, but this time with Forestry.

![a23e71812c3cf0bb8fee217972183bf4](https://cloud.githubusercontent.com/assets/4427684/19623721/eaedd854-9892-11e6-99c4-7fb91fb2102c.png)
[WarmRoast-forestry.zip](https://github.com/SpongePowered/SpongeForge/files/546134/WarmRoast-forestry.zip)
![a23e71812c3cf0bb8fee217972183bf4]

![e3bff4e48fa3cc612b695afe96788ca5](https://cloud.githubusercontent.com/assets/4427684/19623726/1974aac2-9893-11e6-8046-18aaba80252e.png)

```
Minecraft: 1.10.2
SpongeAPI: 6.0.0-SNAPSHOT-cebc736
SpongeForge: 1.10.2-2098-6.0.0-BETA-1823
Minecraft Forge: 12.18.2.2099
```

**Comment by ProsperCraft** [comment]
Fully Updated.

![64582d52eb2cbaa3776f317e8ddab357](https://cloud.githubusercontent.com/assets/4427684/19623805/e89a2f3e-9898-11e6-9257-37831f9af101.png)

[WarmRoast.zip](https://github.com/SpongePowered/SpongeForge/files/546145/WarmRoast.zip)

```
SpongeAPI: 6.0.0-SNAPSHOT-cebc736
SpongeForge: 1.10.2-2107-6.0.0-BETA-1830
Minecraft Forge: 12.18.2.2107
```

![6f762174f32b0fc5ddfe93218eeda24f](https://cloud.githubusercontent.com/assets/4427684/19623811/572d359a-9899-11e6-8214-face6747e872.png)

**Comment by bloodmc** [comment]
@ProsperCraft Please test the following build

https://www.dropbox.com/s/kyoc1ypfkkvrsmy/spongeforge-1.10.2-2107-6.0.0-BETA-test1.jar?dl=0

Set chunk-gc-tick-interval to 1 and set chunk-unload-delay in config to 0.

**Comment by NyleGarcia** [comment]
well that build just broke my base lol https://gyazo.com/f0e2a333f718adcfa8f1204efdc5980d

**Comment by bloodmc** [comment]
@Bebabo10 can you come on IRC to test further?
https://webchat.esper.net/

channel #sponge

**Comment by gabizou** [comment]
The specific fix for this has already been added in a recent commit. The specific issue in this case has been querying for the "virtual" `BlockState` of a `TileEntity`, which some mods end up costing quite a bit of processing for being called so often. Eliminating the method call and using the default block state that is serialized is the solution, which @bloodmc has provided.

The remainder of performance issues can be discussed in separate issues as we find them.
