### ISSUE TITLE
SpongeForge bug

### ISSUE THREAD

**Issue by iKurama** [SpongePowered/SpongeForge#982]
Mods and versions
(Sponge itself is the cause of the dupe, tried without.)
AutoRegLib-1.0-2
Psi-r1.0-41
FTBLib-1.10.2-3.0.0.4
FTBUtilities-1.10.2-3.0.0.3
spongeforge-1.10.2-2098-6.0.0-BETA-1824

https://www.youtube.com/watch?v=QjcXGl8KEEU
(Happened at an unknown sponge version)

So yesterday I tried it again (On hermitpack, which is the new hype apparently), just SpongeForge with HermitPack. I could dupe chests inventories, including inventories saving blocks, on latest SpongeForge.

**Comment by ryantheleach** [comment]
https://github.com/Vazkii/Psi/blob/master/src/main/java/vazkii/psi/common/item/ItemCAD.java#L126

So from what I can gather, when the item is activated, it's launching a ~~projectile~~ EntityThrowable
https://github.com/Vazkii/Psi/blob/master/src/main/java/vazkii/psi/common/entity/EntitySpellProjectile.java#L38 

and when it lands, somewhere in the SpellContext eventually 

https://github.com/Vazkii/Psi/blob/master/src/main/java/vazkii/psi/common/spell/trick/block/PieceTrickBreakBlock.java#L87

**Comment by bloodmc** [comment]
@iKurama update to SF 1830+
