### ISSUE TITLE
Some drops are not dropping

### ISSUE THREAD

**Issue by ProsperCraft** [SpongePowered/SpongeForge#983]
```
SpongeAPI: 6.0.0-SNAPSHOT-cebc736
SpongeForge: 1.10.2-2107-6.0.0-BETA-1830
Minecraft Forge: 12.18.2.2107
```

Players are reporting the followig items are not dropping with sponge enabled.

Actually additions bat wings and solid xp
Enderio broken spawners

**Comment by LemADEC** [comment]
That Sponge version has known inventory issues.

**Comment by bloodmc** [comment]
@LemADEC This is not the build, it's been a known issue for awhile

dupe #857
