### ISSUE TITLE
TP Void Glitch. [1.8.9 Sponge Forge]

### ISSUE THREAD

**Issue by IBGnova** [SpongePowered/SpongeForge#984]
Hello,

I have posted this on the sponge forums but I figured it wouldn't hurt to post it here. Players are getting stuck in the void sometimes when they tp, it is quite random but I am told it is due to the chunks not loading around the player before they tp. We have tested quite a bit with it and it does seem to only happen when a player TPs to somewhere that is not loaded. I have tried everything I can to fix this but I have not had any luck.

Thanks,
Nova

**Comment by IBGnova** [comment]
Is there anyway to get a fix for this, this is causing major problems on my server.

**Comment by bloodmc** [comment]
1.8.9 is no longer supported. Please update to 1.10.2+
