### ISSUE TITLE
Tinkers Tools vanish after retrieving them from the Place item Feature from Draconic. 

### ISSUE THREAD

**Issue by StoneLegion** [SpongePowered/SpongeForge#986]
**Current version is:**
forge-1.10.2-12.18.2.2107-universal.jar
spongeforge-1.10.2-2107-6.0.0-BETA-1835.jar

Without Sponge It Works Fine!

If you use the place item feature:
https://i.imgur.com/HEJTbNb.png

From Draconic and place Tinkers Tool like a Hammer on anything like a wall.

https://i.imgur.com/seUYf1O.png

When you pick it up the item vanishes and does not go in the inventory.

Server console only say the following:
[06:35:49] [Server thread/WARN]: Fetching addPacket for removed entity

**Comment by TheMrCaveman** [comment]
They also disapear if you throw them @ another player!!
