### ISSUE TITLE
Issue regarding Spice of Life and Sponge

### ISSUE THREAD

**Issue by Siigari** [SpongePowered/SpongeForge#987]
http://pastebin.com/W6vM5Q30

This issue occurs after a player dies and then eats with Spice of Life installed. It generates an internal server error.

**Comment by Zidane** [comment]
That trace really doesn't show anything to do with Sponge. Have you tested this without Sponge installed? Need way way more details. Need Forge build numbers/Spice of Life version/Sponge build numbers.

**Comment by simon816** [comment]
Known issue with AppleCore, see https://github.com/SpongePowered/SpongeForge/issues/916

**Comment by gabizou** [comment]
Duplicate of #916.
