### ISSUE TITLE
Redstone Duping Bug.

### ISSUE THREAD

**Issue by StoneLegion** [SpongePowered/SpongeForge#988]
This is a strange one. Throwing Redstone from the inventory dupes it. But I can't seem to find other items that also dupe just Redstone. 

Can't repeat it if I remove Sponge.

spongeforge-1.10.2-2107-6.0.0-BETA-1840.jar
forge-1.10.2-12.18.2.2107-universal.jar

Mod Pack:
https://minecraft.curseforge.com/projects/sandbox-2

Video:
https://www.youtube.com/watch?v=WOccWRMM5r8

**Comment by Aaron1011** [comment]
@KaneHart: Can you try to narrow this down to the mod or mods that this occurs with? In particular, take a look at the mod that's adding the `EMC` tooltip to the redstone.

**Comment by StoneLegion** [comment]
EMC Tooltip would be Project E but it also adds it on many other things and has no dupes to them.

I can try playing around with it later but sadly only happens with sponge and without Sponge no issues.

**Comment by YuRaNnNzZZ** [comment]
I have same issue with BetterWithMods, as the "Hardcore Buoy" feature from it using [custom item entity](https://github.com/BeetoGuy/BetterWithMods/blob/master/src/main/java/betterwithmods/entity/item/EntityItemBuoy.java).

**Comment by StoneLegion** [comment]
I don't use BetterWithMods myself. So it looks like multiple mods might be triggering this.

**Comment by bloodmc** [comment]
@KaneHart Please test latest SpongeForge build and let me know if it still occurs.

**Comment by StoneLegion** [comment]
Still happening with the latest build and even latest forge, latest mods, etc :)

@bloodmc

**Comment by bloodmc** [comment]
@KaneHart Can you try SF 1914?

**Comment by StoneLegion** [comment]
Sorry, TBH we went back to 1.7.10 someone else will have to try LOL.

**Comment by Unnoen** [comment]
Exact same issue happening on spongeforge-1.10.2-2171-5.1.0-BETA-2006

Modpack: https://mods.curse.com/modpacks/minecraft/242462-all-the-mods
