### ISSUE TITLE
Eye of Ender Causes Error executing task and does not execute. 

### ISSUE THREAD

**Issue by StoneLegion** [SpongePowered/SpongeForge#989]
Here is the server log:
http://pastebin.com/JABx02Tt

Works fine without Sponge.

spongeforge-1.10.2-2107-6.0.0-BETA-1840.jar
forge-1.10.2-12.18.2.2107-universal.jar

Mod Pack:
https://minecraft.curseforge.com/projects/sandbox-2

**Comment by ryantheleach** [comment]
Possible duplicate:
https://github.com/SpongePowered/SpongeForge/issues/937
