### ISSUE TITLE
Droping items from any side of inventory causes them to not be droped but be voided

### ISSUE THREAD

**Issue by NyleGarcia** [SpongePowered/SpongeForge#991]

**Comment by thyraxx** [comment]
I had the same issue, after testing I came to the conclusion it's SpongeForge, by using 1.10.2 - 6.0.0-BETA-**1840** it's solved, but if you update to 1.10.2 - 6.0.0-BETA-1843 (newest version right now) the bug is back again. So i'll be using SpongeForge 1.10.2 - 6.0.0-BETA-1840 for a while.

**Comment by NyleGarcia** [comment]
#https://github.com/SpongePowered/SpongeForge/commit/a9936719c1886dd3fb0435e89e90cb2af012296d

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/SpongePowered/SpongeCommon/commit/ea3a08e3611c83877616b6186249a3750c087f14
