### ISSUE TITLE
Villagers possibly causing a crash

### ISSUE THREAD

**Issue by Symsyr** [SpongePowered/SpongeForge#993]
https://gist.github.com/Symsyr/7074efa26c1af516d54acce81a9541fa

**Comment by gabizou** [comment]
Can you link the modpack?

**Comment by Symsyr** [comment]
It is in HermitPack.  We had an issue with Forestry and had to remove it, which should have removed the villagers as well but Sponge is still recognizing them.

**Comment by Symsyr** [comment]
HermitPack 1.1.0, stable release and not Beta

**Comment by gabizou** [comment]
Wait, so Forestry added the villagers and now they're not available so it's crashing?

**Comment by Symsyr** [comment]
Yes, but it is only crashing when sponge is running, which is the odd part.  I have been running the server without sponge for the last 5 hours with no crashes.

**Comment by Symsyr** [comment]
I deleted my sponge level.dat just now and went to a village that was known to crash it, it is still standing.  Doing some more testing now

**Comment by Symsyr** [comment]
Okay, still seems to happen but when I run without Sponge, everything is fine

**Comment by curscascis** [comment]
Getting a  similar issue
https://github.com/SpongePowered/SpongeForge/issues/1104

**Comment by gabizou** [comment]
Closing in favor of #1190's resolution. Will be implementing something more descriptive and productive in terms of a warning/error.
