### ISSUE TITLE
Unable to load single player with spongeforge.

### ISSUE THREAD

**Issue by ProsperCraft** [SpongePowered/SpongeForge#996]
https://paste.ee/p/wwcY6

Steps to reproduce- make a modpack with the three mods listed, it starts fine, add sponge, it will not start.

**Comment by ProsperCraft** [comment]
https://www.dropbox.com/s/0q73wsjlim77x61/CorrelatedPotentialistics.zip?dl=1

Here is the modpack I made to test a bug that flushed this one out.  it has 4 mods(including sponge)

**Comment by Aaron1011** [comment]
@ProsperCraft: I can't seem to reproduce the issue with the mdopack and the latest version of Sponge. Can you retest with the latest SpongeForge bleeding for 1.10?

**Comment by ProsperCraft** [comment]
Still an issue with spongeforge-1.10.2-2107-6.0.0-BETA-1853

https://gist.github.com/ProsperCraft/3c545ae6c1c08f9ad6a708e1da326c61

**Comment by Zidane** [comment]
That last gist shows that you've got a mod classloading MinecraftDummyContainer too early. Not a Sponge issue.
