### ISSUE TITLE
Mekanism Fusion reactor reset

### ISSUE THREAD

**Issue by Vauxite** [SpongePowered/SpongeForge#997]
**Hello**

**Problem**
The mekanism fusion reactor resets after each server restart. Both the reaction inside it and the fuel-input blocks.

**How to reproduce**
1. Build a reactor.
2. Start fusion
3. Restart server
4. Fuel pipes disconnected and reaction has stopped

**Versions**
-     Minecraft: 1.10.2
-     SpongeAPI: 6.0.0-SNAPSHOT-cebc736
-     SpongeForge: 1.10.2-2107-6.0.0-BETA-1850
-     Minecraft Forge: 12.18.2.2107

**Comment by bloodmc** [comment]
@Vauxite Provide a test world with only mekanism so I can debug it on my end.

**Comment by Vauxite** [comment]
Sorry, couldn't reproduce with only mekanism.
