### ISSUE TITLE
Upon login, can't move. 1.10.2 Sponge 1841

### ISSUE THREAD

**Issue by chasem-dev** [SpongePowered/SpongeForge#998]
So whenever I log in, and other users login. We are instantly glitching, and the screen flickers constantly. It looks as if it's teleporting us in between two different locations almost. This has been going on for a while for me up from 1.8.9 builds even. This might be relevant to #995 ?

**Comment by Darktilldawn** [comment]
I can confirm I have the same issues on my server. 1.10.2, pixelmon 5.0.0 beta10, latest sponge and forge.

**Comment by bloodmc** [comment]
@Xwaffle1 @Darktilldawn Have you tested SF 1853+ ?

**Comment by ProsperCraft** [comment]
Is this only happening with Pixelmon?

**Comment by bloodmc** [comment]
Closing as this does NOT happen with latest builds.
