### ISSUE TITLE
Unable to interact with certern items (using Hermitpack)

### ISSUE THREAD

**Issue by Whazaaaaa** [SpongePowered/SpongeForge#999]
I'm running a FTB Hermitpack 1.2.1 and I'm having a problem with not being able to interact with a few items.
One of the items I have this problem with is the IC2 Electric Jetpack and also weapons from the WeaponCaseLoot mod. When I click the item to move it elsewhere (different inventory/crafting bench, etc) it de-selects the item. So I am unable to move this item from the place it is at in my inventory. (What I can still do is drop the item with pressing q while hovering over it)

How to replicate this error:
Its quite simple. Download the 1.2.1 server files from the FTB launcher. Add the spongeforge jar (in my case build 1844 and 1851). Run the server spawn the "Electric Jetpack" or one of the WeaponCaseLoot weapons in your inventory and try to move these items around. There are 2 versions of the electric jetpack in the NEI one has full power the other 0 power. This issue ocurs when the jetpack is NOT at full power.
At this moment no other plugins need to be installed.

Note: Before I was using 1.0.1 and this problem was not occuring It started to happen when we upgraded to 1.2.1 of the hermitpack server

If there is any information that I have not provided but is till needed I'd love to provide this.

I hope this issue can get fixed. Thank you

**Comment by Aaron1011** [comment]
@Whazaaaaa: Can you see if this happens with just IC2/WeaponCaseLoot and Sponge?

**Comment by ProsperCraft** [comment]
I was not able to replicate with Hermitpack 1.1.0.

I did have a user submit this though!
https://youtu.be/ogNfKkgOwBg

versions - 
    SpongeAPI: 6.0.0-SNAPSHOT-f247c80 
    SpongeForge: 1.10.2-2107-6.0.0-BETA-1853  
    Minecraft Forge: 12.18.2.2114

**Comment by Whazaaaaa** [comment]
@Aaron1011 I've created my own server with only IC2 WeaponCaseLoot and Sponge and everything works as it should. Also the video that ProsperCraft posted, thats the same that happens when I try to move the IC2 jetpack or weaponcaseloot items.

**Comment by Vauxite** [comment]
This is still a problem running:
SpongeForge
    Minecraft: 1.10.2
    SpongeAPI: 6.0.0-SNAPSHOT-bd88c91
    SpongeForge: 1.10.2-2107-6.0.0-BETA-1870
    Minecraft Forge: 12.18.2.2107

**Comment by phit** [comment]
still an issue with
spongeforge-1.10.2-2107-6.0.0-BETA-1871.jar
using the FTB Infinity Lite pack

**Comment by phit** [comment]
this should be fixed with 1921+

**Comment by bloodmc** [comment]
This has been fixed in latest SF builds.
